### ISSUE TITLE
Debian: Make failed (last stable version)

### ISSUE THREAD

**Issue by kolobaev** [yandex/ClickHouse#1000]
[ 62%] Building CXX object dbms/CMakeFiles/dbms.dir/src/Common/Collator.cpp.o
/opt/ClickHouse-1.1.54245-stable/dbms/src/Common/Collator.cpp:12:36: error: unknown option after ‘#pragma GCC diagnostic’ kind [-Werror=pragmas]
     #pragma GCC diagnostic ignored "-Wunused-private-field"
                                    ^~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
dbms/CMakeFiles/dbms.dir/build.make:5846: recipe for target 'dbms/CMakeFiles/dbms.dir/src/Common/Collator.cpp.o' failed
make[2]: *** [dbms/CMakeFiles/dbms.dir/src/Common/Collator.cpp.o] Error 1
CMakeFiles/Makefile2:4040: recipe for target 'dbms/CMakeFiles/dbms.dir/all' failed
make[1]: *** [dbms/CMakeFiles/dbms.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by YiuRULE** [comment]
Did you follow the [building instruction](https://clickhouse.yandex/docs/en/development/build.html) ? especially the `Use GCC 6 for builds` ?

I know I also had this kind of problems with building Clickhouse for my PRs, after changing the env, it works for me.

When you use `cmake`, does they display that the `GNU 6.3.0` will be use for building the project ?
