### ISSUE TITLE
Debian initscript causes hang/defunct when called from another package during dpkg package install

### ISSUE THREAD

**Issue by sigsergv** [yandex/ClickHouse#1010]
When another package tries to start clickhouse-server from postinst script the dpkg process tree hangs with some zombie children.

I've created a simple test package that reproduces bug, it contains init script that executes `service clickhouse-server start` and postinst script that calls init script.

Requirements: ubuntu 14.04, clickhouse-server-base, clickhouse-server-common

Download package source [ch-defunct-test.tar.gz](https://github.com/yandex/ClickHouse/files/1164454/ch-defunct-test.tar.gz) and build it:

~~~~
$ tar xf ch-defunct-test.tar.gz
$ dpkg -b ch-defunct-test .
dpkg-deb: building package 'ch-defunct-test' in './ch-defunct-test_1.0-1_amd64.deb'.
~~~~

Install clickhouse-server-base, configure it properly and STOP service clickhouse-server.

Install package ch-defunct-test_1.0-1_amd64.deb.

Expected result: it should complete without errors

Actual result: install process hangs because of some defunct child in dpkg process tree

**Comment by sigsergv** [comment]
This is how it looks in ps:

~~~~~
 3759 pts/10   Ss  \_ /bin/zsh
 3773 pts/10   S   |   \_ sudo -i 
 3774 pts/10   S   |       \_ -bash
12861 pts/10   S+  |           \_ dpkg -i ch-defunct-test_1.0-1_amd64.deb
12871 pts/10   S+  |               \_ /usr/bin/perl -w /usr/share/debconf/frontend /var/lib/dpkg/info/ch-defunct-test.postinst configure 1.0-1
12879 pts/10   Z+  |                   \_ [ch-defunct-test] <defunct>
~~~~~

**Comment by ztlpn** [comment]
Are you sure that the problem lies in ClickHouse init script and not in your scripts? I tried substituting clickhouse-server for nginx (off the top of my mind) and got the same problem...

Also, IMO it is bad practice to restart anything in postinst scripts - any problem like this and the packaging system is locked.

**Comment by sigsergv** [comment]
Yes, I think I've found cause of the problem: exec in bash invocation when demon starts, not closed file descriptors and use of debconf. I've added db_stop at the end of our postinst and that fixed the problem. At least it doesn't hang at the end.
