### ISSUE TITLE
Query with Chinese

### ISSUE THREAD

**Issue by jackpgao** [yandex/ClickHouse#1016]
- Does ClickHouse support query with Chinese?
  - Like this:

```sql
select * from xxx where city = '北京'
```

- In my test, it seems not.

**Comment by alexey-milovidov** [comment]
Basically, ClickHouse could handle Chinese:

```
:) CREATE TABLE test.chinese (d Date, s String) ENGINE = MergeTree(d, s, 8192)

CREATE TABLE test.chinese
(
    d Date, 
    s String
) ENGINE = MergeTree(d, s, 8192)

Ok.

0 rows in set. Elapsed: 0.073 sec. 

:) INSERT INTO test.chinese VALUES ('2000-01-01', '如何看待yandex开源clickhouse这个列式文档数据库?'), ('2000-01-01', '这个列式存储数据库的跑分要超过很多流行的商业MPP数据库软件')

INSERT INTO test.chinese VALUES

Ok.

2 rows in set. Elapsed: 0.002 sec. 

:) SELECT * FROM test.chinese WHERE s LIKE '%开源%'

SELECT *
FROM test.chinese 
WHERE s LIKE '%开源%'

┌──────────d─┬─s────────────────────────────────┐
│ 2000-01-01 │ 如何看待yandex开源clickhouse这个列式文档数据库? │
└────────────┴──────────────────────────────────┘

1 rows in set. Elapsed: 0.002 sec.
```

There could be few issues:

1. String comparison and search are done regardless to unicode composition/normalization. If you write the same character in different combinations of code points, ClickHouse cannot find it. (I am doubt, does it related to Chinese)?

2. If you want some specific string ordering of Chinese characters when doing ORDER BY, you could specify collation. Example: `ORDER BY s COLLATE 'zh'`.

3. Visible widths of characters are calculated wrong in a terminal and pretty tables are displayed misaligned.

BTW, what is your test?

**Comment by jackpgao** [comment]
@alexey-milovidov  Actually, I can never input Chinese character with clickhouse-client in terminal. 

All the character becomes blank.

**Comment by alexey-milovidov** [comment]
It depends on what line editing library you use during build.
ClickHouse support `readline`, `libedit` and build with no editing library.
`readline` should have no issues with Chinese.

`readline` is preferred, if it is available in your system. 
To be sure, do `sudo apt-get install libreadline-dev` before running cmake, as mentioned in documentation: https://github.com/yandex/ClickHouse/blob/master/docs/en/development/build.rst#install-required-libraries-from-packages

In pre-build packages, it should work fine.

Also it depends on your terminal application. If you could type Chinese characters in terminal, then it should also work in ClickHouse.

What system and terminal do you use and what is the way you installed ClickHouse?

**Comment by jackpgao** [comment]
@alexey-milovidov  Sorry for the late.


I use iTerm2 on MacBookPro, when I put a Chinese characters into to the query, it turns into blank:

```sql
:) select distinct city, city_name from XXXX where date=today() limit 10;

SELECT DISTINCT
    city,
    city_name
FROM XXXX
WHERE date = today()
LIMIT 10

┌─city─────┬─city_name─┐
│ CHXX0490 │ 梧州        │
└──────────┴───────────┘
┌─city─────┬─city_name─┐
│ CHXX0442 │ 阜阳        │
└──────────┴───────────┘
┌─city─────┬─city_name─┐
│          │ None      │
│ CHXX0004 │ 鞍山        │
│ WMXX2971 │ 海淀        │
│ CHXX0165 │ 郑州        │
└──────────┴───────────┘
┌─city─────┬─city_name─┐
│ WMXX1031 │ 平顶山       │
└──────────┴───────────┘
┌─city─────┬─city_name─┐
│ CHXX0449 │ 芜湖        │
│ CHXX0016 │ 成都        │
│ CHXX0141 │ 西安        │
└──────────┴───────────┘

10 rows in set. Elapsed: 0.204 sec. Processed 4.57 million rows, 146.38 MB (22.40 million rows/s., 717.18 MB/s.)

:) select distinct city, city_name from XXXX where date=today() and city_name=''   limit 10;

SELECT DISTINCT
    city,
    city_name
FROM XXXX
WHERE (date = today()) AND (city_name = '')
LIMIT 10

Ok.

0 rows in set. Elapsed: 0.377 sec. Processed 320.54 million rows, 4.73 GB (850.15 million rows/s., 12.55 GB/s.)

```



And also, I use Python module 'infi.clickhouse_orm.models' to run a query, the Chinese characters also turns to blank.

**Comment by alexey-milovidov** [comment]
This could be an issue of Mac OS builds of client. 
What happens if you use `clickhouse-client` on Ubuntu (either on server through ssh or using Docker)?

**Comment by jackpgao** [comment]
Actually I use a docker image on Mac.

It based on a Ubuntu image. 



I have another Question.

Superset which created by Airbnb, is a very powerful visualization tool.
I can't in put query with Chinese character. The errors are as below:

```python
{"status": "failed", "query_id": 1356, "error_essage": "Code: 73, e.displayText() = DB::Exception: Unknown format TabSeparatedWithNamesAndT, e.what() = DB::Exception\n"}
```

**Comment by alexey-milovidov** [comment]
In error message we see, that query was cut: it should end with `FORMAT TabSeparatedWithNamesAndTypes` but actually we have `FORMAT TabSeparatedWithNamesAndT`. It is definitely related to multibyte characters.

Looks like an issue either with Superset or with ClickHouse JDBC driver.
I will ask developer of JDBC driver to check.

**Comment by jackpgao** [comment]
superset use sqlalchemy_clickhouse:  https://github.com/cloudflare/sqlalchemy-clickhouse

**Comment by serebrserg** [comment]
This query works through JDBC driver correctly
```sql
select '北京' as n where '北京' = '北京'
```
Anyway that doesn't relate to the issue.

**Comment by jackpgao** [comment]
I sloved the problem.

The reason is docker.

As I do not have a Ubuntu OS, I run clickhouse-client in docker. 

The Docker Lang problem is the root.
