### ISSUE TITLE
Incorrect example https://clickhouse.yandex/reference_en.html#timeSlots(StartTime, Duration)

### ISSUE THREAD

**Issue by shalugin** [yandex/ClickHouse#102]
> timeSlots(toDateTime('2012-01-01 12:20:00'), 600)

This select
`SELECT timeSlots(toDateTime('2012-01-01 12:20:00'), 600)`
will produce error:
> Received exception from server:
Code: 43. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Illegal type UInt16 of second argument of function timeSlots. Must be UInt32..

Correct example:
`SELECT` timeSlots(toDateTime('2012-01-01 12:20:00'), toUInt32(600))

**Comment by alexey-milovidov** [comment]
Thanks. Fixed.

**Comment by ghuname** [comment]
The problem remains in v1.1.54362

**Comment by TianyiLu** [comment]
The [Size] parameter still cannot use refer to https://clickhouse.yandex/docs/en/query_language/functions/date_time_functions/#timeslotsstarttime-duration91-size93

SELECT timeSlot(toDateTime('2018-09-10 00:00:00'), toUInt32(6000), 300)

Received exception from server (version 1.1.54370):
Code: 42. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Number of arguments for function timeSlot doesn't match: passed 3, should be 1.
