### ISSUE TITLE
Type mismatch for Enum column using Buffer table

### ISSUE THREAD

**Issue by hagen1778** [yandex/ClickHouse#1023]
ClickHouse server version 1.1.54236

We have strange issue with updating `Enum`  column. How we doing this:
* `ALTER TABLE events MODIFY COLUMN Event ...`  -  Ok.
* `DROP TABLE events_buffer` - Ok.
* `CREATE TABLE events_buffer AS events ENGINE = Buffer(... `- Ok.
* `DESC events` and `DESC events_buffer` are identical
* `INSERT INTO TABLE events_buffer ...` - Ok.

But when time comes to flush data from Buffer to original table - we are getting error:
`Type mismatch for column Enum...`

And worst thing is that we can't reproduce this behavior at any other instance or version. This table contains huge amount of data for several months and we can't just copy it somewhere.

**Comment by hagen1778** [comment]
Can anyone take a look at this? Because we stuck with scheme updates

**Comment by blinkov** [comment]
@hagen1778 is this issue still relevant?
