### ISSUE TITLE
Fail to use default docker_compose

### ISSUE THREAD

**Issue by amosbird** [yandex/ClickHouse#1025]
Hi, I just grabbed the source tree and did `docker_compose up -d`. After it's done I did `docker_compose run client`. However I end up with `Code: 210. DB::NetException: Connection refused: (localhost:9000, ::1)
`

Using browser to access `localhost:9000` is fine, suggesting this,
```
Port 9000 is for clickhouse-client program.
You must use port 8123 for HTTP.
```

So what went wrong?

**Comment by bamx23** [comment]
With the latest version of `docker-compose.yml` file you could start a server with `docker-compose up -d server` and connect a client with `docker-compose run client`. Also HTTP-API will be available on the host machine at port `8123`.

**Comment by amosbird** [comment]
thanks!
