### ISSUE TITLE
[Clickhouse-client]:  interactively ask for credentials

### ISSUE THREAD

**Issue by Farfaday** [yandex/ClickHouse#1044]
Hi,
currently clickhouse-client can be used with user and password using 
**clickhouse-client -u $USER --password $PASSWORD**.
This enable other users to read the passwords using for example htop/ps.
Password should be asked interactively, as for example the mysql client does.

**Comment by alexey-milovidov** [comment]
Reasonable.

There are the following ways for implementation:

1. Add command line option `--ask-password`. Allow to specify this option in configuration file of client to set default behaviour.

2. Ask password if password was not specified and default empty password was incorrect.

**Comment by mkocikowski** [comment]
I think 2 is cleaner. 3: read password from an environment variable?

**Comment by PhantomPhreak** [comment]
Interested in this feature too. 2 option is exactly what is needed.

Thanks in advance for this feature!

**Comment by shacuros** [comment]
Any news on this topic? Its been a while now and shouldnt be that hard to implement
