### ISSUE TITLE
Start Server with '--daemon' failed.

### ISSUE THREAD

**Issue by jackpgao** [yandex/ClickHouse#1057]
I use root to run this command:

```
clickhouse-server  --config=/data1/clickhouse/config.xml  --daemon --pid-file=/data1/clickhouse/clickhouse.pid
```

Sometimes it will failed, but no error showed.

What maybe the reason? The root user?

**Comment by KochetovNicolai** [comment]
Can you show what is in clickhouse-server.err.log and clickhouse-server.log when it happens?

**Comment by jackpgao** [comment]
Forget that. 

I change the data dir in clickhouse-server.sh and it works fine.
