### ISSUE TITLE
Arrays cannot be nullable ?

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#1062]
After I updated clickhouse to last testing version for the following query:

```sql
CREATE TABLE example_src(`ck.partition` Date,`ck.created_at` DateTime,`ck.timestamp` DateTime,`arr` Nullable(Array(String)),`customer_id` Nullable(String),`user_action_id` Nullable(Int64),`user_id` Nullable(String)) ENGINE = ReplicatedMergeTree('/var/lib/clickhouse/tables/{shard}/example_src','{replica}',`ck.partition`,`ck.timestamp`,8192);
```

I get:

```sql
Code: 43, e.displayText() = DB::Exception: Nested type Array(String) cannot be inside Nullable type, e.what() = DB::Exception
```

So this means we cannot have fields of type array that can accept null value ? This was supported before.. 

Silviu

**Comment by alexey-milovidov** [comment]
We decided, that for simplicity reasons we need to support either arrays with nullable values or nullable arrays, but not both. And arrays with nullable values seems more useful. Nullable arrays are less needed, because often empty arrays are enough.

This is still subject to change.

**Comment by silviucpp** [comment]
Hmm, and how do you solve the problem of adding later let's say in a table a row which is array and you want to select records from past where this property was not available ? I mean where new field it's NULL not empty .. 

Silviu

**Comment by silviucpp** [comment]
Hy @alexey-milovidov do you have an opinion on my previous question ?

Silviu

**Comment by alexey-milovidov** [comment]
This will be more difficult. You could add another field as a flag to indicate older data.
For example, you could have two fields `Items Array(String)` and `HasItems UInt8`.
But sometimes it is enough to not differentiate between empty array and undefined array value.

**Comment by silviucpp** [comment]
Ok then, if the decision that Nullable array are not supported is final then I don't see any option..
