### ISSUE TITLE
batch insert

### ISSUE THREAD

**Issue by fengyuncrawl** [yandex/ClickHouse#107]
When I batch insert 10 million data into stand-alone clickhouse, The time spent avg 16min,why so slowly? @alexey-milovidov

**Comment by alexey-milovidov** [comment]
How exactly (in what format, to what kind of table) do you insert your data?

By the way, when using `Values` format, there is slow path, when data contains expressions (example: `now()` for DateTime field) or requires type conversion (example: `'123'` in quotes for integer field). So, you should specify data in explicit form.

**Comment by fengyuncrawl** [comment]
create table（id Int64,name String,open_time Date）MergeTree('open_time', ('id','name'))
when I use python client insert list to DB （for example: db.insert([p1,p2,p3...])）

**Comment by alexey-milovidov** [comment]
Maybe it is an issue of Python client. Python clients are unofficial, we have not evaluated them.
By the way, there are few different Python clients.

Is problem persists, when you insert data with `clickhouse-client` from command line, as in tutorial?

**Comment by fengyuncrawl** [comment]
I think so, the Python client lib is https://github.com/Infinidat/infi.clickhouse_orm  ,so when I change to use  clickhouse-client ,its so quickly! Thank for your answer.

**Comment by alexey-milovidov** [comment]
Ok. I suggest you to create an issue in infi.clickhouse_orm repository.

**Comment by ishirav** [comment]
Hi, infi.clickhouse_orm v0.7.1 includes several performance improvements that reduce the time it takes to insert large amounts of data. @fengyuncrawl - I would appreciate it if you could try it and report back whether it's working faster than before.
