### ISSUE TITLE
Проблема с кодированием некоторых юникод символов в JSON

### ISSUE THREAD

**Issue by alaexeyshustov** [yandex/ClickHouse#1076]
Версия 1.1.54245
1. echo 'CREATE TABLE t (str String) ENGINE = Memory' | POST 'http://localhost:8123/'
2. echo -ne '"\u2028"\n' | POST 'http://localhost:8123/?query=INSERT INTO t FORMAT CSV'
3. 
 -- CSV -- 
GET 'http://localhost:8123/?query=SELECT * FROM t FORMAT CSV'
 # \u2028
-- JSON --
GET 'http://localhost:8123/?query=SELECT * FROM t FORMAT JSONCompact'
 # \u2028�

**Comment by alexey-milovidov** [comment]
Confirmed.
