### ISSUE TITLE
error when using clickhouse over nfs 

### ISSUE THREAD

**Issue by amosbird** [yandex/ClickHouse#1080]
I'm trying to use clickhouse over nfs (glusterfs), however i get this error upon starting,
```
server_1   | 2017.08.09 03:40:34.505656 [ 1 ] <Error> Application: DB::Exception: Cannot lock file /var/lib/clickhouse/status, errno: 13, strerror: Permission denied
```

nfs mount command is `mount <remote> /chdata -o fsc`

**Comment by alexey-milovidov** [comment]
As you have mentioned in chat, the filesystem doesn't look good: https://la.wentropy.com/nXPX

**Comment by amosbird** [comment]
Ok. I'll avoid using nfs.
