### ISSUE TITLE
Not found column message in block. There are only columns: 

### ISSUE THREAD

**Issue by sasik-github** [yandex/ClickHouse#1087]
```sql
SELECT count(*) as total
FROM
  (
    SELECT message, info, count() AS cnt
    FROM installation_stats
    WHERE message_type LIKE 'fail'
    GROUP BY message, info
    ORDER BY cnt DESC
    LIMIT 5 BY message
)
```
такой запрос производит ошибку
> DB::Exception: Not found column message in block. There are only columns: cnt, e.what() = DB::Exception

но если убрать count() и order by
```sql
SELECT count(*) as total
FROM
  (
    SELECT message, info
    FROM installation_stats
    WHERE message_type LIKE 'fail'
    GROUP BY message, info
    LIMIT 5 BY message
)
```
так работает, также работает если убрать только count() из селекта и добавить его в order by
```sql
SELECT count(*) as total
FROM
  (
    SELECT message, info
    FROM installation_stats
    WHERE message_type LIKE 'fail'
    GROUP BY message, info
    ORDER BY COUNT() DESC
    LIMIT 5 BY message
)
```

почему не отрабатывает первый запрос? похоже на багу

**Comment by alexey-milovidov** [comment]
Проблема не воспроизводится.
Наверное, она была давным-давно исправлена.
На всякий случай я добавил ваш тест в набор.
