### ISSUE TITLE
IN and NOT IN with arrays

### ISSUE THREAD

**Issue by tobia** [yandex/ClickHouse#109]
When the left-hand side argument of IN / NOT IN is an array, the operator checks whether ANY value in the array is present / absent from the right-hand side argument.

This is not a bad choice, but the documentation says:

> This is somewhat illogical, but it is convenient for implementing certain Yandex.Metrica functionality.
> [...] 
> This is completely illogical, so don't rely on this behavior. We recommend using higher-order functions instead. 

Instead of recommending people not to use it, I propose the following roadmap of changes, to increase the readability and usefulness of this feature:

Step 1. **Accept and ignore** (no changes needed to the query engine) an ANY keyword before IN / NOT IT and change the documentation to recommend people use it when the left argument is an array.

Example: `[1, 2, 3] ANY IN (3, 4, 5)` and `[1, 2, 3] ANY NOT IN (3, 4, 5)`

This would make it clear what the operator does, so there's no need to call it "illogical" anymore.

Step 2. Add support for an ALL keyword before IN / NOT IN that performs the check on all elements of the array.

Example: `[1, 2, 3] ALL IN (3, 4, 5)` and `[1, 2, 3] ALL NOT IN (3, 4, 5)`

This would cover most use cases and be much faster than using a higher-order function.

**Comment by alexey-milovidov** [comment]
Thank you for suggestion!

By the way, there is already a way to specify it explicitly:
`arrayExists(x -> x IN (3, 4, 5), [1, 2, 3])`
and 
`arrayAll(x -> x IN (3, 4, 5), [1, 2, 3])`

Implementation of ANY IN, ALL IN operators is possible, but I doubt, do we really need to extend syntax for this special case.
