### ISSUE TITLE
TopN by subgroup

### ISSUE THREAD

**Issue by andrea-s** [yandex/ClickHouse#111]
Hello,

perhaps I'm not seeing it, but is there a way to obtain a "top N by subgroup" result with ClickHouse? For instance: select the top 10 visited URLs (by whatever metric) and for each one the top 5 origin countries.

At the moment I am exploring some possibilities with array functions (e.g. groupArray paired with arrayEnumerate) but it feels kind of clunky and I'm not sure about performance scalability.

Any ideas?

Thanks!

**Comment by andrea-s** [comment]
Following up with an example - with this query I get what I want:

select page, arrayMap(i -> countries[i+1], range(5)) as countries, arrayMap(i -> countryImpressions[i+1], range(5)) as countryImpressions, totalImpressions from
(select page, groupArray(country) as countries, groupArray(impressions) as countryImpressions, sum(impressions) as totalImpressions from
(select page, country, uniq(requestid) as impressions from mydatabase.mytable group by page, country order by impressions desc)
group by page
order by totalImpressions desc)
limit 10

but I'm not quite sure if this is the proper way of doing it.

**Comment by alexey-milovidov** [comment]
Hello.

> Any ideas?

We had an idea to implement non-standard `LIMIT BY` clause. So, you write something like `LIMIT 5 BY Country`. It will be like extended version of DISTINCT.

Of course, it will be much more efficient and convenient than collecting all values into arrays.
If you appreciate this way to implement needed functionality, we will do it.

**Comment by andrea-s** [comment]
Hi Alexey, thanks for your answer!

I think this is a very common use case for analytics purposes, as it happens that often one would like to pivot through dimensions with vastly different cardinalities (e.g. which are the top 10 countries, and the top 10 pages for each country?). Missing this feature, that would always require clunky tricks as above or a complete enumeration of the results.

Some analytics systems are already providing this kind of limiting (e.g. Webtrekk), so in some cases people in the field are used to this kind of thinking.

It would really be appreciated if this feature were to be put on schedule (although unfortunately I am not nearly competent enough with low level programming to actually be able to contribute :-).

Best regards,
Andrea

**Comment by alikrubin** [comment]
Hi Alexey,

LIMIT N BY expr(COL) sounds great.
Do you plan to implement window functions as well? 
Some examples also "DISTRIBUTE BY" in Hadoop/Hive and "RANK OVER ... PARTITION BY" in SQL Server.

**Comment by alexey-milovidov** [comment]
> Do you plan to implement window functions as well? 

We have it in plans only for distant future (Q2 2017 or later).
