### ISSUE TITLE
MongoDB dictionaries example

### ISSUE THREAD

**Issue by umaxfun** [yandex/ClickHouse#112]
Could you please give an example of configuration to start using MongoDB as a source for dictionaries? The documentation lacks the example and description is not too descriptive 🍂

**Comment by alexey-milovidov** [comment]
For MongoDB, source is specified in following way:

```
<source>
    <mongodb>
        <host>localhost</host>
        <port>27017</port>
        <user></user>
        <password></password>
        <db>test</db>
        <collection>dictionary_source</collection>
    </mongodb>
</source>
```

And all other parameters as usual.

**Comment by umaxfun** [comment]
Thanks, Alexey! And what's the correct query to get names? My MongoDb collection `items` contains this kind of documents:
```
{
_id: ObjectId("507f1f77bcf86cd799439011"),
name: "Ohai",
DisplayName: "There!" // may be absent or not
}
```

Should it look like this? 
`select id, DictGetStringOrDefault("items", "DisplayName", id, DictGetStringOrDefault("items", "name", id, "")) from stats` 
The thing I am concerned about is `id`. It is a string in ClickHouse and ObjectId in MongoDb.

**Comment by alexey-milovidov** [comment]
I am not much familiar with MongoDB.
As I see in our tested use case, we are using some other attribute (not `_id`) for dictionary key.
I am not sure, how `_id` will be returned and used by dictionaries. Maybe using `_id` is not suitable.

**Comment by gerasim13** [comment]
Hello, i faced with same issue.
Could you please provide simple example of use of mongo with clickhouse?

**Comment by gerasim13** [comment]
ok. i think i got it. ObjectId is not supported

**Comment by kitaisreal** [comment]
MongoDB dictionaries already support `ObjectId`. Support custom `_id` both for simple dictionaries with `UInt64` primary key type, and for complex dictionaries with any type, `String` for example. Reproducible config can be found in comment https://github.com/ClickHouse/ClickHouse/issues/41990.

**Comment by kitaisreal** [comment]
MongoDB dictionaries already support ObjectId. Support custom _id both for simple dictionaries with UInt64 primary key type, and for complex dictionaries with any type, String for example. Reproducible config can be found in comment https://github.com/ClickHouse/ClickHouse/issues/41990.
