### ISSUE TITLE
Suggestion: Flexible documentation.

### ISSUE THREAD

**Issue by ramazanpolat** [yandex/ClickHouse#1127]
There are lots of undocumented things in CH.
I myself found a couple of things to add to documentation.
Whether it be additional explanation, example codes, SQLs or more, CH also needs contribution for documentation from community(IMHO).

Github Pages is great for these kind of requirements (readme.io is also fine but requires subscription).

**Comment by blinkov** [comment]
ClickHouse documentation resides near code right in this repository and anyone is welcome to contribute to it: https://github.com/yandex/ClickHouse/tree/master/docs

It's then published on official website https://clickhouse.yandex/docs/en/ and there is "pencil" icon that links back to edit on GitHub page.

There are some README.md's in docs root and docs/tools that explain how it works.
