### ISSUE TITLE
data duplication in mergeTree table

### ISSUE THREAD

**Issue by shailee-m** [yandex/ClickHouse#1131]
this is a sample table:

![screenshot from 2017-08-22 10-36-44](https://user-images.githubusercontent.com/10625985/29549422-d6fce236-8725-11e7-9d9c-dc15c7344d86.png)
`CREATE TABLE default.test ( DATE_COLUMN Date,  id Int64,  name String,  numVal Int64) ENGINE = MergeTree(DATE_COLUMN, (DATE_COLUMN, id), 8192);
insert into test (DATE_COLUMN,id,name,numVal) values ('2016-12-01',11,'lee',77);
insert into test (DATE_COLUMN,id,name,numVal) values ('2016-12-01',11,'shailee',999)`

the 2nd row is inserted successfully and now I have duplicates in the table. Am I doing something wrong?

**Comment by vavrusa** [comment]
MergeTree doesn't deduplicate data, it just sorts the rows by the primary key expression and compacts the data parts in the background. Perhaps you might want to take look at the ReplacingMergeTree or AggregatingMergeTree ?

**Comment by shailee-m** [comment]
But why should it duplicate in the first place? Does primary key mean something else in this context?
Here, the primary key is date,id which is the same for both the entries. That shouldn't happen.

**Comment by vavrusa** [comment]
It's not a primary key like you expect in OLTP systems, it's more like a sorting key as I said. You can read about how it works here https://medium.com/@f1yegor/clickhouse-primary-keys-2cf2a45d7324

**Comment by shailee-m** [comment]
Alright! ReplacingMergeTree works. but I still have to optimise it for de-duplication.
