### ISSUE TITLE
Command Line --query param is not work on Mac

### ISSUE THREAD

**Issue by flowbehappy** [yandex/ClickHouse#1132]
> $  clickhouse-client  --query="show tables"
> Code: 62. DB::Exception: Syntax error: failed at position 5 (end of query): . Expected one of: CREATE, PROCESSLIST, TABLES

It works on Linux but fails on Mac. Looks like the param parser stop receiving contents after it find white space.

**Comment by ztlpn** [comment]
That's very strange - I couldn't reproduce it. Can you tell which version of ClickHouse and macOS are you using?

**Comment by flowbehappy** [comment]
Commit: fc409f61e53646d2e88a57287496b67de546bca2 on master.
macOS: 10.12.5.
Using the default Terminal.

**Comment by flowbehappy** [comment]
It turns out is my problem on `clickhouse-client` alias script. Sorry about that.

**Comment by filimonov** [comment]
Relates #235
