### ISSUE TITLE
Binary aggregation

### ISSUE THREAD

**Issue by AlexMAS** [yandex/ClickHouse#1134]
Is there some way to aggregate an integer column using a binary function (e.g. OR, AND, XOR)?

**Comment by alexey-milovidov** [comment]
If you have 0 or 1 values, you could get expected behaviour with:
`max(x)` for or
`min(x)` for and
`sum(x) % 2` for xor.

**Comment by alexey-milovidov** [comment]
If you want bitwise aggregate functions - currently there is no such functions, but this is very easy to implement.

**Comment by AlexMAS** [comment]
Thanks for your answer. Yes, I have some `flags` column which contains integer values (powers of 2) and I need a bitwise OR function to aggregate these values. Currently I use mathematical expression. But it will be cool if you implement bitwise aggregate functions in one of further releases. So this issue is an improvement request.

**Comment by alexey-milovidov** [comment]
https://github.com/yandex/ClickHouse/commit/1531268281b4b63640dca4ba24274ef4f918d570
