### ISSUE TITLE
Segfault while calling uniqUpTo with incorrect parameters

### ISSUE THREAD

**Issue by imdrafter** [yandex/ClickHouse#1142]
Calling the function in the following (wrong) way causes segfault. 
SELECT arrayReduce('uniqUpTo(5)', [1, 2, 2, 1, 3], materialize(['hello', 'world', '', ''])) 
Though the crash is just a consequence of incorrect arguments provided, it might be better to validate input.

2017.08.24 10:31:29.731053 [ 51 ] <Error> BaseDaemon: (from thread 50) Received signal Segmentation fault (11).
2017.08.24 10:31:29.731059 [ 51 ] <Error> BaseDaemon: Address: 0x141b42001
2017.08.24 10:31:29.745140 [ 51 ] <Error> BaseDaemon: 1. clickhouse-server(DB::AggregateFunctionUniqUpToVariadic<false>::add(char*, DB::IColumn const**, unsigned long, DB::Arena*) const+0x7b) [0x1f7688b]
2017.08.24 10:31:29.745152 [ 51 ] <Error> BaseDaemon: 2. clickhouse-server(DB::FunctionArrayReduce::executeImpl(DB::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long)+0x3b9) [0x164a479]
2017.08.24 10:31:29.745172 [ 51 ] <Error> BaseDaemon: 3. clickhouse-server(DB::IFunction::execute(DB::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long)+0x9f) [0x2c637bf]
2017.08.24 10:31:29.745179 [ 51 ] <Error> BaseDaemon: 4. clickhouse-server(DB::ExpressionAction::execute(DB::Block&) const+0x300) [0x2979fc0]
2017.08.24 10:31:29.745185 [ 51 ] <Error> BaseDaemon: 5. clickhouse-server(DB::ExpressionActions::execute(DB::Block&) const+0x32) [0x297c202]
2017.08.24 10:31:29.745190 [ 51 ] <Error> BaseDaemon: 6. clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x46) [0x2cd2226]
2017.08.24 10:31:29.745197 [ 51 ] <Error> BaseDaemon: 7. clickhouse-server(DB::IProfilingBlockInputStream::read()+0x23b) [0x237f7bb]
2017.08.24 10:31:29.745202 [ 51 ] <Error> BaseDaemon: 8. clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x2d) [0x2cd220d]
2017.08.24 10:31:29.745207 [ 51 ] <Error> BaseDaemon: 9. clickhouse-server(DB::IProfilingBlockInputStream::read()+0x23b) [0x237f7bb]
2017.08.24 10:31:29.745214 [ 51 ] <Error> BaseDaemon: 10. clickhouse-server(DB::AsynchronousBlockInputStream::calculate(MemoryTracker*)+0x8b) [0x10c0b8b]
2017.08.24 10:31:29.745220 [ 51 ] <Error> BaseDaemon: 11. clickhouse-server(ThreadPool::worker()+0x181) [0x2f0a991]
2017.08.24 10:31:29.745225 [ 51 ] <Error> BaseDaemon: 12. clickhouse-server() [0x3755fcf]
2017.08.24 10:31:29.745230 [ 51 ] <Error> BaseDaemon: 13. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ca) [0x7fcc8e7536ca]

**Comment by ztlpn** [comment]
Thanks! Confirmed.

**Comment by ztlpn** [comment]
fixed in master
