### ISSUE TITLE
A small question: how can I know my function is auto vectorized by gcc?

### ISSUE THREAD

**Issue by innerr** [yandex/ClickHouse#1143]
Such as this comment:
https://github.com/yandex/ClickHouse/blob/b4c610a8e72dc41d2b5d2cc1626be1526e23513f/dbms/src/Functions/FunctionsArithmetic.h#L334

I want to write some functions for some particular calculating.
And I'm happy to know that it's successfully vectorized.

Thank you.

**Comment by ztlpn** [comment]
Here is one way to do it:

First, find the translation unit where the code of the function in question ends up and the corresponding object file. In our case it is `build/dbms/src/Functions/CMakeFiles/clickhouse_functions.dir/registerFunctionLeast.cpp.o` (this is a bit unusual – recently the giant `FunctionsArithmetic.cpp` translation unit was split up into several autogenerated files to speed up the compilation).

Next, look at the disassembly with the command: 
```
objdump -d -S -C build/dbms/src/Functions/CMakeFiles/clickhouse_functions.dir/registerFunctionLeast.cpp.o | less
```
The command will disassemble object code, interleave it with the source code and demangle the symbols. You will notice that the disassembly consists of lots and lots of template specializations for different types (BTW, this is one of the secrets behind ClickHouse speed).

Now you need to dig through the maze of templated functions calling each other and find the function that does the real work. In our case it is `bool FunctionBinaryArithmetic<LeastImpl, NameLeast>::executeRightTypeImpl()`. Let us look at the particular specialization: `bool DB::FunctionBinaryArithmetic<DB::LeastImpl, DB::NameLeast>::executeRightTypeImpl<unsigned long, unsigned long, unsigned long>(DB::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, DB::ColumnVector<unsigned long> const*)`. It is used when you apply the function `least()` to two UInt64 columns. After scrolling through a lot of junk you will arrive at the inner loop of this function which looks like this:
```
            c[i] = Op::template apply<ResultType>(a[i], b[i]);
 142:   f3 0f 6f 0c 03          movdqu (%rbx,%rax,1),%xmm1
 147:   49 83 c1 01             add    $0x1,%r9
 14b:   66 41 0f 6f 54 05 00    movdqa 0x0(%r13,%rax,1),%xmm2
 152:   66 0f 6f c1             movdqa %xmm1,%xmm0
 156:   66 0f 6f e2             movdqa %xmm2,%xmm4
 15a:   66 0f fb c3             psubq  %xmm3,%xmm0
 15e:   66 0f fb e3             psubq  %xmm3,%xmm4
 162:   66 0f 38 37 c4          pcmpgtq %xmm4,%xmm0
 167:   66 0f 38 10 ca          pblendvb %xmm0,%xmm2,%xmm1
 16c:   0f 11 0c 06             movups %xmm1,(%rsi,%rax,1)
```
Note the use of SSE instructions and registers, in particular [pcmpgtq](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=pcmpgtq&expand=865) and [pblendvb](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=pblendvb&expand=414). These are the ones that do the real work of choosing the least of two column elements.

**Comment by innerr** [comment]
Thanks a lot!
