### ISSUE TITLE
grouping data in intervals

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#1154]
Hello,

It's a bit confusing on how clickhouse can be used to group data in intervals:

For example having the following table:

```sql
CREATE TABLE intervals (date DateTime, age UInt8) ENGINE = Memory
```

And the following values:

```sql
INSERT INTO intervals (date, age) VALUES ('2017-08-01 01:00:00', 18), ('2017-08-02 02:00:00', 18),
('2017-08-03 03:00:00', 18), ('2017-08-04 01:00:00', 18), ('2017-08-05 01:00:00', 18), ('2017-08-06 01:00:00', 18),
('2017-08-07 01:00:00', 18), ('2017-08-08 01:00:00', 18), ('2017-08-09 01:00:00', 18), ('2017-08-10 01:00:00', 18);
```

I want to count the records grouping by intervals of 2 days between `2017-08-01 00:00:00` and `2017-08-10 00:00:00`

So I'm expecting to have the data grouped in the following intervals:

group1 : 2017-08-01 00:00:00 - 2017-08-03 00:00:00 (2 events)
group2 : 2017-08-03 00:00:00 - 2017-08-05 00:00:00 (2 events)
group3 : 2017-08-05 00:00:00 - 2017-08-07 00:00:00 (2 events)
group4 : 2017-08-07 00:00:00 - 2017-08-09 00:00:00 (2 events)
group5 : 2017-08-09 00:00:00 - 2017-08-10 00:00:00 (1 event)

How this is possible using the date times functions provided by clickhouse ?

I tried the following but is not working as expected:

```sql
select intDiv(toRelativeDayNum(date), 2)*2 as dt, count(*), groupUniqArray(date) from intervals
where date BETWEEN '2017-08-01 00:00:00' AND '2017-08-10 00:00:00'
group by dt order by dt asc ;
```

Thanks,
Silviu

**Comment by ztlpn** [comment]
As the reference date of `toRelativeDayNum()` is unspecified, if you want to align your intervals to a particular date, you need to do it manually, e.g. by grouping by `intDiv(toRelativeDayNum(date) - toRelativeDayNum(toDateTime('2017-08-01 00:00:00')), 2)`

**Comment by silviucpp** [comment]
Thanks,
This was the problem

**Comment by silviucpp** [comment]
@ztlpn  one more question here : there is any way I can optimize the toRelativeDayNum(toDateTime('2017-08-01 00:00:00')) to be computed only once and not for every single row that's processed ?

**Comment by alexey-milovidov** [comment]
`toRelativeDayNum(toDateTime('2017-08-01 00:00:00'))` is a constant expression.
All constant expressions are computed only once.
