### ISSUE TITLE
using rand() in reshard does not work

### ISSUE THREAD

**Issue by rpfennin** [yandex/ClickHouse#1169]
According to the documentation (https://clickhouse.yandex/docs/en/table_engines/resharding.html), it should be possible to use rand() to randomly distribute data when resharding a partition.  However when executing the following query:

```
ALTER TABLE analytics.messagelog
RESHARD PARTITION 201708 TO 
    '/clickhouse/tables/01/analytics.messagelog_local' WEIGHT 1, 
    '/clickhouse/tables/02/analytics.messagelog_local' WEIGHT 1, 
    '/clickhouse/tables/03/analytics.messagelog_local' WEIGHT 1, 
    '/clickhouse/tables/04/analytics.messagelog_local' WEIGHT 1
USING rand()
```

I get the following error:

```
Received exception from server:
Code: 16. DB::Exception: Received from localhost:9000, ::1. DB::Exception: There is no column rand() in table..
```

**Comment by komex** [comment]
Any other fuctions for `RESHARD` does not works too.

**Comment by filimonov** [comment]
https://github.com/yandex/ClickHouse/issues/198#issuecomment-330916156

**Comment by silviucpp** [comment]
The resharding code was completely removed from the code while ago

**Comment by rpfennin** [comment]
Guys I think this is a key feature for mass adoption.  Without this, and I'm in the middle of going through this process, it is a pain in the butt when you grow a cluster and want to evenly distribute historical data.

**Comment by filimonov** [comment]
Yep. AFAIR on September's presentation @alexey-milovidov said that they plan to work on fixing that in some close perspective (as they need to do some resharding in their datacenter).

For now - they propose just to increase weigth of new server(s) for inserts.

**Comment by filimonov** [comment]
Clickhouse version 1.1.54356 (2018-03-06) introduce the `clickhouse-copier` tool for copying between clusters and resharding data.

Please, check documentation: https://clickhouse.yandex/docs/en/utils/clickhouse-copier/
