### ISSUE TITLE
Temporary table management

### ISSUE THREAD

**Issue by hatarist** [yandex/ClickHouse#117]
Hey, Happy Birthday to your company and thanks for making an awesome DBMS!

It'd be great to have better control over the native `TEMPORARY TABLE`s.
For instance, if you create one using `CREATE TEMPORARY TABLE temp_table (id UInt8);`,
you won't be able to
1) execute `SHOW CREATE TABLE temp_table;`
`#107: Cannot open file /.../metadata/default/temp_table.sql, errno: 2, strerror: No such file or directory.`

Judging by the exception, it may look like it supports just the permanently-stored ones, but you certainly can do `SHOW CREATE TABLE` over the regular tables with the `Memory` engine.
Also I've thought that the table was already deleted, but it was the same session and `SELECT * FROM temp_table;` works OK.

2) Same with `SHOW TABLES;` - the temporary tables aren't there.

3) You can't run `DROP TABLE` over a temporary table. You can over a `Memory` one though.
Of course, I'm free to end the session to make it disappear, but nevertheless...

I understand that it's not a big deal, and I guess I can send a pull request later that reflects these issues in the documentation. Just wanted to let you know.

**Comment by alexey-milovidov** [comment]
> Hey, Happy Birthday to your company

Thanks for greetings!

> I understand that it's not a big deal, and I guess I can send a pull request later that reflects these issues in the documentation. Just wanted to let you know.

Better to fix these issues (It is not very hard).
Approved.

**Comment by alexey-milovidov** [comment]
@zhang2014 has fixed everything except `SHOW CREATE TABLE`.

**Comment by zhang2014** [comment]
Oh, sorry, I forgot about it.I will  support it later. @alexey-milovidov
