### ISSUE TITLE
Fedora 26 build failed

### ISSUE THREAD

**Issue by sunsingerus** [yandex/ClickHouse#1177]
Hello guys!

Got the following error on Fedora 26/gcc 7.1.1 for ClickHouse-1.1.54284-testing:
```
[ 61%] Building CXX object dbms/CMakeFiles/dbms.dir/src/Dictionaries/DictionarySourceFactory.cpp.o

...crop...

In file included from 
dbms/src/Dictionaries/DictionarySourceFactory.cpp:6:0:
dbms/src/Dictionaries/MySQLDictionarySource.h:7:10: 
fatal error: mysqlxx/PoolWithFailover.h: No such file or directory

 #include <mysqlxx/PoolWithFailover.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
File in question `PoolWithFailover.h` is in `libs/libmysqlxx/include/mysqlxx/PoolWithFailover.h`

Can you please suggest something?

**Comment by proller** [comment]
can you show cmake console output ?

**Comment by sunsingerus** [comment]
Figured out what was that - have MariaDB client lib, and they have no `libmysqlclient.a` file included into `MariaDB-devel` package any more. Interesting that there is this [commit](https://github.com/yandex/ClickHouse/pull/1181/commits/41a8c1412189594d5c6e2d8b0191ee27a3a79d85) right from today. Think we can close this issue
