### ISSUE TITLE
Server start hang with 'FUTEX_WAIT_PRIVATE'

### ISSUE THREAD

**Issue by jackpgao** [yandex/ClickHouse#1191]
After starting the server', it hangs.

The strace msg as belows:

```
# strace -p 5790
Process 5790 attached
futex(0x7fff02a894d4, FUTEX_WAIT_PRIVATE, 1, NULL
```

**Comment by jackpgao** [comment]
Found the problem.

I have 3 node: A, B, C.

And I have a basic table named 'table' with MergeTree engine and a distributed table named 'table_all' with distributed engine .


In the test environment, I build a test table named 'xx_test' and 'xx_test_all' on only one node, such as A, and I miss the different engine I should use, so the tables all use the 'distributed' table.

When I insert into table xx_test, the server A hang, as I just posted.


I think this is not a bug, but it should be optimized.

**Comment by bookeezhou** [comment]
in clickhouse version 19.15.2.2，we encount the same problem . 
# strace -p 5790
Process 5790 attached
futex(0x7fff02a894d4, FUTEX_WAIT_PRIVATE, 1, NULL

how to solve the problem.

**Comment by alexey-milovidov** [comment]
@bookeezhou You are using `strace` in a wrong way.
The rule of thumb: always add `-f` flag,
so it should be: `strace -f -p $(pidof clickhouse)`

**Comment by bookeezhou** [comment]
thank you share the command .i will try it.







--

Your Sincerely,
     Bookee




At 2020-12-19 02:14:42, "alexey-milovidov" <notifications@github.com> wrote:

@bookeezhou You are using strace in a wrong way.
The rule of thumb: always add -f flag,
so it should be: strace -f -p $(pidof clickhouse)
