### ISSUE TITLE
slow query due to not fully utilizing all threads and all cores?

### ISSUE THREAD

**Issue by fleapapa** [yandex/ClickHouse#1197]
Hi, 

First thanks for performant database! It really sets a very high bar on databases for big data.

Recently i am comparing performance between Clickhouse and Spark SQL. In most of my test cases, CH surpasses Spark on speed by a scale. However, in few cases, it is slower by a scale, too :)

For example, using New York Tax Trip data with primary index on (pickup_datetime, dropoff_datetime) columns, if my query is "pickup_datetime > '2013-01-01 00:00:00' and pickup_datetime < '2013-01-02 00:00:00'", CH is x20 faster, but if my query condition is changed to "dropoff_datetime > '2013-01-01 00:00:00' and dropoff_datetime < '2013-01-02 00:00:00'", CH is x10 slower. (it took 8 minutes)

During execution of the slower query, i noticed that all cpu cores were under-utilized (eg. <10%). In contrast, with Spark SQL and parquets and with the same data set and query on the same host, all cpu cores are nearly 100% occupied. (it took 1 minute)

How can i improve performance of the query, eg., without creating another index on  (dropoff_datetime, pickup_datetime)?

Thanks again for making such an excellent software available to the world!!

**Comment by KochetovNicolai** [comment]
Hi,

You can increase performance by adding both index columns in condition. For example, if you know that `pickup_datetime <  dropoff_datetime`,  than instead of query `select ... from table where dropoff_datetime > '2013-01-01 00:00:00'` you can use `select ... from table where dropoff_datetime > '2013-01-01 00:00:00' and pickup_datetime > '2013-01-01 00:00:00'`.

**Comment by fleapapa** [comment]
Hi, thanks a lot for the quick response. 

It's true that more constrained condition can improve the "indexing" performance, but actually my actually point is the poor utilization of massive parallel processing (compare with Spark SQL) in cases of a useless index, which i guess can be improved by forking more threads to fill pipeline of CH query executor.

**Comment by KochetovNicolai** [comment]
If CPU cores were under-utilized, there should be bottle neck in something else. It makes sense to measure performance of i/o operations, such as disk and network loading. You can use `iotop` to measure disk and `iftop` to measure network performance during query execution.

You can try to increase the number of threads using setting `max_threads` (in users.xml or with `set max_threads = ...` query). But if, for example, disk was used on 100%, it won't help.

Also `perf top` can show in which functions process spend the most of the time.

**Comment by fleapapa** [comment]
The comparison is conducted on the same physical host same h/w and s/w environment, so i/o or any objective environment seems not the main factor of the performance difference. (my point here is, on my host CH should be able to read as fast as Spark does)

I raise max_threads to 4 on my dual core cpu. No improvement.

When Spark runs, cpu usage is between 60% - 80%. The query took 1 min.
When CH runs, cpu usage is ~5%. The same query took 8 mins.

It's intriguing...

**Comment by daledude** [comment]
I ran into same, or similar, issue. Whether using a single large table (3tb) or a merge of many tables my queries would start off using all CPU and most IO then dwindle down to a single thread and little IO. It's not an issue with the system as increasing max_streams_to_max_threads_ratio uses most, if not all, resources until the end of the query at the expense of over utilizing all CPU and IO initially. My queries are only using indexed fields: select indexed_field1, indexed_field2 from ... where indexed_field1 = ??? and indexed_field2 = ???.

https://groups.google.com/forum/#!topic/clickhouse/ErV2cwwyoZg

**Comment by KochetovNicolai** [comment]
@fleapapa ,

Could you do the following:

1. run `select count() from system.parts where table = 'your_table_name'`
2. run `iotop` and look at IO column to see if clickhouse threads spent mots of the time on IO operations (I expect it could be close to 100%)
3. increase `max_threads` more (8, 12, 16) and look at changing in `top` and `iotop` numbers

**Comment by fleapapa** [comment]
1.  the result is 10
2.  io was close to 100% on both threads (by default max_threads)
3. when max_threads = 16,  io is nearly 100% on 8 threads but very slow on the other 8 thread.
cpu is only ~3% on one thread and nearly 0% on all the other 15 thread.

iotop:
11857 be/4 root        2.16 M/s    0.00 B/s  0.00 % 99.99 % clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon [ParalInputsProc]
11860 be/4 root        2.16 M/s    0.00 B/s  0.00 % 99.99 % clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon [ParalInputsProc]
11858 be/4 root     1962.52 K/s    0.00 B/s  0.00 % 97.82 % clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon [ParalInputsProc]
11861 be/4 root     1962.52 K/s    0.00 B/s  0.00 % 96.63 % clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon [ParalInputsProc]
11862 be/4 root     1912.69 K/s    0.00 B/s  0.00 % 95.94 % clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon [ParalInputsProc]
11859 be/4 root     1552.39 K/s    0.00 B/s  0.00 % 95.92 % clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon [ParalInputsProc]
11850 be/4 root     1962.52 K/s    0.00 B/s  0.00 % 94.44 % clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon [ParalInputsProc]
11863 be/4 root     1962.52 K/s    0.00 B/s  0.00 % 93.17 % clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon [ParalInputsProc]

htop:
11051 root       20   0 58860 11128  2132 S  6.1  1.1  0:32.27 /usr/bin/python /usr/sbin/iotop                                                                                                          
27992 root       20   0  650M  114M     0 S  4.8 11.6  3:08.09 clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon
 3337 ppan       20   0 26640  1920   708 S  0.7  0.2  0:50.05 htop
11862 root       20   0  650M  114M     0 D  0.7 11.6  0:00.51 clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
11850 root       20   0  650M  114M     0 D  0.7 11.6  0:00.51 clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
11861 root               650M  114M     0 D  0.7 11.6  0:00.51 clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
11857 root       20   0  650M  114M     0 D  0.7 11.6  0:00.38 clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
11860 root       20   0  650M  114M     0 D  0.7 11.6  0:00.49 clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
11859 root       20   0  650M  114M     0 D  0.0 11.6  0:00.52 clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon

**Comment by KochetovNicolai** [comment]
1. means that you have only 10 parts in table, so more than 10 threads won't help. Is it still works slower with 10 threads than spark?

Could you also show table structure (`show create table your_table_name`) and full query text?

**Comment by KochetovNicolai** [comment]
@daledude,
As I can understand, your issue is not the same. You have degradation in performance because during reading from table with `Engine = Merge(...)` threads are doing different amount of work.

You can also try to exclude big table from merge and rewrite query with `UNION ALL`: https://clickhouse.yandex/docs/en/query_language/queries.html#union-all-clause

**Comment by fleapapa** [comment]
1. Nope. With 10 thread, it is even worse -- took 567.033 secs. Weird is during the query, top shows "Load average: 24.83 15.13 6.59" while cpu usage on both cores was very low <5%. Due to the high load, all terminal windows were locked up till the query ended.

2. show create table trip:
CREATE TABLE default.trip ( _cx Date,  _c0 String,  _c1 String,  _c2 String,  _c3 String,  _c4 String,  _c5 DateTime,  _c6 DateTime,  _c7 Int8,  _c8 UInt16,  _c9 Float32,  _c10 Float32,  _c11 Float32,  _c12 Float32,  _c13 Float32) ENGINE = MergeTree(_cx, (_c5, _c6, _c10, _c11), 8192)

3. the query = 
  select _c8,_c9 from trip           
     where _c0='07290D3599E7A0D62097A346EFCC1FB5'           
     and _c1='E7750A37CAB07D0DFF0AF7E3573AC141'           
     and _c6>'2013-01-01 00:00:00'       
     and _c6<'2013-02-01 00:00:00'

**Comment by fleapapa** [comment]
The following tree view might be a clue about why system load was >24. No idea why "set max_threads=10" can result in 20+ threads....

 2925 root       20   0  520M  129M 11592 S  0.0 13.1  0:41.22 ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon
 2960 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.07 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2959 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.00 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2958 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.36 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2957 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.32 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2956 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.32 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2955 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.48 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2954 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.30 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2953 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.35 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2952 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.00 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2951 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.00 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2950 root       20   0  520M  129M 11592 S  0.0 13.1  0:01.31 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2949 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.03 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2948 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.02 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2947 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.02 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2946 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.02 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2945 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.01 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2944 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.02 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2943 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.03 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2942 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.02 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2941 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.02 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2940 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.02 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2939 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.02 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2938 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.02 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2937 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.02 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2936 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.03 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2935 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.02 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2934 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.02 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2931 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.06 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2930 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.06 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2928 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.00 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2927 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.00 │  ├─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon 
 2926 root       20   0  520M  129M 11592 S  0.0 13.1  0:00.00 │  └─ clickhouse-server --config=/etc/clickhouse-server/config.xml --daemon

**Comment by fleapapa** [comment]
any update?

**Comment by fleapapa** [comment]
Any update?

When i redid the test with almost the same environment as previously, except that this time i added 1GB more memory to my Ubuntu VM host, the result got worse! Immediately after i launched Clickhouse server and submitted the first (and the only one) query as below, my VM got completely frozen and no remote ssh access was possible. I had to reboot my VM. 

Here is the query that freezed my host:

> SELECT 
    avg(_c8), 
    avg(_c9)
FROM trip 
WHERE (_c0 = '07290D3599E7A0D62097A346EFCC1FB5') AND (_c1 = 'E7750A37CAB07D0DFF0AF7E3573AC141') AND (_c6 > '2013-01-01 00:00:00') AND (_c6 < '2013-02-01 00:00:00')

**Comment by fleapapa** [comment]
By the way, when the column _c6 in the WHERE condition was changed to _c5, the query took <1s, so index does help a lot. (Note: in my schema, _c5 is the first column in primary index, _c6 is the second one) The problem is CH doesn't support secondary index. Right?

**Comment by Imaskar** [comment]
If your table is MergeTree(_cx, (_c5, _c6, _c10, _c11), 8192) and you query on _c6, the index probably won't be used at all. You don't iterate columns you need indexes on in the 2nd argument, you build one complex index where rows firs sorted on _c5, then on _c6 and so on. Try to add condition on _c5 in your query.

**Comment by blinkov** [comment]
@fleapapa do you have any further questions?

**Comment by fleapapa** [comment]
No. Sorry, i haven't had chance to revisit the issue since. Feel free to close this issue if it has been fixed or never existed. Thanks!
