### ISSUE TITLE
Include not found

### ISSUE THREAD

**Issue by jalateras** [yandex/ClickHouse#12]
I have build the docker server image and when i run it using

```
docker run -it --rm clickhouse/server 
```

 Curious whether I should be concerned about the `Include not found` messages in the console

```
Include not found: clickhouse_remote_servers
Include not found: clickhouse_compression
2016.06.16 10:17:42.461 [ 1 ] <Warning> Application: Logging to console
2016.06.16 10:17:42.471 [ 1 ] <Information> : Starting daemon with revision 53981
2016.06.16 10:17:42.471 [ 1 ] <Information> Application: starting up
2016.06.16 10:17:42.471 [ 1 ] <Debug> Application: rlimit on number of file descriptors is 262144
2016.06.16 10:17:42.471 [ 1 ] <Debug> Application: Initializing DateLUT.
2016.06.16 10:17:42.471 [ 1 ] <Trace> Application: Initialized DateLUT.
2016.06.16 10:17:42.472 [ 1 ] <Debug> Application: Configuration parameter 'interserver_http_host' doesn't exist or exists and empty. Will use '85cbe55f8ddd' as replica host.
2016.06.16 10:17:42.472 [ 1 ] <Debug> UsersConfigReloader: Loading users config
Include not found: networks
Include not found: networks
2016.06.16 10:17:42.473 [ 1 ] <Information> Application: Loading metadata.
2016.06.16 10:17:42.473 [ 1 ] <Information> DatabaseOrdinary (default): Total 0 tables.
2016.06.16 10:17:42.473 [ 1 ] <Debug> Application: Loaded metadata.
2016.06.16 10:17:42.473 [ 1 ] <Information> DatabaseOrdinary (system): Total 0 tables.
2016.06.16 10:17:42.474 [ 1 ] <Information> Application: Ready for connections.
```

**Comment by DieHertz** [comment]
You shall not. Corresponding includes are mentioned in server's config.xml and are optional AFAIK.

**Comment by alexey-milovidov** [comment]
Yes, these messages are just notices.

**Comment by jalateras** [comment]
@alexey-milovidov is there a IRC channel or anywhere here you folks hang. Really interested in giving this a good test run over the next few weeks.

**Comment by alexey-milovidov** [comment]
No IRC.
Feel free to ask (even short/simple) questions on clickhouse-feedback@yandex-team.com and I will try to answer quickly.

**Comment by ACC211314** [comment]
Can I ask some questions? How to resolve the question that "Include not found :clickhouse_remote_servers" and "clickhouse_compression" on earth

**Comment by victor-perov** [comment]
I would like to add, that there are two telegram channels, where you can ask your questions.
* For English speaking community: https://t.me/clickhouse_en
* For Russian speaking guys: https://t.me/clickhouse_ru

**Comment by mator** [comment]
why does the ticket/issue closed , if no one offered a solution ?!

**Comment by alexey-milovidov** [comment]
@yukha-dw It is still supported.

**Comment by den-crane** [comment]
@yukha-dw  `cat /etc/metrika.xml` is not used by default anymore. 

you can do this:

```
cat /etc/clickhouse-server/config.d/compression.xml
<?xml version="1.0"?>
<clickhouse>
    <compression>
        <case>
            <min_part_size>100000000</min_part_size>
            <method>zstd</method>
            <level>1</level>
        </case>
    </compression>
</clickhouse>
```
