### ISSUE TITLE
arm32 support

### ISSUE THREAD

**Issue by marklit** [yandex/ClickHouse#1200]
Is there any sort of arm32 binary distribution of ClickHouse? If nothing officially sanctioned a link to anyone in the community that's put something together would be greatly appreciated.

**Comment by KochetovNicolai** [comment]
Hi,

arm32 and arm64 architectures are not currently supported. It was possible to build ClickHouse on arm64, but there might be problems though.
For 32 bit architectures it's more difficult. The ability to build on 32 bit was recently committed, but visible problems are:

- Possible lack of memory during compilation. Some files may need more than 2GB RAM.
- Not all of the tests are passed for i386.
- There are parts of the code where size_t assumed to be 64 bit

**Comment by marklit** [comment]
Before trying to compile I did increase my swapfile and rebooted my Raspberry Pi:

```
$ grep CONF_SWAPSIZE /etc/dphys-swapfile
CONF_SWAPSIZE=2048
```

It allowed for 1 GB of RAM and 2 GB of Swap. It's slow but I was hoping it would alleviate any memory issues. So far I've made it to about 54% of the way through compilation until I hit ``dbms/src/Common/BitHelpers.h`` and then the system locks up. I'm not sure if there is a way to somehow lower the memory usage during compilation. I'm going to continue to look into this.

**Comment by proller** [comment]
with swap your compile time will take days and you have chance to kill sd card.
and now you need ~3.4G ram
I have tried to compile on boards with 2g ram + swap and all attempts are unsuccessful

**Comment by marklit** [comment]
I've been able to attach mechanical sata drives via USB to avoid hitting the SD card too much.

Do you know of any parameters make or cmake can be given to try and lower that memory footprint? 3.4 GB doesn't feel like a world away from >3 GB.

**Comment by proller** [comment]
No, we need to split/refactor some c++ template code.
Maybe for now easier/faster to use debian arm on qemu or cross compile

**Comment by alexey-milovidov** [comment]
We have support for Aarch64 and PPC64, but we aren't going to support 32 bit architectures.
