### ISSUE TITLE
Support different Rounding Modes

### ISSUE THREAD

**Issue by tobad357** [yandex/ClickHouse#1211]
Would it be possible to add a parameter to the round(x[, N]) function to choose the type of rounding
In this case it would be nice to support HALF_UP, HALF_EVEN and HALF_DOWN
It would help a lot when doing financial calculations

Example from java
https://docs.oracle.com/javase/7/docs/api/java/math/RoundingMode.html

Interesting paper from AMD
http://developer.amd.com/resources/articles-whitepapers/new-round-to-even-technique-for-large-scale-data-and-its-application-in-integer-scaling/

**Comment by alexey-milovidov** [comment]
BTW, it uses HALF_EVEN (banker's rounding) by default.

**Comment by tobad357** [comment]
Thanks thats perfect for us
