### ISSUE TITLE
Deprecated Homebrew tap

### ISSUE THREAD

**Issue by kokes** [yandex/ClickHouse#1215]
When following the OS X [installation doc](https://clickhouse.yandex/docs/en/development/build_osx.html), I got this warning from Homebrew:

```
Warning: homebrew/dupes was deprecated. This tap is now empty as all its formulae were migrated.
==> Tapping homebrew/dupes
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes'...
(...)
Warning: Use zlib instead of deprecated homebrew/dupes/zlib
```

When searching for `zlib` in Homebrew, I got 

```
If you meant "zlib" specifically:
It was migrated from homebrew/dupes to homebrew/core.
```

So perhaps the doc should be updated to reflect these changes? Is it sufficient to replace `homebrew/dupes/zlib` with `homebrew/core/zlib` in all language mutations?

**Comment by proller** [comment]
fixed
