### ISSUE TITLE
Add option to specify custom ssl certificate for connection in MySQL Dictionary

### ISSUE THREAD

**Issue by bgaifullin** [yandex/ClickHouse#1217]
MySQL supports using custom ssl certificates for establish connection ([doc][1]), 
but there is no such option in dictionary configuration.

[1]: https://dev.mysql.com/doc/refman/5.7/en/mysql-ssl-set.html

**Comment by alexey-milovidov** [comment]
It seems easy to implement. Do you want to try?
Similar pull request (as an example): https://github.com/yandex/ClickHouse/pull/983

**Comment by bgaifullin** [comment]
Yes.

**Comment by bgaifullin** [comment]
patch is merged to master.

**Comment by alexey-milovidov** [comment]
Thanks!

**Comment by alexey-milovidov** [comment]
Thanks!
