### ISSUE TITLE
Suggestion: Allow updated field for external dictionaries

### ISSUE THREAD

**Issue by tobad357** [yandex/ClickHouse#1219]
We would like to use a hash dictionary connected to MySQL for 10s of millions of records.
It would seem a bit unnecessary to reload the whole table every X minutes 
Instead we would like a config option for the dictionary that specifies a "updated" field.
Then clickhouse would ask the external dictionary for any records that have changed since last time

Example:
1. First call to table "select * from dict_table"
2. Register the time the update call was started or max(updated_field) from response
3. Next call to table "select * from dict_table where updated_field >= 'last_update_time'

This way every future update would be minimised and we could ask the cache to update every couple of minutes

**Comment by blinkov** [comment]
Seems like your issue has been fixed in #1771
