### ISSUE TITLE
api to work with geo locations

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#1231]
Hello,

What the best way to work with geo locations in clickhouse ? I don't see support for havershine in order to be able to filter for results within a given radius of a given location. For example, filter events within a ten mile radius of San Francisco [-122.42005, 37.77479]. 

Any suggestions ?

Silviu

**Comment by sirkon** [comment]
https://clickhouse.yandex/docs/en/functions/math_functions.html#tgamma-x

![codecogseqn](https://user-images.githubusercontent.com/56399/30302086-6faab3b8-9767-11e7-87c2-f5c7b3889082.gif)

**Comment by silviucpp** [comment]
@sirkon  can you please elaborate. I don't see the link between havershine and tgamma.

Silviu

**Comment by IanCal** [comment]
@silviucpp Perhaps they just were linking to the page on mathematical operators?
 the equation posted looks like it's for the great circle distance : https://en.wikipedia.org/wiki/Great-circle_distance and it's composed entirely of operators that are already supported

**Comment by silviucpp** [comment]
@IanCal yes I figured out this after looking closer. I left this open maybe as an enhancement for clickhouse where we can have a function exported that takes as pramaters the longitude, latitude and a distance, and match the rows in that inverval. 

Something like:

```
geoWithin(latitude1, longitude1, latitude2, longitude2, distance_miles) -> boolean
```

Will make selects more simple :)

**Comment by silviucpp** [comment]
Seems this functionality is already implemented in clickhouse but I don't see any documentation for:

```sql
SELECT floor(greatCircleDistance(33.3, 55.3, 38.7, 55.1)) AS distance;
```

**Comment by alexey-milovidov** [comment]
Yes, the function `greatCircleDistance` is in production state. It is still missing in official documentation.

**Comment by silviucpp** [comment]
@alexey-milovidov should I close this bug or you want to close it when doc is updated ?

**Comment by alexey-milovidov** [comment]
Better to close.
