### ISSUE TITLE
Problem with ReplicatedMergeTree after update

### ISSUE THREAD

**Issue by artemkamolodets** [yandex/ClickHouse#1232]
Hello. I have problem with the creation of ReplicatedMergeTree tables type, after updating to version 1.1.54284 (server and client). 
When i executing statement like: 

 CREATE TABLE mydbname.mytablename ( date UInt32,  universe UInt32,  date_day Date MATERIALIZED toDate(concat(substring(toString(date), 1, 4), '-', substring(toString(date), 5, 2), '-', substring(toString(date), 7, 2)))) 
ENGINE = ReplicatedMergeTree('/clickhouse/tables/myshard/mydbname.mytablename', '01', date_day, date, 8192)

I've got following error: 

DB::Exception: Cannot parse input: expected metadata format version: 1 before: mytable table metadata directory.

The path: /clickhouse/tables/myshard/mydbname.mytablename/metadata "mytable table metadata directory" is present in zookeeper.
Please help, what i'm doing wrong?
Regards.

**Comment by ludv1x** [comment]
Hi!
I can't reproduce the problem.
Also, I can't find a similar exception message in ClickHouse's code base.
Could you provide the full exception message with stacktrace (just run `clickhouse-client` with `--stacktrace` parameter and repeat the query), please?

> The path: /clickhouse/tables/myshard/mydbname.mytablename/metadata "mytable table metadata directory" is present in zookeeper.
Do you mean that the directory had existed before you ran the query?
If so, you have to delete it and its parent directory, so `/clickhouse/tables/myshard/mydbname.mytablename` should not exist.

**Comment by artemkamolodets** [comment]
Hello, i've solved this issue by myself. The problem is, that i'm specifying wrong path to zknode.
Regards
