### ISSUE TITLE
tcmalloc: large alloc 1073750016 bytes == 0x46db2000 @ 

### ISSUE THREAD

**Issue by AlexPosix** [yandex/ClickHouse#1234]
After insert data , i got an error tcmalloc: large alloc 1073750016 bytes == 0x46db2000 @. How can we fix this ?
Server version 1.1.54189.

**Comment by vbadanov** [comment]
See this: https://github.com/gperftools/gperftools/issues/360

**Comment by blinkov** [comment]
@AlexPosix could you provide a way to reproduce it?

**Comment by alexey-milovidov** [comment]
Fixed in 18.10.3.
