### ISSUE TITLE
Implementing funnel and retention queries

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#1241]
Hello,

There is any functionality that allows implementing funnels and retention queries in clickhouse ?

For example, a funnel could include these steps:

- Step1: Count the number of unique users who registered in timeframe X.
- Step2: Of the users who were counted in step 1, count the number of them who created content in that timeframe
- Step3: Of the users who were counted in step 2, count the number of them who shared content in that timeframe
    
Supposing that the information is available in 3 different tables (`registration`, `created_content`, `shared_content`) and the common key is `user_id` what's the optimal way to implement this?

**Comment by ludv1x** [comment]
I could try to use `sequenceMatch` aggregate function.
https://clickhouse.yandex/docs/en/single/#sequencematch-pattern-time-cond1-cond2
But it is suitable when all events are stored in one table.

**Comment by ludv1x** [comment]
Also, there is a presentation about it https://events.yandex.com/events/meetings/05-10-2017/?talk=247
But it will be presented in upcoming ClickHouse meetup.

**Comment by silviucpp** [comment]
But what the use case when are in different tables ?

**Comment by ludv1x** [comment]
You could write subqueries for each table, concatenate them with UNION ALL and use `sequenceMatch`.
Also, the common ClickHouse's case is vast denormalized tables (500 columns is Ok).
