### ISSUE TITLE
Failed to compille under FreeBSD 10.3-RELEASE

### ISSUE THREAD

**Issue by Romamo** [yandex/ClickHouse#1258]
Hello,

System: FreeBSD 10.3-RELEASE with clang++38
Trying to build 1.1.54289 using current master of freebsd port from repo https://github.com/proller/freebsd-ports/tree/master/databases/clickhouse commit 2d4824a

```
In file included from dbms/src/DataStreams/CreatingSetsBlockInputStream.cpp:1:
dbms/src/Interpreters/Set.h:115:18: error: no template named 'shared_mutex' in namespace 'std'; did you mean 'shared_ptr'?
    mutable std::shared_mutex rwlock;
            ~~~~~^~~~~~~~~~~~
                 shared_ptr
/usr/include/c++/v1/memory:4010:61: note: 'shared_ptr' declared here
    template <class _Up> friend class _LIBCPP_TYPE_VIS_ONLY shared_ptr;
```

Could you please help me?
Thank you!

**Comment by proller** [comment]
libc++ in old freebsd (before 11) does not support c++17 features.
Easiest way to compile - upgrade your freebsd first ;)
