### ISSUE TITLE
wrong column with this name already exists error

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#1259]
Hello,

I have the following table:

```sql
CREATE TABLE test_column_name (
  `ss.partition` Date,
  `ss.timestamp` DateTime) ENGINE = ReplicatedMergeTree(
  '/var/lib/clickhouse/tables/{shard}/test_column_name',
  '{replica}',
  `ss.partition`,
  `ss.timestamp`,
  8192
)
```

In case I do :

```sql
ALTER TABLE test_column_name ADD COLUMN `ss` Array(String)
```

Operation fails with :

```sh
Code: 44, e.displayText() = DB::Exception: Cannot add column ss: column with this name already exists, e.what() = DB::Exception\n
```

**Comment by silviucpp** [comment]
Hello @alexey-milovidov ,

Any idea about this problem ?

**Comment by silviucpp** [comment]
Hello guys,

Please feel free to close this in case is not an issue

Silviu

**Comment by alexey-milovidov** [comment]
The behaviour is correct: dots in column names are reserved for Nested types.

It is still possible to define columns with dot in name and with non-Array type, but the prefix before dot should not clash with name of any other column.
