### ISSUE TITLE
how to add servers to existed cluster

### ISSUE THREAD

**Issue by wangyinsheng** [yandex/ClickHouse#1261]
hi, there 
    i build a clickhouse cluster with 5 servers, every server is a shard, now i need to add another 5 servers to this cluster ,  still every server is a shard. while i found that there is no database on the new 5 server.
   so how to synchronize the database and data to the new 5 servers?

**Comment by ludv1x** [comment]
I should just initialize required tables on new servers and update cluster configuration on each server.
Changes in the configuration files will be applied automatically.

If you worry about the non-uniform distribution of the data across the shards (the new one will be empty) then you could reallocate shard weights in the cluster config to increase the fraction of new data inserting into new shards.

**Comment by wangyinsheng** [comment]
thanks a lot!
well, i tried to execute `resharding` to move some data to the new servers , then there is an error `This host is not allowed to subscribe to coordinator......` , it something wrong?

**Comment by ludv1x** [comment]
Currently, the resharding is not supported and it doesn't work.

**Comment by wangyinsheng** [comment]
em.... 
while resharding dosen't work,  what should i do when removing a server from cluster?
by the way, is there any monitor tool for clickhouse cluster?

**Comment by blinkov** [comment]
@wangyinsheng at the moment the recommended way to reshard the data is to use https://clickhouse.yandex/docs/en/operations/utils/clickhouse-copier/
It does not work in-place though.

**Comment by kymtwyf** [comment]
Hi @blinkov @ludv1x  may I ask is resharding supported in latest versions ? if yes, how can I use it?

Thanks!

**Comment by abhilash-radhakrishnaru** [comment]
Latest version of clickhouse supports resharding?
