### ISSUE TITLE
Data Corruption of values inside an Array(Tuple(String, String))

### ISSUE THREAD

**Issue by RoyBellingan** [yandex/ClickHouse#1275]
ClickHouse client version 1.1.54180.
Connecting to localhost:9000.
Connected to ClickHouse server version 1.1.54180.

Changing how the data are retrieved changes the content of this column Array(Tuple(String, String))
Correct value should be [('weight',' a number... ')]  
I have checked carefully the original file of the import and they are fine

SELECT extension
FROM impressions 
WHERE (date = toDate(now())) AND (request_nr = 40532396660301216)

┌─extension───────────────┐
│ [('weight','255050.0')] │
└─────────────────────────┘

:) select request_nr,extension from impressions where date = toDate(now()) limit 10

SELECT 
    request_nr, 
    extension
FROM impressions 
WHERE date = toDate(now())
LIMIT 10

┌────────request_nr─┬─extension─────────────┐
│ 36028797027259213 │ [('weight','weight')] │
│ 36028797027259213 │ [('weight','weight')] │
│ 36028797027259213 │ [('weight','weight')] │
│ 36028797027259213 │ [('weight','weight')] │
│ 36028797027259213 │ [('weight','weight')] │
│ 36028797027259213 │ [('weight','weight')] │
│ 81064793317304563 │ [('weight','weight')] │
│ 76561193690773672 │ [('weight','weight')] │
│ 76561193692811798 │ [('weight','weight')] │
│ 76561193692811798 │ [('weight','weight')] │
└───────────────────┴───────────────────────┘

SELECT any(extension)
FROM impressions 
WHERE date = toDate(now())
GROUP BY zone_id
LIMIT 10

┌─any(extension)──────────┐
│ [('255050.0','50.0')]   │
│ [('weight','weight')]   │
│ [('weight','weight')]   │
│ [('255050.0','5255.0')] │
│ [('50.0','2037.0')]     │
└─────────────────────────┘
┌─any(extension)──────────┐
│ [('3255.0','1255.0')]   │
│ [('weight','weight')]   │
│ [('255050.0','4255.0')] │
└─────────────────────────┘
┌─any(extension)────────┐
│ [('weight','weight')] │
│ [('50.0','4255.0')]   │
└───────────────────────┘

I have no idea how to help more sorry.

**Comment by ludv1x** [comment]
Hi!
Do you use MergeTree engine? Could you show `SHOW CREATE TABLE impressions`?

**Comment by RoyBellingan** [comment]
Hi Ludv1x, yes the table is a MergeTree
Here is the full output

CREATE TABLE rt_analytics.impressions ( request_nr UInt64,  timestamp UInt32,  milliseconds UInt32,  ip String,  user_timezone_offset Int64,  nation UInt64,  subregion_0 UInt64,  subregion_1 UInt64,  city UInt64,  carrier String,  connection_type String,  afsu UInt64,  nugg_segments Array(Int8),  os_family_code UInt64,  os_version String,  browser_code UInt16,  browser_version String,  device_code UInt16,  brand_code UInt16,  affiliate_id UInt64,  affmgr_ids Array(UInt64),  zone_id UInt64,  website_id UInt64,  clean_url String,  weSbsite_primary_categories Array(UInt16),  website_secondary_categories Array(UInt16),  zone_primary_categories Array(UInt16),  zone_secondary_categories Array(UInt16),  campaign_id UInt64,  merchant_id UInt64,  trafficker_ids Array(UInt64),  salesPerson_id UInt64,  channel String,  campaign_primary_categories Array(UInt16),  campaign_secondary_categories Array(UInt16),  campaign_primary_targeting Array(UInt16),  campaign_secondary_targeting Array(UInt16),  banner_id UInt64,  extraNum1 Int64,  extraNum2 Int64,  extraNum3 Int64,  extraNum4 Int64,  extraNum5 Int64,  extraString1 String,  extraString2 String,  extraString3 String,  extraString4 String,  extraString5 String,  slot_position UInt8,  slotCount UInt8,  isWebsiteImpression Int8,  extension Array(Tuple(String, String)),  rtbBidfloor Float32,  rtbOffered Float32,  gross Float32,  tare Float32,  curId Int16,  curRate Float32,  new_merchant_id Int64 MATERIALIZED dictGetInt64(\'campaigns\', \'merchant_id\', campaign_id),  partner_id Int64 MATERIALIZED dictGetInt64(\'campaigns\', \'partner_id\', campaign_id),  date Date MATERIALIZED toDate(timestamp),  dateTime DateTime MATERIALIZED toDateTime(timestamp),  domain String MATERIALIZED domain(concat(\'http://\', clean_url)),  zone_position UInt64 MATERIALIZED dictGetUInt64(\'zones\', \'position\', zone_id)) ENGINE = MergeTree(date, timestamp, 8192)

**Comment by George3d6** [comment]
I believe the problem may lie in the columns definition:

`extension Array(Tuple(String, String))`

MergeTrees don't allow for array of array type columns, but it doesn't complain for array of tuples... though maybe, even if the warning is not there, the same bugs can arise (if tuple is just a wrapper over the array/vector for most part).

However this is pure speculation based on the fact that querying said column can result in crashes if the table is large enough.

**Comment by alexey-milovidov** [comment]
We have added support for multidimensional arrays and combinations of arrays and tuples in tables. It is available in latest master (still yet to be released).
