### ISSUE TITLE
Which directory max_bytes_before_external_group_by parameter uses?

### ISSUE THREAD

**Issue by ramazanpolat** [yandex/ClickHouse#1277]
The _max_bytes_before_external_group_by_ parameter can be used to enable spilling temporary data to disk.
The question is, where does it write?
The linux /tmp directory or the data directory of Clickhouse?
Why I am asking this?
My data folder is backed by SSD. I want to be sure if the temporary data is also written to SSD since HDD will be much more slower.

**Comment by ztlpn** [comment]
The directory name for temporary files is controlled by the `tmp_path` config parameter. It is `/var/lib/clickhouse/tmp/` by default which is inside the data directory.

**Comment by ramazanpolat** [comment]
Ok. That's good to know.
