### ISSUE TITLE
Can't open https://clickhouse.yandex/

### ISSUE THREAD

**Issue by bookin** [yandex/ClickHouse#1280]
I can't open https://clickhouse.yandex/, is it only my problem? Or all have the same problem?

**Comment by alexey-milovidov** [comment]
http://downforeveryoneorjustme.com/clickhouse.yandex
Looks like it is just for you.
Please provide more details: your IP address, traceroute, etc.

**Comment by bookin** [comment]
I think it is problem for Ukrainian. I will try to use other vpn and say about result

**Comment by alexey-milovidov** [comment]
For documentation, you may use this mirror: http://clickhouse-docs.readthedocs.io/en/latest/index.html
(probably outdated)
Or read documentation directly by browsing GitHub:
https://github.com/yandex/ClickHouse/tree/master/docs/ru

**Comment by bookin** [comment]
Thanks for help, it will be better

**Comment by bookin** [comment]
russian - http://clickhouse.readthedocs.io/en/latest/reference_ru.html
