### ISSUE TITLE
Client Exits on error

### ISSUE THREAD

**Issue by vikaasbv** [yandex/ClickHouse#129]
The client exits whenever an exception occurs.  For example when there is an error in the query, the client exits out

**Comment by alexey-milovidov** [comment]
Could you please provide more details?

In interactive mode, client should not exit on error in query; 
but in batch mode with `multiquery` option, client should exit (stop processing the script) on first error.

**Comment by vikaasbv** [comment]
I am using --multiquery option when I connect using the client.  When I do not use the option, the client does not exit.

**Comment by alexey-milovidov** [comment]
It is intended for non-interactive mode.
I think, that in interactive mode, even with multiquery option, client should not exit.

**Comment by alexey-milovidov** [comment]
I will implement the following behavior in interactive multiquery mode:
client will break processing list of queries at first error, but will not exit.

**Comment by alexey-milovidov** [comment]
Like this:

```
:) SELECT 1; SELECT a; SELECT 2;

SELECT 1

┌─1─┐
│ 1 │
└───┘

1 rows in set. Elapsed: 0.002 sec. 


SELECT a

Received exception from server:
Code: 47. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Unknown identifier: a. 

0 rows in set. Elapsed: 0.026 sec. 

:)
```

**Comment by alexey-milovidov** [comment]
https://github.com/yandex/ClickHouse/commit/b1f551d5bab27439e504d3258879ad43d87cf6c4

**Comment by vikaasbv** [comment]
I believe that is really helpful - having to keep reconnecting on every failure was a bit painful, especially when connected to a remote system over a slow connection.

Just a thought on this behaviour. Would it have been better to allow the user 3 modes (say exit, break and continue).  The default in interactive mode can be "break" (stop processing of further queries in the batch but do not exit).  The default in non-interactive mode would be "exit".  If the session mode was set to "continue", the next query would get executed irrespective of the status of the current query.  This can be applicable even for the non-interactive mode as well?  I believe it may be helpful for running some tests that involve verification of behaviour after a failed query.

**Comment by alexey-milovidov** [comment]
Thanks, option to skip through errors in multiquery mode should be useful.
Break on first error is good default.
