### ISSUE TITLE
Internal error with emptyArrayString()

### ISSUE THREAD

**Issue by kislenok-roman** [yandex/ClickHouse#1290]
Code to reproduce is simple as:
```
select 
  case 
    when c1 = 1 then extractURLParameters(url) 
    else emptyArrayString() 
  end as a1 
from (
    select 1 as c1, '/?t=1' as url 
  union all 
    select 2 as c1, '' as url
)
```

Expected result:
```
┌─a1──────┐
│ ['t=1'] │
│ []      │
└─────────┘
```
Actual result:
```
┌─a1──────┐
│ ['t=1'] │
└─────────┘
Received exception from server:
Code: 49. DB::Exception: Received from clickhouse-n1.dev:9000, 172.16.8.163. DB::Exception: Internal error. 
```
Stack trace:
0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x1132036]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0xf293ef]
2. clickhouse-server(DB::Conditional::StringArrayEvaluator::perform(DB::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, DB::Conditional::NullMapBuilder&)+0xa41) [0x1e6f201]
3. clickhouse-server(DB::FunctionMultiIf::perform(DB::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, DB::Conditional::NullMapBuilder&)+0x73) [0x1acb113]
4. clickhouse-server(DB::FunctionMultiIf::executeImpl(DB::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long)+0x3db) [0x1acc02b]
5. clickhouse-server(DB::FunctionCaseWithoutExpr::executeImpl(DB::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long)+0x19)

**Comment by KochetovNicolai** [comment]
Hi,

Which ClickHouse version do you use?
Can't reproduce for 1.1.54289 and 1.1.54292

**Comment by kislenok-roman** [comment]
ClickHouse server version 1.1.54164. So we need to update... ok, thank you

**Comment by kislenok-roman** [comment]
Just updated database and recheck -- everything seems fine.
