### ISSUE TITLE
Foreign data wrappers for integration into Postgres

### ISSUE THREAD

**Issue by ml31415** [yandex/ClickHouse#1291]
I recently came across ClickHouse and would love to use it for it's blazing speed. Nevertheless, I have a bunch of tables, where more features would be desireable, like update/delete, value constraints or dynamical field sizes. Combining the speed and efficiency for a bunch of large tables with the convenience and features of postgres or mysql for a bunch of other tables would be great.

Postgres offers a way to integrate tables not managed by postgres itself into the database, called foreign data wrappers. The cstore_fdw, another columar storage engine, does exactly that, unfortunately not half as fast as ClickHouse.

https://wiki.postgresql.org/wiki/Foreign_data_wrappers
https://github.com/citusdata/cstore_fdw

It would be a pleasure to see ClickHouse integrated into postgres, so that from a developer point of view, I only have to care about one database, and I just use different storage engines for different tables according to different requirements.

**Comment by jotes** [comment]
@ml31415 did you see https://github.com/Infinidat/infi.clickhouse_fdw/ ?

**Comment by ml31415** [comment]
Oh, I guess that fixes it. Thanks!

**Comment by ml31415** [comment]
Being based on multicorn, unfortunately it doesn't seem to be a speedy option :/
