### ISSUE TITLE
Max datetime is 2037 year

### ISSUE THREAD

**Issue by valetanddama** [yandex/ClickHouse#1296]
`SELECT toDateTime('2037-01-01 00:00:00')` return 2037-01-01 00:00:00, but
`SELECT toDateTime('2038-01-01 00:00:00')` return 0000-00-00 00:00:00

It's a bug?

**Comment by KochetovNicolai** [comment]
No, it's not a bug. It's because ClickHouse uses 32-bit type to store DateType.
https://en.wikipedia.org/wiki/Year_2038_problem
