### ISSUE TITLE
ReplacingMergeTree не добавляет новые записи

### ISSUE THREAD

**Issue by valetanddama** [yandex/ClickHouse#1303]
Я создал таблицу 

```
CREATE MATERIALIZED VIEW public.users_first_payment
ENGINE = ReplacingMergeTree(date, (email, project_id), 8192, version) 
POPULATE AS 
SELECT 
    email,
    project_id,
    date_visit,
    toDate(now()) as date,
    toUInt32(toDateTime('2037-01-01 00:00:00') - toDateTime(now())) as version
FROM public.events ... <SOME_SELECT_QUERY>
```

Она отлично заполнилась на уже имеющихся данных в целевой таблице, но когда приходят новые данные, то они не добавляются в public.users_first_payment, хотя произвольное выполнение селекта в public.events для заполнения public.users_first_payment возвращает мне эти данные, которые должны были добавиться.  

Через ваш докер образ все работает без проблем, но на моем сервере нет. Есть ли какие нибудь настройки, которые необходимо установить.

P.S таблица public.users_first_payment селектит из public.events, на которую смотри Distributed таблица и все это лежит на одном сервере, запись осуществляю на второй сервер, где развернута такая же пара public.events и Distributed таблица. Конфиги реплики корректны и нормально обмениваются данными.

**Comment by KochetovNicolai** [comment]
Попытался ответить в [гугл-группе](https://groups.google.com/forum/#!topic/clickhouse/cBgJgFrw4cg).
