### ISSUE TITLE
lost data after built and upgraded to ClickHouse revision 54292

### ISSUE THREAD

**Issue by fleapapa** [yandex/ClickHouse#1307]
Hi, i built CH from source code and upgraded clickhouse-server accordingly. Then i found one of my table lost most of the data. Its row count reduced from 172M rows to 1.5M rows. 

From server log below, seems like CH server did a lot of merge work on the table, which might cause the data loss. i have used (prebuilt binary) CH for a few months and the table had been having the 172M rows without any problem. Why hadn't this merge (duduplication) work been performed until today when i upgraded to a source built revision of CH server?

Fortunately the 172M rows contain all test data not for production :)

> Include not found: clickhouse_remote_servers
> Include not found: clickhouse_compression
> 2017.09.29 08:10:23.358320 [ 1 ] <Warning> Application: Logging to console
> 2017.09.29 08:10:23.363574 [ 1 ] <Information> : Starting daemon with revision 54292
> 2017.09.29 08:10:23.363713 [ 1 ] <Information> Application: starting up
> 2017.09.29 08:10:23.795707 [ 1 ] <Debug> Application: Set max number of file descriptors to 4096 (was 1024).
> 2017.09.29 08:10:23.795769 [ 1 ] <Debug> Application: Initializing DateLUT.
> 2017.09.29 08:10:23.795785 [ 1 ] <Trace> Application: Initialized DateLUT with time zone `America/Los_Angeles'.
> 2017.09.29 08:10:23.798166 [ 1 ] <Debug> ConfigReloader: Loading config `/etc/clickhouse-server/users.xml'
> 2017.09.29 08:10:23.801558 [ 1 ] <Warning> ConfigProcessor: Include not found: networks
> 2017.09.29 08:10:23.801870 [ 1 ] <Warning> ConfigProcessor: Include not found: networks
> 2017.09.29 08:10:23.803453 [ 1 ] <Information> Application: Loading metadata.
> 2017.09.29 08:10:23.804205 [ 1 ] <Information> DatabaseOrdinary (system): Total 0 tables.
> 2017.09.29 08:10:23.804456 [ 1 ] <Information> DatabaseOrdinary (system): Starting up tables.
> 2017.09.29 08:10:23.805972 [ 1 ] <Information> DatabaseOrdinary (default): Total 3 tables.
> 2017.09.29 08:10:25.798736 [ 2 ] <Debug> ConfigReloader: Loading config `/etc/clickhouse-server/config.xml'
> 2017.09.29 08:10:25.800056 [ 2 ] <Warning> ConfigProcessor: Include not found: clickhouse_remote_servers
> 2017.09.29 08:10:25.800143 [ 2 ] <Warning> ConfigProcessor: Include not found: clickhouse_compression
> 2017.09.29 08:10:26.903126 [ 3 ] <Information> StorageSetOrJoinBase: Loaded from backup file /mnt/trip/clickhouse/data/default/setc5/1.bin. 172083714 rows, 656.45 MiB. State has 27209101 unique rows.
> 2017.09.29 08:10:26.908706 [ 3 ] <Information> BackgroundProcessingPool: Create BackgroundProcessingPool with 16 threads
> 2017.09.29 08:10:26.949708 [ 3 ] <Debug> default.trip (Data): Loading data parts
> 2017.09.29 08:10:27.501500 [ 3 ] <Debug> default.trip (Data): Loaded data parts (57 items)
> 2017.09.29 08:10:27.517291 [ 3 ] <Debug> default.trip2 (Data): Loading data parts
> 2017.09.29 08:10:27.813667 [ 3 ] <Debug> default.trip2 (Data): Loaded data parts (20 items)
> 2017.09.29 08:10:27.813899 [ 1 ] <Information> DatabaseOrdinary (default): Starting up tables.
> 2017.09.29 08:10:27.814235 [ 4 ] <Debug> default.trip (Merger): Selected 6 parts from 20131104_20131130_675_1209_7 to 20131104_20131108_1521_1521_0
> 2017.09.29 08:10:27.814327 [ 4 ] <Debug> default.trip (Merger): Merging 6 parts: from 20131104_20131130_675_1209_7 to 20131104_20131108_1521_1521_0 into tmp_merge_20131104_20131130_675_1521_8
> 2017.09.29 08:10:27.814391 [ 7 ] <Debug> default.trip (Merger): Selected 5 parts from 20131203_20131206_1113_1475_6 to 20131203_20131206_1518_1518_0
> 2017.09.29 08:10:27.814460 [ 6 ] <Debug> default.trip (Merger): Selected 4 parts from 20130826_20130831_1428_1481_1 to 20130826_20130831_1519_1519_0
> 2017.09.29 08:10:27.814497 [ 6 ] <Debug> default.trip (Merger): Merging 4 parts: from 20130826_20130831_1428_1481_1 to 20130826_20130831_1519_1519_0 into tmp_merge_20130826_20130831_1428_1519_2
> 2017.09.29 08:10:27.814527 [ 9 ] <Debug> default.trip (Merger): Selected 4 parts from 20130505_20130506_1421_1480_1 to 20130505_20130507_1517_1517_0
> 2017.09.29 08:10:27.814566 [ 9 ] <Debug> default.trip (Merger): Merging 4 parts: from 20130505_20130506_1421_1480_1 to 20130505_20130507_1517_1517_0 into tmp_merge_20130505_20130507_1421_1517_2
> 2017.09.29 08:10:27.814720 [ 8 ] <Debug> default.trip (Merger): Selected 4 parts from 20130412_20130428_1425_1486_1 to 20130412_20130427_1520_1520_0
> 2017.09.29 08:10:27.814740 [ 7 ] <Debug> default.trip (Merger): Merging 5 parts: from 20131203_20131206_1113_1475_6 to 20131203_20131206_1518_1518_0 into tmp_merge_20131203_20131206_1113_1518_7
> 2017.09.29 08:10:27.814730 [ 4 ] <Debug> default.trip (Merger): Selected MergeAlgorithm: Horizontal
> 2017.09.29 08:10:27.815047 [ 4 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20131104_20131130_675_1209_7, approx. 49152 rows starting from 0
> 2017.09.29 08:10:27.815078 [ 4 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20131104_20131130_1222_1468_4, approx. 24576 rows starting from 0
> 2017.09.29 08:10:27.815089 [ 4 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20131104_20131108_1482_1482_0, approx. 8192 rows starting from 0
> 2017.09.29 08:10:27.815098 [ 4 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20131104_20131108_1496_1496_0, approx. 8192 rows starting from 0
> 2017.09.29 08:10:27.815106 [ 4 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20131104_20131108_1508_1508_0, approx. 8192 rows starting from 0
> 2017.09.29 08:10:27.814765 [ 8 ] <Debug> default.trip (Merger): Merging 4 parts: from 20130412_20130428_1425_1486_1 to 20130412_20130427_1520_1520_0 into tmp_merge_20130412_20130428_1425_1520_2
> 2017.09.29 08:10:27.814727 [ 6 ] <Debug> default.trip (Merger): Selected MergeAlgorithm: Horizontal
> 2017.09.29 08:10:27.815180 [ 6 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20130826_20130831_1428_1481_1, approx. 8192 rows starting from 0
> 2017.09.29 08:10:27.815194 [ 6 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20130826_20130831_1492_1492_0, approx. 8192 rows starting from 0
> 2017.09.29 08:10:27.815202 [ 6 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20130826_20130831_1506_1506_0, approx. 8192 rows starting from 0
> 2017.09.29 08:10:27.815211 [ 6 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20130826_20130831_1519_1519_0, approx. 8192 rows starting from 0
> 2017.09.29 08:10:27.815382 [ 8 ] <Debug> default.trip (Merger): Selected MergeAlgorithm: Horizontal
> 2017.09.29 08:10:27.815406 [ 8 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20130412_20130428_1425_1486_1, approx. 8192 rows starting from 0
> 2017.09.29 08:10:27.815418 [ 8 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20130412_20130427_1499_1499_0, approx. 8192 rows starting from 0
> 2017.09.29 08:10:27.814787 [ 9 ] <Debug> default.trip (Merger): Selected MergeAlgorithm: Horizontal
> 2017.09.29 08:10:27.814802 [ 5 ] <Debug> default.trip (Merger): Selected 4 parts from 20130703_20130711_1414_1478_1 to 20130703_20130711_1513_1513_0
> 2017.09.29 08:10:27.815531 [ 5 ] <Debug> default.trip (Merger): Merging 4 parts: from 20130703_20130711_1414_1478_1 to 20130703_20130711_1513_1513_0 into tmp_merge_20130703_20130711_1414_1513_2
> 2017.09.29 08:10:27.815426 [ 8 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20130412_20130428_1509_1509_0, approx. 8192 rows starting from 0
> 2017.09.29 08:10:27.815568 [ 8 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20130412_20130427_1520_1520_0, approx. 8192 rows starting from 0
> 2017.09.29 08:10:27.815622 [ 10 ] <Debug> default.trip (Merger): Selected 4 parts from 20131006_20131022_1111_1483_6 to 20131005_20131013_1523_1523_0
> 2017.09.29 08:10:27.815678 [ 11 ] <Debug> default.trip (Merger): Selected 3 parts from 20130607_20130616_1436_1498_1 to 20130608_20130616_1522_1522_0
> 2017.09.29 08:10:27.815732 [ 11 ] <Debug> default.trip (Merger): Merging 3 parts: from 20130607_20130616_1436_1498_1 to 20130608_20130616_1522_1522_0 into tmp_merge_20130607_20130616_1436_1522_2
> 2017.09.29 08:10:27.815750 [ 10 ] <Debug> default.trip (Merger): Merging 4 parts: from 20131006_20131022_1111_1483_6 to 20131005_20131013_1523_1523_0 into tmp_merge_20131005_20131022_1111_1523_7
> 2017.09.29 08:10:27.815458 [ 9 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20130505_20130506_1421_1480_1, approx. 8192 rows starting from 0
> 2017.09.29 08:10:27.815808 [ 12 ] <Debug> default.trip (Merger): Selected 3 parts from 20130902_20130913_1427_1491_1 to 20130903_20130913_1515_1515_0
> 2017.09.29 08:10:27.815468 [ 7 ] <Debug> default.trip (Merger): Selected MergeAlgorithm: Horizontal
> 2017.09.29 08:10:27.815114 [ 4 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20131104_20131108_1521_1521_0, approx. 8192 rows starting from 0
> 2017.09.29 08:10:27.815882 [ 13 ] <Debug> default.trip (Merger): Selected 3 parts from 20130325_20130331_1258_1502_4 to 20130325_20130331_1524_1524_0
> 2017.09.29 08:10:27.815890 [ 7 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20131203_20131206_1113_1475_6, approx. 40960 rows starting from 0
> 2017.09.29 08:10:27.815891 [ 9 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20130505_20130506_1494_1494_0, approx. 8192 rows starting from 0
> 2017.09.29 08:10:27.815908 [ 7 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20131203_20131206_1485_1485_0, approx. 8192 rows starting from 0
> 2017.09.29 08:10:27.815928 [ 9 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20130505_20130507_1505_1505_0, approx. 8192 rows starting from 0
> 2017.09.29 08:10:27.815930 [ 7 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20131203_20131206_1495_1495_0, approx. 8192 rows starting from 0
> 2017.09.29 08:10:27.815941 [ 9 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20130505_20130507_1517_1517_0, approx. 8192 rows starting from 0
> 2017.09.29 08:10:27.815947 [ 7 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20131203_20131206_1507_1507_0, approx. 8192 rows starting from 0
> 2017.09.29 08:10:27.815956 [ 7 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20131203_20131206_1518_1518_0, approx. 8192 rows starting from 0
> 2017.09.29 08:10:27.816152 [ 12 ] <Debug> default.trip (Merger): Merging 3 parts: from 20130902_20130913_1427_1491_1 to 20130903_20130913_1515_1515_0 into tmp_merge_20130902_20130913_1427_1515_2
> 2017.09.29 08:10:27.816580 [ 13 ] <Debug> default.trip (Merger): Merging 3 parts: from 20130325_20130331_1258_1502_4 to 20130325_20130331_1524_1524_0 into tmp_merge_20130325_20130331_1258_1524_5
> 2017.09.29 08:10:27.816705 [ 1 ] <Debug> Application: Loaded metadata.
> 2017.09.29 08:10:27.817635 [ 1 ] <Information> Application: Listening http://[::1]:8123
> 2017.09.29 08:10:27.817680 [ 1 ] <Information> Application: Listening tcp: [::1]:9000
> 2017.09.29 08:10:27.817706 [ 1 ] <Information> Application: Listening interserver: [::1]:9009
> 2017.09.29 08:10:27.817743 [ 1 ] <Information> Application: Listening http://127.0.0.1:8123
> 2017.09.29 08:10:27.817765 [ 1 ] <Information> Application: Listening tcp: 127.0.0.1:9000
> 2017.09.29 08:10:27.817792 [ 1 ] <Information> Application: Listening interserver: 127.0.0.1:9009
> 2017.09.29 08:10:27.818097 [ 1 ] <Information> Application: Available RAM = 5.38 GiB; physical cores = 7; threads = 7.
> 2017.09.29 08:10:27.818114 [ 1 ] <Information> Application: Ready for connections.
>

**Comment by ztlpn** [comment]
Hi @fleapapa ! Can you provide the CREATE TABLE statement for the problematic table? Is it a simple MergeTree table or some variant such as ReplacingMergeTree?

Can you try to reproduce the unwanted behaviour with a small repeatable test case? You can trigger additional merges with [OPTIMIZE statement](https://clickhouse.yandex/docs/en/query_language/queries.html#optimize).

**Comment by fleapapa** [comment]
Hi @ztlpn, 

Sure. Here you go.
```
    create table trip (
        _cx    Date,
        _c0    String,
        _c1    String,
        _c2    String,
        _c3    String,
        _c4    String,
        _c5    DateTime,
        _c6    DateTime,
        _c7    Int8,
        _c8    UInt32,
        _c9    Float32,
        _c10   Float32,
        _c11   Float32,
        _c12   Float32,
        _c13   Float32
)
engine=MergeTree(_cx, (_c5, _c6), 8192)

```

When loading the test data, _cx column is derived from _c5.

And, here is the [test dataset](http://www.andresmh.com/nyctaxitrips/).

A quick question. Does this type of table allow multiple rows with duplicate primary key as defined above?

**Comment by ztlpn** [comment]
Well, that's not exactly small :) I'll try to reproduce, but maybe the problem manifests itself even with a few rows? Also, what are the `setc5` and `trips2` tables?

> A quick question. Does this type of table allow multiple rows with duplicate primary key as defined above?

MergeTree allows rows with the same primary key. In fact the name is a bit of misnomer (the reason why the index is called "primary key" has to do with the fact that it determines the physical structure of the table). Merging process in an ordinary MergeTree table should not ever delete rows.

**Comment by fleapapa** [comment]
Thanks. I see. I asked the question due to a suspicion that the loss might come from (unexpected) de-duplication of duplicate primary keys in the table. From the original CSV files, there might be some duplicate primary keys but not as many as 170M row. Chance should be small for different taxi drivers to pick up and drop off passengers at the same time. 

I'm sure the **trip** is simply a MergeTree table, though **trip2** is a ReplacingMergeTree table and **setc5** is a Set table. However, the latter two tables were for other test purpose and should be independent of the problematic table trip.

**Comment by ztlpn** [comment]
Well, I failed to reproduce it with clickhouse-server from our prebuilt packages. I created the table with the date column defined as `_cx Date default toDate(_c5)`, loaded all the data into it with the following statement:
```
for i in {1..12}; do tail -n +2 trip_data_$i.csv | clickhouse-client -q 'insert into trip(_c0, _c1, _c2, _c3, _c4, _c5, _c6, _c7, _c8, _c9, _c10, _c11, _c12, _c13) format CSV' --input_format_allow_errors_num=1 --input_format_allow_errors_ratio=0.001; done
```
This resulted in 173178594 rows which is slightly higher than what you report (BTW do you have an idea why?). I then tried merging it using OPTIMIZE and also waited a little bit for some merges to happen naturally. The count didn't change.

What I have found strange in your log is that you seem to have a lot of small parts (part count is in 1500-s and each part is `approx. 8192 rows`) which shouldn't be the case if you have bulk-inserted it. How did you insert the data?

May I also ask what is your reason for re-compiling the package when earlier you were using provided packages?

**Comment by fleapapa** [comment]
Thanks for the investigation. I wrote a python script to load teh data. The reason why my row count was less is there were quite some rows in the source files that contains '-10' and empty strings for _c8 and _c13. Afterward i changed _c8 to Int32 and _c13 to nullable to ignore the errors. Right now i'm reloading the data. I guess my row count should be close to yours this time:)

I recompiled the package simply to check if CH could be built from source code on Ubuntu 16.04.

**Comment by ztlpn** [comment]
If you haven't yet deleted the table, can you check the `<clickhouse data directory>/data/default/trip/detached/` directory? Are there any subdirectories there?

**Comment by fleapapa** [comment]
Unfortunately i have deleted the table and reloaded it. This time i changed _c8 type to Int32 so the block insert API used in my python script wouldn't fail. For _c13 i simply made its value 0 if the source is an empty string to bypass python float() conversion error. Please see [the script](https://github.com/fleapapa/test/blob/master/trip-clickhouse.py).

**Comment by fleapapa** [comment]
BTW, i also changed type of the table from MergeTree to ReplacingMergeTree so will expect any deduplication this time. I may stick to this table type for a while, so let me close this issue first. In case i switch back MergeTree and the issue happens again, i will re-open it. Thanks a lot for the investigation!
