### ISSUE TITLE
cmake3 not found when install Clang

### ISSUE THREAD

**Issue by fleapapa** [yandex/ClickHouse#1310]
When i tried to install Clang using the install-clang.sh script, it shows this error:

`E: Unable to locate package cmake3`

It seems no cmake3 is available for Ubuntu 16.04. Any advise to resolve this issue?

Also, I saw this in CH documentation:

> Clang is embedded into ClickHouse package and used at runtime. Minimum version is 3.8.0. It is optional.

I am confused why Clang is used at runtime but is optional.

Besides, I am curious **how** Clang is used at runtime. Any quick pointer to related source code will be helpful.

**Comment by alexey-milovidov** [comment]
On newer OS, `cmake3` package is named as just `cmake`. You can correct the script.
Clang is optional and used only when you enable `compile` setting. Look at https://clickhouse.yandex/docs/en/single/#compile

**Comment by fleapapa** [comment]
Hi @alexey-milovidov. Thanks for the pointer.
