### ISSUE TITLE
Avro or Parquet support for INSERT queries?

### ISSUE THREAD

**Issue by benepo** [yandex/ClickHouse#1342]
In reviewing the current supported [INSERT formats](https://clickhouse.yandex/docs/en/formats/index.html) for loading data into ClickHouse, I was wondering if your roadmap includes support for newer, more efficient data formats like [Avro](https://blog.cloudera.com/blog/2016/04/benchmarking-apache-parquet-the-allstate-experience/) or [Parquet](https://developer.ibm.com/hadoop/2015/12/03/parquet-for-spark-sql/) over [CSV](https://blog.stitchdata.com/redshift-database-benchmarks-copy-performance-of-csv-json-and-avro-9062f71f8148) (which appears to be the most performant non-proprietary option in your current list).  Our use case involves importing terabytes of data.

**Comment by amosbird** [comment]
+1. This would be really useful to migrate data from hadoop ecosystem to ch.

**Comment by shilf** [comment]
+1 I hope Support Parquet

**Comment by adhamelia** [comment]
+1 for support

**Comment by luc1ph3r** [comment]
I think I'll work on this in my thesis. Can't set the exact deadline, though

**Comment by blinkov** [comment]
Parquet is in development at #2427

**Comment by inv2004** [comment]
Can we reopen the issue for Avro format ?

**Comment by filimonov** [comment]
> Can we reopen the issue for Avro format ?

Please open a new issue for that.
