### ISSUE TITLE
Inconsistent query results

### ISSUE THREAD

**Issue by vikaasbv** [yandex/ClickHouse#135]
I was running some queries to verify the consistency of data after a load operation.  Below are some observations

Clickhouse version details
================
ClickHouse client version 1.1.54022.
Connecting to database smsr at localhost:9000.
Connected to ClickHouse server version 1.1.54022.

TOTAL number of records loaded. This is consistent with the raw CSV data.
==============================================
:) select count() from cdr;

SELECT count()
FROM cdr

┌───count()─┐
│ 527670245 │
└───────────┘

1 rows in set. Elapsed: 0.138 sec. Processed 527.67 million rows, 1.06 GB (3.83 billion rows/s., 7.65 GB/s.)

The number of records for each date.  This too is consistent with the raw data.
================================================
:) select count(), merge_date from cdr group by merge_date;

SELECT
    count(),
    merge_date
FROM cdr
GROUP BY merge_date

┌───count()─┬─merge_date─┐
│ 205080000 │ 2015-01-21 │
│ 322590245 │ 2015-01-22 │
└───────────┴────────────┘

2 rows in set. Elapsed: 0.835 sec. Processed 527.67 million rows, 1.06 GB (631.70 million rows/s., 1.26 GB/s.)

How can the total number of distinct rows when grouped by the merge date field be more than the total records in the table?
=============================================================

:) select count(distinct id), merge_date from cdr group by merge_date;

SELECT
    countDistinct(id),
    merge_date
FROM cdr
GROUP BY merge_date

┌──uniq(id)─┬─merge_date─┐
│ 206247254 │ 2015-01-21 │
│ 324102175 │ 2015-01-22 │
└───────────┴────────────┘

2 rows in set. Elapsed: 21.991 sec. Processed 527.67 million rows, 3.17 GB (23.99 million rows/s., 143.97 MB/s.)

:) select 206247254  + 324102175, 206247254 + 324102175 - 527670245;

SELECT
    206247254 + 324102175,
    (206247254 + 324102175) - 527670245

┌─plus(206247254, 324102175)─┬─minus(plus(206247254, 324102175), 527670245)─┐
│                  530349429 │                                      2679184 │
└────────────────────────────┴──────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.005 sec.

How can the total number of distinct column values be more than the total records in the table?
===========================================================

:) select count(distinct id), count(), count(distinct id) - count() from cdr;

SELECT
    countDistinct(id),
    count(),
    countDistinct(id) - count()
FROM cdr

┌──uniq(id)─┬───count()─┬─minus(uniq(id), count())─┐
│ 531654647 │ 527670245 │                  3984402 │
└───────────┴───────────┴──────────────────────────┘

1 rows in set. Elapsed: 1.169 sec. Processed 527.67 million rows, 2.11 GB (451.55 million rows/s., 1.81 GB/s.)

Are there any approximations involved here?  How can we get precision if it is so?

Attached a text file with the query outputs for readability.

[clickhouse_inconsistent.txt](https://github.com/yandex/ClickHouse/files/528670/clickhouse_inconsistent.txt)

**Comment by vikaasbv** [comment]
After searching through the net, I found the below link in the github test cases

https://github.com/yandex/ClickHouse/blob/master/dbms/tests/queries/0_stateless/00350_count_distinct.sql

The test case mentions several options for a setting called "count_distinct_implementation", one of which is "uniqExact".  When this setting is used, the query takes quite a while, but seems to return the expected result.

**Comment by alexey-milovidov** [comment]
Documentation on differenct `uniq`* functions is here:
https://clickhouse.yandex/reference_en.html#uniq(x)

`COUNT(DISTINCT)` and `count_distinct_implementation` setting was added recently and are not documented. But behaviour is straighforward: COUNT(DISTINCT) acts as corresponding `count_distinct_implementation`.

About different implementations:

`uniqExact` is calculating number of distinct values exactly.
`uniq` is most efficient implementation, gives approximate result of reasonable quality.
`uniqCombined` gives about 3 times better quality than `uniq` as far as I remember, with little performance penalty.

`uniqCombinedRaw`, `uniqCombinedLinearCounting`, `uniqCombinedBiasCorrected` - these functions are only intended for tuning of `uniqCombined` function. Not for end user.

`uniqHLL12` - specialized function with no clear advantages over `uniq`, `uniqCombined`. Exists for support for data structure of some tool outside of ClickHouse.

**Comment by alexey-milovidov** [comment]
Comments in code will be eventually translated to english.

**Comment by vikaasbv** [comment]
Thanks for the detailed explanation.  I have verified the settings and the behaviour with uniqCombined seems to be less accurate (more deviation from the exact result) in my use case. I suppose it may be due to the nature of the approximation techniques.

:) SET count_distinct_implementation = 'uniq';

SET count_distinct_implementation = 'uniq'

Ok.

0 rows in set. Elapsed: 0.000 sec.

:) select count(distinct id) from cdr;

SELECT countDistinct(id)
FROM cdr

┌──uniq(id)─┐
│ 531654647 │
└───────────┘

1 rows in set. Elapsed: 1.046 sec. Processed 527.67 million rows, 2.11 GB (504.33 million rows/s., 2.02 GB/s.)

:) SET count_distinct_implementation = 'uniqExact';

SET count_distinct_implementation = 'uniqExact'

Ok.

0 rows in set. Elapsed: 0.000 sec.

:) select count(distinct id) from cdr;

SELECT countDistinct(id)
FROM cdr

┌─uniqExact(id)─┐
│     527670245 │
└───────────────┘

1 rows in set. Elapsed: 32.049 sec. Processed 527.67 million rows, 2.11 GB (16.46 million rows/s., 65.86 MB/s.)

:) SET count_distinct_implementation = 'uniqCombined';

SET count_distinct_implementation = 'uniqCombined'

Ok.

0 rows in set. Elapsed: 0.052 sec.

:) select count(distinct id) from cdr;

SELECT countDistinct(id)
FROM cdr

┌─uniqCombined(id)─┐
│        558881454 │
└──────────────────┘

1 rows in set. Elapsed: 3.379 sec. Processed 527.67 million rows, 2.11 GB (156.15 million rows/s., 624.59 MB/s.)

**Comment by alexey-milovidov** [comment]
uniqCombined should be more accurate in most cases, but in some cases it could be less.
