### ISSUE TITLE
Cleanup the issue tracker

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#1359]
Hello,

I noticed that when bugs are fixed the tasks where was reported are no longer closed. Also there are very old discussions that better sits on the groups not on the issue tracker.

I created a list with those maybe somebody will be interested to review and close them. The issue tracker already has over 234 opened issue now.

**Bugs already fixed**

https://github.com/yandex/ClickHouse/issues/38
https://github.com/yandex/ClickHouse/issues/43
https://github.com/yandex/ClickHouse/issues/214
https://github.com/yandex/ClickHouse/issues/566
https://github.com/yandex/ClickHouse/issues/790
https://github.com/yandex/ClickHouse/issues/912
https://github.com/yandex/ClickHouse/issues/1092

**No feedback from reporter:**

https://github.com/yandex/ClickHouse/issues/425

**Old discussions:**

https://github.com/yandex/ClickHouse/issues/815
https://github.com/yandex/ClickHouse/issues/14
https://github.com/yandex/ClickHouse/issues/11
https://github.com/yandex/ClickHouse/issues/21
https://github.com/yandex/ClickHouse/issues/57
https://github.com/yandex/ClickHouse/issues/64
https://github.com/yandex/ClickHouse/issues/74
https://github.com/yandex/ClickHouse/issues/109
https://github.com/yandex/ClickHouse/issues/112
https://github.com/yandex/ClickHouse/issues/158
https://github.com/yandex/ClickHouse/issues/569
https://github.com/yandex/ClickHouse/issues/580
https://github.com/yandex/ClickHouse/issues/770

**Questions that better sits on mail group**

https://github.com/yandex/ClickHouse/issues/527
https://github.com/yandex/ClickHouse/issues/528
https://github.com/yandex/ClickHouse/issues/532
https://github.com/yandex/ClickHouse/issues/538
https://github.com/yandex/ClickHouse/issues/542

**Comment by alexey-milovidov** [comment]
I have closed some tasks, but it is still far from being clean.
