### ISSUE TITLE
inconsistent default values in array

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#1373]
For a column of type : Array(Nullable(Float64)) the default value is considered 0 and not NULL

For example if you do:

```sql
SELECT array_field[4]  from table
```

where that element on that index is not existing you receive 0 instead NULL. 

From documentation doesn't seems to be a bug but it's not a consistent behavior.

What I mean is the default for Nullable(Float64) fields is NULL, for Float64 is 0 and for Array(Nullable(Float64)) it's also 0 not NULL as you are expecting.

**Comment by alexey-milovidov** [comment]
Fixed in master.
