### ISSUE TITLE
custom partition Exception

### ISSUE THREAD

**Issue by domsia** [yandex/ClickHouse#1376]
Custom partition is a very important feature for me. So I updated ch and  created a table by custom partition. But ch server is down for some reason. When I restart CH.Exception come add told me that I have used invalid partition. I add . ` set experimental_merge_tree_allow_custom_partitions=1` before table metadata, it also not work.  Does it has another way to start my ch server ?

**Comment by ztlpn** [comment]
Hi @domsia ! First, I must repeat the warning found in the source code: custom partitions are not ready for production yet! The data and metadata formats will change in the future and the future server versions WILL NOT be able to load tables created with the current version.

With that in mind, I would be very grateful if you experiment with the feature and provide feedback on how it fits your use case. To allow creating and attaching tables with custom partitions you should enable `experimental_merge_tree_allow_custom_partitions` for the `default` user profile in the `users.xml` server config file.

**Comment by domsia** [comment]
Thank you for solving the problem. I have started my ch server by hands. I deleted the table's metadata  SQL and started the server. After that, I set the `experimental_merge_tree_allow_custom_partitions` and attached table by hands. It works too.
