### ISSUE TITLE
build error on ubuntu 17.04 and ubuntu 17.10

### ISSUE THREAD

**Issue by snowzjy** [yandex/ClickHouse#1378]
Hi!

When I build the source code on Ubuntu 17.04 and 17.10, use the commands:
cmake .. -DCMAKE_CXX_COMPILER=`which g++-6` -DCMAKE_C_COMPILER=`which gcc-6`
make -j $(nproc || sysctl -n hw.ncpu || echo 2)

I got the error below:
/usr/bin/cmake: symbol lookup error: /usr/lib/x86_64-linux-gnu/libxml2.so.2: undefined symbol: gzclose
contrib/libzlib-ng/CMakeFiles/example.dir/build.make:95: recipe for target 'contrib/libzlib-ng/example' failed
make[2]: *** [contrib/libzlib-ng/example] Error 127
CMakeFiles/Makefile2:1245: recipe for target 'contrib/libzlib-ng/CMakeFiles/example.dir/all' failed
make[1]: *** [contrib/libzlib-ng/CMakeFiles/example.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

How can I  build it succes on ubuntu 17?
If anyone can replay this issues, I will be very grateful!
supplement：
I build clickhouse*.deb success.

**Comment by proller** [comment]
looks like its your /usr/bin/cmake problem, try to reinstall or update.

**Comment by alexey-milovidov** [comment]
You can try current master.
