### ISSUE TITLE
Formats and quoting of ints/strings/array columns

### ISSUE THREAD

**Issue by filimonov** [yandex/ClickHouse#1392]
There are certain inconsistency in a way how clickhouse reads / writes arrays (and nested columns) for TabSeparated format. It make problematic to build a client which should automatically parse server output.

DROP TABLE IF EXISTS test_table;

CREATE TABLE test_table ( str_field String, int_field UInt32, str_array_field Array(String),  int_array_field Array(UInt32) ) ENGINE = Memory;

INSERT INTO test_table(str_field, str_array_field, int_array_field) VALUES ('[]',[],[]);
INSERT INTO test_table(str_field, int_array_field) VALUES ('[1,2,3]',[1,2,3]);
INSERT INTO test_table(str_field, str_array_field) VALUES ('["1","2","3"]',['1','2','3']);
INSERT INTO test_table(str_field, str_array_field) VALUES ('[\'1\',\'2\',\'3\']',['1','2','3']);

SELECT str_field, str_array_field, int_array_field  FROM test_table FORMAT TSV
[]	[]	[]
[1,2,3]	[]	[1,2,3]
["1","2","3"]	['1','2','3']	[]
[\'1\',\'2\',\'3\']	['1','2','3']	[]

SELECT str_field, str_array_field, int_array_field FROM test_table FORMAT CSV

"[]","[]","[]"
"[1,2,3]","[]","[1,2,3]"
"[""1"",""2"",""3""]","['1','2','3']","[]"
"['1','2','3']","['1','2','3']","[]"

So the client should be schema-aware to parse the output, or use JSON formats (which work properly with arrays).

AFAIK you use TabSeparated in your clients. How do you solve that ambiguity?

Also there is a nasty behaviour of clickhouse when reading VALUES or arrays in TSV/CSV for insert:
it REQUIRES strings to be quoted, and numbers to be unquoted.

So 
INSERT INTO test_table(int_field) VALUES ('1'); # dies in VALUES format, but ok in TSV/CSV format
INSERT INTO test_table(str_field) VALUES (1);   # dies in VALUES format, but ok in TSV/CSV format 
INSERT INTO test_table(str_array_field) VALUES ([1,2,3]); # not work (also in TSV, CSV format)
INSERT INTO test_table(int_array_field) VALUES (['1','2','3']); # not work (also in TSV, CSV format)

So for languages without strict types it's hard to decide what to do with stuff which looks numeric, without knowing the schema. The rule - always quote everything which look numeric not works when inserting to Int fields, and the opposite - always leave numerics unquoted - not works when inserting numeric-looking data to String fields. And it's looks like overkill to be schema-aware to make an insert.

Again it looks like the safest is JSONEachRow - at least it allows numbers to be quoted (but not allows to have unquoted numbers when inserting them to a string field).

**Comment by ludv1x** [comment]
> So the client should be schema-aware to parse the output

Yes, of course.
Plain CSV and TSV formats are not intended to be interpreted uniquely without schema info. 
So, either you use plain formats and maintain the schema or you use complex JSON format with the built-in schema.
Also, there is an option to use `TSVWithNamesAndTypes` format which is simple `TSV`, but add a header with type names.

> dies in VALUES format, but ok in TSV/CSV format

In fact, VALUES is not a format, but a part of strict SQL syntax, so integers must be unquoted.
Whereas CSV is a more free format, it doesn't support any types except strings and allows values to be quoted even there no special symbols inside the value.

> AFAIK you use TabSeparated in your clients. How do you solve that ambiguity?
JDBC dirver, for example, uses `TabSeparatedWithNamesAndTypes` format.

**Comment by filimonov** [comment]
Ok, that's clear.  I'll look in JDBC driver source. 

About quoting - for example MySQL doesn't have such a restrictions, and it easier to make correct syntax when inserting data. 

It's not a priority, but may be such a 'loose' mode for inserting (with automatic typecasing) like in Mysql can be useful sumetimes.

```
# in Mysql
mysql> CREATE TABLE `insert_test` (
    ->   `int_field` int unsigned,
    ->   `str_field` varchar(100)
    -> ) ENGINE=MyISAM DEFAULT CHARSET=utf8 ;
Query OK, 0 rows affected (0.00 sec)

mysql> insert into insert_test(int_field) values (1),("2"),('3');
Query OK, 3 rows affected (0.00 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> insert into insert_test(str_field) values ("1"),(2),(3.00);
Query OK, 3 rows affected (0.00 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> select * from insert_test;
+-----------+-----------+
| int_field | str_field |
+-----------+-----------+
|         1 | NULL      |
|         2 | NULL      |
|         3 | NULL      |
|      NULL | 1         |
|      NULL | 2         |
|      NULL | 3.00      |
+-----------+-----------+
6 rows in set (0.00 sec)
```
