### ISSUE TITLE
Constant value in SELECT statement should not be treated as a real column

### ISSUE THREAD

**Issue by tdingus** [yandex/ClickHouse#1396]
I have a table which has 230.03 thousand rows for the time frame below:

  SELECT count(*) FROM profiler.iface WHERE (time >= 1508520600) AND (time < 1508520900) GROUP BY interface
  28 rows in set. Elapsed: 0.011 sec. Processed 230.03 thousand rows, 6.33 MB (20.22 million rows/s., 556.20 MB/s.)

However, if I add a column of constant value, the processed rows becomes huge and the results seem to be wrong!
  SELECT 1508520600 AS time, count(*) FROM profiler.iface WHERE (time >= 1508520600) AND (time < 1508520900) GROUP BY interface
  87 rows in set. Elapsed: 7.553 sec. Processed 2.48 billion rows, 57.72 GB (328.88 million rows/s., 7.64 GB/s.)

Below is some discussion on google group: https://groups.google.com/forum/#!topic/clickhouse/3E-VPzhSWqI

**Comment by ludv1x** [comment]
Aliases have higher priority than column names.
At least MySQL does the same http://sqlfiddle.com/#!9/a6c585/17907
