### ISSUE TITLE
Ошибка visitParamExtractFloat - Cannot parse NaN

### ISSUE THREAD

**Issue by PsychodelEKS** [yandex/ClickHouse#1400]
Проблема с visitParamExtractFloat при попытке достать параметр со значением null - падает в ошибку 
`Cannot parse NaN`

Пример:
`select visitParamExtractFloat('{"myparam":null}', 'myparam') AS myparam_float`

Приходится делать так:
`select toFloat64OrZero(visitParamExtractRaw('{"myparam":null}', 'myparam')) AS myparam_float`

Судя по доке:
`Распарсить UInt64 из значения поля с именем name. Если поле строковое - попытаться распарсить число из начала строки. Если такого поля нет, или если оно есть, но содержит не число, то вернуть 0.`
Должно работать

Инфо:
```
VERSION_FULL	ClickHouse 1.1.54292
VERSION_DESCRIBE	v1.1.54292-testing
BUILD_DATE	2017-09-26
BUILD_TYPE	RELWITHDEBINFO
SYSTEM	Linux-3.18.35-35.1
SYSTEM_PROCESSOR	x86_64
LIBRARY_ARCHITECTURE	x86_64-linux-gnu
CMAKE_VERSION	3.5.1
C_COMPILER	/usr/bin/gcc-6
C_COMPILER_VERSION	6.2.0
CXX_COMPILER	/usr/bin/g++-6
```

**Comment by PsychodelEKS** [comment]
`visitParamExtractInt` работает как надо, кстати.

**Comment by alexey-milovidov** [comment]
7a15be8e6
