### ISSUE TITLE
SSL configuration for Kafka engine

### ISSUE THREAD

**Issue by leoluk** [yandex/ClickHouse#1402]
Connecting to a SSL-secured broker requires the following librdkafka settings:

- `security.protocol=ssl`
- `ssl.ca.location=/path/to/broker.ca`
- `ssl.certificate.location=/path/to/client_cert.pem`
- `ssl.key.location=/path/to/client_cert.key`

**Comment by leoluk** [comment]
@vavrusa 

Thank you for implementing the Kafka engine! :)

**Comment by silviucpp** [comment]
This PR was merged. Bug should be closed

**Comment by leoluk** [comment]
No, this is a separate feature request.

**Comment by vavrusa** [comment]
I wonder where should this configuration go, using SETTINGS is not going to be pretty (especially when you create multiple tables all using the same broker), so either:
* an additional ENGINE parameter with a tuple of SSL settings
* an additional ENGINE parameter with a string of librdkafka (or JSON) settings
* an additional ENGINE parameter with a file containing librdkafka settings

**Comment by leoluk** [comment]
> an additional ENGINE parameter with a file containing librdkafka settings

That's what I would do, just put all broker settings in a XML configuration file just as with external dictionaries, and then reference them in the ENGINE config. That will make them easy to re-use and modify.
