### ISSUE TITLE
Segfault in clickhouse-client (Alt+X)

### ISSUE THREAD

**Issue by tsionyx** [yandex/ClickHouse#1405]
clickhouse-client fails with segmentation fault on pressing various Alt+X keys combination, e.g. Alt-A, Alt-V, Alt-ArrowUp, Alt-ArrowRight:

```bash
$ clickhouse-client 
ClickHouse client version 1.1.54292.
Connecting to localhost:9000.
Connected to ClickHouse server version 1.1.54292.

:) <Alt-A pressed> Segmentation fault
$ echo $?
139
$ cat /etc/os-release  | grep PRETTY
PRETTY_NAME="Ubuntu 16.04.3 LTS"
```

**Comment by ludv1x** [comment]
The problem was fixed in `ClickHouse 1.1.54304`.

BTW `Page Down` led to Segfault in `1.1.54292` also -)
