### ISSUE TITLE
Enum resolution fails sometimes

### ISSUE THREAD

**Issue by ipostelnik** [yandex/ClickHouse#1411]
I have a column with Enum8 type `Enum8('unknown' = -1, 'invalid' = 0, 'valid' = 1)`. On one of the nodes querying this table fails with error:

```
DB::Exception: Unknown element 'invalid' for type Enum8('unknown' = -1, 'invalid' = 0, 'valid' = 1).
```

The same query works fine on other nodes.

**Comment by vavrusa** [comment]
Table was created on v1.1.54290

**Comment by ipostelnik** [comment]
Restarting the affected node corrected the problem. Still I would like to know how it got into bad state.

**Comment by alexey-milovidov** [comment]
Fixed in master.
