### ISSUE TITLE
ReplicatedMergeTree Exception: resource temporarily unavaliable

### ISSUE THREAD

**Issue by wusihang** [yandex/ClickHouse#1435]
hello,guys
   I intended to create a table with ReplicatedMergeTree . At first , I had a sql syntax error , so I got an error. But After I fixed my sql  and retried, I got an error like this: "Resource temporarily unavailable".  And zookeeper node was created but I cannot find table's data dictionary at clickhouse server.
because of system legacy, zookeeper version is 3.4.5. But before this issue happened, everything is just fine.  clickhouse version is 1.1.54284 , compiled with centos 6
Here is my sql : 
##########################################
CREATE TABLE tencent_log.tencent_slow_count_log (
  stat_day Date,       
  host String,
  stat_time Int64, 
  province Int32, 
  isp Int32,  
  threshold Int32, 
  slow_count Int64, 
  all_count Int64
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/tencent_slow_count_log','{replica}',
  stat_day,
  (stat_time, threshold),
  8192
);
#####################################
here is error log:
###########################

2017.11.02 17:26:06.677242 [ 1953 ] <Error> LeaderElection: std::exception. Code: 1001, type: std::system_error, e.what() = Resource temporarily unavailable
2017.11.02 17:26:06.692913 [ 1952 ] <Error> void DB::ReplicatedMergeTreeRestartingThread::run(): std::exception. Code: 1001, type: std::system_error, e.what() = Resource temporarily unavailable
2017.11.02 17:26:06.958645 [ 1954 ] <Error> void DB::ReplicatedMergeTreeRestartingThread::run(): std::exception. Code: 1001, type: std::system_error, e.what() = Resource temporarily unavailable
2017.11.02 17:27:06.744448 [ 1952 ] <Error> void DB::ReplicatedMergeTreeRestartingThread::run(): std::exception. Code: 1001, type: std::system_error, e.what() = Resource temporarily unavailable
2017.11.02 17:27:07.034000 [ 1954 ] <Error> void DB::ReplicatedMergeTreeRestartingThread::run(): std::exception. Code: 1001, type: std::system_error, e.what() = Resource temporarily unavailable
2017.11.02 17:28:06.794469 [ 1952 ] <Error> void DB::ReplicatedMergeTreeRestartingThread::run(): std::exception. Code: 1001, type: std::system_error, e.what() = Resource temporarily unavailable
2017.11.02 17:28:07.105232 [ 1954 ] <Error> void DB::ReplicatedMergeTreeRestartingThread::run(): std::exception. Code: 1001, type: std::system_error, e.what() = Resource temporarily unavailable
2017.11.02 17:29:06.844341 [ 1952 ] <Error> void DB::ReplicatedMergeTreeRestartingThread::run(): std::exception. Code: 1001, type: std::system_error, e.what() = Resource temporarily unavailable
2017.11.02 17:29:07.160914 [ 1954 ] <Error> void DB::ReplicatedMergeTreeRestartingThread::run(): std::exception. Code: 1001, type: std::system_error, e.what() = Resource temporarily unavailable
2017.11.02 17:30:06.890647 [ 1952 ] <Error> void DB::ReplicatedMergeTreeRestartingThread::run(): std::exception. Code: 1001, type: std::system_error, e.what() = Resource temporarily unavailable
2017.11.02 17:30:07.215413 [ 1954 ] <Error> void DB::ReplicatedMergeTreeRestartingThread::run(): std::exception. Code: 1001, type: std::system_error, e.what() = Resource temporarily unavailable
2017.11.02 17:31:06.940520 [ 1952 ] <Error> void DB::ReplicatedMergeTreeRestartingThread::run(): std::exception. Code: 1001, type: std::system_error, e.what() = Resource temporarily unavailable
2017.11.02 17:31:07.265417 [ 1954 ] <Error> void DB::ReplicatedMergeTreeRestartingThread::run(): std::exception. Code: 1001, type: std::system_error, e.what() = Resource temporarily unavai
##########################################
hoping to hear from you

**Comment by wusihang** [comment]
Does clickhouse has any restriction on  number of tables with ReplicatedMerge engine?
I created approximately 300 ReplicatedMerge tables , then I couldn't create more tables with ReplicatedMerge because of  "Resource temporarily unavailable" error.  A lot of deamon process was found on my clickhouse server.

**Comment by wusihang** [comment]
Because of network traffic restriction , clickhouse server's ip was banned by ISP.

**Comment by ztlpn** [comment]
@wusihang  A cause of "resource temporarily unavailable" errors is that some system limit is exceeded. As you have created a lot of tables, the limit in question is likely either the limit on max number of open files or the limit on max number of threads (Replicated tables are quite heavy in this regard, each creating several auxiliary threads). Try increasing these and see if the problem goes away.

Creating lots of Replicated tables is usually not a good idea because after ~1000 tables performance will start to degrade.

**Comment by silviucpp** [comment]
@ztlpn this problem with "Creating lots of Replicated tables is usually not a good idea" apply only to replicated tables ? or there are other tables that follows the same approach ?

Silviu

**Comment by ztlpn** [comment]
@silviucpp It applies to other tables too (replicated tables are just the heaviest ones). Most table engines will store their data in quite a lot of files (e.g. MergeTree tables store each sorted part in a separate directory that contains 2 files per column + some more). This puts a considerable strain on the file system and you can also exceed the system limit on open files and get the same "resource temporarily unavailable" message.

Another example: for a case when you need a lot of small one-off tables there is the StripeLog engine (soon to be documented) - it is similar to TinyLog but stores all its data in just 2 files regardless of the number of columns. You can easily create hundreds of thousands of StripeLog tables.

That said, there is no hard limit on the number of tables - just be aware that creating many tables may not be the optimal design.

**Comment by silviucpp** [comment]
Number of files opened limit I'm not sure will bring too much performance penalty. You can increase the limit. But for number of threads even if you raise that limit the system will slow down a lot as also you mentioned early. 

I saw some cloud solutions for clickhouse and I was curious how they can work as time clickhouse seems was not designed for cloud usage where multiple users are sharing same servers (you end up with multiple databases and tons of tables on the same instances)

Silviu

**Comment by jackpgao** [comment]
I've got the same error, but not caused by the max open files, but the memory.

As ClickHouse uses too much page cache, but the OS is too 'lazy' to release the page cache when the free memory is too little, and with a lot of queries, the memory is out, and ClickHouse met the error 'Resource temporarily unavailabl'.

By changing the page cache release parameter can help:

on CentOS7:
```
sysctl -w vm.min_free_kbytes=10485760
```
