### ISSUE TITLE
ClickHouse Replication Issue

### ISSUE THREAD

**Issue by adhamelia** [yandex/ClickHouse#1445]
Hi @alexey-milovidov 

We have setup  7 nodes cluster for replication a week ago and the cluster run fine for few days and suddenly data insertion stopped  with continues error

2017.10.24 05:50:08.966469 [ 41 ] <Error> default.tbl_xxx (StorageReplicatedMergeTree): Code: 40, e.displayText() = DB::Exception: Checksum mismatch for uncompressed file _time.bin in data part, e.what() = DB::Exception. Data after merge is not byte-identical to data on another replicas. There could be several reasons: 1. Using newer version of compression library after server update. 2. Using another compression method. 3. Non-deterministic compression algorithm (highly unlikely). 4. Non-deterministic merge algorithm due to logical error in code. 5. Data corruption in memory due to bug in code. 6. Data corruption in memory due to hardware issue. 7. Manual modification of source data after server startup. 8. Manual modification of checksums stored in ZooKeeper. We will download merged part from replica to force byte-identical result.

no idea why it behaves weird. rebooted entire cluster and started working but it does not sound a good solution to reboot the cluster.

**Comment by adhamelia** [comment]
guys any clue ??? still waiting for the response

**Comment by alexey-milovidov** [comment]
There could be several possible reasons (listed in exception message).
ClickHouse should download correct part from replica and solve the issue automatically.

If you are using quite old ClickHouse release, it's recommended to update to the latest stable.

**Comment by priyank43** [comment]
Hi,
We have installed the latest version for clickhouse **1.1.54327** but still found same issue, data insertions is stooped working, kindly find the error log and please provide the solution that what to do next?


Clickouse Error:

18.02.07 02:13:56.001450 [ 29 ] <Error> DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 40, e.displayText() = DB::Exception: Checksum mismatch for uncompressed file _time.bin in data part, e.what() = DB::Exception, Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x320c466]
1. clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x1f) [0x149501f]
2. clickhouse-server(DB::MergeTreeDataPartChecksum::checkEqual(DB::MergeTreeDataPartChecksum const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const+0xea) [0x339f9aa]
3. clickhouse-server(DB::MergeTreeDataPartChecksums::checkEqual(DB::MergeTreeDataPartChecksums const&, bool) const+0xb7) [0x339fc67]
4. clickhouse-server(DB::StorageReplicatedMergeTree::checkPartAndAddToZooKeeper(std::shared_ptr<DB::MergeTreeDataPart const> const&, std::vector<std::unique_ptr<zkutil::Op, std::default_delete<zkutil::Op> >, std::allocator<std::unique_ptr<zkutil::Op, std::default_delete<zkutil::Op> > > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)+0x85c) [0x330411c]
5. clickhouse-server(DB::StorageReplicatedMergeTree::fetchPart(std::_cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, unsigned long)+0x4a0) [0x33104d0]
6. clickhouse-server(DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry const&)+0x13a3) [0x3312553]
7. clickhouse-server() [0x3314f3f]
8. clickhouse-server(DB::ReplicatedMergeTreeQueue::processEntry(std::function<std::shared_ptr<zkutil::ZooKeeper> ()>, std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::function<bool (std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>)+0x3e) [0x33ccf0e]
9. clickhouse-server(DB::StorageReplicatedMergeTree::queueTask()+0x16b) [0x32fb8ab]
10. clickhouse-server(DB::BackgroundProcessingPool::threadFunction()+0x467) [0x33469f7]
11. clickhouse-server() [0x412dc6f]
12. /lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x7f92377a2184]
13. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f9236dbd37d]

2018.02.07 02:13:56.023008 [ 16 ] <Error> DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 40, e.displayText() = DB::Exception: Checksum mismatch for uncompressed file _time.bin in data part, e.what() = DB::Exception, Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x320c466]
1. clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x1f) [0x149501f]
2. clickhouse-server(DB::MergeTreeDataPartChecksum::checkEqual(DB::MergeTreeDataPartChecksum const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const+0xea) [0x339f9aa]
3. clickhouse-server(DB::MergeTreeDataPartChecksums::checkEqual(DB::MergeTreeDataPartChecksums const&, bool) const+0xb7) [0x339fc67]
4. clickhouse-server(DB::StorageReplicatedMergeTree::checkPartAndAddToZooKeeper(std::shared_ptr<DB::MergeTreeDataPart const> const&, std::vector<std::unique_ptr<zkutil::Op, std::default_delete<zkutil::Op> >, std::allocator<std::unique_ptr<zkutil::Op, std::default_delete<zkutil::Op> > > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)+0x85c) [0x330411c]
5. clickhouse-server(DB::StorageReplicatedMergeTree::fetchPart(std::_cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, unsigned long)+0x4a0) [0x33104d0]
"clickhouse-server.err.log" 2000353L, 331905731C 1,1 Top
