### ISSUE TITLE
Corrupted data in system.columns

### ISSUE THREAD

**Issue by SaltTan** [yandex/ClickHouse#1448]
1.1.54292
I issued a 'detach partition' query without knowing that a merge on that partition was running at that time.
My query waited for the merge to finish and then completed successfully.
Later I noticed error messages like this in log files:
`<Error> <table_name> (Data): Possibly incorrect subtraction: 7621 - 170117 = 18446744073709389120, variable <column_name>.bin.file_size`
It turned out that the data in system.columns was corrupted for this table.
All three columns with data sizes contained huge numbers for all table columns (like 18446744073709389120).
I detached the table and attached it back.
[Possibly_incorrect_subtraction.log](https://github.com/yandex/ClickHouse/files/1442036/Possibly_incorrect_subtraction.log)

**Comment by alexey-milovidov** [comment]
Does it reproduce in recent versions of ClickHouse?

**Comment by SaltTan** [comment]
That was the only time I saw corrupted data in system.columns.
But I have never tried to reproduce this, and I don't manipulate partitions very often.
We are on 1.1.54385 at the moment, 18.12 is in testing.
