### ISSUE TITLE
FR: change primary key

### ISSUE THREAD

**Issue by fasterharder** [yandex/ClickHouse#147]
Hello!
It would be nice to have support for change of columns included in primary key. 
Now we have to create a new table, copy the data to it using the INSERT SELECT, rename table to the old name. It can takes a lot of time.

**Comment by f1yegor** [comment]
I think it's by design, because data layout/sorted differently when primary key changes.

**Comment by alexey-milovidov** [comment]
There are several implementation possibilities:

1. Allow to modify primary key if it cannot modify order of data (example: adding a column to end of primary key);

2. Allow to modify primary key if it actually does not modify order of data (perform check for that);

3. Allow to modify primary key for new parts, but leave primary key in existing parts as is. Allowing to have different primary keys in different parts of table is theoretically possible, but introduce many difficulties in query execution.

4. Allow to modify primary key and perform non-blocking sorting of whole table in background.

We are not going to implement it right now.

**Comment by pavel-odintsov** [comment]
Hello!

Any updates about it?

**Comment by filimonov** [comment]
In common case changing PK is not possible (data reordering will require the same amount of work as recreate the table with another PK and copy data to it). 

There is support for some very special case (feature not documented because it's too specific). See https://github.com/yandex/ClickHouse/issues/2210#issuecomment-380482697 

You can use it at your own risk if that is it fits your case, or just create new table with another PK and copy data to it.

**Comment by shadowDy** [comment]
Hello!

Do you have any updates about it now?

**Comment by alexey-milovidov** [comment]
@shadowDy Yes. We selected the №3 way of implementation:
```
Allow to modify primary key for new parts, but leave primary key in existing parts as is. Allowing to have different primary keys in different parts of table is theoretically possible, but introduce many difficulties in query execution.
```

Currently this feature is in design stage by @amosbird.

**Comment by malikas05** [comment]
Hi @alexey-milovidov. Where is it possible to track the progress of the development of this feature?

> @shadowDy Yes. We selected the №3 way of implementation:
> 
> > Allow to modify primary key for new parts, but leave primary key in existing parts as is. Allowing to have different primary keys in different parts of table is theoretically possible, but introduce many difficulties in query execution.
> 
> Currently this feature is in design stage by @amosbird.

**Comment by alexey-milovidov** [comment]
@amosbird Started to implement it.
