### ISSUE TITLE
"Segmentation fault (11)" cause server down

### ISSUE THREAD

**Issue by wusihang** [yandex/ClickHouse#1475]
we insert data into a non-exist replicatedMergeTree table continuously ( because of incorrect table name in java code ).
After a lot of  "table doesn't exist " error , server logs a Segmentation fault(11) and goes down. After about 20 minutes , server auto restart. 
can you tell me why this issue happened? 
（clickhouse version is 1.1.54284 , compiled with centos 6）
BTW, can you provide a FAQ list in official documents?
here is the log detail: 
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2017.11.08 20:27:09.574348 [ 606 ] <Error> BaseDaemon: ########################################
2017.11.08 20:27:09.574382 [ 606 ] <Error> BaseDaemon: (from thread 596) Received signal Segmentation fault (11).
2017.11.08 20:27:09.574396 [ 606 ] <Error> BaseDaemon: Address: NULL pointer.
2017.11.08 20:27:09.582123 [ 606 ] <Error> BaseDaemon: 0. clickhouse-server(tcmalloc::ThreadCache::ReleaseToCentralCache(tcmalloc::ThreadCache::FreeList*, unsigned long, int)+0xe3) [0x30151c3]
2017.11.08 20:27:09.582153 [ 606 ] <Error> BaseDaemon: 1. clickhouse-server(tcmalloc::ThreadCache::Scavenge()+0x40) [0x3015320]
2017.11.08 20:27:09.582167 [ 606 ] <Error> BaseDaemon: 2. clickhouse-server(tc_delete_nothrow+0x386) [0x35de486]
2017.11.08 20:27:09.582184 [ 606 ] <Error> BaseDaemon: 3. clickhouse-server(Poco::Net::HTTPServerConnection::~HTTPServerConnection()+0x2f8) [0x33a22e8]
2017.11.08 20:27:09.582200 [ 606 ] <Error> BaseDaemon: 4. clickhouse-server(Poco::Net::HTTPServerConnection::~HTTPServerConnection()+0x11) [0x33a2731]
2017.11.08 20:27:09.582215 [ 606 ] <Error> BaseDaemon: 5. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x15d) [0x339d50d]
2017.11.08 20:27:09.582230 [ 606 ] <Error> BaseDaemon: 6. clickhouse-server(Poco::PooledThread::run()+0xa7) [0x34b3327]
2017.11.08 20:27:09.582245 [ 606 ] <Error> BaseDaemon: 7. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x96) [0x34ad9f6]
2017.11.08 20:27:09.582258 [ 606 ] <Error> BaseDaemon: 8. /lib64/libpthread.so.0() [0x3af0c07aa1]
+++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by blinkov** [comment]
I've tried to reproduce this on recent ClickHouse release and the server works fine. If you know how to do it, please let us know.

> BTW, can you provide a FAQ list in official documents?
We've just recently created it and it's practically empty at the moment https://clickhouse.yandex/docs/en/faq/general/ , but it'll change with time.
