### ISSUE TITLE
Provide SQL formatter with clickhouse-client

### ISSUE THREAD

**Issue by bobrik** [yandex/ClickHouse#1480]
We're adding an alert to catch schema inconsistencies between instances. To do that, we hash all files in `metadata` and check if there are more than on hash for every file. This allowed us to find a couple of tables that missed `DROP COLUMN` migration in the past.

The problem is that just hashing is not sufficient. After the recent upgrade Clickhouse now adds an extra newline before `ENGINE` line.

* Before:

```
$ cat /disk/data/clickhouse/foo/metadata/open/requests_1m_uniques.sql
ATTACH TABLE requests_1m_uniques
(
    date Date,
    timeslot DateTime,
    uniques AggregateFunction(uniqHLL12, UInt32, FixedString(16))
) ENGINE = Distributed('foo', '', 'requests_1m_uniques', rand())
```

* After:

```
$ cat /disk/data/clickhouse/foo/metadata/open/requests_1m_uniques.sql
ATTACH TABLE requests_1m_uniques
(
    date Date,
    timeslot DateTime,
    uniques AggregateFunction(uniqHLL12, UInt32, FixedString(16))
)
ENGINE = Distributed('foo', '', 'requests_1m_uniques', rand())
```

It'd be nice if Clickhouse could provide a tool analogous to `gofmt`, so we can compare hashes of canonical versions of SQL. There's nice output in `clickhouse-client` already, so reusing that seems the most obvious to me:

```
:) select table, max(elapsed) as max_elapsed from system.merges group by table

SELECT
    table,
    max(elapsed) AS max_elapsed
FROM system.merges
GROUP BY table
```

If there's a better way to catch inconsistencies, I'm open to that as well. Checking Zookeeper does not work, because it doesn't know at least about `Distributed` tables.

**Comment by alexey-milovidov** [comment]
We can provide `clickhouse format-query` mode of operation for clickhouse binary.

**Comment by alexey-milovidov** [comment]
https://github.com/yandex/ClickHouse/commit/726301572f2e0de5335cdd2c071e0a912c282ec4

```
$ ./clickhouse format --help
Usage: ./clickhouse [options] < query
Allowed options:
  -h [ --help ]         produce help message
  --hilite              add syntax highlight with ANSI terminal escape 
                        sequences
  --oneline             format in single line
  -q [ --quiet ]        just check syntax, no output on success

$ ./clickhouse format <<< "ATTACH TABLE requests_1m_uniques ( date Date, timeslot DateTime, uniques AggregateFunction(uniqHLL12, UInt32, FixedString(16)) ) ENGINE = Distributed('foo', '', 'requests_1m_uniques', rand())"
ATTACH TABLE requests_1m_uniques
(
    date Date, 
    timeslot DateTime, 
    uniques AggregateFunction(uniqHLL12, UInt32, FixedString(16))
)
ENGINE = Distributed('foo', '', 'requests_1m_uniques', rand())
```

**Comment by bobrik** [comment]
Awesome, thanks!
