### ISSUE TITLE
Arbitrary partitioning key for MergeTree engine family

### ISSUE THREAD

**Issue by badvir** [yandex/ClickHouse#1482]
ClickHouse's partitioning key is fixed in month.
I want to create a partition key on a day basis.
Is it possible after Q4 2017?

**Comment by ztlpn** [comment]
It is possible right now! (starting from the 54310 release)

Documentation is under development now, but here are a few examples in tests:
https://github.com/yandex/ClickHouse/blob/master/dbms/tests/queries/0_stateless/00502_custom_partitioning_local.sql
https://github.com/yandex/ClickHouse/blob/master/dbms/tests/queries/0_stateless/00502_custom_partitioning_replicated_zookeeper.sql
