### ISSUE TITLE
Problems about clang-format

### ISSUE THREAD

**Issue by sundy-li** [yandex/ClickHouse#1492]
Hi, I use `clang-format` to format code with the config file `.clang-format`,but it did not work as expected.

Because I develop c++ in Mac,and I did not use KDevelop, I use this script to test clang-format 

```
 cat dbms/src/Storages/ColumnDefault.cpp | clang-format -style=file  -assume-filename=`pwd`/.clang-format   > dbms/src/Storages/ColumnDefault.cpp
```
But `git diff` shows I modified the file `ColumnDefault.cpp`.
My clang-format version is 
```
➜  ClickHouse git:(master) ✗ clang-format --version
clang-format version 5.0.0 (tags/google/stable/2017-06-22)
```

I also pasted the `.clang-format` config content to my Qt Creator format config , and it was the same problem as above. So I wondered about how to fix it.

**Comment by alexey-milovidov** [comment]
When you type
```
cat file | command > file
```
in your shell,
the shell first opens `file` for writing and truncates it (the `>` redirection) and when `cat` opens the same file for reading, it is already empty.

This has no relation to `clang-format`.

To test clang-format, simply type:
```
clang-format dbms/src/Storages/ColumnDefault.cpp
```

**Comment by alexey-milovidov** [comment]
Please not that our files are formatted a little different than `clang-format` will do:
We carefully place newlines for long fargument lists, long template parameters, ?: operator, etc.

Clang-format config is almost 100% correspond to our style and you can simply use clang-format for new files added by you. But for existing files, it's better to only reformat your modifications.

**Comment by alexey-milovidov** [comment]
If you are feeling fine to use the most fresh clang version, I would recommend to take a look to the scripts `git-clang-format`, `clang-format-diff`, etc. inside `clang/tools/clang-format` directory:

```
git clone git@github.com:llvm-project/llvm-project-20170507.git
cd llvm-project-20170507
mkdir build && cd build

CC=clang CXX=clang++ cmake -D LLVM_TARGETS_TO_BUILD='X86' -D LLVM_ENABLE_PROJECTS='clang;lld;polly' -D CMAKE_BUILD_TYPE=Release -D CMAKE_CXX_FLAGS='-D_GLIBCXX_USE_CXX11_ABI=1' ../llvm

make -j $THREADS
sudo make install
```

**Comment by sundy-li** [comment]
Got that , thanks
