### ISSUE TITLE
extractAll stops extracting after extracting empty string

### ISSUE THREAD

**Issue by filimonov** [yandex/ClickHouse#1493]
Unfortunately JSON support for clickhouse is quite limited - you can't enumerate json keys, nor extract value by non-static json-key name. So i'm trying to get key-value pairs by processing json with regexp and later processing arrays. 

Now i find that extractAll stops extracting data after extracting first empty string.

Sample:
```
SELECT version()

┌─version()─┐
│ 1.1.54304 │
└───────────┘

1 rows in set. Elapsed: 0.002 sec. 

SELECT 
    '{"a":"1","b":"2","c":"","d":"4"}' AS json, 
    extractAll(json, '"([^"]*)":') AS keys, 
    extractAll(json, ':"([^"]*)"') AS values

┌─json─────────────────────────────┬─keys──────────────┬─values────┐
│ {"a":"1","b":"2","c":"","d":"4"} │ ['a','b','c','d'] │ ['1','2'] │
└──────────────────────────────────┴───────────────────┴───────────┘

1 rows in set. Elapsed: 0.002 sec. 
```

expected values: `['1','2','','4']`

**Comment by filimonov** [comment]
Probably caused by that line: 
https://github.com/yandex/ClickHouse/blob/fb2d2d36e0ba5b616e81d38061c91eed6184ddfa/dbms/src/Functions/FunctionsStringArray.h#L308

**Comment by alexey-milovidov** [comment]
Thank you for the test case!
Fixed in https://github.com/yandex/ClickHouse/commit/14e069f7481664831cab1dce679fa47e21ff901e
