### ISSUE TITLE
New function like runningDifference with correct processing of counter reset

### ISSUE THREAD

**Issue by michep** [yandex/ClickHouse#1501]
Is there any chance to have a function linke ```runningDifference()``` which can correctly process counter reset.

Lets say I have a counter with possible values 0 to 99. Now, when I run runningDifference() on values ```94, 96, 3, 8, 14``` I will have result ```2, -93, 5, 6```, while in fact it should be ```2, 7, 5, 6```.
So new function should have additional parameter - ```max_value``` and with it equal to 100 difference should be calculated like this:
```V2 - V1 < 0 ? max_value - V1 + V2 : V2 - V1```

**Comment by filimonov** [comment]
For those type of problems modulo calculation is usually used (formula `(x + max_value) % max_value`)

Your sample:
```
:) select x, runningDifference(x) from
  (select x from system.one array join [94, 96, 3, 8, 14] as x);
┌──x─┬─runningDifference(x)─┐
│ 94 │                    0 │
│ 96 │                    2 │
│  3 │                  -93 │
│  8 │                    5 │
│ 14 │                    6 │
└────┴──────────────────────┘
```
With modulo
```
:) select x, (runningDifference(x) + 100) % 100 from
  (select x from system.one array join [94, 96, 3, 8, 14] as x);
┌──x─┬─modulo(plus(runningDifference(x), 100), 100)─┐
│ 94 │                                            0 │
│ 96 │                                            2 │
│  3 │                                            7 │
│  8 │                                            5 │
│ 14 │                                            6 │
└────┴──────────────────────────────────────────────┘
```

**Comment by filimonov** [comment]
And that requirement looks very specific, and it's very easy to solve that problem without modifications of runningDifference (as i showed), so i don't think that adding that possibility to runningDifference is really needed.

**Comment by michep** [comment]
Nice solution, thanks.
