### ISSUE TITLE
Merges are processing significantly slower than inserts

### ISSUE THREAD

**Issue by AlexPosix** [yandex/ClickHouse#1510]
Hello, after update a server and client from the version 1.1.54189. to the latest 1.1.54310, we enconuntered with an error "Too many parts (372). Merges are processing significantly slower than inserts". We have already added 
<max_bytes_to_merge_at_max_space_in_pool>107374182400</max_bytes_to_merge_at_max_space_in_pool> as mentioned in https://github.com/yandex/ClickHouse/blob/master/CHANGELOG.md. Also i increased the follow options:
from default values to
<max_insert_block_size>10000000</max_insert_block_size>
        <parts_to_delay_insert>1500</parts_to_delay_insert>
        <parts_to_throw_insert>3000</parts_to_throw_insert>
but result the same.

Our config options:
<max_connections>4096</max_connections>
<keep_alive_timeout>3</keep_alive_timeout>
<uncompressed_cache_size>8589934592</uncompressed_cache_size>
<mark_cache_size>5368709120</mark_cache_size>
<merge_tree>
<max_suspicious_broken_parts>5</max_suspicious_broken_parts>
</merge_tree>
others are default.

Hardware:
Dell R430 2.5", 6 x 16GB, 2 x 1 TB SATA 2.5"(clickhouse), 4 x 960GB SSD(system), Perc H730

Tables capacity:
┌─table──────────────────────────────┬─────GB─┐
│ table       │ 513.91 │ (CollapsingMergeTree)
│ table1           │ 462.61 │ (CollapsingMergeTree)
 | table2              │ 131.79 │(SummingMergeTree)
│ table3     │ 131.68 │ (CollapsingMergeTree)
│ table4  │   0.94 │ (CollapsingMergeTree)
│ table5     │   0.55 │ (CollapsingMergeTree)
│ query_log                          │      0 │

What we do wrong ?

**Comment by filimonov** [comment]
Do you use bulk inserts? How many separate insert statements do you execute per minute?

**Comment by vmanyushin** [comment]
Hello,

have same error after upgrade click house to 54310 build. After reading changelog add this settings to config.xml

`    <merge_tree>
        <max_bytes_to_merge_at_max_space_in_pool>107374182400</max_bytes_to_merge_at_max_space_in_pool>
    </merge_tree>
`

But it does't resolve error. Programmers say to me that this problem occur when he use bulk insert.

**Comment by AlexPosix** [comment]
filimonov thanks for reply, we do not use bulk inserts. We inserts for about 280000 per minute.

**Comment by goranc** [comment]
After upgrade server to 1.1.54310 version we encountered problem with merge speed.
The merges are much slower than on previous stable version.
There were no change in our code, batch size or anything else, and database started to refuse inserts.

I suspect that increased size of blocks to 150MB can be related. It is three times increase from previous size.

What we did to improve speed and reduce number of parts is change in parameters for database instance.
```
<yandex>
    <!-- Max insert block size set to 4x than default size 1048576 -->
    <max_insert_block_size>4194304</max_insert_block_size>
    <merge_tree>
        <parts_to_delay_insert>300</parts_to_delay_insert>
        <parts_to_throw_insert>600<parts_to_throw_insert>
        <max_delay_to_insert>2</max_delay_to_insert>
    </merge_tree>
<yandex>
```

After change we are again in sync with ingestion throughput.

g.c.

**Comment by AlexPosix** [comment]
goranc thanks, i will try in our case.

**Comment by alexey-milovidov** [comment]
We confirm, that version 54310 has the regression.
Fix is on the way.

**Comment by goranc** [comment]
For the situations like this, we need to have option to rollback upgrade of server version.

In our situation we have previous .deb packages and can install older version, but it should be more convenient to have previous stable version of packages in yandex repository.

So can you keep two latest stable versions in your repository ?

g.c.

**Comment by AlexPosix** [comment]
Before, we splited batch of inserts on 1000, this means if we get for example 80000 batch and then split on 1000, we inserted 8 batch of 1000  inserts and got an error, now we do not split, we insert full batch, and now all it's ok. Thanks.

**Comment by silviucpp** [comment]
This was fixed ?

**Comment by alexey-milovidov** [comment]
This should be fixed in the latest 1.1.54327 release,
but there is still minor chance, that small performance regression exist and we cannot catch it.

**Comment by salisbury-espinosa** [comment]
@alexey-milovidov 

> This should be fixed in the latest 1.1.54327 release,

we have the same error in `1.1.54390.` (Too many parts (300). Merges are processing significantly slower than inserts.)

**Comment by den-crane** [comment]
> i encounter this error on large request (900M lines on table2) like that :
> 
> ```
> INSERT INTO <table1> SELECT * FROM <table2>
> ```

How is your table partitioned ? By month?

**Comment by mcarbonneaux** [comment]
By day and column identifying the source serveur of the information

**Comment by shivacr** [comment]
> i encounter this error on large request (900M lines on table2) like that :
> 
> ```
> INSERT INTO <table1> SELECT * FROM <table2>
> ```

HI,
Were you able to find any solution for this?
I am facing the same problem.

Inserting into new table from old one.
old one has 440472552 entries and paritioned by date. Old table has data for 5 days.

Thanks

**Comment by den-crane** [comment]
@shivacr you can change 300 to 3000 temporarily for maintenance time. 300 it's just a limiter / alerter.
```

<yandex>
    <merge_tree>
	<parts_to_throw_insert>3000</parts_to_throw_insert>
    </merge_tree>
</yandex>
```
