### ISSUE TITLE
How to add Graph Computing Engine on the top of ClickHouse?

### ISSUE THREAD

**Issue by theseusyang** [yandex/ClickHouse#1514]
Hi team,
I have some requirements about Graph Computing, and want to use ClickHouse as an  underlying Graph DataStore. ClickHouse stored many vertex and edge information, and execute Computing using Graph Engine.

the problem is that how to integrate with a Graph Computing Engine and ClickHouse?

**Comment by alexey-milovidov** [comment]
It's dependent on what kind of graph computations do you want to execute in ClickHouse.
Let's start with any example of real task and we will look how it will be possible to adapt ClickHouse for it.

**Comment by theseusyang** [comment]
@alexey-milovidov Yes, we want to do some graph query and graph analysis like Titan or Neo4j, and also especially like  enterprise product [GraphSQL](http://www.graphsql.com/) , a table with 2 paradigms , graph and relational database.

**Comment by alexey-milovidov** [comment]
It's difficult to integrate complex graph processing directly into ClickHouse,
because ClickHouse gains its performance advantages from flat, uniform, well structured data.

I see only few possibilities:
- using ClickHouse as a storage layer for large graphs, as you can quickly fetch data from ClickHouse based on some simple condition, and perform further analysis in other engine;
- using ClickHouse for analytics on "shingles" (subpaths of N nodes in a graph) extracted from graphs: some tasks can be solved from this data model instead of real graph.

**Comment by theseusyang** [comment]
@alexey-milovidov Yes,  We are researching how to use ClickHouse as an graph storage layer, maybe We need extend the underlying Storage API to complete it.

**Comment by cesarmarinhorj** [comment]
@theseusyang is possible doing some simple experiments with graph with clickhouse? It helps in situations where there are too many edges in same node? Thanks.

**Comment by theseusyang** [comment]
yes, It is feasible that clickhouse is begarded as  a backend storage engine for distributed graph database.

**Comment by kevin1024** [comment]
https://presentations.clickhouse.com/meetup24/2.%20SQLGraph%20--%20When%20ClickHouse%20marries%20graph%20processing%20Amoisbird.pdf

**Comment by alexey-milovidov** [comment]
The professor who supervised the work by @amosbird wanted to keep the implementation private, and then it was abandoned.

**Comment by buithehien1991** [comment]
@alexey-milovidov After reading @amosbird paper, I'm very interested in a Graph Compute Engine for Clickhouse. Is there any chance this's an experimental feature in 2025 roadmap?

**Comment by TheBestOrNothing** [comment]
what is different between puppygraph and the paper? puppygraph can query ClickHouse data as a graph now.

https://docs.puppygraph.com/getting-started/querying-clickhouse-data-as-a-graph/

**Comment by michaelangeloio** [comment]
> what is different between puppygraph and the paper? puppygraph can query ClickHouse data as a graph now.
> 
> https://docs.puppygraph.com/getting-started/querying-clickhouse-data-as-a-graph/

Puppygraph isn't open source AFAIK
