### ISSUE TITLE
Non-informative exception messages while trying to use internal dictionaries

### ISSUE THREAD

**Issue by Abzac** [yandex/ClickHouse#152]
When I try to perform queries depended on internal dictionaries, I receive meaningless errors in error log by no reason and that's all I have.

```
:) select regionToName(12181, 'en');

SELECT regionToName(12181, 'en')

Received exception from server:
Code: 156. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Dictionaries was not loaded. You need to check configuration file..

0 rows in set. Elapsed: 0.688 sec.
```
Then clickhouse-server crashes silently.

```
Connecting to localhost:9000.
Code: 210. DB::NetException: Connection refused: (localhost:9000, 127.0.0.1)
```

The same behavior for

```
:) select regionToCity(980711);

SELECT regionToCity(980711)

Received exception from server:
Code: 156. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Dictionaries was not loaded. You need to check configuration file..

0 rows in set. Elapsed: 0.479 sec.
```

So, I get the same result. Please see error log message:

```
<Error> Dictionaries: Cannot load dictionary! You must resolve this manually.
```

And the same info is in the normal log file

```
...
<Debug> ConfigReloader: Loading config '/etc/clickhouse-server/config.xml'
<Debug> ConfigReloader: Loading config '/etc/clickhouse-server/users.xml'
...
<Information> Dictionaries: Loading dictionaries.
<Debug> RegionsHierarchies: Adding default regions hierarchy from /opt/geo/regions_hierarchy.txt
<Debug> RegionsHierarchy: Reloading regions hierarchy
<Error> Dictionaries: Cannot load dictionary! You must resolve this manually.
<Debug> RegionsNames: Reloading regions names
<Debug> RegionsNames: Reloading regions names for language: ru
<Error> Dictionaries: Cannot load dictionary! You must resolve this manually.
...
<Debug> MemoryTracker: Peak memory usage (for query): 1.00 MiB.
<Debug> MemoryTracker: Peak memory usage (for user): 1.00 MiB.
<Debug> MemoryTracker: Peak memory usage (total): 1.00 MiB.
<Information> TCPHandler: Processed in 0.652 sec.
<Information> Dictionaries: Loading dictionaries.
<Debug> RegionsHierarchies: Adding default regions hierarchy from /opt/geo/regions_hierarchy.txt
<Debug> RegionsHierarchy: Reloading regions hierarchy
```

However, I'm sure that I have the correct configuration and geobase files.

```
<!-- Path to file with region hierarchy. -->
<path_to_regions_hierarchy_file>/opt/geo/regions_hierarchy.txt</path_to_regions_hierarchy_file>
<!-- Path to directory with files containing names of regions -->
<path_to_regions_names_files>/opt/geo</path_to_regions_names_files>
```
I have all the files needed (I generated it myself from open sources)

```
ubuntu@ubuntu-xenial:/opt/geo$ ls -la
total 10124
drwxrwxrwx 2 root root    4096 Oct 27 12:20 .
drwxr-xr-x 5 root root    4096 Oct 26 19:43 ..
-rwxrwxrwx 1 root root 6565160 Oct 27 12:03 regions_hierarchy.txt
-rwxrwxrwx 1 root root 7689036 Oct 27 12:03 regions_names_ru.txt
```

I have correct files format. First lines of regions_hierarchy.txt (region_id, <tab>, parent_id, <tab>, type_id <newline>)

```
137123030      13040   6
124640136      12356892       6
1379136505      137432388      6
13456889      24110   6
```

And region_names.txt
```
541359        Курчатов
17468313      Villeneuve
13791073      Noepoli
9809667       Campodolcino
54138        Нижегородская область
9800331       Cordovilla La Real
9809668       Poljana
541139        Нижний Новгород
1746315      Viviers
9809669       Lostock Gralam
```

So, I dived into the code a little, because error message is totally meaningless!

In https://github.com/yandex/ClickHouse/blob/master/dbms/include/DB/Dictionaries/Embedded/RegionsNames.h we have

```
static constexpr auto required_key = "path_to_regions_names_files";
```

I have that line in my config file. Then file names generation

```
const std::string & language = getSupportedLanguages()[language_id];
std::string path = directory + "/regions_names_" + language + ".txt";
```

And I have all of them, then there is file reading in the code, and I consider I have totally correct file format

```
DB::readIntText(region_id, in);
DB::assertChar('\t', in);
DB::readString(region_name, in);
DB::assertChar('\n', in);
```

I actually have all the code in this file read and I'm pretty sure I'm doing everything right. The same is for Regions Hierarchy https://github.com/yandex/ClickHouse/blob/master/dbms/include/DB/Dictionaries/Embedded/RegionsHierarchy.h

```
RegionsHierarchy(const std::string & path_ = Poco::Util::Application::instance().config().getString("path_to_regions_hierarchy_file"))
		: path(path_), file_modification_time(0), log(&Logger::get("RegionsHierarchy"))
{
}

...

DB::readIntText(region_id, in);
DB::assertChar('\t', in);
DB::readIntText(parent_id, in);
DB::assertChar('\t', in);
DB::readIntText(type, in);
```

What was really bad in the code when I dived in deeper, is absolute exceptions suppressions from informative ones to the general one. See https://github.com/yandex/ClickHouse/blob/1d836b2bf8fef378d47258957ff74ed3a4aff136/dbms/include/DB/Interpreters/Dictionaries.h

```
	void handleException(const bool throw_on_error) const
	{
		const auto exception_ptr = std::current_exception();

		try
		{
			throw;
		}
		catch (const Poco::Exception & e)
		{
			LOG_ERROR(log, "Cannot load dictionary! You must resolve this manually. " << e.displayText());
		}
		catch (...)
		{
			LOG_ERROR(log, "Cannot load dictionary! You must resolve this manually.");
		}

		if (throw_on_error)
			std::rethrow_exception(exception_ptr);
	}
```

Moreover, in some cases it may throw that general error, and all the server silently shuts down just because some dictionaries didn't loaded for some reason! giving no information to fix it at all because of "(...)" ...

I still can't manage with this problem, load and use internal dictionaries.

**Comment by alexey-milovidov** [comment]
Thanks for the report!

You are right. Code is not good, because message for std::exception (and other exceptions not descendant of Poco::Exception) is lost. Fixed https://github.com/yandex/ClickHouse/commit/350f73da02a0a0be94bf1dee32496198a2c6f928

In your case, dictionaries could not load, because (as mentioned in documentation):
> A flat array is used for storing in RAM. For this reason, IDs shouldn't be more than a million.
https://clickhouse.yandex/reference_en.html#Internal%20dictionaries

and there is no check for it (look at RegionsHierarchy.h). 
Thus, std::bad_alloc is thrown, and you don't see the message.

**Comment by Abzac** [comment]
Thanks for your quick reply and the solution! It is really great!
