### ISSUE TITLE
Subquery accessing a memory Table gives an error.

### ISSUE THREAD

**Issue by shahvishal8464** [yandex/ClickHouse#1530]
I Have the following Schema in my database:

CREATE TABLE Stores_TBL (id Int32, Store String, eventdate Date) ENGINE = ReplicatedMergeTree('/clickhouse/tables/5-2/Stores_TBL', '192.168.0.1', eventdate, (id, Store), 8192) ;

CREATE TABLE Stores (id Int32, Store String, eventdate Date) ENGINE = Distributed(ClickHouseCluster, 'default', 'Stores_TBL') ;

 CREATE TABLE TempStores ( Store String) ENGINE = Memory ;

When I execute the Following Query I get an error:
 Select * FROM
 (
    Select id, Store
    FROM
        Stores
    WHERE
        Store IN (SELECT Store FROM TempStores)
)x FORMAT TabSeparatedWithNamesAndTypes;

**Error:**
Received exception from server:
Code: 60. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Received from 192.168.0.2:9000. DB::Exception: Table TempStores doesn't exist.. 

Whereas if I use the Replicated Merge Tree Table the query runs fine:
 Select * FROM
 (
    Select id, Store
    FROM
        Stores_TBL
    WHERE
        Store IN (SELECT Store FROM TempStores)
)x FORMAT TabSeparatedWithNamesAndTypes;

**Comment by alexey-milovidov** [comment]
Short answer: use `GLOBAL IN` instead of `IN`.
Details: https://clickhouse.yandex/docs/en/query_language/queries.html?highlight=subqueries#distributed-subqueries
