### ISSUE TITLE
How to use Clickhouse and Catboost for CTR Prediction to replace XGboost?

### ISSUE THREAD

**Issue by theseusyang** [yandex/ClickHouse#1543]
Hi team,

We are developing a CTR analysis platform, before clickhouse met, We use Greenplum and XGboost, then found clickhouse has already support built-in model e.g. catboost.

So is there a textbook-style demo for the CTR prediction application scenario using Clickhouse and Catboost?

**Comment by theseusyang** [comment]
@KochetovNicolai welcome give me the precious suggestions.

**Comment by KochetovNicolai** [comment]
Hi, I've published a short [tutorial](https://github.com/yandex/clickhouse-presentations/blob/master/tutorials/catboost_with_clickhouse_ru.md), which shows how to use trained CatBoost models in ClickHouse. It's in Russian, but I'll translate it soon.

Short retelling:
1. Trained model from [Amazon Employee Access Challenge](https://www.kaggle.com/c/amazon-employee-access-challenge). Saved it in `/home/catboost/tutorial/catboost_model.bin`
2. Created configuration file `/home/catboost/models/amazon_model.xml` with model description:
```XML
<models>
    <model>
        <!-- Model type. Now catboost only. -->
        <type>catboost</type>
        <!-- Model name. -->
        <name>amazon</name>
        <!-- Path to trained model. -->
        <path>/home/catboost/tutorial/catboost_model.bin</path>
        <!-- Update interval. -->
        <lifetime>0</lifetime>
    </model>
</models>
```
3. Built `libcatboostmodel.so` - CatBoost interface for model evaluation.
* `$ cd /home/catboost`
* `$ git clone https://github.com/catboost/catboost.git`
* `$ cd catboost/catboost/libs/model_interface`
*  `$ ../../../ya make -r` (add `-jN` option to use N processes)
4. Modified `/etc/clickhouse-server/config.xml` - added settings
```XML
<models_config>/home/catboost/models/*_model.xml</models_config>  <!-- path to  amazon_model.xml -->
<catboost_dynamic_library_path>/home/catboost/libcatboostmodel.so</catboost_dynamic_library_path> <!-- path to  libcatboostmodel.so -->
```
5. Created table with train dataset
```SQL
:) CREATE TABLE amazon_train
(
    date Date MATERIALIZED today(), 
    ACTION UInt8, 
    RESOURCE UInt32, 
    MGR_ID UInt32, 
    ROLE_ROLLUP_1 UInt32, 
    ROLE_ROLLUP_2 UInt32, 
    ROLE_DEPTNAME UInt32, 
    ROLE_TITLE UInt32, 
    ROLE_FAMILY_DESC UInt32, 
    ROLE_FAMILY UInt32, 
    ROLE_CODE UInt32
)
ENGINE = MergeTree(date, date, 8192)
```
```bash
$ clickhouse client --host 127.0.0.1 --query 'INSERT INTO amazon_train FORMAT CSVWithNames' < ~/amazon/train.csv
```
6. Now can use `modelEvaluate` function (first argument - name from `amazon_model.xml`, the others - features). list features in the order was used to train model, first numerical ,then categorical.
* Predicted probability:
```SQL
:) SELECT 
    modelEvaluate('amazon', 
                  RESOURCE,
                  MGR_ID,
                  ROLE_ROLLUP_1,
                  ROLE_ROLLUP_2,
                  ROLE_DEPTNAME,
                  ROLE_TITLE,
                  ROLE_FAMILY_DESC,
                  ROLE_FAMILY,
                  ROLE_CODE) AS prediction,
    1. / (1 + exp(-prediction)) AS probability, 
    ACTION AS target
FROM amazon_train
LIMIT 10
```
* Calculated logloss:
```SQL
:) SELECT -avg(tg * log(prob) + (1 - tg) * log(1 - prob)) AS logloss
FROM 
(
    SELECT 
        modelEvaluate('amazon', 
                      RESOURCE,
                      MGR_ID,
                      ROLE_ROLLUP_1,
                      ROLE_ROLLUP_2,
                      ROLE_DEPTNAME,
                      ROLE_TITLE,
                      ROLE_FAMILY_DESC,
                      ROLE_FAMILY,
                      ROLE_CODE) AS prediction,
        1. / (1. + exp(-prediction)) AS prob, 
        ACTION AS tg
    FROM amazon_train
)
```

Note: It may be necessary to add features count settings in `amazon_model.xml` (was removed in last versions)
```XML
<cat_features_count>9</cat_features_count>
<float_features_count>0</float_features_count>
```

**Comment by theseusyang** [comment]
OK @KochetovNicolai
