### ISSUE TITLE
ReplicationMergeTree replicas get out of sync

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#1546]
Hello,

Using this steps you can replicate the problem 100 % on master. In the test I'm using 2 replicas (node1 and node2)

1. create database and schema on both nodes

```sql
CREATE DATABASE db1;

CREATE TABLE db1.tx_src
(
    partition Date,
	timestamp DateTime,
    user_id UInt32,
    counter_id UInt32
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/db1/tx_src', '{replica}', partition, timestamp, 8192)
```

2.  node1 -> run 2 times: `INSERT INTO db1.tx_src(partition, timestamp, user_id, counter_id) VALUES(now(), now(), 1, 1);`
3.  node1 -> perform `select count(*) from db1.tx_src` (got 2 records: OK)
4.  node2 -> perform `select count(*) from db1.tx_src` (got 2 records: OK)
5.  node1 -> shutdown the node
5.  node2 -> run 2 times: `INSERT INTO db1.tx_src(partition, timestamp, user_id, counter_id) VALUES(now(), now(), 1, 1);`
6.  node2 -> `ALTER TABLE db1.tx_src ADD COLUMN desc String;`
7.  node2 -> run 2 times: `INSERT INTO db1.tx_src(partition, timestamp, user_id, counter_id) VALUES(now(), now(), 1, 1);`
8.  node2 -> shutdown  the node
9.  node1 -> startup the node
10. node1 -> `select count(*) from db1.tx_src` (return me 2 (OK) and also the new column is present in the schema - OK as well)
11. node1 -> run 2 times: `INSERT INTO db1.tx_src(partition, timestamp, user_id, counter_id, desc) VALUES(now(), now(), 1, 1, 'ss');`
12. node1 -> `select count(*) from db1.tx_src` (return me 4 - OK)
13. node2 -> startup the node

Observations:

1. select shows 4 on node1 and 8 on node2
2. node1 has 4 items in `system.replication_queue`
3. I restarted node 2 (tooked few minutes in stop) - nothing fixed
4. I restarted node 1 (after 10 minutes in stop I had to kill it) . 

After started again both node GOT IN SYNC :)

**Comment by proller** [comment]
Looks like known bug https://github.com/yandex/ClickHouse/pull/1541

**Comment by silviucpp** [comment]
@proller  thanks a lot ! I'll update to that branch and retest. will let you know about results

**Comment by silviucpp** [comment]
@proller I tested now using the branch you mentions and problem is not fixed.

**Comment by alexey-milovidov** [comment]
I cannot reproduce this issue in master.

A few notes: `VALUES(now(), now(), 1, 1);`
- I have to wait one second between INSERTS, otherwise `now()` is the same and rows will be deduplicated;
- First `now()` is converted to `Date` as number - better to replace it with `today()` (but it doesn't alter results).

**Comment by alexey-milovidov** [comment]
PS. You can also test with more simple test case:
- create both replicas on the same server (with different table names);
- instead of node shutdown and startup, you can use DETACH TABLE and ATTACH TABLE (the effect should be the same);

**Comment by silviucpp** [comment]
Hello,

This was a pretty old report. BackgroundSchedulePool was not yet available at that time. Anyway I'll try again to see if I can or not on master and let you know. Maybe was fixed in the meantime.
