### ISSUE TITLE
Handling ALIAS in Distributed tables

### ISSUE THREAD

**Issue by alniks** [yandex/ClickHouse#1550]
1) Create a Replicated table with an alias column
2) Add Distributed table to above table
3) Try to execute a SELECT statement against Distributed table indicating ALIAS column in WHERE clause but not selecting it:

`Code: 10. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Not found column ... in block. There are only columns: ...`

Some messages are misleading, if you try to select ALIAS column:

`SELECT event_date, domain FROM events WHERE event_date >= '2017-11-27' AND event_date <= today()  limit 10;`

`Received exception from server:
Code: 10. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Not found column domain_name in block. There are only columns: event_date, domain.`

Domain is a ALIAS to domain_name

`SELECT domain, domain_name FROM events WHERE event_date >= '2017-11-27' AND event_date <= today()  limit 10;`

`Received exception from server:
Code: 10. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Not found column event_date in block. There are only columns: domain, domain_name.`

**Comment by alniks** [comment]
We use version 1.1.54292

**Comment by alexey-milovidov** [comment]
Fixed in master.
