### ISSUE TITLE
CLEAR COLUMN does not refresh sizes inside system.columns

### ISSUE THREAD

**Issue by filimonov** [yandex/ClickHouse#1553]
Test case (based on https://github.com/yandex/ClickHouse/blob/master/dbms/tests/queries/0_stateless/00446_clear_column_in_partition_zookeeper.sql)

```
DROP TABLE IF EXISTS test.clear_column;
CREATE TABLE test.clear_column (d Date, num Int64, str String) ENGINE = MergeTree(d, d, 8192);

SELECT data_compressed_bytes, data_uncompressed_bytes FROM system.columns WHERE (database = 'test') AND (table = 'clear_column') AND (name = 'str');
// expect 0, 0

INSERT INTO test.clear_column VALUES ('2016-11-12', 1, 'a');

SELECT data_compressed_bytes, data_uncompressed_bytes FROM system.columns WHERE (database = 'test') AND (table = 'clear_column') AND (name = 'str');

// expect: 28, 2

INSERT INTO test.clear_column VALUES ('2016-12-12', 1, 'a');

SELECT data_compressed_bytes, data_uncompressed_bytes FROM system.columns WHERE (database = 'test') AND (table = 'clear_column') AND (name = 'str');

// expect: 56, 4

ALTER TABLE test.clear_column CLEAR COLUMN num IN PARTITION '201612';

SELECT data_compressed_bytes, data_uncompressed_bytes FROM system.columns WHERE (database = 'test') AND (table = 'clear_column') AND (name = 'str');

// expect: 28, 2 as before previous insert, currently have 56, 4

```

**Comment by filimonov** [comment]
BTW: as i see currently 2 syntax still exists which do the same(?).
ALTER TABLE xxx DROP COLUMN yyy FROM PARTITION zzz;
and 
ALTER TABLE xxx CLEAR COLUMN yyy FROM PARTITION zzz;

No documentation exists for both of them. Probably first syntax should be removed? And some documentation should be created?

**Comment by filimonov** [comment]
BTW: there is no documentation for CLEAR COLUMN xxx IN PARTITION yyyymm

**Comment by ludv1x** [comment]
> ALTER TABLE test.clear_column CLEAR COLUMN num IN PARTITION '201612';
> 
> SELECT data_compressed_bytes, data_uncompressed_bytes FROM system.columns WHERE (database = 'test') AND (table = 'clear_column') AND (name = 'str');
> 
> // expect: 28, 2 as before previous insert, currently have 56, 4

There is an error in your test. 
You clear column `num`, but check column `str`.

The test has already had a check for columns: https://github.com/yandex/ClickHouse/blob/8a7e604a2a5dd2540e73706bd329126ca7fcd65c/dbms/tests/queries/0_stateless/00446_clear_column_in_partition_zookeeper.sql#L46

**Comment by filimonov** [comment]
Yes, it works correctly. Sorry.

Actually I had that problem when was clearing production data.

But i can't reproduce it now, may be i just did something wrong, don't remember now.

**Comment by ludv1x** [comment]
Not that `CLEAR COLUMN IN PARTITION` currently has an inefficient implementation. 
If there are active INSERTs or background merges in the same partition, then the replication is stuck while `CLEAR COLUMN IN PARTITION` is executing.

**Comment by filimonov** [comment]
Good to know.

But rather not a problem for my case, because i olny clean columns in really old partitions - to remove some unneeded debug details for old records.
