### ISSUE TITLE
Is there any way to view a release notes?

### ISSUE THREAD

**Issue by shalugin** [yandex/ClickHouse#156]

**Comment by alexey-milovidov** [comment]
We are not maintaining descriptive changelog.

Internally, for each release, we have linked tasks with descriptions. 
But task tracker is not publicly available. We want to address this issue and made most of tasks visible to public. It is not going to happen in near future (not in 2016).

**Comment by shalugin** [comment]
Ok

**Comment by otisg** [comment]
It's great you are publishing https://github.com/yandex/ClickHouse/blob/master/CHANGELOG.md !
One small suggestion: include the release date.  It is really easy to add and very valuable.
