### ISSUE TITLE
when dropping a database the metadata file is not deleted

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#1560]
Hello,

When you drop a database the sql file in /var/lib/clickhouse/metadata for that db is not deleted.

Is this a bug ?

**Comment by ludv1x** [comment]
Yes, it is a bug.

**Comment by IvanJobs** [comment]
Is this bug done? I plan to fix this.

**Comment by silviucpp** [comment]
Not fixed from what I’m aware
