### ISSUE TITLE
feature: don't waste page cache resources when merging big parts

### ISSUE THREAD

**Issue by valyala** [yandex/ClickHouse#1566]
## The issue

`ClickHouse` opens both source and destination `*MergeTree` part files without [O_DIRECT](https://stackoverflow.com/questions/5055859/how-are-the-o-sync-and-o-direct-flags-in-open2-different-alike) during the merge. This means that the contents of source and destination parts go into [page cache](https://www.thomas-krenn.com/en/wiki/Linux_Page_Cache_Basics) during the merge, evicting useful data from the page cache.

The contents of source parts is never accessed after the merge, so it **always** wastes page cache resources.

The cached contents of destination parts may reduce both read and write I/O during subsequent merges. But this is true only when merging recently created small parts. Merging bigger and/or older parts will certainly waste page cache resources.

## The solution

Open source and destination part files using `O_DIRECT` mode if the part size (either source or destination part) exceeds `min_part_size_for_direct_merge` setting. Default value for the setting may be set to (`RAM size` * [vm.dirty_ratio](https://www.kernel.org/doc/Documentation/sysctl/vm.txt) / `100`).

**Comment by valyala** [comment]
FYI, I tried implementing `O_DIRECT` support for another project and failed to do so, since it has been appeared that certain filesystems and/or configurations don't support `O_DIRECT`. Additionally, `O_DIRECT` usually implies synchronous I/O, which may lead to slow read/write operations on network filesystems with high network latencies.

I fully agree with Linus Torvalds about `O_DIRECT`:

> The thing that has always disturbed me about O_DIRECT is that the whole interface is just stupid, and was probably designed by a deranged monkey on some serious mind-controlling substances 

There is much better solution for the page cache pollution issue - just read and write files as usual, but periodically call `posix_fadvise(POSIX_FADV_DONTNEED)` to clean page cache -
 see https://linux.die.net/man/2/posix_fadvise for details.

**Comment by alexey-milovidov** [comment]
#3117

**Comment by alesapin** [comment]
I forgot to turn on this setting by default.

**Comment by alesapin** [comment]
https://github.com/yandex/ClickHouse/pull/3504
