### ISSUE TITLE
Error converting string to date

### ISSUE THREAD

**Issue by sichkarev** [yandex/ClickHouse#158]
ClickHouse client version 1.1.54030.
Connecting to localhost:9000.
Connected to ClickHouse server version 1.1.54030.
:) select toDate('1967-01-01')
SELECT toDate('1967-01-01')
┌─toDate(\'1967-01-01\')─┐
│             0000-00-00 │
└────────────────────────┘

1 rows in set. Elapsed: 0.002 sec.

**Comment by alexey-milovidov** [comment]
Only dates after the beginning of the unix epoch are supported. As documented here:
https://clickhouse.yandex/reference_en.html#Date

You could use different data type (String or UInt32) to store broader range of dates,
but datetime functions will not work with them.

**Comment by sichkarev** [comment]
Alexey, thank you for answer! It sad restrictions.
Please tell me the best way to store birthdate user? May be date split by 3 columns: year, month and day? And say please how best way for grouping users by age and period 0 - 20, 20 - 40 years old?

Thank you so much!

**Comment by sichkarev** [comment]
![image](https://cloud.githubusercontent.com/assets/16035271/20090125/03bee752-a5ad-11e6-891a-6e4e634223a9.png)
I did it :)
@alexey-milovidov may be you think best way for task?
```sql
select 
    sumIf(cnt, 
        toYear(today()) - year_of_birth between 0 and 13
        and toMonth(today()) <= month_of_birth
        and toDayOfMonth(today()) <= day_of_birth
    ) as yo_13_9, /*от 0 до 13,9*/
    
    sumIf(cnt, 
        toYear(today()) - year_of_birth between 14 and 17
        and toMonth(today()) <= month_of_birth
        and toDayOfMonth(today()) <= day_of_birth
    ) as yo_17_9, /*от 14 до 17,9*/
    
    sumIf(cnt, 
        toYear(today()) - year_of_birth between 18 and 24
        and toMonth(today()) <= month_of_birth
        and toDayOfMonth(today()) <= day_of_birth
    ) as yo_24_9 /*от 18 до 24,9*/
from (
    	select year_of_birth, month_of_birth, day_of_birth, count() as cnt from TABLE group by year_of_birth, month_of_birth, day_of_birth
) FORMAT Vertical
```

**Comment by alexey-milovidov** [comment]
I have no better solution. I wanted to propose the same.

**Comment by yehiaelbehery** [comment]
Do you plan to supporting date functions for dates before 1970 for birth dates, ... and other historic dates. Can you explain the philosohy behind the decision (if not time and resources)?

**Comment by den-crane** [comment]
@yehiaelbehery  yes. It will be implemented in DateTime64 https://github.com/ClickHouse/ClickHouse/issues/7316
