### ISSUE TITLE
extract() does not support some group operations

### ISSUE THREAD

**Issue by alex-zaitsev** [yandex/ClickHouse#1588]
1) Lookahead and lookbehind groups generate errors, e.g. if using '(?='

`error: invalid perl operator: (?=. `

2) Non-capturing groups sometimes do not work right:

```
SELECT extractAll('ab', '((a)|(b))')

┌─extractAll(\'ab\', \'((a)|(b))\')─┐
│ ['a','b']                         │
└───────────────────────────────────┘

SELECT extractAll('ab', '(?:(a)|(b))')

┌─extractAll(\'ab\', \'(?:(a)|(b))\')─┐
│ ['a']                               │
└─────────────────────────────────────┘
```

Second query should return the same result, but it does not.

**Comment by filimonov** [comment]
1. Supported regexp syntax: https://github.com/google/re2/wiki/Syntax
2. Documented. In that case regexp CONTAINs 2 subpatterns, so it return **first** subpattern, which is "a" for a first match, and empty for a second match (second capturing group capture 'b' in second match). So like that it will work (i've removed capturing groups):
```
:) SELECT extractAll('ab', '(?:a|b)') ;
┌─extractAll(\'ab\', \'(?:a|b)\')─┐
│ ['a','b']                       │
└─────────────────────────────────┘

```

**Comment by alexey-milovidov** [comment]
Thanks, @filimonov!
