### ISSUE TITLE
clickhouse-client cli ssl connection

### ISSUE THREAD

**Issue by artemkamolodets** [yandex/ClickHouse#1594]
Hello. I've set up ssl in clickhouse server instance, but there is an error when i'm trying to login via client cli.
The error is about certificate mismatch, so i just generated a client certificate and placed it in /etc/clickhouse-certificate directory but this didn't help. Also there is no any option to set certificate location in the clickhouse client.
Please help, how to login to clickhouse-server via ssl using client cli?

**Comment by vicdashkov** [comment]
Hey, could you please post your solution?
