### ISSUE TITLE
server crash when select using dictionary

### ISSUE THREAD

**Issue by vaslv** [yandex/ClickHouse#1595]
Query:
SELECT `SiteID`, dictGetString('sites', 'domain', 'SiteID') as `SiteDomain`
FROM `video_distributed`
WHERE `EventDate` >= '2017-12-04'
GROUP BY `SiteID`;

Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000, 127.0.0.1

Logs:
2017.12.07 10:44:41.832181 [ 2084 ] <Error> BaseDaemon: ########################################
2017.12.07 10:44:41.835760 [ 2084 ] <Error> BaseDaemon: (from thread 27) Received signal Segmentation fault (11).
2017.12.07 10:44:41.835773 [ 2084 ] <Error> BaseDaemon: Address: NULL pointer.
2017.12.07 10:44:41.900580 [ 2084 ] <Error> BaseDaemon: 0. clickhouse-server(ma_init+0xb) [0x34e6c9b]
2017.12.07 10:44:41.900598 [ 2084 ] <Error> BaseDaemon: 1. clickhouse-server() [0x34dfafe]
2017.12.07 10:44:41.900610 [ 2084 ] <Error> BaseDaemon: 2. /lib64/libpthread.so.0(pthread_once+0x50) [0x7fae6e38de20]
2017.12.07 10:44:41.900630 [ 2084 ] <Error> BaseDaemon: 3. clickhouse-server(mysqlxx::LibrarySingleton::LibrarySingleton()+0x16) [0x3382fd6]
2017.12.07 10:44:41.900644 [ 2084 ] <Error> BaseDaemon: 4. clickhouse-server(mysqlxx::Connection::Connection()+0x58) [0x33830d8]
2017.12.07 10:44:41.900658 [ 2084 ] <Error> BaseDaemon: 5. clickhouse-server(mysqlxx::Pool::allocConnection(bool)+0x3f) [0x338acbf]
2017.12.07 10:44:41.900671 [ 2084 ] <Error> BaseDaemon: 6. clickhouse-server(mysqlxx::Pool::initialize()+0x23e) [0x338b2ee]
2017.12.07 10:44:41.900684 [ 2084 ] <Error> BaseDaemon: 7. clickhouse-server(mysqlxx::Pool::tryGet()+0x3e) [0x338b77e]
2017.12.07 10:44:41.900703 [ 2084 ] <Error> BaseDaemon: 8. clickhouse-server(mysqlxx::PoolWithFailover::Get()+0xd9) [0x338ba29]
2017.12.07 10:44:41.900722 [ 2084 ] <Error> BaseDaemon: 9. clickhouse-server(DB::MySQLDictionarySource::getLastModification() const+0x4a4) [0x3349f64]
2017.12.07 10:44:41.900747 [ 2084 ] <Error> BaseDaemon: 10. clickhouse-server(DB::MySQLDictionarySource::loadAll()+0x29) [0x334aa49]
2017.12.07 10:44:41.900771 [ 2084 ] <Error> BaseDaemon: 11. clickhouse-server(DB::FlatDictionary::loadData()+0x2e) [0x2d211ee]
2017.12.07 10:44:41.900805 [ 2084 ] <Error> BaseDaemon: 12. clickhouse-server(DB::FlatDictionary::FlatDictionary(std::string const&, DB::DictionaryStructure const&, std::unique_ptr<DB::IDictionarySource, std::default_delete<DB::IDictionarySource> >, DB::ExternalLoadableLifetime, bool)+0x60e) [0x2d21cae]
2017.12.07 10:44:41.900828 [ 2084 ] <Error> BaseDaemon: 13. clickhouse-server(DB::DictionaryFactory::create(std::string const&, Poco::Util::AbstractConfiguration const&, std::string const&, DB::Context&) const+0xf24) [0x32933d4]
2017.12.07 10:44:41.900854 [ 2084 ] <Error> BaseDaemon: 14. clickhouse-server(DB::ExternalDictionaries::create(std::string const&, Poco::Util::AbstractConfiguration const&, std::string const&)+0x31) [0x2e16271]
2017.12.07 10:44:41.900882 [ 2084 ] <Error> BaseDaemon: 15. clickhouse-server(DB::ExternalLoader::reloadFromConfigFile(std::string const&, bool, bool, std::string const&)+0x118a) [0x2e1866a]
2017.12.07 10:44:41.900898 [ 2084 ] <Error> BaseDaemon: 16. clickhouse-server(DB::ExternalLoader::reloadFromConfigFiles(bool, bool, std::string const&)+0x34e) [0x2e1a00e]
2017.12.07 10:44:41.900913 [ 2084 ] <Error> BaseDaemon: 17. clickhouse-server(DB::ExternalLoader::reloadAndUpdate(bool)+0x4a) [0x2e1a4fa]
2017.12.07 10:44:41.900925 [ 2084 ] <Error> BaseDaemon: 18. clickhouse-server(DB::ExternalLoader::init(bool)+0x5f) [0x2e1b62f]
2017.12.07 10:44:41.900951 [ 2084 ] <Error> BaseDaemon: 19. clickhouse-server(DB::ExternalDictionaries::ExternalDictionaries(DB::Context&, bool)+0x10c) [0x2e1642c]
2017.12.07 10:44:41.900964 [ 2084 ] <Error> BaseDaemon: 20. clickhouse-server(DB::Context::getExternalDictionariesImpl(bool) const+0xbb) [0x2dd686b]
2017.12.07 10:44:41.900981 [ 2084 ] <Error> BaseDaemon: 21. clickhouse-server(DB::FunctionDictGetString::create(DB::Context const&)+0x12) [0x1878702]
2017.12.07 10:44:41.900999 [ 2084 ] <Error> BaseDaemon: 22. clickhouse-server(std::_Function_handler<std::shared_ptr<DB::IFunction> (DB::Context const&), std::shared_ptr<DB::IFunction> (*)(DB::Context const&)>::_M_invoke(std::_Any_data const&, DB::Context const&)+0x14) [0x154eb34]
2017.12.07 10:44:41.901012 [ 2084 ] <Error> BaseDaemon: 23. clickhouse-server(DB::FunctionFactory::tryGet(std::string const&, DB::Context const&) const+0x43) [0x30f7b83]
2017.12.07 10:44:41.901025 [ 2084 ] <Error> BaseDaemon: 24. clickhouse-server(DB::FunctionFactory::get(std::string const&, DB::Context const&) const+0x18) [0x30f7c38]
2017.12.07 10:44:41.901039 [ 2084 ] <Error> BaseDaemon: 25. clickhouse-server(DB::ExpressionAnalyzer::getActionsImpl(std::shared_ptr<DB::IAST> const&, bool, bool, DB::ExpressionAnalyzer::ScopeStack&)+0xb03) [0x329f763]
2017.12.07 10:44:41.901052 [ 2084 ] <Error> BaseDaemon: 26. clickhouse-server(DB::ExpressionAnalyzer::getActionsImpl(std::shared_ptr<DB::IAST> const&, bool, bool, DB::ExpressionAnalyzer::ScopeStack&)+0x144c) [0x32a00ac]
2017.12.07 10:44:41.901065 [ 2084 ] <Error> BaseDaemon: 27. clickhouse-server(DB::ExpressionAnalyzer::getActionsImpl(std::shared_ptr<DB::IAST> const&, bool, bool, DB::ExpressionAnalyzer::ScopeStack&)+0x144c) [0x32a00ac]
2017.12.07 10:44:41.901078 [ 2084 ] <Error> BaseDaemon: 28. clickhouse-server(DB::ExpressionAnalyzer::getRootActions(std::shared_ptr<DB::IAST> const&, bool, bool, std::shared_ptr<DB::ExpressionActions>&)+0x124) [0x32a18c4]
2017.12.07 10:44:41.901091 [ 2084 ] <Error> BaseDaemon: 29. clickhouse-server(DB::ExpressionAnalyzer::getConstActions()+0x7a) [0x32a44ea]
2017.12.07 10:44:41.901105 [ 2084 ] <Error> BaseDaemon: 30. clickhouse-server(DB::PKCondition::getBlockWithConstants(std::shared_ptr<DB::IAST> const&, DB::Context const&, DB::NamesAndTypesList const&)+0x185) [0x307fd55]
2017.12.07 10:44:41.901126 [ 2084 ] <Error> BaseDaemon: 31. clickhouse-server(DB::MergeTreeWhereOptimizer::MergeTreeWhereOptimizer(DB::SelectQueryInfo&, DB::Context const&, DB::MergeTreeData const&, std::vector<std::string, std::allocator<std::string> > const&, Poco::Logger*)+0x4a1) [0x3077971]
2017.12.07 10:44:41.901139 [ 2084 ] <Error> BaseDaemon: 32. clickhouse-server(DB::InterpreterSelectQuery::executeFetchColumns()+0xe02) [0x2e39e82]
2017.12.07 10:44:41.901150 [ 2084 ] <Error> BaseDaemon: 33. clickhouse-server(DB::InterpreterSelectQuery::executeSingleQuery()+0x23) [0x2e36753]
2017.12.07 10:44:41.901168 [ 2084 ] <Error> BaseDaemon: 34. clickhouse-server(DB::InterpreterSelectQuery::executeWithoutUnion()+0x16d) [0x2e3890d]
2017.12.07 10:44:41.901181 [ 2084 ] <Error> BaseDaemon: 35. clickhouse-server(DB::InterpreterSelectQuery::execute()+0x22) [0x2e38952]
2017.12.07 10:44:41.901195 [ 2084 ] <Error> BaseDaemon: 36. clickhouse-server() [0x32d4155]
2017.12.07 10:44:41.901224 [ 2084 ] <Error> BaseDaemon: 37. clickhouse-server(DB::ClusterProxy::SelectStreamFactory::createForShard(DB::Cluster::ShardInfo const&, std::string const&, std::shared_ptr<DB::IAST> const&, DB::Context const&, std::shared_ptr<DB::Throttler> const&, std::vector<std::shared_ptr<DB::IBlockInputStream>, std::allocator<std::shared_ptr<DB::IBlockInputStream> > >&)+0x435) [0x32d5115]
2017.12.07 10:44:41.901239 [ 2084 ] <Error> BaseDaemon: 38. clickhouse-server(DB::ClusterProxy::executeQuery(DB::ClusterProxy::IStreamFactory&, std::shared_ptr<DB::Cluster> const&, std::shared_ptr<DB::IAST> const&, DB::Context const&, DB::Settings const&)+0x23db) [0x32da06b]
2017.12.07 10:44:41.901254 [ 2084 ] <Error> BaseDaemon: 39. clickhouse-server(DB::StorageDistributed::read(std::vector<std::string, std::allocator<std::string> > const&, DB::SelectQueryInfo const&, DB::Context const&, DB::QueryProcessingStage::Enum&, unsigned long, unsigned int)+0x213) [0x2f765f3]
2017.12.07 10:44:41.901440 [ 2084 ] <Error> BaseDaemon: 40. clickhouse-server(DB::InterpreterSelectQuery::executeFetchColumns()+0xe81) [0x2e39f01]
2017.12.07 10:44:41.901460 [ 2084 ] <Error> BaseDaemon: 41. clickhouse-server(DB::InterpreterSelectQuery::executeSingleQuery()+0x23) [0x2e36753]
2017.12.07 10:44:41.901472 [ 2084 ] <Error> BaseDaemon: 42. clickhouse-server(DB::InterpreterSelectQuery::executeWithoutUnion()+0x16d) [0x2e3890d]
2017.12.07 10:44:41.901484 [ 2084 ] <Error> BaseDaemon: 43. clickhouse-server(DB::InterpreterSelectQuery::execute()+0x22) [0x2e38952]
2017.12.07 10:44:41.901495 [ 2084 ] <Error> BaseDaemon: 44. clickhouse-server() [0x2ebf2d9]
2017.12.07 10:44:41.901508 [ 2084 ] <Error> BaseDaemon: 45. clickhouse-server(DB::executeQuery(std::string const&, DB::Context&, bool, DB::QueryProcessingStage::Enum)+0x126) [0x2ec0b56]
2017.12.07 10:44:41.901519 [ 2084 ] <Error> BaseDaemon: 46. clickhouse-server(DB::TCPHandler::runImpl()+0x591) [0x1476941]
2017.12.07 10:44:41.901543 [ 2084 ] <Error> BaseDaemon: 47. clickhouse-server(DB::TCPHandler::run()+0x1c) [0x147755c]
2017.12.07 10:44:41.901555 [ 2084 ] <Error> BaseDaemon: 48. clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x346c5cf]
2017.12.07 10:44:41.901567 [ 2084 ] <Error> BaseDaemon: 49. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x14c) [0x346ce9c]

**Comment by ztlpn** [comment]
The crash occurs during the initialization of libmariadb client library. Did you compile ClickHouse yourself? Can you try the same query with libmysqlclient library?

**Comment by vaslv** [comment]
Works! Use https://github.com/Altinity/clickhouse-rpm on centos 7 with mysqlcommunity
