### ISSUE TITLE
code: 26. DB::Exception: Cannot parse JSON string: expected opening quote: (at row 1) while importing from JSON with FLOAT without quotes

### ISSUE THREAD

**Issue by Blasterdick** [yandex/ClickHouse#160]
After making:

`cat test.json |clickhouse-client -h 10.0.0.2 -u name --password passwd --database=default --query="INSERT INTO test_table FORMAT JSONEachRow";`

I'm getting: 

`code: 26. DB::Exception: Cannot parse JSON string: expected opening quote: (at row 1)` 

After taking every float value in double quotes, everything works flawlessly.

That's all, folks.

**Comment by alexey-milovidov** [comment]
Need more detailed example, because I couldn't reproduce on trivial example:

```
$ clickhouse-client --query="CREATE TABLE test.json (x Float64) ENGINE = Memory"
$ clickhouse-client --query="INSERT INTO test.json FORMAT JSONEachRow" <<< '{"x": 123.456}'
$ clickhouse-client --query="SELECT * FROM test.json"
123.456
```

Maybe you have column with String data type and try to insert unquoted float value into it.

**Comment by Blasterdick** [comment]
@alexey-milovidov Sorry, mate, my fault. You're right, it was a wrong schema problem, closing this issue.
