### ISSUE TITLE
Probably, error in implementation (or it is just me being stupid)

### ISSUE THREAD

**Issue by dmitsolodkiy** [yandex/ClickHouse#1601]
For our database,
this:
SELECT countIf(trans IN ('oh','ah')),
(CASE WHEN name IN ('X','Y') THEN 'X' ELSE 'Z' END) as name
FROM transactions WHERE name IN ('X','Y','Z') GROUP BY name
and this:
SELECT countIf(trans IN ('oh','ah')),
name
FROM transactions WHERE name IN ('X','Y','Z') GROUP BY name
give different results (namely, 325 for Z in the first case and 1477 for Z in the second case - I mean, count value; 325 is right, by the way)
Moreover, this request works ok:
SELECT
(CASE WHEN  name IN ('X','Y') THEN 'X' ELSE 'Z' END) as name,
u
FROM
(SELECT countIf(trans IN ('oh','ah')) as u,
name
FROM transactions WHERE name IN ('X','Y','Z') GROUP BY name) (325 again)

**Comment by filimonov** [comment]
Your `WHERE name` in first case works on the alias created `(CASE ... ) as name`, and in second case - on table column `name`. Same for group by.

Just remember one simple trick - never create aliases with names which already exist in table, or used in that select. Otherwise it's not always obvious what is happening, and life became full of surprises :)

**Comment by dmitsolodkiy** [comment]
It is understood it should work this way, but that was not the question. Perhaps, I formulated it in rather a strange way, sorry) The problem is that the result of 1 and 3 command (i mean, count value) for Z should be the same anyway (you can clearly see it if you create some mickey-mouse dataset or... if you just perform these operations in mind - don't forget this WHERE clause, which is, of course, important), and result for X (1st case) should be equal to the sum of the results for X and Y (2nd case). While latter is true, former is not - as I stated above, I get 325 for Z in the first case and 1477 in second (I was not even able to understand where this 1477 even come from, by the way, although I tried hard). The thing is WHENEVER I put CASE in the order of operations performed, I couldn't get such a result - so, something really strange and goofy was going there (and I was always relying on it working the way you explained it in your answer)

**Comment by filimonov** [comment]
If your name column contains not only 'X','Y','Z' then in first select all other values (out of that range) will be converted to 'Z' by ELSE clause in CASE WHEN .... May be that is the reason?

**Comment by dmitsolodkiy** [comment]
Ah, yes, forgot, that filtering with WHERE will also be applied after. Ok, thank you and sorry for taking so much of your time!
