### ISSUE TITLE
SSD vs NVMe

### ISSUE THREAD

**Issue by Slind14** [yandex/ClickHouse#1606]
Hi there,
the performance guide only talks about HDD vs SSD. Are there any benchmarks/tests on SSD vs NVMe or general recommendations?

**Comment by zero-master** [comment]
Depends on what NVMe adds to your setup.

When your data is not already in the pagecache and CPU is not bottleneck:

a) If it's offering you a higher sequential read speed, you'll benefit 
b) If it offers you more random read performance, you'll benefit when selecting 80% columns+ of table in your queries. 

These are edge cases only.

**Comment by blinkov** [comment]
@Slind14 NVMe and SSD are not as fundamentally different as HDD and SSD. If you decided that HDD is not enough for your use case, you should start looking for specific disk drive model that provides best tradeoffs, considering not only raw performance, but also costs normalized by expected lifetime. 

We are aware of some people using ClickHouse over NVMe on sub-petabyte scale, afaik they had no issues related to that at all and they looked pretty satisfied with performance
