### ISSUE TITLE
добавление полей

### ISSUE THREAD

**Issue by wormen** [yandex/ClickHouse#1607]
Подскажите
возможно ли добавлять поля к таблице, когда таблица уже была создана?
в документации не нашел описания этого момента

или мне придется полностью пересоздавать таблицу?

**Comment by filimonov** [comment]
Разумеется :) Так же как в нормальном SQL - `ALTER TABLE x ADD COLUMN ...`

См.
https://clickhouse.yandex/docs/ru/query_language/queries.html#id4

9 дек. 2017 г. 3:09 AM пользователь "Oleg Bogdanov" <
notifications@github.com> написал:

**Comment by wormen** [comment]
спасибо
... видимо не внимательно смотрел ...
