### ISSUE TITLE
couchbase как внешний словарь

### ISSUE THREAD

**Issue by wormen** [yandex/ClickHouse#1608]
подскажите, как правильно подключить Couchbase в качестве внешнего словаря?
у вас в документации написано, что так можно подключить любую БД

```
<odbc>
    <db>DatabaseName</db>
    <table>TableName</table>
    <connection_string>DSN=some_parameters</connection_string>
    <invalidate_query>SQL_QUERY</invalidate_query>
</odbc>
```
суть заключается в том .... что Couchbase нет таблиц, там есть так называемые `Bucket`, аналог `Collection` в `MongoDB`

мне эти самые `Bucket` указывать вместо таблиц?

**Comment by avsej** [comment]
@wormen, может быть "любая" в смысле [ODBC](https://github.com/yandex/ClickHouse/blob/master/dbms/src/Storages/StorageODBC.h), которые поддерживаются [Poco::Data]( https://pocoproject.org/docs/Poco.Data.ODBC.html). Для Kafka они писали отдельный коннектор [StorageKafka.cpp](https://github.com/yandex/ClickHouse/blob/master/dbms/src/Storages/StorageKafka.cpp).

А для Couchbase, скорее всего тоже нужно будет писать отдельный коннектор (ну или добавить поддержку в Poco). У нас есть сишная библиотека http://github.com/couchbase/libcouchbase, если будут вопросы по реализации, можно спросить меня.

**Comment by filimonov** [comment]
@avsej, с Kafka история немного другая. Kafka может используется как виртуальная таблица из которой можно читать (правда всего один раз) данные.

Вопрос @wormen -  про подключение [внешних словарей](https://clickhouse.yandex/docs/ru/dicts/external_dicts.html) (это такая удобная штука в Кликхаус, которую можно использовать как удобную альтернативу JOIN для внешних данных), примерно так 
```sql
-- для всех событий вытаскиваем фамилию пользователя по его userid 
-- из внешнего словаря users
SELECT dictGetString('users','surname',toUInt64(userid)) as surname from events;
```

Я не думаю что работа через ODBC-драйвер с key-value NOSQL хранилищ (типа Redis / Memcached / Couchbase / Riak / Aerospike) является хорошей идеей, ODBC предназначен прежде всего для баз с поддержкой обычного SQL.

Для NOSQL проще и надежнее или написать маленькую HTTP или консольную обёртку на своем любимом языке программирования. И подключить словарь как [HTTP](https://clickhouse.yandex/docs/ru/dicts/external_dicts_dict_sources.html#dicts-external_dicts_dict_sources-http), или как [исполняемый файл](https://clickhouse.yandex/docs/ru/dicts/external_dicts_dict_sources.html#dicts-external_dicts_dict_sources-executable). 

Как вариант (если вы "можете" C++) - можно прикрутить "родной" драйвер (как libcouchbase в случает Couchbase) к кликхаус, получить благодаря этому некоторый прирост производительности. В этом случае нужно это делать [тут](https://github.com/yandex/ClickHouse/tree/master/dbms/src/Dictionaries), в качестве примеров можно посмотреть как это сделано в [MySQLDictionarySource.cpp](https://github.com/yandex/ClickHouse/blob/master/dbms/src/Dictionaries/MySQLDictionarySource.cpp) и в [MongoDBDictionarySource.cpp](https://github.com/yandex/ClickHouse/blob/master/dbms/src/Dictionaries/MongoDBDictionarySource.cpp).

**Comment by wormen** [comment]
@filimonov 
1) у нас используется эта БД
2) в COUCHBASE используются SQL запросы

про HTTP словарь, что-то даже не подумал, где по нему примеры можно глянуть? как его использовать

**Comment by avsej** [comment]
Да, у нас есть язык запросов N1QL, который очень похож на SQL, также в следующем релизе будет поддержка ещё одного диалекта SQL++, который позволяет делать запросы для аналитики более эффективно.

А примеры как сделать N1QL запрос на С++ с libcouchbase, можно посмотреть тут
https://github.com/couchbaselabs/devguide-examples/blob/35337cf6c1d68762f932ef9318abaf262462de47/c/query-criteria.cc#L50-L57

**Comment by filimonov** [comment]
> у нас используется эта БД

@wormen я догадываюсь, начало комментария было больше для @avsej - одного из разработчиков Couchbase, который видимо забрел сюда по ключевому слову Couchbase, и мы рады его тут видеть :) Поэтому постарался вкратце описать как Couchbase (может) использоваться в ClickHouse. 

> в COUCHBASE используются SQL запросы

Про N1QL, да, знаю. Но все равно мне кажется значительно более натуральным способ вытащить список ключей без использования громозких контрукций типа `SELECT a,b,c FROM xxx WHERE id in (....) ` которые должен будет построить ClickHouse при помощи ODBC драйвера, а CouchBase должен будет "притворяться" что у него есть таблица xxx со столбцами `a,b,c` обернуть ответ при помощи ODBC драйвера в "стандартный" формат, а кликхаус это прочитать. По-моему, довольно шаткая конструкция, с учетом того что ODBC драйвер для CouchBase написан сторонней фирмой. 

> про HTTP словарь, что-то даже не подумал, где по нему примеры можно глянуть? как его использовать

Про HTTP - вроде все просто, особенной философии нет.  Поднимаете HTTP сервер. Указываете его в конфигурации ClickHouse. После этого HTTP сервер будет получать в POST список ключей, и нужно будет возвращать список значений (например в TabSeparated).

**Comment by avsej** [comment]
А есть в clickhouse такой режим, в котором мы можем уведомлять его об изменениях (удаление и добавление ключей) непрерывно? Что-то типа репликации. У нас есть специальный протокол, который я мог бы использовать, чтобы выгрузить ключи и необходимые данные для словаря в clickhouse и поддерживать в актуальном стостоянии. Я видел в документации настройку `lifetime` для словарей, но это же перезагрузка всех ключей, так? Мы же могли бы присылать только изменения, что было бы более эффективно.

**Comment by filimonov** [comment]
> А есть в clickhouse такой режим, в котором мы можем уведомлять его об изменениях (удаление и добавление ключей) непрерывно? Что-то типа репликации. 

Нет, в настоящее время нет. Полагаю, отчасти потому, что используемые до сих пор источники данных для внешних словарей не позволяли осуществлять такой мониторинг. Ну и конечно, так проще, меньше возможностей гонок и т.п.

**Comment by avsej** [comment]
То есть, если по какой-то причине, внешний источник падает, а передача данных не завершена, clickhouse будет выкачивать заново?

**Comment by avsej** [comment]
Хотя вон Kafka у вас бесконечно в цикле читает данные, пока не остановят. 
https://github.com/yandex/ClickHouse/blob/master/dbms/src/Storages/StorageKafka.cpp#L396-L427

Мы могли бы и из Couchbase так данные получать. Или это уже не dictionary? 

> Kafka история немного другая. Kafka может используется как виртуальная таблица из которой можно читать (правда всего один раз) данные.

А что значит один раз читать?

**Comment by wormen** [comment]
еще вопрос, примерно в ту же сторону, что и у @avsej 
планируется ли добавить подгрузку данных словарей, по TCP сокетам? думаю так будет быстрее и и проще, для обновления новых/измененных данных в КХ

**Comment by avsej** [comment]
libcouchbase пока ещё не умеет DCP (это протокол репликации, который я упоминал выше), но я работаю над прототипом, который в конечном итоге войдёт в libcouchbase

**Comment by filimonov** [comment]
> Хотя вон Kafka у вас бесконечно в цикле читает данные ... Или это уже не dictionary?

Повторюсь, с Kafka - история совсем другая. Это не словарь, а "виртуальная" таблица.

Kafka - это очередь сообщений. Поэтому из неё по определению читают один раз, чтобы что-то с этими сообщениями сделать - переложить в перманентное хранилище, посчитать/записать аггрегации и т.п. Второй раз тоже самое сообщение (обычно) читать не нужно.

> То есть, если по какой-то причине, внешний источник падает, а передача данных не завершена, clickhouse будет выкачивать заново?

Насколько мне известно именно так он и сделает. 

Кажется всё ещё осталось некоторое недопонимание функций словарей в Кликхаус. Обычно словари - это ограниченные по размеру редко изменяемые таблицы соответствия id => аттрибуты. Типичный пример: по почтовому индексу вытащить название города и почтового отделения. Использование словарей для неограниченного по количеству непрерывно изменяемых фактов, типа данных с сенсоров в IoT - это не то для чего эти словари были придуманы.

> планируется ли добавить подгрузку данных словарей, по TCP сокетам? 

Не совсем понятен вопрос. В определенном смысле это уже реализовано, ведь HTTP работает "по TCP сокетам".

**Comment by avsej** [comment]
Понятно, в таком случае нет смысла использовать словари для Couchbase. А судя по описанию работы, Couchbase тоже можно было бы интегрировать как Kafka.

В обычном режиме, просто стримились бы данные, а с materialized view, можно использовать ReplacingMergeTree, чтобы получить то, что реально содержится в Couchbase (без истории всех изменений, а только текущие значения для одинаковых ключей).

**Comment by wormen** [comment]
> В определенном смысле это уже реализовано, ведь HTTP работает "по TCP сокетам".

да, но у HTTP нет двустороннего обмена+по HTTP только КХ запрашивает данные, сами мы туда закинуть их не можем, если они изменились

**Comment by wormen** [comment]
... в принципе, я получил ответ, малость не тот который ожидал, но тоже сойдет ...
спасибо за информацию

**Comment by avsej** [comment]
ну так clickhouse не инициирует обновление внешних словарей и даже кафка в режиме только чтения, я прав, @filimonov?

**Comment by filimonov** [comment]
> по HTTP только КХ запрашивает данные, сами мы туда закинуть их не можем, если они изменились

Ну тут по аналогии с обычной жизнью - человек заглядывает в толковый словарь когда требуется, а не словарь будит человека среди ночи "эй, я такой новое слово узнал, слушай: жандобиться это согласно Далю означает заботиться, стараться" :)

Про стриминг данных из Couchbase в таблицу, не знаю никогда не рассматривал Couchbase как мессадж брокера. Зато приходилось использовать (и вполне успешно) Couchbase  как key-value хранилище данных пользователей (этакие куки на сервере), ну и в такой функции Couchbase 
 вполне мог бы полезен как словарь.

**Comment by avsej** [comment]
ну это да, Couchbase не брокер сообщений, но его данные можно трансформировать в поток изменений, что может быть удобно для анализа. Тот же протокол используется для построения различных индексов в остальных сервисах самого Couchbase, да и внешних инструментов. В ту же Kafka можно писать всё что происходит в Couchbase.

От брокера конечно отличает то, что сам Couchbase не хранит историю, и периодически чистит мурсор. Так что полностью одинакового стрима не получится (со временем две операции сольются в одну), но в итоге результат будет одинаковый, если использовать replacing merge.

**Comment by filimonov** [comment]
> ну это да, Couchbase не брокер сообщений, но его данные можно трансформировать в поток изменений, что может быть удобно для анализа. Тот же протокол используется для построения различных индексов в остальных сервисах самого Couchbase, да и внешних инструментов.

Интересно. Не знал, почитаю.

В общем случая для стриминга чего бы то ни было в ClickHouse - можно просто снаружи лить данные в кликсаус. Или какой-то софт - посредник или даже просто pipe в bash.
