### ISSUE TITLE
Support environment variables in config.xml

### ISSUE THREAD

**Issue by abh** [yandex/ClickHouse#1616]
Running under kubernetes it's much easier to configure some details via environment variables.

(deleted example related to interserver_http_host because that turned out to be me misunderstanding the error message I was getting)

**Comment by alexey-milovidov** [comment]
The possible way of implementation:
modify `ConfigProcessor` - add interpreting some attribute, like `from_env`, example:
`<interserver_http_host from_env="HTTP_HOST" />`

**Comment by alesapin** [comment]
done.

**Comment by derekperkins** [comment]
@alesapin What version of ClickHouse was that added to?

**Comment by alexey-milovidov** [comment]
It's not released yet. I expect it to be in 18.5.
