### ISSUE TITLE
Kafka Engine doesn't flush last messages/block

### ISSUE THREAD

**Issue by tobad357** [yandex/ClickHouse#1625]
Clickhouse version: 1.1.54318
Kafka Version: 1.0

When generating messages we notice that the last couple of messages don't get inserted into the linked materialised view. These messages will only appear if more messages arrive from Kafka and flush the block

Example

Generator script (make sure to 'pip install pykafka')
```
#!/usr/local/bin/python

import json
import time
from kafka import KafkaProducer

producer = KafkaProducer(bootstrap_servers='kafka-1:9092', value_serializer=lambda v: json.dumps(v).encode('utf-8'))
for i in range(1,100000):
	milli_sec = int(round(time.time() * 1000))
	producer.send('test_ck', key=str(i), value={'timestamp': milli_sec, 'key': i, 'xxx': 1.222})
```

Tables
```
CREATE TABLE test_kafka_ck (timestamp UInt64, key UInt64, xxx Float32) 
	ENGINE = Kafka('kafka-1:9092', 'test_ck', 'test_group_7', 'JSONEachRow');


CREATE MATERIALIZED VIEW test_kafka_ck_mat (
	day Date,
	key UInt64,
	xxx Float32
)
ENGINE = MergeTree(day, (day, key), 8192) AS
SELECT toDate(toDateTime(timestamp)) AS day, key, amount from test_kafka_ck
```

When this is run we normally will see 
```
select count(*) from test_kafka_ck_mat
```
return around 99800-99950 rows, looking at the system.parts table also shows around that amount

If we then run the generator again the missing rows will appear in the table but now the last rows from the new batch will be missing

The impact on this is mostly when needing to shutdown Clickhouse as the last block never gets flushed to disk while the consumer offset in Kafka shows all messages read

**Comment by vavrusa** [comment]
It's batching 16 messages at a time currently. I'm reworking this to track offsets externally and commit only when it's flushed.

**Comment by tobad357** [comment]
@vavrusa would that also fix the issue where the last messages never get flushed?
Because if I understand your change correctly it will fix the issue where a shutdown causes some messages to get lost but I'm not sure it fixes messages that end up never being flushed?

**Comment by tobad357** [comment]
Sorry for one more request
It would be great to be able to set the offset when creating the Kafka Table
The default could be "latest" but also allow "earliest" and a specific value
That way reprocessing of data would be to just drop the table and recreate with the correct offset

**Comment by vavrusa** [comment]
Yes, it will fix issue with last block not being written on exit (there's a 7500ms flush interval, which you may or may not hit). I don't know about starting offsets, maybe it's going to be supported in the extended configuration tracked in this ticket: https://github.com/yandex/ClickHouse/issues/1402

**Comment by GroundTech** [comment]
@tobad357 
I have started to test the Kafka storage engine. Haven't configured the materialized view, just the Kafka table and seeing all message including the last few in a batch. 

However, performance seems not very good. I am getting about 3K message per second with a table about 180 columns (kafka topic only 1 partition) . Can you share what sort of performance in terms of messages per second are you getting in your case?

**Comment by tobad357** [comment]
@GroundTech how many messages per second can you read from your kafka with a dummy consumer?
I would guess you are hitting the upper limit on what kafka can deliver when only using one partition

**Comment by GroundTech** [comment]
@tobad357 With kafkacat as a dummy consumer such as kafkacat, I can reach 60K messages per second with single partition, much faster than through the kafka clickhouse storage.

**Comment by tobad357** [comment]
@GroundTech then I would try just doing a test with dummy data containing 1 column and see if your speed changes. It could be the IO for clickhouse that is slowing things down

**Comment by tobad357** [comment]
@vavrusa I will close this one as this issue is fixed.
However I've noticed occasional dropped messages when running tests across 500k messages
