### ISSUE TITLE
unittests for clickhouse

### ISSUE THREAD

**Issue by artpaul** [yandex/ClickHouse#163]
As far as I known there is no unittests in ClickHouse. I propose to use googletest as ut framework. It's easy to integrate and use. There is some examples:
https://github.com/artpaul/ClickHouse/commit/9082c2ff2a51318f766932ffd9e086c65c4812e2
https://github.com/artpaul/ClickHouse/commit/1b6bd83894fe92076a31fc096d46f7f06326c228

**Comment by alexey-milovidov** [comment]
For most cases, we rely on functional tests (that are located in `dbms/tests` directory).
Functional tests are run for each commit. Also, tests are run under valgrind each night.
Also we use test environment. As you are in Yandex, look at METR-22953 task.

Unit tests are not mandatory in our team. But we have some.
Look at `add_check` CMake directives and result of `make test` command.

For one of these tests, Boost.Test is used.
Also we share our codebase and guidelines with Yandex.Metrica team, and they have wide usage of Boost.Test. I have no preference for Boost.Test and don't know about possible drawbacks comparing to googletest, but it is not reasonable to use both.

Also we have bunch of test programs, that are not unit tests: some of them require test dataset, some of them are performance tests, and some are utilities or usage examples.

**Comment by artpaul** [comment]
ОК. Thanks for comment.
