### ISSUE TITLE
force_restore_data as setting in config file

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#1645]
Hello,

In my case I need force_restore_data to be true all the time when server starts. As it is right now clickhouse is not possible. The two mechanisms provides using a flag file or zookepeer are both one shot.

I can implement also a setting in config and when is true will have priority in top of the other 2. Are you interested in a PR?

**Comment by alexey-milovidov** [comment]
Try to set merge_tree settings in config:
```
<!-- Settings to fine tune MergeTree tables. See documentation in source code, in MergeTreeSettings.h -->
    <!--
    <merge_tree>
        <max_suspicious_broken_parts>5</max_suspicious_broken_parts>
    </merge_tree>
    -->
```

The list of all settings can be found in `MergeTreeSettings.h`

The relevant settings are:
`max_suspicious_broken_parts`
`replicated_max_ratio_of_wrong_parts`

**Comment by silviucpp** [comment]
Hello @alexey-milovidov Yes it's true I can tune that settings in order to make sure I will never rich this issue. But it's not ok to add in the settings `skip_sanity_checks` as well ?

**Comment by alexey-milovidov** [comment]
This hypothetical feature shouldn't be recommended in typical usage scenarios, so configuration with `max_suspicious_broken_parts` and similar settings is enough.
