### ISSUE TITLE
insert freezing because of a deadlock

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#1648]
Hello guys,

While running some massive load testing where we insert in a replicated table batches of 3000 records we all the time have the problem that at some point insert is freezing.

Idea is that I'm sure is not the problem of the fact that there are too many partitions to be merged. Why I believe this is because there is nothing in logs telling that are too many partitions and insert will be delayed (as we have when this issue occur)

Today I replicated this issue on my development machine and I was able to get a stack:

In image number 1 you can see the http thread being blocked in `storage.merge_selecting_handle->schedule();`
which means `merge_selecting_handle` it's in progress (`mergeSelectingThread` function).

Looking to this `mergeSelectingThread` function it's blocking in `pullLogsToQueue();` which means another operation is running on another thread (see image 2)

After I identified this thread (image 3) I found out that's locked in zookeper operation:
`zkutil::ZooKeeper::ValueAndStat res = future.second.get();`

The only zookeper thread I see is in image 4 and waits for `queue_updating_task_handle`

I'm still searching for the problem but maybe you have other ideas on what can be

![1](https://user-images.githubusercontent.com/4814731/34036047-af9cfa0c-e18c-11e7-9e33-37e44fe8450f.png)
![2](https://user-images.githubusercontent.com/4814731/34036048-afb9bf48-e18c-11e7-9b62-a83300cbbe7f.png)
![3](https://user-images.githubusercontent.com/4814731/34036049-afd6cf48-e18c-11e7-8bcb-ed20f43995dd.png)
![4](https://user-images.githubusercontent.com/4814731/34036050-aff1249c-e18c-11e7-950f-04c7e62f7825.png)

**Comment by silviucpp** [comment]
My initial conclusion (still working) is:

Zookeper it's using 1 thread to deliver the callbacks. Inside the callback is calling the schedule method for a task that it's already in progress (lock is acquired) . The task also it's waiting for a sync operation in zookeper 

For here we have a deadlock.

**Comment by silviucpp** [comment]
@alexey-milovidov any sugestion on how we fix this ? for me at least in this point seems clear that deadlock occur when a task it's scheduled by zookeper completion callback and in the same time same task it's waiting on an async zookeper operation to complete via a future.

One idea I have is to call from zookeper callback the scheduleAfter method from background schedule pool for that task. 

This should work

Silviu

**Comment by silviucpp** [comment]
So I have a fix that finally seems not blocking any longer during my load tests:

Change scheduleAfter in the following mode (we can make it void)

```c++
bool BackgroundSchedulePool::TaskInfo::scheduleAfter(size_t ms)
{
    pool.scheduleDelayedTask(shared_from_this(), ms);
    return true;
}
```

Basically there is not problem that we don't check if task is already scheduled or disposed. The schedule method once called by delayed tasks thread will do this. I don't see any impact in this change. Let me know if you have better ideas

**Comment by alexey-milovidov** [comment]
Looks reasonable. Thank you!

**Comment by silviucpp** [comment]
I'll close. I already tested a lot this and fix seems good and no performance regression

**Comment by alexey-milovidov** [comment]
The issue is closed automatically as pull request is merged :)
