### ISSUE TITLE
GraphiteMergeTree has no English documentation

### ISSUE THREAD

**Issue by AlekSi** [yandex/ClickHouse#1660]
https://clickhouse.yandex/docs/ru/table_engines/graphitemergetree.html is there, but https://clickhouse.yandex/docs/en/table_engines/graphitemergetree.html returns 404.

**Comment by filimonov** [comment]
You can help the project by translating that page.  Documentation is inside docs folder of the main Clickchouse repo.

**Comment by AlekSi** [comment]
Are you sure? Last time I asked about that, I was told that developers write Russian documentation, then tech writers from Yandex translate it. So no changes should be made to English docs as they will be overwritten.

**Comment by alexey-milovidov** [comment]
> developers write Russian documentation, then tech writers from Yandex translate it.

Exactly.

Right now, https://github.com/krishnevsky has finished translating all accumulated changes and we are going to publish them after we will solve some minor technical issues. Then the process of translation will go smoother.

> So no changes should be made to English docs as they will be overwritten.

That's not correct. You can change english docs and our translator will not overwrite your changes (just review and probably translate back to russian if needed).

**Comment by filimonov** [comment]
There was quite big migration of docs from one format to another. During such a migrations some edits can be lost.

Generally the best way is to change in both languages at the same time. But it requires perfect knowedge of both languages, which is not quite common.

But fortunatelly git is a really nice tool to deal with concurrent edits, and if your edit (in any langyage) is really good quality and helpfull it will not disappear.

**Comment by AlekSi** [comment]
This is done now: https://clickhouse.yandex/docs/en/table_engines/graphitemergetree/
