### ISSUE TITLE
[Question] replicated + distributed, two types, which is recommended

### ISSUE THREAD

**Issue by Jaxvk** [yandex/ClickHouse#1664]
Target is two replicas, two shards
four machiness: clickhouse-6, clickhouse-7, clickhouse-8, clickhouse-9
    
## one way
clickhouse-6 -- replicatedmergetree table -- shard 1
clickhouse-7 -- replicatedmergetree table -- shard 2
clickhouse-8 -- replicatedmergetree table -- shard 1
clickhouse-9 -- replicatedmergetree table -- shard 2

#### the clickhouse-6, clickhouse-7's distributed table config are same, as bellow
```
<sharovara>
	<shard>
		<internal_replication>true</internal_replication>
		<replica>
          	<host>clickhouse-6</host>
          	<port>9000</port>
          </replica>
	</shard>
	<shard>
          <replica>
          	<host>clickhouse-7</host>
          	<port>9000</port>
          </replica>
	</shard>			
</sharovara>
```
#### the clickhouse-8, clickhouse-9's distributed table config are same, as bellow
```
<sharovara>
	<shard>
		<internal_replication>true</internal_replication>
		<replica>
          	<host>clickhouse-8</host>
          	<port>9000</port>
          </replica>
	</shard>
	<shard>
          <replica>
          	<host>clickhouse-9</host>
          	<port>9000</port>
          </replica>
	</shard>			
</sharovara>
```
## the another way
clickhouse-6 -- replicatedmergetree table -- shard 1
clickhouse-7 -- replicatedmergetree table -- shard 2
clickhouse-8 -- replicatedmergetree table -- shard 1
clickhouse-9 -- replicatedmergetree table -- shard 2
#### the clickhouse-6, clickhouse-7, clickhouse-8, clickhouse-9's distributed table config are same, as bellow
```
<sharovarb>
	<shard>
		<internal_replication>true</internal_replication>
		<replica>
			<host>clickhouse-6</host>
			<port>9000</port>
		</replica>
		<replica>
			<host>clickhouse-8</host>
			<port>9000</port>
		</replica>
	</shard>
	<shard>
		<replica>
			<host>clickhouse-7</host>
			<port>9000</port>
		</replica>
		<replica>
			<host>clickhouse-9</host>
			<port>9000</port>
		</replica>
	</shard>
</sharovarb>
```
## question
1, What are the differences between the two ways ？
2, Which way is recommended ？

thank you very match :+1:

**Comment by KochetovNicolai** [comment]
1. Let's say that you want to insert into and read from distributed table on `clickhouse-6` node. At the first way, you will always use `clickhouse-6` and `clickhouse-7`. At the second way, for each query `clickhouse-7` or `clickhouse-9` can be chosen (`clickhouse-6` is local, so it has priority under `clickhouse-8`). It can reduce load for simultaneously running queries.
2. So, the second way is better. Also, you can just copy the same config.
Do not forget to add <internal_replication>true</internal_replication> for the second shard:
```
<sharovarb>
	<shard>
		<internal_replication>true</internal_replication>
		<replica>
			<host>clickhouse-6</host>
			<port>9000</port>
		</replica>
		<replica>
			<host>clickhouse-8</host>
			<port>9000</port>
		</replica>
	</shard>
	<shard>
		<internal_replication>true</internal_replication> <!-- here  -->
		<replica>
			<host>clickhouse-7</host>
			<port>9000</port>
		</replica>
		<replica>
			<host>clickhouse-9</host>
			<port>9000</port>
		</replica>
	</shard>
</sharovarb>
```

**Comment by Jaxvk** [comment]
@KochetovNicolai  I see, thank you. :+1:
