### ISSUE TITLE
UNION ALL - performance question

### ISSUE THREAD

**Issue by AlexMAS** [yandex/ClickHouse#1666]
Hello guys!

It's seems that I have to combine two data set, both of which are gotten by executing `SELECT` statement. I've just seen that ClickHouse can do `UNION ALL` and it's can be appropriate for me. But I'm not sure about its performance in general case. Would you recommend to use `UNION ALL` statement or it was added for the functional completeness? Yes I know it depends on a specific case but as the database developer you may know all pros and cons of using this clause. May be there are advice when it can be appropriate to use `UNION ALL` statement.

Fix me if I'm wrong. A query with `UNION ALL` forces the database node which received this query aggregates data sets in the memory. So it can be cause memory overuse on a database nodes. Also it can add unnecessary computation especially when you union data sets with different columns. Finally your logic of data union can be change in the future. The main advantage `UNION ALL` is possibility to process data by one round trip to the database.

Personally I decided not to use `UNION ALL` because my logic of data union can be changed. But anyway I'm very interesting about your recommendation.

**Comment by filimonov** [comment]
I never looked in code how exactly it works, but I'm using UNION ALL a lot and it just works - fast and without any problems. The way how clickhouse store data in ONE table (multiple parts which should be read at the same time) is quite similar to the case when you need to read multiple tables.

The only problem for me with UNION ALL - is that you need to pass WHERE conditions to both SELECTs separately. 

Small performance check on my data:
```
:) select count() from tableA  where date>today() - 30;
┌───count()─┐
│ 302539708 │
└───────────┘

1 rows in set. Elapsed: 0.109 sec. Processed 332.76 million rows, 665.52 MB (3.04 billion rows/s., 6.08 GB/s.) 

:) select count() from tableB where date>today() - 30;
┌───count()─┐
│ 930953700 │
└───────────┘

1 rows in set. Elapsed: 0.309 sec. Processed 969.66 million rows, 1.94 GB (3.13 billion rows/s., 6.27 GB/s.) 

:) select count() from ( select date FROM tableA where date>today() - 30 UNION ALL select date FROM tableB where date>today() - 30 );
┌────count()─┐
│ 1233493408 │
└────────────┘

1 rows in set. Elapsed: 0.450 sec. Processed 1.30 billion rows, 2.60 GB (2.89 billion rows/s., 5.78 GB/s.) 
```

**Comment by AlexMAS** [comment]
@filimonov Thank you. Nice to hear that it works fine.

P.s. To the developers: If there are nothing to add, this issue can be closed.

**Comment by blinkov** [comment]
As far as I know, most people are satisfied with UNION ALL performance of ClickHouse.
