### ISSUE TITLE
[Question] how to choose between MergeTree and ReplicaMergeTree

### ISSUE THREAD

**Issue by Jaxvk** [yandex/ClickHouse#1667]
When Insert datas to the replicated tables, it delete data which has the same primary key.
But I don't need the feature, can close it?

**Comment by KochetovNicolai** [comment]
Primary key in ClickHouse uses for sorting and it may duplicate. As MergeTree, as ReplicaedMergeTree doesn't delete data with the same primary key.
Only ReplicatedMergeTree deletes duplicating **parts** if they are exactly the same. You can add timestamp to your data to avoid situations when you want to insert the same rows. (or set `replicated_deduplication_window=0` to disable deduplication at all)

**Comment by Jaxvk** [comment]
@KochetovNicolai 
:+1:  yes, this helped me a lot, thank you

**Comment by KochetovNicolai** [comment]
Yes, `replicated_deduplication_window` is for every `Replicated*MergeTree` engine.

**Comment by Jaxvk** [comment]
ok, I see.
