### ISSUE TITLE
ALTER TABLE ... UPDATE

### ISSUE THREAD

**Issue by allyraza** [yandex/ClickHouse#167]
Hi, is it possible to update records in a table?

**Comment by hatarist** [comment]
Kind of. There's no UPDATE statements. There are several choices though:

1) [CollapsingMergeTree](https://clickhouse.yandex/reference_en.html#CollapsingMergeTree) or [ReplacingMergeTree](https://github.com/yandex/ClickHouse/blob/1d836b2bf8fef378d47258957ff74ed3a4aff136/dbms/tests/queries/0_stateless/00325_replacing_merge_tree.sql) (this one isn't documented, see an example in the sources)

2) table renaming. create a new table, insert the updated data to it (insert the unchanged one too), drop the old table, rename the new table. you should make sure that no data is inserted in between (basically, create a lock on your side of the application).

**Comment by allyraza** [comment]
I see but we already have several billion records we can't simply move data in out of tables effects our production system, all this time our operations were append only now we need to update to cater for new feature, do you guys have any plans to implement update and delete operation/queries.

**Comment by alexey-milovidov** [comment]
We have plans for delete. (Currently without schedule, I expect in Q2 2017)

**Comment by goranc** [comment]
Just idea for possible update/delete option with MergeTree family tables.
Delete can be covered using ReplacingMergeTree with functionality of version field of int type, just to allow using of -1 for deletion on merge. When merge is triggered then just skip record from main part when there is new part with -1 version.

**Comment by kszucs** [comment]
@alexey-milovidov is Q2 2017 still actual?

**Comment by alexey-milovidov** [comment]
This estimate is outdated :( Now we expect it not sooner than Q4 2017.

**Comment by shahbour** [comment]
@alexey-milovidov is it still on road map the delete

**Comment by quba** [comment]
@alexey-milovidov any update on this? [GDPR is coming](https://gdpr-info.eu/art-17-gdpr/).

**Comment by meshpaul** [comment]
Is there any update on this feature... is this 2018 or will it make it in 2017 Q4.. We are looking for limited capability example would be a look up table but to update just the record without drop, rename whole table data.

**Comment by alexey-milovidov** [comment]
In first step, we will implement "batch updates", probably under a special syntax like "ALTER ... UPDATE/DELETE", that will perform updates rather suboptimal but without any sacrifice of SELECT performance.

In second step, we will apply some techniques to support short-running updates with little (if any) impact on SELECT performance.

This is the first task in a queue for one of developers.

**Comment by meshpaul** [comment]
@alexey-milovidov класс спасибо

**Comment by menvil** [comment]
@alexey-milovidov Отличная новость. Давайте очень нужно.

**Comment by blackush** [comment]
@alexey-milovidov awesome product! 
there is any chance for update / delete in the near future ?

**Comment by AlekSi** [comment]
See https://github.com/yandex/ClickHouse/pull/2366 for initial DELETE implementation.

**Comment by blinkov** [comment]
FYI: this feature is currently on code review at #3035

**Comment by simPod** [comment]
I have a question. Shouldn't the UPDATE and DELETE propagate to materialized views as well?

**Comment by ztlpn** [comment]
> I have a question. Shouldn't the UPDATE and DELETE propagate to materialized views as well?

Well in theory that would be nice, but I don't see how this could be realized in practice. Materialized views often store aggregated data and deleting/modifying data inside aggregate function states is in general impossible.

Materialized views are INSERT triggers that have been misnamed.

**Comment by ztlpn** [comment]
ALTER UPDATE feature has been released in v18.12.14.

**Comment by simPod** [comment]
I see, you're right. Thanks!

**Comment by charmingcode** [comment]
> ALTER UPDATE feature has been released in v18.12.14.

why master not contain the code of ApplyingMutationsBlockInputStream?

**Comment by ztlpn** [comment]
> why do not master contain the code of ApplyingMutationsBlockInputStream?

ApplyingMutationsBlockInputStream was removed. Look into dbms/src/Interpreters/MutationsInterpreter.h/.cpp for the relevant logic.
