### ISSUE TITLE
[Question] how to configure replica doesn't accept request when it is recovering

### ISSUE THREAD

**Issue by Jaxvk** [yandex/ClickHouse#1675]
Hi, :sake: 

## cluster config
```
Two IDCs
one contains: CH-6, CH-7
one contains: CH-8, CH-9
```
##### CH-6 CH-7 config
```
CH-6
ReplicatedMergeTree('/clickhouse/tables/sharded/1' ....)

CH-7
ReplicatedMergeTree('/clickhouse/tables/sharded/2' ....)
<sharovara>
	<shard>
		<replica>
	      	<host>CH-6</host>
	      	<port>9000</port>
	      </replica>
	</shard>
	<shard>
	      <replica>
	      	<host>CH-7</host>
	      	<port>9000</port>
	      </replica>
	</shard>			
</sharovara>
```

##### CH-8 CH-9 config
```
CH-8
ReplicatedMergeTree('/clickhouse/tables/sharded/1' ....)

CH-9
ReplicatedMergeTree('/clickhouse/tables/sharded/2' ....)
<sharovara>
	<shard>
		<replica>
	      	<host>CH-8</host>
	      	<port>9000</port>
	      </replica>
	</shard>
	<shard>
	      <replica>
	      	<host>CH-9</host>
	      	<port>9000</port>
	      </replica>
	</shard>			
</sharovara>
```
## normal, every machine is ok, like this
![normal](https://user-images.githubusercontent.com/20113411/34195000-006ad2d2-e521-11e7-94b8-ef6c5f547e12.png)

## abnormal, for instance, CH-9 down, when recovering, client will get different datas
![revoverying](https://user-images.githubusercontent.com/20113411/34195059-4acb8c68-e521-11e7-9e4a-1403d52cd44f.png)

## question?
```
Can configure the clickhouse-server don't to accept request when it copying data from other replica？
this will cause data inconsistencies
```

**Comment by tacyuuhon** [comment]
@Jaxvk I think you need a  proxy.
Maybe [chproxy](https://github.com/Vertamedia/chproxy) can help you.

**Comment by filimonov** [comment]
> @Jaxvk I think you need a proxy.

As I understand proxy will not help in described case. It's a matter of choosing healthy replica for distributed requests inside cluster, not about connecting to the cluster from outside.

> Can configure the clickhouse-server don't to accept request when it copying data from other replica？this will cause data inconsistencies

May decreasing of `max_replica_delay_for_distributed_queries` or disabling `fallback_to_stale_replicas_for_distributed_queries` will help? Unfortunately description of that settings is available only in source code or in docs in Russian language.

**Comment by Jaxvk** [comment]
@filimonov , thank you
but which config file to set `fallback_to_stale_replicas_for_distributed_queries`  and `fallback_to_stale_replicas_for_distributed_queries`
```
config.xml or metrika.xml or users.xml ?
```

**Comment by filimonov** [comment]
users.xml

**Comment by Jaxvk** [comment]
ok, I see.

**Comment by Jaxvk** [comment]
I test the config last week, yes, it's ok
