### ISSUE TITLE
few questions

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#1677]
Hello,

I have few questions regarding clickhouse:

1.What is doing `distributed_directory_monitor_batch_inserts` ? In case you have it enable and write via a distributed table you don't have to batch the inserts on the client side ?

2. In case of a replicated table where `partition` is `Date` type and also the primary key is a timestamp of `DateTime`, when you have to search in a certain interval it's better to put in the where clause both ? I mean filter partiton and the timestamp field ? helps somehow ? or it's enough to filter by the timestamp field

Silviu

**Comment by KochetovNicolai** [comment]
1. No, you still need to batch the inserts on the client side. 
By default, when you insert data into distributed table, it firstly stores inserted batch as a part on local file system (or set of parts). Then, distributed table sends each part to remote node. 
When `distributed_directory_monitor_batch_inserts` is enabled, distributed table groups parts for the same node into batch and uses single connection, which is usually more effective.
However, without batching the inserts on the client side, you will have a lot of small files on local file system.
2. If you have `timestamp DateTime` which is in primary key and partition key like `toDate(timestamp)`, that it's not necessary to use condition with date. If `timestamp` has no connection with partition key, then use both condition.

**Comment by silviucpp** [comment]
Hello @KochetovNicolai ,

Thanks a lot for your answers. In my case partition is toDate(timestamp) so becomes pointless
I initially thought it helps on selecting the partitions that needs to scan but seems only primary key is used. Also in case the primary key is composed from multiple fields when I filter it matters the order I specify them ? Like in SQl database ? I mean if yo have an index (a,b) you need to filter a =? & b = ? not b= ? & a = ?

Silviu

**Comment by silviucpp** [comment]
Thanks a lot !
