### ISSUE TITLE
Precision of floating point division is inconsistent

### ISSUE THREAD

**Issue by dqminh** [yandex/ClickHouse#1678]
We have a query that does calculation of seconds from milliseconds like

```
sum(query_duration_ms / 1000 ) 
```

The expectation was that sum(query_duration_ms) is a counter, so the results cant go down. However, we had some results like:

```
5847929.7020000005 @1513782047.633
5847929.702 @1513782107.633
```

As the latter is smaller then the former, this produces some unexpected result when calculating rate of changes for the counter.

cc @bobrik @vavrusa @bocharov

**Comment by KochetovNicolai** [comment]
Even for the same query on the same data the order of parts which are reading is not fixed. (Also, some parts may be merged between queries.)
If the order of parts is not fixed, the order of summation is also arbitrary. For floating point numbers different orders may get slightly different results.

If you want to get same result, you can sum int values:
```
sum(intDiv(query_duration_ms, 1000 ))
```

**Comment by filimonov** [comment]
Aslo - it's better to sum integers (it's more effecient), and make division at the end.
You can get required precision by using round function.

So:
```sql
SELECT round(sum(query_duration_ms)/1000, 3)
```

**Comment by alexey-milovidov** [comment]
Added aggregate function `sumKahan`. It will sum floating point numbers more accurately,
though it is slower (up to 1.5 times) and it is also non-deterministic.

https://github.com/yandex/ClickHouse/commit/609133ea01803379e340e4c9658d276ea7ac4f9e#diff-c6bed5bbf8de99a2db278556cf47bb18
