### ISSUE TITLE
Zookeeper leak complaints are overly agressive

### ISSUE THREAD

**Issue by bobrik** [yandex/ClickHouse#1680]
I'm talking about these:

```
2017.12.20 23:42:44.483618 [ 1532 ] <Error> ZooKeeper: There are 10000 active watches. There must be a leak somewhere.
```

https://github.com/yandex/ClickHouse/blob/b08463ed7bbfbac/dbms/src/Common/ZooKeeper/ZooKeeper.cpp#L225-L228

We have a constant stream of these, because we're hovering around 10k watches:

![image](https://user-images.githubusercontent.com/89186/34233965-20018c22-e59d-11e7-9d65-031cd4139e59.png)

cc @dqminh @vavrusa

**Comment by alexey-milovidov** [comment]
Fixed long time ago.
