### ISSUE TITLE
Syntax error occurs when you try to insert a result of SELECT using WITH into a table

### ISSUE THREAD

**Issue by mikageymir** [yandex/ClickHouse#1682]
Syntax error occurs when you try to insert a result of SELECT using WITH into a table.

<pre>
:) WITH number * 2 AS num2 SELECT number, num2 FROM system.numbers LIMIT 3;

WITH number * 2 AS num2
SELECT
    number,
    num2
FROM system.numbers
LIMIT 3

┌─number─┬─num2─┐
│      0 │    0 │
│      1 │    2 │
│      2 │    4 │
└────────┴──────┘

3 rows in set. Elapsed: 0.007 sec.

:) CREATE TABLE test_number (number UInt64, num2 UInt64) ENGINE = Log;

CREATE TABLE test_number
(
    number UInt64,
    num2 UInt64
)
ENGINE = Log

Ok.

0 rows in set. Elapsed: 0.015 sec.

:) INSERT INTO test_number WITH number * 2 AS num2 SELECT number, num2 FROM system.numbers LIMIT 3;

Syntax error: failed at position 25:

INSERT INTO test_number WITH number * 2 AS num2 SELECT number, num2 FROM system.numbers LIMIT 3;

Expected one of: VALUES, FORMAT, OpeningRoundBracket, Dot, token, SELECT

:) INSERT INTO test_number SELECT number, number * 2 AS num2 FROM system.numbers LIMIT 3;

INSERT INTO test_number SELECT
    number,
    number * 2 AS num2
FROM system.numbers
LIMIT 3

Ok.

0 rows in set. Elapsed: 0.012 sec.
</pre>

**Comment by KochetovNicolai** [comment]
Also you can use subquery as a workaround:
```SQL
INSERT INTO test_number SELECT * FROM (WITH number * 2 AS num2 SELECT number, num2 FROM system.numbers LIMIT 3)
```
