### ISSUE TITLE
When you INSERT a result of JOIN to a table, the server does not validate the schema of the destination table and crashes if they mismatch.

### ISSUE THREAD

**Issue by mikageymir** [yandex/ClickHouse#1683]
When you INSERT a result of JOIN to a table, the server does not validate the schema of the destination table and crashes if they mismatch.

<pre>
ClickHouse client version 1.1.54289.
Connecting to 127.0.0.1:9000 as user ymirlink.
Connected to ClickHouse server version 1.1.54289.

// Preparation of the test data
:) CREATE TABLE test1 ( id String ) ENGINE = StripeLog;
:) CREATE TABLE test2 ( id String ) ENGINE = StripeLog;
:) INSERT INTO test2 VALUES ('a');
:) CREATE TABLE test3 ( id String, name String ) ENGINE = StripeLog;
:) INSERT INTO test3 VALUES ('a', 'aaa');

:) INSERT INTO test1 SELECT id, name FROM test2 ANY INNER JOIN test3 USING (id);

INSERT INTO test1 SELECT
    id,
    name
FROM test2
ANY INNER JOIN test3 USING (id)

Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from 127.0.0.1:9000

Connecting to 127.0.0.1:9000 as user ymirlink.
Code: 210. DB::NetException: Connection refused: (127.0.0.1:9000)

Also happens for queries like this:
INSERT INTO test1 SELECT id, name FROM test2 ANY LEFT OUTER JOIN test3 USING (id);

Snippet from clickhouse-server.log:
2017.12.21 17:21:22.409151 [ 22 ] <Error> BaseDaemon: ########################################
2017.12.21 17:21:22.409209 [ 22 ] <Error> BaseDaemon: (from thread 6) Received signal Segmentation fault (11).
2017.12.21 17:21:22.409227 [ 22 ] <Error> BaseDaemon: Address: NULL pointer.
2017.12.21 17:21:22.432701 [ 22 ] <Error> BaseDaemon: 0. /usr/bin/clickhouse-server() [0x357c553]
2017.12.21 17:21:22.432806 [ 22 ] <Error> BaseDaemon: 1. /usr/bin/clickhouse-server(DB::isConvertableTypes(std::shared_ptr<DB::IDataType> const&, std::shared_ptr<DB::IDataType> const&)+0x35) [0x357c635]
2017.12.21 17:21:22.432831 [ 22 ] <Error> BaseDaemon: 2. /usr/bin/clickhouse-server(DB::NullableAdapterBlockInputStream::buildActions(DB::Block const&, DB::Block const&)+0xfc) [0x3536abc]
2017.12.21 17:21:22.432854 [ 22 ] <Error> BaseDaemon: 3. /usr/bin/clickhouse-server(DB::NullableAdapterBlockInputStream::NullableAdapterBlockInputStream(std::shared_ptr<DB::IBlockInputStream> const&, DB::Block const&, DB::Block const&)+0x7a) [0x353862a]
2017.12.21 17:21:22.432877 [ 22 ] <Error> BaseDaemon: 4. /usr/bin/clickhouse-server(DB::InterpreterInsertQuery::execute()+0xb8a) [0x34a0afa]
2017.12.21 17:21:22.432908 [ 22 ] <Error> BaseDaemon: 5. /usr/bin/clickhouse-server() [0x300dd4c]
2017.12.21 17:21:22.432954 [ 22 ] <Error> BaseDaemon: 6. /usr/bin/clickhouse-server(DB::executeQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum)+0x138) [0x300ecd8]
2017.12.21 17:21:22.432977 [ 22 ] <Error> BaseDaemon: 7. /usr/bin/clickhouse-server(DB::TCPHandler::runImpl()+0x5ed) [0x137e05d]
2017.12.21 17:21:22.432994 [ 22 ] <Error> BaseDaemon: 8. /usr/bin/clickhouse-server(DB::TCPHandler::run()+0x2b) [0x137ebfb]
2017.12.21 17:21:22.433010 [ 22 ] <Error> BaseDaemon: 9. /usr/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x3aa8a7f]
2017.12.21 17:21:22.433027 [ 22 ] <Error> BaseDaemon: 10. /usr/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x13b) [0x3aaeebb]
2017.12.21 17:21:22.433043 [ 22 ] <Error> BaseDaemon: 11. /usr/bin/clickhouse-server(Poco::PooledThread::run()+0xb7) [0x3d19d87]
2017.12.21 17:21:22.433060 [ 22 ] <Error> BaseDaemon: 12. /usr/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0xa5) [0x3ce5dc5]
2017.12.21 17:21:22.433076 [ 22 ] <Error> BaseDaemon: 13. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7fe4b3a936ba]

</pre>

**Comment by alexey-milovidov** [comment]
In master version, it is Ok for both queries (returns correct error message):

```
:) INSERT INTO test.test1 SELECT id, name FROM test.test2 ANY INNER JOIN test.test3 USING (id);

INSERT INTO test.test1 SELECT 
    id, 
    name
FROM test.test2 
ANY INNER JOIN test.test3 USING (id)

Received exception from server (version 1.1.54326):
Code: 20. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Number of columns in INSERT SELECT doesn't match. 

0 rows in set. Elapsed: 0.023 sec. 

:) INSERT INTO test.test1 SELECT id, name FROM test.test2 ANY LEFT OUTER JOIN test.test3 USING (id);

INSERT INTO test.test1 SELECT 
    id, 
    name
FROM test.test2 
ANY LEFT JOIN test.test3 USING (id)

Received exception from server (version 1.1.54326):
Code: 20. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Number of columns in INSERT SELECT doesn't match. 

0 rows in set. Elapsed: 0.017 sec.
```
