### ISSUE TITLE
[Question] Execute query on the specified replica in shard

### ISSUE THREAD

**Issue by igor-sh8** [yandex/ClickHouse#1684]
Hi. 
Maybe someone can help me. 
I have configuration of two shards with two replicas in each shard. 
I created Distributed table on two nodes (on one of each shard).
But when I run some SELECT queries clickhouse distribute it on all four nodes (on all replicas). Is there any way to restrict executing query only on nodes with created distributed table ? For example, I have 4 nodes (2 shards with 2 replicas) and I want that my query execute only on first node in each shard (execute only on two nodes).
I read about max_parallel_replicas but it set only the number of replica nodes on which the query execute but I can not set on which node from replica nodes this query execute.

**Comment by KochetovNicolai** [comment]
Hi.
Yes, you can achieve it. Just create another cluster configuration with only first replica per shard. And create other distributed table on that cluster (only for reading).

**Comment by igor-sh8** [comment]
Thanks for advice. This is really an interesting way. 
But what about the situation when one of those two nodes falls? As I understand SELECT query returns only a part of data that is stored on one shard. Maybe there are something like weights for the replicas in shard ?

**Comment by KochetovNicolai** [comment]
You can set `load_balancing='in_order'` setting and replicas will be accessed in the same order as they are specified in cluster config.
If all replicas in shard are unavailable, exception is thrown. You can enable `skip_unavailable_shards=1` setting in order to skip unavailable data silently.

**Comment by igor-sh8** [comment]
If I set load_balancing='in_order' does it applies only to SELECT queries or also to INSERT queries ?
If I have <internal_replication>false</internal_replication> will the data be always written to the first replica and automatically replicated to second one ?

**Comment by KochetovNicolai** [comment]
`load_balancing` applies also to INSERT queries. But you can apply setting for single query with SETTINGS keyword.

`internal_replication` is for Distributed table on ReplicatedMergeTree. If `internal_replication=1` distributed table will insert data only into one replica for each shard (according to `load_balancing` ) and ReplicatedMergeTree table does replication internally.
 If `internal_replication=1` then Distributed table inserts into each replica. It's correct for ordinary table engines, but with Replicated*MergeTree leads to duplicating data.

**Comment by alexey-milovidov** [comment]
With `internal_replication = false`, the setting `load_balancing` doesn't matter for INSERTs as all replicas are used.

**Comment by igor-sh8** [comment]
That's cool. It works for me.
Thanks for help.

**Comment by MeteHanC** [comment]
So what is the best way to create a cold replica? I just want to create a replica to keep the data but I don't want CH to query that replica? For a workaround I can write a script to make daily insertions manually to the cold replica or   enable & disable clickhouse(which is Configured as a replica as well) daily to get the replicated data but these are obviously not a good way to go. @alexey-milovidov
