### ISSUE TITLE
Больше доки для FileStorage

### ISSUE THREAD

**Issue by arturgspb** [yandex/ClickHouse#1685]
Вот из доки непонятно как это дело подключить.
Хорошо бы хоть один пример с CREATE TABLE для TSV.

https://clickhouse.yandex/docs/en/table_engines/file.html
https://clickhouse.yandex/docs/ru/table_engines/file.html

**Comment by KochetovNicolai** [comment]
Можем создать таблицу с движком File:
```SQL
:) create table test_file_engie (number UInt64, string String) engine = File(TSVWithNames)

CREATE TABLE test_file_engie
(
    number UInt64, 
    string String
)
ENGINE = File(TSVWithNames)

Ok.

0 rows in set. Elapsed: 0.017 sec. 
```
И работать с ней  как с обычной таблицей. например, вставить несколько строк:
```SQL
:) insert into test_file_engie select number, toString(number) from system.numbers limit 10

INSERT INTO test_file_engie SELECT 
    number, 
    toString(number)
FROM system.numbers 
LIMIT 10

Ok.

0 rows in set. Elapsed: 0.007 sec. 

:) select * from test_file_engie

SELECT *
FROM test_file_engie 

┌─number─┬─string─┐
│      0 │ 0      │
│      1 │ 1      │
│      2 │ 2      │
│      3 │ 3      │
│      4 │ 4      │
│      5 │ 5      │
│      6 │ 6      │
│      7 │ 7      │
│      8 │ 8      │
│      9 │ 9      │
└────────┴────────┘

10 rows in set. Elapsed: 0.005 sec. 
```
Тогда в каталоге с данными появится файл соответствующего формата.
```bash
$ sudo ls /var/lib/clickhouse/data/default/test_file_engie
data.TSVWithNames
$ sudo cat /var/lib/clickhouse/data/default/test_file_engie/data.TSVWithNames
number	string
0	0
1	1
2	2
3	3
4	4
5	5
6	6
7	7
8	8
9	9
```

**Comment by alexey-milovidov** [comment]
You can also attach your existing file, but it must be:
- located exactly in the path of the table;
- named like `data.format`, where format is, for example, `TSV`;
- accessible for the `clickhouse` user.

**Comment by arturgspb** [comment]
А на сколько это быстро работает?
Например можно ли так подложить справочник кампаний/клиентов или статистику по рекламным кампаниям по месяцам? =)

На сколько это будет проигрывать по скорости обычным таблицам и внешним справочникам (да, я знаю, что справочники это key-value)?

**Comment by alexey-milovidov** [comment]
Во время SELECT, файл читается и данные парсятся каждый раз из указанного формата.
Данные читаются в один поток. Файл читается целиком - индексов нет.

Таким образом, время обработки любого SELECT не сильно отличается от времени, которое было бы потрачено, если эти данные загрузить в другую таблицу.

Вывод - если из таблицы нужно делать хотя бы несколько SELECT-ов, то эффективнее загрузить хотя бы в таблицу типа Log/TinyLog/StripeLog (если данные загружаются один раз, а затем удаляются); а для серьёзных применений - MergeTree.

**Comment by alexey-milovidov** [comment]
Мотивация для существования таблиц типа File такая:
1. Основная: Они используются в качестве внутреннего механизма для работы программы `clickhouse-local`.
2. Дополнительные возможности: Чтобы мгновенно сделать доступным в сервере небольшой файл в подготовленном формате. Можно использовать для мелких таблиц, если нужно смотреть на них в файловой системе глазами или каким-то скриптом (но как правило это хуже, чем просто сделать SELECT). Как один из способов создания дампов на стороне сервера.

**Comment by arturgspb** [comment]
Все понял, спасибо!
