### ISSUE TITLE
Enter query of "SELECT CAST(1 AS Enum8);" brings down clickhouse-server

### ISSUE THREAD

**Issue by jamesfu8** [yandex/ClickHouse#1688]
We installed clickhouse in docker container on Centos 7 server.  Entering query "SELECT CAST(1 AS Enum8)" in clickhouse-client brings down the clickhouse-server in container. It is also noticed that a clickhouse-server daemon is started directly. 

clickhouse-client -m
ClickHouse client version 1.1.54310.
Connecting to localhost:9000.
Connected to ClickHouse server version 1.1.54310.
:) select cast(1 as Enum8);

SELECT CAST(1 AS Enum8)

Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000, 127.0.0.1

Connecting to localhost:9000.
Code: 210. DB::NetException: Connection reset by peer: while reading from socket (127.0.0.1:9000)

[james.fu@p933.dev ~]$ ps -ef | grep clickhouse
clickho+  223057       1  0 07:00 ?        00:00:00 clickhouse-server --daemon --pid-file=/var/run/clickhouse-server/clickhouse-server.pid --config-file=/etc/clickhouse-server/config.xml
james.fu  223857  205065  0 07:00 pts/0    00:00:00 grep --color=auto clickhouse

Normally it should be:
ps -ef | grep clickhouse
james.fu  209491  194928  0 23:42 pts/0    00:00:00 grep --color=auto clickhouse
105       982153  982136  0 19:26 ?        00:00:17 /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml

**Comment by alexey-milovidov** [comment]
622f0b62e038e1b8fc1d10d3d2e782ce4e553105
b9ca36e5ad530e9488cc501d522f5aad8126d5ed
