### ISSUE TITLE
Check flags when run Clickhouse

### ISSUE THREAD

**Issue by patsevanton** [yandex/ClickHouse#1695]
Hello!
I try run Clickhouse on old CPU, but get error:
`Illegal instruction`
I found Clickhouse required CPU flag SSE 4.2.
Can add check flags when run Clickhouse and echo "CPU doesn`t support SSE 4.2" if CPU doesn`t support SSE 4.2 ?
Thank you

**Comment by proller** [comment]
1. debian init script already prints this warning:  https://github.com/yandex/ClickHouse/blob/master/debian/clickhouse-server.init#L51
2. you can recompile clickhouse on target host without sse4 usage.
or you can use cmake flags: 
-DHAVE_SSE41=0 -DHAVE_SSE42=0 -DHAVE_POPCNT=0 DHAVE_PCLMULQDQ_INTRIN=0 -DPCLMULFLAG=' '

**Comment by patsevanton** [comment]
Thank for answer.
I use CentOS and systemd for run Clickhouse.
I think bad idea recompile clickhouse on target host without sse4
May be add CPU flag SSE 4.2 in binary ?

**Comment by blinkov** [comment]
At the moment there are no plans to support old CPUs in official ClickHouse builds.
