### ISSUE TITLE
data load with POST stack traced

### ISSUE THREAD

**Issue by shinguz** [yandex/ClickHouse#17]
cat /tmp/data_dump.sql | POST 'http://localhost:8123/'
Code: 62, e.displayText() = DB::Exception: Syntax error: failed at end of query.
Expected CHECK, e.what() = DB::Exception, Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0xe) [0xfcad5e]
1. clickhouse-server(DB::parseQuery(DB::IParser&, char const*, char const*, std::string const&)+0x194) [0x127d114]
2. clickhouse-server() [0x1356c88]
3. clickhouse-server(DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, DB::Context&, std::shared_ptr<DB::IBlockInputStream>&, std::function<void (std::string const&)>)+0x20e) [0x135943e]
4. clickhouse-server(DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&)+0x1024) [0xf6f294]
5. clickhouse-server(DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)+0x8a) [0xf702ca]
6. clickhouse-server(Poco::Net::HTTPServerConnection::run()+0x26a) [0x2a7716a]
7. clickhouse-server(Poco::Net::TCPServerConnection::start()+0x7) [0x2a66d37]
8. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x107) [0x2a71a37]
9. clickhouse-server(Poco::PooledThread::run()+0x7f) [0x305a80f]
10. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x87) [0x3018287]
11. /lib/x86_64-linux-gnu/libpthread.so.0(+0x8182) [0x7eff1f513182]
12. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7eff1eb2e47d]

**Comment by shinguz** [comment]
Data can be provided, structure as well when you tell me how.

**Comment by alexey-milovidov** [comment]
Probably your dump has many INSERT queries?

You should create dump with only data, or with single query and then all data.
As in example here:
https://clickhouse.yandex/reference_en.html#HTTP%20interface
(after words "Creating a table")

It because data is parsed with stream format parser, not with SQL-parser, as described here:
https://clickhouse.yandex/reference_en.html#Syntax

**Comment by shinguz** [comment]
you are right. I tried to import a mysqldump from our foodmart example schema to play around a bit. there are/were also many other things broken (in our dump). But: a stacktrace is a non caught exit and thus a bug.

**Comment by DieHertz** [comment]
Not necessarily, the server continues working, stack trace is provided for your convenience of debugging.

**Comment by alexey-milovidov** [comment]
Probably better to disable stack trace by default, as it was done for clickhouse-client (added `--stacktrace` option).

**Comment by alexey-milovidov** [comment]
> disable stack trace by default

Committed, scheduled for next release.
