### ISSUE TITLE
Distributed.DirectoryMonitor: Code: 210, e.displayText() = DB::NetException: I/O error: Broken pipe:  while reading from socket (10.13.224.145:9000), e.what() = DB::NetException

### ISSUE THREAD

**Issue by algorithm-buaa** [yandex/ClickHouse#1703]
hi, I am using the distributed table on centOs 7 with ClickHouse server version 1.1.54236.  If one server was stoped by the command `service clickhouse-server stop`,  Client can continue to insert data to server (not the stoped server) without returning any errors. I saw that the server connected by the client put the data that assigned to the stoped server into folder `{distributed table 
 name}/default@{ip of stoped server}:9000` . The server connected by the client try to send data in folder `{distributed table 
 name}/default@{ip of stoped server}:9000` to the server that just started， but ` I/O error: Broken pipe`  error repeated. I found that  method Connection::sendData did not handle the exception  thrown by method WriteBufferFromPocoSocket::nextImpl() in code  `out->next()`. The connection has been broken when peer server was stoped, but the connection does not call  method  `connections->disconnect()`, so  the the connect continued been used to send data to remote server.Even I started the server that was stoped before, nothing changed,  the error continue repeated.  So, I have to restart the server connected by the client to reconnect to the server that stoped Manually。 Sometimes I have to restart the whole cluster to make sure  all the connections of the cluster  to be good.
(sorry my english is poor,  Hope you can understand, thanks)

```
2017.12.25 19:16:04.107444 [ 407199 ] <Error> ods_saxaccess_offset.Distributed.DirectoryMonitor: Code: 210, e.displayText() = DB::NetException: I/O error: Broken pipe:  while reading from socket (10.13.224.145:9000), e.what() = DB::NetException, Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x28638b6]
1. clickhouse-server(DB::WriteBufferFromPocoSocket::nextImpl()+0x69f) [0x2883e6f]
2. clickhouse-server(DB::Connection::sendData(DB::Block const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0xd6) [0x2a386c6]
3. clickhouse-server(DB::Connection::sendQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, DB::Settings const*, DB::ClientInfo const*, bool)+0xc22) [0x2a39cc2]
4. clickhouse-server(DB::RemoteBlockOutputStream::writePrefix()+0x5b) [0x2c6f95b]
5. clickhouse-server(DB::StorageDistributedDirectoryMonitor::processFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x6e9) [0x2c3aff9]
6. clickhouse-server(DB::StorageDistributedDirectoryMonitor::findFiles()+0x13c) [0x2c3cacc]
7. clickhouse-server(DB::StorageDistributedDirectoryMonitor::run()+0xa5) [0x2c3cfa5]
8. clickhouse-server() [0x324652f]
9. /lib64/libpthread.so.0(+0x7df5) [0x7f476571edf5]
10. /lib64/libc.so.6(clone+0x6d) [0x7f4762ff11ad]
```

**Comment by ztlpn** [comment]
There is a bug in 54236 that causes bad connections to remain in the connection pool for Distributed inserts. You should upgrade. For CentOS please use rpms provided by Altinity: https://packagecloud.io/altinity/clickhouse
