### ISSUE TITLE
Do you have a test ClickHouse benchmark on TPC-H

### ISSUE THREAD

**Issue by ciscoxll** [yandex/ClickHouse#1708]
If there is can you share a link

**Comment by ztlpn** [comment]
Take a look at the [star schema benchmark](https://www.cs.umb.edu/~poneil/StarSchemaB.pdf) which is pretty similar to TPC-H. Here is a [howto guide](https://clickhouse.yandex/docs/en/getting_started/example_datasets/star_schema.html) and [some results](https://www.percona.com/blog/2017/06/22/clickhouse-general-analytical-workload-based-star-schema-benchmark/).
