### ISSUE TITLE
Too much simultaneous queries

### ISSUE THREAD

**Issue by zhaoplayboy** [yandex/ClickHouse#1725]
Today my clickhouse  not accpet request,Logs show that Too much simultaneous queries.but we don't have done that queries,meanwhile some error log output.
2018.01.04 09:52:27.002064 [ 298 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700121_530_17436_7 intersects previous part 19700101_19700101_528_130354_1
2018.01.04 09:52:27.002074 [ 298 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700101_530_131720_1 intersects previous part 19700101_19700121_530_17436_7
2018.01.04 09:52:27.002085 [ 298 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700121_532_35466_6 intersects previous part 19700101_19700101_530_131720_1
2018.01.04 09:52:27.002096 [ 298 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700101_532_130324_1 intersects previous part 19700101_19700121_532_35466_6
2018.01.04 09:52:27.002106 [ 298 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700101_538_130330_1 intersects previous part 19700101_19700101_532_130324_1
2018.01.04 09:52:27.002116 [ 298 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700101_550_130348_1 intersects previous part 19700101_19700101_538_130330_1
2018.01.04 09:52:27.002126 [ 298 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700101_564_130438_1 intersects previous part 19700101_19700101_550_130348_1
2018.01.04 09:52:27.002137 [ 298 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700101_582_130920_1 intersects previous part 19700101_19700101_564_130438_1
2018.01.04 09:52:27.002147 [ 298 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700101_596_131424_1 intersects previous part 19700101_19700101_582_130920_1
2018.01.04 09:52:27.002199 [ 298 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700103_19700119_11554_11554_0 intersects previous part 19700101_19700101_596_131424_1
2018.01.04 09:52:27.166707 [ 347 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700121_444_12714_60 intersects previous part 19700101_19700101_426_19238_1
2018.01.04 09:52:27.166729 [ 347 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700101_444_44896_1 intersects previous part 19700101_19700121_444_12714_60
2018.01.04 09:52:27.166744 [ 347 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700101_448_59065_1 intersects previous part 19700101_19700101_444_44896_1
2018.01.04 09:52:27.166757 [ 347 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700121_450_19282_4 intersects previous part 19700101_19700101_448_59065_1
2018.01.04 09:52:27.166769 [ 347 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700101_458_93634_1 intersects previous part 19700101_19700121_450_19282_4
2018.01.04 09:52:27.166782 [ 347 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700121_460_34692_7 intersects previous part 19700101_19700101_458_93634_1
2018.01.04 09:52:27.166793 [ 347 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700101_460_130546_1 intersects previous part 19700101_19700121_460_34692_7
2018.01.04 09:52:27.166805 [ 347 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700121_482_35342_7 intersects previous part 19700101_19700101_460_130546_1
2018.01.04 09:52:27.166815 [ 347 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700101_482_130568_1 intersects previous part 19700101_19700121_482_35342_7
2018.01.04 09:52:27.166826 [ 347 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700121_512_35436_6 intersects previous part 19700101_19700101_482_130568_1
2018.01.04 09:52:27.166850 [ 347 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700101_512_117939_1 intersects previous part 19700101_19700121_512_35436_6
2018.01.04 09:52:27.166861 [ 347 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700101_528_130354_1 intersects previous part 19700101_19700101_512_117939_1
2018.01.04 09:52:27.166880 [ 347 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700121_530_17436_7 intersects previous part 19700101_19700101_528_130354_1
2018.01.04 09:52:27.166891 [ 347 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700101_530_131720_1 intersects previous part 19700101_19700121_530_17436_7
2018.01.04 09:52:27.166904 [ 347 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700121_532_35466_6 intersects previous part 19700101_19700101_530_131720_1
2018.01.04 09:52:27.166916 [ 347 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700101_532_130324_1 intersects previous part 19700101_19700121_532_35466_6
2018.01.04 09:52:27.166929 [ 347 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700101_538_130330_1 intersects previous part 19700101_19700101_532_130324_1
2018.01.04 09:52:27.166939 [ 347 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700101_550_130348_1 intersects previous part 19700101_19700101_538_130330_1
2018.01.04 09:52:27.166953 [ 347 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700101_564_130438_1 intersects previous part 19700101_19700101_550_130348_1
2018.01.04 09:52:27.166966 [ 347 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700101_582_130920_1 intersects previous part 19700101_19700101_564_130438_1
2018.01.04 09:52:27.166983 [ 347 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700101_19700101_596_131424_1 intersects previous part 19700101_19700101_582_130920_1
2018.01.04 09:52:27.167119 [ 347 ] <Error> ncompass.data_17_0_60_20180103 (Merger): Part 19700103_19700119_11554_11554_0 intersects previous part 19700101_19700101_596_131424_1
2018.01.04 09:52:27.232856 [ 8134153 ] <Error> executeQuery: Code: 202, e.displayText() = DB::Exception: Too much simultaneous queries. Maximum: 100, e.what() = DB::Exception (from 127.0.0.1:38042) (in query:              SELECT *             FROM system.tables              WHERE name='data_17_1508831648862992_60_20180104' AND database='ncompass' ), Stack trace:

0. /opt/ncompass/opt/clickhouse/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x27a44c6]
1. /opt/ncompass/opt/clickhouse/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x1f) [0xfe082f]
2. /opt/ncompass/opt/clickhouse/bin/clickhouse-server(DB::ProcessList::insert(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::IAST const*, DB::ClientInfo const&, DB::Settings const&)+0x268) [0x27533f8]
3. /opt/ncompass/opt/clickhouse/bin/clickhouse-server() [0x278fa86]
4. /opt/ncompass/opt/clickhouse/bin/clickhouse-server(DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>)+0x1dd) [0x279041d]
5. /opt/ncompass/opt/clickhouse/bin/clickhouse-server(DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&)+0x1400) [0xfe78f0]
6. /opt/ncompass/opt/clickhouse/bin/clickhouse-server(DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)+0x32e) [0xfe895e]
7. /opt/ncompass/opt/clickhouse/bin/clickhouse-server(Poco::Net::HTTPServerConnection::run()+0x2c0) [0x2fe87c0]
8. /opt/ncompass/opt/clickhouse/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x2fe17cf]
9. /opt/ncompass/opt/clickhouse/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x12b) [0x2fe2e4b]
10. /opt/ncompass/opt/clickhouse/bin/clickhouse-server(Poco::PooledThread::run()+0xa7) [0x30f5817]
11. /opt/ncompass/opt/clickhouse/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x96) [0x30eff76]
12. /lib64/libpthread.so.0(+0x7dc5) [0x7f971f9efdc5]
13. /lib64/libc.so.6(clone+0x6d) [0x7f971d2c273d]

**Comment by blinkov** [comment]
@zhaoplayboy sounds weird, ClickHouse don't perform any requests on it's own either. Have you figured out what exactly was happening?
