### ISSUE TITLE
How Clickhouse compares to Twitter's Rainbird?

### ISSUE THREAD

**Issue by zero-master** [yandex/ClickHouse#1732]
See: https://www.slideshare.net/kevinweil/rainbird-realtime-analytics-at-twitter-strata-2011
What are the limitations or advantages of both systems and when does one make sense over other?

**Comment by alex-zaitsev** [comment]
In Rainbird you are stick with pre-defined counters and hierarchies. In ClickHouse you have full SQL flexibility. We tried Rainbird approach at some point for an application where it seem to fit, but it proved to be much worse than dedicated RDBMS (Vertica or ClickHouse).

**Comment by f1yegor** [comment]
generally speaking yes, in Rainbird we are talking about pre-aggregated data, on the other hand, Clickhouse allows to work with raw data.

**Comment by shangshujie365** [comment]
I searched rainbird, all things related it is about 2011, so, what happened to it these years?Maybe it has stoped

**Comment by zero-master** [comment]
They promised the opensource it but kept at it.

**Comment by alexey-milovidov** [comment]
@zero-master There was no news about Twitter's Rainbird system, let's assume it is dead.

We have prepared a benchmark suite for analytical DBMS: https://github.com/ClickHouse/ClickBench
It allows to quickly add, validate and reproduce the results for many other systems.

If Rainbird still exists, we can add it there.
