### ISSUE TITLE
performance degrade heavily after insert data into another merge-tree table

### ISSUE THREAD

**Issue by shangshujie365** [yandex/ClickHouse#1736]
Reproduce:
1.create 2 merge-tree table, e.g A and B,  insert many data 2 them.
2.select from A with some filter group by
3. insert to B many data
4. wait until there is no merge threads running
5. repeat step 2, you'll find speed downgrade significantly

In my case, table A has 20billion rows, and I insert 128M rows to table B 
My ch version is 1.1.54327, I install it by apt-get in official doc.
My os is Debian 4.9.2-10.
My machine has 48 cores, 256G memory, no disk io during the query running

**Comment by blinkov** [comment]
@shangshujie365 Sounds perfectly normal: at point 2 the data from table A is in page cache, while point 3 forced it to become evicted. Have you tried repeating point 5 multiple times? Does performance become better again?
