### ISSUE TITLE
Segfault on API call

### ISSUE THREAD

**Issue by acaiafa** [yandex/ClickHouse#1738]
From time to time during an API call clickhouse will segfault on the initial call. I have to restart the database and it will become stable after that. Below is the error:

2018.01.09 13:59:11.260248 [ 335 ] <Trace> HTTPHandler: Request URI: /?query=INSERT+INTO+database.table_name+FORMAT+JSONEachRow
2018.01.09 13:59:11.260460 [ 335 ] <Debug> executeQuery: (from 10.124.31.2:44966) INSERT INTO database.table_name FORMAT JSONEachRow
2018.01.09 13:59:11.260837 [ 335 ] <Debug> MemoryTracker: Peak memory usage (for query): 6.00 KiB.
2018.01.09 13:59:11.260867 [ 335 ] <Debug> MemoryTracker: Peak memory usage (for user): 6.00 KiB.
2018.01.09 13:59:11.260890 [ 335 ] <Debug> MemoryTracker: Peak memory usage (total): 6.00 KiB.
2018.01.09 13:59:11.260988 [ 335 ] <Error> HTTPHandler: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Exception: HTTPServerResponse::beginSend is invalid for HEAD request, e.what() = Exception
2018.01.09 13:59:11.261107 [ 354 ] <Error> BaseDaemon: ########################################
2018.01.09 13:59:11.273228 [ 354 ] <Error> BaseDaemon: (from thread 335) Received signal Segmentation fault (11).
2018.01.09 13:59:11.273251 [ 354 ] <Error> BaseDaemon: Address: NULL pointer.
2018.01.09 13:59:11.274737 [ 354 ] <Error> BaseDaemon: 1. clickhouse-server(std::ostream::sentry::sentry(std::ostream&)+0xc) [0x329ae8c]
2018.01.09 13:59:11.274757 [ 354 ] <Error> BaseDaemon: 2. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x96) [0x31c19c6]
2018.01.09 13:59:11.274781 [ 354 ] <Error> BaseDaemon: 3. /lib64/libpthread.so.0(+0x7dc5) [0x7f1c4928edc5]
2018.01.09 13:59:11.274805 [ 354 ] <Error> BaseDaemon: 4. /lib64/libc.so.6(clone+0x6d) [0x7f1c46b6273d]

**Comment by ztlpn** [comment]
This looks like the issue #912 which was fixed in version 1.1.54289. Which ClickHouse version are you using? Can you try the latest version and see if the problem goes away?
