### ISSUE TITLE
 <Warning> Application: Logging to console

### ISSUE THREAD

**Issue by ondevelop** [yandex/ClickHouse#1743]
i have started server through the docker, but server is not writing logs to file clickhouse-server.log.

Thank you

**Comment by ztlpn** [comment]
This is the intended behavior. You can view the container logs with the `docker logs` command.

If you still need the server to log to a file, you should override the container entrypoint. Something like this:
```
1:~$ docker run -d --name some-clickhouse-server --ulimit nofile=262144:262144 --entrypoint="" yandex/clickhouse-server /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --log-file=/var/log/clickhouse-server/clickhouse-server.log
```
But remember that by default the logs directory is not attached to any volume and so it will be destroyed with the container.
