### ISSUE TITLE
i find BUG,the 30th day of February

### ISSUE THREAD

**Issue by naah69** [yandex/ClickHouse#1744]
i find BUG,the 30th day of February

![snipaste_20180111_194001](https://user-images.githubusercontent.com/25682169/34823969-7de4a15a-f707-11e7-83d7-4ea8ab4c1d0f.png)

**Comment by alexey-milovidov** [comment]
The documentation should state, that the behaviour of parsing incorrect dates is implementation specific.
Returning zero date, throwing an exception or doing "natural" overflow - all are conforming.

Maybe we should change this behaviour to be more strict.

**Comment by naah69** [comment]
but 2018-02-31... 
 is there 02-31?
it return 2018-03-01

**Comment by BayoNet** [comment]
I added the warning about such of behaviour in docs.
https://clickhouse.yandex/docs/en/query_language/functions/date_time_functions/#tostartofmonth
