### ISSUE TITLE
ZooKeeper > etcd

### ISSUE THREAD

**Issue by wormen** [yandex/ClickHouse#1765]
планируется ли замена `ZooKeeper` на `etcd`?
на вопрос навела эта статья https://habrahabr.ru/company/flant/blog/329224/

или есть возможность самому собрать конфигурацию кластера с `etcd`?

**Comment by Slach** [comment]
https://github.com/yandex/ClickHouse/issues/777

https://github.com/Slach/clickhouse-zetcd

Если у вас есть опыт в C++
я был бы благораден за помощь чтобы можно было разобраться почему падает Clickhouse
в текущей версии стенд собирается и работает, 
но падает если повторно вставить теже данные

**Comment by wormen** [comment]
@Slach в C++ к сожалению нет опыта

**Comment by Slach** [comment]
@wormen тогда имеет смысл закрыть этот тикет, в целях неумножения энтропии

**Comment by wormen** [comment]
... ожидал информации по этому поводу побольше ...

**Comment by filimonov** [comment]
Информация "побольше": в настоящее время у разработчиков ClickHouse имеется немало разнородных задач, направленных на улучшение функциональности продукта (о ближайщих планах можно прочитать в ROADMAP: https://clickhouse.yandex/docs/en/roadmap.html ). 

При этом задача замены Zookeepera, не привнося новых функций и не улучшая продукт, может потребовать заметных ресурсов: на изменения в коде, на тестирование, на дальнейшую поддержку. После этого нужно будет поддерживать сразу два режима работы Clickhouse - c Zookeeper и c etcd (потому что многие по разных причинам предпочтут остаться на Zookeeper).

В связи с этим замена относительно стабильной и проверенной части системы (Zookeeper) на что-то пусть многообещающее, но не проверенное - вряд ли можно назвать приоритетной задачей ("Работает? Не трогай!").

При этом интерес к этой теме есть, и если для кого-то из пользователей Clickhouse отказ от Zookeeper важен и он располагает ресурсами на то, чтобы "подружить" ClickHouse с другими хранилищами, протестировать и поддерживать это - разумеется, все будут только "за".

@Slach уже добился определенных успехов. Возможно, чтобы ClickHouse начал работать c zetcd нужно не так уж много.

**Comment by wormen** [comment]
@filimonov спасибо за информативность
