### ISSUE TITLE
UUID field type

### ISSUE THREAD

**Issue by deonwise** [yandex/ClickHouse#1770]
Looks like bug in new data type UUID.
Used version 1.1.54327

I can create table with uuid field, insert data using simple string, representing uuid like '0c5049ab-a9fe-46c6-aee6-bcb5e414a19c'

The problem in using UUID typed field in WHERE clause;

Example:

CREATE TABLE test (id UUID,  gmt DateTime, date_index Date) ENGINE = MergeTree(date_index, (alert_id, gmt), 8192);

INSERT INTO uvo.pos (gmt,  id, date_index) VALUES( '0c5049ab-a9fe-46c6-aee6-bcb5e414a19c','2018-01-10 22:24:35', '2018-01-11');

its ok;
now i can select ALL data: 
select * from test;
┌──────────────id─┬────────────────────gmt─┐
│ 0c5049ab-a9fe-46c6-aee6-bcb5e414a19c │ 2018-01-10 22:24:35 │
└──────────────────────────┴──────────────┘

If i try to provide ID field:
SELECT 
    id,    gmt
FROM test
WHERE id = '0c5049ab-a9fe-46c6-aee6-bcb5e414a19c'

Got:  DB::Exception: Bad type of Field

Ok, there are function: toUUID, lets try: 

SELECT 
    id,    gmt
FROM test
WHERE id = toUUID('0c5049ab-a9fe-46c6-aee6-bcb5e414a19c');

Same result.
By the way: 
SELECT 
    toTypeName(id), 
    toTypeName(toUUID('0c5049ab-a9fe-46c6-aee6-bcb5e414a19c'))
FROM test;

toTypeName(id)─┬─toTypeName(toUUID(\'0c5049ab-a9fe-46c6-aee6-bcb5e414a19c\'))─┐
│ UUID                 │ UUID                                                         │
└──────────┴────────────────────────────────────────

Only one method i found was:

SELECT 
    materialize(id) as id,    gmt
FROM test
WHERE id = toUUID('0c5049ab-a9fe-46c6-aee6-bcb5e414a19c');

That works.

Please tell me where i was wrong?

**Comment by alexm93** [comment]
Hello!

Could you say when this bug will be fixed?
It's very critical for our development team now.

**Comment by deonwise** [comment]
Разработчики ничего не ответили, так что я перешел на использование FixedString(16) и UUIDStringToNum(')

**Comment by deonwise** [comment]
Всё по документации:

**UUIDStringToNum(str)**
Принимает строку, содержащую 36 символов в формате 123e4567-e89b-12d3-a456-426655440000, и возвращает в виде набора байт в FixedString(16).

**UUIDNumToString(str)**
Принимает значение типа FixedString(16). Возвращает строку из 36 символов в текстовом виде.

То есть данные хранятся в бинарной строке, поиск WHERE field = UUIDStringToNum(текстовое представление UUID)

Вставлять тоже так можно

**Comment by deonwise** [comment]
тут много было  про данный формат.

**Comment by alexm93** [comment]
Спасибо, стало понятно. Я просто использовал JSONEachRow при вставке, при его использовании, как я понял,  конструкцию UUIDStringToNum(текстовое представление UUID) не удастся вставить.
Придется переходить на другой формат.

**Comment by alexm93** [comment]
А вы в каком формате делаете инсерт?
Я пытаюсь с помощью обычного VALUES вставлять
Если вставлять по 100 строк, то все ок
Если по 1000 и больше начинают валиться подобные ошибки:
DB::Exception: Unknown identifier: UUIDStringToNum, e.what() = DB::Exception
Или
DB::Exception: Unknown identifier: UUIDStrin, e.what() = DB::Exception

**Comment by alexm93** [comment]
То есть RowBinary форматом? А строки сами кодируете в нужный формат? Или может есть какой то encoder готовый?

**Comment by deonwise** [comment]
На golang драйвер передает, я использую tcp подключение, не http

**Comment by simPod** [comment]
Hey, did you solve it? How to filter with uuid in WHERE?

**Comment by alexey-milovidov** [comment]
In master.
