### ISSUE TITLE
ENGINE = Kafka  Cannot parse input:

### ISSUE THREAD

**Issue by Mcgeey** [yandex/ClickHouse#1781]
I used clickhouse's kafka engine, but there was an exception.
When I send data to kafka not artificially add \ n, this error occurs.
Code: 27. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Cannot parse input: expected \n before: \ttest: (at row 1)

no exception msg like this
String msg =timestamp+"\ttest\n";

exception msg like this
String msg =timestamp+"\ttest";

create table sql:
        CREATE TABLE event_stream (ts String,a String) 
        ENGINE = Kafka('brokerlist', 'chtest', 'testgroup111', 'TabSeparated');

send msg code:
        long timestamp = System.currentTimeMillis();
        String a =timestamp+"\ttest\n";
        String topic = "chtest";
        System.out.println("msg" + a);
        KeyedMessage<String, String> data = new KeyedMessage<String, String>(topic, a);
        producer.send(data);

how to solve this problem?
I'm so sorry. My English is poor.Thanks google and you.

**Comment by meshpaul** [comment]
Cancel

**Comment by Mcgeey** [comment]
@meshpaul   what do you mean?  cancel?

**Comment by alexey-milovidov** [comment]
Fixed in #2701
