### ISSUE TITLE
Is sql_calc_found_rows alternative exist

### ISSUE THREAD

**Issue by chaitenyay** [yandex/ClickHouse#1782]
Is it possible to get total number of records along with limit sql
select sql_calc_found_rows * from table where id > 10 limit 5

Thanks

**Comment by sanchezzzhak** [comment]
yes, use
```
select sql_calc_found_rows * from table where id > 10 limit 5 FORMAT JSON
view key totals, rows_before_limit_at_least

**Comment by chaitenyay** [comment]
Thanks, it works

**Comment by bulletRush** [comment]
for ReplacingMergeTree, yandex/clickhouse-server:latest(4fee701cac0d,  4 weeks ago), this sql

```sql
SELECT xxx_id
FROM t_xxxx
FINAL
LIMIT 10, 10
FORMAT JSON
```

return without `total`: 

```json
	"rows": 10,

	"rows_before_limit_at_least": 20,

	"statistics":
	{
		"elapsed": 0.003157,
		"rows_read": 945,
		"bytes_read": 46305
	}
```

**Comment by sanchezzzhak** [comment]
see https://clickhouse.tech/docs/en/interfaces/formats/

> `rows_before_limit` is the minimal number of rows there would have been without LIMIT. Output only if the query contains LIMIT. If the query contains GROUP BY, `rows_before_limit_at_least` is the exact number of rows there would have been without a LIMIT.

to return totals you need to use `WITH TOTALS`
