### ISSUE TITLE
Minor bugfix to russian doc

### ISSUE THREAD

**Issue by syaroslavtsev** [yandex/ClickHouse#18]
Doc URL https://clickhouse.yandex/reference_ru.html#%D0%92%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D1%8B%D0%B5%20%D0%B3%D0%BB%D1%83%D0%BF%D1%8B%D0%B5%20%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81%D1%8B

-"Распределённая сортировка является основной причиной тормозов при выполнении несложных map-reduce задач."
+"Распределённая сортировка является основной причиной долгого выполнения при выполнении несложных map-reduce задач."

-"Впрочем, производительность при выполнении таких задач является сильно неоптимальной по сравнению"
+"Впрочем, производительность при выполнении таких задач является не оптимальной в использовании по сравнению"

-"Задачи в YT выполняются с помощью произвольного кода в режиме streaming"
+"Задачи в YT выполняются с помощью произвольного кода в режиме потока(ов) (streaming)"

-"(как наиболее высоким throughput на длинных запросах, так и наиболее низкой latency на коротких запросах)"
+"(как наиболее высокой пропускной способностью (throughput) на длинных запросах, так и наиболее низкой задержкой (latency) на коротких запросах)"

-"В кажом шарде можно указать от одной до произвольного числа реплик. Можно указать разное число реплик для каждого шарда."
+"В каждом шарде можно указать от одной до произвольного числа реплик. Можно указать разное число реплик для каждого шарда."

-"Движок принимает параметры: имя столбца типа Date"
+"Движок принимает параметры: имя столбца c типом данных Date/Timestamp?"

-"При вставке, данные относящиеся к разным месяцам, разбиваются на разные кусочки"
+"При вставке, данные относящиеся к разным месяцам, разбиваются на разные сегменты"

-"Вставки никак не мешают чтениям"
+"Операции вставки данных никак не мешают операциям чтения"

-"Чтения из таблицы автоматически распараллеливаются."
+"Операции чтения из таблицы автоматически распараллеливаются."

**Comment by alexey-milovidov** [comment]
> -"Распределённая сортировка является основной причиной тормозов при выполнении несложных map-reduce задач."
+"Распределённая сортировка является основной причиной долгого выполнения при выполнении несложных map-reduce задач."

Не очевидно, что это лучше. "Тормоза" - сленг, но его все знают.

> -"Впрочем, производительность при выполнении таких задач является сильно неоптимальной по сравнению"
+"Впрочем, производительность при выполнении таких задач является не оптимальной в использовании по сравнению"

Не ощущаю преимущества. Даже стало чуть хуже: "производительность ... в использовании".

> -"Задачи в YT выполняются с помощью произвольного кода в режиме streaming"
+"Задачи в YT выполняются с помощью произвольного кода в режиме потока(ов) (streaming)"

Тоже неочевидно. Можно сказать, в потоковом режиме. Но лучше не стоит, так как термин streaming (стриминг) имеет конкретное значение в контексте Hadoop/map-reduce.

> -"(как наиболее высоким throughput на длинных запросах, так и наиболее низкой latency на коротких запросах)"
+"(как наиболее высокой пропускной способностью (throughput) на длинных запросах, так и наиболее низкой задержкой (latency) на коротких запросах)"

Нормально. Могу принять, но целесообразность слабая, так как эти термины должны быть известны читателю.

> -"В кажом шарде можно указать от одной до произвольного числа реплик. Можно указать разное число реплик для каждого шарда."
+"В каждом шарде можно указать от одной до произвольного числа реплик. Можно указать разное число реплик для каждого шарда."

Ок.

> -"Движок принимает параметры: имя столбца типа Date"
+"Движок принимает параметры: имя столбца c типом данных Date/Timestamp?"

Именно типа Date. 
Типа Timestamp нет, есть DateTime, но он не подходит в этом месте.

> -"При вставке, данные относящиеся к разным месяцам, разбиваются на разные кусочки"
+"При вставке, данные относящиеся к разным месяцам, разбиваются на разные сегменты"

Понимаю, что термин "кусочки" звучит более неформально. Но здесь нужно быть аккуратным. Дело в том, что в коде есть очень похожих терминов: part, partition, block, chunk, piece, обозначающие разные вещи, и для них есть закрепившееся слова на русском языке. Менять их нельзя, чтобы самому потом не запутаться. Например, part в таблицах типа MergeTree (Доступны выполнением запроса `SELECT * FROM system.parts`) обозначаются на русском языке именно как "куски".

> -"Вставки никак не мешают чтениям"
+"Операции вставки данных никак не мешают операциям чтения"

> -"Чтения из таблицы автоматически распараллеливаются."
+"Операции чтения из таблицы автоматически распараллеливаются."

Мотивация не очевидна. Я могу внести изменения просто чтобы вы чувствовали себя хорошо.

**Comment by alexey-milovidov** [comment]
https://github.com/yandex/ClickHouse/commit/d19d3a27da2ece3c49a8afbf8c5772a7b74df440

**Comment by syaroslavtsev** [comment]
-"Вы можете прервать длинный запрос, нажав Ctrl+C. При этом вам всё-равно придётся чуть-чуть подождать, пока сервер остановит запрос. На некоторых стадиях выполнения, запрос невозможно прервать. Если вы не дождётесь и нажмёте Ctrl+C второй раз, то клиент будет завершён."
+"Вы можете прервать длинный запрос, нажав Ctrl+C. При этом вам всё равно придётся чуть-чуть подождать, пока сервер остановит запрос. На некоторых стадиях выполнения, запрос невозможно прервать. Если вы не дождётесь и нажмёте Ctrl+C второй раз, то клиент будет завершён."

-"Принимает Float32 или Float64 и возвращает UInt8, равный 1, если агрумент не бесконечный и не NaN, иначе 0."
+"Принимает Float32 или Float64 и возвращает UInt8, равный 1, если аргумент не бесконечный и не NaN, иначе 0."

**Comment by syaroslavtsev** [comment]
-"Принимает строку, число, дату или дату-с-временем. Возвращает строку, содержащую шестнадцатиричное представление аргумента. Используются заглавные буквы A-F. Не используются префиксы %%0x%% и суффиксы %%h%%. Для строк просто все байты кодируются в виде двух шестнадцатиричных цифр. Числа выводятся в big endian ("человеческом") формате. Для чисел вырезаются старшие нули, но только по целым байтам. Например, %%hex(1) = '01'%%. Даты кодируются как число дней с начала unix-эпохи. Даты-с-временем кодируются как число секунд с начала unix-эпохи."
+"Принимает строку, число, дату или дату-с-временем. Возвращает строку, содержащую шестнадцатеричное представление аргумента. Используются заглавные буквы A-F. Не используются префиксы %%0x%% и суффиксы %%h%%. Для строк просто все байты кодируются в виде двух шестнадцатеричных цифр. Числа выводятся в big endian ("человеческом") формате. Для чисел вырезаются старшие нули, но только по целым байтам. Например, %%hex(1) = '01'%%. Даты кодируются как число дней с начала unix-эпохи. Даты-с-временем кодируются как число секунд с начала unix-эпохи."

**Comment by syaroslavtsev** [comment]
-"Эта функция обычно используется совместо с ARRAY JOIN. Она позволяет, после применения ARRAY JOIN, посчитать что-либо только один раз для каждого массива. Пример:"
+"Эта функция обычно используется совместно с ARRAY JOIN. Она позволяет, после применения ARRAY JOIN, посчитать что-либо только один раз для каждого массива. Пример:"

**Comment by alexey-milovidov** [comment]
Всё исправил.
