### ISSUE TITLE
ClickHouse Kafka for CSV & TSV format support

### ISSUE THREAD

**Issue by vicchen7** [yandex/ClickHouse#1805]
Hi,I have the issue Kafka imported data to ClickHouse.
I try to import csv file into one topic and used kafka engine to fetch data from this topic.
But got some error.
2017.12.05 04:36:25.559854 [ 7 ] <Error> executeQuery: Code: 117, e.displayText() = DB::Exception: Expected end of line, e.what() = DB::Exception (from [::1]:39994) (in query: select * from test3), Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x2eb9af6]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x145918f]
2. clickhouse-server() [0x32ffe80]
3. clickhouse-server(DB::CSVRowInputStream::read(DB::Block&)+0x119) [0x33002a9]
4. clickhouse-server(DB::BlockInputStreamFromRowInputStream::readImpl()+0x64) [0x32fd2a4]
5. clickhouse-server(DB::IProfilingBlockInputStream::read()+0x19e) [0x287f9ce]
6. clickhouse-server(DB::KafkaBlockInputStream::readImpl()+0x4c) [0x2f75dac]
7. clickhouse-server(DB::IProfilingBlockInputStream::read()+0x19e) [0x287f9ce]
8. clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x1a) [0x3163caa]
9. clickhouse-server(DB::IProfilingBlockInputStream::read()+0x19e) [0x287f9ce]
10. clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x1a) [0x3163caa]
11. clickhouse-server(DB::IProfilingBlockInputStream::read()+0x19e) [0x287f9ce]
12. clickhouse-server(DB::ParallelInputsProcessor<DB::UnionBlockInputStream<(DB::StreamUnionMode)0>::Handler, (DB::StreamUnionMode)0>::loop(unsigned long)+0x142) [0x2e27332]
13. clickhouse-server(DB::ParallelInputsProcessor<DB::UnionBlockInputStream<(DB::StreamUnionMode)0>::Handler, (DB::StreamUnionMode)0>::thread(MemoryTracker*, unsigned long)+0x73) [0x2e27af3]
14. clickhouse-server() [0x39d2f5f]
15. /lib64/libpthread.so.0(+0x7e25) [0x7ff369219e25]
16. /lib64/libc.so.6(clone+0x6d) [0x7ff366cf534d]

I can import the same csv file into clickhoue table and no error.
Below is my table 
 CREATE TABLE test3 (plant Int16, code Int16, service_level Float32, qty Int8) ENGINE = Kafka('192.168.1.223:9092', 'table_test3', 'group1', 'CSV');
How can I fix it?

Since our streaming data schema is not dynamic and it almost doesn't change.
I used TSV format and got error as well .
Before we used Memsql pipeline solution from the same topic and it worked.

I tested to use JSONEachRow  format files  into Kafka topic and create MATERIALIZED VIEW to import into ClickHouse, it worked fine but the insert throughput rate seems very low,any idea?.

Thanks for your help.

[test3.zip](https://github.com/yandex/ClickHouse/files/1650710/test3.zip)

**Comment by vavrusa** [comment]
Hi @vicchen7, what’s your clickhouse version? Can you reproduce that on latest master if you’re running a version from package? The Kafka engine performance should be fast enough at least, depending on your expectations. I’m getting 100-200k rows/s per consumer on my laptop.

**Comment by marklit** [comment]
This looks like #2298. There's some work ongoing to fix this issue.

**Comment by alexey-milovidov** [comment]
Implemented in #2701
