### ISSUE TITLE
Failed to merge parts because of inconsistent leader

### ISSUE THREAD

**Issue by dqminh** [yandex/ClickHouse#1808]
We had a table that failed to merge its parts.

```
SELECT
    count(),
    database
FROM system.parts
WHERE table = 'table_name'
GROUP BY database

┌─count()─┬─database─┐
│    1000 │ r2       │
│      10 │ r0       │
│      17 │ r1       │
└─────────┴──────────┘
```

When trying to do optimize manually on the table

```
:) optimize table r2.table_name partition '201801'

OPTIMIZE TABLE r2.table_name PARTITION '201801'

Received exception from server:
Code: 292. DB::Exception: Received from current_host:9000, current_ip. DB::Exception: Received from remote_host:9000, remote_ip. DB::Exception: Leader was suddenly changed or logical error..
```

Restart the remote host, then optimize table works without errors and the replicated table seems to be able to merge again.

**Comment by blinkov** [comment]
@dqminh can you provide an instruction on how to reproduce this?

**Comment by dqminh** [comment]
Sorry, this was a while ago and we couldnt replicate it even at the time IIRC. We havent seen the same error so far after a few version upgrades i think so I guess we can close this.
