### ISSUE TITLE
COMMENT for table definition

### ISSUE THREAD

**Issue by alexey-milovidov** [yandex/ClickHouse#1815]
Add optional COMMENT clause to CREATE query. Example:

`CREATE ... COMMENT 'abc'`

It's mostly ignored. The only purpose is to be written to `.sql` file; to show in `SHOW CREATE TABLE` statement and in `system.tables` table.

Add optional COMMENT action in ALTER query. It's allowed to specify COMMENT only in alter columns (not for partitions).

**Comment by pavel-odintsov** [comment]
Hello!

That's awesome! Also would be nice to show it in "DESCRIBE TABLE" because it's more script friendly. 

Very useful thing for schema migration!

**Comment by schursin** [comment]
Maybe something like this?

https://www.postgresql.org/docs/9.1/static/sql-comment.html

**Comment by Jaxvk** [comment]
:+1:

**Comment by alexey-milovidov** [comment]
Implemented: #3377
