### ISSUE TITLE
Странное поведение для arrayJoin

### ISSUE THREAD

**Issue by akonyaev90** [yandex/ClickHouse#1817]
`CREATE TABLE akonyaev.content_app_version_mapi_history_today
ENGINE = MergeTree(date, (app_version_id, content_id), 8192) AS
SELECT 
    today() AS date, 
    content_id, 
    arrayJoin(arrayMap(x -> toUInt32(x), splitByChar(',', versions_with_allowed_formats))) AS app_version_id
FROM dictionaries.content_app_version_mapi 
`
`
↘ Progress: 65.54 thousand rows, 1.56 GB (92.54 thousand rows/s., 2.20 GB/s.) 
Received exception from server:
Code: 241. DB::Exception: Received from localhost:9001, 127.0.0.1. DB::Exception: Memory limit (for query) exceeded: would use 13.00 GiB (attempt to allocate chunk of 4294967296 bytes), maximum: 9.31 GiB. 
0 rows in set. Elapsed: 33.512 sec. Processed 65.54 thousand rows, 1.56 GB (1.96 thousand rows/s., 46.54 MB/s.) `

Я пытаюсь проитерироваться по всем записям в таблице и делая arrayJoin записывать результат в новую таблицу. У меня было чёткое понимание, что если не происходит join или group by, то запрос должен на лету, не откладывая в память многое, писать результаты в новую таблицу.

Вместо этого, он пытается запихнуть результат в память и потом уже в таблицу.

Нормальное ли это поведение для базы?

**Comment by KochetovNicolai** [comment]
Такой запрос действительно должен отрабатывать с константной памятью.
Единственное, есть подозрение на чтение из таблицы на основе словаря - в таком случае все ключи из словаря записываются в память (кроме cache словарей, для них берем только ключи из кеша), и если словарь большой, памяти может не хватить из-за размера ключей.

Будет здорово, если сможете воспроизвести такой расход памяти на искусственных данных, или рассказать, как получить словарь `content_app_version_mapi`.

**Comment by akonyaev90** [comment]
content_app_version_mapi - это словарь из таблицы postgresql

**Comment by akonyaev90** [comment]
Я решил проблему. Но это полумера.
Сначала я вытащил словарь в таблицу типа Log

`CREATE TABLE akonyaev.content_app_version_mapi
ENGINE = Log() AS
SELECT *
FROM dictionaries.content_app_version_mapi `

Затем превратил колонку versions_with_allowed_formats из строки, в сплитнутый массив с Int32.
`CREATE TABLE akonyaev.content_app_version_mapi_preproc_history_today
ENGINE = MergeTree(date, (app_version_id, content_id), 8192) AS
SELECT 
    today() AS date, 
    content_id, 
    arrayMap(x -> toUInt32(x), splitByChar(',', versions_with_allowed_formats)) AS app_version_id
FROM akonyaev.content_app_version_mapi`

И вот уже потом сделал arrayJoin
`CREATE TABLE akonyaev.content_app_version_mapi_history_today
ENGINE = MergeTree(date, (app_version_id, content_id), 8192) AS
SELECT 
    today() AS date, 
    content_id, 
    arrayJoin(app_version_id) AS app_version_id
FROM akonyaev.content_app_version_mapi_preproc_history_today`

Запрос теперь не отжирал память, но я всё равно чувствую что это работает не так как задуманно, ибо если совместить второй и третий запрос в один оно утекает по памяти.
Мне кажется что комбинация  arrayJoin(arrayMap()) должна выполнятся за время линейно зависящее от числа обрабатываемых записей.
Но я вижу что это не так

Есть хоть какие-то идеи?

**Comment by yurial** [comment]
arrayJoin множит строку на размер массива. splitByChar вернет массив по количеству ','. Учитывая, что ClickHouse обрабатывает данные блоками, то расход памяти будет прямо пропорционален количеству ',' в блоке данных.

**Comment by akonyaev90** [comment]
Ок, но если я делаю всё последовательно, с промежуточной таблице - то расход памяти должен быть тот-же

**Comment by yurial** [comment]
Могу предположить, что когда ты делаешь один запрос, в памяти одновременно нужно хранить больше данных т.е. и versions_with_allowed_formats и результат splitByChar и результат arrayMap. Вообще твою проблему можно обойти увеличив доступный объем памяти или уменьшив max_block_size и max_read_buffer_size, что сделает обработку меньшими блоками.

**Comment by blinkov** [comment]
@akonyaev90 эта проблема ещё актуальна?
