### ISSUE TITLE
Проблемы после обновления на версию 1.1.54342

### ISSUE THREAD

**Issue by akonyaev90** [yandex/ClickHouse#1818]
Пытался обновиться с версии  1.1.54327 на 1.1.54342 и получил множество ошибок следующего вида:

2018.01.24 12:24:59.356556 [ 5 ] <Error> DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 33, e.displayText() = DB::Exception: Cannot read all data, e.what() = DB::Exception, Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x15) [0x73178b5]
1. clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x1e) [0x19ca19e]
2. clickhouse-server(DB::DataPartsExchange::Fetcher::fetchPart(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, DB::ConnectionTimeouts const&, bool)+0x14dc) [0x685871c]
3. clickhouse-server(DB::StorageReplicatedMergeTree::fetchPart(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, unsigned long)+0x4a0) [0x6828110]
4. clickhouse-server(DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry const&)+0x1319) [0x682a1e9]
5. clickhouse-server() [0x682cc3e]
6. clickhouse-server(DB::ReplicatedMergeTreeQueue::processEntry(std::function<std::shared_ptr<zkutil::ZooKeeper> ()>, std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::function<bool (std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>)+0x4c) [0x68f71fc]
7. clickhouse-server(DB::StorageReplicatedMergeTree::queueTask()+0x16a) [0x6813c2a]
8. clickhouse-server(DB::BackgroundProcessingPool::threadFunction()+0x466) [0x6851cf6]
9. clickhouse-server() [0x76fcfae]
10. /lib/x86_64-linux-gnu/libpthread.so.0(+0x8183) [0x7f6633db1183]
11. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6c) [0x7f66337d7ffc]

Наш основной кейс - это ReplicatedReplacingMergeTree и поверх них Distributed таблицы

**Comment by misja** [comment]
I can confirm this, had exactly the same issue when setting up a replica, downgrading from 1.1.54342 to 1.1.54327 solved this.

**Comment by Yashin32** [comment]
Confirming this issue, had the same error after updating to 54337. Table engine is ReplicatedSummingMergeTree + Distributed. Downgrade to 54327 also helped to solve issue. Stack trace: https://pastebin.com/NpY3WdtC

**Comment by akonyaev90** [comment]
I use zookeeper 3.4.5. May be this problem due with zookeeper version?

**Comment by misja** [comment]
I'm on 3.4.8, don't really have the impression this is zookeeper related.

**Comment by KochetovNicolai** [comment]
Issue may happen if replicas of replicated table have different versions. Do you have the same issue after updating all replicas?

**Comment by akonyaev90** [comment]
Nope, I was updated first instance and saw this error in log file.
Thank's, i will try update all instances in cluster and report you later.

**Comment by Vladikamira** [comment]
Hi, we had the same issue after upgrade to `1.1.54342`
@akonyaev90 did you solve this issue by updating all cluster instances?
