### ISSUE TITLE
ODBC драйвер для Windows. Использование в SQL Server Intergation Services (SSIS)

### ISSUE THREAD

**Issue by DSeratila** [yandex/ClickHouse#1826]
Версия сервера ClickHouse: 
![image](https://user-images.githubusercontent.com/9797645/35438520-ea481268-02a7-11e8-96c2-9a43ea9bcd1d.png)

Версия драйвера от 2017-11-07 (ANSI). 
https://github.com/yandex/clickhouse-odbc/commit/018c1d14bb6d050453a88eb71db8ad07f3913150
При попытке использование драйвера UNICODE крэшится Visual Studio

Версия Visual Studio: 
![image](https://user-images.githubusercontent.com/9797645/35438710-aaa068ee-02a8-11e8-88ec-e161ff9b5ab6.png)

Версия ОС: Windows 10 Pro x64

При попытке обратиться с любым запросом как к источнику данных с использованием выдает ошибку "There was an error while truing to get schema information. Table has no columns"
![image](https://user-images.githubusercontent.com/9797645/35438675-8018e7cc-02a8-11e8-8ca9-85f367509070.png)

В качестве источника данных используется DSN

Если вместо запроса попытаться получить список таблиц, получаем ошибку:
![image](https://user-images.githubusercontent.com/9797645/35439782-6a04bc5e-02ad-11e8-809f-e5c7df6ecf1f.png)

**Comment by blinkov** [comment]
В последние недели ODBC драйвер был сильно доработан, стоит попробовать свежие версии.

**Comment by zotov-vs** [comment]
> В последние недели ODBC драйвер был сильно доработан, стоит попробовать свежие версии.

сервер Clickhouse 19.1.6

![image](https://user-images.githubusercontent.com/8470631/52902593-20157780-3224-11e9-9d96-3703e8bbfcce.png)

драйвер odbc 1.0.0.20190201

![image](https://user-images.githubusercontent.com/8470631/52902581-f9574100-3223-11e9-8523-d2a31023096f.png)

VS 2017
![image](https://user-images.githubusercontent.com/8470631/52902601-4509ea80-3224-11e9-813c-0d8fc5fdb871.png)

Подключение проходит успешно на драйвере unicode 32-разрядный
![image](https://user-images.githubusercontent.com/8470631/52902627-90bc9400-3224-11e9-9007-e5c1bea60565.png)

На ansi драйвере ошибка, возможно из-за настроек сервера Clickhouse 
![image](https://user-images.githubusercontent.com/8470631/52902637-b2b61680-3224-11e9-9751-178f6857d4e5.png)

При любом запросе ошибка
![image](https://user-images.githubusercontent.com/8470631/52902670-0cb6dc00-3225-11e9-8a05-29b5a6dd7296.png)

При этом из powerBI подключение есть, правда на x64 драйвере

**Comment by filimonov** [comment]
https://github.com/ClickHouse/clickhouse-odbc/issues/202
