### ISSUE TITLE
Distributed table user

### ISSUE THREAD

**Issue by igor-sh8** [yandex/ClickHouse#1834]
Hello.
Maybe someone already come across such case. 
I have clickhouse cluster of 4 servers. On each server I deleted default user and set custom (with password). Then I created distributed table. And when I run SELECT query on this table I get an error:
DB::Exception: Received from host:9000, IP. DB::Exception: Unknown user default.
So I get data from current server but can not get data from another shard server ?
Can I in some way set user and pass for cluster ?

**Comment by igor-sh8** [comment]
Sorry, I found that <replica> section config supports <user> and <password> tags. So all fine, all works properly.

**Comment by milktea02** [comment]
We also came across this issue and the relevant page is: http://clickhouse-docs.readthedocs.io/en/latest/access_rights.html

> The default user is also used for distributed query processing - the system accesses remote servers under this username. So the default user must have an empty password and must not have substantial restrictions or quotas - otherwise, distributed queries will fail.
