### ISSUE TITLE
[Question] how to optimize funnels query?

### ISSUE THREAD

**Issue by Jaxvk** [yandex/ClickHouse#1836]
hi, I need to use clickhouse to funnels query

#### info
- the table `trajectory_trackless_complex` has 2894082787 rows
- pageid: 2538 --> 3242 --> 1682, ( homepage --> listpage --> detailpage )
#### query sql 
```
SELECT 
    sum(step1_time != 0) AS home, 
    sum(step2_time != 0) AS list, 
    sum(step3_time != 0) AS detail
FROM 
(
    SELECT 
        loginkey, 
        groupArray(pageid) AS events, 
        groupArray(createtime) AS events_times, 
        arrayFilter((time, name) -> (name = 2538), events_times, events)[1] AS step1_time, 
        arrayFilter((time, name) -> ((name = 3242) AND (time >= step1_time) AND (step1_time != 0)), events_times, events)[1] AS step2_time, 
        arrayFilter((time, name) -> ((name = 1682) AND (time >= step2_time) AND (step2_time != 0)), events_times, events)[1] AS step3_time
    FROM 
    (
        SELECT 
            pageid, 
            createtime, 
            loginkey
        FROM datacenter.trajectory_trackless_complex 
        WHERE pageid IN (2538, 3242, 1682)
        ORDER BY createtime ASC
    ) 
    GROUP BY loginkey
) 
```
-------
##### begining
it seems run very fast
![image](https://user-images.githubusercontent.com/20113411/35546854-b0713bfa-053b-11e8-8db7-ab3e2a7f10fa.png)

##### after few seconds
it hungs

##### end
it uses 377sec
![image](https://user-images.githubusercontent.com/20113411/35546942-ef96e226-053b-11e8-800b-258d973669f6.png)

-------
#### Question
how to optimize the query ?
how to make it run faster ?
thank you very match

**Comment by Jaxvk** [comment]
@ztlpn can you give me some advice?

**Comment by shangshujie365** [comment]
udaf

**Comment by sundy-li** [comment]
@Jaxvk  Uadf,  try [this](https://zhuanlan.zhihu.com/p/30823204)

**Comment by Jaxvk** [comment]
@sundy-li  如果能通过clickhouse语法可以直接实现就很好了， 易观比赛加了一些限定条件可以快速得出结果。我发现它总是卡在一台机器上 98%，这个阶段如果可以并行使用多个机器运行就好了

**Comment by alexey-milovidov** [comment]
Have you tried the `sequenceMatch` aggregate function?

**Comment by Jaxvk** [comment]
@alexey-milovidov yes, it can't not work
```
Exception: Pattern application proves too difficult, exceeding max iterations
```
