### ISSUE TITLE
<Debug> StorageKafka (cpuinfo): Started streaming to 1 attached views  <Trace> Creating formatted reader <Debug> StorageKafka (cpuinfo): Stopped streaming to views

### ISSUE THREAD

**Issue by sachinkademane** [yandex/ClickHouse#1837]
hey all, i am taking real time data from kafka engine to clickhouse.....to take this data i created the following table
`CREATE TABLE cpuinfo (timestamp UInt64, namespace String, data Float, unit String, plugin_running_on String, version UInt64, last_advertised_time String) ENGINE = Kafka('10.224.54.99:9092', 'cpuout', 'group2', 'JSONEachRow');`
since i got to know that select from above table shows data only once....i tried using MATERIALIZED view so that i can see data whenever i need which is stored in the view...so i also created two more tables..
`CREATE TABLE cpuinfo_t (timestamp UInt64,namespace String,data Float,unit String,plugin_running_on String,version UInt64,last_advertised_time String,DAY Date)ENGINE = MergeTree PARTITION BY DAY ORDER BY (DAY, timestamp) SETTINGS index_granularity = 8192;`
and a view for this
 `CREATE MATERIALIZED VIEW cpuinfo_view TO cpuinfo_t AS SELECT timestamp,namespace,data,unit,plugin_running_on,version,last_advertised_time,toDate(toDateTime(timestamp)) AS DAY FROM cpuinfo;`
but i am unable to see data when i do `select * from cpuinfo_view` but i can see data in `select * from cpuinfo` what might be the problem?

**Comment by vavrusa** [comment]
Is there anything else in the clickhouse logs? Does the table schema match the entries in Kafka topic? Can you post an example of the data from `SELECT * FROM cpuinfo LIMIT 1` ?

**Comment by blinkov** [comment]
@sachinkademane can you provide any additional info?
