### ISSUE TITLE
Problems with DEFAULT in Float32 

### ISSUE THREAD

**Issue by akonyaev90** [yandex/ClickHouse#1842]
After install new version 1.1.54342, I see problem with Float32.

CREATE TABLE groot3.events_test_31_01_local
(
    event_hash String DEFAULT 'None', 
    ivi_id Int64, 
    latitude Float32 DEFAULT 0, 
    longitude Float32 DEFAULT 0, 
    rocket_date Date
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse_prod/{shard}/tables/events_test_31_01', '{replica}', rocket_date, event_hash, 8192)
Ok.
0 rows in set. Elapsed: 0.500 sec. `

CREATE TABLE groot3.events_test_31_01 AS groot3.events_test_31_01_local
ENGINE = Distributed(groot3, groot3, events_test_31_01_local, ivi_id)
Ok.
0 rows in set. Elapsed: 0.047 sec. `

:) INSERT INTO groot3.events_test_31_01 VALUES('test_hash',1, , ,'2015-01-01' )
Exception on client:
Code: 62. DB::Exception: Cannot parse expression of type Float32 here: , ,'2015-01-01' )

On previous version (1.1.54327) - works well

**Comment by alexey-milovidov** [comment]
Fixed in master.
