### ISSUE TITLE
Something strange with IN notation

### ISSUE THREAD

**Issue by akonyaev90** [yandex/ClickHouse#1846]
I have simple query:

> SELECT 
    uniqExact(ivi_id) AS uniq, 
    uniqExactIf(ivi_id, name = 'promo_view') AS uniqEq, 
    uniqExactIf(ivi_id, name IN 'promo_view') AS uniqIN
FROM groot2.events_merge_result 
WHERE (dt = toDate('2017-12-01')) AND (name = 'promo_view')

But the answer puzzled me.
I expected to see three identical values.
But:

> ┌───uniq─┬─uniqEq─┬─uniqIN─┐
    │ 955065 │ 955065 │ 834961 │
└────────┴────────┴────────┘

Can somebody help my?
I think this should work differently.

I use version 1.1.54327.

**Comment by duremar** [comment]
```
SELECT 
    uniqExact(x) AS u, 
    uniqExactIf(x, name = 'a') AS ue, 
    uniqExactIf(x, name IN ('a', 'b')) AS ui
FROM 
(
    SELECT 
        toNullable('a') AS name, 
        arrayJoin(range(10)) AS x
) 
WHERE name = 'a'

┌──u─┬─ue─┬─ui─┐
│ 10 │ 10 │  5 │
└────┴────┴────┘
```

**Comment by akonyaev90** [comment]
> SELECT 
    uniqExact(assumeNotNull(ivi_id)) AS uniq, 
    uniqExactIf(assumeNotNull(ivi_id), name = 'promo_view') AS uniqEq, 
    uniqExactIf(assumeNotNull(ivi_id), name IN 'promo_view') AS uniqIN
FROM groot2.events_merge_result 
WHERE (dt = toDate('2017-12-01')) AND (name = 'promo_view')

> ↖ Progress: 591.88 million rows, 5.97 GB (978.51 million rows/s., 9.87 GB/s.)  98%Received exception from server:
Code: 100. DB::Exception: Received from localhost:9001, 127.0.0.1. DB::Exception: Unknown packet 1468040 from server groot-clickhouse-dtln-1.vcp.digitalaccess.ru:9001, 192.168.59.4. 

When I try apply assumeNotNull for user_id, I catch exception like this.

**Comment by alexey-milovidov** [comment]
```
SELECT sum(toNullable('a') IN 'a')

┌─sum(in(toNullable(\'a\'), \'a\'))─┐
│                               192 │
└───────────────────────────────────┘
```

**Comment by alexey-milovidov** [comment]
Fixed in master.
