### ISSUE TITLE
FreeBSD-CURRENT

### ISSUE THREAD

**Issue by digitalist** [yandex/ClickHouse#1848]
возможно, все эти штуки решаются в cmake: поэтому одним issue

1. не находит sasl и валится на этапе сборки rdkafka
 при добавлении в основной CMakeLists.txt КХ
`include_directories(/usr/local/include)` (где и лежит sasl) - сборка rdkafka проходит

дальше:
2. cmake 3.10.2, не собирается `set.cc`: re2_st, size_ и elem_ not found. Насколько я понимаю, при замене в заголовках namespace на re2_st, не происходит подобной же замены в и исходниках

**Comment by proller** [comment]
Попробуйте 
https://github.com/proller/freebsd-ports/tree/master/databases/clickhouse
 - там должно быть все решено.

**Comment by digitalist** [comment]
о, спасибо, просто неплохо, если бы и из апстрима нормально собиралось через cmake.
п.1. я так понимаю совсем легко запатчить, а вот п.2 я не очень понял (про использование non thread-safe версий re2)

**Comment by proller** [comment]
а какой именно вызов cmake был?
И можно посмотреть что он в консоль написал?
И после того как make упадет - еще раз запустить ```make VERBOSE=1```  - и каике там комманды перед падением?

**Comment by digitalist** [comment]
билд:
```
git clone 
cd ClickHouse && mkdir -p cmake_build  && cd cmake_build
cmake ..
make

```
ошибка при сборке re2_st:
[re2.txt](https://github.com/yandex/ClickHouse/files/1696851/re2.txt)
cmake:
[cmake.txt](https://github.com/yandex/ClickHouse/files/1696852/cmake.txt)

**Comment by proller** [comment]
а можно удалить CMakeCache.txt и еще раз вывод cmake ?
или какая именно версия clang там ?

**Comment by digitalist** [comment]
FreeBSD clang version 6.0.0 (branches/release_60 323338) (based on LLVM 6.0.0)

**Comment by blinkov** [comment]
@digitalist проблема ещё актуальна?

**Comment by digitalist** [comment]
Для меня - нет. Я пока на линуксы вернулся. Вряд ли будет время проверить на Фре в ближайшем будущем
