### ISSUE TITLE
[Question] how to optimize groupArray query?

### ISSUE THREAD

**Issue by Jaxvk** [yandex/ClickHouse#1849]
I test `groupArray` the function, but when table `events` has more rows, the performance is getting worse and worse
```
SELECT 
    userid, 
    groupArray(event) AS events, 
    groupArray(timestamp) AS eventstimes, 
    arrayFilter((time, name) -> (name = 10001), eventstimes, events)[1] AS step1_time
FROM events 
GROUP BY userid
```

**Comment by ludv1x** [comment]
What datatypes of groupArray do you use?
I have not noticed performance degradation with groupArray for numeric and string types.
We need more details to investigate the issue.

Do `userid`s have uniform distribution?
Try to test performance with empty GROUP BY key (`SELECT ignore(groupArray(event) AS events, groupArray(timestamp) AS eventstimes) FROM events` ).

Also, you could compare your performance results with synthetic tests like:
SELECT length(groupArray(hex(number))) FROM (SELECT * FROM system.numbers LIMIT 100000000)

**Comment by Jaxvk** [comment]
@ludv1x, detailed information
### Hardware
five machines as five shards, each of them is CPU E5-2650 v3 @ 2.30GHz, raid5

### Table
local table : datacenter.trajectory_trackless_complex_shard
distribute table : datacenter.trajectory_trackless_complex, shard: rand()
rows: `select count() from datacenter.trajectory_trackless_complex`, 12333179553 rows
insert data: insert data via local table

### Major fields
pageid: UInt32
loginkey: UInt64
createtime: DateTime

### Test performance
#### test local table performance
```

SELECT ignore(groupArray(pageid) AS events, groupArray(createtime) AS eventstimes)
FROM trajectory_trackless_complex_shard 

┌─ignore(groupArray(pageid), groupArray(createtime))─┐
│                                                  0 │
└────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 29.307 sec. Processed 2.46 billion rows, 19.70 GB (84.03 million rows/s., 672.24 MB/s.) 
```

#### test distribute table performance
```
SELECT ignore(groupArray(pageid) AS events, groupArray(createtime) AS eventstimes)
FROM trajectory_trackless_complex 

↘ Progress: 12.33 billion rows, 98.67 GB (4.08 billion rows/s., 32.62 GB/s.) █████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ 98%Received exception from server (version 1.1.54342):
Code: 128. DB::Exception: Received from hadoop-180-111.bigdata.ly:9000, 10.12.180.111. DB::Exception: Too large array size: while receiving packet from hadoop-180-115.bigdata.ly:9000, 10.12.180.115. 

0 rows in set. Elapsed: 15.518 sec. Processed 12.33 billion rows, 98.67 GB (794.76 million rows/s., 6.36 GB/s.) 
```

### Funnel query
use condition to limit `intotime = '2018-02-03'`
```
SELECT 
    sum(step1_time != 0) AS homepage, 
    sum(step2_time != 0) AS listpage, 
    sum(step3_time != 0) AS orderpage
FROM 
(
    SELECT 
        loginkey, 
        groupArray(pageid) AS events, 
        groupArray(createtime) AS events_times, 
        arrayFilter((time, name) -> (name = 2538), events_times, events)[1] AS step1_time, 
        arrayFilter((time, name) -> ((name = 3242) AND (time >= step1_time) AND (step1_time != 0)), events_times, events)[1] AS step2_time, 
        arrayFilter((time, name) -> ((name = 1682) AND (time >= step2_time) AND (step2_time != 0)), events_times, events)[2] AS step3_time
    FROM 
    (
        SELECT 
            pageid, 
            createtime, 
            loginkey
        FROM datacenter.trajectory_trackless_complex 
        WHERE (pageid IN (2538, 3242, 1682)) AND (loginkey > 0) AND (intotime = '2018-02-03')
        ORDER BY createtime ASC
    ) 
    GROUP BY loginkey
) 

┌─homepage─┬─listpage─┬─orderpage─┐
│ 17994714 │  5994820 │   1144207 │
└──────────┴──────────┴───────────┘

1 rows in set. Elapsed: 68.580 sec. Processed 1.52 billion rows, 24.23 GB
```

don't use condition to limit `intotime`, throw exeception
↙ Progress: 12.12 billion rows, 193.95 GB (1.59 billion rows/s., 25.43 GB/s.) ███████████████████████████████████████████Rec██████████████████████████████████████████████████████████████████████████████▊ 98%eived exception from server (version 1.1.54342):
Code: 241. DB::Exception: Received from hadoop-180-111.bigdata.ly:9000, 10.12.180.111. DB::Exception: Memory limit (for query) exceeded: would use 196.39 GiB (attempt to allocate chunk of 12884901888 bytes), maximum: 186.26 GiB. 

### Question
I found if remove the condition `intotime`, the CPU usage of each machine is very low, it's just a bit of growth in memory at the requestor server
