### ISSUE TITLE
Cannot parse input when loading data

### ISSUE THREAD

**Issue by astudnev** [yandex/ClickHouse#1850]
I get an error
```
DB::Exception: Cannot parse input: expected , before: 76043,2017,7,12,3,16,1,4013462,\'0x3148a5385906ff85b007b47dd71cdce3e8bc5fcb7bdd17b8406664b3d39f6aac\',\'0xd997e1beb7450d6d07085a6357451364b992844e\',\'0xd997e1beb745: (at row 722)
```

when loading the attached file with the following HTTP POST:

```
http://clichouse?query=INSERT%20INTO%20references(tx_date,tx_time,year,month,mday,wday,hour,blockchain_id,block,tx_hash,tx_sender,tx_from,tx_to,address,smart_contract_address,smart_contract_id,signature_id,argument,external,internal)%20VALUES%20
```

Table schema is

```
CREATE TABLE references
(
    tx_date Date,
    tx_time DateTime,
    year    UInt16,
    month   UInt8,
    mday    UInt8,
    wday    UInt8,
    hour    UInt8,


    blockchain_id UInt32,
    block UInt32,
    tx_hash String,
    tx_sender String,
    tx_from String,
    tx_to String,
    address String,
    smart_contract_address String,
    smart_contract_id UInt32,
    signature_id UInt32,
    argument String,

    external UInt32,
    internal UInt32

) ENGINE = MergeTree(tx_date, tx_date, 8192);
```

If i remove the first record from the file, the error moves to the next record. If i remove more than 2 records, the error disappears. if i shuffle records, the error disappears, too.

I attached the trace and  the file with data

[references.txt](https://github.com/yandex/ClickHouse/files/1688598/references.txt)
[trace.log](https://github.com/yandex/ClickHouse/files/1688599/trace.log)

version 1.1.54342.

**Comment by astudnev** [comment]
Additional information that could be helpful: error happen on random files, but always around the 710 row (+/-10)

**Comment by astudnev** [comment]
https://groups.google.com/forum/#!topic/clickhouse/iAi9RMPldoc похоже на вопрос уже ответили. Проверю...

**Comment by ludv1x** [comment]
As a workaround, you could set `input_format_values_interpret_expressions=0` setting and use "strict" format for VALUES format. So, use ` 'YYYY-MM-DD HH:MM:SS'` representation for DateTime values instead of unix timestamps.

**Comment by alexey-milovidov** [comment]
ClickHouse parses data in `Values` format (as in `INSERT ... VALUES`) in one of two ways:

1. Fast path - it is used when all values are in expected form. For example, DateTime can be parsed in the `'2018-02-06 20:34:32'` form or in `'1517938472'` form. Note that in both forms it's expected that the value is in quotes.

2. Slow path - it is activated in exceptional case when parser cannot use fast path. Then it parses an expression with full-featured SQL parser, interprets parsed expression and performs type conversion. For example, expressions like `1 + 2` can be parsed, or `now()`, or `1517938472` without single quotes.

You can completely disable slow path by setting `input_format_values_interpret_expressions` to 0. It will make sure that the fast path is always used.

Slow path is actually very slow. And also it has some bugs: data is parsed in a buffer of some size (about hundreds of KB). When some value is not completely in the buffer, it cannot be parsed by slow path, and misleading error message is given. This is what happens in your case.


How to overcome this issue:

You can put unix timestamp in single quotes. Then set `input_format_values_interpret_expressions` to avoid using slow path ever.

How we can fix this issue:

1. It's reasonable to allow to parse unix timestamp as DateTime in Values format even if it is not in single quotes.

2. Stash some bytes from the buffer to allow to parse values located at the edge of the buffer even in slow path mode.

**Comment by alexey-milovidov** [comment]
Fix for DateTime is in master.
