### ISSUE TITLE
Cannot drop partition without password-less 'default' user

### ISSUE THREAD

**Issue by harlinb** [yandex/ClickHouse#1861]
It looks like the 'ALTER TABLE DROP PARTITION' command is expecting a default user with no password.

ALTER TABLE test
DROP PARTITION ('2018-02-05')

Received exception from server:
Code: 192. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Received from node-03:9000, 10.71.1.156. DB::Exception: Unknown user default.

where test is using the 'ReplicatedMergeTree' engine
clickhouse v1.1.54318

**Comment by ludv1x** [comment]
As a workaround, you could send `DROP PARTITION` query to another (leader) replica. 
This happens if the query is sent to non-leader replica, in that case, the replica forwards the query to the leader using default user.

**Comment by harlinb** [comment]
Good to know, thanks for the quick answer.

**Comment by PangKuo** [comment]
@ludv1x  hi, I found the non-leader replica send query to the leader using default user, too. However, we don't use default database and default user in most case. Do you know any way to customize user and password? Thank you very much!

**Comment by filimonov** [comment]
#2202 should fix that, but according to reports from Telegram channel problem still exists.

**Comment by Farfaday** [comment]
Seems that we are also affected with "OPTIMIZE TABLE". We are running version 18.12.14.

**Comment by fokkoru** [comment]
My default user has the password, but I cannot remove the partition 
```
ClickHouse client version 18.14.10.
Connecting to localhost:9000.
Connected to ClickHouse server version 18.14.10 revision 54409.

prusech001 :) ALTER TABLE r0.events DROP PARTITION '2018-03-12';

ALTER TABLE r0.events
    DROP PARTITION '2018-03-12'


Received exception from server (version 18.14.10):
Code: 194. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Received from prusech003:9000, 10.90.12.6. DB::Exception: Password required for user default.

0 rows in set. Elapsed: 0.047 sec.
```

**Comment by fokkoru** [comment]
Also, OPTIMIZE TABLE
```
ClickHouse client version 18.14.10.
Connecting to localhost:9000.
Connected to ClickHouse server version 18.14.10 revision 54409.

prusech001 :) OPTIMIZE TABLE r0.events;

OPTIMIZE TABLE r0.events

Received exception from server (version 18.14.10):
Code: 194. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Received from prusech003:9000, 10.90.12.6. DB::Exception: Password required for user default.

0 rows in set. Elapsed: 0.007 sec.
```

**Comment by Farfaday** [comment]
Hi,
it seems that we are not affected anymore with clickhouse version 19.3.6 :)
Thanks !

**Comment by filimonov** [comment]
PR #3598 fixes that.

**Comment by filimonov** [comment]
PR #3598 fixes that (should work properly in versions > 19.1)

To make it work you need to have a cluster properly configured with user credentials.  

Generally, when you do some DDL on non-leader replica it forwards the request to a leader, and during that forwarding "default" passwordless user was used.
