### ISSUE TITLE
Convert String to AggregateFunction

### ISSUE THREAD

**Issue by kanterov** [yandex/ClickHouse#1862]
There is a similar issue, but I didn't find the solution to my problem. https://github.com/yandex/ClickHouse/issues/756

I have a pre-aggregated dataset that contains rows similar to `stddevPopStableState`: `count: UInt64`, `mean: Float64` and `m2: Float64`. I want to ingest it into ClickHouse `AggregateMergeTree`.

It seems there is a way to access underlying state:
```
SELECT CAST(stddevPopState(1) AS String)

┌─CAST(stddevPopState(1), \'String\')────────┐
│ \0\0\0\0\0\0�?\0\0\0\0\0\0�?\0\0\0\0\0\0�? │
└────────────────────────────────────────────┘
```

But conversion from `String` doesn't work:

```
SELECT CAST(CAST(stddevPopState(1) AS String) AS AggregateFunction(stddevPop, UInt8))

Received exception from server (version 1.1.54337):
Code: 70. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Conversion from String to AggregateFunction(stddevPop, UInt8) is not supported.
```

What I have found in the source code is:

```
/// It's possible to use ConvertImplGenericFromString to convert from String to AggregateFunction,
///  but it is disabled because deserializing aggregate functions state might be unsafe.
```

Do you have any suggestion how to get my dataset into `AggregateMergeTree`? I'm fine with ingesting plain byte array with state of the aggregator if it can help.

**Comment by alexey-milovidov** [comment]
It is still possible to insert data from a dump with any allowed format (TabSeparated, RowBinary, etc.),
though it is unsafe by the same reason.

Appropriate solution will be to add a setting to allow conversion, disabled by default.

**Comment by kanterov** [comment]
Thanks, @alexey-milovidov. Ingesting in RowBinary and Native formats seem to work for me.
