### ISSUE TITLE
Fail on dropping materialised view removes alias but not inner table

### ISSUE THREAD

**Issue by inkrement** [yandex/ClickHouse#1863]
When a drop table on a materialised view X fails because of this 50GB-limitation, the alias X get's deleted anyway but not the "real table" .inner.X. 

Is this behaviour intended?

**Comment by ludv1x** [comment]
Indeed, there is some inconsistency here. If you drop a MV (which size is 0), a real table should be dropped and checked also, but the size of the MV is only checked.
