### ISSUE TITLE
Unused Parameter when using preinstalled poco-lib

### ISSUE THREAD

**Issue by lugt** [yandex/ClickHouse#1874]
This happens when I'm compiling in:
`ClickHouse/dbms/src/IO/InterserverWriteBuffer.cpp` :

Make : 

In constructor 
```shell
‘DB::InterserverWriteBuffer::InterserverWriteBuffer(...)’:
27:28: error: unused parameter ‘send_timeout’ [-Werror=unused-parameter]
     const Poco::Timespan & send_timeout,
                            ^~~~~~~~~~~~
28:28: error: unused parameter ‘receive_timeout’ [-Werror=unused-parameter]
     const Poco::Timespan & receive_timeout)
                            ^~~~~~~~~~~~~~~
```
I've added some some non-effect code to avoid this and it works then,

**Comment by lugt** [comment]
Maybe there can be some kind of trivial use of these two parameters, to circumvent the state of not being used.

**Comment by lugt** [comment]
I've changed it to a void cast and it works fine.


#if POCO_CLICKHOUSE_PATCH || POCO_VERSION >= 0x02000000
    session.setTimeout(connection_timeout, send_timeout, receive_timeout);
#else
    session.setTimeout(connection_timeout);
    static_cast <void> (send_timeout);
    static_cast <void> (receive_timeout);
#endif

**Comment by alexey-milovidov** [comment]
Yes, this is correct solution.
Do you want to make a pull request? (Or we can commit it.)

**Comment by lugt** [comment]
I'll make one. Thx.
