### ISSUE TITLE
Build release package error:add_subdirectory given source "Compiler-7.0.0svn" which is not an existing directory

### ISSUE THREAD

**Issue by zhai3516** [yandex/ClickHouse#1876]
Build release package error with cmd `./release` : 

> -- Will build ClickHouse 1.1.54342
> -- Using internal compiler: headers=/usr/share/clickhouse/headers : clickhouse-clang -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -std=c++17  -D_GLIBCXX_USE_CXX11_ABI=1 -pipe -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall  -Wnon-virtual-dtor   -Wextra -Werror -O3 -DNDEBUG -std=c++1z -x c++ -march=native -fPIC -fvisibility=hidden -fno-implement-inlines -nostdinc -nostdinc++ -Wno-unused-command-line-argument -Bprefix=/usr/share/clickhouse -isysroot=/usr/share/clickhouse/headers; clickhouse-lld
> CMake Error at dbms/src/Server/CMakeLists.txt:49 (add_subdirectory):
>   add_subdirectory given source "Compiler-7.0.0svn" which is not an existing
>   directory.
> 
> 
> -- Target check already exists
> -- Configuring incomplete, errors occurred!
> See also "/data/apps/ClickHouse/build/CMakeFiles/CMakeOutput.log".
> See also "/data/apps/ClickHouse/build/CMakeFiles/CMakeError.log".
> dh_auto_configure: cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE= -DUSE_EMBEDDED_COMPILER=1 -DENABLE_TESTS=0 -DCMAKE_CXX_COMPILER=/usr/local/bin/g++-7 -DCMAKE_C_COMPILER=/usr/local/bin/gcc-7 -DCMAKE_VERBOSE_MAKEFILE=0 -DENABLE_TESTS=0 -DCMAKE_CXX_COMPILER=/usr/local/bin/g++-7 -DCMAKE_C_COMPILER=/usr/local/bin/gcc-7 -DCMAKE_VERBOSE_MAKEFILE=0 returned exit code 1
> make[1]: *** [override_dh_auto_configure] Error 2
> make[1]: Leaving directory `/data/apps/ClickHouse'
> make: *** [build] Error 2
> dpkg-buildpackage: error: debian/rules build gave error exit status 2
> debuild: fatal error at line 1357:
> dpkg-buildpackage -rfakeroot -d -us -uc -b failed

my cmake version:

> root@xxx#:/data/apps/ClickHouse# cmake --version
> cmake version 3.10.2
> 

my gcc version:

> root@xxx#:/data/apps/ClickHouse# gcc -v
> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-pc-linux-gnu/7.3.0/lto-wrapper
> Target: x86_64-pc-linux-gnu
> Configured with: ../gcc-7.3.0/configure --enable-languages=c,c++ --disable-multilib
> Thread model: posix
> gcc version 7.3.0 (GCC)

I find Compiler-6.0.0 in this derectory. Does my clang version too high?  I use the `utils/prepare-environment` scrips to install gcc and clang. 

thanks

**Comment by alexey-milovidov** [comment]
We should add Compiler-7.0.0 directory to support newer clang.

**Comment by proller** [comment]
Already fixed and tested:
https://github.com/yandex/ClickHouse/commit/15e77ec68815013cdf619f3b29ae90f064c1f55b
