### ISSUE TITLE
Console Client break to new line

### ISSUE THREAD

**Issue by f1yegor** [yandex/ClickHouse#188]
When I start to type some command `select * from events group |`
and at this moment want to cancel input and get new empty line. 
Like in bash console `Ctrl^C` but couldn't. 
Ctrl^D is ignored unless current line is empty. 

Possible workarounds for now:
1. Ctrl^A Ctrl&K if multiline mode not used.
2. type `;` and execute wrong/not-complete query(and also garbage history)

**Comment by VladRassokhin** [comment]
Also `Ctrl^U` helps

**Comment by alexey-milovidov** [comment]
Fixed in master.
Ctrl+C works as expected.
