### ISSUE TITLE
[Question] how to optimize the configuration of clickhouse-server

### ISSUE THREAD

**Issue by Jaxvk** [yandex/ClickHouse#1883]
Hi, my machine: CPU E5-2650 v3, 384g memoery, raid5
how to optimize the configuration of clickhouse-server to extrude the machine? thank you

**Comment by ztlpn** [comment]
It depends on your query load. A good first step is to determine which resource (CPU, network bandwith or disk IO) is the bottleneck. You can do it using standard unix tools (e.g. dstat).

**Comment by Jaxvk** [comment]
:+1:
