### ISSUE TITLE
Fastest way of transform to array

### ISSUE THREAD

**Issue by fireya** [yandex/ClickHouse#1894]
Hello!
I am looking for fastest way of transforming simple type (int64) to array (for example, int64).
Test scenario: table with 100 millions of rows.
I have three solutions:
1.  `select transform(Dim1,[1,2],[10,20],0) as c1,sum(Value) from data100m group by c1`
this is very fast, 0.312 sec, but doesn't support arrays as U type.
2. `select [[10],[20]][Dim1] as c1,sum(Value) from data100m group by c1`
this query is significantlly slowly: 1.8 sec
and it assumes, that values of Dim1 will be very small
3. `select dictGetHierarchy('dim01',Dim1) as c1,sum(Value) from data100m group by c1`
this query takes 4.339 sec. I guess, because of there is no any cache in dictGetHierarchy and it calculates on every row.

PS: i can not do intermediate `group by Dim1`, because number of groups will be numerous (there will be `group by Dim1, Dim2, Dim3, etc...`)

Are there any plans to allow array type as U in transform func?
Or any plans to improve speed of dictGetHierarchy?

**Comment by ztlpn** [comment]
Hi! I am not sure I understand what you are trying to achieve (queries 1 and 2 produce different output), can you try to state it more clearly? Some examples of input and desired output would be helpful.

Why is simple `SELECT [f(Dim1)] FROM ...` insufficient?

**Comment by fireya** [comment]
I will try to explain from beginning.
I have multiple hierarchical dictionaries, for example:

Hierarchy1:
1
|_ 2
   3
   |_4

Hierarchy2:
1
|_ 2
3
|_ 4

And some table with 100 millions of rows:
`CREATE table TestTable(Dim1 UInt64, Dim2 UInt64, Value UInt64)`

I need to transform value to all parents in hierarchy and do some kind of aggregations. So canonical query is:
`select dictGetHierarchy('dim01',Dim1) as c1,dictGetHierarchy('dim02',Dim2) as c2,sum(Value) from TestTable group by c1, c2`

It gaves results what i expect, but it is slow.

After some kind of experiments, i have found, that if values are small, then using array of arrays is faster then dictGetHierarchy:

`select [[1],[2,1],[3,1],[4,3,1]][Dim1] as c1,[[1],[2,1],[3],[4,3]][Dim2] as c2,sum(Value) from TestTable group by c1, c2`

This query works much faster, but it works only for small integer values.

Then i have found transform func: https://clickhouse.yandex/docs/ru/functions/other_functions.html#transform

I tried to use it:
`select transform(Dim1,[1,2,3,4],[[1],[2,1],[3,1],[4,3,1]],[0]) as c1,transform(Dim2,[1,2,3,4],[[1],[2,1],[3],[4,3]],[0]) as c2 from TestTable group by c1, c2`
and got error:
>Code: 43, e.displayText() = DB::Exception: Unsupported type Array(UInt8) of fourth argument (default value) of function transform, must be numeric type or Date/DateTime or String, e.what() = DB::Exception 

As stated in documentation, type U in transform func must be int,string or date. Arrays are not supported.

I tried to simplify my query to test performance of transform:
`select transform(Dim1,[1,2,3,4],[10,20,30,40],0) as c1,transform(Dim2,[1,2,3,4],[10,20,30,40],0) as c2 from TestTable group by c1, c2`
 and performance is very well.

So my question are:

- is there any other method i haven't tried?
- can trasform function support arrays as U type? This is the best and simplest solution for me.
- can performance of dictGetHierarchy be improved?

**Comment by alexey-milovidov** [comment]
> can trasform function support arrays as U type? This is the best and simplest solution for me.

It is not so hard to implement.

> is there any other method i haven't tried?

You can combine array-of-arrays subscript and transform function: first transform to indices (1..n), then do array subscript.

> can performance of dictGetHierarchy be improved?

There are some reasons for worse performance of dictGetHierarchy. First, fundamendal reason: it creates an array with hierarchy through one by one iteration over that hierarchy (prepared arrays with hierarchies are not stored in memory to save memory consumption). Second, there are some implementation details, that can be improved.

And also it is possible to implement array-valued dictionaries.

**Comment by fireya** [comment]
thank you very much for clarification
