### ISSUE TITLE
Handling the same names for functions and columns

### ISSUE THREAD

**Issue by the-tinderbox** [yandex/ClickHouse#1896]
The proposal is to throw exception or run function when table contains column which names the same as functions names if column name in select statement and is not escaped in ``.

Lets use this query as source table:

```sql
SELECT
    age,
    count()
FROM
(
    SELECT roundAge(number) AS age
    FROM system.numbers
    LIMIT 100
)
GROUP BY age
```
The result would be

```
┌─age─┬─count()─┐
│   0 │       1 │
│  17 │      17 │
│  18 │       7 │
│  25 │      10 │
│  35 │      10 │
│  45 │      10 │
│  55 │      45 │
└─────┴─────────┘
```

Now i want to count total number of ages encountered from table:

```sql
SELECT count()
FROM
(
    SELECT
        age,
        count()
    FROM
    (
        SELECT roundAge(number) AS age
        FROM system.numbers
        LIMIT 100
    )
    GROUP BY age
)
```

Result would be:

```
┌─count()─┐
│       1 │
│      17 │
│       7 │
│      10 │
│      10 │
│      10 │
│      45 │
└─────────┘
```

I think, that if you want to select column from table with the same name as function name you should escape column name in select statement like this:

`select `count()`, ... from ...`

In other cases run function or throw exception.

**Comment by alexey-milovidov** [comment]
Fixed in master.
