### ISSUE TITLE
Minor bugfix to russian doc 1

### ISSUE THREAD

**Issue by syaroslavtsev** [yandex/ClickHouse#19]
1)
-"Вы можете прервать длинный запрос, нажав Ctrl+C. При этом вам всё-равно придётся чуть-чуть подождать, пока сервер остановит запрос. На некоторых стадиях выполнения, запрос невозможно прервать. Если вы не дождётесь и нажмёте Ctrl+C второй раз, то клиент будет завершён."
+"Вы можете прервать длинный запрос, нажав Ctrl+C. При этом вам всё равно придётся чуть-чуть подождать, пока сервер остановит запрос. На некоторых стадиях выполнения, запрос невозможно прервать. Если вы не дождётесь и нажмёте Ctrl+C второй раз, то клиент будет завершён."

-"Принимает Float32 или Float64 и возвращает UInt8, равный 1, если агрумент не бесконечный и не NaN, иначе 0."
+"Принимает Float32 или Float64 и возвращает UInt8, равный 1, если аргумент не бесконечный и не NaN, иначе 0."

-"Принимает строку, число, дату или дату-с-временем. Возвращает строку, содержащую шестнадцатиричное представление аргумента. Используются заглавные буквы A-F. Не используются префиксы %%0x%% и суффиксы %%h%%. Для строк просто все байты кодируются в виде двух шестнадцатиричных цифр. Числа выводятся в big endian ("человеческом") формате. Для чисел вырезаются старшие нули, но только по целым байтам. Например, %%hex(1) = '01'%%. Даты кодируются как число дней с начала unix-эпохи. Даты-с-временем кодируются как число секунд с начала unix-эпохи."
+"Принимает строку, число, дату или дату-с-временем. Возвращает строку, содержащую шестнадцатеричное представление аргумента. Используются заглавные буквы A-F. Не используются префиксы %%0x%% и суффиксы %%h%%. Для строк просто все байты кодируются в виде двух шестнадцатеричных цифр. Числа выводятся в big endian ("человеческом") формате. Для чисел вырезаются старшие нули, но только по целым байтам. Например, %%hex(1) = '01'%%. Даты кодируются как число дней с начала unix-эпохи. Даты-с-временем кодируются как число секунд с начала unix-эпохи."

**Comment by alexey-milovidov** [comment]
Спасибо, исправил!
https://github.com/yandex/ClickHouse/commit/2fbf85a68207cdb205b1a04e7e495fe4d07dd453

При желании, можете сразу отправлять в виде pull request (а то здесь я не сразу разглядел изменения).

**Comment by alexey-milovidov** [comment]
На сайте обновится само через несколько минут.

**Comment by syaroslavtsev** [comment]
Добрый день. К своему великому сожалению на данный момент нет возможности.
Есть несколько вопросов по продукту:
Есть спецификация на code convention для проекта и комментариям, Public CI
and deployment script for experiments without using docker, for example
vagrant?
Возможно у Вас есть или у Yandex планы в будущем по интеграции с другими
решениями из стека BigDarta, типа spark/kafka/storm/jasperreports/presto?
С чем-то типа R/SAS/SPSS для построения статистико-математических моделей?
Планируется ли в ближайшей будущем подписание партнерского соглашение с
какими-то хостинговыми компаниями по предоставлению решения в виде SAAS?

2016-06-21 1:36 GMT+04:00 alexey-milovidov <notifications@github.com>:

> Спасибо, исправил!
> 2fbf85a
> <https://github.com/yandex/ClickHouse/commit/2fbf85a68207cdb205b1a04e7e495fe4d07dd453>
>
> При желании, можете сразу отправлять в виде pull request (а то здесь я не
> сразу разглядел изменения).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/yandex/ClickHouse/issues/19#issuecomment-227277240>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADS8njfut5ZB4_6KSdL6I7X5LTGZgY8nks5qNwfpgaJpZM4I4BLE>
> .
>



-- 
С наилучшими пожеланиями,

Сергей Ярославцев

**Comment by alexey-milovidov** [comment]
> Есть спецификация на code convention для проекта и комментариям

Есть. Только что добавил эту спецификацию в дерево проекта.
https://github.com/yandex/ClickHouse/blob/master/doc/style_ru.md

> Public CI

Есть только внутренний CI. Он поддерживается другой командой и не открыт.

> deployment script for experiments without using docker, for example vagrant?

Нет.
Тем не менее, установить ClickHouse под Vagrant довольно просто - так же как на обычный сервер с Ubuntu.

> Возможно у Вас есть или у Yandex планы в будущем по интеграции с другими решениями из стека BigDarta, типа spark/kafka/storm/jasperreports/presto? С чем-то типа R/SAS/SPSS для построения статистико-математических моделей? 

Есть планы по интеграции с некоторыми BI-системами.

> Планируется ли в ближайшей будущем подписание партнерского соглашение с какими-то хостинговыми компаниями по предоставлению решения в виде SAAS?

Не могу сказать.
