### ISSUE TITLE
Empty values in INSERT INTO expression causes parsing exception

### ISSUE THREAD

**Issue by cerealcoder** [yandex/ClickHouse#1904]
Note: this issue is similar in nature to issue #469.

When executing an `INSERT INTO` statement that contains a `VALUES` clause that contains multiple adjacent commas, the Clickhouse server produces the following error message in file `clickhouse/logs/clickhouse-server.err.log`:

`<Error> HTTPHandler: Code: 62, e.displayText() = DB::Exception: Cannot parse expression of type String here: ,,,,,,,,,,,,,,,,,'https://tellme.social/',,), ('help','guest','2018-02-09','Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0',, e.what() = DB::Exception, Stack trace:`

The complete `INSERT INTO` statement we're using is:

`INSERT INTO userActionsTemp ( action, userId, actionDate, userAgent, language, hardwareConcurrency, adBlock, hasTamperedLanguages, hasTamperedResolution, hasTamperedOS, hasTamperedBrowser, fingerprint, loginMethod, storyId, storyTagIds, shareTarget, shareFailureReason, storyFilterName, storyFilterMode, storyFilterWords, storyFilterAuthorNames, storyFilterTagIds, storyFilterPeopleNames, storyFilterExclusionTagIds, storyFilterCircaAfterDate, storyFilterCircaBeforeDate, storyReviewNumberOfStars, storyReviewTagIds, tagId, currentUrl, previousUrl, numAdsServed) VALUES ('urlTransition','guest','2018-02-09','Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36','en-US',4,0,0,0,0,0,'b7e609741bcd4886d21c4d5e6ed1814f',,,,,,,,,,,,,,,,,,'https://tellme.social/',,), ('help','guest','2018-02-09','Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0','en-US',8,1,0,0,0,0,'3cf3f888cdcd0983cbe2840133e843d3',,,,,,,,,,,,,,,,,,,,), ('storyFilterUtilize','guest','2018-02-09','Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36','en-US',8,0,0,0,0,0,'209659044477415c233486a31bf4be34',,,,,,'SimpleStoryFilter','AND',,,,,,,,,,,,,)`

Do you have a suggested workaround for this issue? That is, if we cannot use the standard CSV syntax to represent a null value for a string, how should we do so?

**Comment by ztlpn** [comment]
Values format expects empty strings to be enclosed in single quotes, like this: `VALUES (...,'',...)`. If you want the CSV syntax for inserted data, you should use the CSV format (`INSERT INTO ... FORMAT CSV`).

**Comment by cerealcoder** [comment]
Thank you for the clarification!
