### ISSUE TITLE
Unsuccessful upgrade from 1.1.54318 to 1.1.54342 because of DateTime exception

### ISSUE THREAD

**Issue by bocharov** [yandex/ClickHouse#1918]
We tried to do the rolling upgrade of Clickhouse from 1.1.54318 to 1.1.54342 stable and faced the following exception:
```
Code: 378. DB::Exception: Received from <host>. DB::Exception: Data type DateTime cannot have arguments: while receiving packet from <host>:<port>, <host>.
```
It happens when some node with old version (1.1.54318) sends distributed query to another node with new version (1.1.54342). Simplest query example on old node is:
```
SELECT toStartOfHour(timeslot)
FROM <some_distributed_table>
WHERE date = '2018-01-01'
LIMIT 1
```
timeslot is `DateTime` type, date is `Date` type.

We thought, that maybe problem is related to this changelog:

> Improved support for timezones. The DateTime data type can be annotated with the timezone that is used for parsing and formatting in text formats. Example: DateTime('Europe/Moscow'). When timezones are specified in functions for DateTime arguments, the return type will track the timezone, and the value will be displayed as expected.

And it seems that code should handle such problem correctly: https://github.com/yandex/ClickHouse/blob/60477a9aaac73f283d0428b1f357de339512dcf3/dbms/src/DataStreams/NativeBlockOutputStream.cpp#L158

We do the rolling upgrade as usual and it means that we can have different versions of Clickhouse server during the upgrade. Our cluster is big and we can't tolerate query exceptions for long period of time, we need at least 1+ hour to do the full upgrade. Is there anything we can do to avoid this exception and continue with upgrade?

**Comment by alexey-milovidov** [comment]
```
#define DBMS_MIN_REVISION_WITH_TIME_ZONE_PARAMETER_IN_DATETIME_DATA_TYPE 54311
```

That is slightly incorrect and compatibility isn't working for 1.1.54318.

**Comment by alexey-milovidov** [comment]
To avoid this issue, you can postpone upgrade until the next version will be released.
Another possibility is to backport this patch a074b77 and rebuild ClickHouse.

**Comment by bobrik** [comment]
@alexey-milovidov, when do you plan to cut the next stable release? I wonder if we should just wait for that and avoid extra restart round.

**Comment by ztlpn** [comment]
Unfortunately we have tagged a release candidate just before the fix was committed. In case there are no critical problems with it the next release candidate will not appear until after a ~week.

**Comment by bocharov** [comment]
@alexey-milovidov thanks, we're going to backport the patch and try again.
