### ISSUE TITLE
htop startup time 16 threads

### ISSUE THREAD

**Issue by wer** [yandex/ClickHouse#1944]
even with a configuration like this:
```
max_threads: 1
distributed_connections_pool_size: 1
background_pool_size: 1
```
when i use htop i see 16 green threads, could you please explain why?
![screen shot 2018-02-22 at 12 56 21](https://user-images.githubusercontent.com/281600/36534632-d54ff546-17cf-11e8-8f54-9e578b4cd0dc.png)

**Comment by alexey-milovidov** [comment]
As you see on the screenshot, that threads use 0.0% of CPU time and they are sleeping (S).
The green color in htop means "this is thread, not process" and it is completely irrelevant to status or CPU usage.
