### ISSUE TITLE
Clarification on Documentation on Features May Considered Disadvantage

### ISSUE THREAD

**Issue by osbertngok** [yandex/ClickHouse#1945]
https://github.com/yandex/ClickHouse/commit/13d9a4eebee35882f580e06573f1228064265312#diff-1d7fbf038664af29c293810d494040d7R4

> For aggregation, query results must fit in the RAM on a single server. **However, the volume of source data for a query may be indefinitely large.**

What exactly does this sentence want to convey? Does it mean:

A. The limitation of Clickhouse is that the intermediate result must be able to fit in RAM in a single machine, but when the volume of source data is huge, some queries might not be able to fit in, leaving Clickhouse unable to work in those scenarios,

or 

B. The limitation of Clickhouse is that the intermediate result must be able to fit in RAM in a single machine, but that doesn't mean it has any requirement to the volume of the source data - it can be arbitrarily large, as long as the intermediate (aggregated) result can be fit in the RAM in a single machine?

Many thanks! (A couple of Chinese users are translating the documentation in Chinese, and just to make sure it reflects the original intentions of the documentation)

**Comment by osbertngok** [comment]
c.c. @sundy-li

**Comment by alexey-milovidov** [comment]
B.

**Comment by alexey-milovidov** [comment]
And it is slightly outdated.

ClickHouse has support to perform GROUP BY and ORDER BY even if intermediate data doesn't fit in RAM. You can find it in documentation as "GROUP BY in external memory" https://clickhouse.yandex/docs/en/query_language/queries/#group-by-in-external-memory and in "ORDER BY clause" https://clickhouse.yandex/docs/en/query_language/queries/#order-by-clause

But for other types of intermediate data (for IN, JOIN and DISTINCT) it still has to fit in memory during query processing.

**Comment by osbertngok** [comment]
Very informative. Many thanks!
