### ISSUE TITLE
Found parts with the same min block and with the same max block as the missing part

### ISSUE THREAD

**Issue by perez1987** [yandex/ClickHouse#1952]
Hello,

We are encountering two problems that may be related.

- On the one hand we see that when executing a querie in one node and in another the results that it returns to us are different.

- On the other hand, we are seeing these errors that concern us a lot:

2018.02.23 09:59:24.581090 [ 32 ] <Warning> PRO.TimeEvents_Table_Rep (StorageReplicatedMergeTree, PartCheckThread): Checking part 20180206_20180206_99948_99953_1
2018.02.23 09:59:24.581302 [ 13 ] <Information> PRO.TimeEvents_Table_Rep (StorageReplicatedMergeTree): DB::Exception: No active replica has part 20180206_20180206_99948_99953_1 or covering part
2018.02.23 09:59:24.581890 [ 32 ] <Warning> PRO.TimeEvents_Table_Rep (StorageReplicatedMergeTree, PartCheckThread): Checking if anyone has a part covering 20180206_20180206_99948_99953_1.
2018.02.23 09:59:24.587585 [ 32 ] <Warning> PRO.TimeEvents_Table_Rep (StorageReplicatedMergeTree, PartCheckThread): Found parts with the same min block and with the same max block as the missing part 20180206_20180206_99948_99953_1. Hoping that it will eventually appear as a result of a merge.
2018.02.23 09:59:24.597278 [ 129620 ] <Information> HTTPHandler: Done processing query
2018.02.23 09:59:24.597867 [ 32 ] <Warning> PRO.TimeEvents_Table_Rep (StorageReplicatedMergeTree, PartCheckThread): Checking part 20180207_20180207_2473053_2473060_1
2018.02.23 09:59:24.598054 [ 8 ] <Information> PRO.TimeEvents_Table_Rep (StorageReplicatedMergeTree): DB::Exception: No active replica has part 20180207_20180207_2473053_2473060_1 or covering part
2018.02.23 09:59:24.598501 [ 32 ] <Warning> PRO.TimeEvents_Table_Rep (StorageReplicatedMergeTree, PartCheckThread): Checking if anyone has a part covering 20180207_20180207_2473053_2473060_1.
2018.02.23 09:59:24.599426 [ 129621 ] <Information> executeQuery: Read 1 rows, 1.00 B in 0.000 sec., 3353 rows/sec., 3.27 KiB/sec.
2018.02.23 09:59:24.599605 [ 129621 ] <Information> HTTPHandler: Done processing query
2018.02.23 09:59:24.599904 [ 9 ] <Information> PRO.TimeEvents_Table_Rep (StorageReplicatedMergeTree): No active replica has part 20180206_20180206_71374_71374_0. Will fetch merged part instead.
2018.02.23 09:59:24.603875 [ 9 ] <Information> PRO.TimeEvents_Table_Rep (StorageReplicatedMergeTree): DB::Exception: No active replica has part 20180206_20180206_246518_246525_1 or covering part
2018.02.23 09:59:24.605082 [ 32 ] <Warning> PRO.TimeEvents_Table_Rep (StorageReplicatedMergeTree, PartCheckThread): Found parts with the same min block and with the same max block as the missing part 20180207_20180207_2473053_2473060_1. Hoping that it will eventually appear as a result of a merge.
2018.02.23 09:59:24.605378 [ 32 ] <Warning> PRO.TimeEvents_Table_Rep (StorageReplicatedMergeTree, PartCheckThread): Checking part 20180206_20180206_246518_246525_1
2018.02.23 09:59:24.606072 [ 32 ] <Warning> PRO.TimeEvents_Table_Rep (StorageReplicatedMergeTree, PartCheckThread): Checking if anyone has a part covering 20180206_20180206_246518_246525_1.
2018.02.23 09:59:24.611927 [ 32 ] <Warning> PRO.TimeEvents_Table_Rep (StorageReplicatedMergeTree, PartCheckThread): Found parts with the same min block and with the same max block as the missing part 20180206_20180206_246518_246525_1. Hoping that it will eventually appear as a result of a merge.

Can you help us? Thank you very much!

**Comment by lamber-ken** [comment]
+1, @alexey-milovidov , we also meet the message

**Comment by tust05102405** [comment]
+1, version 1.1.54390
any idea for solve it？ @alexey-milovidov @ztlpn 
thank you very match

**Comment by filimonov** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. 

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!

**Comment by honmaple** [comment]
This issue still happen on `ClickHouse server version 19.15.2.2 (official build).` 
How can I fix it?
```
2019.11.19 10:54:50.930268 [ 14 ] {} <Warning> fulllog.attack_local: Part 320_0_15895_15 is covered by 320_0_15895_16 but should be merged into 320_0_22211_16. This shouldn't happen often.
2019.11.19 10:54:50.930803 [ 64 ] {} <Warning> fulllog.attack_local (ReplicatedMergeTreePartCheckThread): Checking part 320_0_22211_16
2019.11.19 10:54:50.931331 [ 64 ] {} <Warning> fulllog.attack_local (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part covering 320_0_22211_16.
2019.11.19 10:54:50.932457 [ 64 ] {} <Warning> fulllog.attack_local (ReplicatedMergeTreePartCheckThread): Found parts with the same min block and with the same max block as the missing part 320_0_22211_16. Hoping that it will eventually appear as a result of a merge.
```

**Comment by honmaple** [comment]
This issue still happen on `ClickHouse server version 19.15.2.2 (official build).` 
How can I fix it?
```
2019.11.19 11:08:30.515068 [ 20 ] {} <Warning> logtest.test_local: Part 318_26055_30571_5 is covered by 318_26055_30571_6 but should be merged into 318_26055_32627_46. This shouldn't happen often.
2019.11.19 11:08:30.515819 [ 23 ] {} <Warning> logtest.test_local (ReplicatedMergeTreePartCheckThread): Checking part 318_26055_32627_46
2019.11.19 11:08:30.516579 [ 23 ] {} <Warning> logtest.test_local (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part covering 318_26055_32627_46.
2019.11.19 11:08:30.518288 [ 23 ] {} <Warning> logtest.test_local (ReplicatedMergeTreePartCheckThread): Found parts with the same min block and with the same max block as the missing part 318_26055_32627_46. Hoping that it will eventually appear as a result of a merge.
```

**Comment by woozhijun** [comment]
> 19.15.2.2

Hi, Has your problem solved？

**Comment by Amixp** [comment]
I have this:
`
2020.09.15 07:57:37.817047 [ 9379 ] {} <Warning> radius.radacct: Part 202002-1_394_394_0 is covered by 202002-1_394_398_1 but should be merged into 202002-1_394_400_1. This shouldn't happen often.
2020.09.15 07:57:37.883105 [ 9399 ] {} <Warning> radius.radacct (ReplicatedMergeTreePartCheckThread): Checking part 202002-1_394_400_1
2020.09.15 07:57:37.905059 [ 9399 ] {} <Warning> radius.radacct (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part covering 202002-1_394_400_1.
2020.09.15 07:57:37.949654 [ 9399 ] {} <Warning> radius.radacct (ReplicatedMergeTreePartCheckThread): Found parts with the same min block and with the same max block as the missing part 202002-1_394_400_1. Hoping that it will eventually appear as a result of a merge.
2020.09.15 07:57:38.241059 [ 9376 ] {} <Warning> radius.radacct: Part 202002-1_394_394_0 is covered by 202002-1_394_398_1 but should be merged into 202002-1_394_400_1. This shouldn't happen often.
2020.09.15 07:57:38.307718 [ 9416 ] {} <Warning> radius.radacct (ReplicatedMergeTreePartCheckThread): Checking part 202002-1_394_400_1
2020.09.15 07:57:38.329854 [ 9416 ] {} <Warning> radius.radacct (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part covering 202002-1_394_400_1.
2020.09.15 07:57:38.374962 [ 9416 ] {} <Warning> radius.radacct (ReplicatedMergeTreePartCheckThread): Found parts with the same min block and with the same max block as the missing part 202002-1_394_400_1. Hoping that it will eventually appear as a result of a merge.
`

**Comment by Amixp** [comment]
and continue
`
2020.09.15 07:57:38.241059 [ 9376 ] {} <Warning> radius.radacct: Part 202002-1_394_394_0 is covered by 202002-1_394_398_1 but should be merged into 202002-1_394_400_1. This shouldn't happen often.
2020.09.15 07:57:38.307718 [ 9416 ] {} <Warning> radius.radacct (ReplicatedMergeTreePartCheckThread): Checking part 202002-1_394_400_1
2020.09.15 07:57:38.329854 [ 9416 ] {} <Warning> radius.radacct (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part covering 202002-1_394_400_1.
2020.09.15 07:57:38.374962 [ 9416 ] {} <Warning> radius.radacct (ReplicatedMergeTreePartCheckThread): Found parts with the same min block and with the same max block as the missing part 202002-1_394_400_1. Hoping that it will eventually ap
pear as a result of a merge.
2020.09.15 08:07:38.889062 [ 9387 ] {} <Warning> radius.radacct: Part 202002-1_394_394_0 is covered by 202002-1_394_398_1 but should be merged into 202002-1_394_400_1. This shouldn't happen often.
2020.09.15 08:07:38.955285 [ 9419 ] {} <Warning> radius.radacct (ReplicatedMergeTreePartCheckThread): Checking part 202002-1_394_400_1
2020.09.15 08:07:38.977609 [ 9419 ] {} <Warning> radius.radacct (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part covering 202002-1_394_400_1.
2020.09.15 08:07:39.023213 [ 9419 ] {} <Warning> radius.radacct (ReplicatedMergeTreePartCheckThread): Found parts with the same min block and with the same max block as the missing part 202002-1_394_400_1. Hoping that it will eventually ap
pear as a result of a merge.
2020.09.15 08:17:39.049117 [ 9380 ] {} <Warning> radius.radacct: Part 202002-1_394_394_0 is covered by 202002-1_394_398_1 but should be merged into 202002-1_394_400_1. This shouldn't happen often.
2020.09.15 08:17:39.116252 [ 9424 ] {} <Warning> radius.radacct (ReplicatedMergeTreePartCheckThread): Checking part 202002-1_394_400_1
2020.09.15 08:17:39.138954 [ 9424 ] {} <Warning> radius.radacct (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part covering 202002-1_394_400_1.
2020.09.15 08:17:39.182953 [ 9424 ] {} <Warning> radius.radacct (ReplicatedMergeTreePartCheckThread): Found parts with the same min block and with the same max block as the missing part 202002-1_394_400_1. Hoping that it will eventually ap
pear as a result of a merge.
2020.09.15 08:27:39.961095 [ 9380 ] {} <Warning> radius.radacct: Part 202002-1_394_394_0 is covered by 202002-1_394_398_1 but should be merged into 202002-1_394_400_1. This shouldn't happen often.
2020.09.15 08:27:40.036717 [ 9399 ] {} <Warning> radius.radacct (ReplicatedMergeTreePartCheckThread): Checking part 202002-1_394_400_1
2020.09.15 08:27:40.059620 [ 9399 ] {} <Warning> radius.radacct (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part covering 202002-1_394_400_1.
2020.09.15 08:27:40.112381 [ 9399 ] {} <Warning> radius.radacct (ReplicatedMergeTreePartCheckThread): Found parts with the same min block and with the same max block as the missing part 202002-1_394_400_1. Hoping that it will eventually ap
pear as a result of a merge.
`

**Comment by Amixp** [comment]
**version 20.7.2.30 (official build))**
