### ISSUE TITLE
Please add sasl.username and sasl.password

### ISSUE THREAD

**Issue by daledude** [yandex/ClickHouse#1956]
We have our kafka cluster secured and requires sasl user and pass. Please allow this to be configured via the Kafka engine syntax.

**Comment by Amper** [comment]
@daledude, look at [this pull request](https://github.com/yandex/ClickHouse/pull/2089), will it help you?

**Comment by daledude** [comment]
@Amper, thanks for the pointer but I don't see anything related to SASL PLAIN or I missed something?

**Comment by Amper** [comment]
@daledude, section "Configuration": 
<img width="1797" alt="kafka" src="https://user-images.githubusercontent.com/495795/37860018-0bab2ea2-2f50-11e8-99ce-3bca54209bd6.png">

**Comment by daledude** [comment]
@Amper Thank you! I missed the crucial "see ... for list of other options" so I didn't realize I could use any of the librdkafka options.
