### ISSUE TITLE
Aggregate functions return nothing on empty set

### ISSUE THREAD

**Issue by hyst329** [yandex/ClickHouse#1965]
Clickhouse 1.1.54342.

Aggregate functions such as `COUNT`, `SUM` etc., when exdecuting on empty set, return nothing instead of more natural result (such as zero for `COUNT` and `SUM`). Is it intended? 
(Actually, such behaviour may break things when using with "generic-SQL" library (such as SQLAlchemy).)

Steps to reproduce:
```SQL
CREATE TEMPORARY TABLE t (i1 Int64); -- t is empty now
SELECT COUNT(*) FROM t; -- returns nothing (0 rows) instead of zero (1 row with value=0)
```

**Comment by KochetovNicolai** [comment]
ClickHouse has always returned nothing when aggregate functions is applied to empty rows set. It's planned to fix such behavior.

**Comment by zenob** [comment]
I think this is the same as this issue: https://github.com/yandex/ClickHouse/issues/51
It seems to be fixed.
