### ISSUE TITLE
Оно не работает в убунту 16.04

### ISSUE THREAD

**Issue by AnotherAnkor** [yandex/ClickHouse#197]
Ставил из реп, ставил из исходников согласно документации. Пробовал на двух серверах, полностью удовлетворявших входным условиям. Один крутился на kvm, второй на virtualbox.
Всегда и на каждой системе получаю примерно одну ошибку: echo "DROP TABLE IF EXISTS myapptest2.testtable; CREATE TABLE myapptest2.testtable (pageURL String,  pageRank UInt32, avgDuration UInt32) ENGINE = Log; SHOW CREATE TABLE myapptest2.testtable; SELECT * FROM myapptest2.testtable FORMAT TabSeparatedWithNames;" | clickhouse-client -n --password qwerty
CREATE TABLE myapptest2.testtable ( pageURL String,  pageRank UInt32,  avgDuration UInt32) ENGINE = Log
pageURL	pageRank	avgDuration
Received exception from server:
Code: 1000. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: File not found: /opt/clickhouse/data/myapptest2/testtable/pageURL.bin.
WTF?
Версия текущая, убунта со всеми последними обновлениями. 64 битная. Собирал с ключом "не надо монги". Установка клиента монговского тоже не помогла.
Ещё какую информацию скинуть?

**Comment by sichkarev** [comment]
Зря вы так. 
Я использовал у себя Ubuntu trusty и xenial.
Полет нормальный на обеих версиях, правда я ENGINE = Log не использую у себя, но по вашему примеру все нормуль отработало.

![image](https://cloud.githubusercontent.com/assets/16035271/20535654/89ba589a-b107-11e6-9992-b07e547c6eeb.png)

**Comment by alexey-milovidov** [comment]
Коллега ludv1x уже догадался, по какой причине именно у вас оно неправильно работало. Исправление уже в пути.

**Comment by ludv1x** [comment]
Да, там баг, который воспроизводится только на одноядерных машинах (или при использовании --max_threads=1) при селекте из пустой таблицы.
Исправление (однострочное)[https://github.com/yandex/ClickHouse/pull/171/files#diff-85aff12c080bc4372b3f71e06d1a4482R694].
Поэтому так вышло, что оно уже едет с #171

**Comment by f1yegor** [comment]
can we close it?)
