### ISSUE TITLE
create wrong Distributed table, but " select count() " server crash

### ISSUE THREAD

**Issue by RustRw** [yandex/ClickHouse#1972]
create Distributed table like this:

CREATE TABLE adx_report.bs_all_idea_report_name_cast
(date               Date     
,hour               UInt8  
,year               UInt8
,quarter             String   
,month               String   
,week_of_year        String   
,week_flag           String     
,user_type          UInt16   
,agent_id           Int64    
,user_id            String   
,plan_id            Int64    
,unit_id            Int64    
,idea_id            Int64    
,idea_group_id      Int64    
,src_id             Int64    
,page_id            Int64    
,template_id        Int64    
,industry0          UInt64   
,industry1          UInt64   
,industry2          UInt64   
,level_name         String   
,subject_label_add  String   
,pv                 UInt64   
,inview_pv          UInt64   
,click              UInt64   
,spend              UInt64   
,update_time        DateTime 
,base_click         UInt64   
,attach_click       UInt64   
,industry0_name     String   
,industry1_name     String   
,industry2_name     String   
,agent_flag         String   
,agent_email        String   
,agent_company      String   
,user_email         String   
,user_company       String   
,plan_name          String   
,unit_name          String   
,idea_group_name    String   
,idea_name          String   
,src_name           String   
,template_name      String   
,page_name          String   
,subject_name       String   
,pt                 Date  ) 
ENGINE = Distributed(bip_ck_cluster, adx_report, bs_all_idea_report_name_cast, rand())

i know this sql is wrong, use bs_all_idea_report_name_cast same name , but when select count() from bs_all_idea_report_name_cast,  clickhouse is crash.

by the way: if crash select from client, it can restart. but it start from default config.xml. i want know how to change this ，i use different config.xml  dir.

**Comment by alexey-milovidov** [comment]
This is because Distributed table is pointed at itself.
I've added a check for this in recent ClickHouse relese (1.1.54370).

> by the way: if crash select from client, it can restart. but it start from default config.xml. i want know how to change this ，i use different config.xml dir.

The server is restarted by either cron script or systemd. You can look at `/etc/init.d/clickhouse-server` to change default config dir.
