### ISSUE TITLE
Error importing using parameters ' input_format_all_errors_<xxx>', client version 1.543.

### ISSUE THREAD

**Issue by SUHAR1K** [yandex/ClickHouse#1976]
I am importing a file:
 `cat out | clickhouse-client --query="INSERT INTO storage FORMAT CSV" --input_format_allow_errors_num=100 --input_format_allow_errors_ratio=1` 

but I get an error: 

> Code: 117. DB::Exception: Expected end of line

There are lines without a line break in the file:

`user@gmail.com,,,,,,,775d0ed6bd4e1d7c58d46d46613d1c03,,md5
user1@gmail.com,,,,,,,775d0ed6bd4e1d7c58d46d46613d1c03,,md5
user2@gmail.com,,,,,,,775d0ed6bd4e1d7c58d46d46613d1c03,,md5user3@gmail.com,,,,,,,775d0ed6bd4e1d7c58d46d46613d1c03,,md5
`
^ error

**Comment by blinkov** [comment]
@SUHAR1K which ClickHouse release do you use?

As far as I can see, this kind of error (https://github.com/yandex/ClickHouse/blob/e4b4b5a4fcc430a4fc427cd313fa7e91c45da3dd/dbms/src/Formats/CSVRowInputStream.cpp#L50 ) became skippable by these settings only recently in 18.14.*** releases (https://github.com/yandex/ClickHouse/commit/e4b4b5a4fcc430a4fc427cd313fa7e91c45da3dd#diff-6461ab491acf5411d4826d20611da744 )
