### ISSUE TITLE
groupArray and Nullable

### ISSUE THREAD

**Issue by fireya** [yandex/ClickHouse#1980]
Hello!
I have noticed, that groupArray function ignores null in nullable  columns, and changes type from nullable to not nullable:
`select groupArray(c) from (select cast(null as Nullable(UInt64)) as c)`
show empty array of UInt64, not array of Nullable(UInt64) with 1 element: null.

Is this a bug or expected behaviour?

**Comment by silviucpp** [comment]
Seems is expected behavior but leads to a lot of unexpected interpretations. 

For example you use `uniq` to count number of distinct values and NULL is taken into account and then you use `groupUniqArray` to see what are these values and you find out that are less values than the first function reports.

**Comment by vpanfilov** [comment]
```sql
SELECT groupArray(arrayJoin([1, NULL, 2]))

┌─groupArray(arrayJoin([1, NULL, 2]))─┐
│ [1,2]                               │
└─────────────────────────────────────┘
```

I found this behavior when I got unexpected `DB::Exception: Sizes of ARRAY-JOIN-ed arrays do not match` in one of my queries. Why it is an expected behavior?

**Comment by hwchen** [comment]
I've also come across this behavior because of `array join`, with a ` DB::Exception: Sizes of ARRAY-JOIN-ed arrays do not match`

**Comment by a-rodin** [comment]
@hwchen It is possible to `COALESCE` nullable values to some "empty" value, then it would work with `groupArray` keeping the same number of items.

**Comment by hwchen** [comment]
Thanks, this is useful to me. It could be a workaround in special
cases, but I probably wouldn't want to depend on it more.

**Comment by e-kor** [comment]
@alexey-milovidov 
recently found out this behaviour and it's quite surprising.


my schema is date - device - temperature
If i have material view with regular timestamps (averaged by 20 minutes, empty values filled with nulls), and want to query temperature timeseries grouped by device (into array)

something like
```sql
select device, groupArray(temperature)
where data between %start and %finish
group by device
```

and I know that all arrays are of the same length, and dates can be generated elsewhere


however now I should make workrounds, to hide nulls from groupArray. Something like 
```sql
select device, groupArray(ifNull(temperature, nan))
where data between %start and %finish
group by device
```

its simple to insert special value in case of floats, however if its integer value, or something else - you have to make serious assumptions regarding data. Moreover - you'll have to replace special value, and then replace back, after array is groupped.
