### ISSUE TITLE
Can't start clickhouse --help

### ISSUE THREAD

**Issue by jgshzy** [yandex/ClickHouse#1981]
os: Ubuntu 16.04.3 LTS \n \l
clickhouse version: 1.1.54342

I use " sudo service clickhouse-server start" . but not start.

so I use "systemctl status clickhouse-server.service"  show message:

● clickhouse-server.service - ClickHouse Server (analytic DBMS for big data)
   Loaded: loaded (/etc/systemd/system/clickhouse-server.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2018-03-01 22:31:55 CST; 21s ago
  Process: 16057 ExecStart=/usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml (code=exited, status=232/ADDRESS_FAMILIES)
 Main PID: 16057 (code=exited, status=232/ADDRESS_FAMILIES)

Mar 01 22:31:55 ubuntu163 systemd[1]: clickhouse-server.service: Unit entered failed state.
Mar 01 22:31:55 ubuntu163 systemd[1]: clickhouse-server.service: Failed with result 'exit-code'.

**Comment by godjil** [comment]
Конфиг в студию!

**Comment by derekperkins** [comment]
I am seeing this too in testing. ClickHouse worked with all the defaults after installing with `apt-get` on Debian 9, but then I saw this error when I changed the location of the logs.

```
        <log>/mnt/resource/chdata/clickhouse-server.log</log>
        <errorlog>/mnt/resource/chdata/clickhouse-server.err.log</errorlog>
```

**Comment by alexey-milovidov** [comment]
`ADDRESS_FAMILIES` means that this is related to IPv4 vs IPv6 addresses in configuration.

Typical Linux system have support both for IPv4 and IPv6 and you can use `::` wildcard address in config to listen.

But sometimes (in some cloud providers) they have a kernel with explicitly disabled IPv4 or IPv6.
In this case you have to edit the configuration (look at both `config.xml` and `users.xml`) to use only supported address families.

**Comment by alexey-milovidov** [comment]
> I saw this error when I changed the location of the logs

Probably you have different error, could you please show it?

**Comment by derekperkins** [comment]
I figured it out, it was just a permissions error, but it also shows that error if the directory doesn't exist. I had to run `chown clickhouse:clickhouse` to fix it.

**Comment by PolinaIP** [comment]
I am seeing this too. What I do wrong? 


```
lickhouse-server.service - ClickHouse Server (analytic DBMS for big data)
   Loaded: loaded (/etc/systemd/system/clickhouse-server.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2018-08-09 13:35:27 UTC; 18s ago
  Process: 6945 ExecStart=/usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml (code=exited, status=70)
  Process: 6941 ExecStartPre=/bin/chown clickhouse:clickhouse -R /etc/clickhouse-server (code=exited, status=0/SUCCESS)
  Process: 6938 ExecStartPre=/usr/bin/chown clickhouse:clickhouse -R /etc/clickhouse-server (code=exited, status=0/SUCCESS)
 Main PID: 6945 (code=exited, status=70)
```

**Comment by PolinaIP** [comment]
the problem is solved! I just had to change the user to  root
 in /etc/systemd/system/clickhouse-server.service

**Comment by healiseu** [comment]
I have the same problem with @jgshzy, the first time I installed clickhouse the service started without any error. But then I decided to move clickhouse data repository to an SSD disk. I modified paths at
/etc/clickhouse-server/config.xml
```xml
<!-- Path to data directory, with trailing slash. -->
    <path>/dbstore/clickhouse/</path>

    <!-- Path to temporary data for processing hard queries. -->
    <tmp_path>/dbstore/clickhouse/tmp/</tmp_path>

    <!-- Directory with user provided files that are accessible by 'file' table function. -->
    <user_files_path>/dbstore/clickhouse/user_files/</user_files_path>
```
then I restarted the server and I got 

```txt
sudo service clickhouse-server status
● clickhouse-server.service - ClickHouse Server (analytic DBMS for big data)
   Loaded: loaded (/etc/systemd/system/clickhouse-server.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2018-09-27 21:04:14 EEST; 4s ago
  Process: 7774 ExecStart=/usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml (code=exited, status=203/EXEC)
  Process: 7770 ExecStartPre=/bin/chown clickhouse:clickhouse -R /etc/clickhouse-server (code=exited, status=0/SUCCESS)
  Process: 7767 ExecStartPre=/usr/bin/chown clickhouse:clickhouse -R /etc/clickhouse-server (code=exited, status=203/EXEC)
 Main PID: 7774 (code=exited, status=203/EXEC)

Sep 27 21:04:14 Tornado systemd[1]: clickhouse-server.service: Unit entered failed state.
Sep 27 21:04:14 Tornado systemd[1]: clickhouse-server.service: Failed with result 'exit-code'
```
Then I tried several things with permissions, users, etc and eventually it was messed up completely so I  decided to remove it and re-install it. I removed all clickhouse* directories first with mlocate and installed it again according to your quick start guide.

Unfortunately I got the same error, can you help please ?

**Comment by sevketozturk** [comment]
!!start the service after making changes to the config !!!
--note the ranking--
To install official packages add the Yandex repository in /etc/apt/sources.list or in a separate,
/etc/apt/sources.list.d/clickhouse.list file:
1- deb http://repo.yandex.ru/clickhouse/deb/stable/ main/
2- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E0C56BD4
3- sudo apt-get update
4- sudo apt-get install clickhouse-client clickhouse-server
5- start the service after making changes to the config (if necessary)
6-  choown clickhouse:clickhouse clickhouse/
7- sudo -R chmod 755 clickhouse/
8- sudo service clickhouse-server start
done :)
![image](https://user-images.githubusercontent.com/45919074/53337717-3ea9fb80-3913-11e9-8e19-638295609ef5.png)

**Comment by lexerom** [comment]
Also had such error. In logs I had: <Error> Application: Exception: Failed to merge config with '/etc/clickhouse-server/users.d/default-password.xml': SAXParseException: Invalid token in '/etc/clickhouse-server/users.d/default-password.xml', line 1 column 38.

It was easy to fix - I updated the password for default user - set it without special symbols, just 0-9a-Z.

**Comment by alexey-milovidov** [comment]
@lexerom You can also use sha256 password.

**Comment by depyronick** [comment]
I was deleted the error log file manually with user ubuntu and created it myself, so the permission got changed to ubuntu. `/var/log/clickhouse` and the files inside it should be chowned to `clickhouse:clickhouse`. That fixed the error.

**Comment by kreuzerkrieg** [comment]
Odd. I have the same error after the config was changed and log level node was left empty. `syslog` has a correct message:

> Sep  8 09:11:00 ip-172-16-8-5 clickhouse-server[3774]: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Invalid argument: Not a valid log level, Stack trace (when copying this message, always include the lines below):

No idea how it translates into `status=232/ADDRESS_FAMILIES`

**Comment by cristianvnica** [comment]
This is what worked for me https://www.cnblogs.com/liang8/p/17565210.html 

(without last step - changing the `/etc/clickhouse-server/config.xml` file);
