### ISSUE TITLE
Is there a way to combine table engines?

### ISSUE THREAD

**Issue by maddhuapplicate** [yandex/ClickHouse#1992]
I want the functionality associated with SummingMergeTree and ReplacingMergeTree. I want the table to calculate the sum of some columns and also to have the version field and delete the the older versions. I am not sure if that is possible. If yes, then please guide me as to how to do this.

**Comment by blinkov** [comment]
@maddhuapplicate no, they are not combineable, but they are extendable, so you could write a new one with logic you need in C++ and open a pull request.
