### ISSUE TITLE
Importing directly from mysql using mysql-source and materialised view does not work

### ISSUE THREAD

**Issue by inkrement** [yandex/ClickHouse#1993]
Seems like queries like the following are not supported now (Error: `Logical error while creating StorageMaterializedView. Could not retrieve table name from select query.`).

```sql
CREATE MATERIALIZED VIEW table_name ENGINE=MergeTree(...) POPULATE AS
SELECT  * FROM mysql('host:3306', 'db', ...);
```

And one has to CREATE it first and the use the `INPUT... SELECT` Statement. Is support for `CREATE MATERIALIZED VIEW` on a mysql source planned?

**Comment by blinkov** [comment]
Materialized views act more like triggers for inserts into table they are attached to, so it doesn't make sense to create one on top of table function call.

**Comment by filimonov** [comment]
relates #5207 (about better exception)
#4006 (some ideas of implementation something similar).
