### ISSUE TITLE
cant't create table on centos7.3

### ISSUE THREAD

**Issue by buddiking** [yandex/ClickHouse#1997]
when create table using  clickhouse-client, meet following error:
[gary@cent75 bigData]$ clickhouse-client 
ClickHouse client version 1.1.54343.
Connecting to localhost:9000.
Connected to ClickHouse server version 1.1.54343.

:) CREATE TABLE default.TestTimes (
    EventDate Date,
    info_id UInt32,
    test_id UInt32
) ENGINE = MergeTree(EventDate, info_id, 8192)
:-] :-] :-] 
Syntax error: failed at position 32 (line 1, col 32):

CREATE TABLE default.TestTimes (
    EventDate Date,
    info_id UInt32,
    test_id UInt32

Unmatched parentheses: (

:) 
====================
this error not happened on  ubuntu.

**Comment by alexey-milovidov** [comment]
Try to run clickhouse-client with `--multiline` option.

**Comment by buddiking** [comment]
@alexey-milovidov:

      Thanks very much.  the problem resolved.

**Comment by jimmy17x** [comment]
> Try to run clickhouse-client with `--multiline` option.

can you share how to read more about --multiline ?
