### ISSUE TITLE
Missing SSE 4.2 -- Cannot start on Intel(r) Xeon(r) CPU E5-2630 v3 @ 2.40GHz

### ISSUE THREAD

**Issue by matthiasg** [yandex/ClickHouse#20]
I am trying to start clickhouse but get the error described below, sse4 is not listed for the cpu, but is sse4 really that important that ClickHouse cannot start without it ? Can we make it start anyway ?

```
root@bc601037-cd0f-c491-80cc-806f9d992c91:~# sudo service clickhouse-server start
SSE 4.2 instruction set is not supported
```

```
sudo lshw

     *-cpu
          product: Intel(r) Xeon(r) CPU E5-2630 v3 @ 2.40GHz
          vendor: Intel Corp.
          physical id: 1
          bus info: cpu@0
          width: 64 bits
          capabilities: fpu fpu_exception vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx x86-64 pni monitor ds_cpl est tm2 cx16 xtpr
````

I would assume **sse4** would have to be listed here, but the [CPU Ark Page][ark] is quite unhelpful to find out whether the CPU does support it. It only lists AVX2.0 

[ark]: http://ark.intel.com/products/83356/Intel-Xeon-Processor-E5-2630-v3-20M-Cache-2_40-GHz

**Comment by matthiasg** [comment]
it did find the system requirements stating SSE 4,2 as required. Sorry skipped that before.

```
System requirements
This is not a cross-platform system. It requires Linux Ubuntu Precise (12.04) or newer, x86_64 architecture with SSE 4.2 instruction set.
To test for SSE 4.2 support, do
grep -q sse4_2 /proc/cpuinfo && echo "SSE 4.2 supported" || echo "SSE 4.2 not supported"
```

**Comment by alexey-milovidov** [comment]
Your CPU supports required instruction set:
http://ark.intel.com/ru/products/83356/Intel-Xeon-Processor-E5-2630-v3-20M-Cache-2_40-GHz

Probably it is VM issue: VM could report wrong flags in /proc/cpuinfo.
It even doesn't report sse3, ssse3...
2014 year CPU definitely has support for it.

**Comment by alexey-milovidov** [comment]
So, we need to modify check in init script.

The most quick way is to remove this fragment:
```
# On x86_64, check for required instruction set.
if uname -mpi | grep -q 'x86_64'; then
        if ! grep -q 'sse4_2' /proc/cpuinfo; then
                # On KVM, cpuinfo could falsely not report SSE 4.2 support, so skip the check.
                if ! grep -q 'Common KVM processor' /proc/cpuinfo; then
                        echo 'SSE 4.2 instruction set is not supported'
                        exit 3
                fi
        fi
fi
```

from `/etc/init.d/clickhouse-server`

**Comment by alexey-milovidov** [comment]
How do we check for required instruction set without /proc/cpuinfo?
We could compile minimal program which using one of instructions and then look does it get 'Illegal instruction' signal. To do it without installed compiler, we could provide minimal program:

```
echo -n 'H4sICAwAW1cCA2Eub3V0AKt39XFjYmRkgAEmBjsGEI+H0QHMd4CKGyCUAMUsGJiBJDNQNUiYlQEZOKDQclB9cnD9CmCSBYqJBRxQOvBpSQobGfqIAWn8FuYnPI4fsAGyPQz/87MeZtArziguKSpJTGLQK0mtKGGgGHADMSgoYH6AhTMPNHyE0NQzYuEzYzEXFr6CBPQDANAsXKTwAQAA' | base64 -d | gzip -d > /tmp/test_sse42 && chmod a+x /tmp/test_sse42 && /tmp/test_sse42; echo $?
```

Created this way:

```
gcc -xc -Os -static -nostdlib - <<< 'void _start() { __asm__("pcmpgtq %%xmm0, %%xmm1; mov $0x3c, %%rax; xor %%rdi, %%rdi; syscall":::"memory"); }' && strip -R .note.gnu.build-id -R .comment -R .eh_frame -s ./a.out && gzip -c -9 ./a.out | base64 -w0; echo
```

But this way is too obscure.

**Comment by matthiasg** [comment]
@alexey-milovidov .. there is indeed a VM issue .. https://github.com/joyent/smartos-live/issues/647#event-696349073 , its been filed for correction.

Nonetheless thanks for pointing out where to look. i will make a change there until the vm is behaving correctly...

**Comment by alexey-milovidov** [comment]
Better check was added.
