### ISSUE TITLE
ссылка на материализованное представление при ошибочном создании

### ISSUE THREAD

**Issue by sichkarev** [yandex/ClickHouse#200]
**1. создаем тестовую табличку**
```sql
DROP TABLE IF EXISTS TEMP.test_version_nested
CREATE TABLE TEMP.test_version_nested (
    object_id UInt8,
    names Nested (
        date Date,
        name String
    )
) ENGINE = Memory
```

**2. вставляем тестовую запись в тестовую табличку**
```sql
INSERT INTO TEMP.test_version_nested VALUES (1, [today()], ['one'])
```

**3. пытаемся создать ошибочное материализованное представление (из за отсутствия ARRAY JOIN names) и закономерно получаем ошибку**
```sql
CREATE MATERIALIZED VIEW TEMP.test_version_nested_m 
ENGINE = AggregatingMergeTree(names.date, (object_id), 8192) 
AS SELECT object_id, names.date from TEMP.test_version_nested

Received exception from server:
Code: 169. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Date column (names.date) for storage of MergeTree family must have type Date. Provided column of type Array(Date). You may have separate column with type Array(Date)..
```

**4. По аналогии с п.2. пытаемся вставить тестовую запись и получаем ошибку.**
```sql
INSERT INTO TEMP.test_version_nested 
VALUES (1, [today()], ['two'])

Received exception from server:
Code: 60. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Table TEMP.test_version_nested_m doesn't exist..
```

**5. Дальнейшая вставка в таблицу становится невозможной.**
Так как он пытается вставить данные в материализованное представление TEMP.test_version_nested_m, которое на этапе 3 не было создано, но видимо часть информации (триггер) о нём всё-таки где-то зафиксировалась.

**6. Устранение проблемы**
Устранение возможно через успешное создание и удаление TEMP.test_version_nested_m
```sql
CREATE MATERIALIZED VIEW TEMP.test_version_nested_m AS
select 1 from TEMP.test_version_nested
DROP TABLE TEMP.test_version_nested_m
```

**Comment by artpaul** [comment]
Спасибо, что раскопали баг. В master исправил.
