### ISSUE TITLE
clickhouse-client Aborts

### ISSUE THREAD

**Issue by kmatt** [yandex/ClickHouse#2001]
From a client machine that can connect to a remote cluster without issues, the clickhouse-client on the same machine "Aborts" when running DESCRIBE TABLE consistently. Client and server are same version. Both machines are CentOS 6.9.

The only diagnostic information I can find is in the server log with messages "DB::NetException: Connection reset by peer" which appear to occur when the client aborts.

```
$ clickhouse-client --stacktrace -m -h <hostname> -d testdb
ClickHouse client version 1.1.54343.
Connecting to database testdb at <hostname>:9000.
Connected to ClickHouse server version 1.1.54343.

:) show databases;

SHOW DATABASES

┌─name────┐
│ default │
│ testdb   │
│ system  │
└─────────┘

3 rows in set. Elapsed: 0.102 sec.

:) use testdb;

USE testdb

Ok.

0 rows in set. Elapsed: 0.001 sec.

:) show tables;

SHOW TABLES

┌─name──┐
│ testtbl │
└───────┘

1 rows in set. Elapsed: 0.002 sec.

:) describe testtbl;

DESCRIBE TABLE testtbl

Aborted
```

**Comment by kmatt** [comment]
Same client connections abort when attempting to do INSERTS which led me to this simple test case.

**Comment by kmatt** [comment]
```

**Comment by kmatt** [comment]
Other CentOS machines running same version can run DESCRIBE without error. Is there any other debug information that clients on the problem machines can emit?

**Comment by perez1987** [comment]
any news?

**Comment by alexey-milovidov** [comment]
You can run `clickhouse-client` under gdb:
`gdb clickhouse-client`
and type `r`

Then try to reproduce this issue and type `bt` to get a stack trace.
Please post stack trace here.

**Comment by blinkov** [comment]
The requested information has not been provided.
