### ISSUE TITLE
[Question] does clickhouse have `geohash algorithm` function?

### ISSUE THREAD

**Issue by Jaxvk** [yandex/ClickHouse#2008]
Hi, I don't found the `geohash algorithm` function in clickhouse, can you help me?

**Comment by alexey-milovidov** [comment]
It doesn't.

It would be nice if it will have.

**Comment by ImreSamu** [comment]
maybe a temporary workaround from carto.com  ( based on "quadtree keys", or  "quadkeys" )
* "Geospatial processing with Clickhouse"  ( May 23, 2017 )
      * https://carto.com/blog/inside/geospatial-processing-with-clickhouse/
* "Geospatial processing with Clickhouse, take 2"   ( Aug 9, 2017 )
      * https://carto.com/blog/inside/geospatial-processing-with-clickhouse-take-2/
