### ISSUE TITLE
How can I get the number of unique arrays 

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#2010]
Hello,

Having a table like:

```sql
CREATE TABLE test_array2 (arr Array(Nullable(Float64))) ENGINE = Memory;
INSERT INTO test_array2(arr) values ([1,2]),([3,4]),([5,6]),([7,8]);
```

How Can I get number of unique arrays ? Seems `uniq` is not working with array fields

Silviu

**Comment by zhang2014** [comment]
Maybe try `arrayUniq` Function ?

**Comment by silviucpp** [comment]
This function returns if I'm not wrong unique elements across all arrays.
not unique arrays for example if I have [1,2], [3,4], [5,6] I expect 3 but
returns 6 (1,2,3,4,5,6)

Silviu

**Comment by silviucpp** [comment]
Is this supposed to be fixed ? I still get `Code: 48, e.displayText() = DB::Exception: Method getDataAt is not supported for Nullable(Float64), e.what() = DB::Exception` when doing `select uniq(arr) from test_array2`

**Comment by alexey-milovidov** [comment]
Not yet, I had almost fixed this.

**Comment by silviucpp** [comment]
Hello @alexey-milovidov  any idea when this bug will be fixed ?

**Comment by alexey-milovidov** [comment]
It was left unfinished, but thank you for reminder, I'll try to keep up!
