### ISSUE TITLE
Date & Datetime: Wrong Comparison Results

### ISSUE THREAD

**Issue by inkrement** [yandex/ClickHouse#2011]
Clickhouse behaves unexpectedly, when someone compares Date and DateTime values. Although, no exception occurs and it works like comparing Date-values, the result changes if someone simply adds a time-value:

![screenshot from 2018-03-08 10-42-46](https://user-images.githubusercontent.com/604528/37144226-ac3302f4-22bd-11e8-8def-0581a15fe080.png)

**Comment by ludv1x** [comment]
Confirm. 
It actually compares Unix timestamp representation of DateTime (UInt64) and Date (UInt16) as ordinary integers.

**Comment by alexey-milovidov** [comment]
Fixed in master.
