### ISSUE TITLE
visitParamExtractString doesn't extract anything if JSON has a space between key/value

### ISSUE THREAD

**Issue by hatarist** [yandex/ClickHouse#2013]
Steps to reproduce:

```
:) CREATE TEMPORARY TABLE test (headers String) ENGINE = Memory;
:) INSERT INTO test (headers) VALUES ('{"foo": "bar"}');
:) INSERT INTO test (headers) VALUES ('{"foo":"bar"}');
:) SELECT
    headers,
    visitParamExtractRaw(headers, 'foo') AS foo_raw,
    visitParamExtractString(headers, 'foo') AS foo_str,
    extract(headers, '(?:"foo": ?")(.*?)(?:")') AS foo_regex
FROM test
FORMAT Vertical;

Row 1:
──────
headers:   {"foo": "bar"}
foo_raw:    "bar"
foo_str:
foo_regex: bar

Row 2:
──────
headers:   {"foo":"bar"}
foo_raw:   "bar"
foo_str:   bar
foo_regex: bar
```

**Comment by hatarist** [comment]
Oops, pardon me.
The documentation [says](https://clickhouse.yandex/docs/en/functions/json_functions/):

> The JSON doesn't have space characters outside of string literals.

I'm closing this issue, then; though it would be nice to have such an improvement.

**Comment by alexeydubinin** [comment]
Hi. I think you should reopen issue, because isValidJSON function return 1(valid) for both json's (with spaced and without).

**Comment by alexey-milovidov** [comment]
It is the documented behaviour of `visitParam` functions. These functions are intended for specific use cases and you cannot say that these functions are any good for JSON (they are fast though).

For JSON processing, we have `JSONExtractRaw`, `JSONExtractString` - those are true JSON processing functions :)

**Comment by alexeydubinin** [comment]
Thanks for reply. But why in this json JSONExtractString not working?
```sql
WITH '{"event": {"login": "djgbjjnwdivin@example.com"}}' as json 
select isValidJSON(json), visitParamExtractString(json, 'login'), JSONExtractString(json, 'login');
```

**Comment by alexey-milovidov** [comment]
Because it is nested inside "event".

Example:
```
JSONExtractString(json, 'event', 'login')
```

**Comment by alexeydubinin** [comment]
Thanks!
