### ISSUE TITLE
[Error]  official docker images build faild

### ISSUE THREAD

**Issue by Jaxvk** [yandex/ClickHouse#2020]
Hi, several compilations failed recently, https://hub.docker.com/r/yandex/clickhouse-server/builds

**Comment by ludv1x** [comment]
It is fixed now

**Comment by StarWix** [comment]
@ludv1x image with latest tag was built only. Other images weren't built, eg: https://hub.docker.com/r/yandex/clickhouse-server/builds/b5uvodq9uwlkdshpeuhi2ka/
