### ISSUE TITLE
Any plan to support decimal?

### ISSUE THREAD

**Issue by innerr** [yandex/ClickHouse#2021]
I don't see it on the roadmap, any chance we can have it?

Time have passed since https://github.com/yandex/ClickHouse/issues/253, so I hope you don't mind I asked this again.

Thanks for the great works :D

**Comment by alexey-milovidov** [comment]
We don't have it in our "short-list" roadmap and it is not scheduled for implementation right now,
but I'm considering this feature for implementation and started reviewing possible approaches.

It will most likely to be implemented as 128 or 64 bit integer as a backed (depending on scale + precision). The implementation is mostly straightforward.

**Comment by innerr** [comment]
Wonderful!

**Comment by blinkov** [comment]
Let's keep just #253 for this.
