### ISSUE TITLE
[Question]How to config the max memory for some queries like uniqExact..etc

### ISSUE THREAD

**Issue by xiao1dian** [yandex/ClickHouse#2030]
I have a table has 900 million rows data. I just want to get the disctinct count for macAddress as below
SELECT uniqExact(MacAddress) FROM wifi.

I always get the below error, 
DB::Exception: Memory limit (for query) exceeded: would use 38.05 GiB (attempt to allocate chunk of 2147483648 bytes), maximum: 37.25 GiB

I already set the below configuration
max_memory_usage to 40G 
max_bytes_before_external_sort =20 G
max_bytes_before_external_group_by=20G

If I don't have enough memory,I can't use the clickhouse do many queries?  I can accept the low performance if use external disk.

**Comment by xiao1dian** [comment]
how to use the external disk for some big queries?

**Comment by filimonov** [comment]
uniqExact can't use disk, all unique records should really fit in memory, with some overhead.

As a workarond you can use:
a) uniq() function which gives a good approximation by using fixed amount of memory
b) add more memory 
c) go group by and later count row of resulting set (group by can use disk, with the options you listed), like that
```sql
SELECT count() FROM (SELECT MacAddress FROM wifi GROUP BY MacAddress).
```

**Comment by xiao1dian** [comment]
Thank you very much. make sense for me

**Comment by alexey-milovidov** [comment]
> uniqExact can't use disk, all unique records should really fit in memory, with some overhead.

uniqExact can use disk - as any other aggregate function with enabled `max_bytes_before_external_group_by` setting,
if you have multiple small states for different aggregation keys.

**Comment by xiao1dian** [comment]
@alexey-milovidov     really?I just did set the max_bytes_before_external_group_by to 20G, but still got Memory limit (for query) exceeded error, so seems it didn't use disk.

**Comment by filimonov** [comment]
When max_bytes_before_external_group_by  is enabled the temporary state of each aggregate function (including uniqExact) can be flushed to disk.

But internal state of each function should fit into memory.

I.e. if you group by let's say minutes, and make a select for 1 year, you will have a lot of small groups. Aggregate states for them can be flushed on disk if needed. But if you do group by years, or creating aggregation for some huge range when state of one aggregate function can get too big and will not fit into memory.

**Comment by I-akshay** [comment]
> max_bytes_before_external_group_by

How to set max_bytes_before_external_group_by because this configuration is not present in config.xml

**Comment by ramazanpolat** [comment]
> > max_bytes_before_external_group_by
> 
> How to set max_bytes_before_external_group_by because this configuration is not present in config.xml

Use `users.xml` file which resides in `/etc/clickhouse-server/users.xml`.

Example `users.xml` config:

```xml
<yandex>
    <!-- Profiles of settings. -->
    <profiles>
        <!-- Default settings. -->
        <default>
            <!-- Maximum memory usage for processing single query, in bytes. -->
            <max_memory_usage>180000000000</max_memory_usage>
            <max_bytes_before_external_group_by>90000000000</max_bytes_before_external_group_by>
            <load_balancing>random</load_balancing>
        </default>
```
