### ISSUE TITLE
Bad hour value in system.parts.remove_time ('1970-01-01 90:28:15')

### ISSUE THREAD

**Issue by tsionyx** [yandex/ClickHouse#2039]
I got this error when trying to parse the result of `select * from system.parts`. 
Reproducing the problem:
```
:) CREATE TABLE test (x Date DEFAULT '1970-01-01') ENGINE = MergeTree(x, (x), 8192)

CREATE TABLE test
(
    x Date DEFAULT '1970-01-01'
)
ENGINE = MergeTree(x, x, 8192)

Ok.

0 rows in set. Elapsed: 0.007 sec. 

:) INSERT INTO test VALUES (now())

INSERT INTO test VALUES

Ok.

1 rows in set. Elapsed: 0.003 sec. 

:) SELECT table, remove_time FROM system.parts

SELECT 
    table, 
    remove_time
FROM system.parts 

┌─table─┬─────────remove_time─┐
│ test  │ 1970-01-01 90:28:15 │
└───────┴─────────────────────┘
```

The problem was initially noticed in 1.1.54343 and still exists in 1.1.54362. However, in 1.1.54318 (the oldest available deb package for now) this problem not exists yet.

**Comment by ludv1x** [comment]
Indeed, since some version C++ `time_t` type become 64-bit integer, whereas previously it was 32-bit integer. So, it broke some internal conversions.
