### ISSUE TITLE
[Question] Manually update clickhouse dictionary

### ISSUE THREAD

**Issue by igor-sh8** [yandex/ClickHouse#2041]
Hi. 
Does it possible to update clickhouse external dictionary manually (forcibly) instead of scheduled <lifetime> settings ?
Or is there some info about the last dictionary update (some exact time) ?

**Comment by millin** [comment]
Since v1.1.54289 you can use `SYSTEM RELOAD DICTIONARY <dict_name>` query or `SYSTEM RELOAD DICTIONARIES` query.

Last dictionary update is stored in `system.dictionaries` table.

**Comment by igor-sh8** [comment]
Great. It works for me. Thanks.

**Comment by Naveen071110** [comment]
What to do if SYSTEM RELOAD DICTIONARIES query throws 
 Received from localhost:9000. DB::Exception: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Exception: Connections to all replicas failed:
This error.
