### ISSUE TITLE
Проблема использования WITH и IN

### ISSUE THREAD

**Issue by TimonKK** [yandex/ClickHouse#2044]
Так работает http://prntscr.com/ir4x95, а так https://prnt.sc/iqztsa - нет. В доке написано такое https://prnt.sc/iqzyh2, но должно ли падать с ошибкой?

**Comment by filimonov** [comment]
test case to reproduce that error message (not sure if it's correct)
```
with ['a','b','c'] as w select arrayFilter(x -> x IN w, c) FROM ( select ['a','b','c','d','e','f','g','h'] c ) ;
Code: 60, e.displayText() = DB::Exception: Table default.w doesn't exist., e.what() = DB::Exception
```

workaround (use has instead if IN)
```
with ['a','b','c'] as w select arrayFilter(x -> has(w,x), c) FROM ( select ['a','b','c','d','e','f','g','h'] c ) ;
```

**Comment by ludv1x** [comment]
The problem is simpler `with ['a'] as w select 'a' IN w`

**Comment by ludv1x** [comment]
Using of arrays as the second argument of IN operator is prohibited: https://clickhouse.yandex/docs/en/single/#in-operators
So, the query should fail for this reason.

But an arguable question about the following queries remains:
````
with ('a') as w select 'a' IN w
with tuple('a') as w select 'a' IN w
```
They don't for the same reason.
Should they work (and should aliases be allowed for tuples and Sets)?

**Comment by TimonKK** [comment]
Thank you, the operator "has" helped
