### ISSUE TITLE
[Bug] query_log duplicate

### ISSUE THREAD

**Issue by Jaxvk** [yandex/ClickHouse#2055]
```
SELECT 
    query_start_time, 
    query_id
FROM query_log 
ORDER BY query_start_time DESC
LIMIT 10;
```

![default](https://user-images.githubusercontent.com/20113411/37459434-0123992a-2883-11e8-9b08-c22aaaaf9dcb.PNG)

**Comment by filimonov** [comment]
Hmm... Thought it's documented. Generally each request logged twice - at the moment of start and at the moment of finishing / exception. Check the 'type' column. 

```
        QUERY_START = 1,
        QUERY_FINISH = 2,
        EXCEPTION_BEFORE_START = 3,
        EXCEPTION_WHILE_PROCESSING = 4,
```

**Comment by Jaxvk** [comment]
:+1:
