### ISSUE TITLE
[Error] create replicatedmergetree throw error

### ISSUE THREAD

**Issue by Jaxvk** [yandex/ClickHouse#2058]
# error
if create replicatedtable with `on cluster xxx` throws error.
if not use `on cluster xxx`, ok

## system.clusters
![image](https://user-images.githubusercontent.com/20113411/37463378-0c70f404-2823-11e8-89c8-53d043526d21.png)

## create replicate table `**on cluster datacenter**`
![image](https://user-images.githubusercontent.com/20113411/37463429-271bc2ac-2823-11e8-9691-ebb064b59949.png)

## create replicate table not use `**on cluster datacenter**`
![image](https://user-images.githubusercontent.com/20113411/37463509-6b031024-2823-11e8-8ac5-6c8f29862943.png)

**Comment by filimonov** [comment]
Error description in not helpful, but may be you should provide node id (after shard name) according to recommendations in documentation?

> Example:
> ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/hits', '{replica}', EventDate, intHash32(UserID), (CounterID, EventDate, intHash32(UserID), EventTime), 8192)
> ...
> hits is the name of the node for the table in ZooKeeper. It is a good idea to make it the same as the table name. It is defined explicitly, because in contrast to the table name, it doesn't change after a RENAME query.

So '/clickhouse/tables/{shard}/ontime16' instead of just '/clickhouse/tables/{shard}'?

**Comment by Jaxvk** [comment]
it seems that the client version is incompatible with the server version. 
I fix it myselft, thank you :smile:
