### ISSUE TITLE
apt repository issue?

### ISSUE THREAD

**Issue by rpfennin** [yandex/ClickHouse#2060]
Trying to install the latest release, and getting the following:

Err:7 http://repo.yandex.ru/clickhouse/xenial stable/main amd64 clickhouse-client amd64 1.1.54362
  404  Not Found [IP: 213.180.204.183 80]
Err:8 http://repo.yandex.ru/clickhouse/xenial stable/main amd64 clickhouse-server-base amd64 1.1.54362
  404  Not Found [IP: 213.180.204.183 80]

E: Failed to fetch http://repo.yandex.ru/clickhouse/xenial/pool/main/c/clickhouse/clickhouse-server-common_1.1.54362_amd64.deb  404  Not Found [IP: 213.180.204.183 80]

E: Failed to fetch http://repo.yandex.ru/clickhouse/xenial/pool/main/c/clickhouse/clickhouse-client_1.1.54362_amd64.deb  404  Not Found [IP: 213.180.204.183 80]

E: Failed to fetch http://repo.yandex.ru/clickhouse/xenial/pool/main/c/clickhouse/clickhouse-server-base_1.1.54362_amd64.deb  404  Not Found [IP: 213.180.204.183 80]

**Comment by peteychuk** [comment]
the same issue

**Comment by peteychuk** [comment]
any luck on this?

**Comment by rpfennin** [comment]
Yes actually, I removed all clickhouse references from /etc/apt/sources.list and deleted the clickhouse.list file in /etc/apt/sources.list.d

Then I re-added the repos, updated, and upgraded successfully

**Comment by peteychuk** [comment]
What service provider do you use? I'm trying to use DigitalOcean and no luck on different 14.04/16.04 droplets.

**Comment by peteychuk** [comment]
Fixed. They've changed the url to:
deb http://repo.yandex.ru/clickhouse/deb/stable/ main/

Not it works. Thanks @rpfennin!
