### ISSUE TITLE
ALIAS in ReplicatedMergeTree table

### ISSUE THREAD

**Issue by alniks** [yandex/ClickHouse#2061]
Create a table:

`CREATE TABLE events ( id UInt64,  campaign_id UInt64, user_id UInt64, type UInt8, contact_id UInt64, domain_name String,  created_at DateTime,  event_date Date,  domain String ALIAS domain_name) ENGINE = ReplicatedMergeTree(\'path\', \'node\', event_date, campaign_id, (campaign_id, type, contact_id, created_at), 8192)`

run a query:

`SELECT domain FROM events    WHERE event_date >= '2017-08-01' AND event_date <= '2017-08-31'  AND user_id = 1`

result:

`Received exception from server (version 1.1.54362):
Code: 9. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Size of filter doesn't match size of column..`

the same is for selecting domain_name and using it in query params.

Using other columns in select is OK. 

domain_name is empty for that date range, the column has been added later. Sometimes I get the result set together with exception (it depends on various query params and selection combination):

`Received exception from server (version 1.1.54362):
Code: 9. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Size of filter doesn't match size of column..

120 rows in set. Elapsed: 0.147 sec.`

**Comment by alniks** [comment]
May relate to #1550

**Comment by alniks** [comment]
The problem may be not in ALIAS column. Dropping it did not help:

`SELECT domain_name
FROM events
WHERE (event_date >= '2017-08-01') AND (event_date <= '2017-08-31') AND (user_id = 1) AND (domain_name = 'gmail.com')

Received exception from server (version 1.1.54362):
Code: 9. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Size of filter doesn't match size of column..`

This query should return empty set. Removing user_id condition will do that:

`SELECT domain_name
FROM events
WHERE (event_date >= '2017-08-01') AND (event_date <= '2017-08-31')  AND (domain_name = 'gmail.com')

0 rows in set. Elapsed: 0.337 sec. Processed 220.53 million rows, 441.06 MB (655.02 million rows/s., 1.31 GB/s.)`

**Comment by alexey-milovidov** [comment]
We have fixed similar issues in past releases.
Does the issue reproduce in the latest stable?

**Comment by alniks** [comment]
Looks like it is fixed in 19.1.6
