### ISSUE TITLE
Awful performance of CollapsingMergeTree table engine.

### ISSUE THREAD

**Issue by simplevil** [yandex/ClickHouse#2063]
I have troubles with perfomance on simple WHERE IN query.
My table:

 `CREATE TABLE IF NOT EXISTS transactions (
    hex String,
    txid String,
    version Int8,
    locktime Int32,
    vin Nested (
      txid String,
      vout Int32,
      sequence Int64
    ),
    vout Nested (
      value Float64,
      valueZat Int64,
      n Int32
    ),
    blockhash String,
    confirmations Int32,
    time DateTime,
    blocktime DateTime,
    created_at Date DEFAULT now(),
    sign Int8
  ) ENGINE=CollapsingMergeTree(created_at, (txid), 10000, sign)`

My query:

`SELECT * FROM transactions WHERE txid IN ('a0dadbe808edf17fc9fc1a36f6e417d2849681d4475f7545fa4bc941f4c0d03f','c01adf8d676e40038738ace00967cede68487f37ce55fefc3ac77d9e2c912902','bb23305742c009fcf25cfa4db4143a1fabdf46291b1807a2c232d600acdc6235','39d763b0d34c1117b9743427f55b3f8d5e4fa387087d20e1ee734f4465de75be','aca5d6e8a9af12fcfde66bc2b378fabd7cf088b08fbba0353cf4fbcdf8202e14','2dd047c04b929e595ff601c4c77a69dcaedd4e26c8a89a71da6492d5331bfe95','dd9b8d066de2cf671571059fc0192947d7277b8cadd4db76c0c6b6184dd280cc','63ff05f98689de0ca9c6343b6b0866ffb7461c72e99540eaaa2acc570b64946a','e04c2fafae6d8fa25c8327f004dfcfd32e3502f429e2cd9638bfd4fdb17d904f','ce09f829757b1f13f7a2f1e37f2978a2ced1cf3cce76d39e9f563ee6989558f7','8590927fcc56f9b15b92db9153f771dfa6d70f5c1140479e787d4fd338ec8ed3','da60606e205a9e7b141aa58ccce1e9c12e6ede0876e1da36150658776c16aee0','5c0fd4dac806cea19031a682cf516b695050f492544ac31900093ef1009a1ef6','6658c8df25bf1e11734f950942f4cb3c6832499bbc89fa50d09106c5ef7cf982','1b178eab24ed344be303a5516cf6acbbcba828835b6ae5b2bc91e768d32d24bb','d4144a17a17c462298df5c8aa5c67962c31d25a240dd17c25750d8b8277005b1','df24ace819374cf395514f45ab3974e7ee205cceb37c330b071d853ee231f8ef','4d531c326a572614fe7326316b600781190b921b521203d172e98f0de6c13163','727f4c6b3b1d5e8b6596e124a5de9cccb09f515b9e189a67702301b1163ba337','ee8218bc6ba99178c3b8542e40bf1a69e15d8d4d8b074b1828071c4d94db8627','24d23b6cff89f577631cc1557e0070ba062874ef7aaf9fb69f4c785a8db7c4c9','a83107908f7b5fcdbe912f6a5145b62b7d0fe0778009b14de7dd4c6aa7433f43','73cf97e6c11c6ba795fec3c3a34d8bc62a73f856efbe0095d039e938d0a380ea','c3e4ce5637c02f51a25842eba3c488cb288f62f90ff9c56563700d00349794c2','cd74801a62c5fb756cf48d902f05d764fb3058786884196f94d49507a93007b2','50e6cb5a47c7ce81cb8a2e2ee5fdef505019a10b21cad2c862bb0308600a7920','23e526dd8589db9bb86964b02802d8c954c1f46f9c0711a7ce21081e60538a45','73e8ec3d15999a07bf33b584726454a6a729f2b5b026087dce9c4a3cef9f6cee','6197289bf7314b4a719ee9006a29c95119d4b94c94b693b17772228ea62bda22','acaf0ac1e707c0afa6c4157c935ab7783bcf156b2e2256eada454487ed787049','576fa328c39d26463b0599758b0a9167e539a255833f7ed2c1fa95009ce48227','c80061d7fd6d11a98811e646ff5509658ae8a276197c3a087a362df54e5bc9a9','5c7936e17788e8a87292c9873fd93d3f51d4192dddcfac33ec2aa92c880cdbf3','368041a0d4ac75de891e67179b5656986c721bb429dcc813bfebe447be756bfc','25c755609d6d8f4db867327e8682940744ffd51959f79d75233787da4ed7de9c','b8529d960ba308bdb9eeefe628cffb6559916bc08ad0c4d90285c4badb3c2c14','1e70ecb59ac9046780b00eb616dcbdf77763cf8664f587f2251f34886ebf1461','607faaa22d2d7d8a386a200d005e3417155bb36cef279d4251f31fc8dc36d0ae','064de7792af165f1f9b30b4c9d8b293a9113cbe75f9453a91ff141bb236f947c','0645e79f14126c06657e887b854d1710906234e21863115d0fa00bec55661e0f','a1914b6aec28370b074d3d3ee6a70fcea9952d81832d3d385ea231bedf47f49c','aee4f2dcfd36f0d1d86de178d69056a4f1493b20559b3d77177461f4698c5b0d','df4e4c74a1ce0dec2aab36274b51314e59902b7da7073bceae6b2e851079c9a8','19c13d934356271a6fcdbd808fb62b9fcc0a1c4f5a8d644400a0ba7de2117d09','370ab53c3b504a84a2ff3bf8ea3cb1e69caeb1301e544cd0d71902894ec1c35b','8a514948bed0deff2a6853dc3a52def4b623475547683f49215cc7f2d10b6d42','a3fcedf517474fec12fcbbd0a5647fc17c687bef12ffe2105de19096259b0657','06f395d0d8f2b0fb0a00a23603a5840d6d55e4237ba31edc81d455bf778a0952','2d417ec6fab7ae95edae0320afa0f9f041d0c75c5b01509631b98b2362cd518b','5cefebd7fdb4fd481f17b284c422c868d5d6849bccee76566e6998891efde2ca','6d81505203a9ada7cf9e1ca818ab500bd2fd7f0c3b40deea221a55b7381a19e5','8772d123f54508684bdcfee9ec40bf8d689aa60980e3fed203d808da46b5a5e4','5a3d07d8ff6a13cad5b6dbf74947825216a3b5d6931070b151c18351180c3fbb','0fa88c30ed7c8b49cb10f69e0136b8747e33b4d7e3e510d32d4a7231729cfa47','b037b9a5319a083d9a6552a8361d2cfe152db077c8f460a19916fd8bf142143d','5778d7277d075ab78b2128464c39766187a585b5ff139a3e792613858b3d8615','0315951e0239fee3972e8d73643168179dbe634959d77b362ffdd9183c37dc5d','c4686c72fba3015de8f4c49f302c0e93544355ae5f0808d15854fba5292ea3d1','814853f53994441fc2e648ba06c39c29f73dcd9236f4711947a1851c3c1bdb7d','ead6aafcde172d59f6c39a05a1aa3cb6b0dda8e4ee16decec5a7caabda3af97b','c99655c10b7017bc3a1380df1184e0e7c114595a557998d0de5ea9600b5061d8','39c6be47f263531bc2a82f4ce2186059cdbc59f4ccfbdaf85c7af7d5e0fe2bf6','dd29f23e7caaf7c6f490504c424dc3b91cd81e4bb56cc6e14c10a0db0eeae889','d2dbb58bdd990997ae12dcd6611e38e02aa2533eca3932b1e3d34c128d7dd0fd','41bd41d4be0a3d2f064ab7d0e295f11a11214a6c162f9132e8fb78d6435201d6','ef71075f455bd51d1b128bade1232c8e158310a8f15a18a139dee721cc06bac2','c77a5c55d8f1a5384527540d12e700db1b0f061d2fbbb3100ae932527492a0a0','f9d0b6275dc742daaa7cc43b226dd6975c1786047b6d2f8d160d8feb7760eef4','2594c18c1191107352a833cd20840cd6b63add1b2ae667ef82a4fc4d6d0ff35b','89a7d3e8b79b937bf0faf6b239ff0b731dad56588aaa1d78c092e4ca24341f17','fb6c3dd02ba497eff0a8e3bf9ce590fadba0f9d6992566f6bf1b7dd3c1a4106a','826d04164a9e1853d3da9cc0d9a5910a11878082e974d99f12b5030ae6ee0865','81c9e3ab483f9d7327f596d5a6bdf9f055fd954ed8a22e9eee232804a1c7e9fa','4aae421550ca643d856d59254d6d7a548eb6727b5a3cb17e392112e9efef2824','dc47e8063c550e4c38e20904961815f7e784a64ef7fa2fa906d314b9c30e8420','c0cc6d96c2b734652e0a970396ee6a43cf62a919200e61fef51a5c8b5af64e1c','685ea3b7c3b58e5eb89c9f7ca0392edcc881bcdee9ac9839b4364f72e832880d','d126f8ea59ecfba838e1609735ab5295870c329966b6b011f0f78248aadfc4a1','59b18dd75bfd9b64009132b98b644fb80c42aefc74882aed098be26f879bb01f','a1840f1b28832ff36b9cd6fa9481fd38e6b06e83107f4ebace3a1f8fd11cc1e7');`

With total count of 500000 rows in transactions table i have following result:

`27 rows in set. Elapsed: 10.432 sec. Processed 434.01 thousand rows, 5.86 GB (41.60 thousand rows/s., 562.18 MB/s.)`

10 sec for simple where in query even without array join for nested rows.

**Comment by alex-zaitsev** [comment]
Performance is bad because of index granularity - 10000 in your example.

For point queries try to reduce parameter to something small, like 128:

ENGINE=CollapsingMergeTree(created_at, (txid), 128, sign)

**Comment by simplevil** [comment]
Thanks a lot.
