### ISSUE TITLE
[Question] how to query on all replicas

### ISSUE THREAD

**Issue by Jaxvk** [yandex/ClickHouse#2067]
Hi, Maybe someone can help me.
I have 4 nodes (2 shards with 2 replicas) and I want that my query execute on all node in each shard 
max_parallel_replicas is useless

**Comment by kshvakov** [comment]
`max_parallel_replicas` works only for the tables created with [`SAMPLE`](https://clickhouse.yandex/docs/en/single/#sample-clause).  ClickHouse server splits the query by sample section and executes part of the query on N (max_parallel_replicas) replicas.

**Comment by kshvakov** [comment]
From official help: 

```sql 
SELECT *
FROM system.settings 
WHERE name = 'max_parallel_replicas'

Row 1:
──────
name:        max_parallel_replicas
value:       1
changed:     0
description: The maximum number of replicas of each shard used when the query is executed. For consistency (to get different parts of the same partition), this option only works for the specified sampling key. The lag of the replicas is not controlled.
```
Example: https://github.com/yandex/ClickHouse/blob/1acf404ed1d88efe4d9c87ee2a7728779f4b58a8/dbms/tests/queries/0_stateless/00124_shard_distributed_with_many_replicas.sql

**Comment by Jaxvk** [comment]
Thank you!
