### ISSUE TITLE
ON CLUSTER not working in latest update

### ISSUE THREAD

**Issue by ben-motiv** [yandex/ClickHouse#2071]
Query:
 CREATE TABLE shard1.facts_test_2 on cluster motiv_1s2r (
 ...
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/facts_test_2', '{server}') PARTITION BY (toYear(time), toMonth(time))
ORDER BY
  (mpid, siteid, time) SETTINGS index_granularity = 8192
 
Returns:
click1	9000	49	Code: 49, e.displayText() = DB::Exception: Query id cannot be empty, e.what() = DB::Exception	1	0
click2	9000	49	Code: 49, e.displayText() = DB::Exception: Query id cannot be empty, e.what() = DB::Exception	0	0

This occurs both within Tabix and running on clickhouse-client. Running without ON CLUSTER is fine.

**Comment by alexey-milovidov** [comment]
We have fixed it in 1.1.54370.
