### ISSUE TITLE
[Question] too large array size when test the AggreateFunctionMergeTree engine

### ISSUE THREAD

**Issue by Jaxvk** [yandex/ClickHouse#2078]
Hi, may someone can help me.
when I test the `AggreateFunctionMergeTree`, met the error, here are the steps
```
DROP TABLE IF EXISTS test.stored_aggregates;

CREATE TABLE test.stored_aggregates
(
	d	Date,
	GroupArray	AggregateFunction(groupArray, String)
)
ENGINE = AggregatingMergeTree(d, (d), 8192);

INSERT INTO test.stored_aggregates
SELECT
	toDate('2014-06-01') AS d,
	groupArrayState(toString(number)) AS GroupArray
FROM
(
	SELECT * FROM system.numbers LIMIT 20000000
)
GROUP BY d
ORDER BY d;


SELECT
    d,
    length(groupArrayMerge(GroupArray))
FROM test.stored_aggregates
GROUP BY d
ORDER BY d ASC;
```

**Comment by ztlpn** [comment]
Max length of the array stored in the groupArray state is limited to 16777215. This arbitrary limit is checked only on deserialization of a state and acts as a guard against corrupted data.

**Comment by Jaxvk** [comment]
:+1:

**Comment by dinhthengoc2021998** [comment]
Same problem, i cant use sumMerge or anything else when met that error, so how can i deal with that. Could i change the setting just like i did with max_memory_usage? I want to use Array Calculation because it's very fast. Thank you so much. Hope u reply soon!
