### ISSUE TITLE
Slower merges with ReplicatedAggregatingMergeTree 

### ISSUE THREAD

**Issue by rajadayalan** [yandex/ClickHouse#2084]
We are ingesting 25 billion records/day with  5 node clickhouse cluster, with additional 5 nodes used for replica. Data is ingested to Source table (MergeTree) and Materialized views using ReplicatedAggregatingMergeTree and get the error "Too many parts. Merges are processing significantly slower than inserts." We used ReplicatedSummingMergeTree first and the merges were fine. After we switched to ReplicatedAggregatingMergeTree to use aggregation functions other than sum. But we are running into the issue. 

2018.03.19 21:10:01.040218 [ 155 ] <Error> HTTPHandler: Code: 252, e.displayText() = DB::Exception: Too many parts (1508). Merges are processing significantly slower than inserts.: while pushing to view rta.access_logs_mv, e.w
hat() = DB::Exception, Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x15) [0x733b6b5]
1. clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x1e) [0x19ce42e]
2. clickhouse-server(DB::MergeTreeData::delayInsertIfNeeded(Poco::Event*)+0x3ca) [0x68999ba]
3. clickhouse-server(DB::ReplicatedMergeTreeBlockOutputStream::write(DB::Block const&)+0x4e) [0x691190e]
4. clickhouse-server(DB::PushingToViewsBlockOutputStream::write(DB::Block const&)+0x41) [0x6a1d3a1]
5. clickhouse-server(DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::atomic<bool>*)+0xb2) [0x6a540d2]
6. clickhouse-server(DB::PushingToViewsBlockOutputStream::write(DB::Block const&)+0x41f) [0x6a1d77f]
7. clickhouse-server(DB::MaterializingBlockOutputStream::write(DB::Block const&)+0x36) [0x66f0ef6]
8. clickhouse-server(DB::AddingDefaultBlockOutputStream::write(DB::Block const&)+0x2cc) [0x698643c]
9. clickhouse-server(DB::ProhibitColumnsBlockOutputStream::write(DB::Block const&)+0x5e) [0x6a1b81e]
10. clickhouse-server(DB::SquashingBlockOutputStream::write(DB::Block const&)+0x457) [0x6a24e87]
11. clickhouse-server(DB::CountingBlockOutputStream::write(DB::Block const&)+0x2a) [0x69ac6da]
12. clickhouse-server(DB::StorageBuffer::writeBlockToDestination(DB::Block const&, std::shared_ptr<DB::IStorage>)+0x8f0) [0x6b54ff0]
13. clickhouse-server(DB::StorageBuffer::flushBuffer(DB::StorageBuffer::Buffer&, bool)+0x3b8) [0x6b55958]
14. clickhouse-server(DB::BufferBlockOutputStream::insertIntoBuffer(DB::Block const&, DB::StorageBuffer::Buffer&, std::unique_lock<std::mutex>&&)+0x2e8) [0x6b57738]
15. clickhouse-server(DB::BufferBlockOutputStream::write(DB::Block const&)+0x50e) [0x6b5820e]
16. clickhouse-server(DB::PushingToViewsBlockOutputStream::write(DB::Block const&)+0x41) [0x6a1d3a1]
17. clickhouse-server(DB::MaterializingBlockOutputStream::write(DB::Block const&)+0x36) [0x66f0ef6]
18. clickhouse-server(DB::AddingDefaultBlockOutputStream::write(DB::Block const&)+0x2cc) [0x698643c]
19. clickhouse-server(DB::ProhibitColumnsBlockOutputStream::write(DB::Block const&)+0x5e) [0x6a1b81e]
20. clickhouse-server(DB::SquashingBlockOutputStream::finalize()+0x255) [0x6a247a5]
21. clickhouse-server(DB::SquashingBlockOutputStream::writeSuffix()+0x10) [0x6a24a10]
22. clickhouse-server(DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::atomic<bool>*)+0x503) [0x6a54523]
23. clickhouse-server(DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>)+0x269) [0x679a859]
24. clickhouse-server(DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&)+0x2c38) [0x19eb828]
25. clickhouse-server(DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)+0x397) [0x19edca7]
26. clickhouse-server(Poco::Net::HTTPServerConnection::run()+0x335) [0x7655e85]
27. clickhouse-server(Poco::Net::TCPServerConnection::start()+0xe) [0x764eb4e]
28. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x165) [0x764ef15]
29. clickhouse-server(Poco::PooledThread::run()+0x76) [0x740ad36]
30. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x37) [0x74070a7]
31. clickhouse-server() [0x7720dae]

**Comment by ztlpn** [comment]
There is a known bug that under certain conditions inserts into aggregating materialized views generate x256 number of original inserts. And this then leads to "too many parts" exception.

So let us first check if this bug is the culprit or not. To do it first track the failed INSERT in your server logs. It will look like
```
... [ <thread number> ] <Debug> executeQuery: ... INSERT ...
```
Then look at the next lines with the same `[ <thread number> ]`. They will contain
```
... <Trace> Aggregator: Aggregating
... <Trace> Aggregator: Aggregation method: ...
... <Trace> Aggregator: Aggregated.
```
for each aggregating materialized view. And if the bug is triggered, then there will be lines
```
... <Trace> Aggregator: Aggregating
... <Trace> Aggregator: Aggregation method: ...
... <Trace> Aggregator: Converting aggregation data to two-level.
```
Let me know if you find this `Converting aggregation data to two-level` line.

**Comment by rajadayalan** [comment]
Yes, found "Converting aggregation data to two-level" in the logs.

2018.03.19 22:01:42.510429 [ 637 ] <Trace> Aggregator: Aggregating
2018.03.19 22:01:42.510490 [ 637 ] <Trace> Aggregator: Aggregation method: concat
2018.03.19 22:01:42.588868 [ 637 ] <Trace> Aggregator: Converting aggregation data to two-level.
2018.03.19 22:01:42.603749 [ 637 ] <Trace> Aggregator: Aggregated. 150000 to 117925 rows (from 40.669 MiB) in 0.093 sec. (1611397.989 rows/sec., 436.898 MiB/sec.)
2018.03.19 22:01:42.603976 [ 637 ] <Trace> Aggregator: Merging aggregated data

**Comment by ztlpn** [comment]
Well, we better fix this bug then :)

Meanwhile, here is a workaround. Two-level aggregation is controlled by two settings: `group_by_two_level_threshold` and `group_by_two_level_threshold_bytes` - if an aggregated result size (in rows or bytes correspondingly) exceeds any of these thresholds, it is turned on. Your goal is to eliminate this possibility during the execution of materialized view queries. As apparently your batch size is 150000, increasing the thresholds to 2x default values should be enough. So try setting them for the default profile and restarting ClickHouse and see if the errors go away.

**Comment by rajadayalan** [comment]
Thank You Alex. 

Changing the values for the settings "group_by_two_level_threshold" and "group_by_two_level_threshold_bytes" helped. Dont see the "Converting aggregation data to two-level" any more. It looks good :).

Total number of parts(including the inactive parts) with ReplicatedAggregatingMergeTree for the Materialized View has increased to 700 whereas it was around 200 when we were using ReplicatedSummingMergeTree. Is this expected? Ingestion is stable now with ReplicatedAggregatingMergeTree.

**Comment by rajadayalan** [comment]
We are noticing the parts count for ReplicatedAggregatingMergeTree also same around 200. We use custom partition, so the nature of data arriving at that time caused more parts. .

**Comment by ztlpn** [comment]
You should count active parts only. Insertion stops when the number of active parts in one partition exceeds 300 (and generally if this number is greater than 100 it is a cause for concern). You can track it with the `MaxPartCountForPartition` metric (either in `system.asynchronous_metrics` table or in graphite if you enabled the export of metrics).

Inactive parts don't slow down SELECTs or hinder INSERTs so counting them only makes sense when you want to check that the cleaning process is doing its job.

**Comment by rajadayalan** [comment]
Thank You Alex. that is useful information to know.

**Comment by ztlpn** [comment]
Fixed in master.
