### ISSUE TITLE
Add third parameter for timeSlot() function

### ISSUE THREAD

**Issue by vmanyushin** [yandex/ClickHouse#2085]
It will be so good if you add third parameter to timeSlots() function. Now, this function generate series by half of hour and this limit defined as 

`#define TIME_SLOT_SIZE 1800`

so, if it possible, third argument timeSlots(date, duration, <step>) can be default 1800, but, we can change it and get series by 1,10,60 etc seconds.

**Comment by filimonov** [comment]
in master #3724

**Comment by vmanyushin** [comment]
Спасибо!
