### ISSUE TITLE
1.1.54370: Не работает оператор IN в запросах из агрегированных таблиц

### ISSUE THREAD

**Issue by QSer29** [yandex/ClickHouse#2087]
После обновления кликхауса до версии 1.1.54370 перестал работать оператор IN в запросах к таблицам семейства AggregatingMergeTree.

Вот такой запрос выдает Ok:

```
:) SELECT site_id FROM websites_21 WHERE site_id IN (1002) LIMIT 1

SELECT site_id
FROM websites_21
WHERE site_id IN 1002
LIMIT 1

Ok.
```

Если же вместо IN указать =, то получим идентификатор:

```
:) SELECT site_id FROM websites_21 WHERE site_id=1002 LIMIT 1

SELECT site_id
FROM websites_21
WHERE site_id = 1002
LIMIT 1

┌─site_id─┐
│    1002 │
└─────────┘
```

Очевидно, что результат в обоих случаях должен быть одинаковым, но это не так.
Исправьте, пожалуйста.

**Comment by alex-zaitsev** [comment]
Could be related to: https://github.com/yandex/ClickHouse/commit/590feb02b5907aad4715227e64efc4b773c2a72f

**Comment by ztlpn** [comment]
Это тот же баг, если websites_21 это materialized view, а site_id в первичном ключе. @QSer29 это так?

**Comment by QSer29** [comment]
Да, это так. Спасибо.
