### ISSUE TITLE
Subscribe to multiple Kafka topics doesn't work

### ISSUE THREAD

**Issue by tobad357** [yandex/ClickHouse#2095]
In the documentation it says that a list of topic names can be provided
When testing this functionality, it seems like this functionality doesn't work

This works
```
create table test_kafka (
 `id` UInt64
) ENGINE = Kafka('kafka-1:9092', 'topic_1', 'group1', 'JSONEachRow');
```

This doesn't work and no results come in from either topic

```
create table test_kafka (
 `id` UInt64
) ENGINE = Kafka('kafka-1:9092', 'topic_1,topic_2', 'group1', 'JSONEachRow');
```

**Comment by blinkov** [comment]
Sounds like it's fixed in #2100
