### ISSUE TITLE
X-Forwarded-For support

### ISSUE THREAD

**Issue by rpuch** [yandex/ClickHouse#2098]
It looks like Clickhouse does not support X-Forwarded-For HTTP header to detect client IP address when Clickhouse is behind a reverse proxy.

I've installed Clickhouse, its HTTP port is 8123.

For `test` user, only access from certain IP is allowed (let's say it's 1.2.3.4).

I'm using nginx as a reverse proxy with the following config:

    server {
        listen 80;
        server_name clickhouse.mydomain;
        resolver 8.8.8.8;

        proxy_redirect          off;
        proxy_set_header        Host            $host;
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;

        location / {
            proxy_pass http://localhost:8123/;
        }
    }

Then I try to run a query using curl.

curl 'http://clickhouse.mydomain/?user=test&password=pass&query=select%20%2A%20from%20aaa.bbb'

Code: 195, e.displayText() = DB::Exception: User test is not allowed to connect from address 127.0.0.1, e.what() = DB::Exception

But when I do the same directly (using port 8123), it works fine:

curl 'http://clickhouse.mydomain:8123/?user=test&password=&query=select%20%2A%20from%20aaa.bbb'

The response is

123
1234

which is expected.

So it looks like in the first case when nginx is used as a reverse proxy, Clickhouse does not pick up the X-Forwarded-For header value when determining the IP address.

Is it possible to have this feature? Is there a workaround?

**Comment by rpuch** [comment]
I've used a simple echo server https://gist.github.com/solusipse/6419144 to make sure X-Forwarded-For is actually passed. For the following request

curl http://clickhouse.mydomain/aaa

I got the following:

GET /aaa HTTP/1.0
Host: clickhouse.mydomain
X-Real-IP: <my.ip>
X-Forwarded-For: <my.ip>
Connection: close
User-Agent: curl/7.47.0
Accept: */*

**Comment by filimonov** [comment]
X-Forwarded-For probably can be added to some stats, but using it for use authentication sounds  highly unsafe. 

If Clickhouse will start to trust X-Forwarded-For header (which can be easily added to any request), it will give a lot of options to abuse that.

So for example you will connect from every ip, and will add X-Forwarded-For: 127.0.0.1 to make ClickHouse think that this request is from localhost. 

For me it sounds like you need to just allow to connect to clickhouse from your reverse proxy ip, and limit the ips which can connect to proxy (inside proxy configuration) to get desired effect.

**Comment by rpuch** [comment]
Let's see how it looks case by case.

1. Someone makes a request from outside and that request goes through a reverse proxy, the reverse proxy will not let the existing X-Forwarded-For header through and instead it will replace it with a valid header. This case is ok.
2. Someone makes a request from outside, but that request reaches Clickhouse *directly*, then there is a danger that the request will smuggle its X-Forwarded-For header. In such a case, Clickhouse should only trust to IPs from a white list (IPs that are known to be reverse proxy IPs). By default, this list could contain just '127.0.0.1' (and ::1). When an attacker from outside tries to smuggle his X-Forwarded-For, his real IP will be different from any whitelisted address, so X-Forwarded-For will be ignored.
3. Someone who is already at reverse proxy host (usually, it's the same host where Clickhouse resides) makes a request and tries to fool the authentication. Here I can't invent anything. But the attacker is already inside the perimeter...

Wouldn't it possible to add this feature, but disable it by default, and add a clarification in the documentation which would state the risks?

>For me it sounds like you need to just allow to connect to clickhouse from your reverse proxy ip, and limit the ips which can connect to proxy (inside proxy configuration) to get desired effect.

It seems that this would reduce the flexibility of access control. I would like to have two users to only be able to connect from 2 IPs, one for each. Would it be possible?

**Comment by filimonov** [comment]
> It seems that this would reduce the flexibility of access control. I would like to have two users to only be able to connect from 2 IPs, one for each. Would it be possible?

Of course. If you will use Basic HTTP Authentication then you have a lot of configuration options. 
For example for Apache:
```
AuthType Basic
AuthUserFile /www/.site_htpasswd
AuthName "Protected Area"

<RequireAny>
    Require ip 1.2.3.4
    Require valid-user
</RequireAny>
```

Also, please take a look on that project https://github.com/Vertamedia/chproxy
It's a HTTP-proxy created especially for ClickHouse, it has a lot of ClickHouse-specific features and introduce few improvements in ClickHouse HTTP support.

**Comment by rpuch** [comment]
Thank you! I'll take a look at it
