### ISSUE TITLE
AVX Support

### ISSUE THREAD

**Issue by matthiasg** [yandex/ClickHouse#21]
Since many XEON processors available dont actually seem to support SSE4 but do support AVX are there any plans on updating to AVX ?

**Comment by alexey-milovidov** [comment]
All CPUs with AVX also have SSE4.

**Comment by DieHertz** [comment]
Concerning the initial question, SSE4.2 has some unique string-related instructions which are not present in AVX, thus "updating to AVX" is impossible is this regard.
However it may be interesting to implement runtime AVX code paths for functions which are currently vectorized using SSE2, potentially increasing theoretical throughput.

**Comment by matthiasg** [comment]
really annoying that the intel ark pages are so utterly unclear on this topic. some show avx, some show sse4 and some show both. also sse4 and other features are not filterable unlike  things such as socket type etc.

**Comment by alexey-milovidov** [comment]
Please also check these performance results: https://github.com/ClickHouse/ClickHouse/pull/20001#issuecomment-774661963
