### ISSUE TITLE
has function doesn't work corectly with Nullable strings

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#2115]
`has` functions seems is not working correctly when we have an array of nullable strings:

I saw that using `Array(Nullable(Uint8))` is working correctly . I didn't tested with more data types.

```sql
CREATE TABLE test_has_function(arr Array(Nullable(String))) ENGINE = Memory;
INSERT INTO test_has_function(arr) values ([null, 'str1', 'str2']),(['str1', 'str2']), ([]), ([]);
```

```sql
SELECT arr, has(`arr`, 'str1') FROM test_has_function;

[null,'str1','str2']  0 (WRONG - should be 1)
['str1','str2']       1 (OK)
[]                    0 (OK)
[]                    0 (OK)
```

**Comment by silviucpp** [comment]
Hello @alexey-milovidov ,

I'm trying to investigate this issue and I have a question: For the example I provided above what branch in FunctionArray it's expected to be executed starting from line 855:

Currently the second one is executed, but I have a feeling that first one is the proper one and `item_arg->onlyNull()` should evaluate to true and not false for this case. 

```c++
if (item_arg->onlyNull())
	ArrayIndexStringNullImpl<IndexConv>::vector_const(col_nested->getChars(), col_array->getOffsets(),
		col_nested->getOffsets(), col_res->getData(), null_map_data);
else if (const auto item_arg_const = checkAndGetColumnConstStringOrFixedString(item_arg))
	ArrayIndexStringImpl<IndexConv>::vector_const(col_nested->getChars(), col_array->getOffsets(),
		col_nested->getOffsets(), item_arg_const->getValue<String>(), col_res->getData(),
		null_map_data);
else if (const auto item_arg_vector = checkAndGetColumn<ColumnString>(item_arg))
	ArrayIndexStringImpl<IndexConv>::vector_vector(col_nested->getChars(), col_array->getOffsets(),
		col_nested->getOffsets(), item_arg_vector->getChars(), item_arg_vector->getOffsets(),
		col_res->getData(), null_map_data, null_map_item);
```

I'm trying to realize if I'm on the good track with debugging

Silviu

**Comment by alexey-milovidov** [comment]
Yes, it's a bug. I'll try to investigate.

**Comment by alexey-milovidov** [comment]
> item_arg->onlyNull() should evaluate to true and not false for this case

It's for the case when you write `arrayHas([...], NULL)`

**Comment by silviucpp** [comment]
Ok, so problem is in another place.

**Comment by alexey-milovidov** [comment]
The code is just plain wrong (no magic).

**Comment by alexey-milovidov** [comment]
Fix is in master.
