### ISSUE TITLE
Подзапрос выполняется в неверной БД.

### ISSUE THREAD

**Issue by aCLr** [yandex/ClickHouse#2124]
Имеется кластер БД, называется `mydb_cluster`, имеется БД `mydb`. БД по умолчанию - `mydb_cluster`.
Есть табличка такая:
```sql
CREATE TABLE mydb.traffic_stats ( ts_spawn UInt32,  user_id UInt32,  ...) ENGINE = Distributed(\'my_cluster\', \'mydb_shard\', \'traffic_stats\', rand()) 
```

И есть такая таблица:
```sql
SHOW CREATE TABLE users
CREATE TABLE mydb.users ( id UInt64,  name String,  manager_id UInt32) ENGINE = Dictionary(users)
```

Подключаюсь клиентом (или использую сторонний драйвер, неважно) указывая явно бд `mydb`.
```bash
➜  ~ clickhouse-client --database=mydb
ClickHouse client version 1.1.54370.
Connecting to database mydb at localhost:9000.
Connected to ClickHouse server version 1.1.54370.
```
Выполняю такой запрос:
```sql
SELECT 1  FROM traffic_stats  WHERE toUInt64(user_id) IN (SELECT id FROM users  WHERE manager_id IN (4));
```

Получаю ошибку:
```
Received exception from server (version 1.1.54370):
Code: 60. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Received from HOST:9000. DB::Exception: Table mydb_shard.users doesn't exist.. 
```

Немного неправильное, на мой взгляд, поведение. Да, лучше явно указать бд, в которую делать подзапрос, но тем не менее: я явно указал БД, в которую должны идти все запросы (если не указано иного), а запрос пошел куда-то не туда.

**Comment by filimonov** [comment]
Это поведение задокументировано: https://clickhouse.yandex/docs/ru/query_language/queries/#_8

> При использовании обычного IN-а, запрос отправляется на удалённые серверы, и на каждом из них выполняются подзапросы в секциях IN / JOIN. 

Попробуйте заменить IN на GLOBAL IN.

**Comment by aCLr** [comment]
Спасибо, разобрался
