### ISSUE TITLE
Wrong query result for WHERE (a, b) IN (SELECT (a, b) with *MergeTree

### ISSUE THREAD

**Issue by den-crane** [yandex/ClickHouse#2147]
version 1.1.54371

CREATE TABLE trololo (a String, b String) ENGINE = MergeTree order by a;
INSERT INTO trololo VALUES ('1', '2');

TEST: SELECT * FROM trololo WHERE (a, b) IN (SELECT (a, b) FROM trololo);
**0 rows in set. Elapsed: 0.003 sec.** . <-- expected one row.

WORKAROUND: SELECT * FROM trololo WHERE concat(a, b) IN (SELECT  concat(a, b) FROM trololo);
┌─a─┬─b─┐
│ 1 │ 2 │
└───┴───┘
1 rows in set. Elapsed: 0.013 sec

probable consequences of "An index of MergeTree tables is used when IN is applied to a tuple of expressions from the columns of the primary key. "

-----------------------------------
more weird issue: 

CREATE TABLE trololo (a date, b Int, c Int) ENGINE = MergeTree order by (a,b);
INSERT INTO trololo VALUES (0, 1, 3);

SELECT * FROM trololo WHERE (a, b) IN (SELECT (a, b) FROM trololo)
**Code: 169. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Bad type of Field.**

**second execution (wrong result):**
SELECT * FROM trololo WHERE (a, b) IN (SELECT (a, b) FROM trololo)
0 rows in set. Elapsed: 0.003 sec.

third: Ok. 0 rows in set. Elapsed: 0.003 sec.
forth: Code: 169. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Bad type of Field.

**Comment by den-crane** [comment]
seems first part of issue (0 rows) fixed in ClickHouse server version 1.1.54373.

But  weird issue still persists 

```
drop table trololo;
CREATE TABLE trololo (a date, b Int, c Int) ENGINE = MergeTree order by (a,b);
INSERT INTO trololo VALUES (0, 1, 3);


SELECT * FROM trololo WHERE (a, b) IN (SELECT (a, b) FROM trololo);
0 rows in set. Elapsed: 0.004 sec.

SELECT * FROM trololo WHERE (a, b) IN (SELECT (a, b) FROM trololo);
Received exception from server (version 1.1.54373):
Code: 169. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Bad type of Field.
0 rows in set. Elapsed: 0.062 sec.
```

**Comment by den-crane** [comment]
I realized now that I did typo "SELECT (a, b) " it's a tuple so the right behaviour is error "Bad type of Field"

But still v1.1.54378 returns no error in 10% of executions.
```

:) SELECT * FROM trololo WHERE (a, b) IN (SELECT (a, b) FROM trololo);

SELECT *
FROM trololo
WHERE (a, b) IN
(
    SELECT (a, b)
    FROM trololo
)

Ok.

0 rows in set. Elapsed: 0.003 sec.
```

**Comment by alexey-milovidov** [comment]
We've the behaviour more strict in https://github.com/yandex/ClickHouse/blob/master/CHANGELOG.md#backward-incompatible-changes
