### ISSUE TITLE
Cannot insert a human-readable Enum value using INSERT INTO .. SELECT

### ISSUE THREAD

**Issue by hatarist** [yandex/ClickHouse#215]
An example table:
```
 :) CREATE TABLE events (
        type Enum8('session' = 1, 'pageview' = 2, 'click' = 3),
        date Date,
        id UInt64
    ) ENGINE = MergeTree(date, (type, date, id), 8192);

Ok. 0 rows in set. Elapsed: 0.008 sec.
```

Adding the data from another table on the first try:
```
 :) INSERT INTO events
        SELECT
            'session' AS type,
            today() AS date,
            number AS id
        FROM system.numbers LIMIT 100
    ;

Received exception from server:
Type mismatch for column type. Column has type Enum8('session' = 1, 'pageview' = 2, 'click' = 3), got type String
```

Numbers won't be inserted too:
```
 :) INSERT INTO events
        SELECT
            1 AS type,
            today() AS date,
            number AS id
        FROM system.numbers LIMIT 100
    ;

Received exception from server:
Type mismatch for column type. Column has type Enum8('session' = 1, 'pageview' = 2, 'click' = 3), got type UInt8


 :) INSERT INTO events
        SELECT
            toInt8(1) AS type,
            today() AS date,
            number AS id
        FROM system.numbers LIMIT 100
    ;

Received exception from server:
Type mismatch for column type. Column has type Enum8('session' = 1, 'pageview' = 2, 'click' = 3), got type Int8
```

CASTing works, but it looks pretty bloaty:
```
 :) INSERT INTO events 
        SELECT 
            CAST('session' AS Enum8('session' = 1, 'pageview' = 2, 'click' = 3)) AS type,
            today() AS date,
            number AS id
        FROM system.numbers LIMIT 100
    ;

Ok. 0 rows in set. Elapsed: 0.005 sec.
```

Would it be OK to make `INSERT INTO (enum, ...) SELECT 'enumvalue', ...` work?

Related discussion on Google Groups: https://groups.google.com/forum/#!topic/clickhouse/sBxSJL3vZQ8

**Comment by hatarist** [comment]
Is there any way I could fix it myself? Could you describe the origin of the issue so I could dig into it?

**Comment by alexey-milovidov** [comment]
It is needed to create stream, that will apply type conversions.
Look at `InterpreterInsertQuery::execute`. There are similar things: `AddingDefaultBlockOutputStream`, `SquashingBlockOutputStream`, that do some transformations on INSERT.

I hope that https://github.com/artpaul could implement it.

**Comment by philodavies** [comment]
What was the status of this issue? It got closed, but I don't seem to be able to insert into a table with the int8 value of an enum.

**Comment by filimonov** [comment]
@philodavies please, give a simple sample.

**Comment by philodavies** [comment]
Hi @filimonov, here's a test schema I am using
`CREATE TABLE IF NOT EXISTS test
(
    date Date,
    datetime DateTime,
    unit Enum8('TRUE' = 0, 'FALSE' = 1),
    value UInt64
)
ENGINE = MergeTree(date, (date, unit), 8192);
`

I can insert with the following `insert into test VALUES (18128, 1566305279, 'TRUE', 7685439657824)` and it succeeds.

However, when I try to replace 'TRUE' with 0, it fails:
`insert into test VALUES (18128, 1566305279, 0, 7685439657824)`
Error message: `Code: 53. DB::Exception: Type mismatch in IN or VALUES section. Expected: Enum8('TRUE' = 0, 'FALSE' = 1). Got: UInt64`

I get the same with the following: `insert into test VALUES (18128, 1566305279, toInt8(0), 7685439657824)`
Error message: `Code: 53. DB::Exception: Type mismatch in IN or VALUES section. Expected: Enum8('TRUE' = 0, 'FALSE' = 1). Got: Int64`

**Comment by filimonov** [comment]
So It's actually another issue. Human-readable format is accepted. If you think that numeric form shoul be also accepted - please create another issue with motivation. 


BTW, the workaround is simple - use CAST(1,'Enum8('TRUE' = 0, 'FALSE' = 1)

**Comment by alexey-milovidov** [comment]
Numeric form should be accepted.

**Comment by philodavies** [comment]
@alexey-milovidov you say that it should be accepted, any clue why it was failing in my sample?
