### ISSUE TITLE
Зависает первая вставка в ENGINE File (после Select)

### ISSUE THREAD

**Issue by Artemeey** [yandex/ClickHouse#2150]
1) `CREATE TABLE test_file_engine (number UInt64) ENGINE = File(TSV)`
2) `SELECT * FROM test_file_engine`
Code: 107, e.displayText() = DB::Exception: Cannot open file .../test_file_engine/data.TSV, errno: 2, strerror: No such file or directory
> Это не проблема, тут все работает верно!
3) `INSERT INTO positions.test_file_engine VALUES (1)`
>А вот это уже приведет к ошибке
Данные запрос почему-то зависает и висит в процессах. Помогает только перезапуск сервера CH.

Если шаги 2 и 3 поменять местами, ошибка не воспроизводится.

version(): 1.1.54370

**Comment by alexey-milovidov** [comment]
Действительно, там дурацкий код.
