### ISSUE TITLE
Kafka Engine ignore input encode error message

### ISSUE THREAD

**Issue by linuxgood1230** [yandex/ClickHouse#2171]
I want drop some input message

2018.04.04 23:22:51.992124 [ 25 ] <Error> void DB::StorageKafka::streamThread(): Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected , before:

**Comment by linuxgood1230** [comment]
Found It
input_format_allow_errors_ratio

**Comment by linuxgood1230** [comment]
input_format_allow_errors_ratio
input_format_allow_errors_num
Do not effect StoreKafka

**Comment by yctn** [comment]
Did you manage to resolve this? it seems 
input_format_allow_errors_ratio
input_format_allow_errors_num
doesnt affect kafka

**Comment by linuxgood1230** [comment]
nobody nobody no. close
