### ISSUE TITLE
KafkaEngine and chained materialized views doesn't work

### ISSUE THREAD

**Issue by tobad357** [yandex/ClickHouse#2174]
This used to work in v1.1.54342 but now doesn't work in v1.1.54370
Expected is as follows

Kafka -> foo_mv (mat view) -> foo (table) -> foo_2_mv (mat view) -> foo_2
currently it goes
Kafka -> foo_mv (mat view) -> foo (table)

But if I insert a row manually into foo (table) then it will go into foo_2 via foo_2_mv

```
CREATE TABLE foo
(
    date Date,
    id UInt8
) ENGINE = MergeTree(date, (date, id), 8192)

CREATE TABLE foo_2
(
    date Date,
    id UInt8
) ENGINE = MergeTree(date, (date, id), 8192)

CREATE TABLE IF NOT EXISTS foo_kafka (
    transactionTime UInt64,
    id UInt64
) ENGINE = Kafka('localhost:9092', 'TEST_TOPIC', 'foo', 'test,'Test');

CREATE MATERIALIZED VIEW IF NOT EXISTS foo_mv
TO foo
AS SELECT toDate(testDate) as date, toUInt8(id) as id from foo_kafka

CREATE MATERIALIZED VIEW IF NOT EXISTS foo_2_mv
TO foo_2
AS SELECT date, id from foo
```

**Comment by vavrusa** [comment]
Does it work when you attach the second MV to `foo_mv`? e.g.

```CREATE MATERIALIZED VIEW IF NOT EXISTS foo_2_mv TO foo_2 AS SELECT date, id FROM foo_mv```

I think I've encountered that as well recently, the behavior must have changed.

**Comment by tobad357** [comment]
Great news that works. so it solves my problem but is still a bit of a papercut.

**Comment by simPod** [comment]
Encountered the same issue. I intended to chain it 

```
kafka -> mv stream A -> table A -> mv stream B -> table B
```

but had to create `MV stream B` from `MV stream A` instrad of from `table A`

```
kafka -> mv stream A -> table A 
                     -> mv stream B -> table B
```

Glad it works tho

**Comment by adilets** [comment]
Why we can't read from `foo` and write to `foo_2`. I really need to read from foo table. 

I have like this structure: 
```
kafkaA -> mv stream A \  table A -> mv stream B -> table B
kafkaB -> mv stream B  /                     
```

**Comment by filimonov** [comment]
Cascading materialized views are nor supported.

Probably you can workaround it by creating MV to Distributed table which will insert data to MergeTree, which have another MV.
