### ISSUE TITLE
Question about data update capabilities

### ISSUE THREAD

**Issue by HelgiHelgason** [yandex/ClickHouse#2179]
Are there any plans in the near future to provide more options for updating existing data in Clickhouse? This may be more relevant now than before as with the onset of GDPR organizations will need to be able to regularly do things such as erase or anonymize customer data with minimal operational impact.

**Comment by tobad357** [comment]
As far as I know mid may - june is planned for some simple update/delete functionality

**Comment by blinkov** [comment]
Batch deletes has been released few weeks ago, batch updates are in progress.
