### ISSUE TITLE
"PKCondition::mayBeTrueInRange" errors on 1.1.54370

### ISSUE THREAD

**Issue by jpiper** [yandex/ClickHouse#2181]
I upgraded my cluster to 1.1.54370 and queries on a distributed table that point to a ReplicatedAggregativeMergeTree are failing with

> Unexpected stack size in PKCondition::mayBeTrueInRange

Downgrading to 1.1.54362 fixed the issue. Any ideas what it could be (and any information that would be helpful for your debugging?)

**Comment by den-crane** [comment]
https://github.com/yandex/ClickHouse/issues/2170
https://github.com/yandex/ClickHouse/pull/2173
