### ISSUE TITLE
Update YUM Packages to last stable version

### ISSUE THREAD

**Issue by jonatasfreitasv** [yandex/ClickHouse#2187]
Using this tutorial https://github.com/Altinity/clickhouse-rpm-install the last version is 1.1.54362-1.el7.

Please, update to last stable version!

**Comment by alex-zaitsev** [comment]
We are waiting for the latest stable version. 1.1.54.370 is not stable -- too many bugs.

**Comment by millin** [comment]
From now you can checkout official repo:
https://repo.yandex.ru/clickhouse/rpm/stable/x86_64/

**Comment by jonatasfreitasv** [comment]
@alex-zaitsev and @millin 

The 1.1.54370 version is stable for now ?

**Comment by xiaoshuai** [comment]
try to add `/etc/yum.repos.d/clickhouse.repo`

```
[clickhouse]
name=clickhouse repo
baseurl=http://repo.yandex.ru/clickhouse/rpm/stable/$basearch/
gpgcheck=0
enabled=1
```
