### ISSUE TITLE
Support LIMIT n, m BY clause

### ISSUE THREAD

**Issue by derekperkins** [yandex/ClickHouse#2198]
I love the power of `LIMIT N BY`. The issue I run into is when someone is paginating through a list, there isn't a way to offset those numbers. For example, with page size of 10, I end up doing `LIMIT 10 BY date` for the first set of results, then `LIMIT 20 BY date` for the second page, but then I have to ignore page 1 of the results. Each new page multiplies the response size.

I'd like to propose a new syntax that works the same as a traditional `LIMIT` clause. To get the third page in my example, I would write `LIMIT 20, 10 BY date`.

**Comment by AlexMAS** [comment]
Is there any progress for this issue? :)

**Comment by alexey-milovidov** [comment]
It is assigned to @CurtizJ

**Comment by alexey-milovidov** [comment]
Implemented in #5138.
Merged into master.
