### ISSUE TITLE
Clickhouse Distributed Table Issue

### ISSUE THREAD

**Issue by fahrettinf89** [yandex/ClickHouse#2199]
Hi there,
I am trying to create a distributed table with 2 shards. And this each shard have one replica.  I have another remote clickhouse server with the same database, table name and same table type. The query while I'm using to create mergetree table on both server with the following syntax;
`create table boncuk ENGINE=MergeTree PARTITION by toDate(EventTime) order by (EventTime,Ip2,Ip3) as select * from remote('192.168.56.102',default.b) limit 1`

to create Distributed table on localhost ;
`create table d_y as boncuk ENGINE=Distributed(mavi,default,boncuk,2)`

and my clickhouse-server/config.xml contains;

```
<remote_servers incl="clickhouse_remote_servers" >
        <!-- Test only shard config for testing distributed storage -->
        <mavi>
            <shard>
                <weight>9</weight>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>localhost</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <weight>10</weight>
                <internal_replication>false</internal_replication>
                <replica>
                    <host>192.168.56.102</host>
                    <port>9000</port>
                </replica>
            </shard>
        </mavi>
    </remote_servers>
```
When I trying to insert data to d_y(distributed table),the data inserted only one of the replicas. But I have two. Am I missing something maybe some extra setting that should be set?

**Comment by jonatasfreitasv** [comment]
Insert data into a Distributed table to insert in both shards.

**Comment by fahrettinf89** [comment]
@jonatasfreitasv I was inserting to Distributed data already as I mention above. Do you mean "I have to have separate Distributed tables on both remote and localhost?"

**Comment by filimonov** [comment]
>When I trying to insert data to d_y(distributed table),the data inserted only one of the replicas. But I have two.

In your config i see only one replica in each shard. You was also saying that:

> And this each shard have one replica.

So the data should be inserted into one (and only) replica in one of the shards. (there are 10/19 chances that it will be 192.168.56.102 and 9/19 that it will be localhost). 

So what is the exact problem?

**Comment by fahrettinf89** [comment]
@filimonov I create my Distributed table with following syntax and it seems work;
`create table d_y as boncuk ENGINE=Distributed(mavi,default,boncuk,2rand())`

Thx. 
But I think sharding key part in documentation should be more detailed. I would never understand the problem if I didn't ask this question.

Thank you very much.

**Comment by filimonov** [comment]
If you need to have the same data on 2 servers - you need a replication, not a shardind. 

Please read answers here: https://github.com/yandex/ClickHouse/issues/2161

**Comment by blinkov** [comment]
@fahrettinf89 do you have any further questions?

**Comment by filimonov** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. 

Please reopen if you still encounter this issue with the latest stable version. 

Thank you!
