### ISSUE TITLE
Stable build is broken

### ISSUE THREAD

**Issue by podshumok** [yandex/ClickHouse#221]
```
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/memory:81:0,
                 from /tmp/src/github.com/yandex/ClickHouse/dbms/include/DB/Common/Exception.h:5,
                 from /tmp/src/github.com/yandex/ClickHouse/dbms/include/DB/Core/Field.h:10,
                 from /tmp/src/github.com/yandex/ClickHouse/dbms/include/DB/Core/FieldVisitors.h:3,
                 from /tmp/src/github.com/yandex/ClickHouse/dbms/include/DB/Storages/MergeTree/PKCondition.h:5,
                 from /tmp/src/github.com/yandex/ClickHouse/dbms/src/Storages/tests/pk_condition.cpp:2:
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/bits/unique_ptr.h: In instantiation of 'typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = DB::PKCondition; _Args = {std::shared_ptr<DB::IAST>&, DB::Context&, DB::NamesAndTypesList&, std::vector<DB::SortColumnDescription, std::allocator<DB::SortColumnDescription> >&}; typename std::_MakeUniq<_Tp>::__single_object = std::unique_ptr<DB::PKCondition>]':
/tmp/src/github.com/yandex/ClickHouse/dbms/src/Storages/tests/pk_condition.cpp:34:72:   required from here
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/bits/unique_ptr.h:765:69: error: no matching function for call to 'DB::PKCondition::PKCond
ition(std::shared_ptr<DB::IAST>&, DB::Context&, DB::NamesAndTypesList&, std::vector<DB::SortColumnDescription>&)'
     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
                                                                     ^
In file included from /tmp/src/github.com/yandex/ClickHouse/dbms/src/Storages/tests/pk_condition.cpp:2:0:
/tmp/src/github.com/yandex/ClickHouse/dbms/include/DB/Storages/MergeTree/PKCondition.h:226:2: note: candidate: DB::PKCondition::PKCondition(DB::
ASTPtr&, const DB::Context&, const DB::NamesAndTypesList&, const SortDescription&, const DB::Block&)
  PKCondition(ASTPtr & query, const Context & context, const NamesAndTypesList & all_columns, const SortDescription & sort_descr,
  ^
/tmp/src/github.com/yandex/ClickHouse/dbms/include/DB/Storages/MergeTree/PKCondition.h:226:2: note:   candidate expects 5 arguments, 4 provided
/tmp/src/github.com/yandex/ClickHouse/dbms/include/DB/Storages/MergeTree/PKCondition.h:216:7: note: candidate: DB::PKCondition::PKCondition(const DB::PKCondition&)
 class PKCondition
       ^
/tmp/src/github.com/yandex/ClickHouse/dbms/include/DB/Storages/MergeTree/PKCondition.h:216:7: note:   candidate expects 1 argument, 4 provided
/tmp/src/github.com/yandex/ClickHouse/dbms/include/DB/Storages/MergeTree/PKCondition.h:216:7: note: candidate: DB::PKCondition::PKCondition(DB::PKCondition&&)
/tmp/src/github.com/yandex/ClickHouse/dbms/include/DB/Storages/MergeTree/PKCondition.h:216:7: note:   candidate expects 1 argument, 4 provided
dbms/src/Storages/tests/CMakeFiles/pk_condition.dir/build.make:62: recipe for target 'dbms/src/Storages/tests/CMakeFiles/pk_condition.dir/pk_condition.cpp.o' failed
```

**Comment by ludv1x** [comment]
Could you provide hash of a commit used for build?
It seems that you use outdated version.
Master branch now looks as follows:
https://github.com/yandex/ClickHouse/blob/master/dbms/src/Storages/tests/pk_condition.cpp#L35
(5 arguments in constructor)

**Comment by alexey-milovidov** [comment]
I have just checked the build and it is fine.

BTW, in per-commit auto builds, we are building only clickhouse-server, not all targets.

**Comment by podshumok** [comment]
I use last tag labeled as stable:

git checkout tags/v1.1.54083-stable
HEAD is now at 0a2d1eb... Attempt to improve merge selecting algorithm [#METR-23632].

**Comment by podshumok** [comment]
May be you can benefit from building all targets with Circle CI or something like that?

**Comment by alexey-milovidov** [comment]
We have investigated possibility of using Travis CI and Circle CI.
For Travis CI, maximum build time in free version is not enough.
For Circle CI, there is no root access to install custom packages.

We already have our internal CI, and our QA engineers could enable check for all targets.

**Comment by podshumok** [comment]
With Circle CI you can build in docker.

https://circleci.com/docs/docker/

**Comment by ludv1x** [comment]
We considered different variants of CI build system to make results of per-commits builds and tests publicly available.
Circle CI and similar CI systems (CI as a service) have serious limitations.
For example, Circle CI allows to use only strictly pre-defined VM configurations, so we even cannot use gcc 5 to compile.
Nevertheless, we plan to make our task tracker and CI system publicly available.

**Comment by podshumok** [comment]
While it is not possible to install gcc5 in Circle CI with free plan (with paid access you can ask their tech support to install everything you want), you are allowed to run `docker build` inside CircleCI instance.
Having that you can create builder image with newest GCC and other dependencies and than run `docker run` to compile clickhouse and collect artefacts.
I believe this is the fastest way.

**Comment by alexey-milovidov** [comment]
I have just created v1.1.54093-testing:
https://github.com/yandex/ClickHouse/releases/tag/v1.1.54093-testing
which is as stable as the latest stable tag.

**Comment by podshumok** [comment]
What is the criteria for a tag to be "-stable"?

**Comment by alexey-milovidov** [comment]
It must be released to our production clusters.

**Comment by alexey-milovidov** [comment]
We have several new stable releases since then.
Including release 1.1.54127 today.
