### ISSUE TITLE
there are a lot of files in the data directory

### ISSUE THREAD

**Issue by 27260102** [yandex/ClickHouse#2214]
ClickHouse/dbms/src/Storages/Distributed/DistributedBlockOutputStream.cpp

the function  【writeToShard】will make a lot of files in the data directory,and it maybe influence start

like this

-rw-r--r-- 1 root root 525 Apr 13 13:50 973.bin
-rw-r--r-- 1 root root 523 Apr 13 13:50 977.bin
-rw-r--r-- 1 root root 524 Apr 13 13:48 97.bin
-rw-r--r-- 1 root root 524 Apr 13 13:50 985.bin
-rw-r--r-- 1 root root 529 Apr 13 13:50 993.bin
-rw-r--r-- 1 root root 523 Apr 13 13:50 995.bin
-rw-r--r-- 1 root root 521 Apr 13 13:50 997.bin
drwxr-xr-x 3 root root  17 Apr 13 14:07 default@172%2E22%2E94%2E76:9001
drwxr-xr-x 3 root root  17 Apr 13 14:07 default@172%2E22%2E94%2E77:9001
drwxr-xr-x 3 root root  17 Apr 13 14:07 default@172%2E22%2E94%2E78:9001
drwxr-xr-x 3 root root  17 Apr 13 14:07 default@172%2E22%2E94%2E79:9001
drwxr-xr-x 2 root root   6 Apr 13 14:07 tmp

**Comment by blinkov** [comment]
@27260102 it is recommended to write data to shards directly instead of via Distributed table.
