### ISSUE TITLE
A good notice - Enterprise ClickHouse Database IDE 

### ISSUE THREAD

**Issue by jonatasfreitasv** [yandex/ClickHouse#2218]
Hello Yandex friends,

after several tests on ClickHouse, I felt the power of this tool.

I would like to thank the wonderful work done by the Yandex team.

We are already using the company where I work, Zenvia, and is bringing us great solutions for data analysis.

However we are having some difficulties in making it available for "non-technical" users to do querys, monitor features and everything else. For the tools of interaction with ClickHouse are very bad and full of bug (like Tabix).

ClickHouse has to have a tool similar to that of MemSQL for example, I'm sure it will greatly increase the use of ClickHouse throughout the community.

Thinking about that, I decided to start a project to make it possible, it's right at the beginning, but I have good visions of how it should be.

This is the initial repository -> https://github.com/jonatasfreitasv/HouseDash
The name I'm still thinking, if you have suggestions hehe :).

My vision with some features -> https://github.com/jonatasfreitasv/HouseDash/projects

I want to do something really relevant, to be proud of Yandex and your team.

If anyone wants to contribute to the project, I will be very grateful (jonatasfreitasv@gmail.com).

I need UX / UI and React professionals.

If you can publish this work so that I can get more contributors, I would appreciate it.

Thank you again, and got o work hard!!!

**Comment by sundy-li** [comment]
Sounds great!

**Comment by jonatasfreitasv** [comment]
Preview:

![alt text](https://image.ibb.co/k70urn/Screenshot_from_2018_04_16_01_10_27.png)

**Comment by jonatasfreitasv** [comment]
*Last commits:*

- Implement query post and ace editor
- Implement React Table
- Added basic layout with React Ant Design

**Comment by tannerlinsley** [comment]
I can be of assistance.

**Comment by jonatasfreitasv** [comment]
Wow! Thx a lot @tannerlinsley !

**Comment by jonatasfreitasv** [comment]
Last commits:

- Database, Tables, Columns spec in SideBar
- Split panels
- Database settings

**Comment by jonatasfreitasv** [comment]
Last comits:
- Refactor a lot of thinks in layout
- Added refresh data in SideBar
- Added ScrollBars in Table, SideBar and JSON Response
- Added Keyboar ShortCuts in Query
- Added Query header Buttons

**Comment by jonatasfreitasv** [comment]
Day 4 (2018-04-26)
- Added Split Panel horizontal on Query
- Refactor all design in SideBar Tree
- Fix bugs when query not have any data


Day 3 (2018-04-19)
- Refactor a lot of thinks in layout
- Added refresh data in SideBar
- Added ScrollBars in Table, SideBar and JSON Response
- Added Keyboar ShortCuts in Query
- Added Query header Buttons


Day 2 (2018-04-18)
- Database, Tables, Columns spec in SideBar
- Split panels
- Database settings


Day 1 (2018-04-17)
- Implement query post and ace editor
- Implement React Table
- Added basic layout with React Ant Design

**Comment by zhaodagang** [comment]
dear @jonatasfreitasv:

We are also doing this product, we hope to develop together.

**Comment by jonatasfreitasv** [comment]
### Day 5 (2018-04-29)
- First alpha release (https://github.com/jonatasfreitasv/HouseOps/releases/tag/0.0.1-alpha.1)
- User and Pass on Database Configuration
- Launch Query in selected text
- Change prmary color to Yandex Yellow
- Remove a lot of unused files.

**Comment by jonatasfreitasv** [comment]
Version 1.0.0-beta is open!!!!

https://github.com/HouseOps/HouseOps

**Comment by sundy-li** [comment]
@meshpaul  By the way, we are working on Java Native jdbc library, 
 see [here](https://github.com/houseflys/ClickHouse-Native-JDBC)

**Comment by perez1987** [comment]
Congratulations! I'm going to try it and test it.

**Comment by meshpaul** [comment]
@sundy-li anything wrong with this one https://github.com/yandex/clickhouse-jdbc. We use it and WOW what a difference 75% decrease on our GC during massive heavy loads when we switched from Oracle

**Comment by perez1987** [comment]
Testing in development environment :-)

**Comment by jonatasfreitasv** [comment]
Version 0.2.1-beta (Version name is reseted!)
https://github.com/HouseOps/HouseOps

- `Epic Feature` Alert in UI on new release or auto-update.
- `Feature` Additional serach in columns table results.
- `Feature` Button for open debug tools in production.

- `UI/UX` Fix column filter/search style (https://github.com/HouseOps/HouseOps/pull/17)

- `Improvement` Add https://github.com/sindresorhus/pretty-bytes module in location when show bytes information.
- `Improvement` Send all errors log to ElasticSearch, with user confirmation.
- `Improvement` Loading spinner on DatabaseTree.

- `Refactor` Refactor React Props usage.

- `BUG` Fix background-color bug in Loading page and No database is configured.
- `BUG` Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option> in Settings.js.
- `BUG` Clear use database cache when save new connection.
- `BUG` Fix query execution when have `;` character.

**Comment by jonatasfreitasv** [comment]
Version 0.3.0-beta!
https://github.com/HouseOps/HouseOps

Feature In Processes List, recording feature to capture all processes.
Feature In Processes List, added line graphic to show pending processes.
Feature Query history.

Improvement Put http:// or https:// before host message in Database Settings.

UI/UX Add icons in all buttons.
UI/UX Added animations in elements on show.
UX/UI EULA dialog cause undesired scroll.

BUG Error connection message in Database Tree when run count in bugged Distributed table.

Refactor A lot of refactors.

**Comment by blinkov** [comment]
HouseOps is listed on a 3rd party GUI page: https://clickhouse.yandex/docs/en/interfaces/third-party/gui/

**Comment by mbtolou** [comment]
I wrote driver for popular database client project to use as clickhouse IDE.

https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-mysql-client2
