### ISSUE TITLE
REST API to delivery results query in browser front-end

### ISSUE THREAD

**Issue by jonatasfreitasv** [yandex/ClickHouse#2225]
I need to deliver the data from ClickHouse to a browser, obviously I will not run the querys directly in the database, for security reasons.

My idea is to develop an intermediate REST API, do you have any suggestions for stack, modules or ideas? (aside from the oblivion of simply doing a POST on the HTTP interface of ClickHouse)

**Comment by sundy-li** [comment]
You could build a restful web server to handle the front queries, and send the query to ClickHouse  by tcp or native tcp client. In this way,  the web server is just a query proxy,  and you can do anything to have security control of queries.  
May be you could try the client https://github.com/kshvakov/clickhouse.   We have already built an api server based on this client and go http, it's very simple by using Go to make that.

**Comment by jpiper** [comment]
Try https://github.com/Vertamedia/chproxy

**Comment by ruslantalpa** [comment]
I've developed exactly this,
PostgREST compatible api on top of clickhouse https://github.com/subzerocloud/showcase/tree/main/clickhouse
