### ISSUE TITLE
Address already in use error with docker image 1.1.54378

### ISSUE THREAD

**Issue by derekperkins** [yandex/ClickHouse#2228]
I just upgraded my application from 1.1.54370 to 1.1.54378 by simply using the new docker image. I'm now getting an error in the error log:
`Error&gt; Application: Net Exception: Address already in use: 127.0.0.1:8123`

Any idea what might be causing this error?

**Comment by derekperkins** [comment]
When I rolled back to `1.1.54370`, everything initialized properly.

cc @alex-zaitsev

**Comment by filimonov** [comment]
Check the changelog ( #2215 ) regarding port reuse and listen configuration.

вт, 17 апр. 2018 г., 0:02 Derek Perkins <notifications@github.com>:

**Comment by derekperkins** [comment]
Thanks @filimonov! For future reference, here is the Google Translate version of the changelog. Adding `<listen_reuse_port>1</listen_reuse_port>` to my config.xml solved the problem immediately.

> The server no longer uses the SO_REUSEPORT socket option by default. Now a multiple listen of one address, for example <listen_host> :: </ listen_host> <listen_host> 0.0.0.0 </ listen_host>, will generate an error. To enable this option, add <listen_reuse_port> 1 </ listen_reuse_port>
