### ISSUE TITLE
Setting up ClickHouse on MacOS not working as per documentation

### ISSUE THREAD

**Issue by gksinghjsr** [yandex/ClickHouse#2232]
I tried to set up ClickHouse on my mac, and followed the steps listed here - https://clickhouse.yandex/docs/en/development/build_osx/, however, it did not work for me.
I had to use clang and some changes in code in order to set it up. 
Is this documentation updated, if not, what are the steps to be followed to set it up on mac.

**Comment by jonatasfreitasv** [comment]
For dev env, Docker is best option.

**Comment by arduanov** [comment]
Last stable build for homebrew
https://github.com/arduanov/homebrew-clickhouse

**Comment by millin** [comment]
@arduanov Is there the way to install client only?

**Comment by arduanov** [comment]
no, client and server is the one binary

**Comment by proller** [comment]
Now you can build only client : 
```cmake .. -DENABLE_CLICKHOUSE_ALL=0 -DENABLE_CLICKHOUSE_CLIENT=1 -DCMAKE_CXX_COMPILER=`which g++-7` -DCMAKE_C_COMPILER=`which gcc-7`
make -j clickhouse-client
```

**Comment by Duiesel** [comment]
Doesn't work for now.

**Comment by Duiesel** [comment]
> Now you can build only client :
> 
> ```
> cmake .. -DENABLE_CLICKHOUSE_ALL=0 -DENABLE_CLICKHOUSE_CLIENT=1 -DCMAKE_CXX_COMPILER=`which g++-7` -DCMAKE_C_COMPILER=`which gcc-7`
> make -j clickhouse-client
> ```

Doesn't work for now.

**Comment by proller** [comment]
How exactly it doesn't work?

**Comment by alexey-milovidov** [comment]
You have to replace `make` with `ninja`.

**Comment by filimonov** [comment]
Relates #235

**Comment by innerstage** [comment]
Hi! This was a big problem for me, but I used Docker and now it's working fine. Here are a few steps that might help:
1. Install [Docker Desktop](https://www.docker.com/products/docker-desktop) on your Mac.
2. Create a Clickhouse container, but remember to expose both ports:
`docker run -d --name clickhouse-local -p 8123:8123 -p 9000:9000 --ulimit nofile=262144:262144 yandex/clickhouse-server`
3. You can access the container with `sudo docker exec -it clickhouse-local bash`
4. Inside the container you can access the Clickhouse client by doing `clickhouse-client`
5. You can create your first database there with `CREATE DATABASE myfirstdatabase`
6. I recommend [DBeaver](https://dbeaver.io/) to set up a connection with the database, remember the structure for the JDBC driver will be: `jdbc:clickhouse://<USER>:<PASSWORD>@localhost:8123/<DATABASE>`. Remember that the 8123 port is exposed for the HTTP interface, but if you want to connect to the native client (maybe an ingestion via script like I do) you need to use port 9000.

I hope this helps!

**Comment by scottlepp** [comment]
brew tap arduanov/clickhouse
brew install gcc@8
brew install --cc=gcc-8 clickhouse

You many encounter dependency errors during the above install. If a dependency fails to install, identify that dependency in the error and: 
1. brew install <dependency> (without the --cc flag). 
2. brew install --cc=gcc-8 clickhouse (again)

You may have to do the above repeatedly for each error.

**Comment by filimonov** [comment]
Let's continue in #6459

**Comment by ice1x** [comment]
> brew tap arduanov/clickhouse

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/arduanov/homebrew-clickhouse/clickhouse.rb
clickhouse: undefined method `devel' for #<Class:0x00007f87ff88abb0>
Error: Cannot tap arduanov/clickhouse: invalid syntax in tap!
