### ISSUE TITLE
"OR" Condition does not behave as expected

### ISSUE THREAD

**Issue by mighTY94** [yandex/ClickHouse#2237]
I have a table, populated with data.

For the sake of simplicity, I will call my **table x**, the problematic field **prob_field** and the other non-problematic ones **field** and **field2**

When I run the query:
`Select COUNT(*) FROM x WHERE field = 4445`
it returns the expected count.
Also:
`Select COUNT(*) FROM x WHERE prob_field = 1114`
it does return 0 rows, as expected.

But when I run:
`SELECT COUNT(*) FROM x WHERE field = 4445 OR prob_field = 1114`
it returns 0 rows.

It is a strange behaviour, because I have another field(field2 for example), which when I substitute with prob_field, works as expected even though the value does not exist.

This strange behaviour happens only with 2 fields in the database, with the following structure:
`Nullable(UInt32)`

The non-problematic fields are also with `Nullable(UInt32)`

Note:
If the value provided for prob_field exists in the whole table as a value, it works great. _This only happens with values, that do not currently exist in the table for the column._ I tried with `prob_field IS NULL` and `prob_field IS NOT NULL`, still works great.

EDIT:
**After further investigation, it turns out the problem isn't with the fields themselves. More like if the condition is X = 4 OR y = 5, it WON'T return the cases, where X is 4 and Y is NULL even if specify OR (X = 4 AND y IS NULL)**

**Comment by ludv1x** [comment]
What ClickHouse version do you use?
We have fixed several bugs related to Nullable columns and logical operators in recent releases.

**Comment by mighTY94** [comment]
How recent?
Clickhouse version - 1.1.54310

**Comment by ludv1x** [comment]
It works fine in the latest 54378.

```
CREATE TABLE nullable
(
    k UInt32, 
    v1 Nullable(UInt32), 
    v2 Nullable(UInt32)
)
ENGINE = MergeTree
ORDER BY k

Ok.

0 rows in set. Elapsed: 0.007 sec. 

vludv-ub :) insert into nullable VALUES (1, 1, 1)

INSERT INTO nullable VALUES

Ok.

1 rows in set. Elapsed: 0.003 sec. 

vludv-ub :) insert into nullable VALUES (2, NULL, 1)

INSERT INTO nullable VALUES

Ok.

1 rows in set. Elapsed: 0.003 sec. 

vludv-ub :) insert into nullable VALUES (3, 1, NULL)

INSERT INTO nullable VALUES

Ok.

1 rows in set. Elapsed: 0.002 sec. 

vludv-ub :) insert into nullable VALUES (4, NULL, NULL)

INSERT INTO nullable VALUES

Ok.

1 rows in set. Elapsed: 0.003 sec. 

vludv-ub :) select * from nullable

SELECT *
FROM nullable 

┌─k─┬─v1─┬─v2─┐
│ 3 │  1 │ \N │
└───┴────┴────┘
┌─k─┬─v1─┬─v2─┐
│ 1 │  1 │  1 │
└───┴────┴────┘
┌─k─┬─v1─┬─v2─┐
│ 4 │ \N │ \N │
└───┴────┴────┘
┌─k─┬─v1─┬─v2─┐
│ 2 │ \N │  1 │
└───┴────┴────┘

4 rows in set. Elapsed: 0.003 sec. 

vludv-ub :) select * from nullable ORDER BY k

SELECT *
FROM nullable 
ORDER BY k ASC

┌─k─┬─v1─┬─v2─┐
│ 1 │  1 │  1 │
│ 2 │ \N │  1 │
│ 3 │  1 │ \N │
│ 4 │ \N │ \N │
└───┴────┴────┘

4 rows in set. Elapsed: 0.003 sec. 

vludv-ub :) SELECT * FROM nullable WHERE v1 = 1

SELECT *
FROM nullable 
WHERE v1 = 1

┌─k─┬─v1─┬─v2─┐
│ 1 │  1 │  1 │
└───┴────┴────┘
┌─k─┬─v1─┬─v2─┐
│ 3 │  1 │ \N │
└───┴────┴────┘

2 rows in set. Elapsed: 0.004 sec. 

vludv-ub :) SELECT * FROM nullable WHERE v2 = 1

SELECT *
FROM nullable 
WHERE v2 = 1

┌─k─┬─v1─┬─v2─┐
│ 1 │  1 │  1 │
└───┴────┴────┘
┌─k─┬─v1─┬─v2─┐
│ 2 │ \N │  1 │
└───┴────┴────┘

2 rows in set. Elapsed: 0.004 sec. 

vludv-ub :) SELECT * FROM nullable WHERE v1 = 1 OR v2 = 1 

SELECT *
FROM nullable 
WHERE (v1 = 1) OR (v2 = 1)

┌─k─┬─v1─┬─v2─┐
│ 3 │  1 │ \N │
└───┴────┴────┘
┌─k─┬─v1─┬─v2─┐
│ 1 │  1 │  1 │
└───┴────┴────┘
┌─k─┬─v1─┬─v2─┐
│ 2 │ \N │  1 │
└───┴────┴────┘

3 rows in set. Elapsed: 0.003 sec. 

vludv-ub :) SELECT * FROM nullable WHERE v1 = 1 OR v2 = 2

SELECT *
FROM nullable 
WHERE (v1 = 1) OR (v2 = 2)

┌─k─┬─v1─┬─v2─┐
│ 3 │  1 │ \N │
└───┴────┴────┘
┌─k─┬─v1─┬─v2─┐
│ 1 │  1 │  1 │
└───┴────┴────┘
```
