### ISSUE TITLE
Bug: different names of columns

### ISSUE THREAD

**Issue by sundy-li** [yandex/ClickHouse#2239]
report a bug

version: ClickHouse version 1.1.54378. 
error log is:

```

:) select  name,   uid   from dis_cdn  where its > now()-3600  order by its desc limit 10;

SELECT
    name,
    uid
FROM dis_cdn
WHERE its > (now() - 3600)
ORDER BY its DESC
LIMIT 10

Received exception from server (version 1.1.54378):
Code: 171. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Block structure mismatch in MergingSorted stream: different names of columns:
its UInt32 UInt32(size = 10), name String String(size = 10), uid UInt32 UInt32(size = 10)
its UInt32 UInt32(size = 0), uid UInt32 UInt32(size = 0), name String String(size = 0).

```

The column `name` was new  added by `alter table add coumn name String`.

But `select  name,   uid   from cluster('logs','default', 't_cdn')  where its > now()-3600  order by its desc limit 10;` works fine.

**Comment by jpiper** [comment]
You're not using a distributed table are you? You'd need to run alter on all copies of the table.

i.e.

    alter table X on cluster Y add column Z String

**Comment by sundy-li** [comment]
closed，this problem was caused by the  distribute table create sql，the order of the  column  must be same with local table
