### ISSUE TITLE
Add support for logging to stdout/stderr

### ISSUE THREAD

**Issue by derekperkins** [yandex/ClickHouse#2241]
We are running ClickHouse inside Kubernetes, which prefers all logs be written to stdout and stderr. It would be great to have that as a supported `logger` setting that would just write out logs and not handle any log rotation.

**Comment by proller** [comment]
Remove from your config this strings:
```
<log>/var/log/clickhouse-server/clickhouse-server.log</log>              
<errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
```
And add (to <logger> section)
```
<console>1</console>
```

**Comment by proller** [comment]
1. You can remove <errorlog> <log> from your config.xml and add <console>1</console>
2. https://github.com/yandex/ClickHouse/commit/89b67dd25a19895144adca2f8200558ac6aad6ce with this commit you can define <logger><log/><errorlog/><console>1</console></logger> in your conf.d files

**Comment by proller** [comment]
And simpler redefining logger config keys:
https://github.com/yandex/ClickHouse/commit/89b67dd25a19895144adca2f8200558ac6aad6ce

**Comment by derekperkins** [comment]
That helped some but didn't fully work for me. After applying these logger settings:

    <logger>
        <level>trace</level>
        <console>1</console>
    </logger>

I saw this in my error log:

`2018.04.19 18:20:59.196532 [ 28 ] &lt;Warning&gt; Application: Logging trace to console`

I started to see some error logs in the console output, but it also continued to write some logs (but not all) to `/var/log/clickhouse-server/clickhouse-server.err.log`. These are the only two logs I saw still being output to the error log after making the config change, but it's possible that there are more.

```
2018.04.19 18:30:37.794871 [ 3583 ] &lt;Warning&gt; TCPHandler: Client has not sent any data.
2018.04.19 18:30:40.782907 [ 80 ] &lt;Error&gt; MySQLDictionarySource: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Exception: Connections to all replicas failed: clickhouse@mysql:3306 as user clickhouse, e.what() = Exception
```

It also continued to write to `/var/log/clickhouse-server/clickhouse-server.log` with no obvious difference. Do I need to restart the server to fully apply these logging changes?

**Comment by proller** [comment]
Yes, better to restart server.

**Comment by derekperkins** [comment]
After restarting, logs appear to be only routing to stdout. Thanks for your help!

**Comment by megastef** [comment]
Thank you for the workaround above. I developed a CH log parser with multi line parsing of CH logs, which works also for containers. 

I wonder why these logger settings are not enabled by default in the docker specific configuration: https://github.com/yandex/ClickHouse/blob/master/docker/server/docker_related_config.xml

Is there a plan to enable console logs by default - many logging tools collect logs from container console output.

**Comment by corpix** [comment]
Corresponding to https://clickhouse.tech/docs/en/operations/server-configuration-parameters/settings/ this is not working anymore

**Comment by scraton** [comment]
The following worked for me with ClickHouse v21.7:

```xml
<logger>
    <console>true</console>
    <log remove="remove"/>
    <errorlog remove="remove"/>
</logger>
```

Source: https://github.com/ClickHouse/ClickHouse/blob/b89da7b420ada3eae6659b556c6cc3e2158a69a8/tests/integration/test_config_xml_full/configs/config.d/log_to_console.xml
