### ISSUE TITLE
greatCircleDistance undocumented

### ISSUE THREAD

**Issue by leoluk** [yandex/ClickHouse#2248]
https://github.com/yandex/ClickHouse/blob/master/dbms/src/Functions/FunctionsGeo.h

https://github.com/yandex/ClickHouse/blob/master/dbms/tests/queries/0_stateless/00362_great_circle_distance.sql

**Comment by stavrolia** [comment]
https://clickhouse.yandex/docs/en/query_language/functions/geo/
