### ISSUE TITLE
Problems with clickhouse memory allocator

### ISSUE THREAD

**Issue by artemkamolodets** [yandex/ClickHouse#2269]
Hello. I'm using clickhouse-server (docker container) version: 1.1.54342. 
I've got a problems with query execuition: the queries is failing with error message "DB Exception. Allocator: Cannot allocate memory chunk <some value>."
The option "max_memory_usage" is set to 126GB.
I can see in zabbix, that the container memory usage peak is 80GB. The host have like 100GB free memory (free + available). Also i can see in graphite, that the clickhouse-server memory usage is 60GB max.
Why this thing happens, while there is a lot of free memory in the system. Please help.
p.s. The huge memory pages is disabled (transparent + normal).

**Comment by KochetovNicolai** [comment]
Hello.
It's possible that ClickHouse need to allocate a lot of memory very fast. Or it can be a bug (probably fixed in last versions). Try to update ClickHouse and check that you still get an exception.
There also should be stack trace in log file. Please, attach it if you can. Show the query and table structure if possible.

**Comment by alexey-milovidov** [comment]
You should check your overcommit settings: https://clickhouse.yandex/docs/en/operations/tips/#ram

**Comment by ramazanpolat** [comment]
I'm facing the same problem and overcommit settings seem fine (it is zero).

`max_memory_usage` is 80G and `max_bytes_before_external_group_by` is 40G.

Any idea?

**Comment by den-crane** [comment]
> I'm facing the same problem and overcommit settings seem fine (it is zero).
> 
> `max_memory_usage` is 80G and `max_bytes_before_external_group_by` is 40G.
> 
> Any idea?

@ramazanpolat 
What EXACT error message did you get. What CH version do you use?

**Comment by ramazanpolat** [comment]
@den-crane 
This **was** the message and the CH version **was** `19.17.2`.:
```
Received exception from server (version 19.17.2):
Code: 240. DB::Exception: Received from localhost:9000. DB::ErrnoException. 
DB::ErrnoException: 
Allocator: Cannot mremap memory chunk from 5.00 GiB to 10.00 GiB., 
errno: 14, strerror: Bad address.
```
Server has 40G memory.

Updated CH to `19.17.6.36`. 

Then set `max_memory_usage` to 90G and `max_bytes_before_external_group_by` to 30G.

And now CH server crashes :(
```
:) SET max_memory_usage = 90000000000
Ok.
:) SET max_bytes_before_external_group_by = 30000000000
Ok.
:) SELECT
    ak.*,
    AB_CS1.AB_CALSAY1 AS AB_CALSAY,
    AB_CS1.AB_DONEM_CALSAY1 AS AB_DONEM_CALSAY,
    AB_CS1.AB_ISYERI_CALSAY1 AS AB_ISYERI_CALSAY,
    AB_CS1.AB_ISYERI_DONEM_CALSAY1 AS AB_ISYERI_DONEM_CALSAY,
    PB_CS1.PB_CALSAY1 AS PB_CALSAY,
    PB_CS1.PB_DONEM_CALSAY1 AS PB_DONEM_CALSAY,
    PB_CS1.PB_ISYERI_CALSAY1 AS PB_ISYERI_CALSAY,
    PB_CS1.PB_ISYERI_DONEM_CALSAY1 AS PB_ISYERI_DONEM_CALSAY
FROM AYS_KIMLIK AS ak
LEFT JOIN AB_CS1 ON (ak.AYS_SICIL_NO, ak.AYS_YIL_DONEM_SIRA, ak.AYS_ISYERI_NO) = (AB_CS1.SICIL_NO1, AB_CS1.YIL_DONEM_SIRA1, AB_CS1.ISYERI_NO1)
LEFT JOIN PB_CS1 ON (ak.AYS_SICIL_NO, ak.AYS_YIL_DONEM_SIRA, ak.AYS_ISYERI_NO) = (PB_CS1.SICIL_NO1, PB_CS1.YIL_DONEM_SIRA1, PB_CS1.ISYERI_NO1)
LIMIT 100

↘ Progress: 273.08 million rows, 15.29 GB (1.66 million rows/s., 93.05 MB/s.) ███████████████████████████████████████████████████████████████████████████████▋                             73%
Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000

Connecting to database prod at localhost:9000 as user default.
Code: 210. DB::NetException: Connection refused (localhost:9000)

root@myserver:~#
```

Last lines in server process output:
```
2020.01.09 00:42:36.078586 [ 18 ] {} <Trace> system.trace_log: Renaming temporary part tmp_merge_202001_4775_7228_1732 to 202001_4775_7228_1732.
2020.01.09 00:42:36.078818 [ 18 ] {} <Trace> system.trace_log (MergerMutator): Merged 2 parts: from 202001_4775_7227_1731 to 202001_7228_7228_0
2020.01.09 00:42:36.100944 [ 94 ] {13a5a20f-fcbc-4257-83d4-49a40f3f0b48} <Debug> MemoryTracker: Current memory usage: 58.00 GiB.

root@myserver:~#
```

**Comment by den-crane** [comment]
@ramazanpolat It probably because of JOIN (LEFT JOIN AB_CS1 ON ... LEFT JOIN PB_CS1)
CH JOIN is a HashJoin it places `right` tables  AB_CS1 and PB_CS1 into memory into hash-tables at whole. There is no settings to change this behavior. 

How many rows in AB_CS1 and PB_CS1 ?

**Comment by ramazanpolat** [comment]
@den-crane The size of tables are 210M and 170M.

After setting `partial_merge_join = 1`, it WORKED! 👍 

Do you think that I should open an issue for the crash?

Because being able to bring down whole CH server with an SQL looks like a bug that needs to be addressed.

**Comment by artemkamolodets** [comment]
btw in my case the problem was:
i'm using clickhouse in docker container and there are special mount point /shm which is 64mb in size by default. This value is too small. Increasing it resolved the issue.
p.s. my english is best, i know :)

**Comment by den-crane** [comment]
> Do you think that I should open an issue for the crash?

I would not. I believe OOM crashes are normal behavior.
