### ISSUE TITLE
Issues while building Clickhouse on Debian

### ISSUE THREAD

**Issue by elukey** [yandex/ClickHouse#228]
Hi ClickHouse developers,

I tried to follow the build.md documentation to build a .deb for Debian using pdebuild, and I took me a while to make sure that the control's build dependencies were set correctly. Would it make sense to include the following? 

```
--- a/debian/control.in
+++ b/debian/control.in
@@ -1,6 +1,10 @@
 Source: clickhouse
 Priority: optional
 Maintainer: Alexey Milovidov <milovidov@yandex-team.ru>
-Build-Depends: debhelper (>= 5)
-Standards-Version: 3.8.0
+Build-Depends: debhelper (>= 5), cmake, gcc-6, g++-6, libboost-dev,
+               libicu-dev, libreadline-dev, libmysqlclient-dev, unixodbc-dev,
+               libboost-thread-dev, libboost-program-options-dev,
+               libboost-system-dev, libboost-regex-dev, libboost-filesystem-dev,
+               libglib2.0-dev, libltdl-dev, libssl-dev
+Standards-Version: 3.9.8
 Section: libs
```

Other misc requests:
- It would be really helpful if the debian/rules file was translated to English.
- It would be really helpful if the release script had an option to just generate debian files (like control and rules) leaving the build part to the user (for example, say I want to use pdebuild rather than debuild).

Thanks a lot!

Luca

**Comment by alexey-milovidov** [comment]
This is reasonable.

But if user has compiled some dependencies from sources and have installed to `/usr/local` without using debian packages (example: gcc-6), then build will refuse to work.
Is it worth to specify build dependencies, considering that use case?

**Comment by elukey** [comment]
Hi Alexey,

thanks for the response! I got your point and I agree that this could impact other use cases different than mine, maybe it could be enough to mention it in build.md for people trying to build the deb package by themselves? 

The other thing that I would add (for newbies like me) is a suggestion about what git tag use to build the "latest stable". For example, I tried to build two versions, corresponding to the tags "54010" and "v1.1.54083-stable", but in the end of the latter build I get issues like:

1) Linking problems (might be related to my settings, but it might also be Cmake related?)
```
[100%] Building CXX object dbms/src/Server/CMakeFiles/clickhouse.dir/main.cpp.o
[100%] Linking CXX executable clickhouse
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libreadline.a(readline.o): relocation R_X86_64_32 against symbol `rl_get_previous_history' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libreadline.a(vi_mode.o): relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libreadline.a(funmap.o): relocation R_X86_64_32 against symbol `rl_abort' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libreadline.a(keymaps.o): relocation R_X86_64_32S against symbol `rl_insert' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libreadline.a(search.o): relocation R_X86_64_32S against symbol `rl_history_substr_search_backward' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libreadline.a(rltty.o): relocation R_X86_64_32S against symbol `rl_vi_unix_word_rubout' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libreadline.a(complete.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
[...]
```

2) Debian rule problems, like dh_install not finding the debian/tmp directory and failing.

The above ones do not affect version 54010, so I am wondering if I am missing something trivial or if the docs are missing some indications.

Thanks a lot for the support!

Luca

**Comment by elukey** [comment]
I also noticed one thing using Lintian:

```
E: clickhouse source: license-problem-json-evil contrib/libpoco/doc/Acknowledgements.html
E: clickhouse source: license-problem-json-evil contrib/libpoco/doc/90100-Acknowledgements.page
E: clickhouse source: license-problem-json-evil contrib/libpoco/JSON/include/Poco/JSON/Parser.h
```

https://wiki.debian.org/qa.debian.org/jsonevil

This prevents Clickhouse to be included in Debian distros due to non free licenses.

**Comment by alexey-milovidov** [comment]
1. In fact we don't use Poco/JSON, so I could just remove it from sources.

2. About stable tag. Latest stable tag is the right one.
Later we will also add two branches for convenience: stable and testing, so you could just checkout stable branch.

3. About linking with readline. Maybe your system is trying to link clickhouse with PIC (position independent code), for unknown reason. You could 
- change `libreadline.a` to `readline` or `libreadline.so` in `dbms/src/Client/CMakeLists.txt`;
Plese tell me, on what system you encounter this issue?

4. Why don't add gcc-6 to build depends? Because gcc 6 is still rarely available in packages. Users could install it from PPA or build from sources. Second option is also valid choice. 
Probably later we will move to clang 4, when it will be released (we have done benchmarks and in results, clang 4 is generating as efficient code as gcc 6, though clang 3.9 is slower). I doubt it will be easy to find packages for clang 4.

**Comment by elukey** [comment]
Thanks a lot, sorry for the delay :)

1. If you could remove it and release a stable version it would be massive! 
2. For some reason I didn't see the stable branch, my bad :)
3. I followed up with your suggestions and I was able to build changing the following:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 863b7f0..90c43e6 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -182,7 +182,7 @@ find_library (BOOST_THREAD_LIB libboost_thread.a HINTS ${BOOST_HINTS})

 # 4. ltdl
 set (LTDL_HINTS "/usr/local/opt/libtool/lib")
-find_library (LTDL_LIB libltdl.a HINTS ${LTDL_HINTS})
+find_library (LTDL_LIB libltdl.so HINTS ${LTDL_HINTS})

 # Directory for Yandex specific files
 SET(CLICKHOUSE_PRIVATE_DIR ${ClickHouse_SOURCE_DIR}/private/)
diff --git a/contrib/libpoco/Net/CMakeLists.txt b/contrib/libpoco/Net/CMakeLists.txt
index de9e618..f58feff 100644
--- a/contrib/libpoco/Net/CMakeLists.txt
+++ b/contrib/libpoco/Net/CMakeLists.txt
@@ -17,7 +17,7 @@ if(WIN32)
         set(SYSLIBS ${SYSLIBS} "ws2_32.lib" "iphlpapi.lib")
     endif()
 elseif(NOT APPLE)
-    set(SYSLIBS ${SYSLIBS} "libanl.a")
+    set(SYSLIBS ${SYSLIBS} "libanl.so")
 endif(WIN32)

 add_library( "${LIBNAME}" ${LIB_MODE} ${SRCS} )
diff --git a/contrib/libpoco/cmake/FindODBC.cmake b/contrib/libpoco/cmake/FindODBC.cmake
index 67cb5d4..0292c7d 100644
--- a/contrib/libpoco/cmake/FindODBC.cmake
+++ b/contrib/libpoco/cmake/FindODBC.cmake
@@ -29,7 +29,7 @@ find_path(ODBC_INCLUDE_DIRECTORIES
 )

 find_library(ODBC_LIBRARIES
-       NAMES libiodbc.a iodbc libodbc.a odbc odbcinst odbc32
+       NAMES iodbc libiodbc.so odbc odbcinst odbc32
        HINTS
        /usr/lib
        /usr/lib/odbc
diff --git a/dbms/src/Client/CMakeLists.txt b/dbms/src/Client/CMakeLists.txt
index a74c261..24311fe 100644
--- a/dbms/src/Client/CMakeLists.txt
+++ b/dbms/src/Client/CMakeLists.txt
@@ -1,5 +1,5 @@
 find_library(READLINE_LIB
-       NAMES libreadline.a libreadline.so
+       NAMES readline libreadline.so
        HINTS "/usr/local/opt/readline/lib")

 find_library(LIBEDIT_LIB
```
I am trying to build Clickhouse on Debian Sid (using the chroot provided by pdebuild) and from what I can read, .a libraries are usually compiled without -fPIC, meanwhile .so are compiled with it. I am not a great expert but it makes sense in my opinion, but I haven't dig a lot into why the Cmake tries to find either a .a or a .so version of a lib.

4. I would still provide a complete Build-Depends and then document how to change it to allow other use cases like people building from sources by themselves, but it is also fine the other way around if documented :)

**Comment by alexey-milovidov** [comment]
> If you could remove it and release a stable version it would be massive!

Already removed. We have new stable version today, I just published it.

> For some reason I didn't see the stable branch, my bad :)

We have added stable and testing branched just few days ago.

> I followed up with your suggestions and I was able to build the stable 54083 version changing the following

We have added CMake option `USE_STATIC_LIBRARIES` that may be turned off.
It is in master, not yet in stable branch.

I still cannot guess, why code is not linking with static libraries on your system. Maybe I will experiment on VM by myself, if I will have time.

> I would still provide a complete Build-Depends and then document how to change it to allow other use cases like people building from sources by themselves, but it is also fine the other way around if documented :)

Ok.

> I think that that dh_install assumes the presence of a debian/tmp dir, but I can't find it in the sources..

I expect, `debian/tmp` directory should be created here:
https://github.com/yandex/ClickHouse/blob/master/debian/rules#L54
BTW, I am not expert in debian package build system.

**Comment by elukey** [comment]
> Already removed. We have new stable version today, I just published it.

Tested it, lintian does not complain anymore, nice!

> We have added CMake option USE_STATIC_LIBRARIES that may be turned off.

I used it (USE_STATIC_LIBRARIES=0) for v1.1.54112-stable and it removes all the linking issues except the following (that I had to patch manually):

```
--- a/contrib/libpoco/Net/CMakeLists.txt
+++ b/contrib/libpoco/Net/CMakeLists.txt
@@ -17,7 +17,7 @@ if(WIN32)
         set(SYSLIBS ${SYSLIBS} "ws2_32.lib" "iphlpapi.lib")
     endif()
 elseif(NOT APPLE)
-    set(SYSLIBS ${SYSLIBS} "libanl.a")
+    set(SYSLIBS ${SYSLIBS} "libanl.so")
 endif(WIN32)
```

> I still cannot guess, why code is not linking with static libraries on your system.

As far as I know in debian the static .a libraries are not built using -fPIC..

> I expect, debian/tmp directory should be created here:

I am not an expert too, but I'll try to spend some time to debug it :)

Thanks!

**Comment by elukey** [comment]
I was able to figure out the issue, I was missing `DAEMONS=clickhouse-server` before the git-buildpackage command. Without it, several files under debian/tmp/etc were not created triggering the build.

So the only outstanding issue is the remaining linking problem reported above!

**Comment by alexey-milovidov** [comment]
We should use find_*.cmake scripts for `libanl` library, that is linked inside Poco.

**Comment by elukey** [comment]
Still very far from being able to build correctly on Debian:

```
ldd ./usr/bin/clickhouse-server
./usr/bin/clickhouse-server: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.23' not found (required by ./usr/bin/clickhouse-server)
	linux-vdso.so.1 (0x00007ffc69583000)
	libreadline.so.7 => not found
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007ff32f1ec000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007ff32eedc000)
	libicui18n.so.57 => not found
	libicuuc.so.57 => not found
	libicudata.so.57 => not found
	libmysqlclient.so.20 => not found
	libssl.so.1.1 => not found
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ff32ecbf000)
	libcrypto.so.1.1 => not found
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff32eaa2000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ff32e899000)
	libanl.so.1 => /lib/x86_64-linux-gnu/libanl.so.1 (0x00007ff32e695000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff32e491000)
	libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007ff32e286000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff32df85000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff32dbda000)
	/lib64/ld-linux-x86-64.so.2 (0x00005588236ff000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007ff32d96b000)
```

The above is the result after using USE_STATIC_LIBRARIES=1, I didn't think about the runtime's repercussions. I tried to play with the `-fPIC` flag in the codebase but didn't manage to make a build completing correctly. The error is always the same:

`/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libreadline.a(readline.o): relocation R_X86_64_32 against symbol `rl_get_previous_history' can not be used when making a shared object; recompile with -fPIC`

Plus others of course.. How do you usually build your releases and on which platform? Is there any special procedure that you follow other than the one outlined in the build.md doc?

**Comment by elukey** [comment]
Some info: I do use the `release` script but I removed the debuild part since I am using git-pbuilder (Debian sid and latest git stable tag).

**Comment by elukey** [comment]
I also checked the /etc files produced by the build and I have some suggestions:

1) etc/cron.d/clickhouse-server
```
#*/10 * * * * root /etc/init.d/clickhouse-server condstart 1>/dev/null 2>&1
```
This functionality should not be present since admins usually prefer to manage them in other ways (for example leaving the job to systemd). The cron is disabled but it is not super great the fact that it will be installed by default on the target system.

2) etc/init.d/clickhouse-server

I would not let this script to manage file systems permissions with hardcoded values:

```
USER=metrika
GROUP=metrika
[..]
		chown -R $USER:$GROUP $LOGDIR
		chown -R $USER:$GROUP $PIDDIR
		chown -R $USER:$GROUP $SYSCONFDIR
				su -l $USER -s $SHELL -c "flock -u 9; exec -a $(generate_program_name $i) \"$BINDIR/$PROGRAM\" --daemon --pid-file=\"$(generate_pid_name $i)\" --config-file=\"$CNFFILE\" $(specific_log_file_for_each_process $i)
[..]
```
And I would remove the following too:

```
enable_cron()
{
	sed -i 's/^#*//' "$CRONFILE"
}

disable_cron()
{
	sed -i 's/^#*/#/' "$CRONFILE"
}

is_cron_disabled()
{
	[[ `grep -E "^#.*" $CRONFILE` == `cat $CRONFILE` ]];
}
```
And all the other references to the cron scripts mentioned in 1). 

Thanks!

**Comment by alexey-milovidov** [comment]
About cron and init script.
<[admins usually prefer to manage them in other ways]>
We still must have some reasonable default.
How we could make better packages, but leave this cron job as default or as a fallback solution?

**Comment by elukey** [comment]
> How we could make better packages, but leave this cron job as default or as a fallback solution?

I would personally leave the choice to the end user/admin. For example, systemd might be used to restart the service on failure or maybe an admin might not want to remember about the 10 minutes cron during maintenance (so stop - update - start for example).

I would also avoid changing permissions in the init.d file, but rather use something like `postinst` (so do it once while installing rather than all the times that init.d is executed).

**Comment by elukey** [comment]
Gentle ping for the build :)

**Comment by proller** [comment]
some fixes merged https://github.com/yandex/ClickHouse/pull/316/
now in debian jessie works:  ```debuild -e USE_STATIC_LIBRARIES=0```

**Comment by elukey** [comment]
@proller: in my use case USE_STATIC_LIBRARIES=0 was already working, and I was happy to have shared libraries rather than everything on one binary. The main issue with this setting is that to satisfy dependencies like gcc-6 you'd need to build in Sid for example, precluding the possibility to use the deb created in Jessie for obvious reasons (our production fleet is all Debian stable). The USE_STATIC_LIBRARIES=1 seems the only viable option, but there is still the problem with relocable code (-fPIC). Can you confirm that you reproduced the problem on your environment?

**Comment by proller** [comment]
you can use gcc5+ for building

**Comment by elukey** [comment]
@proller the "-no-pie" flag seems to have fixed the fPIC issue, I have just built the latest master commit and everything went fine. One little thing left: if I do use ldd to check runtime dependencies I can see the following error on Debian Jessie:

```
ldd ./usr/bin/clickhouse-server
./usr/bin/clickhouse-server: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.23' not found (required by ./usr/bin/clickhouse-server)
```
Reading through the glibc_compatibility files it seems that I should be able to use older versions of libc..

I am using the GLIBC_COMPATIBILITY flag while building, is there anything else that I need to specify?

**Comment by proller** [comment]
Did you try build without GLIBC_COMPATIBILITY ?
GLIBC_COMPATIBILITY needed if you will run pachage on systems older than jessie

**Comment by elukey** [comment]
@proller yes I tried but same issue, GLIBC_2.23 required. I might be missing something..

**Comment by elukey** [comment]
Whenever you have time, there are also [previous comments](https://github.com/yandex/ClickHouse/issues/228#issuecomment-268243199) that in my opinion would need some more discussion (cronjobs and permissions chowns hardcoded in init files).

**Comment by proller** [comment]
>  I suspect that this is due to the fact that I am building on Debian Sid (to satisfy all the dependencies requested).
You build on sid and then run on jessie? its bad.
Better find way to install gcc5 or gcc6 on jessie ( https://www.google.ru/webhp?#q=debian%20jessie%20gcc%205 )

>On which platform do you build the debs that you release? What is the correct procedure?
 We use ubuntu ( trusty+ ) with available gcc5+ from apt

>Whenever you have time, there are also previous comments that in my opinion would need some more discussion (cronjobs and permissions chowns hardcoded in init files).
cron edit will be removed, rc.d script will be simplified.
clickhouse default  user will be changed from 'metrika' to 'clickhouse'

Also here https://github.com/jbfavre/ClickHouse/tree/debian work in progress on true debian package

**Comment by elukey** [comment]
> You build on sid and then run on jessie? its bad.
Yep you are completely right, I started building on Sid to satisfy all the dependencies, without realizing that I'd have an issue with Glibc (got also fooled by the GLIB_COMPATIBILITY flag). As stated above, I'll follow what you mentioned trying to build and use gcc5 on Jessie. Thanks for the links and the suggestions.

> cron edit will be removed, rc.d script will be simplified.
> clickhouse default user will be changed from 'metrika' to 'clickhouse'
Also please make sure to remove unnecessary chown/chmod in init files.

> Also here https://github.com/jbfavre/ClickHouse/tree/debian work in progress on true debian package.
Very nice, just followed the fork, hope that it will get merged to Clickhouse soon.

**Comment by proller** [comment]
Some changes:
https://github.com/yandex/ClickHouse/commit/c51801d7762bda374757cf61a062b6c6542762b5
Now you can adjust  init script by creating /etc/default/clickhouse:

# to skip old path checks:
CLICKHOUSE_DATADIR_OLD=""
# to not touch cron:
CLICKHOUSE_CRONFILE=""
# change use/group:
CLICKHOUSE_USER=superman
CLICKHOUSE_GROUP=pupermans
