### ISSUE TITLE
What is new param <secure>1</secure> in Shard/Replica configuration?

### ISSUE THREAD

**Issue by jonatasfreitasv** [yandex/ClickHouse#2286]

**Comment by filimonov** [comment]
It allows to use ssl encryption for distributed tables. See 
https://github.com/yandex/ClickHouse/pull/2065

Sp if you prefer to have traffic interchange between server with Distributed table and underlying servers to be encrypted you need to enable 
```xml
<tcp_port_secure>9440</tcp_port_secure>
```

and turn on `<secure>1</secure>` in cluster config.

**Comment by jonatasfreitasv** [comment]
wow, nice! thx a lot!
