### ISSUE TITLE
Is security to update ClickHouse server version 1.1.54362 to 1.1.54380 ?

### ISSUE THREAD

**Issue by jonatasfreitasv** [yandex/ClickHouse#2287]
And what is the best way to make this, in production cluster.

**Comment by filimonov** [comment]
In most cases simple 'update package - restart clickhouse' if enough.
But it's always safer to check it on some staging environment, and check the changelog for information about compatibility changes.

**Comment by jonatasfreitasv** [comment]
Thx a lot!!
