### ISSUE TITLE
Where is CHANGELOG for version 1.1.54380 ?

### ISSUE THREAD

**Issue by jonatasfreitasv** [yandex/ClickHouse#2288]

**Comment by filimonov** [comment]
Probably Yandex developers are on ClickHouse Meetup in Sunnyvale & San Francisco. 

For now you can check that: https://github.com/yandex/ClickHouse/compare/v1.1.54378-stable...v1.1.54380-stable

**Comment by alex-zaitsev** [comment]
Here is translation from Russian:

ClickHouse release 1.1.54380, 2018-04-21
New features:
* Added new table function file(path, format, structure). Example:

ln -s /dev/urandom /var/lib/clickhouse/user_files/random clickhouse-client -q "SELECT * FROM file('random', 'RowBinary', 'd UInt8') LIMIT 10".

Improvements:
* Added an option to surround subqueries with brackets () for readability. 
Example: (SELECT 1) UNION ALL (SELECT 1).
* Simple SELECT queries from  system.processes are not considered when checking for max_concurrent_queries.
* Option to turn off logging removing <log/> or <errorlog/> in server configuration.

Bug fixes:
* Removed support for expressions like:  (a, b) IN (SELECT (a, b)), that resulted in problems with WHERE implementation. Instead, the expression should be used as:  (a, b) IN (SELECT a, b)
* Fixed a bug with IN for MATERIALIZED VIEW
* Fixed incorrect index behaviour when partitioning column is used for filtering like: partition_key_column IN (...).
* Fixed a bug when OPTIMIZE could not be run on leader replica after renaming the table.
* Fixed authorisation problems when OPTIMIZE or ALTER were executed on non-leader replica
* Fixed a bug when 'KILL QUERY' could not finish sometimes.
* Fixed a bug in ZooKeeper client library, that could happen if chroot has been used in configuration. The problem could lead to lost watches, stopping distributed DDL queries queue and general replication slowdown.

**Comment by jonatasfreitasv** [comment]
Thx!
