### ISSUE TITLE
Support password_sha256_hex in external dictionaries

### ISSUE THREAD

**Issue by derekperkins** [yandex/ClickHouse#2290]
I'm using `<password_sha256_hex>` to store my user passwords in `users.xml`. The problem with dictionaries is that I am storing a MySQL password in plaintext in my dictionary file. I'd like to at least be able to store that encrypted, the same as user passwords.

cc @alex-zaitsev

**Comment by den-crane** [comment]
sha256 is a hash function, there is no way to restore original password from hash.
But to connect to mysql server one need to have original password.
So there is no way to fulfill your request.

In case of encryption you CH needs to have a password to decrypt and it has no sense to put an encrypted mysql password and plain text password to decrypt the encrypted mysql password.

Just set rw-rw--- rights on your dictionary.xml

**Comment by derekperkins** [comment]
@den-crane that makes sense. My main concern is that I am checking my clickhouse xml files into git, where I'd prefer to not have passwords. What about allowing for environment variables to be referenced inside config files? That would solve a number of issues with macros and other replacements.

**Comment by filimonov** [comment]
You can store connection credentials for dictionaries in substitutions file
`/etc/metrika.xml' and include them like `<password
incl="section_name_from_substitutions_file' />`.

Or even extract the whole `<source>` section into substitutions file.

>

**Comment by derekperkins** [comment]
This should be solved when #1616 makes it into a public release.

**Comment by filimonov** [comment]
Can we close that?
