### ISSUE TITLE
Can not Connect ClickHouse via clickhouse-client after change listen_host

### ISSUE THREAD

**Issue by xiaomaijiang** [yandex/ClickHouse#2299]
ClickHouse Version:1.1.54380

i change the `/etc/clickhouse-server/config.xml` to set the `listen_host` to `0.0.0.0.` and restart clickhouse 
```
tcp        0      0 0.0.0.0:9000            0.0.0.0:*               LISTEN      16545/clickhouse-se
```

and then ,i want to use `clickhouse-client -h 10.128.210.150` to enter the clickhouse ,but i got error 
```
ClickHouse client version 1.1.54380.
Connecting to 10.128.210.150:9000.
Code: 102. DB::NetException: Unexpected packet from server 10.128.210.150:9000 (expected Hello or Exception, got Unknown packet)

```

**Comment by sundy-li** [comment]
Try set the listen_host to `<listen_host>::</listen_host>` , it could accept connections both with IPv4 and IPv6

**Comment by proller** [comment]
Code: 210. DB::NetException: Connection refused: (localhost:9000, ::1)
- your client tries to use ipv6.
change 
    `<listen_host>127.0.0.1</listen_host>`
to
    `<listen_host>::1</listen_host>`

or you can configure default host for client:
/etc/clickhouse-client/config.xml:
`<host>127.0.0.1</host>`

**Comment by alexey-milovidov** [comment]
You can run
```
clickhouse-client --host=127.0.0.1
```
instead of
```
clickhouse-client
```

**Comment by TommyLemon** [comment]
I tried all advices above but none of them works

**Comment by pavelsc** [comment]
> I tried all advices above but none of them works
> 
> ```shell
> clickhouse-client --host=127.0.0.1
> ClickHouse client version 21.7.5.29 (official build).
> Connecting to 127.0.0.1:9000 as user default.
> Code: 210. DB::NetException: Connection refused (127.0.0.1:9000)
> ```

Make sure `/etc/clickhouse-server/config.xml` and `/etc/clickhouse-server/users.d/default-password.xml` does not contain the same user _default_ with different password options. You can simply delete the last one file

**Comment by akbarali1** [comment]
I tried all advices above but none of them works

```
clickhouse-client --host=127.0.0.1:8123
ClickHouse client version 23.3.1.755 (official build).
Cannot resolve host (127.0.0.1:8123), error 0: Host not found.
Code: 198. DB::Exception: Not found address of host: 127.0.0.1:8123. (DNS_ERROR)
```

**Comment by alexey-milovidov** [comment]
@akbarali1

`127.0.0.1:8123` is not a hostname because this string contains a port number.
The host should be `127.0.0.1`, without a port number.
