### ISSUE TITLE
Translate comments from Russian to English

### ISSUE THREAD

**Issue by alexandear** [yandex/ClickHouse#23]
There are a lot of comments written in Russian that should be in English to understand other developers.

**Comment by DieHertz** [comment]
You are welcome to research the code, translate commentaries and submit a pull request :-)

**Comment by alexey-milovidov** [comment]
DieHertz, you are welcome too.

To translate all comments is a difficult task: about one month of work (really longer).
Today we have alternatives: to get done some important tasks (for example, compatibility of SQL dialect for JOINs) or start to translate comments.

Translation of comments is important task, but if we cannot translate all coments, lets translate one-by-one. You point to most important comment, and we translate it.

**Comment by halilduygulu** [comment]
for future readers, google translate can translate them to understandable English, i use for specific classes which i can not find in documentation.

**Comment by alexey-milovidov** [comment]
Now we have translated 50.6% of all comments :)

**Comment by cce** [comment]
This seems to be resolved by https://github.com/yandex/ClickHouse/pull/787

**Comment by alexey-milovidov** [comment]
Now we have 100% translated in `dbms` directory. Only few files in `libs` remains.
In total we have translated 97.1% of comments.

**Comment by silviucpp** [comment]
Maybe this task should be closed
