### ISSUE TITLE
FR: Slow queries log

### ISSUE THREAD

**Issue by f1yegor** [yandex/ClickHouse#230]
Feature request: In many databases there is "slow queries log" functionality. All information about query timing could be written to system table to keep track of all/exceeding-threshold queries.
It could relate to Quotas functionality https://clickhouse.yandex/reference_en.html#Quotas.

**Comment by alexey-milovidov** [comment]
We have "query log".

To enable query log, set log_queries to 1.
To enable for all users, write <log_queries>1</log_queries> in /users/default element in users.xml file.
Query log is located in system.query_log table.

Each query is logged up to two times, on following events:
- begin of query execution (type = 1);
- end of query execution (type = 2);
- exception before begin of query execution (type = 3);
- exception during query execution (type = 4);

To select slow queries, use condition on `query_duration_ms` column.

Query log has almost zero impact on performance.
Usually, query log is also quite compact.
We have query log enabled on production clusters.

**Comment by f1yegor** [comment]
By trial and error I think the right config should be

users.xml
```
<?xml version="1.0"?>
<yandex>
        <profiles>
                <default>
                        <log_queries>1</log_queries>
                </default>
        </profiles>
        <users>
         <default>
           <profile>default</profile>
        </default>
      </users>
</yandex>
```

Only with this I can see 
```
<Trace> SystemLog (system.query_log): Flushing query log
```
and actual records in `system.query_log`

**Comment by alexey-milovidov** [comment]
That's fine.
