### ISSUE TITLE
build failure with submodule issue

### ISSUE THREAD

**Issue by chenxing-xc** [yandex/ClickHouse#2300]
My develop branch is based on stable 1.1.54370,  and encounter the following error:
(Note that this error raise while "git submodule update --init --recursive")
19:42:03 Submodule path 'contrib/poco': checked out '8238852d7ab2a4abdf87adff233b3b83686f4fe4'
19:42:03 Submodule 'openssl' (https://github.com/pocoproject/openssl) registered for path 'contrib/poco/openssl'
19:42:14 error: no such remote ref 26b1673caad94a702b6d694f48f917a283b30777
19:42:14 Fetched in submodule path 'contrib/poco/openssl', but it did not contain 26b1673caad94a702b6d694f48f917a283b30777. Direct fetching of that commit failed.

could anyone help this problem?

**Comment by chenxing-xc** [comment]
I tried to simplified this problem as below, here is the reproduce:
chenxing.xc@XX:~$ git clone https://github.com/ClickHouse-Extras/poco poco3
Cloning into 'poco3'...
remote: Counting objects: 110401, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 110401 (delta 0), reused 0 (delta 0), pack-reused 110393
Receiving objects: 100% (110401/110401), 138.40 MiB | 9.23 MiB/s, done.
Resolving deltas: 100% (89055/89055), done.
chenxing.xc@XX:~$ cd poco3/
chenxing.xc@XX:~/poco3$ git submodule update --init --recursive
Submodule 'openssl' (https://github.com/pocoproject/openssl) registered for path 'openssl'
Cloning into '/home/chenxing.xc/poco3/openssl'...
error: no such remote ref af3dfc6ca786061640f55618b022aa4a62dffb2e
Fetched in submodule path 'openssl', but it did not contain af3dfc6ca786061640f55618b022aa4a62dffb2e. Direct fetching of that commit failed.
chenxing.xc@n10-187-053:~/poco3$

**Comment by proller** [comment]
https://github.com/pocoproject/poco/issues/2290

but in ClickHouse-Extras/poco this submodule was removed.
https://github.com/ClickHouse-Extras/poco/commit/879d51427a74c1de52fc38160c070f02ae11cb4d

so you can use latest stable clickhouse tag without this issue.
