### ISSUE TITLE
Updating ClickHouse version

### ISSUE THREAD

**Issue by vladis1650** [yandex/ClickHouse#2302]
I'm looking for tools to update the version. 
Tell me there is an update instruction?
If not - then at least the commands for the update.

**Comment by jonatasfreitasv** [comment]
yum update clickhouse-*
apt update clickhouse-*

**Comment by vladis1650** [comment]
In response, we get that the update function has no arguments
`root@s2604:~# apt update clickhouse-1.1.54378
E: The update command takes no arguments`

**Comment by jonatasfreitasv** [comment]
apt-get install --only-upgrade clickhouse-* try this

**Comment by meshpaul** [comment]
Ok
