### ISSUE TITLE
Internal dictionaries - (optionally) change the layout to hashed?

### ISSUE THREAD

**Issue by filimonov** [yandex/ClickHouse#2304]
When trying to use [geonames](http://www.geonames.org/) database as a source of 'internal' dictionaries, found that internal dicts are stored as a regular array (`flat` layout). In case of geonames database (which contain not only citys/regions/countries - but a lot of other geo objects) - that is far from optimal, as ids are very big and rows count (if you filter only citys and "higher") is relatively small. 

```
:) select max(geoname_id),count() from geoip2_city_locations_en;
┌─max(geoname_id)─┬─count()─┐
│        11838964 │  143236 │
└─────────────────┴─────────┘
```

May be it can be optionated to use `hashed` as layout?  Of course it's very easy to workaround with custom external dicts instead of `internal` dicts. But may be it would be better to have that nice syntax avaliable for general use?

**Comment by alexey-milovidov** [comment]
Embedded dictionaries implementation is totally determined by initial Yandex.Metrica use case. We are not going to extend embedded dictionaries. Better to improve usability of external dictionaries instead. Even Yandex.Metrica is using external dictionaries for all new use cases. Some embedded dictionaries (`OS` and `SE`) are considered obsolete and will be removed.
