### ISSUE TITLE
Add system.merge_log table

### ISSUE THREAD

**Issue by bocharov** [yandex/ClickHouse#2311]
It would be nice to have a table `system.merge_log` similar to `system.query_log` in order to track all merges ever happened. Right now there is only `system.merges` table, which only shows current state of merge queue, and it doesn't provide good insights for analysis, especially for long term analysis and cluster resource usage optimization.

New table `system.merge_log` would have similar columns as `system.merges` like:
- database
- table
- num_parts
- source_part_names
- result_part_name
- total_size_bytes_compressed
- total_size_marks
- bytes_read_uncompressed
- bytes_written_uncompressed
- rows_written
- memory_usage
- thread_number

But additionally it should have the following columns:
- event_date
- event_time
- merge_start_time
- merge_duration_ms
- files_open_for_read?
- files_open_for_write?

cc @dqminh, @vavrusa, @bobrik

**Comment by alexey-milovidov** [comment]
We already have it!
Look at:

```
    <!-- Uncomment if use part_log
    <part_log>
        <database>system</database>
        <table>part_log</table>

        <flush_interval_milliseconds>7500</flush_interval_milliseconds>
    </part_log>
    -->
```

in config.xml.

If you enable it, the table `system.part_log` will contain log about all part changes ever happened: added parts, merges, parts fetched over network, deleted parts.
