### ISSUE TITLE
Method dropPartition is not supported by storage MaterializedView

### ISSUE THREAD

**Issue by astudnev** [yandex/ClickHouse#2320]
ClickHouse server version 1.1.54342

DROP PARTITION works on table:

:) alter table production.transfers drop partition '197001'

ALTER TABLE production.transfers
DROP PARTITION '197001'

Ok.

0 rows in set. Elapsed: 0.000 sec. 

But does not work on MV associated with this table:

:) alter table production.transfers_currency drop partition '197001'

ALTER TABLE production.transfers_currency
DROP PARTITION '197001'

Received exception from server (version 1.1.54342):
Code: 48. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Method dropPartition is not supported by storage MaterializedView. 

0 rows in set. Elapsed: 0.019 sec. 

Is it expected that eventually MV will come in sync with the table ( it still does not ), or i should use another method to remove partition data from MV's ?

**Comment by filimonov** [comment]
Each materialized view create underlying table with .inner. suffix to store the data. Try drop partition from that underlying table.

**Comment by astudnev** [comment]
Thank you, it works

**Comment by ztlpn** [comment]
Support for applying ALTER PARTITION commands directly to materialized views was added in 1.1.54380
