### ISSUE TITLE
Error: INTO OUTFILE is not allowed

### ISSUE THREAD

**Issue by vixa2012** [yandex/ClickHouse#2326]
Hello dier support.
When I am doing some query, I am receiving Error: INTO OUTFILE is not allowed

`echo "SELECT * from test.\`stats\` where date = '2018-05-04' INTO OUTFILE '/var/lib/clickhouse/user_files/1525769878920.csv'" | curl 'http://admin:123456@localhost:8123/' -d @-`

How I can set parameter allow_into_outfile in config file?

**Comment by ztlpn** [comment]
As stated in [the docs](https://clickhouse.yandex/docs/en/query_language/queries/#into-outfile-clause), the output file is created on the client side. It is pretty hard to do via the HTTP interface :) So INTO OUTFILE is disabled in this case. You can use `clickhouse-client` for that.

**Comment by vixa2012** [comment]
I made it via the shell

`ssh user@192.198.0.1 /bin/bash << EOF
    clickhouse-client --user=admin --password=111111 --query="SELECT * FROM test.\"stats\" AS t WHERE date = '2018-04-07'  INTO OUTFILE '/user/reports/1525777158845.csv' FORMAT CSVWithNames"
EOF`

My nodejs solution
`
function clientExec(sql) {
    return new Promise((resolve, reject) => {
        const command = config.useSSH ? sshExec(sql) : callClient(sql);
        exec(command, (error, stdout, stderr) => {
            if (error) return reject(error);
            if (stderr) return reject(stderr);
            resolve(stdout);
        });
    });
}
function callClient(sql) {
    return `clickhouse-client --user=user --password=111111 --query="${sql}"`;
}

function sshExec(sql) {
    return 'ssh user@192.198.0.1 /bin/bash << EOF\n' +
        '    '+callClient(sql)+'\n' +
        'EOF\n';
}`

**Comment by RaviTejaKomma** [comment]
> As stated in [the docs](https://clickhouse.yandex/docs/en/query_language/queries/#into-outfile-clause), the output file is created on the client side. It is pretty hard to do via the HTTP interface :) So INTO OUTFILE is disabled in this case. You can use `clickhouse-client` for that.

Hey @ztlpn Can you please point to me where I can find the reasons why it is disabled over the HTTP interface and any issue which is tracking this feature?

**Comment by dev01-isarflow** [comment]
I would like to have this feature via an HTTP client, with the restriction that the file is written out on the server.
