### ISSUE TITLE
toStartOfMonth() bug

### ISSUE THREAD

**Issue by b-l-a-c-k-b-e-a-r-d** [yandex/ClickHouse#2327]
This function returns `0000-00-00` for any date in January, 1970:

```
 :) SELECT toStartOfMonth(toDate('1970-01-01'));
┌─toStartOfMonth(toDate(\'1970-01-01\'))─┐
│                             0000-00-00 │
└────────────────────────────────────────┘

 :) SELECT toStartOfMonth(toDate('1970-02-01'));
┌─toStartOfMonth(toDate(\'1970-02-01\'))─┐
│                             1970-02-01 │
└────────────────────────────────────────┘
```

This was from Clickhouse version 1.1.54378.

**Comment by filimonov** [comment]
Documented: https://clickhouse.yandex/docs/en/data_types/date/ 

> A date. Stored in two bytes as the number of days since 1970-01-01 (unsigned). Allows storing values from just after the beginning of the Unix Epoch to the upper threshold defined by a constant at the compilation stage (currently, this is until the year 2106, but the final fully-supported year is 2105). **The minimum value is output as 0000-00-00**.
