### ISSUE TITLE
TCPHandler Errors

### ISSUE THREAD

**Issue by derekperkins** [yandex/ClickHouse#2332]
I have a 3 node cluster running on Kubernetes in Azure that is spewing about 6,000 logs per hour regarding TCPHandler, of which 2,000 are `<Warning> TCPHandler: Client has not sent any data.\n`. I originally reported this in the Go driver - https://github.com/kshvakov/clickhouse/issues/102, but I still see these logs when the client is disconnected.

I can't tell from the logs if these communication errors are from internal communication or not. I suspect that they may be related to MySQL dictionary connections, but I'm not sure how to verify that.

My cluster otherwise seems to be performing well, with queries running quickly and no errors in operation. My tables use `ReplicatedReplacingMergeTree`, with no shards or distributed tables.

What is the best way to find out more information? I am running on the `yandex/clickhouse-server:1.1.54380` Docker image and using ZooKeeper 3.5.3beta.

### error.log
```
2018.04.19 18:38:25.329715 [ 3343 ] &lt;Warning&gt; TCPHandler: Client has not sent any data.
2018.04.19 18:38:26.672138 [ 6750 ] &lt;Warning&gt; TCPHandler: Client has not sent any data.
2018.04.19 18:38:27.913569 [ 6749 ] &lt;Warning&gt; TCPHandler: Client has not sent any data.
2018.04.19 18:38:32.519611 [ 6752 ] &lt;Warning&gt; TCPHandler: Client has not sent any data.
2018.04.19 18:38:35.329742 [ 3343 ] &lt;Warning&gt; TCPHandler: Client has not sent any data.
2018.04.19 18:38:42.915973 [ 3583 ] &lt;Warning&gt; TCPHandler: Client has not sent any data.
2018.04.19 18:38:45.329743 [ 3343 ] &lt;Warning&gt; TCPHandler: Client has not sent any data.
2018.04.19 18:38:46.676854 [ 6752 ] &lt;Warning&gt; TCPHandler: Client has not sent any data.
2018.04.19 18:38:47.523200 [ 3681 ] &lt;Warning&gt; TCPHandler: Client has not sent any data.
2018.04.19 18:38:55.329787 [ 3343 ] &lt;Warning&gt; TCPHandler: Client has not sent any data.
2018.04.19 18:38:57.527671 [ 3583 ] &lt;Warning&gt; TCPHandler: Client has not sent any data.
2018.04.19 18:39:02.921512 [ 3343 ] &lt;Warning&gt; TCPHandler: Client has not sent any data.
2018.04.19 18:39:05.329785 [ 3681 ] &lt;Warning&gt; TCPHandler: Client has not sent any data.
2018.04.19 18:39:06.681526 [ 6750 ] &lt;Warning&gt; TCPHandler: Client has not sent any data.
2018.04.19 18:39:07.531955 [ 6752 ] &lt;Warning&gt; TCPHandler: Client has not sent any data.
2018.04.19 18:39:12.923069 [ 3343 ] &lt;Warning&gt; TCPHandler: Client has not sent any data.
```

### log
```
2018.04.19 18:32:37.426676 [ 6750 ] &lt;Trace&gt; TCPHandlerFactory: TCP Request. Address: 1.2.3.4:58719
2018.04.19 18:32:37.825411 [ 3343 ] &lt;Trace&gt; TCPHandlerFactory: TCP Request. Address: 1.2.3.4:49876
2018.04.19 18:32:41.591676 [ 6745 ] &lt;Trace&gt; TCPHandlerFactory: TCP Request. Address: 1.2.3.4:55638
2018.04.19 18:32:42.427051 [ 6750 ] &lt;Warning&gt; TCPHandler: Client has not sent any data.
2018.04.19 18:32:42.427087 [ 6750 ] &lt;Information&gt; TCPHandler: Done processing connection.
2018.04.19 18:32:42.825456 [ 3343 ] &lt;Warning&gt; TCPHandler: Client has not sent any data.
2018.04.19 18:32:42.825525 [ 3343 ] &lt;Information&gt; TCPHandler: Done processing connection.
2018.04.19 18:32:45.329679 [ 6749 ] &lt;Trace&gt; TCPHandlerFactory: TCP Request. Address: 10.244.0.1:44156
2018.04.19 18:32:45.329926 [ 6749 ] &lt;Warning&gt; TCPHandler: Client has not sent any data.
2018.04.19 18:32:45.329953 [ 6749 ] &lt;Information&gt; TCPHandler: Done processing connection.
2018.04.19 18:32:46.592199 [ 6745 ] &lt;Warning&gt; TCPHandler: Client has not sent any data.
2018.04.19 18:32:46.592246 [ 6745 ] &lt;Information&gt; TCPHandler: Done processing connection.
2018.04.19 18:32:55.329507 [ 6749 ] &lt;Trace&gt; TCPHandlerFactory: TCP Request. Address: 1.2.3.4:44200
2018.04.19 18:32:55.329688 [ 6749 ] &lt;Warning&gt; TCPHandler: Client has not sent any data.
2018.04.19 18:32:55.329711 [ 6749 ] &lt;Information&gt; TCPHandler: Done processing connection.
2018.04.19 18:32:56.595929 [ 3681 ] &lt;Trace&gt; TCPHandlerFactory: TCP Request. Address: 10.240.0.5:55722
2018.04.19 18:32:57.429842 [ 6750 ] &lt;Trace&gt; TCPHandlerFactory: TCP Request. Address: 10.240.0.4:58814
2018.04.19 18:33:01.596887 [ 3681 ] &lt;Warning&gt; TCPHandler: Client has not sent any data.
2018.04.19 18:33:01.596999 [ 3681 ] &lt;Information&gt; TCPHandler: Done processing connection.
```

**Comment by den-crane** [comment]
>TCP Request. Address: 1.2.3.4:58719
It's really strange IP -- 1.2.3.4, usually it's been used for icmp hole punching.
Check your firewall settings, it seems you allow tcp connections from the public network.

**Comment by derekperkins** [comment]
> It's really strange IP -- 1.2.3.4, usually it's been used for icmp hole punching.
I took out my public IP and replaced it with `1.2.3.4` when reporting this issue.

> Check your firewall settings, it seems you allow tcp connections from the public network.
That's a good idea, I'll try closing my load balancer and see if that eliminates the errors.

**Comment by derekperkins** [comment]
After running without any external access for a few hours, there was no difference in the internal log errors, so it wasn't just rogue bots trying to connect. It must be internal.

**Comment by filimonov** [comment]
May be some health checks? I.e. for example loadbalancer checking yhat port
is opened?

ср, 9 мая 2018 г., 20:35 Derek Perkins <notifications@github.com>:

**Comment by derekperkins** [comment]
@filimonov Thanks for the suggestion, that is absolutely it, I can't believe I didn't realize it sooner.

Right now, the health check is opening a TCP connection to port 9000. Is there a better way to make sure that ClickHouse is working properly that won't throw errors?

**Comment by den-crane** [comment]
try to 8123 instead of 9000

$ curl http://localhost:8123
Ok.

**Comment by derekperkins** [comment]
That worked great, thanks!
