### ISSUE TITLE
clickhouse Received signal Segmentation fault (11)

### ISSUE THREAD

**Issue by zhaoplayboy** [yandex/ClickHouse#2336]
clickhouse unormal stopped with a Segment Fault the log I recevied as follow:
2018.05.10 14:48:11.466971 [ 4085 ] <Error> BaseDaemon: ########################################
2018.05.10 14:48:11.467048 [ 4085 ] <Error> BaseDaemon: (from thread 1007) Received signal Segmentation fault (11).
2018.05.10 14:48:11.467059 [ 4085 ] <Error> BaseDaemon: Address: 0x1b
2018.05.10 14:48:11.468212 [ 4085 ] <Error> BaseDaemon: 1. /lib64/libc.so 

.6(+0x14bcd0) [0x7f838c192cd0]
2018.05.10 14:48:11.468248 [ 4085 ] <Error> BaseDaemon: 2. /opt/ncompass/opt/clickhouse/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x96) [0x30eff76]
2018.05.10 14:48:11.468256 [ 4085 ] <Error> BaseDaemon: 3. /lib64/libpthread.so 

.0(+0x7dc5) [0x7f838e86bdc5]
2018.05.10 14:48:11.468263 [ 4085 ] <Error> BaseDaemon: 4. /lib64/libc.so 

.6(clone+0x6d) [0x7f838c13e73d]

**Comment by filimonov** [comment]
Can you provide more information?
For example - query which caused that?

**Comment by zhaoplayboy** [comment]
we have solved it by update new version.
