### ISSUE TITLE
clickhouse query result have additional colume named _table

### ISSUE THREAD

**Issue by zhaoplayboy** [yandex/ClickHouse#2338]
clickhouse query result would have additional colume named _table when we used merge function if we used distributed table.MergeTree table is ok.

**Comment by zhaoplayboy** [comment]
SELECT
    datasource_id AS dimension_datasource_id,
    sum(if_in_pkts) AS metric_in_pkt_pps
FROM merge(ncompass, '^(data_17_1508831948520041_3600_20180510_all)$')
WHERE dimension_datasource_id = 1525680565993917
GROUP BY dimension_datasource_id
ORDER BY metric_in_pkt_pps DESC
LIMIT 0, 50

┌─_table─────────────────────────────────────┬─dimension_datasource_id─┬─metric_in_pkt_pps─┐
│ data_17_1508831948520041_3600_20180510_all │        1525680565993917 │                 0 │
└────────────────────────────────────────────┴─────────────────────────┴───────────────────┘

1 rows in set. Elapsed: 0.034 sec.

SELECT
    datasource_id AS dimension_datasource_id,
    sum(if_in_pkts) AS metric_in_pkt_pps
FROM data_17_1508831948520041_3600_20180510_all
WHERE dimension_datasource_id = 1525680565993917
GROUP BY dimension_datasource_id
ORDER BY metric_in_pkt_pps DESC
LIMIT 0, 50

┌─dimension_datasource_id─┬─metric_in_pkt_pps─┐
│        1525680565993917 │                 0 │
└─────────────────────────┴───────────────────┘

1 rows in set. Elapsed: 0.036 sec.

**Comment by zhang2014** [comment]
Maybe related to #2226

**Comment by zhaoplayboy** [comment]
I have found a new problem.when I used group by clause the _table column would be added to the group condition caused the result not correct.The sql and result as follow picture in the url. 
http://chuantu.biz/t6/309/1526026570x-1376440078.png

**Comment by zhaoplayboy** [comment]
solve it by update new version.
