### ISSUE TITLE
Чистка от DB::Exception: No active replica has part

### ISSUE THREAD

**Issue by alxark** [yandex/ClickHouse#2339]
Есть кластер КХ запущенный в динамическом окружении ( docker + nomad). Во время эксплуатации возможны ситуации когда на ноду прошла запись ( создалась партиция), но например хост сдох и инстанс кликхауса переехал на другую ноду. В этом случае у нас в ZK остается запись о созданной партиции но физически мы ее уже не получим ( потому что сервак умер и туда уже инстанс не переедет). При возникновении таких ситуаций лог начинает забивать данными о No active replica has part. Есть ли какой то вариант сказать КХ что по прошествии Х часов при недоступности партиции ее надо считать навсегда утерянной и вообще забыть про ее существование и удалить из ZK?

**Comment by KochetovNicolai** [comment]
Такой настройки нет. ClickHouse ожидает, что неактивная реплика будет когда-нибудь запущена, и данные не будут потеряны. Если реплика не будет восстановлена, то должно помочь удаление ноды из зукипера, соответствующей реплике.

**Comment by alxark** [comment]
@KochetovNicolai спасибо за ответ. Это может быть проблематично в сильно динамических окружениях. Можно ли ожидать появления такой настройки в будущем? Чистка нод как я понимаю тоже необходимо, потому что они могут подыхать с завидной регулярностью в больших инсталляциях.

**Comment by filimonov** [comment]
Duplicate https://github.com/yandex/ClickHouse/issues/2755
