### ISSUE TITLE
questions about sumMap function

### ISSUE THREAD

**Issue by mga-chka** [yandex/ClickHouse#2355]
Hi,

I have some questions about the sumMap function.
I was first sending a mail to @vavrusa and @bocharov who wrote this function but it's better to write an issue so that it can be useful to other people.

I'm leading the migration of our data infrastructure to Clickhouse and I'm using the sumMap function for one of the features of my company (we're building an analytics tool). It gives very good performance (up to 3 time faster than the same query without sumMap) so many thanks to you guys for this awesome function.

However, I have 2 questions/remarks:
- The first question is about overflow for the result of this function:
If I use sumMap(key,value) where value is an UInt8 or an UInt16, the function will give a result as an UInt8/UInt16 and it will overflow since I'm using sumMap on more than 200 millions rows.
I could store the value field as an UInt64 (with a small storage overhead) or cast the value as an UInt64 (with a small processing overhead) but I was wandering if there is a better way to deal with overflow.

- The second question is about high cardinality keys:
The sumMap function is fast as long as the number of distinct keys is small. I ran some benchmarks and I was having huge performance issues when there were millions of distinct keys (on 6 Amazon i3.8xl instances). One of the solutions I thought about would be to have a "sumMapWithFilter" function that would sum only the keys specified on the filter clause. Before starting to work on this function, I was wondering if you have this kind of problems at Cloudflare and if this kind of function was on your roadmap.

**Comment by alexey-milovidov** [comment]
Both questions have been resolved by @ercolanelli-leo (in master, scheduled for the next release).
