### ISSUE TITLE
Cannot skip nested JSON field when inserting JSON data with input_format_skip_unknown_fields=1

### ISSUE THREAD

**Issue by maxulan** [yandex/ClickHouse#2367]
Hello,
Following cmd fails if input JSON contains nested fields: 

`clickhouse-client --input_format_skip_unknown_fields=1 --query="INSERT INTO my_table FORMAT JSONEachRow" < my.json`

**Code: 117. DB::Exception: Unexpected nested field for key 'originalMsg'**

In my case input JSON contains fields prepared for insertion into clickhouse and  'originalMsg' filed containing 'backup data' which is valid JSON object too.

**Comment by filimonov** [comment]
Clickhouse doesn't support deep structures in JSON like `{"x": {"a":"1", "b":"2"}}`.
If your input data doesn't contain such a deep structures like, and ClickHouse still complain that something's wrong, please provide some sample of your JSON.

**Comment by maxulan** [comment]
I don't use nested fields in target table however nested field exists in my input JSON. 
I use --input_format_skip_unknown_fields=1 specifically to ignore that nested field. 

However it doesn't work. See exception above.
If I don't use that field then why Clickhouse cares if it's nested or not?
