### ISSUE TITLE
protobuf format

### ISSUE THREAD

**Issue by leoluk** [yandex/ClickHouse#2369]
protobuf is a binary serialization format similar to Cap'n'Proto. It's very popular in the Go ecosystem in particular and is a popular Kafka serialization format.

Example use case: I'm working on an open-source flow record analyzer and I'm planning to use protobuf. Right now I'm using a separate inserter process that reads messages from Kafka and insert them into ClickHouse. However, in the long term, it would be desirable to skip that and use the Kafka engine instead.

While protobuf usually requires code generation, there's support for reading a schema at runtime using [DynamicMessage](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.dynamic_message). It's not ideal from a performance point of view, but it should be faster than JSON in any case. 

The Cap'n'Proto implementation works similarly:

https://github.com/yandex/ClickHouse/blob/412c154045a119f618e206180c6e455c944b1f79/dbms/src/DataStreams/CapnProtoRowInputStream.cpp#L37

**Comment by luc1ph3r** [comment]
I'm currently working on Protobuf support. The first testable implementation should be available at the end of this week. Stay tuned (:

**Comment by jvmlet** [comment]
Hello
Any progress with protobuf messages support ? DWH that natively  supports storing/querying protobuf  messages  is the most demanding  feature ;-)

**Comment by alexey-milovidov** [comment]
This task is reassigned and scheduled for January.

> DWH that natively supports storing/querying protobuf messages is the most demanding feature ;-)

It will allow to import/export/store subset of Protobuf messages. Nested messages will be limited to Arrays.

**Comment by alexey-milovidov** [comment]
Protobuf output format (export from ClickHouse) has been implemented (in master).
Nested messages are not yet supported.
We are going to implement protobuf input format, and only then consider implementing nested messages.

**Comment by vitlibar** [comment]
Protobuf IO format has been implemented and merged in master. All types of fields (repeated/optional/required) and nested messages are supported now. See [documentation](https://github.com/yandex/ClickHouse/blob/master/docs/en/interfaces/formats.md) for details.
