### ISSUE TITLE
All rows in one row grouped by key

### ISSUE THREAD

**Issue by jonatasfreitasv** [yandex/ClickHouse#2371]
Hi guys!!!

Have any way to make this table:

#### key;event;payload
7fa01d14-75e3-4eba-905d-4708ae57681c;idEventoInicial;response_1_1
7fa01d14-75e3-4eba-905d-4708ae57681c;idEnd2;response_1_2

09880880-75e3-4eba-905d-73812798372;idEventoInicial;response_2_1
09880880-75e3-4eba-905d-73812798372;idEnd2;response_2_2

In this vision:

#### key;idEventoInicial;idEnd2
7fa01d14-75e3-4eba-905d-4708ae57681c;response_1_1;response_1_2
09880880-75e3-4eba-905d-73812798372;response_2_1;response_2_2

*or other way to view all rows in one row grouped by key.*

?

**Comment by filimonov** [comment]
Actually concrete SQL depends on what you want to do in case if same eventid will appear twice.
If it can't happen you can do just 
```
SELECT
  key,
  anyIf(payload, event = 'idEventoInicial') as idEventoInicial,
  anyIf(payload, event = 'idEnd2') as idEnd2
FROM 
  table 
GROUP BY 
  key
```
