### ISSUE TITLE
FORMAT JSON for Int64 returns string rather than integer

### ISSUE THREAD

**Issue by rpfennin** [yandex/ClickHouse#2375]
I have a field named offset in a table that is of type Int64.

When I specify FORMAT JSON in my query the result is returned (incorrectly, wrapped in quotes) as:

"data":
	[
		{
			"offset": "260431",
		}
	],

However, when I specify FORMAT CSV, the result is returned (correctly) as:

260431 (without quotes)

**Comment by vpanfilov** [comment]
You can see the explanation of this behaviour here:
https://github.com/yandex/ClickHouse/issues/114

There is an option in config to disable quotes for Int64:
https://clickhouse.yandex/docs/en/operations/settings/settings/#output_format_json_quote_64bit_integers

**Comment by rpfennin** [comment]
I'm having an issue getting the setting to be respected.  i have tried both 

 <output_format_json_quote_64bit_integers>false</output_format_json_quote_64bit_integers>
and
 <output_format_json_quote_64bit_integers>0</output_format_json_quote_64bit_integers>

in the config.xml but i'm not having any luck.

**Comment by vpanfilov** [comment]
@rpfennin, here is a simple example without touching config:

```sql
Connected to ClickHouse server version 1.1.54380.

:) select toInt64(12345) as testInt64 format JSONEachRow

SELECT toInt64(12345) AS testInt64
FORMAT JSONEachRow

{"testInt64":"12345"}

1 rows in set. Elapsed: 0.083 sec.

:) set output_format_json_quote_64bit_integers=0

SET output_format_json_quote_64bit_integers = 0

Ok.

0 rows in set. Elapsed: 0.026 sec.

:) select toInt64(12345) as testInt64 format JSONEachRow

SELECT toInt64(12345) AS testInt64
FORMAT JSONEachRow

{"testInt64":12345}

1 rows in set. Elapsed: 0.001 sec.
```

Option in config should work the same way.

**Comment by alexey-milovidov** [comment]
@rpfennin It's per user setting. You can define it in `users.xml` file for a user profile.
