### ISSUE TITLE
Ошибка запроса с match для MySQL-движка

### ISSUE THREAD

**Issue by TimonKK** [yandex/ClickHouse#2384]
Делаю запрос к таблице с MySQL-движком:
SELECT ... FROM users u WHERE match(u.email, 'bk.ru')

Получаю такую ошибку
Code: 1000. DB::Exception: Received from localhost:9000, ::1. DB::Exception: mysqlxx::BadQuery: Operand should contain 1 column(s) (localhost:3306)

Важное уточнение, на самом деле таблица users в КХ смотрит на MariaDB базу.

Получается что КХ корректно распарсил сам запрос, но не смог его передать в mysql?

**Comment by TimonKK** [comment]
Такое повторяется и для такого запроса
SELECT
        _id
      FROM
        users u
      WHERE
        (
          u.createdLang IN ('ru')
          AND u.isAdmin = 0
          AND u.role = 'guest'
        )


Poco::Exception. Code: 1000, e.code() = 1241, e.displayText() = mysqlxx::BadQuery: Operand should contain 1 column(s) (localhost:3306), e.what() = mysqlxx::BadQuery

**Comment by alexey-milovidov** [comment]
Проблема со вторым запросом может быть исправлена в https://github.com/yandex/ClickHouse/pull/5313
Но мне нужен более подробный пример, чтобы воспроизвести проблему.

**Comment by TimonKK** [comment]
Схема таблицы:
 CREATE TABLE users (_id String, email String) ENGINE = MySQL('localhost:3306', 'db', 'table', 'username', 'password')

Запрос:
SELECT _id FROM users AS u WHERE ( u.createdLang IN ('ru') AND u.isAdmin = 0 AND u.role = 'guest' )

Ошибка:
Received exception from server (version 19.5.2):
Code: 1000. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: mysqlxx::BadQuery: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''ru') AND (`isAdmin` = 0) AND (`role` = 'guest')' at line 1 (localhost:3306).

**Comment by alexey-milovidov** [comment]
Спасибо, как раз эта ошибка исправляется в моём pull request!
