### ISSUE TITLE
CASE evaluation

### ISSUE THREAD

**Issue by alniks** [yandex/ClickHouse#2385]
If we have two columns in a table: logged (only empty strings) and created and try to run the following query 

`SELECT CASE WHEN empty(time_logged) = 0 THEN toDateTime(substring(logged,1,19)) ELSE created END as created_at from events`

We will have an error:

Code: 32. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Attempt to read after eof: Cannot parse DateTime from String, because value is too short

Why ClickHouse tries to parse the logged column even if it should do so only if it's not empty?

**Comment by filimonov** [comment]
Known (and very nasty) issue. Currently clickhouse calculate both branches, and only afterwards choose one.

Workaround usually possible, in your case you can try: 
``` 
SELECT CASE WHEN empty(time_logged) = 0 THEN toDateTime(substring(concat(logged,'0000-00-00 00:00:00') ,1,19)) ELSE created END as created_at from events
```

Fixing that is in roadmap, and AFAIK work is already in progress.

**Comment by filimonov** [comment]
See also #1562 #1768

**Comment by alniks** [comment]
Closing as a duplicate and there is a workaround

**Comment by filimonov** [comment]
Let's continue tracking that issue in #1562
