### ISSUE TITLE
Некорректное экранирование строки?

### ISSUE THREAD

**Issue by VerusK** [yandex/ClickHouse#2401]
Если вставить вот такую строку
`{"key":"data-md-component=\"navigation\"><div class=\"md-sidebar__scrollwrap\">"}`

затем сделать запрос `select visitParamExtractString(data, 'key') from logs`, то на выходе получаем 
```
┌─visitParamExtractString(data, \'key\')─┐
│ data-md-component=                     │
└────────────────────────────────────────┘
```
корректно ли, что необходимо вставлять строку с дополнительным экранированием?
Вот такая строка потом обрабатывается корректно
`{"key":"data-md-component=\\"navigation\\"><div class=\\"md-sidebar__scrollwrap\\">"}`

**Comment by ludv1x** [comment]
Два раза экранировать не надо:

```
vludv-ub :) create table test.string (key String) ENGINE = Memory

CREATE TABLE test.string
(
    key String
)
ENGINE = Memory

Ok.

0 rows in set. Elapsed: 0.012 sec. 

vludv-ub :) insert into test.string FORMAT JSONEachRow {"key":"data-md-component=\"navigation\"><div class=\"md-sidebar__scrollwrap\">"}

INSERT INTO test.string FORMAT JSONEachRow

Ok.

1 rows in set. Elapsed: 0.001 sec. 

vludv-ub :) select * FROM test.string

SELECT *
FROM test.string 

┌─key─────────────────────────────────────────────────────────────────┐
│ data-md-component="navigation"><div class="md-sidebar__scrollwrap"> │
└─────────────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.001 sec. 
```
А вы как вставляете?
То, что вам приходится это делать говорит о том, что один раз у вас происходит эскейпинг для вашей среды (например bash), а потом только для ClickHouse.

**Comment by VerusK** [comment]
@ludv1x Вставка происходит с `FORMAT TabSeparated` и вставка происходит не руками из консоли, а через clickhouse-client и на входе файлы.

**Comment by ludv1x** [comment]
При вставке в формате `TabSeparated` пары символов `\<symbol>` заменяются на `<symbol>`. 
Соответственно при вставке строки
```{"key":"data-md-component=\"navigation\"><div class=\"md-sidebar__scrollwrap\">"}```
в формате TSV реально вставится 
```{"key":"data-md-component="navigation"><div class="md-sidebar__scrollwrap">"}```

**Comment by aCLr** [comment]
Считается ли такое поведение корректным? Нет ли в планах это изменить? Спрашиваю чтобы в будущем, после гипотетического обновления версии сервера, не пришлось данные переливать.

**Comment by alexey-milovidov** [comment]
Это полностью корректно.

Ведь формат TabSeparated требует экранирования, а JSON тоже требует экранирование внутри строковых литералов. Получается, что для корректной вставки в формате TabSeparated строки, содержащей JSON, содержащий строковый литерал, содержащий двойную кавычку, вам потребуется два бэкслеша.
