### ISSUE TITLE
AggregatingMergeTree not updating from Kafka

### ISSUE THREAD

**Issue by TheMcGoose** [yandex/ClickHouse#2402]
Table Architecture:
1) Kafka Engine Table
2)  Local Table with MergeTree Engine
3) Materialized view selecting from Kafka table into the Local table
4) Materialized view with AggregatingMergeTree Engine that selects from the Local table

Expected behavior is that as new values appear in the Local table, they should also be loaded into the AMT, and their aggregations should be queryable from the AMT.

What actually happens is that data comes cleanly in up to the local table, is queryable and you can run any aggregated or unaggregated query against the local table with no problems.  However, any attempt to select from the Local table into the AMT results in 0 rows being added and no new rows appearing ever, even after new rows are added to the Local table.

If the AMT is created with `POPULATE` it does pull data in from the local table, creating a point-in-time aggregation snapshot, as no values are added to the AMT after it's created and populated.

With the same exact local table and AMT, if instead you insert data into the local table via the clickhouse-client, everything behaves as expected.  The AMT shows the aggregated forms of the data that was inserted into the local table.

There may be something weird happening when the data gets moved into the Local table, the AMT doesn't get 'triggered' to look for updates and pull the new data in.

**Comment by mvanderkroon** [comment]
We have the same issue, any progress on this?

**Comment by MyReserved** [comment]
> We have the same issue, any progress on this?

Cascading Materialized views are not working at the moment.
KafkaEngine use one MV so you cannot use another MV on target table
I asked @alexey-milovidov last week

**Comment by mvanderkroon** [comment]
Thanks for the update!

**Comment by TH-HA** [comment]
Hello 
Cascading MV are not working , but can we have multiple MV on the same source to feed the input but also the aggregation ?
Typically can we feed the input and aggregated table directly from the Kafka table ? 

Thanks

**Comment by minaevmike** [comment]
We have the same issue, any progress on this?

**Comment by abyss7** [comment]
It's possible to have multiple views on the same kafka table - just tested it on 19.5. The cascading mat. views is not a kafka-specific feature, so it's better to create a new separate issue for this feature.

**Comment by DipalPrajapati** [comment]
So can we have multiple MVs those read from same KafkaEngine ?
