### ISSUE TITLE
Upgrading docker image

### ISSUE THREAD

**Issue by ilyabreev** [yandex/ClickHouse#2404]
I'm using ClickHouse docker image with tag `1.1.54343`.
It works with directory mount and stores its data on the host directory.
When I try to use any tag that newer than  `1.1.54343`, including `latest` on that previously stored data, ClickHouse exits with code 70. It looks like permission error and I checked uid/gid of owner of ClickHouse data - they are 105:106.
So I can't upgrade ClickHouse docker image version.
Can anyone please give me some hint?

**Comment by filimonov** [comment]
Recent ClickHouse version give much better control on file owners in docker, see documentation on docker hub. 

Closing that issue (obsolete). Please create a new issue in case of additional questions.

**Comment by filimonov** [comment]
See also: #1464 #3828 #2114 #4753
