### ISSUE TITLE
Stoping the server bug

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#2407]
In case you are using a HTTP client with keepalive the server will never close till you close the client connections.

You can replicate by:

1. start clickhouse
2. telnet 127.0.0.1 8123
3. stop the clickhouse process (CTRL+Z)

Till you cut of the connection of telnet the server won't close. 

Not sure if clickhouse is started as daemon will have the same behavior

**Comment by silviucpp** [comment]
Note: seems at some point there is a timeout but in case you have a pool off connections 20 in my case the server is started in few minutes even if no query is sent on that server

**Comment by ludv1x** [comment]
The reason of the freezing is that clickhouse does not handle SIGSTOP signal properly.
So, if you make ```sudo kill -s 15 `pidof clickhouse-server` ``` than ClickHouse freezes even it there are no active connections.

But it correctly handles SIGTERM.
If you make ``` sudo kill -s 15 `pidof clickhouse-server` ``` with active ``` telnet 127.0.0.1 8123 ``` you will see something like the following in the log:
```
2018.05.24 15:10:07.712493 [ 31 ] <Information> Application: Received termination signal (Terminated)
2018.05.24 15:10:07.712603 [ 1 ] <Debug> Application: Received termination signal.
2018.05.24 15:10:07.712623 [ 1 ] <Debug> Application: Waiting for current connections to close.
2018.05.24 15:10:08.146284 [ 1 ] <Debug> Application: Closed all listening sockets. Waiting for 1 outstanding connections.
2018.05.24 15:10:13.153275 [ 1 ] <Debug> Application: Closed connections. But 1 remains. Tip: To increase wait time add to config: <shutdown_wait_unfinished>60</shutdown_wait_unfinished>
2018.05.24 15:10:23.154150 [ 1 ] <Information> Application: Shutting down storages.
```
In this case, the behavior is correct and even adjustable.

**Comment by silviucpp** [comment]
Hello @ludv1x ,

On My mac at CTRL+C I see:

2018.05.24 13:26:11.498059 [ 8 ] <Information> Application: Received termination signal (Interrupt: 2)

And server stop accepting new connections but it won't close after all existing connections are closed by the client.

Also I see that on a client that's using http pipeline-ing and persistent connection the server close the connection after each provided response. Is this how should work or it's a bug ?

Silviu

**Comment by silviucpp** [comment]
I found why the connection is cut of after a response : keep_alive_timeout setting, but is not working as it suppose to:

For example set : keep_alive_timeout = 3 and create a connection.

This one is not close even after minutes.The send a request and after you get the response connection is closed after that 3 seconds.

So in order to work at least one request needs to be received. 

Also keep_alive_timeout is not the best name :) usually this kind of name makes me think about the frequency used by the server to send keep alive messages over the tcp connection in order to keep it alive.. instead a better name might be connection_idle_time or something similar

**Comment by alexey-milovidov** [comment]
> I am not sure that ClickHouse have to close all connection on SIGSTOP.

The process cannot handle SIGSTOP.

**Comment by alexey-milovidov** [comment]
I don't understand, what's wrong with `keep_alive_timeout` - it's exactly for HTTP/1.1 Connection: Keep-Alive.

Ok, I will close.
