### ISSUE TITLE
Set all function names as a parameter of registerFunction

### ISSUE THREAD

**Issue by artpaul** [yandex/ClickHouse#241]
There are different ways to assign name to functions:
1. Using struct - `struct NameProtocol { static constexpr auto name = "protocol"; };`
2. Using constant inside implementation class - `static constexpr auto name = "URLPathHierarchy";`

So it hard to find the concrete name of function for given type with grep. My proposal is to add a parameter to the `registerFunction` and pass all names with it.

**Comment by alexey-milovidov** [comment]
Ok. The only problem is that function is using its own name in exception messages.

**Comment by alexey-milovidov** [comment]
Cancelled?

**Comment by artpaul** [comment]
Yes, there is some another cons with this proposal. So it's better to keep as is now.
