### ISSUE TITLE
Primary key and its effect on data size

### ISSUE THREAD

**Issue by simPod** [yandex/ClickHouse#2422]
Does primary key composition have influence on data size in the same manner as in other databases like MySQL or Postgres?

If I understood correctly, it influences how data are sorted in tables so it shouldn't create any significant data on top but only influence the sorting, right? Eg. in Postgres sometimes happen that indexes are larger in size than actual data but that shouldn't be the case here or am I mistaken?

Thanks!

**Comment by den-crane** [comment]
The right PK order allows to reduce data size by column compression.
PK it's not an index it just a sort order of data in columns.

so you have data
```
field0  field1  field3
---------
1 1 longstring1
2 2 anotherstring1
3 3 thirtdstring1
4 1 longstring2
5 2 anotherstring2
6 3 thirtdstring2
```

case of PK = field1, field0 the data on the will take less space because of higher compression.
```
field0  field1  field3
---------
1 1 longstring1
4 1 longstring2
2 2 anotherstring1
5 2 anotherstring2
3 3 thirtdstring1
6 3 thirtdstring2
```

**Comment by simPod** [comment]
Thank you very much!
