### ISSUE TITLE
'table doesn't exist' Exception when MV table create to StorageKafka

### ISSUE THREAD

**Issue by LiuYangkuan** [yandex/ClickHouse#2439]
I created a Kafka Engine table mq, and then create a materialized view tab_view to this mq.
There was an Error in log as following:

> 2018.05.29 02:14:07.639819 [ 5 ] <Error> void DB::StorageKafka::streamThread(): Code: 60, e.displayText() = DB::Exception: Table default.tab_view doesn't exist., e.what() = DB::Exception, Stack trace:
> 0. ./clickhouse-server(StackTrace::StackTrace()+0x16) [0x4a9af56]
> 1. ./clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x1f) [0x25e3f9f]
> 2. ./clickhouse-server(DB::Context::getTableImpl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Exception*) const+0x2fd) [0x42b373d]
> 3. ./clickhouse-server(DB::Context::getTable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const+0x5f) [0x42b3a4f]
> 4. ./clickhouse-server(DB::PushingToViewsBlockOutputStream::PushingToViewsBlockOutputStream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<DB::IStorage> const&, DB::Context const&, std::shared_ptr<DB::IAST> const&, bool)+0x751) [0x46440b1]
> 5. ./clickhouse-server(DB::InterpreterInsertQuery::execute()+0x206) [0x42f6ca6]
> 6. ./clickhouse-server(DB::StorageKafka::streamToViews()+0x603) [0x47d90e3]
> 7. ./clickhouse-server(DB::StorageKafka::streamThread()+0x18a) [0x47d96ca]
> 8. ./clickhouse-server() [0x5059baf]
> 9. /lib64/libpthread.so.0(+0x7dc5) [0x7fb051de6dc5]
> 10. /lib64/libc.so.6(clone+0x6d) [0x7fb04f6bb76d]

**Comment by millin** [comment]
Could you show your CREATE TABLE requests of both mq and tab_view?

**Comment by LiuYangkuan** [comment]
Here it is:

Create table mq (id UInt64, name String, addr String) ENGINE=Kafka(‘Kafka-server:9092’, ’topic_name’, ‘group0',’TSV’);
Create materialized view tab_view (id UInt64, name String, addr String) ENGINE=Log as select * from mq;

**Comment by millin** [comment]
I created the same using your statement and didn't see any errors in log.
What is your CH version and OS?

**Comment by millin** [comment]
You mean your pr #2398?
I think your changes are the source of this issue. In stable branch it works fine.

**Comment by LiuYangkuan** [comment]
PR [#2448](https://github.com/yandex/ClickHouse/pull/2448)
It is not a critical bug. And table can work fine, but an Exception in log.
