### ISSUE TITLE
[Question]How about UPDATE&DELETE now?

### ISSUE THREAD

**Issue by zlzforever** [yandex/ClickHouse#2452]
I saw the roadmap: Q1 2018 implement UPDATE&DELETE. Any updates?

**Comment by avalon12** [comment]
+1

**Comment by salisbury-espinosa** [comment]
@zlzforever 
https://github.com/yandex/ClickHouse/blob/master/dbms/src/Parsers/ASTAlterQuery.cpp#L170

```c++
else if (p.type == ASTAlterQuery::DELETE)
        {
            settings.ostr << (settings.hilite ? hilite_keyword : "") << indent_str << "DELETE WHERE " << (settings.hilite ? hilite_none : "");
            p.predicate->formatImpl(settings, state, frame);
        }
```

https://github.com/yandex/ClickHouse/blob/c888903488fa995245dcbe8db63c261343ac1ffb/dbms/src/Parsers/ASTAlterQuery.h#L66

so alter deletes are ready and was released  in https://github.com/yandex/ClickHouse/releases/tag/v1.1.54386-testing (4 days ago)

at the time of your question this has not happened yet ;)

**Comment by yjygit** [comment]
+1

**Comment by tonylauCN** [comment]
it's great work，thks！
i saw DELETE was released in 
[https://github.com/yandex/ClickHouse/releases/tag/v1.1.54386-testing]
if you give me some tips how to deal with that?
-------------------------------------
ALTER TABLE ontime_all
DELETE WHERE Year = 1987

Received exception from server (version 1.1.54386):
Code: 48. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Mutations are not supported by storage Distributed. 
-------------------------------------

**Comment by vitalvas** [comment]
Is it possible to add this functionality to the "MergeTree" engine?

```
ALTER TABLE log
    DELETE WHERE ClientIPv4 = 0

Received exception from server (version 1.1.54388):
Code: 48. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: 
    Mutations are not supported by storage MergeTree.
```

**Comment by blinkov** [comment]
> by the way, why the code responsible for removing of rows is in AlterQuery (ALTER DELETE vs DELETE)

To make it clear that those are not cheap operations that can be done with high rate (unlike normal DELETEs in RDBMS).

> if you give me some tips how to deal with that?

Point ALTER towards local tables, not the distributed one.

> Is it possible to add this functionality to the "MergeTree" engine?

See #2634

**Comment by blinkov** [comment]
I'm grouping up issues about updates in #167
