### ISSUE TITLE
Crash when add a new column Nullable<UInt8>

### ISSUE THREAD

**Issue by zlzforever** [yandex/ClickHouse#2454]
1. Create a table like below:

`
create table t1(name String, run_date Date) Engine=MergeTree(run_date, name, 8192);
`

2. Insert  data:

`
insert into t1 (name, run_date) values ('aaaa', '2018-05-31');
`

3. Add a new Nullable<UInt8> column

`
ALTER table t1 add column n1 Nullable(UInt8);
`

4. Try select data then crash

`
select * from t1;
SELECT *
FROM t1
↑ Progress: 1.00 rows, 15.00 B (9.87 rows/s., 148.10 B/s.)  0%
Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000, ::1
Connecting to database test at localhost:9000 as user default.
Code: 210. DB::NetException: Connection refused: (localhost:9000, ::1)
`

5. After restart service, try insert data not contains new column will crash

`
insert into t1 (name, run_date) values ('bbbbb', '2018-05-31');
`

insert all columns works well

`
insert into t1 (name, run_date, n1) values ('bbbbb', '2018-05-31',1);
`

6. Error logs:

`
2018.05.31 13:57:22.361201 [ 8 ] <Error> BaseDaemon: ########################################
2018.05.31 13:57:22.361264 [ 8 ] <Error> BaseDaemon: (from thread 7) Received signal Segmentation fault (11).
2018.05.31 13:57:22.361277 [ 8 ] <Error> BaseDaemon: Address: NULL pointer.
2018.05.31 13:57:22.364706 [ 8 ] <Error> BaseDaemon: 1. clickhouse-server(DB::ColumnNullable::ColumnNullable(std::shared_ptr<DB::IColumn>, std::shared_ptr<DB::IColumn>)+0x64) [0x28a7224]
2018.05.31 13:57:22.364733 [ 8 ] <Error> BaseDaemon: 2. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x96) [0x31c19c6]
2018.05.31 13:57:22.364747 [ 8 ] <Error> BaseDaemon: 3. /lib64/libpthread.so.0(+0x7e25) [0x7f4eccf12e25]
2018.05.31 13:57:22.364760 [ 8 ] <Error> BaseDaemon: 4. /lib64/libc.so.6(clone+0x6d) [0x7f4eca7e0bad]
`

**Comment by alexey-milovidov** [comment]
No issue on recent ClickHouse versions.
