### ISSUE TITLE
slow order by using MergeTree

### ISSUE THREAD

**Issue by Jingyi244** [yandex/ClickHouse#2457]
**Table Schema**:

>    CREATE TABLE compass.logs (event_uuid String, event String, event_timestamp UInt64,data_date Date  ) ENGINE = MergeTree(data_date, (event_timestamp, event_uuid), 8192)

Since MergeTree tables are partly sorted. sometimes I need do full sort on dataset. And I encounter poor performance when running sql below:

 

> select any(event_timestamp) from (select event_timestamp from logs order by event_timestamp)

I have to cancle the query after waiting minutes.

data size  : 598.13 million rows , and the server has 80 cores,200G RAM, I guess the hardware may not be the bottleneck

So my questions is why this sql costs so much time, and is there a better way to sort the whole dataset ?

**Comment by Slach** [comment]
why you need ANY(event_timestamp) ?
you need random timestamp? or you just need last event_timestamp?

just try 
```
select event_timestamp from logs order by event_timestamp limit 1
```
in your request you buffer 598 million values of event_timestamp in memory

**Comment by Jingyi244** [comment]
@Slach 
Thanks for ur reply.
I am using ANY(event_timestamp)  in the upper sql just to reduce the output to 1 line, for test purpose. Sorry for the misleading.

And i am doing user funnel analysis, as shown in Page 56 of the slide [Creating marketing funnels or how to calculate complex metrics in ClickHouse]
[https://events.yandex.com/lib/talks/247/](url)

they present a way to calculate the achievement users and in the subquery 
![image](https://user-images.githubusercontent.com/3183188/40887813-c813ac28-6780-11e8-8ab7-13e273a2c2ee.png)
there is a ORDER BY EventTimestamp on the Distributed Table.

I found it quite slow when running the order by subquery .Is there a better way to archieve that(the order by subquery,not the funnel)?
