### ISSUE TITLE
Logical error: zero number of streams requested

### ISSUE THREAD

**Issue by valetanddama** [yandex/ClickHouse#246]
Ubuntu 14.04, установлена по документации, конфиги дефолтные.

Запросы вида CREATE TABLE, SHOW CREATE TABLE проходят успешно, но на SELECT 1, SELECT * FROM  и т.п выдает ошибку:

> Received exception from server:
Code: 49. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Logical error: zero number of streams requested.

**Comment by alexey-milovidov** [comment]
Попробуй выполнить на этом сервере:

```
g++ -xc++ -std=c++11 - <<< '#include <thread>'$'\n''int main() { return std::thread::hardware_concurrency(); }' && ./a.out; echo $?
```

И посмотреть, что будет.

**Comment by valetanddama** [comment]
Вывел 1

**Comment by alexey-milovidov** [comment]
А что выводит 
```
SELECT * FROM system.settings WHERE name = 'max_threads'
```
?

**Comment by navdeep710** [comment]
Any updates on this issue , i am facing this issue when i pulled the repo today , previous week pull was working fine.

**Comment by alexey-milovidov** [comment]
Please check the result of query:
```
SELECT * FROM system.settings WHERE name = 'max_threads'
```
The query should not return 0. If it returns 0, it indicates a bug. 

Does the issue get fixed, if you specify setting max_threads manually, like
```
SET max_threads = 16
```
or in parameter of URL?
(recommended value is number of CPU cores)

Do you use physical hardware or VM? And what kind of VM?
If it is VM, please send output of `cat /proc/cpuinfo`.

**Comment by navdeep710** [comment]
thanks Alexey for such quick response , issue got resolved with setting max_threads .

**Comment by navdeep710** [comment]
response of SELECT * FROM system.settings WHERE name = 'max_threads' is indeed 1 , but issue was not present in version 1.1.54083 but is present in 1.1.54112

**Comment by navdeep710** [comment]
Issue got fixed with max_threads setting ... We are running it on VMs

**Comment by emakarov** [comment]
have same issue,trying to solve it.

is this setting (max_threads) applies to all users and sessions of clickhouse?
I'm fixing it, but in another session (from python client) still have same error

**Comment by emakarov** [comment]
cat output of VM (google cloud compute engine instance - g1-small (1 виртуальный ЦП, 1,7 ГБ памяти), Ubuntu 17

cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 62
model name      : Intel(R) Xeon(R) CPU @ 2.50GHz
stepping        : 4
microcode       : 0x1
cpu MHz         : 2500.000
cache size      : 30720 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic popcnt aes xsave avx f16c rdrand hypervisor lahf_lm fsgsbase tsc_adjust smep erms xsaveopt
bugs            :
bogomips        : 5000.00
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

**Comment by emakarov** [comment]
получается вот такое; после разлогина опять ошибка:
`:) SELECT * FROM system.settings WHERE name = 'max_threads'

SELECT *
FROM system.settings
WHERE name = 'max_threads'

Received exception from server:
Code: 49. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Logical error: zero number of streams requested.

0 rows in set. Elapsed: 0.015 sec.

:) SET max_threads = 1

SET max_threads = 1

Ok.

0 rows in set. Elapsed: 0.001 sec.

:) SELECT * FROM system.settings WHERE name = 'max_threads'

SELECT *
FROM system.settings
WHERE name = 'max_threads'

┌─name────────┬─value─┬─changed─┐
│ max_threads │ 1     │       1 │
└─────────────┴───────┴─────────┘

1 rows in set. Elapsed: 0.003 sec.

:) Bye.
(mx) em@instance-1:~/dev/maptonix$ clickhouse-client
ClickHouse client version 1.1.54197.
Connecting to localhost:9000.
Connected to ClickHouse server version 1.1.54197.

:) SELECT * FROM system.settings WHERE name = 'max_threads'

SELECT *
FROM system.settings
WHERE name = 'max_threads'

Received exception from server:
Code: 49. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Logical error: zero number of streams requested.

0 rows in set. Elapsed: 0.063 sec.`

**Comment by alexey-milovidov** [comment]
https://github.com/yandex/ClickHouse/commit/2e47c35fa904ec0a78c4087714437fd79dc6b7da
https://github.com/yandex/ClickHouse/commit/0a553100760207d24a0b90f52d05a263520442ec
