### ISSUE TITLE
Недетерминированный результат выполнения запроса с arrayJoin

### ISSUE THREAD

**Issue by QSer29** [yandex/ClickHouse#2467]
Развернут кластер из мастер сервера и 2 шардов, по 2 реплики в каждом.
На мастер сервере есть Distributed таблица, которая смотрит в таблицы MergeTree на репликах.
Есть запрос следующего вида в эту таблицу:

```
SELECT
    intDiv(date - toDate('2017-12-07'), 90) AS period,
    arrayJoin(labels),
    uniqHLL12(user_id, notEmpty(info) OR (requests != 0) OR (active_days > 0)) AS users
FROM events
WHERE (site_id = 1001) AND (date >= toDate('2017-12-07')) AND (date < toDate('2018-06-05')) AND (arrayJoin(labels) IN ('label_1', 'label_2'))
GROUP BY
    period,
    arrayJoin(labels)
ORDER BY
    period DESC,
    users DESC
```
Который в большинстве случаев возвращает ответ:
```
┌─period─┬─arrayJoin(labels)──────┬───users─┐
│      1 │ label_1                │    2334 │
│      1 │ label_2                │     988 │
│      0 │ label_1                │    1798 │
│      0 │ label_2                │     611 │
└────────┴────────────────────────┴─────────┘
```
Но иногда, по непонятным причинам, строки столбца с arrayJoin размножаются, как будто данные не сгруппировались до конца:
```
┌─period─┬─arrayJoin(labels)──────┬───users─┐
│      1 │ label_1                │    1747 │
│      1 │ label_2                │     733 │
│      1 │ label_1                │     592 │
│      1 │ label_2                │     258 │
│      0 │ label_1                │    1314 │
│      0 │ label_2                │     455 │
│      0 │ label_1                │     453 │
│      0 │ label_2                │     156 │
└────────┴────────────────────────┴─────────┘
```

Была попытка подготовить простенький пример с тестовыми данными для воспроизведения проблемы, но она не увенчалась успехом.

Ошибка тяжела для воспроизведения и наблюдается в конкретных специфических условиях.
Например, перестает воспроизводиться если убрать группировку по period, и воспроизводится гораздо реже если упростить расчет метрики users.

Ошибка наблюдается только если делать запрос в Distributed таблицу. Тот же самый запрос выполненный на одной из реплик дает корректный результат.

В таблице за период запроса около 4 000 000 000 записей, порядка 100 столбцов.

Массив labels содержит строки, как правило от 0 до 10-20 штук, почти всегда с дублями одной и той же строки (label_1, в примере)

Текущая версия сервера 1.1.54385, но проблема наблюдалась и на версии 1.1.54378.

В чем может быть причина такого поведения?

**Comment by filimonov** [comment]
В логах при выполнении этого запроса не остаётся чего-нибудь интересного?
