### ISSUE TITLE
All statements in "case" are executed

### ISSUE THREAD

**Issue by andrea-s** [yandex/ClickHouse#2496]
83b6f0483a5c :) select case when mycol like '%-%-%' then toDate(mycol) else toDate('2000-01-01') end from (select 'error' as mycol from system.numbers limit 10);

SELECT multiIf(mycol LIKE '%-%-%', toDate(mycol), toDate('2000-01-01'))
FROM
(
    SELECT 'error' AS mycol
    FROM system.numbers
    LIMIT 10
)

Received exception from server (version 1.1.54380):
Code: 33. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Cannot read all data.

0 rows in set. Elapsed: 0.067 sec.

--------------------------------------------------------

It looks like the above query will still try to evaluate toDate(mycol) even if its "when" condition is not matched. Same happens when the query is formulated with a plain "if". This on ClickHouse 1.1.54380.

Cheers

**Comment by filimonov** [comment]
Duplicate: #1562 #2385 #1768 #1816 

AFAIK the task is taken some time ago, so i hope it will be changed soon.

Workarounds are possible, try function toDateTimeOrZero / parseDateTimeBestEffort

**Comment by filimonov** [comment]
Let's continue tracking that issue in #1562
