### ISSUE TITLE
What this errors show by clickhouse-test is critical?

### ISSUE THREAD

**Issue by jonatasfreitasv** [yandex/ClickHouse#2498]
`ClickHouse server version 1.1.54385`

00463_long_sessions_in_http_interface:                          [ FAIL ] - return code 1
00429_long_http_bufferization:                                         [ FAIL ] - return code 1
00374_json_each_row_input_with_noisy_fields:              [ FAIL ] - result differs with reference
00352_external_sorting_and_constants:                          [ FAIL ] - return code 76
00284_external_aggregation:                                           [ FAIL ]
00110_external_sort:                                                        [ FAIL ] - return code 76
00301_csv:                                                                       [ FAIL ]
00107_totals_after_having:                                              [ FAIL ]

**Comment by alexey-milovidov** [comment]
Every package (either testing and stable) pass all tests before we publish it on `repo.yandex.ru`.

You should look at test results. It may be:
- different configuration that prevents some tests to run;
- different build of clickhouse.

**Comment by jonatasfreitasv** [comment]
Thx @alexey-milovidov.

**Comment by alexey-milovidov** [comment]
So, why you get these errors?
