### ISSUE TITLE
[BUG]There is no column with name 

### ISSUE THREAD

**Issue by sundy-li** [yandex/ClickHouse#2500]
*  ClickHouse Version: 1.1.54380

 * Problem:
   Insert to the table  `t_coderate` got some errors. The table on cluster didn't  have column  name`cnt`, but it have  `_cnt` with default value 1
 
   I can't reproduce it on other tables, it confuse me.

* Logs:

   2018.06.13 13:39:17.706317 [ 1774011 ] <Error> executeQuery: Code: 16, e.displayText() = DB::Exception: There is no column with name cnt. There are columns: day, its, anchoruid, coderate, line, p2p, platform_id, version, value, h265, harddecode, iretcode, txp2p, platform, experiment, networktype, sdk, simcardtype, device, originalpainting, experiment_p2p, _cnt, switchp2p, theoryp2p, e.what() = DB::Exception (from 10.64.61.236:36540) (in query: INSERT INTO default.t_coderate (its, platform_id, platform, version, experiment, anchoruid, coderate, h265, harddecode, iretcode, line, networktype, p2p, sdk, device, simcardtype, txp2p, originalpainting, experiment_p2p, value) VALUES), Stack trace:

**Comment by KochetovNicolai** [comment]
Can you provide
* the way how you have created tables
* your cluster configuration
* structure of your tables (show create table)
?

Also, you may check that all replicas has the same schema (run show create table on each node), and that all cluster configs are the same.

**Comment by sundy-li** [comment]
Checked , there are some replicas with different schema, thank you.
