### ISSUE TITLE
NULL values

### ISSUE THREAD

**Issue by kakoni** [yandex/ClickHouse#252]
I know currently null-values are not supported but there was discussion on the mailing list (google groups clickhouse) about limited support coming up in November. Any progress on this?

**Comment by hatarist** [comment]
Seems that it was merged a few days ago. https://github.com/yandex/ClickHouse/pull/70

```
$ ./build/dbms/src/Server/clickhouse --client
ClickHouse client version 1.1.54112.
Connecting to localhost:9000.
Connected to ClickHouse server version 1.1.54112.

:) select NULL;

SELECT NULL

┌─NULL─┐
│   \N │
└──────┘

1 rows in set. Elapsed: 0.003 sec.
```

**Comment by Nopius** [comment]
It looks like clickhouse-client now breaks on importing nullable strings starting with '\'.
Here is my test case:
```
CREATE TABLE test.test2
(
    col1 String
) ENGINE = Memory
CREATE TABLE test.test3
(
    col1 Nullable(String)
) ENGINE = Memory

```
Now try to populate it with clickhouse-client and  'stdin':
-bash-4.2$ echo -e '\\xFFtest' | clickhouse-client --query="insert into test.test2 FORMAT TabSeparated"
-bash-4.2$ echo -e '\\xFFtest' | clickhouse-client --query="insert into test.test3 FORMAT TabSeparated"
Code: 27. DB::Exception: Cannot parse input: expected N before: xFFtest\n: 

Row 1:
Column 0,   name: col1, type: Nullable(String), parsed text: "<BACKSLASH>"ERROR

: (at row 1)

**Comment by alexey-milovidov** [comment]
Confirmed.
Fixed in master.
