### ISSUE TITLE
Where should I specify max  query size? 

### ISSUE THREAD

**Issue by Joozty** [yandex/ClickHouse#2529]
Hi, I would like to ask. Where can I increase [max_query_size](https://clickhouse.yandex/docs/en/operations/settings/settings/#max_query_size)  parameter? I tried to create entry in `config.xml` (`<max_query_size>1000000</max_query_size>` but it didn't help. I am still receiving an error that my query is too big. 

I am using your [Docker image](https://hub.docker.com/r/yandex/clickhouse-server/)

Thanks in advance.

**Comment by filimonov** [comment]
I know that it's not clear from documentation where to put some config parameters. 

You can check if some setting is "user"-setting by checking it in one of those places:
1) `system.settings` table
2) CH sources: https://github.com/yandex/ClickHouse/blob/master/dbms/src/Interpreters/Settings.h
3) CH docs: https://clickhouse.yandex/docs/en/operations/settings/

Generally "user"-settings are relatively dinamic, they can be changed for each user / user group / or for one concrete session. They can be changed in one of those ways:
1) in your users.xml for some concrete user 
2) in your users.xml for some profile which can be used for multiple users,
3) in your users.xml for default profile - in that can it will be used for all user and all profiles
4) if your client support session you can just use `SET setting_name = 'new_value'`
5) for clickhouse-client you can add setting as command-line parameter (check `clickhouse-client --help`)
6) for HTTP interface you can add setting as query parameter. like `http://localhost:8123/?setting_name=value`

In contrast main server setting are listed only here https://clickhouse.yandex/docs/en/operations/server_settings/settings/
and there is not one central place in sources where you can find comprehensive list of them. 
Only those settings should go to config.xml, and the define very important core setting, which can't be changed from user to user - kike ports to listen, data directory path etc.

**Comment by Joozty** [comment]
Thanks, @filimonov I tried to put it into `user.xml` and `config.xml`  files without any effect. 

I also tried to send http request:
`http://localhost:8123/?max_query_size=100000000`

But this seems it doesn't work at all. 
This is the response `Code: 62, e.displayText() = DB::Exception: Empty query, e.what() = DB::Exception`

@dveselov Have you found any solution?

**Comment by filimonov** [comment]
@Joozty what client software do you use?

**Comment by Joozty** [comment]
@filimonov Thanks a lot. I finally found a solution.  Actually `max_query_size` did work. The problem was that the number wasn't high enough.  The number is in bytes, isn't it? Maybe it would be great to write this to the documentation.
