### ISSUE TITLE
 NUMERIC/DECIMAL type

### ISSUE THREAD

**Issue by kakoni** [yandex/ClickHouse#253]
Any chance getting numeric/decimal support for clickhouse?

**Comment by alexey-milovidov** [comment]
We are not going to have native support for NUMERIC/DECIMAL data type in near months.
It is still possible to be implemented in more distant future.

Now we are using UInt64 data type with values, multiplied by fixed amout (like 1 000 000).
For example, we could store price in millionth parts of currency unit.

**Comment by arduanov** [comment]
Decimal is needed to work with financial data, UInt64 is not enough for sum aggregations

**Comment by lidalei** [comment]
C++ does not support decimal natively. But have a look at https://github.com/yandex/ClickHouse/blob/609133ea01803379e340e4c9658d276ea7ac4f9e/dbms/src/AggregateFunctions/AggregateFunctionSum.h#L49 and https://en.wikipedia.org/wiki/Kahan_summation_algorithm.
