### ISSUE TITLE
Command line help using `--help`, `-h` 

### ISSUE THREAD

**Issue by luc-lynx** [yandex/ClickHouse#2546]
It seems options like `--help`, `-h` haven't been supported in clickhouse-server. There's no man page by default and the offitial documentation doesn't have any page dedicated to clickhouse-server's command line arguments.

It would be great to add at least support for `--help` and `-h` options.

```
$ clickhouse-server --help
Unknown option specified: help
$ clickhouse-server -h
Unknown option specified: h
```

**Comment by dvska** [comment]
and for **clickhouse-client** please

**Comment by filimonov** [comment]
`--help` works for clickhouse-client.

**Comment by alexey-milovidov** [comment]
Solved in https://github.com/yandex/ClickHouse/pull/4233
