### ISSUE TITLE
SASL + SCRAM-SHA-256

### ISSUE THREAD

**Issue by alexanderzafirov** [yandex/ClickHouse#2551]
I am trying to setup a materialzed view on top of clickhouse through the kafka integration. Unfortunately I am unable to start clickhouse once the following configuration is in place. Here is the message I get in the `/var/log/clickhouse-server/clickhouse-server.log`:

> 2018.06.22 21:24:07.537483 [ 1 ] <Error> Application: DB::Exception: Failed to create consumer handle: No provider for SASL mechanism SCRAM-SHA-256: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN

I am also using SSL/SCRAM. Here is the relevant part of the config.xml as per the [docs](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md):

```
<kafka>
    <security_protocol>sasl_ssl</security_protocol>
    <sasl_mechanisms>SCRAM-SHA-256</sasl_mechanisms>
    <sasl_username>some_user</sasl_username>
    <sasl_password>some_pass</sasl_password>
</kafka>
```
As I am using an external kafka provider I cannot choose between different type of security in Kafka so I'm stuck with sasl/scram.

Any ideas how to work around this will be greatly appreciated!

**Comment by mcarbonneaux** [comment]
cmake must be ajusted to compile libsasl with librdkafka....

**Comment by filimonov** [comment]
Related #3997

**Comment by abyss7** [comment]
Fixed in v19.8+

**Comment by mcarbonneaux** [comment]
ok they look good ! 

and i see that they use libgsasl !
i've done quasi the same with libsasl from cyrus project...

**Comment by filimonov** [comment]
Related https://github.com/ClickHouse/ClickHouse/pull/12771
