### ISSUE TITLE
crash when using CREATE TEMPORARY TABLE and remote function

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#2560]
Hello,

Having the following schema:

```sql
CREATE DATABASE db1;
CREATE TABLE db1.sessions (user_id Nullable(Int64), lifetime_session_count Nullable(Int64), timestamp DateTime, created_at DateTime) ENGINE = MergeTree PARTITION BY toYYYYMM(timestamp) ORDER BY timestamp;
CREATE TABLE db1.purchases (product Nullable(String), person_id Nullable(Int64), timestamp DateTime, created_at DateTime) ENGINE = MergeTree PARTITION BY toYYYYMM(timestamp) ORDER BY timestamp;
```

The following query is crashing the server:

```sql
CREATE TEMPORARY TABLE `temp1` AS SELECT person_id FROM (SELECT DISTINCT `person_id` FROM remote('127.0.0.1', db1, purchases)) WHERE person_id NOT IN (SELECT DISTINCT user_id FROM remote('127.0.0.1', db1, sessions))
```

Stack:

```sh
2018.06.26 08:37:25.068154 [ 9 ] <Error> BaseDaemon: ########################################
2018.06.26 08:37:25.068241 [ 9 ] <Error> BaseDaemon: (from thread 8) Received signal Segmentation fault: 11 (11).
2018.06.26 08:37:25.068288 [ 9 ] <Error> BaseDaemon: Address: NULL pointer.
2018.06.26 08:37:25.068338 [ 9 ] <Error> BaseDaemon: Unknown si_code.
2018.06.26 08:37:25.068408 [ 9 ] <Error> BaseDaemon: 0. 0   libsystem_platform.dylib            0x00007fff7bba3bbd _platform_memcmp + 29
```

Btw remote table in this example has no sense. I used it here just to create the most simple scenario that's crashing the server.

**Comment by alexey-milovidov** [comment]
Confirmed.

**Comment by silviucpp** [comment]
While investigating this issue I found that problem is in InterpreterSelectQuery line 129 where getQueryContext() point to an already released context.

To avoid such problems maybe it's a better idea to use them as shared_ptr ?

**Comment by alexey-milovidov** [comment]
Yes, but we need to dig deeper, as it may indicate wrong logic in code.

**Comment by extead** [comment]
@alexey-milovidov, I found release 1.1.54343, which works correctly in this case. I hope this helps.

**Comment by silviucpp** [comment]
I tested with master as well today and seems fixed ! 
@alexey-milovidov  I think you can close it

Silviu

**Comment by alexey-milovidov** [comment]
Ok.

The root cause of this issue is more fundamental.
Query context is passed by reference, but sometimes copied to temporary.
Proper fix is still to do.
