### ISSUE TITLE
Select materialized column while querying the underlying column doesn't work

### ISSUE THREAD

**Issue by mdonkers** [yandex/ClickHouse#2567]
Hi,

We have a table with several columns and a few `MATERIALIZED` columns, say:

```
│ errorCount                                   │ UInt64        │              │                                      │
│ erroneous                                    │ UInt8         │ MATERIALIZED │ errorCount > 0                       │
```
(other columns don't matter for now)

If I'm now querying the table with; `select erroneous, errorCount from test_table where errorCount>1;`
it fails with the following message;
```Received exception from server (version 1.1.54380):
Code: 10. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Not found column erroneous in block. There are only columns: errorCount. 

0 rows in set. Elapsed: 0.081 sec. 
```
All other variants work;
- Adding more columns to the `select` clause
- Leaving out the `where` clause
- Filtering on a different column (even on e.g. `erroneous=1`)

Only when selecting the materialized column and underlying column, combined with filtering on the underlying column, the query seems to fail.

**Comment by den-crane** [comment]
your columns have different type that is a bad idea (UInt64 vs UInt8)

though could not reproduce
```

create table testx(errorCount UInt64, erroneous UInt8 MATERIALIZED errorCount) Engine=MergeTree partition by tuple() order by tuple();

insert into testx values (1000000),(2),(3),(4),(5)

┌─erroneous─┬─errorCount─┐
│        64 │    1000000 │
│         2 │          2 │
│         3 │          3 │
│         4 │          4 │
│         5 │          5 │
└───────────┴────────────┘
```

**Comment by mdonkers** [comment]
Closing issue, was due to the way the `select` statement was constructed.
Thanks for the assistance.
