### ISSUE TITLE
CH complains when create a table : DB::Exception: Existing table metadata in ZooKeeper differs in primary key. Stored in ZooKeeper: name, tags, ts, local: name, ts.

### ISSUE THREAD

**Issue by Johnny-Three** [yandex/ClickHouse#2568]
I drop the table  before and  I rebuild it with another primary key .
CH says the different primary key exists in the ZK.
Should I clean the meta data as the time when drop a table ?
If have to , what is the right way to do this ?

**Comment by filimonov** [comment]
Did you drop it on all the replicas?

**Comment by Johnny-Three** [comment]
no . I have two shards and each shard has two replicas. 
Only one shard's replica's  table is dropped.

**Comment by filimonov** [comment]
And that is the reason. If you will drop table on all the replicas then table metadata will be removed from zookeeper. Till that moment any attempts to create table on the same zookeeper path will be considered as attempts to make another replica of that table (and all table replicas should have the same structure).

**Comment by Johnny-Three** [comment]
thanks I'll have a try .

**Comment by alexey-milovidov** [comment]
@filimonov :+1:

**Comment by ManchesterUnited16** [comment]
how to drop all replicas

**Comment by hz0ne** [comment]
I also want to know how to delete all replicas

**Comment by Photon94** [comment]
> I also want to know how to delete all replicas

You should use `on cluster` or `sync` clause, for example:
```sql
drop table my_table on cluster my_cluster;
```

For looking list of your clusters, you can use this statement:
```sql
select distinct cluster from system.clusters;
```
