### ISSUE TITLE
Создание отдельного движка для таблиц

### ISSUE THREAD

**Issue by vixa2012** [yandex/ClickHouse#2575]
Привет ребята, хотел задать пару вопросов. 
1) Можно ли в Click House создавать собственные движки для таблиц, как дополнительный динамический плагин? 
2) Планируете Вы создать отдельный движок таблиц, для динамических данных. 
Чтобы данные можно было обновлять, удалять и быстро искать по ключам.
По сути то выбор в таких таблицах будет происходить лишь по 1 или нескольким записям, в динамических таблицах нет смысла делать select на миллионы записей за раз.
Я бы с удовольствием отказался от использования сторонних баз данных и перешел полностью на clickhouse, если появится такой движок таблиц.

**Comment by alexey-milovidov** [comment]
Привет.

> Можно ли в Click House создавать собственные движки для таблиц, как дополнительный динамический плагин?

Архитектура ClickHouse позволяет добавлять свои движки таблиц, но не динамически. Они должны находиться в кодовой базе ClickHouse, хотя в то же время, их код довольно изолирован.

Для примера смотрите `StorageMemory`, `StorageTinyLog`.

Документация по архитектуре ClickHouse: https://clickhouse.yandex/docs/en/development/architecture/
Видео: https://www.youtube.com/watch?v=g5CDi8Nbut4

> Планируете Вы создать отдельный движок таблиц, для динамических данных.
Чтобы данные можно было обновлять, удалять и быстро искать по ключам.
По сути то выбор в таких таблицах будет происходить лишь по 1 или нескольким записям, в динамических таблицах нет смысла делать select на миллионы записей за раз.

Пока нет, потому что для этого необходимо не только реализовать отдельный движок таблиц, но и адаптировать другие места ClickHouse, связанные с выполнением запросов. Хотя эта задача разрешима, но это не является приоритетным направлением развития.
