### ISSUE TITLE
No Docker Hub tag created for v1.1.54388

### ISSUE THREAD

**Issue by derekperkins** [yandex/ClickHouse#2576]
It looks like the new images were pushed to `latest`, `1` and `1.1`, but there wasn't a new `1.1.54388` tag created.

https://hub.docker.com/r/yandex/clickhouse-server/tags/

![image](https://user-images.githubusercontent.com/3588778/42109935-a07e9c06-7b9c-11e8-8414-61312f2537c5.png)

**Comment by ztlpn** [comment]
Thanks for noticing, I've rebuilt it.
The previous build failed due to some problems with the ubuntu keyserver.
