### ISSUE TITLE
Poco::Exception. Code: 1000

### ISSUE THREAD

**Issue by rpfennin** [yandex/ClickHouse#2577]
I'm seeing this error over and over again in my logs:

2018.06.29 23:48:52.769736 [ 78 ] <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 104, e.displayText() = Connection reset by peer, e.what() = Connection reset by peer

From what i've read, this is related to external dictionaries but I don't have any defined.  Can anyone shed some light?

**Comment by onine007** [comment]
my logs have the same error, How to solve ?

**Comment by rpfennin** [comment]
in my case the issue was haproxy making a tcp check.

**Comment by xiaods** [comment]
@rpfennin  i came across same issue, do you resolve this issue?

**Comment by rpfennin** [comment]
it wasn't anything i needed to resolve.  the logs are still a tad noisy but it doesn't affect anything.  it was just related to the haproxy check.

**Comment by xiaods** [comment]
@rpfennin got it. thanks for your remind
