### ISSUE TITLE
[Question] Clickhouse resharding with clickhouse-copier

### ISSUE THREAD

**Issue by igor-sh8** [yandex/ClickHouse#2579]
Hello. 
We have a question about clickhouse resharding. Maybe someone can give us an advise.
We have cluster of four clickhouse servers (two as shards and two as their replicas). And now we want to improve the cluster by adding two servers (third shard and its replica). But we want not only to add new shard but also to reshard old data between all three servers. How can we do this ? 
We could not find the instruction for such resharding on the official site (https://clickhouse.yandex/docs/en/utils/clickhouse-copier/). 
Is it possible to reshard data with clickhouse-copier, and is there some instruction of configuration for resharding ?

**Comment by KochetovNicolai** [comment]
Yes, you can reshard your data with clickhouse-copier. What's you need is to properly configure your task. Write your current cluster as `<source_cluster>` and cluster with new replicas as `<destination_cluster>`, `<table_pull>` is your current table and `<table_push>` is a table you will reshard to.

**Comment by igor-sh8** [comment]
Hi. 
Thanks for the info. 
So as I understand, we can not use the same table. We need to create a new table in the new cluster, then copy data to this table and then drop old table (if we need it) ?

**Comment by alexey-milovidov** [comment]
> So as I understand, we can not use the same table. We need to create a new table in the new cluster, then copy data to this table and then drop old table (if we need it) ?

Yes. 

Also you can create a new table on the same cluster.
But resharding within the same table on the same cluster is not possible.
