### ISSUE TITLE
Падение процесса после использования windowFunnel

### ISSUE THREAD

**Issue by akonyaev90** [yandex/ClickHouse#2587]
> select  
      session_id,     
      windowFunnel(10)(
          rocket_datetime, 
          ui_type='main_promo_list' and name='section_impression',
          ui_type='promo' and name='click' ) as seq
    from events 
    where     
        rocket_date='2018-04-01'     
        and ((ui_type='main_promo_list' and name='section_impression') 
        	or (ui_type='promo' and name='click'))	
    group by  session_id 
    LIMIT 1000

вот такой запрос убивает базу

> ########################################
2018.07.03 14:07:40.320772 [ 23 ] <Error> BaseDaemon: (from thread 20) Received signal Segmentation fault (11).
2018.07.03 14:07:40.320800 [ 23 ] <Error> BaseDaemon: Address: NULL pointer.
2018.07.03 14:07:40.320820 [ 23 ] <Error> BaseDaemon: Access: read.
2018.07.03 14:07:40.320841 [ 23 ] <Error> BaseDaemon: Unknown si_code.
2018.07.03 14:07:40.383336 [ 23 ] <Error> BaseDaemon: 0. clickhouse-server(DB::ConcatBlockInputStream::readImpl()+0x
d6) [0x4e06276]
2018.07.03 14:07:40.383358 [ 23 ] <Error> BaseDaemon: 1. clickhouse-server(DB::IProfilingBlockInputStream::read()+0x
25a) [0x46f126a]
2018.07.03 14:07:40.383385 [ 23 ] <Error> BaseDaemon: 2. clickhouse-server(DB::Aggregator::execute(std::shared_ptr<D
B::IBlockInputStream> const&, DB::AggregatedDataVariants&)+0x278) [0x51c8618]
2018.07.03 14:07:40.383400 [ 23 ] <Error> BaseDaemon: 3. clickhouse-server(DB::AggregatingBlockInputStream::readImpl
()+0x3b6) [0x50fd716]
2018.07.03 14:07:40.383415 [ 23 ] <Error> BaseDaemon: 4. clickhouse-server(DB::IProfilingBlockInputStream::read()+0x
25a) [0x46f126a]
2018.07.03 14:07:40.383428 [ 23 ] <Error> BaseDaemon: 5. clickhouse-server(DB::ExpressionBlockInputStream::readImpl(
)+0x2e) [0x51378be]
2018.07.03 14:07:40.383441 [ 23 ] <Error> BaseDaemon: 6. clickhouse-server(DB::IProfilingBlockInputStream::read()+0x
25a) [0x46f126a]
2018.07.03 14:07:40.383454 [ 23 ] <Error> BaseDaemon: 7. clickhouse-server(DB::ExpressionBlockInputStream::readImpl(
)+0x2e) [0x51378be]
2018.07.03 14:07:40.383468 [ 23 ] <Error> BaseDaemon: 8. clickhouse-server(DB::IProfilingBlockInputStream::read()+0x
25a) [0x46f126a]
2018.07.03 14:07:40.383486 [ 23 ] <Error> BaseDaemon: 9. clickhouse-server(DB::copyData(DB::IBlockInputStream&, DB::
IBlockOutputStream&, std::atomic<bool>*)+0x81) [0x47068e1]
2018.07.03 14:07:40.383515 [ 23 ] <Error> BaseDaemon: 10. clickhouse-server(DB::executeQuery(DB::ReadBuffer&, DB::Wr
iteBuffer&, bool, DB::Context&, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::al
locator<char> > const&)>)+0x563) [0x4e755a3]
2018.07.03 14:07:40.383534 [ 23 ] <Error> BaseDaemon: 11. clickhouse-server(DB::HTTPHandler::processQuery(Poco::Net:
:HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&)+0x2e07) [0x2d8eb47]
2018.07.03 14:07:40.383550 [ 23 ] <Error> BaseDaemon: 12. clickhouse-server(DB::HTTPHandler::handleRequest(Poco::Net
::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)+0x248) [0x2d90e88]
2018.07.03 14:07:40.383563 [ 23 ] <Error> BaseDaemon: 13. clickhouse-server(Poco::Net::HTTPServerConnection::run()+0
x332) [0x58412a2]
2018.07.03 14:07:40.383576 [ 23 ] <Error> BaseDaemon: 14. clickhouse-server(Poco::Net::TCPServerConnection::start()+
0xf) [0x5839b4f]
2018.07.03 14:07:40.383590 [ 23 ] <Error> BaseDaemon: 15. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x
16a) [0x5839f2a]
2018.07.03 14:07:40.383603 [ 23 ] <Error> BaseDaemon: 16. clickhouse-server(Poco::PooledThread::run()+0x77) [0x58dbd
47]
2018.07.03 14:07:40.383643 [ 23 ] <Error> BaseDaemon: 17. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0
x38) [0x58d7c08]
2018.07.03 14:07:40.383656 [ 23 ] <Error> BaseDaemon: 18. clickhouse-server() [0x92cc1af]
2018.07.03 14:07:40.383667 [ 23 ] <Error> BaseDaemon: 19. /lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x7f1c6c75
1184]

При limit 10 всё отрабатывает

версия 1.1.54388

events - это distributed поверх ReplicatedReplacingMergeTree

**Comment by alexey-milovidov** [comment]
Не хватает структуры таблицы и данных для воспроизведения.

**Comment by blinkov** [comment]
Запрошенная информация не была предоставлена.
