### ISSUE TITLE
Зацикливание команды удаления

### ISSUE THREAD

**Issue by TimonKK** [yandex/ClickHouse#2588]
1. Создал реплицируемую таблицу (удалёный сервер)
2. Залил туда данные (из обычной MergeTree через INSERT INTO ... SELECT ... примерно 200кк записей)
3. На ноуте
   а. пробросил порты для Zookeeper и ClickHouse (чтобы на ноуте были видны сервисы удалённого сервера)
  б. Создал такую же реплицируемую таблицу, минут через 10 данные доехали.
4. На удалёном сервер в консоле запустил команду удаления части данных
ALTER TABLE ... DELETE WHERE date >= '20178-06-01'
5. В лог пишет такое "String is too long for Date: 20178-06-01" (сообщение циклически повторяется)

В документации
https://clickhouse.yandex/docs/ru/query_language/queries/#_7
написано что
"Откатить мутацию после её добавления нельзя."

Вопрос: что делать?

**Comment by ztlpn** [comment]
Можно вручную удалить команду мутации из ZooKeeper и тогда сервер её пропустит. Для этого нужно узнать ID мутации из таблицы `system.mutations`, соответствующая znode находится в ZK по пути `<path_to_table>/mutations/<id>`.

**Comment by ztlpn** [comment]
Для предотвращения такого в дальнейшнем, надо усилить валидацию команд мутации.

**Comment by TimonKK** [comment]
Спасибо, буду пробовать

**Comment by TimonKK** [comment]
Помогло:
1. запустил zookeeper cli (bin/zkCli.sh)
2. rmr <path_to_table>/mutations/XXXXXXXXXX

**Comment by filimonov** [comment]
На новых версиях можно использовать команду KILL MUTATION чтобы удалить ненужные мутации.
