### ISSUE TITLE
Looks like ALTER TABLE t DELETE... not cleaning disk space actually

### ISSUE THREAD

**Issue by berghauz** [yandex/ClickHouse#2589]
OPTIMIZE also haven't any effect, i haven't checked FINAL because many chunks can be affected at ones and it is a lot of handworks.
Clarify please, what is underlying under DELETE process and how we can reuse free space after.

In mongodb, for example, we should restart instance for changes have taken in account.

**Comment by berghauz** [comment]
I'm sorry, it's my fault. I'm checking another table when comparing size...
btw, any chance to support ON CLUSTER in future?

**Comment by ztlpn** [comment]
ON CLUSTER should work, the syntax is (just as with other ALTER commands):
```sql
ALTER TABLE [db].table ON CLUSTER 'cluster' DELETE WHERE expr
```

**Comment by berghauz** [comment]
Thank you!
