### ISSUE TITLE
ограничение в 500к записей у flat словарей

### ISSUE THREAD

**Issue by aCLr** [yandex/ClickHouse#2591]
Есть таблица в бд, в которой 10к записей, но присутствуют записи с id > 500000 (не спрашивайте :)). 
Можно ли сделать так, чтобы перед загрузкой проверялось количество записей в источнике, а не их айди?

**Comment by KochetovNicolai** [comment]
Нет, для flat словарей так сделать не получится. Для flat словарей используется прямая адресация, из-за этого они быстро работают и имеют ограничение по памяти. В случае, если есть id со значением > 500000, можно:
* Сделать преобразование id руками так, чтобы они укладывались в требуемый интервал.
* Использовать hashed словарь. Для 10k записей он будет работать достаточно быстро.

**Comment by KochetovNicolai** [comment]
Поиск по атрибутам в словаре будет работать одинаково (неоптимально) как для словарей типа flat, так и для hashed. В таком подзапросе сначала будет прочитан весь словарь (для hashed это может работать даже чуть быстрее), а затем сформировано множество из id (которое тоже хеш-таблица).

Для поиска по атрибутам использование словаря примерно равнозначно использованию обычной таблицы (а в случае, если в подзапросе будет отсечение по первичному ключу - то таблица лучше). Если словарь не используется для поиска по ключам, то можно заменять.

**Comment by aCLr** [comment]
Благодарю за объяснения
