### ISSUE TITLE
Unknown identifier when a column is referenced in subquery

### ISSUE THREAD

**Issue by buremba** [yandex/ClickHouse#26]
The following query doesn't work and complains that `t` used in subquery is an unknown identifier.

`select (select t), (select dummy), t from system.one array join([1,2] as t)`

I guess the problem is that `t` comes from ARRAY JOIN and the subqueries can only reference columns from the table `system.one`. I think that this is a consistency problem, however; if it's a technical restriction, the documentation should state it.

**Comment by duremar** [comment]
subquery can't reference columns from outer query. correlated queries are impossible for now.

**Comment by alexey-milovidov** [comment]
Added note about that to documentation: https://github.com/yandex/ClickHouse/commit/fa98bd6789aa474cbb1e9c7cf684b2773e94e626

> subqueries can only reference columns from the table system.one

And from other available tables too; but not from outside.

**Comment by blinkov** [comment]
@dveselov in nearest plans are improvements for normal JOINs, the priority of correlated subqueries is not clear yet

**Comment by filimonov** [comment]
https://github.com/yandex/ClickHouse/issues/6697
