### ISSUE TITLE
Support of INET type and eventually other existing network types (similar to postGRE)

### ISSUE THREAD

**Issue by Matt-Texier** [yandex/ClickHouse#2605]
Hi Guys,

This is more a roadmap question. 

I am in the process of using clickhouse for network logs collection. I wanted to know if there is any plan to expose new types from clickhouse dedicated to network information.

As an example postGRESQL supports INET, cidr and MAC address. 

As far as I can see, all storage work for network information has been done (uint32 for IPv4, string16 for IPv6) and conversion functions between UNIT32 and a readable IPv4 and STRING(16) and readable IPv6 are provided, however, manipulation of those date type gets a bit complicated to upper layers (typically like SQLAlchemy) as those once have no clue about the "real" type of those data and the way they should expose it. Metadata telling SQLAlchemy that data are either UINT32 or STRING ... not obvious to attached a specific semantic. On top of that string(16) for IPv6 gives none UTF-8 strings which make things even more complicated.

It is making upper layer like UI and frontend have a specific branch for clickhouse and makes some existing tools like superset unusable with those IPv4 and IPv6 fields.

Do you have any plan to complete existing features and development by adding support of specific types ? Something similar to postGRE: INET, cidr, MAC would be awesome.

I would be happy to contribute but starting almost from 0 on clickhouse code ... It will take me ages to do so.

Thanks a lot,
Matthieu.

**Comment by alex-zaitsev** [comment]
PostgreSQL network types: https://www.postgresql.org/docs/9.1/static/datatype-net-types.html

**Comment by blinkov** [comment]
It makes sense to add those some day, but at the moment decimal/numeric seems to be in much higher demand.

**Comment by alex-zaitsev** [comment]
What about SQL domains? That does not change internal representation, mostly type name aliasing.
https://www.postgresql.org/docs/9.1/static/sql-createdomain.html

**Comment by simPod** [comment]
@blinkov @alex-zaitsev Hi, any way this could get reevaluated?

**Comment by alex-zaitsev** [comment]
@simPod , there are IPv4 and IPv6 datatypes already. Does it work for you or you are looking for PostgreSQL compatibility?

**Comment by Matt-Texier** [comment]
Support of IPv4 and IPv6 types has been added and it works fine.

See this snippet of an example of model using those types:

```sql
CREATE TABLE telemetry.enriched_flows
(
    full_time_stamp DateTime, 
    bin_cycle_sec UInt16, 
    as_src UInt32, 
    as_dst UInt32, 
    comms String, 
    as_path String, 
    local_pref UInt32, 
    peer_as_dst UInt32, 
    peer_as_src UInt32, 
    peer_ip_dst String,
    ip_version LowCardinality(String), 
    ipv4_src IPv4,
    ipv6_src IPv6,
    net_src String, 
    ipv4_dst IPv4,
    ipv6_dst IPv6, 
```

After writing few patch's those types are also supported by SQLAlchemy driver proposed by this repository:

https://github.com/xzkostyan/clickhouse-sqlalchemy

So you have all foundation code to build up something great using those types...

My 2 cents !

**Comment by simPod** [comment]
@alex-zaitsev ipv4 and ipv6 are great. Now I'm looking for a way to store '0.0.0.0/0' properly. I.e. for Inet type.
