### ISSUE TITLE
PrimaryKey on Array, Nested datatypes

### ISSUE THREAD

**Issue by shawel** [yandex/ClickHouse#2606]
Hi, 

I could not find documentation on the behaviors of array datatype columns when used in primary keys. My experiment does a full scan even filtering on  array[1] values..  is that the expected behavior? 

Thanks

**Comment by KochetovNicolai** [comment]
Arrays can be used as a primary key. However, arrays are stored continuously as a pair of columns with values and offsets. So, primary key can't be used for single array element. You need to settle a condition on full array in order to get profit from pk.

If you know the exactly number of columns you need to store, try to use tuple. Tuples are stored like a set of separate columns for each tuple element, so filtering by single element will work.

**Comment by shawel** [comment]
Thanks @KochetovNicolai  for the response. 

> If you know the exactly number of columns you need to store, try to use tuple

The array length  is very arbitrary (~100 average length) so tuple might not work.

> You need to settle a condition on full array in order to get profit from pk

In my use case i have two columns. Id (string) and Category Array(string). I was using something like arrayExists(x->  x='keyword', category) on the category column and filter out user id for specific categories. and this does a full scan (i have about 500mil rows)

My hope is to cut down on the number of rows by leveraging the index. I see that is not possible with array index.  Is there any way to achieve this outside of exploding each category per row.

Thanks

**Comment by alexey-milovidov** [comment]
> Is there any way to achieve this outside of exploding each category per row.

No, this is the only way.

**Comment by filimonov** [comment]
>I was using something like arrayExists(x-> x='keyword', category) on the category column and filter out user id for specific categories. and this does a full scan (i have about 500mil rows)
>My hope is to cut down on the number of rows by leveraging the index. 

If number of categories is limited - you can just add separate columns to flag them. Even if they will not be in PK - scan on of columns with simple datatype will be much faster than scan for strings inside array. 

I.e.
```sql
ALTER TABLE name ADD COLUMN category_contains_keyword UInt8 DEFAULT arrayExists(x-> x='keyword', category) ...;
```
For 500 mln rows that extra columns should be too big (500 Mb uncompressed, compressed would be about 8 times smaller, as only one bit will be used). 

If smaller amount of rows will have that category setup ( <10% ) PREWHERE will filter needed rows almost as fast as with using index.

Also you can add that column to PK. But it not always will give good results (depends on the current  table structure and typical requests pattern).

**Comment by shawel** [comment]
@filimonov thanks for the suggestion! I have about 5000 categories in total.  I will try and see if creating columns on the prefix of the categories might help to cut it down to about ~500, or maybe convert to columns only heavily used categories. 

Thanks!
