### ISSUE TITLE
How to alter max_bytes_to_merge_at_max_space_in_pool for the table?

### ISSUE THREAD

**Issue by den-crane** [yandex/ClickHouse#2607]
I created a table 

create table x (a Int64) Engine=MergeTree Partition by tuple() order by tuple()
settings max_bytes_to_merge_at_max_space_in_pool = 214748364800;

How to alter max_bytes_to_merge_at_max_space_in_pool to another value?

Can I do detach / fix x.sql / attach ?
The same question if a table is replicated.

**Comment by ztlpn** [comment]
Currently there is no command to alter table settings. So yes, detach x / fix x.sql / attach x is the correct way to do it. For replicated tables you can change settings independently for each replica (except the `index_granularity` setting which must be equal for all replicas).
