### ISSUE TITLE
CI pass even when there are errors during build/test run

### ISSUE THREAD

**Issue by simPod** [yandex/ClickHouse#2617]
Shouldn't Travis run tests located in `tests` folder so we know when something is broken in a commit?

**Comment by simPod** [comment]
Also, it passes when there's a build error

```
1 error generated.
[796/1396] Building CXX object contrib/poco/Data/CMakeFiles/Data.dir/src/StatementImpl.cpp.o
ninja: build stopped: subcommand failed.
+date
Mon Jul  9 21:06:43 UTC 2018
The command "utils/travis/normal.sh" exited with 0.
```

**Comment by simPod** [comment]
@alexey-milovidov oh I see. I tried to break the test and the build passed so I though it's not run.

Probably the issue is just error code 0 when there is an error

**Comment by alexey-milovidov** [comment]
We have two Travis jobs for each commit.

This is for your pull request:
https://travis-ci.org/yandex/ClickHouse/builds/401968092?utm_source=github_status&utm_medium=notification

Second job is failed as expected:
https://travis-ci.org/yandex/ClickHouse/jobs/401968094

Although the first job passed. As I remember, it is designed as a "dry run" for different environment.
