### ISSUE TITLE
Process not exit on interrupt

### ISSUE THREAD

**Issue by miolini** [yandex/ClickHouse#265]
Hello!

When I try to run server in Docker with you official image and try to stop the interactive console nothing happening. One way to stop the docker container is send SIGKILL signal to server pid process.

Command to start server in Docker (try to send CTRL-C after):
```bash
# docker run --rm --name clickhouse --ulimit nofile=262144:262144 yandex/clickhouse-server
```

**Comment by hatarist** [comment]
Shouldn't you start it with the `-t` flag?
(and, perhaps, with an `-i`, I'm not that familiar with Docker, sorry)
```
-i              : Keep STDIN open even if not attached
-t              : Allocate a pseudo-tty
```

**Comment by hatarist** [comment]
Shouldn't you start it with the `-i` and `-t` flags to be able to control the container's terminal?
```
-i              : Keep STDIN open even if not attached
-t              : Allocate a pseudo-tty
```

> If you use `-t` and `-i` then `Control-C` will terminate the container. 
> When using `-i` with `-t` then you have to use `Control-P` `Control-Q` to detach without terminating.

(reference: https://github.com/docker/docker/issues/2838#issuecomment-29176882)

**Comment by miolini** [comment]
Sorry. My fault.
