### ISSUE TITLE
Can you allow to alter enum key columns ?

### ISSUE THREAD

**Issue by TH-HA** [yandex/ClickHouse#2667]
Enum are a nice way to have more compact and efficient column in Clickhouse. Even if those enum are generally pretty static , they may change from time to time.  Enum list is part of the column declaration and then cannot be modified if the column is part of the key.  
Is it possible to allow enum modification if they are not impacting the underlying storage? This can be ( and this is the main use case ) to only allow extension of this enum definition.

**Comment by champtar** [comment]
Hi @TH-HA 
you might be interested in this PR #1567

**Comment by champtar** [comment]
Hi @TH-HA I just tested with latest master and it works
```
CREATE TABLE testenum
(
    date Date, 
    datetime DateTime, 
    a Enum8('GET' = 1, 'POST' = 2, 'HEAD' = 3, 'PUT' = 4, 'DELETE' = 5, 'OPTIONS' = 6, 'TRACE' = 7, 'CONNECT' = 8)
)
ENGINE = MergeTree
PARTITION BY date
ORDER BY (date, toStartOfMinute(datetime))
SETTINGS index_granularity = 8192

INSERT INTO testenum VALUES (toDate('2018-08-20'),toDateTime('2018-08-20 00:00:00'),'GET');
OK.

INSERT INTO testenum VALUES (toDate('2018-08-20'),toDateTime('2018-08-20 00:00:00'),'NEWVERB');                                                                                             
Exception on client:
Code: 49. DB::Exception: Unknown element 'NEWVERB' for type Enum8('GET' = 1, 'POST' = 2, 'HEAD' = 3, 'PUT' = 4, 'DELETE' = 5, 'OPTIONS' = 6, 'TRACE' = 7, 'CONNECT' = 8)

ALTER TABLE testenum MODIFY COLUMN a Enum8('GET' = 1, 'POST' = 2, 'HEAD' = 3, 'PUT' = 4, 'DELETE' = 5, 'OPTIONS' = 6, 'TRACE' = 7, 'CONNECT' = 8, 'NEWVERB'=9);

INSERT INTO testenum VALUES (toDate('2018-08-20'),toDateTime('2018-08-20 00:00:00'),'NEWVERB');
OK.
```

**Comment by alexey-milovidov** [comment]
This feature was implemented 1.5 years ago in https://github.com/yandex/ClickHouse/commit/9918965c

**Comment by alexey-milovidov** [comment]
And here is the test: https://github.com/yandex/ClickHouse/blob/master/dbms/tests/queries/0_stateless/00427_alter_primary_key.sh

**Comment by develar** [comment]
Doesn't work.

```
default> alter table report modify column product Enum8('IU' = 1, 'WS' = 2, 'PS' = 3)
[2019-10-25 12:29:44] Code: 44, e.displayText() = DB::Exception: Trying to ALTER key column product (version 19.15.2.2 (official build))
```

Current type: `Enum8('IU' = 1, 'WS' = 2)`

**Comment by filimonov** [comment]
@develar thanks for the report. Raised to separate issue #7513.
