### ISSUE TITLE
Remote connect fail

### ISSUE THREAD

**Issue by dmitrydrynov** [yandex/ClickHouse#2673]
I can't connect from my website tabix.mysite.com:8123
"Login or connect error, check host:port,login & password"

localhost:8123 on server is ok

![image](https://user-images.githubusercontent.com/4089575/42884227-7df2abb4-8aa6-11e8-8e5a-72cd3c6d5e7f.png)

User config
![image](https://user-images.githubusercontent.com/4089575/42884272-98c1b0b6-8aa6-11e8-8d80-d063014cf50b.png)

Help me please

**Comment by filimonov** [comment]
Please. Check [listen_host](https://clickhouse.yandex/docs/en/operations/server_settings/settings/#listen_host) directive and your firewall/network settings.

**Comment by dmitrydrynov** [comment]
the same problem

I try
<listen_host>::</listen_host>

In previous version its worked. I updated clickhouse and has this problem now

**Comment by dmitrydrynov** [comment]
Start clickhouse-server service: Path to data directory in /etc/clickhouse-server/config.xml: /var/lib/clickhouse/
DONE

**Comment by dmitrydrynov** [comment]
I deleted clickhouse and install again. I have the problem

` sudo apt-get install -y clickhouse-server cl                                                                                                                               ickhouse-client
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  clickhouse-common-static
The following NEW packages will be installed:
  clickhouse-client clickhouse-common-static clickhouse-server
0 upgraded, 3 newly installed, 0 to remove and 4 not upgraded.
Need to get 0 B/67.0 MB of archives.
After this operation, 235 MB of additional disk space will be used.
Selecting previously unselected package clickhouse-common-static.
dpkg: warning: files list file for package 'onlyoffice-documentserver' missing;                                                                                                                                assuming package has no files currently installed
(Reading database ... 150289 files and directories currently installed.)
Preparing to unpack .../clickhouse-common-static_1.1.54394_amd64.deb ...
Unpacking clickhouse-common-static (1.1.54394) ...
Selecting previously unselected package clickhouse-client.
Preparing to unpack .../clickhouse-client_1.1.54394_all.deb ...
Unpacking clickhouse-client (1.1.54394) ...
Selecting previously unselected package clickhouse-server.
Preparing to unpack .../clickhouse-server_1.1.54394_all.deb ...
Unpacking clickhouse-server (1.1.54394) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up clickhouse-common-static (1.1.54394) ...
Setting up clickhouse-client (1.1.54394) ...
Setting up clickhouse-server (1.1.54394) ...
update-rc.d: /etc/init.d/clickhouse-server exists during rc.d purge (use -f to f                                                                                                                               orce)
dpkg: error processing package clickhouse-server (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for ureadahead (0.100.0-16) ...
Errors were encountered while processing:
 clickhouse-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
`

**Comment by dmitrydrynov** [comment]
This problem is relevant
I can't use clickhouse (

![image](https://user-images.githubusercontent.com/4089575/43049608-1bf6e6fe-8e03-11e8-9bb1-f3f6dd5b45ad.png)

**Comment by dmitrydrynov** [comment]
it turned out successfully to reinstall but ... :)
"Unknown setting tabix_client"

2018.07.24 19:27:16.835933 [ 3 ] <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: OPTIONS, Address: [::ffff:37.17.18.150]:63530, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
2018.07.24 19:27:16.836008 [ 3 ] <Trace> HTTPHandler: Request URI: /query?tabix_client=18.07.1&random=69452214
2018.07.24 19:27:16.868678 [ 3 ] <Error> HTTPHandler: Code: 115, e.displayText() = DB::Exception: Unknown setting tabix_client, e.what() = DB::Exception, Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x56b1a76]
1. clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x22) [0x2da8462]
2. clickhouse-server(DB::Settings::set(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x11ab) [0x4eb2c0b]
3. clickhouse-server(DB::Context::setSetting(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x9e) [0x4dfd16e]
4. clickhouse-server(DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&)+0x2eb2) [0x2dc2a72]
5. clickhouse-server(DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)+0x248) [0x2dc4e08]
6. clickhouse-server(Poco::Net::HTTPServerConnection::run()+0x332) [0x58ad422]
7. clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x58a5ccf]
8. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x16a) [0x58a60aa]
9. clickhouse-server(Poco::PooledThread::run()+0x77) [0x5947e47]
10. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x5943d08]
11. clickhouse-server() [0x936dc0f]
12. /lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x7f1a7882b184]
13. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f1a7804e03d]

**Comment by dmitrydrynov** [comment]
hm, after the next update, everything worked
