### ISSUE TITLE
[Question] Multiple groupArray functions run on only one CPU core

### ISSUE THREAD

**Issue by paruru48** [yandex/ClickHouse#2679]
I have 2 table `test_cl_1` and `test_cl_2` (both with `Memory` engine) and want to match rows of 2 table based on some condition.
I wrote a query like below. I notice that when the query runs only one CPU of my server reaches 100% and the rest is all 0%. And, seems like it taking too long before `<Debug> executeQuery: Query pipeline`.
```
SELECT 
    field1, 
    timestamp, 
    r_field1, 
    t.2[num] AS r_timestamp, 
    t.3[num], 
    t.4[num], 
    t.5[num], 
FROM 
(
    SELECT 
        field1, 
        timestamp, 
        (
            SELECT 
                groupArray(field1), 
                groupArray(timestamp), 
                groupArray(field2), 
                groupArray(field3), 
                groupArray(field4), 
                groupArray(field5), 
            FROM test_cl_2 
            WHERE field2 IN (144, 148, 181)
        ) AS t
    FROM test_cl_1
    WHERE (field2 IN (1, 2, 3, 4, 6, 7, 8, 17, 19, 21, 22, 23))
) 
ARRAY JOIN 
    t.1 AS r_field1, 
    arrayEnumerate(t.1) AS num
WHERE (field1 = r_field1) AND (((timestamp - r_timestamp) >= 0) AND ((timestamp - r_timestamp) <= 60))
```
`0 rows in set. Elapsed: 52.476 sec. Processed 20.94 million rows, 2.15 GB (398.94 thousand rows/s., 41.03 MB/s.)`

**Comment by vpanfilov** [comment]
Your guery is not optimal. Try to group your data by `field1`, join tables and do some magic with `ARRAY JOIN` and higher order functions. `GROUP BY` clause will help you go multicore:

Here is a sample query for futher experiments:
```sql
SELECT
  *
FROM
((SELECT 
  field1,
  groupArray(timestamp) AS timestamp_cl1
FROM test_cl_1
WHERE (field2 IN (1, 2, 3, 4, 6, 7, 8, 17, 19, 21, 22, 23))
GROUP BY field1)
ANY INNER JOIN
(SELECT 
  field1,
  groupArray(timestamp) AS timestamp_cl2
  groupArray(field2) AS field2,
  groupArray(field3) AS field3,
  groupArray(field4) AS field4,
  groupArray(field5) AS field5
FROM test_cl_2 
WHERE field2 IN (144, 148, 181)
GROUP BY field1)
USING field1)
```

P.S. I can't write full query or test it without data

**Comment by alexey-milovidov** [comment]
ClickHouse parallelize work for different rows (actually - for blocks of data).
In your case, the `groupArray` aggregation is almost not parallelized, because most of the time is spent on collecting data in the single huge result row.

Processing of multiple rows is parallelized, but for single huge array - it is not.
There are many opportunities for improvement.
