### ISSUE TITLE
Silent import via clickhouse-client

### ISSUE THREAD

**Issue by dvska** [yandex/ClickHouse#2682]
CentOS, ClickHouse client version 1.1.54390.

 ```wc -l log_records_unsent_to_clickhouse.JSONEachRow```
4727 

```clickhouse-client   --query="INSERT INTO table Log_buffer FORMAT JSONEachRow" <  log_records_unsent_to_clickhouse.JSONEachRow```

actually inserts, but say nothing. Some prev version was more talkative.

**Comment by VadimPE** [comment]
Yes, it is normal. If your query fell, you would see error message.

**Comment by VadimPE** [comment]
You can use `--echo`

**Comment by alexey-milovidov** [comment]
Now you can also use
`--send_logs_level=trace`
option for clickhouse-client.

It is available in master.
