### ISSUE TITLE
[Question] Postgres vs Clickhouse stress tests

### ISSUE THREAD

**Issue by CompadreP** [yandex/ClickHouse#2684]
Hello! 

At the moment I'm deciding what dbms to choose for quite simple goal. We need to show real-time analytics with simple sum aggregates for different periods. So I decided to compare ClickHouse and Postgres on the same type of load. Unfortunately ClickHouse shows significantly worse characteristics for my tests. May be I am doing something wrong? Or should I tweak settings somehow?

Here is some test's info:

## Virtual machine
Virtual machine is in google cloud (compute engine)
OS - Ubuntu 18.04 LTS
Cores - 4
RAM - 26G
Disk - 300G - Standard persistent disk(HDD)

## Postgres

```
                                                          version                                                           
-----------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 10.4 (Ubuntu 10.4-0ubuntu0.18.04) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0, 64-bit

```

```
                Table "public.receipt"

  Column   |            Type             | Nullable |
-----------+-----------------------------+----------+
id         | bigint                      | not null |
kkt_sn     | bigint                      | not null |
created_at | timestamp without time zone | not null |
type       | smallint                    | not null |
amount     | double precision            | not null |
Indexes: 
   "receipt_pkey" PRIMARY KEY, btree (id) 
   "receipt_id_uindex" UNIQUE, btree (id) 
   "kkt_sn_cereated_at_index" btree (kkt_sn, created_at) 
```
## ClickHouse

```
ClickHouse server version 1.1.54390
```

```
TABLE receipt 
( 
   id UInt64 DEFAULT CAST(0, 'UInt64'),  
   kkt_sn UInt64 DEFAULT CAST(0, 'UInt64'),  
   created_at_date Date DEFAULT CAST('1970-01-01', 'Date'),  
   created_at_datetime DateTime DEFAULT CAST('0000000000', 'DateTime'),  
   type UInt16 DEFAULT CAST(0, 'UInt16'),  
   amount Float64 DEFAULT CAST(0, 'Float64') 
) 
ENGINE = MergeTree() 
PARTITION BY toYYYYMM(created_at_date) 
ORDER BY (created_at_datetime, kkt_sn) 
SETTINGS index_granularity = 8192
```

## Generated data

days = 33
n_serials = 100000  # how much unique values in column kkt_sn 
avg_receipts = 100  # how much records (average) for each kkt_sn for each day

Total records generated - 356019972

## Disk usage
Postgres - 56G
Clickhouse - 4.9G

### Queries generation
Generated queries were quite simple.
```
SELECT sum(amount) FROM receipt WHERE kkt_sn IN ({10 random existing values}}
```
for sums for all available dates.
And appendixes for filtering by dates:
Postgres
```
AND created_at >= {random datetime}
AND created_at < {same datetime + shift(one of 1,7,30 days)}
```
ClickHouse
```
AND created_at_datetime >= {random datetime}
AND created_at_datetime < {same datetime + shift(one of 1,7,30 days)}
```
queries_versions = 100  # each version of query has its own kkt_sn set

Prefixes:
PG - results for postgres
CH - results for clickhouse-а

### Queries execution

Client was my local machine. At first all queries were executed in postgres, then all same queries were executed in clickhouse.

#### Sequential reads

Each version of query executed only one time and only in one connection. 

Filtering by random period of one day
PG_FIRST_TIME_SUM_1_DAY | 0.1955
CH_FIRST_TIME_SUM_1_DAY | 0.5602

Filtering by random period of seven days
PG_FIRST_TIME_SUM_WEEK | 0.2683
CH_FIRST_TIME_SUM_WEEK | 0.7833

Filtering by random period of thirty days
PG_FIRST_TIME_SUM_30_DAYS | 0.2702
CH_FIRST_TIME_SUM_30_DAYS | 1.6629

Filtering by random period of all available dates (33 days)
PG_FIRST_TIME_SUM_ALL | 0.2313  
CH_FIRST_TIME_SUM_ALL | 4.2138

#### Parallel reads

queries_tries = 10  # how many times repeat each query
pool_size = 99  # how much connections

Filtering by random period of one day
PG_TIMES_SUM_1_DAY | 0.2093
CH_TIMES_SUM_1_DAY | 3.7097

Filtering by random period of seven days
PG_TIMES_SUM_WEEK | 0.2123
CH_TIMES_SUM_WEEK | 23.6476

Filtering by random period of thirty days
PG_TIMES_SUM_30_DAYS | 0.2234
CH_TIMES_SUM_30_DAYS | 102.7503

Filtering by random period of all available dates (33 days)
PG_TIMES_SUM_ALL | 0.2651
CH_TIMES_SUM_ALL | 236.2448

While running parallel tests I saw full utilization of cores for both postgres and clickhouse

I will be very grateful for the feedback!

**Comment by filimonov** [comment]
1) there were few issues with IN operator in recent versions of Clickhouse
2) try to replace WHERE to PREWHERE in your query.
3) Isn't your kkt_sn is some kind of autoincrement / other unique id for accessing single record? If so - please remember that Clickhouse is not good for point selects. It's main scenario is do some operations on huge range of data, not on single rows. Please check the section "When NOT to use ClickHouse" on https://clickhouse.yandex/ "Key-value access with high request rate" is what you're trying to benchmark.

**Comment by Deninc** [comment]
Hi @CompadreP, have you done any further test in this regard?

**Comment by CompadreP** [comment]
@Deninc We decided to use postgres for this case because it handles this type of workload much better

**Comment by gajus** [comment]
@filimonov Is this issue specific to the `IN` operator?

**Comment by filimonov** [comment]
> @filimonov Is this issue specific to the IN operator? 

In spring 2018 there were few issues connected with using (or rather "not using") primary key for IN operators. They are fixed right now (dig the changelog somewhere in March-May 2018 for details).

**Comment by filimonov** [comment]
And 'key-value' usage doesn't suit ClickHouse well independently of using IN operator. ClickHouse does the best in processing ranges of data (like do some daily aggregations), not in single row access.
