### ISSUE TITLE
Use `stable` branch for the reference pages at clickhouse.yandex

### ISSUE THREAD

**Issue by hatarist** [yandex/ClickHouse#270]
It'd be awesome to show the stable version of the docs at the http://clickhouse.yandex/ site.

I suppose, most of the users will use the stable/packaged version and not the bleeding-edge one. 
There are currently some differences between the reference and the stable version (for example, UUID functions aren't available yet in the stable branch) that confuse users.

**Comment by ludv1x** [comment]
Let denote "stable release" is when stable branch is build and published to ClickHouse deb repository (so you can update it via `apt-get`)

As I know, on each "stable release" contents of https://clickhouse.yandex/ is updated with respect to contents of doc/ directory of stable branch.

It is worth noting that appearing of new stable tag in "origin" repo doesn't mean that "stable release" will be  100% published. Up to 2 days are required to test stable branch. If there are no problems detected during the testing, release could be published.

**Comment by hatarist** [comment]
> As I know, on each "stable release" contents of https://clickhouse.yandex/ is updated with respect to contents of doc/ directory of stable branch.

Hm, but there is no any mention of UUIDNumToString/UUIDStringToNum in https://github.com/yandex/ClickHouse/blob/stable/doc/reference_ru.html at the moment, but there is at https://clickhouse.yandex/reference_ru.html.

I recall when my commits with the reference improvements were merged it was also deployed pretty fast, so maybe it still updates on every push to `master` or so.

> It is worth noting that appearing of new stable tag in "origin" repo doesn't mean that "stable release" will be 100% published. Up to 2 days are required to test stable branch. If there are no problems detected during the testing, release could be published.

Yeah, I understand - but still, 2 days is still less than - how long was it, ~10 days? - since UUID functions were added in both the source code and the documentation :)

I don't really want to mess or intercept the Yandex's way of doing things, especially when it comes to deploying to your own servers. I just think it'd be more convenient/clear for the users.

**Comment by alexey-milovidov** [comment]
In fact, stable tag is created (and stable branch is updated) at publishing of packages.
Publishing of packages is ordered manually and usually done after release was deployed in production on our clusters.

**Comment by ludv1x** [comment]
@alexey-milovidov If per-commits builds will be introduced, we can add an artefact which will publish docs/ in master branch to https://clickhouse.yandex/master/

**Comment by alexey-milovidov** [comment]
I want single version of docs published: for single landing page.
(There are difficulties if many version of docs are available, especially for search traffic. Examples: MySQL, boost.)
