### ISSUE TITLE
windowFunnel() NULL pointer error

### ISSUE THREAD

**Issue by huang--yijian** [yandex/ClickHouse#2700]
We are using windowFunnel() function of 1.1.54390. The following SQL gives NULL pointer error, and makes the Clickhouse server process crashed.
Is something wrong with our following SQL? 

SELECT
    level,
    count() AS c
FROM
(
    SELECT
        deviceId,
        windowFunnel(3600)(toUInt32
(clientTime), srcPageId = '4695760', srcPageId = '4371702') AS level
    FROM client_log_all
    WHERE serverDate = '2018-04-16'
    GROUP BY deviceId
)
GROUP BY level
ORDER BY level

Note that clientTime is Int64, so we have to convert it to UInt32.

Table structure:
CREATE TABLE default.client_log_all ( serverDate Date,  channel String,  version String,  carrierOperator String,  deviceId String,  deviceName String,  deviceType String,  manufacturer String,  networkMode String,  os String,  ip String,  userAgent String,  serverTime UInt64,  uid String,  height UInt32,  width UInt32,  latitude Float64,  longitude Float64,  responseCode String,  resource String,  clientTime UInt64,  tid String,  traffic String,  playResource String,  srcPage String,  srcPageId String,  srcModule String,  srcPosition String,  srcSubModule String,  moduleType String,  item String,  itemId String,  appName String,  x_abtest_bucketIds String,  offline_data_gentime UInt64,  x_client_sendtime UInt64,  type String,  copy UInt32) ENGINE = Distributed(four, default, client_log, rand())

Here is the detailed error:

2018.07.23 12:35:26.357896 [ 26 ] <Trace> Aggregator: Merging aggregated data
2018.07.23 12:35:26.600817 [ 25 ] <Trace> Aggregator: Read 1024 blocks of partially aggregated data, total 1299132 rows.
2018.07.23 12:35:26.601869 [ 25 ] <Trace> Aggregator: Merging partially aggregated two-level data.
2018.07.23 12:35:26.639062 [ 25 ] <Trace> Aggregator: Merged partially aggregated two-level data.
2018.07.23 12:35:26.639460 [ 25 ] <Trace> Aggregator: Converting aggregated data to blocks
2018.07.23 12:35:26.639908 [ 39 ] <Error> BaseDaemon: ########################################
2018.07.23 12:35:26.639957 [ 39 ] <Error> BaseDaemon: (from thread 38) Received signal Segmentation fault (11).
2018.07.23 12:35:26.639968 [ 39 ] <Error> BaseDaemon: Address: NULL pointer.
2018.07.23 12:35:26.639977 [ 39 ] <Error> BaseDaemon: Access: read.
2018.07.23 12:35:26.639986 [ 39 ] <Error> BaseDaemon: Unknown si_code.
2018.07.23 12:35:26.666365 [ 39 ] <Error> BaseDaemon: 0. clickhouse-server(tcmalloc::ThreadCache::ReleaseToCentralCache(tcmalloc::ThreadCache::FreeList*, unsigned long, int)+0xe3) [0x4a31033]
2018.07.23 12:35:26.666402 [ 39 ] <Error> BaseDaemon: 1. clickhouse-server(tcmalloc::ThreadCache::ListTooLong(tcmalloc::ThreadCache::FreeList*, unsigned long)+0x19) [0x4a31109]
2018.07.23 12:35:26.666428 [ 39 ] <Error> BaseDaemon: 2. clickhouse-server(operator delete(void*, std::nothrow_t const&)+0x2f7) [0x4c1a4f7]
2018.07.23 12:35:26.666497 [ 39 ] <Error> BaseDaemon: 3. clickhouse-server(DB::Block DB::Aggregator::prepareBlockAndFill<DB::Block DB::Aggregator::convertOneBucketToBlock<DB::AggregationMethodString<TwoLevelHashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef>, HashTableNoState>, DefaultHash<StringRef>, TwoLevelHashTableGrower<8ul>, Allocator<true> > > >(DB::AggregatedDataVariants&, DB::AggregationMethodString<TwoLevelHashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef>, HashTableNoState>, DefaultHash<StringRef>, TwoLevelHashTableGrower<8ul>, Allocator<true> > >&, bool, unsigned long) const::{lambda(std::vector<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, std::vector<DB::PODArray<char*, 4096ul, Allocator<false>, 15ul>*, std::allocator<DB::PODArray<char*, 4096ul, Allocator<false>, 15ul>*> >&, std::vector<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, std::vector<unsigned long, std::allocator<unsigned long> > const&, bool)#1}>(DB::AggregatedDataVariants&, bool, unsigned long, DB::AggregationMethodString<TwoLevelHashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef>, HashTableNoState>, DefaultHash<StringRef>, TwoLevelHashTableGrower<8ul>, Allocator<true> > >&&) const+0x5d7) [0x445e717]
2018.07.23 12:35:26.666551 [ 39 ] <Error> BaseDaemon: 4. clickhouse-server(std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<DB::Block>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_state<std::_Bind<std::list<DB::Block, std::allocator<DB::Block> > DB::Aggregator::prepareBlocksAndFillTwoLevelImpl<DB::AggregationMethodString<TwoLevelHashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef>, HashTableNoState>, DefaultHash<StringRef>, TwoLevelHashTableGrower<8ul>, Allocator<true> > > >(DB::AggregatedDataVariants&, DB::AggregationMethodString<TwoLevelHashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef>, HashTableNoState>, DefaultHash<StringRef>, TwoLevelHashTableGrower<8ul>, Allocator<true> > >&, bool, ThreadPool*) const::{lambda(unsigned long, MemoryTracker*)#1} (unsigned long, MemoryTracker*)>, std::allocator<int>, DB::Block ()>::_M_run()::{lambda()#1}, DB::Block> >::_M_invoke(std::_Any_data const&)+0x9b) [0x445ef9b]
2018.07.23 12:35:26.666573 [ 39 ] <Error> BaseDaemon: 5. clickhouse-server(std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)+0x1f) [0x443080f]
2018.07.23 12:35:26.666584 [ 39 ] <Error> BaseDaemon: 6. /lib64/libpthread.so.0(pthread_once+0x53) [0x7f1756365e03]
2018.07.23 12:35:26.666612 [ 39 ] <Error> BaseDaemon: 7. clickhouse-server(void std::call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(std::once_flag&, void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&)+0x4a) [0x443205a]
2018.07.23 12:35:26.666627 [ 39 ] <Error> BaseDaemon: 8. clickhouse-server(std::__future_base::_State_baseV2::_M_set_result(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>, bool)+0x4e) [0x44320be]
2018.07.23 12:35:26.666668 [ 39 ] <Error> BaseDaemon: 9. clickhouse-server(std::__future_base::_Task_state<std::_Bind<std::list<DB::Block, std::allocator<DB::Block> > DB::Aggregator::prepareBlocksAndFillTwoLevelImpl<DB::AggregationMethodString<TwoLevelHashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef>, HashTableNoState>, DefaultHash<StringRef>, TwoLevelHashTableGrower<8ul>, Allocator<true> > > >(DB::AggregatedDataVariants&, DB::AggregationMethodString<TwoLevelHashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef>, HashTableNoState>, DefaultHash<StringRef>, TwoLevelHashTableGrower<8ul>, Allocator<true> > >&, bool, ThreadPool*) const::{lambda(unsigned long, MemoryTracker*)#1} (unsigned long, MemoryTracker*)>, std::allocator<int>, DB::Block ()>::_M_run()+0x38) [0x4432538]
2018.07.23 12:35:26.666682 [ 39 ] <Error> BaseDaemon: 10. clickhouse-server(ThreadPool::worker()+0x167) [0x48dfdd7]
2018.07.23 12:35:26.666692 [ 39 ] <Error> BaseDaemon: 11. clickhouse-server() [0x4be6eef]
2018.07.23 12:35:26.666706 [ 39 ] <Error> BaseDaemon: 12. /lib64/libpthread.so.0(+0x7aa1) [0x7f1756360aa1]
2018.07.23 12:35:26.666719 [ 39 ] <Error> BaseDaemon: ########################################
2018.07.23 12:35:26.666734 [ 39 ] <Error> BaseDaemon: (from thread 40) Received signal Segmentation fault (11).
2018.07.23 12:35:26.666743 [ 39 ] <Error> BaseDaemon: Address: NULL pointer.

**Comment by huang--yijian** [comment]
It seems this problem occurs when querying a Distributed table like our "client_log_all".
If we query a MergeTree table like our "client_log", the query succeeds.

**Comment by sundy-li** [comment]
Confirmed

**Comment by sundy-li** [comment]
This bug only occurred in `distribute query` ,  yet this Aggregate function works fine by table function `remote`.
It crashed by nullpointer in the Aggregator two level stage, but that code is a little complicated for me to fix, maybe @alexey-milovidov  could help with it.

**Comment by huang--yijian** [comment]
Thank you for the quick response and confirm. @sundy-li
