### ISSUE TITLE
Running same query but got different result.

### ISSUE THREAD

**Issue by thanhthai3010** [yandex/ClickHouse#2711]
Hi everyone!
I just created a ClickHouse cluster with 3 nodes, 3 shards and replicated twice, following this tutorial: https://www.altinity.com/blog/2018/5/10/circular-replication-cluster-topology-in-clickhouse

After insert data from `ontime` dataset, I run a query:
```sql
SELECT 
    Carrier, 
    COUNT() AS c, 
    round(quantileTDigest(0.99)(DepDelay), 2) AS q
FROM distributed 
GROUP BY Carrier
ORDER BY q DESC
LIMIT 5
```

But I got a different result each time:
Query result: 
![alt text](https://snag.gy/50toZy.jpg "Different result")

What did I do wrong?
Thanks

**Comment by blinkov** [comment]
Wouldn't it become stable if you wait for a while after the data is fully ingested?

**Comment by blinkov** [comment]
Yep, it's supposed to be `true` if Distributed table is built on top of ReplicatedMergeTree. See https://clickhouse.yandex/docs/en/operations/table_engines/distributed/ for detailed explanation on this.

I agree that it'd be easier if it was just properly selected automatically by default.

**Comment by thanhthai3010** [comment]
Thank you so much, I will close this issue follow your help.
Thank you again, Ivan :+1:
