### ISSUE TITLE
How to secure Distributed table with user?

### ISSUE THREAD

**Issue by thanhthai3010** [yandex/ClickHouse#2724]
I just created a cluster with 3 nodes and then created a Distributed table.
Follow this document: http://clickhouse-docs.readthedocs.io/en/latest/access_rights.html

> The default user is also used for distributed query processing - the system accesses remote servers under this username. So the default user must have an empty password and must not have substantial restrictions or quotas - otherwise, distributed queries will fail.

So, what can we do to protect distributed table with user name and password?

**Comment by ztlpn** [comment]
When you query a Distributed tables, it issues secondary queries to all shards in a cluster. By default these secondary queries are executed under the `default` user. If you want these queries to execute under another user, just add its username and password to the `<remote_servers>` section of the ClickHouse config. E.g. suppose you have user `username` with password `password`. The config should look like this:
```
<remote_servers>
  ...
           <replica>
                <host>host</host>
                <port>9000</port>
                <user>username</user>
                <password>password</password>
            </replica>
  ...
</remote_servers>
```

PS. http://clickhouse-docs.readthedocs.io/ is an unofficial documentation mirror. It is likely to be outdated. Official docs are at https://clickhouse.yandex/docs/en/
