### ISSUE TITLE
query on distributed table use aggreate function result be divided multity item

### ISSUE THREAD

**Issue by zhaoplayboy** [yandex/ClickHouse#2734]
Hi,
I have found a bug about query on distributed table. when I query with the distributed table the result be divided two item.
Here is my clickhouse setting:

`<yandex>
	<clickhouse_remote_servers>
		<test_cluster>
			<shard>
				<internal_replication>false</internal_replication>
				<replica>
					<host>127.0.0.1</host>
					<port>9000</port>
					<user>test</user>
					<password>test</password>
				</replica>
			</shard>
		</test_cluster>
	</clickhouse_remote_servers>
</yandex>`

Here is my steps on this problem appear:
`CREATE TABLE local_table_1 ( datatime UInt32, datadate Date, number1 UInt32) ENGINE = MergeTree(datadate, datatime, 8192);`
`CREATE TABLE local_table_2 ( datatime UInt32, datadate Date, number1 UInt32) ENGINE = MergeTree(datadate, datatime, 8192);`
`insert into local_table_1 (datatime,datadate,number1) values (1533091943,'2018-08-01',100);`
`insert into local_table_2 (datatime,datadate,number1) values (1533091943,'2018-08-01',200);`
`CREATE TABLE distributed_table_1 AS local_table_1 ENGINE = Distributed('test_cluster', "test", local_table_1, rand());`
`CREATE TABLE distributed_table_2 AS local_table_2 ENGINE = Distributed('test_cluster', "test", local_table_2, rand());`

Then we query it with distributed table:
`select sum(number1) from merge('test','distributed_table_2|distributed_table_1');`

Result:
![result](https://user-images.githubusercontent.com/34508173/43565761-77c22a3a-965e-11e8-9f5f-68e69fe92a95.png)

It is very imoport to me and I don't know how to deal with it,Please give me some advice about it.Thanks!

**Comment by thanhthai3010** [comment]
Have you waited until data is fully inserted? By the way, Could you please share your Clusters setting?

**Comment by zhaoplayboy** [comment]
@thanhthai3010  I have query some history data,so i am very sure that the data have fully inserted.The setting as following:
![image](https://user-images.githubusercontent.com/34508173/43299943-25fba484-918f-11e8-8c44-c96a8ad52a7a.png)

I have just try the newest version,and the quesion still exsist.

**Comment by thanhthai3010** [comment]
I also got the same problem before, then I tried to change my cluster config by adding `<internal_replication>true</internal_replication>`. Like this config:

![alt text](https://snag.gy/2Ywfc6.jpg "Cluster Config")

Maybe this change can help you.

**Comment by zhaoplayboy** [comment]
@thanhthai3010 I have try it,not worked...You just change that config file and the problem be solved?Could you give me more suggession?thanks.

**Comment by thanhthai3010** [comment]
After that, you have to re-import data, I think it's because the data is duplicated.
You can read the document here: https://clickhouse.yandex/docs/en/operations/table_engines/distributed/

> If this parameter is set to 'true', the write operation selects the first healthy replica and writes data to it. Use this alternative if the Distributed table "looks at" replicated tables. In other words, if the table where data will be written is going to replicate them itself.

> If it is set to 'false' (the default), data is written to all replicas. In essence, this means that the Distributed table replicates data itself. This is worse than using replicated tables, because the consistency of replicas is not checked, and over time they will contain slightly different data.
