### ISSUE TITLE
The clickhouse server continuously outputs the same error logs

### ISSUE THREAD

**Issue by kevinli1** [yandex/ClickHouse#2740]
Dear ClickHouse,

    
The clickhouse server continuously outputs the following error logs. Table engine is ReplicatedReplacingMergeTree. What is the possible reason? Thanks.

Error logs on node 1 (ip:9.1.1.167 shard_num:13 replica_num:2):
---------------------------------
 2018.07.27 23:01:22.314017 [ 448 ] <Debug> mdata_analysis.mcontent_app_summary_v1_daily_local (StorageReplicatedMergeTree): Fetching part 20180723_1_1_0 from /clickhouse/mdata_analysis/shard13/mcontent_app_summary_v1_daily_local/replicas/9.1.1.80
2018.07.27 23:01:22.314783 [ 448 ] <Trace> ReadWriteBufferFromHTTP: Sending request to http://9.1.1.142:9009/?endpoint=DataPartsExchange%3A%2Fclickhouse%2Fmdata_analysis%2Fshard13%2Fmcontent_app_summary_v1_daily_local%2Freplicas%2F9.1.1.80&part=20180723_1_1_0&compress=false
2018.07.27 23:01:22.342659 [ 448 ] <Error> DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 33, e.displayText() = DB::Exception: Cannot read all data, e.what() = DB::Exception, Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x45d5226]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x25f068f]
2. clickhouse-server(DB::DataPartsExchange::Fetcher::fetchPart(std::string const&, std::string const&, std::string const&, int, DB::ConnectionTimeouts const&, bool)+0x7b2) [0x41d74b2]
3. clickhouse-server(DB::StorageReplicatedMergeTree::fetchPart(std::string const&, std::string const&, bool, unsigned long)+0x4fb) [0x41aca6b]
4. clickhouse-server(DB::StorageReplicatedMergeTree::executeFetch(DB::ReplicatedMergeTreeLogEntry const&)+0x6e2) [0x41aded2]
5. clickhouse-server(DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry const&)+0xe2) [0x41af682]
6. clickhouse-server() [0x41affd0]
7. clickhouse-server(DB::ReplicatedMergeTreeQueue::processEntry(std::function<std::shared_ptr<zkutil::ZooKeeper> ()>, std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::function<bool (std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>)+0x3e) [0x4271c0e]
8. clickhouse-server(DB::StorageReplicatedMergeTree::queueTask()+0x136) [0x419a816]
9. clickhouse-server(DB::BackgroundProcessingPool::threadFunction()+0x3f6) [0x41d3606]
10. clickhouse-server() [0x4b027cf]
11. /lib64/libpthread.so.0(+0x7e25) [0x7f6ccde41e25]
12. /lib64/libc.so.6(clone+0x6d) [0x7f6ccd1f635d]
----------------------------------------

Error Logs on node 2 (ip:9.1.1.142 shard_num:1 replica_num:1):
----------------------------------------
2018.07.27 22:54:26.085814 [ 5080 ] <Trace> InterserverIOHTTPHandler-factory: HTTP Request for InterserverIOHTTPHandler-factory. Method: POST, Address: 9.1.1.167:37982, User-Agent: none
2018.07.27 22:54:26.085851 [ 5080 ] <Trace> InterserverIOHTTPHandler: Request URI: ?endpoint=DataPartsExchange%3A%2Fclickhouse%2Fmdata_analysis%2Fshard13%2Fmcontent_app_summary_v1_daily_local%2Freplicas%2F9.1.1.80&part=20180723_1_1_0&compress=false
2018.07.27 22:54:26.097676 [ 5080 ] <Error> InterserverIOHTTPHandler: Code: 221, e.displayText() = DB::Exception: No interserver IO endpoint named DataPartsExchange:/clickhouse/mdata_analysis/shard13/mcontent_app_summary_v1_daily_local/replicas/9.1.1.80, e.what() = DB::Exception, Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x45d5226]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x25f068f]
2. clickhouse-server(DB::InterserverIOHTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)+0xce2) [0x26138e2]
3. clickhouse-server(DB::InterserverIOHTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)+0x40) [0x2614260]
4. clickhouse-server(Poco::Net::HTTPServerConnection::run()+0x2a2) [0x47f2632]
5. clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x47ee56f]
6. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x110) [0x47eebd0]
7. clickhouse-server(Poco::PooledThread::run()+0x77) [0x4a08f57]
8. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x4a066b8]
9. clickhouse-server() [0x4b027cf]
10. /lib64/libpthread.so.0(+0x7dc5) [0x7f4677fcddc5]
11. /lib64/libc.so.6(clone+0x6d) [0x7f467738374d]
----------------------------------------

**Comment by filimonov** [comment]
check the replica names / netword routing / NAT.
It looks like it was trying to download part which was registed in '9.1.1.80' replica from '9.1.1.142' replica.

**Comment by ShanQincheng** [comment]
> Dear ClickHouse,
> 
> The clickhouse server continuously outputs the following error logs. Table engine is ReplicatedReplacingMergeTree. What is the possible reason? Thanks.
> 
> ## Error logs on node 1 (ip:9.1.1.167 shard_num:13 replica_num:2):
> 2018.07.27 23:01:22.314017 [ 448 ] mdata_analysis.mcontent_app_summary_v1_daily_local (StorageReplicatedMergeTree): Fetching part 20180723_1_1_0 from /clickhouse/mdata_analysis/shard13/mcontent_app_summary_v1_daily_local/replicas/9.1.1.80
> 2018.07.27 23:01:22.314783 [ 448 ] ReadWriteBufferFromHTTP: Sending request to http://9.1.1.142:9009/?endpoint=DataPartsExchange%3A%2Fclickhouse%2Fmdata_analysis%2Fshard13%2Fmcontent_app_summary_v1_daily_local%2Freplicas%2F9.1.1.80&part=20180723_1_1_0&compress=false
> 2018.07.27 23:01:22.342659 [ 448 ] DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 33, e.displayText() = DB::Exception: Cannot read all data, e.what() = DB::Exception, Stack trace:
> 
> 1. clickhouse-server(StackTrace::StackTrace()+0x16) [0x45d5226]
> 2. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x25f068f]
> 3. clickhouse-server(DB::DataPartsExchange::Fetcher::fetchPart(std::string const&, std::string const&, std::string const&, int, DB::ConnectionTimeouts const&, bool)+0x7b2) [0x41d74b2]
> 4. clickhouse-server(DB::StorageReplicatedMergeTree::fetchPart(std::string const&, std::string const&, bool, unsigned long)+0x4fb) [0x41aca6b]
> 5. clickhouse-server(DB::StorageReplicatedMergeTree::executeFetch(DB::ReplicatedMergeTreeLogEntry const&)+0x6e2) [0x41aded2]
> 6. clickhouse-server(DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry const&)+0xe2) [0x41af682]
> 7. clickhouse-server() [0x41affd0]
> 8. clickhouse-server(DB::ReplicatedMergeTreeQueue::processEntry(std::function<std::shared_ptrzkutil::ZooKeeper ()>, std::shared_ptrDB::ReplicatedMergeTreeLogEntry&, std::function<bool (std::shared_ptrDB::ReplicatedMergeTreeLogEntry&)>)+0x3e) [0x4271c0e]
> 9. clickhouse-server(DB::StorageReplicatedMergeTree::queueTask()+0x136) [0x419a816]
> 10. clickhouse-server(DB::BackgroundProcessingPool::threadFunction()+0x3f6) [0x41d3606]
> 11. clickhouse-server() [0x4b027cf]
> 12. /lib64/libpthread.so.0(+0x7e25) [0x7f6ccde41e25]
> 13. /lib64/libc.so.6(clone+0x6d) [0x7f6ccd1f635d]
> 
> ## Error Logs on node 2 (ip:9.1.1.142 shard_num:1 replica_num:1):
> 2018.07.27 22:54:26.085814 [ 5080 ] InterserverIOHTTPHandler-factory: HTTP Request for InterserverIOHTTPHandler-factory. Method: POST, Address: 9.1.1.167:37982, User-Agent: none
> 2018.07.27 22:54:26.085851 [ 5080 ] InterserverIOHTTPHandler: Request URI: ?endpoint=DataPartsExchange%3A%2Fclickhouse%2Fmdata_analysis%2Fshard13%2Fmcontent_app_summary_v1_daily_local%2Freplicas%2F9.1.1.80&part=20180723_1_1_0&compress=false
> 2018.07.27 22:54:26.097676 [ 5080 ] InterserverIOHTTPHandler: Code: 221, e.displayText() = DB::Exception: No interserver IO endpoint named DataPartsExchange:/clickhouse/mdata_analysis/shard13/mcontent_app_summary_v1_daily_local/replicas/9.1.1.80, e.what() = DB::Exception, Stack trace:
> 
> 1. clickhouse-server(StackTrace::StackTrace()+0x16) [0x45d5226]
> 2. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x25f068f]
> 3. clickhouse-server(DB::InterserverIOHTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)+0xce2) [0x26138e2]
> 4. clickhouse-server(DB::InterserverIOHTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)+0x40) [0x2614260]
> 5. clickhouse-server(Poco::Net::HTTPServerConnection::run()+0x2a2) [0x47f2632]
> 6. clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x47ee56f]
> 7. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x110) [0x47eebd0]
> 8. clickhouse-server(Poco::PooledThread::run()+0x77) [0x4a08f57]
> 9. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x4a066b8]
> 10. clickhouse-server() [0x4b027cf]
> 11. /lib64/libpthread.so.0(+0x7dc5) [0x7f4677fcddc5]
> 12. /lib64/libc.so.6(clone+0x6d) [0x7f467738374d]

--------------------------------------------------------------------------------------------------

Can you tell me how did you solved the NODE 2 "No interserver IO endpoint named" problem?
