### ISSUE TITLE
ZFS Compatibility

### ISSUE THREAD

**Issue by adhamelia** [yandex/ClickHouse#2743]
Guys,

Will ClickHouse work on ZFS ??? Is there any performance difference over ext4 ???

**Comment by alexey-milovidov** [comment]
ClickHouse works on ZFS. We use it for backup servers.

> Is there any performance difference over ext4 ???

We have no comparison of performance, and we don't run queries on ZFS cluster (it is used for passive replicas).

**Comment by adhamelia** [comment]
Thanks @alexey-milovidov :+1: 

I will do some bench marking and identify the performance gap.

**Comment by tshev** [comment]
@adhamelia Do you have any results, which are worth sharing?

**Comment by adhamelia** [comment]
We are running clickhouse on Butter FS and performance got increased almost
3 times than ext4 and ZFS.

ZFS was giving us much better compression but no performance gain.

**Comment by roimor** [comment]
@alexey-milovidov @adhamelia any new information regarding this? is btrfs really compatible with clickhouse? any reason it wouldn't be?

**Comment by roimor** [comment]
@den-crane i got to this issue from the link you gave..

**Comment by jpds** [comment]
I've noticed that https://klarasystems.com/articles/introducing-openzfs-fast-dedup/ appears to work well on my ClickHouse data volumes, not a substantial difference but something in ClickHouse is being deduplicated:

![Image](https://github.com/user-attachments/assets/fda9129b-9a4f-45aa-8cb4-19b2d99368c2)
