### ISSUE TITLE
What is the difference between version v18.x.x and v1.1.xxxx?

### ISSUE THREAD

**Issue by vnnw** [yandex/ClickHouse#2746]
I notice there is a naming pattern change on ClickHouse version code.
I wonder whether both are compatible, and I am safe to upgrade from v1.1.xxx to v18.xx?

**Comment by vnnw** [comment]
Sorry. The CHANGELOG.md already explains my question.

**Comment by alexey-milovidov** [comment]
TLDR: 
Versions 1 and 18 are totally compatible.
