### ISSUE TITLE
Table Schema for custom data

### ISSUE THREAD

**Issue by fizerkhan** [yandex/ClickHouse#2747]
We want to store custom events in clickhouse table. Events will have dynamic properties as follows

```
salesquic.track(user_unique_id, event_name, event_properties);

salesquic.track("123456", "created a new project", {
  account_id : "78910",
  project_name : "HubSpot",
  url: 'acme.com'
});

salesquic.track("123456", "upgraded", {
  account_id : "78910",
  plan : "Premium",
  total: 199
});
```

What is the best way to define a schema for dynamic key-values pairs?

**Comment by alesapin** [comment]
Look at [similar question in Google Groups](https://groups.google.com/forum/#!msg/clickhouse/9BrNXnCJGdE/Mnyqu-EsBgAJ;context-place=searchin/clickhouse/schema%7Csort:date).

**Comment by vpanfilov** [comment]
There is also an intresting key-value approch for VERY high number of diffent events and parameters, which change very often.

It is described in [this presentation](https://github.com/yandex/clickhouse-presentations/blob/master/meetup15/lightning/badoo.pdf) (only in Russian). You can see table schemas at the last slides.

- raw data is stored in **Events** table;
- semi-aggregated data for every event is stored in different **Agg_$Event** tables
- final aggregation states are stored in **Results** table.

But I haven't tested it in practice yet.

**Comment by alesapin** [comment]
If there would be any additional questions, please reopen issue.
