### ISSUE TITLE
compile error occurs while USE_POCO_NETSSL is open

### ISSUE THREAD

**Issue by set-daemon** [yandex/ClickHouse#2748]
Hi, my environment is  gcc/g++ is 8.1.0 under ubuntu 14.04 LTS, and according to the official guide "How to build ClickHouse on Linux"(https://clickhouse.yandex/docs/en/development/build/), i tried to build clickhouse from source code, but failed, the detailed error information shown as following:

[2/328] Building CXX object dbms/CMakeFiles/dbms.dir/src/Client/Connection.cpp.o
FAILED: /usr/local/bin/g++   -DBOOST_SYSTEM_NO_DEPRECATED -DLIBRDKAFKA_STATICLIB -DLZ4_DISABLE_DEPRECATE_WARNINGS=1 -DPOCO_STATIC -DPOCO_UNBUNDLED_ZLIB -DWITH_GZFILEOP -DX86_64 -DZLIB_COMPAT -isystem ../contrib/libsparsehash -isystem ../contrib/libdivide -isystem /usr/include/x86_64-linux-gnu -I../dbms/src -Idbms/src -isystem ../contrib/double-conversion -isystem ../contrib/libpcg-random/include -isystem ../contrib/poco/Data/ODBC/include -I../contrib/cityhash102/include -I../libs/libcommon/include -Ilibs/libcommon/include -I../libs/libpocoext/include -I../contrib/poco/Data/include -I../contrib/poco/Foundation/include -I../contrib/zlib-ng -Icontrib/zlib-ng -I../contrib/poco/Util/include -I../contrib/poco/XML/include -I../contrib/poco/JSON/include -I../contrib/poco/Net/include -I../contrib/cctz/include -I../contrib/boost -I../contrib/libtcmalloc/include -I../contrib/libcpuid/include -I../contrib/lz4/lib -I../contrib/zstd/lib -I../contrib/poco/NetSSL_OpenSSL/include -I../contrib/poco/Crypto/include -isystem /usr/local/include -I../libs/libmysqlxx/include -Icontrib/re2_st -I../contrib/re2 -I../contrib/libbtrie/include -I../contrib/poco/MongoDB/include -I../contrib/librdkafka/src -Icontrib/librdkafka/generated/dummy -fdiagnostics-color=always -std=c++1z  -D_GLIBCXX_USE_CXX11_ABI=1 -pipe -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall  -Wnon-virtual-dtor  -no-pie -Wextra -Werror -O2 -g -DNDEBUG -O3    -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc -pthread -MMD -MT dbms/CMakeFiles/dbms.dir/src/Client/Connection.cpp.o -MF dbms/CMakeFiles/dbms.dir/src/Client/Connection.cpp.o.d -o dbms/CMakeFiles/dbms.dir/src/Client/Connection.cpp.o -c ../dbms/src/Client/Connection.cpp
In file included from /usr/local/include/openssl/err.h:21,
                 from ../contrib/poco/Crypto/include/Poco/Crypto/CryptoException.h:24,
                 from ../contrib/poco/Crypto/include/Poco/Crypto/OpenSSLInitializer.h:22,
                 from ../contrib/poco/Crypto/include/Poco/Crypto/X509Certificate.h:22,
                 from ../contrib/poco/NetSSL_OpenSSL/include/Poco/Net/Context.h:23,
                 from ../contrib/poco/NetSSL_OpenSSL/include/Poco/Net/SecureStreamSocket.h:23,
                 **from ../dbms/src/Client/Connection.cpp:27:**
/usr/local/include/openssl/bio.h:690:1: error：expected constructor, destructor, or type conversion before ‘DEPRECATEDIN_1_1_0’
 DEPRECATEDIN_1_1_0(int BIO_get_port(const char *str, unsigned short *port_ptr))
 ^~~~~~~~~~~~~~~~~~
In file included from ../contrib/poco/Crypto/include/Poco/Crypto/CryptoException.h:24,
                 from ../contrib/poco/Crypto/include/Poco/Crypto/OpenSSLInitializer.h:22,
                 from ../contrib/poco/Crypto/include/Poco/Crypto/X509Certificate.h:22,
                 from ../contrib/poco/NetSSL_OpenSSL/include/Poco/Net/Context.h:23,
                 from ../contrib/poco/NetSSL_OpenSSL/include/Poco/Net/SecureStreamSocket.h:23,
                 from ../dbms/src/Client/Connection.cpp:27:
/usr/local/include/openssl/err.h:260:1: error：expected constructor, destructor, or type conversion before ‘DEPRECATEDIN_1_0_0’
 DEPRECATEDIN_1_0_0(void ERR_remove_state(unsigned long pid))
 ^~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/openssl/asn1.h:23,
                 from /usr/local/include/openssl/objects.h:15,
                 from /usr/local/include/openssl/evp.h:28,
                 from /usr/local/include/openssl/x509.h:18,
                 from /usr/local/include/openssl/ssl.h:20,
                 from ../contrib/poco/Crypto/include/Poco/Crypto/X509Certificate.h:28,
                 from ../contrib/poco/NetSSL_OpenSSL/include/Poco/Net/Context.h:23,
                 from ../contrib/poco/NetSSL_OpenSSL/include/Poco/Net/SecureStreamSocket.h:23,
                 from ../dbms/src/Client/Connection.cpp:27:
/usr/local/include/openssl/bn.h:281:1: error：expected constructor, destructor, or type conversion before ‘DEPRECATEDIN_0_9_8’
 DEPRECATEDIN_0_9_8(int
 ^~~~~~~~~~~~~~~~~~
/usr/local/include/openssl/bn.h:352:1: error：expected constructor, destructor, or type conversion before ‘DEPRECATEDIN_0_9_8’
 DEPRECATEDIN_0_9_8(int BN_get_params(int which)) /* 0, mul, 1 high, 2 low, 3
 ^~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/openssl/objects.h:15,
                 from /usr/local/include/openssl/evp.h:28,
                 from /usr/local/include/openssl/x509.h:18,
                 from /usr/local/include/openssl/ssl.h:20,
                 from ../contrib/poco/Crypto/include/Poco/Crypto/X509Certificate.h:28,
                 from ../contrib/poco/NetSSL_OpenSSL/include/Poco/Net/Context.h:23,
                 from ../contrib/poco/NetSSL_OpenSSL/include/Poco/Net/SecureStreamSocket.h:23,
                 from ../dbms/src/Client/Connection.cpp:27:
/usr/local/include/openssl/asn1.h:555:7: error：expected constructor, destructor, or type conversion before ‘unsigned’
 const unsigned char *ASN1_STRING_get0_data(const ASN1_STRING *x);
       ^~~~~~~~
In file included from /usr/local/include/openssl/x509.h:25,
                 from /usr/local/include/openssl/ssl.h:20,
                 from ../contrib/poco/Crypto/include/Poco/Crypto/X509Certificate.h:28,
                 from ../contrib/poco/NetSSL_OpenSSL/include/Poco/Net/Context.h:23,
                 from ../contrib/poco/NetSSL_OpenSSL/include/Poco/Net/SecureStreamSocket.h:23,
                 from ../dbms/src/Client/Connection.cpp:27:
/usr/local/include/openssl/rsa.h:231:1: error：expected constructor, destructor, or type conversion before ‘int’
 int RSA_generate_key_ex(RSA *rsa, int bits, BIGNUM *e, BN_GENCB *cb);
 ^~~
In file included from /usr/local/include/openssl/dsa.h:26,
                 from /usr/local/include/openssl/x509.h:26,
                 from /usr/local/include/openssl/ssl.h:20,
                 from ../contrib/poco/Crypto/include/Poco/Crypto/X509Certificate.h:28,
                 from ../contrib/poco/NetSSL_OpenSSL/include/Poco/Net/Context.h:23,
                 from ../contrib/poco/NetSSL_OpenSSL/include/Poco/Net/SecureStreamSocket.h:23,
                 from ../dbms/src/Client/Connection.cpp:27:
/usr/local/include/openssl/dh.h:142:1: error：expected constructor, destructor, or type conversion before ‘int’
 int DH_generate_parameters_ex(DH *dh, int prime_len, int generator,
 ^~~
In file included from /usr/local/include/openssl/x509.h:26,
                 from /usr/local/include/openssl/ssl.h:20,
                 from ../contrib/poco/Crypto/include/Poco/Crypto/X509Certificate.h:28,
                 from ../contrib/poco/NetSSL_OpenSSL/include/Poco/Net/Context.h:23,
                 from ../contrib/poco/NetSSL_OpenSSL/include/Poco/Net/SecureStreamSocket.h:23,
                 from ../dbms/src/Client/Connection.cpp:27:
/usr/local/include/openssl/dsa.h:128:1: error：expected constructor, destructor, or type conversion before ‘int’
 int DSA_generate_parameters_ex(DSA *dsa, int bits,
 ^~~
In file included from /usr/local/include/openssl/ssl.h:20,
                 from ../contrib/poco/Crypto/include/Poco/Crypto/X509Certificate.h:28,
                 from ../contrib/poco/NetSSL_OpenSSL/include/Poco/Net/Context.h:23,
                 from ../contrib/poco/NetSSL_OpenSSL/include/Poco/Net/SecureStreamSocket.h:23,
                 from ../dbms/src/Client/Connection.cpp:27:
/usr/local/include/openssl/x509.h:728:1: error：expected constructor, destructor, or type conversion before ‘DEPRECATEDIN_1_1_0’
 DEPRECATEDIN_1_1_0(ASN1_TIME *X509_CRL_get_nextUpdate(X509_CRL *crl))
 ^~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/openssl/ssl.h:26,
                 from ../contrib/poco/Crypto/include/Poco/Crypto/X509Certificate.h:28,
                 from ../contrib/poco/NetSSL_OpenSSL/include/Poco/Net/Context.h:23,
                 from ../contrib/poco/NetSSL_OpenSSL/include/Poco/Net/SecureStreamSocket.h:23,
                 from ../dbms/src/Client/Connection.cpp:27:
/usr/local/include/openssl/hmac.h:31:12: error：expected constructor, destructor, or type conversion before ‘int’
 /*__owur*/ int HMAC_Init_ex(HMAC_CTX *ctx, const void *key, int len,
            ^~~
In file included from ../contrib/poco/Crypto/include/Poco/Crypto/X509Certificate.h:28,
                 from ../contrib/poco/NetSSL_OpenSSL/include/Poco/Net/Context.h:23,
                 from ../contrib/poco/NetSSL_OpenSSL/include/Poco/Net/SecureStreamSocket.h:23,
                 from ../dbms/src/Client/Connection.cpp:27:
/usr/local/include/openssl/ssl.h:969:1: error：expected constructor, destructor, or type conversion before ‘typedef’
 typedef enum {
 ^~~~~~~
**/usr/local/include/openssl/ssl.h:1020:3: error：‘OSSL_HANDSHAKE_STATE’ does not name a type; did you mean ‘SSL_CB_HANDSHAKE_START’?**
 } OSSL_HANDSHAKE_STATE;
   ^~~~~~~~~~~~~~~~~~~~
   SSL_CB_HANDSHAKE_START
/usr/local/include/openssl/ssl.h:1829:1: error：expected constructor, destructor, or type conversion before ‘DEPRECATEDIN_1_1_0’
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *SSLv3_server_method(void))
 ^~~~~~~~~~~~~~~~~~
/usr/local/include/openssl/ssl.h:1844:1: error：expected constructor, destructor, or type conversion before ‘DEPRECATEDIN_1_1_0’
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_server_method(void))
 ^~~~~~~~~~~~~~~~~~
/usr/local/include/openssl/ssl.h:1963:8: error：‘OSSL_HANDSHAKE_STATE’ does not name a type; did you mean ‘SSL_CB_HANDSHAKE_START’?
 __owur OSSL_HANDSHAKE_STATE SSL_get_state(const SSL *ssl);
        ^~~~~~~~~~~~~~~~~~~~
        SSL_CB_HANDSHAKE_START
ninja: build stopped: subcommand failed.

I find that:
OSSL_HANDSHAKE_STATE is defined like  
typedef enum {
} OSSL_HANDSHAKE_STATE
but it can not be recognized as a type while compiling clickhouse?

thanks very much!

**newly found:**
# include <openssl/opensslconf.h>
this header seems not be included successfully in <openssl/ssl.h> and others header file which use the macros defined in opensslconf.h

**Comment by alesapin** [comment]
Please, provide command output:
`dpkg -l | grep ssl`

It's seems like something whent wrong with ssl version.

**Comment by alesapin** [comment]
Sorry, but I cannot reproduce this problem with the same ubuntu, compiler and openssl version. Can you please provide `cmake` output?

**Comment by alexey-milovidov** [comment]
This is not relevant because we have migrated from OS OpenSSL package to LibreSSL from submodules.
