### ISSUE TITLE
[Question] are there any parameters that can limit the number of inserts?

### ISSUE THREAD

**Issue by lamber-ken** [yandex/ClickHouse#2766]
hi, we use `ReplicatedMergeTree`, when client insert datas, it'll create one znode for each block.

but when the client accidentally set the batch size to 1, will create many znodes. likes ddos to zk.

so, it's great, if there is a parameter that can set the size of the mini batch size for insert.

**Comment by alesapin** [comment]
Which batch size do you mean? ClickHouse can't do anything, If clients make `INSERT` queries with one row. Otherwise if `INSERT` queries generate too small blocks, squashing of small blocks will be used by default (except case when you have distributed table with `insert_distributed_sync` setting).

**Comment by lamber-ken** [comment]
@alesapin, thank for your explain.

What's I think is parameter likes `min_insert_rows`, for example, if the server use `ReplicatedMergeTree` engine and set `min_insert_rows = 1000`. 
when client inserts just one row, it'll get error message. if so, this mechanism can prevent create 
many znodes.

our real case, the client accidentally set the batch size to 1, a lot of nodes have been created for a moment. zk server oom!

**Comment by alesapin** [comment]
Although ClickHouse has the setting `min_insert_rows` it doesn't work like you describe.

It seems very strange to prevent client from small inserts inside DB. I never heard about such functionality in DBs. Maybe it's better to reject client's small insert requests inside your application server? Or prevent client to set up batch size to 1 on client side of your application?

**Comment by lamber-ken** [comment]
@alesapin, hi, my point is as follows

first, the difference between ck and other dbs is that when using the `ReplicatedMergeTree` engine, each block will create a znode node. when the data source has a large amount of data, it'll create many znodes at a moment.

second, it can't be controlled on the client side. For example, the dev environment doesn't have so many datas, so set the batch size to 1 or 100 for testing. Sometimes developers may forget to change the batch size to 3000 or more when publish the program to the production environment.
so I think it's better the server refuses the client to insert data into the server when the batch size is less than `min_insert_rows`.

**Comment by alesapin** [comment]
Unfortunately the answer is no, ClickHouse doesn't have this setting.
