### ISSUE TITLE
The delete usage of "in" in ReplicatedMergeTree engine

### ISSUE THREAD

**Issue by Tongmyong** [yandex/ClickHouse#2769]
select id from stat_new_phoneid_remain_test_tmp where id in (243174967,243174968);
The execution of this statement is valid，
but，
select id from stat_new_phoneid_remain_test_tmp where id in (select id from stat_new_phoneid_remain_tmp limit 4);
The execution of this statement is not effective

Do anyone know what's going on?

**Comment by ztlpn** [comment]
This bug should be fixed in v18.4.0 and higher. Please try upgrading.

**Comment by alexey-milovidov** [comment]
#2571
