### ISSUE TITLE
Summing Merge Tree table does not return correct rows

### ISSUE THREAD

**Issue by manojrbj** [yandex/ClickHouse#2776]
Hi Team,
I am using your example to understand the Summing Merge Tree. I executed statements into file located at https://github.com/yandex/ClickHouse/blob/master/dbms/tests/queries/0_stateless/00043_summing_empty_part.sql

```
CREATE DATABASE IF NOT EXISTS test;
DROP TABLE IF EXISTS test.empty_summing;
CREATE TABLE test.empty_summing (d Date, k UInt64, v Int8) ENGINE=SummingMergeTree(d, k, 8192);

INSERT INTO test.empty_summing VALUES ('2015-01-01', 1, 10);
INSERT INTO test.empty_summing VALUES ('2015-01-01', 1, -10);

OPTIMIZE TABLE test.empty_summing;
SELECT * FROM test.empty_summing;

INSERT INTO test.empty_summing VALUES ('2015-01-01', 1, 4),('2015-01-01', 2, -9),('2015-01-01', 3, -14);
INSERT INTO test.empty_summing VALUES ('2015-01-01', 1, -2),('2015-01-01', 1, -2),('2015-01-01', 3, 14);
INSERT INTO test.empty_summing VALUES ('2015-01-01', 1, 0),('2015-01-01', 3, 0);

OPTIMIZE TABLE test.empty_summing;
SELECT * FROM test.empty_summing;

DROP TABLE test.empty_summing;
```

I am expecting below for final select statement:
```
d				k		v
2015-01-01		1		0
2015-01-01		2		-9
2015-01-01		3		0
```

however below result is being shows at console.
```
SELECT *
FROM test.empty_summing 

┌──────────d─┬─k─┬──v─┐
│ 2015-01-01 │ 2 │ -9 │
└────────────┴───┴────┘
```

Is this a bug OR expected behaviour. Please help me to understand the process.

**Comment by alesapin** [comment]
This behaviour is expected. As [documentation](https://clickhouse.yandex/docs/en/operations/table_engines/summingmergetree/) says:

> If the values were null in all of these columns, the row is deleted. (The exception is cases when the data part would not have any rows left in it.)
