### ISSUE TITLE
How can I remove cluster in the config file and take effect immediately without restarting clickhouse ？

### ISSUE THREAD

**Issue by AlexanderJLiu** [yandex/ClickHouse#2777]
Hi, I come across some troubles recently. I removed one **cluster** from the config file, but the cluster was still available for the distributed table. When I restarted clickhouse-server, everything back to normal. The same situation occurred while removing the dictionary file. As the official documentation says **Clusters from config are updated on the fly, it does not require server restart**， adding cluster and dictionary can work well without restarting server while removing was not ok. what should I do to solve the problem ? 😄

**Comment by alesapin** [comment]
External dictionaries reload will be fixed in this pr https://github.com/yandex/ClickHouse/pull/2779.

**Comment by alexey-milovidov** [comment]
Added removing clusters.
