### ISSUE TITLE
Unexpected SELECT * with Join

### ISSUE THREAD

**Issue by zhang2014** [yandex/ClickHouse#2786]
### Steps to reproduce the behavior
SELECT * FROM (SELECT 1 AS id, 2 AS value) ANY INNER JOIN (SELECT 1 AS id, 2 AS values) USING id;
### Expected Result
1    2    2
### Actual Result
1    2

**Comment by alesapin** [comment]
Yes, this is weird, but this behaviour is [documented](https://clickhouse.yandex/docs/en/query_language/select/#join-clause) and works according to documentation:

> All columns that are not needed for the JOIN are deleted from the subquery.

`subquery` here is right part of join. Currently you have to specify all required columns.

**Comment by zhang2014** [comment]
I am currently trying to fix this problem, but it is not compatible with the version.

**Comment by TimonKK** [comment]
[It](https://github.com/yandex/ClickHouse/issues/2803) is same problem
