### ISSUE TITLE
JSONEachRow parsing: null values

### ISSUE THREAD

**Issue by xmariachi** [yandex/ClickHouse#2798]
JSONEachRow format for KafkaEngine seems not to be able to parse null values such as: 
```
... ,"voucher":null, ...
```

```
2018.08.02 16:49:47.798295 [ 21 ] <Error> executeQuery: Code: 26, e.displayText() = DB::Exception: Cannot parse JSON string: expected opening quote: (while read the value of key voucher): (at row 1)
```
I understand this is a limitation of the JSON Parser. 
However, how to feed null values into a table? I've read in docs that NULLs are not supported for default values at least, but some [other issues](https://github.com/yandex/ClickHouse/pull/2730) seem to give support to them.

**Comment by den-crane** [comment]
try to omit null attributes, JSONEachRow treat {} the same as {"voucher":null}

**Comment by alexey-milovidov** [comment]
NULLs are supported. This is documentation issue.

You can insert NULLs from JSONEachRow if you have Nullable data type in your table: by writing them as null or by omitting the key and value pair. The latter is treated as inserting default value.

**Comment by BayoNet** [comment]
Documentation is ready.
