### ISSUE TITLE
Не могу получить результат запроса из ClickHouse, используя JavaScript

### ISSUE THREAD

**Issue by dcyrils** [yandex/ClickHouse#2800]
Я только знакомлюсь как с СН, так и JS - ну, так вышло.. (( 
СН подключен через @apla. Я посылаю простейшие запросы к существующей таблице примерно так: this.clickHouse.query ("SELECT count() FROM gStat.cand001")

На выходе получаю стрим - как и запланировано... разработчиками. Но где мой результат (счетчик) - мне непонятно :( Как его получить? 
Спасибо

**Comment by alesapin** [comment]
В этом случае лучше обратиться к меинтейнеру js-библиотеки. Тут врятли смогут помочь, потому что  библиотек для разных языков [очень много](https://clickhouse.yandex/docs/ru/interfaces/third-party_client_libraries/). Для уверенности можно попробовать выполнить этот запрос через консольную утилиту `clickhouse-client`.
