### ISSUE TITLE
Does MergeTree still require date column?

### ISSUE THREAD

**Issue by simPod** [yandex/ClickHouse#2802]
The [docs](https://clickhouse.yandex/docs/en/operations/table_engines/mergetree/) says:

> A MergeTree table must have a separate column containing the date. Here, it is the EventDate column. The date column must have the 'Date' type (not 'DateTime').

However, I tried using `ORDER BY (<DateTime column>)` and it seems to work just fine.

```sql
CREATE TABLE default.test
(
time DateTime,
dest_ip String
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(time)
ORDER BY time
```

**Comment by alesapin** [comment]
No it doesn't. You have tried the new syntax https://clickhouse.yandex/docs/en/operations/table_engines/custom_partitioning_key/ with custom partitioning ability.

**Comment by alexey-milovidov** [comment]
Need to update the docs.

**Comment by champtar** [comment]
Don't know if there is any impact, but if you use only `DateTime` and not `Date`, `system.parts` `min_date` and `max_date` is 0

```
DESCRIBE TABLE testdatetime

┌─name───────┬─type─────────────┬─default_type─┬─default_expression─┐
│ datetime   │ DateTime         │              │                    │
│ clientipv4 │ Nullable(UInt32) │              │                    │
└────────────┴──────────────────┴──────────────┴────────────────────┘

SELECT 
    count(*), 
    min(datetime), 
    max(datetime)
FROM testdatetime 

┌────count()─┬───────min(datetime)─┬───────max(datetime)─┐
│ 1533463750 │ 2018-07-09 03:00:00 │ 2018-07-10 02:59:59 │
└────────────┴─────────────────────┴─────────────────────┘


SELECT 
    table, 
    formatReadableSize(sum(bytes)) AS size, 
    min(min_date) AS min_date, 
    max(max_date) AS max_date
FROM system.parts 
WHERE active AND (table = 'testdatetime')
GROUP BY table
ORDER BY table ASC

┌─table────────┬─size─────┬───min_date─┬───max_date─┐
│ testdatetime │ 5.12 GiB │ 0000-00-00 │ 0000-00-00 │
└──────────────┴──────────┴────────────┴────────────┘

```

**Comment by simPod** [comment]
Yes, it's mentioned in this issue https://github.com/yandex/ClickHouse/issues/2362

**Comment by alexey-milovidov** [comment]
> Don't know if there is any impact, but if you use only DateTime and not Date, system.parts min_date and max_date is 0

`min_date` and `max_date` columns in `system.parts` are for convenience and doen't affect performance. If you have DateTime column as partition key, the table will track min and max value of that column and use these values for partition pruning. But they will not be visible in `system.parts`.

**Comment by alexey-milovidov** [comment]
Nevertheless it's a good practice to have separate column with just Date.

Because Date column has many repeated values and it will compress much better. In contrast, DateTime often have pseudorandom lower bits that correspond to seconds.

In total, reading and filtering by Date could be 10..100 times faster than by DateTime.

**Comment by champtar** [comment]
If you are already partitioned by day, Date should be useless (but maybe it's not right now, haven't tested)

**Comment by DivyaRao30** [comment]
can somebody explain how exactly the below partition works?

1. ENGINE = MergeTree PARTITION BY toYYYYMMDD(created_date)

   with YYYYMMDD(created_date) it's creating 100's of partitions./

2. ENGINE = MergeTree PARTITION BY  (created_date)
   
   with just (created_date) it's creating 8 partitions for 1 weeks data.

Thanks,


Please let me know which function will fetch the data faster and feasible to me as we have more than 60 weeks of data stored in the in the same table.

**Comment by alexey-milovidov** [comment]
> I want to know what function can be used to convert the date into week number and partitioned on that.
Note: Tried toRelativeWeekNum but am not able to understand how it works.

Yes, it will work. You can also use `toMonday` function.
