### ISSUE TITLE
clickhouse 升级导致kafka表不可用

### ISSUE THREAD

**Issue by 754154377** [yandex/ClickHouse#2821]
使用clickhouse 390版本创建的kafka表，json格式。升级新版本不支持，增加了kafka消息的分隔符，导致升级后，原有的kakfk表不可用。

**Comment by amosbird** [comment]
Yeah, that update turns

```
Kafka(kafka_broker_list, kafka_topic_list, kafka_group_name, kafka_format
      [, kafka_schema, kafka_num_consumers])
```

into

```
Kafka(kafka_broker_list, kafka_topic_list, kafka_group_name, kafka_format
      [, kafka_row_delimiter, kafka_schema, kafka_num_consumers])
```

Errors might occur if your old Kafka tables make use of `kafka_schema` or `kafka_num_consumers`. In such case, you'd need to manually modify the metadata files under `<data>/metadata/<database>/<table>.sql`. Using `kafka_row_delimiter = ''` if you want the old behavior back.

**Comment by zhang2014** [comment]
This should be a version-incompatible feature, but is not recorded in the change log @alexey-milovidov 

https://github.com/yandex/ClickHouse/blob/master/CHANGELOG.md#new-features-1
```
Support for adding arbitrary message separators when reading from Kafka Amos Bird.
```
