### ISSUE TITLE
alter table + prewhere: Not found column ... in block

### ISSUE THREAD

**Issue by den-crane** [yandex/ClickHouse#2827]
ClickHouse client version 18.6.0.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 18.6.0 revision 54401.

create table y(a Int64, b Int64, z Date) engine = MergeTree partition by (a,z) order by tuple();
insert into y  select 1,number, toDate('2018-01-01') from numbers(1);
insert into y  select 2,number, toDate('2018-02-01') from numbers(1);
alter table y add column c Array(Float32);
alter table y add column d Array(Float32);

**select c,d from y prewhere a <1000;
Received exception from server (version 18.6.0):
Code: 10. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Not found column c in block. There are only columns: a.**

**Comment by den-crane** [comment]
Though
```
SELECT *
FROM y
PREWHERE a < 1000

┌─a─┬─b─┬──────────z─┬─c──┬─d──┐
│ 1 │ 0 │ 2018-01-01 │ [] │ [] │
└───┴───┴────────────┴────┴────┘
┌─a─┬─b─┬──────────z─┬─c──┬─d──┐
│ 2 │ 0 │ 2018-02-01 │ [] │ [] │
└───┴───┴────────────┴────┴────┘
```

**Comment by 4ertus2** [comment]
18.10.3

drop table if exists t;
create table t
(
    a Int32,
    b Int32
) engine = MergeTree partition by (a,b) order by (a);

insert into t values (1, 1);
alter table t add column c Int32;

select b from t prewhere a < 1000; -- OK
select c from t prewhere a < 1000;
-- Block structure mismatch in MergeTreeThread stream: different number of columns:
-- a Int32 Int32(size = 1)
-- a Int32 Int32(size = 0), c Int32 Int32(size = 0).

**Comment by alexey-milovidov** [comment]
It is started to work in master.
This is related to changes in #2226

**Comment by alexey-milovidov** [comment]
Not quite.
The last query returns empty set while it should return the same result as the previous query.

**Comment by alexey-milovidov** [comment]
Ready test case:

```
drop table if exists test.t;
create table test.t
(
a Int32,
b Int32
) engine = MergeTree partition by (a,b) order by (a);

insert into test.t values (1, 1);
alter table test.t add column c Int32;

select b from test.t prewhere a < 1000;
select c from test.t where a < 1000;
select c from test.t prewhere a < 1000;

drop table test.t;
```

**Comment by wake-up-neo** [comment]
@alexey-milovidov Please take a look

```
drop table if exists test.trepl;
create table test.trepl
(
d Date,
a Int32,
b Int32
) engine = ReplacingMergeTree(d, (a,b), 8192);


insert into test.trepl values ('2018-09-19', 1, 1);
select b from test.trepl FINAL prewhere a < 1000;
drop table test.trepl;
```

> Received exception from server (version 18.12.17):
> Code: 10. DB::Exception: Received from localhost:9002, 127.0.0.1. DB::Exception: Not found column a in block. There are only columns: b.

**Comment by wake-up-neo** [comment]
The same for CollapsingMergeTree, and only with FINAL.
