### ISSUE TITLE
ability to kill query via cli-client

### ISSUE THREAD

**Issue by f1yegor** [yandex/ClickHouse#283]
There is a well known way to kill a query via http request
https://clickhouse.yandex/reference_en.html#replace_running_query

https://groups.google.com/forum/#!msg/clickhouse/JKb9FmHP-yA/Jva_SzmqCwAJ;context-place=forum/clickhouse

Please implement kill via cli-client.

**Comment by alexey-milovidov** [comment]
Will do. There is a task on `ludv1x`.

It will look like
```
KILL QUERY WHERE query_id = '...'
```
In where you could specify any expression on columns of `system.processes`.

**Comment by f1yegor** [comment]
sounds good

**Comment by hatarist** [comment]
I also have this in [clickhouse-cli](https://github.com/hatarist/clickhouse-cli)
