### ISSUE TITLE
Data can be skipped when using partial dictionary updates

### ISSUE THREAD

**Issue by SaltTan** [yandex/ClickHouse#2847]
I am experimenting with partial dictionary updates using the update_field parameter.
I found out that time_point is increased after every update, even if there was an error.
Because of that data can be completely or partially skipped.
An example:
There was an error during the initial dictionary loading (create_time >= '0000-00-00 00:00:00')
```
2018.08.09 20:00:11.179273 [ 23 ] <Trace> MySQLDictionarySource: SELECT `table_name`, `create_time`, (max_data_length/avg_row_length) AS `number` FROM `information_schema`.`tables` WHERE table_schema='information_schema' AND create_time >= '0000-00-00 00:00:00';
2018.08.09 20:00:11.455287 [ 23 ] <Error> ExternalDictionaries: Cannot create external dictionary 'dict' from config path /etc/clickhouse-server/dict/dict.xml: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = mysqlxx::CannotParseValue: Cannot parse signed integer: 2796202.0000, query: SELECT `table_name`, `create_time`, (max_data_length/avg_row_length) AS `number` FROM `information_schema`.`tables` WHERE table_schema='information_schema' AND create_time >= '0000-00-00 00:00:00';, e.what() = mysqlxx::CannotParseValue
```
But the next time the dictionary only requests new data (create_time >= '2018-08-09 20:00:10')
```
2018.08.09 20:00:18.407470 [ 23 ] <Trace> MySQLDictionarySource: SELECT `table_name`, `create_time`, (max_data_length/avg_row_length) AS `number` FROM `information_schema`.`tables` WHERE table_schema='information_schema' AND create_time >= '2018-08-09 20:00:10';
2018.08.09 20:00:18.683732 [ 23 ] <Error> ExternalDictionaries: Failed reloading 'dict' external dictionary: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = mysqlxx::CannotParseValue: Cannot parse signed integer: 2796202.0000, query: SELECT `table_name`, `create_time`, (max_data_length/avg_row_length) AS `number` FROM `information_schema`.`tables` WHERE table_schema='information_schema' AND create_time >= '2018-08-09 20:00:10';, e.what() = mysqlxx::CannotParseValue
```

**Comment by den-crane** [comment]
@vitlibar Can you fix it, please? It should be pretty easy fix. Need just a check that the partial dictionary update was successful before shifting(updating) last updating time?

And would be good to lag (-1 sec) configurable in dictionary config, because 1 second is not enough for *most* of cases (time drifting & commit exposes rows for `committed read` later than `updated ON UPDATE CURRENT_TIMESTAMP` happen).

**Comment by vitlibar** [comment]
It seems it's already done.
https://github.com/yandex/ClickHouse/pull/5567

**Comment by den-crane** [comment]
@vitlibar I am not sure that it's fixed.

Check this https://github.com/yandex/ClickHouse/blob/master/dbms/src/Dictionaries/HTTPDictionarySource.cpp#L57

```
        auto tmp_time = update_time;  // time for current partial update (http_get & updated=tmp_time -1
        update_time = std::chrono::system_clock::now(); // unconditionally set time for next check.

      ......
        do   http_get & updated=tmp_time -1
        { update FAILED for example because of network issue }
        oops we already set update_time to next check and we lost previous value of update_time
     ....     
```
The same for all other dicts.

**Comment by vitlibar** [comment]
I still think the problem is already fixed (in another place).

**Comment by den-crane** [comment]
https://github.com/yandex/ClickHouse/blob/master/dbms/src/Dictionaries/HTTPDictionarySource.cpp#L57

update_time = std::chrono::system_clock::now();

Речь про частичное обновление.
Мы запоминаем новое время, до запроса изменений из бекэнда.
Если обновление неуспешно, в следующем цикле partial update мы 
прочитаем обновления с новой точки, и теряем частичное изменение неудачного.

**Comment by SaltTan** [comment]
I could not reproduce this on 19.13.3
