### ISSUE TITLE
An object with engine=Dictionary makes all dictionaries to load earlier than tables

### ISSUE THREAD

**Issue by SaltTan** [yandex/ClickHouse#2870]
I have a problem with that, because I have a dictionary with source=ClickHouse and lifetime=0.

When CH restarts, it tries to load the dictionary while its source is not available yet. It fails of course, but there is no exception in the system.dictionaries table, the dictionary is just empty (element_count=0).

dictGet* functions do not trigger an update either, so the dictionary stays empty until I run 'system reload dictionary'.

In my environment dictionaries_lazy_load is not set to anything, and when I drop all tables and databases with engine=Dictionary the dictionaries are not loaded at startup.
In this case the dictionary would load when the table is already available.

I would like CH to load dictionaries AFTER it went online if dictionaries_lazy_load is on (even if there are tables with engine=Dictionary), or at least remember that there was an exception.

**Comment by den-crane** [comment]
There are two issues:
1. table with  engine=Dictionary or database=Dictionary breaks dictionaries_lazy_load
2. dictionary stays empty forever because it failed to load on CH startup (with lifetime=0) because CH table was not ready.

**Comment by alexey-milovidov** [comment]
@s-mx is going to fix this issue.

**Comment by alexey-milovidov** [comment]
Fixed in master.
