### ISSUE TITLE
Build ClickHouse-18.1.0-stable for centos6 error

### ISSUE THREAD

**Issue by qinzl1** [yandex/ClickHouse#2874]
cmake3 --version
cmake3 version 3.6.1
gcc --version   
gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Copyright (C) 2017 Free Software Foundation, Inc.

cmake3 ..
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE is not set, set to default = RELWITHDEBINFO
-- CMAKE_BUILD_TYPE: RELWITHDEBINFO
-- Performing Test HAVE_SSE41
-- Performing Test HAVE_SSE41 - Success
-- Performing Test HAVE_SSE42
-- Performing Test HAVE_SSE42 - Success
-- Performing Test HAVE_POPCNT
-- Performing Test HAVE_POPCNT - Success
-- Performing Test HAVE_NO_PIE
-- Performing Test HAVE_NO_PIE - Success
-- Tests are enabled
-- Building for: Linux-2.6.32-573.el6.x86_64 x86_64  ; USE_STATIC_LIBRARIES=ON MAKE_STATIC_LIBRARIES=ON UNBUNDLED=OFF CCACHE=CCACHE_FOUND-NOTFOUND 
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_LIBRARIES) (found version "1.0.1e")
-- Using ssl=1: /usr/include : /usr/lib64/libssl.so;/usr/lib64/libcrypto.so
-- Build without ICU (support for collations and charset conversion functions will be disabled)
CMake Warning at cmake/find_boost.cmake:5 (message):
  submodules in contrib/boost is missing.  to fix try run:

   git submodule update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:255 (include)

CMake Warning at /usr/share/cmake3/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake3/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake3/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
  cmake/find_boost.cmake:12 (find_package)
  CMakeLists.txt:255 (include)

CMake Warning at /usr/share/cmake3/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake3/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake3/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
  cmake/find_boost.cmake:12 (find_package)
  CMakeLists.txt:255 (include)

CMake Warning at /usr/share/cmake3/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake3/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake3/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
  cmake/find_boost.cmake:12 (find_package)
  CMakeLists.txt:255 (include)

CMake Warning at /usr/share/cmake3/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake3/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake3/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
  cmake/find_boost.cmake:12 (find_package)
  CMakeLists.txt:255 (include)

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Could NOT find Boost
-- Using Boost: /usr/local/ClickHouse-18.1.0-stable/contrib/boost : boost_program_options_internal,boost_system_internal,boost_filesystem_internal
-- Using zlib: /usr/local/ClickHouse-18.1.0-stable/contrib/zlib-ng;/usr/local/ClickHouse-18.1.0-stable/build/contrib/zlib-ng : zlibstatic
CMake Warning at cmake/find_zstd.cmake:4 (message):
  submodule contrib/zstd is missing.  to fix try run:

   git submodule update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:258 (include)

-- Using zstd: ZSTD_INCLUDE_DIR-NOTFOUND : zstd
-- Using ltdl: LTDL_LIBRARY-NOTFOUND
-- Using termcap: /usr/lib64/libtermcap.so
-- Could NOT find ODBC (missing:  ODBC_INCLUDE_DIRECTORIES ODBC_LIBRARIES) 
-- Using odbc: ODBC_INCLUDE_DIRECTORIES-NOTFOUND : ODBC_LIBRARIES-NOTFOUND
CMake Warning at cmake/find_poco.cmake:5 (message):
  submodule contrib/poco is missing.  to fix try run:

   git submodule update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:267 (include)

-- Looking for Poco install directory structure.
-- Poco: Could not find Poco install directory
-- Using Poco:  : ,,,,,,,,,,; MongoDB=, DataODBC=, NetSSL=
CMake Warning at cmake/find_lz4.cmake:4 (message):
  submodule contrib/lz4 is missing.  to fix try run:

   git submodule update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:268 (include)

-- Using lz4: /usr/local/ClickHouse-18.1.0-stable/contrib/lz4/lib : lz4
-- Using sparsehash: /usr/local/ClickHouse-18.1.0-stable/contrib/libsparsehash
-- Using rt: 
-- Using line editing libraries (readline): /usr/include : /usr/lib64/libreadline.so;/usr/lib64/libtermcap.so
-- Performing Test HAVE_READLINE_HISTORY
-- Performing Test HAVE_READLINE_HISTORY - Success
-- Using re2:  : re2;  : re2_st
CMake Warning at cmake/find_rdkafka.cmake:8 (message):
  submodule contrib/librdkafka is missing.  to fix try run:

   git submodule update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:274 (include)

-- Using librdkafka=1: /usr/local/include : /usr/local/lib/librdkafka.a;/usr/lib64/libssl.so;/usr/lib64/libcrypto.so;/usr/lib64/libsasl2.so.2;lz4
-- Build without capnp (support for Cap'n Proto format will be disabled)
CMake Warning at cmake/find_llvm.cmake:18 (find_package):
  Could not find a package configuration file provided by "LLVM" (requested
  version 6) with any of the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:276 (include)

CMake Warning at cmake/find_llvm.cmake:20 (find_package):
  Could not find a package configuration file provided by "LLVM" (requested
  version 5) with any of the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:276 (include)

CMake Warning at cmake/find_llvm.cmake:23 (find_package):
  Could not find a package configuration file provided by "LLVM" (requested
  version 7) with any of the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:276 (include)

-- Using cpuid: /usr/local/ClickHouse-18.1.0-stable/contrib/libcpuid/include : cpuid
-- Using cityhash: /usr/local/ClickHouse-18.1.0-stable/contrib/cityhash102/include : cityhash
-- Using farmhash:  : farmhash
-- Using metrohash:  : metrohash
-- Using btrie:  : btrie
-- Using double-conversion: /usr/local/ClickHouse-18.1.0-stable/contrib/double-conversion : double-conversion
-- Using tcmalloc=1: /usr/local/ClickHouse-18.1.0-stable/contrib/libtcmalloc/include : tcmalloc_minimal_internal
CMake Warning at libs/libcommon/cmake/find_cctz.cmake:4 (message):
  submodule contrib/cctz is missing.  to fix try run:

   git submodule update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:289 (include)

-- Using cctz: CCTZ_INCLUDE_DIR-NOTFOUND : CCTZ_LIBRARY-NOTFOUND
-- Using mysqlclient=1: /usr/include : ; staticlib=/usr/lib64/mysql/libmysqlclient.so
-- Using unwind=1: /usr/local/ClickHouse-18.1.0-stable/contrib/libunwind/include : unwind
-- compiler C   = /opt/rh/devtoolset-7/root/usr/bin/cc   -D_GLIBCXX_USE_CXX11_ABI=1 -pipe -msse4.1 -msse4.2 -mpopcnt -fno-omit-frame-pointer  -Wall   -no-pie -O2 -g -DNDEBUG -O3 
-- compiler CXX = /opt/rh/devtoolset-7/root/usr/bin/c++  -std=c++1z  -D_GLIBCXX_USE_CXX11_ABI=1 -pipe -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall  -Wnon-virtual-dtor  -no-pie -O2 -g -DNDEBUG -O3 
-- LINKER_FLAGS =  -static-libgcc -static-libstdc++ 
CMake Error at contrib/zstd-cmake/CMakeLists.txt:46 (FILE):
  file failed to open for reading (No such file or directory):

    /usr/local/ClickHouse-18.1.0-stable/contrib/zstd/lib/zstd.h

-- ZSTD VERSION ..
CMake Error at contrib/CMakeLists.txt:19 (add_subdirectory):
  The source directory

    /usr/local/ClickHouse-18.1.0-stable/contrib/re2

  does not contain a CMakeLists.txt file.

CMake Warning (dev) at contrib/re2_st/CMakeLists.txt:8 (get_target_property):
  Policy CMP0045 is not set: Error on non-existent target in
  get_target_property.  Run "cmake --help-policy CMP0045" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  get_target_property() called with non-existent target "re2".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at contrib/CMakeLists.txt:25 (add_subdirectory):
  The source directory

    /usr/local/ClickHouse-18.1.0-stable/contrib/double-conversion

  does not contain a CMakeLists.txt file.

-- The ASM compiler identification is GNU
-- Found assembler: /opt/rh/devtoolset-7/root/usr/bin/cc
CMake Error at contrib/CMakeLists.txt:49 (add_subdirectory):
  The source directory

    /usr/local/ClickHouse-18.1.0-stable/contrib/zlib-ng

  does not contain a CMakeLists.txt file.

CMake Error at contrib/CMakeLists.txt:52 (target_compile_definitions):
  Cannot specify compile definitions for target "zlib" which is not built by
  this project.

CMake Error at contrib/CMakeLists.txt:53 (target_compile_definitions):
  Cannot specify compile definitions for target "zlibstatic" which is not
  built by this project.

CMake Error at contrib/CMakeLists.txt:55 (target_compile_definitions):
  Cannot specify compile definitions for target "zlib" which is not built by
  this project.

CMake Error at contrib/CMakeLists.txt:56 (target_compile_definitions):
  Cannot specify compile definitions for target "zlibstatic" which is not
  built by this project.

CMake Error at contrib/CMakeLists.txt:59 (set_target_properties):
  set_target_properties Can not find target to add properties to: example

CMake Error at contrib/CMakeLists.txt:64 (set_target_properties):
  set_target_properties Can not find target to add properties to: minigzip

-- Building: tcmalloc_minimal_internal
-- Link libtcmalloc_minimal : tcmalloc_minimal_internal
-- Will build ClickHouse 18.1.0
-- Using internal=OFF compiler=0: headers=/usr/share/clickhouse/headers :  clickhouse-clang  -std=c++1z  -D_GLIBCXX_USE_CXX11_ABI=1 -pipe -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall  -Wnon-virtual-dtor   -Wextra -Werror -O2 -g -DNDEBUG -O3   -x c++ -march=native -fPIC -fvisibility=hidden -fno-implement-inlines -nostdinc -nostdinc++ -Wno-unused-command-line-argument -Bprefix=/usr/share/clickhouse -isysroot=/usr/share/clickhouse/headers; clickhouse-lld
-- Target check already exists
CMake Warning at cmake/find_gtest.cmake:5 (message):
  submodule contrib/googletest is missing.  to fix try run:

   git submodule update --init --recursive
Call Stack (most recent call first):
  dbms/CMakeLists.txt:247 (include)

-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Using gtest:  : 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/usr/local/ClickHouse-18.1.0-stable/libs/libcommon/CCTZ_INCLUDE_DIR
   used as include directory in directory /usr/local/ClickHouse-18.1.0-stable/libs/libcommon
CCTZ_LIBRARY
    linked by target "common" in directory /usr/local/ClickHouse-18.1.0-stable/libs/libcommon

-- Configuring incomplete, errors occurred!
See also "/usr/local/ClickHouse-18.1.0-stable/build/CMakeFiles/CMakeOutput.log".
See also "/usr/local/ClickHouse-18.1.0-stable/build/CMakeFiles/CMakeError.log".

**Comment by alexey-milovidov** [comment]
> git submodule update --init --recursive
