### ISSUE TITLE
lost backslashes in CSV format

### ISSUE THREAD

**Issue by konkov-alexey** [yandex/ClickHouse#2876]
if there are some backslashes on the end of text field, then you get erroneous csv.

0. server version 1.1.54390
1. table with fields id, str, int
2. values: 1, 'some text \\', 0
3. when we use FORMAT CSV the string `1,"some text \",0` is generated
4. so backslash now escape double-quote and csv could not be correctly parsed

==========================

если текстовое поле заканчивается несколькими обратными слэшами, при выводе в формате csv получается ошибка.

0. версия сервера 1.1.54390
1. таблица id, str, int
2. строка значений: 1, 'some text \\', 0
3. при выгрузке в csv получаем строку 1,"some text \",0
4. при этом получается экранированная слэшом кавычка, что не даёт правильно распарсить csv штатными средствами

**Comment by 4ertus2** [comment]
Can't reproduce on master branch:

$ ./clickhouse-client -nq 'DROP TABLE t; CREATE TABLE t (id UInt32, str String, int Int32) engine = Memory; INSERT INTO t FORMAT CSV' < ~/clickhouse/test/2876.csv
$ ./clickhouse-client -q 'SELECT * FROM t'
1       some text \\    0
$ cat ~/clickhouse/test/2876.csv
1,"some text \",0

**Comment by konkov-alexey** [comment]
1. create table Temp (date Date, id Int8, s String, i Int8) ENGINE = MergeTree(date, (id, date) , 8192);
2. insert into Temp values(today(), 1, 'some text\\', 0);
3. select * from Temp;
2018-08-16 │  1 │ some text\\ │ 0
4. select * from Temp format CSV;
"2018-08-16",1,"some text\",0

and result of selecting in CSV format -- is not correct CSV
===
и вот результат выбора в формате CSV -- уже не является корректным CSV

**Comment by konkov-alexey** [comment]
yep, by default php csv-parser use backslash as escape symbol instead of double-quote. changing escape symbol to double quote solves the problem.

===

по-умолчанию пхп-парсер использует эскейп-символом обратный слэш. если поставить эскейп-символом двойные кавычки, то всё работает корректно.
