### ISSUE TITLE
how to read json correctly

### ISSUE THREAD

**Issue by laoguanjie** [yandex/ClickHouse#2880]
query like :
```
 select visitParamExtractRaw('{"first":{"second":{"value":"null"}},"second":"target"}', 'second')
```
i want to get the value of "target", but it return {"value":"null"}
how can i read value in json?

**Comment by den-crane** [comment]
This is a feature as documented:
Fields are searched for on any nesting level, indiscriminately. If there are multiple matching fields, the first occurrence is used.
https://clickhouse.yandex/docs/en/query_language/functions/json_functions/
