### ISSUE TITLE
How to implement MERGE update in ClickHouse

### ISSUE THREAD

**Issue by DeanThompson** [yandex/ClickHouse#2883]
There are two tables with the same structure, the `target` holds history data, and the `staging` holds the incremental data. I want to load the incremental data into target, update the records with same primary keys and insert all new added ones.

In MySQL, this can be done by a combination of `LEFT JOIN` and `UNION ALL`:

```sql
SELECT target.* FROM target LEFT JOIN staging USING (id) WHERE staging.id IS NULL

UNION ALL

SELECT * FROM staging
```

How can I do this in ClickHouse?

Any comments will be help, thanks.

**Comment by DeanThompson** [comment]
I had tried the following SQL

```sql
SELECT target.* FROM target ALL LEFT JOIN staging USING id WHERE staging.id IS NULL

UNION ALL

SELECT * FROM staging

```

But ClickHouse said

```
Received exception from server (version 18.6.0):
Code: 47. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Unknown identifier: default.staging.id.
```

**Comment by DeanThompson** [comment]
I found a work around, but wondering if there is a better solution.

```sql
SELECT *
FROM target
WHERE NOT (id IN
(
    SELECT id
    FROM staging
))
UNION ALL
SELECT *
FROM staging
```

**Comment by 4ertus2** [comment]
I don't think 'SELECT * FROM target' is a good solution on big data. You probably have a date column with partitioning on it. Would it be enough to update just a time interval including some old records? If so, it should be much faster. Cause if you have partitioned table in ClickHouse and date predicate in select it would use only needed parts.

If not and you really need all the data, your have to read all 'id' columns from both target and staging. So your work around looks OK.

**Comment by blinkov** [comment]
@DeanThompson consider using https://clickhouse.yandex/docs/en/operations/table_engines/collapsingmergetree/ for this, if used properly it'll allow to get rid of a staging table in the first place.

**Comment by DeanThompson** [comment]
@blinkov Thanks for the suggestion, I would use CollapsingMergeTree in the future.
