### ISSUE TITLE
Ways to include per user configuration from external files

### ISSUE THREAD

**Issue by pavel-odintsov** [yandex/ClickHouse#2892]
Hello!

I'm working on some ways to simplify user management for Clickhouse.

Global user configuration file "/etc/clickhouse-server/users.xml" does not work for me very well. Because it requires complicated logic when we add/remove users.

I have two options to maintain it properly:
- Regenerate this user.xml file each time when we add new user external source (JSON/YAML). But it requires external code to generate it and increases complexity.
- Read content of existing file, add new section, write changes. But it also involves pretty tricky XML processing and can break something.

I'm interested in extracting this information to separate files:
```
<admin>
  <password>new_password</password>
  <networks incl="networks" replace="replace">
    <ip>::/0</ip>
  </networks>
  <profile>default</profile>
  <quota>default</quota>
</admin>
```

Is there is any way to extract configuration for each use in separate file? 

Thank you!

**Comment by alexey-milovidov** [comment]
Sure. You can add files for each user inside `/etc/clickhouse-server/users.d` directory.

**Comment by alexey-milovidov** [comment]
```
$ cat /etc/clickhouse-server/users.d/alice.xml
<yandex>
  <users>
      <alice>
          <profile>analytics</profile>
            <networks>
                  <ip>::/0</ip>
            </networks>
          <password_sha256_hex>...</password_sha256_hex>
          <quota>analytics</quota>
      </alice>
    </users>
</yandex>
```

**Comment by alexey-milovidov** [comment]
The list of external files is tracked and updated on the fly.

**Comment by pavel-odintsov** [comment]
Hello!

Wow! That's awesome! It works for me!
