### ISSUE TITLE
Is there a way to check mutation is in progress?

### ISSUE THREAD

**Issue by simPod** [yandex/ClickHouse#2895]
I recently triggered a DELETE mutation on relatively small table. Is there a way I can see it is in progress or approximatelly determine when it will finish? 
In `mutations` table I can only see `parts_to_do=1` but nothing else.

Thanks

**Comment by alexey-milovidov** [comment]
> In mutations table I can only see parts_to_do=1 but nothing else.

There is nothing else to track mutations: only system.mutations table.

**Comment by alexey-milovidov** [comment]
For Replicated tables, you can also look at `system.replication_queue`.

**Comment by simPod** [comment]
Thank you! 

For those wondering, also check server error log.
