### ISSUE TITLE
[Question] ALTER DELETE in Materialized Views

### ISSUE THREAD

**Issue by simPod** [yandex/ClickHouse#2897]
Hello, will alter delete work for materialized views as well? Thanks

**Comment by alexey-milovidov** [comment]
You have to apply it to `.inner.` table (that you can find in `system.tables`) and mutations will work if the underlying storage is of MergeTree family.

**Comment by simPod** [comment]
Thank's for the reply! I also see you implememented query forwarding to the underlying table 👍
