### ISSUE TITLE
C++ client

### ISSUE THREAD

**Issue by ggodik** [yandex/ClickHouse#29]
The documentation makes a reference to a C++ API / some way of programmaticly accessing a ClickHouse server via C++ via TCP.

Can you guys separate it out into a libclickhouseclient and provide headers?

Excuse my ignorance if this exists already and I'm unable to find it.

**Comment by alexey-milovidov** [comment]
We have C++ API internally. Drawback is that it depends on (almost) whole ClickHouse codebase.
We could open it, but I am not sure, would it be appropriate solution.
Linking with whole ClickHouse is ugly.

Maybe, we could open it with many precautions statements.

**Comment by ggodik** [comment]
@alexey-milovidov Спасибо за быстрый ответ

Do you see any benefits to using the C++ API vs going over http. Is the TCP interface somehow more efficient, less chatty, etc?

**Comment by alexey-milovidov** [comment]
> Do you see any benefits to using the C++ API vs going over http. Is the TCP interface somehow more efficient, less chatty, etc?

There are some benefits, but (I think) not crucial.

**Comment by artpaul** [comment]
For anyone who interested in native C++ client please take a look at https://github.com/artpaul/clickhouse-cpp

**Comment by silviucpp** [comment]
This task should be closed

**Comment by ibrarahmad** [comment]
What are the native options available? I really don't want to use third party solution.
