### ISSUE TITLE
Strange text format in documentation

### ISSUE THREAD

**Issue by brigadier** [yandex/ClickHouse#290]
It looks like you use some mix of html and preformatted text in the documentation. So in the browser it looks like a wall of text http://imgur.com/a/SsfMi 
It is easier to view the docs as plain text, but in this case it contains html tags.

Do you use some plugin to read the docs?

**Comment by alexey-milovidov** [comment]
Documentation is preprocessed by JavaScript code (located inline, at end of HTML).
If documentation doesn't look properly for you, check that JS is enabled, and there is not JS related errors. You could look for errors in browser console (in Firefox and Chrome, press F12). 

Please tell me if there are any JS errors in console.

Also, documentation is a single huge HTML (400KB). If you are using mobile connection, probably it had not been loaded completely.

**Comment by brigadier** [comment]
You are right, the problem is that I have yandex.st (and ajax.googleapis.com too, so don't take it personal) blocked in /etc/hosts on my laptop. Because of that jquery won't load and text is not postprocessed.
