### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by coreground** [yandex/ClickHouse#2902]
2018.08.20 16:37:49.453360 [ 10036 ] <Error> BaseDaemon: ########################################
2018.08.20 16:37:49.453443 [ 10036 ] <Error> BaseDaemon: (from thread 2295) Received signal Segmentation fault (11).
2018.08.20 16:37:49.453486 [ 10036 ] <Error> BaseDaemon: Address: 0x1c0ee0
2018.08.20 16:37:49.453632 [ 10036 ] <Error> BaseDaemon: Access: write.
2018.08.20 16:37:49.453665 [ 10036 ] <Error> BaseDaemon: Address not mapped to object.
2018.08.20 16:37:49.523031 [ 10036 ] <Error> BaseDaemon: 0. /usr/bin/clickhouse-server(vtable for DB::DataTypeNumber<unsigned long>+0x18) [0xd6ec3a0]
2018.08.20 16:37:49.523089 [ 10036 ] <Error> BaseDaemon: 1. /usr/bin/clickhouse-server(auto ext::collection_cast<DB::NamesAndTypesList, boost::range::joined_range<DB::NamesAndTypesList const, DB::NamesAndTypesList const> >(boost::range::joined_range<DB::NamesAndTypesList const, DB::NamesAndTypesList const> const&)+0x1bb) [0x4f82dcb]
2018.08.20 16:37:49.523118 [ 10036 ] <Error> BaseDaemon: 2. /usr/bin/clickhouse-server(DB::ColumnsDescription::getAllPhysical() const+0x5b) [0x4f7f93b]
2018.08.20 16:37:49.523147 [ 10036 ] <Error> BaseDaemon: 3. /usr/bin/clickhouse-server(DB::ITableDeclaration::check(DB::Block const&, bool) const+0x5f) [0x4f8e6ff]
2018.08.20 16:37:49.523174 [ 10036 ] <Error> BaseDaemon: 4. /usr/bin/clickhouse-server(DB::MergeTreeDataWriter::splitBlockIntoParts(DB::Block const&)+0xa0) [0x50926e0]
2018.08.20 16:37:49.523200 [ 10036 ] <Error> BaseDaemon: 5. /usr/bin/clickhouse-server(DB::MergeTreeBlockOutputStream::write(DB::Block const&)+0x5a) [0x503718a]
2018.08.20 16:37:49.523226 [ 10036 ] <Error> BaseDaemon: 6. /usr/bin/clickhouse-server(DB::PushingToViewsBlockOutputStream::write(DB::Block const&)+0x43) [0x520c623]
2018.08.20 16:37:49.523253 [ 10036 ] <Error> BaseDaemon: 7. /usr/bin/clickhouse-server(DB::PushingToViewsBlockOutputStream::write(DB::Block const&)+0x478) [0x520ca58]
2018.08.20 16:37:49.523295 [ 10036 ] <Error> BaseDaemon: 8. /usr/bin/clickhouse-server(DB::AddingDefaultBlockOutputStream::write(DB::Block const&)+0x6b8) [0x51911b8]
2018.08.20 16:37:49.523321 [ 10036 ] <Error> BaseDaemon: 9. /usr/bin/clickhouse-server(DB::SquashingBlockOutputStream::finalize()+0x248) [0x5211978]
2018.08.20 16:37:49.523346 [ 10036 ] <Error> BaseDaemon: 10. /usr/bin/clickhouse-server(DB::SquashingBlockOutputStream::writeSuffix()+0x11) [0x5211c01]
2018.08.20 16:37:49.523395 [ 10036 ] <Error> BaseDaemon: 11. /usr/bin/clickhouse-server(DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::atomic<bool>*)+0x51a) [0x477f86a]
2018.08.20 16:37:49.523422 [ 10036 ] <Error> BaseDaemon: 12. /usr/bin/clickhouse-server(DB::StorageKafka::streamToViews()+0x655) [0x53a8b65]
2018.08.20 16:37:49.523447 [ 10036 ] <Error> BaseDaemon: 13. /usr/bin/clickhouse-server(DB::StorageKafka::streamThread()+0x264) [0x53a9224]
2018.08.20 16:37:49.523470 [ 10036 ] <Error> BaseDaemon: 14. /usr/bin/clickhouse-server() [0x938cc0f]
2018.08.20 16:37:49.523504 [ 10036 ] <Error> BaseDaemon: 15. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f79b07e16db]

**Comment by alexey-milovidov** [comment]
Please provide more details on this issue:
- what version of ClickHouse do you run;
- do you use Yandex packages, Altinity packages or built ClickHouse by yourself;
- install `clickhouse-common-dbg` package and run `addr2line -iCe /usr/bin/clickhouse 0x4f82dcb 0x4f7f93b ...` for all addresses from the stack trace;
- what is your database schema;
- how frequently does the issue reproduce;
- it there simple way to trigger the issue (isolated test case is the best).

**Comment by coreground** [comment]
version 18.6.0 pulled from  docker.io:

REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
docker.io/yandex/clickhouse-client   latest              85ab63b6bb17        2 weeks ago         349 MB
docker.io/yandex/clickhouse-server   latest              e129e1cdb731        2 weeks ago         376 MB

The issue can be reproduced if you try to drop a table before you detach a materialized view.  Obviously not the correct order of operations. 

DROP TABLE IF EXISTS netflow_full_queue;
create table IF NOT EXISTS netflow_full_queue (
app_cat String,
app_id String,
app_name String,
app_desc String,
as_dst UInt32,
as_path String,
as_src UInt32,
bytes UInt64,
class String,
cos UInt16,
country_ip_dst String,
country_ip_src String,
etype String,
flows UInt32,
iface_in UInt16,
iface_out UInt16,
ip_dst String,
ip_proto String,
ip_src String,
label String,
mac_dst String,
mac_src String,
mpls_vpn_rd String,
nat_event UInt16,
packets UInt64,
peer_ip_src String,
port_dst UInt16,
port_src UInt16,
post_nat_ip_dst String,
post_nat_ip_src String,
post_nat_port_dst UInt16,
post_nat_port_src UInt16,
src_as_path String,
src_local_pref UInt16,
tag UInt16,
tag2 UInt16,
tcp_flags String,
timestamp_arrival String,
timestamp_end String,
timestamp_start String,
tos UInt16,
vlan UInt16,
stamp_inserted String,
stamp_updated String,
threat_match UInt16 DEFAULT 0,
record_date Date DEFAULT toDate(now())
)
ENGINE = Kafka('host:9092', 'queue', 'consumer', 'JSONEachRow');

drop table IF EXISTS netflow_full;
create table IF NOT EXISTS netflow_full (
customer_id String DEFAULT '',
bundle_id String DEFAULT '',
threat_match UInt16 DEFAULT 99, 
app_cat String,
app_id String,
app_name String,
app_desc String,
as_dst UInt32,
as_dst_org String DEFAULT '',
as_path String,
as_src UInt32,
as_src_org String DEFAULT '',
bytes UInt64,
class String,
cos UInt16,
country_ip_dst String,
country_ip_src String,
etype String,
flows UInt32,
iface_in UInt16,
iface_out UInt16,
ip_dst String,
ip_proto String,
ip_src String,
label String,
mac_dst String,
mac_src String,
mpls_vpn_rd String,
nat_event UInt16,
packets UInt64,
peer_ip_src String,
port_dst UInt16,
port_src UInt16,
post_nat_ip_dst String,
post_nat_ip_src String,
post_nat_port_dst UInt16,
post_nat_port_src UInt16,
src_as_path String,
src_local_pref UInt16,
tag UInt16,
tag2 UInt16,
tcp_flags String,
timestamp_arrival DateTime,
timestamp_end DateTime,
timestamp_start DateTime,
tos UInt16,
vlan UInt16,
stamp_inserted DateTime,
stamp_updated DateTime,
record_date Date
)
ENGINE = MergeTree(record_date, (stamp_inserted, customer_id, bundle_id, peer_ip_src, iface_in, ip_src, app_name, ip_dst, country_ip_dst, port_dst ), 8192);



DETACH TABLE IF EXISTS MV_netflow_full;
CREATE MATERIALIZED VIEW MV_netflow_full TO netflow_full
    AS SELECT
    '00' as customer_id,
    '00' as bundle_id,
	peer_ip_src,
	app_id,
	dictGetString('app_data', 'app_name', tuple(app_id)) as app_name,
	dictGetString('app_data', 'app_desc', tuple(app_id)) as app_desc,
    dictGetString('app_data', 'app_cat', tuple(app_id)) as app_cat,
	class,
	cos,
	tos,
	vlan,
	ip_dst,
	ip_proto,
	ip_src,
	dictGetString('citydetails', 'country_name', dictGetUInt64('ip2city', 'geoname_id',tuple(IPv4StringToNum(ip_dst))) ) AS country_ip_dst,
	dictGetString('citydetails', 'country_name', dictGetUInt64('ip2city', 'geoname_id',tuple(IPv4StringToNum(ip_src))) ) AS country_ip_src,
	toUInt16(dictHas('threat_name',tuple(IPv4StringToNum(ip_dst)))) AS threat_match,
	port_dst,
	port_src,
	post_nat_ip_dst,
	post_nat_ip_src,
	post_nat_port_dst,
	post_nat_port_src,
	toDateTime( stamp_inserted ) AS stamp_inserted,
	toDateTime( stamp_updated ) AS stamp_updated,
	packets,
	bytes,	
	toDateTime( replaceRegexpOne( timestamp_start,'^(.*)T(.*)[.]0.*$','\\1 \\2' )) AS timestamp_start,
	toDateTime( replaceRegexpOne( timestamp_end,'^(.*)T(.*)[.]0.*$','\\1 \\2' )) AS timestamp_end,
	toDateTime( replaceRegexpOne( timestamp_arrival,'^(.*)T(.*)[.]0.*$','\\1 \\2' )) AS timestamp_arrival,
	toDate( stamp_inserted ) AS record_date,
	dictGetString('ip2asn','autonomous_system_organization' ,tuple(IPv4StringToNum(ip_src))) as as_src_org,
	dictGetUInt32('ip2asn','autonomous_system_number' ,tuple(IPv4StringToNum(ip_src))) as as_src,
	dictGetString('ip2asn','autonomous_system_organization' ,tuple(IPv4StringToNum(ip_dst))) as as_dst_org,
	dictGetUInt32('ip2asn','autonomous_system_number' ,tuple(IPv4StringToNum(ip_dst))) as as_dst,
	as_path,
	etype,
	flows,
	iface_in,
	iface_out,
	label,
	mac_dst,
	mac_src,
	mpls_vpn_rd,
	nat_event,
	src_as_path,
	src_local_pref,
	tag,
	tag2,
	tcp_flags
	FROM netflow_full_queue

**Comment by filimonov** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.

Kafka engine had a lot of changes/fixes in 19.7 and 19.8. Please try it.

Please reopen if you still encounter this issue with the latest stable version.

Thank you!
