### ISSUE TITLE
Status of LowCardinality feature

### ISSUE THREAD

**Issue by champtar** [yandex/ClickHouse#2903]
Hi ClickHouse team,

I tried to read the design document of the LowCardinality feature (https://gist.github.com/alexey-milovidov/ebdc6a0b8731fdba9438bda3ec6e8ca4) using google trad, I tested and saw the nice size improvements, and I'm just wondering why it's behind "experimental" flag:
- Do you have some missing parts to implement ? (performance improvements ?)
- Are you waiting to iron out the remaining bugs ?
- Do you have doubts about the design ?
- doubts about the on disk format ?
- ...?

I'm just trying to have an idea of when I can try it in production ;)

Thanks a lot!

**Comment by champtar** [comment]
Asking on google groups instead of here
https://groups.google.com/forum/#!topic/clickhouse/izXdc52aF0k

**Comment by alexey-milovidov** [comment]
Answered in groups.
