### ISSUE TITLE
LowCardinality performance issue

### ISSUE THREAD

**Issue by champtar** [yandex/ClickHouse#2904]
Hello ClickHouse team,

Trying out LowCadinality i expected "big" performance improvements, but request time is almost the same
Here my tests table:
```
CREATE TABLE testlowcardinality2
(
    date Date, 
    datetime DateTime, 
    a_nolow String, 
    a_low LowCardinality(String)
)
ENGINE = MergeTree
PARTITION BY date
ORDER BY date
SETTINGS index_granularity = 8192;

INSERT INTO testlowcardinality2 SELECT date, datetime, user_agent, user_agent FROM <another table>;
(ie a_low == a_low / no particular sorting)

SELECT count() FROM testlowcardinality2;
=> 1454437957

SELECT uniq(a_nolow) FROM testlowcardinality2;
=> 244

SELECT avg(length(a_nolow)) FROM testlowcardinality2;
=> 50.332
```

When doing count / group by a_*, timing is pretty close
```
SELECT a_nolow, count() FROM testlowcardinality2 GROUP BY a_nolow ORDER BY count() DESC LIMIT 10;
=> 10 rows in set. Elapsed: 5.406 sec. Processed 1.45 billion rows, 86.30 GB (269.02 million rows/s., 15.96 GB/s.)

SELECT a_low, count() FROM testlowcardinality2 GROUP BY a_low ORDER BY count() DESC LIMIT 10;
=> 10 rows in set. Elapsed: 5.142 sec. Processed 1.45 billion rows, 1.71 GB (282.84 million rows/s., 332.84 MB/s.)
```

Playing with perf + flamegraph (https://github.com/brendangregg/FlameGraph)
```
perf record -F 99 -p $(pidof clickhouse-server) -g -- sleep 60
perf script | ./stackcollapse-perf.pl > nolow.folded
./flamegraph.pl nolow.folded > nolow.svg
```
I get the 2 following flame graphs (the svg are clickable)
[flame.zip](https://github.com/yandex/ClickHouse/files/2304498/flame.zip)

According to the flame graph, in the case of LowCardinality request, 40% of the time is spent in "convertToFullColumnIfWithDictionary", which seems wrong to me, as we shouldn't need to "materialize" a_low while counting, only at the end when merging result from each parts

If it matters, there is currently 18 parts for table testlowcardinality2

Thanks in advance

**Comment by alexey-milovidov** [comment]
GROUP by is not optimized yet for LowCardinality data type. It is still to do.

Currently the most performance benefit happens:
- when you apply filtering (WHERE), by LowCardinality column or by any other column (because filtering itself is much faster);
- when you apply functions on LowCardinality column (though this optimization is not finished because calculation with Dictionary is repeated for each block).

Nikolay have nice presentation about current state of LowCardinality column:
https://yandex.github.io/clickhouse-presentations/meetup17/1_low_cardinality_strings.pdf
(it is in russian, but most of the content is tables and diagrams)

**Comment by alexey-milovidov** [comment]
PS. About your flame graph:

In production build you should have `memcpy` instead of `__memcpy_ssse3_back`, because we use internal variant of memcpy instead of libc.

`CRC32Hash::operator()`, `memEqualSSE2Wide` and `Aggregator...::getKey` methods should probably better to be inlined (note that clang inlines slightly worse than gcc).

And Nikolay is doing some research to optimize `IColumn::index` method.

**Comment by champtar** [comment]
Thanks a lot @alexey-milovidov 
I'm using CentOS 7 / GCC 7 building with `-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo`
```
-- Will build ClickHouse 18.11.0
-- Using internal=OFF compiler=0: headers=/usr/share/clickhouse/headers/18.11.0 :  clickhouse-clang   -pipe -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall  -Wnon-virtual-dtor  -Wextra -Werror -O2 -g -DNDEBUG -O3  -std=c++1z -x c++ -march=native -fPIC -fvisibility=hidden -fno-implement-inlines -nostdinc -nostdinc++ -Wno-unused-command-line-argument -Bprefix=/usr/share/clickhouse -isysroot=/usr/share/clickhouse/headers/18.11.0; clickhouse-lld
```

 I though I needed `-g` to have proper debug packages but that but maybe it's a bad idea, and I should stick to `Release` ?

**Comment by champtar** [comment]
Just tried with `Release`
```
# cat build/dbms/src/Common/config_build.cpp
// .cpp autogenerated by cmake

#include <Common/config_build.h>

const char * auto_config_build[]
{
    "VERSION_FULL", "ClickHouse 18.11.0",
    "VERSION_DESCRIBE", "v18.11.0-testing",
    "VERSION_GITHASH", "76af46ed5d223b3a7af92e31eae291174da16355",
    "VERSION_REVISION", "54406",
    "BUILD_DATE", "2018-08-21",
    "BUILD_TYPE", "Release",
    "SYSTEM", "Linux-3.10.0-862.11.6.el7.x86_64",
    "SYSTEM_PROCESSOR", "x86_64",
    "LIBRARY_ARCHITECTURE", "",
    "CMAKE_VERSION", "3.12.0",
    "C_COMPILER", "/opt/rh/devtoolset-7/root/usr/bin/cc",
    "C_COMPILER_VERSION", "7.3.1",
    "CXX_COMPILER", "/opt/rh/devtoolset-7/root/usr/bin/c++",
    "CXX_COMPILER_VERSION", "7.3.1",
    "C_FLAGS", "  -pipe -msse4.1 -msse4.2 -mpopcnt -fno-omit-frame-pointer  -Wall  -no-pie -O2 -DNDEBUG",
    "CXX_FLAGS", "  -pipe -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall  -Wnon-virtual-dtor -no-pie -O2 -DNDEBUG",
    "LINK_FLAGS", " -static-libgcc -static-libstdc++",
    "BUILD_COMPILE_DEFINITIONS", "",
    "BUILD_INCLUDE_DIRECTORIES", "",
    "STATIC", "ON",
    "USE_EMBEDDED_COMPILER", "0",
    "USE_INTERNAL_MEMCPY", "",
    "USE_GLIBC_COMPATIBILITY", "",
    "USE_JEMALLOC", "1",
    "USE_TCMALLOC", "",
    "USE_UNWIND", "1",
    "USE_ICU", "1",
    "USE_MYSQL", "1",
    "USE_RE2_ST", "1",
    "USE_VECTORCLASS", "",
    "USE_RDKAFKA", "1",
    "USE_CAPNP", "1",
    "USE_POCO_SQLODBC", "",
    "USE_POCO_DATAODBC", "1",
    "USE_POCO_MONGODB", "1",
    "USE_POCO_NETSSL", "1",

    nullptr, nullptr
};
```

**Comment by alexey-milovidov** [comment]
> I though I needed -g to have proper debug packages but that but maybe it's a bad idea, and I should stick to Release?

There is no performance difference between RelWithDebInfo and Release. In fact we always use RelWithDebInfo.

**Comment by alexey-milovidov** [comment]
We use
```
USE_INTERNAL_MEMCPY
USE_GLIBC_COMPATIBILITY
```
for our build.

Though performance difference could be hardly noticed.

**Comment by champtar** [comment]
Ok, problem is that `CMAKE_LIBRARY_ARCHITECTURE` is no defined or empty on CentOS7, we should use `CMAKE_SYSTEM_PROCESSOR`

**Comment by champtar** [comment]
https://github.com/yandex/ClickHouse/pull/2912

**Comment by zhang2014** [comment]
I have a suggestion, if the data is below a certain threshold, can we use bitmap coding to optimize the storage file ? this should be friendly to file io

**Comment by champtar** [comment]
done in #3138
