### ISSUE TITLE
Cannot connect MongoDB version 4.0 as External Dictionary

### ISSUE THREAD

**Issue by thanhthai3010** [yandex/ClickHouse#2926]
Hi Guys,

I just try to create an external dictionary with MongoDB, but it's seen not work.
I tried to create with the same config to MongoDB version 3.4.10 and everything is ok, but this time is not, ClickHouse even does not output any error log.
I think the problem is because of the version of MongoDB.

Do you have any idea about this problem?

Thank you, guys.

**Comment by alexey-milovidov** [comment]
I wonder, how it is resolved?

**Comment by blinkov** [comment]
@thanhthai3010 yep, please, post the reason/solution in case someone will google this up.

**Comment by thanhthai3010** [comment]
Thank you guys, in my case, the problem is ClickHouse cannot connect to MongoDB using the default `admin` user, with `root` role. So I try with the solution by creating a new MongoDB with reading role only, for example:
`
use test;
db.createUser(
  {
    user: "userReadTest",
    pwd: "read#test#2018",
    roles: [ { role: "read", db: "test" } ]
  }
);
`

Then create ClickHouse dictionary, connect to MongoDB server with these configurations, and the problem was solved.
