### ISSUE TITLE
Block structure mismatch in UNION stream: different number of columns

### ISSUE THREAD

**Issue by yuragr76** [yandex/ClickHouse#2932]
Версия 18.6.0
select по  distributed таблице, которая создана поверх ReplicatedCollapsingMergeTree
`SELECT
date_oper
FROM checks.all_opers final
prewhere date_oper between '2018-08-01' and '2018-08-02'
limit 100`
бросает ошибку
`ClickHouse exception, code: 171, host: 10.177.3.33, port: 8123; Code: 171, e.displayText() = DB::Exception: Block structure mismatch in UNION stream: different number of columns:
date_oper Date UInt16(size = 0)
camera_id UInt64 UInt64(size = 0), date_check_hash UInt64 UInt64(size = 0), date_oper Date UInt16(size = 0), date_oper_hash UInt64 UInt64(size = 0), sign Int8 Int8(size = 0), time_oper DateTime UInt32(size = 0), tr_check_id UInt64 UInt64(size = 0), viol_oper_id UInt64 UInt64(size = 0), e.what() = DB::Exception`
запрос
`SELECT
date_oper
FROM checks.all_opers final
prewhere date_oper between '2018-08-01' and '2018-08-02'
where date_oper between '2018-08-01' and '2018-08-02'
limit 100`
выполняется корректно

**Comment by Ouriel** [comment]
Looks a lots like #2156
