### ISSUE TITLE
approximate Top-K function

### ISSUE THREAD

**Issue by vavrusa** [yandex/ClickHouse#294]
Hi, this is a followup issue to [1] "approximate Top-K" asked on mailing list. Are you working on this / have plans to implement it in near future? I could probably help with it, but wouldn't want to duplicate effort if you're already on it.

[1]: https://groups.google.com/d/msg/clickhouse/MSesFLwmSyQ/wj-G72JECgAJ

**Comment by alexey-milovidov** [comment]
It is not in our near plans, but we are interested. Feel free to contribute!
Surely, we will help.

**Comment by pavel-odintsov** [comment]
+1 for this thing

**Comment by jason-heo** [comment]
Hi,

I'm wondering `approximate Top-K` has already been implemented.

Event though it looks like it merged, I couldn't find its functionality on the ClickHouse documentation.

Thanks.

**Comment by vavrusa** [comment]
I added a basic documentation in the PR https://github.com/yandex/ClickHouse/commit/5f1e65b2523d7fee66404fc764a4c5d281c989fa#diff-f186d69ae6d035b5aecbfa9ccf644ba1 not sure why it's not showing up in documentation pages? cc @blinkov

**Comment by blinkov** [comment]
1. The reference_en.html and reference_ru.html are the original version of documentation and are currenly deprecated. It's actually published as https://clickhouse.yandex/deprecated/reference_en.html and already has your changes.
2. The current documentation lives here https://github.com/yandex/ClickHouse/tree/master/docs , but it's currently in the middle of yet another migration from ReStructured Text to Markdown, so it's kind of temporary frozen in terms of publishing to website either.

**Comment by alexey-milovidov** [comment]
It was forgotten while changing documentation engine. I just created a task to restore the documentation of `topK` and add `anyHeavy`.

**Comment by vavrusa** [comment]
Ah okay, thanks!
