### ISSUE TITLE
Нет подключения к репликам

### ISSUE THREAD

**Issue by valetanddama** [yandex/ClickHouse#296]
Объявил реплики, все они на разных машинах

```
<remote_servers>
    <data>
        <shard>
            <weight>1</weight>
            <internal_replication>1</internal_replication>
            <replica>
                <host>xx.xxx.xx.xxx</host>
                <port>9000</port>
            </replica>
            <replica>
                <host>xx.xxx.xx.xxx</host>
                <port>9000</port>
            </replica>
           <replica>
                <host>xx.xxx.xx.xxx</host>
                <port>9000</port>
            </replica>
        </shard>
    </data>
</remote_servers>
```

в итоге для каждой реплики при выполнение SELECT появляется ошибка

> Code: 209, e.displayText() = DB::NetException: Timeout: connect timed out: xx.xxx.xx.xxx:9000: (54.197.73.250:9000), e.what() = DB::NetException

конфиги стандартные, добавлено только remote_servers

**Comment by alexey-milovidov** [comment]
It means, that server could not connect to specified address in timeout.
Default timeout is quite low: 50 ms (for each of 3 connection tries to each of replica).
If you have geographically distributed cluster, you need to raise the timeout.

It is controlled with `connect_timeout_with_failover_ms` setting.

This setting could be set in `users.xml` file (set for user `default` to change for all users),
or interactively: `SET connect_timeout_with_failover_ms = 1000` in clickhouse-client,
or in parameter of URL: `&connect_timeout_with_failover_ms=1000` in HTTP request.

Also please check, that you have network connectivity between nodes and ports are not closed by firewall. By using telnet:
```telnet 54.197.73.250 9000```
