### ISSUE TITLE
"TRUNCATE TABLE" does nothing for tables with Distributed engine

### ISSUE THREAD

**Issue by faucct** [yandex/ClickHouse#2963]

**Comment by faucct** [comment]
> You can use TRUNCATE TABLE local_table_name ON CLUSTER cluster_name;

Yes, I have figured this out.

> BTW, TRUNCATE a distributed table only removes temporary files

Don't you think this seems a little counterintuitive?

**Comment by faucct** [comment]
Also I have noticed that there is a little between inserting in a distributed table and the results appearing in it for selection. Is there a way to have no delay for testing purposes?

**Comment by zhang2014** [comment]
You're right, but the current implementation is more consistent with ClickHouse's other DDL. Like `DROP` : )

**Comment by zhang2014** [comment]
> Also I have noticed that there is a little delay between inserting in a distributed table and the results appearing in it for selection. Is there a way to have no delay for testing purposes?

You can try the following two configurations:
- insert_distributed_sync
- insert_distributed_timeout

**Comment by faucct** [comment]
Regarding the configurations: `yandex > insert_distributed_sync` put in `/etc/clickhouse-server/conf.d/*.xml` file does not get reflected in `SELECT * FROM system.settings`. Am I doing everything right?
Regarding `TRUNCATE` behaviour: I don't see anyone wanting to use it for removing some temporary files, do you?

**Comment by alexey-milovidov** [comment]
DDL operations for Distributed tables are not propagated to the cluster by default and this is done intentionally.

First, we don't propagate DROP TABLE. This allows to drop Distributed table itself without affecting the cluster. And this also helps for isolation when your users only have access to an empty server with Distributed tables, that works as a view to a cluster.

Second, we don't propagate ALTER with partitions, for the same reason. So, it looks reasonable to not propagate TRUNCATE by default.

**Comment by faucct** [comment]
I guess I didn’t consider TRUNCATE a DDL command.
