### ISSUE TITLE
website: bad sitemaps

### ISSUE THREAD

**Issue by filimonov** [yandex/ClickHouse#2995]
I was wondering why google don't index http://clickhouse.yandex/ properly.
Most probably it's connected to the fact that site uses sitemap.xml files, which are completely out of order. 

[robots.txt](https://clickhouse.yandex/robots.txt) says that crawlers should respect [/docs/sitemap.xml](https://clickhouse.yandex/docs/sitemap.xml)

[/docs/sitemap.xml](https://clickhouse.yandex/docs/sitemap.xml) links to 4 subsitemaps
- [/docs/ru/single_page/sitemap.xml](https://clickhouse.yandex/docs/ru/single_page/sitemap.xml)  404 not found (and not needed, as multipage version should be indexed)
- [/docs/en/single_pabe/sitemap.xml](https://clickhouse.yandex/docs/en/single_pabe/sitemap.xml) 404 not found (and not needed, as multipage version should be indexed, in addition there is a typo in the url)
- [/docs/en/sitemap.xml](https://clickhouse.yandex/docs/en/sitemap.xml) and [/docs/ru/sitemap.xml](https://clickhouse.yandex/docs/ru/sitemap.xml) (mkdocs generated?) which has `None` everywhere instead all the links.
- probably it's better to have also sitemaps for top level site links (like index / tutorial / blog / benchmark). 

Righ now I have no time for that, if nobody will take that i can fix that at ~ the end of next week.

**Comment by filimonov** [comment]
#3052

**Comment by blinkov** [comment]
@filimonov looks way better now, thanks.

`sitemap_static.xml` has not been added to the list of what's published to website, but it'll get fixed in next release.
