### ISSUE TITLE
[Question] Safe way to filters including account id

### ISSUE THREAD

**Issue by fizerkhan** [yandex/ClickHouse#2996]
We would like to allows our users to filers the data. We want to apply `accountId` along with all filters(provided by the user) in the where condition. What is the safe to apply filters along with account Id?  

We want to avoid any sql injection and getting results for all `accountIds`.
We are think of writing subquery. We really doubt about performances.

Normal Query:

```
select accountId, appName, avg(duration) from performance_table where
accountId = '500' and  eventDateTime >= now() - 30 * 60 and env = "production"
group by appName order by appName limit 10
```

Using Sub Query:

```
select accountId, appName, avg(duration) from (select * from  performance_table where
accountId = '500' and  eventDateTime >= now() - 30 * 60) where env = "production"
group by appName order by appName limit 10
```

Could you please suggest the safe way of doing it?

**Comment by filimonov** [comment]
That is general question, not Clickhouse related (answer would be the same for any DB) - please use StackOverflow for finding answers for such a problems.

**Comment by blinkov** [comment]
@fizerkhan do you have any further questions?

**Comment by fizerkhan** [comment]
Thanks @filimonov @blinkov. I will post it in the stackoverflow.

**Comment by blinkov** [comment]
@fizerkhan when you will, leave here a link, please.

**Comment by fizerkhan** [comment]
Done https://stackoverflow.com/questions/52164354/safe-way-to-filters-including-account-id-or-user-id-in-sql-query
