### ISSUE TITLE
Memory management issues

### ISSUE THREAD

**Issue by mrdun** [yandex/ClickHouse#300]
Hi everyone,

After update to the latest stable release 1.1.54127 we have got an issues with ClickHouse.
The point is that ClickHouse server started to eat all available RAM until it will be full then OOM come and kill it.
The behavior  change could be clearly seen on Munin memory graph:
![screenshot from 2017-01-04 17-40-24](https://cloud.githubusercontent.com/assets/10163114/21673959/4512bd50-d334-11e6-8caf-62489f3a2380.png)

I tried to make lower values to _uncompressed_cache_size_ and _mark_cache_size_ parameters but this didn't help, below our current ClickHouse config:
[config.txt](https://github.com/yandex/ClickHouse/files/686799/config.txt)

Our server configuration:
RAM: 96G
OS: Centos 6.8
ClickHouse server running using Docker 1.12.2, inside Ubuntu 14.04.5 container.

What could be the reason of the issues? 
Please let me know if you will need any additional information.

**Comment by alexey-milovidov** [comment]
Please show graphs of following metrics:

ClickHouse.Metrics.MemoryTracking
ClickHouse.Metrics.MemoryTrackingInBackgroundProcessingPool
ClickHouse.Metrics.Merge

**Comment by mrdun** [comment]
If I understood you right these metrics available from system.metrics table:
```
│ Merge                                    │         0 
│ MemoryTracking                           │     21581646 
│ MemoryTrackingInBackgroundProcessingPool │ -23638864
```

**Comment by alexey-milovidov** [comment]
Do these values grow with growing of total memory usage?

Also, please provide result of
`SELECT * FROM system.merges` 
query at some time after server startup.

What kind of tables do you use?
If you also provide structure of corresponding tables, it will help.

**Comment by mrdun** [comment]
> Do these values grow with growing of total memory usage?
_MemoryTracking_ metric could be lower or higher,  _MemoryTrackingInBackgroundProcessingPool_ is growing (or lowering?), now it has value -253653632. BTW what **-** symbol mean for this value?

> Also, please provide result of
> SELECT * FROM system.merges
The result of the query most time is empty, after few tries I can get some non empty result: 
```
┌─database─┬─table──┬─────elapsed─┬───────────progress─┬─num_parts─┬─result_part_name──────────────────────┬─total_size_bytes_compressed─┬─total_size_marks─┬─bytes_read_uncompressed─┬─rows_read─┬─bytes_written_uncompressed─┬─rows_written─┬─columns_written─┐
│ prod     │ ctr_kr │ 0.035895109 │    0.7335205078125 │         2 │ 20170105_20170105_1613740_1616758_845 │                      759257 │               26 │                 2968446 │    156234 │                    2801664 │       147456 │               0 │
│ prod     │ ctr_nl │ 0.029025295 │ 0.3530203683035714 │         2 │ 20170105_20170105_1940820_1942040_182 │                     1004489 │               35 │                 1923142 │    101218 │                    1712128 │        90112 │               0 │
└──────────┴────────┴─────────────┴────────────────────┴───────────┴───────────────────────────────────────┴─────────────────────────────┴──────────────────┴─────────────────────────┴───────────┴────────────────────────────┴──────────────┴─────────────────┘
```
> What kind of tables do you use?
We are using _CollapsingMergeTree_ for most tables an _Merge_ for largest one.

>  If you also provide structure of corresponding tables, it will help.
Tables structure available by link:
[prod.sql.txt](https://github.com/yandex/ClickHouse/files/687151/prod.sql.txt)

**Comment by alexey-milovidov** [comment]
> BTW what - symbol mean for this value?

It means, that memory was freed in context of background job (like eviction of old data from cache), but was allocated in other context. Usually, this is fine.
I had hypothesis, that memory usage is due to merges, but your data shows that this is not true.

**Comment by alexey-milovidov** [comment]
I still cannot guess, why this issue happens.
Try to isolate possible dependencies. For example, try to enable/disable some types of queries.
Maybe, you could temporary disable queries from Merge table and leave other queries, and see what happens.

**Comment by mrdun** [comment]
Unfortunately we can't disable queries to Merge table since the bug happened on our prod environment.
Instead we had tried temporary switch off  all write activity to ClickHouse and got the similar picture for RAM usage:
![screenshot from 2017-01-11 18-17-21](https://cloud.githubusercontent.com/assets/10163114/21856537/0d9743fe-d82b-11e6-85b9-2594d9895fea.png)

To keep environment stable we have switched back to previous ClickHouse version.
As you can see on screenshot everything was fine until we have started again version 54112.

**Comment by alexey-milovidov** [comment]
Please try to update to 54135.

**Comment by mrdun** [comment]
After the week of testing I can confirm that issue has gone.
What was the reason, could you make a comment?
Thanks.

**Comment by alexey-milovidov** [comment]
The reason was incorrect implementation of move-assignment in Field.
The issue was presented only in cases when column of String or Array type was used in primary key.

**Comment by zhangxin0112** [comment]
1.Create tablea(memory).  
2.Create tableb(mergetree).  Primary key is column with type Int.
3. Load csv into the memory.
4.Check clickhouse-server cached 4G memory. 
5.Exe SQL: Insert into tableb select * from tablea;
6.Exe SQL: Drop table tablea;
7.Check clickhouse-server still cache 4G+ memory. 
Why?
