### ISSUE TITLE
Regex or Wildcard with Dictionaries

### ISSUE THREAD

**Issue by Slind14** [yandex/ClickHouse#3001]
Hi there,
is there any way to make use of regex or at least some wildcard with dictionary matching?

**Comment by filimonov** [comment]
There is no such a way currently.

There is similar issue about user agent: https://github.com/yandex/ClickHouse/issues/157#issuecomment-258265684 

If you don't need high performance from that dictionary you can create http / or executable wrapper which will get list of key from CH, do matches / regexp agains external DB and return what matched.

**Comment by filimonov** [comment]
It will work quite good if most of the used keys (>99.9%) will fit into memory. Otherwise performance will not be good.
