### ISSUE TITLE
Array(LowCardinality(String)) and has() function throws error

### ISSUE THREAD

**Issue by reflection** [yandex/ClickHouse#3004]
`Received exception from server (version 18.11.0):
Code: 43. DB::Exception: Received from ch-0:9000, 10.64.10.226. DB::Exception: Types of array and 2nd argument of function has must be identical up to nullability or numeric types or Enum and numeric type. Passed: Array(LowCardinality(String)) and String.. `

Test sql statements follow.  I also tried changing the type of the String constant 'c' below, `toLowCardinality('c')` and `CAST('c' as LowCardinality(String))`, but still same error.

```
CREATE TABLE lc_test (
  ts     DateTime,
  cat    Array(LowCardinality(String)),
  domain String
) ENGINE=MergeTree
  PARTITION BY toYYYYMMDD(ts)
  ORDER BY (ts, cityHash64(domain))
  SAMPLE BY cityHash64(domain);

INSERT INTO lc_test VALUES (1535676900, ['a', 'b', 'c'], 'google.com');
INSERT INTO lc_test VALUES (1535676901, ['c', 'd', 'a'], 'yandex.ru');
INSERT INTO lc_test VALUES (1535676902, ['b',], 'bing.com');

SELECT domain, COUNT(ts) as requests 
FROM lc_test
WHERE has(cat, 'c')
GROUP BY domain
ORDER BY requests DESC;
```

**Comment by reflection** [comment]
Any movement on this issue?  Also, probably related, simple `WHERE <low cardinality string column> IN (<list of strings>)` doesn't work either.
```
SET allow_experimental_low_cardinality_type = 1;

CREATE TABLE lc_test2 (
  ts DateTime,
  hero LowCardinality(String)
) ENGINE = MergeTree
  PARTITION BY toYYYYMMDD(ts)
  ORDER BY ts;

INSERT INTO lc_test2 VALUES (1535676900, 'superman');

SELECT ts, hero
FROM lc_test2
WHERE hero IN ('superman', 'batman');

Received exception from server (version 18.12.6):
Code: 53. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Types of column 1 in section IN don't match: LowCardinality(String) on the right, String on the left..
```

**Comment by alexey-milovidov** [comment]
LowCardinality data type is in active development right now.
Both of the mentioned issues are in todo.
