### ISSUE TITLE
max_result_rows is ignored by clickhouse

### ISSUE THREAD

**Issue by 2DKot** [yandex/ClickHouse#3007]
Query:
```
clickhouse-client --password 1234 --max_result_rows=5 --query="select * from system.numbers limit 10"
```
Result:
```
0
1
2
3
4
5
6
7
8
9
```
Expected result: exception or
```
0
1
2
3
4
```
ClickHouse server version 18.10.3 revision 54405

Does I misunderstand this setting? How can I limit result rows for all queries in clickhouse configuration?

**Comment by alexey-milovidov** [comment]
Data in ClickHouse is processed by blocks and limits are checked after each block is processed.

For example, max_result_rows will stop query processing if the size of result appears to be larger than the limit after processing a block.

The size of block may be arbitary and depend on query, table engine, etc. In this example, the block size is selected to be 10.

**Comment by alexey-milovidov** [comment]
Updated docs (ru) cfb448cce6656a81d8c30bd009fee9737a5b4cf7.
