### ISSUE TITLE
[Question]: Detail information about metrics from system tables?

### ISSUE THREAD

**Issue by vkolomiets** [yandex/ClickHouse#3010]
Hello,
Clickhouse has tables with system information. Is there any detailed information about the metrics of these tables? I'm especially interested in the system.metrics table. I tried to find detailed information in the official documentation, but I find only a description of the tables.

Could you give any information about these metrics?

**Comment by alexey-milovidov** [comment]
There is no detailed information.

**Comment by alexey-milovidov** [comment]
I've added the info.
https://github.com/yandex/ClickHouse/pull/3016
