### ISSUE TITLE
Segmentation fault on macOS

### ISSUE THREAD

**Issue by nvartolomei** [yandex/ClickHouse#3015]
ClickHouse fails with segmentation error on macOS after https://github.com/yandex/ClickHouse/pull/2482.

https://github.com/yandex/ClickHouse/blob/6ccd74aeeb3226028f4af50653b6922152a7d702/dbms/src/Common/ThreadStatus.cpp#L26 This initialization is not effective for some reason (`ThreadStatus::create()` doesn't seem to be called).

Compiling with GCC 8.2.0

**Comment by alexey-milovidov** [comment]
This may happen due to a usage of thread_local variable in different translation units.
Does the issue reproduce if we merge ThreadStatus.cpp, ThreadStatusExt.cpp, CurrentThread.cpp to a single translation unit?

Also we need to check that non-trivial initialization of thread_local is not broken at all on this platform.

**Comment by alexey-milovidov** [comment]
I will just remove these lines from our Poco fork.

**Comment by nvartolomei** [comment]
A minimal example with thread_local failing under gcc 8.2 on macOS, however works with llvm.

`main.cpp`
```c++
#include "lib.h"

int main() {
    getProfileEvents();
    return 0;
}
```

`lib.h`
```c++
#pragma once

#include <memory>
#include <iostream>

class ThreadStatus {
public:
    int x = 0;

    ThreadStatus();

    static void doX() { std::cout << "test"; }
};

extern thread_local ThreadStatus * thread_local_var;

static int getProfileEvents() {
    return thread_local_var->x;
}
```

`lib.c++`
```c++
#include "lib.h"

thread_local ThreadStatus * thread_local_var = new ThreadStatus();

ThreadStatus::ThreadStatus() { doX(); }
```

`g++-8  -std=c++17 -c -I . main.cpp && g++-8  -std=c++17 -c -I . lib.cpp && g++-8 -o main main.o lib.o && ./main`

```
Segmentation fault: 11
```

`g++  -std=c++17 -c -I . main.cpp && g++  -std=c++17 -c -I . lib.cpp && g++ -o main main.o lib.o && ./main`

```
test
```

```
$ g++-8 --version
g++-8 (Homebrew GCC 8.2.0) 8.2.0

$ g++ --version
Apple LLVM version 9.1.0 (clang-902.0.39.1)
````

However, if definition of `ThreadStatus::doX` is moved to `lib.cpp` instead of `lib.h` it executes correctly.
