### ISSUE TITLE
Too large array size while reading from ZooKeeper (Marshalling error)

### ISSUE THREAD

**Issue by mxsavchenko** [yandex/ClickHouse#3023]
Hi,

Clickhouse version 18.10.3.
Zookepeer version 3.4.8-1.
Configured replication of 2 tables (graphite and graphite_tree) on two servers and on the same servers installed and configured Zookepeer cluster.

Today the base has ceased to work. When i try to start clickhouse, in log errors:
`2018.09.02 17:53:57.458979 [ 3 ] <Error> Application: ZooKeeperImpl::Exception: Marshalling error, path: /clickhouse/tables/replicator/graphite/log
2018.09.02 17:54:28.503005 [ 2 ] <Error> void ZooKeeperImpl::ZooKeeper::receiveEvent(): Code: 999, e.displayText() = ZooKeeperImpl::Exception: Too large array size while reading from ZooKeeper (Marshalling error), e.what() = ZooKeeperImpl::Exception, Stack trace:

0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x56d06c6]
1. /usr/bin/clickhouse-server(ZooKeeperImpl::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0xce) [0x54579ee]
2. /usr/bin/clickhouse-server(ZooKeeperImpl::ZooKeeper::ListResponse::readImpl(DB::ReadBuffer&)+0x156) [0x5458cd6]
3. /usr/bin/clickhouse-server(ZooKeeperImpl::ZooKeeper::receiveEvent()+0x543) [0x545ea83]
4. /usr/bin/clickhouse-server(ZooKeeperImpl::ZooKeeper::receiveThread()+0x2b2) [0x545f232]
5. /usr/bin/clickhouse-server() [0x930310f]
6. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f6e6e8df6ba]
7. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f6e6e10841d]`

I tried purge Zookepeer data directory in two servers and restart zookepeer/clickhouse  - still does not work. Also tried disable one server and change settings to work database to one server - does not work, in the logs the same errors

**Comment by VadimPE** [comment]
Hi

It stores metadata about inserted chunks.
znodes inside log are cleaned after all replicas have processed these log entries.
If you have replicas that are abandoned forever, log will not be cleaned up. You have to remove abandoned replicas inside replicas znode.
Now you can delete some old entries inside log manually.
It is the case when one replica is abandoned, but its node in ZooKeeper was not deleted. ClickHouse think that there is a possibility for replica to become alive and keeps old logs for this case.

This is fixed and will be available in new versions of CH.

**Comment by VadimPE** [comment]
#2758
