### ISSUE TITLE
[Question] Backup Clickhouse data

### ISSUE THREAD

**Issue by igor-sh8** [yandex/ClickHouse#3027]
Hello.
As I understand the best practice for backup clickhouse data without stopping the clickhouse server for now is ALTER TABLE ... FREEZE PARTITION.
Is it possible to freeze not only partition or a few partitions but a whole table or even a whole database ?
And one more question, is it possible to disable the incremental creation of folders in the shadow (/var/lib/clickhouse/shadow) folder ?
Thanks in advance.

**Comment by fizerkhan** [comment]
+1

**Comment by VadimPE** [comment]
igor-sh8
Hi!
https://clickhouse.yandex/docs/en/query_language/alter/#backups-and-replication

You can copy data from the `/var/lib/clickhouse/data/database/table`, but it isn't a good way.

**Comment by VadimPE** [comment]
@igor-sh8
1) If you do not stop CH, you will not be sure about the end of operations in CH. So it is bad solution.
2) Unfortunately, not

**Comment by igor-sh8** [comment]
Ok. 
I understand. 
Thanks.
