### ISSUE TITLE
ClickHouse exception:Unknown function timezone

### ISSUE THREAD

**Issue by dsfishchen** [yandex/ClickHouse#3040]
When connect to clickhouse-server by jdbc, there is an exception:
Unexpected driver error occurred while connecting to database
  ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 46, host: 192.168.1.24, port: 8123; Code: 46, e.displayText() = DB::Exception: Unknown function timezone, e.what() = DB::Exception
    ClickHouse exception, code: 46, host: 192.168.1.24, port: 8123; Code: 46, e.displayText() = DB::Exception: Unknown function timezone, e.what() = DB::Exception
      Code: 46, e.displayText() = DB::Exception: Unknown function timezone, e.what() = DB::Exception
      Code: 46, e.displayText() = DB::Exception: Unknown function timezone, e.what() = DB::Exception

Other message: I can connect the clickhouse-server by clickhouse-client on another computer:
ClickHouse client version 1.1.54180.
Connecting to 192.168.1.24:9000 as user default.
Connected to ClickHouse server version 1.1.54023.
Warning: could not determine server time zone. Proceeding with local time zone.

**Comment by blinkov** [comment]
@dsfishchen  Which ClickHouse version do you use?

**Comment by dsfishchen** [comment]
ClickHouse server version 1.1.54023.

**Comment by dsfishchen** [comment]
I contrast this clickhouse to another normal clickhouse,the following functions was not found.
how can i repair it.

│ UUIDNumToString                │            0 │
│ UUIDStringToNum                │            0 │
│ arrayReverseSort               │            0 │
│ arraySort                      │            0 │
│ assumeNotNull                  │            0 │
│ caseWithExpr                   │            0 │
│ caseWithoutExpr                │            0 │
│ coalesce                       │            0 │
│ decodeURLComponent             │            0 │
│ hasColumnInTable               │            0 │
│ ifNull                         │            0 │
│ isNotNull                      │            0 │
│ isNull                         │            0 │
│ nullIf                         │            0 │
│ pointInEllipses                │            0 │
│ timezone                       │            0 │
│ toStartOfDay                   │            0 │

**Comment by blinkov** [comment]
You just need to consider updating ClickHouse server. The version you named is pretty old, not even from this year.

Or at least use older jdbc driver release, it won't rely on relatively recent features.

**Comment by dsfishchen** [comment]
I use a older jdbc driver release,it works!!
Thank you very much!!

<dependency>
            <groupId>ru.yandex.clickhouse</groupId>
            <artifactId>clickhouse-jdbc</artifactId>
            <version>0.1.13</version>
        </dependency>

**Comment by serebrserg** [comment]
Actually you can use recent versions of clickhouse-jdbc as well with additional settings 
either through ClickHouseProperties
```java
properties.setUseServerTimeZone(false);
```
or through Properties
```java
properties.setProperty("use_server_time_zone", "false")
```
and passing it to 
ru.yandex.clickhouse.ClickHouseDriver#connect(java.lang.String, ru.yandex.clickhouse.settings.ClickHouseProperties) or 
ru.yandex.clickhouse.ClickHouseDriver#connect(java.lang.String, java.util.Properties) respectively.

There are couple of other settings regarding timezones defined there
https://github.com/yandex/clickhouse-jdbc/blob/master/src/main/java/ru/yandex/clickhouse/settings/ClickHouseConnectionSettings.java

**Comment by dsfishchen** [comment]
Ok，thank you.
becouse of need to connect to clickhouse by DBeaver, so i choose an older jdbc driver.
