### ISSUE TITLE
Not Fount "Ready for connections", Why?

### ISSUE THREAD

**Issue by ymlair** [yandex/ClickHouse#305]
2017.01.08 00:05:51.158568 [ 1 ] <Debug> Application: rlimit on number of file descriptors is 262144
2017.01.08 00:05:51.158577 [ 1 ] <Debug> Application: Initializing DateLUT.
2017.01.08 00:05:51.158581 [ 1 ] <Trace> Application: Initialized DateLUT.
2017.01.08 00:05:51.161431 [ 1 ] <Debug> Application: Configuration parameter 'interserver_http_host' doesn't exist or exists and empty. Will use 'localhost.localdomain' as replica host.
2017.01.08 00:05:51.161498 [ 1 ] <Debug> ConfigReloader: Loading config '/etc/clickhouse-server/config.xml'
2017.01.08 00:05:51.165752 [ 1 ] <Debug> ConfigReloader: Loading config '/etc/clickhouse-server/users.xml'
2017.01.08 00:05:51.170103 [ 1 ] <Information> Application: Loading metadata.
2017.01.08 00:05:51.170263 [ 1 ] <Information> DatabaseOrdinary (default): Total 0 tables.
2017.01.08 00:05:51.170342 [ 1 ] <Information> DatabaseOrdinary (sosa): Total 2 tables.

No "Ready for connections"

**Comment by alexey-milovidov** [comment]
What happens, if you run clickhouse-server from console:
```
sudo service clickhouse-server stop
sudo -u metrika /usr/bin/clickhouse-server --config /etc/clickhouse-server/config.xml
```

What tables are located in `sosa` database? (I am interested in their ENGINE).

**Comment by ymlair** [comment]
@alexey-milovidov  Command dont work，and database engine is mergeTree;  maybe it is VPS problem, i reinstall the OS, now it is ok;
i will provide more information if get the problem again,
Thanks.
