### ISSUE TITLE
[Question] Add column to SummingMergeTree table

### ISSUE THREAD

**Issue by igor-sh8** [yandex/ClickHouse#3054]
Hello. 
As I know I can add a column to an existing SummingMergeTree table using Alter table statement.
But is it possible to add this new column to the primary key or to the aggregated columns ?
For example I have a table:
`CREATE TABLE Test ( Date Date,  Test1 Int32, Test2 Int32, Test3 Int32) ENGINE = SummingMergeTree(Date, (Date,  Test1), 8192, (Test2, Test3))`
I added column:
`ALTER TABLE Test  ADD COLUMN Test4 Int32 After Test2`
And I got (show create table statement):
`CREATE TABLE Test ( Date Date,  Test1 Int32, Test2 Int32, Test4 Int32, Test3 Int32) ENGINE = SummingMergeTree(Date, (Date,  Test1), 8192, (Test2, Test3))`
So can i get something like:
`CREATE TABLE Test ( Date Date,  Test1 Int32, Test2 Int32, Test4 Int32, Test3 Int32) ENGINE = SummingMergeTree(Date, (Date,  Test1, Test4), 8192, (Test2, Test3))`
or
`CREATE TABLE Test ( Date Date,  Test1 Int32, Test2 Int32, Test4 Int32, Test3 Int32) ENGINE = SummingMergeTree(Date, (Date,  Test1), 8192, (Test2, Test3,Test4))`
?

Thanks in advance

**Comment by alexey-milovidov** [comment]
Extending the primary key is not officially supported.

There is an undocumented feature to add a column to primary key of non-replicated table.
https://github.com/yandex/ClickHouse/issues/2210#issuecomment-380482697
This feature exist as a hack.

**Comment by alexey-milovidov** [comment]
#147
#2210

**Comment by alexey-milovidov** [comment]
Good news are that recently we have added this feature to our plans.

**Comment by igor-sh8** [comment]
Hi, @alexey-milovidov. 
Thanks for the info. 

Maybe you could also suggest something about adding a column to the aggregated columns like:
`CREATE TABLE Test ( Date Date, Test1 Int32, Test2 Int32, Test4 Int32, Test3 Int32) ENGINE = SummingMergeTree(Date, (Date, Test1), 8192, (Test2, Test3,Test4))`  
Is it possible ?

**Comment by ztlpn** [comment]
You will have to add new aggregated columns by hand:
* Execute `ALTER ADD COLUMN`
* Do `DETACH TABLE Test`
* Find the metadata file (usually its path is `/var/lib/clickhouse/metadata/<database>/<table>.sql`) and add the new column to the list of the aggregated columns.
* Do `ATTACH TABLE Test`

**Comment by igor-sh8** [comment]
Hi, Alex. 
This is great news. Thanks.
