### ISSUE TITLE
DB::Exception: Conversion from String to UUID is not supported

### ISSUE THREAD

**Issue by sjoerdmulder** [yandex/ClickHouse#3061]
Clickhouse version 18.10.3 revision 54405.

I'm trying to convert one of my columns that contains UUID's (36 chars) to the new `UUID` type using
```
ALTER TABLE events MODIFY COLUMN visitor_id UUID
```
on a ReplicatedMergeTree. But the query doesn't seem to work.

The actual ALTER TABLE calls times out with:
`Alter is not finished because timeout when waiting for some replicas: 01 (replication_alter_columns_timeout = 60). Alter will be done asynchronously..`

But the logs reveal:
```
void DB::ReplicatedMergeTreeAlterThread::run(): Code: 70, e.displayText() = DB::Exception: Conversion from String to UUID is not supported
0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x56d06c6]
1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x22) [0x2da2d92]
2. /usr/bin/clickhouse-server(DB::FunctionCast::prepareImpl(std::shared_ptr<DB::IDataType const> const&, std::shared_ptr<DB::IDataType const> const&, bool) const+0x5b8) [0x33cd728]
3. /usr/bin/clickhouse-server(DB::FunctionCast::prepare(std::shared_ptr<DB::IDataType const> const&, std::shared_ptr<DB::IDataType const> const&) const+0x102) [0x33cd992]
4. /usr/bin/clickhouse-server(DB::FunctionCast::prepare(DB::Block const&) const+0x36) [0x33cdc36]
5. /usr/bin/clickhouse-server(DB::IFunctionBase::execute(DB::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long)+0x3c) [0x2fd75fc]
6. /usr/bin/clickhouse-server(DB::ExpressionAction::execute(DB::Block&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >&) const+0x4b6) [0x52e84a6]
7. /usr/bin/clickhouse-server(DB::ExpressionActions::execute(DB::Block&) const+0xe6) [0x52e98b6]
8. /usr/bin/clickhouse-server(DB::ExpressionBlockInputStream::getHeader() const+0x1b4) [0x51de184]
9. /usr/bin/clickhouse-server(DB::MergeTreeData::alterDataPart(std::shared_ptr<DB::MergeTreeDataPart const> const&, DB::NamesAndTypesList const&, std::shared_ptr<DB::IAST> const&, bool)+0x114f) [0x505e87f]
10. /usr/bin/clickhouse-server(DB::ReplicatedMergeTreeAlterThread::run()+0xa9c) [0x50cd04c]
11. /usr/bin/clickhouse-server(DB::BackgroundSchedulePool::TaskInfo::execute()+0xef) [0x56b117f]
12. /usr/bin/clickhouse-server(DB::BackgroundSchedulePool::threadFunction()+0xc2) [0x56b1f52]
13. /usr/bin/clickhouse-server() [0x930310f]
14. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7efcc7d286db]
15. /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7efcc74af88f]
```

**Comment by 4ertus2** [comment]
Reproduced with MergeTree on master

`USE test;
CREATE TABLE IF NOT EXISTS uuid
(
    created_at DateTime,
    id0 String,
    id1 FixedString(36)
)
ENGINE = MergeTree
PARTITION BY toDate(created_at)
ORDER BY (created_at);

INSERT INTO uuid VALUES ('2018-01-01 01:02:03', '00000000-0000-03f8-9cb8-cb1b82fb3900', '00000000-0000-03f8-9cb8-cb1b82fb3900');

ALTER TABLE uuid MODIFY COLUMN id0 UUID;
ALTER TABLE uuid MODIFY COLUMN id1 UUID;

SELECT * FROM uuid;

DROP TABLE uuid;
`

> Code: 70. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Conversion from String to UUID is not supported.
> Code: 70. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Conversion from FixedString(36) to UUID is not supported.

**Comment by sjoerdmulder** [comment]
Great :-) but one suggestion for the test is that the FixedString should be
16 chars (128bit) since it can store the binary representation.

Op vr 7 sep. 2018 17:02 schreef Artem Zuikov <notifications@github.com>:

**Comment by 4ertus2** [comment]
Nope. If you use FixedString representation than it would be stored as is.
It should use 128 bit only after conversion to UUID.

**Comment by sjoerdmulder** [comment]
Yes I understand, its more in the scenario when using
the UUIDStringToNum(str) and UUIDNumToString(str) with FixedString(16) to
mimic the new UUID type.

Op vr 7 sep. 2018 18:33 schreef Artem Zuikov <notifications@github.com>:

**Comment by 4ertus2** [comment]
#3074

P.S. It based on changes from #3071

**Comment by 4ertus2** [comment]
fixed in master
