### ISSUE TITLE
Потребление памяти ClickHouse

### ISSUE THREAD

**Issue by zuart** [yandex/ClickHouse#3075]
Приветствую.

Волей судеб пришлось на некоторое время перенести базу на маломощный сервер с 8Га памяти, на котором крутится еще несколько некритичных сервисов. Начались проблемы с памятью, отсюда вопрос. Можно ли как-то ограничить потребление памяти ClickHouse, скажем, до 5Га?

Спасибо.

**Comment by alexey-milovidov** [comment]
Имеет смысл выставить более сильные ограничения на потребление памяти запросами:

max_memory_usage - например, в 1 GB
max_memory_usage_for_user - например, в 4 GB
max_memory_usage_for_all_queries - например, в 4 GB

https://clickhouse.yandex/docs/ru/operations/settings/query_complexity/#max_memory_usage

Ограничить количество одновременных запросов:

max_concurrent_queries_for_user - в 4.

Эти настройки задаются в файле users.xml

Также имеет смысл уменьшить размеры кэшей.

mark_cache_size - до 1 GB

Эта настройка указывается в config.xml.
