### ISSUE TITLE
Question: exporting raw column data into separate files, sorted by all columns

### ISSUE THREAD

**Issue by heyciao** [yandex/ClickHouse#3082]
Hi
First of all, compliments for your software (I tested it the first time in 2017 but at that time the lack of custom partitioning was a problem and insert-performance wasn't good; now with custom partitioning and the availability of the "Buffer"-engine it's incredibly fast - and thanks as well a lot for making it available directly in the main portage tree of Gentoo :) ).

**Situation**
(version being used: 18.10.3)
I have a base/source table like this one (simplified example)...
```
create table testtbl (col01 UInt8, col02 UInt8, col03 String, col04 UInt64,...) engine=MergeTree partition by(col01) order by (col02,col03,col04,...) settings index_granularity=65536
```
...and I keep on inserting data into it => works perfectly.

**What I need**
I need an extract of all raw/original data that belongs to a specific partition, one file per column, where each column has its contents perfectly sorted by all columns.

**What I'm currently doing**
I'm running scripts like these ones:
```
create table export_mypart123_col02 engine=File(RowBinary) as select col02 from testtbl where col01 = 123 order by col02,col03,col04;
create table export_mypart123_col03 engine=File(RowBinary) as select col03 from testtbl where col01 = 123 order by col02,col03,col04;
create table export_mypart123_col04 engine=File(RowBinary) as select col04 from testtbl where col01 = 123 order by col02,col03,col04;
...
```

**Problem**
Exporting a single column takes in my case ~35 minutes for a table that contains ~5 billion records.
FYI I had to activate the option "max_bytes_before_external_sort" (currently set to 5GBs, which is enough for ~2.5% of the data) as the whole table does not fit in my server's RAM (32GBs).

I see that retrieving the data from the DB is superfast but when Clickhouse starts writing the temporary files needed for the "sort" and then later the final output file into the "RowBinary"-table it's veeery slow (nothing much going on there; I see 1 CPU-thread being fully used and ~20MB/s being written to the temporary sort files and later to the final file).

**Question**
Is there a more intelligent way to do this kind of export?

Currently, I'm just splitting all "create table"-statements (1 per column) into groups (e.g. 3 groups of 5 "create table"-statements each), start up 3 clickhouse-clients in parallel and make each client run sequentially all 5 queries of their own group => in this example, running 5 such statements would need ~3 hours.

For example MariaDB has the vector-table type (https://mariadb.com/kb/en/library/connect-vec-table-type/) which writes the contents of each of its columns into single files (some fields, e.g. "varbinary" which more or less matches "String" in Clickhouse is a problem but I was handling it in a different way) => is it possible in Clickhouse for example to make a "File(RowBinary)"-table write the contents of its columns into separate files?
Or is there any other altenative so that I don't have to keep re-running the "order by" (e.g. some sort of table that would have its contents ordered perfectly by rows inserted into it, from which I could therefore just "select" when creating the single columns)?

**Reason**
I'm doing some experiments with indexing of data; I want to check how the amount of data and/or the order or the columns impact the singlecolumn&total compression ratio of the data.
From time to time I therefore export the raw contents of the columns, compress it and then compare the file sizes to the previous result.

Thanks a lot :)
Stefano

**Comment by filimonov** [comment]
>I'm doing some experiments with indexing of data; I want to check how the amount of data and/or the order or the columns impact the singlecolumn&total compression ratio of the data.

1) are you aware about existence of `system.parts` , `system.columns`, `system.parts_columns`? They have different metadata, including real sizes of columns/parts and their compressed sizes. So if you need that data for analyzing how Clickhouse stores the data you don't need to export it outside :)
2) Clickhouse already stores columns in filesystem in 'one file per column' format (spit to partitions / parts) sorted by PK. 
3) if you will create another copy of your table with another PK and copy data there you will see how compression ratio changes.

**Comment by heyciao** [comment]
Thank you, no I wasn't aware of "system.parts_columns", great! I will use the sum of the bytes directly from that table when I test changes to the order of columns or other stuff :) .

On the other hand, if I compare "sum(column_data_compressed_bytes)" of a specific column and partition against the compressed size of the file I generated as explained above with "File(RowBinary)" and then compressed manually, the size is more or less similar for small partitions (e.g. for a part that contains 186'150'292 rows I get from the DB ~390MBs and ~380MBs from the external file), but for bigger partitions there is a big difference (e.g. for a part containing 5'170'344'578 rows I get from the system-table a sum of ~5033MBs but the manually exported and compressed file is only 3820MBs big) => can it be that the compressed data in Clickhouse needs more storage because it is compressed in smaller "chunks" (and is therefore less efficient) than when fully exported into a single file and compressed all together?

Fyi I have this in "config.xml"...
```
<compression incl="clickhouse_compression">
      <case>
         <method>zstd</method>
      </case>
</compression>
```
...and when compressing manually the exported file I used zstd compression level 3 ("zstd -3 <sourcefile> -o <trgtfile>").

Thank you

**Comment by alexey-milovidov** [comment]
ClickHouse use zstd compression level 1 by default. You can change it by adding
`<level>3</level>` in `<case>` near `<method>`.

And yes, ClickHouse use smaller compressed blocks by default (from 64 KB to 1 MB, depending on your data and index granularity).

This is controlled by 
`min_compress_block_size`
and
`max_compress_block_size`
per user settings, that can be tuned in users.xml in default profile.

**Comment by heyciao** [comment]
Great, very useful to know, thanks a lot!
