### ISSUE TITLE
Inserting now() in Date column results in incorrect value.

### ISSUE THREAD

**Issue by sarg** [yandex/ClickHouse#3088]
When I insert `now()` into Date column somewhat strange conversion/truncation occurs.

Here is a test scenario.
```
c5edc8389dfc :) create table tst_date (ts Date, val UInt16) ENGINE=MergeTree(ts, (val), 8192);

CREATE TABLE tst_date
(
    ts Date,
    val UInt16
)
ENGINE = MergeTree(ts, val, 8192)

Ok.

0 rows in set. Elapsed: 0.013 sec.

c5edc8389dfc :) insert into tst_date values (now(), 1);

INSERT INTO tst_date VALUES

Ok.

1 rows in set. Elapsed: 0.006 sec.

c5edc8389dfc :) select * from tst_date;

SELECT *
FROM tst_date

┌─────────ts─┬─val─┐
│ 2005-04-02 │   1 │
└────────────┴─────┘

1 rows in set. Elapsed: 0.003 sec.

c5edc8389dfc :) select now();

SELECT now()

┌───────────────now()─┐
│ 2018-09-10 08:59:07 │
└─────────────────────┘

1 rows in set. Elapsed: 0.003 sec.
```

**Comment by Chenjp** [comment]
select now() as nowts,* from tst_date 

| nowts | ts | val | 3 |
 | 2018-09-10 18:52:26 | 2023-09-08 | 1 |  |

**Comment by Chenjp** [comment]
We need cast now() to Date or DateTime!!!
CREATE TABLE tst_datetime
(
    ts Date,
    ts2 DateTime,
    val UInt16
)
ENGINE = MergeTree(ts, val, 8192);

insert into tst_datetime values (cast(now() as Date),cast(now() as DateTime), 1) ;

select * from tst_datetime;

 | ts | ts2 | val | 3 |
 | 2018-09-10 | 2018-09-10 19:05:14 | 1 |  |
 |  |  |  |  |

**Comment by sarg** [comment]
@Chenjp, in fact there is `today()` function which is the same as `toDate(now())` according to official docs.
But the point that the way clickhouse handles this situation violates principle of least astonishment. Pg and mysql correctly truncates the datetime to fit into date column.

**Comment by Chenjp** [comment]
@sarg According to official doc, `DateTime` stored in 4-bytes indicates unix-timestamp while `Date` in 2-bytes indicates days from 1970-01-01. Maybe implicit convertion between `Date` and `DateTime` is a new feature / engine enhancement request.
Currently maxinum supported `Date` is 2105, extended date range support is appreciated.

**Comment by alexey-milovidov** [comment]
#3226
#3229
