### ISSUE TITLE
Question: Default Data Compression Ratio?

### ISSUE THREAD

**Issue by AlexanderJLiu** [yandex/ClickHouse#3100]
Does the **`Default Data Compression Ratio`** range between 30%-100%? In config.xml, compression block has comments as fllow: 
> Uncomment if you want data to be compressed 30-100% better

I just want to know the ratio, and easy for me to compute the real data size (PB). Thanks! 👍

**Comment by filimonov** [comment]
Compression ratio depends on the nature of the data.

If you have almost random column (for example we have one column with md5) compression ratio is very bad for it (like 99.9%).
If you have 'mostly constant' column compression ratio for it would be really good - close 0%.
For 'regular' data it's usually it's about 30-45% from my experience. 

Try it on your data. It's enough to import few hundreds of megabytes to have a real feeling of compression ratio for your data.

**Comment by ztlpn** [comment]
The comment in config.xml refers to the zstd compression algorithm which achieves better compression ratios than the default lz4 algorithm, but is also more CPU-intensive. You can experiment with it and see if you are ok with the increased CPU load.

**Comment by AlexanderJLiu** [comment]
Thanks all of you, I've got it. 💯
