### ISSUE TITLE
system.parts is not filterable by partitions.

### ISSUE THREAD

**Issue by crakjie** [yandex/ClickHouse#3109]
the following query return all database partitions.
```
SELECT
	partition,
	database,
	table
FROM
	system.parts
group by partition, database, table
```

but the following is returning nothing, while the first request is returning this partition.
but filtering on table name is working.

```  
SELECT
	partition,
	database,
	table
FROM
	system.parts
WHERE  
     partition = 'b710e103-3d07-481e-afc0-1687a8782b73'
group by partition, database, table
```

**Comment by alexey-milovidov** [comment]
@ztlpn Clarification is needed.

**Comment by ztlpn** [comment]
We need to get rid of unnecessary quoting.

**Comment by ztlpn** [comment]
quoting removed in v18.16.0
