### ISSUE TITLE
clickhouse query on distributed table using aggreate function result not correct using merge function

### ISSUE THREAD

**Issue by zhaoplayboy** [yandex/ClickHouse#3110]
clickhouse clusters setting as following:
![image](https://user-images.githubusercontent.com/34508173/45410138-9c1ef880-b6a3-11e8-88d9-ec8975225d14.png)

Bug reappearance steps:
1. create database and tables
```
create database test：
use test;
CREATE TABLE local_table_1 ( datatime UInt32, datadate Date, number1 UInt32) ENGINE = MergeTree(datadate, datatime, 8192);
CREATE TABLE local_table_2 ( datatime UInt32, datadate Date, number1 UInt32) ENGINE = MergeTree(datadate, datatime, 8192);
CREATE TABLE distributed_table_1 AS local_table_1 ENGINE = Distributed('test_cluster', 'test', local_table_1, rand());
CREATE TABLE distributed_table_2 AS local_table_2 ENGINE = Distributed('test_cluster', 'test', local_table_2, rand());
```
2.Insert some test data:
insert into local_table_1 (datatime,datadate,number1) values (1533091943,'2018-08-01',100);
insert into local_table_2 (datatime,datadate,number1) values (1533091943,'2018-08-01',200); 

3.query with distributed table:
`SELECT sum(number1) FROM merge('test', 'distributed_table_2|distributed_table_1')`
result on the picture below,result is divided into two item.
![image](https://user-images.githubusercontent.com/34508173/45410548-9249c500-b6a4-11e8-91f0-9ca9171450c6.png)

query on the local table is ok!
` SELECT sum(number1) FROM merge('test', 'local_table_2|local_table_1')`
![image](https://user-images.githubusercontent.com/34508173/45410654-dd63d800-b6a4-11e8-9c8d-ee0c8c0481ad.png)

**Comment by ztlpn** [comment]
Which ClickHouse version do you use?

**Comment by alex-zaitsev** [comment]
I confirm the issue exist at latest 18.12.13, but with slightly different output:

```
 select sum(number1) from merge('test','distributed_table_2|distributed_table_1');

SELECT sum(number1)
FROM merge('test', 'distributed_table_2|distributed_table_1') 

┌─sum(number1)─┐
│          100 │
└──────────────┘
┌─sum(number1)─┐
│          200 │
└──────────────┘
```
