### ISSUE TITLE
Error with VIEW and enable_optimize_predicate_expression

### ISSUE THREAD

**Issue by TimonKK** [yandex/ClickHouse#3111]
If option `enable_optimize_predicate_expression = 1` and tables like this
```sql
DROP TABLE IF EXISTS test1
DROP TABLE IF EXISTS test2
CREATE TABLE test1 (_id String) ENGINE=Memory
CREATE TABLE test2 (_id String, userId String) ENGINE=Memory
CREATE VIEW IF NOT EXISTS test2_view AS SELECT * FROM test2
```
so query
```sql
SELECT * FROM test2_view AS t2 ALL INNER JOIN ( SELECT * FROM test1 AS t1 ) AS t3 ON (t3._id = t2.userId)
```
return error
`Unknown identifier: t2.userId`

If enable_optimize_predicate_expression = 0 - the query is ok

**Comment by zhang2014** [comment]
thank you, view predicate optimization has a logical error, and I'm fixing that : )

**Comment by zhang2014** [comment]
fixed in https://github.com/yandex/ClickHouse/pull/3107/commits/e6e376e86afd9121f48cd72ab84637347fe91e6b

**Comment by TimonKK** [comment]
Thank you too. Could you tell me, when I can get this fix in stable?
