### ISSUE TITLE
update doc for MySQL engine

### ISSUE THREAD

**Issue by paruru48** [yandex/ClickHouse#3113]
In [MySQL engine doc section](https://clickhouse.yandex/docs/en/operations/table_engines/mysql/),

> 'on_duplicate_clause' — Adds the ON DUPLICATE KEY UPDATE 'on_duplicate_clause' expression to the INSERT query. For example: impression = VALUES(impression) + impression

But `on_duplicate_clause` is prepended after `ON DUPLICATE KEY`, [link](https://github.com/yandex/ClickHouse/blob/28bc6db85755811de096315f8b8dd8940199b96b/dbms/src/Storages/StorageMySQL.cpp#L122) source code.

> if (!storage.on_duplicate_clause.empty())
>             sqlbuf << " ON DUPLICATE KEY " << storage.on_duplicate_clause;
> sqlbuf << ";";

**Comment by BayoNet** [comment]
I rewrote the description of 'on_duplicate_clause', it should become more clear.

https://clickhouse.yandex/docs/en/operations/table_engines/mysql/
