### ISSUE TITLE
JOIN unexpected results

### ISSUE THREAD

**Issue by den-crane** [yandex/ClickHouse#3145]
```
create table t(a Int64, b Int64) engine = TinyLog;
insert into t values(1,1);
insert into t values(2,2);
create table s(a Int64, b Int64) engine = TinyLog;
insert into s values(1,1);
```

**Right(expected) result:**
`select a, b, s_a, s_b from t all left join (select a,b,a s_a, b s_b from s) using (a,b)`

a | b | s_a | s_b
-- | -- | -- | --
1 | 1 | 1 | 1
2 | 2 | 0 | 0

`select a,b,s_a,s_b from t all left join (select a, b, a s_a, b s_b from s) s on (s.a = t.a and s.b = t.b)`

a | b | s_a | s_b
-- | -- | -- | --
1 | 1 | 1 | 1
2 | 2 | 0 | 0

**Wrong (unexpected) results**

`select * from t all left join s using (a,b)`

a | b | a | b
-- | -- | -- | --
1 | 1 | 1 | 1
2 | 2 | 2 | 2

`select t.*, s.* from t all left join s on (s.a = t.a and s.b = t.b)`

a | b | a | b | a | b | a | b
-- | -- | -- | -- | -- | -- | -- | --
1 | 1 | 1 | 1 | 1 | 1 | 1 | 1
2 | 2 | 2 | 2 | 2 | 2 | 2 | 2

`select * from t all left join (select a s_a, b s_b from s)  on (s_a = t.a and s_b = t.b)`

a | b | s_a | s_b
-- | -- | -- | --
1 | 1 | 1 | 1
2 | 2 | 2 | 2

`select a,b,s_a,s_b from t all left join (select a,b, a s_a, b s_b from s)  on (s_a = t.a and s_b = t.b) `

a | b | s_a | s_b
-- | -- | -- | --
1 | 1 | 1 | 1
2 | 2 | 2 | 2

**Comment by den-crane** [comment]
```
create table t(a Int64, b Int64) engine = TinyLog;
insert into t values(1,1);
insert into t values(2,2);
create table z(c Int64, d Int64, e Int64) engine = TinyLog;
insert into z values(1,1,1);
```
Wrong result
`select * from t all left  join z on (z.c = t.a and z.d = t.b)`

a | b | c | d | e
-- | -- | -- | -- | --
1 | 1 | 1 | 1 | 1
2 | 2 | 2 | 2 | 0

**Comment by zhang2014** [comment]
Everything except `select t.*, s.* from t all left join s on (s.a = t.a and s.b = t.b) ` is expected.
You can refer to Backward incompatible changes of 18.12.13 [CHANGELOG](https://github.com/yandex/ClickHouse/blob/master/CHANGELOG.md)

**Comment by den-crane** [comment]
I did not mean that something wrong with the last version.
I mean it works and always worked incompatible with other SQL databases.

psql
create table t(a int, b int); insert into t values (1,1); insert into t values (2,2);
create table s(a int, b int);
insert into s values (1,1);
```

select * from t left outer join s using (a,b);
 a | b
---+---
 1 | 1
 2 | 2

select t.*, s.* from t left outer join s using (a,b);
 a | b | a | b
---+---+---+---
 1 | 1 | 1 | 1
 2 | 2 |   |

select * from t left outer join s on t.a=s.a and t.b=s.b;
 a | b | a | b
---+---+---+---
 1 | 1 | 1 | 1
 2 | 2 |   |
```

mysql
create table t(a int, b int); insert into t values (1,1); insert into t values (2,2);
create table s(a int, b int); insert into s values (1,1);

```
select * from t left outer join s using (a,b);
+------+------+
| a    | b    |
+------+------+
|    1 |    1 |
|    2 |    2 |
+------+------+

select t.*, s.* from t left outer join s using (a,b);
+------+------+------+------+
| a    | b    | a    | b    |
+------+------+------+------+
|    1 |    1 |    1 |    1 |
|    2 |    2 | NULL | NULL |
+------+------+------+------+

select * from t left outer join s on (t.a = s.a and t.b = s.b);
+------+------+------+------+
| a    | b    | a    | b    |
+------+------+------+------+
|    1 |    1 |    1 |    1 |
|    2 |    2 | NULL | NULL |
+------+------+------+------+
```

**Comment by zhang2014** [comment]
OK，Two questions, and I'll try to fix that : )
- Unexpected : `SELECT t.*, s.* FROM t ALL LEFT JOIN s ON (s.a = t.a and s.b = t.b)` .
- Remove duplicate join key when use `USING`.

**Comment by den-crane** [comment]
One more test. 
There is a very useful use-case find all rows in T which are "not-exists" in S using semi-join.

mysql
```
create table t(a int, b int, c varchar(100)); insert into t values (1,1,'a'); insert into t values (2,2,'b');
create table s(a int, b int, c varchar(100)); insert into s values (1,1,'a');

select t.* from t left outer join s on (t.a = s.a and t.b = s.b) where s.a is null and s.b is null;
+------+------+------+
| a    | b    | c    |
+------+------+------+
|    2 |    2 | b    |
+------+------+------+

select t.* from t left outer join s using (a,b) where s.a is null and s.b is null;
+------+------+------+
| a    | b    | c    |
+------+------+------+
|    2 |    2 | b    |
+------+------+------+
```

psql
```
select t.* from t left outer join s on (t.a = s.a and t.b = s.b) where s.a is null and s.b is null;
 a | b | c
---+---+---
 2 | 2 | b

select t.* from t left outer join s using (a,b) where s.a is null and s.b is null;
 a | b | c
---+---+---
 2 | 2 | b
```

CH:

```
create table t(a Int64, b Int64, c String) engine = TinyLog;
insert into t values(1,1,'a'),(2,2,'b');
create table s(a Int64, b Int64, c String) engine = TinyLog;
insert into s values(1,1,'a');


select t.* from t all left join s on (s.a = t.a and s.b = t.b) where s.a = 0 and s.b = 0;

Received exception from server (version 18.10.3):
Code: 47. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Unknown identifier: default.s.b.


create table z(d Int64, e Int64, f String) engine = TinyLog; insert into z values(1,1,'a');
select a,b,c from (select a,b,c,d,e,f from t all left join z on (z.d = t.a and z.e = t.b)) where d=0 and e=0;
0 rows in set. Elapsed: 0.003 sec.
```

**Comment by den-crane** [comment]
create table t(a Int64, b Int64, c String) engine = TinyLog;
insert into t values(1,1,'a'),(2,2,'b');
create table s(a Int64, b Int64, c String) engine = TinyLog;
insert into s values(1,1,'a');

CORRECT
```
select t.*,s.a sa, s.b sb, s.c sc from t all left join s on (s.a = t.a and s.b = t.b);
┌─a─┬─b─┬─c─┬─sa─┬─sb─┬─sc─┐
│ 1 │ 1 │ a │  1 │  1 │ a  │
│ 2 │ 2 │ b │  0 │  0 │    │
└───┴───┴───┴────┴────┴────┘
```

INCORRECT ( join_use_nulls = 1)
```
set join_use_nulls = 1
select t.*,s.a sa, s.b sb, s.c sc from t all left join s on (s.a = t.a and s.b = t.b);
┌─a─┬─b─┬─c─┬─sa─┬─sb─┬─sc───┐
│ 1 │ 1 │ a │  1 │  1 │ a    │
│ 2 │ 2 │ b │  0 │  0 │ ᴺᵁᴸᴸ │
└───┴───┴───┴────┴────┴──────┘

sa sb -- zeros have to be null too
```

**Comment by den-crane** [comment]
Yep,

set join_use_nulls = 1;
select t.*, s.* from t all left join s using (a,b) format PrettyCompact; -- NULLs expected

current result
```
┌─a─┬─b─┬─s.a─┬─s.b─┐
│ 1 │ 1 │   1 │   1 │
│ 2 │ 2 │   0 │   0 │
└───┴───┴─────┴─────┘
```

expected result
```
┌─a─┬─b─┬─s.a─┬─s.b─┐
│ 1 │ 1 │   1 │   1 │
│ 2 │ 2 │   ᴺᵁᴸᴸ │   ᴺᵁᴸᴸ │
└───┴───┴─────┴─────┘
```

**Comment by den-crane** [comment]
19.1.6.

```
select x, z.y, z.x from (select 666 x) t any left join (select 555 x, x as y) z  using(x)
┌───x─┬─y─┬─z.x─┐
│ 666 │ 0 │ 666 │
└─────┴───┴─────┘
expected
┌───x─┬─y─┬───x─┐
│ 666 │ 0 │ 0      │
└─────┴───┴─────┘
```
----------------------------
```
select x, z.y, z.x from (select 666 x) t any left join (select 555 x, x as y) z on (t.x = z.x)
┌───x─┬─y─┬─z.x─┐
│ 666 │ 0 │ 666 │
└─────┴───┴─────┘
expected
┌───x─┬─y─┬─z.x─┐
│ 666 │ 0 │ 0    │
└─────┴───┴─────┘
```

**Comment by den-crane** [comment]
I think 3d and 6 also wrong
select * from t all left join (select a,b,a s_a, b s_b from s) using (a,b)
┌─a─┬─b─┬─a─┬─b─┬─s_a─┬─s_b─┐
│ 1 │ 1 │ 1 │ 1 │   1 │   1 │
│ 2 │ 2 │ 2 │ 2 │   0 │   0 │
└───┴───┴───┴───┴─────┴─────┘
expected
┌─a─┬─b─┬─a─┬─b─┬─s_a─┬─s_b─┐
│ 1 │ 1 │ 1 │ 1 │   1 │   1 │
│ 2 │ 2 │ 0 │ 0 │   0 │   0 │
└───┴───┴───┴───┴─────┴─────┘


select * from t all left join (select a,b,a s_a, b s_b from s) using (a,b)
┌─a─┬─b─┬─a─┬─b─┬──s_a─┬──s_b─┐
│ 1 │ 1 │ 1 │ 1 │    1 │    1 │
│ 2 │ 2 │ 2 │ 2 │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │
└───┴───┴───┴───┴──────┴──────┘
expected
┌─a─┬─b─┬─a─┬─b─┬──s_a─┬──s_b─┐
│ 1 │ 1 │ 1 │ 1 │    1 │    1 │
│ 2 │ 2 │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │
└───┴───┴───┴───┴──────┴──────┘

**Comment by den-crane** [comment]
And let's remove a setting **asterisk_left_columns_only** 
It's broken in master anyway and has no sense.

**Comment by den-crane** [comment]
I did typo and got
select * from t left outer join s on (t.a=s.a and t.b = s.a);
DB::Exception: Not found column dw.s.a in block. There are only columns: dw.s.b.

**Comment by den-crane** [comment]
some examples https://den-crane.github.io/CHvsPG.html
