### ISSUE TITLE
Questions: Joining Columns/Compression/Segments

### ISSUE THREAD

**Issue by notbdu** [yandex/ClickHouse#3156]
Hi, I had a few questions:

- Where is the code located that reads segment files for separate columns and joins them together? 
- Where is the code that writes/reads segment files to/from disk?
- For float/int compression strategies:
  - Does clickhouse sort the floats/int before compressing?
  - If sorting happens before storing on disk, how are the row ids determined from the sorted values.
- Does clickhouse support variable length columns?
- If variable length columns are supported, how are the row ids determined from the variable length data?

**Comment by filimonov** [comment]
> Hi, I had a few questions:

You can find some overview of ClickHouse architecture here: https://clickhouse.yandex/docs/en/development/architecture/

There is also few videos (Russian)
https://www.youtube.com/watch?v=g5CDi8Nbut4
https://www.youtube.com/watch?v=PLMSA_gDdyM
https://www.youtube.com/watch?v=vbhSrZxm66E
 
>     * Where is the code located that reads segment files for separate columns and joins them together?

ClickHouse is columnar database. Each columns is just stored in a separate file.

> 
>     * Where is the code that writes/reads segment files to/from disk?

About code related to data reading it is organazed by logical levels, sounds like you are interested in storage by data type - check here: 
https://github.com/yandex/ClickHouse/blob/master/dbms/src/Columns/IColumn.h

> 
>     * For float/int compression strategies:
>       * Does clickhouse sort the floats/int before compressing?

Yes. As any other columns - by main sorting key (aka PRIMARY key).

>       * If sorting happens before storing on disk, how are the row ids determined from the sorted values.

They are sorted in the same order as other columns.

>     * Does clickhouse support variable length columns?
>     * If variable length columns are supported, how are the row ids determined from the variable length data?

Yes. String and Array. Offsets are stored separately.
Please check the sources:
https://github.com/yandex/ClickHouse/blob/master/dbms/src/Columns/ColumnArray.cpp
https://github.com/yandex/ClickHouse/blob/master/dbms/src/Columns/ColumnString.cpp
