### ISSUE TITLE
Exception: Could not determine local time zone: custom time zone file used.

### ISSUE THREAD

**Issue by BraisedFish** [yandex/ClickHouse#3157]
I try to connect the clickhouse-server, get this error
[root@vm24177 bin]# clickhouse-client --port=9100 --host=localhost
ClickHouse client version 18.12.14.
Connecting to localhost:9100.
Connected to ClickHouse server version 18.12.14 revision 54407.

Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Exception: Could not determine local time zone: custom time zone file used., e.what() = Exception

**Comment by filimonov** [comment]
What linux/unix distribution do you use? 
Can you show your timezone settings? Those commands can be helpful:
```bash
$ ls -la /etc/localtime
$ strings /etc/localtime 
$ echo $TZ
$ echo $TZDIR
$ date 
$ timedatectl
```

**Comment by BraisedFish** [comment]
> What linux/unix distribution do you use?
> Can you show your timezone settings? Those commands can be helpful:
> 
> ```shell
> $ ls -la /etc/localtime
> $ strings /etc/localtime 
> $ echo $TZ
> $ echo $TZDIR
> $ date 
> $ timedatectl
> ```

root@vm24177 packege]# ls -la /etc/localtime
-rw-r--r--. 1 root root 405 Jan 28  2015 /etc/localtime
[root@vm24177 packege]# strings /etc/localtime
TZif2
p ~h
!Iap"^J
#)Cp$Gg
TZif2
!Iap
#)Cp
CST-8
[root@vm24177 packege]# echo $TZ

[root@vm24177 packege]# echo $TZDIR

[root@vm24177 packege]# date
Tue Sep 18 15:43:03 CST 2018
[root@vm24177 packege]# timedatectl
      Local time: Tue 2018-09-18 15:43:15 CST
  Universal time: Tue 2018-09-18 07:43:15 UTC
        RTC time: Tue 2018-09-18 07:43:15
       Time zone: n/a (CST, +0800)
     NTP enabled: no
NTP synchronized: no
 RTC in local TZ: no
      DST active: n/a

**Comment by BraisedFish** [comment]
> What linux/unix distribution do you use?
> Can you show your timezone settings? Those commands can be helpful:
> 
> ```shell
> $ ls -la /etc/localtime
> $ strings /etc/localtime 
> $ echo $TZ
> $ echo $TZDIR
> $ date 
> $ timedatectl
> ```

I defined TZ and TZDIR, and it' s ok now. thanks!

**Comment by filimonov** [comment]
> Time zone: n/a (CST, +0800)

Hm... It look's like your linux distribution itself is not sure which timezone is in use :) 
So clickhouse also can't determine proper timezone - may be it's caused by using /etc/localtime from another version of tzdata database.

1) What a distro do you use? 
2) Could you also show the output of those commands:
```
$ sha1sum /etc/localtime
$ sha1sum /usr/share/zoneinfo/posix/Asia/Shanghai
$ grep -rl '!Iap' /usr/share/zoneinfo/ | xargs sha1sum
```

And solution is - ensure that you use proper version of tzdata database (update tzdata package if needed), and setup proper system timezone, for Debian based linux it's ```sudo dpkg-reconfigure tzdata```.

**Comment by whatwo** [comment]
dpkg-reconfigure tzdata

**Comment by RalphSu** [comment]
`sudo dpkg-reconfigure tzdata` works for me. Thanks

**Comment by Sammion** [comment]
After execute dpkg-reconfigure tzdata and choose one time zone, it works!
