### ISSUE TITLE
Why "alter table update/delete" can not used for Distributed engine?

### ISSUE THREAD

**Issue by sdlcwangsong** [yandex/ClickHouse#3158]

**Comment by ztlpn** [comment]
Because a Distributed table is just a view over local tables that contain the data. You can use [distributed DDLs](https://clickhouse.yandex/docs/en/query_language/create/#distributed-ddl-queries-on-cluster-clause) to update/delete data on the whole cluster.

**Comment by sdlcwangsong** [comment]
@ztlpn thank you ,but my table engine  is ReplicatedMergeTree, and I saw " ALTER queries are not yet supported for replicated tables"

**Comment by alexey-milovidov** [comment]
The message `ALTER queries are not yet supported for replicated tables` indicate that you are using old ClickHouse version (at least on one of your cluster nodes).

**Comment by sdlcwangsong** [comment]
@alexey-milovidov , after update version, I got this error:
![image](https://user-images.githubusercontent.com/7447175/45727635-25c84c00-bbf7-11e8-9230-5bcba1b0f026.png)
is my sql wrong? 
thanks!

**Comment by ztlpn** [comment]
Thanks! Turns out I forgot to enable ON CLUSTER for ALTER UPDATE queries - fixed in badefe14bcc6c55c0e4ed9140379fb506f164c7b
ALTER DELETE should work though.

**Comment by sdlcwangsong** [comment]
thank you very much
