### ISSUE TITLE
the mysql function error when the sql include ‘like' statement

### ISSUE THREAD

**Issue by Hitvz** [yandex/ClickHouse#3168]
sql :
`SELECT  *,  toDate(ctime) AS dth FROM mysql('my-host',  'my-database', 'my-table', 'my-user', 'my-password') WHERE (mch_type IN (4, 11, 12)) AND (toString(ctime) like '2018-09-17%')
`
the  statement using 'like' key word
it is like this issue :[https://github.com/yandex/ClickHouse/issues/2310](https://github.com/yandex/ClickHouse/issues/2310)? not Support like?

**Comment by VadimPE** [comment]
#3182

**Comment by Hitvz** [comment]
thx，i will try it later
