### ISSUE TITLE
null comparison exception

### ISSUE THREAD

**Issue by ben-motiv** [yandex/ClickHouse#3169]
Hi,

Just updated clickhouse to latest from possibly 1.1.54385. The following query now fails with exception:
DB::Exception: Cannot compare unsigned long with DB::Null., e.what() = DB::Exception

`SELECT
	mpid
FROM
	xxxxxx
where toUInt32(time) = null and (mpid = 90 or mpid = 46) and siteid = null;`

using latest (and older) versions of JDBC driver. SiteId = UInt32, time = DateTime. This query is auto generated by Pentaho PDI where null is used to get the return types of the query, and is automatically replaced with variable substitution when running live.

This worked perfectly fine on earlier version of clickhouse? I tried replacing null with ifnull(null, 0) but this still gives the same issue.

**Comment by alexey-milovidov** [comment]
Does not reproduce on version 19.11:

```
milovidov-Pro-P30 :) CREATE TABLE xxxxxx (time Nullable(UInt64), mpid UInt8, siteid Nullable(UInt64)) ENGINE = Memory

CREATE TABLE xxxxxx
(
    `time` Nullable(UInt64), 
    `mpid` UInt8, 
    `siteid` Nullable(UInt64)
)
ENGINE = Memory

Ok.

0 rows in set. Elapsed: 0.030 sec. 

milovidov-Pro-P30 :) SELECT mpid FROM xxxxxx where toUInt32(time) = null and (mpid = 90 or mpid = 46) and siteid = null;

SELECT mpid
FROM xxxxxx
WHERE (toUInt32(time) = NULL) AND ((mpid = 90) OR (mpid = 46)) AND (siteid = NULL)

Ok.
```
