### ISSUE TITLE
CH can not found column  if two tables has one same field  and run inner join with condition

### ISSUE THREAD

**Issue by lightee2** [yandex/ClickHouse#3170]
if two tables has one same filed name ,when run inner join with condition like beflow, i got an error

CREATE TABLE IF NOT EXISTS t1 ( 
  f1 UInt32,
  f2 String
) ENGINE  = MergeTree ORDER BY (f1);

 CREATE TABLE IF NOT EXISTS t2 ( 
  f1 String,
  f3 String
) ENGINE  = MergeTree ORDER BY (f1);

insert into t1 values(1,'1');
insert into t2 values('1','name1');

select t1.f1,t2.f3 from t1 all inner join t2 on t1.f2 = t2.f1
where t2.f1 = '1'

Code: 10. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Not found column f1 in block. There are only columns: f3, default.t2.f1.

**Comment by alexey-milovidov** [comment]
The issue has been fixed in master.

**Comment by alexey-milovidov** [comment]
I've added a test from your example.
