### ISSUE TITLE
Attempt to attach to nullptr thread group when creating materalized view

### ISSUE THREAD

**Issue by astudnev** [yandex/ClickHouse#3173]
Error happens

2018.09.19 14:43:03.046468 [ 356 ] {3c0ea2eb-f069-41b4-900a-e907f5bc5917} <Error> executeQuery: Code: 49, e.displayText() = DB::Exception: There was an error on ch3: Code: 49, e.displayText() = DB::Exception: Attempt to attach to nullptr thread group, e.what() = DB::Exception, e.what() = DB::Exception (from [::1]:60750) (in query: CREATE MATERIALIZED VIEW db_origin.transfers_from ON CLUSTER all_servers (     tx_date Date,     tx_time DateTime,     blockchain_id UInt32,     block UInt32,     tx_hash_bin String,     tx_from_bin String,     tx_to_bin String,     transfer_from_bin String,     transfer_to_bin String,     currency_id UInt32,     entity_id UInt64,     gas_used UInt32,     gas_price Float32,     gas_value Float32,     value Float64,     external UInt32,     internal UInt32 ) Engine=ReplicatedMergeTree('/clickhouse/cross_replicated/tables/{shard_origin}/transfers_from',                            'origin',                            tx_date,                            transfer_from_bin,                            1024) populate as select     tx_date,     tx_time,     blockchain_id,     block,     unhex(substring(tx_hash, 3, length(tx_hash))) tx_hash_bin,     unhex(substring(tx_from, 3, length(tx_from))) tx_from_bin,     unhex(substring(tx_to, 3, length(tx_to))) tx_to_bin,     unhex(substring(transfer_from, 3, length(transfer_from))) transfer_from_bin,     unhex(substring(transfer_to, 3, length(transfer_to))) transfer_to_bin,     currency_id,     entity_id,     gas_used,     gas_price,     gas_value,     value,     external,     internal from production.transfers where success=1), Stack trace:

0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x54dbc86]
1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x1f) [0x2ae3aef]
2. /usr/bin/clickhouse-server(DB::DDLQueryStatusInputSream::readImpl()+0xba8) [0x4e28308]
3. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x135) [0x47dc8e5]
4. /usr/bin/clickhouse-server(DB::AsynchronousBlockInputStream::calculate()+0x44) [0x47d4f44]
5. /usr/bin/clickhouse-server() [0x47d52ba]
6. /usr/bin/clickhouse-server(ThreadPool::worker()+0x12d) [0x5684aed]
7. /usr/bin/clickhouse-server() [0x5c5301f]
8. /lib/x86_64-linux-gnu/libpthread.so.0(+0x7494) [0x7f65fc9e9494]
9. /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f65fc01bacf]

on DDL:

CREATE MATERIALIZED VIEW db_origin.transfers_from ON CLUSTER all_servers
(
    tx_date Date,
    tx_time DateTime,

    blockchain_id UInt32,
    block UInt32,

    tx_hash_bin String,
    tx_from_bin String,
    tx_to_bin String,
    transfer_from_bin String,
    transfer_to_bin String,

    currency_id UInt32,
    entity_id UInt64,

    gas_used UInt32,
    gas_price Float32,
    gas_value Float32,

    value Float64,
    external UInt32,
    internal UInt32

) Engine=ReplicatedMergeTree('/clickhouse/cross_replicated/tables/{shard_origin}/transfers_from',
                           'origin',
                           tx_date,
                           transfer_from_bin,
                           1024)
populate
as select
    tx_date,
    tx_time,
    blockchain_id,
    block,

    unhex(substring(tx_hash, 3, length(tx_hash))) tx_hash_bin,
    unhex(substring(tx_from, 3, length(tx_from))) tx_from_bin,
    unhex(substring(tx_to, 3, length(tx_to))) tx_to_bin,
    unhex(substring(transfer_from, 3, length(transfer_from))) transfer_from_bin,
    unhex(substring(transfer_to, 3, length(transfer_to))) transfer_to_bin,

    currency_id,
    entity_id,

    gas_used,
    gas_price,
    gas_value,

    value,
    external,
    internal

from production.transfers where success=1;

Clickhouse version 18.12.17 revision 54407

**Comment by alexey-milovidov** [comment]
Fixed in master.
