### ISSUE TITLE
Cast decimal to Int question

### ISSUE THREAD

**Issue by e11it** [yandex/ClickHouse#3177]
Привет!

Это поведение корректное?

```
SELECT toInt64(toDecimal128('7654321987654321', 6))

┌─toInt64(toDecimal128('7654321987654321', 6))─┐
│                               -1076802935142 │
└──────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.004 sec.
```

```
SELECT toInt64(toDecimal128('7654321987654321', 0))

┌─toInt64(toDecimal128('7654321987654321', 0))─┐
│                             7654321987654321 │
└──────────────────────────────────────────────┘
```

decimal_check_overflow = 1

**Comment by e11it** [comment]
Добавлю еще один пример неправильного cast:

19 символов помещается в Decimal64, вместо 18.
```bash
SELECT toDecimal64(toDecimal64('1234567890', 8), 9)

┌─toDecimal64(toDecimal64('1234567890', 8), 9)─┐
│                         1234567890.000000000 │
└──────────────────────────────────────────────┘
```

При этом в лоб такие шутки не проходят:

```
SELECT toDecimal64('1234567890', 9)

Received exception from server (version 18.12.17):
Code: 69. DB::Exception: Received from clickhouse-server:9000, 172.17.0.2. DB::Exception: Cannot read decimal value.
```

**Comment by e11it** [comment]
Ну и первый пример это скорее BUG.

**Comment by 4ertus2** [comment]
В первом кейсе действетльно, можно кинуть исключение.
Про второй кейс есть в документации в git-е (пока не доехал до веб-а):
https://github.com/yandex/ClickHouse/blob/master/docs/ru/data_types/decimal.md

> Внутри данные представляются как знаковые целые числа, соответсвующей разрядности. Реальные диапазоны, хранящиеся в ячейках памяти несколько больше заявленных. Заявленные диапазоны Decimal проверяются только при вводе числа из строкового представления.

Правда для следующего запроса тоже куда-то потерялось исключение.
`
SELECT toDecimal64(toDecimal64('9234567890', 8), 9)

┌─toDecimal64(toDecimal64('9234567890', 8), 9)─┐
│                        -9212176183.709551616 │
└──────────────────────────────────────────────┘
`

**Comment by e11it** [comment]
Нельзя ли реализовать так, чтобы результат приведение типа decimal к Int не зависел от размерности дробной части? Например присваивать целую часть, а затем добавлять результат округления дробной части.

**Comment by 4ertus2** [comment]
> Нельзя ли реализовать так, чтобы результат приведение типа decimal к Int не зависел от размерности дробной части?
Да, на вскидку, не должно быть с этим проблем.

> добавлять результат округления дробной части.
Тут дорого делать реальное округление. Скорее всего будет отбрасывание дробной части - неявный trunc(x, 0). При желании сохранить точность, надо сначала будет сделать round(x, 0), затем приведение.

**Comment by e11it** [comment]
Может быть лучше сделать так, чтобы не было неочевидных поведений:

a) Приведение к Int вызывает round(x, 0) -  дорогая операция.
b) Две дополнительные функции для быстрого получения целой и дробной части для типа decimal.

**Comment by 4ertus2** [comment]
И сложно по реализации и расходится с текущим поведением при приведении Decimal-ов друг к другу (там лишние знаки отбрасываются). В добавок, с round есть особенности типа: обычное ожидается или банковское. Текущая реализация предполагает, что trunk(x, 0) = toIntNN(x), trunk(x, s) = toDecimalNN(x, s).

#3211
