### ISSUE TITLE
DB::Exception: Memory limit (for query) exceeded: would use 9.31 GiB (attempt to allocate chunk of 1048576 bytes), maximum: 9.31 GiB

### ISSUE THREAD

**Issue by SnailFastGo** [yandex/ClickHouse#3179]
Hello！
I met a problem。
I want to execute a SQL like this “ select A , B C , D, E ,F, G, H from tableName order by primaryKey limit 2000”, and my table use MergeTree engine. But it costs so much RAM that the database throws exception:
"DB::Exception: Memory limit (for query) exceeded: would use 9.31 GiB (attempt to allocate chunk of 1048576 bytes), maximum: 9.31 GiB".
Howerer, each record in the table is less than 200 Bytes.
Why it needs so much RAM?

**Comment by filimonov** [comment]
Because of ORDER BY. Due to parallel processing of different parts and the fact that different parts can have intersecting PK ranges clickhouse really need to do ORDER BY on all the resulting rows, and after that apply the LIMIT.

**Comment by shangshujie365** [comment]
but i think, ch can use topk to optimise this query, each thread just keep the top 2000 records and merge them finally

**Comment by SnailFastGo** [comment]
@filimonov  
Thank you very much for your reply！
However，In my opinion, althoug parallel processing, every part can reserve topk records .finally all of parts are sorted with  topk records their own. Then the result is also right. Or could you give me a counterexample?

**Comment by filimonov** [comment]
This optimization is possible but implemented yet.
If you can write C++ you can help the project by implementing that. 

Please check that issue: https://github.com/yandex/ClickHouse/issues/1344

**Comment by SnailFastGo** [comment]
Unfortunately！I am not good at writing C++. Howerve I will keep attention to clickhouse

**Comment by alexey-milovidov** [comment]
@filimonov We already use almost the same optimization.

We keep top N ordered records for every processed block. We collect all that filtered blocks and finally extract top N records from all of them by merging.

This algorithm (partial sort in mini-batches before merging) is more CPU efficient than usual priority queue based merging (we use it only as a final step).

To mitigate higher memory usage, we should add intermediate merging steps when number of rows become large.

**Comment by filimonov** [comment]
@alexey-milovidov but i think it still do sorting inside EACH block ignoring the fact that requested sorting order is PK, and it's enough to read few blocks from each part and merge them. Or it's not true?

**Comment by alexey-milovidov** [comment]
That's true. We have another task for it.

**Comment by alexey-milovidov** [comment]
In master.
