### ISSUE TITLE
How many column in Primary Key when create a table?

### ISSUE THREAD

**Issue by thanhthai3010** [yandex/ClickHouse#3180]
Hi guys,

I just created a table with 20 columns in Primary Key, then I inserted data into this table.

And here is the information on`system.part` table:
![table data](https://snag.gy/MY5obP.jpg "Table parts data")

It seems that the data of the primary key is too large.
So, Should I re-create the table, with fewer columns Primary key?

Thank you, guys.

**Comment by blinkov** [comment]
@thanhthai3010 20 indeed sounds like too many, please refer to https://clickhouse.yandex/docs/en/operations/table_engines/mergetree/#primary-keys-and-indexes-in-queries and https://github.com/yandex/clickhouse-presentations/blob/master/percona2018/internals.pdf

**Comment by alexey-milovidov** [comment]
86 kilobytes of memory doesn't looks too much.

**Comment by thanhthai3010** [comment]
Thank a lot for your help.
