### ISSUE TITLE
import data from hive

### ISSUE THREAD

**Issue by panda403** [yandex/ClickHouse#3187]
i want to import my hive data into clickhouse,currently i use clickhouse-driver with python for insert,but it's too slowly,the speed is 1W/s ,is there has any quick way to import data from hive to clickhouse?

**Comment by filimonov** [comment]
You can try to export data to CSV / TSV from Hive like that https://stackoverflow.com/a/19730477/1555175
And import it to ClickHouse via clickhouse-client.

**Comment by panda403** [comment]
Wow！Thanks，I tried your suggestion,It's seems the most efficient way I've found,Thank you very much!@filimonov

**Comment by filimonov** [comment]
Please kindly close the issue if you have no more questions regarding that case.
