### ISSUE TITLE
Create and drop permissions for one database

### ISSUE THREAD

**Issue by MPocahontas** [yandex/ClickHouse#3199]
Hello everyone. We use clickhouse in our organization. We have two databases: myDb and testDb. I created two users (user and testUser) with the help of users.xml file and <allow_databases> section. The first one should have all permissions for myDb and the second one should have all permissions for testDb. All works fine but there is one problem: testUser can't create database with the name testDb if such does not exist. But it would be fine for me to have such opportunity, for example, for writing all types of tests without any possibility to corrupt main database. So there are 2 questions.
1) Do I have any possibility to allow user work with only one database also with create and drop permissions.
2) Do I have any possibility to restrict all permissions for one user to one database (testUser should not corrupt myDb in this example). It also would help me.
Thanks for your reply.

**Comment by filimonov** [comment]
Just give access for your user to some third dummy database which will be used only for connecting and will always exists (for example to the `default`).
```xml
<allow_databases>
  <database>default</database>
  <database>testDb</database>
</allow_databases>
```

Use that `default` database in connection settings, and never drop it. It will be possible to CREATE / DROP `testDb` database, while keeping your your `myDb` safe.

**Comment by MPocahontas** [comment]
Thanks. It solved my problem.
