### ISSUE TITLE
Proposal to always write query_id field to logs

### ISSUE THREAD

**Issue by WouldYouKindly** [yandex/ClickHouse#3203]
Hi.

`query_id` field is optional in logs at the moment, and it makes parsing these logs harder. We use Logstash to deliver logs to Elasticsearch. Logstash has `dissect` filter that can split text logs into structured data by separators. But it can't deal with optional fields, and we have to parse logs with regular expressions, which is slower and more error prone.

We thought about using JDBC and `query_log` table, but it comes with its own set of drawbacks.

What are your thoughts?

**Comment by filimonov** [comment]
It's quite easy to change the [output format](https://github.com/yandex/ClickHouse/blob/master/libs/libdaemon/src/OwnPatternFormatter.cpp) of Clickhouse logs.
But it is also not a big issue to parse that optional query_id with `grok` filter of logstash (it's uses usual regular express, optional groups are supported). It can still be a bit tricky, because Clickhouse logs sometimes have multiline messages (like execution plans / exceptions), you can try to workaround them by `multiline` filter. 

The good news is that there are plans to duplicate ClickHouse text logs in ClickHouse table: https://www.youtube.com/watch?v=2ZO6i_Q3uRc&t=3227s

**Comment by alexey-milovidov** [comment]
Maybe something like `{}` in absense of query context will be appropriate solution?

**Comment by WouldYouKindly** [comment]
@alexey-milovidov yes, it would completely solve our problem.

@filimonov thank you. We have to use grok at the moment, but it would be much nicer to have a predetermined list of fields. Easier to read and faster to parse (IIRC grok is considered to be much slower than dissect).

**Comment by alexey-milovidov** [comment]
I've tried it, but it looks weird:

```
2018.09.24 21:49:16.045919 [ 19 ] {} <Debug> default.one_table (Data): Loading data parts
2018.09.24 21:49:16.048664 [ 19 ] {} <Debug> default.one_table (Data): Loaded data parts (1 items)
2018.09.24 21:49:16.050706 [ 19 ] {} <Debug> default.t (Data): Loading data parts
2018.09.24 21:49:16.054439 [ 19 ] {} <Debug> default.t (Data): Loaded data parts (1 items)
2018.09.24 21:49:16.061056 [ 19 ] {} <Debug> default.test_1 (Data): Loading data parts
2018.09.24 21:49:17.804759 [ 19 ] {} <Debug> default.test_1 (Data): Loaded data parts (424 items)
2018.09.24 21:49:17.811607 [ 19 ] {} <Debug> default.test_2 (Data): Loading data parts
2018.09.24 21:49:19.512565 [ 19 ] {} <Debug> default.test_2 (Data): Loaded data parts (336 items)
2018.09.24 21:49:19.531089 [ 19 ] {} <Debug> default.test_in_tuple_1 (Data): Loading data parts
2018.09.24 21:49:19.540656 [ 19 ] {} <Debug> default.test_in_tuple_1 (Data): Loaded data parts (1 items)
2018.09.24 21:49:19.544278 [ 19 ] {} <Debug> default.test_in_tuple_2 (Data): Loading data parts
2018.09.24 21:49:19.552642 [ 19 ] {} <Debug> default.test_in_tuple_2 (Data): Loaded data parts (1 items)
2018.09.24 21:49:19.557015 [ 1 ] {} <Information> DatabaseOrdinary (default): Starting up tables.
```

**Comment by alexey-milovidov** [comment]
Maybe I will get used to it in five minutes...

**Comment by alexey-milovidov** [comment]
In master.

**Comment by norrs** [comment]
Anyone keen on sharing their grok filters? ie @WouldYouKindly ?
We have some clickhouse instances running in kubernetes, and would want to monitor it's stderr logs. 

Thought of combining it together with https://github.com/fstab/grok_exporter for easily monitoring clickhouse via prometheus and alertmanager.
