### ISSUE TITLE
Exception: Not found column in block

### ISSUE THREAD

**Issue by yuragr76** [yandex/ClickHouse#3209]
Версия 18.12.17. 
Запрос
`
CREATE TABLE default.test (
	date_check Date  ,
	id1 UInt64  ,
	id2 UInt64  ,
	sign Int8
) ENGINE = CollapsingMergeTree(date_check, (date_check, id1), 8192, sign);

INSERT INTO default.test (
date_check,
	id1,
	id2,
	sign
	) VALUES (  '2018-09-24',
	1,
	1,
	1);

select id1, id2 from default.test final prewhere date_check = '2018-09-24';
`
приводит к ошибке 
 DB::Exception: Not found column date_check in block. There are only columns: id1, id2, sign, e.what() = DB::Exception
Если поле date_check не включать в ключ или убрать final, то работает без ошибок.

**Comment by topvisor** [comment]
Аналогичная проблема с ReplacingMergeTree, FINAL, PREWHERE.

Добавлю, что если date_check запрашивается в SELECT или используется в GROUP BY, то ошибки нет.

v18.12.17

**Comment by orloffv** [comment]
Тоже столкнулся с проблемой
```
ALTER TABLE errors_replicated_index ADD COLUMN testIds DEFAULT experiments
select experiments, testIds from errors_replicated_index where notEmpty(experiments) limit 10
```
->
```
Code: 10, e.displayText() = DB::Exception: Not found column testIds in block. There are only columns: experiments, e.what() = DB::Exception
```
начинает работать, если есть testIds в where

**Comment by den-crane** [comment]
>ALTER TABLE errors_replicated_index ADD COLUMN testIds DEFAULT experiments

и с каким типом поле testIds добавилось?

**Comment by den-crane** [comment]
так это все тоже самое что и #2827 и это исправлено давно.
