### ISSUE TITLE
No supertype for type Decimal

### ISSUE THREAD

**Issue by e11it** [yandex/ClickHouse#3218]
Привет!

В запросах использовались выражения типа `multiIf(decimal_field = 0, 0, decimal_field+value)`.
После перехода на decimal перестали работать, т.к.`no supertype for types Decimal(18, 4), UInt8`.
Запросы генерит Tableau и нет возможности указать toDecimal.

Синтетический пример для воспроизведения проблемы:

```sql
SELECT *
FROM
(
    SELECT toDecimal64('1234.00', 4)
    UNION ALL
    SELECT 0
)
```

Exception:

```
Received exception from server (version 18.12.17):
Code: 386. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: There is no supertype for types Decimal(18, 4), UInt8 because some of them are Decimals and some are not.
```

**Comment by 4ertus2** [comment]
Привет,

Текущее поведение соответствует ожиданиям. Когда делали обобщение - предполагалось, что объединать decimal-ы и не-decimal-ы не потребуется.
Обсудим в ближайшее время, можно ли найти тут воркэраунд или нужно менять поведение.

**Comment by alexey-milovidov** [comment]
Можно сделать так, что есть supertype, и это decimal, если он включает в себя всё множество значений соответствующего int-а.

**Comment by 4ertus2** [comment]
#3224
