### ISSUE TITLE
Array(Int64) <=> Array(String)

### ISSUE THREAD

**Issue by Graygood** [yandex/ClickHouse#3222]
I specify the column as Array(Int64). When I am trying to insert array with Int's  
`[[-1], [1], [-1], [1], [2], [-1], [1], [1], [-1], [-1], [1], [-1], [1], [1], [1], [1], [1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [1], [3, 5, 4, 2, 1], [-1], [-1], [-1], [1], [-1], [-1], [-1], [-1], [-1], [1], [2, 1], [1], [1], [-1], [-1], [1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [2, 1], [-1], [-1], [-1], [3, 2, 1], [-1], [1], [-1], [1], [-1], [-1], [1], [-1], [-1], [1], [1], [-1], [2, 1], [1], [-1], [1], [-1], [-1], [2, 1], [1], [1], [1], [0], [1], [-1], [-1], [2, 1], [-1], [-1], [-1], [1], [2, 1], [5, 2, 1], [-1], [-1], [1], [-1], [-1], [3, 5, 2, 1], [1], [1], [-1], [1], [1], [-1]]`

to clickhouse, I get 
`Code: 53, e.displayText() = DB::Exception: Type mismatch in IN or VALUES section. Expected: Array(Int64). Got: String, e.what() = DB::Exception`

On the other hand, when specifying column as Array(String) with the same array, I get 
`Code: 53, e.displayText() = DB::Exception: Type mismatch in IN or VALUES section. Expected: String. Got: Int64, e.what() = DB::Exception`

May be I am doing smth wrong, but I can't get it.

**Comment by filimonov** [comment]
> May be I am doing smth wrong, but I can't get it.

The sample you show is array of arrays. 

Please refer that sample:

```sql
:) CREATE TEMPORARY TABLE x ( id UInt32, vals Array(Int64) );
Ok.
0 rows in set. Elapsed: 0.003 sec. 

:) insert into x(id,vals) VALUES (1, [1,2,3,4,5]), (2, [10000,10001]);
Ok.
2 rows in set. Elapsed: 0.003 sec. 

:) select * from x;
┌─id─┬─vals──────────┐
│  1 │ [1,2,3,4,5]   │
│  2 │ [10000,10001] │
└────┴───────────────┘
```

If you will still have some problems - please send your insert statement sample.
