### ISSUE TITLE
foreign table grammar

### ISSUE THREAD

**Issue by cmdares** [yandex/ClickHouse#3228]
CREATE TABLE ck_table_name ENGINE = MergeTree ORDER BY id AS
----support mysql 
SELECT * FROM mysql(‘host:port’, ‘db’, ‘article_clientuser_sum’, ‘user’, ‘password’)
----support postgre
SELECT * FROM postgre(‘host:port’, ‘db’, ‘article_clientuser_sum’, ‘user’, ‘password’)
----support oracle
SELECT * FROM oracle(‘host:port’, ‘db’, ‘article_clientuser_sum’, ‘user’, ‘password’)

**Comment by filimonov** [comment]
Not sure if i understand you correctly, but if you want to access remote table like to local table, without using credentials all the time you should use corresponding table engine.

Access to postgres / oracle is possible via odbc. 

Samples: 
```
CREATE TABLE table_from_mysql (column1 UInt64, column2 String)
  ENGINE = MySQL('mysqlhost:3306', 'database', 'table', 'user', 'password');

CREATE TABLE table_from_sqlite (x Int32, y String, z String)
  ENGINE = ODBC('DSN=sqlite', 'schema', 'table_name');
```

**Comment by cmdares** [comment]
thanks! let me try.
