### ISSUE TITLE
Bad cast from type DB::ASTIdentifier to DB::ASTSelectWithUnionQuery 

### ISSUE THREAD

**Issue by kostian02** [yandex/ClickHouse#3232]
При переезде на новую версию возникли проблемы.
На старой:
SELECT version()

┌─version()─┐
│ 1.1.54304 │
└───────────┘

SELECT uniq(visitor_id) AS metric
FROM stat.visit
ALL LEFT JOIN
(
    SELECT
        id AS deal_id,
        user_id AS deal_user_id,
        payed_money,
        cost_rub,
        created_by_visit_id,
        reg_by_visit_id,
        greatest(created_by_visit_id, reg_by_visit_id) AS visit_id
    FROM deal
) USING (visit_id)
WHERE (ACCOUNT_ID = 116) AND (visit_id > 0) AND 1

┌─metric─┐
│ 637105 │
└────────┘

На новой:
SELECT version()

┌─version()─┐
│ 18.12.17  │
└───────────┘

SELECT uniq(visitor_id) AS metric
FROM stat.visit
LEFT JOIN
(
    SELECT
        id AS deal_id,
        user_id AS deal_user_id,
        payed_money,
        cost_rub,
        created_by_visit_id,
        reg_by_visit_id,
        greatest(created_by_visit_id, reg_by_visit_id) AS visit_id
    FROM deal
) USING (visit_id)
WHERE (ACCOUNT_ID = 116) AND (visit_id > 0) AND 1

Received exception from server (version 18.12.17):
Code: 368. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Bad cast from type DB::ASTIdentifier to DB::ASTSelectWithUnionQuery.

Причем если убрать join или вместо AND 1 написать AND ACCOUNT_ID > 0 или еще что-то использующее столбцы, то начинает работать. А AND 1 или AND 1 > 0 выдает ошибку приведения такую.

**Comment by CurtizJ** [comment]
Баг при прокидывании условия внутрь подзапроса. Потому что данный запрос работает при enable_optimize_predicate_expression=0.
