### ISSUE TITLE
Where can I find DAEMONS values list ?

### ISSUE THREAD

**Issue by jbfavre** [yandex/ClickHouse#324]
In release script, list of daemons to build can be passed as argument.
If not provided script uses `debian/daemons` content to build the list.

I figured out we can use, for example, `config-processor` but could not find any complete list of available "daemons" to be built.

Is there such a list, and where ?

**Comment by alexey-milovidov** [comment]
There is no explicit list. I think, every program with INSTALL CMake directive should work.

```
$ find . -name CMakeLists.txt | grep -v contrib | xargs grep -iP 'install\s*\('
./utils/config-processor/CMakeLists.txt:INSTALL(TARGETS config-processor RUNTIME DESTINATION bin COMPONENT config-processor)
./utils/compressor/CMakeLists.txt:install (TARGETS compressor RUNTIME DESTINATION bin COMPONENT compressor)
./utils/corrector_utf8/CMakeLists.txt:INSTALL( TARGETS corrector_utf8 RUNTIME DESTINATION bin COMPONENT corrector_utf8)
./dbms/src/Server/CMakeLists.txt:INSTALL(TARGETS clickhouse RUNTIME DESTINATION bin COMPONENT clickhouse)
./dbms/src/Server/CMakeLists.txt:       INSTALL(CODE "execute_process(COMMAND ln -sf clickhouse ${app} WORKING_DIRECTORY \"\$ENV{DESTDIR}\${CMAKE_INSTALL_PREFIX}/bin\" )" COMPONENT ${app})
./dbms/src/Server/CMakeLists.txt:INSTALL(
./dbms/src/Server/CMakeLists.txt:INSTALL(
./dbms/src/Server/CMakeLists.txt:INSTALL(
./dbms/src/Client/CMakeLists.txt:install (FILES config.xml DESTINATION /etc/clickhouse-client COMPONENT clickhouse-client)
```

It shows, that in addition to what is already specified in `daemons`, you could add `config-processor`, `corrector_utf8`. These are miscellaneous utilities, I doubt you need them.

**Comment by jbfavre** [comment]
Thanks for the answer @alexey-milovidov 
I'm preparing a native Debian package and therefore am trying to understand what is important and what's less important :)

Another question: how can I build & run the test suite ?
It doesn't seem to be built by default but I will need it to ensure Debian package quality :)

Cheers

**Comment by alexey-milovidov** [comment]
To run functional tests:
1. Start clickhouse-server. Install clickhouse-client or make it visible in $PATH.
2. Go to dbms/tests directory in sources and run `./clickhouse-test`.

In case of success, it will return zero exit code.

Some tests are run only if ZooKeeper is configured in /etc/clickhouse-server/config.xml
If ZK is not configured, you will get most of tests, except tests for replication.

**Comment by jbfavre** [comment]
Thanks @alexey-milovidov :)
