### ISSUE TITLE
Add column renaming functionality in DDL

### ISSUE THREAD

**Issue by alex-zaitsev** [yandex/ClickHouse#3243]
Syntax options:

1. ALTER TABLE table_name RENAME COLUMN old_name TO new_name
2. ALTER TABLE table_name CHANGE COLUMN old_name TO new_name

I personally prefer #1, though MySQL uses #2.

**Comment by perez1987** [comment]
I prefer first option

**Comment by vpanfilov** [comment]
It is a duplicate of https://github.com/yandex/ClickHouse/issues/146

**Comment by filimonov** [comment]
Fixed in #9948
