### ISSUE TITLE
[question] How to do arrayToBitmask ?

### ISSUE THREAD

**Issue by jimmykuo** [yandex/ClickHouse#3244]
https://clickhouse.yandex/docs/en/query_language/functions/encoding_functions/
`bitmaskToArray()` is pretty useful.
Is it possible to encode an `array<UInt64>` to `bitmask`?

**Comment by filimonov** [comment]
With higher-order functions.
Try that 
```
select number, bitmaskToArray(number) as bitmask, arrayReduce('groupBitOr', bitmask) as reverse from numbers(100);
```

**Comment by jimmykuo** [comment]
@filimonov 
thank you! help me a lot
