### ISSUE TITLE
Basic authentication from browser

### ISSUE THREAD

**Issue by rekby** [yandex/ClickHouse#325]
Need basic authentication header for http-requests when they denied:
WWW-Authenticate: Basic realm="User Visible Realm"
https://en.wikipedia.org/wiki/Basic_access_authentication#Server_side

It need for allow direct access to clickhouse from browsers, they doesn't send login,password for url queries in form http://user:password@server and I have only text error:
Password required for user default

When browser see basic authentication header it will ask me login/password and will send it with next requests.

**Comment by ludv1x** [comment]
> It need for allow direct access to clickhouse from browsers, they doesn't send login,password for url queries in form http://user:password@server

You could use `http://localhost:8123/?user=default&password=password&query=SELECT+123` instead of `http://user:password@server`.

**Comment by rekby** [comment]
It isn't work for users with readonly=1

**Comment by ludv1x** [comment]
This query `http://127.0.0.1:8123/?user=readonly&password=123&query=SELECT+number+FROM+system.number+LIMIT+5` works for me with readonly user.

**Comment by ludv1x** [comment]
But anyway IMHO specific 401 HTTP code in auth fail case is better than unclear 500 Internal Server Error.
