### ISSUE TITLE
Server showing wrong client patch version in logs

### ISSUE THREAD

**Issue by champtar** [yandex/ClickHouse#3255]
Hi ClickHouse Team,

```
TCPHandler: Connected ClickHouse client version 18.14.0, revision: 54409, user: default.
```
client version is 18.14.1 (same as server)

**Comment by alexey-milovidov** [comment]
This is known issue. Client cannot send its patch version in a handshake, because protocol compatibility is required. For that reason, its version is received by server as x.x.0.

**Comment by champtar** [comment]
If you don't known patch version, might I suggest not displaying it, ie showing "18.14" or "18.14.x" or "18.14.?"
