### ISSUE TITLE
Is there any plan to support the SQL Update command?

### ISSUE THREAD

**Issue by janurag** [yandex/ClickHouse#3259]
Currently i sync data between mysql and redshift and the issue i face is updating the transactional data  in realtime
So, is there any plan of supporting  SQL Update Command with Clickhouse. Also, is there any time line on it?

**Comment by 4ertus2** [comment]
There're no plans for real Update for now. At least for MergeTree engines.
ClickHouse support ALTER UPDATE syntax for rare data manipulations. Look at block Mutations at this page https://clickhouse.yandex/docs/en/query_language/alter/

**Comment by filimonov** [comment]
Also: CollapsingMergeTree / ReplacingMergeTree engines allow implementing some kind of updates by overwriting row with the newer version (usage of those Engines have some important limitations).
