### ISSUE TITLE
interserver_http_host seems to be ignored

### ISSUE THREAD

**Issue by MasterGroosha** [yandex/ClickHouse#3279]
Hello! I'm trying to switch replication to another interface. Let's say I was using `192.168.2.92` ip for everything before. Now I change `interserver_http_host` value from `192.168.2.92` to `192.168.40.92`. On another replica I do the same (`192.168.2.94 -> 192.168.40.94`).

After restarting clickhouse I run `sudo netstat -nlp | grep -e 9009 -e Foreign`, but it says that port 9009 (default `interserver_http_port`) is being listened by `192.168.2.92`, not `192.168.40.92` despite explicitly set the latter value in config file. It looks like Clickhouse keeps using `listen_host` value instead.

Am I missing something or is this bug with Clickhouse? Using **version 18.12.17 revision 54407**
P.S. You can answer me in Russian if you wish.

**Comment by proller** [comment]
interserver_http_host not usen for listen address.

**Comment by MasterGroosha** [comment]
@proller Thank you for quoting comment from config file, however this is not what I'm asking.

I'll try again:
**Previous** configuration:
```xml
<interserver_http_port>9009</interserver_http_port>
<interserver_http_host>192.168.2.92</interserver_http_host>
<tcp_port>9000</tcp_port>
<listen_host>192.168.2.92</listen_host>
```

**New** configuration:
```xml
<interserver_http_port>9009</interserver_http_port>
<interserver_http_host>192.168.40.92</interserver_http_host> <-- this value was changed
<tcp_port>9000</tcp_port>
<listen_host>192.168.2.92</listen_host>
```

After restarting clickhouse: `sudo netstat -nlp | grep -e 9009 -e Foreign`
![default](https://user-images.githubusercontent.com/2780044/46408267-3c53c480-c71a-11e8-81af-e9ae0b7f15bb.png)

So what's the use of `interserver_http_host` then?

**Comment by proller** [comment]
its only for sending to remote replicas as our hostname.

**Comment by proller** [comment]
If you set interserver_http_host = hostname/ip from eth2  - other servers will connect to this ip .
And you should have one listen_host = interserver_http_host  or  ::

Now you can't define explicit pairs of listen_host and *some*_port .
But you can use many listen_host .

**Comment by MasterGroosha** [comment]
Do you mean that to make clickhouse-client / third-party clients work through `eth1 : 192.168.2.92` AND replication work through `eth2: 192.168.40.92` I simply have to add `<listen_host>192.168.40.92</listen_host>` so that config will be the following one?

```xml
<interserver_http_port>9009</interserver_http_port>
<interserver_http_host>192.168.40.92</interserver_http_host>
<tcp_port>9000</tcp_port>
<listen_host>192.168.2.92</listen_host>
<listen_host>192.168.40.92</listen_host>
```

It seems to be working, but I'm not sure whether it is the right way or not.

**Comment by proller** [comment]
Correct.
Also you can use <listen_host>::</listen_host> for listening all possible interfaces.

**Comment by MasterGroosha** [comment]
Thank you @proller. Now this is clear to me and my issue is solved.
