### ISSUE TITLE
Unsupported type Nullable(Date) when trying to load range_hash MySQL dictionary

### ISSUE THREAD

**Issue by FirstImpression** [yandex/ClickHouse#3284]
Upgraded to 8.12, and my external `range_hash` dictionary that loads data from MYSQL stopped working. 
Error message is: `Unsupported type Nullable(Date)`. 

Downgraded to 8.6 and it works fine. Because did not have time to dig further could not try any other versions, just semi-randomly selected 18.6 after going over some change logs.

**Comment by EvgenyVinogradov** [comment]
Same problem with ODBC(Postgres) dictionaries

**Comment by den-crane** [comment]
Probably this ability (nullable types for  range_min range_max at backend) was removed with https://github.com/yandex/ClickHouse/issues/2093

**Comment by FirstImpression** [comment]
The schema of my dictionary follows. Which of the fields is nullable type? How can they be done not nullable...?
```
CREATE TABLE `sampling_history` (
  `id` int(10) UNSIGNED NOT NULL,
  `websiteId` int(11) UNSIGNED NOT NULL,
  `dateFrom` date NOT NULL DEFAULT '2017-06-01',
  `dateTill` date NOT NULL DEFAULT '2050-10-30',
  `probability` smallint(3) UNSIGNED NOT NULL DEFAULT '0',
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

**Comment by den-crane** [comment]
@Enmk

check this, range_hashed does not work with any type

Received exception from server (version 18.14.6):

Code: 50. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Unsupported type Nullable(UInt64).

Code: 50. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Unsupported type Nullable(Date).

**Comment by alexey-milovidov** [comment]
Broken after #3123
Steps to reproduce: https://gist.github.com/alexey-milovidov/c31b37f56114b822c7fdcf21d8557c9d

**Comment by alexey-milovidov** [comment]
Fixed in master.
