### ISSUE TITLE
LowCardinality data type: creation of mat. view doesn't work

### ISSUE THREAD

**Issue by xx25** [yandex/ClickHouse#3288]
Версия: 18.14.1
Сборка: https://repo.yandex.ru/clickhouse/deb/testing/main/

Падает создание matview c ошибками в логе:
[ 41 ] {bcc26060-4ec5-4f50-a0da-c55f9f4f23db} <Error> executeQuery: Code: 48, e.displayText() = DB::Exception: Method index is not supported for ColumnUni
que., e.what() = DB::Exception (from 127.0.0.1:42500) (in query: create materialized view radius.mv_traffic_by_tadig15min Engine=AggregatingMergeTree partition by tadig order by (ts
,tadig) populate as select toStartOfFifteenMinutes(timestamp) ts,toDayOfWeek(timestamp) dow, tadig,sumState(acctinputoctets+acctoutputoctets) traffic_bytes,maxState(timestamp) last_
stop,minState(radacctid) min_radacctid,maxState(radacctid) max_radacctid from radius.radacct where acctstatustype='Stop' and acctinputoctets+acctoutputoctets > 0 group by tadig,ts,d
ow), Stack trace:

0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x96249e6]
1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x22) [0x306c692]
2. /usr/bin/clickhouse-server(DB::IColumnUnique::index(DB::IColumn const&, unsigned long) const+0x4d) [0x6b0b44d]
3. /usr/bin/clickhouse-server(DB::ColumnWithDictionary::getExtremes(DB::Field&, DB::Field&) const+0x38) [0x73777a8]
4. /usr/bin/clickhouse-server(DB::MergeTreeDataPart::MinMaxIndex::update(DB::Block const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>
>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x184) [0x7490cf4]
5. /usr/bin/clickhouse-server(DB::MergeTreeDataWriter::writeTempPart(DB::BlockWithPartition&)+0xaf) [0x74b77df]
6. /usr/bin/clickhouse-server(DB::MergeTreeBlockOutputStream::write(DB::Block const&)+0xc9) [0x7459a29]
7. /usr/bin/clickhouse-server(DB::PushingToViewsBlockOutputStream::write(DB::Block const&)+0x51) [0x7638a61]
8. /usr/bin/clickhouse-server(DB::SquashingBlockOutputStream::write(DB::Block const&)+0x4ad) [0x764187d]
9. /usr/bin/clickhouse-server(DB::AddingDefaultBlockOutputStream::write(DB::Block const&)+0x73d) [0x75bb0ed]
10. /usr/bin/clickhouse-server(DB::CountingBlockOutputStream::write(DB::Block const&)+0x2c) [0x75dfcbc]
11. /usr/bin/clickhouse-server(DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::atomic<bool>*)+0xc1) [0x6ab4aa1]
12. /usr/bin/clickhouse-server(DB::NullAndDoCopyBlockInputStream::readImpl()+0x24) [0x7228754]
13. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x25a) [0x6a9a07a]
14. /usr/bin/clickhouse-server(DB::AsynchronousBlockInputStream::calculate()+0x56) [0x6a8f696]
15. /usr/bin/clickhouse-server() [0x6a8fb00]
16. /usr/bin/clickhouse-server(ThreadPool::worker()+0x19e) [0x982514e]
17. /usr/bin/clickhouse-server() [0xa00c96f]
18. /lib/x86_64-linux-gnu/libpthread.so.0(+0x7494) [0x7fafc9d97494]
19. /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7fafc93c9acf]

Структура таблицы: CREATE TABLE radius.radacct ( radacctid UInt64,  f3gppchargingid Nullable(String),  f3gppggsnaddress Nullable(String),  f3gppggsnmccmnc Nullable(String),  f3gppgprsqos Nullable(String),  f3gppimeisv Nullable(String),  f3gppimsi Nullable(UInt64),  f3gppimsimccmnc Nullable(String),  f3gpploci Nullable(String),  f3gppnsapi Nullable(String),  f3gpprattype Nullable(String),  f3gppsgsnaddress Nullable(String),  f3gppsgsnmccmnc Nullable(String),  acctdelaytime Nullable(UInt32),  acctinputoctets Nullable(UInt64),  acctinputpackets Nullable(UInt64),  acctoutputoctets Nullable(UInt64),  acctoutputpackets Nullable(UInt64),  acctsessionid String,  acctstatustype Nullable(String),  acctuniqueid String,  calledstationid Nullable(String),  callingstationid Nullable(String),  framedipaddress Nullable(String),  nasidentifier Nullable(String),  nasipaddress Nullable(String),  acctstarttime Nullable(DateTime),  acctstoptime Nullable(DateTime),  acctsessiontime Nullable(UInt32),  acctterminatecause Nullable(String),  acctstartdelay Nullable(UInt32),  acctstopdelay Nullable(UInt32),  connectinfo_start Nullable(String),  connectinfo_stop Nullable(String),  timestamp DateTime,  username Nullable(String),  realm Nullable(String),  f3gppimsi_int UInt64,  f3gppsgsnaddress_int Nullable(UInt32),  timestamp_date Date,  tac Nullable(String),  mnc Nullable(String),  tadig LowCardinality(String),  country LowCardinality(String),  tadig_op_ip Nullable(String) DEFAULT CAST('TADIG NOT FOUND', 'Nullable(String)'),  mcc Nullable(UInt16) MATERIALIZED toUInt16OrNull(substring(f3gppsgsnmccmnc, 1, 6))) ENGINE = MergeTree(timestamp_date, (timestamp, radacctid, acctuniqueid), 8192)

При этом MV создается пустым.

**Comment by 4ertus2** [comment]
Выжимка:
Method index is not supported for ColumnUnique.

```
tadig LowCardinality(String),
country LowCardinality(String),
````
