### ISSUE TITLE
Issue on insert statements when inserting '0' into a DateTime field

### ISSUE THREAD

**Issue by George3d6** [yandex/ClickHouse#3293]
I've had some weird issues when inserting the number "0" into a timestamp field with the raw insert from files.

If I insert a file as such:

`clickhouse-cleint --query="INSERT INTO ... FORMAT TabSeparate < my_file.tsv`

And one of the `DateTime` fields in my table matches with a `0` in the file, I get the following parsing:

`Column 18,  name: content_end_dt,   type: DateTime,      parsed text: "0<TAB>0<TAB>None<LINE FEED>1538357239"`

Essentially all tabs after the zero are ignored, and clickhouse tries to turn everything up until (and the first value after) the `\n` into a 'DateTime' String... which is rather weird.

If I replace the zero with any other number (e.g. `1`) the problem is gone.

This is rather weird behavior since `toDateTime(0)` works just fine inside the database.

Is this a bug ? Is it expected behavior ? Is there a workaround ?

**Comment by 4ertus2** [comment]
Can't reproduce.
In current version in all cases I've got an error:

```
DateTime, parsed text: "1"ERROR: DateTime must be in YYYY-MM-DD hh:mm:ss or NNNNNNNNNN (unix timestamp, exactly 10 digits) format.
```

Code to reproduce
```
CREATE TABLE IF NOT EXISTS test.tsv (d DateTime, x UInt32) ENGINE = Memory;
INSERT INTO test.tsv (d, x) FORMAT TabSeparated 0	0
;
```

So there's a strict behaviour in new versions. It's possible to insert the data using aliases:

```
CREATE TABLE IF NOT EXISTS test.tsv (x UInt32, d DateTime ALIAS toDateTime(x)) ENGINE = Memory;

INSERT INTO test.tsv (x) FORMAT TabSeparated 0
;

SELECT d FROM test.tsv;
```
