### ISSUE TITLE
Clickhouse Dictionary: Resolve exception errors and questions 

### ISSUE THREAD

**Issue by healiseu** [yandex/ClickHouse#3299]
Hi, that's the first time I am posting an issue for this project. Kudos to the development team of Clickhouse database it's definitely among the best of its kind.

Now the issue is the following, I have been experimenting with setting a [clickhouse dictionary][1]. This is my setup to reproduce the error.
1. lookup_dictionary.xml
```xml
      <name>Lookup</name>
      <source>
	    <clickhouse>
	        <host>localhost</host>
	        <port>9000</port>
	        <user>default</user>
	        <password></password>
	        <db>DemoDB</db>
       		<table>LookupSource</table>
	    </clickhouse>
        </source>
```

2. LookupSource Table
`DESCRIBE TABLE LookupSource`
key: UInt8
value: String

3. Lookup Dictionary
```sql
select name, key from system.dictionaries where name='Lookup';
```
name: Lookup
key:  UInt64

4. Facts Main Table
`DESCRIBE TABLE BicycleTripStar`
member_type : UInt8
```sql
SELECT * FROM BicycleTripStar LIMIT 1 FORMAT Values`
```
`(851, '2011-01-13 09:09:36', '2011-01-13 09:23:48', 31618, 31219, 'W00332',2)`

5. Query that produces the error
```sql
SELECT dictGetString('Lookup', 'value', member_type) AS memtype
FROM BicycleTripStar 
GROUP BY memtype
```
Received exception from server (version 18.12.17)
`Exception: Illegal type UInt8 of third argument of function dictGetString, must be UInt64 or tuple(...)`

### Questions
1. **Is it always the case that `id` fields of a dictionary are of type UInt64 ?** 
I noticed that system.dictionaries display always, **no matter what I define in the dictionary source table**, id fields such as the `key` field here with data type UInt64.
2. **Why is it compulsory to have a lookup field in a facts-main table that is set to UInt64 ?**
The `group by` query works fine if the Facts table, e.g. `BicycleTripStar` is created with a lookup field (member_type) of type UInt64. Even if create the LookupSource table with an id field of type UInt8 the `group by` query still works fine but that looks like an inconsistency to me. 
```sql
CREATE TABLE LookupSource (key UInt8, value String) Engine = Memory
```
3. **What is the role of a dictionary table ?**
In the documentation I read that you can also create a table with a Dictionary engine, e.g.
```sql
CREATE TABLE LookupDict (key UInt64, value String) ENGINE = Dictionary(lookup_dict)
```
But I could execute the `group by` query in my example without creating this table. Is it only for viewing dictionary items when you define external dictionary sources from some other DBMS ?

[1]: https://clickhouse.yandex/docs/en/operations/table_engines/dictionary/

**Comment by healiseu** [comment]
**UPDATE:** I have read in more detail the documentation of clickhouse and it seems the mandatory UInt64 data type of the Dictionary I tried to set up above is due to the limitations imposed from the data structure layout of the dictionary in memory, i.e. [flat type unpacked array][1]. Sorry, I should have written the whole (XML) configuration which I am doing it now. It is slightly modified to demonstrate better my case. The file I created inside the folder `/etc/clickhouse-server` is named `bicycle_trips_dictionary.xml` I have also set group:owner permissions to `clickhouse:clickhouse`.
```xml
<dictionaries>
    <dictionary>
        <name>MemberTypeLookup</name>
        <source>
            <clickhouse>
	        <host>localhost</host>
	        <port>9000</port>
	        <user>default</user>
	        <password></password>
	        <db>DemoDB</db>
       		<table>MemberTypeFlat</table>
	    </clickhouse>
        </source>
        <lifetime>
            <min>120</min>
            <max>180</max>
        </lifetime>
        <layout>
            <flat/>
        </layout>
        <structure>
            <id>
                <name>key</name>
            </id>
            <attribute>
                <name>value</name>
                <type>UInt64</type>
            </attribute>
        </structure>
    </dictionary>
</dictionaries>
```
The problem here is that in order for the dictionary to work you have to make the lookup field (member_type) in the main (facts) table of type UInt64 and this is not efficient for just a small number of lookup values (only 3 in my example).

Is that the reason you have added recently this LowCardinality data type feature ?

[1]: https://clickhouse.yandex/docs/en/query_language/dicts/external_dicts_dict_layout/#dicts-external_dicts_dict_layout-flat

**Comment by filimonov** [comment]
> Is it always the case that id fields of a dictionary are of type UInt64 ?

It depends on the chosen [memory layout](https://clickhouse.yandex/docs/en/query_language/dicts/external_dicts_dict_layout/).

> Why is it compulsory to have a lookup field in a facts-main table that is set to UInt64 ?

Just implementation trait AFAIK.

> What is the role of a dictionary table 

Sometimes you need to do some simple lookups in dictionaries.

Example:
```sql
-- THat will first read all rows, and create a column named city_name, and after that filter out not needed rows
SELECT  dictGetString('postal_codes', 'city_name', UInt64(postal_code) ) as city_name, [columns...] WHERE city_name = 'New-York';

-- with dictionary table you can do something like and you will need to process much fewer rows
SELECT  'New-York' as city_name, [columns...] WHERE postal_code in (SELECT postal_code FROM postal_codes_dictionary_table WHERE city_name = 'New-York');
```

> Is that the reason you have added recently this LowCardinality data type feature ?

In short:
1) there are a lot of cases when the range of values of columns is very small (so Cardinality is low), but enum is not flexible enough
2) strings are processed/compresses much slower that int types (need more memory, more work on compression/decompression).
3) maintaining dictionary is sometimes an overkill and users want it to work 'magically' :)

Some additional motivation - check that #1567 issue, also there is nice presentation (in Russian): https://www.youtube.com/watch?v=rqf-ILRgBdY

> The dictionary is not created correctly in system.dictionaries why ?

check `last_exception` column in `system.dictionaries`.

**Comment by healiseu** [comment]
@filimonov about the error, you are right `last_exception` column displays it crystal clear
`dictionary.structure.attribute.null_value, e.what() = Not found`
I added `<null_value></null_value>` in the structure section of the configuration file and the problem is solved.
Thank you also for the motivational links, I think that's the first time to try youtube auto-translation and check how it works ;-)

**Comment by healiseu** [comment]
Following @filimonov examples and after creating again the dictionary above and the main facts table
`describe table BicycleTripStar` 

| name | type |
| --------| ------ |
| ..//..    | ..//.. |
| member_id | UInt8 |

I managed to bypass the UInt8 conflict data type by applying type conversion function `toUInt64`. Therefore the query that is causing the error can be rewritten as:
```sql
SELECT dictGetString('MemberTypeLookup', 'value', toUInt64(member_id)) AS memtype
FROM BicycleTripStar 
GROUP BY memtype
```
Case closed

**Comment by healiseu** [comment]
OK I decided to add another source to my `bicycle_trips` dictionaries, so I modified the XML configuration as follows:

```xml
<bicycle_trips>
    <dictionary>
        <name>MemberTypeLookup</name>
        <source>
            <clickhouse>
	        <host>localhost</host>
	        <port>9000</port>
	        <user>default</user>
	        <password></password>
	        <db>DemoDB</db>
       		<table>MemberTypeFlat</table>
	    </clickhouse>
        </source>
        <lifetime>
            <min>120</min>
            <max>180</max>
        </lifetime>
        <layout>
            <flat />
        </layout>
        <structure>
            <id>
                <name>id</name>
            </id>
            <attribute>
                <name>value</name>
		<type>String</type>
		<null_value></null_value>
            </attribute>
        </structure>
    </dictionary>

   <dictionary>
        <name>StartStationLookup</name>
        <source>
            <clickhouse>
	        <host>localhost</host>
	        <port>9000</port>
	        <user>default</user>
	        <password></password>
	        <db>DemoDB</db>
       		<table>StartStation</table>
	    </clickhouse>
        </source>
        <lifetime>
            <min>120</min>
            <max>180</max>
        </lifetime>
        <layout>
            <flat />
        </layout>
        <structure>
            <id>
                <name>id</name>
            </id>
	    <attribute>
                <name>ndx</name>
		<type>UInt16</type>
		<null_value></null_value>
            </attribute>
	    <attribute>
                <name>name</name>
		<type>String</type>
		<null_value></null_value>
            </attribute>
        </structure>
    </dictionary>

</bicycle_trips>
```
```sql
    CREATE TABLE StartStation
    (        
        id UInt8,
        ndx UInt16, 
        name String
    )
    ENGINE = MergeTree()
    ORDER BY (ndx, name)
    SETTINGS index_granularity = 8192
```
and then I looked at system.dictionaries, where it created `StartStationLookup` but I got another exception
`Attempt to read after eof: error parsing null_value`

Can you help me fix this error too ?

**Comment by filimonov** [comment]
I think that it caused by the fact that empty string is not correct UInt16 value for`ndx` attribute. Try zero instead.

**Comment by healiseu** [comment]
This is the [CSV file][1] I load on StartStation dictionary source table
```bash
cat 2011-tripdata-start_station.csv | clickhouse-client --database=DemoDB --query="INSERT INTO StartStationRAM FORMAT CSV"
```
I thought the problem was with the order of columns, but it seems that is not the case. Notice that there aren't any missing values, e.g. empty strings, etc.

[1]: https://drive.google.com/file/d/1wIkh-zy_zApVvyanK2dxcFklA3o7wdtr/view?usp=sharing

**Comment by healiseu** [comment]
@filimonov I traced the error, it is caused by the attribute definition of `ndx` field:
```xml
	    <attribute>
                <name>ndx</name>
		<type>UInt16</type>
		<null_value></null_value>
            </attribute>
```
If I change the <type>UInt16</type> to <type>String</type> it works. But I don't understand why it doesn't accept numerical types ?

**Comment by filimonov** [comment]
Try that:
```xml
<attribute>
    <name>ndx</name>
    <type>UInt16</type>
    <null_value>0</null_value>
</attribute>
```
(See my comment above)

**Comment by healiseu** [comment]
Yes, it accepts it this way
Thanks

**Comment by Crusader4Christ** [comment]
I can`t use LowCardinality(UInt8) in dictionaries?
Because I get the "Unknown type LowCardinality(UInt8)"
