### ISSUE TITLE
Clickhouse server failed to restart because of LowCardinality setting

### ISSUE THREAD

**Issue by healiseu** [yandex/ClickHouse#3308]
Hi, I tried to play with LowCardinality setting, I got a message saying that this is an experimental feature and I have to  `SET allow_experimental_low_cardinality_type = 1` in order to use it.

I executed this command inside clickhouse-client and then I restarted the server. But I got 
`clickhouse-server.service: Unit entered failed state`

Now I am trying to find out how to disable this setting and make my clickhouse-server start again. 
Can you help with this please ?

PS: The version I use is the 18.12.17 and I installed it on Linux Ubuntu 16.04

**Comment by filimonov** [comment]
For non-replicated tables removing corresponding files / folders in those directories should help to completely forget 'bad' table:
```
/var/lib/clickhouse/metadata
/var/lib/clickhouse/data
```

**Comment by healiseu** [comment]
@filimonov I see, well actually I ended up doing this anyway because when I reinstalled clickhouse and attempted to attach my old tables I got this server startup error. So I had to remove the data/metadata folder that was causing the problem.

**Comment by filimonov** [comment]
> So I had to remove the data/metadata folder that was causing the problem.

It's enough to remove one file. And it would be nice if you will attach it's content here to allow developers to reproduce that problem :)

**Comment by healiseu** [comment]
I wish I could, out of frustration I `rm -rf` the whole folder and I also deleted the `xml` dictionary configuration I have made inside the `/etc/clickhouse-server` folder and when I tried to create a new configuration for the dictionary I run into the problem I described in issue #3299. Once I finish playing with normal dictionaries I will probably give another go to try to set this experimental feature and I will let you know.
