### ISSUE TITLE
Please add support for /docker-entrypoint-initdb.d to the server image

### ISSUE THREAD

**Issue by altvod** [yandex/ClickHouse#3319]
Please add the ability to run initialization scripts in the server's docker image. It is a quite common feature for database server images to have a `/docker-entrypoint-initdb.d` directory where `.sql` or `.sh` initialization scripts can be put to be run on startup.
Examples:
- MySQL: https://hub.docker.com/_/mysql/
- Postgres: https://hub.docker.com/_/postgres/

They both have it.

It will make using ClickHouse in docker much easier

**Comment by abraithwaite** [comment]
This issue should be closed.
