### ISSUE TITLE
group by decimal crashes CH server 

### ISSUE THREAD

**Issue by den-crane** [yandex/ClickHouse#3378]
ClickHouse client version 18.14.8.
Connecting to localhost:9000.
Connected to ClickHouse server version 18.14.8 revision 54409.

select  y from
(select toDecimal128(5.5,12) y)
group by  y

↘ Progress: 1.00 rows, 1.00 B (9.87 rows/s., 9.87 B/s.)
Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000, ::1

Connecting to localhost:9000.
Code: 210. DB::NetException: Connection refused: (localhost:9000, ::1)

**Comment by den-crane** [comment]
workaround: concat with empty string: 
select  toString(y)||'' z from
(select toDecimal128(5.5,12) y)
group by  z

**Comment by 4ertus2** [comment]
Reproduced only in release build. It's probably some undefined behaviour here.

**Comment by 4ertus2** [comment]
#3391
