### ISSUE TITLE
Catboost multiclass support

### ISSUE THREAD

**Issue by ghuname** [yandex/ClickHouse#3379]
On https://tech.yandex.com/catboost/doc/dg/concepts/python-reference_apply_catboost_model-docpage/
it is stated: "Multiclassification models are not currently supported"

Can you please add support for multiclassification?

**Comment by blinkov** [comment]
@ghuname are you sure that you need it inside ClickHouse, not Python?

**Comment by ghuname** [comment]
That is the idea.
