### ISSUE TITLE
Insert is skipped after ALTER TABLE DELTE

### ISSUE THREAD

**Issue by f1llon** [yandex/ClickHouse#3388]
Actually is's pretty same issue as [827]( https://github.com/yandex/ClickHouse/issues/827).
Steps to reproduce:

1. `create database data`
2. `create table data.test(date Date, id UInt64, metric UInt64) ENGINE ReplicatedMergeTree('/clickhouse/tables/{shard}/data/test', '{replica}', date, (date, id), 8192)`
3. `insert into data.test values ('2018-01-01', 1, 1)`
4. `select count() from data.test` => 1
5. `alter table data.test delete where id=1`
6. `insert into data.test values ('2018-01-01', 1, 1)`
7. `select count() from data.test` => 0 expected 1

**Comment by lapkofear** [comment]
It's pretty tricky issue due to absence of any errors except for logs like:

<table_name> (Replicated OutputStream): Block with like: <block_id> already exists; ignoring it.

**Comment by filimonov** [comment]
Exact duplicate #3526  (there are more comments there).
