### ISSUE TITLE
libcommon need git access to get revision number

### ISSUE THREAD

**Issue by jbfavre** [yandex/ClickHouse#339]
While trying to build clickhouse from a forked repo, I notice build keep waiting on something, until I hit the "Enter" key.
Here is the output:

```[ 58%] Building CXX object contrib/libpoco/Data/ODBC/CMakeFiles/PocoDataODBC.dir/src/Connector.cpp.o
[ 58%] Building CXX object contrib/libpoco/Data/ODBC/CMakeFiles/PocoDataODBC.dir/src/ConnectionHandle.cpp.o
[ 58%] Building CXX object contrib/libpoco/Data/ODBC/CMake`Files/PocoDataODBC.dir/src/Binder.cpp.o
[ 58%] Building CXX object contrib/libpoco/Data/ODBC/CMakeFiles/PocoDataODBC.dir/src/EnvironmentHandle.cpp.o
[ 58%] Building CXX object contrib/libpoco/Data/ODBC/CMakeFiles/PocoDataODBC.dir/src/Extractor.cpp.o
[ 58%] Building CXX object contrib/libpoco/Data/ODBC/CMakeFiles/PocoDataODBC.dir/src/ODBCException.cpp.o
[ 58%] Building CXX object contrib/libpoco/Data/ODBC/CMakeFiles/PocoDataODBC.dir/src/ODBCMetaColumn.cpp.o
[ 60%] Building CXX object contrib/libpoco/Data/ODBC/CMakeFiles/PocoDataODBC.dir/src/ODBCStatementImpl.cpp.o
[ 60%] Building CXX object contrib/libpoco/Data/ODBC/CMakeFiles/PocoDataODBC.dir/src/Parameter.cpp.o
[ 60%] Building CXX object contrib/libpoco/Data/ODBC/CMakeFiles/PocoDataODBC.dir/src/Preparator.cpp.o
[ 60%] Building CXX object contrib/libpoco/Data/ODBC/CMakeFiles/PocoDataODBC.dir/src/SessionImpl.cpp.o
[ 60%] Building CXX object contrib/libpoco/Data/ODBC/CMakeFiles/PocoDataODBC.dir/src/TypeInfo.cpp.o
[ 60%] Building CXX object contrib/libpoco/Data/ODBC/CMakeFiles/PocoDataODBC.dir/src/Unicode.cpp.o
[ 60%] Building CXX object contrib/libpoco/Data/ODBC/CMakeFiles/PocoDataODBC.dir/src/Utility.cpp.o
[ 60%] Linking CXX static library ../../lib/libPocoDataODBC.a
make[5] : on quitte le répertoire « /home/dev/Debian/clickhouse/build »
[ 60%] Built target PocoDataODBC

Permission denied (publickey).
fatal: Impossilble de lire le dépôt distant.

Veuillez vérifier que vous avez les droits d'accès
et que le dépôt existe.
++ git tag
++ tag_filter
++ tail -1
++ grep -E '^v1\.1\.[0-9]{5}-testing$'
++ sed 's/^v1\.1\.\(.*\)-testing$/\1/'
++ cd /home/dev/Debian/clickhouse/build/libs/libcommon
+ revision=54133
+ [[ 54133 == '' ]]
+ echo '
#ifndef REVISION
#define REVISION 54133
#endif
'
```

I traced it down to `libs/libcommon/src/get_revision_lib.sh` which tries to `git fetch --tags`. On a repository with SSH access, this is likely to fail unless the key is unlocked, which wasn't the case for me.

More, it's mandatory for a Debian package to **not** perform any network access during the build.

It's also a terrible idea from a security point of vue anyway.
I don't like the idea of a script using my github credentials to perform "something". In that particuliar case, it's not evil but it could be (`git push -f` or anything else).

I suggest to found another solution to build libcommon.

**Comment by proller** [comment]
fixed? e634bc05a9d4e4f07c4225d37be76818a4fa8fa0

**Comment by jbfavre** [comment]
Yes and no.
Yes if you use `release` script.
Probably no when you use native debian packaging.

I will test it, but I think there could be an issue with this: if you have your own fork, there are chances that you add upstream repo as a specific remote. In this case, chances are you also have upstream tags.
But, when you build clickhouse from your master you might miss some commit (like building stable release only while you can have many testing release in between).
In that case, you could use a revision number for libcommon which is greater than the clickhouse revision you're buiding.

**Comment by jbfavre** [comment]
Here is my solution: https://github.com/yandex/ClickHouse/pull/344

**Comment by proller** [comment]
https://github.com/yandex/ClickHouse/commit/22797da2a634e2d6eecf531b4485278fd8bec32c
fixed?

**Comment by jbfavre** [comment]
testing right now

**Comment by jbfavre** [comment]
Works for me
