### ISSUE TITLE
uniqState multiple times before uniqMerge

### ISSUE THREAD

**Issue by PetarLotrean** [yandex/ClickHouse#3395]
Hi,

Is there a way to do uniqState two (or more) times? Then merge on the final one?
Or a better question: is there a way to aggregate type AggregateFunction(uniq, String)  that results again in AggregateFunction(uniq, String)? 

Example:
I want to count unique users per group per day
Then count unique users per group
Then finally get final unique count for all

and I need all 3, and I don't want to recalculate from base table every time

So first table has day, group, AggregateFunction(uniq, String) as agg
Second table has group, AggregateFunction(uniq, String) as agg

But I can't do an insert from first table to second table by using
```
insert into table2 
select group, uniqState(agg)
from table1
group by group
```
I get an error saying `Conversion from AggregateFunction(uniq, AggregateFunction(uniq, String)) to AggregateFunction(uniq, String) is not supported.`

Thanks!

**Comment by filimonov** [comment]
You are looking for [MergeState](https://clickhouse.yandex/docs/en/query_language/agg_functions/combinators/#-mergestate) combinator.

**Comment by PetarLotrean** [comment]
That's it! Thanks!
