### ISSUE TITLE
false alias conflict with sub-queries? v18.14.9

### ISSUE THREAD

**Issue by ocmajortom** [yandex/ClickHouse#3420]
### ClickHouse server version 18.14.9 revision 54409

Hi,
I have a sql-generator that produces sub-queries with aliases like

```
select * from  
(
  select sub1.caption as c0 from 
  (
   select caption from test.dim_service
  ) as sub1 
)
```

But this runs into error: 
**DB::Exception: Different expressions with the same alias c0:
sub1.caption AS c0
and
caption AS c0**

But query
```
select * from
(
  select  caption as c0 from
  (
    select caption from test.dim_service
  )
)
```
works.

I hope this could be changed.
Cheers! Keep up the good work!

**Comment by YuryBolkonsky** [comment]
Same error. Please fix.
It is a problem to use enable_optimize_predicate_expression with DataGrip or connection through python not native clickhouse client

**Comment by YuryBolkonsky** [comment]
Fixed. Add <enable_optimize_predicate_expression>0</enable_optimize_predicate_expression> to users.xml. 

But i think this setting should be 0 by default

**Comment by zhang2014** [comment]
Now it's closed in the master,  Sorry to open it too optimistically.

https://github.com/yandex/ClickHouse/blob/master/CHANGELOG_RU.md#%D0%9E%D0%B1%D1%80%D0%B0%D1%82%D0%BD%D0%BE-%D0%BD%D0%B5%D1%81%D0%BE%D0%B2%D0%BC%D0%B5%D1%81%D1%82%D0%B8%D0%BC%D1%8B%D0%B5-%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F-1
