### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by sdlcwangsong** [yandex/ClickHouse#3427]
Hi, 
when I update some records with replicateMergeTree, I got this error:

`2018.10.19 18:57:29.685957 [ 17 ] <Error> default.sub_table (StorageReplicatedMergeTree): Code: 40, e.displayText() = DB::Exception: Checksums of parts don't match: uncompressed hash of compressed files doesn't match, e.what() = DB::Exception. Data after mutation is not byte-identical to data on another replicas. We will download merged part from replica to force byte-identical result.`

is this means my update is not successful? and that data was overwritten by another replicas？

**Comment by ztlpn** [comment]
Hi, this message means that the update succeeded, but updated data parts for different replicas were not byte-identical. So one replica downloaded the updated part from another. There can be several reasons for this: different compression settings for different replicas; non-deterministic UPDATE expression or MATERIALIZED column expression (e.g. `now()`, `rand()` or something like that); a bug in ClickHouse code. It is difficult to tell without the details

**Comment by sdlcwangsong** [comment]
thank you
