### ISSUE TITLE
clickhouse-server ERROR on mac osx 10.13

### ISSUE THREAD

**Issue by Tasselmi** [yandex/ClickHouse#3437]
can someone help me?  thanks. 
my error log trace below:

`./clickhouse-server --config-file=/Users/lf/ClickHouse/dbms/programs/server/config.xml

Include not found: clickhouse_remote_servers
Include not found: clickhouse_compression
Logging trace to console
2018.10.22 21:01:29.653988 [ 1 ] {} <Information> : Starting ClickHouse 18.14.9 with revision 54409
2018.10.22 21:01:29.657086 [ 1 ] {} <Information> Application: starting up
2018.10.22 21:01:29.659283 [ 1 ] {} <Debug> Application: rlimit on number of file descriptors is 524288
2018.10.22 21:01:29.659316 [ 1 ] {} <Debug> Application: Initializing DateLUT.
2018.10.22 21:01:29.659327 [ 1 ] {} <Trace> Application: Initialized DateLUT with time zone `Asia/Shanghai'.
2018.10.22 21:01:29.896878 [ 1 ] {} <Debug> Application: Configuration parameter 'interserver_http_host' doesn't exist or exists and empty. Will use 'liangfans-macbook-pro.local' as replica host.
2018.10.22 21:01:29.898659 [ 1 ] {} <Debug> ConfigReloader: Loading config `/Users/lf/ClickHouse/dbms/programs/server/users.xml'
Include not found: networks
2018.10.22 21:01:29.902760 [ 1 ] {} <Information> Application: Loading metadata.
2018.10.22 21:01:29.907185 [ 1 ] {} <Debug> Application: Loaded metadata.
2018.10.22 21:01:29.907314 [ 1 ] {} <Information> BackgroundProcessingPool: Create BackgroundProcessingPool with 16 threads
2018.10.22 21:01:29.907342 [ 3 ] {} <Debug> DDLWorker: Started DDLWorker thread
2018.10.22 21:01:29.907696 [ 1 ] {} <Information> Application: TaskStats is not implemented for this OS. IO accounting will be disabled.
2018.10.22 21:01:29.908020 [ 1 ] {} <Information> Application: Listening http://0.0.0.0:8123
2018.10.22 21:01:29.908085 [ 1 ] {} <Information> Application: Listening tcp: 0.0.0.0:9000
2018.10.22 21:01:29.908144 [ 1 ] {} <Information> Application: Listening interserver http: 0.0.0.0:9009
2018.10.22 21:01:29.908291 [ 1 ] {} <Information> Application: Available RAM = 8.00 GiB; physical cores = 2; threads = 4.
2018.10.22 21:01:29.908304 [ 1 ] {} <Information> Application: Ready for connections.
2018.10.22 21:01:31.920601 [ 21 ] {} <Debug> ConfigReloader: Loading config `/Users/lf/ClickHouse/dbms/programs/server/config.xml'
Include not found: clickhouse_remote_servers
Include not found: clickhouse_compression
2018.10.22 21:01:36.800666 [ 3 ] {} <Error> void DB::DDLWorker::run(): Code: 999, e.displayText() = Coordination::Exception: All connection tries failed while connecting to ZooKeeper. Addresses: [::1]:2181, 111.0.1.2:2181, 77.88.55.80:2181
Poco::Exception. Code: 1000, e.code() = 61, e.displayText() = Connection refused, e.what() = Connection refused, [::1]:2181
Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: 111.0.1.2:2181, e.what() = Timeout, 111.0.1.2:2181
Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: 77.88.55.80:2181, e.what() = Timeout, 77.88.55.80:2181
Poco::Exception. Code: 1000, e.code() = 61, e.displayText() = Connection refused, e.what() = Connection refused, [::1]:2181
Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: 111.0.1.2:2181, e.what() = Timeout, 111.0.1.2:2181
Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: 77.88.55.80:2181, e.what() = Timeout, 77.88.55.80:2181
Poco::Exception. Code: 1000, e.code() = 61, e.displayText() = Connection refused, e.what() = Connection refused, [::1]:2181
Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: 111.0.1.2:2181, e.what() = Timeout, 111.0.1.2:2181
Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: 77.88.55.80:2181, e.what() = Timeout, 77.88.55.80:2181
 (Connection loss), e.what() = Coordination::Exception, Stack trace:

0. 0   clickhouse-server                   0x000000010dd443f6 _ZN10StackTraceC1Ev + 22
1. 1   clickhouse-server                   0x0000000110d3b7c8 _ZN12Coordination9ExceptionC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEii.constprop.62 + 56
2. 2   clickhouse-server                   0x0000000110d3d72c _ZN12Coordination9ExceptionC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi + 348
3. 3   clickhouse-server                   0x0000000110d5e14d _ZN12Coordination9ZooKeeper7connectERKSt6vectorIN4Poco3Net13SocketAddressESaIS4_EENS2_8TimespanE + 733
4. 4   clickhouse-server                   0x0000000110d5e640 _ZN12Coordination9ZooKeeperC1ERKSt6vectorIN4Poco3Net13SocketAddressESaIS4_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESG_SG_NS2_8TimespanESH_SH_ + 1104
5. 5   clickhouse-server                   0x0000000110d4dbd8 _ZN6zkutil9ZooKeeper4initERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_iiS8_ + 888
6. 6   clickhouse-server                   0x0000000110d4e1f7 _ZN6zkutil9ZooKeeperC1ERKN4Poco4Util21AbstractConfigurationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE + 167
7. 7   clickhouse-server                   0x000000011087e780 _ZNK2DB7Context12getZooKeeperEv + 384
8. 8   clickhouse-server                   0x00000001108a9edc _ZN2DB9DDLWorker3runEv + 76
9. 9   libstdc++.6.dylib                   0x000000011b39afbf execute_native_thread_routine + 15
10. 10  libsystem_pthread.dylib             0x00007fff6f59850d _pthread_body + 0
11. 11  libsystem_pthread.dylib             0x00007fff6f597bf9 thread_start + 13`

**Comment by Tasselmi** [comment]
> help me  , plz .    I am struggling~~~

**Comment by ztlpn** [comment]
The error means that you have configured ClickHouse to use the ZooKeeper cluster on servers 77.88.55.80 and 111.0.1.2 but it cannot connect to them. If you are just experimenting with ClickHouse on a single node, you can just comment out the `<zookeeper>` section in `config.xml`.

**Comment by Tasselmi** [comment]
thank you a lot.  I am a newer in big data.  SO much thanks for your warm heart help.
Github 's server is not stable~~  I offten get a 404 page today.
