### ISSUE TITLE
can login by http but can't use tcp

### ISSUE THREAD

**Issue by Tasselmi** [yandex/ClickHouse#3443]
I input 127.0.0.1:8123 in browser , it shows ok. and i CAN USE UI.TABIX.IO TO LOG IN.

BUT WHEN i USE TERMINAL  IT CAME OUT BELOW : 
`
liangfans-MacBook-Pro:programs lf$     ./clickhouse-client
ClickHouse client version 18.14.9.
Connecting to localhost:9000.
Code: 210. DB::NetException: Connection refused: (localhost:9000, ::1)
`

MY OS IS MAC OSX 10.13  ~     need help , thanks.

**Comment by filimonov** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the latest stable version.

Thank you!
