### ISSUE TITLE
SELECT from Nothing

### ISSUE THREAD

**Issue by simPod** [yandex/ClickHouse#3444]
How can I SELECT from nothing?

I need to run query like

```sql
SELECT 1
CROSS JOIN ...
```

But for that syntax validator requires to have FROM clause present, otherwise it says the syntax is invalid.

->

```sql
SELECT 1
FROM <something here>
CROSS JOIN ...
```

Eg. [some databases support `select ... from dual`](https://stackoverflow.com/questions/3732422/select-from-nothing)

Possible with ClickHouse something similar?

**Comment by alexey-milovidov** [comment]
Yes, just write `FROM system.one`
https://clickhouse.yandex/docs/en/operations/system_tables/#systemone
