### ISSUE TITLE
greatCircleDistance is Lon/Lat, but pointInEllipses is Lat/Lon

### ISSUE THREAD

**Issue by Soetens** [yandex/ClickHouse#3447]
`greatCircleDistance(lon1Deg, lat1Deg, lon2Deg, lat2Deg)`
So it is longitude and then latitude.

While in most cases you see the order latitude, longitude.
Also in pointInEllipses you see this.
`pointInEllipses(latitude, longitude....)`

Is there a logical point of view why this is done?

**Comment by alexey-milovidov** [comment]
As far as I know, `pointInEllipses` works on plane, so the order of arguments and their units are insignificant. This is documentation issue.

**Comment by BayoNet** [comment]
I have corrected descriptions of the geo-functions.
https://github.com/yandex/ClickHouse/pull/3464/
