### ISSUE TITLE
pointInEllipses() работает не корректно?

### ISSUE THREAD

**Issue by BooBSD** [yandex/ClickHouse#3448]
Здравствуйте,

`SELECT greatCircleDistance(55.1, 37.1, 55.8, 37.8)`

возвращает `99409.90688957152`, то есть почти 100 км.

При этом,

`SELECT pointInEllipses(55.1, 37.1, 55.8, 37.8, 1., 1.)`

возвращает `1`, что можно интерпретировать, как "точка, находящаяся в 100 км от центра круга, радиусом 1 м, находится внутри этого круга".

Или я неправильно использую функцию `pointInEllipses`?

**Comment by ztlpn** [comment]
Функция `pointInEllipses` работает со своими аргументами, как с декартовыми координатами. Соответственно, расстояние считается на плоскости, а не на поверхности Земли.
