### ISSUE TITLE
I FIND A WAY TO SET multi-path data storage

### ISSUE THREAD

**Issue by Tasselmi** [yandex/ClickHouse#3455]
to recorrect the mistake here :  [https://github.com/yandex/ClickHouse/issues/1460](https://github.com/yandex/ClickHouse/issues/1460)

Just use symbolic links.

Suppose you have `<path>/opt/clickhouse/</path>`. Then create symbolic links in `/opt/clickhouse/data/ `for every db you need:

```
ln -s /mnt/ssd/fastdb /opt/clickhouse/data/fastdb
ln -s /mnt/hdd/slowdb /opt/clickhouse/data/slowdb
```

correct way below : 
1. create a db and find its data storage path , for example  `/opt/clickhouse/data/fastdb`
2. create a path in another ssd ,for example `/mnt/ssd/fastdb` 
3. delete  file `fastdb` that under `/opt/clickhouse/data/fastdb` ---- `/opt/clickhouse/data/fastdb` must be blank and no file exists
4.  run `ln -s /mnt/ssd/fastdb /opt/clickhouse/data/` in terminal
5. done

all above , is to replace the orginal data path by a symbolink that has the same file name.

**Comment by alesapin** [comment]
Why not `¯\_(ツ)_/¯`?

**Comment by hwn123** [comment]
@alesapin Could you please be more specific =), because smileys can have different interpretation.
For example, some might think that using soft links is verified, bulletproof stable production-ready solution for multi-volume setup. Is it?

**Comment by alexey-milovidov** [comment]
@hwn123 This issue is from 2.5 years ago. Now ClickHouse has support for multi-volume storage out of the box, see https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/mergetree/#table_engine-mergetree-multiple-volumes
