### ISSUE TITLE
Honor Nullable types in LEFT JOIN

### ISSUE THREAD

**Issue by mikageymir** [yandex/ClickHouse#346]
I want LEFT JOIN to honor Nullable types. In the current
implementation, a DEFAULT value is returned when there is no
corresponding record, but I want value2 to be NULL in the following
example:

```
DROP TABLE test1;
DROP TABLE test2;

CREATE TABLE test1 (day Date, key String, value1 Nullable(UInt32)) ENGINE=MergeTree(day, (key), 8192);
CREATE TABLE test2 (day Date, key String, value2 Nullable(UInt32)) ENGINE=MergeTree(day, (key), 8192);
INSERT INTO test1 VALUES ('0000-00-00', '1', NULL);

SELECT day, key, value1, value2 FROM test1 ANY LEFT JOIN test2 USING (key) FORMAT CSVWithNames;

:) SELECT day, key, value1, value2 FROM test1 ANY LEFT JOIN test2 USING (key) FORMAT CSVWithNames;

SELECT
    day,
    key,
    value1,
    value2
FROM test1
ANY LEFT JOIN test2 USING (key)
FORMAT CSVWithNames

"day","key","value1","value2"
"0000-00-00","1",NULL,0

1 rows in set. Elapsed: 0.004 sec.
```

**Comment by ludv1x** [comment]
Thank you for you note.
NULL functionality is unstable and not finalized yet (especially for "JOIN" clauses).
Finalized functionality will include proper JOIN implementation.

**Comment by mxzwrnz** [comment]
Is there any news on that? Thanks a lot!

**Comment by alexey-milovidov** [comment]
It is implemented.

Behaviour is controlled by `join_use_nulls` setting.
If set to 1, NULLs will be substituted instead of default values.

You could adjust this setting like any other - per query, per session, per user...

**Comment by ramazanpolat** [comment]
> Behaviour is controlled by `join_use_nulls` setting.
> If set to 1, NULLs will be substituted instead of default values.

If the RIGHT table have `Array(String)` column, it is substituted with [], even if  `join_use_nulls` is set to 1.

Is this expected behaviour?

```sql
SELECT *
FROM
(
    SELECT *
    FROM
    (
        SELECT
            [1, 2, 3, 4, 5] AS TCKN,
            ['ali', 'veli', 'celil', 'delil', 'halil'] AS AD
    )
    ARRAY JOIN
        TCKN,
        AD
) AS K
LEFT JOIN
(
    SELECT *
    FROM
    (
        SELECT
            *,
            rand() % 3 AS SAYI,
            ['X', 'Y'] AS X
        FROM
        (
            SELECT
                [2, 3, 4, 5] AS TCKN,
                ['ali', 'veli', 'celil', 'delil'] AS ADLAR
        )
        ARRAY JOIN
            TCKN,
            ADLAR
    )
) AS N ON K.TCKN = N.TCKN

┌─TCKN─┬─AD────┬─N.TCKN─┬─ADLAR─┬─SAYI─┬─X─────────┐
│    1 │ ali   │   ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ  │ ᴺᵁᴸᴸ │ []        │
│    2 │ veli  │      2 │ ali   │    0 │ ['X','Y'] │
│    3 │ celil │      3 │ veli  │    0 │ ['X','Y'] │
│    4 │ delil │      4 │ celil │    0 │ ['X','Y'] │
│    5 │ halil │      5 │ delil │    0 │ ['X','Y'] │
└──────┴───────┴────────┴───────┴──────┴───────────┘

5 rows in set. Elapsed: 0.015 sec.
```
As you can see the column `X` is `[]` while column `AD` is `ᴺᵁᴸᴸ`.

**Comment by den-crane** [comment]
@ramazanpolat because for Arrays empty array [] is analog for Null. Arrays cannot be nullable itself but can contain nullable types.

**Comment by crakjie** [comment]
is join_use_nulls affect a function like `emptyArrayToSingle` ?
I'm using this to make left `arrayJoin()` that could be nice to have both `LEFT ARRAY JOIN` and `arrayJoin` linked by the same parameter.

**Comment by 4ertus2** [comment]
You may try and make an issue if there's some unexpected.

**Comment by crakjie** [comment]
@4ertus2 I tried and it seems `emptyArrayToSingle` is not impacted by `join_use_nulls`. What is the expected behavior ?

**Comment by 4ertus2** [comment]
> @4ertus2 I tried and it seems `emptyArrayToSingle` is not impacted by `join_use_nulls`. What is the expected behavior ?

Let's make an issue. It could be something unknown or related to #9253
