### ISSUE TITLE
Unused variable gosu_ver in Dockerfile

### ISSUE THREAD

**Issue by spyzhov** [yandex/ClickHouse#3463]
Argument `gosu_ver` is unused in `server/Dockerfile`.

        ClickHouse/docker/server/Dockerfile
```Dockerfile
FROM ubuntu:18.04
#...
ARG version=18.14.9
ARG gosu_ver=1.10
#...
ADD https://github.com/tianon/gosu/releases/download/1.10/gosu-amd64 /bin/gosu
#...
```

**Comment by spyzhov** [comment]
Isn't it more correct ?
```Dockerfile
ADD https://github.com/tianon/gosu/releases/download/${gosu_ver}/gosu-amd64 /bin/gosu 
```

**Comment by filimonov** [comment]
> Isn't it more correct ?
> 
> ```dockerfile
> ADD https://github.com/tianon/gosu/releases/download/${gosu_ver}/gosu-amd64 /bin/gosu 
> ```

Can you test it and create pull request?
