### ISSUE TITLE
[Question] Engine = Log table size

### ISSUE THREAD

**Issue by igor-sh8** [yandex/ClickHouse#3467]
Hello. 
Is it possible to get the table size with the Log engine from clickhouse inside (using some type of query) ?
Thanks in advance.

**Comment by alesapin** [comment]
Unfortunately this information available for MergeTree family https://github.com/yandex/ClickHouse/blob/master/dbms/src/Storages/System/StorageSystemColumns.cpp#L109-L120 only.
