### ISSUE TITLE
first data row is missing when inserting from file with format 'CSVWithNames'

### ISSUE THREAD

**Issue by yuliujuan** [yandex/ClickHouse#3469]
>ClickHouse client version 18.14.9.

my csv file
`cat SLA1.csv`
>Number,Has breached
>INC8185669,FALSE
>INC8162430,FALSE
>INC8225693,FALSE
>INC8146423,FALSE

My table looks like;
```
DROP TABLE IF EXISTS TICKETS_SLA; 
CREATE TABLE TICKETS_SLA  (CREATE_DATE Date, TICKET_NUMBER String, SLA String ) ENGINE=MergeTree(CREATE_DATE, (TICKET_NUMBER), 8192);
DESCRIBE TABLE HRAI.TICKETS_SLA
```

>┌─name──────────┬─type───┬─default_type─┬─default_expression─┐
>│ CREATE_DATE   │ Date   │              │                    │
>│ TICKET_NUMBER │ String │              │                    │
>│ SLA           │ String  │              │                    │
>└───────────────┴────────┴──────────────┴────────────────────┘
>
>3 rows in set. Elapsed: 0.009 sec.

When select from this file, it reads total 4 records.
`SELECT *   FROM file('SLA1.csv', 'CSVWithNames', 'TICKET_NUMBER String, SLA String');`

>clickhouse :) SELECT * FROM file('SLA1.csv', 'CSVWithNames', 'TICKET_NUMBER String, SLA String');
>
>SELECT *
>FROM file('SLA1.csv', 'CSVWithNames', 'TICKET_NUMBER String, SLA String')
>
>┌─TICKET_NUMBER─┬─SLA───┐
>│ INC8185669    │ FALSE │
>│ INC8162430    │ FALSE │
>│ INC8225693    │ FALSE │
>│ INC8146423    │ FALSE │
>└───────────────┴───────┘
>
>4 rows in set. Elapsed: 0.016 sec.

However, when inserting into table TICKETS_SLA, it only has 3 records.
`insert into  TICKETS_SLA SELECT today(), TICKET_NUMBER, SLA FROM file('SLA1.csv', 'CSVWithNames', 'TICKET_NUMBER String, SLA String');`
>clickhouse :) insert into  TICKETS_SLA SELECT today(), TICKET_NUMBER, SLA FROM file('SLA1.csv', 'CSVWithNames', 'TICKET_NUMBER String, SLA String');
>
>INSERT INTO TICKETS_SLA SELECT
>    today(),
>    TICKET_NUMBER,
>    SLA
>FROM file('SLA1.csv', 'CSVWithNames', 'TICKET_NUMBER String, SLA String')
>
>Ok.
>
>0 rows in set. Elapsed: 0.016 sec.

First data row in CSV is missing.

>clickhouse :) select * from TICKETS_SLA;
>
>SELECT *
>FROM TICKETS_SLA
>
>┌─CREATE_DATE─┬─TICKET_NUMBER─┬─SLA───┐
>│  2018-10-26 │ INC8146423    │ FALSE │
>│  2018-10-26 │ INC8162430    │ FALSE │
>│  2018-10-26 │ INC8225693    │ FALSE │
>└─────────────┴───────────────┴───────┘
>
>3 rows in set. Elapsed: 0.007 sec.

Looks like when inserting into tables, ClickHouse ignore the first two rows in the csv file when using format 'CSVWithNames' i/o the first row claimed in their [documentation
](https://clickhouse.yandex/docs/en/interfaces/formats/#csvwithnames)

Please help to check what went wrong. Thanks.

**Comment by ztlpn** [comment]
Confirmed. Internal detail: `CSVRowInputStream::readPrefix()` is called twice.
