### ISSUE TITLE
ReplacingMergeTree или ALTER TABLE UPDATE?

### ISSUE THREAD

**Issue by BooBSD** [yandex/ClickHouse#3472]
Здравствуйте.

Подскажите, пожалуйста, что лучше использовать для обновления записей: `ReplacingMergeTree ` или `ALTER TABLE UPDATE`? И в каких случаях выгоднее первое, а в каких -- второе?

Информации об этом в документации нет.

Спасибо.

**Comment by BooBSD** [comment]
@filimonov Спасибо.

Правильно ли я понимаю, что, если мне нужны точечные апдейты по первичному ключу, то после втавки исправленной строки в `ReplacingMergeTree`, можно сразу же сделать `SELECT FINAL` по этому ключу и все остальные `SELECT` уже можно использовать без `FINAL`, и данные уже будут актуальными (без дублей)?

**Comment by filimonov** [comment]
> А вот ALTER TABLE UPDATE работает на удивление быстро.

Если условие для UPDATE позволяет выбрать маленькое количество частей то будет быстро. В общем случае это может быть эквивалентно перезаписыванию всех затронутых колонок во всей таблице.

**Comment by BooBSD** [comment]
@ztlpn 
>ALTER UPDATE перезаписывает только изменяющиеся столбцы в изменяющихся кусках

Не совсем понятно. Если я делаю точечный апдейт по конкретному первичному ключу, то перезаписывается весь кусок (из `system.parts`) или только небольшая часть куска, которая относится к конкретному первичному ключу? Иными словами, как много данных перезаписывается (какая нагрузка на дисковую подсистему?), при единичном апдейте по конкретному первичному ключу?

**Comment by ztlpn** [comment]
@BooBSD В процессе апдейта создаётся новый кусок. Если в нём изменяется хотя бы одна строка, то изменяемые столбцы будут полностью перезаписаны. Остальные столбцы перезаписаны не будут (файлы столбцов в новом куске будут хардлинками к файлам столбцов в старом куске). Также не будет перезаписан кусок, если в нём ни одна строчка не подпадает под условие WHERE в апдейте.

**Comment by ztlpn** [comment]
Будут ещё вопросы - открывайте новую issue.
