### ISSUE TITLE
how to load all data into memory for preload and improve performance

### ISSUE THREAD

**Issue by lightee2** [yandex/ClickHouse#3479]
hi,is there a way to  load all data into memory after service started? i want to improve the performace and avoid fit cold data. i tried select * from table ,select sum(f1),sum(f2) from table,but the memory usage still very low by the free command.

**Comment by alesapin** [comment]
It's strange case for using ClickHouse, when all your data can fit into memory. 

ClickHouse doesn't cache compressed data from MergeTree, it relies on OS page cache. But if you really want to load all your data into memory you can place your clickhouse data directory into [tmpfs](https://en.wikipedia.org/wiki/Tmpfs) or use [vmtouch](https://github.com/hoytech/vmtouch) to load files into OS-cache.

**Comment by alesapin** [comment]
If you have other questions related to the you can reopen issue.
