### ISSUE TITLE
Wrong error message for null in array + possible memory leak

### ISSUE THREAD

**Issue by dorantor** [yandex/ClickHouse#3480]
Minimal test case:

```sql
CREATE TABLE arraytest
(
    created_date Date DEFAULT toDate(created_at), 
    created_at DateTime DEFAULT now(), 
    strings Array(String) DEFAULT emptyArrayString()
)
ENGINE = MergeTree(created_date, cityHash64(created_at), (created_date, cityHash64(created_at)), 8192)
```

```sql
insert into arraytest (created_at, strings) values (now(), ['aaaaa', 'bbbbb', null]);
```

Instead of some error about wrong type in array got:
```
Exception on client:
Code: 173. DB::Exception: Allocator: Cannot mmap 8.00 EiB., errno: 12, strerror: Cannot allocate memory
```

Minimal test case prepared with `1.1.54343` but can be reproduced on recent versions also.

**Comment by dorantor** [comment]
Forgot to mention. If this errors happens for some time(as we had) then you'll get segfaults in threads and after some more time server will silently close. This makes me think that memory leaks are very possible.

**Comment by alesapin** [comment]
Fixed in https://github.com/yandex/ClickHouse/pull/3487.

**Comment by dorantor** [comment]
Awesome! Thanks!
