### ISSUE TITLE
same dimensions query results   having  countDistinct and  with cube

### ISSUE THREAD

**Issue by onine007** [yandex/ClickHouse#3482]
query:
SELECT 
    clientid, 
    clientplatform, 
    modek, 
    countDistinct(user_id) AS active_total_users
FROM 
(
    SELECT 
        client_id AS clientid, 
        client_platform AS clientplatform, 
        mode AS modek, 
        user_id
    FROM dw_ga_bi_active_fact 
    WHERE (ymd = '2018-10-26') AND (((client_id = 1) AND (client_ver >= 670)) OR (client_id != 1))
) AS a 
GROUP BY 
    clientid, 
    clientplatform, 
    modek
    WITH CUBE
ORDER BY 
    clientid ASC, 
    clientplatform ASC, 
    modek ASC ;

results:
┌─clientid─┬─clientplatform─┬─modek─┬─active_total_users─┐
│        0 │              0 │     0 │               9165 │
│        0 │              0 │     0 │             466745 │
│        0 │              0 │     0 │             309935 │
│        0 │              0 │     0 │               6038 │
│        0 │              0 │     0 │               1649 │
│        0 │              0 │     0 │            1192247 │
│        0 │              0 │     0 │               6038 │
│        0 │              0 │     0 │                 13 │
│        0 │              0 │     0 │               4387 │
│        0 │              0 │     0 │                 13 │
│        0 │              0 │     0 │              14230 │
│        0 │              0 │     0 │             321652 │
│        0 │              0 │     0 │            1192247 │
│        0 │              0 │     0 │               4387 │
│        0 │              0 │     0 │            1595704 │
│        0 │              0 │     0 │               1891 │
│        0 │              0 │     0 │            1595704 │
│        0 │              0 │     0 │              38659 │
│        0 │              0 │     0 │             544079 │
│        0 │              0 │     0 │               1891 │
│        0 │              0 │     0 │              61473 │
│        0 │              0 │     0 │             125808 │
│        0 │              0 │     0 │               3659 │
│        0 │              0 │     0 │             120603 │
│        0 │              0 │     0 │              38659 │

**Comment by alesapin** [comment]
Can you provide some self-contained example to reproduce the problem? I think you have zeros in your `GROUP BY` columns, but even with them I cannot reproduce this behaviour.
