### ISSUE TITLE
Question: How to use from_env in config.xml ?

### ISSUE THREAD

**Issue by AlexanderJLiu** [yandex/ClickHouse#3483]
> clickhouse version: 18.14.8

I've tried to use `from_env` in config.xml as follow:
```xml
<macros>
        <shard from_env="SHARD" />
        <replica from_env="HOSTNAME" />
<macros>
```
`SHARD` and `HOSTNAME` are the environment variables on server. And they worked correctly.
But the config didn't work.  What should I do to use `from_env` ? 
Thanks.

**Comment by alesapin** [comment]
Can't reproduce:
config.xml:
```
...
    <!-- Substitutions for parameters of replicated tables.
          Optional. If you don't use replicated tables, you could omit that.

         See https://clickhouse.yandex/docs/en/table_engines/replication/#creating-replicated-tables
      -->
    <macros>
            <shard from_env="SHARD" />
            <replica from_env="HOSTNAME" />
    </macros>
...
```
```
And after:
$ export SHARD=1111
$ export HOSTNAME=2222
$ /usr/bin/clickhouse-server --config config.xml
...
$ clickhouse-client
:) select * from system.macros;

SELECT *
FROM system.macros 

┌─macro───┬─substitution─┐
│ replica │ 2222         │
│ shard   │ 1111         │
└─────────┴──────────────┘
```

**Comment by AlexanderJLiu** [comment]
> Some notice if you run clickhouse-server as a system service you need to setup env in a way it will be visible for system service.

@filimonov  I've setup env(SHARD and HOSTNAME) in `/etc/profile`, and using command `source /etc/profile` to make it effective. But they still invisible for clickhouse-server(system service as you said). What  should I do next? 😭 

Thanks...

**Comment by filimonov** [comment]
Please, try to create some reproducible example.

**Comment by AlexanderJLiu** [comment]
@filimonov  Maybe I've found the answer for `man service` : 
> service runs a System V init script in as predictable environment as possible, **removing most environment variables** and with current working directory set to /.

As the bold part said. Is there any way to solve this problem? Because we always start clickhouse with `service`.
Thanks..

**Comment by filimonov** [comment]
> As the bold part said. Is there any way to solve this problem? Because we always start clickhouse with `service`.

I think you need to adjust service file in that case.
https://coreos.com/os/docs/latest/using-environment-variables-in-systemd-units.html

**Comment by Tasselmi** [comment]
Hey, do you want some help？ actually I solved this problem by myself
