### ISSUE TITLE
Performance issue with large number of ALTER ADD COLUMN statements

### ISSUE THREAD

**Issue by bgranvea** [yandex/ClickHouse#3485]
I have a specific use case:
- I create columns on-the-fly because I don't know in advance the schema of the metrics I have to store. And the name of the metrics (thus the columns) can be quite long.
- I have a dozen of tables, each one with several thousands of metrics columns

I have 2 performance problems when I implement it:
- adding all the columns takes a lot of time because I have to add them one by one
- more surprisingly, Zookeeper transactional log becomes quite large (I'm using ReplicatedMergeTree)

Steps to reproduce:

- Configure a single node replica with <internal_replication>true</internal_replication>

- create 10 tables:

```
for i in {1..10}; do echo "CREATE TABLE test$i (Timestamp DateTime) ENGINE = ReplicatedMergeTree('/clickhouse/tables/s1/test$i','r1') PARTITION BY toStartOfDay(Timestamp) ORDER BY tuple()" | clickhouse-client; done
```

- add 4000 columns to each table:

```
time for i in {1..10}; do echo $i; for j in {1..4000}; do echo "ALTER TABLE test$i ADD COLUMN some_very_very_very_very_long_column_name_$j Nullable(String)" | clickhouse-client; done; done
```

This takes 80 minutes on my virtual machine and Zookeeper disk usage grows by 10Gb.

I noticed that for each ADD COLUMN, a complete description of the table structure is stored in Zookeeper, this explains the disk usage.

As a workaround, I will try to play with Zookeeper settings to keep the log smaller, but IMHO, the best solution would be to implement a ADD COLUMN for multiple columns. This feature exists in Oracle, Postgresql, MySQL and SQL Server. 

It would also be nice to have a IF NOT EXISTS option (it exists only in Postgresql).

**Comment by alexey-milovidov** [comment]
> to implement a ADD COLUMN for multiple columns

ADD COLUMN *is implemented* for multiple columns from the beginning. You can execute multiple operations on columns in a single ALTER statement:

```
ALTER TABLE t ADD COLUMN a UInt8, ADD COLUMN b UInt16, DROP COLUMN c, MODIFY COLUMN d String, ...
```

> It would also be nice to have a IF NOT EXISTS option (it exists only in Postgresql).

You have successfully implemented it :)

> I noticed that for each ADD COLUMN, a complete description of the table structure is stored in Zookeeper, this explains the disk usage.

Recently we store complete list of columns for every data part in a table. But now we have an option to disable it: https://github.com/yandex/ClickHouse/blob/master/CHANGELOG.md#performance-improvements-1

`use_minimalistic_part_header_in_zookeeper`
