### ISSUE TITLE
[Performance] Severe performance degradation of the query on AMD processors

### ISSUE THREAD

**Issue by lapkofear** [yandex/ClickHouse#3490]
We have created new CH cluster based on AMD EPYC 7401P processor. For some reasons all queries with grouping by <date> became extremely slow. Example: 
```
CREATE TABLE test.perf_test (
	event_date MATERIALIZED today(),
	col1 UInt32,
	col2 UInt32,
	col3 UInt32,
	col4 UInt32,
	col5 UInt32,
	col6 UInt32,
	col7 UInt32
) ENGINE = MergeTree(event_date, (col1, col2, col3, col4), 8192)

INSERT INTO test.perf_test
(col1, col2, col3, col4, col5, col6, col7)
SELECT rand(), rand(), rand(), rand(), rand(), rand(), rand() FROM `system`.numbers LIMIT 10000000
```
And There are two queries: 
```
SELECT 1 FROM test.perf_test GROUP BY now()
SELECT 1 FROM test.perf_test GROUP BY today()
```
Both works quickly and stable on Intel CPUs. But on AMD machines second one executes 2 - 40 seconds instead of 10 ms on Intel machine. Interesting, that first one behaves normally.
Linux and clickhouse versions are the same. Both server didn't have any other queries executed.
After each executing of the 'slow' query on the AMD this metric increases on 20k
```
SELECT * FROM `system`.events WHERE event = 'SoftPageFaults'
```
"perf top" shows a lot of "page_failure"(bigger 60%). 

We tried to disable 'NUMA' feature in the system without any success. 
Here are logs of the server
[normal_query_log.txt](https://github.com/yandex/ClickHouse/files/2526272/normal_query_log.txt)
[slow_query_log.txt](https://github.com/yandex/ClickHouse/files/2526273/slow_query_log.txt)

**Comment by lapkofear** [comment]
It seems, that this bug is reproducing on all 16 bit types, because next queries executes the sama:
```
SELECT 1 FROM test.perf_test GROUP BY toUInt16(1)
SELECT 1 FROM test.perf_test GROUP BY toUInt32(1)
```
First one up to 20s, second one almost immediately.

**Comment by MykhailoSobol** [comment]
Flame Graphs 
perf record -F 99 -p <pid>  -g -- sleep <time>
amd tme = 30s
intell time = 5s

[amd__slow.svg.zip](https://github.com/yandex/ClickHouse/files/2530057/amd__slow.svg.zip)
[intell__fast.svg.zip](https://github.com/yandex/ClickHouse/files/2530058/intell__fast.svg.zip)

**Comment by lapkofear** [comment]
Added pull request https://github.com/yandex/ClickHouse/pull/3512

**Comment by lapkofear** [comment]
Temporary fix has been merged. Further investigation of the root cause is required.

**Comment by alexey-milovidov** [comment]
- we have allocated a buffer with 1 MB of memory (65536 cells of 16 bytes);
- we have written to a single cell in this buffer while we aggregated data;
- then we iterate through this buffer and compare a key in each cell to zero;
- most of the buffer is not page-faulted (not really allocated, does not point to physical memory);
- when we read from this memory, it will read as zero; and this is done via page fault (interrupt, switch to kernel code and back);
- for unknown reason, page faults occurs every time;
- this is somehow related to the details of the inner loop, only on EPYC CPU, need to investigate further.

**Comment by alexey-milovidov** [comment]
This will reproduce this issue even harder:

`./clickhouse benchmark <<< 'SELECT 1 FROM test.perf_test GROUP BY toUInt16(intHash64(rand() % 10))'`

**Comment by alexey-milovidov** [comment]
Reproduced with a simple test case.
https://github.com/yandex/ClickHouse/commit/89f4c6a36f49c74a92856f4beb4c681e1ac35005

**Comment by lapkofear** [comment]
Unfortunately this bug is still reproduced. Not as critical as when the bug was opened, but still seriously affect performance

**Comment by alexey-milovidov** [comment]
Does it reproduce with the same test case in recent ClickHouse versions (master, 19.13. 19.11)?
How big is performance difference?

**Comment by lapkofear** [comment]
Ch version: 19.13.1.11. For example above difference is ~1s on AMD vs 60ms on Intel. Symptoms are the same, but test from your commit does not show any degradation.

**Comment by alexey-milovidov** [comment]
Does this fix help https://github.com/yandex/ClickHouse/pull/6667 ?
(Go to "ClickHouse build check" and download a package for test).

**Comment by alexey-milovidov** [comment]
Also we need to test for hypothesis that I had one year ago:
- page faults happen more frequently than expected: after a page was read with page fault, subsequent read from the same page may introduce another page fault (that should not happen but happens on AMD processor under unknown circumstances).

**Comment by lapkofear** [comment]
Unfortunately I can't currently check this fix due to hardware lack

**Comment by lapkofear** [comment]
We will update our production cluster next week and double check fix.

**Comment by lapkofear** [comment]
We have updated prod CH cluster to version 19.14.3.3 and tested our queries. The problem has been solved.  Thanks to everyone who helped =)
