### ISSUE TITLE
 DB::Exception: Unknown identifier for select value query

### ISSUE THREAD

**Issue by kaitorecca** [yandex/ClickHouse#3494]
Hi all,

As I work on modifying ProxySQL to make Clickhouse work like MySQL. I have made this basic query to clickhouse to overcome the validation check of some jdbc driver. However, it's always return:

`DB::Exception: Unknown identifier: REPEATABLE-READ`

When I delete this column, it continue on SYSTEM, then OFF, then ...
 I believe this is a bug because it's very basic to select "value" as `column_name`
```
SELECT "1" as `auto_increment_increment`,	
"utf8mb4" as `character_set_client`,	
"utf8mb4" as `character_set_connection`,	
"utf8mb4" as `character_set_results`,	
"utf8mb4" as `character_set_server`,	
"utf8mb4_unicode_ci" as `collation_server`,	
NULL as `init_connect`,	
"28800" as `interactive_timeout`,	
"GPL" as `license`,	
"0" as `lower_case_table_names`,	
"268435456" as `max_allowed_packet`,	
"16384" as `net_buffer_length`,	
"60" as `net_write_timeout`,	
"0" as `query_cache_size`,	
"OFF" as `query_cache_type`,	
"IGNORE_SPACE,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" as `sql_mode`,	
"UTC" as `system_time_zone`,	
"SYSTEM" as `time_zone`,	
"REPEATABLE-READ" as `tx_isolation`,	
"600" as `wait_timeout`
```

**Comment by blinkov** [comment]
In ClickHouse only single quotes can be used for string literals. Double quotes work the same as backticks, for identifiers.
