### ISSUE TITLE
SELECT from (JOIN to itself) doesn't work

### ISSUE THREAD

**Issue by SuperCobra2017** [yandex/ClickHouse#3495]
drop table if exists t;
create table t (a Int8, val Float32) engine=Memory();

**this works**
```
SELECT a, t1.val as val1, t2.val as val2
        FROM t t1 any left join t t2 USING a
```

After wrapping with SELECT
**it stops working**
same for a View or Materialized View
```
SELECT
*
FROM (
  SELECT a, t1.val as val1, t2.val as val2
        FROM t t1 any left join t t2 USING a
);
```

Error:
> Code: 179, e.displayText() = DB::Exception: Different expressions with the same alias val1: t1.val AS val1 and val AS val1 , e.what() = DB::Exception

**Comment by 4ertus2** [comment]
Test for the issue #5870. It seems to be fixed.
