### ISSUE TITLE
Removing temporary directory <Error> executeQuery: Poco::Exception. Code: 1000, e.code() = 2, e.displayText() = File not found

### ISSUE THREAD

**Issue by q0987** [yandex/ClickHouse#3497]
Hello,

I have a scheduled script that keeps removing old partitions daily. Recently, we observed the errors as follows:

> 2018.10.30 00:06:59.206203 [ 15 ] <Warning> default.MyTable (Data): Removing temporary directory /var/lib/clickhouse/do/data/default/MyTable/tmp_delete_20181025_70930_71036_3
> 2018.10.30 00:07:17.690370 [ 58 ] <Error> executeQuery: Poco::Exception. Code: 1000, e.code() = 2, e.displayText() = File not found: /var/lib/clickhouse/do/data/default/MyTable/tmp_delete_20181025_70930_71036_3/column_one.mrk, e.what() = File not found (from 127.0.0.1:44552) (in query: alter table default.MyTable drop partition '2018-10-25')
> 

The partition of '2018-10-25' in fact has been dropped because I can no longer see it from the system.parts.

Question> What is the potential issue that caused this failure?

Thank you

**Comment by den-crane** [comment]
The partition is fact is not dropped (and the data is still on disk). 
The partition will appear after CH restart or table detach/attach.
I observe this on CH 1.1.54394

**Comment by q0987** [comment]
Hello Den,

Here is the directories listed on my machine for default.MyTable.


$ ls -l | grep 20181025
drwxr-x--- 2 clickhouse clickhouse 36 Oct 26 05:41 20181025_71037_71100_3
drwxr-x--- 2 clickhouse clickhouse 36 Oct 26 04:41 20181025_71101_71171_3
drwxr-x--- 2 clickhouse clickhouse 36 Oct 26 04:44 20181025_71172_71262_3
drwxr-x--- 2 clickhouse clickhouse 36 Oct 26 15:31 20181025_71263_71330_4
drwxr-x--- 2 clickhouse clickhouse 36 Oct 27 00:58 20181025_71333_77698_14
drwxr-x--- 2 clickhouse clickhouse 36 Oct 26 23:49 20181025_77704_77704_0
$ pwd
/var/lib/clickhouse/do/data/default/MyTable

Question> Do you have a workaround for this issue?

Thank you

**Comment by den-crane** [comment]
I am not sure you are experiencing the same issue, I just tried to warn you.
I have no workaround and I did not researched this issue.
Try to stop load into your table and execute detach table MyTable; attach table MyTable; and check the partitions.

**Comment by q0987** [comment]
Hello all,

Can I directly delete those partition directories(i.e. 20181025_x_y) from the disk without causing issues?

Thank you

**Comment by alexey-milovidov** [comment]
The "File not found" exception at server startup is fixed in #4369.

The issue may also happen if ClickHouse and you tries to delete the same directory simultaneously.
It's not recommended to manually manipulate data inside ClickHouse directory.

> Can I directly delete those partition directories(i.e. 20181025_x_y) from the disk without causing issues?

You can manually delete partition directories only if:
- clickhouse-server is not running;
- if you are using non-Replicated tables.

The only exception is `detached` directory where you can freely do anything.

In all other cases, you should use `ALTER ... DROP PARTITION` or `ALTER ... DETACH PARTITION` queries.

**Comment by q0987** [comment]
which version of the release includes this bug fix?
I am not able to find the update information through
https://github.com/yandex/ClickHouse/blob/master/CHANGELOG.md.

Thank you

**Comment by alexey-milovidov** [comment]
It's in the upcoming release 19.3.3. We're preparing changelog right now. Stay tuned!
