### ISSUE TITLE
I FIND SO BIG A BUG!!!!!!!

### ISSUE THREAD

**Issue by Tasselmi** [yandex/ClickHouse#3498]
here is my cluster config(2shards 2replicas):

```
   <!-- cluster setting -->
    <clickhouse_remote_servers>
        <cluster_1st>

            <shard>
                <weight>1</weight>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>TimeMachine01</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>TimeMachine02</host>
                    <port>9000</port>
                </replica>
            </shard>

            <shard>
                <weight>1</weight>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>TimeMachine03</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>TimeMachine04</host>
                    <port>9000</port>
                </replica>
            </shard>

        </cluster_1st>
    </clickhouse_remote_servers>

```

I created one distributed table on TimeMachine01 , and 4 local tables on each node(on node one table).  Then i inserted data into the distributed table, and run `SELECT count(*) FROM each local table`.  The result is no surprise, two tables contain data(each one contains half of the data), and the other two contains no data.

BUT!!! BUT!!  HERE IS THE FUNNY THING:
 WHEN I run `SELECT count(*) FROM the distributed table`, the results vary.
here is the code: 

```
TimeMachine01 :) SELECT count(*) FROM default.bank_dist

SELECT count(*)
FROM default.bank_dist 

┌─count()─┐
│   13853 │
└─────────┘

1 rows in set. Elapsed: 0.005 sec. Processed 13.85 thousand rows, 13.85 KB (2.62 million rows/s., 2.62 MB/s.) 

TimeMachine01 :) SELECT count(*) FROM default.bank_dist

SELECT count(*)
FROM default.bank_dist 

┌─count()─┐
│   27595 │
└─────────┘

1 rows in set. Elapsed: 0.006 sec. Processed 27.59 thousand rows, 27.59 KB (4.60 million rows/s., 4.60 MB/s.) 

```

Sometimes its the total counts, but sometimes it's the half........................I run the same snytax 10 times, 3 are different and wrong result.
What the fuck happened?

**Comment by den-crane** [comment]
>and the other two contains no data.

Seems you do not use replicated tables so your replicas do not have data at all, or replication does not work because of misconfiguration. 
If you did not use zookeeper and Replicated* table Engines you should set internal_replication = false and insert data via the distributed table.

**Comment by Tasselmi** [comment]
> > and the other two contains no data.
> 
> Seems you do not use replicated tables so your replicas do not have data at all, or replication does not work because of misconfiguration.
> If you did not use zookeeper and Replicated* table Engines you should set internal_replication = false and insert data via the distributed table.

so if internal_replication=true and no use of zookeeper , there is highly prob. of mistakes.
BUT this makes me confused , if one of the nodes broke and  before the break data was inserted into one replica and after the break data was inserted into the other replica, when I query distributed table, it is reasonable there is mistakes .   But when no node is broken , why there is mistakes,?  

I am just testing how the replica works when internal_replication=true or false. 
But I think it is not reasonable here . because no node is broken , two nodes contains data and the other two contain no data , the logic is simple.

**Comment by den-crane** [comment]
If you do not use Zookeeper and ReplicatedMergeTree table engines you MUST set internal_replication = false.

https://clickhouse.yandex/docs/en/operations/table_engines/distributed/
_If it is set to 'false' (the default), data is written to all replicas. In essence, this means that the Distributed table replicates data itself. This is worse than using replicated tables, because the consistency of replicas is not checked, and over time they will contain slightly different data._

**Comment by Tasselmi** [comment]
> If you do not use Zookeeper and ReplicatedMergeTree table engines you MUST set internal_replication = false.
> 
> https://clickhouse.yandex/docs/en/operations/table_engines/distributed/
> _If it is set to 'false' (the default), data is written to all replicas. In essence, this means that the Distributed table replicates data itself. This is worse than using replicated tables, because the consistency of replicas is not checked, and over time they will contain slightly different data._

so  there is only two solutions:
1. internal_replication=false
2.internal_replication=true and using zookeeper to sync replicas 
and 2 is better than 1.
thanks.

**Comment by alesapin** [comment]
@den-crane Thanks for help)
