### ISSUE TITLE
Long Strings processing performance degradation in CH 18.12+

### ISSUE THREAD

**Issue by den-crane** [yandex/ClickHouse#3499]
Connected to ClickHouse server version 18.14.10 revision 54409.

"Macros" CREATE_INSERT:
create table xxxx (row String) engine=Memory;
insert into xxxx(row) select arrayStringConcat( arrayMap(x -> 'x'||toString(x)||':"'||toString(9999999)||'"',range(3000)), ',' )||',"test":"111",' from numbers(100000);

1. set max_block_size=65536;
2. CREATE_INSERT
3. select  1 from xxxx where row like '%test:0%'
   **0 rows in set. Elapsed: 4.383 sec**
   Processed 100.00 thousand rows, 4.69 GB (22.81 thousand rows/s., 1.07 GB/s.) 
4. set max_block_size=5000;
   select  1 from xxxx where row like '%test:0%'
   0 rows in set. Elapsed: 4.546 sec
5. drop table xxxx;

6. exit / enter CH client
   **set max_block_size=5000;**
   CREATE_INSERT;
7. select  1 from xxxx where row like '%test:0%'
   **0 rows in set. Elapsed: 0.963 sec.**   
8. set max_block_size=65536;
   select  1 from xxxx where row like '%test:0%';
   0 rows in set. Elapsed: 1.061 sec.

**Comment by den-crane** [comment]
The same server, downgrade to ClickHouse version 18.10.3.
select 1 from xxxx where row like '%test:0%'
**0 rows in set. Elapsed: 0.691 sec.**

@KochetovNicolai is it somehow connected to LowCardinality ?

**Comment by den-crane** [comment]
fixed in 18.14.13 ?

Connected to ClickHouse server version 18.14.13 revision 54409.

SELECT 1 FROM xxxx WHERE row LIKE '%test:0%'

0 rows in set. Elapsed: 0.697 sec. Processed 100.00 thousand rows, 4.69 GB (143.42 thousand rows/s., 6.73 GB/s.)

**Comment by alexey-milovidov** [comment]
https://github.com/yandex/ClickHouse/pull/3530
