### ISSUE TITLE
Date and DateTime are limited by 2105

### ISSUE THREAD

**Issue by TimonKK** [yandex/ClickHouse#3507]
Hi,
I have dates that are over 2105 years old. How can I get around this limitation? And is there any hope that it will be removed or extended?

**Comment by den-crane** [comment]
I suppose new datatypes can be implemented -- Date64, DateTime128 :)

**Comment by filimonov** [comment]
> I suppose new datatypes can be implemented -- Date64, DateTime128 :)
it's not so easy as Clickhouse uses lookup tables for date time manipulations (like one record per day), to fill such a lookup table for Date64 a lot of memory can be needed... :) 

Probably the most straight-ahead way is either to store timestamps as some one big numbers, and do presentation layer outside.

If you need also to make some datetime magic on clickhouse side you will need to create special columns for that, or use some calculations.

offtopic: you have some long-term plans? :)

**Comment by TimonKK** [comment]
I have a payment end date in the analyst. And it can be more than 2105th year for some "eternal" tariffs. I did not come up with this, but I need to build reports on this parameter.
Thanks for advice about Int64, I will try it

**Comment by alexey-milovidov** [comment]
Postponed.
