### ISSUE TITLE
distributed table on unoin all  erro  is bug ??

### ISSUE THREAD

**Issue by Jessica4j** [yandex/ClickHouse#3541]
table a is distributed , table b is distributed .
select c1 as c  from  a  unoin all select c1 as c  from   b where b.c2 =3 

select c1 as c  from   b where b.c2 =3   => count = 0 ;
**show erro  :  because it is non constant in source stream but must be constant in result**

**Comment by 4ertus2** [comment]
Hi,

Could you attach here 'show create' for the tables, remote_servers section in your config.xml and minimal insert + select sample to reproduce the issue?

**Comment by filimonov** [comment]
I think it's the duplicate of https://github.com/yandex/ClickHouse/issues/2507
and reporter provide no useful information, so closing this one.

Let's continue in #2507
