### ISSUE TITLE
Can't build ClickHouse on mac 10.14

### ISSUE THREAD

**Issue by aleh-null** [yandex/ClickHouse#3546]
When following [instructions](https://clickhouse.yandex/docs/en/development/build_osx/), after running `ninja` the build fails with:
```
...
In file included from ../dbms/src/Core/Row.h:6,
                 from ../dbms/src/DataStreams/GraphiteRollupSortedBlockInputStream.h:5,
                 from ../dbms/src/DataStreams/GraphiteRollupSortedBlockInputStream.cpp:1:
../dbms/src/Core/Field.h: In instantiation of 'decltype(auto) DB::nearestFieldType(T&&) [with T = long int&]':
../dbms/src/Core/Field.h:630:35:   required from 'DB::Field::Field(T&&, std::enable_if_t<(! is_same_v<typename std::decay<_Tp>::type, DB::Field>), void*>) [with T = long int&; std::enable_if_t<(! is_same_v<typename std::decay<_Tp>::type, DB::Field>), void*> = void*]'
../dbms/src/DataStreams/GraphiteRollupSortedBlockInputStream.cpp:254:65:   required from here
../dbms/src/Core/Field.h:613:63: error: invalid use of incomplete type 'struct DB::NearestFieldType<long int>'
     using U = typename NearestFieldType<std::decay_t<T>>::Type;
                                                               ^
../dbms/src/Core/Field.h:581:30: note: declaration of 'struct DB::NearestFieldType<long int>'
 template <typename T> struct NearestFieldType;
                              ^~~~~~~~~~~~~~~~
[769/3289] Building CXX object dbms/CMakeFiles/dbm...r/src/DataStreams/IProfilingBlockInputStream.cpp.o
ninja: build stopped: subcommand failed.
```
I'm building from master and according to `cmake` it's ClickHouse 18.14.9.

**Comment by trK54Ylmz** [comment]
Same problem

**Comment by proller** [comment]
fix : https://github.com/yandex/ClickHouse/pull/3545/files#diff-bc4722bf5d3b20b34d99c8dfb48f87f7R588

**Comment by aleh-null** [comment]
@proller 
Tried to build from PR same issue in a different place ```
In file included from ../dbms/src/DataTypes/IDataType.h:6,
                 from ../dbms/src/Core/NamesAndTypes.h:9,
                 from ../dbms/src/Interpreters/Context.h:16,
                 from ../dbms/src/Interpreters/DDLWorker.h:2,
                 from ../dbms/src/Interpreters/DDLWorker.cpp:1:
../dbms/src/Core/Field.h: In instantiation of 'decltype(auto) DB::nearestFieldType(T&&) [with T = long unsigned int]':
../dbms/src/Core/Field.h:633:35:   required from 'DB::Field::Field(T&&, std::enable_if_t<(! is_same_v<typename std::decay<_Tp>::type, DB::Field>), void*>) [with T = long unsigned int; std::enable_if_t<(! is_same_v<typename std::decay<_Tp>::type, DB::Field>), void*> = void*]'
../dbms/src/Interpreters/DDLWorker.cpp:1071:77:   required from here
../dbms/src/Core/Field.h:616:63: error: invalid use of incomplete type 'struct DB::NearestFieldType<long unsigned int>'
     using U = typename NearestFieldType<std::decay_t<T>>::Type;
                                                               ^
../dbms/src/Core/Field.h:581:30: note: declaration of 'struct DB::NearestFieldType<long unsigned int>'
 template <typename T> struct NearestFieldType;
                              ^~~~~~~~~~~~~~~~
[987/3289] Building CXX object dbms/CMakeFiles...bms.dir/src/Dictionaries/CacheDictionary.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by proller** [comment]
Fixed and tested and commited:
https://github.com/yandex/ClickHouse/commit/bb1dafd2b32a3fad288f0d31c0d45d6cdea44f4a
https://github.com/yandex/ClickHouse/commit/9a98b80cf8eafba1ada1baf565d5a1d7bfb93cd5

**Comment by filimonov** [comment]
Relates #235
