### ISSUE TITLE
Kafka engine produces buffers with leading row_delimiters if one is defined

### ISSUE THREAD

**Issue by wawaka** [yandex/ClickHouse#3547]
create a kafka table:
```sql
CREATE TABLE kafka_source (
    s String
) ENGINE = Kafka
SETTINGS
    kafka_broker_list = '...',
    kafka_topic_list = '...',
    kafka_group_name = '...',
    kafka_format = 'TSV',
    kafka_row_delimiter = '\n',
    kafka_schema = '',
    kafka_num_consumers = 1;
```
and start sending messages (just '.') to that kafka topic at a rate of 1 msg every 2 seconds while doing
```sql
select * from kafka_source
```
eventually you will see empty lines among you data ('.')

Apparently this happens because kafka engine sometimes produces buffers with leading row_delimiter which end up being parsed as empty lines.

```
SELECT *
FROM kafka_source

┌─s─┐
│ . │
└───┘
┌─s─┐
│   │
└───┘
┌─s─┐
│ . │
└───┘

3 rows in set. Elapsed: 2.753 sec.
```

version 18.14.12

**Comment by abyss7** [comment]
Can't reproduce on latest master. Is it possible to provide some trivial example using console producer?
