### ISSUE TITLE
I want to know how to take part in the document translation?

### ISSUE THREAD

**Issue by lcy362** [yandex/ClickHouse#3548]
I notice that I can modify the code and submit a merge request, so, is this all? Will anybody check the accuracy?
And is there some group doing the chinese version translation currently?

**Comment by blinkov** [comment]
There are few active ClickHouse users/contributors from China who volunteered to help reviewing docs translation. So yes, just modify, open pull request and we'll ask them to take a look. 

Keep in mind that there are symlinks in zh folder for articles without any translation, so to translate them you need to remove symlink and place plain text file with translated text.
