### ISSUE TITLE
delete mutation doesn't work properly

### ISSUE THREAD

**Issue by hannamonnah** [yandex/ClickHouse#3554]
i have a merge tree table with big data. 
when i execute delete query, it says "0 rows affected".  but records are not deleted.

my table has datetime and id columns and partition by date. 

when i try on little size table, it works.
is it related with size of table or type of data? should i make any change in config.xml or settings? 

thanks in advance..

**Comment by den-crane** [comment]
it works in background and eventually will finish.

check
select * from system.mutations where parts_to_do>0;

**Comment by hannamonnah** [comment]
hi!
my query's filter is "`where toDate(DateTime_value) < today()-5`" and it has suspended for 5 days.
but when i writer filter as "`where toDate(DateTime_value) = '2018-11-12'` " it executed in 10 seconds.
in system.mutations table command column of my filter is shown like "`delete where  toDate(DateTime_value) < '((2018 - 11) -  7 )'` "

what does it mean?

but i execute "`where toDate(DateTime_value) = '2018-11-12'`" filter, it is shown in system.mutations table like "`where toDate(DateTime_value) = '2018-11-12'`"

what is the difference between these two queries?

thanks.

**Comment by den-crane** [comment]
@ztlpn seems a bug in alter delete
today()-5 --->  '((2018 - 11) - 7 )'

**Comment by hannamonnah** [comment]
i found out why this was occurred. i forgot quote with date.

when date is written like 2018-11-7, db transforms ((2018 - 11 ) - 7) 

thanks.
