### ISSUE TITLE
Performance issue of LowCardinality on group-by with multi-keys

### ISSUE THREAD

**Issue by fancyqlx** [yandex/ClickHouse#3562]
Hi. I have tested the performance of LowCardinality feature. I found that the performance has improved a lot when we use group-by with only one key. But if I use multiple keys, the performance did not improve much. For example, I have a query:
`select device_brand, count() from medium group by device_brand, app_name`
where device_brand and app_name are LowCardinality(String) type. I get almost the same running time:

![image](https://user-images.githubusercontent.com/6196299/48310770-45646b00-e5cf-11e8-80f2-f8fe881e28f3.png)
![image](https://user-images.githubusercontent.com/6196299/48310781-64fb9380-e5cf-11e8-9e32-f3daa7a50515.png)

I read the most of the code about the LowCardinality and found it cannot handle the case of group-by with multi-keys in the current version.  The engine selects serialized aggregation method instead of low_cardinality_key_string so that we convert indexes to full column.

I wonder if the LowCardinality will support group-by with multi-keys. And is there any plans for improving LowCardinality since the current version seems not very helpful for many kinds of queries.

**Comment by KochetovNicolai** [comment]
Well, that's a very good question. The case with multiple LowCardinality keys can actually be improved, but it' s more difficult than in case with single key and potential speedup is lower.

There are two main optimizations for GROUP BY LowCardinality, and both of them optimize access to hash table (when for aggregation key we need to find the position of corresponding data):
1. Hash of aggregation key is cached for dictionary. So, when we search in hash table, we don't calculate hash function result, and only need to find corresponding cell.
2. The result of hash table find() function is also cached, and if we have a few different keys in local dictionary, we can mostly skip the hash table step.

For multiple LowCardinality keys the first optimization is partly possible. We still can cache hash function result for each LowCardinality column, and if we use combination of hashes as result hash value, and it's computable fast enough, we can have some profit. 

The second one is much more difficult as soon as the total number of different keys is a multiplication of each column. If it's much less than the total number of rows, it will probably be possible to create similar cache but with two-level address scheme (each dictionary to temporary index, and tuple of temporary indexes to final result). But, we need a fallback in case we have a lot of different tuples.

Right now I can't say when (if) it will be implemented.

**Comment by fancyqlx** [comment]
> Well, that's a very good question. The case with multiple LowCardinality keys can actually be improved, but it' s more difficult than in case with single key and potential speedup is lower.
> 
> There are two main optimizations for GROUP BY LowCardinality, and both of them optimize access to hash table (when for aggregation key we need to find the position of corresponding data):
> 
> 1. Hash of aggregation key is cached for dictionary. So, when we search in hash table, we don't calculate hash function result, and only need to find corresponding cell.
> 2. The result of hash table find() function is also cached, and if we have a few different keys in local dictionary, we can mostly skip the hash table step.
> 
> For multiple LowCardinality keys the first optimization is partly possible. We still can cache hash function result for each LowCardinality column, and if we use combination of hashes as result hash value, and it's computable fast enough, we can have some profit.
> 
> The second one is much more difficult as soon as the total number of different keys is a multiplication of each column. If it's much less than the total number of rows, it will probably be possible to create similar cache but with two-level address scheme (each dictionary to temporary index, and tuple of temporary indexes to final result). But, we need a fallback in case we have a lot of different tuples.
> 
> Right now I can't say when (if) it will be implemented.

Thanks for your reply. I will continue to pay attention to this feature and look forward to your progress in the future.
