### ISSUE TITLE
on cluster error 

### ISSUE THREAD

**Issue by RustRw** [yandex/ClickHouse#3566]
echo 'alter table dw.dim_davinci_app_cate_wandoujia_local on cluster wkdata_ck_cluster delete where pt = '\''2018-11-06'\''' | clickhouse-client --host xxxx --user xxx --password xxx --database=dw
Received exception from server (version 18.10.3):
Code: 291. DB::Exception: Received from 172.18.0.203:9000. DB::Exception: Access denied to database **dim_davinci_app_cate_wandoujia_local**.

**Comment by 4ertus2** [comment]
It was fixed in master one ot two weeks ago. You need a newer release.
