### ISSUE TITLE
int overflow when parsing min int

### ISSUE THREAD

**Issue by andreyfedorov** [yandex/ClickHouse#3569]
https://github.com/yandex/ClickHouse/blob/03c35f2aa4cf425c6778db8d8c771c343d1bd18f/libs/libmysqlxx/src/Value.cpp#L57

int overflow if you are trying to parse int_min

**Comment by alexey-milovidov** [comment]
Confirmed.

**Comment by amosbird** [comment]
Isn't that deliberately allowed? https://github.com/yandex/ClickHouse/blob/master/dbms/src/IO/ReadHelpers.h#L304

**Comment by alexey-milovidov** [comment]
Yes. But it will confuse compiler. And all tests should pass under UBSan (currently they don't; and we don't have autotests with UBSan).

**Comment by alexey-milovidov** [comment]
We can avoid it in two possible ways:
1. Add `__attribute__((optimize("fwrapv")))` for function.
2. Parse in unsigned type. Then cast to signed, perform a branch for min int, invert. Or invert via bit not and plus one, and then do bit_cast.

**Comment by amosbird** [comment]
+1 to `__attribute__((optimize("fwrapv")))` . It's very descriptive.

**Comment by alexey-milovidov** [comment]
UBSan have a suggestion for us:

```
test.cpp:3:9: runtime error: negation of -2147483648 cannot be represented in type 'int'; cast to an unsigned type to negate this value to itself
```

C++ supports negate operator for unsigned types, that do exactly what we need without UB.

**Comment by alexey-milovidov** [comment]
```
milovidov@milovidov-Latitude-E7470:~/work/ClickHouse$ cat test.cpp
void __attribute__((__noinline__)) f(int & x)
{
    x = -x;
}

void __attribute__((__noinline__)) g(int & x)
{
    x = ~x + 1;
}

void __attribute__((__noinline__)) h(int & x)
{
    x = -static_cast<unsigned>(x);
}

#include <limits>
#include <iostream>

int main()
{
    int x = std::numeric_limits<int>::min();
    std::cerr << x << '\n';
    g(x);
    std::cerr << x << '\n';
    f(x);
    std::cerr << x << '\n';
    h(x);
    std::cerr << x << '\n';
    return 0;
}
milovidov@milovidov-Latitude-E7470:~/work/ClickHouse$ clang++ -O3 -fsanitize=undefined test.cpp 
milovidov@milovidov-Latitude-E7470:~/work/ClickHouse$ ./a.out 
-2147483648
test.cpp:8:12: runtime error: signed integer overflow: 2147483647 + 1 cannot be represented in type 'int'
-2147483648
test.cpp:3:9: runtime error: negation of -2147483648 cannot be represented in type 'int'; cast to an unsigned type to negate this value to itself
-2147483648
-2147483648
```

Third function works fine. The machine code is identical in all three cases.

**Comment by alexey-milovidov** [comment]
Fixed in master.

Please note that this bug actually had no effect.
