### ISSUE TITLE
Segmentation fault on 18.14.13, 18.14.10

### ISSUE THREAD

**Issue by EvgenyVinogradov** [yandex/ClickHouse#3585]
Clickhouse v.18.14.13 crashed by Segmentation fault (11) on intensive data loading into ReplicatedMergeTree table. 
Call-stack:
2018.11.15 11:47:22.623746 [ 2 ] {} <Error> BaseDaemon: ########################################
2018.11.15 11:47:22.623803 [ 2 ] {} <Error> BaseDaemon: (from thread 243) Received signal Segmentation fault (11).
2018.11.15 11:47:22.623821 [ 2 ] {} <Error> BaseDaemon: Address: 0x310bb
2018.11.15 11:47:22.623838 [ 2 ] {} <Error> BaseDaemon: Access: read.
2018.11.15 11:47:22.623854 [ 2 ] {} <Error> BaseDaemon: Address not mapped to object.
2018.11.15 11:47:22.658215 [ 2 ] {} <Error> BaseDaemon: 0. clickhouse-server(DB::ColumnNullable::checkConsistency() const+0x15) [0x5041235]
2018.11.15 11:47:22.658254 [ 2 ] {} <Error> BaseDaemon: 1. clickhouse-server(DB::DataTypeNullable::serializeBinaryBulkWithMultipleStreams(DB::IColumn const&, unsigned long, unsigned long, DB::IDataType::SerializeBinaryBulkSettings&, std::shared_ptr<DB::IDataType::SerializeBinaryBulkState>&) const+0x31) [0x4560101]
2018.11.15 11:47:22.658270 [ 2 ] {} <Error> BaseDaemon: 2. clickhouse-server(DB::IMergedBlockOutputStream::writeData(std::string const&, DB::IDataType const&, DB::IColumn const&, std::set<std::string, std::less<std::string>, std::allocator<std::string> >&, bool, std::shared_ptr<DB::IDataType::SerializeBinaryBulkState>&)+0x2f5) [0x51bdbb5]
2018.11.15 11:47:22.658285 [ 2 ] {} <Error> BaseDaemon: 3. clickhouse-server(DB::MergedBlockOutputStream::writeImpl(DB::Block const&, DB::PODArray<unsigned long, 4096ul, Allocator<false>, 15ul> const*)+0x7ad) [0x51be5ed]
2018.11.15 11:47:22.658295 [ 2 ] {} <Error> BaseDaemon: 4. clickhouse-server(DB::MergeTreeDataWriter::writeTempPart(DB::BlockWithPartition&)+0xa23) [0x519d853]
2018.11.15 11:47:22.658318 [ 2 ] {} <Error> BaseDaemon: 5. clickhouse-server(DB::ReplicatedMergeTreeBlockOutputStream::write(DB::Block const&)+0x55f) [0x51ca65f]
2018.11.15 11:47:22.658328 [ 2 ] {} <Error> BaseDaemon: 6. clickhouse-server(DB::PushingToViewsBlockOutputStream::write(DB::Block const&)+0x3b) [0x52ee94b]
2018.11.15 11:47:22.658338 [ 2 ] {} <Error> BaseDaemon: 7. clickhouse-server(DB::SquashingBlockOutputStream::finalize()+0x101) [0x52f5f01]
2018.11.15 11:47:22.658348 [ 2 ] {} <Error> BaseDaemon: 8. clickhouse-server(DB::SquashingBlockOutputStream::writeSuffix()+0x11) [0x52f6171]
2018.11.15 11:47:22.658362 [ 2 ] {} <Error> BaseDaemon: 9. clickhouse-server(DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::atomic<bool>*)+0x49b) [0x44f889b]
2018.11.15 11:47:22.658379 [ 2 ] {} <Error> BaseDaemon: 10. clickhouse-server(DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::function<void (std::string const&)>)+0x1b7) [0x4ff8c07]
2018.11.15 11:47:22.658392 [ 2 ] {} <Error> BaseDaemon: 11. clickhouse-server(DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&)+0x31f4) [0x2998194]
2018.11.15 11:47:22.658403 [ 2 ] {} <Error> BaseDaemon: 12. clickhouse-server(DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)+0x3c9) [0x299a649]
2018.11.15 11:47:22.658412 [ 2 ] {} <Error> BaseDaemon: 13. clickhouse-server(Poco::Net::HTTPServerConnection::run()+0x23e) [0x5748e3e]
2018.11.15 11:47:22.658422 [ 2 ] {} <Error> BaseDaemon: 14. clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x5744ddf]
2018.11.15 11:47:22.658432 [ 2 ] {} <Error> BaseDaemon: 15. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x110) [0x5745440]
2018.11.15 11:47:22.658441 [ 2 ] {} <Error> BaseDaemon: 16. clickhouse-server(Poco::PooledThread::run()+0x77) [0x57fad87]
2018.11.15 11:47:22.658450 [ 2 ] {} <Error> BaseDaemon: 17. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x57f80e8]
2018.11.15 11:47:22.658459 [ 2 ] {} <Error> BaseDaemon: 18. clickhouse-server() [0x5c7c19f]
2018.11.15 11:47:22.658468 [ 2 ] {} <Error> BaseDaemon: 19. /lib64/libpthread.so.0(+0x7e25) [0x7f365227ce25]

**Comment by EvgenyVinogradov** [comment]
both tables has a same structure described below:
CREATE TABLE default.ONLINE_LOG_local ( RECORD_ID UInt64,  ENV_ID Nullable(String),  ENV_TIMEIN DateTime,  SAF_PLAN_ID Nullable(String),  TXN_SOURCE Nullable(String),  TXN_MTI Nullable(String),  TXN_F2 Nullable(String),  TXN_F3 Nullable(String),  TXN_F4 Nullable(Int64),  TXN_F5 Nullable(UInt64),  TXN_F6 Nullable(UInt64),  TXN_F7 Nullable(String),  TXN_F9 Nullable(UInt64),  TXN_F10 Nullable(UInt64),  TXN_F11 Nullable(String),  TXN_F12 Nullable(String),  TXN_F13 Nullable(String),  TXN_F14 Nullable(String),  TXN_F15 Nullable(String),  TXN_F16 Nullable(String),  TXN_F18 Nullable(String),  TXN_F22 Nullable(String),  TXN_F23 Nullable(String),  TXN_F25 Nullable(String),  TXN_F28 Nullable(String),  TXN_F32 Nullable(String),  TXN_F33 Nullable(String),  TXN_F35 Nullable(String),  TXN_F37 Nullable(String),  TXN_F38 Nullable(String),  TXN_F39 Nullable(String),  TXN_F41 Nullable(String),  TXN_F42 Nullable(String),  TXN_F43 Nullable(String),  TXN_F44 Nullable(String),  TXN_F45 Nullable(String),  TXN_F48 Nullable(String),  TXN_F49 Nullable(String),  TXN_F50 Nullable(String),  TXN_F51 Nullable(String),  TXN_F52 Nullable(String),  TXN_F53 Nullable(String),  TXN_F55 Nullable(String),  TXN_F60 Nullable(String),  TXN_F61 Nullable(String),  TXN_F62_2 Nullable(String),  TXN_F63_2 Nullable(String),  TXN_F90_1 Nullable(String),  ISSUER_BIN Nullable(String),  ISSUER_ID Nullable(String),  SERVICE_CODE Nullable(String),  ECI_IND Nullable(String),  UCAF_IND Nullable(String),  PIN_IND Nullable(String),  IN_GATE_ID Nullable(String),  OUT_GATE_ID Nullable(String),  IN_NODE_ID Nullable(String),  OUT_NODE_ID Nullable(String),  IN_GATE_TIMEIN DateTime,  IN_GATE_TIMEOUT Nullable(DateTime),  OUT_GATE_TIMEIN Nullable(DateTime),  OUT_GATE_TIMEOUT Nullable(DateTime),  EXPORT_STATUS Nullable(String),  FORMAT_VER Nullable(Int8),  EXTERNAL_SERVICE Nullable(String),  PS_CODE UInt8,  SMS_FLAG Nullable(Int8),  UNLOAD2BO Nullable(Int8),  TXN_F4RU Nullable(Int64),  TXN_F63 Nullable(String),  ISSUER_MEMBER_ID Nullable(String),  ISS_COUNTRY Nullable(String),  ACQ_COUNTRY Nullable(String),  TXN_F48_15 Nullable(String),  TXN_F123 Nullable(String),  TXN_F126_9_1 Nullable(String),  TKN_STATUS Nullable(String),  AFF_FORM_STATUS Nullable(String),  ISS_REJECT Nullable(String),  ACQ_REJECT Nullable(String),  SFM_REQUEST Nullable(String),  SFM_RESPONSE Nullable(String),  SFM_RESULT Nullable(String),  ONUS Nullable(String),  CPD Nullable(DateTime),  TXN_F108 Nullable(String),  TXN_F124 Nullable(String),  RATE_TYPE Nullable(String),  RATE_TYPE_ISSUER Nullable(String),  TXN_F121 Nullable(String),  MIT Nullable(String),  INGATE_DATE Date,  TXN_F2TAN Nullable(String),  RATES_VERSION Nullable(String),  SYS_EDIT_ID Nullable(String),  TXN_F104 Nullable(String),  TXN_F126_13 Nullable(String),  CF_BIN6 Nullable(String) MATERIALIZED substring(TXN_F2, 1, 6),  CF_BIN8 Nullable(String) MATERIALIZED substring(TXN_F2, 1, 8),  CF_MERCHANT_NAME Nullable(String) MATERIALIZED multiIf(PS_CODE IN (2, 4), upper(substring(TXN_F43, 1, 25)), upper(substring(TXN_F43, 1, 22))),  CF_MERCHANT_CITY Nullable(String) MATERIALIZED multiIf(PS_CODE IN (2, 4), upper(substring(TXN_F43, 26, 13)), upper(substring(TXN_F43, 24, 13))),  CF_POSTAL_CODE String MATERIALIZED multiIf(PS_CODE IN (2, 4), '-1', PS_CODE IN (0, 1, 3), ifNull(replaceRegexpOne(replaceRegexpOne(substring(TXN_F61, 17, 6), '^s+', ''), 's+$', ''), '-1'), ifNull(replaceRegexpOne(replaceRegexpOne(substring(TXN_F61, 10, 6), '^s+', ''), 's+$', ''), '-1')),  CF_PROCESSING_CODE Nullable(String) MATERIALIZED substring(TXN_F3, 1, 2),  CF_POS_ENTRY_MODE Nullable(String) MATERIALIZED substring(TXN_F22, 1, 2),  CF_IS_DECLINED Nullable(String) MATERIALIZED CAST(multiIf(TXN_F39 NOT IN ('00', '85'), 'Y', 'N'), 'Nullable(String)'),  CF_IS_DIRECT Nullable(String) MATERIALIZED CAST(multiIf(TXN_MTI IN ('0100', '0101', '0200'), 'Y', 'N'), 'Nullable(String)'),  CF_IS_ISSUER_RESPONSE Nullable(String) MATERIALIZED CAST(multiIf((EXTERNAL_SERVICE NOT IN ('A', 'S')) AND isNotNull(OUT_GATE_ID), 'Y', 'N'), 'Nullable(String)')) ENGINE = ReplicatedMergeTree('/clickhouse/tables/01/MIR_ONLINE_LOG_DAY_local', '<ipaddr>') PARTITION BY toYYYYMMDD(IN_GATE_TIMEIN) ORDER BY (ENV_TIMEIN, PS_CODE, RECORD_ID) SETTINGS index_granularity = 8192

**Comment by abyss7** [comment]
Is it a new load workflow or have you updated to the new version? Do you have any stable version number which doesn't reproduce the bug?

**Comment by abyss7** [comment]
Can you tell if you built the server from source or installed the .deb from public repo?

**Comment by abyss7** [comment]
Also if it's possible can you provide a sample of the most probable queries that may lead to segmentation fault?

**Comment by EvgenyVinogradov** [comment]
18.12.17 is not crashing by SegFault
All builds I assembling as RPMs by my self. OS - ContOS 7
Queries that leads SegFault are so easy and selecting max(RECORD_ID) value from default.ONLINE_LOG_local

I guess problems are related to calculated fields. I'll try to upgrade to 18.14.13, drop calculated fields and reload table in few hours. I will inform about the results.

**Comment by filimonov** [comment]
Can you also try Altinity builds? https://packagecloud.io/Altinity/clickhouse (build scripts are there https://github.com/Altinity/clickhouse-rpm )

**Comment by alexey-milovidov** [comment]
You can help if you share results of `addr2line` for addresses from the stack trace. Example:

`addr2line -iCe /usr/bin/clickhouse 0x5041235`

(the stack trace should correspond to the version installed)
