### ISSUE TITLE
Selecting aggregating function state from subquery fails

### ISSUE THREAD

**Issue by podshumok** [yandex/ClickHouse#3590]
Hi!

here is an example:

```sql
SELECT 
    (
        SELECT uniqState('')
    )
```

```response
Received exception from server (version 18.12.17):
Code: 70. DB::Exception: Received from click:9000, 127.0.0.1. DB::Exception: Conversion from String to AggregateFunction(uniq, String) is not supported. 
```

**Comment by abyss7** [comment]
We decided to forbid such kind of subqueries with AggregateFunction states - as a workaround your query may be simply transformed to another one:

    SELECT * FROM ( SELECT uniqState('') )

**Comment by podshumok** [comment]
I wanned to use this subquery in ALTER TABLE statement to add a new column to AggregatingMergeTree table.

@alexey-milovidov  showed me another way to achieve this via `arrayReduce('uniqState', CAST([] AS Array(String)))`

but in the end I still had to recreate table and populate it with `INSERT ... SELECT *, new_field FROM ...`

**Comment by abyss7** [comment]
PR #3865
