### ISSUE TITLE
ALTER Enum field with condition failed

### ISSUE THREAD

**Issue by 5cmpersec** [yandex/ClickHouse#3591]
- Problem: ALTER command fails on Enum8 fields if specify a condition in WHERE
- Expected: ALTER with a condition should not fail
- Occurrence rate: always
- Server version: 18.14.12 revision 54409
- Client version: 18.14.13

- Reprocedure:

`CREATE TABLE t (d Date, e Enum8('foo'=1, 'bar'=2)) Engine = MergeTree(d, (d), 8192);`
`INSERT INTO t (d, e) VALUES ('2018-01-01', 'foo');`
`INSERT INTO t (d, e) VALUES ('2018-01-02', 'bar');`

`ALTER TABLE t UPDATE e = CAST('foo', 'Enum8(\'foo\' = 1, \'bar\' = 2)') WHERE d='2018-01-02'`

> Code: 44. DB::Exception: Received from localhost:9000, 10.0.0.111. DB::Exception: Illegal columns Const(Int8) and Int8 of second (then) and third (else) arguments of function if.

`ALTER TABLE t UPDATE e = CAST('foo', 'Enum8(\'foo\' = 1, \'bar\' = 2)') WHERE 1`

> Ok.

Please help to check this.

Thanks.

**Comment by abyss7** [comment]
PR #3875
