### ISSUE TITLE
Why I cannot specify the partition value in select?

### ISSUE THREAD

**Issue by q0987** [yandex/ClickHouse#3595]
ClickHouse client version 18.6.0.
Connected to ClickHouse server version 18.6.0 revision 54401.

:) select partition,name,database,table from system.parts where table='MyTable' and database='default'

SELECT
    partition,
    name,
    database,
    table
FROM system.parts
WHERE (table = 'MyTable') AND (database = 'default')

┌─partition────┬─name─────────────────┬─database─┬─table─────┐
│ '2018-11-13' │ 20181113_6321_6329_1 │ default  │ MyTable │
│ '2018-11-13' │ 20181113_6331_6337_1 │ default  │ MyTable │
│ '2018-11-13' │ 20181113_6338_6358_2 │ default  │ MyTable │
└──────────────┴──────────────────────┴──────────┴───────────┘

3 rows in set. Elapsed: 0.005 sec.

 :) select partition,name,database,table from system.parts where table='MyTable' and database='default' and partition='2018-11-13'

SELECT
    partition,
    name,
    database,
    table
FROM system.parts
WHERE (table = 'MyTable') AND (database = 'default') AND (partition = '2018-11-13')

Ok.

0 rows in set. Elapsed: 0.004 sec.

Question> Why I cannot specify the partition name in the select statement? What is the correct value for the partition of '2018-11-13'?

Thank you

**Comment by den-crane** [comment]
Why do you need it? 

You can https://clickhouse.yandex/docs/en/changelog/#new-features_3 
Tables in the MergeTree family now have the virtual column _partition_id

BUT:

create table foo (a Int64, b String, X String) engine=MergeTree partition by (a%2, b) order by X;
insert into foo values(1,'A','A'), (1,'B','B');
select partition, name from system.parts where table = 'foo'

partition | name
-- | --
(1, 'B') | 0e86ce951f9de01c08639aa81680f857_2_2_0
(1, 'A') | 6944a781bc9c7cf8a184979de860c391_1_1_0

select * from foo where _partition_id = '6944a781bc9c7cf8a184979de860c391';

a | b | X
-- | -- | --
1 | A | A

**Comment by den-crane** [comment]
AND (partition = '\'2018-11-13\'')

**Comment by q0987** [comment]
It works now.
Thank you
