### ISSUE TITLE
add toStartOfWeek function

### ISSUE THREAD

**Issue by blackbass1988** [yandex/ClickHouse#36]
Hi!

Can you add *toStartOfWeek* function? 

Behavior of this function is similar to toStartOfMonth, 
but I want that function returns truncated to monday's date.

example : 

toStartOfWeek(2016-06-28, 0) -> 2016-06-26
toStartOfWeek(2016-06-23, 1) -> 2016-06-20

here is first argument is a date
second argument is a first day week (sunday, monday ...)

**Comment by blackbass1988** [comment]
toMonday exists

**Comment by alexey-milovidov** [comment]
BTW it is intentionally named `toMonday`, not `toStartOfWeek`, because there are different rules about at what day week starts.
