### ISSUE TITLE
Optimize table final causes `Unknown log entry type: 0` on replicated tables

### ISSUE THREAD

**Issue by the-tinderbox** [yandex/ClickHouse#3611]
Trying to execute `optimize table table_name final` on server 18.12.17 version and it causes error on another replica: 

```
Code: 49. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Received from cl-01.fakedomain.org:9000, 10.66.0.21. DB::Exception: Unknown log entry type: 0.
```

It works on any ReplicatedMergeTree table. Simple `otimize table table_name` work, but not with `final` statement in query.

**Comment by vglocus** [comment]
Having the same issue.

`OPTIMIZE TABLE fake_table_1d_local_10 FINAL;
Received exception from server (version 18.14.9):
Code: 49. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Received from <remote_replica_host>:9000, 10.173.42.1. DB::Exception: Unknown log entry type: 0.`

**Comment by alexey-milovidov** [comment]
CC @amosbird 

I cannot reproduce the issue in a simple use case:
```
CREATE TABLE test.replicated_numbers (k UInt64, x UInt64) ENGINE = ReplicatedMergeTree('/clickhouse/tables/test/replicated_numbers', 'r1') PARTITION BY k ORDER BY x;
CREATE TABLE test.replicated_numbers_2 (k UInt64, x UInt64) ENGINE = ReplicatedMergeTree('/clickhouse/tables/test/replicated_numbers', 'r2') PARTITION BY k ORDER BY x;
SET min_insert_block_size_rows = 0, min_insert_block_size_bytes = 0;
INSERT INTO test.replicated_numbers SELECT number % 100, number FROM numbers(1000000);
OPTIMIZE TABLE test.replicated_numbers FINAL;
```

This is related to #2604. The code in #2604 have minor issues (log entries are created not in a single transaction; we are waiting to just single log entry) but I cannot figure out how this issue can happen.

**Comment by den-crane** [comment]
I can reproduce it with 100% probability.
ClickHouse server version 18.14.18 revision 54409.

```
not sure is it important or not
ping zoo1
.
64 bytes from 10.249.101.2: icmp_seq=1 ttl=62 time=5.73 ms
64 bytes from 10.249.101.2: icmp_seq=2 ttl=62 time=5.12 ms
```
on 2 servers:
CREATE TABLE opt_test(t   Int32)
ENGINE = ReplicatedReplacingMergeTree ('/clickhouse/{cluster}/tables/opt_test','{replica}') order by tuple();

```
cat test.sql
truncate table opt_test;
insert into dw.opt_test select 999 from numbers(20);
optimize table opt_test final;
```

execute on non-leader
```
cat test.sql |clickhouse-client -mn
Received exception from server (version 18.14.18):
Code: 49. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Received from chdw1-1.sde317.mycmdb.net:9000, 10.252.35.2. DB::Exception: Unknown log entry type: 0.
```

Workaround [sleep(1)]

```
cat Workaround.sql
truncate table opt_test;
insert into dw.opt_test select 999 from numbers(20);
select sleep(1);
optimize table opt_test final;
```

**Comment by moxiaofan9** [comment]
Having the same issue. 
 Clickhouse verision 18.14.13 & 18.14.19.
I can reproduce it with 100% probability.

**Comment by amosbird** [comment]
@den-crane can you reproduce it without `final`. The only difference I can see here is `final` will select the only part to merge which might not exist on the leader server. @alexey-milovidov This doesn't look like a  transaction issue as we are still creating only one log entry.

**Comment by den-crane** [comment]
@amosbird everything works fine without final.

And I execute optimize final at the non-leader host localhost and error reports about the leader XXXX
Received from localhost:9000, ::1. DB::Exception: Received from XXXX DB::Exception: Unknown log entry type: 0.


```
| => cat test_final.sql |clickhouse-client -mn
Received exception from server (version 18.14.18):
Code: 49. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Received from xxxx. DB::Exception: Unknown log entry type: 0.
| => cat test_final.sql |clickhouse-client -mn
Received exception from server (version 18.14.18):
Code: 49. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Received from xxxx. DB::Exception: Unknown log entry type: 0.
| => cat test_final.sql |clickhouse-client -mn
Received exception from server (version 18.14.18):
Code: 49. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Received from xxxx. DB::Exception: Unknown log entry type: 0.

| => cat test_non_final.sql |clickhouse-client -mn
| => cat test_non_final.sql |clickhouse-client -mn
| => cat test_non_final.sql |clickhouse-client -mn

| => cat test_final.sql |clickhouse-client -mn
Received exception from server (version 18.14.18):
Code: 49. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Received from xxxx. DB::Exception: Unknown log entry type: 0.

| => cat test_non_final.sql |clickhouse-client -mn

| => cat test_final.sql |clickhouse-client -mn
Received exception from server (version 18.14.18):
Code: 49. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Received from xxxx. DB::Exception: Unknown log entry type: 0.

```

**Comment by amosbird** [comment]
can you try doing twice insert to generate two parts?

```
cat test.sql
truncate table opt_test;
insert into dw.opt_test select 999 from numbers(20);
insert into dw.opt_test select 999 from numbers(20);
optimize table opt_test final;
```

**Comment by den-crane** [comment]
The same```

| => cat test.sql
truncate table opt_test;
insert into dw.opt_test select 999 from numbers(20);
insert into dw.opt_test select 999 from numbers(20);
optimize table opt_test final;

| => cat test.sql |clickhouse-client -mn
Received exception from server (version 18.14.18):
Code: 49. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Received from  DB::Exception: Unknown log entry type: 0.

| => cat test.sql |clickhouse-client -mn
Received exception from server (version 18.14.18):
Code: 49. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Received from  DB::Exception: Unknown log entry type: 0.

| => cat test.sql |clickhouse-client -mn
Received exception from server (version 18.14.18):
Code: 49. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Received from  DB::Exception: Unknown log entry type: 0.

| => cat test.sql |clickhouse-client -mn
Received exception from server (version 18.14.18):
Code: 49. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Received from  DB::Exception: Unknown log entry type: 0.

| => cat test.sql |clickhouse-client -mn
Received exception from server (version 18.14.18):
Code: 49. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Received from  DB::Exception: Unknown log entry type: 0.

```

**Comment by den-crane** [comment]
Hm. Magic sleep.

```
| => cat test.sql
truncate table opt_test;
insert into dw.opt_test select 999 from numbers(20);
select sleep(1);
insert into dw.opt_test select 999 from numbers(20);
optimize table opt_test final;
```
```


| => cat test.sql |clickhouse-client -mn
0

| => cat test.sql |clickhouse-client -mn
0

| => cat test.sql |clickhouse-client -mn
0

| => cat test.sql |clickhouse-client -mn
0

| => cat test.sql |clickhouse-client -mn
0

```

**Comment by den-crane** [comment]
```
| => cat test.sql
truncate table opt_test;
insert into dw.opt_test select 999 from numbers(20);
select sleep(1);
insert into dw.opt_test select 666 from numbers(2);
optimize table opt_test final;
```
| => cat test.sql |clickhouse-client -mn
0

| => cat test.sql |clickhouse-client -mn
0

**Comment by den-crane** [comment]
```
cat test.sql
truncate table opt_test;
select sleep(1);
insert into dw.opt_test select 999 from numbers(20);
optimize table opt_test final;

| => cat test.sql |clickhouse-client -mn
0
Received exception from server (version 18.14.18):
Code: 49. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Received from XXX DB::Exception: Unknown log entry type: 0.
```

**Comment by amosbird** [comment]
So it seems when the table is initially empty and when the first part gets created and immediately being remerged, the leader get confused of an empty table having a part to merge.

**Comment by amosbird** [comment]
@den-crane can you try this pr  https://github.com/yandex/ClickHouse/pull/4683
