### ISSUE TITLE
Drop X- prefix from X-ClickHouse-Progress header

### ISSUE THREAD

**Issue by simPod** [yandex/ClickHouse#3613]
We should drop `X-` prefix from `X-ClickHouse-Progress` header based on IETF RFC https://tools.ietf.org/html/rfc6648

The document suggests

```
   Creators of new parameters to be used in the context of application
   protocols:

   1.  SHOULD assume that all parameters they create might become
       standardized, public, commonly deployed, or usable across
       multiple implementations.

   2.  SHOULD employ meaningful parameter names that they have reason to
       believe are currently unused.

   3.  SHOULD NOT prefix their parameter names with "X-" or similar
       constructs.
```

I propose simply `ClickHouse-Progress`

**Comment by filimonov** [comment]
Avoiding X- prefixes is just a 'best practice' / 'recommendation', not a hard rule. 

Changing is a bad idea, as will broke backward compatibility. But it's easy to make it configurable.

Generally those header are kinda controversial : streaming headers is not something normal for HTTP exchange, and usually you need to hack your HTTP client to make the steaming read of HTTP headers work. Even poco was hacked to make it possible to send them in steaming mode. 
https://github.com/yandex/ClickHouse/blob/0eed697623afd251c1908073c4a2850a9bfc9cdc/dbms/src/IO/WriteBufferFromHTTPServerResponse.cpp#L168-L170

So if you are coding ClickHouse client in multiprocess / multithread environment it's much clearer just to open one more connection and query `SELECT * FROM system.processes WHERE query_id = xxx;` with any suitable tempo.

**Comment by simPod** [comment]
Sure but we should follow best practices. Ofc it's a BC break tho. Can be taken care of with version IMO.

_About the hacking, yea. I had to bend Guzzle php as well but that's not relevant :)_

**Comment by alexey-milovidov** [comment]
@filimonov Maybe we can also add a header with query_id.
It will be useful if the user has not provided their own query_id with query.

**Comment by alexey-milovidov** [comment]
@simPod I see that naming headers with `X-` prefix is common practice.

Example: S3 API
https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonRequestHeaders.html

Maybe we simply should not make this changes right now.

**Comment by alexey-milovidov** [comment]
We can change it without any compatibility configuration settings. I think, this is Ok in this case.

**Comment by alexey-milovidov** [comment]
But we also have X-ClickHouse-User, X-ClickHouse-Key, X-ClickHouse-Quota.
And I cannot change this headers, it will be more harmful than X-ClickHouse-Progress.

**Comment by alexey-milovidov** [comment]
Adding a configuration option for HTTP headers prefix (`X-ClickHouse-`) is Ok, but looks like overkill, because we will have to keep the default with `X` and almost nobody will have any reson to change it.

**Comment by simPod** [comment]
Yes, thats definitely overkill. I guess it's only this or that, not both. Decision is yours.
