### ISSUE TITLE
Sliding Window Total in Clickhouse

### ISSUE THREAD

**Issue by calgs** [yandex/ClickHouse#3635]
Hello Experts! 
CH Rocks!.. We are saying that even more after working with this for almost a year.

Recently we stumbled upon a use case wherein we have to aggregate leading N values. For e.g. on Date 01/01/208, I want to add Sales of this date (10) + next two (15+20) = 45.

Is there a way we can get the sliding/rolling window totals.

Date            | Sales | Leading_3_Sales
01/01/2018 | 10 | 45
01/02/2018 | 15 | 60
01/03/2018 | 20 | 75
01/04/2018 | 25 | 90
01/05/2018 | 30 | 105
01/06/2018 | 35 | 120
01/07/2018 | 40 | 135
01/08/2018 | 45 | 95
01/09/2018 | 50 | 50

Thanks in advance!

**Comment by KochetovNicolai** [comment]
If your result set is not very big and can be placed to array, it's possible to calculate such aggregation using groupArray, arrayMap, arraySlice and sumArray functions.

It may be something like
```
groupArray(Sales) as sales_arr, 
arrayMap(shift -> arraySum(arraySlice(sales_arr, shift, N)), range(length(sales_arr)))
```

**Comment by calgs** [comment]
Learning something new (and nice) every time. This is neat. Thank you so much.
