### ISSUE TITLE
Function: power versus pow

### ISSUE THREAD

**Issue by dfulachier** [yandex/ClickHouse#3638]
ClickHouse defines the pow(x,y) function, as most common name in SQL dialects is power(x,y).
When using Tableau BI tool, Tableau generates SQL query using power(x,y), causing an SQL error.

Why not aliasing pow(x,y) to power(x,y) to get a more common SQL support for this function?

**Comment by alexey-milovidov** [comment]
Yes, we can easily add `power` alias.

**Comment by dfulachier** [comment]
Thank you Alexey for your very quick answer (I was not able to measure the time it took, you were too fast ;-).
Surely a simple way to improve ClickHouse SQL standards conformity, and ClickHouse support for Tableau BI.

**Comment by alexey-milovidov** [comment]
In master.
