### ISSUE TITLE
TimeSeries Calc | Using Arrays to Calculate Previous and Next Values

### ISSUE THREAD

**Issue by calgs** [yandex/ClickHouse#3648]
Hi,

Is there a way I can use Clickhouse (Arrays?) to calculate sequential values that are dependent on previously calculated values.

For e.g. 
On day 1, I start with 0 -- consume 5 -- Add 100 -- ending up with 0-5+100=95
My day2, starts with what I ended up on day 1 which is 95 -- again consume 10 -- add 5 -- ending up with 95-10+5=90 (which will be the start for day3)

Given 
ConsumeArray [5,10,25]
AddArray [100,5,10]
Calculate EndingPosition and (= StartingPosition for Next day)

[

  | Day 1 | Day 2 | Day 3 |  
-- | -- | -- | -- | --
StartingPosition (a) = Previous Ending Position | 0 | 95 | 90 | Calculate
Consumed (b) | 5 | 10 | 25 |  
Added (c) | 100 | 5 | 10 |  
EdingPosition (d) = a-b+c | 95 | 90 | 75 | Calculate

](url)

**Comment by KochetovNicolai** [comment]
Now I don't know if you can calculate something dependent on previously calculated values (I think it's not possible for general case now). However, for your example you can avoid such calculations because 
```
EndingPosition = sum(Added for prev. days) - sum(Consumed for prev. days) + StartingPosition_Day1
```
You can use arrays for such calculations. Something like:
```
arrayMap(day_idx -> sumArray(arraySlice(AddArr, 0, day_idx)) - sumArray(arraySlice(ConsumeArray, 0, day_idx)) + StartingPosition, range(length(AddArray))
```

**Comment by calgs** [comment]
Thanks.

Were you trying to propose something like this

WITH 
    0 AS StartingPosition, 
    [100, 5, 10] AS AddArr, 
    [5, 10, 25] AS ConsumeArray
SELECT arrayMap(day_idx -> ((sumArray(arraySlice(AddArr, 0, day_idx)) - sumArray(arraySlice(ConsumeArray, 0, day_idx))) + StartingPosition), range(length(AddArr)))

**This errors out**
_Received exception from server (version 18.6.0):
Code: 47. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Unknown identifier: day_idx, projection layer ._

**Comment by calgs** [comment]
Corrected Query...
with  0 as StartingPosition , [100,5,10] as AddArr , [5,10,25]  as ConsumeArray select arrayMap(x -> arraySum(arraySlice(AddArr, 1, x)) - arraySum(arraySlice(ConsumeArray, 1, x)) + StartingPosition, range(length(AddArr)));

This works.

**Comment by calgs** [comment]
Corrected Query [This worked].. Thanks so much!

`WITH 
    0 AS StartingPosition, 
    [100, 5, 10] AS AddArr, 
    [5, 10, 25] AS ConsumeArray
SELECT arrayMap(day_idx -> ((arraySum(arraySlice(AddArr, 1, day_idx)) - arraySum(arraySlice(ConsumeArray, 1, day_idx))) + StartingPosition), range(length(AddArr)))`
