### ISSUE TITLE
Build failed on FreeBSD

### ISSUE THREAD

**Issue by stofel** [yandex/ClickHouse#365]
Try to build by doc/build_freebsd.sh instructions on freebsd11
`>cmake --version
cmake version 3.7.1
`

`>cmake .. -DCMAKE_CXX_COMPILER=`which g++6` -DCMAKE_C_COMPILER=`which gcc6`
CMake Error: The source directory "/home/user/work/ClickHouse/build/found" does not exist.
`

**Comment by proller** [comment]
Checked now - anything works for me.

Can you try manually follow commands from this script?

Also here almost ready freebsd port:
https://github.com/proller/clickhouse-freebsd/tree/master/ports/databases/clickhouse

usage:
```
git clone https://github.com/proller/clickhouse-freebsd.git
cd clickhouse-freebsd/ports/databases/clickhouse
pw useradd clickhouse
make package install
```

**Comment by stofel** [comment]
>Can you try manually follow commands from this script?
Script reinstall many packages and make my devel server complete unworkable.
Now ill try to install gcc6, its not so easy.

**Comment by proller** [comment]
doc fixed https://github.com/yandex/ClickHouse/commit/7201e2846ad4170702c86a32d749328af0044f28

Also no need in gcc now.
but use `cmake .. -DUSE_INTERNAL_GPERFTOOLS_LIBRARY=0`

**Comment by stofel** [comment]
> cmake .. -DUSE_INTERNAL_GPERFTOOLS_LIBRARY=0 
Yes, this work. Thanks.

**Comment by jbwl** [comment]
Same error happens on Mac OS 10.14.6 trying to build from master branch with these instructions: https://clickhouse.yandex/docs/en/development/build_osx/#caveats
