### ISSUE TITLE
Building Error on Mac osx 10.14

### ISSUE THREAD

**Issue by ColorWork** [yandex/ClickHouse#3655]
Hi, 
failed to build the ClickHouse on macOS mojave 10.14

cmake .. -DCMAKE_CXX_COMPILER=`which g++` -DCMAKE_C_COMPILER=`which gcc`
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /usr/bin/gcc
CMake Error:
  The detected version of Ninja (GNU Make 3.81

  Copyright (C) 2006 Free Software Foundation, Inc.

  This is free software; see the source for copying conditions.

  There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A

  PARTICULAR PURPOSE.

  

  This program built for i386-apple-darwin11.3.0) is less than the version of
  Ninja required by CMake (1.3).

CMake Error at /usr/local/Cellar/cmake/3.13.0/share/cmake/Modules/CMakeTestCCompiler.cmake:37 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)

-- Configuring incomplete, errors occurred!

**Comment by filimonov** [comment]
Relates #235
