### ISSUE TITLE
failed to build clickhouse on Mac 10.14

### ISSUE THREAD

**Issue by ColorWork** [yandex/ClickHouse#3657]
ninja
[15/318] Building CXX object dbms/src/Common/tests/CMakeFiles/hashes_test.dir/hashes_test.cpp.o
FAILED: dbms/src/Common/tests/CMakeFiles/hashes_test.dir/hashes_test.cpp.o 
/usr/local/bin/g++-8  -DBOOST_SYSTEM_NO_DEPRECATED -DPOCO_STATIC -DPOCO_UNBUNDLED_ZLIB -DUNALIGNED_OK -DWITH_GZFILEOP -DX86_64 -DZLIB_COMPAT -I../dbms/src -Idbms/src -I../libs/libcommon/include -Ilibs/libcommon/include -I../contrib/zlib-ng -Icontrib/zlib-ng -I../contrib/cityhash102/include -I../libs/libpocoext/include -isystem ../contrib/double-conversion -isystem ../contrib/libpcg-random/include -isystem ../contrib/poco/Foundation/include -isystem ../contrib/boost -isystem ../contrib/poco/Net/include -isystem ../contrib/poco/Util/include -isystem ../contrib/poco/XML/include -isystem ../contrib/poco/JSON/include -isystem contrib/re2_st -isystem ../contrib/re2 -fdiagnostics-color=always  -pipe -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall  -Wnon-virtual-dtor -Wextra -Werror -O2 -g -DNDEBUG -O3  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk   -fno-tree-loop-distribute-patterns -std=c++17 -MD -MT dbms/src/Common/tests/CMakeFiles/hashes_test.dir/hashes_test.cpp.o -MF dbms/src/Common/tests/CMakeFiles/hashes_test.dir/hashes_test.cpp.o.d -o dbms/src/Common/tests/CMakeFiles/hashes_test.dir/hashes_test.cpp.o -c ../dbms/src/Common/tests/hashes_test.cpp
../dbms/src/Common/tests/hashes_test.cpp:5:10: fatal error: openssl/md5.h: No such file or directory
 #include <openssl/md5.h>
          ^~~~~~~~~~~~~~~
compilation terminated.

**Comment by hatarist** [comment]
Did you install openssl via homebrew?
Check the [OS X building guide](https://github.com/yandex/ClickHouse/blob/master/docs/en/development/build_osx.md)

**Comment by KochetovNicolai** [comment]
#3631

**Comment by proller** [comment]
fixed here - https://github.com/yandex/ClickHouse/commit/ad6ae4fdbea33b5c56ed7674611c7794974c71b6

**Comment by filimonov** [comment]
Relates #235
