### ISSUE TITLE
DISTINCT with JOIN returns duplicates (18.14.15)

### ISSUE THREAD

**Issue by ocmajortom** [yandex/ClickHouse#3658]
Hi,

sometimes, the following query leaves duplicates in the result (number of result rows differ on repeated queries):

`select  distinct ds.id 
from test.facts f all join test.dim_service ds 
on f.dim_service_id=ds.id `

**facts** is a MergeTree-table, **dim_service** an external dictionary.

Additional **group by** works:

`select  distinct ds.id from test.facts f all join test.dim_service ds on f.dim_service_id=ds.id group by ds.id`

Cheers!

**Comment by KochetovNicolai** [comment]
What is the dictionary layout and lifetime? Is it possible that dictionary had updated between queries?
Can you look for some ids which appeared or disappeared and check what `dictHas` function returns for them? Can you check also if reading from external dictionary returns different results sometimes?

It also would be helpful if you make test example which I could reproduce.

**Comment by ocmajortom** [comment]
Hi Nicolai,

it's an odbc-dictionary (see definitions below), 227 rows, underlying data did not change. select distinct on one of the tables seems stable and correct. Join between two MergeTree-Tables seems to be ok, too.

The duplicates only appear when joining the dictionary table with MergeTree-Table. The duplicate values  change after about 5 repeated requests, so you should be able to reproduce it, easily.


The MergeTree-Table test.facts is partitioned by the join-column!
`PARTITION BY dim_service_id`



----------------

CREATE TABLE test.dim_service ( sid UInt64,  caption String) ENGINE = Dictionary(dim_service)                                                                                                                                                    │ Dictionary(dim_service) 

```
<dictionary>
<name>dim_service</name>
        <source>
            <odbc>
          DATABASE=my_db -->
                <connection_string>DSN=psql</connection_string>
                <table>l4.dim_service</table>
            </odbc>
        </source>
        <lifetime>
            <min>300</min>
            <max>360</max>
        </lifetime>
        <layout>
            <hashed/>
        </layout>
        <structure>
            <id>
                <name>sid</name>
            </id>
            <attribute>
                <name>caption</name>
                <type>String</type>
                <null_value>0</null_value>
            </attribute>
        </structure>
    </dictionary>
```

**Comment by mpolano** [comment]
I also have a similar issue joining two MergeTree tables:

`SELECT distinct ip FROM measures ALL INNER JOIN netunits USING ip `

The result returns a variable number of rows at every run with a large number of duplicates.
If I swap the order of the two tables the result is correct:

`SELECT distinct ip FROM elements ALL INNER JOIN netunits USING ip `

Even in my case GROUP BY works.

**Comment by den-crane** [comment]
```
create table fooL (a Int64, v String) engine = Memory;
insert into fooL values (0, 'L');
insert into fooL values (0, 'L');
select distinct v from fooL any left outer join (select toInt64(0) a) using(a)  
┌─v─┐
│ L │
└───┘
┌─v─┐
│ L │
└───┘
```

VS

```
create table fooL (a Int64, v String) engine = Memory;
insert into fooL values (0, 'L'), (0, 'L');
select distinct v from fooL any left outer join (select toInt64(0) a) using(a)  
┌─v─┐
│ L │
└───┘
```

**Comment by 4ertus2** [comment]
Need check after #5001
