### ISSUE TITLE
Error when loading DateTime from CSV file

### ISSUE THREAD

**Issue by goranc** [yandex/ClickHouse#366]
I have problem with DateTime field when loading from CSV format.
When I use Linux Timestamp 10 digits format, I've got error about length of the field, it seems that parser is expecting 19 chars as in YYYY-MM-DD hh:mm:ss.

ERROR: DateTime must be in YYYY-MM-DD hh:mm:ss or NNNNNNNNNN (unix timestamp, exactly 10 digits) format.

In documentation is stated:
As an exception, parsing DateTime is also supported in Unix timestamp format, if it consists of exactly 10 decimal digits. The result is not time zone-dependent. The formats YYYY-MM-DD hh:mm:ss and NNNNNNNNNN are differentiated automatically.

If I specify 10 digits + 9 trailing spaces as input field then parser works, but loaded data is not correct.

**Comment by ludv1x** [comment]
@alexey-milovidov Such conversion (UInt -> DateTime) is supported inside queries. Should this conversion  be supported inside input formats?

**Comment by alexey-milovidov** [comment]
It is already supported for TSV, but for somewhat reason doesn't work for CSV,
and it works for Values format only through very indirect way.

It's better to make it work in all text formats.
