### ISSUE TITLE
error: LowCardinality(Nullable(String)) can't be group by column

### ISSUE THREAD

**Issue by shangshujie365** [yandex/ClickHouse#3677]
I have a column 'columnA' with type 'LowCardinality(Nullable(String))', when I group by this column, I got core file, 
my sql is quite simple, like this:
select count() from (
select 1 from XXX group by columnA
)

and the error msg is this:
2018.11.27 12:34:35.317994 [ 2 ] {} <Error> BaseDaemon: (from thread 575) Received signal Segmentation fault (11).
2018.11.27 12:34:35.317999 [ 2 ] {} <Error> BaseDaemon: Address: 0x7f867bfff006
2018.11.27 12:34:35.318004 [ 2 ] {} <Error> BaseDaemon: Access: read.
2018.11.27 12:34:35.318008 [ 2 ] {} <Error> BaseDaemon: Attempted access has violated the permissions assigned to the memory area.
2018.11.27 12:34:35.329132 [ 2 ] {} <Error> BaseDaemon: 0. clickhouse-server(memcpy+0xd0) [0x6060830]
2018.11.27 12:34:35.329142 [ 2 ] {} <Error> BaseDaemon: 1. clickhouse-server(DB::ColumnString::deserializeAndInsertFromArena(char const*)+0x4c) [0x55714fc]
2018.11.27 12:34:35.329149 [ 2 ] {} <Error> BaseDaemon: 2. clickhouse-server(DB::ColumnUnique<DB::ColumnString>::uniqueDeserializeAndInsertFromArena(char const*, char const*&)+0x4d) [0x4a2bc6d]
2018.11.27 12:34:35.329156 [ 2 ] {} <Error> BaseDaemon: 3. clickhouse-server(DB::ColumnLowCardinality::deserializeAndInsertFromArena(char const*)+0x30) [0x5560390]
2018.11.27 12:34:35.329182 [ 2 ] {} <Error> BaseDaemon: 4. clickhouse-server(void DB::Aggregator::convertToBlockImplFinal<DB::AggregationMethodSerialized<TwoLevelHashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef>, HashTableNoState>, DefaultHash<StringRef>, TwoLevelHashTableGrower<8ul>, Allocator<true> > >, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef>, HashTableNoState>, DefaultHash<StringRef>, TwoLevelHashTableGrower<8ul>, Allocator<true> > >(DB::AggregationMethodSerialized<TwoLevelHashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef>, HashTableNoState>, DefaultHash<StringRef>, TwoLevelHashTableGrower<8ul>, Allocator<true> > >&, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef>, HashTableNoState>, DefaultHash<StringRef>, TwoLevelHashTableGrower<8ul>, Allocator<true> >&, std::vector<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, std::vector<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn> > >&) const+0x74) [0x58fc8a4]
2018.11.27 12:34:35.329208 [ 2 ] {} <Error> BaseDaemon: 5. clickhouse-server(void DB::Aggregator::convertToBlockImpl<DB::AggregationMethodSerialized<TwoLevelHashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef>, HashTableNoState>, DefaultHash<StringRef>, TwoLevelHashTableGrower<8ul>, Allocator<true> > >, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef>, HashTableNoState>, DefaultHash<StringRef>, TwoLevelHashTableGrower<8ul>, Allocator<true> > >(DB::AggregationMethodSerialized<TwoLevelHashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef>, HashTableNoState>, DefaultHash<StringRef>, TwoLevelHashTableGrower<8ul>, Allocator<true> > >&, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef>, HashTableNoState>, DefaultHash<StringRef>, TwoLevelHashTableGrower<8ul>, Allocator<true> >&, std::vector<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, std::vector<DB::PODArray<char*, 4096ul, Allocator<false>, 15ul>*, std::allocator<DB::PODArray<char*, 4096ul, Allocator<false>, 15ul>*> >&, std::vector<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, bool) const+0x78) [0x58fca18]
2018.11.27 12:34:35.329228 [ 2 ] {} <Error> BaseDaemon: 6. clickhouse-server(DB::Block DB::Aggregator::prepareBlockAndFill<DB::Block DB::Aggregator::convertOneBucketToBlock<DB::AggregationMethodSerialized<TwoLevelHashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef>, HashTableNoState>, DefaultHash<StringRef>, TwoLevelHashTableGrower<8ul>, Allocator<true> > > >(DB::AggregatedDataVariants&, DB::AggregationMethodSerialized<TwoLevelHashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef>, HashTableNoState>, DefaultHash<StringRef>, TwoLevelHashTableGrower<8ul>, Allocator<true> > >&, bool, unsigned long) const::{lambda(std::vector<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, std::vector<DB::PODArray<char*, 4096ul, Allocator<false>, 15ul>*, std::allocator<DB::PODArray<char*, 4096ul, Allocator<false>, 15ul>*> >&, std::vector<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, bool)#1}>(DB::AggregatedDataVariants&, bool, unsigned long, DB::AggregationMethodSerialized<TwoLevelHashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef>, HashTableNoState>, DefaultHash<StringRef>, TwoLevelHashTableGrower<8ul>, Allocator<true> > >&&) const+0x3d7) [0x58fce77]
2018.11.27 12:34:35.329236 [ 2 ] {} <Error> BaseDaemon: 7. clickhouse-server(DB::MergingAndConvertingBlockInputStream::thread(int, std::shared_ptr<DB::ThreadGroupStatus>)+0x9c0) [0x5949c80]
2018.11.27 12:34:35.329245 [ 2 ] {} <Error> BaseDaemon: 8. clickhouse-server(std::_Function_handler<void (), std::_Bind<void (DB::MergingAndConvertingBlockInputStream::*(DB::MergingAndConvertingBlockInputStream*, int, std::shared_ptr<DB::ThreadGroupStatus>))(int, std::shared_ptr<DB::ThreadGroupStatus>)> >::_M_invoke(std::_Any_data const&)+0x50) [0x58b27a0]
2018.11.27 12:34:35.329252 [ 2 ] {} <Error> BaseDaemon: 9. clickhouse-server(ThreadPool::worker()+0x167) [0x5e0ef97]
2018.11.27 12:34:35.329260 [ 2 ] {} <Error> BaseDaemon: 10. clickhouse-server() [0x64efd6f]
2018.11.27 12:34:35.329266 [ 2 ] {} <Error> BaseDaemon: 11. /lib64/libpthread.so.0(+0x7e25) [0x7f8947b0ce25]

**Comment by shangshujie365** [comment]
18.14.13

**Comment by KochetovNicolai** [comment]
From stacktrace I can assume that the issue the same as in #3615 which was fixed in #3632 .
Fix is not in any release yet, but you can build from master if you want to check it.

**Comment by shangshujie365** [comment]
ok
