### ISSUE TITLE
Include not found

### ISSUE THREAD

**Issue by qJkee** [yandex/ClickHouse#3679]
Привет.
Пытаюсь сделать ограничение по ip для каждого пользователя
Для этого, создал конфигурационные файлы для каждого пользователя в `/etc/clickhouse-server/config.d`
В файл xxxuser.xml добавил следующее
```
    <users>
        <xxxuser>
            <password_sha256_hex>passwd here</password_sha256_hex>
    	<profile>default</profile>
		<quota>default</quota>
        <networks incl="networks" />
	    <networks>
        	<ip>ip1</ip>
                <ip>ip2</ip>
        </networks>
		</xxxuser>
    </users>
</yandex>
```
В итоге, в логах вижу `Include not found: networks`
И зайти на сервер с указанных ip не могу, т.к пишет что нельзя зайти с указанного ip

**Comment by den-crane** [comment]
Также в конфиге могут быть указаны "подстановки". Если у элемента присутствует атрибут incl, то в качестве значения будет использована соответствующая подстановка из файла. По умолчанию, путь к файлу с подстановками - **/etc/metrika.xml**
пример https://gist.github.com/den-crane/d6e0f1c7849a0bc44c27eab2de51c911

networks incl="networks"  -- непонятно что вы вообще хотели сделать? вынести общую часть в отдельный файл?

**Comment by qJkee** [comment]
Ну изначально только пытался сконфигурировать только пользователя.
После неудачи - добавил эту строчку отсюда - https://clickhouse.yandex/docs/ru/operations/access_rights/
Т.е стоит описать всех пользователей в users.xml?

**Comment by den-crane** [comment]
> Ну изначально только пытался сконфигурировать только пользователя.
> После неудачи - добавил эту строчку отсюда - https://clickhouse.yandex/docs/ru/operations/access_rights/

Не нужна вам эта строчка, в чем была неудача?

> Т.е стоит описать всех пользователей в users.xml?

да нет, и так все будет работать (каждый пользователь в своем xml)

**Comment by blinkov** [comment]
@qJkee получилось настроить в итоге?
