### ISSUE TITLE
replacingMergeTree would not merge data in different month

### ISSUE THREAD

**Issue by yuliujuan** [yandex/ClickHouse#3696]
version 18.14.15
```
create table t (gmt  Date, id UInt16, name String, point UInt16) ENGINE=ReplacingMergeTree(gmt, (name), 10);

insert into t (gmt, id, name, point) values ('2017-07-10', 1, 'a', 20);
insert into t (gmt, id, name, point) values ('2017-07-11', 1, 'a', 30);
insert into t (gmt, id, name, point) values ('2017-08-10', 1, 'a', 20);
insert into t (gmt, id, name, point) values ('2017-08-11', 1, 'a', 10);


optimize table t;

select * from t;


SELECT *
FROM t

┌────────gmt─┬─id─┬─name─┬─point─┐
│ 2017-07-11 │  1 │ a    │    30 │
└────────────┴────┴──────┴───────┘
┌────────gmt─┬─id─┬─name─┬─point─┐
│ 2017-08-10 │  1 │ a    │    10 │
└────────────┴────┴──────┴───────┘

```

My expected result is that only data in 2017-08-11 remains.
Is ClickHouse designed not to merge data in different month? What is the consideration?
Please advise. Thanks in advance.

**Comment by KochetovNicolai** [comment]
ClickHouse do not merge data from different partitions. Your table is partitioned by month. You can use [custom partitioning](https://clickhouse.yandex/docs/en/single/?query=Log#custom-partitioning-key) or manually select only rows with maximal version.

**Comment by blinkov** [comment]
@yuliujuan do you have any further questions?

**Comment by yuliujuan** [comment]
@blinkov 
sorry for the late reply.
I will use custom partitioning.
Please close the issue. Thank you all.

Actually, I am thinking that if select * from t final can be used for getting the latest record, is it possible to make "optimize table t FINAL" to merge data from different partitions, 'cause the site doesn't recommend to avoid using FINAL in most of the cases.
