### ISSUE TITLE
pointInPolygon() has different result from table and directly use latitude and longitude

### ISSUE THREAD

**Issue by vicchen7** [yandex/ClickHouse#3697]
I found the tricky issue about pointInPolygon().
I checked all points of the attached and they are not in below polygon .

{ "type": "Polygon", "coordinates": [[[43.909597,26.410569],[43.912987,26.405629],[43.908288,26.40315],[43.906014,26.407321],[43.906056,26.407244],[43.909597,26.410569]]]}

![latlon](https://user-images.githubusercontent.com/5370461/49213413-38cd7880-f3ff-11e8-93ec-eeb7e4008a0b.jpg)

I use the attached data imported into ClickHouse and tried to use below script to query and got wrong result.
But I used the value of latitude and longitude in function directly and can get the correct result.

CREATE TABLE test_pointinpolygon_1 ( POS_LON Float32,  POS_LAT Float32) ENGINE = MergeTree ORDER BY tuple() SETTINGS index_granularity = 8192;

SELECT POS_LON, POS_LAT ,pointInPolygon((POS_LON,POS_LAT), [(43.909597, 26.410569), (43.912987, 26.405629), (43.908288, 26.40315), (43.906014, 26.407321), (43.906056, 26.407244), (43.909597, 26.410569)]) AS str from test_pointinpolygon_1;

SELECT pointInPolygon((43.910027, 26.403429), [(43.909597, 26.410569), (43.912987, 26.405629), (43.908288, 26.40315), (43.906014, 26.407321), (43.906056, 26.407244), (43.909597, 26.410569)]) AS str;

![latlon-1](https://user-images.githubusercontent.com/5370461/49213451-50a4fc80-f3ff-11e8-87a4-76097e2b3271.jpg)

[20181129_latlon.zip](https://github.com/yandex/ClickHouse/files/2628470/20181129_latlon.zip)

How can fix it?

**Comment by KochetovNicolai** [comment]
Now I can see that the difference is in point coord. types. It works if I change Floar32 to Float64.
```SQL
CREATE TABLE test_pointinpolygon_1
(
    POS_LON Float64, 
    POS_LAT Float64
)
ENGINE = MergeTree
ORDER BY tuple()
SETTINGS index_granularity = 8192

Ok.

0 rows in set. Elapsed: 0.040 sec. 


INSERT INTO test_pointinpolygon_1 VALUES

Ok.

1 rows in set. Elapsed: 0.002 sec. 


SELECT 
    POS_LON, 
    POS_LAT, 
    pointInPolygon((POS_LON, POS_LAT), [(43.909597, 26.410569), (43.912987, 26.405629), (43.908288, 26.40315), (43.906014, 26.407321), (43.906056, 26.407244), (43.909597, 26.410569)]) AS str
FROM test_pointinpolygon_1 

┌───POS_LON─┬───POS_LAT─┬─str─┐
│ 43.910027 │ 26.403429 │   0 │
└───────────┴───────────┴─────┘

1 rows in set. Elapsed: 0.010 sec.
```

**Comment by bicubic** [comment]
A float32 latlong has an error of ~1.7 meters. Two float32s have a cumulative error of ~3.4 meters. Any intermediate arithmetic using float32 in the point in polygon test will further compound the error.

**Comment by bicubic** [comment]
A float32 latlong has an error of ~1.7 meters. Two float32s have a cumulative error of ~3.4 meters. Any intermediate arithmetic using float32 in the point in polygon test will further compound the error.

The point that's shown on the highway looks a bit extreme though.

**Comment by vicchen7** [comment]
After updating the data type of latitude and longitude using Float64 and the result is correct.
