### ISSUE TITLE
Security issue: bind 127.0.0.1 only for unsecured database

### ISSUE THREAD

**Issue by jacktang** [yandex/ClickHouse#371]
Hello,

I install ClickHouse on the debian server, and play around according the guides. Thanks for the great product! I find ClickHouse server bind to 0.0.0.0 by default, and all databases are unsecured,
```
$ netstat -nao | grep 8123
tcp6       0      0 :::8123                 :::*                    LISTEN      off (0.00/0/0)
```
Which means everyone can scan 8123 port and see the data using ClickHouse http interface. There are a lot of reports on [hijacking unsecured mongoDB](http://thehackernews.com/2017/01/secure-mongodb-database.html). 

So I strongly suggest to bind 127.0.0.1 IP address only for the unsecured database (like mysql server). Make sense?

**Comment by alexey-milovidov** [comment]
Hello.
Yes, that makes sense. 

Probably we should bind to 127.0.0.1 (::1) by default and highlight it in documentation and tutorials. 
Or we could still bind to wildcard address, but don't allow connections without password from everywhere except 127.0.0.1.

(The only difficulty is that users frequently create clustered setup, that use user `default` without password for internal communications between servers.)

We will choose some solution.

**Comment by proller** [comment]
problem:
::1 does not listen 127.0.0.1
need split <listen_host> to allow listen multiple addresses

**Comment by proller** [comment]
also all tests with 127.0.0.2 127.0.0.3 will fail

**Comment by proller** [comment]
done.
https://github.com/yandex/ClickHouse/commit/107fb86a40e39deaaa2a00d32fe2f0af6595348b

**Comment by bobrik** [comment]
@alexey-milovidov, is there a way to have `default` with password for internal cluster communication?

**Comment by alexey-milovidov** [comment]
It is possible to either:
- specify password for default user;
- use non-default user for inter cluster communication.

In both cases, you just need to specify `user` and `password` (near `host` and `port`) in definitions of your clusters.
