### ISSUE TITLE
Support standard 'locate' SQL function

### ISSUE THREAD

**Issue by dfulachier** [yandex/ClickHouse#3711]
ClickHouse proposes the 'position' function, and we can do with that.
But in some case (queries generated from a BI tool such as Tableau), we cannot master the SQL generated. So it may be fine to get the locate function, with both possible syntaxes:

- locate(search, source)
- locate(search, source, startPos)

**Comment by blinkov** [comment]
Alias added in #3774, but `position` don't support startPos optional arg at the moment.
