### ISSUE TITLE
LowCardinality for PARTITION BY

### ISSUE THREAD

**Issue by tishkinis** [yandex/ClickHouse#3716]
select version();
18.12.13

create table lc_table
(
	event_time DateTime,
	partition_type LowCardinality(String)
) engine = MergeTree()
	PARTITION BY (toYYYYMM(event_time), partition_type)
	ORDER BY (toDate(event_time))
	SETTINGS index_granularity=8192
;

insert into lc_table (event_time, partition_type)
values (toDateTime('0000-00-00 00:00:00'), 'string');

java.lang.Throwable: Code: 48, e.displayText() = DB::Exception: Method index is not supported for ColumnUnique., e.what() = DB::Exception

**Comment by KochetovNicolai** [comment]
I think it works in master.
```SQL
:) insert into lc_table (event_time, partition_type)
:-] values (toDateTime('0000-00-00 00:00:00'), 'string');

INSERT INTO lc_table (event_time, partition_type) VALUES
Ok.

1 rows in set. Elapsed: 0.006 sec. 

mtdev04t.yandex.ru :) select * from lc_table

SELECT *
FROM lc_table 

┌──────────event_time─┬─partition_type─┐
│ 0000-00-00 00:00:00 │ string         │
└─────────────────────┴────────────────┘

1 rows in set. Elapsed: 0.003 sec. 

```

**Comment by blinkov** [comment]
@tishkinis try upgrading to v18.14.17-stable

**Comment by filimonov** [comment]
See #3288

Still appears in 18.14.17. Fix only in master?

**Comment by tishkinis** [comment]
18.16.0, #3716 fixed
