### ISSUE TITLE
quantile/median are not implemented for Decimal types

### ISSUE THREAD

**Issue by den-crane** [yandex/ClickHouse#3730]
select median(a) from (select toDecimal128(10,18) a union all select toDecimal128(10,18))
select median(a) from (select toDecimal64(10,3) a union all select toDecimal64(10,3))

DB::Exception: Illegal type Decimal(18, 3) of argument for aggregate function quantile.

CH: 18.14.15

**Comment by den-crane** [comment]
workaround :   select median(toFloat64(a))

**Comment by 4ertus2** [comment]
There's only quantileExact supported for now. We probably need quantile and quantileTDigest as well.

**Comment by alexey-milovidov** [comment]
@4ertus2 

Implementation of `quantile`, `quantileWeighted` should be straightforward (decimals are processed as scaled integers).

`quantileTDigest` implies conversion to Float32.
`quantileTiming` implies conversion to UInt16.

**Comment by 4ertus2** [comment]
#5304
