### ISSUE TITLE
Question : will hdfs + parquet support available for the file table engine  ?

### ISSUE THREAD

**Issue by TH-HA** [yandex/ClickHouse#3734]
If it does , Clickhouse may become a game changer in the hadoop world ( of course this may require more evolution on the file directory layout supported by the file engine ). 
This need to be tested , but i'm really confident that the performance of query will be at a different level compare to hive/impala/drill. For us as we will need to integrate our data with such kind of technology, this can become a key feature.

Thanks

**Comment by blinkov** [comment]
@TH-HA Parquet is going to be just yet another supported serialization format (similar to [these](https://clickhouse.yandex/docs/en/interfaces/formats/)) and as far as I can see current PR for HDFS support (#3617) includes either table function and table engine.

**Comment by TH-HA** [comment]
Thanks a lot , waiting for the release to test that.

Regards
