### ISSUE TITLE
Integer or decimal conversion from hex string wich can contains up to UInt256 maximum.

### ISSUE THREAD

**Issue by TrollStation** [yandex/ClickHouse#3735]
I trying to get Ethereum token value from `transfer` event.
In one column i have hex-encoded UInt256 and other column contains `decimals` field represents how many decimal digits fraction has.
There is no functions like `reinterpretAs` for Decimal-types for use it after `unhex()`(just like in #2686)
Is there a way how i can get Decimal type in that situation?

**Comment by TrollStation** [comment]
For example, i have couple of values like `000000000000000000000000000000000000000000000002b5e3af16b1880000`. It's 50000000000000000000 in dec which overflow UInt64 as maximum possible unsigned integer type. Should i try to use `bitmaskToArray()` or something like this while slitting this number by parts?

**Comment by 4ertus2** [comment]
It looks like we need to realize reinterpretAsDecimal*. It's possible to make some dirty workaround. Something like this:

```
SELECT out
FROM 
(
    SELECT 
        '02b5e3af16b1880000' AS x, 
        length(x) AS xlen, 
        substring(x, 1, xlen - 16) AS first, 
        substring(x, (xlen - 16) + 1, 16) AS last, 
        reinterpretAsUInt64(reverse(unhex(first))) AS high, 
        reinterpretAsUInt64(reverse(unhex(last))) AS low, 
        reinterpretAsInt64(reverse(unhex('100000000'))) AS pwr, 
        ((toDecimal128(high, 0) * pwr) * pwr) + low AS out
) 

┌──────────────────out─┐
│ 50000000000000000000 │
└──────────────────────┘
```

Any case there's no support for 256-bit decimals for now (we have it in plan for the next year). Even if you try to split it to two Decimal128 you may get troubles with type borders: (-1*10^38, 10^38).

**Comment by TrollStation** [comment]
Thanks for the reply! Glad to hear that big numbers will be nativly supported in near future because Clickhouse is really cool DB.
