### ISSUE TITLE
Memory usage of merge

### ISSUE THREAD

**Issue by fancyqlx** [yandex/ClickHouse#3750]
Hi. We have some problems recently and I wonder that Is there any possibility to further optimize the merge process? 

We got a new cluster and there are a large amount of data inserted into this cluster. So there are many merges in the background process. The problem is that we found the memory usage is very high and it sometimes got out of memory. For example, I found that merging 14 parts needs 10.81GB. When there are several merges, we may eat all of the free memory. 

![image](https://user-images.githubusercontent.com/6196299/49442631-0956ab80-f805-11e8-9c2a-2b879d813fa6.png)

![image](https://user-images.githubusercontent.com/6196299/49443749-2e98e900-f808-11e8-9541-40e08c719c16.png)

The above picture is the memory usage of vertical merges. I have read MergeSortingBlocksBlockInputStream and ColumnGathererStream. I still do not know why we need so much memory. As far as I know, the engine contains 15 blocks when we merge 14 parts and only the columns of partition keys will be read. All the remaining column are read one by one and sorted by ColumnGathererStream. Is there any possibility to further optimize the merge process?

**Comment by fancyqlx** [comment]
why not limit the usage of memory. I found there is a parameter for limiting disk usage. Can we add some parameters for limiting memory usage when selecting parts to merge.

**Comment by filimonov** [comment]
Is it still actual? Usually merges shouldn't take so much RAM, and executed in streaming manner. 

Can you show the create table statement?

**Comment by fancyqlx** [comment]
thanks, we did not see it again.
