### ISSUE TITLE
Question: How to speed-up deletion of inactive parts ?

### ISSUE THREAD

**Issue by healiseu** [yandex/ClickHouse#3758]
Hi, in the system I build (associative-semiotic-hypergraph) performance is significantly better if I optimize my tables. But after optimization, the size of data is doubled. 

I have read the relevant part of [documentation][1] where it says that:
> "Inactive parts are, for example, source parts remaining after merging to a larger part – these parts are deleted approximately 10 minutes after merging."

How is it possible to speed-up deletion ?

Relevant Issues: #745
Relevant posts: [If we drop and create the same partition, do we need to wait for the drop to succeed, before creating the same partition?][2]

[1]: https://clickhouse.yandex/docs/en/query_language/alter/#manipulations-with-partitions-and-parts
[2]: https://groups.google.com/forum/#!msg/clickhouse/YJBhivgCnZw/H6Ns9RByBAAJ

**Comment by alex-zaitsev** [comment]
It is controlled by merge tree setting old_parts_lifetime. Default is 480s, or 8 mins. You can change it at server level or per table.

**Comment by healiseu** [comment]
@alex-zaitsev I have used a SETTINGS directive in CREATE TABLE e.g.
``` sql
CREATE TABLE Test (   
    dim3 UInt16,
    dim2 UInt16,
    dim1 UInt16,

    val  Float32,
    sel  UInt8)

 ENGINE = MergeTree()
 PARTITION BY (dim3, dim2)
 ORDER BY (dim3, dim2, dim1)
 SETTINGS old_parts_lifetime = 120
''');
```
It works. How can I view the settings of this table ;

**Comment by alex-zaitsev** [comment]
@healiseu 

SHOW CREATE TABLE. 

Only overrides are shown. Global settings can be viewed in system.merge_tree_settings table (as of 18.10.3 release and later)

**Comment by healiseu** [comment]
OK thanks Alex, issue is closed
