### ISSUE TITLE
cube/rollup got wrong result in large data with multi-threads

### ISSUE THREAD

**Issue by shangshujie365** [yandex/ClickHouse#3764]
My data is large, more than 100M lines, 

=> when 'SET max_threads = 1', result is right
=> SELECT 
    gender, 
    platform, 
    count()
FROM test.xxx
WHERE ((gender = 'M') OR (gender = 'F')) AND (platform = 'IPHONE')
GROUP BY 
    gender, 
    platform
    WITH CUBE

┌─gender─┬─platform─┬─count()─┐
│ M      │ IPHONE   │ Num1 │
│ F      │ IPHONE   │  Num2 │
└────────┴──────────┴─────────┘
┌─gender─┬─platform─┬─count()─┐
│ F      │ ᴺᵁᴸᴸ     │  Num2 │
│ M      │ ᴺᵁᴸᴸ     │  Num1 │
└────────┴──────────┴─────────┘
┌─gender─┬─platform─┬─count()─┐
│        │ IPHONE   │  Num1 + Num2 │
└────────┴──────────┴─────────┘
┌─gender─┬─platform─┬─count()─┐
│        │ ᴺᵁᴸᴸ     │ Num1 + Num2 │
└────────┴──────────┴─────────┘

6 rows in set. Elapsed: 0.253 sec. 

=> SET max_threads = 50, got wrong result
=> SELECT 
    gender, 
    platform, 
    count()
FROM ks_dws_test.party_allprod_user_active_di_local 
WHERE ((gender = 'M') OR (gender = 'F')) AND (platform = 'IPHONE')
GROUP BY 
    gender, 
    platform
    WITH CUBE

┌─gender─┬─platform─┬─count()─┐
│ M      │ IPHONE   │  Num1 │
└────────┴──────────┴─────────┘
┌─gender─┬─platform─┬─count()─┐
│ M      │ ᴺᵁᴸᴸ     │  Num1 │
└────────┴──────────┴─────────┘
┌─gender─┬─platform─┬─count()─┐
│        │ IPHONE   │  Num1 │
└────────┴──────────┴─────────┘
┌─gender─┬─platform─┬─count()─┐
│        │ ᴺᵁᴸᴸ     │  Num1 │
└────────┴──────────┴─────────┘
┌─gender─┬─platform─┬─count()─┐
│ F      │ IPHONE   │  Num2 │
└────────┴──────────┴─────────┘
┌─gender─┬─platform─┬─count()─┐
│ F      │ ᴺᵁᴸᴸ     │  Num2 │
└────────┴──────────┴─────────┘
┌─gender─┬─platform─┬─count()─┐
│        │ IPHONE   │  Num2 │
└────────┴──────────┴─────────┘
┌─gender─┬─platform─┬─count()─┐
│        │ ᴺᵁᴸᴸ     │  Num2 │
└────────┴──────────┴─────────┘

8 rows in set. Elapsed: 0.075 sec. 

I guess, In the result of '50 threads', the line 1 and line 5 are somehow in different blocks, so they are calculated by 'Cube' operator separately, so the final result can't merged.

**Comment by shangshujie365** [comment]
this problem is very wired, keep max_threads=52, set max_block_size=65529, the result sometimes is right, sometimes is wrong, if set max_block_size larger, the result is always wrong, is set max_block_size smaller, the result is always right. btw, our defult max_block_size = 5242880.
if set max_threads=1, the result is right

**Comment by shangshujie365** [comment]
somehow, if these 2 lines are in one block, like following, the result is right,
┌─gender─┬─platform─┬─count()─┐
│ M      │ IPHONE   │  Num1 │
│ F      │ IPHONE   │  Num2 │
└────────┴──────────┴─────────┘
if these 2 lines are in different blocks, the result is wrong, like following:
┌─gender─┬─platform─┬─count()─┐
│ M      │ IPHONE   │  Num1 │
└────────┴──────────┴─────────┘
┌─gender─┬─platform─┬─count()─┐
│ F     │ IPHONE   │  Num2 │
└────────┴──────────┴─────────┘

**Comment by shangshujie365** [comment]
the wrong result are always occurred with  'Aggregator: Converting aggregation data to two-level.'

**Comment by shangshujie365** [comment]
you can reproduce my problem by 'set group_by_two_level_threshold=1;'

using a table like following:
select * from test.r2;
┌───────date─┬─id─┐
│ 2018-10-01 │  1 │
│ 2018-10-02 │  2 │
│ 2018-11-01 │  1 │
│ 2018-11-03 │  2 │
└────────────┴────┘
set group_by_two_level_threshold=1;
select date,id,count() from test.r2 group by date,id with cube

**Comment by shangshujie365** [comment]
In line 62 of CubeBlockInputStream.cpp,
 source_block = children[0]->read();
CH get a block of underline stream, and do some mask on it, but can't guarantee all related data is in one block, maybe there are too many rows or some related data crossed blocks.

**Comment by shangshujie365** [comment]
actually I have write a small fix to this problem

**Comment by shangshujie365** [comment]
here is my small fix:
add these fields to CubeBlockInputStream.h:
    BlocksList ori_blocks;
    bool startMask = false;
add new read method of CubeBlockInputStream.cpp:
Block CubeBlockInputStream::readImpl()
{
    if (startMask){
        return {};
    }else {
        source_block = children[0]->read();
        if (!source_block) {
            BlocksList cube_blocks;
            for (auto &block : ori_blocks) {
                zero_block = block.cloneEmpty();
                for (auto key : keys)
                {
                    auto & current = zero_block.getByPosition(key);
                    current.column = current.column->cloneResized(block.rows());
                }

                mask = (1 << keys.size()) - 1;
                while (mask) {
                    --mask;
                    Block cube_block = block;
                    for (size_t i = 0; i < keys.size(); ++i) {
                        if (!((mask >> i) & 1)) {
                            size_t pos = keys.size() - i - 1;
                            auto &current = cube_block.getByPosition(keys[pos]);
                            current.column = zero_block.getByPosition(keys[pos]).column;
                        }
                    }
                    cube_blocks.push_back(cube_block);
                }
            }

            startMask = true;

            Block finalized = aggregator.mergeBlocks(cube_blocks, true);
            return finalized;
        } else {
            ori_blocks.push_back(source_block);

            Block finalized = source_block;
            finalizeBlock(finalized);

            return finalized;
        }
    }
}

**Comment by shangshujie365** [comment]
sure, let me try

**Comment by shangshujie365** [comment]
Hi, @filimonov, you can see my fix at https://github.com/shangshujie365/ClickHouse/commit/4f143af9a00d36c115c239d2466131d8509016d5.
The bug has been fixed, but introduce another bug, 
if gender or platform has 'null' value, the partial cube result (gender=null, platform-cubed-to-null), (gender-cubed-to-null, platform-cubed-to-null) will be aggregated together, so the result will be wrong.
May be we should introduce a new column 'cubeId', its value is the column not be cubed, in this case, it should be 'gender,platform', 'gender', 'platform', 'null'

**Comment by viongpanzi** [comment]
hi @shangshujie365 

We have the same problem, is the problem fixed now?

**Comment by shangshujie365** [comment]
@viongpanzi 
not yet

**Comment by viongpanzi** [comment]
@shangshujie365 thx~

**Comment by reflection** [comment]
@blinkov @KochetovNicolai this should be very high priority, please.  We have to run `SET max_threads=1;` before *all* of our `WITH ROLLUP` queries because otherwise ClickHouse returns unusable data.  Setting max_threads to 1 adversely affects ClickHouse performance.

**Comment by reflection** [comment]
No response yet, so I'll ask again: what are the consequences of disabling `group_by_two_level`?  Since this issue is not fixed, it is the only workaround we have, and searching through ClickHouse documentation hasn't yielded anything.  Thanks.

**Comment by blinkov** [comment]
> No response yet, so I'll ask again: what are the consequences of disabling `group_by_two_level`?
Should be mostly performance and scalability.

**Comment by alexey-milovidov** [comment]
> what are the consequences of disabling group_by_two_level

Severe performance degradation of GROUP BY with large result (merging will be done single-threaded).

**Comment by buyology** [comment]
Would be great with a patch for this. @shangshujie365 do you plan on submitting yours?
