### ISSUE TITLE
Negative Decimal128 values

### ISSUE THREAD

**Issue by igor-sh8** [yandex/ClickHouse#3768]
Hi.
I have a problem with decimal128 column type. I could not insert negative values to such column. 
Need to say, that I am using custom C# client and TCP protocol in it for inserting data into clickhouse.
What I have for now.
I can insert positive values to decimal128 column type as simple 16 byte array.
```
var res = new byte[16]; //initialize new byte array 
var val = (decimal)d * (int)Math.Pow((double)10, (double)_scale); // applying scale parameter
if (val >= 0 && val <= Int64.MaxValue) //the simplest case when the size of the decimal value  fits in 8 bytes
                {
                    var intVal = (Int64)(val); // cast decimal to int64
                    var bytes = BitConverter.GetBytes(intVal); //get 8 byte array from int64
                    Array.Copy(bytes, 0, res, 0, 8); //fill first 8 bytes of result from int64 byte array
                }
```
After that I just insert these bytes into decimal column. 
This works great for me but only with positive numbers. 
If the `val` variable is below zero and greater then `Int64.MinValue` then such code does not work because it inserts unexpected values. 
So I think that in clickhouse decimal128 structure must be some sign bit that represents the sign of the stored value or maybe something else.
Have you any suggestions for my problem ?

**Comment by 4ertus2** [comment]
Hi,

Decimals are integers inside. You can write fist 8 bytes to 0xFF and negative Int64 after them for 64-bit values. For full 128-bit math you need 128-bit integers support (native or self-made). Then you could write Int128 values to the column as is.
