### ISSUE TITLE
clickhouse-server pidfile missing

### ISSUE THREAD

**Issue by PascalWithopf** [yandex/ClickHouse#3780]
I'm running clickhouse version 18.14.17 on Ubuntu 18.04.

I installed clickhouse as described in the [Quick Start](https://clickhouse.yandex/#quick-start).

I start clickhouse-server in the terminal like this:
```sudo clickhouse-server --config-file=/etc/clickhouse-server/config.xml --pid-file=/var/run/clickhouse-server/clickhouse-server.pid```

I can find the pid in the status file `/var/lib/clickhouse/status` and the
command `pidof clickhouse-server` is working too.

But a pidfile is not created.

**Comment by filimonov** [comment]
May be related: #3501 #3610

**Comment by filimonov** [comment]
BTW why do you run `clickhouse-server` directly?

If you install clickhouse-server from the packages it should be registered as a systemd service, which should be started automatically.

**Comment by PascalWithopf** [comment]
I want to run clickhouse in a docker container for testing, so that's not an option.

**Comment by filimonov** [comment]
1) pid file is created only in daemon mode (so just add --daemon command line parameter if you really need that):
https://github.com/yandex/ClickHouse/blob/f1791e94e209b238b28a89c25e3a5f81882785a6/libs/libdaemon/src/BaseDaemon.cpp#L957-L958
2) folder for pid-file shoud exists i.e. run first 
```bash
mkdir -p /var/run/clickhouse-server/
```

**Comment by blinkov** [comment]
@PascalWithopf do you have any further questions?

**Comment by PascalWithopf** [comment]
@blinkov No, thanks for answering my questions.
