### ISSUE TITLE
Remove invalid mutation

### ISSUE THREAD

**Issue by simPod** [yandex/ClickHouse#3782]
I have mutation with `is_done = 0` that will never complete but clickhouse tries to execute it. Is there a way to drop such mutation? Thanks

**Comment by simPod** [comment]
Removed mutation txt file, just took a while

**Comment by ztlpn** [comment]
Currently it is only possible manually.

For non-replicated MergeTree:
1. `DETACH TABLE <table>`
2. Remove the `mutation_xxx.txt` file from the `/var/lib/data/<database>/<table>/` directory. Exact file name can be determined from the `mutation_id` column of the `system.mutations` table.
3. `ATTACH TABLE <table>`

For replicated tables:
* Remove the `/<path_to_table>/mutations/xxxxxxxxxx` znode from ZooKeeper. ZNode name can be determined from the `mutation_id` column of the  `system.mutations` table. DETACH/ATTACH is not needed in this case.

**Comment by ztlpn** [comment]
Reopening as this is a common request and we should implement a more convenient method to do it.

**Comment by simPod** [comment]
Kk, cool. But my MergeTree is not replicated and only thing I had to do was `rm mutation_xxx.txt` and then wait few minutes, no need for detaching table.

**Comment by blinkov** [comment]
@simPod do you have any further questions?

**Comment by ztlpn** [comment]
@blinkov don't close it yet :)

I'll close when an easy method to cancel a mutation will be implemented.

**Comment by ztlpn** [comment]
Available since 19.3.3
