### ISSUE TITLE
Does clickhouse-server need to run when I only use clickhouse-client to send data?

### ISSUE THREAD

**Issue by q0987** [yandex/ClickHouse#3787]
Hello all,

I have two machines(i.e. machine A and machine B). The clickhouse-server is running on machine A to accept queries and data insertion. I use clickhouse-client to send data constantly from machine B to machine A. During testing, I realized that the clickhouse-server process is also running on machine B and it takes 500MB memory space and a little CPU usage.

Question> The machine B is only used to send data to machine A. Can I stop the clickhouse-server on machine B to save resources?

Thank you

**Comment by alexey-milovidov** [comment]
Yes.

clickhouse-client doesn't need and doesn't use any clickhouse-server other than the server it is connected to.
