### ISSUE TITLE
Aggregate function running out of memory

### ISSUE THREAD

**Issue by karteek-gamooga** [yandex/ClickHouse#38]
Hi,

I'm creating a table containing 3 columns uid, ev and timestamp and running sequencematch function grouped by uid and searching for a pattern on events. The table has 10 million unique uids and 100 evs per uid, so a total of 1 billion rows. The query below is running out of memory(which is 8gb on the test machine). I understand from the docs that merge tree is sorted by the primary key in each part.

Is it guaranteed that a uid is present in a single part as it is part of the primary key? If so can we not call merge and insert for each part and not at the end and deallocate the data?

If uid is not guaranteed to be in the same part can you suggest a better alternative to achieve the below result.

Table:
CREATE TABLE ev ( uid String,  ev String,  t DateTime,  d Date) ENGINE = MergeTree(d, (uid, t, d), 8192)

Query:
SELECT count()  
FROM  
(  
    SELECT uid  
    FROM ev  
    GROUP BY uid  
    HAVING sequenceMatch('{"pattern":["ev1","ev2"]}')(t, ev)  
)   

Thanks

**Comment by alexey-milovidov** [comment]
GROUP BY doesn't take into account order of data in table, it keeps in memory all states of aggregate functions even when GROUP BY is by primary key.

The problem could be solved in following ways:

1. Split query to several parts by ranges of uid:
`WHERE uid < '8'`
`WHERE uid >= '8'`
and do UNION ALL.
(BTW it's strange that your uid column has type String.)

2. Filter set of uids by part of pattern. Write condition for ev1 or ev2 to WHERE.

    BTW, I don't understand what pattern `'{"pattern":["ev1","ev2"]}'` is. Maybe it is `'(?1)(?2)'`?
    For that simple pattern, you could proceed without seqenceMatch function.
    Look at https://clickhouse.yandex/reference_en.html#sequenceMatch%28pattern%29%28time,%20cond1,%20cond2,%20...%29

3. It is possible to enable "external aggregation" feature: writing temporary data to filesystem.
Write
    ```
    SET max_bytes_before_external_group_by = 4000000000;
    ```
But for 'sequenceMatch' function, amount of memory is not tracking correctly and it may not work.

**Comment by karteek-gamooga** [comment]
Thanks Alexey for your quick response. The uid is a string because it is typically a email id or some other unique identifier. Your first solution could work, I will try that out. The pattern matching is a little more complex than what sequenceMatch provides so i just quickly wrote a custom function. Regarding max_bytes_before_external_group_by i can confirm that any setting above 2 gb is not working and for a smaller value it is throwing the following error:
tcmalloc: large alloc 3515645734401048576 bytes == (nil) @                                                                                                                                                  
2016.06.30 12:35:42.677 [ 4 ] <Error> executeQuery: std::exception. Code: 1001, type: std::bad_alloc, e.what() = std::bad_alloc

**Comment by alexey-milovidov** [comment]
Commited fix for accounting of used memory for aggregate function sequenceMatch.
Scheduled for next release.
