### ISSUE TITLE
ALTER TABLE MODIFY COLUMN – Syntax error

### ISSUE THREAD

**Issue by simPod** [yandex/ClickHouse#3802]
Trying to run

```sql
ALTER TABLE `sensor_value` MODIFY COLUMN `value` Nullable(Decimal(18,4));
```

Returns `syntax error at or near "`"` Is the syntax really wrong? Seems to me compliant with docs https://clickhouse.yandex/docs/en/query_language/alter/#column-manipulations

**Comment by s-mx** [comment]
Hi. I checked on my machine and that's ok. Could you provide more info about server version? It would be great if you can write small ddl script to demonstrate that behavior.

**Comment by simPod** [comment]
Hi, sure!

`SELECT version()`
18.14.18

**Comment by simPod** [comment]
Hm, you're right. Tried to create minimal example and it works :/ Closing as cannot reproduce-'.
