### ISSUE TITLE
ANY LEFT JOIN RETURN ERROR

### ISSUE THREAD

**Issue by wuyanxing001** [yandex/ClickHouse#3810]
ClickHouse version:
ClickHouse client version 18.14.13.
Connecting to localhost:9000.
Connected to ClickHouse server version 18.14.13 revision 54409.

left table:
CREATE TABLE default.joinl ( id1 UInt8) ENGINE = Log
select * from joinl

SELECT *
FROM joinl 

┌─id1─┐
│   1 │
└─────┘

right table:
CREATE TABLE default.joinr ( id1 UInt8) ENGINE = Log
select * from joinr

SELECT *
FROM joinr 

┌─id1─┐
│   1 │
│   1 │
└─────┘

any left join SQL:
select * from joinl all left join joinr using(id1)

error message:
====>client log
Exception on client:
Code: 89. DB::Exception: Unknown compression method: 105: while receiving packet from localhost:9000, ::1

===>server log
2018.12.11 16:28:34.569414 [ 26 ] {a12fb0a1-4705-4e38-969c-10c2a698f568} <Error> executeQuery: Code: 9, e.displayText() = DB::Exception: Sizes of columns doesn't match: id1: 2, default.joinr.id1: 1, e.what() = DB::Exception (from [::1]:51902) (in query: select * from joinl all left join joinr using(id1)), Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x99ea536]
1. clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x22) [0x30873f2]
2. clickhouse-server(DB::Block::checkNumberOfRows() const+0x33c) [0x6ab1b3c]
3. clickhouse-server(DB::NativeBlockOutputStream::write(DB::Block const&)+0x51) [0x6ae74c1]
4. clickhouse-server(DB::TCPHandler::sendData(DB::Block const&)+0x41) [0x3090ad1]
5. clickhouse-server(DB::TCPHandler::processOrdinaryQuery()+0x48d) [0x30916cd]
6. clickhouse-server(DB::TCPHandler::runImpl()+0x8c0) [0x3094fc0]
7. clickhouse-server(DB::TCPHandler::run()+0x2b) [0x3095d9b]
8. clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x9b68c8f]
9. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x16a) [0x9b6906a]
10. clickhouse-server(Poco::PooledThread::run()+0x77) [0x9c85e47]
11. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x9c819b8]
12. clickhouse-server() [0xa3db80f]
13. /lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x7f25bb784184]
14. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f25bad9f03d]

**Comment by blinkov** [comment]
Duplicate for #3779
