### ISSUE TITLE
Ignore broken messages from Kafka

### ISSUE THREAD

**Issue by levonet** [yandex/ClickHouse#3814]
I want to ignore broken messages from Kafka if I have some problems #2381
```
018.10.24 14:56:08.751404 [ 79 ] <Error> void DB::StorageKafka::streamThread(): Code: 27, e.displayText() = DB::Exception: Cannot parse input…
```

Otherwise you have to wait until the data in the topic to be expired or you have to edit them by hand.

**Comment by den-crane** [comment]
kafka engine does not respect input_format_allow_errors_ratio input_format_allow_errors_num #2171 #2675

**Comment by blinkov** [comment]
Let's keep only #2675 for this.
