### ISSUE TITLE
Clickhouse query, 5 tables union all query vs 1 union sparse table

### ISSUE THREAD

**Issue by denisovser1406** [yandex/ClickHouse#3817]
Hello,

I have a question regarding clickhouse performance.

Situation: We have 5 different datas and we have a similar column 'A' in each of the data.

1. We create 5 tables using MergeTable (around 20 columns in each table).
We need to find some value in each table in column 'A'.
Query: WHERE A = {value} ORDER BY {time}  LIMIT {n} or GROUP BY A using UNION ALL.

2. We create 1 table using UNION MergeTable (around 50 columns in total).
Query: WHERE A = {value} ORDER BY {time} LIMIT {n} or GROUP BY A.

Which method will give better performance? 1st method should traverse among all tables, however speed of clickhouse is fast, so will it be the problem? In 2nd method among 50 columns 20 are full of data and rest 30 contains NULL values or empty values. Will it affect the speed of query?
I dont know all of ClickHouse details, so I want your recommendation on which way is better to use.

Thank you all,

Have a nice day.

**Comment by blinkov** [comment]
@denisovser1406 I think we have discussed this on email, do you have any further questions?

**Comment by denisovser1406** [comment]
Yes,thank you for your help!


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Ivan Blinkov <notifications@github.com> Date: 12/21/18  20:03  (GMT+09:00) To: yandex/ClickHouse <ClickHouse@noreply.github.com> Cc: denisovser1406 <denisovser1406@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [yandex/ClickHouse] Clickhouse query, 5 tables union all query vs 1 union sparse table (#3817) 
@denisovser1406 I think we have discussed this on email, do you have any further questions?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/yandex/ClickHouse","title":"yandex/ClickHouse","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/yandex/ClickHouse"}},"updates":{"snippets":[{"icon":"PERSON","message":"@blinkov in #3817: @denisovser1406 I think we have discussed this on email, do you have any further questions?"}],"action":{"name":"View Issue","url":"https://github.com/yandex/ClickHouse/issues/3817#issuecomment-449358954"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/yandex/ClickHouse/issues/3817#issuecomment-449358954",
"url": "https://github.com/yandex/ClickHouse/issues/3817#issuecomment-449358954",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by sanathkumarbs** [comment]
Could we get some insights that were shared over the email? Which option did you choose and was one outperforming the other?

**Comment by mayank-pant** [comment]
@blinkov @denisovser1406 Can you please post here what you guys shared in that mail. I have similar use case where i want to store transaction, app event, and many more events like pin_change, refferral events(its a credit card company) in clickhouse db each having only one common value that is customer_id. I am confused whether to store seperate event to its own table or serialize/flatten all the events in one table.

**Comment by sananguliyev** [comment]
Same here. Could you share the  insights that were shared over the email?
