### ISSUE TITLE
ARRAY JOIN and arrayJoin memory limits

### ISSUE THREAD

**Issue by bicubic** [yandex/ClickHouse#3831]
I am running the following query on a table with ~50M rows Where `vec` is an array of integers. It yields the this error: `DB::Exception: Memory limit (for query) exceeded: would use 9.32 GiB`. I have tried using arrayJoin with the same outcome.  

Are there any workarounds that could execute this query on disk? Or do I need to restructure my table to denormalize across `vec`? As powerful as the array functions are, being purely in-memory is a very limiting requirement. 

```SQL
SELECT vec, author, count(*) as ct FROM(
    SELECT * FROM messages
    ARRAY JOIN vec
)
GROUP BY vec, author
ORDER by author, vec DESC
LIMIT 20 by author
```

**Comment by filimonov** [comment]
Did you enable on disk group by and order by? 

Check those settings:
max_bytes_before_external_sort
max_bytes_before_external_group_by
distributed_aggregation_memory_efficient
