### ISSUE TITLE
Data Insert error from CSV

### ISSUE THREAD

**Issue by DivyaRao30** [yandex/ClickHouse#3847]
Trying to load data into the table and its throwing error which is not in specific

Table:

CREATE TABLE insightbasev2.company_temp (
a UInt32,
b String,
c String,
.....
......
) ENGINE = MergeTree PARTITION BY state_province_code
ORDER BY
domain SETTINGS index_granularity = 8192

Insert statement:

clickhouse-client -h1.0.1.2.3 -u default --password xxxx --query="INSERT INTO insightbasev2.company_temp FORMAT CSV" </temp/company_1/3.csv

Error:

Syntax error: failed at position 1:

clickhouse-client -h1.0.1.2.3 -u default --password xxxx --query="INSERT INTO insightbasev2.company_temp FORMAT CSV" </temp/company_1/4.csv

Expected one of: CREATE, ATTACH, DETACH, DROP, SHOW, SELECT, WITH, DESC, SYSTEM query, AST, list of elements, ALTER query, ALTER TABLE, CREATE TABLE or ATTACH TABLE query, Query with output, SHOW PROCESSLIST query, SHOW PROCESSLIST, RENAME query, RENAME TABLE, SELECT query, possibly with UNION, SET query, SHOW [TEMPORARY] TABLES|DATABASES [[NOT] LIKE 'str'], EXISTS or SHOW CREATE query, SELECT query, subquery, possibly with UNION, USE query, SELECT subquery, CHECK TABLE, DESCRIBE query, DROP query, EXISTS, TRUNCATE, INSERT query, INSERT INTO, KILL QUERY query, KILL QUERY, OPTIMIZE query, OPTIMIZE TABLE, SELECT query, DESCRIBE, Query, USE, SET

any suggestion will be appreciated

**Comment by filimonov** [comment]
Don't you wrap whole command in some another bash call? (in that case double quote char can disappear, and you will get the similar error).


In case of direct call everything works.

```
CREATE DATABASE insightbasev2;

CREATE TABLE insightbasev2.company_temp
(
    a UInt32, 
    b String, 
    c String, 
    state_province_code String, 
    domain String
)
ENGINE = MergeTree
PARTITION BY state_province_code
ORDER BY domain
SETTINGS index_granularity = 8192;

➜ echo '1,2,3,4,5' > /tmp/company_13.csv
➜ clickhouse-client -h127.0.0.1 --query="INSERT INTO insightbasev2.company_temp FORMAT CSV"  < /tmp/company_13.csv

SELECT *
FROM insightbasev2.company_temp 

┌─a─┬─b─┬─c─┬─state_province_code─┬─domain─┐
│ 1 │ 2 │ 3 │ 4                   │ 5      │
└───┴───┴───┴─────────────────────┴────────┘

1 rows in set. Elapsed: 0.003 sec. 
```

**Comment by DivyaRao30** [comment]
Hi ,

I do wrap the commands in single line.

Understood , but I have exported the file from another database and using
it as input file for clickhouse which is in cvs format.

When I tried to load the input file data into clickhouse getting the
mentioned error.

Input file is huge like millions.

Not sure whether I explained my query correctly !

**Comment by ztlpn** [comment]
The error
```
Syntax error: failed at position 1:

clickhouse-client -h1.0.1.2.3 -u default --password xxxx --query="INSERT INTO insightbasev2.company_temp FORMAT CSV" </temp/company_1/4.csv

Expected one of: 
```
will appear if you enter the `clickhouse-client -h...` command not in the shell prompt but in the `clickhouse-client` prompt.

Can you show the exact shell command that you use to insert data?

**Comment by DivyaRao30** [comment]
I was not entering it in the shell instead I was doing it in clickhouse-client prompt. 

Corrected it 

Thanks for the suggestions.
