### ISSUE TITLE
How to  create view on cluster and need not to kown how much node it has

### ISSUE THREAD

**Issue by MrWhiteL** [yandex/ClickHouse#3858]

**Comment by ztlpn** [comment]
Hi, can you please state your question with more detail?

You can create views (as well as ordinary tables) on a cluster that you configured in the `<remote_servers>` section of `config.xml` with the [ON CLUSTER command](https://clickhouse.yandex/docs/en/query_language/create/#distributed-ddl-queries-on-cluster-clause).

**Comment by MrWhiteL** [comment]
There is two nodes in my cluster , I want  to create view by my program on one node and need not to connect to another one to execute it once more.  create table can use " on cluster ck_cluster_162 " but create view how?
![image](https://user-images.githubusercontent.com/32286846/50195893-ec30e980-037b-11e9-89bc-5de94721f0b4.png)
