### ISSUE TITLE
Materialized view to count combinations of rows: Summing vs. AggregatingMergeTree?

### ISSUE THREAD

**Issue by heyciao** [yandex/ClickHouse#3866]
Hi
Could you please tell me, in the context of counting rows that have a certain combination of values in their columns, what's the difference between the table engines "SummingMergeTree" and "AggregatingMergeTree"? I see that I can use both engines to achieve the same, but maybe one is better than the other?
Example:

1)I create my base table:
```
create table test_tbl
(
col1 UInt8
,col2 UInt8
,col3 UInt8
,someval String
)
engine=MergeTree
partition by(col1)
order by (col2,col3)
```
2)I insert some rows into the base table:
```
insert into test_tbl values (1,1,1,'aaa')

insert into test_tbl values (1,2,1,'bbb')

insert into test_tbl values (1,1,1,'ccc')

insert into test_tbl values (1,1,3,'ddd')

insert into test_tbl values (1,1,3,'ddd')

insert into test_tbl values (1,1,3,'ddd')
```
3a)I create a materialized view using SummingMergeTree:
```
CREATE MATERIALIZED VIEW test_mvw_summing
ENGINE = SummingMergeTree()
partition by(col1)
order by (col1,col2,col3)
POPULATE
AS
select col1,col2,col3, toUInt64(1) as "cnt"
from test_tbl
```
3b)I create a similar materialized view but this time using AggregatingMergeTree:
```
CREATE MATERIALIZED VIEW test_mvw_aggregating
ENGINE = AggregatingMergeTree()
partition by(col1)
ORDER BY (col1,col2,col3)
POPULATE
AS
select col1,col2,col3, countState() as "cnt"
from test_tbl
group by col1,col2,col3
```
4)I force the "merge" of the materialized views:
```
OPTIMIZE TABLE test_mvw_summing FINAL

OPTIMIZE TABLE test_mvw_aggregating FINAL
```
4)I query both tables => they both seem to deliver the same results:
```
SELECT col1,col2,col3,sum(cnt)
FROM test_mvw_summing
group by col1,col2,col3

select col1,col2,col3, countMerge(cnt)
from test_mvw_aggregating
group by col1,col2,col3
```

I am inserting hundreds of millions into my base table and currently I am using the engine SummingMergeTree for the materialized view, and when the "merge" starts running in the background I see (in "system.merges") a lot of activity going on involving the materialized view => maybe using the engine "AggregatingMergeTree" would be more effective?

Thank you

**Comment by heyciao** [comment]
Replaced the big SummingMergeTree materialized view with an AggregatingMergeTree and ran the usual workload for a day => the average hourly amount of inserted records and queries that ran against the matview is the same as with SummingMergeTree => no difference => closing this ticket.
Cheers

**Comment by abraithwaite** [comment]
I'm actually curious about the differences too.  Did you ever find out?

**Comment by qbit-git** [comment]
I found AggregatingMergeTree take effect right row when insert data to base table, but SummingMergeTree  need OPTIMIZE.
