### ISSUE TITLE
CollapsingMergeTree bug ?

### ISSUE THREAD

**Issue by luongdieu86** [yandex/ClickHouse#3869]
I'm using clickhouse on docker from:
>https://hub.docker.com/r/yandex/clickhouse-server/

I'm create test table as below:
CREATE TABLE test3
`(`
`    UserID UInt64,`
`    PageViews UInt8,`
`    Duration UInt8,`
`    Sign Int8`
`)`
`ENGINE = CollapsingMergeTree(Sign)`
`ORDER BY UserID;`

And insert data to table:

`INSERT INTO test3 VALUES (1, 1, 1, 1);`
`INSERT INTO test3 VALUES (1, 2, 2, 1),(1, 3, 3, 1),(1, 3, 3, -1),(1, 2, 2, -1);`
`INSERT INTO test3 VALUES(1, 4, 4, -1)`

Result as

SELECT *
FROM test3

┌─UserID─┬─PageViews─┬─Duration─┬─Sign─┐
│      1 │         2 │        2 │    1 │
│      1 │         3 │        3 │    1 │
│      1 │         3 │        3 │   -1 │
│      1 │         2 │        2 │   -1 │
└────────┴───────────┴──────────┴──────┘
┌─UserID─┬─PageViews─┬─Duration─┬─Sign─┐
│      1 │         4 │        4 │   -1 │
└────────┴───────────┴──────────┴──────┘
┌─UserID─┬─PageViews─┬─Duration─┬─Sign─┐
│      1 │         1 │        1 │    1 │
└────────┴───────────┴──────────┴──────┘

I'm execute OPTIMIZE to test3.
All data in table test3 deleted.

According to document: 
[https://clickhouse.yandex/docs/en/single/#collapsingmergetree](url)

> CollapsingMergeTree asynchronously deletes (collapses) pairs of rows if all of the fields in a row are equivalent excepting the particular field Sign which can have 1 and -1 values. Rows without a pair are kept

It's mean that below record have to be kept after data parts are merge:

┌─UserID─┬─PageViews─┬─Duration─┬─Sign─┐
│      1 │         4 │        4 │   -1 │
└────────┴───────────┴──────────┴──────┘
┌─UserID─┬─PageViews─┬─Duration─┬─Sign─┐
│      1 │         1 │        1 │    1 │
└────────┴───────────┴──────────┴──────┘

is it an issue ? or my understand and test code is not correct.
Thank you

**Comment by den-crane** [comment]
CollapsingMergeTree(**Sign**)
ORDER BY **UserID**;

INSERT INTO test3 VALUES (1 .. 1);
INSERT INTO test3 VALUES (1 .. 1),(1 .. 1),(1 .. -1),(1 .. -1);
INSERT INTO test3 VALUES(1 .. -1)

1 + 1 + 1 - 1 - 1 -1

https://clickhouse.yandex/docs/en/operations/table_engines/versionedcollapsingmergetree/#algorithm

When ClickHouse merges data parts, it deletes each pair of rows having **the same primary key** and version and different Sign. The order of rows does not matter.

**Comment by luongdieu86** [comment]
Thank you, I got it.

> PRIMARY KEY - The primary key if it differs from the sorting key.
> By default the primary key is the same as the sorting key (which is specified by the ORDER BY clause). Thus in most cases it is unnecessary to specify a separate PRIMARY KEY clause.
