### ISSUE TITLE
Clickhouse lags at each query

### ISSUE THREAD

**Issue by DChistyakov** [yandex/ClickHouse#3871]
Hi everyone!
Well, I have 2 servers located in the same place with about 1-2ms ping between each other: A and B. Clickhouse server with basic configuration is located on the A serever. 
I do 2 same queries: "SHOW databases". 
1. clickhouse-cli @ A server to localhost 
2. clickhouse-cli @ B server to A server:9000

Server A: 0.002 sec. 
Server B: 0.19 sec.

Next "SELECT * FROM table": 
1. clickouse-cli @ A server to localhost - 8 rows in set. Elapsed: 0.003 sec. 
2. clickouse-cli @ B server to A server:9000 - 8 rows in set. Elapsed: 0.15 sec.

And so on.. The same result I have while try to execute query at A server from my PC (about 0.19 sec). So each query executed from remote source has at least 0.1 sec. 
It looks like latency but too much.. anyway I suppose that the latency shoud not affect the executuion time. So the question is: what do I do wrong? 
Thanks in advance!

**Comment by den-crane** [comment]
Maybe a some clickhouse-client issue when it runs on machine without some ch configs.

Try curl
curl -s -w "%{time_total}\n" http://user:password@serverA:8123/?query=select%201

**Comment by DChistyakov** [comment]
dc@severA:~$ curl -s -w "%{time_total}\n" http://94.130.133.182:8123/?query=select%201
1
0.001034

dc@serverB:~$ curl -s -w "%{time_total}\n" http://94.130.133.182:8123/?query=select%201
1
0.180937

**Comment by den-crane** [comment]
Looks like a network issue.

try
ping -s 1500 serverA

**Comment by DChistyakov** [comment]
Yes, looks like it is! Thank you very much. Hope it will solve after hardware replace.
