### ISSUE TITLE
Wrong folder "preprocessed" link

### ISSUE THREAD

**Issue by angeldestroyer** [yandex/ClickHouse#3892]
Hi!
When update from 18.16.0 to 18.16.1:
```
...
ln: не удалось создать символьную ссылку '/etc/clickhouse-server/preprocessed': Файл существует 
...
```
I use non-default data path:
```XML
# from local.xml in clickhouse-server/config.d
<path replace="replace">/mnt/data/clickhouse/</path>
```
but,
```bash
# ls -la /etc/clickhouse-server | grep preprocessed
lrwxrwxrwx   1 clickhouse       clickhouse          40 дек 19 11:27 preprocessed -> /var/lib/clickhouse/preprocessed_configs
```

maybe because of this #2443?

Is it possible to add similar for dictionaries?
```XML
# from local.xml in clickhouse-server/config.d
 <dictionaries_config replace="replace">/etc/clickhouse-server/dictionaries/*_dictionary.xml</dictionaries_config>     
```
in this folder i found ```*_dictionary.xml``` and ```*dictionary-preprocessed.xml```. 
At the same time, ```dictionaries_<name>_dictionary.xml``` is present in ```/mnt/data/clickhouse/preprocessed_configs```.
I would like to see only dictionaries in folder from config, without ```*-preprocessed.xml```. 
it is possible?

p.s. Sorry, my fault, the preprocessing-link already existed from previous version. But still points to the wrong folder.

**Comment by proller** [comment]
/var/lib/clickhouse/preprocessed_configs now contains all preprocessed config including from /dictionaries/ dir. 
All '/' in path relative to  etc/clickhouse-server/ changed to '_'  (to avoid too deep tree in preprocessed dir)

Now you can delete all *dictionary-preprocessed.xml in /etc/clickhouse-server/dictionaries/ - they from old versions and not updated now.
