### ISSUE TITLE
Load data from mysql timeout

### ISSUE THREAD

**Issue by sliontc** [yandex/ClickHouse#3893]
Hi, when I load data from MySQL using MySQL engine, once the data is more than 6 million, it always turns out read timeout exception. See the screenshot.

![tim 20181221155410](https://user-images.githubusercontent.com/6959147/50331328-4034fd00-0539-11e9-8513-26b8adbd1bc9.png)

I have set the timeout config in MySQL to 30 minutes.

**Comment by blinkov** [comment]
@sliontc it sounds like the timeout you see is not between ClickHouse and MySQL, but between your desktop client and ClickHouse.

What happens if you open http://192.168.1.37:8123/ping in web browser?

**Comment by sliontc** [comment]
It returns "Ok.". Seem no errors.

**Comment by sliontc** [comment]
![qq20181221-214843](https://user-images.githubusercontent.com/6959147/50345479-37a8ea80-056a-11e9-8eff-e5557adb875d.png)

**Comment by sliontc** [comment]
Yes, it should be the db client issue. When I load data in local clickhouse-client, no such timeout present, as shown below:
![qq20181221-220616](https://user-images.githubusercontent.com/6959147/50346350-15fd3280-056d-11e9-999c-db249ade876a.png)

**Comment by sliontc** [comment]
Then is it possible to fix it? Or are there related configuration in clickhouse?

**Comment by sliontc** [comment]
I have set the connect_timeout and keep_alive_timeout to:
    <keep_alive_timeout>30</keep_alive_timeout>
    <connect_timeout>60</connect_timeout>
But no lucky.

**Comment by blinkov** [comment]
@sliontc What is this client you are trying to use? Looks like Eclipse? If yes, it's probably using JDBC driver so you should check it's settings.

**Comment by sliontc** [comment]
I'm using DBeaver Enterprise version, the website is [https://dbeaver.com/](https://dbeaver.com/)

**Comment by alexey-milovidov** [comment]
Is the issue still relevant? Did you ask DBeaver developers about it?

**Comment by den-crane** [comment]
CH JDBC driver overrides server settings.
And set own parameter   socket_timeout = 30000 (30s).

But of course DBeaver allows to fix it for a connection 
`Under the Advanced tab, you can configure advanced connections settings, e.g., Character Coding.`
And set large socket_timeout.

**Comment by oxyii** [comment]
@sliontc @blinkov @alexey-milovidov It looks like ClickHouse is trying to get **ALL** the data from the remote table, and then execute the proposed query. This works fine as long as there are few rows in the remote table (less that 1M for example). But if we have something about 100M rows then timeout even if I try to request just one row.

**Comment by sliontc** [comment]
Yes, that's the point.
