### ISSUE TITLE
How to get last inserted row fast?

### ISSUE THREAD

**Issue by q0987** [yandex/ClickHouse#3901]
Hello,

Since ClickHouse doesn't support `last` operation, I used the following query to obtain one of the most recently inserted row from table.

As you can see from the query result, the `last` operation takes almost **100** seconds.
I ran the query @Fri Dec 21 08:55:12 CST 2018 and all data import had been done yesterday 16:00PM.
I assume all the merge operation is done.

Question> Is there a way that I can improve the `last` operation query performance?

Thank you

-------------------------------------------------------------------------------------------------------
```
SELECT
    'MyTable',
    date,
    date_time,
    timestamp,
    symbol
FROM default.MyTable
WHERE timestamp =
(
    SELECT max(timestamp)
    FROM default.MyTable
    WHERE date =
    (
        SELECT max(max_date)
        FROM system.parts
        WHERE (table = 'MyTable') AND (database = 'default')
    )
)
LIMIT 1
```

┌─'MyTable'─┬───────date─┬───────────date_time─┬───────────timestamp─┬─symbol─────────┐
│     MyTable   │ 2018-12-20 │ 2018-12-20 15:15:00 │ 1545340500087945622 │ abc │
└───────────────┴────────────┴─────────────────────┴─────────────────────┴────────────────┘

1 rows in set. Elapsed: **98.859** sec. Processed 1.41 billion rows, 52.97 GB (14.24 million rows/s., 535.76 MB/s.)

------------------------------------------------------------------------------------------------------------

 :) select count(*) from default.MyTable where date='2018-12-20';

```
SELECT count(*)
FROM default.MyTable
WHERE date = '2018-12-20'
```

┌────count()─┐
│ 5680233918 │
└────────────┘

1 rows in set. Elapsed: 0.603 sec. Processed 5.68 billion rows, 11.36 GB (9.42 billion rows/s., 18.84 GB/s.)

----------------------------------------------------------------------------------------------------------
When I ran the query, the load average of this machine is around 3.
Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz
processor       0 : 63
memory: 512GB
4x 2TB 7200 RPM SAS 12Gb/s HDD

------------------------------------------------------------------------------------------------------------------------
```
/var/lib/clickhouse/data/default/MyTable
$ du -hsc 20181220_2*
63G     20181220_23236_26182_5
2.8G    20181220_26183_26311_3
3.2G    20181220_26312_26473_3
19G     20181220_26474_27512_4
3.4G    20181220_27513_27669_3
3.0G    20181220_27670_27809_3
3.1G    20181220_27810_27952_3
663M    20181220_27953_27983_2
608M    20181220_27984_28011_2
610M    20181220_28012_28039_2
609M    20181220_28040_28067_2
17M     20181220_28068_28068_0
100G    total

$ du -hsc 20181219_*
59G     20181219_18344_21930_5
15G     20181219_21931_22632_4
3.0G    20181219_22633_22774_3
3.3G    20181219_22775_22930_3
3.2G    20181219_22931_23078_3
2.9G    20181219_23079_23218_3
114M    20181219_23219_23224_1
118M    20181219_23225_23230_1
93M     20181219_23231_23235_1
86G     total
```
ClickHouse client version 18.6.0.
Connected to ClickHouse server version 18.6.0 revision 54401.

**Comment by den-crane** [comment]
1. It's completely wrong task for CH. CH is not an OLTP database. 
Just save somehow the last inserted time in additional table from client.

2. you missed date = ... predicate in the first query.

```
SELECT tx,...,
FROM MyTable
preWHERE (access_day , access_time) in
( SELECT access_day, max(access_time)
  FROM MyTable
  preWHERE access_day = (SELECT max(max_date) FROM system.parts 
         WHERE (table = 'MyTable') AND (database = 'default'))
  group by access_day     
) LIMIT 1;
```
1 rows in set. Elapsed: **0.374 sec. Processed 138.44 million rows**

vs
```
SELECT  tx,...,
FROM MyTable
preWHERE access_time =
( SELECT max(access_time)
  FROM MyTable
  preWHERE access_day = (SELECT max(max_date) FROM system.parts 
         WHERE (table = 'MyTable') AND (database = 'default'))
  group by access_day     
) LIMIT 1;
```
1 rows in set. Elapsed: **82.801 sec. Processed 28.50 billion rows**


SELECT count() FROM MyTable
┌─────count()─┐
│ 53805510636 │
└─────────────┘
1 rows in set. Elapsed: 33.192 sec. Processed 53.81 billion rows

**Comment by q0987** [comment]
Hello den-crane,

> 2>CH unable to find max(timestamp) from index so it will scan all records.

`ENGINE = MergeTree PARTITION BY date ORDER BY (date, symbol, timestamp) SETTINGS index_granularity = 8192
`
The table is created by the index of (date, symbol, timestamp).
In this case, is it still true that Clickhouse cannot find the max(timestamp) by index?

`3> maybe you missed date = ... predicate in the first query.`

```
preWHERE (access_day , access_time) in
VS
preWHERE access_time =
```
Using the tulpe of (date, timestamp) does improve the query performance.

Thank you

**Comment by den-crane** [comment]
>In this case, is it still true that Clickhouse cannot find the max(timestamp) by index?

It does not matter how was created a table. The only way for CH to find max -- to scan everything. There is no such optimization -- to use index for max -- yet.

create table mx(a Int64) engine=MergeTree order by a;
insert into mx select number from numbers(1000000);
select max(a) from mx;
1 rows in set. Elapsed: 0.006 sec. **Processed 1.00 million rows,**

------------

>Using the tulpe of (date, timestamp) does improve the query performance.

It's not because of tuple
**PARTITION BY date** 
if you execute where timestamp =.. CH scans all partitions.
if you execute where date = ... and timestamp =.. CH scans only one partition.

------------

PARTITION BY **date** ORDER BY (**date,** symbol, timestamp)
order by date has no sense, because it's only one date value in partition -- nothing to sort.

try to replace it with
PARTITION BY **date** ORDER BY (symbol, timestamp)
 
------------

>Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz
>memory: 512GB
>4x 2TB 7200 RPM SAS 12Gb/s HDD

from my perspective it's very unbalanced system, only 4 SAS disk slowdown the system

**Comment by den-crane** [comment]
And BTW, you can use argMax & tuple if you need only 1 row
```
    SELECT argMax(('MyTable', date, date_time, timestamp, symbol), timestamp)
    FROM default.MyTable
    WHERE date =
    (
        SELECT max(max_date) FROM system.parts
        WHERE (table = 'MyTable') AND (database = 'default')
    )

```

**Comment by q0987** [comment]
I will make a change based on your suggestion.

Thank you.
