### ISSUE TITLE
MySQL table function not found

### ISSUE THREAD

**Issue by wenxingxing** [yandex/ClickHouse#3927]
Is MySQL table function removed?

```
CREATE TABLE test
ENGINE = MergeTree
ORDER BY id AS
SELECT *
FROM MySQL('localhost', 'test', 'test', 'reader', 'qwerty') 

Received exception from server (version 18.14.18):
Code: 46. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Unknown table function MySQL. 
```

version of clickhouse:

```shell
$ clickhouse-client --version
ClickHouse client version 18.14.18.
```

**Comment by blinkov** [comment]
Try `mysql` in lower case.

**Comment by den-crane** [comment]
Check that your CH server compiled with mysql

```
select * from system.build_options where name like 'USE_MYSQL'

┌─name──────┬─value─┐
│ USE_MYSQL │ 1     │
└───────────┴───────┘
```

**Comment by den-crane** [comment]
actually table functions are case sensitive 

SELECT *
FROM MySQL('x', 'x', 'x', 'x', 'x')
Received exception from server (version 18.14.18):
Code: 46. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Unknown table function MySQL.

SELECT *
FROM mysql('x', 'x', 'x', 'x', 'x')

Received exception from server (version 18.14.18):
Code: 1000. DB::Exception: Received from localhost:9000, ::1. DB::Exception: mysqlxx::ConnectionFailed: Unknown MySQL server host 'x' (-2) ((nullptr):0).

**Comment by wenxingxing** [comment]
@den-crane @blinkov  I've tried the `mysql` before `MySQL`, getting the same answer.

I'll tried it tomorrow, thank's for ur reply, happy new year!

**Comment by den-crane** [comment]
then check mysql is supported by your CH server

select * from system.build_options where name like 'USE_MYSQL'
```
┌─name──────┬─value─┐
│ USE_MYSQL │ 1     │
└───────────┴───────┘
```
mysqllib is statically linked to CH binary.

**Comment by wenxingxing** [comment]
looks like mysqllib is not built with clickhouse
```
SELECT *
FROM system.build_options 
WHERE name LIKE 'USE_MYSQL'

┌─name──────┬─value─┐
│ USE_MYSQL │       │
└───────────┴───────┘
```

**Comment by wenxingxing** [comment]
I'll rebuild it

**Comment by wenxingxing** [comment]
solved, thanks!

**Comment by lostsnow** [comment]
```
clickhouse :) CREATE TABLE xxx ENGINE = MergeTree ORDER BY id AS SELECT * FROM MySQL('xxx', 'xxx', 'xxx', 'xxx', 'xxx');

CREATE TABLE xxx
ENGINE = MergeTree
ORDER BY id AS
SELECT *
FROM MySQL('xxx', 'xxx', 'xxx', 'xxx', 'xxx') 

Received exception from server (version 19.1.6):
Code: 46. DB::Exception: Received from 10.11.6.2:9000. DB::Exception: Unknown table function MySQL. 

0 rows in set. Elapsed: 0.003 sec. 
```

```
clickhouse :) select * from system.build_options where name like 'USE_MYSQL'                                                                                              

SELECT *
FROM system.build_options 
WHERE name LIKE 'USE_MYSQL'

┌─name──────┬─value─┐
│ USE_MYSQL │ 1     │
└───────────┴───────┘

1 rows in set. Elapsed: 0.005 sec. 
```

**Comment by lostsnow** [comment]
My fault, DB permission configuration is incorrect.
