### ISSUE TITLE
Low resource usage but low query performance.

### ISSUE THREAD

**Issue by seven7777777** [yandex/ClickHouse#3939]
Hi, I am having the similar situation. Low cpu/mem/io usage but really low performance.it's my table create sql:
CREATE TABLE met430_base ( created_date Date DEFAULT today(),  created_at DateTime DEFAULT now(),  id Int32,  time String,  uuid String,  dep String,  sevice String,  idc String,  cpuload1 Float64,  cpuload2 Float64,  cpuload3 Float64,  cpuload4 Float64,  cpuload5 Float64,  cpuload6 Float64,  cpuload7 Float64,  cpuload8 Float64,  diskusage1 Float64,  diskusage2 Float64,  diskusage3 Float64,  diskusage4 Float64,  diskusage5 Float64,  diskusage6 Float64,  diskusage7 Float64,  diskusage8 Float64,  memory1 Float64,  memory2 Float64,  memory3 Float64,  memory4 Float64,  memory5 Float64,  memory6 Float64,  memory7 Float64,  memory8 Float64,  network1 Float64,  network2 Float64,  network3 Float64,  network4 Float64,  network5 Float64,  network6 Float64,  network7 Float64,  network8 Float64,  temp1 Float64,  temp2 Float64,  temp3 Float64,  temp4 Float64,  temp5 Float64,  temp6 Float64,  temp7 Float64,  temp8 Float64,  fopen1 Float64,  fopen2 Float64,  fopen3 Float64,  fopen4 Float64,  fopen5 Float64,  fopen6 Float64,  fopen7 Float64,  fopen8 Float64) ENGINE = MergeTree(created_date, (uuid, created_at), 8192)

CREATE TABLE met430 as met430_base ENGINE = Distributed(logs, mdb, met430_base, rand())

8 nodes: 80 x Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz         MEM:300GiB
2 clickhouse-servers on 1 node.
clusters: sharding:8.   repica:2
dataset:  met430 with:22 billions rows, 

query:
select idc,sum(cpuload1*8) ,count(*) from   mdb.met430  group by idc limit 1

it took at least 80s  with almost no resource consumption.

I wonder if there is some settings or configures to make clickhouse-server use resource as much as possible  to improve the  query performance  and reduce time cost.

thanks.

**Comment by TH-HA** [comment]
Hello 
We had a similar issue where queries were slow without resource usage (CPU and IO ). In our context the issue was related to a bad partitioning schema leading to too many files on nodes. In this case CH was spending all the time opening/closing files ( and i 'm just guessing but the file system was saturated). 
Do a simple math  , number of col * number of part ( which need to be retreived from the system.part as partition can be split ). If it reach millions you may face the same issue. 

Also, a good KPI is the amount of system-cpu-time which was large compare to normal workload.

I hope that help

**Comment by den-crane** [comment]
Can you show the output from cl-client with processed stats for one shard

select idc,sum(cpuload18) ,count() from mdb. met430_base group by idc limit 1

If you have huge number of idc, huge results need to be transferred (so it maybe a network is a bottleneck) to a node query-initiator and then the initiator needs to do final aggregation.

**Comment by seven7777777** [comment]
@den-crane  @TH-HA   
Thanks for your reply and advice.  I tried to modify my sort key, and I really works for me. 
Best regards and happy new year.

**Comment by nickevin** [comment]
@seven7777777 I met the same problem, I have a table just like met430_base? so, how did you modify sort key on this met430_base table? thanks.
