### ISSUE TITLE
[Question] Accumulation data in Distributed table

### ISSUE THREAD

**Issue by igor-sh8** [yandex/ClickHouse#3941]
Hello. 
I have a cluster of four servers with two shards and two replicas in each shard. I have ReplicatedSummingMergeTree:
`CREATE TABLE db1.test_shard( Date Date,  Col1 Int32,  Col2 Int32,  Col3 Int32,  Col4 Int32,  Col5 Int32,  Col6 Int32,  Col7 Int32,  Col8 Int32,  Col9 Int32,  Col10 Int32,  Col11 Int32,  Col12 Int32,  Col13 Int32,  Col14 Int32,  Col15 Int32,  Col16 Int32,  Col17 Int32,  Col18 Int32,  Col19 Int32,  Col20 Int32,  Col21 Int32,  Col22 Int32,  Col23 Int32,  Col24 Int32,  Val1 Int64,  Val2 Int64,  Val3 Int64,  Val4 Int64,  Val5 Float64,  Val6 Float64,  Val7 Float64,  Val8 Float64,  Val9 Float64,  Val10 Float64) ENGINE = ReplicatedSummingMergeTree('/clickhouse/tables/{shard}/test_shard', '{replica}', Date, (Date,  Col1,  Col2,  Col3,  Col4,  Col5,  Col6,  Col7,  Col8,  Col9,  Col10,  Col11,  Col12,  Col13,  Col14,  Col15,  Col16,  Col17,  Col18,  Col19,  Col20,  Col21,  Col22,  Col23,  Col24), 8192, ( Val1,  Val2,  Val3,  Val4,  Val5,  Val6,  Val7,  Val8,  Val9,  Val10))`
and distributed table:
`CREATE TABLE db1.test( Date Date,  Col1 Int32,  Col2 Int32,  Col3 Int32,  Col4 Int32,  Col5 Int32,  Col6 Int32,  Col7 Int32,  Col8 Int32,  Col9 Int32,  Col10 Int32,  Col11 Int32,  Col12 Int32,  Col13 Int32,  Col14 Int32,  Col15 Int32,  Col16 Int32,  Col17 Int32,  Col18 Int32,  Col19 Int32,  Col20 Int32,  Col21 Int32,  Col22 Int32,  Col23 Int32,  Col24 Int32,  Val1 Int64,  Val2 Int64,  Val3 Int64,  Val4 Int64,  Val5 Float64,  Val6 Float64,  Val7 Float64,  Val8 Float64,  Val9 Float64,  Val10 Float64) ENGINE = Distributed(cluster1, db1, test_shard, cityHash64(Date,  Col1,  Col2,  Col3,  Col4,  Col5,  Col6,  Col7,  Col8,  Col9,  Col10,  Col11,  Col12,  Col13,  Col14,  Col15,  Col16,  Col17,  Col18,  Col19,  Col20,  Col21,  Col22,  Col23,  Col24))`

I insert into distributed table something about 15 mln records per minute. And sometimes I see in file system of my OS that such distributed table starts to grow. As I understand, inserts records into replicated tables (clickhouse internal mechanism) are slower then inserts into distributed table. But the servers did not reached any hardware limits. So maybe it is possible to increase speed of such internal inserts ?
Or I do something wrong ?
Thanks.

**Comment by filimonov** [comment]
In general - you should check the logs to find the reason / exact error which blocked pushing data forward. 

If you have huge stream of data and you're overloading your hardware limits - most probably the exception will be "Too many parts..." ( check #6720 )

Closing issue for now (it's old, and rather non-actual), please reopen if there are more questions on that.
