### ISSUE TITLE
Mutation `UPDATE` requests that depend on previous queries fall in incomplete state

### ISSUE THREAD

**Issue by healiseu** [yandex/ClickHouse#3953]
Hi, I have been running recently two or three consecutive mutation `UPDATEs` e,g,
```sql

SELECT table, create_time, command, is_done
FROM system.mutations 
ORDER BY create_time DESC
LIMIT 2

┌─table─────┬─────────create_time─┬─command──────────────────────────────────────────────────────────────────────────────────┬─is_done─┐
│ HAtom_100 │ 2018-12-27 21:15:00 │ UPDATE sel = 1 WHERE (ha2 = 6) AND (str = 'Kennedy Center') AND (pos = 1)                │       1 │
│ HAtom_100 │ 2018-12-27 21:15:00 │ UPDATE sel = 1 WHERE (ha2 = 2) AND ((uint32 >= 1000) AND (uint32 <= 1003)) AND (pos = 1) │       1 │
└───────────┴─────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────┴─────────┘
```
The `create_time` for the two mutations above is the same but in fact those queries where executed after calling python commands e.g.
```python
durflt.execute()
sleep(0.02)
fromflt.execute()
```
You will notice that there is a sleeping time of 20msec to allow mutations to complete. If I remove this sleeping time and try to execute these commands. mutations are falling into an incomplete state, i.e. `is_done=0`.

Why is that happening ? Is there a parameter that controls how frequently you can ALTER a table ? I have read [documentation on mutations][1] and that paragraph seems relevant
> A mutation query returns immediately after the mutation entry is added. The mutation itself executes asynchronously using the system profile settings.

Can you explain it in more detail and also suggest if there is anything in settings that controls the frequency of updates ?

[1]: https://clickhouse.yandex/docs/en/query_language/alter/#query_language_queries_show_databases

**Comment by ztlpn** [comment]
So what is the contents of `block_numbers.partition_id` and `block_numbers.number` columns in the case when mutations fail to complete?

**Comment by healiseu** [comment]
```sql
SELECT 
    table, 
    create_time, 
    command, 
    block_numbers.partition_id AS blk_id, 
    block_numbers.number AS blk_num, 
    parts_to_do, 
    is_done
FROM system.mutations 
ORDER BY create_time DESC
LIMIT 2

┌─table─────┬─────────create_time─┬─command──────────────────────────────────────────────────────────────────────────────────┬─blk_id─┬─blk_num─┬─parts_to_do─┬─is_done─┐
│ HAtom_100 │ 2018-12-28 18:26:23 │ UPDATE sel = 1 WHERE (ha2 = 6) AND (str = 'Kennedy Center') AND (pos = 1)                │ ['']   │ [296]   │           1 │       0 │
│ HAtom_100 │ 2018-12-28 18:26:23 │ UPDATE sel = 1 WHERE (ha2 = 2) AND ((uint32 >= 1000) AND (uint32 <= 1003)) AND (pos = 1) │ ['']   │ [295]   │           1 │       0 │
└───────────┴─────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────┴────────┴─────────┴─────────────┴─────────┘
```

**Comment by ztlpn** [comment]
Are there any errors in ClickHouse logs?

**Comment by healiseu** [comment]
Hi Alex, I discovered that **my error log was several GBs in size** due to processes that were writing to the (log, err.log) very frequently  the same errors over and over again from other tables that were not in my default TriaDB database. 
* I dropped the offending tables, cleaned databases, deleted the logs and restarted the server. 
That made the size of err.log 0 bytes
But I have set `log_queries=1` and trace and debug messages  were logged continuously in server.log
```txt
2018.12.30 00:43:11.036054 [ 1 ] {} <Trace> system.query_thread_log (Data): Found 5 old parts to remove.
2018.12.30 00:43:11.036063 [ 1 ] {} <Debug> system.query_thread_log (Data): Removing part from filesystem 201812_1_3640_1719
```
Since I got into the trouble of checking and understanding server logs I have two questions
##### Q1: What is the level I should use for less verbose logging e.g. only errors ? 
##### Q2: How do you tune the frequency of writing to the server.err.log for the query_log ?

OK I also disabled query_log to check for the mutation problem. I ran my python code as before with a 20msec sleeping time interval between mutation updates. Queries were completed successfully but an error.log was created with messages like

```txt
2018.12.30 00:46:49.976166 [ 16 ] {} <Error> void DB::BackgroundProcessingPool::threadFunction(): Code: 60, e.displayText() = DB::Exception: Table TriaDB.HAtom_100_POS doesn't exist., e.what() = DB::Exception
2018.12.30 00:46:50.102992 [ 4 ] {} <Error> void DB::BackgroundProcessingPool::threadFunction(): Code: 60, e.displayText() = DB::Exception: Table TriaDB.HAtom_100_POS doesn't exist., e.what() = DB::Exception, Stack trace:
```
The same error was recorded 10 times. 
TriaDB.HAtom_100_POS is a materialized view that is dropped and created again every time a new filter is applied prior to the update of the `pos` state. In other words two of the mutations are dependent on HAtom_100_POS but they were completed (see the following creation times).

```sql
┌─table─────┬─────────create_time─┬─command──────────────────────────────────────────────────────────────────────────────────┬─blk_id─┬─blk_num─┬─parts─┬─is_done─┐
│ HAtom_100 │ 2018-12-30 00:47:04 │ UPDATE sel = 1 WHERE (ha2 = 2) AND ((uint32 >= 1000) AND (uint32 <= 1003)) AND (pos = 1) │ ['']   │ [303]   │     0 │       1 │
│ HAtom_100 │ 2018-12-30 00:47:04 │ UPDATE sel = 1 WHERE (ha2 = 6) AND (str = 'Kennedy Center') AND (pos = 1)                │ ['']   │ [304]   │     0 │       1 │
│ HAtom_100 │ 2018-12-30 00:46:49 │ UPDATE pos = 1 WHERE [ha2, ha1] IN (SELECT hatom FROM TriaDB.HAtom_100_POS )             │ ['']   │ [301]   │     0 │       1 │
│ HAtom_100 │ 2018-12-30 00:46:49 │ UPDATE pos = 1 WHERE [ha2, ha1] IN (SELECT hatom FROM TriaDB.HAtom_100_POS )             │ ['']   │ [302]   │     0 │       1 │
└───────────┴─────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────┴────────┴─────────┴───────┴─────────┘
```
Therefore it seems the above error message happens because the process of writing/finalizing the materialized view (HAtom_100_POS) has not been finished and the mutation update of POS is looking for the result of `SELECT hatom FROM TriaDB.HAtom_100_POS`.

And now the case that is causing the incomplete mutation updates for the `sel` state, i.e. execution 

### Without 20msec sleeping time between updates

```sql
┌─table─────┬─────────create_time─┬─command──────────────────────────────────────────────────────────────────────────────────┬─blk_id─┬─blk_num─┬─parts─┬─is_done─┐
│ HAtom_100 │ 2018-12-30 01:45:02 │ UPDATE sel = 1 WHERE (ha2 = 6) AND (str = 'Kennedy Center') AND (pos = 1)                │ ['']   │ [308]   │     1 │       0 │
│ HAtom_100 │ 2018-12-30 01:45:02 │ UPDATE sel = 1 WHERE (ha2 = 2) AND ((uint32 >= 1000) AND (uint32 <= 1003)) AND (pos = 1) │ ['']   │ [307]   │     1 │       0 │
│ HAtom_100 │ 2018-12-30 01:44:12 │ UPDATE pos = 1 WHERE [ha2, ha1] IN (SELECT hatom FROM TriaDB.HAtom_100_POS )             │ ['']   │ [306]   │     0 │       1 │
│ HAtom_100 │ 2018-12-30 01:43:58 │ UPDATE pos = 1 WHERE [ha2, ha1] IN (SELECT hatom FROM TriaDB.HAtom_100_POS )             │ ['']   │ [305]   │     0 │       1 │
└───────────┴─────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────┴────────┴─────────┴───────┴─────────┘
```
Notice that `pos` mutations started at `1:43:58` and `1:44:12` I have deliberately delayed the execution of my filters (python commands) by waiting a couple of seconds. Then at `1:45:02` I executed the two consecutive `sel` mutation updates without any delay (sleeping time) between them. Now what's in the err.log.

```txt
2018.12.30 01:45:02.363911 [ 13 ] {} <Error> void DB::BackgroundProcessingPool::threadFunction(): Code: 349, e.displayText() = DB::Exception: Cannot convert NULL value to non-Nullable type
2018.12.30 01:45:02.406505 [ 7 ] {} <Error> void DB::BackgroundProcessingPool::threadFunction(): Code: 349, e.displayText() = DB::Exception: Cannot convert NULL value to non-Nullable type
--//-- ...  --//-- (x10)
2018.12.30 01:45:13.134744 [ 16 ] {} <Error> void DB::BackgroundProcessingPool::threadFunction(): Code: 349, e.displayText() = DB::Exception: Cannot convert NULL value to non-Nullable type
--//-- .... --//--
2018.12.30 01:47:45.902347 [ 8 ] {} <Error> void DB::BackgroundProcessingPool::threadFunction(): Code: 349, e.displayText() = DB::Exception: Cannot convert NULL value to non-Nullable type
```
The same error message is written continuously at the error log, and the mutation update has fallen to an incomplete state with an endless loop of recording the same error message.

### **Q3:** Regarding to the continuous process of writing error messages. Why is the server keep writing to the err.log file, shouldn't it stop after some time. Is it because of the `trace` default debug level (see also my Q1, Q2) ? 

I am stopping here as I don't have time to search deeper at your code. Hope this information is enough for you to search for a possible bug and offer a solution in my case.

**Comment by alexey-milovidov** [comment]
You're right. Mutations are executed asynchronously. Moreover, if there are multiple mutations to be performed, they are coalesced and run together. This is the intended behaviour and should be clearly documented.
