### ISSUE TITLE
Bug in inner join on expression

### ISSUE THREAD

**Issue by kindred77** [yandex/ClickHouse#3962]
I have a distributed table cluster_customer, has a column named C_CUSTKEY:

CREATE TABLE default.cluster_customer (
C_CUSTKEY UInt32,
 C_NAME String,
C_ADDRESS String, 
C_CITY String,
C_NATION String,
C_REGION String,
C_PHONE String,
C_MKTSEGMENT String,
C_FAKEDATE Date
) ENGINE = Distributed(all_cluster, default, customer, C_CUSTKEY);

SELECT c.C_CUSTKEY
FROM cluster_customer AS c
LIMIT 5

┌─C_CUSTKEY─┐
│        12 │
│        24 │
│        36 │
│        48 │
│        60 │
└───────────┘

But, got a exception below:

SELECT
    c.C_CITY,
    countDistinct(o.LO_PARTKEY) AS cnt
FROM cluster_customer AS c
INNER JOIN cluster_lineorder AS o ON c.C_CUSTKEY = o.LO_CUSTKEY
GROUP BY c.C_CITY
ORDER BY cnt DESC
LIMIT 5

Received exception from server (version 18.16.0):
Code: 47. DB::Exception: Received from localhost:7000, 127.0.0.1. DB::Exception: Unknown identifier: c.C_CUSTKEY.

It's OK when I rewrite it like this:

SELECT
    c.C_CITY,
    countDistinct(o.LO_PARTKEY) AS cnt
FROM cluster_customer AS c
INNER JOIN cluster_lineorder AS o ON C_CUSTKEY = LO_CUSTKEY
GROUP BY c.C_CITY
ORDER BY cnt DESC
LIMIT 5

┌─C_CITY─────┬────cnt─┐
│ FRANCE   4 │ 917135 │
│ INDONESIA8 │ 915617 │
│ INDIA    4 │ 915447 │
│ INDIA    6 │ 915014 │
│ UNITED KI8 │ 914908 │
└────────────┴────────┘

It seams can not work well when I add a table alias in join on expression.

**Comment by den-crane** [comment]
duplicate for #3710
