### ISSUE TITLE
There is a mismatch  between MATERIALIZED VIEW and origin table

### ISSUE THREAD

**Issue by jasper-zhang** [yandex/ClickHouse#3963]
origin table structure is (some other column has ignored):

```
CREATE TABLE  cdn_access_log ( 
datetime DateTime,  
host String, 
bytes_sent Float64
) ENGINE = ReplicatedMergeTree(’/clickhouse/log/{shard}’, ‘{replica}’)
 PARTITION BY toYYYYMMDD(datetime)
 ORDER BY datetime
 SETTINGS index_granularity = 8192
```

I created a MATERIALIZED VIEW to make aggregation:

```
CREATE MATERIALIZED VIEW cdn_access_log_5m_count_view_for_host 
 ENGINE = AggregatingMergeTree() 
PARTITION BY toYYYYMMDD(datetime) 
ORDER BY (datetime, host)  
AS SELECT host, toStartOfFiveMinute(datetime) AS datetime, countState() AS c 
FROM  log  GROUP BY datetime, host
```

Running for a while， I select the two table, and I found  the result unmatch:

Origin table:
![image](https://user-images.githubusercontent.com/6657098/50532603-a54eab00-0b56-11e9-9ac2-9600c1ae06f4.png)

MATERIALIZED VIEW:
![image](https://user-images.githubusercontent.com/6657098/50532605-b7304e00-0b56-11e9-825d-801b290ef010.png)

Differ greatly !!!
The result is same after I optimize the  MATERIALIZED VIEW.

**Comment by jasper-zhang** [comment]
Add:  ClickHouse server version is 18.14.15

**Comment by den-crane** [comment]
T: ENGINE = ReplicatedMergeTree
MV: ENGINE = AggregatingMergeTree() 

MV is a pre-insert trigger so your MV sees only rows inserted into the current replica.

**Comment by jasper-zhang** [comment]
- I know the MV is only received the rows of the current replica, but the result between MV and T of  current replica should match, also.
   btw, For ReplicatedMergeTree, How can l create MV ?

-  sorry, I just input error,  CREATE MATERIALIZED VIEW FROM **cdn_access_log**, Actually.

**Comment by jasper-zhang** [comment]
My fault, I understand it wrong.
