### ISSUE TITLE
There are a lot of query cannot be killed 

### ISSUE THREAD

**Issue by xiashuijun** [yandex/ClickHouse#3964]
one of the query elapsed like this:

com.cn :) select elapsed from system.processes limit 1;

SELECT elapsed
FROM system.processes
LIMIT 1

┌───────────elapsed─┐
│ 1628712.238700054 │
└───────────────────┘

1 rows in set. Elapsed: 0.005 sec.

com.cn :) select count() from system.processes  where elapsed > 1628712;

SELECT count()
FROM system.processes
WHERE elapsed > 1628712

┌─count()─┐
│      80 │
└─────────┘

1 rows in set. Elapsed: 0.128 sec.

when i use kill query where elapsed > 1628712, all the status is waiting.

my clickhouse version is 18.14.13.

how can i kill this query where  elapsed is too long? thank you

**Comment by xiashuijun** [comment]
> 1. Some types of queries can't be killed (for example if it contains scalar subquery).
> 2. Some of queries check the 'killed' flag only on certain moments of execution and you need to wait till query will come to that moment.
> 3. In versions before 18.16.0 where was no possibility to kill the query which was not started yet (for example due to waiting for locks).

thank you

**Comment by filimonov** [comment]
Related #1576
