### ISSUE TITLE
Clickhouse Start slowly due to explicit chown 

### ISSUE THREAD

**Issue by k1dave6412** [yandex/ClickHouse#3966]
Hey guys,
After I insert my data (2GB) to Clickhouse (with volume),
I restart the container ,
found the container process "chown"...
after 20mins, Clickhouse started...
someone knows how to improve the start speed or any alternatively?

**Comment by filimonov** [comment]
related #3828

**Comment by alesapin** [comment]
https://github.com/yandex/ClickHouse/pull/3967/files

**Comment by k1dave6412** [comment]
Thanks Guys
But I have another problems now...

Load Data slowly
maybe I need to edit the compression setting (is default now)? 
![image](https://user-images.githubusercontent.com/14539608/50548880-109b9880-0c8f-11e9-9c50-e835201296a3.png)

**Comment by alesapin** [comment]
It's hard to give any advice without information about amount of data in tables and disk load (`dstat` output, for example).

**Comment by k1dave6412** [comment]
Thx @alesapin 
I will checkout about the system and setting
