### ISSUE TITLE
ALL JOIN inflating numbers

### ISSUE THREAD

**Issue by Slind14** [yandex/ClickHouse#3971]
Hi there,
imagine a simple query with a join like the following. When using an ANY join I get the same result as without a join but as soon as I use ALL, the result from the local fields (impressions, value..) is inflated. Usually this inflation is just 1-4% but in some cases it is 10-100 times. What would be the best course of action here?

```
SELECT
    category,
    count() AS impressions,
    uniq(sessionId) as sessions,
    sum(value) as value,
    sum(visible) AS visible,
    sum(engaged) AS engaged
FROM impressions ALL LEFT JOIN
(
    SELECT
        CounterID,
        engaged,
        visible
    FROM visits
    GROUP BY CounterID
) USING CounterID
GROUP BY category
```

**Comment by alexey-milovidov** [comment]
If I understand your question correctly, this is how ALL JOIN is expected to behave.
(And ALL JOIN is the default behaviour of JOIN in other relational DBMSs)
If there are multiple rows in the right table with corresponding CounterID, it will create multiple rows in the result.

**Comment by den-crane** [comment]
>Usually this inflation is just 1-4% but in some cases it is 10-100 times. 
CH always gives exact numbers. If you experience some inflation, even 0.00001% it means something wrong with design or it's some unknown CH's bug.

`GROUP BY CounterID ) USING CounterID`
means that the right table has only one row with each CounterID, so it should not be any difference with ALL vs ANY.

Can you show exact table DDLs and exact SQL, because your example is too vague and wrong for the right table _engaged_ and _visible_ are not a SUMS and they are not in GROUP BY section.

**Comment by Slind14** [comment]
Here is a real query and the result:

Both tables are a simple MergeTree.

```
SELECT
    date,
    count() AS impressions,
    uniq(sessionUUID) as sessions,
    sum(value) as value,
    sum(visible) AS visible,
    sum(engaged) AS engaged
FROM `impressions` ANY LEFT JOIN
(
    SELECT
        impressionUUID,
        visible,
        engaged
    FROM `meta`
    WHERE date = yesterday()
) USING impressionUUID
WHERE date = yesterday()
GROUP BY date;
```

## NO JOIN

```
┌───────date─┬─impressions─┬─sessions─┬──────────value─┬─visible─┬─engaged─┐
│ 2018-12-30 │     4353169 │   123935 │ 5636888.545389 │         │         │
└────────────┴─────────────┴──────────┴────────────────┴─────────┴─────────┘
```

## ANY LEFT JOIN

```
┌───────date─┬─impressions─┬─sessions─┬──────────value─┬─visible─┬─engaged─┐
│ 2018-12-30 │     4353169 │   123935 │ 5636888.545389 │ 2662372 │    2274 │
└────────────┴─────────────┴──────────┴────────────────┴─────────┴─────────┘
```

## ALL LEFT JOIN

```
┌───────date─┬─impressions─┬─sessions─┬───────────value─┬──visible─┬─engaged─┐
│ 2018-12-30 │    41745815 │   123935 │ 17641794.240708 │ 39908334 │  148958 │
└────────────┴─────────────┴──────────┴─────────────────┴──────────┴─────────┘
```

**Comment by den-crane** [comment]
So probably meta has duplicates for some reason

SELECT      impressionUUID, count() cnt
    FROM `meta` WHERE date = yesterday() group by impressionUUID having cnt > 1

What table engine is used by meta ? Replacing ?

**Comment by Slind14** [comment]
> Both tables are a simple MergeTree.

Your query returns: `13 rows in set. Elapsed: 0.485 sec.` all with a cnt of 2

**Comment by den-crane** [comment]
OK. Is it valid to have duplicates?
The observed difference is because these duplicates multiply select's result rows with ALL and does not with ANY.

**Comment by den-crane** [comment]
>Yes, these are not really duplicates, visible and engaged are treated separately. 

so are they flags?

visible 0  engaged  1
visible 1  engaged  1

or numbers?

What CH version do you use?

**Comment by Slind14** [comment]
They are boolean (numbers which can only be 0 and 1).
It is not possible that one row has visible and engaged set. It is always
impressionA visible 1 engaged 0
impressionA visible 0 engaged 1

`18.16.1 revision 54412`

**Comment by den-crane** [comment]
OK. So is any difference in result 
```

SELECT
    date,
    count() AS impressions,
    uniq(sessionUUID) as sessions,
    sum(value) as value,
    sum(visible) AS visible,
    sum(engaged) AS engaged
FROM `impressions` ANY LEFT JOIN
(
    SELECT
        impressionUUID,
        sum(visible) visible,
        sum(engaged) engaged
    FROM `meta`
    WHERE date = yesterday()
    GROUP BY impressionUUID
) USING impressionUUID
WHERE date = yesterday()
GROUP BY date;

```

the same with ALL LEFT JOIN

**Comment by Slind14** [comment]
You are right, it works with the group by. I guess it was my mistake. 

Btw. is there any way to tell `ANY` to pick the latest record? (go through it staring with the latest)

**Comment by den-crane** [comment]
It's in your data. Just check what is going on for one of these (of 13) impressionUUID.
There is no mystery or magic or inflation.

>Btw. is there any way to tell ANY to pick the latest record? (go through it staring with the latest)
No.
It will be something like that
```

select mx.1 impressionUUID, sum(mx.2) visible, sum(mx.3) engaged from
( select argMax((impressionUUID,visible,engaged),date) mx 
  from `meta`
  group by impressionUUID, visible, engaged)
group by impressionUUID
```

**Comment by Slind14** [comment]
I see. Thank you.
