### ISSUE TITLE
Query timeout and readonly

### ISSUE THREAD

**Issue by edonin** [yandex/ClickHouse#3974]
Hi,

On my clickhouse server, I have one _read only_ user, with unlimited execution time (no max_execution_time defined in its profile).

Nevertheless, for very specific queries for this user, I need to set a query timeout. So I add the parameter max_execution_time=5 in the URL of my HTTP request. But I get an error : 
`Cannot override setting (max_execution_time) in readonly mode`.

I understand that the user should not be allowed to bypass some limits, but here, I am just trying to add some a new limit :-)

Is there any workaround that allows to keep the readonly mode, that is usefull here for security reasons ?

**Comment by den-crane** [comment]
* you need **readonly 2**
 2 — Read data and change settings queries are allowed. 
 https://clickhouse.yandex/docs/en/operations/settings/permissions_for_queries/#settings_readonly

but 
* When using the GET method in the HTTP interface, readonly = 1 is set automatically. 
  To modify data, use the **POST** method.
