### ISSUE TITLE
18.16.1 compile_expressions eats memory

### ISSUE THREAD

**Issue by den-crane** [yandex/ClickHouse#3976]
<img width="993" alt="screen shot 2019-01-02 at 9 40 44 am" src="https://user-images.githubusercontent.com/19737682/50594450-01754000-0e73-11e9-90ee-d0cd73a400b6.png">

Without compile expressions CH eats ~3 GB (2 cache_marks + 1 dictionary)
With compile expressions upto 30GB (maybe indefinite)

RSS (top): 8.5GB

metric | value | formatReadableSize(value)
-- | -- | --
CompiledExpressionCacheBytes | 24275840 | 23.15 MiB
CompiledExpressionCacheCount | 12067 | 11.78 KiB
jemalloc.active | 1673678848 | 1.56 GiB
jemalloc.allocated | 1653140456 | 1.54 GiB
jemalloc.mapped | 2982797312 | 2.78 GiB
jemalloc.metadata | 18678872 | 17.81 MiB
jemalloc.resident | 2916798464 | 2.72 GiB
jemalloc.retained | 2162565120 | 2.01 GiB
MarkCacheBytes | 322326272 | 307.39 MiB
MarkCacheFiles | 708775 | 692.16 KiB

@alesapin

**Comment by den-crane** [comment]
rss 25.4GB


metric | value | formatReadableSize(value)
-- | -- | --
CompiledExpressionCacheBytes | 92513984 | 88.23 MiB
CompiledExpressionCacheCount | 45757 | 44.68 KiB
jemalloc.active | 1673678848 | 1.56 GiB
jemalloc.allocated | 1653140456 | 1.54 GiB
jemalloc.mapped | 2982797312 | 2.78 GiB
jemalloc.metadata | 18678872 | 17.81 MiB
jemalloc.resident | 2916798464 | 2.72 GiB
jemalloc.retained | 2162565120 | 2.01 GiB
MarkCacheBytes | 606976720 | 578.86 MiB
MarkCacheFiles | 1644690 | 1.57 MiB
MaxPartCountForPartition | 19 | 19.00 B
Uptime | 350588 | 342.37 KiB

**Comment by angeldestroyer** [comment]
Disabling this functionality solved my problem with OOM on versions 18.14.9 and 18.16.1
(my graphics with RAM are similar)

**Comment by alesapin** [comment]
Unfortunately this is not memory leak. There is problem in compiled expressions cache implementation.

**Comment by alesapin** [comment]
Fixes https://github.com/yandex/ClickHouse/pull/4042 https://github.com/yandex/ClickHouse/pull/4041

**Comment by den-crane** [comment]
Seems <compiled_expression_cache_size>500 fixes the issue

<img width="953" alt="screen shot 2019-01-14 at 9 42 14 am" src="https://user-images.githubusercontent.com/19737682/51116336-36718300-17e1-11e9-8ac1-b8f006cfe384.png">



metric | value
-- | --
CompiledExpressionCacheBytes | 976000
CompiledExpressionCacheCount | 500
MarkCacheBytes | 574170160
MarkCacheFiles | 1392709
MaxPartCountForPartition | 21
Uptime | 246588
jemalloc.active | 1690431488
jemalloc.allocated | 1665101056
jemalloc.mapped | 4476731392
jemalloc.metadata | 25512904
jemalloc.resident | 4394479616
jemalloc.retained | 3510796288
