### ISSUE TITLE
SELECT from Url table using https URL fails with certificate validation error 

### ISSUE THREAD

**Issue by hodgesrm** [yandex/ClickHouse#3983]
Selecting data from an Url table fails using ClickHouse version 18.16.1 on Ubuntu 16.04 when the URL scheme is https. To get it to work you have to set the client invalidCertificateHandler name to AcceptCertificateHandler in config.xml

Here's an example script to reproduce and the resulting error.  First, the reproduction script:
```shell
#!/bin/bash
clickhouse-client --multiquery <<_EOF
SELECT version();
DROP TABLE IF EXISTS iris_web;
CREATE TABLE iris_web ( sepal_length Decimal32(2), sepal_width Decimal32(2), petal_length Decimal32(2), petal_width Decimal32(2), species String) ENGINE=URL('https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv', CSVWithNames);
SELECT COUNT(*), species FROM iris_web GROUP BY species ORDER BY species;
_EOF
```
On execution this gives the following error:
```shell
18.16.1
Received exception from server (version 18.16.1):
Code: 1000. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: SSL Exception: error:14007086:SSL routines:CONNECT_CR_CERT:certificate verify failed. 
```
The error log shows a similar error:
```shell
2019.01.03 21:38:53.057331 [ 24 ] {0220a869-5b7f-4725-a849-92a34e0ab4ad} <Error> executeQuery: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = SSL Exception: error:14007086:SSL routines:CONNECT_CR_CERT:certificate verify failed, e.what() = SSL Exception (from 127.0.0.1:41084) (in query: SELECT COUNT(*), species FROM iris_web GROUP BY species ORDER BY species)
```
The workaround is to set the client invalidCertificateHandler to AcceptCertificateHandler and restart ClickHouse.  Here's an example: 
```shell
    <openSSL>
        ...
        <client> <!-- Used for connecting to https dictionary source -->
            <loadDefaultCAFile>true</loadDefaultCAFile>
            <cacheSessions>true</cacheSessions>
            <disableProtocols>sslv2,sslv3</disableProtocols>
            <preferServerCiphers>true</preferServerCiphers>
            <!-- Use for self-signed: <verificationMode>none</verificationMode> -->
            <invalidCertificateHandler>
                <name>AcceptCertificateHandler</name>
            </invalidCertificateHandler>
        </client>
    </openSSL>
```
Note: The certificate is actually OK--Chrome shows that the URL is properly protected.  I can fetch the content from the same host using curl without problems, so the host overall is fine.

**Comment by filimonov** [comment]
> Note: The certificate is actually OK--Chrome shows that the URL is properly protected. I can fetch the content from the same host using curl without problems, so the host overall is fine.

Sounds like openssl client doesn't use default CA file.
May be it's connected to that issue: https://security.stackexchange.com/a/142172

Can you try with `<caConfig>/dev/null</caConfig>` after `<loadDefaultCAFile>true</loadDefaultCAFile>` (and without `<invalidCertificateHandler>`) ? 

Also you can try to direct ClickHouse to your CA files directory (usually something like `/etc/ssl/certs/`)

openssl s_client -connect www.feistyduck.com:443

**Comment by hodgesrm** [comment]
@filimonov, ClickHouse is definitely not picking up the right certificate directory.  The simplest workaround is to set it explicitly using the caConfig tag.  The following client config works on Ubuntu 16.04. 
```
        <client> <!-- Used for connecting to https dictionary source -->
            <loadDefaultCAFile>true</loadDefaultCAFile>
            <caConfig>/etc/ssl/certs</caConfig>
            <cacheSessions>true</cacheSessions>
            <disableProtocols>sslv2,sslv3</disableProtocols>
            <preferServerCiphers>true</preferServerCiphers>
        </client>
```
I think this behavior is indeed similar to the OPENSSLDIR problem you referenced. I notice that source builds of ClickHouse seem to override OPENSSLDIR.  build/compile_commands.json contains gcc-7 commands like the following: 
```
{
  "directory": "/home/rhodges/git/ClickHouse/build",
  "command": "/usr/bin/gcc-7  -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DHAVE_ASPRINTF -DHAVE_ERR_H -DHAVE_GETPAGESIZE -DHAVE_INET_PTON -DHAVE_MEMMEM -DHAVE_STRCASECMP -DHAVE_STRNDUP -DHAVE_STRNLEN -DHAVE_STRSEP -DHAVE_TIMEGM -DLIBRESSL_INTERNAL -DMD5_ASM -DOPENSSLDIR=\\\"/usr/local/etc/ssl\\\" -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_NO_HW_PADLOCK -DRSA_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DSIZEOF_TIME_T=8 -DVPAES_ASM -DWHIRLPOOL_ASM -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_GNU_SOURCE -D_POSIX_SOURCE -D__BEGIN_HIDDEN_DECLS=\"\" -D__END_HIDDEN_DECLS=\"\" -I../contrib/ssl/crypto/. -I../contrib/ssl/crypto/../include -I../contrib/ssl/crypto/../include/compat -I../contrib/ssl/crypto/asn1 -I../contrib/ssl/crypto/bn -I../contrib/ssl/crypto/dsa -I../contrib/ssl/crypto/evp -I../contrib/ssl/crypto/modes   -fdiagnostics-color=always  -pipe -msse4.1 -msse4.2 -mpopcnt -fno-omit-frame-pointer  -Wall  -no-pie -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-result -Wno-deprecated-declarations -Wno-maybe-uninitialized -Wno-format -Wno-misleading-indentation -Wno-stringop-overflow -O2 -g -DNDEBUG -O3  -fPIC   -Wno-pointer-sign -o contrib/ssl/crypto/CMakeFiles/crypto-objects.dir/aes/aes-elf-x86_64.S.o   -c /home/rhodges/git/ClickHouse/contrib/ssl/crypto/aes/aes-elf-x86_64.S",
  "file": "/home/rhodges/git/ClickHouse/contrib/ssl/crypto/aes/aes-elf-x86_64.S"
},
```
It looks as if OPENSSLDIR is being set magically by some dependency.  I grepped -r the sources and don't find an explicit assignment.

**Comment by alexey-milovidov** [comment]
So, we should just set `OPENSSLDIR` to `/etc/ssl/certs` at the build time?

**Comment by hodgesrm** [comment]
> So, we should just set `OPENSSLDIR` to `/etc/ssl/certs` at the build time?

That should fix it on Ubuntu at least.  Thanks for the fix.  I'll check the next release.
