### ISSUE TITLE
libpoco compilation problem on Fedora 28, error: too few arguments to function ‘int pthread_setaffinity_np

### ISSUE THREAD

**Issue by Ormod** [yandex/ClickHouse#3991]
This is with a fresh checkout of current master on Fedora 28:

commit acb9696dddf08899df273262a2fa37d220ee9505 (HEAD -> master, origin/master, origin/HEAD)

$ gcc --version
gcc (GCC) 8.2.1 20181215 (Red Hat 8.2.1-6)
$ g++ --version
g++ (GCC) 8.2.1 20181215 (Red Hat 8.2.1-6)

Seems to be picking up the wrong version of the function. (two param version instead instead of the one taking three parameters)

If you'd like to see any other information, please let me know.

--clip--
[717/2908] Building CXX object contrib/poco/Foundation/CMakeFiles/Foundation.dir/src/Thread.cpp.o
FAILED: contrib/poco/Foundation/CMakeFiles/Foundation.dir/src/Thread.cpp.o 
/usr/lib64/ccache/c++  -DHAVE_PTHREAD_SETAFFINITY_NP -DPCRE_STATIC -DPOCO_EXTERNAL_OPENSSL -DPOCO_HAVE_FD_EPOLL -DPOCO_STATIC -DPOCO_UNBUNDLED -DPOCO_UNBUNDLED_ZLIB -DUNALIGNED_OK -DWITH_GZFILEOP -DX86_64 -DZLIB_COMPAT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_REENTRANT -D_THREAD_SAFE -D_XOPEN_SOURCE=500 -isystem ../contrib/poco/Foundation/include -isystem ../contrib/poco/Foundation/src -I../contrib/zlib-ng -Icontrib/zlib-ng -fdiagnostics-color=always  -pipe -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall  -Wnon-virtual-dtor -no-pie -Wno-old-style-cast -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-result -Wno-deprecated-declarations -Wno-non-virtual-dtor -Wno-maybe-uninitialized -Wno-format -Wno-misleading-indentation -Wno-implicit-fallthrough -Wno-class-memaccess -Wno-sign-compare -std=c++1z -Wno-sign-compare  -fno-strict-aliasing -Wno-unknown-pragmas -Wno-non-virtual-dtor -O2 -g -DNDEBUG -O3    -std=c++1z -MD -MT contrib/poco/Foundation/CMakeFiles/Foundation.dir/src/Thread.cpp.o -MF contrib/poco/Foundation/CMakeFiles/Foundation.dir/src/Thread.cpp.o.d -o contrib/poco/Foundation/CMakeFiles/Foundation.dir/src/Thread.cpp.o -c ../contrib/poco/Foundation/src/Thread.cpp
In file included from ../contrib/poco/Foundation/src/Thread_STD.cpp:25,
                 from ../contrib/poco/Foundation/src/Thread.cpp:21:
../contrib/poco/Foundation/src/Thread_STD_POSIX.cpp: In member function ‘void Poco::ThreadImpl::setAffinityImpl(int)’:
../contrib/poco/Foundation/src/Thread_STD_POSIX.cpp:170:62: error: invalid conversion from ‘cpu_set_t*’ to ‘size_t’ {aka ‘long unsigned int’} [-fpermissive]
  if (pthread_setaffinity_np(_pData->thread->native_handle(), &cpuset) != 0)
                                                              ^~~~~~~
../contrib/poco/Foundation/src/Thread_STD_POSIX.cpp:170:69: error: too few arguments to function ‘int pthread_setaffinity_np(pthread_t, size_t, const cpu_set_t*)’
  if (pthread_setaffinity_np(_pData->thread->native_handle(), &cpuset) != 0)
                                                                     ^
In file included from /usr/include/c++/8/x86_64-redhat-linux/bits/gthr-default.h:35,
                 from /usr/include/c++/8/x86_64-redhat-linux/bits/gthr.h:148,
                 from /usr/include/c++/8/ext/atomicity.h:35,
                 from /usr/include/c++/8/bits/basic_string.h:39,
                 from /usr/include/c++/8/string:52,
                 from ../contrib/poco/Foundation/include/Poco/Bugcheck.h:22,
                 from ../contrib/poco/Foundation/include/Poco/Foundation.h:152,
                 from ../contrib/poco/Foundation/include/Poco/Thread.h:21,
                 from ../contrib/poco/Foundation/src/Thread.cpp:15:
/usr/include/pthread.h:475:12: note: declared here
 extern int pthread_setaffinity_np (pthread_t __th, size_t __cpusetsize,
            ^~~~~~~~~~~~~~~~~~~~~~
In file included from ../contrib/poco/Foundation/src/Thread_STD.cpp:25,
                 from ../contrib/poco/Foundation/src/Thread.cpp:21:
../contrib/poco/Foundation/src/Thread_STD_POSIX.cpp: In member function ‘int Poco::ThreadImpl::getAffinityImpl() const’:
../contrib/poco/Foundation/src/Thread_STD_POSIX.cpp:206:62: error: invalid conversion from ‘cpu_set_t*’ to ‘size_t’ {aka ‘long unsigned int’} [-fpermissive]
  if (pthread_getaffinity_np(_pData->thread->native_handle(), &cpuset) != 0)
                                                              ^~~~~~~
../contrib/poco/Foundation/src/Thread_STD_POSIX.cpp:206:69: error: too few arguments to function ‘int pthread_getaffinity_np(pthread_t, size_t, cpu_set_t*)’
  if (pthread_getaffinity_np(_pData->thread->native_handle(), &cpuset) != 0)
                                                                     ^
In file included from /usr/include/c++/8/x86_64-redhat-linux/bits/gthr-default.h:35,
                 from /usr/include/c++/8/x86_64-redhat-linux/bits/gthr.h:148,
                 from /usr/include/c++/8/ext/atomicity.h:35,
                 from /usr/include/c++/8/bits/basic_string.h:39,
                 from /usr/include/c++/8/string:52,
                 from ../contrib/poco/Foundation/include/Poco/Bugcheck.h:22,
                 from ../contrib/poco/Foundation/include/Poco/Foundation.h:152,
                 from ../contrib/poco/Foundation/include/Poco/Thread.h:21,
                 from ../contrib/poco/Foundation/src/Thread.cpp:15:
/usr/include/pthread.h:480:12: note: declared here
 extern int pthread_getaffinity_np (pthread_t __th, size_t __cpusetsize,
            ^~~~~~~~~~~~~~~~~~~~~~
[722/2908] Building CXX object contrib/capnproto/c++/src/capnp/CMakeFiles/capnpc_cpp.dir/compiler/capnpc-c++.c++.o
ninja: build stopped: subcommand failed.

**Comment by proller** [comment]
Please show full cmake output.
important strings like
```
-- Looking for pthread_setaffinity_np in pthread
-- Looking for pthread_setaffinity_np in pthread - found
-- Performing Test HAVE_THREE_PARAM_SCHED_SETAFFINITY
-- Performing Test HAVE_THREE_PARAM_SCHED_SETAFFINITY - Success
-- Platform has THREE PARAM at PTHREAD_SETAFFINITY_NP
```
And show files in build dir  CMakeFiles/CMakeError.log CMakeFiles/CMakeOutput.log

Looks like this tests broken on your system.

**Comment by Ormod** [comment]
Looked at the output and figured out the reason, I was missing the fedora RPM package:

libstdc++-static

which caused the compile test for the three param version to fail since it tried to do -L stdc++ (could've been called something else, writing this based on memory) which wasn't obviously defined because the RPM wasn't installed. 

Ran into another Fedora compilation problem at the same time but I'll write up an issue about that separately.
