### ISSUE TITLE
File not found after removing temporary directory

### ISSUE THREAD

**Issue by badvir** [yandex/ClickHouse#3995]
Hi~

File not found error occurred when starting clickhouse-server.
CH version : ClickHouse 18.14.18 with revision 54409

clickhouse-server.log file is below.

2019.01.04 08:46:05.608361 [ 4 ] {} <Debug> local.traffic_session (Data): Loaded data parts (88 items)
2019.01.04 08:46:05.609377 [ 4 ] {} <Debug> local.traffic_stat_cnt (Data): Loading data parts
2019.01.04 08:46:05.672654 [ 4 ] {} <Debug> local.traffic_stat_cnt (Data): Loaded data parts (39 items)
2019.01.04 08:46:05.673446 [ 4 ] {} <Debug> local.user_auth (Data): Loading data parts
2019.01.04 08:46:05.673475 [ 4 ] {} <Debug> local.user_auth (Data): Loaded data parts (0 items)
2019.01.04 08:46:05.674134 [ 4 ] {} <Debug> local.zombiepc (Data): Loading data parts
2019.01.04 08:46:05.674162 [ 4 ] {} <Debug> local.zombiepc (Data): Loaded data parts (0 items)
2019.01.04 08:46:05.674202 [ 1 ] {} <Information> DatabaseOrdinary (local): Starting up tables.
2019.01.04 08:46:05.675098 [ 21 ] {} <Trace> local.alert (Data): Found 6 old parts to remove.
2019.01.04 08:46:05.675119 [ 21 ] {} <Debug> local.alert (Data): Removing part from filesystem 20190102_100708_104320_723
2019.01.04 08:46:05.675356 [ 10 ] {} **<Warning> local.alert (Data): Removing temporary directory /secui/log/db/data/local/alert/tmp_delete_20190102_100708_104320_723**
2019.01.04 08:46:05.701738 [ 14 ] {} <Trace> ThreadStatus: Thread 14 exited
2019.01.04 08:46:05.701749 [ 5 ] {} <Trace> ThreadStatus: Thread 5 exited
2019.01.04 08:46:05.701758 [ 13 ] {} <Trace> ThreadStatus: Thread 13 exited
2019.01.04 08:46:05.701776 [ 10 ] {} <Trace> ThreadStatus: Thread 10 exited
2019.01.04 08:46:05.701754 [ 11 ] {} <Trace> ThreadStatus: Thread 11 exited
2019.01.04 08:46:05.701756 [ 19 ] {} <Trace> ThreadStatus: Thread 19 exited
2019.01.04 08:46:05.701761 [ 8 ] {} <Trace> ThreadStatus: Thread 8 exited
2019.01.04 08:46:05.701766 [ 6 ] {} <Trace> ThreadStatus: Thread 6 exited
2019.01.04 08:46:05.701740 [ 20 ] {} <Trace> ThreadStatus: Thread 20 exited
2019.01.04 08:46:05.701752 [ 16 ] {} <Trace> ThreadStatus: Thread 16 exited
2019.01.04 08:46:05.701754 [ 18 ] {} <Trace> ThreadStatus: Thread 18 exited
2019.01.04 08:46:05.701747 [ 15 ] {} <Trace> ThreadStatus: Thread 15 exited
2019.01.04 08:46:05.701746 [ 9 ] {} <Trace> ThreadStatus: Thread 9 exited
2019.01.04 08:46:05.701769 [ 12 ] {} <Trace> ThreadStatus: Thread 12 exited
2019.01.04 08:46:05.701756 [ 17 ] {} <Trace> ThreadStatus: Thread 17 exited
2019.01.04 08:46:05.701743 [ 7 ] {} <Trace> ThreadStatus: Thread 7 exited
2019.01.04 08:46:05.702859 [ 1 ] {} <Debug> Application: Destroyed global context.
2019.01.04 08:46:05.703422 [ 1 ] {} **<Error> Application: File not found: /secui/log/db/data/local/alert/tmp_delete_20190102_100708_104320_723/message.mrk**
2019.01.04 08:46:05.703441 [ 1 ] {} <Information> Application: shutting down
2019.01.04 08:46:05.703447 [ 1 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2019.01.04 08:46:05.703469 [ 2 ] {} <Information> BaseDaemon: Stop SignalListener thread

**Comment by alexey-milovidov** [comment]
This is fixed in #4369
