### ISSUE TITLE
0.3s for single one query, but low concurrency

### ISSUE THREAD

**Issue by seven7777777** [yandex/ClickHouse#3996]
Hi, 
 I have about 37 billion rows data stored in 8 nodes. thats to say I  have  4 shards with 2 replicas.  It's part of  my users.xml  as following:
                <max_memory_usage>0</max_memory_usage>
                <max_block_size>65536100</max_block_size>
                <max_threads>200</max_threads>
                <max_streams_to_max_threads_ratio>10</max_streams_to_max_threads_ratio>
                <max_read_buffer_size>21474836480</max_read_buffer_size>
               <use_uncompressed_cache>0</use_uncompressed_cache>
               <load_balancing>random</load_balancing>

Creating MergeTree table on each node:

CREATE TABLE met204_base ( date Date DEFAULT today(),  at DateTime DEFAULT now(),  uuid String,  dep String,  dep1 String,  dep2 String,  app String,  idc String,  cpuload1 Float64,  cpuload2 Float64) ENGINE = MergeTree() PARTITION BY toHour(at) ORDER BY (dep, dep1, dep2, app, idc, at) SAMPLE BY at SETTINGS index_granularity = 32768

And then create a Distributed table on each node:
 CREATE TABLE  met204 as met204_base ENGINE = Distributed(logs, mdb, met204_base, rand())

Now I query  **on Distributed table** on each  one of 8 nodes like this:
 select sum(cpuload1) from met204 where dep='DEP-8sjREfQzn' AND dep1='DEP-8sjREfQzn-7' AND dep2='DEP-8sjREfQzn-7-0' AND app='DEP-8sjREfQzn-SRV-lF6oZbPDi'

1 rows in set. Elapsed: 0.083 sec. Processed 13.68 million rows, 1.59 GB (165.64 million rows/s., 19.24 GB/s.) 

ITS REALLY FAST AND PERFECT! 
But when I make similar queries **concurrently** in 500 theads  to 8 nodes(80c300g) without any sleep op, IT JUST DOES NOT ACHIEVE  ANY higher qps, just about 50 qps. 

HAVE NO IDEA WHAT TO DO NOW, Please help:
1. Is it appropriate to query on Distributed table?
2.Any config or settings can help?

**Comment by den-crane** [comment]
1. PARTITION BY toHour(at)  --- SUPER EXTRA MEGA HUGEEEEEE Mistake.
Initial Ch design suggest monthly partitions

2. execute ONE query 
select sum(cpuload1), dep, dep1, ... from met204 
group by  dep, dep1, ...
partition results to 500 by dep... at Application side

**Comment by seven7777777** [comment]
Thank you @den-crane , I will try again as your advice.

**Comment by seven7777777** [comment]
@den-crane  Thank you so much!  IT WORKS, REALLY! 500 QPS NOW!
