### ISSUE TITLE
Possibly wrong Column lookup

### ISSUE THREAD

**Issue by edonin** [yandex/ClickHouse#3998]
Hi,

With Clickhouse 18.16.1, I have an issue when I am using subqueries with column name collision:

For example:
```
SELECT 0 as t
FROM (SELECT 1 as t) as inn
WHERE inn.t = 1
```
Return no rows. For me, I should have one row returned with 0 as single value.

From my understanding,  in the where part, the inn.t is resolved as 0 instead of the value that comes from the sub query.

I have the same kind of issues with:
```
SELECT sum(value) as value
FROM (SELECT 1 as value) as data
WHERE data.value > 0
```

where I have an error: ```Aggregate function sum(value) is found in WHERE or PREWHERE in query```, instead of having 1 returned.

**Comment by 4ertus2** [comment]
It looks like 'data.value' has been cropped to 'value' before aliases calculation.
Correlated issue #3998

**Comment by 4ertus2** [comment]
#4351

**Comment by 4ertus2** [comment]
fixed in master
