### ISSUE TITLE
How the Clickhouse as backend for JanusGraph?

### ISSUE THREAD

**Issue by ggservice007** [yandex/ClickHouse#4001]
I want to use JanusGraph for processing graph.

http://janusgraph.org/

```cmd
Support for various storage backends:

    Apache Cassandra®
    Apache HBase®
    Google Cloud Bigtable
    Oracle BerkeleyDB
```
I like Clickhouse as the storage backend.

Any ideas?

**Comment by ggservice007** [comment]
I have submitted a issue.

https://github.com/JanusGraph/janusgraph/issues/1370

We can together make it.

So nice.

**Comment by ggservice007** [comment]
https://github.com/JanusGraph/janusgraph/issues/1370

So nice.

Who will make it with me?

**Comment by blinkov** [comment]
Let's open specific feature requests if something will need to be improved in ClickHouse to make this JanusGraph integration happen.

**Comment by ggservice007** [comment]
@blinkov 
nice
