### ISSUE TITLE
Why not use JDBC native for the offical support?

### ISSUE THREAD

**Issue by ggservice007** [yandex/ClickHouse#4002]
The Http version JDBC is often bad performance.

For example, sometimes some query run normally, but the same query run abnormally on undefined time. 

Why not use native JDBC?
https://github.com/housepower/ClickHouse-Native-JDBC.

**Comment by filimonov** [comment]
Can you provide some samples when Native 'beats' HTTP? With Native the client need to convert columns to rows by it's own, and it's hard to do that faster than Clickhouse itself. At the same time overhead of HTTP itself is minimal. The real reason for using Native - is better protocol features, i.e. you can exchange some extra metainformation with server.

**Comment by den-crane** [comment]
We have no problems with official JDBC(http). 
It's superfast and super stable.
In one project (JDBC(http)) we run about 100 mil. queries every day (over Europe - latency 60ms). Half of queries retrieve more that 500 thousands rows and >10 GB each (huge jsons in column).
Try to tune timeouts i.e. socket_timeout.

**Comment by alex-zaitsev** [comment]
In our benchmarks native driver above (ClickHouse-Native-JDBC) is significantly slower than official HTTP JDBC when querying data. See this issue: https://github.com/housepower/ClickHouse-Native-JDBC/issues/70

**Comment by ggservice007** [comment]
@den-crane @filimonov 
Any idea the HTTP JDBC with HikariCP.

光 HikariCP・A solid, high-performance, JDBC connection pool at last. 

https://github.com/brettwooldridge/HikariCP

```xml
maximumPoolSize=100
minimumIdle=50
validationTimeout=5000
idleTimeout=60000
maxLifetime=120000
connectionTestQuery=SELECT 1
readOnly=false
```
Sometime the SQL can not work normally.

**Comment by ggservice007** [comment]
Why a lot of handlers?

![image](https://user-images.githubusercontent.com/9192908/50889567-42e98a80-1433-11e9-9c50-34a32ff83979.png)

**Comment by ggservice007** [comment]
@filimonov 
I use mybatis. My program almost run normally. But sometime error occurs.

```cmd
The error occurred while setting parameters
SQL: select * from some_table where one = ?
exception, code: 1002
```

**Comment by filimonov** [comment]
> exception, code: 1002

Those issues may be related: 
https://github.com/yandex/clickhouse-jdbc/issues/122 
https://github.com/yandex/clickhouse-jdbc/issues/174

**Comment by alex-krash** [comment]
We've faced performance issues with official driver, when working with Date/DateTime fields - it uses parsing of incoming string into object. Issue was solved, when support for RowBinary read was implemented - https://github.com/yandex/clickhouse-jdbc/blob/a86eb8a65c25788f767e51a619f62073dbbfeddb/src/main/java/ru/yandex/clickhouse/ClickHouseStatement.java#L25
It does not work "out-of-the-box", e.g. it extends JDBC API, but it is blazing fast.

**Comment by blinkov** [comment]
At the moment "official" JDBC driver is supported by Yandex.Metrica team who develops it and uses it in production. This is the main reason for it's status, performance has nothing to do with it.

Other users are free to choose whatever implementation better fits their needs, this might include performance of select/insert queries into consideration.
