### ISSUE TITLE
Major: 'stable' apt repo contains the 'testing' version and vice-versa

### ISSUE THREAD

**Issue by pdeva** [yandex/ClickHouse#4019]
using ubuntu 18.04
repo used `deb http://repo.yandex.ru/clickhouse/deb/stable main/`
packages installed: "clickhouse-server clickhouse-client"

however, the package version installed is `v18.16.1-testing` instead of `v18.16.1-stable`

**Comment by pdeva** [comment]
i can confirm that the `stable` repo has the `testing` version and the `testing` repo has the `stable` version....

**Comment by alexey-milovidov** [comment]
Don't understand, why it is closed?
If it was your mistake - what exact?
