### ISSUE TITLE
memory limit cause server crash down

### ISSUE THREAD

**Issue by lzy305** [yandex/ClickHouse#4021]
My  test server RAM is 6Gb.
Now I run this sql:
create table xxx
  engine  = MergeTree partition by  year_month order by col_1
  as
select  toYYYYMM(rl.deliver_date) as year_month,
         rl.col_1,
         rl.col_2,
         rl.col_3,
         rl.col_4,
         rl.col_5,
         sum(rl.col_5) as month_cost,
         sum(rl.col_6) as month_qty
 from table_a rl
where rl.deliver_date >= toDate('2018-01-01', 'yyyy-mm-dd')
  and rl.deliver_date < toDate('2019-01-01', 'yyyy-mm-dd')
group by year_month,
         rl.col_1,
         rl.col_2,
         rl.col_3,
         rl.col_4,
         rl.col_5;

it cause my server crash down.  so I set max_memory_usage = 5000000000;

I run again.
but it not work.

error 
 Code: 241. DB::Exception: Received from 192.168.89.102:9000. DB::Exception: Memory limit (for query) exceeded: would use 4.68 GiB (attempt to allocate chunk of 134217728 bytes), maximum: 4.66 GiB.

How Do the sql run well?

**Comment by filimonov** [comment]
> it cause my server crash down.

Most probably OOM killer is killing server.

> How Do the sql run well?

You need to enable ondisk group by and order by. It can be done by setting up those 2 settings:
* `max_bytes_before_external_sort`
* `max_bytes_before_external_group_by`
Values should be smaller than max_memory_usage, for example `set max_memory_usage = 4000000000;`
It can be done in session by `set` command, or in users config file

**Comment by lzy305** [comment]
Thank you. It work well

**Comment by aa8808021** [comment]
> Thank you. It work well

hi， I have encountered the same problem. I want to know how to solve it. Which file are the two configuration items configured in?thank you
