### ISSUE TITLE
formatDateTime() week number issue

### ISSUE THREAD

**Issue by mac798** [yandex/ClickHouse#4023]
```
SELECT formatDateTime(toDate('2018-12-31'), '%V')

┌─formatDateTime(toDate('2018-12-31'), '%V')─┐
│ 01                                         │
└────────────────────────────────────────────┘
```

**Comment by alexey-milovidov** [comment]
https://en.wikipedia.org/wiki/ISO_week_date

%%
%V     The ISO 8601 week number (see NOTES) of the current year as a decimal number, range 01 to 53, where week 1 is the first week that has at least 4  days  in
              the new year.

NOTES
   ISO 8601 week dates
       %G, %g, and %V yield values calculated from the week-based year defined by the ISO 8601 standard.  In this system, weeks start on a Monday, and are numbered from
       01, for the first week, up to 52 or 53, for the last week.  Week 1 is the first week where four or more days fall within the new year (or, synonymously, week  01
       is:  the first week of the year that contains a Thursday; or, the week that has 4 January in it).  When three of fewer days of the first calendar week of the new
       year fall within that year, then the ISO 8601 week-based system counts those days as part of week 53 of the preceding year.  For example, 1  January  2010  is  a
       Friday, meaning that just three days of that calendar week fall in 2010.  Thus, the ISO 8601 week-based system considers these days to be part of week 53 (%V) of
       the year 2009 (%G); week 01 of ISO 8601 year 2010 starts on Monday, 4 January 2010.
%%

**Comment by alexey-milovidov** [comment]
We can implement other week numbers for your choice.

**Comment by karakum** [comment]
@alexey-milovidov, What about `SELECT formatDateTime(toDate('2018-12-31'), '%Y%V')` -> `201801` ?
It seems that new modificator "year of %V week" required.

**Comment by filimonov** [comment]
> @alexey-milovidov, What about `SELECT formatDateTime(toDate('2018-12-31'), '%Y%V')` -> `201801` ?

Other tools will work exactly the same:
```bash
➜ date -d "2018-12-31 12:00:00 CST" +"%Y%V"
201801
```

> It seems that new modificator "year of %V week" required.

Looks like it should be `W`.

```
➜ date --help | grep 'week number'
  %g   last two digits of year of ISO week number (see %G)
  %G   year of ISO week number (see %V); normally useful only with %V
  %U   week number of year, with Sunday as first day of week (00..53)
  %V   ISO week number, with Monday as first day of week (01..53)
  %W   week number of year, with Monday as first day of week (00..53)

➜ date -d "2018-12-31 12:00:00 CST" +"%Y%W"
201853
```

**Comment by karakum** [comment]
@alexey-milovidov, yes, but what about
```
$ date -d "2018-12-31 00:00:00" +"%G%V"
201901
```
help:
```
  %g   последние две цифры года для номера недели ISO (см. %G)
  %G   год для номера недели ISO (см. %V); обычно бывает полезно только с %V
```

**Comment by alexey-milovidov** [comment]
@karakum 
Yes, we need to add `%g` and `%G` for `formatDateTime`. That's very easy task. Does anyone want to do?
