### ISSUE TITLE
Parse DateTime consistently

### ISSUE THREAD

**Issue by ebati** [yandex/ClickHouse#4045]
Inserting string formatted datetime with subsecond and/or with time zone is working as expected with `date_time_input_format` setting set to `best_effort` (as tested with [this sql](https://github.com/yandex/ClickHouse/blob/master/dbms/tests/queries/0_stateless/00645_date_time_input_format.sql)). But 

```sql
SELECT toDateTime('2018-06-08T01:02:03.000Z')
```
gives error:

```
Code: 6. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Cannot parse string '2018-06-08T01:02:03.000Z' as DateTime: syntax error at position 19 (parsed just '2018-06-08T01:02:03'). 
```
I think both datetime parsing should behave the same so if `INSERT` can parse `toDateTime` should also parse the same string.

I am testing with docker image `yandex/clickhouse-server:18.16.1`

**Comment by den-crane** [comment]
Are you aware of parseDateTimeBestEffort ? 

select * from system.functions where name like '%Best%'

SELECT parseDateTimeBestEffort('2018-06-08T01:02:03.000Z')

**Comment by ebati** [comment]
Great news, i couldnt find that function :man_facepalming: . Closing issue.
