### ISSUE TITLE
Booleans in config true/false vs 1/0

### ISSUE THREAD

**Issue by crrlcx** [yandex/ClickHouse#4049]
Hi, could you please some help
What I have:
* **client version 18.16.1**
* **server version 18.16.1 revision 54412**
* Table engine: **ReplicatedReplacingMergeTree**
* Table active_replicas: **2**

What is my trouble:
* When run optimize — it's fail with "DB::Exception: No active replicas" error.

```shell
:) OPTIMIZE TABLE tbl_test;

OPTIMIZE TABLE tbl_test

Received exception from server (version 18.16.1):
Code: 254. DB::Exception: Received from localhost:9000, ::1. DB::Exception: No active replicas.

0 rows in set. Elapsed: 0.001 sec.
```
```shell
:) OPTIMIZE TABLE tbl_test FINAL;

OPTIMIZE TABLE tbl_test FINAL

Received exception from server (version 18.16.1):
Code: 254. DB::Exception: Received from localhost:9000, ::1. DB::Exception: No active replicas.

0 rows in set. Elapsed: 0.001 sec.
```

**UPD**
Replicated tables are correctly updated with zookeeper via http ch-to-ch connection over tcp/9009 port.

**Comment by M1hacka** [comment]
The same result is seen, when I try to drop a partition with:
`ALTER TABLE tbl_test DROP PARTITION 201901;`

**Comment by den-crane** [comment]
Seems your zookeeper servers not in one cluster.
Please show 
echo stat | nc <zookeeper ip> 2181
for all zoo servers

**Comment by M1hacka** [comment]
http://prntscr.com/m7tkhm

**Comment by carrolcox** [comment]
> Seems your zookeeper servers not in one cluster.
> Please show
> `echo stat | nc <zookeeper ip> 2181`
> for all zoo servers

* zoo only
```shell
Zookeeper version: 3.4.10-3--1, built on Sat, 03 Feb 2018 14:58:02 -0800
Clients:
 /10.130.0.1:44908[0](queued=0,recved=1,sent=0)
 /10.130.0.1:56854[1](queued=0,recved=320,sent=320)

Latency min/avg/max: 0/1/282
Received: 321
Sent: 320
Connections: 2
Outstanding: 0
Zxid: 0x2800000073
Mode: follower
Node count: 187
```
* zoo + ch 01
```shell
Zookeeper version: 3.4.10-3--1, built on Sat, 03 Feb 2018 14:58:02 -0800
Clients:
 /10.130.0.1:43610[0](queued=0,recved=1,sent=0)
 /10.130.0.52:33346[1](queued=0,recved=237,sent=244)
 /10.130.0.1:53604[1](queued=0,recved=79,sent=79)

Latency min/avg/max: 0/21/1889
Received: 317
Sent: 323
Connections: 3
Outstanding: 0
Zxid: 0x2800000073
Mode: follower
Node count: 187
```
* zoo + ch 02
```shell
Zookeeper version: 3.4.10-3--1, built on Sat, 03 Feb 2018 14:58:02 -0800
Clients:
 /10.130.0.50:42346[1](queued=0,recved=90,sent=90)
 /10.130.0.1:36390[0](queued=0,recved=1,sent=0)
 /10.130.0.1:53888[1](queued=0,recved=83,sent=83)
 /10.130.0.51:36396[1](queued=0,recved=252,sent=253)

Latency min/avg/max: 0/11/2036
Received: 426
Sent: 426
Connections: 4
Outstanding: 0
Zxid: 0x2800000073
Mode: leader
Node count: 187
```

**Comment by carrolcox** [comment]
Replicated tables are correct updating with zookeeper via http ch-to-ch connection over tcp/9009 port.
PS: Also I was update the topic message.

**Comment by carrolcox** [comment]
Looks like my issue is solved.
---
The problem was in the __`replicated_can_become_leader`__ parameter. I set it to _`true`_, according to the documentation and description in [MergeTreeSettings.h](https://github.com/yandex/ClickHouse/blob/v18.16.1-stable/dbms/src/Storages/MergeTree/MergeTreeSettings.h). 

However, this parameter must be set to _`1`_.

Replication also works when it is not set (clickhouse uses the default value).

Examples
---
* Parameter is considered as __`False`__ (normal behavior):
    ```xml
    <merge_tree>
       …
       <replicated_can_become_leader>false</replicated_can_become_leader>
       …
    ```
    ```xml
     <merge_tree>
            …
            <replicated_can_become_leader>False</replicated_can_become_leader>
            …
    ```
    ```xml
     <merge_tree>
            …
            <replicated_can_become_leader>0</replicated_can_become_leader>
            …
    ```
* Parameter is considered as __`False`__ (NOT normal behavior):
    ```xml
     <merge_tree>
            …
            <replicated_can_become_leader>true</replicated_can_become_leader>
            …
    ```
    ```xml
     <merge_tree>
            …
            <replicated_can_become_leader>True</replicated_can_become_leader>
            …
    ```
* Parameter is considered as __`True`__ (normal behavior):
    ```xml
     <merge_tree>
            …
            <replicated_can_become_leader>1</replicated_can_become_leader>
            …
    ```
Description of XMS xs:boolean
---
> The value space of xs:boolean is “true” and “false” and its lexical space accepts true, false, and also “1” (for true) and “0” (for false).

Description of __`replicated_can_become_leader`__ from [MergeTreeSettings.h](https://github.com/yandex/ClickHouse/blob/v18.16.1-stable/dbms/src/Storages/MergeTree/MergeTreeSettings.h)
---
> ```cpp
> /** If true, Replicated tables replicas on this node will try to acquire leadership. */                   \
> M(SettingBool, replicated_can_become_leader, true)
>```

**Comment by filimonov** [comment]
Fixed in https://github.com/yandex/ClickHouse/pull/6278
