### ISSUE TITLE
Неоднозначное поведение мутации

### ISSUE THREAD

**Issue by YuryRyapolov** [yandex/ClickHouse#4058]
Здравствуйте. Заметил такую особенность, если нужно выполнить несколько мутаций подряд, то зачастую часть мутаций попадает в таблицу **system.mutations**, через время помечается как выполненные но при этом данные которые должны были быть удалены остаются в таблице. 
Для примера сымитировал проблему на Java [Код](https://github.com/YuryRyapolov/clickhouse-test-mutations). Тесты проводил на Clickhouse 18.16.1 revision 54412, Debina 9 все настройки по умолчанию.
Во время теста в clickhouse загружается набор из 1 млн записей, после чего выполняется их удаление с помощью мутации: ALTER TABLE … DELETE WHERE docId IN (…) по 500 ID за раз.
Если тест выполнить как есть, т.е. мутации идут одна за одной в цикле:
ALTER TABLE … DELETE WHERE docId IN (…);
ALTER TABLE … DELETE WHERE docId IN (…);
…
То после того, как все мутации завершаться – большая часть документов останется в таблице, при этом в таблице **system.mutations** есть все необходимые команды на удаление, и они все помечены как выполненные.
Если в тесте в методе removeData добавить задержку >= 150 мс т.е. мутации будут выполняться в следующем порядке:
ALTER TABLE … DELETE WHERE docId IN (…);
SLEEP(150);
ALTER TABLE … DELETE WHERE docId IN (…);
SLEEP(150);
…
То после того, как все мутации завершаться – с высокой степенью вероятности таблица становится полностью пустой (как и задумывалось).
В общем чем меньше задержка между созданием мутаций, тем выше вероятность того, что часть из них не выполнится.

**Comment by ztlpn** [comment]
Fixed in 19.3.3, 19.1.7.
