### ISSUE TITLE
odbc-bridge fork/exec socket leak and hung connections

### ISSUE THREAD

**Issue by nvartolomei** [yandex/ClickHouse#4060]
Symptom: A request to ClickHouse is stuck, socket to ClickHouse http port is in ESTABLISHED state but belongs to `odbc-bridge` instead of `clickhouse-server` 😱

Here is my hypothesis so far:

At the moment `odbc-bridge` is started lazily when it is needed (odbc table/dictionary) is used. If it is running it - is used as is, otherwise a odbc-bridge is started. (not 100% sure if I got this right yet) https://github.com/yandex/ClickHouse/blob/0822f500f8c174ee46a47218deb40ca0c5f64acd/dbms/src/Common/XDBCBridgeHelper.h#L144-L149

`startBridge` method uses vfork and execv in order to launch a child process.

The problem is that during vfork/execv dance, fd table of the parent process which has sockets for TCP and HTTP connections are copied to the odbc-bridge. However odbc-bridge is not aware of them, so they are never closed.

If dictionaries are reloaded at server start (and odbc-bridge is started at the same time) this is not a big issue. However, if odbc-bridge crashes, or is intentionally restarted – sockets will be leaked.

**Comment by alesapin** [comment]
This assumption is not correct:
`The problem is that during vfork/execv dance, fd table of the parent process which has sockets for TCP and HTTP connections are copied to the odbc-bridge. However odbc-bridge is not aware of them, so they are never closed.`
odbc-bridge closes all parents FDs on start https://github.com/yandex/ClickHouse/blob/master/dbms/programs/odbc-bridge/ODBCBridge.cpp#L118 (https://github.com/yandex/ClickHouse/blob/master/libs/libdaemon/src/BaseDaemon.cpp#L782-L811).

Please, can you provide reproducible example or at least something like `lsof` output, which can confirm the issue?

On my machine everything seems ok:
```
$ ps ax | grep clickhouse
1033543 pts/9    Sl+    0:01 ./clickhouse-server --config $HOME/clickhouseconf/config.xml
1033633 pts/9    Sl+    0:00 $HOME/ClickHouse/bld/dbms/programs/clickhouse odbc-bridge --http-port 9018 --listen-host localhost --http-timeout 180000000
```
```
$ sudo lsof -p 1033543
COMMAND       PID   USER   FD      TYPE    DEVICE   SIZE/OFF      NODE NAME
... so-libraries, some pipes, binaries ...
clickhous 1033543 alesap   12u     IPv6 491980827        0t0       TCP localhost:9000->localhost:40364 
```
```
$ sudo lsof -p 1033633
COMMAND       PID   USER   FD      TYPE             DEVICE   SIZE/OFF      NODE NAME
... so-libraries, some pipes, binaries ...
clickhous 1033633 alesap    3u     IPv6          491980152        0t0       TCP localhost:9018 (LISTEN)
clickhous 1033633 alesap    6u     unix 0xffff880130780c00        0t0 491980153 type=STREAM
clickhous 1033633 alesap    8r      CHR                1,9        0t0        16 /dev/urandom
clickhous 1033633 alesap   10u     IPv4          491979700        0t0       TCP localhost:44262->localhost:postgresql (ESTABLISHED)

```

**Comment by nvartolomei** [comment]
pid process name

```
20577 /usr/bin/clickhouse odbc-bridge --http-port 9018 --listen-host localhost --http-timeout 1800000000
```

some random lines that i think are related to the issue, stripped `ss`

```
LISTEN     0      64     127.0.0.1:9018                     *:*                     users:(("clickhouse",pid=20577,fd=3))
ESTAB      0      0      127.0.0.1:9018                 127.0.0.1:62138                 users:(("clickhouse",pid=20577,fd=5))
ESTAB      0      0      an-ip:43142                some-ip:postgresql            users:(("clickhouse",pid=20577,fd=7)) timer:(keepalive,15min,0)
CLOSE-WAIT 6      0      127.0.0.1:9018                 127.0.0.1:47934                 users:(("clickhouse",pid=20577,fd=4))
)
ESTAB      1218064 0       local-ip:33900                 a-remote-ip:9000                  users:(("clickhouse",pid=20577,fd=3638))
ESTAB      0      0       lolcal-ip:9000                  other-remote-ip:48800                 users:(("clickhouse-serv",pid=124064,fd=3254),("clickhouse",pid=20577,fd=3254))
```

**Comment by nvartolomei** [comment]
Live from a machine:

```
$ ps ax | grep clickhouse


 69950 ?        Sl   128877:09 /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml
 73474 ?        Z     36:04 [clickhouse] <defunct>
 99308 ?        Sl     7:54 /usr/bin/clickhouse odbc-bridge --http-port 9018 --listen-host localhost --http-timeout 1800000000
120283 ?        Z      3:22 [clickhouse] <defunct>
145449 ?        Z     37:10 [clickhouse] <defunct>
204421 ?        Z     35:47 [clickhouse] <defunct>
```

```
$ sudo lsof -p 99308

libraries

lots of 

clickhous 99308      IPv6 1070769918         0t0        TCP ...:9000->[...]:53006 (ESTABLISHED)
clickhous 99308      IPv6 1089339200         0t0        TCP ...:9000->[...]:48712 (ESTABLISHED)
clickhous 99308      IPv6 1142650532         0t0        TCP ...:65518->[...]:9000 (ESTABLISHED)
clickhous 99308      IPv6 1070808254         0t0        TCP ...:9000->[...]:41040 (ESTABLISHED)

then lots of 

clickhous 99308     REG      9,127     5582938 1602289981 /var/lib/clickhouse/data/r1/censored/tmp_delete_20190117_20190121_163005_163074_3/columnName.bin (deleted)

and event poll
```

**Comment by alesapin** [comment]
hmm... looks strange. Which version of clickhouse do you use? You use linux or some other OS (maybe run it in docker)? Seems like closeFDs doesn't work correctly in your setup. Actually, it was tested on linux only.

**Comment by nvartolomei** [comment]
```c
stat("/proc/self/fd", {st_mode=S_IFDIR|0500, st_size=0, ...}) = 0
open("/proc/self/fd", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 12
fstat(12, {st_mode=S_IFDIR|0500, st_size=0, ...}) = 0
getdents(12, /* 287 entries */, 32768)  = 6888
close(3)                                = 0
close(4)                                = 0
...
close(12)                               = 0
...
getdents(12, 0x..., 32768)     = -1 EBADF (Bad file descriptor)
close(12)                               = -1 EBADF (Bad file descriptor)
```

We are asymptotically approaching the limits of my linux fu, but looks like it closed fd to `/proc/self/fd` 🙃 and fails getting next batch of files

**Comment by alesapin** [comment]
https://github.com/yandex/ClickHouse/pull/4120

**Comment by YuYuYan** [comment]
JDBC occurs the same leak, how do fix it

**Comment by YuYuYan** [comment]
thank you very much ,please help me

**Comment by filimonov** [comment]
@YuYuYan It can be the same leak only if you use a very old clickhouse version. 

Otherwise, it's something different and we need a detailed report and reproducible scenario to be able to help you.
