### ISSUE TITLE
Mutation processes all parts instead of needed

### ISSUE THREAD

**Issue by vasyaabr** [yandex/ClickHouse#4062]
We have ReplicatedMergeTree table, declared in the old way (3 replicas):

> CREATE TABLE Turnovers (RecordDate Date, ... ) ENGINE = ReplicatedMergeTree('/clickhouse/tables/db/Turnovers', '{replica}', RecordDate, (RecordDate, NetID, StallID, UserID, GameID), 8192);

After applying mutation 

> ALTER TABLE Turnovers DELETE WHERE RecordDate = '2018-12-21'  AND ...

We see in **system.mutations**, that **parts_to_do** for this mutation = 1, but in the logs we see, that Clickhouse is processing each part from the very beginning (201001), but not the only needed part '201812'. Looks like a bug in implementation.

Clickhouse server 18.14.11.

**Comment by ztlpn** [comment]
This is as expected. The server will still have to look at each part to determine if the mutation changes the part or not, but the parts that are not changed will be cloned from the old parts using hard links, which should be very cheap.

**Comment by vasyaabr** [comment]
Thanks

**Comment by simPod** [comment]
@vasyaabr How did you find it in logs? My mutations hang on `parts_to_do` 1 too but so far I have not found a way to check whether it's doing something or not.

**Comment by den-crane** [comment]
@simPod check that you don't have parts with a size bigger than max_bytes_to_merge_at_max_space_in_pool

```
select table, partition, name, round(bytes_on_disk / 1024/1024/1024) size 
from system.parts where bytes_on_disk > (select toInt64(value) from system.merge_tree_settings where name = 'max_bytes_to_merge_at_max_space_in_pool'); 
```

**Comment by simPod** [comment]
@den-crane thanks for response. It eventually finished, it just makes one nervous that it processes several hunded parts in minutes and for the last one it waits few hours and there's no way to check it's doing something.

**Comment by den-crane** [comment]
>several hunded parts in minutes and for the last one it waits few hours

I observe this every time. This is because a mutation mutates all parts and for most of parts it just do clones (hard-links) because they are not covered by where. And real mutation takes time -- need to read/uncompress a column and write/compress.
