### ISSUE TITLE
if I can set clickhouse as mysql slave?

### ISSUE THREAD

**Issue by justlooks** [yandex/ClickHouse#4070]
hi, I already try https://github.com/Altinity/clickhouse-mysql-data-reader ,but when import data into clickhouse from csv file ,it broken. I want to ask if any other tool can do replication between mysql and clickhouse?

**Comment by alex-zaitsev** [comment]
Altinity replicator works in production in some companies, so it is reliable enough. Thanks for the problem report, we will look what's wrong.

Continuent recently released replication to ClickHouse as well, you can try it out: https://www.continuent.com/replicating-data-into-clickhouse/

**Comment by blinkov** [comment]
I'm not aware of any alternative similar tools. You could start with some more simple table and gradually come closer to real one to figure out what exactly is not working. Or just manually convert your data to one of formats supported by ClickHouse https://clickhouse.yandex/docs/en/interfaces/formats/

Link to your original issue so it's not lost in future:
https://github.com/Altinity/clickhouse-mysql-data-reader/issues/143

**Comment by justlooks** [comment]
> Altinity replicator works in production in some companies, so it is reliable enough. Thanks for the problem report, we will look what's wrong.
> 
> Continuent recently released replication to ClickHouse as well, you can try it out: https://www.continuent.com/replicating-data-into-clickhouse/

where  I can get the new release of Tungsten replicator? should I need by it?

**Comment by justlooks** [comment]
> > where I can get the new release of Tungsten replicator? should I need by it?
> 
> From their "download" page it looks like it's the commercial software, not open source.

yes, it seems not fit for me :(

**Comment by justlooks** [comment]
> I'm not aware of any alternative similar tools. You could start with some more simple table and gradually come closer to real one to figure out what exactly is not working. Or just manually convert your data to one of formats supported by ClickHouse https://clickhouse.yandex/docs/en/interfaces/formats/
> 
> Link to your original issue so it's not lost in future:
> [Altinity/clickhouse-mysql-data-reader#143](https://github.com/Altinity/clickhouse-mysql-data-reader/issues/143)

i reinstalled the clickhouse-mysql with git clone, one of problem is when dump ddl from MySQL ,it will convert all decimal to string ,that will cause import action failed.I think it is a bug and  updated the issue .

**Comment by DivyaRao30** [comment]
Is there any option to migrate table from MySql/MariaDB to Clickhouse in real time with some 10 to 15 sec of difference ?

Thanks

**Comment by DivyaRao30** [comment]
Is there any option to migrate table from MySql/MariaDB to Clickhouse in real time with some 10 to 15 sec of difference ?

Thanks

**Comment by blinkov** [comment]
@Crazylearner30 https://github.com/Altinity/clickhouse-mysql-data-reader#mysql-migration-case-1---listen-for-new-data is supposed to do that.

**Comment by Crazylearner30** [comment]
Thanks

**Comment by alexey-milovidov** [comment]
PS. You can also do it with PostgreSQL: https://github.com/mkabilov/pg2ch

**Comment by BohuTANG** [comment]
Hi,

It's a bit late, but we can now use MaterializeMySQL engine to replicate MySQL datas.
```
CREATE DATABASE ckdb ENGINE = MaterializeMySQL('172.17.0.2:3306', 'ckdb', 'root', '123');
```
