### ISSUE TITLE
when i batch insert into clickhouse table make the system crash and power off

### ISSUE THREAD

**Issue by qinzl1** [yandex/ClickHouse#4071]
/var/log/message 
kernel: BUG: scheduling while atomic: HTTPHandler/186790/0xffffea00
batch number 1000 rows

**Comment by ggservice007** [comment]
A lot of HTTPHandlers

**Comment by den-crane** [comment]
Please provide stack-trace(s) from /var/log/clickhouse-server.log

**Comment by 4ertus2** [comment]
ClickHouse cannot lead to power off of your system. It's you kernel / hardware issue.
