### ISSUE TITLE
18.16.1 Operation not permitted

### ISSUE THREAD

**Issue by afpd** [yandex/ClickHouse#4095]
Hello!

Deb package version 18.16.1   from Yandex repository gives errors:

# clickhouse-extract-from-config: Operation not permitted

Need to emphasis what clickhouse deployed inside systemd-nspawn container.

Strace shows that makedev attempt has failed. 

# strace /usr/bin/clickhouse-client
execve("/usr/bin/clickhouse-client", ["/usr/bin/clickhouse-client"], 0x7ffc58cc3260 /* 10 vars */) = -1 EPERM (Operation not permitted)
fstat(2, {st_mode=S_IFCHR|0600, st_rdev=makedev(136, 0), ...}) = 0
write(2, "strace: exec: Operation not perm"..., 38strace: exec: Operation not permitted

Problem does not exists in version 18.14.17 since that version doesn't try to [re]create device (136, 0)

**Comment by alexey-milovidov** [comment]
#4136
