### ISSUE TITLE
Out-Of-Memeory during INSERTs

### ISSUE THREAD

**Issue by agend** [yandex/ClickHouse#4104]
We set up a cluster for test. 1 bln rows of data. We are trying to load data in batches. All requests are sent via single node (there are 4 nodes with 2 shards and 2 replicas). Memory is consumed only on node which is used for connection to the cluster. But after some time clickhouse consume all available RAM and got killed by OOM.
![screenshot from 2019-01-20 18-23-42](https://user-images.githubusercontent.com/2485016/51442835-11ee3d00-1cf2-11e9-8f45-8872d69cee50.png)

I have tried to use this settings: by
```
            <max_memory_usage>1368709120</max_memory_usage>
            <max_memory_usage_for_user>4368709120</max_memory_usage_for_user>
            <max_memory_usage_for_all_queries>4368709120</max_memory_usage_for_all_queries>
            <max_concurrent_queries_for_user>4368709120</max_concurrent_queries_for_user>
```
Other nodes in cluster just fine and don't have issued with memory at all:
![screenshot from 2019-01-20 18-27-41](https://user-images.githubusercontent.com/2485016/51441291-19591a80-1ce1-11e9-9c4d-bf900efc9e0c.png)

Any help?

**Comment by den-crane** [comment]
What CH version do you use? How much memory does your servers have? Please provide table DDL.

max_memory_usage* -- these settings are limit for selects. So your select will fail if it tries to use more than this limit.

To reduce insert memory usage try to lower max_insert_block_size (1mil rows by default).
Try to disable <compile_expressions>0</compile_expressions> #3976
Try to lower mark_cache_size -- 5Gb by default <mark_cache_size>1368709120</mark_cache_size>

**Comment by agend** [comment]
Here you go:
`Connected to ClickHouse server version 18.16.1 revision 54412.`
RAM: 8 GB

We send data by 10000 rows.
We already had decreased mark_cache_size 
`<mark_cache_size>1368709120</mark_cache_size>`

Пробуем с опцией <compile_expressions>0</compile_expressions>

Thx

**Comment by agend** [comment]
`<compile_expressions>0</compile_expressions>` fix the issue with memory. Thank you for help.
