### ISSUE TITLE
SQL query alias matched with column name leads to data substitution in unpredictable way.

### ISSUE THREAD

**Issue by kkrakovych** [yandex/ClickHouse#4110]
Hi Team,

Could you please check SQL below and clarify why ClickHouse returns 11 for A and 13 for B though 12 for B is expected? It does not matter wether we work with subquery or table. And it does not matter either alias B goes before or after A.

In the SQL query we obviously specify - we want to get data from table/subquery S and add +1 and +2 in different aliases. Yes, alias A is the same with column name, but it looks like you substitute table/subquery data on the fly.

```sql
select s.a + 1 as a
     , s.a + 2 as b
  from (
         select 10 as a
         ) s
```

If we talk about Oracle, PostgreSQL or any other DBMS - the mentioned behavior of DBMS is a bug.

Best regards,
Kostyantyn

**Comment by 4ertus2** [comment]
#4351

**Comment by 4ertus2** [comment]
fixed in master
