### ISSUE TITLE
ClickHouse function IF treats NULL values in different way than expected

### ISSUE THREAD

**Issue by kkrakovych** [yandex/ClickHouse#4114]
Hi Team,

Could you please clarify why ClickHouse function IF treats NULL values in different way comparing with CASE?

1. NULL values are enabled on CLickHouse server.
2. When we compare NULL value with something in CASE statement NULL with anything produces FALSE condition.
3. When we compare NULL value with something in IF function NULL with anything produces NULL, not a FALSE result.

Please check SQL below:

```sql
select if(1=1,    'A', 'B')                   as if_a      -- A
     , if(1=2,    'A', 'B')                   as if_b      -- B
     , if(null=1, 'A', 'B')                   as if_null   -- NULL
     , case when 1=1    then 'A' else 'B' end as case_a    -- A
     , case when 1=2    then 'A' else 'B' end as case_b    -- B
     , case when null=1 then 'A' else 'B' end as case_null -- B
     , 'dumb text'
```

Could you please clarify is it a bug?

Best regards,
Kostyantyn

**Comment by alexey-milovidov** [comment]
Fixed in https://github.com/yandex/ClickHouse/pull/5238
