### ISSUE TITLE
Cannot read all marks from file *.size1.mrk.

### ISSUE THREAD

**Issue by magnum-ferox** [yandex/ClickHouse#413]
ClickHouse client version 1.1.54134.
Connecting to localhost:9000.
Connected to ClickHouse server version 1.1.54134.

```
CREATE TABLE test (
    uid UInt64,
    chaining Nested (
        uid UInt64,
        sources Array(Int8)
    ),

	date Date,
	sign Int8
)
ENGINE = CollapsingMergeTree(date, (uid), 8192, sign);
```
ok!

`INSERT INTO test (uid, chaining.uid, chaining.sources) VALUES (1, [123, 456], [[1, 3], [3, 12]]);`
ok!

```
SELECT count(*) FROM test;

┌─count()─┐
│       1 │
└─────────┘
```

```
SELECT chaining.uid FROM test;

┌─chaining.uid─┐
│ [123,456]    │
└──────────────┘
```

```
SELECT chaining.sources FROM test;

Received exception from server:
Code: 33. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Cannot read all marks from file /opt/clickhouse/data/xxx/test/19700101_19700101_2_2_0/chaining.size1.mrk.
```

**Comment by ztlpn** [comment]
Arrays inside Nested are equivalent to multidimensional arrays which are not supported by MergeTree engines. Duplicates: #234 #193. As this bug surfaces pretty frequently, we will add checks forbidding the creation of such tables.

For now you should stick to single-level nested structures.
