### ISSUE TITLE
[Question] Clickhouse Replication factor

### ISSUE THREAD

**Issue by igor-sh8** [yandex/ClickHouse#4139]
Hello. 
Have a small question about replication factor. I want to use clickhouse replicated/distributed mechanism with some replication factor? For example I have 3 hosts with replication factor 2, so every node need to store data 2 times. Is it possible to use such schema ?

**Comment by blinkov** [comment]
It's possible, but less convenient than 2 shards with 2 replicas (on 4 nodes). Here's an article describing this: https://www.altinity.com/blog/2018/5/10/circular-replication-cluster-topology-in-clickhouse

**Comment by igor-sh8** [comment]
Great, thanks. It works well. 
Considering that we now have all the databases different, I can’t normally use queries with `ON CLUSTER` statement ? Or maybe `ON CLUSTER` has also some additional properties like the "default database" ?

**Comment by filimonov** [comment]
> I can’t normally use queries with ON CLUSTER statement 

Unfortunately currently ON CLUSTER doesn't support that scenario (AFAIK)
