### ISSUE TITLE
How do I configure multiple zookeeper clusters?

### ISSUE THREAD

**Issue by iameugenejo** [yandex/ClickHouse#4146]
The documentation says `For very large clusters, you can use different ZooKeeper clusters for different shards`, and I couldn't find any documentation about how this can be achieved.

**Comment by KochetovNicolai** [comment]
You just need to use different zookeeper's hosts in config.xml (zookeeper cluster must be the same for replicas in ReplicationMergeTree, but may be different for different shards).
Actually, we use single zookeeper cluster for more than 500 nodes, and it works fine.

**Comment by iameugenejo** [comment]
Just having different zookeer hosts in config makes the different shards to use different zookeeper clusters? How does that work? I already have multiple zookeepers in the config but they are clustered.

First, how do I configure multiple zookeeper clusters, and second how do I point a shard to one zookeeper cluster and another to the other zookeeper cluster?

**Comment by filimonov** [comment]
Hm. Most probably in that case ON CLUSTER DDL/mutations will work only inside shard scope. 

Do you have some issues with single zookeeper?

**Comment by iameugenejo** [comment]
We see `fsync-ing the write ahead log in SyncThread:* took *ms which will adversely effect operation latency` warning frequently atm. It's not causing any issues but I'd need to prepare to scale the zookeeper if it does in the future when we increase the inserts by 20 fold (650billion rows per day). And also we're planning to migrate the instances from physical hardwares to VMs, and I don't know how much negative impact on the zookeeper there would be, so I'm just planning ahead.

**Comment by filimonov** [comment]
Looks like I/O issues from zookeeper (slow write on disk). 
Stupid questions:
1) you have zookeeper on separate servers (Installing zookeeper on the same servers as ClickHouse is usually a very bad idea)
2) zookeeper's `dataDir` points to some fast / not overused disk (ideally separate SSD)?

Generally, each shard can be considered as a separate cluster. Configure each shard separately (as they don't know anything about each other) and afterwards create a Distributed table above.

For huge clusters, it's worth to consider multilevel sharding (like Distribured over Distributed), that allow optimizing inter-server data exchange is a case when there are hundreds of servers.

**Comment by iameugenejo** [comment]
1. We don't have clickhouse running on the boxes zookeeper is running. Though we have ingestor (inserter) running on the zookeeper boxes. The ingestors do not write on disks, perform less memory and high cpu usage tasks, whereas zookeeper uses decent memory and less cpu with high disk usages. So we decided to have them in the same box to utilize the resources efficiently.
2. It's on a dedicated set of 4 spindles in raid-0.

And for more information, the raw rows ingested are inserted into 4 different materialized views that merges them into smaller number of rows (number of rows going down to about 0.2%), and the materialized views are the only tables being replicated, not the raw table. As far as I know the merge happens after a while but replication still happens beforehand, so the number of nodes (and I/O) in the zookeeper will be still be much higher than 0.2% of ingested.

Thanks for providing information on how to use different zookeeper clusters for different shards. I think I get the idea now. It would be great if such information is available somewhere in the official documentation with some example configurations for different clickhouse clusters with different zookeeper clusters setup for each.

**Comment by filimonov** [comment]
> Though we have ingestor (inserter) running on the zookeeper boxes. The ingestors do not write on disks, perform less memory and high cpu usage tasks, whereas zookeeper uses decent memory and less cpu with high disk usages. So we decided to have them in the same box to utilize the resources efficiently.

That kind of server sharing still may be the reason of those write delays. It sounds like you have quite a big steam of incoming data, so even if that data is not written do disks by your ingestor it still creates quite high I/O load (push the data through system bus, read/write memory etc). And smaller but dedicated zookeeper servers may work better.

**Comment by iameugenejo** [comment]
I see, I'll try separating them out when we migrate to another environment. Thank you for the suggestion.

**Comment by iameugenejo** [comment]
Thank you, will try out.
