### ISSUE TITLE
How to add new server

### ISSUE THREAD

**Issue by qietingfengling** [yandex/ClickHouse#4157]
Is there a better way to expand, except to modify the weight of the shard?

**Comment by KochetovNicolai** [comment]
I think now modifying weights is the best way.
You can also reshard all data using [clickhouse-copier](https://clickhouse.yandex/docs/en/single/#utils/clickhouse-copier/), but it's not so cheap.

**Comment by nvartolomei** [comment]
@KochetovNicolai how would you reshard data if date is used as partition key and partitions are present on both servers? From the following comment my understanding is that it is not possible. Let me know if I did misinterpret it.

```
NOTE: In spite of this section is optional (if it is not specified, all partitions will be copied),
                 it is strictly recommended to specify them explicitly.
                 If you already have some ready paritions on destination cluster they
                 will be removed at the start of the copying since they will be interpeted
                 as unfinished data from the previous copying!!!
```
