### ISSUE TITLE
Exception "Data compressed with different methods" when doing JOIN

### ISSUE THREAD

**Issue by jvitkauskas** [yandex/ClickHouse#4160]
# Version
ClickHouse server version 19.1.6 revision 54413 on Ubuntu 18.04.1 LTS (Linux 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)

# Repro

```sql
CREATE TABLE head
(
  pathid Int64,
  client Int32
)
ENGINE = MergeTree()
ORDER BY pathid
PRIMARY KEY pathid;

CREATE TABLE body
(
  pathid Int64,
  interaction Int32
)
ENGINE = MergeTree()
ORDER BY pathid;

INSERT INTO head values(1, 1);
INSERT INTO head values(2, 1);
INSERT INTO head values(3, 1);

INSERT INTO body values(1, 100);
INSERT INTO body values(1, 200);
INSERT INTO body values(1, 100);
INSERT INTO body values(1, 100);

SELECT *
FROM head 
ALL LEFT JOIN body USING (pathid);
```

# Exception

> Exception on client:
> Code: 271. DB::Exception: Data compressed with different methods, given method byte 69, previous method byte 82: while receiving packet from localhost:9000, 127.0.0.1

**Comment by jvitkauskas** [comment]
I know this is not the preferred way to select data from ClickHouse, but it was the first thing I have tried and even if I am no longer using that table arrangement, I think this issue (exception) should be still valid.

**Comment by 4ertus2** [comment]
fixed in master
