### ISSUE TITLE
19.1.6 segfaults

### ISSUE THREAD

**Issue by rpfennin** [yandex/ClickHouse#4187]
I am not sure the root cause but I'm seeing this consistently since upgrading from 18.16.1 to 19.1.6:

2019.01.29 13:19:46.432464 [ 2 ] {} <Error> BaseDaemon: ########################################
2019.01.29 13:19:46.432571 [ 2 ] {} <Error> BaseDaemon: (from thread 9) Received signal Segmentation fault (11).
2019.01.29 13:19:46.432596 [ 2 ] {} <Error> BaseDaemon: Address: NULL pointer.
2019.01.29 13:19:46.432615 [ 2 ] {} <Error> BaseDaemon: Access: read.
2019.01.29 13:19:46.432633 [ 2 ] {} <Error> BaseDaemon: Unknown si_code.
2019.01.29 13:19:46.547646 [ 2 ] {} <Error> BaseDaemon: 0. /usr/bin/clickhouse-server(DB::MergeTreeReader::Stream::loadMarks()+0x59c) [0x75b30ec]
2019.01.29 13:19:46.547697 [ 2 ] {} <Error> BaseDaemon: 1. /usr/bin/clickhouse-server(DB::MergeTreeReader::Stream::seekToMark(unsigned long)+0xb5) [0x75b4765]
2019.01.29 13:19:46.547724 [ 2 ] {} <Error> BaseDaemon: 2. /usr/bin/clickhouse-server() [0x75b4d0f]
2019.01.29 13:19:46.547756 [ 2 ] {} <Error> BaseDaemon: 3. /usr/bin/clickhouse-server(DB::IDataType::deserializeBinaryBulkWithMultipleStreams(DB::IColumn&, unsigned long, DB::IDataType::DeserializeBinaryBulkSettings&, std::shared_ptr<DB::IDataType::DeserializeBinaryBulkSt
ate>&) const+0x28) [0x3482ad8]
2019.01.29 13:19:46.547781 [ 2 ] {} <Error> BaseDaemon: 4. /usr/bin/clickhouse-server(DB::DataTypeNullable::deserializeBinaryBulkWithMultipleStreams(DB::IColumn&, unsigned long, DB::IDataType::DeserializeBinaryBulkSettings&, std::shared_ptr<DB::IDataType::DeserializeBinar
yBulkState>&) const+0x179) [0x6eb3cb9]
2019.01.29 13:19:46.547805 [ 2 ] {} <Error> BaseDaemon: 5. /usr/bin/clickhouse-server(DB::MergeTreeReader::readData(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::IDataType const&, DB::IColumn&, unsigned long, bool, unsigned lo
ng, bool)+0x2b2) [0x75b0512]
2019.01.29 13:19:46.547830 [ 2 ] {} <Error> BaseDaemon: 6. /usr/bin/clickhouse-server(DB::MergeTreeReader::readRows(unsigned long, bool, unsigned long, DB::Block&)+0x387) [0x75b0ce7]
2019.01.29 13:19:46.547852 [ 2 ] {} <Error> BaseDaemon: 7. /usr/bin/clickhouse-server(DB::MergeTreeSequentialBlockInputStream::readImpl()+0x328) [0x7278118]
2019.01.29 13:19:46.547868 [ 2 ] {} <Error> BaseDaemon: 8. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x262) [0x6e21b62]
2019.01.29 13:19:46.547883 [ 2 ] {} <Error> BaseDaemon: 9. /usr/bin/clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x2e) [0x73adb6e]
2019.01.29 13:19:46.547899 [ 2 ] {} <Error> BaseDaemon: 10. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x262) [0x6e21b62]
2019.01.29 13:19:46.547915 [ 2 ] {} <Error> BaseDaemon: 11. /usr/bin/clickhouse-server(DB::MaterializingBlockInputStream::readImpl()+0x3b) [0x73c220b]
2019.01.29 13:19:46.547930 [ 2 ] {} <Error> BaseDaemon: 12. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x262) [0x6e21b62]
2019.01.29 13:19:46.547952 [ 2 ] {} <Error> BaseDaemon: 13. /usr/bin/clickhouse-server(DB::MergingSortedBlockInputStream::init(std::vector<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn> > >&)+0xce) [0x73daaae]
2019.01.29 13:19:46.547970 [ 2 ] {} <Error> BaseDaemon: 14. /usr/bin/clickhouse-server(DB::MergingSortedBlockInputStream::readImpl()+0x65) [0x73dc085]
2019.01.29 13:19:46.547985 [ 2 ] {} <Error> BaseDaemon: 15. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x262) [0x6e21b62]
2019.01.29 13:19:46.548004 [ 2 ] {} <Error> BaseDaemon: 16. /usr/bin/clickhouse-server(DB::MergeTreeDataMergerMutator::mergePartsToTemporaryPart(DB::MergeTreeDataMergerMutator::FuturePart const&, DB::MergeListEntry&, long, DB::DiskSpaceMonitor::Reservation*, bool)+0x289f)
 [0x722602f]
2019.01.29 13:19:46.548021 [ 2 ] {} <Error> BaseDaemon: 17. /usr/bin/clickhouse-server(DB::StorageReplicatedMergeTree::tryExecuteMerge(DB::ReplicatedMergeTreeLogEntry const&)+0x6ea) [0x718b9ba]
2019.01.29 13:19:46.548039 [ 2 ] {} <Error> BaseDaemon: 18. /usr/bin/clickhouse-server(DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&)+0x28b) [0x719422b]
2019.01.29 13:19:46.548053 [ 2 ] {} <Error> BaseDaemon: 19. /usr/bin/clickhouse-server() [0x719490f]
2019.01.29 13:19:46.548073 [ 2 ] {} <Error> BaseDaemon: 20. /usr/bin/clickhouse-server(DB::ReplicatedMergeTreeQueue::processEntry(std::function<std::shared_ptr<zkutil::ZooKeeper> ()>, std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::function<bool (std::shared_ptr<D
B::ReplicatedMergeTreeLogEntry>&)>)+0x55) [0x72b9665]
2019.01.29 13:19:46.548094 [ 2 ] {} <Error> BaseDaemon: 21. /usr/bin/clickhouse-server(DB::StorageReplicatedMergeTree::queueTask()+0x1ef) [0x716b19f]
2019.01.29 13:19:46.548110 [ 2 ] {} <Error> BaseDaemon: 22. /usr/bin/clickhouse-server(DB::BackgroundProcessingPool::threadFunction()+0x43e) [0x71d54ee]
2019.01.29 13:19:46.548130 [ 2 ] {} <Error> BaseDaemon: 23. /usr/bin/clickhouse-server() [0xaa3e73f]
2019.01.29 13:19:46.548145 [ 2 ] {} <Error> BaseDaemon: 24. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7fc9fd0546ba]

**Comment by rpfennin** [comment]
Here's the output from the  server log:

2019.01.29 13:19:46.133460 [ 33594 ] {} <Trace> analytics.event_local (Replicated PartsService): Sending part 20190129_20190129_4478454_4478454_0
2019.01.29 13:19:46.135124 [ 14 ] {} <Debug> MergingSortedBlockInputStream: Merge sorted 2 blocks, 12608 rows in 0.01 sec., 1575966.31 rows/sec., 124.97 MB/sec.
2019.01.29 13:19:46.135169 [ 14 ] {} <Debug> validation..inner.lookup_engagement_local (MergerMutator): Merge sorted 12609 rows, containing 4 columns (4 merged, 0 gathered) in 0.01 sec., 1197594.44 rows/sec., 95.74 MB/sec.
2019.01.29 13:19:46.136281 [ 14 ] {} <Trace> validation..inner.lookup_engagement_local (Data): Renaming temporary part tmp_merge_all_3161680_3162123_310 to all_3161680_3162123_310.
2019.01.29 13:19:46.136390 [ 14 ] {} <Trace> validation..inner.lookup_engagement_local (MergerMutator): Merged 2 parts: from all_3161680_3162122_309 to all_3162123_3162123_0
2019.01.29 13:19:46.136876 [ 33594 ] {} <Information> InterserverIOHTTPHandler: Done processing query
2019.01.29 13:19:46.162965 [ 17 ] {} <Trace> analytics.event_local (Data): Renaming temporary part tmp_fetch_20190129_20190129_4478453_4478453_0 to 20190129_20190129_4478453_4478453_0.
2019.01.29 13:19:46.172241 [ 17 ] {} <Debug> analytics.event_local (StorageReplicatedMergeTree): Fetched part 20190129_20190129_4478453_4478453_0 from /clickhouse/tables/01/analytics.event_local/replicas/03
2019.01.29 13:19:46.256419 [ 105 ] {} <Trace> SystemLog (system.part_log): Flushing system log
2019.01.29 13:19:46.258624 [ 105 ] {} <Trace> system.part_log (Data): Renaming temporary part tmp_insert_201901_7554_7554_0 to 201901_7554_7554_0.
2019.01.29 13:19:46.259092 [ 6 ] {} <Debug> system.part_log (MergerMutator): Selected 2 parts from 201901_7291_7548_97 to 201901_7549_7549_0
2019.01.29 13:19:46.259135 [ 6 ] {} <Debug> system.part_log (MergerMutator): Merging 2 parts: from 201901_7291_7548_97 to 201901_7549_7549_0 into tmp_merge_201901_7291_7549_98
2019.01.29 13:19:46.259436 [ 6 ] {} <Debug> system.part_log (MergerMutator): Selected MergeAlgorithm: Horizontal
2019.01.29 13:19:46.259494 [ 6 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 57 marks from part 201901_7291_7548_97, totaly 57896 rows starting from the beginning of the part
2019.01.29 13:19:46.259984 [ 6 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 1 marks from part 201901_7549_7549_0, totaly 194 rows starting from the beginning of the part
2019.01.29 13:19:46.304711 [ 6 ] {} <Debug> system.part_log (MergerMutator): Merge sorted 58090 rows, containing 16 columns (16 merged, 0 gathered) in 0.05 sec., 1275113.16 rows/sec., 245.23 MB/sec.
2019.01.29 13:19:46.307422 [ 6 ] {} <Trace> system.part_log (Data): Renaming temporary part tmp_merge_201901_7291_7549_98 to 201901_7291_7549_98.
2019.01.29 13:19:46.307582 [ 6 ] {} <Trace> system.part_log (MergerMutator): Merged 2 parts: from 201901_7291_7548_97 to 201901_7549_7549_0
2019.01.29 13:19:46.400712 [ 112 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: POST, Address: 192.168.100.110:19088, User-Agent: python-requests/2.17.3, Content Type: , Transfer Encoding: chunked
2019.01.29 13:19:46.400842 [ 112 ] {} <Trace> HTTPHandler: Request URI: /?max_execution_time=600&database=analytics&max_result_rows=10000000&user=ok250_app&password=***************&max_result_bytes=1000000000
2019.01.29 13:19:46.405221 [ 112 ] {3483ba2a-d015-479f-b0ed-6000bd1dd6dd} <Debug> executeQuery: (from 192.168.100.110:19088, user: ok250_app) insert into `messagelog` FORMAT TabSeparated
2019.01.29 13:19:46.408888 [ 112 ] {3483ba2a-d015-479f-b0ed-6000bd1dd6dd} <Debug> MemoryTracker: Peak memory usage (total): 2.29 MiB.
2019.01.29 13:19:46.408969 [ 112 ] {3483ba2a-d015-479f-b0ed-6000bd1dd6dd} <Debug> MemoryTracker: Peak memory usage (for query): 4.31 MiB.
2019.01.29 13:19:46.409026 [ 112 ] {} <Information> HTTPHandler: Done processing query
2019.01.29 13:19:46.411341 [ 43 ] {} <Debug> analytics.event_local (ReplicatedMergeTreeQueue): Pulling 1 entries to queue: log-0046451437 - log-0046451437
2019.01.29 13:19:46.413870 [ 43 ] {} <Debug> analytics.event_local (ReplicatedMergeTreeQueue): Pulled 1 entries to queue.
2019.01.29 13:19:46.414063 [ 9 ] {} <Trace> analytics.event_local (StorageReplicatedMergeTree): Executing log entry to merge parts 20190129_20190129_4477818_4478415_211, 20190129_20190129_4478416_4478449_7 to 20190129_20190129_44778
18_4478449_212
2019.01.29 13:19:46.414147 [ 9 ] {} <Debug> analytics.event_local (MergerMutator): Merging 2 parts: from 20190129_20190129_4477818_4478415_211 to 20190129_20190129_4478416_4478449_7 into tmp_merge_20190129_20190129_4477818_4478449_2
12
2019.01.29 13:19:46.415317 [ 9 ] {} <Debug> analytics.event_local (MergerMutator): Selected MergeAlgorithm: Horizontal
2019.01.29 13:19:46.415488 [ 9 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 3 marks from part 20190129_20190129_4477818_4478415_211, totaly 18309 rows starting from the beginning of the part
2019.01.29 13:19:46.417320 [ 9 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 1 marks from part 20190129_20190129_4478416_4478449_7, totaly 982 rows starting from the beginning of the part
2019.01.29 13:19:46.432464 [ 2 ] {} <Error> BaseDaemon: ########################################
2019.01.29 13:19:46.432571 [ 2 ] {} <Error> BaseDaemon: (from thread 9) Received signal Segmentation fault (11).
2019.01.29 13:19:46.432596 [ 2 ] {} <Error> BaseDaemon: Address: NULL pointer.
2019.01.29 13:19:46.432615 [ 2 ] {} <Error> BaseDaemon: Access: read.
2019.01.29 13:19:46.432633 [ 2 ] {} <Error> BaseDaemon: Unknown si_code.

**Comment by rpfennin** [comment]
Here's the relevant table schema:

CREATE TABLE analytics.event_local
(
    user_id UInt32,
    created DateTime,
    eventday Date,
    eventhour DateTime,
    eventminute DateTime,
    campaign_id Nullable(String),
    message_id Nullable(String),
    ip String,
    fromaddress Nullable(String),
    toaddress String,
    todomain Nullable(String),
    provider String,
    source Nullable(String),
    integrationkey String,
    activity String,
    seconds Nullable(UInt8),
    readcategory Nullable(Enum8('glancedorunread' = 1, 'skimmed' = 2, 'read' = 3)),
    url Nullable(String),
    isp_id UInt32,
    connection_type Nullable(Enum8('dialup' = 1, 'isdn' = 2, 'cable' = 3, 'dsl' = 4, 'fttx' = 5, 'wireless' = 6)),
    useragent String,
    platform_id UInt8,
    device_id UInt16,
    client_id UInt16,
    country String,
    region String,
    city String,
    lat Nullable(Float32),
    lon Nullable(Float32),
    timezone_id UInt16,
    timeofday Enum8('unknown' = 0, 'morning' = 1, 'afternoon' = 2, 'evening' = 3, 'night' = 4),
    properties Nested(key String, value String),
    partition Nullable(Int8),
    offset Nullable(Int64)
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/analytics.event_local', '{replica}', eventday, sipHash64(toaddress), (user_id, eventday, eventhour, eventminute, sipHash64(toaddress), integrationkey, activity, provider, useragent, ip), 8192)

CREATE TABLE analytics.event AS analytics.event_local ENGINE = Distributed(analytics_cluster, analytics, event_local, rand());

**Comment by mkarmona** [comment]
same here. I got a core dump too, not sure same problem though; breaking even from a simple query as this on my side
```sql
select 
  rs_id, 
  position, 
  ref_allele, 
  alt_allele,  
  most_severe_consequence, 
  raw, 
  phred 
from ot.variants 
prewhere chr_id = '1' and segment = 10
where ref_allele = 'C' 
limit 10
```
It works just once and when I repeat it again it breaks. Here the mergetree table
```sql
create table if not exists ot.variants
engine MergeTree partition by (chr_id, segment) order by (variant_id)
as select
  assumeNotNull(chr_id) as chr_id,
  assumeNotNull(position) as position,
  assumeNotNull(segment) as segment,
  assumeNotNull(ref_allele) as ref_allele,
  assumeNotNull(alt_allele) as alt_allele,
  assumeNotNull(variant_id) as variant_id,
  assumeNotNull(rs_id) as rs_id,
  gene_id,
  gene_id_prot_coding,
  most_severe_consequence,
  raw,
  phred,
  gnomad_afr,
  gnomad_seu,
  gnomad_amr,
  gnomad_asj,
  gnomad_eas,
  gnomad_fin,
  gnomad_nfe,
  gnomad_nfe_est,
  gnomad_nfe_seu,
  gnomad_nfe_nwe,
  gnomad_nfe_onf,
  gnomad_oth
from ot.variants_log;
```
coming from this log table
```sql
create table if not exists ot.variants_log (
  chr_id String,
  position UInt32,
  segment UInt32 MATERIALIZED (intDiv(position,1000000)),
  ref_allele String,
  alt_allele String,
  variant_id String MATERIALIZED (concat(chr_id,'_',toString(position),'_',ref_allele,'_',alt_allele)),
  rs_id String,
  gene_id_prot_coding String,
  gene_id String,
  most_severe_consequence String,
  raw Float64,
  phred Float64,
  gnomad_afr Float64,
  gnomad_seu Float64,
  gnomad_amr Float64,
  gnomad_asj Float64,
  gnomad_eas Float64,
  gnomad_fin Float64,
  gnomad_nfe Float64,
  gnomad_nfe_est Float64,
  gnomad_nfe_seu Float64,
  gnomad_nfe_nwe Float64,
  gnomad_nfe_onf Float64,
  gnomad_oth Float64
  )
engine = Log;
```
and the output of the `err.log` was at that time
```
2019.01.30 23:24:01.918199 [ 2 ] {} <Error> BaseDaemon: (from thread 32) Received signal Segmentation fault (11).                                     
2019.01.30 23:24:01.918211 [ 2 ] {} <Error> BaseDaemon: Address: NULL pointer.                                                                        
2019.01.30 23:24:01.918218 [ 2 ] {} <Error> BaseDaemon: Access: read.                                                                                 
2019.01.30 23:24:01.918225 [ 2 ] {} <Error> BaseDaemon: Address not mapped to object.                                                                 
2019.01.30 23:24:02.005437 [ 2 ] {} <Error> BaseDaemon: 0. /usr/bin/clickhouse-server(DB::CachedCompressedReadBuffer::nextImpl()+0xa8f) [0x76aab9f]   
2019.01.30 23:24:02.005514 [ 2 ] {} <Error> BaseDaemon: 1. /usr/bin/clickhouse-server(DB::CachedCompressedReadBuffer::seek(unsigned long, unsigned lon
g)+0x6f) [0x76a9dff]                                                                                                                                  
2019.01.30 23:24:02.005530 [ 2 ] {} <Error> BaseDaemon: 2. /usr/bin/clickhouse-server(DB::MergeTreeReader::Stream::seekToMark(unsigned long)+0x69) [0x
75b4719]                                                                                                                                              
2019.01.30 23:24:02.005537 [ 2 ] {} <Error> BaseDaemon: 3. /usr/bin/clickhouse-server() [0x75b4d0f]                                                   
2019.01.30 23:24:02.005562 [ 2 ] {} <Error> BaseDaemon: 4. /usr/bin/clickhouse-server(DB::IDataType::deserializeBinaryBulkWithMultipleStreams(DB::IColumn&, unsigned long, DB::IDataType::DeserializeBinaryBulkSettings&, std::shared_ptr<DB::IDataType::DeserializeBinaryBulkState>&) const+0x28) [0x3482ad8]
2019.01.30 23:24:02.005576 [ 2 ] {} <Error> BaseDaemon: 5. /usr/bin/clickhouse-server(DB::MergeTreeReader::readData(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::IDataType const&, DB::IColumn&, unsigned long, bool, unsigned long, bool)+0x2b2) [0x75b0512]
2019.01.30 23:24:02.005585 [ 2 ] {} <Error> BaseDaemon: 6. /usr/bin/clickhouse-server(DB::MergeTreeReader::readRows(unsigned long, bool, unsigned long, DB::Block&)+0x387) [0x75b0ce7]
2019.01.30 23:24:02.005593 [ 2 ] {} <Error> BaseDaemon: 7. /usr/bin/clickhouse-server(DB::MergeTreeRangeReader::DelayedStream::finalize(DB::Block&)+0x136) [0x75abdd6]
2019.01.30 23:24:02.005603 [ 2 ] {} <Error> BaseDaemon: 8. /usr/bin/clickhouse-server(DB::MergeTreeRangeReader::startReadingChain(unsigned long, std::vector<DB::MarkRange, std::allocator<DB::MarkRange> >&)+0x46c) [0x75ac89c]
2019.01.30 23:24:02.005612 [ 2 ] {} <Error> BaseDaemon: 9. /usr/bin/clickhouse-server(DB::MergeTreeRangeReader::read(unsigned long, std::vector<DB::MarkRange, std::allocator<DB::MarkRange> >&)+0x10f) [0x75addbf]
2019.01.30 23:24:02.005625 [ 2 ] {} <Error> BaseDaemon: 10. /usr/bin/clickhouse-server(DB::MergeTreeRangeReader::read(unsigned long, std::vector<DB::MarkRange, std::allocator<DB::MarkRange> >&)+0x696) [0x75ae346]
2019.01.30 23:24:02.005633 [ 2 ] {} <Error> BaseDaemon: 11. /usr/bin/clickhouse-server(DB::MergeTreeBaseSelectBlockInputStream::readFromPart()+0x7e8)
[0x75a6858]
2019.01.30 23:24:02.005641 [ 2 ] {} <Error> BaseDaemon: 12. /usr/bin/clickhouse-server(DB::MergeTreeBaseSelectBlockInputStream::readImpl()+0xbd) [0x75a7afd]
2019.01.30 23:24:02.005658 [ 2 ] {} <Error> BaseDaemon: 13. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x262) [0x6e21b62]     
2019.01.30 23:24:02.005666 [ 2 ] {} <Error> BaseDaemon: 14. /usr/bin/clickhouse-server(DB::FilterBlockInputStream::readImpl()+0xbd) [0x73ae89d]      
2019.01.30 23:24:02.005673 [ 2 ] {} <Error> BaseDaemon: 15. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x262) [0x6e21b62]     
2019.01.30 23:24:02.005680 [ 2 ] {} <Error> BaseDaemon: 16. /usr/bin/clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x2e) [0x73adb6e]  
2019.01.30 23:24:02.005687 [ 2 ] {} <Error> BaseDaemon: 17. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x262) [0x6e21b62]     
2019.01.30 23:24:02.005694 [ 2 ] {} <Error> BaseDaemon: 18. /usr/bin/clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x2e) [0x73adb6e]  
2019.01.30 23:24:02.005701 [ 2 ] {} <Error> BaseDaemon: 19. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x262) [0x6e21b62]     
2019.01.30 23:24:02.005708 [ 2 ] {} <Error> BaseDaemon: 20. /usr/bin/clickhouse-server(DB::LimitBlockInputStream::readImpl()+0x225) [0x6e271a5]      
2019.01.30 23:24:02.005715 [ 2 ] {} <Error> BaseDaemon: 21. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x262) [0x6e21b62]     
2019.01.30 23:24:02.005722 [ 2 ] {} <Error> BaseDaemon: 22. /usr/bin/clickhouse-server(DB::AsynchronousBlockInputStream::calculate()+0x56) [0x6e19376]
2019.01.30 23:24:02.005729 [ 2 ] {} <Error> BaseDaemon: 23. /usr/bin/clickhouse-server() [0x6e197e0]                                                 
2019.01.30 23:24:02.005736 [ 2 ] {} <Error> BaseDaemon: 24. /usr/bin/clickhouse-server(ThreadPool::worker()+0x19e) [0xa53af5e]                       
2019.01.30 23:24:02.005743 [ 2 ] {} <Error> BaseDaemon: 25. /usr/bin/clickhouse-server() [0xaa3e73f]                                                 
2019.01.30 23:24:02.005754 [ 2 ] {} <Error> BaseDaemon: 26. /lib/x86_64-linux-gnu/libpthread.so.0(+0x7494) [0x7f34a72f2494]                          
```
and this is my test configuration for my dev env
```
<?xml version="1.0"?>
<yandex>
    <logger>
        <level>debug</level>
        <log>/var/log/clickhouse-server/clickhouse-server.log</log>
        <errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
        <size>1000M</size>
        <count>7</count>
    </logger>
    <display_name>ots</display_name>
    <http_port>8123</http_port>
    <tcp_port>9000</tcp_port>
    <interserver_http_port>9009</interserver_http_port>
    <listen_host>::</listen_host>
    <listen_host>0.0.0.0</listen_host>
    <listen_try>0</listen_try>
    <listen_reuse_port>1</listen_reuse_port>
    <listen_backlog>256</listen_backlog>
    <max_connections>2048</max_connections>
    <keep_alive_timeout>5</keep_alive_timeout>
    <max_concurrent_queries>256</max_concurrent_queries>
    <max_open_files>262144</max_open_files>
    <uncompressed_cache_size>17179869184</uncompressed_cache_size>
    <mark_cache_size>17179869184</mark_cache_size>
    <!-- Path to data directory, with trailing slash. -->
    <path>/var/lib/clickhouse/</path>
    <tmp_path>/var/lib/clickhouse/tmp/</tmp_path>
    <user_files_path>/var/lib/clickhouse/user_files/</user_files_path>
    <users_config>users.xml</users_config>
    <default_profile>default</default_profile>
    <!-- <system_profile>default</system_profile> -->
    <default_database>default</default_database>
    <umask>022</umask>
    <zookeeper incl="zookeeper-servers" optional="true" />
    <macros incl="macros" optional="true" />
    <dictionaries_config>*_dictionary.xml</dictionaries_config>
    <builtin_dictionaries_reload_interval>3600</builtin_dictionaries_reload_interval>
    <max_session_timeout>3600</max_session_timeout>
    <default_session_timeout>60</default_session_timeout>
    <distributed_ddl>
        <path>/clickhouse/task_queue/ddl</path>
    </distributed_ddl>
    <format_schema_path>/var/lib/clickhouse/format_schemas/</format_schema_path>
</yandex>
```

**Comment by filimonov** [comment]
@mkarmona, it's another, please see: https://github.com/yandex/ClickHouse/issues/4175

**Comment by alesapin** [comment]
@mkarmona Your issue is same with https://github.com/yandex/ClickHouse/issues/4175 and it will be fixed in next release. 

But @rpfennin problem is something different. He get null pointer while loading marks to marks cache.

**Comment by mkarmona** [comment]
@alesapin thanks for your explanation. That's what I understood from @rpfennin but not sure if you wanted me to move my issue description to the other one. I will do it just to not mess up with the bug described here on this issue.
