### ISSUE TITLE
[Question] Too many parts exception with replication_queue table log

### ISSUE THREAD

**Issue by igor-sh8** [yandex/ClickHouse#4199]
Hello. 
I faced with already known error on a few my tables: 
`Too many parts (302). Merges are processing significantly slower than inserts.`
Based on one of the answers @alexey-milovidov (https://github.com/yandex/ClickHouse/issues/2811)
I checked `system.replication_queue` table. And I see two types of errors there:
`postpone_reason: Not executing log entry for part 20190116_20190130_3_536764_20612 because source parts size (10.36 MiB) is greater than the current maximum (4.45 MiB).`
and
`postpone_reason: Not merging into part 20190130_20190130_652661_654726_398 because part 20190130_20190130_654726_654726_0 is not ready yet (log entry for that part is being processed).`
None of the resources on the server are loaded even by 20 percent. All the tables are ReplicatedSummingMergeTree. Zookeeper cluster is on separate servers. 

What mean such exceptions ? Maybe it is possible to fix them with some clickhouse configs?
Thanks.

**Comment by den-crane** [comment]
Probably you've chosen a wrong partitioning key (partitions are too small so inserted block has been divided into many small pieces). 
Please show table DDL.

**Comment by igor-sh8** [comment]
Show create table statement:
CREATE TABLE db1.table1 ( Col0 Int32,  Col1 String,  Col2 Date,  Col3 Int16,  Col4 Int16,  Col5 Int16,  Col6 Int64,  Col7 Int64,  Col8 Int64,  Col9 Int64,  Col10 Int64) ENGINE = ReplicatedSummingMergeTree('/clickhouse/tables/{shard}/table1', '{replica}', Col2, (Col2, Col3, Col4, Col5, Col1, Col0), 8192, (Col6, Col7, Col8, Col9, Col10))

**Comment by igor-sh8** [comment]
The problem is solved by creating buffer tables.

**Comment by xmariachi** [comment]
Hi @igor-sh8 , could you please give more detail on how you solved it using tables? Also - did you have to do anything special / did you find any limitation by using `Replicated*` tables?

**Comment by igor-sh8** [comment]
Hi, @xmariachi.
The main problem in Too many parts error - is a lot of inserts and as a result a lot of merges. 
So I came to the next schema: client inserts -> buffer table -> materializedview to table -> table. 
In case I have a small cluster (4 servers) I decided to set failover schema on client side and not use replicated tables.
