### ISSUE TITLE
Insert the same data repeatedly for several times, the num by count is wrong 

### ISSUE THREAD

**Issue by moxiaofan9** [yandex/ClickHouse#4203]
### Version: 18.14.13
Engine: ReplicatedMergeTree

When insert the same data repeatedly for several times, the num by count is wrong.
For example, insert  `1000` data, the num is `1000` by count on clickhouse-client.
Repeatdly one time, the num is `2000` by count on clickhouse-client.
But, repeatly agin, the num is `not 3000` by count on clickhouse-client.

This situation is  easy to reproduce.

If I choose another engine `Memory`,  there is nothing wrong with this.
Or I change other datasource, there is nothing wrong with this too.

**Comment by den-crane** [comment]
clickhouse-client --insert_deduplicate 0

https://clickhouse.yandex/docs/en/operations/table_engines/replication/

Data blocks are deduplicated. For multiple writes of the same data block (data blocks of the same size containing the same rows in the same order), the block is only written once. The reason for this is in case of network failures when the client application doesn't know if the data was written to the DB, so the INSERT query can simply be repeated. It doesn't matter which replica INSERTs were sent to with identical data. INSERTs are idempotent. Deduplication parameters are controlled by merge_tree server settings.

**Comment by VitalyNeganov** [comment]
@den-crane Can somebody explain deduplication mechanism in more details?
Does it mean that Clickhouse provide "at most once" semantics on write in ReplicatedMergeTree?

Scenario:
1. Client sends batch of 100 rows for insert.
2. Batch Insert fails on server due to unexpected error, but 50 rows were inserted successfully.
3. Client sends same batch again.

Will Clickhouse contain 150 rows or 100 rows?

Thanks in advance!

**Comment by den-crane** [comment]
100 rows if:
1. it is the same shard.
2. it is the exactly the same insert batch (100 rows, the same order) (batch produces the same hashsum).
3. less than 100 insert happened after fail
4. less than week while after fail
5. original insert covered one partition

6...21  and so on. I am tired to type
