### ISSUE TITLE
arrayCount work only for UInt8 arrays

### ISSUE THREAD

**Issue by rekby** [yandex/ClickHouse#425]
select arrayCount(emptyArrayInt8())
fails with error:
Code: 43, e.displayText() = DB::Exception: The only argument for function arrayCount must be array of UInt8. Found Array(Int8) instead., e.what() = DB::Exception

But workaround is worked:
select arrayCount(x->1,emptyArrayInt8())

**Comment by ztlpn** [comment]
UInt8 acts as a substitute for a boolean type in this function.  Could you describe in more detail the particular use case for which you need arrayCount without lambda to work with non-UInt8 arrays?
