### ISSUE TITLE
[Question] different sorting keys on a replicated table

### ISSUE THREAD

**Issue by opavader** [yandex/ClickHouse#4253]
Can the `ORDER BY` columns be in different order on two different replicas ?

say I want to have sorting key for a replicated table on server 1 as :

`ORDER BY (CounterID, EventDate)` 

while on server 2 as 
`ORDER BY (EventDate, CounterID)`

rest of the schema is same.

**Comment by nvartolomei** [comment]
You can create a materialized view with a different sorting/primary key if that is required.

**Comment by alexey-milovidov** [comment]
It is possible if you use independent MergeTree tables and Distributed table just looks at them as replicas. For data replication, you can INSERT into Distributed table (cluster should has `internal_replication` set to false) or INSERT data to both replicas directly. Data consistency between replicas will not be maintained.
