### ISSUE TITLE
RPM on rhel7 not correctly specified....

### ISSUE THREAD

**Issue by mcarbonneaux** [yandex/ClickHouse#4265]
I've try to install package from `https://repo.yandex.ru/clickhouse/rpm/stable/x86_64/`

then when launch package install they throw an conflict error with rhel7 base package...

```
# yum install clickhouse-server
Loaded plugins: langpacks, product-id, search-disabled-repos
Resolving Dependencies
--> Running transaction check
---> Package clickhouse-server.noarch 0:19.1.6-2 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===========================================================================================================================================================================================
 Package                                           Arch                                   Version                                     Repository                                      Size
===========================================================================================================================================================================================
Installing:
 clickhouse-server                                 noarch                                 19.1.6-2                                    sfr-clickhouse                                  31 k

Transaction Summary
===========================================================================================================================================================================================
Install  1 Package

Total size: 31 k
Installed size: 51 k
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test


Transaction check error:
  file / from install of clickhouse-server-19.1.6-2.noarch conflicts with file from package filesystem-3.2-20.el7.x86_64
  file /lib from install of clickhouse-server-19.1.6-2.noarch conflicts with file from package filesystem-3.2-20.el7.x86_64
  file /usr/bin from install of clickhouse-server-19.1.6-2.noarch conflicts with file from package filesystem-3.2-20.el7.x86_64
  file /etc/init.d from install of clickhouse-server-19.1.6-2.noarch conflicts with file from package chkconfig-1.3.61-5.el7.x86_64

Error Summary
-------------
```

i think the spec `%file` part include some file/dir that should not be included in `%file` part... like `/`, `/lib`, `/usr/bin`, `/etc/init.d`....

When you package a rpm with file inside directory that are part of other package, you must not add this directory in `%file`  section of your package, juste add sub file and directory.

**Comment by filimonov** [comment]
I don't recommend using rpms https://repo.yandex.ru/  (as i understand it's just repacked deb packages with some automatic converting tool). 

For now it's better to use that repo https://packagecloud.io/Altinity/clickhouse 
Or build rpm by your own with scripts from https://github.com/Altinity/clickhouse-rpm/

**Comment by mcarbonneaux** [comment]
> I don't recommend using rpms from https://repo.yandex.ru/ for now (as i understand it's just repacked deb packages with some automatic converting tool).

they don't install for now... without correcting the packaing process they are useless...

i've successfully installed the altinity version.

why not integrate the rpm packaging from altinity to your master and generated rpm in https://repo.yandex.ru/ with it ?

**Comment by filimonov** [comment]
> they don't install for now... without correcting the packaging process they are useless...

Yes, that is the reason why they are not listed / supported officially.
 
> but why not integrate the rpm packaging from altinity to your master and generated rpm in https://repo.yandex.ru/ with it ?

Currently it's a lot of copy&paste inside activity scripts. See https://github.com/yandex/ClickHouse/pull/3702 

Generally somebody just need to take care of that, and do it in a proper way, to make the common parts for debian & redhat baseed distros reuse the same scripts, and incorporate specs in proper way in ClickHouse repo.

**Comment by mcarbonneaux** [comment]
I found it beceause is listed in documentation... Before the altinity repo....

https://clickhouse.yandex/docs/en/getting_started/


```
Packages from https://repo.yandex.ru/clickhouse/rpm/stable/x86_64/ are generated from official deb packages by Yandex and have byte-identical binaries.
```

But you have standalone binary in tar format but you don't speak of it in documentation.

The only problem are that list some systeme directory in the generated spec. 

How you build this rpm from Debian package?

**Comment by mcarbonneaux** [comment]
https://www.tecmint.com/convert-from-rpm-to-deb-and-deb-to-rpm-package-using-alien/

This link explain the problem.

**Comment by mcarbonneaux** [comment]
You can use rpmrebuild for filtering files of genereted rpm.

**Comment by filimonov** [comment]
Ro repacking also there are
https://github.com/jordansissel/fpm
https://github.com/goreleaser/nfpm

**Comment by alexey-milovidov** [comment]
We have added better `rpm` packages but they still have some minor issues:
https://github.com/yandex/ClickHouse/issues/5815
