### ISSUE TITLE
Exception when running more concurrent queries than max_concurrent_queries

### ISSUE THREAD

**Issue by dsr301** [yandex/ClickHouse#4283]
When we run more queries than the configured parameter "max_concurrent_queries" clickhouse throws an exception. 
Is there a configuration to queue up the queries instead of throwing an exception.

**Comment by dsr301** [comment]
Thanks for the quick reply.
Is there any recommendation if we want to have the queries waiting instead of timeout. Will ch_proxy help?
What is the default value for `queue_max_wait_ms`, I don't see it mentioned in users.xml

**Comment by alexey-milovidov** [comment]
> Is there any recommendation if we want to have the queries waiting instead of timeout.

I don't recomment to have a queue of waiting queries at all.
If the system cannot keep up with load, a queue will not help much.

> What is the default value for `queue_max_wait_ms`

Five seconds.
```
:) SELECT * FROM system.settings WHERE name = 'queue_max_wait_ms'

SELECT *
FROM system.settings 
WHERE name = 'queue_max_wait_ms'

┌─name──────────────┬─value─┬─changed─┬─description───────────────────────────────────────────────────────────────────────────────────┐
│ queue_max_wait_ms │ 5000  │       0 │ The wait time in the request queue, if the number of concurrent requests exceeds the maximum. │
└───────────────────┴───────┴─────────┴───────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by Fanduzi** [comment]
> There is `queue_max_wait_ms` setting.
> It is user level setting, that can be set up per user profile in `users.xml` configuration file.
> When the max wait time is exceeded, ClickHouse will throw an exception nevertheless.

Is this parameter described in the documentation?, I found that many parameters of clickhouse need to be found in the issue
