### ISSUE TITLE
[PATCH] Adding support for POSIX AIO compliant OS

### ISSUE THREAD

**Issue by urgordeadbeef** [yandex/ClickHouse#4302]
Now Clickhouse use weird AIO solution - supporting only linux AIO. 
This patch implement Linux AIO wrapper for POSIX AIO compliant systems.
I believe, much better rework AIO code to using POSIX AIO.

P.S. FreeBSD tested only.

[patch-freebsd_aio_support.txt](https://github.com/yandex/ClickHouse/files/2841116/patch-freebsd_aio_support.txt)

**Comment by alexey-milovidov** [comment]
Thank you!
Merged.
