### ISSUE TITLE
Deadlock with concurrent SELECT / DROP TABLE

### ISSUE THREAD

**Issue by bgranvea** [yandex/ClickHouse#4316]
I get a random deadlock when performing concurrently a SELECT and a DROP TABLE on the same view. I've tested with Clickhouse 18.14.19 and 19.1.6.

To reproduce the problem, just launch these 2 scripts in different shells:

`for i in {1..1000}; do echo $i; echo "drop table if exists test_view" | clickhouse-client; echo "create view test_view as select count(*),database,table from system.columns group by database,table" | clickhouse-client; done
`

`for i in {1..1000}; do echo $i; echo "select * from test_view order by table" | clickhouse-client >/dev/null; done
`

I can see in system.processes my 2 queries which are still running:

```
select elapsed,query from system.processes limit 2 format Vertical

Row 1:
──────
elapsed: 502.919283347
query:   select * from test_view order by table

Row 2:
──────
elapsed: 502.918433233
query:   drop table if exists test_view

```

**Comment by alexey-milovidov** [comment]
There is fundamental issue with current implementation of table locks.
Nevertheless, we are going to fix it.
