### ISSUE TITLE
Why mergeTree index could not use nullable column?

### ISSUE THREAD

**Issue by edonin** [yandex/ClickHouse#4332]
Hi,

Currently, when you try to add a nullable column inside a mergetree sorting index, you have an error:
`Sorting key cannot contain nullable columns`

Nevertheless, if you modify the code for allowing them, everything sems to be working. 
So, is there still a technical reason to do allow them?

The only issue I found seems to be the case of Nullable String with collation, but I am not sure that they could be used in a sorting index case.

**Comment by ztlpn** [comment]
For simplicity (comparison of NULLs requires special logic).

    Nevertheless, if you modify the code for allowing them, everything sems to be working.

Not really:
```
:) create table t (x Nullable(UInt32)) engine MergeTree order by x

CREATE TABLE t
(
    x Nullable(UInt32)
)
ENGINE = MergeTree
ORDER BY x

Ok.
0 rows in set. Elapsed: 0.002 sec.

:) insert into t values (NULL)

INSERT INTO t VALUES

Ok.

1 rows in set. Elapsed: 0.001 sec.

:) select count() from t where x < 1

SELECT count()
FROM t
WHERE x < 1

Received exception from server (version 18.14.18):
Code: 169. DB::Exception: Received from localhost:9001, ::1. DB::Exception: Cannot compare unsigned long with DB::Null.

0 rows in set. Elapsed: 0.002 sec.
```

**Comment by edonin** [comment]
Ok,

In may case, 95% of the columns are nullable, and this limit is very restrictive.

Currently, null comparaisons seems to be well managed in the ordering of the select statement, by not in the KeyCondition of the merge tree. I will take a look.

Thanks
