### ISSUE TITLE
When reading data from kafka

### ISSUE THREAD

**Issue by adilets** [yandex/ClickHouse#4356]
When i send data to kafka 1 message per 1 sec it works, but when i send messages more often i get this error for some messages 

 <Error> void DB::StorageKafka::streamThread(): Code: 32, e.displayText() = DB::Exception: Attempt to read after eof, e.what() = DB::Exception, Stack trace:

0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x9fde646]
1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x22) [0x3317a42]
2. /usr/bin/clickhouse-server(DB::throwReadAfterEOF()+0x4d) [0x3317d5d]
3. /usr/bin/clickhouse-server(DB::DataTypeNumberBase<unsigned char>::deserializeText(DB::IColumn&, DB::ReadBuffer&, DB::FormatSettings const&) const+0x127) [0x6eb7af7]
4. /usr/bin/clickhouse-server(DB::TabSeparatedRowInputStream::read(std::vector<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::RowReadExtension&)+0xfe) [0x732ff0e]
5. /usr/bin/clickhouse-server(DB::BlockInputStreamFromRowInputStream::readImpl()+0x15c) [0x75b838c]
6. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x262) [0x6e21b62]
7. /usr/bin/clickhouse-server(DB::KafkaBlockInputStream::readImpl()+0x4f) [0x71d043f]
8. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x262) [0x6e21b62]
9. /usr/bin/clickhouse-server(DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::atomic<bool>*)+0x81) [0x6e3e661]
10. /usr/bin/clickhouse-server(DB::StorageKafka::streamToViews()+0x5ed) [0x71cd69d]
11. /usr/bin/clickhouse-server(DB::StorageKafka::streamThread()+0x1a8) [0x71cdd18]
12. /usr/bin/clickhouse-server(DB::BackgroundSchedulePool::TaskInfo::execute()+0xef) [0x736baef]
13. /usr/bin/clickhouse-server(DB::BackgroundSchedulePool::threadFunction()+0xba) [0x736c8ba]
14. /usr/bin/clickhouse-server() [0xaa3e73f]
15. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7fdcc78726ba]
16. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7fdcc6e9341d]

**Comment by abyss7** [comment]
- What is your CH version? Some frames indicate that the version is quite old.
- Do you send multiple rows inside one message or one row per message?
- Have you set the `kafka_row_delimiter` setting for Kafka table?

**Comment by abyss7** [comment]
Closing for now.
