### ISSUE TITLE
Can I cancel delete or update operation with mutation_id?

### ISSUE THREAD

**Issue by sdlcwangsong** [yandex/ClickHouse#4357]
there are many mutations which is_done is 0 in system.mutations table, and those mutations was created at 2019.1, Can I cancel those mutations? how?

**Comment by sdlcwangsong** [comment]
Can I delete it directly from zookeeper?

**Comment by blinkov** [comment]
This feature has been added few days ago in #4287 and will be available in next release, stay tuned.

**Comment by sdlcwangsong** [comment]
> This feature has been added few days ago in #4287 and will be available in next release, stay tuned.

thank you, but those mutations has exist long time ago, and when I create new distributed table, I got error: "Code: 269, e.displayText() = DB::Exception: Distributed table aaaa looks at itself, e.what() = DB::Exception"

Can I delete it directly from zookeeper?

**Comment by ztlpn** [comment]
@sdlcwangsong Yes you can, it is safe.
