### ISSUE TITLE
Default database doesn't substituted on insert into distributed table

### ISSUE THREAD

**Issue by xoddarrin** [yandex/ClickHouse#437]
Greetings,

I am trying to build a distributed cluster with replication according to the instruction provided earlier: https://groups.google.com/d/msg/clickhouse/GFl04GsTNZg/UvIfdGjuBQAJ

I am using <default_database> tag as described, please see the cluster config:

```
<remote_servers>
    <logs_cluster>
        <shard>
            <internal_replication>true</internal_replication>
            <replica>
                <host>host1</host>
                <default_database>replica_1</default_database>
            </replica>
            <replica>
                <host>host3</host>
                <default_database>replica_2</default_database>
            </replica>
        </shard>
        <shard>
            <internal_replication>true</internal_replication>
            <replica>
                <host>host2</host>
                <default_database>replica_1</default_database>
            </replica>
            <replica>
                <host>host1</host>
                <default_database>replica_2</default_database>
            </replica>
        </shard>
        <shard>
            <internal_replication>true</internal_replication>
            <replica>
                <host>host3</host>
                <default_database>replica_1</default_database>
            </replica>
            <replica>
                <host>host2</host>
                <default_database>replica_2</default_database>
            </replica>
        </shard>
    </logs_cluster>
</remote_servers>
```

The distributed table definition is:

`ENGINE = Distributed(logs_cluster, '', logs)`

SELECT queries work fine, but INSERTs into the Distributed table fail: no data on shards and I see the following errors in the log:

`[ 35 ] <Error> distributed_logs.Distributed.DirectoryMonitor: Code: 60, e.displayText() = DB::Exception: Received from *:9000. DB::Exception: Table default.logs doesn't exist..`

It looks like <default_database> value is respected by SELECT code only, but just taken directly from the engine for INSERTs (and empty string is replaced by 'default').

I am using ClickHouse 1.1.54134.

Looking forward for your help.

**Comment by ztlpn** [comment]
Confirmed, it is a bug.
