### ISSUE TITLE
Possible doku bug in DataTypes

### ISSUE THREAD

**Issue by shinguz** [yandex/ClickHouse#44]
https://clickhouse.yandex/reference_en.html#Data%20types
FixedString(N)

When reading a string that contains more bytes, an error message is returned.
When writing a string, null bytes are not trimmed off of the end of the string, but are output. 

I assume this should be:

When writing a string that contains more bytes, an error message is returned.
When reading a string, null bytes are not trimmed off of the end of the string, but are output.

Regards,
Oli

**Comment by alexey-milovidov** [comment]
Example 1:

```
SELECT toFixedString('Hello', 10) AS s

┌─s───────────────┐
│ Hello\0\0\0\0\0 │
└─────────────────┘
```

As you see, to convert string `Hello` to FixedString(10), server pads string with zero bytes,
and when server writes (output) result to client, it writes all that zero bytes.

Example 2:

```
SELECT toFixedString('Hello', 3) AS s

Received exception from server:
Code: 131. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: String too long for type FixedString(3).
```

When server tries to read (parse) value of type FixedString(3) from string `Hello`, the exception is thrown.

Example 3:

```
:) CREATE TABLE test.fixed_string (s FixedString(10)) ENGINE = Memory

CREATE TABLE test.fixed_string
(
    s FixedString(10)
) ENGINE = Memory

Ok.

0 rows in set. Elapsed: 0.012 sec. 

:) INSERT INTO test.fixed_string VALUES ('Hello')

INSERT INTO test.fixed_string VALUES

Ok.

1 rows in set. Elapsed: 0.010 sec. 

:) SELECT * FROM test.fixed_string

SELECT *
FROM test.fixed_string

┌─s───────────────┐
│ Hello\0\0\0\0\0 │
└─────────────────┘

1 rows in set. Elapsed: 0.001 sec. 

:) INSERT INTO test.fixed_string VALUES ('Hello, world')

INSERT INTO test.fixed_string VALUES


Exception on client:
Code: 131. DB::Exception: Too large value for FixedString(10): (at row 1)

Connecting to localhost:9000.
Connected to ClickHouse server version 1.1.53981.
```

In this example, when we INSERT data to a table, client or server **reads** data from Values format.
And when we do SELECT, server **writes** data to client and client writes it to terminal.

**Comment by shinguz** [comment]
Hello Alexey

Thank you for the detailed explanation. I think I understand the problem know.

You are developer and have a developer view: READ from client and WRITE to client.

I am a user and have a user view: READ = SELECT, WRITE = INSERT. Which is exactly the opposite.

The same thing from different view points. So far so good I understood.

But now for whom should the documentation be written for? Or at least it should be written more explicitly from what point of view this read/write is seen. IMHO

Regards,
Oli

**Comment by alexey-milovidov** [comment]
Documentation is for end user, of course.
I agree, the documentation should be written more explicitly.

3ca3d31b98db5de1f2c3e4dc86f9524e4b0986a0

(there is also minor inaccuracy, because, when using command-line client, the data is parsed/formatted by client, not server)

**Comment by shinguz** [comment]
Hi Alexey

Thanks for this interesting architectural hint! I was wondering already why other solutions do not lay off the expensive parsing phase to the clients...

Regards,
Oli
