### ISSUE TITLE
Unexpected behavior with 'Division by zero' for Decimal attributes' calculation with conditional logic.

### ISSUE THREAD

**Issue by kkrakovych** [yandex/ClickHouse#4411]
**Description**
When conditional logic operates with Decimal values exception 'Division by zero' takes place when it should not.

**How to reproduce**
* ClickHouse 18.14.18 with revision 54409
* Both via clickhouse-client on server locally and via JDBC driver from a IDEA.
* Non-default settings: NULL values are enabled.
* Create table statements
```
create table test_table
(
  id          int,
  val_int     Nullable(int),
  val_decimal Nullable(Decimal(38, 12))
) engine MergeTree()
    partition by id
    order by id;
```
* Sample data for all these tables:
```
insert into test_table (id, val_int, val_decimal) values (1, null, null);
insert into test_table (id, val_int, val_decimal) values (2, 10, 10);
```

* Queries to run that lead to unexpected result with 'Division by zero' exception.
If we run these queries against table with *Decimal* attributes - 'Division by zero' exception takes place.
```
select id
     , case when val_decimal is null then null else 100 / val_decimal end as calc
  from test_table;

select id
     , if(val_decimal is not null, 100 / val_decimal, null) as calc
  from test_table;

select id
     , multiIf(val_decimal is null, null, 100 / val_decimal) as calc
  from test_table;
```

**Expected behavior**
If we run _the same_ queries against columns with *int* attributes - everything works as expected.
```
select id
     , case when val_int is null then null else 100 / val_int end as calc_1
     , if(val_int is not null, 100 / val_int, null)               as calc_2
     , multiIf(val_int is null, null, 100 / val_int)              as calc_3
  from test_table;
```

**Error message and/or stacktrace**
Via clickhouse-client on server locally.
```
Received exception from server (version 18.14.18):
Code: 153. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Division by zero.
```
Via JDBC driver
```
Code: 153, e.displayText() = DB::Exception: Division by zero, e.what() = DB::Exception
```

**Comment by filimonov** [comment]
Please check that: https://github.com/yandex/ClickHouse/issues/1562

**Comment by kkrakovych** [comment]
Hi @filimonov ,

Thank you for the link. Here is a workaround for Decimal values:
```
select val_decimal
     , case when val_decimal is null then 1 else val_decimal end as weird_value
     , multiIf(val_decimal is null, null, 100 / weird_value) as result
  from test_table;
```

**Comment by filimonov** [comment]
Let's continue tracking that issue in #1562

**Comment by billsbooth** [comment]
Seems like this issue is solved for basic cases, but it breaks when you have two `first_value(...)` calls inside the conditional:

```
WITH 
  nums AS (SELECT toDecimal128(number, 18) as number FROM numbers(10))
  
SELECT if(first_value(number) > 0, divideDecimal(first_value(number), first_value(number)), 0) FROM nums;
```

https://fiddle.clickhouse.com/ebc5805e-7e91-4322-8db9-9246e3361a00
