### ISSUE TITLE
Some functions 'bleed' into following rows

### ISSUE THREAD

**Issue by tobia** [yandex/ClickHouse#442]
Example:

    CREATE TABLE test (
        name FixedString(3)
    ) ENGINE = TinyLog;

    INSERT INTO test VALUES ('foo'), ('bar'), ('zzz');

    SELECT 
        name, 
        reinterpretAsUInt64(name), 
        reinterpretAsUInt64('foo')
    FROM test 
    WHERE name = 'foo';

    ┌─name─┬─reinterpretAsUInt64(name)─┬─reinterpretAsUInt64(\'foo\')─┐
    │ foo  │       7017296931985518438 │                      7303014 │
    └──────┴───────────────────────────┴──────────────────────────────┘

The middle value looks wrong. What is really inside it?

    SELECT reinterpretAsString(reinterpretAsUInt64(name))
    FROM test 
    WHERE name = 'foo'

    ┌─reinterpretAsString(reinterpretAsUInt64(name))─┐
    │ foobarzz                                       │
    └────────────────────────────────────────────────┘

Oh boy! Is this expected behaviour?

I'm using client and server 1.1.54140.

**Comment by ztlpn** [comment]
Confirmed.
