### ISSUE TITLE
Is Clickhouse support UTC timezone like UTC+8 ,UTC-2?

### ISSUE THREAD

**Issue by gclinux** [yandex/ClickHouse#4421]
Is Clickhouse support UTC timezone like UTC+8 ,UTC-2?
---------------
formatDateTime(event_time,'%Y-%m-%d','PRC')as date  //ok
formatDateTime(event_time,'%Y-%m-%d','UTC+8')as date //wrong

I will usually select data from different timezone, it is not convenient to use timezone encode.

**Comment by filimonov** [comment]
1) Most probably it's not the best idea, as those in that case you need to care of daylight saving and historical changes manually
2) But if you really need it and understand all possible complications, tzdata allows you to reference those absolute offsets like that:
```select toDateTime(now(), 'Etc/GMT+8');```
