### ISSUE TITLE
String to array (split string to individual chars)

### ISSUE THREAD

**Issue by filimonov** [yandex/ClickHouse#4433]
Sometimes you need to easily make an array from string characters (Especially in some synthetic tests creation), or to split a binary string to individual bytes. 

**Describe the solution you'd like**
New function:
`splitToChars(s)` or `toCharArray(s)` (or similar)

OR
`splitByString(separator, s)` accepts an empty string as a first parameter to split string to indiviual charactes / bytes.  

**Describe alternatives you've considered**
That works but it's too much typing, and uneffecient:
```
WITH 'abcd' AS str
SELECT arrayMap(i -> substring(str, i + 1, 1), range(length(str)))
```

**Comment by ztlpn** [comment]
`extractAll` should be reasonably efficient:
```
WITH 'abcd' AS str
SELECT extractAll(str, '.')

┌─extractAll(str, '.')─┐
│ ['a','b','c','d']    │
└──────────────────────┘
```

**Comment by filimonov** [comment]
Yep. that workaround is good enough. Thanks.

**Comment by filimonov** [comment]
#9742 implements the feature
