### ISSUE TITLE
[PATCH] Fixup for "AIOcontextPool: Found io_event with unknown id 0'' error

### ISSUE THREAD

**Issue by urgordeadbeef** [yandex/ClickHouse#4434]
For multiple AIO requests in a queue always raise error "AIOcontextPool: Found io_event with unknown id 0". This is a FreeBSD specific issue.

Error always reproduce when set non zero min_merge_bytes_to_use_direct_io and starting to merge multiple pieces for any MergeTree tables.

Attached patch solve this issue.
[patch-aio-requiest_id-fixup.txt](https://github.com/yandex/ClickHouse/files/2875234/patch-aio-requiest_id-fixup.txt)

**Comment by proller** [comment]
https://github.com/yandex/ClickHouse/pull/4438
