### ISSUE TITLE
Cannot load time zone Etc/GMT5

### ISSUE THREAD

**Issue by Slind14** [yandex/ClickHouse#4443]
Hi,

I'm unable to use any timezone values which contain a `+` or `-` (it is removing those). The timezone is available under `/usr/share/zoneinfo/Etc`.

`DB::Exception: Exception: Cannot load time zone Etc/GMT5.`

**Comment by filimonov** [comment]
What do you mean by 'unable to use'?  (Relates #4421)

```
SELECT toDateTime(now(), 'Etc/GMT+5')

┌─toDateTime(now(), 'Etc/GMT+5')─┐
│            2019-02-19 07:19:14 │
└────────────────────────────────┘

1 rows in set. Elapsed: 0.026 sec. 

SELECT toDateTime(now(), 'Etc/GMT-5')

┌─toDateTime(now(), 'Etc/GMT-5')─┐
│            2019-02-19 17:19:17 │
└────────────────────────────────┘
```

**Comment by Slind14** [comment]
ahh, sorry my mistake. The query had multiple "toDate" and I forgot one of them.
