### ISSUE TITLE
bug Address not mapped to object.

### ISSUE THREAD

**Issue by foolfish3** [yandex/ClickHouse#4450]
version 19.3.3
Linux 4.14.62-70.117.amzn2.x86_64

always down with this message 

2019.02.20 03:06:28.703276 [ 65 ] {} <Error> BaseDaemon: ########################################
2019.02.20 03:06:28.703345 [ 65 ] {} <Error> BaseDaemon: (from thread 39) Received signal Segmentation fault (11).
2019.02.20 03:06:28.703357 [ 65 ] {} <Error> BaseDaemon: Address: 0x7f487c180000
2019.02.20 03:06:28.703364 [ 65 ] {} <Error> BaseDaemon: Access: write.
2019.02.20 03:06:28.703371 [ 65 ] {} <Error> BaseDaemon: Address not mapped to object.
2019.02.20 03:06:28.749636 [ 65 ] {} <Error> BaseDaemon: 0. clickhouse-server() [0x4b1df41]
2019.02.20 03:06:28.749683 [ 65 ] {} <Error> BaseDaemon: 1. clickhouse-server(DB::DataTypeString::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const+0x2ad) [0x4b2119d]
2019.02.20 03:06:28.749702 [ 65 ] {} <Error> BaseDaemon: 2. clickhouse-server(DB::MergeTreeReader::readData(std::string const&, DB::IDataType const&, DB::IColumn&, unsigned long, bool, unsigned long, bool)+0x406) [0x51a85a6]
2019.02.20 03:06:28.749712 [ 65 ] {} <Error> BaseDaemon: 3. clickhouse-server(DB::MergeTreeReader::readRows(unsigned long, bool, unsigned long, DB::Block&)+0x2c1) [0x51a8cc1]
2019.02.20 03:06:28.749721 [ 65 ] {} <Error> BaseDaemon: 4. clickhouse-server() [0x51a39d3]
2019.02.20 03:06:28.749729 [ 65 ] {} <Error> BaseDaemon: 5. clickhouse-server(DB::MergeTreeRangeReader::DelayedStream::finalize(DB::Block&)+0x46) [0x51a4916]
2019.02.20 03:06:28.749751 [ 65 ] {} <Error> BaseDaemon: 6. clickhouse-server(DB::MergeTreeRangeReader::continueReadingChain(DB::MergeTreeRangeReader::ReadResult&)+0x123) [0x51a5c53]
2019.02.20 03:06:28.749762 [ 65 ] {} <Error> BaseDaemon: 7. clickhouse-server(DB::MergeTreeRangeReader::read(unsigned long, std::vector<DB::MarkRange, std::allocator<DB::MarkRange> >&)+0x7f6) [0x51a6736]
2019.02.20 03:06:28.749770 [ 65 ] {} <Error> BaseDaemon: 8. clickhouse-server(DB::MergeTreeBaseSelectBlockInputStream::readFromPart()+0x5f0) [0x519fb60]
2019.02.20 03:06:28.749778 [ 65 ] {} <Error> BaseDaemon: 9. clickhouse-server(DB::MergeTreeBaseSelectBlockInputStream::readImpl()+0xb2) [0x51a0fa2]
2019.02.20 03:06:28.749788 [ 65 ] {} <Error> BaseDaemon: 10. clickhouse-server(DB::IBlockInputStream::read()+0x1f5) [0x4a93c25]
2019.02.20 03:06:28.749798 [ 65 ] {} <Error> BaseDaemon: 11. clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x1a) [0x4fe3e4a]
2019.02.20 03:06:28.749806 [ 65 ] {} <Error> BaseDaemon: 12. clickhouse-server(DB::IBlockInputStream::read()+0x1f5) [0x4a93c25]
2019.02.20 03:06:28.749814 [ 65 ] {} <Error> BaseDaemon: 13. clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x1a) [0x4fe3e4a]
2019.02.20 03:06:28.749821 [ 65 ] {} <Error> BaseDaemon: 14. clickhouse-server(DB::IBlockInputStream::read()+0x1f5) [0x4a93c25]
2019.02.20 03:06:28.749829 [ 65 ] {} <Error> BaseDaemon: 15. clickhouse-server(DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>::loop(unsigned long)+0x101) [0x4bc0c41]
2019.02.20 03:06:28.749839 [ 65 ] {} <Error> BaseDaemon: 16. clickhouse-server(DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>::thread(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long)+0x1fb) [0x4bc119b]
2019.02.20 03:06:28.749866 [ 65 ] {} <Error> BaseDaemon: 17. clickhouse-server(ThreadFromGlobalPool::ThreadFromGlobalPool<DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>::process()::{lambda()#1}>(DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>::process()::{lambda()#1}&&)::{lambda()#1}::operator()() const+0x58) [0x4bc15f8]
2019.02.20 03:06:28.749877 [ 65 ] {} <Error> BaseDaemon: 18. clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x199) [0x5d9e1b9]
2019.02.20 03:06:28.749884 [ 65 ] {} <Error> BaseDaemon: 19. clickhouse-server() [0x65c272f]
2019.02.20 03:06:28.749892 [ 65 ] {} <Error> BaseDaemon: 20. /lib64/libpthread.so.0(+0x754b) [0x7f5334e8254b]

**Comment by filimonov** [comment]
Can you describe the circumstances?
Like a select / other actions happened just before the failure? You can also check it in clickhouse-server.log (if enabled)

**Comment by foolfish3** [comment]
many sql runs,so  not very sure which sql cause it, maybe (because below sql is runs heavy and long time)
CREATE TABLE files ( rank_date Date,  filename String,  filetime Int64,  content String) ENGINE = MergeTree PARTITION BY rank_date ORDER BY filetime SETTINGS index_granularity = 81920;

CREATE TABLE files_new ( rank_date Date CODEC(ZSTD(3)),  filename String CODEC(ZSTD(3)),  filetime Int64 CODEC(ZSTD(3)),  content String CODEC(ZSTD(3))) ENGINE = MergeTree PARTITION BY rank_date ORDER BY filetime SETTINGS index_granularity = 81920;

============================================
insert into files_new select * from files;
after about 2 hour ....  Address not mapped to object occur

run twice/die twice ,all about two hours after execute it
============================================
clickhouse-client -q "insert into files_new select * from files where rank_day='2019-01-01'"
clickhouse-client -q "insert into files_new select * from files where rank_day='2019-01-02'"
clickhouse-client -q "insert into files_new select * from files where rank_day='2019-01-03'"
clickhouse-client -q "insert into files_new select * from files where rank_day='2019-01-04'"
.......
day by day
run once/die once, also  about two hours after execute first sql

one day of files table size raw size 17G, lz4 compressed size 5G,about 18,000,000 rows
