### ISSUE TITLE
GROUP BY Enum attribute WITH ROLLUP 

### ISSUE THREAD

**Issue by levw** [yandex/ClickHouse#4455]
This question may become a bug, that's why I created issue.

Here is test table with three versions of  the same Enum attribute.

```
CREATE table tmp_test_rollup
(
  UserGroupZeroBased Enum8('new' = 0, 'certain' = 1, 'test' = 2),
  UserGroupOneBased  Enum8('new' = 1, 'certain' = 2, 'test' = 3),
  UserGroupWithAll   Enum8('all' = 0, 'new' = 1, 'certain' = 2, 'test' = 3),
  Period             UInt64,
  Metric             Int64
)
  engine = TinyLog;

INSERT INTO tmp_test_rollup (UserGroupZeroBased, UserGroupOneBased, UserGroupWithAll, Period, Metric)
VALUES ('new', 'new', 'new', 1, 1000),
       ('new', 'new', 'new', 2, 2000),
       ('certain', 'certain', 'certain', 1, 500),
       ('certain', 'certain', 'certain', 1, 100);
```
If I want group by UserGroup with rollup, I can do three versions of query.

1. In results of this query I'll get value `new` in rows where I expect get empty value. 
```
SELECT Period, UserGroupZeroBased, sum(Metric)
FROM tmp_test_rollup
GROUP BY ROLLUP (Period, UserGroupZeroBased);
``` 

2. In results of this query I'll get exception `Unexpected value 0 for type Enum8('new' = 1, 'certain' = 2, 'test' = 3)`
```
SELECT Period, UserGroupOneBased, sum(Metric)
FROM tmp_test_rollup
GROUP BY ROLLUP (Period, UserGroupOneBased);
```
3. In this query I'll get the expected correct result, but through special expression of `UserGroupWithAll` which was written for this case.
```
SELECT Period, UserGroupWithAll, sum(Metric)
FROM tmp_test_rollup
GROUP BY ROLLUP (Period, UserGroupWithAll);
```

Results in the first and second case correspond to expected results?
Solution of this problem by extension of Enum list (as in the third example) is supposed?

CH  version: 19.1.6

**Comment by filimonov** [comment]
As by defaults types clickhouse use NOT NULLs, it need to represent somehow the default/empty/nonexisting values with some value which can be stored in that NOT NULL type. So for all numerical types (and also Enum) types the default value is 0. When doing group by with rollup - default value for a column in rollup rows is used. So i would say that this behaviour is expected. 

Best practice here: just always to add 'empty' value to your not null Enums at 0 position. Like that: 
```  UserGroupWithEmpty   Enum8('' = 0, 'new' = 1, 'certain' = 2, 'test' = 3),```

If you will use Nullable types NULL will be used as a default value, and you will not face taht issue, try like that:
```  UserGroupWithNull   Nullable(Enum8('new' = 1, 'certain' = 2, 'test' = 3)),```
(But remember that Nullable type have some performance/storage overhead)

**Comment by levw** [comment]
Thanks for answer!
