### ISSUE TITLE
 create a database using Http interface

### ISSUE THREAD

**Issue by samz406** [yandex/ClickHouse#4490]
i want to use http interface create database.can it be?

**Comment by den-crane** [comment]
Yes just use POST to enable write mode

echo 'create database testxxx' | curl 'http://localhost:8123/?' --data-binary @-

https://clickhouse.yandex/docs/en/operations/settings/permissions_for_queries/#settings_readonly
When using the GET method in the HTTP interface, readonly = 1 is set automatically. To modify data, use the POST method.
