### ISSUE TITLE
FR: Add Postgres table engine

### ISSUE THREAD

**Issue by simPod** [yandex/ClickHouse#4492]
Today I noticed this MySQL table engine https://clickhouse.yandex/docs/en/operations/table_engines/mysql/

I was wondering as I use Postgres that it might be nice to have the same engine for it. Currently I sync some data from Postgres to ClickHouse using custom scripts so I can access data from my Postgres database.

Postgres is gaining more and more popularity recently (eg. see https://db-engines.com/en/ranking) and seems it has the best features set compared to other standard relational databases (see https://www.slideshare.net/MarkusWinand/standard-sql-features-where-postgresql-beats-its-competitors) it's IMO safe to suppose the Postgres popularity will keep growing.

I noticed this issue https://github.com/yandex/ClickHouse/issues/1291 mentioning https://github.com/Infinidat/infi.clickhouse_fdw/ but 1) seems that it's not very fast 2) it doesn't support for example DateTime

**Comment by den-crane** [comment]
But there is ODBC table engine

https://www.altinity.com/blog/2018/9/20/using-odbc-with-clickhouse

**Comment by simPod** [comment]
That looks like solution. Thanks!

Why is there MySQL engine btw? Doesn't ODBC engine replace it?

**Comment by den-crane** [comment]
Backward compatibility I guess and probably better performance because mysqlib is statically compiled to CH binary and ODBC works through several layers CH -> CH-ODBC-Bridge -> ODBC -> DB LIB

**Comment by simPod** [comment]
Kk, thanks for answers!
