### ISSUE TITLE
Unknown table engine Kafka

### ISSUE THREAD

**Issue by DaemonMonch** [yandex/ClickHouse#4498]
hi i,ve  installed clickhouse 19.3.5 ,  but when i create table with kafka engine, it reports exception about 
Received exception from server (version 19.3.5):
Code: 56. DB::Exception: Received from localhost:9002, ::1. DB::Exception: Unknown table engine Kafka.

could anyone help me?  thx

**Comment by abyss7** [comment]
Can you provide the `CREATE TABLE` query, please?

**Comment by alexey-milovidov** [comment]
Your version of ClickHouse was built without support for Kafka. This may happen if you are using  unofficial packages or built ClickHouse by yourself.

**Comment by DaemonMonch** [comment]
> Your version of ClickHouse was built without support for Kafka. This may happen if you are using unofficial packages or built ClickHouse by yourself.

ok ! got it  thanks

**Comment by Vxider** [comment]
> Your version of ClickHouse was built without support for Kafka. This may happen if you are using unofficial packages or built ClickHouse by yourself.

I'm build from source with tag `v19.8.3.8-stable` and encountered the same problem. How can I  build a version that supports kafka?

**Comment by filimonov** [comment]
You can use official build (ubuntu/docker), or look for librdkafka in cmake output, maybe some adjustment can be required for your platform. Please check: https://github.com/yandex/ClickHouse/blob/master/cmake/find_rdkafka.cmake
