### ISSUE TITLE
build fail for v19.3.5-stable on ubuntu13.10

### ISSUE THREAD

**Issue by kindred77** [yandex/ClickHouse#4507]
**Operating system**
ubuntu13.10(EGLIBC 2.17-93ubuntu4)

**Cmake version**
cmake3.6.3

**Ninja version**
1.5.1

**Compiler name and version**
gcc7.1.0

**Full cmake and/or ninja output**
[2675/3596] Building CXX object dbms/C...CollapsingSortedBlockInputStream.cpp.o
FAILED: /usr/local/bin/g++   -DBOOST_SYSTEM_NO_DEPRECATED -DPOCO_STATIC -DPOCO_UNBUNDLED_ZLIB -DUNALIGNED_OK -DWITH_GZFILEOP -DX86_64 -DZLIB_COMPAT -isystem ../contrib/jemalloc-cmake/include -isystem ../contrib/jemalloc-cmake/include_linux_x86_64 -isystem ../contrib/protobuf/src -isystem ../contrib/libsparsehash -isystem ../contrib/libdivide -isystem ../contrib/poco/Data/include -isystem /usr/include/x86_64-linux-gnu -I../dbms/src -Idbms/src -isystem ../contrib/double-conversion -isystem ../contrib/re2 -isystem ../contrib/pdqsort -isystem ../contrib/libpcg-random/include -I../libs/libcommon/include -Ilibs/libcommon/include -isystem ../contrib/poco/Foundation/include -I../contrib/zlib-ng -Icontrib/zlib-ng -I../contrib/cityhash102/include -isystem ../contrib/boost -isystem ../contrib/poco/Net/include -isystem ../contrib/poco/Util/include -isystem ../contrib/poco/XML/include -isystem ../contrib/poco/JSON/include -isystem contrib/re2_st -I../libs/libpocoext/include -I../libs/libmysqlxx/include -I../contrib/mariadb-connector-c-cmake/linux_x86_64/include -I../contrib/mariadb-connector-c-cmake/common/include -I../contrib/mariadb-connector-c/include -isystem ../contrib/ssl/include -I../contrib/libbtrie/include -isystem ../contrib/poco/Data/ODBC/include -I../contrib/unixodbc-cmake/linux_x86_64 -I../contrib/unixodbc/include -I../contrib/unixodbc/libltdl -I../contrib/unixodbc/libltdl/libltdl -isystem ../contrib/poco/MongoDB/include -isystem ../contrib/poco/NetSSL_OpenSSL/include -isystem ../contrib/poco/Crypto/include -fdiagnostics-color=always -std=c++1z  -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall  -Wnon-virtual-dtor -no-pie -Wextra -Werror -O2 -g -DNDEBUG -O3    -fno-tree-loop-distribute-patterns -pthread -MD -MT dbms/CMakeFiles/dbms.dir/src/DataStreams/VersionedCollapsingSortedBlockInputStream.cpp.o -MF dbms/CMakeFiles/dbms.dir/src/DataStreams/VersionedCollapsingSortedBlockInputStream.cpp.o.d -o dbms/CMakeFiles/dbms.dir/src/DataStreams/VersionedCollapsingSortedBlockInputStream.cpp.o -c ../dbms/src/DataStreams/VersionedCollapsingSortedBlockInputStream.cpp
In file included from ../dbms/src/DataStreams/VersionedCollapsingSortedBlockInputStream.cpp:2:0:
../dbms/src/DataStreams/VersionedCollapsingSortedBlockInputStream.h: In instantiation of ‘void DB::FixedSizeDequeWithGaps<T>::destructValue(size_t) [with T = DB::MergingSortedBlockInputStream::RowRef; size_t = long unsigned int]’:
../dbms/src/DataStreams/VersionedCollapsingSortedBlockInputStream.h:56:30:   required from ‘DB::FixedSizeDequeWithGaps<T>::~FixedSizeDequeWithGaps()::<lambda(size_t, size_t)> [with T = DB::MergingSortedBlockInputStream::RowRef; size_t = long unsigned int]’
../dbms/src/DataStreams/VersionedCollapsingSortedBlockInputStream.h:53:32:   required from ‘struct DB::FixedSizeDequeWithGaps<T>::~FixedSizeDequeWithGaps() [with T = DB::MergingSortedBlockInputStream::RowRef]::<lambda(size_t, size_t)>’
../dbms/src/DataStreams/VersionedCollapsingSortedBlockInputStream.h:53:14:   required from ‘DB::FixedSizeDequeWithGaps<T>::~FixedSizeDequeWithGaps() [with T = DB::MergingSortedBlockInputStream::RowRef]’
../dbms/src/DataStreams/VersionedCollapsingSortedBlockInputStream.cpp:22:41:   required from here
../dbms/src/DataStreams/VersionedCollapsingSortedBlockInputStream.h:132:40: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
     void destructValue(size_t index) { reinterpret_cast<T *>(container[index].value)->~T(); }
                                        ^~~~~~~~~~~~~~~~
../dbms/src/DataStreams/VersionedCollapsingSortedBlockInputStream.h: In instantiation of ‘const T& DB::FixedSizeDequeWithGaps<T>::getValue(size_t) const [with T = DB::MergingSortedBlockInputStream::RowRef; size_t = long unsigned int]’:
../dbms/src/DataStreams/VersionedCollapsingSortedBlockInputStream.h:109:24:   required from ‘const T& DB::FixedSizeDequeWithGaps<T>::back() const [with T = DB::MergingSortedBlockInputStream::RowRef]’
../dbms/src/DataStreams/VersionedCollapsingSortedBlockInputStream.cpp:129:35:   required from here
../dbms/src/DataStreams/VersionedCollapsingSortedBlockInputStream.h:135:53: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
     const T & getValue(size_t index) const { return *reinterpret_cast<const T *>(container[index].value); }
                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../dbms/src/DataStreams/VersionedCollapsingSortedBlockInputStream.h: In instantiation of ‘T& DB::FixedSizeDequeWithGaps<T>::getValue(size_t) [with T = DB::MergingSortedBlockInputStream::RowRef; size_t = long unsigned int]’:
../dbms/src/DataStreams/VersionedCollapsingSortedBlockInputStream.h:97:24:   required from ‘T& DB::FixedSizeDequeWithGaps<T>::front() [with T = DB::MergingSortedBlockInputStream::RowRef]’
../dbms/src/DataStreams/VersionedCollapsingSortedBlockInputStream.cpp:150:51:   required from here
../dbms/src/DataStreams/VersionedCollapsingSortedBlockInputStream.h:134:41: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
     T & getValue(size_t index) { return *reinterpret_cast<T *>(container[index].value); }

**Comment by 4ertus2** [comment]
You may try to make it with 'cmake -DNO_WERROR=1'

**Comment by kindred77** [comment]
it works, thanks
