### ISSUE TITLE
[Question] Too many parts error Monitoring

### ISSUE THREAD

**Issue by igor-sh8** [yandex/ClickHouse#4512]
Hello. 
According to our last experience with the `Too many parts` errors we would like to start monitor this metric.
How I can do this ?
For example I think about such kind of query:
`select count(*) from system.merges`
or maybe
`select count(*) from system.merges` + `select count(*) from system.replication_queue`
?
Or maybe there is some already built-in metric ?

**Comment by den-crane** [comment]
select value from system.asynchronous_metrics where metric = 'MaxPartCountForPartition'

select value from system.metrics where metric = 'ReadonlyReplica'

**Comment by igor-sh8** [comment]
Great. Thanks. 
We will try it.
