### ISSUE TITLE
query_log misbehave when query return 0 rows

### ISSUE THREAD

**Issue by jangorecki** [yandex/ClickHouse#4518]
Query log does not log queries that returns 0 rows

```sh
clickhouse-client --query="CREATE TABLE IF NOT EXISTS G1 (id1 Int32, id2 Int32) ENGINE = Memory()"
clickhouse-client --query="TRUNCATE TABLE G1;"
echo -e 'id1,id2\n1,2\n1,4\n2,6\n2,8' | clickhouse-client --query="INSERT INTO G1 FORMAT CSVWithNames"
clickhouse-client --query="TRUNCATE TABLE system.query_log;"
echo -e "SELECT id1, sum(id2) AS id2 FROM G1 WHERE 1=0 GROUP BY id1;\n\nSELECT count(*) AS cnt_where_false FROM system.query_log;\n\nSELECT id1, sum(id2) AS id2 FROM G1 WHERE 1=1 GROUP BY id1;\n\nSELECT count(*) AS cnt_where_true FROM system.query_log;" | clickhouse-client -mn --log_queries 1 --format=Pretty
#┏━━━━━━━━━━━━━━━━━┓
#┃ cnt_where_false ┃
#┡━━━━━━━━━━━━━━━━━┩
#│               0 │
#└─────────────────┘
#┏━━━━━┳━━━━━┓
#┃ id1 ┃ id2 ┃
#┡━━━━━╇━━━━━┩
#│   2 │  14 │
#├─────┼─────┤
#│   1 │   6 │
#└─────┴─────┘
#┏━━━━━━━━━━━━━━━━┓
#┃ cnt_where_true ┃
#┡━━━━━━━━━━━━━━━━┩
#│              1 │
#└────────────────┘
clickhouse-client --query="SELECT version();"
#19.3.5
```

**Comment by a-rodin** [comment]
@jangorecki You should flush logs with `SYSTEM FLUSH LOGS;` query to see the queries in the logs table immediately.

For you example if the last command is be changed to
```
echo -e "SELECT id1, sum(id2) AS id2 FROM G1 WHERE 1=0 GROUP BY id1;\n\nSYSTEM FLUSH LOGS;\n\nSELECT count(*) AS cnt_where_false FROM system.query_log;\n\nSELECT id1, sum(id2) AS id2 FROM G1 WHERE 1=1 GROUP BY id1;\n\nSYSTEM FLUSH LOGS;\n\nSELECT count(*) AS cnt_where_true FROM system.query_log;" | clickhouse-client -mn --log_queries 1 --format=Pretty
```

then the query is present in `system.query_log`:

```sql
select query from system.query_log limit 1;

SELECT query
FROM system.query_log 
LIMIT 1

┌─query──────────────────────────────────────────────────────┐
│ SELECT id1, sum(id2) AS id2 FROM G1 WHERE 1=0 GROUP BY id1 │
└────────────────────────────────────────────────────────────┘
```

**Comment by a-rodin** [comment]
You should flush logs with `SYSTEM FLUSH LOGS` query to see the queries in the logs table immediately.

For you example the last command in your example is changed to
```
echo -e "SELECT id1, sum(id2) AS id2 FROM G1 WHERE 1=0 GROUP BY id1;\n\nSYSTEM FLUSH LOGS;\n\nSELECT count(*) AS cnt_where_false FROM system.query_log;\n\nSELECT id1, sum(id2) AS id2 FROM G1 WHERE 1=1 GROUP BY id1;\n\nSYSTEM FLUSH LOGS;\n\nSELECT count(*) AS cnt_where_true FROM system.query_log;" | clickhouse-client -mn --log_queries 1 --format=Pretty
```

then the query without results is present in `system.query_log`:

```sql
select query from system.query_log limit 1;

SELECT query
FROM system.query_log 
LIMIT 1

┌─query──────────────────────────────────────────────────────┐
│ SELECT id1, sum(id2) AS id2 FROM G1 WHERE 1=0 GROUP BY id1 │
└────────────────────────────────────────────────────────────┘
```

**Comment by jangorecki** [comment]
@a-rodin Thanks, that resolves my problem. I would say it is not a bug then, but a lack of documentation.

**Comment by jangorecki** [comment]
It looks like there is a bug somewhere there. Simplified reproducible example below:
```sh
clickhouse-client --query="CREATE TABLE IF NOT EXISTS G1 (id1 Int32, id2 Int32) ENGINE = Memory()"
echo -e "SET log_queries = 1;\nSELECT id1, sum(id2) AS id2 FROM G1 GROUP BY id1;\nSET log_queries = 0;\nSYSTEM FLUSH LOGS;\nSELECT count(*) AS log_cnt FROM system.query_log;\n" > ch-log-queries.sql

sudo /usr/sbin/service clickhouse-server stop
sudo /usr/sbin/service clickhouse-server start

while sleep 0.5; do clickhouse-client --query="TRUNCATE TABLE system.query_log" && cat "ch-log-queries.sql" | clickhouse-client -mn --format=Pretty --output_format_pretty_max_rows 1; done
```
yields the following output
```
┏━━━━━━━━━┓
┃ log_cnt ┃
┡━━━━━━━━━┩
│       2 │
└─────────┘
  Showed first 1.

┏━━━━━━━━━┓
┃ log_cnt ┃
┡━━━━━━━━━┩
│       6 │
└─────────┘
  Showed first 1.
┏━━━━━━━━━┓
┃ log_cnt ┃
┡━━━━━━━━━┩
│       4 │
└─────────┘
  Showed first 1.
┏━━━━━━━━━┓
┃ log_cnt ┃
┡━━━━━━━━━┩
│       4 │
└─────────┘
  Showed first 1.

# all further executions returns 4 consistently
```
we can see that first two scripts executions returns unexpected value

```sh
clickhouse-client --query="SELECT version();"
#19.5.3.8
```

**Comment by nvartolomei** [comment]
There are 2 stages. Need to sleep a bit before calling flush logs.

Logs are inserted into a queue first. Then in background moved to another queue. Second queue is flushed periodically to the table or on flush logs.

**Comment by alexey-milovidov** [comment]
That's a race condition.
`SYSTEM FLUSH LOGS` should flush both queues to ensure that all previous queries are written to logs.

**Comment by jangorecki** [comment]
Thanks for explanations.
I agree with Alexey, `SYSTEM FLUSH LOGS` should flush all queues used to log queries. I will proceed my development assuming such behaviour. Hopefully it will be addressed sooner than later, so I can include clickhouse in https://h2oai.github.io/db-benchmark/

**Comment by BayoNet** [comment]
I have found the information about SYSTEM FLUSH LOGS in the system.query_log description https://clickhouse.yandex/docs/en/operations/system_tables/#system_tables-query-log.

**Comment by jangorecki** [comment]
@alexey-milovidov any idea if `SYSTEM FLUSH LOGS` now flushes both queues?
The issue has been closed not being referred by any commit/PR, just comment linking new documentation page. On that page I can only find:
> To flush the logs forcibly from the memory buffer into the table, use the SYSTEM FLUSH LOGS query.

Thus it is not clear if race condition bug reported here has been fixed?

**Comment by alexey-milovidov** [comment]
> any idea if SYSTEM FLUSH LOGS now flushes both queues

No, the issue was not fixed. The race condition still exist. This is to do.

**Comment by jangorecki** [comment]
Could we re-open this issue then?

**Comment by alexey-milovidov** [comment]
I've created another issue.
