### ISSUE TITLE
[Question] Materialized view partial reload

### ISSUE THREAD

**Issue by igor-sh8** [yandex/ClickHouse#4528]
Hi. 
I have such a scheme of work with Clickhouse:
I have one big table (where I insert the data) and a few Materialized Views based on this table. 
All was fine until recently I received an error  "Too many parts" from one of the Materialized Views. 
It turned out that the data appeared in the main big table. and in one Materialized View but did not appear in the other. So it turned out the discrepancy of the same data in the two Materialized Views.
Is it possible to reload for example only one day in Materialized View ? 
(The whole View size is more then 100 GB and included several month of data, so recreating the whole View is a too long operation.)
And also want to ask about Materialized View based on replicated table. 
I have a Replicated table on two servers and Materialized Views (non replicated merge engine) on each server. When I insert the data on one of the servers the data as expected replicate to another server but the data in the Materialized View appear only on the server where was the inset process but not appear in the Materialized View based on replica table. So is it possible to create such materialized view that can keep data from replica server (not active for inserts) ? Is it possible to do it without creating a Replicated Materialized View ?
Thanks.

**Comment by den-crane** [comment]
>So it turned out the discrepancy of the same data in the two Materialized Views.

it's expected. No atomicity with multiple mviews. 

>Is it possible to reload for example only one day in Materialized View ?
No. Only manual fix with / alter delete / drop partition / insert

>but the data in the Materialized View appear only on the server where was the inset process

MV is an on insert trigger. It works over inserting buffer. 
It does not select the table directly -- So it can be creates over Engine=Null table.
Just create MV with replicated engine and will get the same data at all replicas.

**Comment by igor-sh8** [comment]
Hi. 
Thanks for the explanation.

> MV is an on insert trigger. It works over inserting buffer.
So I also can not create MV behind another MV, or MV behind MV To Table ?

**Comment by den-crane** [comment]
>So I also can not create MV behind another MV, or MV behind MV To Table ?

No. No MV cascading. But you can attach several MVs to a table.

**Comment by igor-sh8** [comment]
Ok. Thanks for the explanation.
