### ISSUE TITLE
How could i extract the values of nested json object from kafka?

### ISSUE THREAD

**Issue by kindred77** [yandex/ClickHouse#4533]
I have json message in kafka:
{
    "trace_id":"",
    "time":"",
    "properties":{
        "device_id":"",
        "othercol":""
    }
}

I want to map the nested json object "properties" to the kafka table.

I have tried this:
CREATE TABLE event(
trace_id String,
time String,
properties Nested(
	`device_id` String,
	`$othercol` String
)
)
ENGINE = Kafka
setting ....

but it does not work:

select properties.device_id from event limit 1;

----properties.device_id-----
[]

please help. thks

**Comment by den-crane** [comment]
18.14.9 Nested data structures can be read as nested objects in JSONEachRow format. Added the input_format_import_nested_json setting.

```

echo "create table N(a String, KV Nested(K String, V String)) engine=MergeTree order by a;"|clickhouse-client

echo '{"a":"xxx", "KV" : { "K" : ["a", "b"], "V":["1","2"]} }'|clickhouse-client --input_format_import_nested_json=1 --input_format_skip_unknown_fields=1 -q 'insert into N format JSONEachRow'

echo "select * from N"|clickhouse-client
xxx	['a','b']	['1','2']
```

**Comment by kindred77** [comment]
It seams does not work.
I test it on 19.3.5.

select name,value,changed from system.settings where name='input_format_import_nested_json';
-----------------------------------name-------value------changed--------
input_format_import_nested_json                     1                 1


CREATE TABLE event_topic(
distinct_id String,
time UInt64,
type String,
properties Nested(
	latitude String,
	page_id String
)
)
ENGINE = Kafka
SETTINGS
kafka_broker_list = '***:9092,***:9092',
kafka_topic_list = 'event_topic',
kafka_group_name = 'group_test_2',
kafka_row_delimiter = '\n',
kafka_format = 'JSONEachRow',
kafka_num_consumers = 4;


CREATE TABLE event_topic_final(
distinct_id String,
time Date,
type String,
properties Nested(
	latitude String,
	page_id String
)
) ENGINE = MergeTree(time, (distinct_id,time), 8192);


CREATE MATERIALIZED VIEW consumer TO event_topic_final
AS SELECT distinct_id, toDate(time/1000) as time, type,properties.latitude,properties.page_id
from event_topic;

select count() from event_topic_final;
----count()------
240254976

select distinct_id,time,type from event_topic_final limit 1;
-----------------------------------distinct_id-------time------------type-----------
862c8aed-ef3d-4914-abd7-36daaf3230bc         2002-04-16     track

select distinct properties.latitude,properties.page_id from event_topic_final;
-----properties.latitude--------properties.page_id----
[]                                                 []

The message in kafka like this:
{
	"lib": {
		"$lib": "Android"
	},
	"distinct_id": "3178030173002175",
	"time": 1551337843102,
	"type": "track",
	"properties": {
		"latitude": "28.920899",
		"page_id": "010400000000"
	},
	"extractor": {
		"o": 141668912,
		"n": "access_log.2019022815",
		"s": 1228688488,
		"c": 1228688488,
	},
	"ver": 2
}

**Comment by kindred77** [comment]
no error in log:

2019.03.01 11:19:49.121865 [ 130 ] {} <Trace> StorageKafka (event_topic): Committing message with offset 752877126
2019.03.01 11:19:49.128301 [ 21 ] {} <Trace> StorageKafka (event_topic): Committing message with offset 724775060
2019.03.01 11:19:49.151314 [ 92 ] {} <Trace> StorageKafka (event_topic): Committing message with offset 725077884
2019.03.01 11:19:49.171871 [ 92 ] {} <Trace> StorageKafka (event_topic): Polled batch of 65536 messages
2019.03.01 11:19:49.179798 [ 125 ] {} <Trace> StorageKafka (event_topic): Committing message with offset 757366585
2019.03.01 11:19:49.200414 [ 21 ] {} <Trace> StorageKafka (event_topic): Polled batch of 65536 messages
2019.03.01 11:19:49.235037 [ 125 ] {} <Trace> StorageKafka (event_topic): Polled batch of 65536 messages
2019.03.01 11:19:49.297688 [ 92 ] {} <Trace> StorageKafka (event_topic): Committing message with offset 723293041
2019.03.01 11:19:49.305397 [ 130 ] {} <Trace> StorageKafka (event_topic): Polled batch of 65536 messages
2019.03.01 11:19:49.333444 [ 92 ] {} <Trace> StorageKafka (event_topic): Polled batch of 65536 messages

**Comment by den-crane** [comment]
"properties": {
"latitude": "28.920899",
"page_id": "010400000000"
},

oh, CH does not support such nested, it's not an array [].

**Comment by kindred77** [comment]
Is there another solution?

**Comment by ruslangm** [comment]
@kindred77 did you find another solution to this problem? The only option that I see at the moment is to decompose the entire json into a flat table. But it confuses me that nested structures should be just for such cases (IMHO)

**Comment by kindred77** [comment]
@ruslangm yes, and I find the nested structure is not for this situation, it is for nested table(array+tupple), I have changed the code to parse json nestly to solve this problem. 
thanks for comment.
