### ISSUE TITLE
Whats the max download limit in clickhouse ?

### ISSUE THREAD

**Issue by DivyaRao30** [yandex/ClickHouse#4537]
Hi,

I ran a query without limit clause and total records set was some 16.5 M rows and i can only see first 10k records.

is there any way to see the next set of rows? and whats the max download limit ?

Thanks

**Comment by den-crane** [comment]
To download data try to use non-human formats TSV / CSV / JSONEachRow
https://clickhouse.yandex/docs/en/interfaces/formats/
select * from numbers(10) format TSV

10000 -- controlled by output_format_pretty_max_rows
```
set output_format_pretty_max_rows = 3;
select * from numbers(10)
┌─number─┐
│      0 │
│      1 │
│      2 │
└────────┘
  Showed first 3.
```

```
set output_format_pretty_max_rows = 3;
select * from numbers(10) format TSV
0
1
2
3
4
5
6
7
8
9
```

**Comment by DivyaRao30** [comment]
Thanks i got it . 

Now i have a new query where in i want to download the large file directly from the console.

Is there any command or format to download the csv file into server directly from the console ?

Thanks,
Divya

**Comment by filimonov** [comment]
```bash
# insert from csv file
clickhouse-client --query='INSERT INTO table_name FORMAT CSV' < data.csv

# select and put results to csv file
clickhouse-client --query='SELECT * FROM table_name FORMAT CSV' > data.csv
```

**Comment by DivyaRao30** [comment]
Thanks a lot

**Comment by DivyaRao30** [comment]
Thanks
