### ISSUE TITLE
Should Select be optimized for MATERIALIZED VIEW?

### ISSUE THREAD

**Issue by simPod** [yandex/ClickHouse#4544]
When using materialized view as a trigger, that said used for inserting data to table A when data is inserted to table B:

```sql
CREATE MATERIALIZED VIEW IF NOT EXISTS tableBToTableA TO tableA
AS
SELECT
    some_fields
FROM tableB
GROUP BY some_fields
```

Is it also required to optimize the MV select so it uses partitioning key and sorting keys of `tableB`? Or it doesn't matter?

**Comment by den-crane** [comment]
Does not matter.
MV does not read real tableB (except at populate stage).
MV gets inserted buffer (from insert query) and evaluates select over this buffer.

**Comment by simPod** [comment]
Thanks for explanation!
