### ISSUE TITLE
Distributed->Buffer->MergeTree and PREWHERE

### ISSUE THREAD

**Issue by adubovikov** [yandex/ClickHouse#4546]
Hi here,

my question is about using PREWHERE condition in  the Buffer engine. Currently I have a cluster and have created a table that linked to a buffer table and the buffer table has been pointed to a normal MegeTable. The current situation, the Buffer engine doesn't allow to use PREWHERE condition and if you even have set optimize_move_to_prewhere =1, it will force to 0 and send this settings to another reads. This means in the current construct, I couldn't use PREWHERE condition in any ways. Is it possible to re-read settings, specialy for the "optimize_move_to_prewhere" , then the read go to the destination MergeTable ? Otherwise I have to create another distributed table "distributed_read", that should pointed directly to the MergeTable, but in this case it will bypass the "Buffer". 

Thanks a lot in advance

**Comment by adubovikov** [comment]
any feedback ? ;-)

**Comment by den-crane** [comment]
https://github.com/yandex/ClickHouse/pull/4671

**Comment by adubovikov** [comment]
thanks. Looks like it will fix it :-)
