### ISSUE TITLE
Don't we need to ”threads.erase(thread_it)” here?

### ISSUE THREAD

**Issue by nicelulu** [yandex/ClickHouse#4572]
https://github.com/yandex/ClickHouse/blob/master/dbms/src/Common/ThreadPool.cpp#L160

**Comment by alexey-milovidov** [comment]
No.

`new_job_or_shutdown.wait(lock, [this] { return shutdown || !jobs.empty(); });`
We wait for shutdown or when there are new jobs. No spurious wakeups possible.

It means, that if after wait we have `jobs.empty()`, it means that the ThreadPool is destroying (`shutdown` is true). And we can simply exit from thread.

This can be compared with the case when we need to just remove some threads from ThreadPool but continue to work.

**Comment by alexey-milovidov** [comment]
But we still have an issue in our implementation of `ThreadFromGlobalPool`.
We lock mutex in one thread (when constructing `ThreadFromGlobalPool` object) and unlock in another (when shared_ptr<std::mutex> is destroyed in the task).

According to the C++ standard:

```
The mutex must be locked by the current thread of execution, otherwise, the behavior is undefined. 
```
