### ISSUE TITLE
Implement DETACH PART

### ISSUE THREAD

**Issue by buremba** [yandex/ClickHouse#46]
It's possible to ATTACH PARTs manually but DETACH only works with partitions which makes moving data between nodes impossible. Currently, the only workaround is to delete the directory of PART and restart the node but it's not a reliable way since we don't keep track of merges which might include the PART we want to delete and the queries that are executed before restart will fail because of missing PART.

At least support for DETACH PART for non-replicated MergeTree tables would be a good starting point and would solve our issue since we handle replication externally.

Also see the discussion here: https://groups.google.com/forum/#!msg/clickhouse/ZABNyXsiIWI/fZyFk6IQBAAJ

**Comment by zhxiaogg** [comment]
+1 We need DETACH PARTs so we can purge data in a daily manner.

**Comment by blinkov** [comment]
If you need daily data purge, nowadays you should consider using custom partitioning:
https://clickhouse.yandex/docs/en/table_engines/custom_partitioning_key/
