### ISSUE TITLE
clickhouse calculate the average

### ISSUE THREAD

**Issue by brucejrc** [yandex/ClickHouse#4606]
I have two Field,one is timestamp,another is sum of network in bytes.just like this:

```
timestamp      network_in_bytes
1551196802144   1
1551196802145   5 
1551196802147   18 
1551196802158   80
```
I want to calculate(B>A)
```
avg_network_in_bytes=(network_in_bytes_B-network_in_bytes_A)/(timestamp_B-timestamp_A).
```
How do I get the avg_network_in_bytes?

**Comment by filimonov** [comment]
On versions after 19.1:
```SELECT boundingRatio(timestamp, network_in_bytes) FROM table```
(Not documented yet, check PR: https://github.com/yandex/ClickHouse/pull/3139 )

On previous versions:
```SELECT ( argMax(network_in_bytes, timestamp) - argMin(network_in_bytes, timestamp) ) / ( max(timsetamp) - min(timestamp)) FROM table```

**Comment by brucejrc** [comment]
@filimonov thanks,I try another way like this
```
SELECT (runningDifference(network_in_bytes))/(runningDifference(timestamp)) FROM
(
    SELECT network_in_bytes,timestamp FROM tables
    order by network_in_bytes,timestamp
)
```

**Comment by filimonov** [comment]
ah, you wanted pairwise rate no by 2 border points. So your solution is ok.
