### ISSUE TITLE
Не собирается если не находит readline

### ISSUE THREAD

**Issue by burunduk3** [yandex/ClickHouse#464]
Пытался собрать из f87ae6808fe08f15be64976b5334415183ed5981, не удалось скомпилировать dbms/src/Client/Client.cpp, line 254, не нашлась функция read_history.

Кажется, строчкой выше написали `#ifdef USE_READLINE`, а имели в виду `#if USE_READLINE`.

**Comment by proller** [comment]
https://github.com/yandex/ClickHouse/commit/045fd6f55db37059c97c0c276e8914b096e1f6bb
