### ISSUE TITLE
HTTPDictionarySource doesn't support HTTPS

### ISSUE THREAD

**Issue by vavrusa** [yandex/ClickHouse#465]
HTTP dictionary source [doesn't recognise](https://github.com/yandex/ClickHouse/blob/b8f1ea48058ed0f8c7dbf3a62d7994005e4d548c/dbms/src/Dictionaries/HTTPDictionarySource.cpp#L50) `https://` and is sending plaintext request, so pulling dictionary from HTTPS endpoint doesn't work.

It should probably check scheme and implement https://pocoproject.org/docs/Poco.Net.HTTPSClientSession.html

**Comment by proller** [comment]
https://github.com/yandex/ClickHouse/commit/57c336f267bbf049f9ffdf87e50fe5f2cded4882

for use with self-signed https servers use config option <https_client_insecure>1</https_client_insecure>

**Comment by vavrusa** [comment]
Awesome, thanks a lot! I'll close this and reopen if there's a problem.
