### ISSUE TITLE
Segmentation fault on JOIN ... USING nullable column (19.3.7)

### ISSUE THREAD

**Issue by vanzi** [yandex/ClickHouse#4681]
**Describe the bug**
NULL value in a column causes segmentation fault in a JOIN query. This happens when the column is Nullable in one of the tables.

We've encountered this issue in one of the earlier versions, but it still occurs in the current version (19.3.7).

**How to reproduce**

Start server

    docker run --rm --name clickhouse-srv --ulimit nofile=262144:262144 yandex/clickhouse-server:19.3.7

Start client

    docker run -it --rm --link clickhouse-srv:clickhouse-server yandex/clickhouse-client:19.3.7 --host clickhouse-server

Run in client

	CREATE TABLE IF NOT EXISTS table_a (
	    server_date Date,
	    event_id UInt64,
	    something String
	) ENGINE = MergeTree(server_date, (server_date, event_id), 8192);

	CREATE TABLE IF NOT EXISTS table_b (
	    server_date Date,
	    event_id UInt64,
	    something Nullable(String)
	) ENGINE = MergeTree(server_date, (server_date, event_id), 8192);

	INSERT INTO table_a VALUES
	    ('2019-01-01', 1, 'foo'),
	    ('2019-01-01', 2, 'foo'),
	    ('2019-01-01', 3, 'bar');

	INSERT INTO table_b VALUES
	    ('2019-01-01', 1, 'bar'),
	    ('2019-01-01', 2, 'bar'),
	    ('2019-01-01', 3, 'test'),
	    ('2019-01-01', 4, NULL);

	SELECT something, count_a, count_b FROM
	(
	    SELECT something, count() AS count_a FROM table_a GROUP BY something
	)
	ALL FULL OUTER JOIN
	(
	    SELECT something, count() AS count_b FROM table_b GROUP BY something
	)
	USING (something)
	ORDER BY count_a DESC;

The server then crashes with a segmentation fault.

**Error message and/or stacktrace**

[clickhouse-server.log](https://github.com/yandex/ClickHouse/files/2962520/clickhouse-server.log)
[clickhouse-server.err.log](https://github.com/yandex/ClickHouse/files/2962522/clickhouse-server.err.log)

**Comment by 4ertus2** [comment]
related #4218

**Comment by 4ertus2** [comment]
Need retry test with #4815

**Comment by alexey-milovidov** [comment]
Fixed in master.
