### ISSUE TITLE
Different results for median and quantile between Clickhouse Versions

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#4690]
Hello,

Having a table with a `Nullable(UInt16)` field populated with 4 rows with values: `65535, 0, null, null`

Running the following functions on ClickHouse master I get different results than running same scenario on Clickhouse 18.12:

```
count = 4,
uniq = 2,
min = 0,
max = 65535,
sum = 65535,
avg = 32767.5,
median = 32767 vs 32767.5 (on 18.12),
quantile(0.9) = 58981 vs 58981.5 (on 18.12)
```

Running another test on a  `Nullable(UInt8)` populated with `255, 0, null, null` I have same results on both Clickhouse versions:

```
count = 4,
uniq = 2,
min = 0,
max = 255,
sum = 255,
avg = 127.5
median = 127.5,
percentile = 229.5
```

Different results I only get on `UInt16`, `UInt32` and `UInt64`.

**Comment by alexey-milovidov** [comment]
Looks like interpolation was lost.

**Comment by hczhcz** [comment]
Seems that it only happens on `UInt16` and `UInt32`.

```sql
select arrayReduce('median', [0, 255]);
select arrayReduce('median', [0, 257]);
select arrayReduce('median', [0, 4294967295]);
select arrayReduce('median', [0, 4294967297]);
```
