### ISSUE TITLE
select data from distributed table and got expected Hello or Exception, got Unknown packet

### ISSUE THREAD

**Issue by xxxxzr** [yandex/ClickHouse#4703]
Hey,I tried to build a cluster with 3 node with following steps;
1.install clickhouse using rpm,ClickHouse client version 19.3.6.
2.modify  /etc/clickhouse-server/config.xml,add 
`<include_from>/etc/clickhouse-server/metrika.xml</include_from>
`
3.then create metrika.xml
`<yandex>
<clickhouse_remote_servers>
    <cluster_3shards_1replicas>
        <shard>
            <replica>
                <host>xxx.xx.xx.32</host>
                <port>9000</port>
                <user>default</user>
                <password>qwerasdf</password>
            </replica>
        </shard>
        <shard>
            <replica>
                <host>xxx.xx.xx.33</host>
                <port>9000</port>
                <user>default</user>
                <password>qwerasdf</password>
            </replica>
        </shard>
        <shard>
            <replica>
                <host>xxx.xx.xx.35</host>
                <port>9000</port>
                <user>default</user>
                <password>qwerasdf</password>
            </replica>
        </shard>
    </cluster_3shards_1replicas>
</clickhouse_remote_servers>
</yandex>`
4.then I modify user.xml,add a password to default
5. repeat 2,3,4 on other 2 node
6.login to node1 (xxx.xx.xx.32),use clickhouse-client,then create table ontime,import some data
7.create table ontime_local with the same schema
8.create table ontime_all
`CREATE TABLE ontime_all AS ontime_local
ENGINE = Distributed(cluster_3shards_1replicas, default, ontime_local, rand())`
9.INSERT INTO ontime_all SELECT * FROM ontime; and succuess insert to ontime_all

Here comes the question,when I use `select count(1) from ontime_all;`
I got
`SELECT count(1)
FROM ontime_all

← Progress: 6.17 million rows, 6.17 MB (53.35 million rows/s., 53.35 MB/s.) Received exception from server (version 19.3.6):
Code: 102. DB::Exception: Received from 127.0.0.1:9000. DB::NetException. DB::NetException: Unexpected packet from server xxx.xx.xx.35:9000 (expected Hello or Exception, got Unknown packet).

0 rows in set. Elapsed: 10.057 sec. Processed 6.17 million rows, 6.17 MB (613.26 thousand rows/s., 613.26 KB/s.)
`
and if I `SELECT count(1) FROM ontime_local` ,I got 33% amount of data in table ontime,
but when I run the same command on 33 and 35 ,I got 0.
what's the problem..

**Comment by filimonov** [comment]
Please try to connect from xxx.xx.xx.32 to xxx.xx.xx.35 using same credentials with `clickhouse-client`

**Comment by xxxxzr** [comment]
> Please try to connect from xxx.xx.xx.32 to xxx.xx.xx.35 using same credentials with `clickhouse-client`

It didn't work. I tried to use  `clickhouse-client`  on xxx.xx.xx.32 and  xxx.xx.xx.35 ,when I run 
 `SELECT count(1) FROM ontime_local` and got count=0

**Comment by xxxxzr** [comment]
> Please try to connect from xxx.xx.xx.32 to xxx.xx.xx.35 using same credentials with `clickhouse-client`

Besides when I login in to xxx.xx.xx.32,I can't connect to xxx.xx.xx.35 using
`clickhouse-client -host xxx.xx.xx.35 --password xxx`

**Comment by filimonov** [comment]
> Besides when I login in to xxx.xx.xx.32,I can't connect to xxx.xx.xx.35 using clickhouse-client -host xxx.xx.xx.35 --password xxx

So you have some connectivity issues. 

Please check your network/ports/listen configuration (for example ensure that you listen needed network interfaces), also firewalls/iptable etc.

**Comment by xxxxzr** [comment]
> > Besides when I login in to xxx.xx.xx.32,I can't connect to xxx.xx.xx.35 using clickhouse-client -host xxx.xx.xx.35 --password xxx
> 
> So you have some connectivity issues.
> 
> Please check your network/ports/listen configuration (for example ensure that you listen needed network interfaces), also firewalls/iptable etc.

When I set <listen_host>0.0.0.0</listen_host> or <listen_host>xxx.xx.xx.35</listen_host>,I find 
`2019.03.18 10:53:08.784607 [ 1 ] {} <Error> Application: Net Exception: Address already in use: 0.0.0.0:9000` 
in `/var/log/clickhouse-server/clickhouse-server.err.log`. 
The only situation  I can start clickhouse server is when I'm not set <listen_host> tab or set <listen_host>127.0.0.1</listen_host>,could you give me some advice?

**Comment by xxxxzr** [comment]
> > Besides when I login in to xxx.xx.xx.32,I can't connect to xxx.xx.xx.35 using clickhouse-client -host xxx.xx.xx.35 --password xxx
> 
> So you have some connectivity issues.
> 
> Please check your network/ports/listen configuration (for example ensure that you listen needed network interfaces), also firewalls/iptable etc.

besides when I login in xxx.xx.xx.32 and  set `<listen_host> xxx.xx.xx.35</listen_host>`,I got this
`2019.03.18 11:07:24.946599 [ 1 ] {} <Error> Application: Listen [::1]: 97: Net Exception: Address family not supported  If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>`
