### ISSUE TITLE
Fail to insert due to "DB::Exception: Unknown setting send_logs_level"

### ISSUE THREAD

**Issue by q0987** [yandex/ClickHouse#4709]
I am not able to insert the data to the remote machine with the following command.

`$ cat file.csv.bin | /usr/bin/clickhouse-client --query="INSERT INTO default.table(timestamp, age) FORMAT RowBinary" --host=ip.address.of.remote --port=9000 --user=username --password=password
`

Error shown from terminal:
Received exception from server (version 18.6.0):
Code: 115. DB::Exception: Received from ip.address.of.remote:9000. DB::Exception: Unknown setting send_logs_level.

However, I am able to insert the data locally through the remote machine.

`$ cat file.csv.bin | /usr/bin/clickhouse-client --query="INSERT INTO default.table(timestamp, age) FORMAT RowBinary" --host=127.0.0.1 --port=9000 --user=username --password=password`

Error shown in server log file:
2019.03.15 13:18:58.656348 [ 23996 ] <Error> ServerErrorHandler: Code: 99, e.displayText() = DB::Exception: Unknown packet 110 from client, e.what() = DB::Exception, Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x48abed6]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x2682dcf]
2. clickhouse-server(DB::TCPHandler::receivePacket()+0x2e0) [0x268c690]
3. clickhouse-server(DB::TCPHandler::runImpl()+0x2b0) [0x268d0c0]
4. clickhouse-server(DB::TCPHandler::run()+0x1c) [0x268e0ac]
5. clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x49eefaf]
6. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x110) [0x49ef610]
7. clickhouse-server(Poco::PooledThread::run()+0x77) [0x4a4df27]
8. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x4a4b488]
9. clickhouse-server() [0x4d3fe1f]
10. /lib64/libpthread.so.0(+0x7dd5) [0x7f0e19b2cdd5]
11. /lib64/libc.so.6(clone+0x6d) [0x7f0e1934fead]

Question> What is the issue of this insertion failure?

Thank you

ClickHouse client version 19.1.6.

**Comment by 4ertus2** [comment]
There's an error when a new version of client have been sending a fresh option 'send_logs_level' to old version of server that could not understand it. You need update (client or server).
