### ISSUE TITLE
[Question] Buffer table num_layers

### ISSUE THREAD

**Issue by igor-sh8** [yandex/ClickHouse#4738]
Hi. 
Have a small question about num_layers in the Buffer table. 
How to choose the right number of the layers ?
How does it correlate maybe with the CPU cores or maybe with something else ? 
Thanks.

**Comment by KochetovNicolai** [comment]
It't usually the number of physical CPU cores.
Also, note that in case of crash data in buffer table which wasn't flushed to ordinary will be lost.

**Comment by igor-sh8** [comment]
Hi. 
Thanks for the info. 
Are there some best practices for creating buffer tables ?
If I have server with 20 cpu cores and I need to create two high load buffer tables (insert 300 rows per second). What value of num_layers do I need to set ? For example 16 layers on the first and 16 layers on the second table - is this a normal configuration ?

**Comment by alexey-milovidov** [comment]
Two layers is enough for at least 1000 inserts per second.

There are very few cases when you need more layers. More layers will lead to higher memory usage and more frequent inserts to the target table.
