### ISSUE TITLE
SET vs MEMORY engine usage in the right half of the IN operator

### ISSUE THREAD

**Issue by healiseu** [yandex/ClickHouse#4739]
Hi, this question occurred to me as I have been experimenting with my data.
Suppose you have the following engines

```sql
CREATE TABLE SX ( hbx UInt32 ) ENGINE = Set
CREATE TABLE MX ( hbx UInt32 ) ENGINE = Memory

INSERT INTO MX (SELECT ....)
Ok.
0 rows in set. Elapsed: 0.019 sec. Processed 1.26 million rows, 11.64 MB (68.25 million rows/s., 628.21 MB/s.)

INSERT INTO SX (SELECT ....)
Ok.
0 rows in set. Elapsed: 0.081 sec. Processed 1.26 million rows, 11.64 MB (15.69 million rows/s., 144.46 MB/s.)

SELECT COUNT(*) FROM MX
┌─count()─┐
│ 1097065 │
└─────────┘
1 rows in set. Elapsed: 0.003 sec. Processed 1.10 million rows, 4.39 MB (408.53 million rows/s., 1.63 GB/s.) 
```
### Up to this point there is a difference in writing speed (1) and according to ClickHouse documentation you cannot count or see the data in `Set` engine (2). 

Now, suppose you want to use these engines at the right half of the IN operator e.g.

```sql
DESCRIBE TABLE HL

┌─name─┬─type───┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┐
│ ha2  │ UInt16 │              │                    │         │                  │
│ ha1  │ UInt32 │              │                    │         │                  │
│ hb2  │ UInt16 │              │                    │         │                  │
│ hb1  │ UInt32 │              │                    │         │                  │
└──────┴────────┴──────────────┴────────────────────┴─────────┴──────────────────┘

SELECT count(*) FROM HL
┌──count()─┐
│ 64894609 │
└──────────┘
1 rows in set. Elapsed: 0.029 sec. Processed 64.89 million rows, 129.79 MB (2.26 billion rows/s., 4.52 GB/s.)

SELECT count(*) FROM HL WHERE (hb1 IN SX) AND (ha2 = 11)
┌─count()─┐
│ 1097065 │
└─────────┘
1 rows in set. Elapsed: 0.066 sec. Processed 2.78 million rows, 16.68 MB (42.06 million rows/s., 252.35 MB/s.)

SELECT count(*) FROM HL  WHERE (hb1 IN MX) AND (ha2 = 11)
┌─count()─┐
│ 1097065 │
└─────────┘
1 rows in set. Elapsed: 0.105 sec. Processed 3.88 million rows, 21.07 MB (36.88 million rows/s., 200.42 MB/s.)
```
### It's clear that `Set` engine is faster than `Memory` engine because it is processing less rows (3). 

Can someone **comment on these differences (1, 2, 3) ?** , what are the internals for each engine under the hood, e.g. data structures, and how they are used in each case ?

Would you recommend a different approach for the case I covered above ?

In terms of the overall performance, it seems `Set` engine has an advantage when it is used in the right half of the IN operator but one has to compensate for the limited visibility of this engine and its writing speed that is lower compared to `Memory` engine 

Thanks in advance for your effort and time to answer this.

**Comment by KochetovNicolai** [comment]
(1) Because data for Set engine is also was written to file, but for Memory only to memory (so this table will not have data after restart). Also, Set is a hash table inside, and it takes time to build it. Memory is just a list of columns.
(2) Because in some cases (for complex keys) hash table stores SipHash(row)  instead of row in order to save memory. Technically, it may lead to collision, but has is cryptographic and probability is negligible.
(3) When Memory table is used in IN, it's just converted to Set (that's why extra 1.10 million rows from MX were processed).

**Comment by healiseu** [comment]
@KochetovNicolai  thank you, that's a crystal clear explanation, I am closing this issue.
