### ISSUE TITLE
DB::Exception: Table structure in ZooKeeper is too different from local table structure.

### ISSUE THREAD

**Issue by nvartolomei** [yandex/ClickHouse#4746]
Hi,

Would like advise on how to fix this issue, got myself into this.

The story: there are 2 shards which now have columns in different order in their schemas.

`table_null` (Null engine) materialized view to `table_1m` (ReplicatedMergeTree).

Problem: Bootstrap sql files I use to create a new replica when one dies will be always inconsistent in respect to one of the shards and it will fail.

How could I fix this problem for both null tables and table_1m?

For null table i guess it is enough to edit sql file in metadata directory.

What about table with ReplicatedMergeTree engine? There is sql file in metadata directory, then columns.txt and then zk metadata, do all of them need to be fixed? Is there something else to be aware of?

What about materialized view?

**Comment by KochetovNicolai** [comment]
I'm not sure, but probably it's enough to change only .sql file. However, it's not a good idea to change metadata and `columns.txt` manually. Better to use proper scheme for create query, or recreate table on one replica to make them same.

**Comment by xmariachi** [comment]
Hi @nvartolomei, was this fixed or worked around? Could you please share any insights? Thanks!
