### ISSUE TITLE
"LIMIT n OFFSET m" syntax is not documented

### ISSUE THREAD

**Issue by ssheludchenko** [yandex/ClickHouse#4765]
Hi,
Support of "LIMIT n OFFSET m" syntax is not documented anywhere in [docs](https://clickhouse.yandex/docs/en/query_language/select/#limit-clause) except changelog.
Could you please add it to documentation to make sure that support of this syntax won't be dropped in near future?

Related PR:
[#2840](https://github.com/yandex/ClickHouse/pull/2840)

**Comment by alexey-milovidov** [comment]
Ok. You can be sure that that support of this syntax won't be dropped in future.
