### ISSUE TITLE
pointInPolygon and polygons crosses the ~180 (Opposite of Greenwich)

### ISSUE THREAD

**Issue by ivanzolotuhin** [yandex/ClickHouse#4769]
(you don't have to strictly follow this form)

**Describe the bug**
Sometimes requires to check pointInPolygon (and potentially other Geo functions) that point in polygon which crosses Opposite Greenwich meridian in Pacific ocean, but this polygons outside the -/+180 boundary. But google maps uses them and generates them.

Example:

Function returns 0 results.

**How to reproduce**
* Which ClickHouse server version to use
19.4.0.49
* Queries to run that lead to unexpected result

Both example points are in polygon, but ClickHouse showing that only one in Polygon
```
SELECT pointInPolygon((0, -170), [(41.21726864182845, -180), (42.78528336200011, -115.66406250000001), (-11.92471931078849, -100.89843750000001), (-23.29943075461891, -180)]) AS res

┌─res─┐
│   1 │
└─────┘

1 rows in set. Elapsed: 0.002 sec. 

SELECT pointInPolygon((0, 170), [(41.21726864182845, -211), (42.78528336200011, -115.66406250000001), (-11.92471931078849, -100.89843750000001), (-23.29943075461891, -211)]) AS res

┌─res─┐
│   0 │
└─────┘

1 rows in set. Elapsed: 0.002 sec. 

```

moreover on example dataset it returns me less point on original polygon, but it ~2x bigger than reduced to 180 degree boundry
```
SELECT count(*)
FROM ais.messages 
PREWHERE ((message_ts >= '2010-10-01 00:00:00') AND (message_ts <= '2010-10-05 08:00:00')) AND pointInPolygon((lat, lon), [(41.21726864182845, -211.99218750000003), (42.
78528336200011, -115.66406250000001), (-11.92471931078849, -100.89843750000001), (-23.29943075461891, -215.5078125)])

┌─count()─┐
│ 2787820 │
└─────────┘

1 rows in set. Elapsed: 0.424 sec. Processed 88.54 million rows, 1.06 GB (208.63 million rows/s., 2.50 GB/s.) 

ip-10-1-164-17.corplan.net :) SELECT count(*) \
:-] FROM ais.messages \
:-] PREWHERE message_ts  \
:-]     BETWEEN  '2010-10-01 00:00:00' \
:-]         AND  '2010-10-05 08:00:00' \
:-] AND pointInPolygon((lat, lon), [ \
:-] (41.21726864182845, -180), \
:-] (42.78528336200011, -115.66406250000001), \
:-] (-11.92471931078849, -100.89843750000001), \
:-] (-23.29943075461891, -180) \
:-] ])

SELECT count(*)
FROM ais.messages 
PREWHERE ((message_ts >= '2010-10-01 00:00:00') AND (message_ts <= '2010-10-05 08:00:00')) AND pointInPolygon((lat, lon), [(41.21726864182845, -180), (42.78528336200011,
 -115.66406250000001), (-11.92471931078849, -100.89843750000001), (-23.29943075461891, -180)])

┌─count()─┐
│ 2801649 │
└─────────┘

1 rows in set. Elapsed: 0.503 sec. Processed 88.54 million rows, 1.06 GB (176.06 million rows/s., 2.11 GB/s.) 
```

**Expected behavior**
If I am trying to find points in polygon then in whole example polygon (up to -211 longtitude) it returns me less vessels than when I am manually limiting polygon up to -180, but polygon ~2x bigger.

**Additional context**
Not sure how to handle -/+ polygons in Opposite Greenwich in Pacific Ocean

**Comment by KochetovNicolai** [comment]
Well, it's expected behaviour for current implementation of `pointInPolygon` function. It works for points on the Cartesian plane. It's also ok for small polygons on sphere, but for sure won't fork for poles and polygons outside the -/+180 boundary.
