### ISSUE TITLE
JBOD Support

### ISSUE THREAD

**Issue by nvartolomei** [yandex/ClickHouse#4786]
JBOD support is present in 2019 roadmap. Do you already have a design in mind? Would we get some features related to https://clickhouse.yandex/blog/en/concept-cloud-mergetree-tables with automatic resharding on disk failures or just the ability to spread writes to multiple disks in a consistent fashion across multiple replicas so that in case of a disk failure there is less to replicate and that's it?

**Comment by blinkov** [comment]
It was about much more simple feature: allow to configure multiple folders to store data (that might reside on different kinds of disks or filesystems) and specify rules on which table part goes where.

**Comment by nvartolomei** [comment]
#4918
