### ISSUE TITLE
support distribute ddl

### ISSUE THREAD

**Issue by cmdares** [yandex/ClickHouse#4787]
Distributed tables need to be built for a large number of tables. At present, there are 20 nodes in the cluster. The workload of table structure management is very large. It is hoped that the ability of distributed management can be optimized, especially for ddl.
Because of the previous use of elasticsearch, the distributed management of ES is very perfect, and some excellent experience can be used for reference.
thanks.

**Comment by blinkov** [comment]
Distributed DDL feature has already been implemented pretty long time ago: https://clickhouse.yandex/docs/en/query_language/create/#distributed-ddl-queries-on-cluster-clause
