### ISSUE TITLE
use streamsets jdbc insert clickhouse allway throw sock error

### ISSUE THREAD

**Issue by qinzl1** [yandex/ClickHouse#4788]
clickhouse version 18.16.1
![menu saveimg savepath20190325103002](https://user-images.githubusercontent.com/20242930/54896579-ea893b80-4eff-11e9-8126-9e5b57068911.jpg)

**Comment by den-crane** [comment]
Not a bug. Default JDBC socket timeout time is 30sec.
https://github.com/yandex/clickhouse-jdbc/issues/159
