### ISSUE TITLE
I got a build error in centos7 for 19.3.5

### ISSUE THREAD

**Issue by kindred77** [yandex/ClickHouse#4789]
centos7
gcc7.3.0
cmake3.13.2

error in command "make -j 4"

[ 25%] Linking CXX executable rvo_test
[ 25%] Built target farmhash
g++: error: libs/libglibc-compatibility/libglibc-compatibility.a: No such file or directory
make[2]: *** [dbms/src/Core/tests/rvo_test] Error 1
make[1]: *** [dbms/src/Core/tests/CMakeFiles/rvo_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 26%] Built target metrohash
[ 26%] Built target murmurhash
[ 26%] Built target thrift_static
make: *** [all] Error 2

please help.

**Comment by proller** [comment]
Try build with  ```cmake -DGLIBC_COMPATIBILITY=0```

**Comment by proller** [comment]
Also it maybe already fixed in master by https://github.com/yandex/ClickHouse/commit/18e3dd137c0e67175f6878e413821625a547ecb6

**Comment by kindred77** [comment]
It works, thanks.
