### ISSUE TITLE
all inner join  data is null

### ISSUE THREAD

**Issue by huaerze** [yandex/ClickHouse#4800]
I have two tables. the first table number is about 300000. the second number is about 400000.
I executed a query 
"select  AA.user_id user_id0, BB.user_id user_id1
  from (select user_id
        from table1
        where time >= '20190214'
          and time <= '20190325'
        group by user_id) AA
        all inner join (select user_id
                    from table2
                    where time >= '20190214'
                      and time <= '20190325' and product_id=111
                    group by user_id ) BB using user_id"
I got a result  
user_id0	user_id1
11115	
11243	
11296	
11201	
11223	
11279	
11302	
11224	

if I executed another query 
"select  AA.user_id user_id0, BB.user_id user_id1
  from (select user_id
        from table1
        where time >= '20190214'
          and time <= '20190325'
        group by user_id) AA
        **any** inner join (select user_id
                    from table2
                    where time >= '20190214'
                      and time <= '20190325' and product_id=111
                    group by user_id ) BB using user_id"

I got a result 
user_id0	user_id1
11115	11115
11243	11243
11296	11296
11201	11201
11223	11223
11279	11279
11302	11302
11224	11224

if I executed another query, I just switched the columns
"select  BB.user_id user_id0, AA.user_id user_id1
  from (select user_id
        from table1
        where time >= '20190214'
          and time <= '20190325'
        group by user_id) AA
        all inner join (select user_id
                    from table2
                    where time >= '20190214'
                      and time <= '20190325' and product_id=111
                    group by user_id ) BB using user_id"

I got exception

2019.03.26 14:49:33.287378 [ 2 ] {} <Error> BaseDaemon: ########################################
2019.03.26 14:49:33.287441 [ 2 ] {} <Error> BaseDaemon: (from thread 35) Received signal Segmentation fault (11).
2019.03.26 14:49:33.287451 [ 2 ] {} <Error> BaseDaemon: Address: NULL pointer.
2019.03.26 14:49:33.287458 [ 2 ] {} <Error> BaseDaemon: Access: read.
2019.03.26 14:49:33.287466 [ 2 ] {} <Error> BaseDaemon: Unknown si_code.
2019.03.26 14:49:33.316936 [ 2 ] {} <Error> BaseDaemon: 0. clickhouse-server(memcpy+0x7f) [0x5f481df]
2019.03.26 14:49:33.316986 [ 2 ] {} <Error> BaseDaemon: 1. clickhouse-server(void DB::writeAnyEscapedString<(char)39>(char const*, char const*, DB::WriteBuffer&)+0x29f) [0x2ce3e8f]
2019.03.26 14:49:33.317010 [ 2 ] {} <Error> BaseDaemon: 2. clickhouse-server(DB::DataTypeNullable::serializeTextEscaped(DB::IColumn const&, unsigned long, DB::WriteBuffer&, DB::FormatSettings const&) const+0x30) [0x4924f20]
2019.03.26 14:49:33.317021 [ 2 ] {} <Error> BaseDaemon: 3. clickhouse-server(DB::BlockOutputStreamFromRowOutputStream::write(DB::Block const&)+0x94) [0x4f5a714]
2019.03.26 14:49:33.317030 [ 2 ] {} <Error> BaseDaemon: 4. clickhouse-server(DB::MaterializingBlockOutputStream::write(DB::Block const&)+0x5ed) [0x4cef85d]
2019.03.26 14:49:33.317042 [ 2 ] {} <Error> BaseDaemon: 5. clickhouse-server(DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::atomic<bool>*)+0x96) [0x48c04f6]
2019.03.26 14:49:33.317055 [ 2 ] {} <Error> BaseDaemon: 6. clickhouse-server(DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::function<void (std::string const&)>)+0x4c6) [0x4aa4006]
2019.03.26 14:49:33.317070 [ 2 ] {} <Error> BaseDaemon: 7. clickhouse-server(DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&)+0x32b4) [0x2c7a0d4]
2019.03.26 14:49:33.317080 [ 2 ] {} <Error> BaseDaemon: 8. clickhouse-server(DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)+0x3c9) [0x2c7c5e9]
2019.03.26 14:49:33.317094 [ 2 ] {} <Error> BaseDaemon: 9. clickhouse-server(Poco::Net::HTTPServerConnection::run()+0x23e) [0x6127c9e]
2019.03.26 14:49:33.317125 [ 2 ] {} <Error> BaseDaemon: 10. clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x6123c3f]
2019.03.26 14:49:33.317134 [ 2 ] {} <Error> BaseDaemon: 11. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x110) [0x61242a0]
2019.03.26 14:49:33.317143 [ 2 ] {} <Error> BaseDaemon: 12. clickhouse-server(Poco::PooledThread::run()+0x77) [0x62d3217]
2019.03.26 14:49:33.317151 [ 2 ] {} <Error> BaseDaemon: 13. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x62d0778]
2019.03.26 14:49:33.317158 [ 2 ] {} <Error> BaseDaemon: 14. clickhouse-server() [0x6387c2f]
2019.03.26 14:49:33.317165 [ 2 ] {} <Error> BaseDaemon: 15. /lib64/libpthread.so.0(+0x7dc5) [0x7f54382eedc5]

I do not the  reason

**Comment by huaerze** [comment]
clickhouse version is 19.1.6

**Comment by 4ertus2** [comment]
Hi,

It looks like you are trying join with nullable columns. There could be some bugs there.

1. Could you get your schema. It's interesting which of joined columns are Nullable and which are not.
2. Could you reproduce crash without GROUP BY and other complex constructions? We need the minimum minimorum sample :)

Thanks

**Comment by 4ertus2** [comment]
related #4681

**Comment by huaerze** [comment]
@4ertus2  I have upgraded clickhouse version to 4.1.0. Then everything is ok. Thanks
