### ISSUE TITLE
ld.gold build issue when using additional "libocci" library.

### ISSUE THREAD

**Issue by kindred77** [yandex/ClickHouse#4817]
Hi, I want to add oracle occi for clickhouse on ubuntu, but I got "clickhouse-server: symbol lookup error: ***/libocci.so.12.1: undefined symbol: OCIEnvCreate".

I analyzed the clickhouse exe file using ldd:

linux-vdso.so.1 =>  (0x00007ffe9582f000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbbd36e9000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fbbd34e5000)
librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fbbd32dd000)
libocci.so.12.1 => /occi_lib/test/instantclient_12_1/libocci.so.12.1 (0x00007fbbd2f9f000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbbd2c96000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbbd28cc000)
/lib64/ld-linux-x86-64.so.2 (0x00007fbbd3906000)
libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fbbd2540000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fbbd2328000)

nm  libocci.so | grep OCIEnvCreate
                 U OCIEnvCreate
nm libclntsh.so | grep OCIEnvCreate
000000000052d330 T OCIEnvCreate

It seams OCIEnvCreate is a reference function in occi.so, actually it is defined in clntsh.so.
but the ld.gold linker do not link the clntsh.so to clickhouse, so I got this error.

It is ok when I build clickhouse in centos7:

ldd clickhouse:
        linux-vdso.so.1 =>  (0x00007ffe56d68000)
	libreadline.so.6 => /lib64/libreadline.so.6 (0x00007f659ed5b000)
	libtinfo.so.5 => /lib64/libtinfo.so.5 (0x00007f659eb31000)
	libicui18n.so.50 => /lib64/libicui18n.so.50 (0x00007f659e732000)
	libicuuc.so.50 => /lib64/libicuuc.so.50 (0x00007f659e3b9000)
	libicudata.so.50 => /lib64/libicudata.so.50 (0x00007f659cde7000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f659cbe3000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f659c9c7000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f659c7bf000)
	libocci.so.12.1 => /clickhouse/instantclient_12_1/libocci.so.12.1 (0x00007f659c481000)
	libclntsh.so.12.1 => /clickhouse/instantclient_12_1/libclntsh.so.12.1 (0x00007f65994c4000)
	libnnz12.so => /clickhouse/instantclient_12_1/libnnz12.so (0x00007f6598dba000)
	libclntshcore.so.12.1 => /clickhouse/instantclient_12_1/libclntshcore.so.12.1 (0x00007f6598848000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f6598546000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f6598179000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f659efa1000)
	libstdc++.so.6 => /usr/local/lib64/libstdc++.so.6 (0x00007f6597df7000)
	libgcc_s.so.1 => /usr/local/lib64/libgcc_s.so.1 (0x00007f6597be0000)
	libmql1.so => /clickhouse/instantclient_12_1/libmql1.so (0x00007f659796a000)
	libipc1.so => /clickhouse/instantclient_12_1/libipc1.so (0x00007f65975ec000)
	libons.so => /clickhouse/instantclient_12_1/libons.so (0x00007f65973a7000)
	libnsl.so.1 => /lib64/libnsl.so.1 (0x00007f659718d000)
	libaio.so.1 => /lib64/libaio.so.1 (0x00007f6596f8b000)

I think may be there's parameter for ld.gold to solve this problem.
Please help.

**Comment by kindred77** [comment]
I add below in CMakeLists.txt in ubuntu for occi libs:

target_link_libraries(dbms PUBLIC -locci -lclntsh -lnnz12 -lclntshcore)

**Comment by proller** [comment]
Try use full path to lib.
Or better use find_library https://cmake.org/cmake/help/latest/command/find_library.html

**Comment by kindred77** [comment]
Hi, I got another error:

../contrib/boost/boost/system/error_code.hpp:461: error: undefined reference to 'boost::system::system_category()'
../contrib/boost/boost/system/error_code.hpp:491: error: undefined reference to 'boost::system::system_category()'
../contrib/boost/boost/system/error_code.hpp:733: error: undefined reference to 'boost::system::generic_category()'
../contrib/boost/boost/system/error_code.hpp:736: error: undefined reference to 'boost::system::generic_category()'
../contrib/boost/boost/system/error_code.hpp:748: error: undefined reference to 'boost::system::generic_category()'
../contrib/boost/boost/system/error_code.hpp:703: error: undefined reference to 'boost::system::generic_category()'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
