### ISSUE TITLE
funtion toFloat64 does not return the minimum positive number possible

### ISSUE THREAD

**Issue by mkarmona** [yandex/ClickHouse#4819]
The operation `toFloat64('5e-324')` and `toFloat64('4.9e-324')` should return the minimum positive value for a Float64 number which is `4.9e-324`

```sql

SELECT toFloat64('5e-324')

┌─toFloat64('5e-324')─┐
│                   0 │
└─────────────────────┘

1 rows in set. Elapsed: 0.002 sec. 

ot-genetics :) select toFloat64('4.9e-324')

SELECT toFloat64('4.9e-324')

┌─toFloat64('4.9e-324')─┐
│                     0 │
└───────────────────────┘

1 rows in set. Elapsed: 0.002 sec. 
```

Clickhouse version
```
ii  clickhouse-client                     19.4.1.3                       all          Client binary for ClickHouse
ii  clickhouse-common-static              19.4.1.3                       amd64        Common files for ClickHouse
ii  clickhouse-server                     19.4.1.3                       all          Server binary for ClickHouse
```

**Comment by alexey-milovidov** [comment]
Our floating point parser does not always return the nearest machine representable number (this is documented behaviour). Details are here: https://github.com/yandex/ClickHouse/blob/0eed697623afd251c1908073c4a2850a9bfc9cdc/dbms/src/IO/readFloatText.h#L9

Though, we still have a chance to implement a setting to dynamically choose the method of floats parsing and include precise method.
