### ISSUE TITLE
Create load balancing policy: random_prefer_first

### ISSUE THREAD

**Issue by nvartolomei** [yandex/ClickHouse#4820]
**Use case**
For [cross-replication topology setups](https://github.com/yandex/ClickHouse/blob/master/dbms/tests/integration/test_cross_replication/test.py) `load_balancing=in_order` works best as nodes handle equal amount of load and usually they hit only 1/n of data (n = number of replicas), which makes page cache usage more efficient.

The problem is when one node of the shard goes down. If one replica goes down, the next one in config will handle twice the usual load while remaining ones will handle usual traffic.

**Describe the solution you'd like**

Create a random_prefer_first load balancing policy, so that when all replicas are present load will be spread equally among them, but when one goes down all other replicas will handle 1+1/(n-1) load instead of 1+1.

**Comment by alexey-milovidov** [comment]
Prefer first replica in order, and if it is unavailable, loop through all other replicas at random?

**Comment by nvartolomei** [comment]
@alexey-milovidov sounds like it ;)
