### ISSUE TITLE
I got "undefined reference to boost::system::***" when build mater on ubuntu16.04. 

### ISSUE THREAD

**Issue by kindred77** [yandex/ClickHouse#4840]
../contrib/boost/boost/system/error_code.hpp:461: error: undefined reference to 'boost::system::system_category()'
../contrib/boost/boost/system/error_code.hpp:491: error: undefined reference to 'boost::system::system_category()'
../contrib/boost/boost/system/error_code.hpp:733: error: undefined reference to 'boost::system::generic_category()'
../contrib/boost/boost/system/error_code.hpp:736: error: undefined reference to 'boost::system::generic_category()'
../contrib/boost/boost/system/error_code.hpp:748: error: undefined reference to 'boost::system::generic_category()'
../contrib/boost/boost/system/error_code.hpp:703: error: undefined reference to 'boost::system::generic_category()'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by proller** [comment]
Did you have libboost-dev installed?
Can you show full cmake and ninja/make output ?

**Comment by kindred77** [comment]
libboost-dev 1.58 is installed.

apt list | grep libboost-dev
libboost-dev/xenial 1.58.0.1ubuntu1 amd64

cmake ..

-- IPO/LTO not enabled.
-- CMAKE_BUILD_TYPE is not set, set to default = RELWITHDEBINFO
-- CMAKE_BUILD_TYPE: RELWITHDEBINFO
-- Using linker: gold (selected from: LLD_PATH=LLD_PATH-NOTFOUND; GOLD_PATH=/usr/bin/gold; COMPILER_POSTFIX=-7)
-- Disabling compiler -pipe option (have only 2622 mb of memory)
-- Default libraries: -nodefaultlibs -Wl,-Bstatic -lstdc++ -lgcc_eh -lgcc  -Wl,-Bdynamic -lrt -ldl -lpthread -lm -lc
-- Tests are enabled
-- Building for: Linux-4.15.0-43-generic x86_64 x86_64-linux-gnu ; USE_STATIC_LIBRARIES=ON MAKE_STATIC_LIBRARIES=ON SPLIT_SHARED= UNBUNDLED=OFF CCACHE=CCACHE_FOUND-NOTFOUND 
-- Using ssl=1: /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/ssl/include : ssl;crypto
-- Found the following ICU libraries:
--   i18n (required)
--   uc (required)
--   data (required)
-- Using icu=1: /usr/include/x86_64-linux-gnu : /usr/lib/x86_64-linux-gnu/libicui18n.a;/usr/lib/x86_64-linux-gnu/libicuuc.a;/usr/lib/x86_64-linux-gnu/libicudata.a
CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  cmake/find_boost.cmake:12 (find_package)
  CMakeLists.txt:291 (include)


CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  cmake/find_boost.cmake:12 (find_package)
  CMakeLists.txt:291 (include)


CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  cmake/find_boost.cmake:12 (find_package)
  CMakeLists.txt:291 (include)


CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  cmake/find_boost.cmake:12 (find_package)
  CMakeLists.txt:291 (include)


CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  cmake/find_boost.cmake:12 (find_package)
  CMakeLists.txt:291 (include)


-- Could NOT find Boost
-- Using Boost: /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/boost : boost_program_options_internal,boost_system_internal,boost_filesystem_internal;boost_system_internal,boost_regex_internal
-- Using zlib-ng: /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/zlib-ng;/home/kindred/clickhouse/for_deploy/ClickHouse/build/contrib/zlib-ng : zlibstatic
-- Using zstd: /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/zstd/lib : zstd
-- Using termcap: /usr/lib/x86_64-linux-gnu/libtermcap.a
-- Using odbc=1:  : unixodbc
-- Using Poco: /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/poco/Foundation/include/;/home/kindred/clickhouse/for_deploy/ClickHouse/contrib/poco/Util/include/;/home/kindred/clickhouse/for_deploy/ClickHouse/contrib/zlib-ng/;/home/kindred/clickhouse/for_deploy/ClickHouse/build/contrib/zlib-ng/ : PocoFoundation,PocoUtil,PocoNet,PocoNetSSL;ssl;crypto,PocoCrypto;ssl;crypto,PocoXML,PocoData,PocoDataODBC;unixodbc,,,PocoMongoDB; MongoDB=1, DataODBC=1, NetSSL=1
-- Using lz4: /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/lz4/lib : lz4
-- Using xxhash=1: /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/lz4/lib : lz4
-- Using sparsehash: /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/libsparsehash
-- Using rt: 
-- Using line editing libraries (readline): /usr/include : /usr/lib/x86_64-linux-gnu/libreadline.a;/usr/lib/x86_64-linux-gnu/libtermcap.a
-- Using re2: /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/re2 : re2;  : re2_st
-- Using librdkafka=1: /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/librdkafka/src : rdkafka cppkafka
-- Build without capnp (support for Cap'n Proto format will be disabled)
CMake Warning at cmake/find_llvm.cmake:21 (find_package):
  Could not find a package configuration file provided by "LLVM" (requested
  version 7) with any of the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:308 (include)


CMake Warning at cmake/find_llvm.cmake:23 (find_package):
  Could not find a package configuration file provided by "LLVM" (requested
  version 6) with any of the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:308 (include)


CMake Warning at cmake/find_llvm.cmake:26 (find_package):
  Could not find a package configuration file provided by "LLVM" (requested
  version 8) with any of the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:308 (include)


CMake Warning at cmake/find_llvm.cmake:29 (find_package):
  Could not find a package configuration file provided by "LLVM" (requested
  version 5) with any of the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:308 (include)


-- Using cpuid=1: /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/libcpuid/include : cpuid
-- Using libgsasl: /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/libgsasl/src;/home/kindred/clickhouse/for_deploy/ClickHouse/contrib/libgsasl/linux_x86_64/include : libgsasl
-- Using libxml2: /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/libxml2/include;/home/kindred/clickhouse/for_deploy/ClickHouse/contrib/libxml2-cmake/linux_x86_64/include : libxml2
-- Using brotli=1: /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/brotli/c/include : brotli
-- Using protobuf=1: /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/protobuf/src : libprotobuf
-- Using pdqsort: /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/pdqsort
-- Using hdfs3=1: /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/libhdfs3/include : hdfs3
-- Using consistent-hashing:  : consistent-hashing
-- Using hyperscan=1: /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/hyperscan/src : hs
-- Using cityhash:  : cityhash
-- Using farmhash:  : farmhash
-- Using metrohash: /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/libmetrohash/src : metrohash
-- Using btrie:  : btrie
-- Using double-conversion: /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/double-conversion : double-conversion
-- Using snappy=1: /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/snappy : snappy
-- Using Parquet: arrow_static: ; parquet_static: ; thrift_static
-- Using gtest=1: /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/googletest/googletest : gtest_main;gtest : 
-- Using jemalloc=1: /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/jemalloc-cmake/include;/home/kindred/clickhouse/for_deploy/ClickHouse/contrib/jemalloc-cmake/include_linux_x86_64 : jemalloc
-- Using cctz: /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/cctz/include : cctz
-- Using mysqlclient=1:  : mysqlclient; staticlib=
-- Using unwind=1: /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/libunwind/include : unwind
-- compiler C   = /usr/bin/gcc-7  -fdiagnostics-color=always  -msse4.1 -msse4.2 -mpopcnt -fno-omit-frame-pointer  -Wall  -no-pie -O2 -g -DNDEBUG -O3 
-- compiler CXX = /usr/bin/g++-7  -fdiagnostics-color=always -std=c++1z  -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall  -Wnon-virtual-dtor -no-pie -O2 -g -DNDEBUG -O3 
-- LINKER_FLAGS =  -fuse-ld=gold 
-- ZSTD VERSION 1.3.17
-- Architecture: x86_64
-- Architecture-specific source files: arch/x86/x86.c;arch/x86/insert_string_sse.c;arch/x86/deflate_quick.c;arch/x86/fill_window_sse.c;arch/x86/crc_folding.c;arch/x86/crc_pclmulqdq.c
-- 
-- The following features have been enabled:

 * CMAKE_BUILD_TYPE , Build type: RELWITHDEBINFO (selected)
 * ZLIB_COMPAT , Provide a zlib-compatible API
 * WITH_GZFILEOP , Compile with support for gzFile-related functions
 * WITH_OPTIM , Build with optimisation
 * WITH_NEW_STRATEGIES , Use new strategies
 * SSE2 , Use the SSE2 instruction set, using "-msse2"
 * SSE4_CRC , Support CRC hash generation using the SSE4.2 instruction set, using "-msse4"
 * SSE4DEFLATE , Support SSE4.2-accelerated quick decompression
 * PCLMUL_CRC , Support CRC hash generation using PCLMULQDQ, using "-mpclmul"

-- The following OPTIONAL packages have been found:

 * Threads
 * ICU

-- The following OPTIONAL packages have not been found:

 * Boost (required version >= 1.60)
 * LLVM (required version >= 5)

-- Using OpenSSL from /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/ssl
-- Using odbc: /home/kindred/clickhouse/for_deploy/ClickHouse/contrib/unixodbc/include : unixodbc
-- checking compiler: GCC (7.7.)
-- Checking whether strerror_r returns an int
-- Checking whether strerror_r returns an int -- no
-- Build type RELWITHDEBINFO
-- Boost version: 1.69.0
-- Build date: 2019-04-01
-- gcc version 7.4.0
-- g++ version 7.4.0
-- generator is Ninja
-- Building without AVX512 support
-- Building for current host CPU: 
-- Doxygen not found, unable to generate API reference
-- Sphinx not found, unable to generate developer reference
-- Checking for module 'libpcre>=8.41'
--   
-- PCRE version 8.41 or above not found
-- PCRE 8.41 or above not found
-- Could not find libpcap - some examples will not be built
-- Link jemalloc: jemalloc
-- /home/kindred/clickhouse/for_deploy/ClickHouse/utils: Have 2608 megabytes of memory. Limiting concurrent linkers jobs to 1 and compiler jobs to OFF
-- /home/kindred/clickhouse/for_deploy/ClickHouse/dbms: Have 2606 megabytes of memory. Limiting concurrent linkers jobs to 1 and compiler jobs to 1
-- Will build ClickHouse 19.5.1.1 revision 54417
-- Using internal=OFF compiler=0: headers=/usr/share/clickhouse/headers/19.3.4 :  /usr/local/bin/clickhouse-clang  -fdiagnostics-color=always -std=c++1z  -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall  -Wnon-virtual-dtor  -Wextra -Werror -O2 -g -DNDEBUG -O3   -x c++ -march=native -fPIC -fvisibility=hidden -fno-implement-inlines -nostdinc -nostdinc++ -Wno-unused-command-line-argument -Bprefix=/usr/share/clickhouse -isysroot=/usr/share/clickhouse/headers/19.3.4; clickhouse-lld
-- Using occi lib: /occi_lib/test/instantclient_12_1/libocci.so /occi_lib/test/instantclient_12_1/libclntsh.so
-- Target check already exists
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kindred/clickhouse/for_deploy/ClickHouse/build

ninja clickhouse:

[22/22] Linking CXX executable dbms/programs/clickhouse
FAILED: : && /usr/bin/g++-7   -fdiagnostics-color=always -std=c++1z  -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall  -Wnon-virtual-dtor -no-pie -Wextra -Werror -O2 -g -DNDEBUG -O3  -fuse-ld=gold dbms/programs/CMakeFiles/clickhouse.dir/main.cpp.o  -o dbms/programs/clickhouse  -rdynamic dbms/libclickhouse_common_io.a dbms/src/Common/StringUtils/libstring_utils.a dbms/programs/server/libclickhouse-server-lib.a dbms/programs/client/libclickhouse-client-lib.a dbms/programs/local/libclickhouse-local-lib.a dbms/programs/benchmark/libclickhouse-benchmark-lib.a dbms/programs/performance-test/libclickhouse-performance-test-lib.a dbms/programs/copier/libclickhouse-copier-lib.a dbms/programs/extract-from-config/libclickhouse-extract-from-config-lib.a dbms/programs/compressor/libclickhouse-compressor-lib.a dbms/programs/format/libclickhouse-format-lib.a dbms/programs/obfuscator/libclickhouse-obfuscator-lib.a dbms/programs/server/libclickhouse-server-lib.a dbms/programs/client/libclickhouse-client-lib.a /usr/lib/x86_64-linux-gnu/libreadline.a /usr/lib/x86_64-linux-gnu/libtermcap.a libs/libdaemon/libdaemon.a contrib/libunwind/libunwind.a dbms/src/Functions/libclickhouse_functions.a dbms/src/Dictionaries/libclickhouse_dictionaries.a libs/consistent-hashing/libconsistent-hashing.a libs/consistent-hashing-sumbur/libconsistent-hashing-sumbur.a contrib/libfarmhash/libfarmhash.a contrib/libmetrohash/libmetrohash.a contrib/murmurhash/libmurmurhash.a contrib/base64-cmake/libbase64.a contrib/hyperscan/lib/libhs.a dbms/src/AggregateFunctions/libclickhouse_aggregate_functions.a dbms/src/TableFunctions/libclickhouse_table_functions.a dbms/src/Storages/System/libclickhouse_storages_system.a dbms/libdbms.a dbms/src/Common/Config/libclickhouse_common_config.a dbms/src/Common/ZooKeeper/libclickhouse_common_zookeeper.a contrib/poco/XML/libPocoXML.a contrib/boost-cmake/libboost_program_options_internal.a dbms/src/Compression/libclickhouse_compression.a dbms/src/Parsers/libclickhouse_parsers.a contrib/libbtrie/libbtrie.a contrib/poco/Data/ODBC/libPocoDataODBC.a contrib/poco/Data/libPocoData.a contrib/unixodbc-cmake/libunixodbc.a contrib/unixodbc-cmake/libltdl.a contrib/poco/MongoDB/libPocoMongoDB.a /usr/lib/x86_64-linux-gnu/libicui18n.a /usr/lib/x86_64-linux-gnu/libicuuc.a /usr/lib/x86_64-linux-gnu/libicudata.a dbms/src/Dictionaries/Embedded/libclickhouse_dictionaries_embedded.a libs/libmysqlxx/libmysqlxx.a contrib/mariadb-connector-c-cmake/libmysqlclient.a dbms/src/Storages/Kafka/libclickhouse_storage_kafka.a dbms/libclickhouse_common_io.a dbms/src/Common/StringUtils/libstring_utils.a libs/libcommon/libcommon.a contrib/cctz-cmake/libcctz.a contrib/boost-cmake/libboost_filesystem_internal.a contrib/jemalloc-cmake/libjemalloc.a libs/libmemcpy/libmemcpy.a libs/libwidechar_width/libwidechar_width.a libs/libpocoext/libpocoext.a contrib/poco/Net/libPocoNet.a contrib/poco/Util/libPocoUtil.a contrib/poco/Foundation/libPocoFoundation.a contrib/re2/libre2.a contrib/re2_st/libre2_st.a contrib/cityhash102/libcityhash.a contrib/boost-cmake/libboost_system_internal.a libs/libcommon/libapple_rt.a contrib/croaring/libroaring.a contrib/libcpuid/libcpuid.a contrib/poco/Data/libPocoData.a contrib/poco/NetSSL_OpenSSL/libPocoNetSSL.a contrib/poco/Crypto/libPocoCrypto.a contrib/poco/Net/libPocoNet.a contrib/poco/Util/libPocoUtil.a contrib/poco/XML/libPocoXML.a contrib/poco/JSON/libPocoJSON.a contrib/poco/Crypto/libPocoCrypto.a contrib/poco/Foundation/libPocoFoundation.a -lpthread -ldl -lrt contrib/libhdfs3-cmake/libhdfs3.a contrib/libgsasl/liblibgsasl.a contrib/libxml2-cmake/liblibxml2.a contrib/protobuf/cmake/libprotobuf.a contrib/brotli-cmake/libbrotli.a contrib/cppkafka-cmake/libcppkafka.a contrib/librdkafka-cmake/librdkafka.a contrib/ssl/ssl/libssl.a contrib/ssl/crypto/libcrypto.a contrib/arrow-cmake/libparquet_static.a contrib/arrow-cmake/libarrow_static.a contrib/double-conversion/libdouble-conversion.a contrib/zlib-ng/libz.a -pthread contrib/lz4-cmake/liblz4.a contrib/zstd-cmake/libzstd.a contrib/snappy/libsnappy.a contrib/arrow-cmake/libthrift_static.a contrib/boost-cmake/libboost_regex_internal.a /occi_lib/test/instantclient_12_1/libocci.so /occi_lib/test/instantclient_12_1/libclntsh.so -Wl,-rpath,/occi_lib/test/instantclient_12_1: -nodefaultlibs -Wl,-Bstatic -lstdc++ -lgcc_eh -lgcc  -Wl,-Bdynamic -lrt -ldl -lpthread -lm -lc && :
../contrib/boost/boost/system/error_code.hpp:461: error: undefined reference to 'boost::system::system_category()'
../contrib/boost/boost/system/error_code.hpp:491: error: undefined reference to 'boost::system::system_category()'
../contrib/boost/boost/system/error_code.hpp:733: error: undefined reference to 'boost::system::generic_category()'
../contrib/boost/boost/system/error_code.hpp:736: error: undefined reference to 'boost::system::generic_category()'
../contrib/boost/boost/system/error_code.hpp:748: error: undefined reference to 'boost::system::generic_category()'
../contrib/boost/boost/system/error_code.hpp:703: error: undefined reference to 'boost::system::generic_category()'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

I have built a previous version in this environment.
It can be built successfully in a newly installed environment with the same version ubuntu, gcc and cmake.

**Comment by proller** [comment]
Can you try remove libboost-dev and recompile with deletion of build/CMakeCache.txt ?
Or compile with your system boost : `cmake -DUSE_INTERNAL_BOOST_LIBRARY=0`

**Comment by kindred77** [comment]
it works, thanks very much.
