### ISSUE TITLE
CAST and toDateTime accept zero values for month and day

### ISSUE THREAD

**Issue by kmatt** [yandex/ClickHouse#4861]
As zero is not a valid month or day, the engine should raise an exception on invalid dates, but instead returns all zeros (also not a valid date). It appears the JDBC driver converts that zero date to a NULL in some cases.

```sql
SELECT CAST('2019-00-00 00:00:00', 'DateTime')

┌─CAST('2019-00-00 00:00:00', 'DateTime')─┐
│                     0000-00-00 00:00:00 │
└─────────────────────────────────────────┘
```

MySQL also allows this, but it can be the cause of logic corruption if date arithmetic is used.

For comparison in Postgres:

```sql
postgres=# select cast('0000-00-00 00:00:00' as timestamp);
ERROR:  date/time field value out of range: "0000-00-00 00:00:00"
LINE 1: select cast('0000-00-00 00:00:00' as timestamp);

postgres=# select cast('2019-00-00 00:00:00' as timestamp);
ERROR:  date/time field value out of range: "2019-00-00 00:00:00"
LINE 1: select cast('2019-00-00 00:00:00' as timestamp);
                    ^
HINT:  Perhaps you need a different "datestyle" setting.
```

**Comment by alexey-milovidov** [comment]
Where to look in code:
`DateLUTImpl.h`, `makeDayNum` and `makeDateTime` functions.

We can throw an exception for definitely invalid dates/datetimes, but we still accept something like February 31th; 25th hour; 99th minute, etc. This is documented behaviour. Introducing better checks will require careful performance measurements.
