### ISSUE TITLE
How could I use jdbc table function?

### ISSUE THREAD

**Issue by kindred77** [yandex/ClickHouse#4878]
Hi, how could I use jdbc table function?

I got error below when using this function like "SELECT * FROM jdbc('jdbc:mysql://localhost:3306/?user=***&password=***','schema','table')".

Received exception from server (version 19.5.1):
Code: 86. DB::Exception: Received from localhost:7000, 127.0.0.1. DB::Exception: Received error from remote server /columns_info?connection_string=jdbc%3Amysql%3A%2F%2Flocalhost%3A3306%2F%3Fuser%3D***%26password%3D***&schema=schema&table=table. HTTP status code: 500 Internal Server Error, body: Error getting columns from ODBC 'Code: 404, e.displayText() = DB::Exception: ODBC connection string parameter doesn't have value'

The clickhouse-odbc-bridge is running and binding 9019 port.

**Comment by alex-krash** [comment]
@kindred77 , you have to start Java bridge application https://github.com/alex-krash/clickhouse-jdbc-bridge
According to error, you've provided, you are trying to query MySQL via **odbc**-bridge. JDBC-bridge requires standalone Java application with MySQL driver loaded.
