### ISSUE TITLE
ngrambf_v1 index not accessible

### ISSUE THREAD

**Issue by TH-HA** [yandex/ClickHouse#4893]
Hello 

I'm trying to create or alter a table to index of type ngrambf_v1.  But the server refuse the creation of the index  with the following error message : Index type 'ngrambf_v1'. Available index types: set, minmax

**How to reproduce**
just create of alter a table to add an index of type : ngrambf or tokenbf

* Which ClickHouse server version to use

19.4.3.11

* Which interface to use, if matters
HTTP Interface thru TABIX

* Non-default settings, if any
allow_experimental_data_skipping_indices=1

**Expected behavior**
Index of the specified type created.

**Error message and/or stacktrace**
2019.04.03 12:26:29.478866 [ 28 ] {5371c57b-1508-4038-ad3d-c95cbd8983c0} <Error> executeQuery: Code: 80, e.displayText() = DB::Exception: Unknown Index type 'ngrambf_v1'. Available index types: set, minmax (from [::ffff:10.1.30.136]:62140) (in query:  /*TABIX_QUERY_ID_lG85IYRl*/    alter table IPANEMA.FLOW add INDEX src_site_idx (src_site,lower(src_site)) TYPE ngrambf_v1(3, 256, 4, 0) GRANULARITY 4), Stack trace:

0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x6f73536]
1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x22) [0x3712ab2]
2. /usr/bin/clickhouse-server(DB::MergeTreeIndexFactory::get(DB::NamesAndTypesList const&, std::shared_ptr<DB::ASTIndexDeclaration>, DB::Context const&) const+0x485) [0x6735bd5]
3. /usr/bin/clickhouse-server(DB::MergeTreeData::setPrimaryKeyIndicesAndColumns(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::IAST>, DB::ColumnsDescription const&, DB::IndicesDescription const&, bool)+0xb0b) [0x66ebb5b]
4. /usr/bin/clickhouse-server(DB::MergeTreeData::checkAlter(DB::AlterCommands const&, DB::Context const&)+0x845) [0x66efc95]
5. /usr/bin/clickhouse-server(DB::StorageMergeTree::alter(DB::AlterCommands const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context const&)+0xc4) [0x664ab54]
6. /usr/bin/clickhouse-server(DB::InterpreterAlterQuery::execute()+0x647) [0x6a0c8e7]
7. /usr/bin/clickhouse-server() [0x655cb1f]
8. /usr/bin/clickhouse-server(DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>)+0xfa) [0x655e8aa]
9. /usr/bin/clickhouse-server(DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&)+0x35f6) [0x372e1b6]
10. /usr/bin/clickhouse-server(DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)+0x3f1) [0x3730181]
11. /usr/bin/clickhouse-server(Poco::Net::HTTPServerConnection::run()+0x32c) [0x707ceec]
12. /usr/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x7076eef]
13. /usr/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0xe9) [0x7077629]
14. /usr/bin/clickhouse-server(Poco::PooledThread::run()+0x81) [0x712a761]
15. /usr/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x7126928]
16. /usr/bin/clickhouse-server() [0xadef39f]
17. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7ff1ad3a16ba]
18. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7ff1ac9c241d]

Thanks in advance

**Comment by alexey-milovidov** [comment]
The minimum version is `v19.5.1.246` that is available in testing.

**Comment by TH-HA** [comment]
Thanks a lot for your answer. 
A small comment on this part , it may be usefull to avoid such kind of question to put on the actual documentation the clickhouse version on which the documentation apply. I was naively and wrongly  thinking that it was always on the latest stable version. 
Regards

**Comment by alexey-milovidov** [comment]
Yes, this is a frequent complaint. Today, the docs are not in sync with any ClickHouse release.
(For most features, the docs lag behind, but there are some features where docs are prepared in advance.)

We're only going to prepare a better process of docs publishing. I cannot guarantee when it will happen.
