### ISSUE TITLE
should cluster local table create and drop table on each instance ? 

### ISSUE THREAD

**Issue by yunhuizhu** [yandex/ClickHouse#4902]
hello,i see the [ClickHouse deployment to cluster](https://clickhouse.yandex/tutorial.html),find 

> Create local tables on each instance
I want to be able  to create local table on one instance ,other instance automatic to create same local table 。 drop local table on one instance ,other instance automatic to drop same local table 。 someone help me

**Comment by kindred77** [comment]
May be you can use the "on cluster" option.

**Comment by blinkov** [comment]
@yunhuizhu see https://clickhouse.yandex/docs/en/query_language/create/#distributed-ddl-queries-on-cluster-clause

**Comment by blinkov** [comment]
...or maybe https://clickhouse.yandex/docs/zh/query_language/create/#fen-bu-shi-ddlcha-xun-on-cluster-zi-ju given the punctuation you use

**Comment by yunhuizhu** [comment]
@blinkov @kindred77 thanks,we had used old 2017 clickhouse-server,now upgrade the newest clickhouse-server,it is usefull
