### ISSUE TITLE
How to configure data storage for multiple disks ,  like on /data1 and /data2?

### ISSUE THREAD

**Issue by RunningHu** [yandex/ClickHouse#4905]
My server has multiple disks, it is like this:
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2        40G  5.2G   33G  14% /
tmpfs            32G   16K   32G   1% /dev/shm
/dev/sda1       485M   60M  400M  14% /boot
/dev/sda5       392G  375M  372G   1% /data
/dev/sdc1       550G  211G  311G  41% /data1
/dev/sdb1       440G   71M  418G   1% /data2
/dev/sdd1       550G   70M  522G   1% /data3

I want to put datas on /data1 and /data3. This is my /etc/clickhouse-server/config.xml :

    
    <path>/data1/clickhouse/data/,/data3/clickhouse/data/</path>

    
    <tmp_path>/data1/clickhouse/tmp/</tmp_path>

    
    <user_files_path>/data1/clickhouse/user_files/</user_files_path>

But it didn't work,  the data is still only stored on /data1.  Data1's space is not enough.
What should I do ?
How can I divide the data into data1?

**Comment by blinkov** [comment]
This is on roadmap #4786, but for now you should use RAID.

**Comment by RunningHu** [comment]
> This is on roadmap #4786, but for now you should use RAID.
ok,  I got it, thank you.
