### ISSUE TITLE
JSON SELECT вложенные поля

### ISSUE THREAD

**Issue by wormen** [yandex/ClickHouse#4916]
... не нашел в документации
в случае, когда поле в формате JSON/JSONEachRow, как обратиться к вложенным полям явным образом?

например, в MySQL, это выглядит так 

для объектов
SELECT sentence->>"$.mascot" FROM facts;

для масивов
SELECT JSON_EXTRACT('[1, 2, 3, 4, 5]', '$[1 to 3]');

примеры взяты с https://dev.mysql.com/doc/refman/8.0/en/json.html

**Comment by wasaeshoaib** [comment]
take a look at https://clickhouse-docs.readthedocs.io/en/latest/functions/json_functions.html
