### ISSUE TITLE
How does streaming from Kafka engine table work internally?

### ISSUE THREAD

**Issue by simPod** [yandex/ClickHouse#4926]
I'd like to understand what happens when I create 
1. MergeTree Engine table as data storage (A)
2. Kafka Engine table as Kafka consumer (B)
3. Materialized view as stream from B to A

In materialized view I `GROUP BY toDate(datetime_column)`

What does it mean internally. How does it "window" data consumed from Kafka toDate? I guess the consumer tries to consume data ASAP, are they then held in some tmp file so they can be aggregated per day?

Consider first kafka message consumed at 1 am, second message at 11 pm. Those are two messages I want to be grouped into 1 (by toDate()) when inserted into table A. So how does it ClickHouse do for such window like 24h?

**Comment by nvartolomei** [comment]
It works pretty much similar to how MV works on inserted data. The query is applied per each new block.

From MV docs:

> A materialized view is arranged as follows: when inserting data to the table specified in SELECT, part of the inserted data is converted by this SELECT query, and the result is inserted in the view.
>
> A SELECT query can contain DISTINCT, GROUP BY, ORDER BY, LIMIT... Note that the corresponding conversions are performed independently on each block of inserted data. For example, if GROUP BY is set, data is aggregated during insertion, but only within a single packet of inserted data. The data won't be further aggregated. The exception is when using an ENGINE that independently performs data aggregation, such as SummingMergeTree.
> — [SQL Reference &rarr; Create](https://clickhouse.yandex/docs/en/query_language/create/)

From Kafka docs:

> To improve performance, received messages are grouped into blocks the size of max_insert_block_size. If the block wasn't formed within stream_flush_interval_ms milliseconds, the data will be flushed to the table regardless of the completeness of the block.
> — [Table Engines &rarr; Integratiosn &rarr; Kafka](https://clickhouse.yandex/docs/en/operations/table_engines/kafka/)

To answer your last question. You would create a SummingMergeTree or a AggregatingMergeTree table and insert data into that table. The table engine will take care of grouping messages properly.

Kafka Engine documentation has an actual example for your question.

**Comment by simPod** [comment]
Thank you for response, that makes it clear!
