### ISSUE TITLE
DB::Exception: Multiple JOIN expects joined tables.

### ISSUE THREAD

**Issue by den-crane** [yandex/ClickHouse#4929]
CH 19.5.1.246.

select ax,c from (select [1,2,3] ax, 1 c) array join ax all inner join (select 1 c) using(c)
DB::Exception: Multiple JOIN expects joined tables.

set allow_experimental_multiple_joins_emulation = 0
select ax,c from (select [1,2,3] ax, 1 c) array join ax all inner join (select 1 c) using(c)
```
┌─ax─┬─c─┐
│  1 │ 1 │
│  2 │ 1 │
│  3 │ 1 │
└────┴───┘
```

source: t.me/clickhouse_ru/96302

**Comment by 4ertus2** [comment]
#4938

**Comment by 4ertus2** [comment]
fixed in master
