### ISSUE TITLE
question about order by limit  syntax

### ISSUE THREAD

**Issue by peaksnail** [yandex/ClickHouse#4945]
hi, I have a table `goods_stats`  below, there has 32 records

name     total    category 

抽盒纸	37	其它
瓜子	20	其它
怪味胡豆	9	其它
卤豆干	20	卤菜系列
卤荤菜	5	卤菜系列
拌素菜	4	卤菜系列
雪花纯生	507	啤酒类
燕京厚道	180	啤酒类
燕京鲜啤	102	啤酒类
乐堡啤酒	48	啤酒类
望和啤酒	48	啤酒类
爆米花（份）	33	小吃类
微记煮瓜子175g	20	小吃类
友趣爆米花(桶装)	4	小吃类
配送小吃	4	小吃类
老灶花生	1	小吃类
手撕鱿鱼丝80g	1	小吃类
开心果	1	小吃类
川汉子牛肉干108g	1	小吃类
芥末黄瓜	1	小吃类
中果盘	29	果盘类
大果盘	1	果盘类
柠檬水(壶)	1	茶水类
菊花茶(壶)	1	茶水类
王老吉	24	饮料类
百事可乐(瓶装)	2	饮料类
娃哈哈苏打水	2	饮料类
光明酸奶	1	饮料类
果粒橙	1	饮料类
荷花  	2	香烟类
硬中华	2	香烟类
X娇子	1	香烟类

first, when I run sql 
```
select * from goods_stats order by category,total desc limit 0,10
```
I get the results

抽盒纸	37	其它
瓜子	20	其它
怪味胡豆	9	其它
卤豆干	20	卤菜系列
卤荤菜	5	卤菜系列
拌素菜	4	卤菜系列
雪花纯生	507	啤酒类
燕京厚道	180	啤酒类
燕京鲜啤	102	啤酒类
乐堡啤酒	48	啤酒类

second, when I run sql 
```
select * from goods_stats order by category,total  desc limit 10,10
```

I get the results, it skip record `望和啤酒 48	啤酒类`

乐堡啤酒	48	啤酒类
爆米花（份）	33	小吃类
微记煮瓜子175g	20	小吃类
友趣爆米花(桶装)	4	小吃类
配送小吃	4	小吃类
手撕鱿鱼丝80g	1	小吃类
老灶花生	1	小吃类
芥末黄瓜	1	小吃类
川汉子牛肉干108g	1	小吃类
开心果	1	小吃类

In the fact ,the 11th record should be  `望和啤酒	48	啤酒类` when I run the second step

is't a bug or how to explain it?

**Comment by blinkov** [comment]
Are there any writes to this table? If not, could you produce the full script to reproduce this?

**Comment by peaksnail** [comment]
I solve it by adding `order by name,category,total` when I read the  [link](https://www.percona.com/blog/2017/04/07/non-deterministic-order-select-limit/)

the name is uniq, and the categgory/total will be the same value

**Comment by George-A** [comment]
"limit 0 offset 10" working fine

**Comment by alexey-milovidov** [comment]
> "limit 0, 10" working incorrect
"limit 0 offset 10" working fine

Both variants work correct, exactly as expected.

`limit 0, 10` is equivalent to `LIMIT 10 OFFSET 0` or just `LIMIT 10`
`limit 0 offset 10` is equivalent to `LIMIT 10, 0` or just `LIMIT 0`

**Comment by alexey-milovidov** [comment]
> I solve it by adding order by name,category,total when I read the link
the name is uniq, and the categgory/total will be the same value

Yes, this is the answer for this issue.
