### ISSUE TITLE
streaming output

### ISSUE THREAD

**Issue by hwchen** [yandex/ClickHouse#4948]
Hello,

I am trying to stream output to reduce memory usage on large query results. However, I notice that sometimes the result comes back in many blocks, and sometimes in just one large block.

I was wondering if there were some rules for when results were output in smaller blocks or in one large block.

For example, in my data set,
```
$ clickhouse-stream/target/release/clickhouse-stream "select year, geoid, nz, az from (select geoid, geoid as puma from geography) all inner join (select year, nz, puma, az from fact_table limit 1000000) using puma" | ag counts
block counts: 0 rows
block counts: 1000000 rows
```
but adding a group by on all final cols results in blocks of about 300 rows in size (with a total of about 7200 rows):
```
$ clickhouse-stream/target/release/clickhouse-stream "select year, geoid, nz, az from (select geoid, geoid as puma from geography) all inner join (select year, nz, puma, az from fact_table limit 1000000) using puma group by year, geoid, nz, az" | ag counts
```

I had figured that things like ordering or joining would affect whether the output streams. So I was surprised to see in this case that a group by would make it stream again.

Let me know if it's worthwhile for me to create a reproducible example.

I'm using https://github.com/hwchen/clickhouse-stream to inspect the blocks coming to the client. And https://github.com/suharev7/clickhouse-rs as the driver.

**Comment by filimonov** [comment]
ClickHouse use streaming almost everywhere, and distibute the query between threads. 

Every time when thread finished it's part of work it's either passed to the client either passed to another working thread.

Some tasks (like ORDER BY) require to execute final sorting in the single thread so you get the result in one block (from single thread).
Direct data read from table - will read the block by max_block_size (64Kb by default).

For HTTP protocol you can enable server-side buffering.
For console you can use PrettyCompactMonoBlock format instead of default PrettyCompact

**Comment by alexey-milovidov** [comment]
> Some tasks (like ORDER BY) require to execute final sorting in the single thread so you get the result in one block (from single thread).

That's not true.

```
SELECT DISTINCT blockNumber() FROM (SELECT rand() AS x FROM numbers(1000000) ORDER BY rand())
```

**Comment by alexey-milovidov** [comment]
> So I was surprised to see in this case that a group by would make it stream again.

There are two algorithms for group by: single-level and two-level. Or, in other words, single-bucketed and multi-bucketed. ClickHouse automatically switch to two-level algorithm for large results. This algorithm helps with parallel merging of aggregation results from different threads and different servers, allows for aggregation in external memory and helps to save memory in distributed aggregation. But by default it still needs to buffer all intermediate data in memory (just as single-level) algorithm, but outputs it to client one bucket at once. So, the client can read this data in multiple smaller blocks.

**Comment by alexey-milovidov** [comment]
> either passed to the client either passed to another working thread which will countine data processing

Streams of data and threads of execution are independent (orthogonal) concepts in ClickHouse. Multiple data streams can be processed by a single thread and vice-versa.
