### ISSUE TITLE
select last record with where

### ISSUE THREAD

**Issue by gusevartemasd** [yandex/ClickHouse#4955]
I have a few billions rows in table for 4k mutable params and I need to get last values for 500 of them My table is partitioned by day and order by param ids so i need just to find last record with needed id

    SELECT max(time)
    FROM obj_ntgres.param_values_history
    PREWHERE param_id = 4171
work bad: Elapsed: 0.437 sec. Processed 2.56 million rows, 5.21 MB (5.87 million rows/s., 11.92 MB/s.)

    SELECT *
    FROM obj_ntgres.param_values_history
    WHERE param_id = 4171
    ORDER BY time DESC
    LIMIT 1
worse: 1 rows in set. Elapsed: 3.413 sec. Processed 2.56 million rows, 5.45 MB (751.21 thousand rows/s., 1.60 MB/s.)

Table

    CREATE TABLE obj_ntgres.param_values_history (

      time DateTime,

      param_id UInt16,

      param_value Float32,

      param_value_quality Decimal(1, 0),

      msec Decimal(3, 0)

    ) ENGINE = MergeTree PARTITION BY toStartOfDay(time)

    ORDER BY

      param_id SETTINGS index_granularity = 8192
Maybe you have some ideas?

**Comment by nvartolomei** [comment]
Likely duplicate of #1344.

**Comment by nvartolomei** [comment]
I did make a workaround for simple use cases. Add param id to primary key first. Then run a query to group number of rows for a param is by buckets (say 1h bucket). Find last buckets that contain more than limit (500 in your case) records.

Re-run the query with constraint on time that is derived from time buckets and on param_id.

**Comment by gusevartemasd** [comment]
> I did make a workaround for simple use cases. Add time and param id to primary key. Then run a query to group number of rows for a param is by buckets (say 1h bucket). Find last buckets that contain more than limit (500 in your case) records.
> 
> Re-run the query with constraint on time that is derived from time buckets and on param_id.

if trully understand you, it will work if i can find all my params in small timerange , but i have many params second ago and some 3 months ago

**Comment by gusevartemasd** [comment]
Now i'm using Materialized view for my purposes and it looks preaty good

**Comment by filimonov** [comment]
Cross link with SO question https://stackoverflow.com/questions/55608325/clickhouse-select-last-record-without-max-on-all-table/55657641#55657641
