### ISSUE TITLE
Segmentation fault in arrayIntersect

### ISSUE THREAD

**Issue by lmikhailov** [yandex/ClickHouse#4964]
**Describe the bug**
Clickhouse server crashes when arrayIntersect is used in select from table that contains 10 rows with empty arrays and one row with two elements

**How to reproduce**
drop table if exists test_case;

CREATE TABLE test_case (test_arr Array(UInt32)) ENGINE = Log;

insert into test_case values ([]);
insert into test_case values ([]);
insert into test_case values ([]);
insert into test_case values ([]);
insert into test_case values ([]);
insert into test_case values ([]);
insert into test_case values ([]);
insert into test_case values ([]);
insert into test_case values ([]);
insert into test_case values ([105,205]);

select arrayIntersect(test_arr, [101, 102, 103, 104, 105, 106]) from test_case;

Version:
ClickHouse 19.4.2.7 with revision 54416 
CentOS release 6.10 (Final)
Build from Altinity

**Expected behavior**
Query completes successfully with result: [105] , server does not crash.

**Error message and/or stacktrace**
2019.04.10 18:58:43.105061 [ 28 ] {8b9a33bc-b8c5-413f-8738-e62af8cdcd94} <Debug> executeQuery: (from 10.199.30.129:56158) drop table if exists test_case;
2019.04.10 18:58:43.105532 [ 28 ] {8b9a33bc-b8c5-413f-8738-e62af8cdcd94} <Debug> MemoryTracker: Peak memory usage (for query): 121.00 B.
2019.04.10 18:58:43.105571 [ 28 ] {8b9a33bc-b8c5-413f-8738-e62af8cdcd94} <Debug> MemoryTracker: Peak memory usage (total): 121.00 B.
2019.04.10 18:58:43.105597 [ 28 ] {8b9a33bc-b8c5-413f-8738-e62af8cdcd94} <Information> TCPHandler: Processed in 0.001 sec.
2019.04.10 18:58:53.105219 [ 28 ] {6195296a-494c-42c5-8b1a-2ee4121b2c43} <Debug> executeQuery: (from 10.199.30.129:56158) CREATE TABLE test_case (test_arr Array(UInt32)) ENGINE = Log;
2019.04.10 18:58:53.153585 [ 28 ] {6195296a-494c-42c5-8b1a-2ee4121b2c43} <Debug> MemoryTracker: Peak memory usage (for query): 121.00 B.
2019.04.10 18:58:53.153644 [ 28 ] {6195296a-494c-42c5-8b1a-2ee4121b2c43} <Debug> MemoryTracker: Peak memory usage (total): 121.00 B.
2019.04.10 18:58:53.153683 [ 28 ] {6195296a-494c-42c5-8b1a-2ee4121b2c43} <Information> TCPHandler: Processed in 0.049 sec.
2019.04.10 18:58:56.818605 [ 28 ] {fb36f9f5-8b41-424e-bae7-7e8e493822b1} <Debug> executeQuery: (from 10.199.30.129:56158) insert into test_case values
2019.04.10 18:58:56.820106 [ 28 ] {fb36f9f5-8b41-424e-bae7-7e8e493822b1} <Debug> MemoryTracker: Peak memory usage (for query): 6.00 MiB.
2019.04.10 18:58:56.820217 [ 28 ] {fb36f9f5-8b41-424e-bae7-7e8e493822b1} <Debug> MemoryTracker: Peak memory usage (total): 6.00 MiB.
2019.04.10 18:58:56.820260 [ 28 ] {fb36f9f5-8b41-424e-bae7-7e8e493822b1} <Information> TCPHandler: Processed in 0.002 sec.
2019.04.10 18:58:56.821545 [ 28 ] {899bddf1-545a-4600-a91f-a84fa039d725} <Debug> executeQuery: (from 10.199.30.129:56158) insert into test_case values
2019.04.10 18:58:56.822478 [ 28 ] {899bddf1-545a-4600-a91f-a84fa039d725} <Debug> MemoryTracker: Peak memory usage (for query): 6.00 MiB.
2019.04.10 18:58:56.822569 [ 28 ] {899bddf1-545a-4600-a91f-a84fa039d725} <Debug> MemoryTracker: Peak memory usage (total): 6.00 MiB.
2019.04.10 18:58:56.822609 [ 28 ] {899bddf1-545a-4600-a91f-a84fa039d725} <Information> TCPHandler: Processed in 0.001 sec.
2019.04.10 18:58:56.823930 [ 28 ] {aaeeeca7-3057-4c93-9cb7-f00dc2eec899} <Debug> executeQuery: (from 10.199.30.129:56158) insert into test_case values
2019.04.10 18:58:56.824875 [ 28 ] {aaeeeca7-3057-4c93-9cb7-f00dc2eec899} <Debug> MemoryTracker: Peak memory usage (for query): 6.00 MiB.
2019.04.10 18:58:56.824965 [ 28 ] {aaeeeca7-3057-4c93-9cb7-f00dc2eec899} <Debug> MemoryTracker: Peak memory usage (total): 6.00 MiB.
2019.04.10 18:58:56.825005 [ 28 ] {aaeeeca7-3057-4c93-9cb7-f00dc2eec899} <Information> TCPHandler: Processed in 0.001 sec.
2019.04.10 18:58:56.826360 [ 28 ] {59d10bbd-7ee7-4609-985c-91b628efc747} <Debug> executeQuery: (from 10.199.30.129:56158) insert into test_case values
2019.04.10 18:58:56.827261 [ 28 ] {59d10bbd-7ee7-4609-985c-91b628efc747} <Debug> MemoryTracker: Peak memory usage (for query): 6.00 MiB.
2019.04.10 18:58:56.827351 [ 28 ] {59d10bbd-7ee7-4609-985c-91b628efc747} <Debug> MemoryTracker: Peak memory usage (total): 6.00 MiB.
2019.04.10 18:58:56.827392 [ 28 ] {59d10bbd-7ee7-4609-985c-91b628efc747} <Information> TCPHandler: Processed in 0.001 sec.
2019.04.10 18:58:56.828715 [ 28 ] {c17e540b-6bbc-4e8f-9499-75d9377edd51} <Debug> executeQuery: (from 10.199.30.129:56158) insert into test_case values
2019.04.10 18:58:56.829612 [ 28 ] {c17e540b-6bbc-4e8f-9499-75d9377edd51} <Debug> MemoryTracker: Peak memory usage (for query): 6.00 MiB.
2019.04.10 18:58:56.829701 [ 28 ] {c17e540b-6bbc-4e8f-9499-75d9377edd51} <Debug> MemoryTracker: Peak memory usage (total): 6.00 MiB.
2019.04.10 18:58:56.829741 [ 28 ] {c17e540b-6bbc-4e8f-9499-75d9377edd51} <Information> TCPHandler: Processed in 0.001 sec.
2019.04.10 18:58:56.831077 [ 28 ] {043e9029-05df-466b-adc9-fa1ea8b71ed0} <Debug> executeQuery: (from 10.199.30.129:56158) insert into test_case values
2019.04.10 18:58:56.832018 [ 28 ] {043e9029-05df-466b-adc9-fa1ea8b71ed0} <Debug> MemoryTracker: Peak memory usage (for query): 6.00 MiB.
2019.04.10 18:58:56.832110 [ 28 ] {043e9029-05df-466b-adc9-fa1ea8b71ed0} <Debug> MemoryTracker: Peak memory usage (total): 6.00 MiB.
2019.04.10 18:58:56.832154 [ 28 ] {043e9029-05df-466b-adc9-fa1ea8b71ed0} <Information> TCPHandler: Processed in 0.001 sec.
2019.04.10 18:58:56.833455 [ 28 ] {1ae7c6d2-7d9b-467f-98b8-39925f27edf7} <Debug> executeQuery: (from 10.199.30.129:56158) insert into test_case values
2019.04.10 18:58:56.834357 [ 28 ] {1ae7c6d2-7d9b-467f-98b8-39925f27edf7} <Debug> MemoryTracker: Peak memory usage (for query): 6.00 MiB.
2019.04.10 18:58:56.834445 [ 28 ] {1ae7c6d2-7d9b-467f-98b8-39925f27edf7} <Debug> MemoryTracker: Peak memory usage (total): 6.00 MiB.
2019.04.10 18:58:56.834486 [ 28 ] {1ae7c6d2-7d9b-467f-98b8-39925f27edf7} <Information> TCPHandler: Processed in 0.001 sec.
2019.04.10 18:58:56.835811 [ 28 ] {36cd38e5-7f39-4b83-a8f4-6c8260144f9a} <Debug> executeQuery: (from 10.199.30.129:56158) insert into test_case values
2019.04.10 18:58:56.836792 [ 28 ] {36cd38e5-7f39-4b83-a8f4-6c8260144f9a} <Debug> MemoryTracker: Peak memory usage (for query): 6.00 MiB.
2019.04.10 18:58:56.836881 [ 28 ] {36cd38e5-7f39-4b83-a8f4-6c8260144f9a} <Debug> MemoryTracker: Peak memory usage (total): 6.00 MiB.
2019.04.10 18:58:56.836922 [ 28 ] {36cd38e5-7f39-4b83-a8f4-6c8260144f9a} <Information> TCPHandler: Processed in 0.001 sec.
2019.04.10 18:58:56.838284 [ 28 ] {73a10651-813d-41be-8b17-349613f05750} <Debug> executeQuery: (from 10.199.30.129:56158) insert into test_case values
2019.04.10 18:58:56.839148 [ 28 ] {73a10651-813d-41be-8b17-349613f05750} <Debug> MemoryTracker: Peak memory usage (for query): 6.00 MiB.
2019.04.10 18:58:56.839257 [ 28 ] {73a10651-813d-41be-8b17-349613f05750} <Debug> MemoryTracker: Peak memory usage (total): 6.00 MiB.
2019.04.10 18:58:56.839309 [ 28 ] {73a10651-813d-41be-8b17-349613f05750} <Information> TCPHandler: Processed in 0.001 sec.
2019.04.10 18:58:56.840863 [ 28 ] {60f27904-2391-4bc0-a9c5-c519ea37db8d} <Debug> executeQuery: (from 10.199.30.129:56158) insert into test_case values
2019.04.10 18:58:56.841839 [ 28 ] {60f27904-2391-4bc0-a9c5-c519ea37db8d} <Debug> MemoryTracker: Peak memory usage (for query): 6.00 MiB.
2019.04.10 18:58:56.841928 [ 28 ] {60f27904-2391-4bc0-a9c5-c519ea37db8d} <Debug> MemoryTracker: Peak memory usage (total): 6.00 MiB.
2019.04.10 18:58:56.841969 [ 28 ] {60f27904-2391-4bc0-a9c5-c519ea37db8d} <Information> TCPHandler: Processed in 0.001 sec.
2019.04.10 18:58:59.260956 [ 28 ] {6e8c3e4b-460f-4377-a812-bde40145ae8d} <Debug> executeQuery: (from 10.199.30.129:56158) select arrayIntersect(test_arr, [101, 102, 103, 104, 105, 106]) from test_case;
2019.04.10 18:58:59.261834 [ 28 ] {6e8c3e4b-460f-4377-a812-bde40145ae8d} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
2019.04.10 18:58:59.262676 [ 28 ] {6e8c3e4b-460f-4377-a812-bde40145ae8d} <Debug> executeQuery: Query pipeline:
Union
 Expression × 8
  Expression
   Log

2019.04.10 18:58:59.302300 [ 34 ] {} <Error> BaseDaemon: ########################################
2019.04.10 18:58:59.302357 [ 34 ] {} <Error> BaseDaemon: (from thread 26) Received signal Segmentation fault (11).
2019.04.10 18:58:59.302379 [ 34 ] {} <Error> BaseDaemon: Address: 0x7f760c396000
2019.04.10 18:58:59.302398 [ 34 ] {} <Error> BaseDaemon: Access: read.
2019.04.10 18:58:59.302416 [ 34 ] {} <Error> BaseDaemon: Attempted access has violated the permissions assigned to the memory area.
2019.04.10 18:58:59.344715 [ 34 ] {} <Error> BaseDaemon: 0. clickhouse-server(COWPtr<DB::IColumn>::immutable_ptr<DB::IColumn> DB::FunctionArrayIntersect::execute<ClearableHashMap<unsigned char, unsigned long, DefaultHash<unsigned char>, HashTableGrower<9ul>, AllocatorWithStackMemory<Allocator<true>, 512ul> >, DB::ColumnVector<unsigned char>, true>(DB::FunctionArrayIntersect::UnpackedArrays const&, COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn>)+0x283) [0x349d8e3]
2019.04.10 18:58:59.344765 [ 34 ] {} <Error> BaseDaemon: 1. clickhouse-server(void DB::FunctionArrayIntersect::NumberExecutor::operator()<unsigned char, 0ul>()+0x84) [0x349e464]
2019.04.10 18:58:59.344787 [ 34 ] {} <Error> BaseDaemon: 2. clickhouse-server(DB::FunctionArrayIntersect::executeImpl(DB::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long)+0x251) [0x3497691]
2019.04.10 18:58:59.344805 [ 34 ] {} <Error> BaseDaemon: 3. clickhouse-server(DB::PreparedFunctionImpl::execute(DB::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long, bool)+0xa7f) [0x59740ff]
2019.04.10 18:58:59.344836 [ 34 ] {} <Error> BaseDaemon: 4. clickhouse-server(DB::ExpressionAction::execute(DB::Block&, bool) const+0x226) [0x5b078d6]
2019.04.10 18:58:59.344852 [ 34 ] {} <Error> BaseDaemon: 5. clickhouse-server(DB::ExpressionActions::execute(DB::Block&, bool) const+0x6e) [0x5b099ee]
2019.04.10 18:58:59.344868 [ 34 ] {} <Error> BaseDaemon: 6. clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x35) [0x59d65d5]
2019.04.10 18:58:59.344884 [ 34 ] {} <Error> BaseDaemon: 7. clickhouse-server(DB::IBlockInputStream::read()+0x205) [0x5456e95]
2019.04.10 18:58:59.344898 [ 34 ] {} <Error> BaseDaemon: 8. clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x1a) [0x59d65ba]
2019.04.10 18:58:59.344913 [ 34 ] {} <Error> BaseDaemon: 9. clickhouse-server(DB::IBlockInputStream::read()+0x205) [0x5456e95]
2019.04.10 18:58:59.344929 [ 34 ] {} <Error> BaseDaemon: 10. clickhouse-server(DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>::loop(unsigned long)+0x101) [0x5585491]
2019.04.10 18:58:59.344946 [ 34 ] {} <Error> BaseDaemon: 11. clickhouse-server(DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>::thread(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long)+0x1fb) [0x55859eb]
2019.04.10 18:58:59.344989 [ 34 ] {} <Error> BaseDaemon: 12. clickhouse-server(ThreadFromGlobalPool::ThreadFromGlobalPool<DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>::process()::{lambda()#1}>(DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>::process()::{lambda()#1}&&)::{lambda()#1}::operator()() const+0x58) [0x5585e48]
2019.04.10 18:58:59.345009 [ 34 ] {} <Error> BaseDaemon: 13. clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x199) [0x5e9c719]
2019.04.10 18:58:59.345023 [ 34 ] {} <Error> BaseDaemon: 14. clickhouse-server() [0x6736d4f]
2019.04.10 18:58:59.345041 [ 34 ] {} <Error> BaseDaemon: 15. /lib64/libpthread.so.0() [0x3626407aa1]
2019.04.10 18:58:59.345060 [ 34 ] {} <Error> BaseDaemon: ########################################
2019.04.10 18:58:59.345075 [ 34 ] {} <Error> BaseDaemon: (from thread 29) Received signal Segmentation fault (11).
2019.04.10 18:58:59.345087 [ 34 ] {} <Error> BaseDaemon: Address: 0x7f760c396000
2019.04.10 18:58:59.345098 [ 34 ] {} <Error> BaseDaemon: Access: read.
2019.04.10 18:58:59.345110 [ 34 ] {} <Error> BaseDaemon: Attempted access has violated the permissions assigned to the memory area.
2019.04.10 18:58:59.379948 [ 34 ] {} <Error> BaseDaemon: 0. clickhouse-server(COWPtr<DB::IColumn>::immutable_ptr<DB::IColumn> DB::FunctionArrayIntersect::execute<ClearableHashMap<unsigned char, unsigned long, DefaultHash<unsigned char>, HashTableGrower<9ul>, AllocatorWithStackMemory<Allocator<true>, 512ul> >, DB::ColumnVector<unsigned char>, true>(DB::FunctionArrayIntersect::UnpackedArrays const&, COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn>)+0x283) [0x349d8e3]
2019.04.10 18:58:59.379983 [ 34 ] {} <Error> BaseDaemon: 1. clickhouse-server(void DB::FunctionArrayIntersect::NumberExecutor::operator()<unsigned char, 0ul>()+0x84) [0x349e464]
2019.04.10 18:58:59.380002 [ 34 ] {} <Error> BaseDaemon: 2. clickhouse-server(DB::FunctionArrayIntersect::executeImpl(DB::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long)+0x251) [0x3497691]
2019.04.10 18:58:59.380019 [ 34 ] {} <Error> BaseDaemon: 3. clickhouse-server(DB::PreparedFunctionImpl::execute(DB::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long, bool)+0xa7f) [0x59740ff]
2019.04.10 18:58:59.380041 [ 34 ] {} <Error> BaseDaemon: 4. clickhouse-server(DB::ExpressionAction::execute(DB::Block&, bool) const+0x226) [0x5b078d6]
2019.04.10 18:58:59.380059 [ 34 ] {} <Error> BaseDaemon: 5. clickhouse-server(DB::ExpressionActions::execute(DB::Block&, bool) const+0x6e) [0x5b099ee]
2019.04.10 18:58:59.380075 [ 34 ] {} <Error> BaseDaemon: 6. clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x35) [0x59d65d5]
2019.04.10 18:58:59.380096 [ 34 ] {} <Error> BaseDaemon: 7. clickhouse-server(DB::IBlockInputStream::read()+0x205) [0x5456e95]
2019.04.10 18:58:59.380111 [ 34 ] {} <Error> BaseDaemon: 8. clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x1a) [0x59d65ba]
2019.04.10 18:58:59.380126 [ 34 ] {} <Error> BaseDaemon: 9. clickhouse-server(DB::IBlockInputStream::read()+0x205) [0x5456e95]
2019.04.10 18:58:59.380141 [ 34 ] {} <Error> BaseDaemon: 10. clickhouse-server(DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>::loop(unsigned long)+0x101) [0x5585491]
2019.04.10 18:58:59.380158 [ 34 ] {} <Error> BaseDaemon: 11. clickhouse-server(DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>::thread(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long)+0x1fb) [0x55859eb]
2019.04.10 18:58:59.380181 [ 34 ] {} <Error> BaseDaemon: 12. clickhouse-server(ThreadFromGlobalPool::ThreadFromGlobalPool<DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>::process()::{lambda()#1}>(DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>::process()::{lambda()#1}&&)::{lambda()#1}::operator()() const+0x58) [0x5585e48]
2019.04.10 18:58:59.380199 [ 34 ] {} <Error> BaseDaemon: 13. clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x199) [0x5e9c719]
2019.04.10 18:58:59.380217 [ 34 ] {} <Error> BaseDaemon: 14. clickhouse-server() [0x6736d4f]
2019.04.10 18:58:59.380230 [ 34 ] {} <Error> BaseDaemon: 15. /lib64/libpthread.so.0() [0x3626407aa1]

**Comment by lmikhailov** [comment]
Stack trace in #4843  looks different from this one.

**Comment by alesapin** [comment]
Cannot reproduce on official ubuntu 19.4.2.7 build:
```
:) select arrayIntersect(test_arr, [101, 102, 103, 104, 105, 106]) from test_case;

SELECT arrayIntersect(test_arr, [101, 102, 103, 104, 105, 106])
FROM test_case 

┌─arrayIntersect(test_arr, [101, 102, 103, 104, 105, 106])─┐
│ []                                                       │
└──────────────────────────────────────────────────────────┘
┌─arrayIntersect(test_arr, [101, 102, 103, 104, 105, 106])─┐
│ []                                                       │
└──────────────────────────────────────────────────────────┘
┌─arrayIntersect(test_arr, [101, 102, 103, 104, 105, 106])─┐
│ []                                                       │
└──────────────────────────────────────────────────────────┘
┌─arrayIntersect(test_arr, [101, 102, 103, 104, 105, 106])─┐
│ []                                                       │
└──────────────────────────────────────────────────────────┘
┌─arrayIntersect(test_arr, [101, 102, 103, 104, 105, 106])─┐
│ []                                                       │
└──────────────────────────────────────────────────────────┘
┌─arrayIntersect(test_arr, [101, 102, 103, 104, 105, 106])─┐
│ []                                                       │
└──────────────────────────────────────────────────────────┘
┌─arrayIntersect(test_arr, [101, 102, 103, 104, 105, 106])─┐
│ [105]                                                    │
└──────────────────────────────────────────────────────────┘
┌─arrayIntersect(test_arr, [101, 102, 103, 104, 105, 106])─┐
│ []                                                       │
└──────────────────────────────────────────────────────────┘
┌─arrayIntersect(test_arr, [101, 102, 103, 104, 105, 106])─┐
│ []                                                       │
└──────────────────────────────────────────────────────────┘
┌─arrayIntersect(test_arr, [101, 102, 103, 104, 105, 106])─┐
│ []                                                       │
└──────────────────────────────────────────────────────────┘

10 rows in set. Elapsed: 0.003 sec. 

```

**Comment by alesapin** [comment]
Also cannot reproduce on Altinity 19.4.3.11:
```
:) select arrayIntersect(test_arr, [101, 102, 103, 104, 105, 106]) from test_case;

SELECT arrayIntersect(test_arr, [101, 102, 103, 104, 105, 106])
FROM test_case 

┌─arrayIntersect(test_arr, [101, 102, 103, 104, 105, 106])─┐
│ []                                                       │
└──────────────────────────────────────────────────────────┘
┌─arrayIntersect(test_arr, [101, 102, 103, 104, 105, 106])─┐
│ []                                                       │
└──────────────────────────────────────────────────────────┘
┌─arrayIntersect(test_arr, [101, 102, 103, 104, 105, 106])─┐
│ []                                                       │
└──────────────────────────────────────────────────────────┘
┌─arrayIntersect(test_arr, [101, 102, 103, 104, 105, 106])─┐
│ []                                                       │
└──────────────────────────────────────────────────────────┘
┌─arrayIntersect(test_arr, [101, 102, 103, 104, 105, 106])─┐
│ []                                                       │
└──────────────────────────────────────────────────────────┘
┌─arrayIntersect(test_arr, [101, 102, 103, 104, 105, 106])─┐
│ []                                                       │
└──────────────────────────────────────────────────────────┘
┌─arrayIntersect(test_arr, [101, 102, 103, 104, 105, 106])─┐
│ []                                                       │
└──────────────────────────────────────────────────────────┘
┌─arrayIntersect(test_arr, [101, 102, 103, 104, 105, 106])─┐
│ []                                                       │
└──────────────────────────────────────────────────────────┘
┌─arrayIntersect(test_arr, [101, 102, 103, 104, 105, 106])─┐
│ []                                                       │
└──────────────────────────────────────────────────────────┘
┌─arrayIntersect(test_arr, [101, 102, 103, 104, 105, 106])─┐
│ [105]                                                    │
└──────────────────────────────────────────────────────────┘

```
