### ISSUE TITLE
Replica stuck with master's wrong IP despite DNS disabled and manually flushed

### ISSUE THREAD

**Issue by andrei-dascalu** [yandex/ClickHouse#4970]
Hello,

I am having a strange issue with Clickhouse that's mostly annoying than anything though I suspect it may (over time) lead to more serious issues.

My setup:
Using dockerised ClickHouse, 19.3 (latest 19.3, always pulling it) in Kubernetes. Internal DNS cache disabled, keep alive timeout 7s. 2 ReplicatedMergeTree tables.

What's happening is that on the slave node I have 8 entries in replication queue that show one of 2 errors (it's always 8 items, never growing at the moment):
`Poco::Exception. Code: 1000, e.code() = 113, e.displayText() = Net Exception: No route to host`
`Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: 10.8.6.15:9009`

What has happened is that at one time or another, one of the nodes was killed for exceeding memory and was recreated. The other node became master and the killed node rejoined as slave. In good Kubernetes fashion, it also got a new IP so somewhere along the way the other node lost connection and also somehow the old IP is still recorded.

Now, I've manually ran the query to flush DNS from both nodes. At one time I manually added the nodes to each other's host file under correct IP.

My questions:

What can I do to either help the queue along or just flush it? 
Why can't the new slave reach the master anymore? It obviously can, otherwise the queue would have become huge by now (in the past I had a similar situation except the queue grew to over 10k rows over a day).
Where is the wrong IP still cached? I suspect ZK, but I'm not sure where or how I could intervene to correct it.

Thanks

**Comment by wasaeshoaib** [comment]
Hi @andrei-dascalu,
The IPs are stored in the **system.clusters** table. You cannot update this table. I faced the same issue and even restarting the clickhouse server didn't solve the issue. I had to restart the instance to get this data refreshed.

Regards

**Comment by filimonov** [comment]
Does `system flush dns` query helps?

**Comment by filimonov** [comment]
Probably related #3882

**Comment by andrei-dascalu** [comment]
@filimonov thanks for looking into my question. Unfortunately the `SYSTEM DROP DNS CACHE` query didn't seem to do much. Are you referring to this query or is `SYSTEM FLUSH DNS` a different query?

**Comment by andrei-dascalu** [comment]
@wasaeshoaib THanks for the tip. I looked in clusters table, but the data store there is correct and used for communicating on port 9000, whereas my issue happens when communication is sought on port 9009 ... I think that is cached in ZK ?

**Comment by den-crane** [comment]
>Timeout: connect timed out: 10.8.6.15:9009

Replicas store in ZK information about themselves using hostname (hostname -f / interserver_http_host).
/clickhouse/tables/01-08/visits/replicas/host == **example01-08-1.yandex.ru**

I would check disable_internal_dns_cache parameter and that Kubernetes/nslookup resolves to a new ip address.

**Comment by andrei-dascalu** [comment]
@den-crane see initial post, disable_internal_dns_cache is disabled.

`<disable_internal_dns_cache>1</disable_internal_dns_cache>`

same line appears commended out in the default config.xml and I have it as part of a file config.d

**Comment by filimonov** [comment]
> @filimonov thanks for looking into my question. Unfortunately the `SYSTEM DROP DNS CACHE` query didn't seem to do much. Are you referring to this query?

Yes. 

So once again:
1) pod was recreated
2) ip changed
3) replication stuck, and SYSTEM DROP DNS CACHE doesn't help

Did I understand that correctly?

Questions:
1) what do you see in zookeeper:
```
SELECT * FROM system.zookeeper WHERE path='/clickhouse/<path_to_table>/replicas' 
```
and in 
```
SELECT * FROM system.zookeeper WHERE path='/clickhouse/<path_to_table>/replicas/<PROBLEMATIC_REPLICA_NAME>' 
```

2) Do you access pods directly or via Service?
3) Do you use interserver_host_name?

**Comment by andrei-dascalu** [comment]
@filimonov Unfortunately in the meantime the cluster where this persistent problem happened was removed as we had to replace it to get things going. However, I will try to reconstruct it on a smaller scale as the issue happened virtually every time when running in Kubernetes and I will investigate a bit further. It's been fairly easy to replicate the issue.

Regarding the sequence of events, you are correct. One pod recreated, ip changed, replication stuck.

> what do you see in zookeeper: `SELECT * FROM system.zookeeper WHERE path='/clickhouse/<path_to_table>/replicas' `

I will try to reproduce issue in a new cluster and come back on that.

> Do you access pods directly or via Service?

Via service but both replicas of the single shard we had were behind one service (not one service per replica, which was the suggested workaround I read in another ticket)

> Do you use interserver_host_name?

No

**Comment by den-crane** [comment]
related to https://github.com/yandex/ClickHouse/issues/5101 interserver_http_host helped

**Comment by abraithwaite** [comment]
Following up on this: are the replication connection pools recycled when calling `system flush dns cache`?

https://github.com/yandex/ClickHouse/blob/8814e0cda578806d2f159f2d0cbcdae11a2d6744/dbms/src/IO/HTTPCommon.cpp#L96-L166

**Comment by andrei-dascalu** [comment]
@abraithwaite hi, unfortunately no, `system flush dns cache` didn't help in the original issue.

**Comment by alesapin** [comment]
https://github.com/yandex/ClickHouse/pull/5534 fix
