### ISSUE TITLE
Is there a way to allocate more resources to the merge operation?

### ISSUE THREAD

**Issue by wasaeshoaib** [yandex/ClickHouse#4977]
Hi,
I have a clickhouse cluster setup with distribution and replication. I have a backup node which has replicas of all the shards in the cluster. I am getting the following errors only on my backup node

 <Error> executeQuery: Code: 252, e.displayText() = DB::Exception: Too many parts (304). Merges are processing significantly slower than inserts.

My backup node is not serving any queries so I can allocate more resources to the merge process. Is there a configuration to do that?

Regards

**Comment by den-crane** [comment]
https://github.com/yandex/ClickHouse/issues/3174#issuecomment-423074171

https://github.com/yandex/ClickHouse/issues/2811#issuecomment-414464589

**Comment by wasaeshoaib** [comment]
Thanks @den-crane
