### ISSUE TITLE
arrayEnumerateDense documentation/function is incorrect

### ISSUE THREAD

**Issue by ninePebbles** [yandex/ClickHouse#4999]
Hi,

according to[ [1]]( https://clickhouse.yandex/docs/en/query_language/functions/array_functions/#arrayenumeratedense-arr) , function arrayEnumerateDense  "_returns an array of the same size as the source array, indicating where each element first appears in the source array. **For example: arrayEnumerateDense([10,20,10,30]) = [1,2,1,4]**_".

The example in the documentation is correct according to the explanation given. However, if I run the example, I get a different result (ClickHouse server version 19.4.3 revision 54416):

```
SELECT arrayEnumerateDense([10, 20, 10, 30])

┌─arrayEnumerateDense([10, 20, 10, 30])─┐
│ [1,2,1,3]                             │
└───────────────────────────────────────┘

```

I see the utility of the result (the order of appearance). In fact, this is what I was looking for. However, I am afraid that the function might be changed in the future.

Is this the case or can I assume that the documentation will be changed instead? 

Thanks a lot! :)

[1] https://clickhouse.yandex/docs/en/query_language/functions/array_functions/#arrayenumeratedense-arr (retrieved 20190412)

**Comment by ogorbacheva** [comment]
@ninePebbles, thanks!
