### ISSUE TITLE
jdbc driver

### ISSUE THREAD

**Issue by bseng** [yandex/ClickHouse#50]
I've read that jdbc driver will be open source later, when will it be ready and where will the code go?

Thanks.

**Comment by alexey-milovidov** [comment]
> I've read that jdbc driver will be open source later

Right.

> when will it be ready

I expect it in this week or next.

> where will the code go

Here: https://github.com/yandex
In separate repository with name like 'clickhouse-jdbc'.

**Comment by bseng** [comment]
Thanks.

**Comment by alexey-milovidov** [comment]
Published at https://github.com/yandex/clickhouse-jdbc
