### ISSUE TITLE
Error encountred after upgrade from 18.14.19 to 19.4.3.11

### ISSUE THREAD

**Issue by EvgenyVinogradov** [yandex/ClickHouse#5005]

**Comment by EvgenyVinogradov** [comment]
After upgrade error encountered in log-file. Ports listening not yet started.
 Error :

**Comment by EvgenyVinogradov** [comment]
2019.04.15 09:11:46.010647 [ 16 ] {} <Error> pmp.pmp (StorageReplicatedMergeTree): DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeT
ree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Null pointer: _pInstance in file "../contrib/poco/Util/include/Poco/Util/Applicat
ion.h", line 457
[clickhouse-server.log.gz](https://github.com/yandex/ClickHouse/files/3079403/clickhouse-server.log.gz)

**Comment by EvgenyVinogradov** [comment]
Additional log (error
[clickhouse-server.err.log.gz](https://github.com/yandex/ClickHouse/files/3079437/clickhouse-server.err.log.gz)
) attaching

**Comment by EvgenyVinogradov** [comment]
After downgrading to v.19.1.16.79 clickhouse started w/o errors but I cant connect via clickhouse-client, it's hangs on :

**Comment by EvgenyVinogradov** [comment]
After downgrading to 18.16.0 revision 54412 server started properly and accept connections via local clickhouse-client and JDBC(HTTP)

**Comment by filimonov** [comment]
It looks like there were few dictionary issues (looks like you solved them successfully), and later issue with one of the tables:
```
2019.04.15 09:03:14.333885 [ 1 ] {} <Error> Application: Caught exception while loading metadata: Code: 132, e.displayText() = DB::Exception: Cannot create table from metadata file /var/lib/clickhouse/metadata/rator//diameter_cdr.sql, error: DB::Exception: The local set of parts of table rator.diameter_cdr doesn't look like the set of parts in ZooKeeper: 338.73 million rows of 338.73 million total rows in filesystem are suspicious. There are 298 unexpected parts with 338734913 rows (209 of them is not just-written with 338734913 rows), 0 unexpectedly merged parts with 0 rows, 0 missing obsolete parts (with 0 blocks), 0 missing parts (with 0 blocks)., stack trace:
```
As i understand that exception was not properly handled, it leads to global context destruction, and that lead to all later errors. 

I will close that issue in preference to a bit clearer #5257 describing the same issue (not properly handled exception during metadata reading)
