### ISSUE TITLE
Protobuf messages are corrupted or doesn't match the provided schema

### ISSUE THREAD

**Issue by simPod** [yandex/ClickHouse#5010]
```
<Error> void DB::StorageKafka::streamThread(): Code: 444, e.displayText() = DB::Exception: Protobuf messages are corrupted or doesn't match the provided schema, Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x6f73536]
1. clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x22) [0x3712ab2]
2. clickhouse-server() [0x6aac6ad]
3. clickhouse-server(DB::ProtobufReader::SimpleReader::ignoreGroup()+0xb6) [0x6aad3b6]
4. clickhouse-server(DB::ProtobufReader::SimpleReader::readFieldNumber(unsigned int&)+0x205) [0x6aad785]
5. clickhouse-server(DB::ProtobufReader::readColumnIndex(unsigned long&)+0x3f) [0x6aae03f]
6. clickhouse-server(DB::ProtobufRowInputStream::read(std::vector<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::RowReadExtension&)+0xd4) [0x680c974]
7. clickhouse-server(DB::BlockInputStreamFromRowInputStream::readImpl()+0x15c) [0x6a97a6c]
8. clickhouse-server(DB::IBlockInputStream::read()+0x178) [0x62edae8]
9. clickhouse-server(DB::KafkaBlockInputStream::readImpl()+0x28) [0x6f53878]
10. clickhouse-server(DB::IBlockInputStream::read()+0x178) [0x62edae8]
11. clickhouse-server(DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::atomic<bool>*)+0x6b) [0x630926b]
12. clickhouse-server(DB::StorageKafka::streamToViews()+0x5cd) [0x6f4cb6d]
13. clickhouse-server(DB::StorageKafka::streamThread()+0x1a8) [0x6f4d128]
14. clickhouse-server(DB::BackgroundSchedulePool::TaskInfo::execute()+0xfa) [0x68732fa]
15. clickhouse-server(DB::BackgroundSchedulePool::threadFunction()+0x62) [0x68739c2]
16. clickhouse-server() [0x6873a39]
17. clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1ab) [0x6f794cb]
18. clickhouse-server() [0xadef39f]
19. /lib/x86_64-linux-gnu/libpthread.so.0(+0x74a4) [0x7f82b97064a4]
20. /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f82b8d38d0f]
```

I'm getting this error when trying to consume protobuf messages. I defined my schema as mentioned here https://github.com/yandex/ClickHouse/issues/4744#issuecomment-478280745

To test that messages are not corrupted, I wrote simple java consumer that consumes the messages from the topic correctly so the content of kafka topic seems to be fine.

I even tried to define the message.proto with package as:

```proto
syntax = "proto3";

package com.domain.package.name;

message Message {
...
```
```kafka_schema = 'message:com.domain.package.name.Message'```
but also tried this

```proto
syntax = "proto3";

message Message {
```
```kafka_schema = 'message:Message'```

message.proto has been chowned by `clickhouse:clickhouse`, I suppose there's no need for delimiter.

My serializer basically looks like this 
```java
    @Override
    public byte[] serialize(String topic, MessageType data) {
        return data.toByteArray();
    }
``` 
so it's pretty smple and I'm using official google's protobuf package so I guess the error neither won't be there.

```sql
ENGINE = Kafka 
SETTINGS
    kafka_broker_list = 'localhost:9092',
    kafka_topic_list = 'messages.processed',
    kafka_group_name = 'clickhouse',
    kafka_format = 'Protobuf',
    kafka_schema = 'message:Message',
    kafka_num_consumers = 1
```

Any idea? I don't know, how to debug this TBH. In error log there's no more info.

**Comment by simPod** [comment]
Just created MVP with https://github.com/yandex/ClickHouse/blob/master/dbms/tests/integration/test_format_schema_on_server/clickhouse_path/format_schemas/simple.proto and I can select those messages. Will try to investigate, probably something specific about my message.

**Comment by simPod** [comment]
Something is wrong

![image](https://user-images.githubusercontent.com/327717/56162018-4f015d00-5fcb-11e9-9090-7d4178d4bf8f.png)

On the left is output of `SELECT * FROM kafka_table`.   
On the right is output from simple java consumer with protobuf decoder.

I'm using this schema:

```proto
message KeyValuePair {
    uint64 key = 1;
}
```

And producing like this:

```java
    @Override
    public byte[] serialize(String topic, T t) {
        KeyValuePair.Builder message = KeyValuePair.newBuilder();
        message.setKey(10000);

        return message.build().toByteArray();
```

You can see I'm setting value `10000` to all messages. ClickHouse however also somehow found 0es there 🤔 Maybe this is another bug but it's difficult to debug the original one.

**Comment by vitlibar** [comment]
> And producing like this:
> 
> ```java
>     @Override
>     public byte[] serialize(String topic, T t) {
>         KeyValuePair.Builder message = KeyValuePair.newBuilder();
>         message.setKey(10000);
> 
>         return message.build().toByteArray();
> ```

ClickHouse expects protobuf-messages to be [length-delimited](https://cwiki.apache.org/confluence/display/GEODE/Delimiting+Protobuf+Messages), i.e. before every message should be written its length as a varint.

The method [toByteArray()](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/AbstractMessageLite.html#toByteArray--) serializes a protobuf message without this varint before it. Seems the method [writeDelimitedTo()](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/AbstractMessageLite.html#writeDelimitedTo-java.io.OutputStream-) will help.

**Comment by simPod** [comment]
@vitlibar you're absolutely right, thanks!

**Comment by simPod** [comment]
for anyone interested

```java
public class ProtoSerializer<T> implements Serializer<T> {
    @Override
    public void configure(Map<String, ?> map, boolean b) {

    }

    @Override
    public byte[] serialize(String topic, T t) {
        Message message = (Message) t;
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        try {
            message.writeDelimitedTo(outputStream);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        return outputStream.toByteArray();

    }

    @Override
    public void close() {
    }
}
```
