### ISSUE TITLE
lz4 upgrade in contrib

### ISSUE THREAD

**Issue by citrin** [yandex/ClickHouse#5013]
Please consider upgrading lz4 in contrib to the latest release (1.8.3). Version 1.8.2 have seen substantial performance improvement and ClickHouse probably can benefit from it.

**Comment by llchan** [comment]
I was about to file a very similar issue for lz4 [v1.9.0](https://github.com/lz4/lz4/releases/tag/v1.9.0), which coincidentally came out a few hours after your request :)

In any case, +1 to bumping the vendored lz4 for the new performance improvements.

**Comment by 4ertus2** [comment]
#5040

**Comment by alexey-milovidov** [comment]
We are using our own decompression loop that is significantly faster than in LZ4:

https://github.com/yandex/ClickHouse/blob/master/dbms/src/Compression/LZ4_decompress_faster.h
https://github.com/yandex/ClickHouse/blob/master/dbms/src/Compression/LZ4_decompress_faster.cpp

Yann Collett is aware of our improvements.

**Comment by alexey-milovidov** [comment]
Nevertheless, LZ4 should be upgraded to latest.

**Comment by alexey-milovidov** [comment]
Video (in russian): https://www.youtube.com/watch?v=V2CqQBICt7M
Presentation (in russian): https://yandex.github.io/clickhouse-presentations/highload_siberia_2018/#

**Comment by llchan** [comment]
Very interesting, didn't know clickhouse had a custom decompressor. What does Yann Collett think? Is there a chance lz4 could eventually include an adaptive decompressor?

**Comment by alexey-milovidov** [comment]
https://github.com/lz4/lz4/commit/219abab74bf8914d3f8761db5b398103cbbd77d7#commitcomment-27520069

**Comment by alexey-milovidov** [comment]
@danlark1 has found additional ASan report (in addition to https://github.com/lz4/lz4/issues/676) in internal Yandex CI (tests across all Yandex codebase). It will be reported.

(`LZ4_wildCopy32` read 16 bytes after end of buffer)

**Comment by danlark1** [comment]
We tested a bit new LZ4 and it turned out to be slightly faster than our own implementation. We will investigate more and maybe update LZ4 with referenced implementation

**Comment by alexey-milovidov** [comment]
Happy enough, there are two totally different ways to improve performance. There is a chance that we can combine both.

**Comment by danlark1** [comment]
https://github.com/yandex/ClickHouse/pull/5070

**Comment by alexey-milovidov** [comment]
The library was updated.
Mixed with our implementation of decompression loop, it became even faster.

**Comment by alexey-milovidov** [comment]
We've published an article describing all these optimizations in great detail:
https://habr.com/en/company/yandex/blog/457612/

Hope you'll enjoy!
