### ISSUE TITLE
New to Clickhouse - Need tips and clarity about our Clickhouse slow query performance

### ISSUE THREAD

**Issue by bzon** [yandex/ClickHouse#5019]
We have this example schema.

```sql
CREATE TABLE IF NOT EXISTS repl_table (
    date Date DEFAULT toDate(request_time),
    request_time DateTime DEFAULT now(),
    employee_id String,
    org_id String,
) ENGINE=ReplicatedMergeTree('/clickhouse/tables/{shard}/default/repl_table', '{replica}', date, (date, employee_id), 8192);

CREATE TABLE IF NOT EXISTS dist_table AS repl_table
ENGINE = Distributed(cluster_x, default, repl_table , rand());
```

And then we have this example query. Is there something that we can or consider do to speed to get a better performance?

```sql
SELECT COUNT(*) FROM dist_table
WHERE employee_id ='xxxxxxxxx'
AND org_id IN('11111')
AND request_time >= '2019-04-16 00:00:00'
AND request_time <= '2019-04-16 23:59:59
```

The query runs for 3 seconds on average. Without any parameters, it's perfectly fast.

```
┌─COUNT()─┐
│  143164 │
└─────────┘

1 rows in set. Elapsed: 2.952 sec. Processed 39.83 million rows, 2.35 GB (13.49 million rows/s., 795.10 MB/s.)
```

**Comment by 4ertus2** [comment]
Your partitioning is by date, but your request is on request_time that is nor in partition key nor in order key. So it's a full scan with filter on second column in order by key. It cannot be fast.

**Comment by bzon** [comment]
@4ertus2  I managed to get it working fast by including the partitioning key in the query.

```sql
SELECT COUNT(*) FROM dist_table
WHERE employee_id ='xxxxxxxxx'
AND date BETWEEN '2019-04-16' AND  '2019-04-16' 
AND org_id IN('11111')
AND request_time BETWEEN '2019-04-16 00:00:00' AND  '2019-04-16 23:59:59'
```

**Comment by alexey-milovidov** [comment]
1. Your order key should be `(org_id, request_time)` instead of `(date, employee_id)`.

2. Change 
```
employee_id String,
org_id String,
```
to
```
employee_id LowCardinality(String),
org_id LowCardinality(String),
```

**Comment by bzon** [comment]
@alexey-milovidov thanks for the answers! 🎉 

Sorry but I want to be enlightened about the following:

* Why do we have to ORDER BY **org_id** instead of **employee_id**? In our case, **org_id** has a lower cardinality than **employeed_id**. Is that why you recommended it?
* What's the benefit of using **LowCardinality()** over a normal **string**?
* Now that we already have a table with my mentioned settings running in production, what is the best practice to change the current table settings?
