### ISSUE TITLE
Clickhouse working slow 

### ISSUE THREAD

**Issue by KrunalT** [yandex/ClickHouse#5022]
Q.1 > If I will do 10000 insert query in a single batch so that will consider as a single query or multiple queries?

Q.2 > In my current application I am facing an issue that **insertion and SELECT** at same time and in that I found merging working in the backend, So I am facing **slowness from retrieving data** from clickhouse and **utilization goes up to 90-95 %**. So for this, any solution or any option is there to handle this?

**Comment by blinkov** [comment]
@KrunalT you need to put all N rows into single INSERT INTO statement, not N separate INSERT INTO statements with one row each. Aren't you doing the latter?

**Comment by bzon** [comment]
For insert, use a single transaction then run many insert, then commit.

**Comment by KrunalT** [comment]
@4ertus2 
What about this ??

In my current application I am facing an issue that insertion and SELECT at same time and in that I found merging working in the backend, So I am facing slowness from retrieving data from clickhouse and utilization goes up to 90-95 %. So for this, any solution or any option is there to handle this?

**Comment by 4ertus2** [comment]
You need to batch inserts. ClickHouse expects one INSERT statement per second or less. Each of them should contain lots rows of data. If you're inserting your data correctly and face with full hardware utilisation you probably need a better hardware.
