### ISSUE TITLE
How to copy big data  to ClickHouse

### ISSUE THREAD

**Issue by sangli00** [yandex/ClickHouse#503]
I used tpch make 20G data in my OS.
I know used command
 ```
  time clickhouse-client --query="INSERT INTO NATION FORMAT CSV" < some.csv
```
tpch make   data format is |  ,I read document can't find customer define  format .

how to copy this data to ClickHouse?

Thanks....

**Comment by ludv1x** [comment]
Could you provide example of data (or its format description) which you try to load?

**Comment by sangli00** [comment]
1  copy this data to postgres database 
2 copy postgres database from to directory
3 use ClickHouse-client copy to ClickHouse 
Is very trouble

![Uploading 5784F93A-C638-4F3A-A79B-D653845DAFD6.png…]()

**Comment by ludv1x** [comment]
I downloaded Download TPCH_Tools_v2.17.1.zip and loaded data from `customer.tbl.150000`
You just need remove last `|` in each line and replace `|` to `\t`.
After you can import data into ClickHouse using TabSeparated FORMAT.

```
sed 's/|$//g' customer.tbl.150000 | tr "|" "\t" | clickhouse-client -q "INSERT INTO tpc FORMAT TSV"
```

**Comment by sangli00** [comment]
yes, I remove last ```|```
but I can't replace ```|``` to ```\t```

used TabSeparated FORMAT is OK.
Thanks.
