### ISSUE TITLE
An error occurs if you specify only one value in the IN condition with type LowCardinality(String)

### ISSUE THREAD

**Issue by znatashka** [yandex/ClickHouse#5031]
Hi,
**Server version:** 19.5.2.6

An error occurs if you specify only one value in the `IN` condition with type `LowCardinality(String)`,
eg, `select from users where type in ('admin')`

when two values are used in the condition or table is empty everything works

**Error message:** DB::Exception: Set for IN is not created yet (version 19.5.2.6 (official build))

**Comment by alex-zaitsev** [comment]
Easily reproducible test:
`create table test_in (a LowCardinality(String)) Engine = MergeTree order by a;

insert into test_in values ('a');

select * from test_in where a in ('a');


Received exception from server (version 19.5.3):
Code: 49. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Set for IN is not created yet.
`

**Comment by alexey-milovidov** [comment]
Fixed in master.
