### ISSUE TITLE
Clickhouse poor select performance due to inserts & background merges

### ISSUE THREAD

**Issue by KrunalT** [yandex/ClickHouse#5032]
In my current application I am facing an issue that insertion and SELECT at same time and in that I found merging working in the backend, So I am facing slowness from retrieving data from clickhouse and utilization goes up to 90-95 %. So for this, any solution or any option is there to handle this?

**Comment by den-crane** [comment]
1. How many columns in your table?
2. How many rows you insert per day?
3. How many rows you insert per batch?
4. Do you use buffer tables?
5. How many disks (HDD or SSD) in your server?
6. How many CPUs  in your server?

**Comment by filimonov** [comment]
>  So for this, any solution or any option is there to handle this?

I see the following solutions:
1) check if you use clickhouse in a proper use case (using OLAP database for certain scenarios can be ineffective)
2) optimize your schema / usage patterns if possible (follow @den-crane questions)
3) scale cluster vertically / horizontally
4) try to find something faster

Hint: p. 4 can be the most problematic ;)
