### ISSUE TITLE
LowCardinality(String) does not use index with IN operator

### ISSUE THREAD

**Issue by olegkv** [yandex/ClickHouse#5044]
create table test.test1
(
a LowCardinality(String),
b Date
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(b)
ORDER BY (a)

create table test.test2
(
a String,
b Date
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(b)
ORDER BY (a)

insert into test.test1 (a, b)
select top 100000 toString(number), today() from system.numbers

insert into test.test2 (a, b)
select top 100000 toString(number), today() from system.numbers

select count() from test.test1 where a in ('1', '2')

1 rows in set. Elapsed: 0.014 sec. Processed 100.00 thousand rows, 1.72 MB

select count() from test.test2 where a in ('1', '2')

1 rows in set. Elapsed: 0.002 sec. Processed 16.38 thousand rows, 227.55 KB

As you can see, first select processes all rows. If I change "a in ('1', '2')" to "a = '1' or a  = '2'"
it works correctly.

**Comment by blind-oracle** [comment]
I think that was fixed in recent 19.5 release. Close?
