### ISSUE TITLE
timezones for toStartOfHour/FiveMinute/Minute functions do not work

### ISSUE THREAD

**Issue by guseynov-ilyas** [yandex/ClickHouse#505]
This query show that functions toStartOfHour, toStartOfFiveMinute and toStartOfMinute do not work with timezone correctly. But in pair with toString function it works.
See results for Tokyo tz below.
(ClickHouse client version 1.1.54140)
SELECT
    toDateTime(1483210000),
    toStartOfYear(toDateTime(1483210000), 'Europe/Moscow'),
    toStartOfQuarter(toDateTime(1483210000), 'Europe/Moscow'),
    toStartOfMonth(toDateTime(1483210000), 'Europe/Moscow'),
    toStartOfHour(toDateTime(1483210000), 'Europe/Moscow'),
    toStartOfFiveMinute(toDateTime(1483210000), 'Europe/Moscow'),
    toStartOfMinute(toDateTime(1483210000), 'Europe/Moscow'),
    toStartOfYear(toDateTime(1483210000), 'Asia/Tokyo'),
    toStartOfQuarter(toDateTime(1483210000), 'Asia/Tokyo'),
    toStartOfMonth(toDateTime(1483210000), 'Asia/Tokyo'),
    toStartOfHour(toDateTime(1483210000), 'Asia/Tokyo'),
    toStartOfFiveMinute(toDateTime(1483210000), 'Asia/Tokyo'),
    toStartOfMinute(toDateTime(1483210000), 'Asia/Tokyo'),
    toString(toStartOfHour(toDateTime(1483210000), 'Asia/Tokyo'), 'Asia/Tokyo'),
    toString(toStartOfFiveMinute(toDateTime(1483210000), 'Asia/Tokyo'), 'Asia/Tokyo'),
    toString(toStartOfMinute(toDateTime(1483210000), 'Asia/Tokyo'), 'Asia/Tokyo')

Row 1:
──────
toDateTime(1483210000):                                                                2016-12-31 21:46:40
toStartOfYear(toDateTime(1483210000), \'Europe/Moscow\'):                              2016-01-01
toStartOfQuarter(toDateTime(1483210000), \'Europe/Moscow\'):                           2016-10-01
toStartOfMonth(toDateTime(1483210000), \'Europe/Moscow\'):                             2016-12-01
toStartOfHour(toDateTime(1483210000), \'Europe/Moscow\'):                              2016-12-31 21:00:00
toStartOfFiveMinute(toDateTime(1483210000), \'Europe/Moscow\'):                        2016-12-31 21:45:00
toStartOfMinute(toDateTime(1483210000), \'Europe/Moscow\'):                            2016-12-31 21:46:00
toStartOfYear(toDateTime(1483210000), \'Asia/Tokyo\'):                                 2017-01-01
toStartOfQuarter(toDateTime(1483210000), \'Asia/Tokyo\'):                              2017-01-01
toStartOfMonth(toDateTime(1483210000), \'Asia/Tokyo\'):                                2017-01-01
toStartOfHour(toDateTime(1483210000), \'Asia/Tokyo\'):                                 2016-12-31 21:00:00
toStartOfFiveMinute(toDateTime(1483210000), \'Asia/Tokyo\'):                           2016-12-31 21:45:00
toStartOfMinute(toDateTime(1483210000), \'Asia/Tokyo\'):                               2016-12-31 21:46:00
toString(toStartOfHour(toDateTime(1483210000), \'Asia/Tokyo\'), \'Asia/Tokyo\'):       2017-01-01 03:00:00
toString(toStartOfFiveMinute(toDateTime(1483210000), \'Asia/Tokyo\'), \'Asia/Tokyo\'): 2017-01-01 03:45:00
toString(toStartOfMinute(toDateTime(1483210000), \'Asia/Tokyo\'), \'Asia/Tokyo\'):     2017-01-01 03:46:00

**Comment by ztlpn** [comment]
Could you provide expected results and how they differ from what you get?

**Comment by guseynov-ilyas** [comment]
Ok, here's another examples. Seems like toStartOfHour function ignores timezone parameter. 
Eample 1: toStartOfMonth works with tz correctly, but toStartOfHour is not
SELECT
    toStartOfMonth(toDateTime(1483210000), 'Asia/Tokyo'),
    toStartOfHour(toDateTime(1483210000), 'Asia/Tokyo'),
    toString(toStartOfHour(toDateTime(1483210000)), 'Asia/Tokyo')
──────
toStartOfMonth(toDateTime(1483210000), \'Asia/Tokyo\'):          2017-01-01
toStartOfHour(toDateTime(1483210000), \'Asia/Tokyo\'):           2016-12-31 21:00:00
toString(toStartOfHour(toDateTime(1483210000)), \'Asia/Tokyo\'): 2017-01-01 03:00:00

Example 2: toStartOfHour ignores tz
SELECT
    toStartOfHour(toDateTime(1483210000), 'Asia/Tokyo'),
    toStartOfHour(toDateTime(1483210000), 'Europe/Moscow')
──────
toStartOfHour(toDateTime(1483210000), \'Asia/Tokyo\'):    2016-12-31 21:00:00
toStartOfHour(toDateTime(1483210000), \'Europe/Moscow\'): 2016-12-31 21:00:00

Example 3: toString function works with tz correctly
SELECT
    toString(toStartOfHour(toDateTime(1483210000)), 'Asia/Tokyo'),
    toString(toStartOfHour(toDateTime(1483210000)), 'Europe/Moscow')
──────
toString(toStartOfHour(toDateTime(1483210000)), \'Asia/Tokyo\'):    2017-01-01 03:00:00
toString(toStartOfHour(toDateTime(1483210000)), \'Europe/Moscow\'): 2016-12-31 21:00:00

**Comment by ztlpn** [comment]
Results are actually correct in this case. Below are some explanations.

Here is how toStartOf* functions work: they take a moment in time (a DateTime value) and a timezone, round this moment to the start of desired time period _in that timezone_ and return the resulting moment in time (again a DateTime value).

Now, it is important to understand that DateTime values do not carry any timezone information. They are just Unix timestamps. When they are displayed, they are converted into a string using the server timezone (or a timezone passed to toString() function).

Back to your examples. A start of hour in Tokyo is also a start of hour in Moscow and vice versa. So `toStartOfHour(toDateTime(1483210000), 'Asia/Tokyo')` and `toStartOfHour(toDateTime(1483210000), 'Europe/Moscow')` return the same DateTime value (corresponding to Unix timestamp 1483207200) which is then formatted according to your server timezone (which is Europe/Moscow) or a timezone passed to toString().

Timezone passed to toStartOfHour really starts to matter when that timezone has a fractional offset to UTC, say Asia/Kolkata which is UTC+05:30. The result of toStartOfHour would be different in that case (namely, timestamp 1483209040). Unfortunately, ClickHouse doesn't support fractional offsets at the moment, so the result would be incorrect. But that's another story ;)

Hope that helps.

**Comment by guseynov-ilyas** [comment]
Ok, how I can explain this expamle:
SELECT
    toStartOfMonth(toDateTime(1483210000), 'Asia/Tokyo'),
    toStartOfMonth(toDateTime(1483210000), 'Europe/Moscow')\G
──────
toStartOfMonth(toDateTime(1483210000), \'Asia/Tokyo\'):    2017-01-01
toStartOfMonth(toDateTime(1483210000), \'Europe/Moscow\'): 2016-12-01

Seems like toStartOfMonth work with tz parameter.

**Comment by ztlpn** [comment]
While moments when the new hour starts do not differ between Moscow and Tokyo, moments when the new month (as well as new day, new week and new year) starts do differ. So 1483210000 is before 2017-01-01 00:00:00 (local time when the new month starts) in Moscow but after 2017-01-01 00:00:00 in Tokyo. So toStartOfMonth returns different days for Moscow and Tokyo.

Also note that toStartOfMonth returns a Date value and not DateTime value.
