### ISSUE TITLE
Recovery After Complete Data Loss cause disk IO util 100%

### ISSUE THREAD

**Issue by songjiao** [yandex/ClickHouse#5055]
**Use case**
20 (12*8TB Raid10) servers ,  shard6 have two servers s1,s2, s2 crashed and lost all the data. 30TB+ data need to be recover  from s1 that cause s1 disk IO 100% for 4 days. during the recovery query became very slow and cluster tcp connection reached the max limit  and the whole cluster became unavailable  

**Describe the solution you'd like**
Data recovery may cause high disk IO util and network traffic . It's will be better if there is a way to control the recovery speed

**Comment by filimonov** [comment]
Duplicate https://github.com/yandex/ClickHouse/issues/1821
