### ISSUE TITLE
force_index_by_date can't work with primary key 'toDate(toDateTime(dt / 1000))'

### ISSUE THREAD

**Issue by shangshujie365** [yandex/ClickHouse#5059]
**Describe the bug**
force_index_by_date can't work with toDate(toDateTime(dt / 1000))

**How to reproduce**
the unit of our timestamp is 'millisecond', not 'second', so, when we convert it to datetime, we should
/1000 at first, but this let force_index_by_date can't work.

we opened conf 'force_index_by_date', my MergeTree table set 'PARTITION BY toDate(toDateTime(dt / 1000))', but the query
SELECT count() FROM table1 
WHERE toDate(toDateTime(dt / 1000)) = '2019-04-18'
=> DB::Exception: MinMax index by columns (dt) is not used and setting 'force_index_by_date' is set

but

SELECT count()
FROM ks_app_analytics_dev.mwprod_overview_hourly_analysis_realtime_local 
WHERE toDateTime(dt) = '2019-04-19 00:00:00'
can work, although wrong result, no exception

may be this is a bug, CH version: 18.14.13

**Comment by shangshujie365** [comment]
SELECT count() FROM table1
WHERE toDate(toDateTime(dt / toInt32(1000))) = '2019-04-18',
This can work, so, the problem is, CH use the 'biggest' type for input, use 'float' here, not 'int'

**Comment by alexey-milovidov** [comment]
MinMax index of partition key is build on columns participating in expression (`dt`) and not on expression itself (`toDate(toDateTime(dt / 1000))`).

You can write `dt BETWEEN toUInt64(toDateTime(toDate('2019-04-18'))) * 1000 AND toUInt64(toDateTime(toDate('2019-04-19'))) * 1000 - 1`
