### ISSUE TITLE
ClickHouse can't used alias in table join?

### ISSUE THREAD

**Issue by sangli00** [yandex/ClickHouse#506]
eg: 
create table t1(x UInt32,y String) ENGINE = Memory;
create table t2(x UInt32,y String) ENGINE = Memory;

I can't used SQL: select t1.x,t2.y from t1 as t11,t2 as t22
where t11.x = t22.y;

**Comment by ludv1x** [comment]
Yes, table aliases isn't supported yet.
You could manually set aliases for columns of both tables in subqueries, and use these subqueris in JOIN, like [here](https://github.com/yandex/ClickHouse/blob/master/dbms/tests/queries/0_stateless/00057_join_aliases.sql#L1).

**Comment by sangli00** [comment]
But now,ClickHouse is support ```exists```?

**Comment by ludv1x** [comment]
Yes https://clickhouse.yandex/reference_en.html#EXISTS

**Comment by sangli00** [comment]
If i used ClickHouse test TPCH is OK？

**Comment by sangli00** [comment]
could you give me about ClickHouse SQL  diff  ANSI SQL documents?

**Comment by ludv1x** [comment]
> If i used ClickHouse test TPCH is OK？

I am not familiar with TPC-H benchmarks, but it seems that they are designed to test [OLTP](https://en.wikipedia.org/wiki/OLTP) systems.
ClickHouse is [OLAP](https://en.wikipedia.org/wiki/Online_analytical_processing) system.

**Comment by sangli00** [comment]
so,which one is ClickHouse benchmarks?  TPC-H&TPC-DS is test OLAP system .

**Comment by alexey-milovidov** [comment]
Due to unconveniencies of supported JOIN syntax in ClickHouse, it is quite difficult to run TPC-H style benchmark. Most of benchmarks with ClickHouse are using "big flat table" schema. See https://github.com/yandex/ClickHouse/tree/master/doc/example_datasets directory for examples.

**Comment by alexey-milovidov** [comment]
Nevertheless, you could run modified version of TPC-H benchmark, if you rewrite queries and possibly replace most of dimension tables with [external dictionaries](https://clickhouse.yandex/reference_en.html#External%20dictionaries).

**Comment by sangli00** [comment]
@alexey-milovidov 
If i benchmark ClickHouse ,only reference https://github.com/yandex/ClickHouse/tree/master/doc/example_datasets?

 I need compare some MPPDB ,Greenplum&HAWQ&DeepGreen... 
 
Maybe I will test  TB data in ClockHouse,so could you tell me good method?

**Comment by blinkov** [comment]
We collect instructions on how to experiment with example datasets in respective section of documentation: https://clickhouse.yandex/docs/en/getting_started/example_datasets/nyc_taxi/

Various improvements in JOIN syntax are currently in development.
