### ISSUE TITLE
Add a LIMIT and OFFSET keyword for INSERT query

### ISSUE THREAD

**Issue by YiuRULE** [yandex/ClickHouse#5088]
**Use case**
Add a possibility to add a `LIMIT` and possibly an `OFFSET` keyword. The `LIMIT` keyword will limit the number of rows inserted with a query while the `OFFSET` will be from which rows we should begin with.

**Describe the solution you'd like**
```
$ clickhouse client --query "CREATE TABLE test (a UInt8) Engine = Memory;"

$ seq 1 20 | clickhouse client --query "INSERT INTO test FORMAT CSV  LIMIT 10 OFFSET 5"

$ clickhouse client --query "SELECT a FROM test"
6
7
8
9
10
11
12
13
14
15
```

**Additional context**
This feature can be quite useful when a client need to deal directly with files without doing a pre-processing.

**Comment by alexey-milovidov** [comment]
We have a different feature in plan that will cover your needs.
It looks like this:
```
INSERT INTO test SELECT * FROM input(CSV, 'a UInt8') LIMIT 10 OFFSET 5
```

**Comment by YiuRULE** [comment]
Ok thanks, seem to be normally adapted to our case :) 

So if I understand well, it will work in a similar way compared to when we insert a CSV with clickhouse with a first argument who is the format of the file and the second argument the defiintion of the datas right ?

**Comment by alexey-milovidov** [comment]
Right. It will allow to to arbitrary data transformations on INSERT.

**Comment by alexey-milovidov** [comment]
@palasonic1 will do this task.

**Comment by abyss7** [comment]
> @palasonic1 will do this task.

Maybe reference and close this one?

**Comment by alexey-milovidov** [comment]
Ok.
