### ISSUE TITLE
What is the recommended server config to use sharding on 2TB data 

### ISSUE THREAD

**Issue by Crazylearner30** [yandex/ClickHouse#5099]
Hi,

We have some 2TB of data to be loaded into different tables.

can somebody tell me what should be the server configuration?

Like how many servers to take to go well with sharding.

what should be the memory for each server. (we currently using AWS t22x large machine).

Basically, we work more with joins and memory consuming queries.

Please suggest me the config in detail.

Thanks in advance!

**Comment by krnaveen14** [comment]
r5.xlarge or r5d.xlarge - 4 vCPU, 32GB RAM, 150GB Instance Storage (r5d)

8 x 300GB GP2 EBS Volumes Striped (RAID0)
150GB Instance Storage as Temporary location for External GROUP BY

CPU and RAM requirements depends on the usage pattern. Above is just an approximation based on t2.2xlarge. If vCPU count of r5 is not sufficient, you could go with m5.2xlarge or m5d.2xlarge.

**Comment by Crazylearner30** [comment]
Thanks for the information Naveen,

Little confused on this.

How many machines to be considered for better performance ?

Thanks,
Divya

**Comment by krnaveen14** [comment]
Depends on the use case and usage pattern (Latency sensitive / Throughout sensitive / Parallel Queries / Response Time / IO Limits / No.of databases / Tables / Partition keys) etc...

I would suggest configure the EC2 instance in staging environment, simulate the production workload in staging environment and analyse the CPU usage, RAM usage, parallel no of queries, IO usage, etc... Based on the analysis, you could try with different configurations and arrive at optimal configuration for your usage pattern.

It involves various strategies like identifying the slowest part / limiting component - CPU Starvation, RAM memory limit, GROUP By spilling to disk, hitting the EBS IOPS Limit on sustained usage and lot more.

**Comment by Crazylearner30** [comment]
Thanks for the information Naveen,

Little confused on this.

How many machines to be considered for better performance ?

Thanks,
Divya
