### ISSUE TITLE
Option for returning result instead of empty

### ISSUE THREAD

**Issue by rasmus93** [yandex/ClickHouse#51]
Need to add option(setting) to return result from one of the rows containing the initial values of aggregate functions instead of returning no result (as we discussed it here: https://groups.google.com/forum/#!topic/clickhouse/2JS_yzvYAHM)
This described in documentation: 
"However, in contrast to standard SQL, if the table doesn't have any rows (either there aren't any at all, or there aren't any after using WHERE to filter), an empty result is returned, and not the result from one of the rows containing the initial values of aggregate functions."

It will be very useful.
Thanks!

**Comment by rasmus93** [comment]
For now working with aggregate functions in sub-queries is uncomfortable(I would even say impossible). 
Because for "count" we can do union with one, OK. But for example for "avg" union will be much more complicate and we can't  easy do sub-queries with aggregate functions. 
@alexey-milovidov Can you, please, tell when the option for this can be added?

**Comment by alexey-milovidov** [comment]
I hope, it is about few weeks.

**Comment by ramazanpolat** [comment]
Hello @rasmus93,
The following workaround will also work for AVG, SUM and other aggregate functions.

```
SELECT *
FROM 
(
    SELECT count(*) AS count
    FROM mytable
    UNION ALL 
    SELECT toUInt64 (0)
) 
LIMIT 1
```

**Comment by osbertngok** [comment]
May I know if this option is implemented?
