### ISSUE TITLE
Add setting to choose if CH commits Kafka message after each poll

### ISSUE THREAD

**Issue by minaevmike** [yandex/ClickHouse#5100]
CH version 19.5.2
**Describe the bug**
We don't have high event-rate in kafka, but i see in our kafka watcher that CH commits message very fast(at version 18.16 CH commits messages when it buffered and store 64k messages). So If i restart CH server it lost data, because it was already commited to kafka and not saved to disk. 
In logs i have lots of messages like
```
2019.04.24 02:26:28.532624 [ 42 ] {} <Trace> StorageKafka (queue): Polled batch of 1 messages
```
So my assumption(i am not common with CH code), that CH shouldn't commit messages here https://github.com/yandex/ClickHouse/blob/b1cf026b5b765d436c8c412ce592d6639df85619/dbms/src/Storages/Kafka/ReadBufferFromKafkaConsumer.cpp#L48 . Seems the correct commit already done at https://github.com/yandex/ClickHouse/blob/b1cf026b5b765d436c8c412ce592d6639df85619/dbms/src/Storages/Kafka/KafkaBlockInputStream.cpp#L49

**Comment by abyss7** [comment]
We already realized that there is a trade-off in this situation: if we read a very big message and partially handle it, then on server crash we may end with a committed message and partially lost data, or with uncommitted message and process some data twice. We'll introduce the setting to choose the desired behavior.

**Comment by minaevmike** [comment]
Also i wan't to clarify, what should happen's with block of data when server restarts(`systemctl restart`). This block must be written or it would be lost?

**Comment by abyss7** [comment]
> Also i wan't to clarify, what should happen with block of data when server restarts(`systemctl restart`). This block must be written or it would be lost?

I will give detailed answer a little bit later.
