### ISSUE TITLE
How to reduce memory usage with arrayEnumerate?

### ISSUE THREAD

**Issue by den-crane** [yandex/ClickHouse#5105]
I have to use arrayEnumerate because of nested ( ['a','a'] k, [1,2] v ) k='a' -> [1,2]
And I noticed that arrayEnumerate eats memory for long arrays (for example 1000 elements)

create table X(A Array(String)) engine = Memory;
insert into X select arrayMap(x->toString (x) , range(1000)) from numbers(10);

select arrayFilter(x->x='777', A) from X format Null;
Peak memory usage (for query): 1.21 MiB

select arrayFilter(x->A[x]='777', arrayEnumerate(A)) from X format Null;
Peak memory usage (for query): **257.33 MiB**

insert into X select arrayMap(x->toString (x) , range(1000)) from numbers(1000);

select arrayFilter(x->x='777', A) from X format Null;
Peak memory usage (for query): 14.01 MiB.

select arrayFilter(x->A[x]='777', arrayEnumerate(A)) from X format Null;
Peak memory usage (for query): **16.02 GiB**

select arrayFilter(x->A[x]='777', range(length(A))) from X format Null;
Peak memory usage (for query): **16.03 GiB.**

How I can reduce memory usage in this case?

**Comment by alexey-milovidov** [comment]
Consider the following expression:
`arrayMap(x -> f(x, b), a)`

To calculate this expression, temporary array join by `a` is performed:

```
a[1], b
a[2], b
a[3], b
...
```

and expression is evaluated:

```
a[1], b, f(a[1], b)
a[2], b, f(a[2], b)
a[3], b, f(a[3], b)
...
```

then the result is collected.

If `b` is also an array, it will be multiplied by the size of `a` in memory:

```
a[1], ['x', 'y', 'z']
a[2], ['x', 'y', 'z']
a[3], ['x', 'y', 'z']
```

if `a` has size 3 and `b` has size 3, we need 3 * 3 = 9 elements to keep in memory for calculations.

**Comment by alexey-milovidov** [comment]
Possible workarounds:
1. Lower `max_block_size`.

**Comment by alexey-milovidov** [comment]
Possible solutions:
1. Automatically use `LowCardinality` data type for array joining.

**Comment by alexey-milovidov** [comment]
create table X(A Array(String)) engine = **TinyLog**;
insert into X select arrayMap(x->toString (x) , range(1000)) from numbers(1000);
SET send_logs_level = 'trace', **max_block_size = 1**;
select arrayFilter(x->A[x]='777', arrayEnumerate(A)) from X format Null;

Peak memory usage (for query): 18.08 MiB.

**Comment by den-crane** [comment]
It seems I always used arrayEnumerate to iterate & filter through nested (K,V) by mistake. 
arrayFilter is able to do pure magic.

select arrayFilter((v, k) -> (toString(k) = 'a'), values, keys) from
(select ['a','a','b','a'] keys, [1,2,3,4] values)
---
[1,2,4]

select arrayFilter((v, k)-> k = '777', A, A) from X format Null;
Peak memory usage (for query): 14.20 MiB.
