### ISSUE TITLE
is "ENABLE_MONGODB=0" outdated ?

### ISSUE THREAD

**Issue by chipitsine** [yandex/ClickHouse#511]
I see usage of "ENABLE_MONGODB=0" in "release" script, however, it seems that variable is not used anywhere

```
[ilia@localhost ClickHouse]$ grep -r ENABLE_MONGODB .
./contrib/libpoco/CMakeLists.txt:option(POCO_ENABLE_MONGODB "Enable MongoDB" ON)
./contrib/libpoco/CMakeLists.txt:if (POCO_ENABLE_MONGODB)
./doc/build_osx.md:export ENABLE_MONGODB=0
./doc/getting_started/getting_started_en.md:~/ClickHouse$ ENABLE_MONGODB=0 ./release --standalone
./doc/getting_started/getting_started_ru.md:~/ClickHouse$ ENABLE_MONGODB=0 ./release --standalone
./.travis.yml:    - ENABLE_MONGODB=0
./release:debuild -e DAEMONS="${DAEMONS}" -e ENABLE_MONGODB -e GLIBC_COMPATIBILITY -e CC -e CXX -b ${DEBUILD_NOSIGN_OPTIONS} ${DEBUILD_NODEPS_OPTIONS}
[ilia@localhost ClickHouse]$ 
```

is it still possible to build Clickhouse without mongodb support ? am I missing something ?

**Comment by ludv1x** [comment]
We removed libmongodb dependency at December. Now we use Poco library (which is built from sources by default) for external MongoDB dictionaries.

Remaining mentions of ENABLE_MONGODB variable in ClickHouse's sources don't make sense.

**Comment by chipitsine** [comment]
ok, I can make "cleanup PR" on that
stay tuned....
