### ISSUE TITLE
Error when filtering on updated enum column type

### ISSUE THREAD

**Issue by valyala** [yandex/ClickHouse#512]
Clickhouse version `1.1.54164`.

## Steps to reproduce

1. Create a `MergeTree` table with Enum field in primary key:

```sql
CREATE TABLE t (d Date, e Enum8('foo'=1)) Engine = MergeTree(d, (d, e), 8192);
```

2. Insert at least one row into the table:

```sql
insert into t (d, e) values ('2017-02-20', 'foo');
```

3. Add new value to enum field:

```sql
alter table t modify column e Enum8('foo'=1, 'bar'=2);
```

4. Try to select on new enum value:

```sql
select count(*) from t where e = 'bar';
```

## Actual result:

Clickhouse returns the following error:

```
Primary key expression contains comparison between inconvertible types: Enum8('foo' = 1) and String inside e = 'bar'.
```

## Expected result:

Clickhouse must return 

```
0 rows in set.
```

## Temporary workaround:

Use 'IN' instead of '=' in the filter on updated enum column:

```sql
select count(*) from t where e in('bar');
```

This issue is related to #364 .

**Comment by ztlpn** [comment]
Confirmed, thanks for reporting.

Another workaround: restart the server.
