### ISSUE TITLE
Do clickhouse support SQL:2016？ And support window functions？

### ISSUE THREAD

**Issue by vkingnew** [yandex/ClickHouse#5132]
Do you have a plan to support window function？ 
the window functions are：
> ROW_NUMBER 
  RANK 
  DENSE_RANK 
  PERCENT_RANK 
  CUME_DIST 
  FIRST_VALUE 
  LAG 
  LAST_VALUE 
  LEAD 
  NTH_VALUE 
  NTILE

**Comment by blinkov** [comment]
There are such plans, but they are not short term. Meanwhile some of window functions can be emulated otherwise. See #1469
