### ISSUE TITLE
Wrong error message for UInt16 type with dictGetUInt64 (Unexpected index.)

### ISSUE THREAD

**Issue by den-crane** [yandex/ClickHouse#5145]
Expected error message:  type mismatch: attribute width has type UInt16.
Current error message: Unexpected index.

touch /etc/clickhouse-server/empty.tsv

```
# cat Banner.xml
<?xml version="1.0"?>
<dictionaries><dictionary>
    <name>Banner</name>
    <source><file><path>/etc/clickhouse-server/empty.tsv</path>
        <format>TabSeparated</format></file>
    </source>
    <lifetime>0</lifetime>
    <layout><flat/> </layout>
    <structure><id><name>id</name></id>
      <attribute>
        <name>width</name>
        <type>UInt16</type>
	<null_value>0</null_value>
      </attribute></structure></dictionary></dictionaries>
```

SELECT dictGetUInt64('Banner', 'width', toUInt64(447379050))
DB::Exception: **Unexpected index.**

But in case of  `<type>Int16</type>` the error message is correct
SELECT dictGetUInt64('Banner', 'width', toUInt64(447379050))
DB::Exception: Banner: type mismatch: attribute width has type Int16.

**Comment by 4ertus2** [comment]
fixed in master - checkAttributeType() in DictionaryStructure.h
