### ISSUE TITLE
How to quickly import data into MergeTree tables

### ISSUE THREAD

**Issue by achimbab** [yandex/ClickHouse#5153]
I ask your understanding for my poor English in advance.

I checked many options to import huge data into MergeTree, such as [Native](https://clickhouse.yandex/docs/en/interfaces/formats/#native), [BatchMode](https://clickhouse.yandex/docs/en/interfaces/cli/#cli_usage), ....

But, I want some faster one.

I wonder about whether the below process is possible or not.

1. I collect data for a day.
2. Convert one-day-data to in the form of MergeTree-partitioned-data
3. ClickHouse just import the MergeTree-partitioned-data without any other merging and partitioning processes.

**Comment by blinkov** [comment]
@achimbab how fast was inserts that you have tried, which hardware have you used, how large was the batches and how much faster do you need it to be?

**Comment by achimbab** [comment]
@blinkov 
* Which hardware have you used?
  - I have 30 machines  (dual intel silver 4110, 256GB Memory, 24TB HDD RAID 1+0)
* How large was the batches?
  - Batches insert 3,000,000,000 rows into the ClickHouse. Each row has 200 columns and the size of a row ranges from 200 to 800 bytes.
* How much faster do you need it to be?
  - I want total insert speed to be at least 1,000,000 rows/second.

**Comment by den-crane** [comment]
>24TB HDD RAID 1+0

And how many disks? You need as many disks as possible for random i/o because each insert creates 400 files (200cols*2).

Though 30 machines should easily ingest 1,000,000 rows/second.
Try bigger batches / upload with clickhouse-client from TSV files by 1mil rows directly to Mergetree table (without distributed)

**Comment by blinkov** [comment]
@achimbab how exactly do you perform inserts and how many rows/second you see at the moment?
Do you insert into `Distributed` table or directly to shards? How MergeTree tables are configured?

**Comment by achimbab** [comment]
@blinkov 
Sorry, I'm too late.
I have some other issues in my company. 
I just tested the insertion speed of ClickHouse.
ClickHouse is fast enough for our purpose and I will push more heavier load to ClickHouse for the production level.
If I have another question put a new issue. 
Sincerely, thank you very much.
