### ISSUE TITLE
Kafka topic name as a field ?

### ISSUE THREAD

**Issue by kmatt** [yandex/ClickHouse#5165]
**Use case**
Kafka topics can be a category of metadata where message structure is the same but the topic name is different, and therefore could be managed as ClickHouse table column data, and also useful for partition definition.

**Describe the solution you'd like**
A function that can be included in the Kafka table engine definition, or consumer materialized view, that can be passed into a MergeTree table as a column:

```
INSERT INTO table ...
SELECT kafka_topic(), ... FROM kafka_engine
```

**Describe alternatives you've considered**
Separate consumers per topic and broker, but as messages have a common structure this is unnecessary repetition.

**Comment by filimonov** [comment]
Related: https://github.com/yandex/ClickHouse/issues/4797#issuecomment-476324427

**Comment by abyss7** [comment]
Both `kafka_broker_list` and `kafka_topic_list` may have multiple comma-separated values.

**Comment by abyss7** [comment]
If it doesn't solve your problem, please, let me know about more details on your scenario.

**Comment by kmatt** [comment]
@abyss7 We do use a list to connect a single Kafka table to multiple topics and brokers, but what I am looking for the ability to insert the topic name from that list with each Kafka message.

This would give us the ability to use a single consumer and query messages by topic, without having to create separate Kafka table connectors. 

Unless there is a feature I am not aware of, to store the topic with each row, I need to create a separate Kafka table and materialized view consumer for each topic.

**Comment by abyss7** [comment]
Now I understood. Will reconsider, how this can be implemented if possible.

**Comment by abyss7** [comment]
Consumed by #5286
