### ISSUE TITLE
Safety threshold on number of partitions.

### ISSUE THREAD

**Issue by alexey-milovidov** [yandex/ClickHouse#5166]
Throw on INSERT if total number of data parts is greater than 100 000
or if total number of partitions is greater than 10 000.

(feature request from Yandex Cloud)

**Comment by andrea-s** [comment]
What's the risk here? Aside from potential slowness

**Comment by alexey-milovidov** [comment]
- inode exhaust;
- difficult to resolve this situation due to extreme degradation of filesystem performance.

We assume that in 100% cases this situation indicates user misconception.

**Comment by den-crane** [comment]
> What's the risk here? Aside from potential slowness

Problems with ZK transactions. To start a mutation CH performs a ZK transaction which includes a list with all partitions names. 
Basically is impossible to execute alter delete/update if the table has more than 10k partitions.
