### ISSUE TITLE
Argument exception when using substringUTF8 on Merge -> Buffer -> MergeTree with PREWHERE

### ISSUE THREAD

**Issue by ohoshio** [yandex/ClickHouse#5174]
**Describe the bug**
Argument exception occurs when applying substringUTF8 to a column in select list from Merge -> Buffer -> MergeTree with PREWHERE clause.

**How to reproduce**
ClickHouse server version 19.5.3 revision 54417

`create table foo (bar String, r_date Date) Engine = MergeTree partition by r_date order by r_date`
`create table foo_buffer as foo ENGINE = Buffer(currentDatabase(), foo, 4, 10, 100, 1000, 10000, 5000000, 50000000)`
`create table foo_merge as foo ENGINE=Merge(currentDatabase(), '^foo_buffer$')`

`select substringUTF8(bar, 1, 100000) from foo_merge prewhere 1=0 limit 1`

**Expected behavior**
Query should return an empty result set.

**Error message and/or stacktrace**
Error: ClickHouse exception, code: 44, host: <hostname>, port: 8123; Code: 44, e.displayText() = DB::Exception: Argument at index 1 for function substringUTF8 must be constant (version 19.5.3.1)

SQLState:  null
ErrorCode: 44

**Additional information**
All of these work without throwing an error:
`select substringUTF8(bar, 1, 100000) from foo_merge where 1=0 limit 1`
`select substring(bar, 1, 100000) from foo_merge prewhere 1=0 limit 1`
`select substringUTF8(bar, 1, 100000) from foo_buffer prewhere 1=0 limit 1`
`select substringUTF8(bar, 1, 100000) from foo prewhere 1=0 limit 1`

**Comment by filimonov** [comment]
On 19.4 i get the following exception:
```
Received exception from server (version 19.4.2):
Code: 182. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Storage Buffer doesn't support PREWHERE.. 
```

On 19.5 weird exception as in issue
```
Received exception from server (version 19.5.2):
Code: 44. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Argument at index 1 for function substringUTF8 must be constant. 
```

On master - works correcty.

**Comment by ohoshio** [comment]
Reporting back to confirm that after updating to ClickHouse server version 19.6.2 revision 54418 the bug is gone.
