### ISSUE TITLE
Multiple Joins with alias results in error

### ISSUE THREAD

**Issue by yellow1912** [yandex/ClickHouse#5180]
I'm completely new to ClickHouse and I wonder if I'm doing something stupid here:

Server version: 19.5.3.

The query:
`select e1.user_id, e2.pageview, e3.event_label from (select distinct(user_id), user_id from alias as e1 group by user_id) any left join (select user_id, count(*) as pageview from event as e2 where event_category = 'pageview' group by user_id) on e2.user_id = e1.user_id any left join (select event_label from event as e3 where event_category = 'pageview' limit 1) on e3.user_id = e1.user_id;`

The error:

> Code: 352. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Cannot refer column 'e1.user_id' to table.

I'm trying to build a complex query that summarize several information for the users such as pageview, last page view and more.

**Comment by 4ertus2** [comment]
Your variant of table aliasing is not supported.
'alias as e1' is not visible here cause it's in subselect. You should place aliases for subselect themselfs, not for tebles inside subselects.

```
select ... from () e1 any left join () e2 on e2.user_id = e1.user_id ...
```
