### ISSUE TITLE
allow ngramdistance needle to be more than a constant

### ISSUE THREAD

**Issue by TH-HA** [yandex/ClickHouse#5181]
Current implementation of ngramDistance restrict the needle to be only a constant.
It may be due to performances consideration but the side effect is it restrict drastically it's usage.

For instance , if you want to use it to correlate or group similar string entry ( it can be log , alarm ....)  stored in clickhouse , you can do it only interactively based on user input ( as you will inject the constant in the query ) . But you cannot use it into some aggregation queries which will group/correlate similar entry together ( which should normally be done using a self join - or in my case by simply defining a set of reference entry in another table on which i 'll associate the record based on the smallest distance.)

Even if it's not fast enough , in my context it should be ok as this correlation/grouping detection can be scheduled once a day.  

Do you have any plan to open the functions in a near future ?

Thanks in advance

**Comment by danlark1** [comment]
I will add it in the near one-two days

**Comment by danlark1** [comment]
And I promise it not to be fast :)

**Comment by danlark1** [comment]
https://github.com/yandex/ClickHouse/pull/5198
