### ISSUE TITLE
Clickhouse 19.5.3 revision 54417 left join speeds about 10 times slower than ClickHouse server version 18.16.0 revision 54412

### ISSUE THREAD

**Issue by wangzhen11aaa** [yandex/ClickHouse#5190]
Hello, everyone, I upgrade the clickhouse from 18.16.0 to 19.5.3, then test the same sql with the same data. The result is not good, like this:

ClickHouse server version 18.16.0 revision 54412

SELECT count(0) FROM test.local a left JOIN test.test_local b ON _id = b._id;

┌─count(0)─┐
│   719930 │
└──────────┘

1 rows in set. Elapsed: 0.009 sec. Processed 719.93 thousand rows, 5.76 MB (83.56 million rows/s., 668.49 MB/s.) 

----------------------------------------------------------------------------------------

Clickhouse 19.5.3 revision 54417

SELECT count(0) FROM test.local a left JOIN test.test_local b ON _id = b._id;

┌─count(0)─┐
│   719930 │
└──────────┘

1 rows in set. Elapsed: 0.050 sec. Processed 719.93 thousand rows, 5.76 MB (14.53 million rows/s., 116.27 MB/s.) 

I appreciate that you guys can pay attention to this problem.

**Comment by den-crane** [comment]
Test (19.7.1.402): 
create table jt(A Int64, S0 String, S1 String, S2 String, S3 String) Engine=MergeTree order by A;
insert into jt select number, toString(arrayMap(x->x, range(100))) s, s, s, s from numbers(500000);

select count() from jt left join jt using A;
Elapsed: 0.030 sec.

select count() from jt a left join (select A from jt) b on a.A=b.A;
Elapsed: 0.309 sec.

18.16.0
select count() from jt left join jt using A;
Elapsed: 0.027 sec.

**Comment by alexey-milovidov** [comment]
@zhang2014 has fixed the issue.
