### ISSUE TITLE
clickhouse default hash algorithm

### ISSUE THREAD

**Issue by etah000** [yandex/ClickHouse#5199]
After applying sharding expression, clickhouse computes the reminder of the returned results to distribute data.

As Jump consistent hashing algorithm says that using this algorithm can greatly reduce network communication while resharding the data in cluster expansion, why don't we use this algothrim as the default hashing algorithm.  Is there any special consideration?

Thanks.

**Comment by den-crane** [comment]
What resharding? CH does not have resharding.

**Comment by filimonov** [comment]
ClickHouse supports 3 consistent hash algorithms: 

```
SELECT *
FROM system.functions 
WHERE name LIKE '%Consi%'

┌─name─────────────────┬─is_aggregate─┬─case_insensitive─┬─alias_to─┐
│ sumburConsistentHash │            0 │                0 │          │
│    │            0 │                0 │          │
│ yandexConsistentHash │            0 │                0 │          │
└──────────────────────┴──────────────┴──────────────────┴──────────┘
```


And of course you can use them in sharding expression, to limit the network communication when cluster is reconfigured.
```
CREATE TABLE distributed AS test_table ENGINE = Distributed(cluster, db, test_table, jumpConsistentHash(field1, 2))
```

Quite often people prefer just to distribute data randomly. It doesn't make sense to calculate consistent hashes from random values. 

And resharding is not a common task. So why should we enforce some defaults?

**Comment by etah000** [comment]
I see. The computation of the reminder does not influence the data distribution generated by "jumpConsistentHash". In order to follow the data distribution weight specified by shard configuration parameter, the "bucket number" should be the total weight of all the shards.

Thanks.
