### ISSUE TITLE
Materialized view on merge table fails

### ISSUE THREAD

**Issue by MrBuddyCasino** [yandex/ClickHouse#5201]
**Describe the bug**
Create several tables, then create a merge table based on them. Then create a materialized view based on the merge table. This will fail with an "unknown identifier" error.

**How to reproduce**

This is a zip containing all the statements and a script to run them, via cURL:
https://drive.google.com/file/d/1apnlD80_-WtjEiKIFiRNon1JzlQp5_GG/view?usp=sharing

We use version CH 18.14.13, but latest shows the same issue.

**Expected behavior**
All tables are created without error.

**Error message and/or stacktrace**
The `create_40_calls_fast_row_count.up.sql` statement creates the error `Code: 47, e.displayText() = DB::Exception: Unknown identifier: t, e.what() = DB::Exception`.

**Comment by MrBuddyCasino** [comment]
These issues might be related: 
https://github.com/yandex/ClickHouse/issues/2878
https://github.com/yandex/ClickHouse/issues/956

**Comment by MrBuddyCasino** [comment]
Turns out this is probabaly a regex issue. The merge table definition should have used `^calls$|^longterm_calls$|^calls_v2$`, but was `'^calls|longterm_calls|calls_v2$'`

**Comment by den-crane** [comment]
Materialized view  is INSERT_TRIGGER. 
Engine Merge does not support INSERTs so MV over Merge is nonsense.

**Comment by MrBuddyCasino** [comment]
I just tested this, and executed `select countMerge(row_count_state) from calls_fast_row_count` after running the scripts. It returned the correct result. I made an updated version of the zip, get it at https://drive.google.com/file/d/1A53kAmMeOHzAzYKaLo_yRLhxzjdpsZ0o/view?usp=sharing.

**Comment by den-crane** [comment]
>It returned the correct result.

haha, just make your inserts in the end, after MV creation.

**Comment by filimonov** [comment]
The bug here is that is allowed you to create the Materialized View which has no practical sense. 

If you need to collect data from several tables to one materialized view you do something like: 
```sql
create table source1(...) Engine=...;
create table source2(...) Engine=...;
create table target (...) Engine=...;
create materialized view source1_to_target to target as select * from source1;
create materialized view source2_to_target to target as select * from source2;
```

**Comment by filimonov** [comment]
Created feature issue, please see #5207
