### ISSUE TITLE
Optimize queries with has function over static arrays

### ISSUE THREAD

**Issue by a-rodin** [yandex/ClickHouse#5203]
If there is a table with primary key `(CounterId, Date)` and I do a query

```sql
SELECT count() FROM table WHERE CounterId = 123 OR CounterId = 345
```

ClickHouse reads only the rows related to the given `CounterId`s.

However, the very same query written as

```sql
SELECT count() FROM table WHERE has([123, 345], CounterId)
```

makes ClickHouse read all rows from the table, without the optimization by primary key.

**Comment by den-crane** [comment]
Just in case. Are you aware of an optimization `PRIMARY_KEY_COLUMN IN ()` including `PRIMARY_KEY_COLUMN IN (SUBQUERY)`

SELECT count() FROM table WHERE CounterId in (123, 345, ....)
For long lists with enumerations check https://clickhouse.yandex/docs/en/operations/table_engines/external_data/

**Comment by a-rodin** [comment]
@den-crane Thank you, it works even better!
