### ISSUE TITLE
How to restart clickhouse server with kafka engine tables gracefully?

### ISSUE THREAD

**Issue by ghuname** [yandex/ClickHouse#5208]
Hi,

on page https://clickhouse.yandex/docs/en/operations/table_engines/kafka/

is the following example:

  CREATE TABLE queue (
    timestamp UInt64,
    level String,
    message String
  ) ENGINE = Kafka('localhost:9092', 'topic', 'group1', 'JSONEachRow');

  CREATE TABLE daily (
    day Date,
    level String,
    total UInt64
  ) ENGINE = SummingMergeTree(day, (day, level), 8192);

  CREATE MATERIALIZED VIEW consumer TO daily
    AS SELECT toDate(toDateTime(timestamp)) AS day, level, count() as total
    FROM queue GROUP BY day, level;

  SELECT level, sum(total) FROM daily GROUP BY level;

To **stop receiving topic data** or to change the conversion logic, detach the materialized view:

  DETACH TABLE consumer;
  ATTACH MATERIALIZED VIEW consumer; (ATTACH MATERIALIZED VIEW doesn't work, ATTACH TABLE consumer works, but it is not necessary if server is restarted, because consumer is automatically attached). 

We have tried to deatach consumer table before restarting clickhouse-server, but after clickhouse-server is up again, we have noticed that we have lost some of the messages.
We also tried to deatach consumer and queue tables, but the problem still remains.

What would bi the best way to restart clickhouse-server node and not to lose any kafka messages?
Do we have to set up something on clickhouse side? Kafka side? Or both?

Regards.

**Comment by ghuname** [comment]
Nobody knows?

**Comment by abyss7** [comment]
There was a problem with Kafka messages get lost even without restarts. It was fixed in 19.5 and 19.6 (you haven't provided the version you're using). Can you test against latest 19.5.* or 19.6.* versions and confirm that problem persists?

**Comment by ghuname** [comment]
In our case server version is 18.14.15. 
I misreported the issue. I appologize. Sorry. 

We are not loosing kafka messages. After restarting clickhouse server, last messages are duplicated (not lost). 

Looks like clickhouse has collected messages from kafka and put them into tables but haven't sent acknowledge back to kafka.
Therefore, when clickhouse server is up again, it recollects the same messages second time.

I should somehow say to clickhouse server to stop collecting messages from kafka topic, and to put all previously collected messages into tables.
After that is completed, we could bring the clickhouse server down securely, and prevent duplication.

Can you please help how to do that?

Regards

**Comment by abyss7** [comment]
Your version is too old - I think there is no mechanism to achieve desired behavior, beside using very small `kafka_max_block_size` in the table.

**Comment by nvartolomei** [comment]
@abyss7 why not possible? You can commit (best effort), before shutting down the tables.

**Comment by abyss7** [comment]
> @abyss7 why not possible? You can commit (best effort), before shutting down the tables.

It's not possible in this specific version, because it's too old and we won't update it. For 19.8+ there is already an option that allows to commit either on every message batch or on every merged block: #5100

**Comment by nvartolomei** [comment]
Got it.

**Comment by ghuname** [comment]
Thanks for an explanation. I will wait for v19.8 in order to check this subject again.

**Comment by abyss7** [comment]
Will close for now.
