### ISSUE TITLE
Load balance in clickhouse shard

### ISSUE THREAD

**Issue by Crazylearner30** [yandex/ClickHouse#5219]
We have two shards, and two tables 

Tables:
Company
Contact

we have sharded contact table and have distributed equally among two shards.

but company table we have not sharded and its available only in shard 1.

When i tried to join company and contact table through shard 1

am getting the results correctly.

1. My confusion here is are we putting more load on shard 1 ? and shard 2 is idling when we are trying to query from shard1.

2. how can we distribute the work load on both the shards?

3. do we have to shard both the tables in both the shards.

Note: Company has some  (8 million ~)  and contacts we have some (19 million ~) 

Kindly help us with the answers at the earliest.

Thanks

**Comment by Crazylearner30** [comment]
Thanks for the reply
 let me try and come back

**Comment by filimonov** [comment]
Please kindly close the ticket if you have no more questions.

**Comment by filimonov** [comment]
Please reopen in case of extra questions
