### ISSUE TITLE
Parallelism when running concurrent queries 

### ISSUE THREAD

**Issue by hanguyen6** [yandex/ClickHouse#5226]
Hi, 

We are running a concurrency test with ClickHouse and see some strange behaviors and would like to understand it: 

Single Server: 28CPUs, 256GB Ram 

Table definition: 
tbl (eventDate datetime, id UInt64, col1 string, col2 string, ... coln string) ENGINE = mergeTree () PARTITION BY toYYYYMMDD(event_date) PRIMARY KEY (event_date, id); 

- Concurrent query to run : SELECT col1, col2 FROM tbl where eventDate between [<some-date>] and [<some-date>] and col3 = [<some-value> ]
 
Behavior: 
- Running single query took around 2 seconds to finish 
- Running n * query took 2*n seconds to finish (n < 10) 

Observation:
- can not see any resource contention during concurrent testing :  only 5/6 CPU used, lots of memory free, less disk seeking 

Question: 
- we was expecting that when running n concurrent queries (n small < 10), time taken should be the more or less as running single query given that ClickHouse can take into advantage of CPU parallelism  ? 

Please let me know if there is any misconception here or anything that we could do to check ? 

Thanks,

**Comment by den-crane** [comment]
Please show the output line with statistics from clickhouse-client (proccessed / mb/s)
And `iostat -x 1 20` during the single query.

**Comment by hanguyen6** [comment]
Hi, 
it turns out to be CPU bound.  We saw CPU limit when number of queries are running in parallel due to large number of rows the server needs to load.  Using PREWHERE to filter rows we were able to achieve better parallelism. 

Thanks,
