### ISSUE TITLE
Segmentation fault during insert into Distributed/Replicated table

### ISSUE THREAD

**Issue by blind-oracle** [yandex/ClickHouse#5233]
Version: 19.5.4.1

I was transferring data from another Clickhouse cluster using
`insert into graphite select * from remote('10.91.2.59', default.graphite);`

Maybe there's a duplicate bug already, but I couldn't find it.

After about 90% the server I was executing the query on crashed with:
```
2019.05.09 17:54:29.175797 [ 124 ] {} <Error> BaseDaemon: ########################################
2019.05.09 17:54:29.182463 [ 124 ] {} <Error> BaseDaemon: (version 19.5.4.1) (from thread 39) Received signal Segmentation fault (11).
2019.05.09 17:54:29.182548 [ 124 ] {} <Error> BaseDaemon: Address: 0xffffffea
2019.05.09 17:54:29.182585 [ 124 ] {} <Error> BaseDaemon: Access: read.
2019.05.09 17:54:29.182620 [ 124 ] {} <Error> BaseDaemon: Address not mapped to object.
2019.05.09 17:54:29.225987 [ 124 ] {} <Error> BaseDaemon: 0. clickhouse-server(std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(char const*, std::basic_string<char, std::char_traits<
2019.05.09 17:54:29.226133 [ 124 ] {} <Error> BaseDaemon: 1. clickhouse-server() [0x2ea776d]
2019.05.09 17:54:29.226176 [ 124 ] {} <Error> BaseDaemon: 2. clickhouse-server(DB::StorageReplicatedMergeTree::clearOldPartsAndRemoveFromZK()+0x1e2) [0x5f80652]
2019.05.09 17:54:29.226212 [ 124 ] {} <Error> BaseDaemon: 3. clickhouse-server(DB::ReplicatedMergeTreeCleanupThread::iterate()+0x16) [0x607f966]
2019.05.09 17:54:29.226254 [ 124 ] {} <Error> BaseDaemon: 4. clickhouse-server(DB::ReplicatedMergeTreeCleanupThread::run()+0xcb) [0x607fbab]
2019.05.09 17:54:29.226299 [ 124 ] {} <Error> BaseDaemon: 5. clickhouse-server(DB::BackgroundSchedulePool::TaskInfo::execute()+0xe1) [0x6174951]
2019.05.09 17:54:29.226335 [ 124 ] {} <Error> BaseDaemon: 6. clickhouse-server(DB::BackgroundSchedulePool::threadFunction()+0x62) [0x6175022]
2019.05.09 17:54:29.226396 [ 124 ] {} <Error> BaseDaemon: 7. clickhouse-server() [0x6175084]
2019.05.09 17:54:29.226444 [ 124 ] {} <Error> BaseDaemon: 8. clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x187) [0x66c7017]
2019.05.09 17:54:29.226478 [ 124 ] {} <Error> BaseDaemon: 9. clickhouse-server() [0x71f129f]
2019.05.09 17:54:29.226512 [ 124 ] {} <Error> BaseDaemon: 10. /lib64/libpthread.so.0(+0x7dd5) [0x7fcfa131fdd5]
```

Target table is distributed, under it there are 3 replicated shards.

**Comment by blind-oracle** [comment]
If some more info on table structure & environment needed - please let me know.

**Comment by den-crane** [comment]
Is it repeatable? Why did you build this by yourself?
Check what thread [ 39 ] wrote in the log before crash.

Try this
https://clickhouse-builds.s3.yandex.net/4884/ac8ceade2096781a30586fcba24ccb38553318bc/report.html

**Comment by filimonov** [comment]
It would be really cool if you will be able to create a minimal verifiable example.
I.e. create table statements + some data (if needed) & needed config.

**Comment by blind-oracle** [comment]
@den-crane I've seen this happen only once for now.
I've built it myself using Altinity RPM builder scripts to include fixes for stuff like this https://github.com/yandex/ClickHouse/pull/5127

@filimonov It's hard to verify because the table has around 30 billion rows and what exactly caused the crash is difficult to tell. But it's not some specific data for sure, because after the crash I've re-selected the data and it went fine.

The table structure is very simple, here it is with the server config: https://gist.github.com/blind-oracle/87230b1431fabbf4efe3ffaeebdb2e6e

**Comment by den-crane** [comment]
Try to validate you build with this https://github.com/yandex/ClickHouse/issues/5197#issuecomment-489462448 .

**Comment by blind-oracle** [comment]
Haven't seen it in recent versions. Let's close.
