### ISSUE TITLE
bitmap functions produce wrong result

### ISSUE THREAD

**Issue by svladykin** [yandex/ClickHouse#5244]
On the current master I see the following:
```
SELECT bitmapAndCardinality(bitmapBuild([100, 200, 500]), bitmapBuild([100, 200])) AS result

┌─result─┐
│      0 │
└────────┘
```
Manual cast to `Array(UInt32)` fixes the issue, but I believe the query above must either throw an exception or produce the correct result. Preferably it should do the needed type conversions automatically.
```
SELECT bitmapAndCardinality(bitmapBuild(CAST([100, 200, 500], 'Array(UInt32)')), bitmapBuild(CAST([100, 200], 'Array(UInt32)'))) AS result

┌─result─┐
│      2 │
└────────┘
```

**Comment by svladykin** [comment]
@andyyzh Looks like I have another one for you :)

**Comment by andyyzh** [comment]
Run this sql, the result is fine, and it should be a type conversion problem.
```
SELECT bitmapAndCardinality(bitmapBuild([1, 2, 5]), bitmapBuild([1, 2])) AS result

┌─result─┐
│      2 │
└────────┘
```

**Comment by andyyzh** [comment]
Automatic type of bitmap conversion is expensive,
Only add parameter type check.

**Comment by svladykin** [comment]
Parameter type check works fine.
