### ISSUE TITLE
Incorrect single quote escaping in CSV output

### ISSUE THREAD

**Issue by ilyabo** [yandex/ClickHouse#5265]
When using the HTTP interface the CSV output escapes single quotes with a backslash. From my understanding this is not compliant with [RFC4180](https://tools.ietf.org/html/rfc4180). In CSV only double quotes must be escaped when the full value is quoted in double quotes if it contains the separator  (and not with a backslash, but with a double double quote).

**How to reproduce**

I can reproduce this with ClickHouse 19.1.1 and with 18.14.9 using the HTTP interface:
```
$ echo "SELECT 'd\'Artagnan'"  | curl http://localhost:8123 --data-binary @-
d\'Artagnan
```
The single quote in `d\'Artagnan` is escaped. This is incorrect.

When running the same query in `clickhouse-client` the single quote in the result is **not** escaped (this is correct):
```
ilya.local :) select 'd\'Artagnan'

SELECT 'd\'Artagnan'

┌─'d\'Artagnan'─┐
│ d'Artagnan    │
└───────────────┘

1 rows in set. Elapsed: 0.002 sec. 
```

**Expected behavior**

Single quotes in CSV produced by the HTTP interface shouldn't be escaped:

```
$ echo "SELECT 'd\'Artagnan'"  | curl http://localhost:8123 --data-binary @-
d'Artagnan
```

**Comment by den-crane** [comment]
Default http format is TSV not CSV

echo "SELECT 'd\'Artagnan', 'am I' format CSV"  | curl http://localhost:8123 --data-binary @-
"d'Artagnan","am I"

Default clickhouse-client format is pretty-compact

```
:) select 'd\'Artagnan' format TSV
d\'Artagnan
```

```
:) select 'd\'Artagnan' format CSV
"d'Artagnan"
```

https://clickhouse.yandex/docs/en/interfaces/formats/

**Comment by ilyabo** [comment]
Thanks for the hint! I didn't realize that it's possible to switch to CSV.  This can solve our issue.

Still, is this escaping defined by this TSV standard? The [library we use for TSV parsing](https://github.com/d3/d3-dsv) does not unescape these.

**Comment by den-crane** [comment]
CH needs to escape ' because of arrays
`['arr1','arr2']<tab>someString`

**Comment by ilyabo** [comment]
Ok, I see. Thanks for the suggestion again. Using `format CSV` solves our issue.
