### ISSUE TITLE
How to trim  blank data  in column?

### ISSUE THREAD

**Issue by sangli00** [yandex/ClickHouse#527]
create table tx(x String,y String)ENGINE=Log;

I copy cvs file to this table.
![99](https://cloud.githubusercontent.com/assets/3765918/23347490/ac899828-fcdd-11e6-8a52-46af35dc406f.png)

```
:] select * from tx where y = 'b';

SELECT *
FROM tx 
WHERE y = 'b'

┌─x─────┬─y─┐
│ aaaaa  │ b │
└───────┴───┘
↖ Progress: 4.00 rows, 153.00 B (900.19 rows/s., 34.43 KB/s.) 
1 rows in set. Elapsed: 0.004 sec. 

```

**Comment by ztlpn** [comment]
You can use `replaceRegexpOne` function to trim whitespace at the end of a string:
```sql
SELECT replaceRegexpOne(y, '\\s+$', '') FROM tx
```

**Comment by sangli00** [comment]
why  copy csv  to Clickhouse ,everyone columns is blank?

**Comment by sangli00** [comment]
@ztlpn  why can't ``` insert into t select * from t;```?

**Comment by sangli00** [comment]
```
Code: 1000. DB::Exception: Received from localhost:9000, ::1. DB::Exception: System exception: cannot lock reader/writer lock. 
```
this is error

**Comment by alexey-milovidov** [comment]
It is likely, you are using tables of `Log` or `TinyLog` engines. These kind of tables are intended for simple write-once scenarios. They are using read-write lock and INSERT SELECT to the same table is impossible.

As mentioned in documentation, "Note that for most serious tasks, you should use engines from the MergeTree family."
