### ISSUE TITLE
windowFunnel support for 64bit numbers for time column

### ISSUE THREAD

**Issue by Chr1sxu** [yandex/ClickHouse#5277]
use case
I d like to use aggregated function windowFunnel, but the parameter 'timestamp' only support DateTime and Uint32, which means the time is stored with accuracy up to one second . But actually, tons of events triggerred within one seconds. We do encounter the inconveniences because of it. Im not sure is there any solutions to solve this problem. If no, are u going to improve it.

**Comment by a-rodin** [comment]
As a workaround, you can try to use `UInt32` with number of fractions of second since specific date. For example, you can store high-precision timestamp as the number of microseconds since UNIX epoch, then call `windowFunnel` as

```
windowFunnel(1000 * 60  * 10)(toUInt32(timestampMs - firstTimestampMs), cond1, cond2, ...)
```

where `timestampMs - firstTimestampMs` is assumed to be less than `2^32`.

**Comment by Chr1sxu** [comment]
cheer 4 this，it helps more or less，but hope Uint64 would be supported soon

**Comment by filimonov** [comment]
It was done like that to limit the memory consumption during calculations.
Currently, it requires 32+32=64bit per event, with that change it will be 64+32=96. 

Change is problematic as it will break binary compatibility of windowFunnel state
between CH versions, it could be easier to add windowFunnel64 or something similar.

**Comment by filimonov** [comment]
Support for 64bit numbers in windowFunnel added in 19.8.
