### ISSUE TITLE
How to create UDF in ClickHouse?

### ISSUE THREAD

**Issue by sangli00** [yandex/ClickHouse#529]
Sometimes I need used UDF parse  data in ClickHouse. like Postgres extension.
could you ask me, how to create UDF in ClickHouse Database?

**Comment by ztlpn** [comment]
Short answer: currently there is no extension support in ClickHouse so the only way to define a "UDF" is to implement it as a built-in function and open the pull request to merge the code into the main ClickHouse repository. See issue #11
