### ISSUE TITLE
Service fails to restart on ubuntu-trusty-14.04-amd64-server-20160314

### ISSUE THREAD

**Issue by buremba** [yandex/ClickHouse#53]
I'm trying to install Clickhouse on AWS. Initially I decided to use instance-store for better IO performance and the AMI for instances that supports instance-store is `ubuntu-trusty-14.04-amd64-server-20160314.manifest.xml (ami-2c717046)`.

I simply install Clickhouse from `http://repo.yandex.ru/clickhouse/trusty stable main`, start ClickHouse service and run `clickhouse-client`. Then I create a table like this one: (the table definition doesn't make difference)

`CREATE TABLE testtable ( EventDate Date, UserID UInt64, Attrs Nested( Key String, Value String) ) ENGINE = MergeTree(EventDate, UserID, 8192)`

Then I restarted clickhouse-server service but clickhouse-client was not able to connect the server. Unfortunately clickhouse-server doesn't log any error message (clickhouse.err, stderr and stdout is empty) but output of clickhouse.log file is similar to this one:

```
2016.07.13 12:00:07.699 [ 1 ] <Information> : Starting daemon with revision 53988
2016.07.13 12:00:07.814 [ 1 ] <Information> Application: starting up
2016.07.13 12:00:07.814 [ 1 ] <Debug> Application: rlimit on number of file descriptors is 262144
2016.07.13 12:00:07.814 [ 1 ] <Debug> Application: Initializing DateLUT.
2016.07.13 12:00:07.814 [ 1 ] <Trace> Application: Initialized DateLUT.
2016.07.13 12:00:07.815 [ 1 ] <Debug> Application: Configuration parameter 'interserver_http_host' doesn't exist or exists and empty. Will use 'clickhouse1.localdomain' as replica host.
2016.07.13 12:00:07.815 [ 1 ] <Debug> UsersConfigReloader: Loading users config
2016.07.13 12:00:07.816 [ 1 ] <Information> Application: Loading metadata.
2016.07.13 12:00:07.816 [ 1 ] <Information> DatabaseOrdinary (default): Total 1 tables.
```

It seems that the server got stuck when loading the table and never able to start. `service clickhouse-server stop` also got stuck since the process doesn't respond so I had to execute forcestop command in order to shutdown the clickhouse-server process. 

If I don't create any table, I'm able to restart the service without any issue. Also when I try to install Clickhouse on `ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-20160114.5 (ami-fce3c696)` it works as expected.

**Comment by alexey-milovidov** [comment]
I investigated this bug recently.

On some virtual machines, ClickHouse think, that there are zero number of CPU cores.
More precisely, it is the behavior of 'cpuid' library (https://github.com/anrieff/libcpuid).

Reason could be a bug in cpuid library or incorrect result of virtualized 'cpuid' instruction.
I have already committed workaround https://github.com/yandex/ClickHouse/commit/fe216b7338e5108a1bd3171b51e0b63fac38b468, it is scheduled for next release.

Right now you could build master revision from sources.

**Comment by alexey-milovidov** [comment]
https://github.com/anrieff/libcpuid/issues/50

**Comment by alexey-milovidov** [comment]
In release.

**Comment by buremba** [comment]
Thanks!
