### ISSUE TITLE
FR: arbitrary min-max indices

### ISSUE THREAD

**Issue by valyala** [yandex/ClickHouse#530]
It looks like that MergeTree sparse index nodes currently maintain only min and max values for tuples built from primary key columns. I.e.:
```
min((key_column1, key_column2, ... key_columnN))
max((key_column1, key_column2, ... key_columnN))
```

It would be great if each node in MergeTree sparse index would contain min and max values for each individual column from the primary key:
```
min(key_column1), min(key_column2), ... , min(key_columnN)
max(key_column1), max(key_column2), ... , max(key_columnN)
```

Then clickhouse could skip a lot of rows on `SELECT` queries with filters on `key_column{X}`, `X > 1` for high values of `uniq(key_column1, ... key_column{X-1})`. For instance:

Suppose the following `MergeTree` table exists with millions of distinct `CustomerID` values:
```sql
CREATE TABLE t (
    EventDate Date,
    CustomerID UInt32,
    EventTime DateTime,
) ENGINE = MergeTree(EventDate, (CustomerID, EventDate, EventTime), 8192);
```

Then the following queries could be sped up if nodes in the sparse index would contain min and max values for `EventTime` and `EventDate` columns:

```sql
-- the number of events for the last hour
SELECT COUNT(*) FROM t WHERE EventTime > now() - 3600;

-- the number of events for the current day
SELECT COUNT(*) FROM t WHERE EventDate = today();
```

As I understood, currently these queries require rows scanning for each individual `CustomerID`.

**Comment by ztlpn** [comment]
A similar idea goes by the name "range index" or "min-max index" (https://en.wikipedia.org/wiki/Block_Range_Index). It is not even necessary for the indexed column to be part of the primary key - the data just has to be stored in such a way that min-max ranges do not overlap much for different blocks.

In fact, MergeTree tables already maintain one such index - on the date column. If you specify a condition on the date column, data will be read only from the partitions consistent with this condition. There are plans to allow arbitrary partition keys (not limited to dates), so you will be able to define one additional min-max index. But as far as I know, currently there no plans to support arbitrary min-max indices.

**Comment by alexey-milovidov** [comment]
https://github.com/yandex/ClickHouse/pull/4143
