### ISSUE TITLE
Increase the speed of getting replica back to healthy state 

### ISSUE THREAD

**Issue by filimonov** [yandex/ClickHouse#5317]
Case
1) some replica go temporary offline
2) Distributed table connection pool error_count for that replica get high
3) replica gets back online again, but Distributed doesn't use it for a long time, as the speed of error_count decreasing is very slow currently (halved every 10 minutes).

We need to make some better heuristic for that. 

We can just decrease the value for
DBMS_CONNECTION_POOL_WITH_FAILOVER_DEFAULT_DECREASE_ERROR_PERIOD
but in that case flapping replica errors will be 'forgotten' too fast ( see https://github.com/yandex/ClickHouse/commit/192bbc02859ba140cb46878750318dbbc13f5837 ).

Maybe we should introduce some upper limit for `error_count` and never increase it above that number to give a chance to return back alive fast enough?

**Comment by alexey-milovidov** [comment]
> decreasing is very slow currently (halved every 10 minutes)

For whatever reason, I remember that my first intention was to halve every 60 seconds. It means that 1000 errors will vanish after 10 minutes. Let's change it accordingly...

> Maybe we should introduce some upper limit for error_count and never increase it above that number to give a chance to return back alive fast enough?

Reasonable. Let it be 1000 by default. It means that 10 minutes is always enough for recovery.

PS. We can also think about totally different algorithms. Some kind of weighted sampling according to bayesian bandits. Reason: if the number of errors differs insignificantly, start to infrequently try use replicas with slightly more errors.

**Comment by alex-zaitsev** [comment]
So the proposal is:
1) Decrease DBMS_CONNECTION_POOL_WITH_FAILOVER_DEFAULT_DECREASE_ERROR_PERIOD to 60 seconds. 
2) Add DBMS_CONNECTION_POOL_WITH_FAILOVER_MAX_ERROR_COUNT = 1000
3) Add 'replica_error_decrease_period' and 'replica_error_max_count' to make those settings configurable.
4) Add current error count to system.replicas ?
