### ISSUE TITLE
Problem: Asterisk with ARRAY JOIN

### ISSUE THREAD

**Issue by artpaul** [yandex/ClickHouse#533]
`SELECT x, a FROM (SELECT arrayJoin(['Hello', 'Goodbye']) AS x, [1, 2, 3] AS arr) ARRAY JOIN arr as a` 
works fine:
Hello	1
Hello	2
Hello	3
Goodbye	1
Goodbye	2
Goodbye	3

but 
`SELECT * FROM (SELECT arrayJoin(['Hello', 'Goodbye']) AS x, [1, 2, 3] AS arr) ARRAY JOIN arr as a`
returns unexpected result:
Hello	[1,2,3]
Hello	[1,2,3]
Hello	[1,2,3]
Goodbye	[1,2,3]
Goodbye	[1,2,3]
Goodbye	[1,2,3]

**Comment by ztlpn** [comment]
Even simpler:
```sql
:) SELECT * FROM (SELECT [1, 2, 3] AS arr) ARRAY JOIN arr AS a

SELECT *
FROM
(
    SELECT [1, 2, 3] AS arr
)
ARRAY JOIN arr AS a

┌─arr─────┐
│ [1,2,3] │
│ [1,2,3] │
│ [1,2,3] │
└─────────┘

3 rows in set. Elapsed: 0.002 sec.
```
The contents of `arr` column is as expected. From the docs: 
> An alias can be specified for an array in the ARRAY JOIN clause. In this case, an array item can be accessed by this alias, but the array itself by the original name.

So the problem can be stated as follows: ARRAY JOIN alias doesn't appear in the set of columns denoted by asterisk.
