### ISSUE TITLE
Implement dictGet dictGetOrDefault for Decimal

### ISSUE THREAD

**Issue by golubev-ml** [yandex/ClickHouse#5343]
I suggest to create similar functions that exist for Integer and Float but for Decimal32, Decimal64 and Decimal128 for example dictGetDecimal32
https://clickhouse.yandex/docs/en/query_language/functions/ext_dict_functions/

I have a dictionary with Decimal32 field in it, but when I try to get this field from the dictionary I can't
```
ClickHouse client version 19.4.0.49.

select dictGetDecimal32('dictionary', 'column', id)
Code: 46. DB::Exception: Unknown function dictGetDecimal32. Maybe you meant: ['dictGetFloat32','toDecimal32']. 

select dictGetFloat32('dictionary', 'column', id)
Code: 53. DB::Exception: service: type mismatch: attribute price has type Decimal32.
```

**Comment by 4ertus2** [comment]
It's in our plans to implement dictGet functions for Decimals.

**Comment by 4ertus2** [comment]
#5394
