### ISSUE TITLE
Clickhouse Add date column to new table with specific date

### ISSUE THREAD

**Issue by Crazylearner30** [yandex/ClickHouse#5351]
table 1----- without date column
table 2----- want to insert date column with a specific date

Query--- insert into table 2
               select a,b,c,d,NOW() from table 1 

NOW() will insert current date but I want to insert a specific date  into table 2

EX: 2019-12-09

Please help me with the query as early as possible

**Comment by filimonov** [comment]
```
insert into table2
select a,b,c,d,toDate('2019-12-09') from table1
```

**Comment by Crazylearner30** [comment]
i tried this and its not working :(

**Comment by den-crane** [comment]
> i tried this and its not working :(

with what error ???

**Comment by Crazylearner30** [comment]
Hi sorry i was using todate instead of toDate('YYYY-MM-DD')

Its working and thanks for the quick reply :)
