### ISSUE TITLE
Address: NULL pointer

### ISSUE THREAD

**Issue by yxjsnj2018** [yandex/ClickHouse#5362]
**Centos7, Altinity rpm package, version 19.6.2.11, will repeatedly output the following errors:**

2019.05.21 16:04:57.879013 [ 59 ] {} <Error> BaseDaemon: ########################################
2019.05.21 16:04:57.879075 [ 59 ] {} <Error> BaseDaemon: (version 19.6.2.1) (from thread 50) Received signal Segmentation fault (11).
2019.05.21 16:04:57.879093 [ 59 ] {} <Error> BaseDaemon: Address: NULL pointer.
2019.05.21 16:04:57.879103 [ 59 ] {} <Error> BaseDaemon: Access: read.
2019.05.21 16:04:57.879113 [ 59 ] {} <Error> BaseDaemon: Address not mapped to object.
2019.05.21 16:04:57.959795 [ 59 ] {} <Error> BaseDaemon: 0. clickhouse-server(DB::ColumnString::insertFrom(DB::IColumn const&, unsigned long)+0x78) [0x60b9508]
2019.05.21 16:04:57.959821 [ 59 ] {} <Error> BaseDaemon: 1. clickhouse-server() [0x5f7bf6e]
2019.05.21 16:04:57.959833 [ 59 ] {} <Error> BaseDaemon: 2. clickhouse-server() [0x5fc792d]
2019.05.21 16:04:57.959875 [ 59 ] {} <Error> BaseDaemon: 3. clickhouse-server(void DB::Join::joinBlockImpl<(DB::ASTTableJoin::Kind)0, (DB::ASTTableJoin::Strictness)1, DB::Join::MapsTemplate<DB::Join::WithFlags<false, false, DB::RowRef> > >(DB::Block&, std::vector<std::string, std::allocator<std::string> > const&, DB::NamesAndTypesList const&, DB::Block const&, DB::Join::MapsTemplate<DB::Join::WithFlags<false, false, DB::RowRef> > const&) const+0xa89) [0x5fd3a49]
2019.05.21 16:04:57.959898 [ 59 ] {} <Error> BaseDaemon: 4. clickhouse-server(DB::Join::joinBlock(DB::Block&, std::vector<std::string, std::allocator<std::string> > const&, DB::NamesAndTypesList const&) const+0x33c) [0x5f9222c]
2019.05.21 16:04:57.959912 [ 59 ] {} <Error> BaseDaemon: 5. clickhouse-server(DB::ExpressionAction::execute(DB::Block&, bool) const+0xad9) [0x64e6749]
2019.05.21 16:04:57.959931 [ 59 ] {} <Error> BaseDaemon: 6. clickhouse-server(DB::ExpressionActions::execute(DB::Block&, bool) const+0x45) [0x64e7ab5]
2019.05.21 16:04:57.959944 [ 59 ] {} <Error> BaseDaemon: 7. clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x35) [0x63adee5]
2019.05.21 16:04:57.959959 [ 59 ] {} <Error> BaseDaemon: 8. clickhouse-server(DB::IBlockInputStream::read()+0x135) [0x5e338a5]
2019.05.21 16:04:57.959975 [ 59 ] {} <Error> BaseDaemon: 9. clickhouse-server(DB::FilterBlockInputStream::readImpl()+0x9e) [0x63aea4e]
2019.05.21 16:04:57.959987 [ 59 ] {} <Error> BaseDaemon: 10. clickhouse-server(DB::IBlockInputStream::read()+0x135) [0x5e338a5]
2019.05.21 16:04:57.959999 [ 59 ] {} <Error> BaseDaemon: 11. clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x1a) [0x63adeca]
2019.05.21 16:04:57.960021 [ 59 ] {} <Error> BaseDaemon: 12. clickhouse-server(DB::IBlockInputStream::read()+0x135) [0x5e338a5]
2019.05.21 16:04:57.960032 [ 59 ] {} <Error> BaseDaemon: 13. clickhouse-server(DB::CreatingSetsBlockInputStream::readImpl()+0x1e0) [0x6398940]
2019.05.21 16:04:57.960044 [ 59 ] {} <Error> BaseDaemon: 14. clickhouse-server(DB::IBlockInputStream::read()+0x135) [0x5e338a5]
2019.05.21 16:04:57.960055 [ 59 ] {} <Error> BaseDaemon: 15. clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x1a) [0x63adeca]
2019.05.21 16:04:57.960067 [ 59 ] {} <Error> BaseDaemon: 16. clickhouse-server(DB::IBlockInputStream::read()+0x135) [0x5e338a5]
2019.05.21 16:04:57.960078 [ 59 ] {} <Error> BaseDaemon: 17. clickhouse-server(DB::ConvertingBlockInputStream::readImpl()+0x2e) [0x639161e]
2019.05.21 16:04:57.960090 [ 59 ] {} <Error> BaseDaemon: 18. clickhouse-server(DB::IBlockInputStream::read()+0x135) [0x5e338a5]
2019.05.21 16:04:57.960101 [ 59 ] {} <Error> BaseDaemon: 19. clickhouse-server(DB::FilterBlockInputStream::readImpl()+0x9e) [0x63aea4e]
2019.05.21 16:04:57.960112 [ 59 ] {} <Error> BaseDaemon: 20. clickhouse-server(DB::IBlockInputStream::read()+0x135) [0x5e338a5]
2019.05.21 16:04:57.960123 [ 59 ] {} <Error> BaseDaemon: 21. clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x1a) [0x63adeca]
2019.05.21 16:04:57.960134 [ 59 ] {} <Error> BaseDaemon: 22. clickhouse-server(DB::IBlockInputStream::read()+0x135) [0x5e338a5]
2019.05.21 16:04:57.960148 [ 59 ] {} <Error> BaseDaemon: 23. clickhouse-server(DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::thread(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long)+0x28d) [0x63d8e8d]
2019.05.21 16:04:57.960168 [ 59 ] {} <Error> BaseDaemon: 24. clickhouse-server(_ZZN20ThreadFromGlobalPoolC4IZN2DB23ParallelInputsProcessorINS1_35ParallelAggregatingBlockInputStream7HandlerEE7processEvEUlvE_JEEEOT_DpOT0_ENKUlvE_clEv+0x59) [0x63d9669]
2019.05.21 16:04:57.960185 [ 59 ] {} <Error> BaseDaemon: 25. clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x187) [0x68d7947]
2019.05.21 16:04:57.960201 [ 59 ] {} <Error> BaseDaemon: 26. clickhouse-server() [0x745371f]
2019.05.21 16:04:57.960214 [ 59 ] {} <Error> BaseDaemon: 27. /lib64/libpthread.so.0(+0x7e25) [0x7fb8035c8e25]

**Comment by 4ertus2** [comment]
It looks like we in ANY INNER JOIN. Do you have the query that leads to the crash? Do you use both the right and the left join key columns in the query?

**Comment by yxjsnj2018** [comment]
The problem was found.
Wrong SQL:
====================================================
select 
....
 ) AS u  
 ANY INNER JOIN (SELECT * FROM v_cur_pre_shift ) AS v 
 USING (shift_code, shift_date) 
 WHERE (u.cur_date >= v.begin_times) AND (u.cur_date < **end_times**) 
====================================================

Correct SQL
====================================================
select 
....
 ) AS u  
 ANY INNER JOIN (SELECT * FROM v_cur_pre_shift ) AS v 
 USING (shift_code, shift_date) 
 WHERE (u.cur_date >= v.begin_times) AND (u.cur_date < **v.end_times**) 
====================================================
Thanks.:)

**Comment by filimonov** [comment]
Reopening. (ClickHouse should not crash even if query is wrong)

**Comment by 4ertus2** [comment]
Cannot reproduce the issue. Can you modify this sample into crashed variant?

```
CREATE TABLE t
(
    shift_code UInt32,
    shift_date UInt32,
    cur_date UInt32,
    begin_times UInt32,
    end_times UInt32
) Engine = Memory;

INSERT INTO t SELECT number as shift_code, number as shift_date, number as cur_date, number as begin_times, number as end_times FROM numbers(10);

SELECT cur_date FROM (SELECT * FROM t) as u
ANY INNER JOIN (SELECT * FROM t) AS v
USING (shift_code, shift_date)
WHERE (u.cur_date >= v.begin_times) AND (u.cur_date <= end_times);
```

**Comment by filimonov** [comment]
On altinity build syntethic sample is also working propely.
