### ISSUE TITLE
outdated version.cmake content

### ISSUE THREAD

**Issue by ajax16384** [yandex/ClickHouse#5370]
version.cmake inside release tags contains outdated version values.

repro:
trying to build v19.5.3.8 under gentoo (https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-db/clickhouse/clickhouse-19.5.3.8.ebuild) will produce app image with 19.5.3.1 version string, cause ebuild pulls https://github.com/yandex/ClickHouse/archive/v19.5.3.8-stable.zip which contains outdated version: https://github.com/yandex/ClickHouse/blob/v19.5.3.8-stable/dbms/cmake/version.cmake

**Comment by alesapin** [comment]
Fourth number in version doesn't mean anything in releases. It's uniquely determined by third number. But I'll try to fix this in our CI.

**Comment by ajax16384** [comment]
I am not gentoo ebuild maintainer. Stable release creation is not gentoo specific issue. I think any v*-stable.zip archive should contain appropriate version string, so version.cmake commit like version tagging is just another preparation before release (there is no uglification).

**Comment by alesapin** [comment]
Fixed for stable and prestable releases since v19.7.5.27-stable.
