### ISSUE TITLE
extra single quote added when inserting a string column through JDBC

### ISSUE THREAD

**Issue by bill1234567890abc** [yandex/ClickHouse#5375]
**Describe the bug**
I insert some records to a table with following columns:

CREATE TABLE IF NOT EXISTS test.books(id UInt16, name String) engine = MergeTree PARTITION BY (id % 16) ORDER BY id SETTINGS index_granularity = 8192

The inserted records are added extra single quotes as below.

node1 :) SELECT * FROM cpeople;

SELECT *
FROM cpeople 

┌──id─┬─名字───────┐
│ 203 │ '罗马假日' │
└─────┴────────────┘
┌──id─┬─名字─────────┐
│ 202 │ '三个火枪手' │
└─────┴──────────────┘
┌──id─┬─名字─────┐
│ 201 │ '水浒传' │
└─────┴──────────┘

jdbc calling code looks like:
      ......
      conn = DriverManager.getConnection(DB_URL,USER,PASS);

      //STEP 4: Execute a query
      System.out.println("Creating statement...");
      PreparedStatement ps = conn.prepareStatement("INSERT INTO test.cpeople(\"id\", \"name\") VALUES (?, ?)");
      ps.setInt(1, 201);
      ps.setString(2, "水浒传");
      ps.addBatch();

      ps.clearParameters();
      ps.setInt(1, 202);
      ps.setString(2, "三个火枪手");
      ps.addBatch();

      ps.clearParameters();
      ps.setInt(1, 203);
      ps.setString(2, "罗马假日");
      ps.addBatch();
      ps.clearParameters();
      int[] results = ps.executeBatch();

      //STEP 5: Extract data from result set
      for (int i = 0; i < results.length; i++)
          System.out.print("res[" + i + "] : " + results[i] + "\n");
      
      //STEP 6: Clean-up environment
      ps.close();
      conn.close();

**How to reproduce**
see above

* Which ClickHouse server version to use
19.3.9

* Which interface to use, if matters
JDBC

* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/yandex/ClickHouse/blob/master/dbms/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

**Error message and/or stacktrace**

**Additional context**
I can avoid it by change insert statement to 
      PreparedStatement ps = conn.prepareStatement("INSERT INTO test.cpeople(id, name) VALUES (?, ?)");

But that will bring out another problem, that makes column names containing Chinese characters fail to be parsing, like example below.
      PreparedStatement ps = conn.prepareStatement("INSERT INTO test.cpeople(id, 书名) VALUES (?, ?)");

So I have to quote column name to use Chinese column name.

**Comment by bill1234567890abc** [comment]
I checked clickhouse jdbc source. It seems an issue in PreparedStatementParser.parseSQL()

**Comment by filimonov** [comment]
Can you make a pull request with fix to https://github.com/yandex/ClickHouse-jdbc project?

**Comment by bill1234567890abc** [comment]
This issuse was fixed in clickhouse-jdbc 0.1.51 , by PR #297 : Prepared statements: Support single and double quotes. 

I just need upgrade from 0.1.50 to latest 0.1.53.
