### ISSUE TITLE
DB::Exception: Unknown function JSONHas

### ISSUE THREAD

**Issue by nshah14285** [yandex/ClickHouse#5386]
We are using ClickHouse 19.6.2.11 stable version.

When we run query using JSON function, we are getting below error.

Query
`select JSONHas('{"a": "hello", "b": [-100, 200.0, 300]}', 'b', 4) = 0`

Error
> Received exception from server (version 19.6.2):
Code: 46. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Unknown function JSONHas. 

Similarly, we are getting same error for other JSON functions.

Is JSON function support ClickHouse 19.6.2.11 version?

Thanks,
Nishit

**Comment by alexey-milovidov** [comment]
No. The minimal version is 19.8.

**Comment by nshah14285** [comment]
Thanks for the update.
Version 19.8 release date?

**Comment by filimonov** [comment]
Before 19.6 you can use old-fashioned functions to work with JSON (those having visitParam prefix).

**Comment by filimonov** [comment]
> Version 19.8 release date?

Soon. Stay tuned! :)

Before release - you can try master build on non-prod environments.

https://github.com/yandex/ClickHouse/commits/master
-> find last commit with greenmark
-> click the greenmark
-> click the Detail link next to ClickHouse build check
-> pick debs from first row from the table (gcc-8, relwithdebuginfo, bundled, unspitted)
