### ISSUE TITLE
Cannot use SHA-256 in replication settings

### ISSUE THREAD

**Issue by gle4er** [yandex/ClickHouse#5441]
**Describe the bug**
When describe ClickHouse cluster in remote_servers, It doesn't recognize <password_256_sha> tag.

**How to reproduce**
* Which ClickHouse server version to use: 19.1.6
* Settings:
```       
<remote_servers>
    <test_cluster>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>host1</host>
                    <port>29000</port>
                    <user>replica</user>
                    <password_sha256_hex>SHA256 hex</password_sha256_hex>
                </replica>
                <replica>
                    <host>host2</host>
                    <port>29000</port>
                    <user>replica</user>
                    <password_sha256_hex>SHA256 hex</password_sha256_hex>
                </replica>
            </shard>
        </test_cluster>
    </remote_servers>
<remote_servers>
```
* Queries to run that lead to unexpected result
`select * from table_distributed;`

**Expected behavior**
I expected to receive no errors

**Error message and/or stacktrace**
```
Code: 194. DB::Exception: Received from host2:29000, 172.22.33.17. DB::Exception: Received from host1:29000, 172.22.33.9. DB::Exception: Password required for user replica. 
```
**Additional context**
If I replace `<password_sha256_hex>` to `<password>` - all queries works perfectly, no errors.

**Comment by den-crane** [comment]
password_sha256_hex is not supported against **remote_servers**.

**remote_servers**  uses these passwords to connect to other instances of CH. 
So there is only way is to set open password.

**Comment by filimonov** [comment]
Similar: #2416

**Comment by den-crane** [comment]
@filimonov you mean https://github.com/yandex/ClickHouse/issues/2290

**Comment by filimonov** [comment]
Yes, bad copy&paste :) Thanks.

**Comment by gle4er** [comment]
> password_sha256_hex is not supported against **remote_servers**.
> 
> **remote_servers** uses these passwords to connect to other instances of CH.
> So there is only way is to set open password.

Okay, I got it.
