### ISSUE TITLE
Loading Parquet through curl

### ISSUE THREAD

**Issue by georgantasp** [yandex/ClickHouse#5453]
I realize this is a new feature and perhaps loading through `clickhouse-client` is the only supported way. None-the-less...

**Describe the bug**
Errors are returned when trying to load parquet data with curl.

**How to reproduce**
* Which ClickHouse server version to use
19.6.2.11

* `CREATE TABLE` statements for all tables involved
```
echo "CREATE TABLE IF NOT EXISTS test(col1 Int32) ENGINE = MergeTree PARTITION BY col1 ORDER BY col1" | curl -s localhost:8123 -d @-
```
* Sample data for all these tables
```
echo "INSERT INTO test VALUES (1)" | curl -s localhost:8123 -d @-
```

* Queries to run that lead to unexpected result
```
# create a parquet file:
echo "SELECT * FROM test FORMAT Parquet" | curl -s localhost:8123 -d @- > out.pq
# try load it back:
cat out.pq | curl -s 'localhost:8123?query=INSERT%20INTO%20test%20FORMAT%20Parquet' -d @-
# yields
std::exception. Code: 1001, type: parquet::ParquetException, e.what() = Invalid parquet file. Corrupt footer., version = 19.6.2.11 (official build)
```
**Expected behavior**
Expect that the data is loaded same as clickhouse-client
```
cat out.pq | clickhouse-client --query="INSERT INTO test FORMAT Parquet"
```

**Error message and/or stacktrace**
From `/var/log/clickhouse-server/clickhouse-server.err.log`
```
2019.05.28 20:10:32.258740 [ 25 ] {73656d24-f854-4737-b888-4626a677865a} <Error> executeQuery: std::exception. Code: 1001, type: parquet::ParquetException, e.what() = Invalid parquet file. Corrupt footer., version = 19.6.2.11 (official build) (from 127.0.0.1:36012) (in query: INSERT INTO test FORMAT Parquet )
2019.05.28 20:10:32.259987 [ 25 ] {73656d24-f854-4737-b888-4626a677865a} <Error> HTTPHandler: std::exception. Code: 1001, type: parquet::ParquetException, e.what() = Invalid parquet file. Corrupt footer., version = 19.6.2.11 (official build)
```

**Additional context**
Tested and reproduced in docker.

**Comment by alexey-milovidov** [comment]
You have to use `--data-binary` instead of `-d` for curl.
Otherwise curl will mangle binary data.

**Comment by georgantasp** [comment]
My mistake. I thought `-d` was the proper alias. Thanks for the fast response!
