### ISSUE TITLE
SYSTEM FLUSH LOGS query doesn't flush on-the-fly log entries.

### ISSUE THREAD

**Issue by alexey-milovidov** [yandex/ClickHouse#5456]
If you execute a query and immediately execute `SYSTEM FLUSH LOGS`, the query may not appear in query_log.

See https://github.com/yandex/ClickHouse/issues/4518#issuecomment-485001233

**Comment by jangorecki** [comment]
2 weeks ago there was a PR merged that mentioned this issue, what is the current status of this?

**Comment by CurtizJ** [comment]
Fixed in #5685. Backported to 19.9, which soon will be released.
