### ISSUE TITLE
Merge Engine Bug

### ISSUE THREAD

**Issue by alpswjc** [yandex/ClickHouse#546]
Hi There 

Everyday we create a distributed table and also we have a merge table(merge engine) to combine all the distributed tables.

so there is the query , and it works well for distribute table
`select abc from distributed_table where id GLOBAL IN (select id from local_table table)`

but when we query merge table , we got an exception 
`select abc from merge_table where id GLOBAL IN (select id from local_table table)`

Code: 60. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Received from xxx.xxx.xxx.xxx:9000. DB::Exception: Table default.local doesn't exist..

if i understand GLOBAL IN correctly , this query will execute the subquery first and send to all the remote servers(shards), it doesn't require local_table to be exists in all remote servers.  please correct me if i am wrong. 

Thanks

**Comment by alpswjc** [comment]
Alex Zatelepin has confirmed its a bug

**Comment by ztlpn** [comment]
fix was released in v1.1.54245
