### ISSUE TITLE
user password question

### ISSUE THREAD

**Issue by gcw831** [yandex/ClickHouse#5460]
I do not set password for default user, Could anyone please tell me why I only use clickhouse-client connect to server use system login password?

**Comment by filimonov** [comment]
Sorry, it's very hard to understand the question due to poor translation to English.

If you can connect only from localhost most probably you need to adjust `<listen>` directive in your `/etc/clickhouse-server/config.xml`.

**Comment by gcw831** [comment]
I mean I do not set password for clickhouse user <default>, but 
![image](https://user-images.githubusercontent.com/11831924/58618632-acd8d280-82f5-11e9-93cd-c4e739fbb258.png)
then I find I can login with the password same as ubuntu shell login password, so I am confused.
![image](https://user-images.githubusercontent.com/11831924/58618710-e4e01580-82f5-11e9-9b67-e999bd2c6137.png)

Sorry for my poor english , do you know what I say

**Comment by gcw831** [comment]
@filimonov as above

**Comment by filimonov** [comment]
Look's like you have some non-empty password for `default` user.

Please examine / show the contents `/etc/clickhouse-server/users.xml` and files in  `/etc/clickhouse-server/users.d` subfolder.

**Comment by gcw831** [comment]
Thank you so much. I found the file default-password.xml in /etc/clickhouse-server/users.d。I only check user.xml before, while do not check this folder. Thank you!

**Comment by gcw831** [comment]
@filimonov
