### ISSUE TITLE
Question about query optimization on Functions

### ISSUE THREAD

**Issue by yingfeng** [yandex/ClickHouse#5474]
Suppose I want to implement a function to be applied to each row in the WHERE clause, and the first argument of the function comes from the results from a subquery, while the second argument comes from the column value, just like folllowing:

`select count(*) from table where FUNCTION((select groupArray(userid) from table2), table.id);`

Could Clickhouse guarantee the subquery(just `select groupArray(userid) from table2`) could only be executed once?

**Comment by alexey-milovidov** [comment]
These type of subqueries (independent subqueries that return a single value) are named "scalar subqueries". They are executed only once. Yes, it is guaranteed.
