### ISSUE TITLE
Slow performance of scalar subqueries

### ISSUE THREAD

**Issue by yingfeng** [yandex/ClickHouse#5475]
I use `mergetree` as the table engine, while the data comes from [here](https://tech.marksblogg.com/benchmarks.html) where the trips table contains around 700M records.
Here the query:

`select count(*) from trips where hasAny((select groupAny(id) from trips where id <1000), [id]);`

The reason of the above strange query is I want to write a bitmap Function like `hasAny`, and the first argument comes from ids from another huge table, and I need to verify the performance at first.

According to my previous question [5474](https://github.com/yandex/ClickHouse/issues/5474), the scala subquery of `select groupAny(id) from trips where id <1000)` is guaranteed to be executed once, while the subquery itself is pretty fast( sub second level), however, I could only see the lines of trips table could only be started to be scanned after above 1min, while the overall execution time of the query is around 2min or so. So what's happening during the first 1min before the table is started to be scanned?  Ideally, the above query time should be around 1min.

**Comment by alexey-milovidov** [comment]
Yes, there is a detail that negatively affects performance of this particular query.

The result of scalar subquery is substituted to the parent query in AST level. When you have large array, it will create large temporary value, that will be placed in AST and interpreted.

It is going to be fixed in https://github.com/yandex/ClickHouse/pull/4914 or subsequent PRs.

**Comment by yingfeng** [comment]
@alexey-milovidov 
So it means if the result set of subquery is large, in the above scenario, if the subquery is changed to `select groupbitmapstate(id) from trips`, although I use bitmap to store ids which is a kind of compressed format, the practical memory consumption is still high?

**Comment by alexey-milovidov** [comment]
It depend on the size of the groupBitmap state.

**Comment by yingfeng** [comment]
@alexey-milovidov @KochetovNicolai 
The scalar subqueries' performance issue still exist even if I turn on the switch : 
```
SET experimental_use_processors = 1
```
The version of ClickHouse is `v19.13.4.32-stable` and `v19.14.3.3-stable`. The cpu occupation is still kept 100% for a long time before the progress bar of rows processed has appeared. For example:


```
CREATE TABLE user_segments ( \
    tag_id String, \
    ids AggregateFunction(groupBitmap, UInt32) \
) engine=ReplacingMergeTree() \
ORDER BY (tag_id);

select count(cab_type_id) from trips where bitmapContains((
select
 ids
from
 user_segments
where
 tag_id = 'member_origin_channel_NA'),
toUInt32(id))
group by vendor_id;
```
The table `trips` contains over 700M rows, the above query will take 20s on my machine, however, the progress bar could not be seen on the cli until 18s later, with an only 100% CPU occupation, which means 90% of the query time has not been executed in parallel. 

What happens during that period of this kind of scalar subquery? Could such overhead be improved further?
