### ISSUE TITLE
Add Decimal type support to external Dictionary and Operators 

### ISSUE THREAD

**Issue by SergioSafonov** [yandex/ClickHouse#5483]
As i understand, i can't use Decimal type as a attribute in External dictionaries and in operators (a * b as attribute_name). Only Int, UInt and Float as numeric types.
Why it does and it possible to add support Decimal type?

**Comment by 4ertus2** [comment]
It's possible to use Decimals in dictionaries in master #5343
What do you mean saying you cannot use Decimals in operators?

**Comment by SergioSafonov** [comment]
Sorry, i'm just trying to multiply Decimal and Float values
but i was confused about error report:
>  Illegal types Decimal(18, 3) and Float64 of arguments of function multiply (version 19.5.3.8 (official build))

and also i read about this in documentation about support of multiply operations only for all Int and UInt types and Float64 only (don't remember where).

**Comment by 4ertus2** [comment]
It's expected behaviour. If you do need strict values you use Decimal. If you do not need strict values you use Floats. If you use both Float and Decimal it's not cleat what result do you want: strict or not. You should explicitly cast one of arguments to say it.
