### ISSUE TITLE
Modifying TTL on ReplicatedMergeTree does not seem to work

### ISSUE THREAD

**Issue by iameugenejo** [yandex/ClickHouse#5494]
**Describe the bug**
Modifying TTL on ReplicatedMergeTree
* does not work,
* does not show the added TTL option,
* or does not throw an error if it's not supported.

**How to reproduce**
* Which ClickHouse server version to use
`19.6.2.11`

* Which interface to use, if matters
`clickhouse-client`

* Non-default settings, if any
`n/a`

* `CREATE TABLE` statements for all tables involved
```sql
CREATE TABLE test.repl1 (
    `dt` DateTime, 
    `test` Int64
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/test.repl1', '{replica}') 
ORDER BY dt 
SETTINGS index_granularity = 8192;
```

* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/yandex/ClickHouse/blob/master/dbms/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
`n/a`
* Queries to run that lead to unexpected result
```sql
ALTER TABLE test.repl1 MODIFY TTL dt + INTERVAL 1 DAY;
```

**Expected behavior**

`SHOW CREATE TABLE test.repl1;` should show `TTL dt + toIntervalDay(1)` but it doesn't.

**Error message and/or stacktrace**
`n/a`

**Additional context**

**Comment by alexey-milovidov** [comment]
https://github.com/yandex/ClickHouse/pull/5539

**Comment by alexey-milovidov** [comment]
Fixed in master and will be available in next testing release within a day.
