### ISSUE TITLE
Python driver

### ISSUE THREAD

**Issue by anaderi** [yandex/ClickHouse#55]
Are there any estimations on making python driver for ClickHouse?
Or.. what is the best way of running queries from Python?

**Comment by alexey-milovidov** [comment]
There is 3rd party python driver: https://github.com/Infinidat/infi.clickhouse_orm

> Or.. what is the best way of running queries from Python? 

Try this driver. 
Otherwise, simply send requests with `urllib2`.

**Comment by anaderi** [comment]
will give it a try, thanks! 
was not very obvious where to look for the driver though ))

**Comment by alexey-milovidov** [comment]
Added to documentation: https://clickhouse.yandex/reference_en.html#Third-party%20client%20libraries
