### ISSUE TITLE
failed to build ClickHouse-19.7.3.9 on Mac 10.14.5

### ISSUE THREAD

**Issue by liaorui** [yandex/ClickHouse#5511]
I built the ClickHouse-19.7.3.9-stable.

**Operating system**
Darwin liaor-mac.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

Mac OS 10.14.5 (18F132)

**Cmake version**
cmake version 3.14.3

**Ninja version**
1.9.0

**Compiler name and version**
gcc-8 (Homebrew GCC 8.3.0) 8.3.0
g++-8 (Homebrew GCC 8.3.0) 8.3.0

**Full cmake and/or ninja output**
cmake .. -DCMAKE_CXX_COMPILER=`which g++-8` -DCMAKE_C_COMPILER=`which gcc-8`
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Check for working C compiler: /usr/local/bin/gcc-8
-- Check for working C compiler: /usr/local/bin/gcc-8 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Check for working CXX compiler: /usr/local/bin/g++-8
-- Check for working CXX compiler: /usr/local/bin/g++-8 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- IPO/LTO not enabled.
-- CMAKE_BUILD_TYPE is not set, set to default = RELWITHDEBINFO
-- CMAKE_BUILD_TYPE: RELWITHDEBINFO
-- Disabling compiler -pipe option (have only 2042 mb of memory)
-- Performing Test HAVE_SSE41
-- Performing Test HAVE_SSE41 - Success
-- Performing Test HAVE_SSE42
-- Performing Test HAVE_SSE42 - Success
-- Performing Test HAVE_SSSE3
-- Performing Test HAVE_SSSE3 - Success
-- Performing Test HAVE_AVX
-- Performing Test HAVE_AVX - Success
-- Performing Test HAVE_AVX2
-- Performing Test HAVE_AVX2 - Success
-- Performing Test HAVE_POPCNT
-- Performing Test HAVE_POPCNT - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Performing Test HAVE_NO_PIE
-- Performing Test HAVE_NO_PIE - Failed
-- Tests are enabled
-- Building for: Darwin-18.6.0 x86_64  ; USE_STATIC_LIBRARIES=ON MAKE_STATIC_LIBRARIES=ON SPLIT_SHARED= UNBUNDLED=OFF CCACHE=/usr/local/bin/ccache 3.4.3
CMake Warning at cmake/find_ssl.cmake:11 (message):
  submodule contrib/ssl is missing.  to fix try run:

   git submodule update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:286 (include)

CMake Warning at cmake/find_ssl.cmake:24 (message):
  Disable USE_STATIC_LIBRARIES if you have linking problems with OpenSSL on
  MacOS
Call Stack (most recent call first):
  CMakeLists.txt:286 (include)

-- Found OpenSSL: /usr/local/opt/openssl/lib/libcrypto.a (found version "1.0.2r")  
-- Using ssl=1: /usr/local/opt/openssl/include : /usr/local/opt/openssl/lib/libssl.a;/usr/local/opt/openssl/lib/libcrypto.a
-- The following ICU libraries were not found:
--   i18n (required)
--   uc (required)
--   data (required)
-- Failed to find all ICU components (missing: ICU_INCLUDE_DIR ICU_LIBRARY _ICU_REQUIRED_LIBS_FOUND) 
-- Build without ICU (support for collations and charset conversion functions will be disabled)
CMake Warning at cmake/find_boost.cmake:5 (message):
  submodules in contrib/boost is missing.  to fix try run:

   git submodule update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:289 (include)

-- Boost version: 1.69.0
-- Found the following Boost libraries:
--   program_options
--   system
--   filesystem
--   thread
--   regex
--   chrono
--   date_time
--   atomic
-- Using Boost: /usr/local/include : /usr/local/lib/libboost_program_options-mt.a,/usr/local/lib/libboost_system-mt.a,/usr/local/lib/libboost_filesystem-mt.a,/usr/local/lib/libboost_regex-mt.a
-- Using zlib-ng: /Users/liaorui/github/ClickHouse-19.7.3.9-stable/contrib/zlib-ng;/Users/liaorui/github/ClickHouse-19.7.3.9-stable/build/contrib/zlib-ng : zlibstatic
CMake Warning at cmake/find_zstd.cmake:4 (message):
  submodule contrib/zstd is missing.  to fix try run:

   git submodule update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:291 (include)

-- Using zstd: /Users/liaorui/github/ClickHouse-19.7.3.9-stable/contrib/zstd/lib : zstd
-- Using termcap: /usr/lib/libtermcap.dylib
CMake Warning at cmake/find_poco.cmake:5 (message):
  submodule contrib/poco is missing.  to fix try run:

   git submodule update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:296 (include)

-- Looking for Poco install directory structure.
-- Poco: Could not find Poco install directory
-- Using Poco:  : ,,,,,,,,,,; MongoDB=, DataODBC=, NetSSL=
CMake Warning at cmake/find_lz4.cmake:5 (message):
  submodule contrib/lz4 is missing.  to fix try run:

   git submodule update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:297 (include)

-- Using lz4: /usr/local/include : /usr/local/lib/liblz4.a
CMake Warning at cmake/find_xxhash.cmake:4 (message):
  can not use internal xxhash without internal lz4
Call Stack (most recent call first):
  CMakeLists.txt:298 (include)

-- Using xxhash=0: XXHASH_INCLUDE_DIR-NOTFOUND : XXHASH_LIBRARY-NOTFOUND
-- Using sparsehash: /Users/liaorui/github/ClickHouse-19.7.3.9-stable/contrib/libsparsehash
-- Using rt: apple_rt
-- Using line editing libraries (readline): /usr/local/opt/readline/include : /usr/local/opt/readline/lib/libreadline.a;/usr/lib/libtermcap.dylib
-- Performing Test HAVE_READLINE_HISTORY
-- Performing Test HAVE_READLINE_HISTORY - Success
-- Using re2: /Users/liaorui/github/ClickHouse-19.7.3.9-stable/contrib/re2 : re2;  : re2_st
CMake Warning at cmake/find_rdkafka.cmake:7 (message):
  submodule contrib/cppkafka is missing.  to fix try run:

   git submodule update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:304 (include)

-- Using librdkafka=:  :  
CMake Warning at cmake/find_capnp.cmake:20 (message):
  submodule contrib/capnproto is missing.  to fix try run:

   git submodule update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:305 (include)

-- Build without capnp (support for Cap'n Proto format will be disabled)
-- Using cpuid=1: /Users/liaorui/github/ClickHouse-19.7.3.9-stable/contrib/libcpuid/include : cpuid
-- Using libgsasl: LIBGSASL_INCLUDE_DIR-NOTFOUND : LIBGSASL_LIBRARY-NOTFOUND
CMake Warning at cmake/find_libxml2.cmake:5 (message):
  submodule contrib/libxml2 is missing.  to fix try run:

   git submodule update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:312 (include)

-- Found LibXml2: /usr/lib/libxml2.dylib (found version "2.9.4") 
-- Using libxml2: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/libxml2 : /usr/lib/libxml2.dylib
CMake Warning at cmake/find_brotli.cmake:9 (message):
  submodule contrib/brotli is missing.  to fix try run:

   git submodule update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:313 (include)

-- Using brotli=: BROTLI_INCLUDE_DIR-NOTFOUND : 
CMake Warning at cmake/find_protobuf.cmake:9 (message):
  submodule contrib/protobuf is missing.  to fix try run:

   git submodule update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:314 (include)

-- Found Protobuf: /usr/local/lib/libprotobuf.a (found version "3.5.1") 
-- Using protobuf=1: /usr/local/include : /usr/local/lib/libprotobuf.a
-- Using pdqsort: /Users/liaorui/github/ClickHouse-19.7.3.9-stable/contrib/pdqsort
-- Using hdfs3=:  : 
-- Using consistent-hashing:  : consistent-hashing
CMake Warning at cmake/find_base64.cmake:3 (message):
  submodule contrib/base64 is missing.  to fix try run:

   git submodule update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:318 (include)

CMake Warning at cmake/find_hyperscan.cmake:11 (message):
  submodule contrib/hyperscan is missing.  to fix try run:

   git submodule update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:319 (include)

-- Using hyperscan=: HYPERSCAN_INCLUDE_DIR-NOTFOUND : HYPERSCAN_LIBRARY-NOTFOUND
-- Using cityhash:  : cityhash
-- Using farmhash:  : farmhash
-- Using metrohash: /Users/liaorui/github/ClickHouse-19.7.3.9-stable/contrib/libmetrohash/src : metrohash
-- Using btrie:  : btrie
-- Using double-conversion: /Users/liaorui/github/ClickHouse-19.7.3.9-stable/contrib/double-conversion : double-conversion
CMake Warning at cmake/find_parquet.cmake:11 (message):
  submodule contrib/arrow (required for Parquet) is missing.  to fix try run:

   git submodule update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:326 (include)

-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'arrow'
--   No package 'arrow' found
-- Could not find the Arrow library. Looked for headers in , and for libs in 
-- Checking for module 'parquet'
--   No package 'parquet' found
--  Could not find the parquet library. Looked in  system search paths.
-- Building without Parquet support
CMake Warning at cmake/find_gtest.cmake:5 (message):
  submodule contrib/googletest is missing.  to fix try run:

   git submodule update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:328 (include)

-- Found GTest: /usr/local/lib/libgtest.a  
-- Using gtest=1: /usr/local/include : /usr/local/lib/libgtest.a;/usr/local/lib/libgtest_main.a : 
CMake Warning at libs/libcommon/cmake/find_cctz.cmake:4 (message):
  submodule contrib/cctz is missing.  to fix try run:

   git submodule update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:334 (include)

-- Using cctz: /usr/local/include : /usr/local/lib/libcctz.a
-- Using mysqlclient=1: /usr/local/include;/usr/local/include/mysql : ; staticlib=/usr/local/lib/libmysqlclient.a
-- Performing Test HAVE_UNW_INIT_LOCAL2
-- Performing Test HAVE_UNW_INIT_LOCAL2 - Failed
-- Using unwind=:  : 
-- compiler C   = /usr/local/bin/gcc-8  -fdiagnostics-color=always  -msse4.1 -msse4.2 -mpopcnt -fno-omit-frame-pointer  -Wall  -O2 -g -DNDEBUG -O3 
-- compiler CXX = /usr/local/bin/g++-8  -fdiagnostics-color=always  -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall  -Wnon-virtual-dtor -O2 -g -DNDEBUG -O3 
-- LINKER_FLAGS =  
CMake Error at contrib/zstd-cmake/CMakeLists.txt:46 (FILE):
  FILE failed to open for reading (No such file or directory):

    /Users/liaorui/github/ClickHouse-19.7.3.9-stable/contrib/zstd/lib/zstd.h

-- ZSTD VERSION ..
CMake Error at contrib/CMakeLists.txt:27 (add_subdirectory):
  The source directory

    /Users/liaorui/github/ClickHouse-19.7.3.9-stable/contrib/re2

  does not contain a CMakeLists.txt file.

CMake Error at contrib/re2_st/CMakeLists.txt:8 (get_target_property):
  get_target_property() called with non-existent target "re2".

CMake Error at contrib/CMakeLists.txt:33 (add_subdirectory):
  The source directory

    /Users/liaorui/github/ClickHouse-19.7.3.9-stable/contrib/double-conversion

  does not contain a CMakeLists.txt file.

CMake Error at contrib/CMakeLists.txt:72 (add_subdirectory):
  The source directory

    /Users/liaorui/github/ClickHouse-19.7.3.9-stable/contrib/zlib-ng

  does not contain a CMakeLists.txt file.

CMake Error at contrib/CMakeLists.txt:75 (target_compile_definitions):
  Cannot specify compile definitions for target "zlib" which is not built by
  this project.

CMake Error at contrib/CMakeLists.txt:76 (target_compile_definitions):
  Cannot specify compile definitions for target "zlibstatic" which is not
  built by this project.

CMake Error at contrib/CMakeLists.txt:78 (target_compile_definitions):
  Cannot specify compile definitions for target "zlib" which is not built by
  this project.

CMake Error at contrib/CMakeLists.txt:79 (target_compile_definitions):
  Cannot specify compile definitions for target "zlibstatic" which is not
  built by this project.

CMake Warning at libs/libcommon/CMakeLists.txt:81 (message):
  Non default allocator is disabled.  This is not recommended for production
  Linux builds.

-- /Users/liaorui/github/ClickHouse-19.7.3.9-stable/utils: Have 1968 megabytes of memory. Limiting concurrent linkers jobs to 1 and compiler jobs to OFF
-- /Users/liaorui/github/ClickHouse-19.7.3.9-stable/dbms: Have 1961 megabytes of memory. Limiting concurrent linkers jobs to 1 and compiler jobs to 1
-- Will build ClickHouse 19.7.3.1 revision 54419 
-- Using internal= compiler=: headers=/usr/share/clickhouse/headers/19.7.3.1 :  /usr/local/bin/clickhouse-clang  -fdiagnostics-color=always  -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall  -Wnon-virtual-dtor -Wextra -Werror -O2 -g -DNDEBUG -O3  -std=c++1z -x c++ -march=native -fPIC -fvisibility=hidden -fno-implement-inlines -nostdinc -nostdinc++ -Wno-unused-command-line-argument -Bprefix=/usr/share/clickhouse -isysroot=/usr/share/clickhouse/headers/19.7.3.1; clickhouse-lld
-- Target check already exists
-- Configuring incomplete, errors occurred!
See also "/Users/liaorui/github/ClickHouse-19.7.3.9-stable/build/CMakeFiles/CMakeOutput.log".
See also "/Users/liaorui/github/ClickHouse-19.7.3.9-stable/build/CMakeFiles/CMakeError.log".

**CMakeError.log**
Performing C++ SOURCE FILE Test HAVE_NO_PIE failed with the following output:
Change Dir: /Users/liaorui/github/ClickHouse-19.7.3.9-stable/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/local/bin/ninja cmTC_bbf73 
[1/2] Building CXX object CMakeFiles/cmTC_bbf73.dir/src.cxx.o
FAILED: CMakeFiles/cmTC_bbf73.dir/src.cxx.o 
/usr/local/bin/g++-8    -fdiagnostics-color=always  -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall  -Wnon-virtual-dtor -DHAVE_NO_PIE -no-pie -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -o CMakeFiles/cmTC_bbf73.dir/src.cxx.o -c src.cxx
g++-8: error: unrecognized command line option '-no-pie'
ninja: build stopped: subcommand failed.

Source file was:

        int main() {
            return 0;
        }
        
Performing C++ SOURCE FILE Test HAVE_UNW_INIT_LOCAL2 failed with the following output:
Change Dir: /Users/liaorui/github/ClickHouse-19.7.3.9-stable/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/local/bin/ninja cmTC_310a7 
[1/2] Building CXX object CMakeFiles/cmTC_310a7.dir/src.cxx.o
FAILED: CMakeFiles/cmTC_310a7.dir/src.cxx.o 
/usr/local/bin/g++-8    -fdiagnostics-color=always  -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall  -Wnon-virtual-dtor -DHAVE_UNW_INIT_LOCAL2 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -o CMakeFiles/cmTC_310a7.dir/src.cxx.o -c src.cxx
In file included from src.cxx:2:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/ucontext.h:43:2: error: #error The deprecated ucontext routines require _XOPEN_SOURCE to be defined
 #error The deprecated ucontext routines require _XOPEN_SOURCE to be defined
  ^~~~~
src.cxx: In function 'int main()':
src.cxx:6:8: error: 'ucontext_t' was not declared in this scope
        ucontext_t context;
        ^~~~~~~~~~
src.cxx:6:8: note: suggested alternative: 'unw_context_t'
        ucontext_t context;
        ^~~~~~~~~~
        unw_context_t
src.cxx:8:34: error: 'context' was not declared in this scope
        unw_init_local2(&cursor, &context, UNW_INIT_SIGNAL_FRAME);
                                  ^~~~~~~
src.cxx:8:34: note: suggested alternative: 'constexpr'
        unw_init_local2(&cursor, &context, UNW_INIT_SIGNAL_FRAME);
                                  ^~~~~~~
                                  constexpr
src.cxx:8:43: error: 'UNW_INIT_SIGNAL_FRAME' was not declared in this scope
        unw_init_local2(&cursor, &context, UNW_INIT_SIGNAL_FRAME);
                                           ^~~~~~~~~~~~~~~~~~~~~
src.cxx:8:8: error: 'unw_init_local2' was not declared in this scope
        unw_init_local2(&cursor, &context, UNW_INIT_SIGNAL_FRAME);
        ^~~~~~~~~~~~~~~
src.cxx:8:8: note: suggested alternative: 'unw_init_local'
        unw_init_local2(&cursor, &context, UNW_INIT_SIGNAL_FRAME);
        ^~~~~~~~~~~~~~~
        unw_init_local
ninja: build stopped: subcommand failed.

Source file was:

    #include <ucontext.h>
    #define UNW_LOCAL_ONLY
    #include <libunwind.h>
    int main () {
       ucontext_t context;
       unw_cursor_t cursor;
       unw_init_local2(&cursor, &context, UNW_INIT_SIGNAL_FRAME);
       return 0;
    }

**Comment by liaorui** [comment]
Can anyone help?  thanks.

**Comment by proller** [comment]
You should fetch submodules before running cmake: `git submodule update --init --recursive`

**Comment by liaorui** [comment]
@proller , after `git submodule update --init --recursive`,  there is another error:

`../dbms/src/IO/tests/gtest_aio_seek_back_after_eof.cpp: In member function 'virtual void ReadBufferAIOTest_TestReadAfterAIO_Test::TestBody()':
../dbms/src/IO/tests/gtest_aio_seek_back_after_eof.cpp:42:21: error: 'DB' is not a namespace-name
     using namespace DB;
                     ^~
../dbms/src/IO/tests/gtest_aio_seek_back_after_eof.cpp:42:23: error: expected namespace-name before ';' token
     using namespace DB;
                       ^
../dbms/src/IO/tests/gtest_aio_seek_back_after_eof.cpp:46:5: error: 'ReadBufferAIO' was not declared in this scope
     ReadBufferAIO testbuf(file_path);
     ^~~~~~~~~~~~~
../dbms/src/IO/tests/gtest_aio_seek_back_after_eof.cpp:51:25: error: 'testbuf' was not declared in this scope
     size_t total_read = testbuf.read(newdata.data(), newdata.length());
                         ^~~~~~~
../dbms/src/IO/tests/gtest_aio_seek_back_after_eof.cpp:51:25: note: suggested alternative: 'setbuf'
     size_t total_read = testbuf.read(newdata.data(), newdata.length());
                         ^~~~~~~
                         setbuf
ninja: build stopped: subcommand failed.`

Any suggestion?  thanks.

**Comment by proller** [comment]
This bug already fixed in master : https://github.com/yandex/ClickHouse/commit/b9385f9620d26808279b330e7bea8b03f48adbc6

**Comment by liaorui** [comment]
@proller done!  thanks.
