### ISSUE TITLE
Open zh PDF file show that unreadable text.

### ISSUE THREAD

**Issue by andyyzh** [yandex/ClickHouse#5532]
(you don't have to strictly follow this form)

**How to reproduce**
open flowing link:
https://clickhouse.yandex/docs/zh/single/clickhouse_zh.pdf

Then displays unreadable text, not chinese text.

**Comment by andyyzh** [comment]
it is ready.

**Comment by blinkov** [comment]
Yes, fixed a while ago, but forgot to close in time.
