### ISSUE TITLE
ALTER TABLE UPDATE JOIN

### ISSUE THREAD

**Issue by audricbizouarn** [yandex/ClickHouse#5538]
Hello, is there a way to make the following request?

ALTER TABLE table1 INNER JOIN table2 ON table1.id = table2.id UPDATE table1.name = table2.name

thanks.

**Comment by alex-zaitsev** [comment]
Use Join engine table. See https://stackoverflow.com/questions/55764093/updating-rows-with-values-from-another-table-in-clickhouse

**Comment by audricbizouarn** [comment]
Hello, thank you very much for your answer. So I made the following requests:

CREATE TABLE table2_join as table2 Engine = Join(ANY, INNER, id)
INSERT INTO table2_join SELECT * from table2

When I do 
ALTER TABLE table1 UPDATE name= joinGet('tabe2_join', 'name', id)
I have the following error
Code: 49. DB::Exception: Received from localhost:9000, ::1. DB::Exception: StorageJoin doesn't contain column name.

Do you see where the problem may come from?
Thanks

**Comment by peaksnail** [comment]
hi 

I create a Join table with multi join key, and It failed with tips: 

joinGet only supports StorageJoin containing exactly one key 

tables 
``` 
 CREATE TABLE stock_temp (`storeId` String, `warehouseId` String, `goodsId` String, `stock` Int32) ENGINE = Join(ANY, LEFT, storeId, warehouseId, goodsId)
```

**Comment by ygj6** [comment]
```
drop table if exists one;
CREATE TABLE one (`id` UInt32,`val` UInt32,`name` String)
ENGINE = MergeTree()
order by id;
insert into one (id, val) values (1,11),(2,12),(3,13);

drop table if exists two;
CREATE TABLE two (`id` UInt32,`word` String)
ENGINE = Join(ANY, LEFT , id);
insert into two values (1,'one'), (3,'three'),(5,'five');

alter table one update name = joinGet('two', 'word', id) where name = '';
```
I want to update the table `one`. But there's no change here. What did I do wrong?

**Comment by ygj6** [comment]
@alex-zaitsev, @audricbizouarn, Could you give me some advice please?
