### ISSUE TITLE
Memory growth/DFA out of memory

### ISSUE THREAD

**Issue by lfundaro** [yandex/ClickHouse#5551]
We have a situation when clickhouse starts allocating huge amount of memory and at the same time we see hundreds of logs with:

```
../contrib/re2/re2/re2.cc:711: DFA out of memory: size 35192, bytemap range 67, list count 29039
```

The server has 20GB available of allocatable memory, and while facing this problem, allocation reaches up to 19GB and it becomes unresponsive. 

**Which ClickHouse server version to use**
18.6.0

**Additional context**
We also see at the same time a spike of `MemoryTrackingForMerges`. 

Can you guys please give some hints on how to further debug this and eventually understand the root cause. 

Thank you !

**Comment by filimonov** [comment]
That warning is related to regular expression engine.
Do you have some complicated regexps in you DEFAULT expressions?

Can you check what exactly ClickHouse doing by examing `/var/log/clickhouse-server/clickhouse-server.log` and provide the create statement of the table which was processed at that time?

**Comment by den-crane** [comment]
Seems like CompiledExpressions leak.
Check select * from system.asynchronous_metrics where metric = 'CompiledExpressionCacheCount'
https://github.com/yandex/ClickHouse/issues/3976
And set` <compile_expressions>0</compile_expressions>` in user's profiles.

**Comment by alexey-milovidov** [comment]
You should upgrade to version 19.7.

**Comment by lfundaro** [comment]
> Seems like CompiledExpressions leak.
> Check select * from system.asynchronous_metrics where metric = 'CompiledExpressionCacheCount'
> #3976
> And set` <compile_expressions>0</compile_expressions>` in user's profiles.

this one gives me nothing as output. I was checking the issue you mentioned and the graphs there looked very similar to mines. You get a steady grow of memory and then a sudden drop. Maybe I will try to follow @alexey-milovidov suggestion of upgrading clickhouse, since that version already has the fix of the issue you reference.

**Comment by den-crane** [comment]
Then it's not the #3976 compile_expressions leak

**Comment by alexey-milovidov** [comment]
> ../contrib/re2/re2/re2.cc:711: DFA out of memory

These messages does not relate to high memory usage, because `re2` has it's own memory limit.
Messages were removed in recent versions.

**Comment by alexey-milovidov** [comment]
@lfundaro Does the issue present in recent ClickHouse versions?
