### ISSUE TITLE
LIMIT BY + GROUP BY inside of MV dosn`t work?

### ISSUE THREAD

**Issue by RudanovskiyM** [yandex/ClickHouse#5552]
Initials:

CREATE TABLE tbl_test
(
    dt_     DateTime DEFAULT now(),
    dt_create Date default today(),
    user_id   UInt32,
    item_id   UInt32,
    score     Float64
) ENGINE = ReplacingMergeTree(dt_)
    PARTITION BY dt_create
    ORDER BY (user_id, dt_create, item_id);

INSERT INTO tbl_test(dt_create, user_id, item_id, score)
VALUES
('2019-05-27', 100, 111, 0.811),
('2019-05-27', 100, 112, 0.812),
('2019-05-27', 100, 113, 0.813),
('2019-05-27', 100, 114, 0.814),
('2019-05-27', 100, 115, 0.815),
('2019-05-27', 100, 116, 0.816),
('2019-05-27', 100, 117, 0.817),
('2019-05-27', 100, 118, 0.818),
('2019-05-27', 100, 119, 0.819);

Let`s create two MVs pupulated from the existing values:

CREATE MATERIALIZED VIEW mv_test_1
ENGINE = ReplacingMergeTree(dt_) PARTITION BY dt_create ORDER BY (user_id, dt_create)
POPULATE AS
SELECT t.dt_create, t.user_id, arrayDistinct(groupArray(t.item_id)) AS item_ids, max(t.dt_) as dt_
FROM (SELECT dt_, dt_create, user_id, item_id
    FROM tbl_test
    ORDER BY dt_create DESC, user_id ASC, score DESC
    LIMIT 3 BY dt_create, user_id) as t
GROUP BY t.dt_create, t.user_id;

SELECT * FROM mv_test_1 FINAL;
┌──dt_create─┬─user_id─┬─item_ids────────────┬───────────dt_─┐
│ 2019-05-27   │     100      │ [119,118,117]                         │ 2019-06-07 12:32:49  │

The result is expected.

CREATE MATERIALIZED VIEW mv_test_2
ENGINE = ReplacingMergeTree(dt_) PARTITION BY dt_create ORDER BY (user_id, dt_create, item_id)
POPULATE AS
SELECT dt_, dt_create, user_id, item_id
    FROM tbl_test
    ORDER BY dt_create DESC, user_id ASC, score DESC
    LIMIT 3 BY dt_create, user_id;

SELECT * FROM mv_test_2 FINAL;
┌─ ─────────dt_─┬─dt_create─┬user_id─┬─item_id ┐
│ 2019-06-07 12:32:49 │ 2019-05-27 │     100   │     117    │
│ 2019-06-07 12:32:49 │ 2019-05-27 │     100   │     118    │
│ 2019-06-07 12:32:49 │ 2019-05-27 │     100   │     119    │

The result is expected.

Lets insert more values when the MVs was created

INSERT INTO tbl_test(dt_create, user_id, item_id, score)
VALUES
('2019-05-27', 200, 121, 0.811),
('2019-05-27', 200, 122, 0.812),
('2019-05-27', 200, 123, 0.813),
('2019-05-27', 200, 124, 0.814),
('2019-05-27', 200, 125, 0.815),
('2019-05-27', 200, 126, 0.816),
('2019-05-27', 200, 127, 0.817),
('2019-05-27', 200, 128, 0.818),
('2019-05-27', 200, 129, 0.819);

SELECT * FROM mv_test_1 FINAL;
┌─dt_create─┬user_id─┬─item_ids─────────────────┬────────────dt_─┐
│ 2019-05-27 │     100 │ [119,118,117]                                        │ 2019-06-07 12:32:49     │
│ 2019-05-27 │     200 │ [121,122,123,124,125,126,127,128,129]│ 2019-06-07 12:32:49     │
└────────┴────┴────────────────────────┴───────────────┘

SELECT * FROM mv_test_2 FINAL;
┌──────────dt_─┬──dt_create─┬─user_id─┬─item_id─┐
│ 2019-06-07 12:32:49 │ 2019-05-27 │     100       │     117      │
│ 2019-06-07 12:32:49 │ 2019-05-27 │     100       │     118      │
│ 2019-06-07 12:32:49 │ 2019-05-27 │     100       │     119      │
│ 2019-06-07 12:32:49 │ 2019-05-27 │     200       │     127      │
│ 2019-06-07 12:32:49 │ 2019-05-27 │     200       │     128      │
│ 2019-06-07 12:32:49 │ 2019-05-27 │     200       │     129      │
└─────────────┴────────┴───┴───┘

Why do we get so long item_ids array ([121,122,123,124,125,126,127,128,129]) from the first MV? 
The second MV result looks good.

**Comment by den-crane** [comment]
It just does not have any sense to use LIMIT inside MV.
MV it's an insert trigger which performs select over insert buffer and MV never reads real source table.

So when if you insert one row `VALUES('2019-05-27', 200, 121, 0.811),` MV query and limit will be evaluated over exactly this 1 ROW.
When you insert 10 mil. rows by one insert this MV query and limit will be evaluated over some unknown sequential parts like 65k or 1mil.

**Comment by RudanovskiyM** [comment]
According to CH documentation (https://clickhouse.yandex/docs/en/query_language/create/)  LIMIT shoud work:

> .... A SELECT query can contain DISTINCT, GROUP BY, ORDER BY, LIMIT... Note that the corresponding conversions are performed independently on each block of inserted data. .... 

The second MV work as expected. But there is unexpected behavior in the first case.

BTW:
10Mil batch inserted records should be as input dataset which processed by SELECT statement with any options.

Or when i make batch insert MV process record by record? If so why does the second MV work fine?

**Comment by den-crane** [comment]
>Or when i make batch insert MV process record by record? If so why does the second MV work fine?
It's processed by blocks (max_insert_block_size/max_block_size/min_insert_block_size_rows/min_insert_block_size_bytes), and it depends of the nature of the source and partitioning.

**Comment by RudanovskiyM** [comment]
Thnx
