### ISSUE TITLE
Docker - error apt-get update

### ISSUE THREAD

**Issue by vvp83** [yandex/ClickHouse#556]
command - docker pull yandex/clickhouse-server
TAG - latest (24 days ago)

Problem:
 apt-get update
E: Archives directory /var/cache/apt/archives/partial is missing. - Acquire (2: No such file or directory)

Resolve:
sudo mkdir -p /var/cache/apt/archives/partial
sudo touch /var/cache/apt/archives/lock
sudo chmod 640 /var/cache/apt/archives/lock

sudo apt-get clean

please rebuild image

**Comment by bamx23** [comment]
Fixed by #557
