### ISSUE TITLE
Improve error messages in JOINs

### ISSUE THREAD

**Issue by Slind14** [yandex/ClickHouse#5565]
When using the in-memory join engine, I'm getting this error `Unknown JOIN keys variant for limited use.`. What does it mean?

**Comment by 4ertus2** [comment]
It's some misleading error message, saying your key type is not supported in StorageJoin yet. StorageJoin does not support all the types JOIN does.

FYI, @amosbird

**Comment by amosbird** [comment]
Yeah, this error message is useless. I borrowed it from 

https://github.com/yandex/ClickHouse/blob/master/dbms/src/Interpreters/Join.cpp#L1331

It definitely deserves verbosity .

**Comment by Slind14** [comment]
I see. Is LowCardinality or Null the cause?

**Comment by simPod** [comment]
For me it was UUID type

**Comment by 4ertus2** [comment]
There's less confusing error message in master now.
