### ISSUE TITLE
How ClickHouse select leader within the shard?

### ISSUE THREAD

**Issue by ravibhushankumarsonu** [yandex/ClickHouse#5583]
How ClickHouse select leader within the shard?

**Comment by filimonov** [comment]
It uses zookeeper leader election algorithm described here:
http://zookeeper.apache.org/doc/r3.4.5/recipes.html#sc_leaderElection  

For details - please check the source: https://github.com/yandex/ClickHouse/blob/master/dbms/src/Common/ZooKeeper/LeaderElection.h
