### ISSUE TITLE
CSV insert error when Float value is 0.00000000 in CSV

### ISSUE THREAD

**Issue by dgrr** [yandex/ClickHouse#5584]
(you don't have to strictly follow this form)

**Describe the bug**
The error is caused when the CSV contains a value like `0.00000000`.
ClickHouse shows `ERROR: garbage after UInt64: ".00000000,"`.
I think it's because ClickHouse CSV decoder is looking for a `0`, not a `0.0000000` value.
If I change that field to `0` then the decoder works.

**How to reproduce**
* Which ClickHouse server version to use: `ClickHouse server version 19.7.4.26 (official build).`
* Which interface to use, if matters: `clickhouse-client`
* Non-default settings, if any: `No`
* `CREATE TABLE` statements for all tables involved: 
```
CREATE TABLE x (
  field1 UInt64,
  field2 Float64,
  field3 String
) Engine xxx
```

**Comment by den-crane** [comment]
Could not reproduce

```
CREATE TABLE x22 (
  field1 UInt64,
  field2 Float64,
  field3 String
) Engine = Memory;

insert into x22 format CSV 0,0.00000000,"aaa" 
OK

insert into x22 format CSV 0,"0.00000000","aaa"
OK
```

19.9.1.623

**Comment by dgrr** [comment]
Fixed here https://github.com/yandex/ClickHouse/issues/5585
