### ISSUE TITLE
Blank CSV fields not detected

### ISSUE THREAD

**Issue by dgrr** [yandex/ClickHouse#5585]
(you don't have to strictly follow this form)

**Describe the bug**
When decoding a CSV ClickHouse does not detect the blank fields. For example:
```
field1,field2,field3
hello,,world
```
If we have the table
```
CREATE TABLE x (
  field1 String,
  field2 Int64,
  field3 String
) ...
```
The error will be:
```ERROR: text ",world" is not like Int64```

**How to reproduce**
* Which ClickHouse server version to use: `ClickHouse server version 19.7.4.26 (official build).`
* Which interface to use, if matters `clickhouse-client`

**Comment by dgrr** [comment]
This errors doesn't make sens to me after seeing this. https://github.com/yandex/ClickHouse/blob/master/dbms/src/IO/ReadHelpers.cpp#L545

**Comment by javisantana** [comment]
could you change field2 to Nullable(Int64) and test again?

**Comment by den-crane** [comment]
```
CREATE TABLE x23 (
  field1 String,
  field2 Int64,
  field3 String
) Engine = Memory;

insert into x23 format CSV 0,,aaa
OK.
```

**Comment by dgrr** [comment]
If I take the rows that give me the error individually it doesn't show any other error, but when I try to parse the file by using `cat file.csv | clickhouse-client --query="INSERT INTO x23 (field1, field2, field3) FORMAT CSVWithNames"` it shows me the error above

**Comment by den-crane** [comment]
>but when I try to parse the file by using

attach your file then

**Comment by dgrr** [comment]
The file:
I simulated the file content. The shown errors are the same.
The `query` file contains the query I am doing.
The `table.sql` contains the query to build the table.
The `input.csv` is the generated file.

https://files.catbox.moe/9wnd04.zip

**Comment by den-crane** [comment]
0.74874870  --  `field22` Int64,
0.00000000  --  `field23` UInt64

**Comment by dgrr** [comment]
Anyway, I changed all the `Int64` and `UInt64` to `Float64`, but the error stills there:
```
...
Column 24,  name: field25, type: String,  parsed text: "f1ya"
Column 25,  name: field26, type: Float64, parsed text: "0041"
Column 26,  name: field27, type: Float64, ERROR: text ",kaaisiqnq" is not like Float64
```

**Comment by den-crane** [comment]
@dgrr are you trolling ? REALLY ?

your table HAS to have **37** columns

```
CREATE TABLE `x28` (
`field1` Float64,
`field2` Float64,
`field3` Float64,
`field4` String,
`field5` String,
`field6` Int64,
`field7` String,
`field8` String,
`field9` String,
`field10` String,
`field11` String,
`field12` Int64,
`field13` UInt64,
`field14` String,
`field15` String,
`field16` String,
`field17` Int64,
`field18` Float64,
`field19` Int64,
`field20` Float64,
`field21` Float64,
`field22` Float64,
`field23` Float64,
`field24` String,
`field25` String,
`field26` String,
`field27` Int64,
`field28` String,
`field29` Float64,
`field30` String,
`field31` String,
`field32` Float64,
`field33` String,
`field34` String,
`field35` String,
`field36` String,
`field37` String
) ENGINE = Memory;

```
cat input.csv | clickhouse-client --query="INSERT INTO x28 FORMAT CSV"
OK

**Comment by dgrr** [comment]
With your table works. I am going to review mine. And no, I am not trolling, I changed the table before executing that query. Seems there is an error with my schema.

**Comment by den-crane** [comment]
I showed that number of columns is inconsistent 35 VS 37 

> @dgrr you have 37 columns in CSV
> head -1 input.csv | awk -F "," '{print NF}'
> 37
> 
> and 35 columns in the table.

**Comment by dgrr** [comment]
Ok. Works. There was an inconsistency in the table data types.

Thanks @den-crane

**Comment by dgrr** [comment]
I was getting the same error with different tables and the solution was mentioned by @javisantana 

Thanks to everyone, but the main error is caused by the lack of `Nullable` in the column definition.
