### ISSUE TITLE
Find most occurring value in a group

### ISSUE THREAD

**Issue by dsr301** [yandex/ClickHouse#5597]
I want to find the most occurring value per group.
I tried using top(k)(column) but I get below error: 
Column class is not under aggregate function and not in GROUP BY.

For example:
If I have table test_date with columns(pid, value)
pid, value
----------
1,a
1,b
1,a
1,c

I want result : 
pid, value
----------
1,a

 SELECT pid,top(1)(value) top_value FROM test_data group by pid
> Column value  is not under aggregate function and not in GROUP BY

I also tried with anyHeavy() but it only works for values that occur more than in half the cases

**Comment by den-crane** [comment]
select count() cnt, pid, value
....
group by pid, value
order by pid, cnt desc 
limit 1 by pid

**Comment by hczhcz** [comment]
It's `topK(1)(value)`.
