### ISSUE TITLE
Enabling CORS for HTTP Interface

### ISSUE THREAD

**Issue by dewang-mistry** [yandex/ClickHouse#56]
Hi,

Is there a configuration setting where we can enable cross domain sharing for HTTP interface?

Right now when I query using jQuery I get the following error: 

`"No 'Access-Control-Allow-Origin' header is present on the requested resource"`

Thanks!

**Comment by alexey-milovidov** [comment]
No settings right now.
Seems to be easy change...
Worth to do.

**Comment by isublimity** [comment]
+1 vote

**Comment by isublimity** [comment]
i think is close issue, in https://github.com/yandex/ClickHouse/pull/83

**Comment by alexey-milovidov** [comment]
Yes.

Release build with this feature is not ready. Maybe on thursday or after 12 sept.
