### ISSUE TITLE
system.parts.remove_time is -1

### ISSUE THREAD

**Issue by tobia** [yandex/ClickHouse#560]
I don't know if this is a bug or just undocumented behaviour.

I was trying to query the active parts of a table from `system.parts`, that is the rows where `remove_time` is zero. But all these attempts fail:

```sql
select * from system.parts where remove_time = '0000-00-00 00:00:00';
select * from system.parts where remove_time = toDateTime(0);
```

Finally, I figured out that even if the value is shown as `0000-00-00 00:00:00`, it actually contains -1:

```sql
select * from system.parts where toInt32(remove_time) = -1;
```

**Comment by artpaul** [comment]
This is correct behaviour because by default remove_time initialized to std::numeric_limits<time_t>::max(). See https://github.com/yandex/ClickHouse/blob/master/dbms/include/DB/Storages/MergeTree/MergeTreeDataPart.h#L102

So it means that data_part was removed in far far future or still don't.

**Comment by tobia** [comment]
Right, so it is actually UINT_MAX, not -1 (although it's the same bit pattern.)

In that case, I think there is a bug in the way it is displayed as `0000-00-00 00:00:00`

If ClickHouse is using `toDateTime(UINT_MAX)` to mean "removed in the far future == not yet removed", then it should be either displayed as its actual date `2106-02-07 06:28:15` [1] or treated as a special case and displayed as `9999-99-99 00:00:00`, just like `toDateTime(0)` is displayed as `0000-00-00 00:00:00` instead of `1970-01-01 00:00:00`

Along the same lines, `toDate(65535)` could be treated as a special case and displayed as `9999-99-99`, just like `toDate(0)` is displayed as `0000-00-00`

There is a related bug, in than dates between 24855 and 65535 and date-times between 2147397248 and 4294967295 are displayed as zero, probably because of the Year 2038 problem. (This might be due to the C library?)

[1] examples using UTC timezone
