### ISSUE TITLE
Where to ask?

### ISSUE THREAD

**Issue by kreuzerkrieg** [yandex/ClickHouse#5609]
Is GitHub the best place to ask "How-To" design questions?

**Comment by blinkov** [comment]
https://stackoverflow.com/questions/tagged/clickhouse is probably better

**Comment by filimonov** [comment]
Follow the instructions :) 

> Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse

> If you still prefer GitHub issues, remove all this text and ask your question here.

Generally GitHub is mostly for ClickHouse development related discussions / issues / bug reports / feature requests and similar.

**Comment by kreuzerkrieg** [comment]
> Generally GitHub is mostly for ClickHouse development related discussions / issues / bug reports / feature requests and similar.

Thanks for your reply. In your opinion, design question is "development related discussions" and should be asked here or SO? Since SO is not exactly suitable for design discussions, such a question would be closed as "too broad" definition

**Comment by filimonov** [comment]
Personally I would prefer to answer the ClickHouse question, not a question about where to ask questions ;)

If you think that github suits better for your question - put it here. I can't know what the question is :)

**Comment by kreuzerkrieg** [comment]
> Personally I would prefer to answer the ClickHouse question, not a question about where to ask questions ;)

Here you go :)
https://github.com/yandex/ClickHouse/issues/5662
