### ISSUE TITLE
Max and avg on the same null value should return the same answer

### ISSUE THREAD

**Issue by CAspeling** [yandex/ClickHouse#5612]
We are showing IoT results in a time series graph over x amount of time. We need to show max and average results but are getting zeros back for max when we would expect nulls in the following case:

avg(null, null, null) = null
max(null,null,null) = 0 (expect null here)

Once we have those results, we need to average but since max returns zero instead of null, we have more results to average, giving a false answer.

This also causes issues when we have states (0 and 1) on devices that only report changes. So if we max 3 nulls because a device has simply not had a change from 1 to 0, then the max still comes back as 0 which is not correct.

Expect to see:
avg(null, null, null) = null
max(null,null,null) = null

Any way of forcing this behaviour? It is vital so that we can display our 1000s of graph points correctly.

**Comment by den-crane** [comment]
What CH version do you use? I don't observe the described behavior.
```

SELECT CAST(NULL, 'Nullable(Float64)') AS a
FROM numbers(3)

┌────a─┐
│ ᴺᵁᴸᴸ │
│ ᴺᵁᴸᴸ │
│ ᴺᵁᴸᴸ │
└──────┘

SELECT max(a)
FROM
(
    SELECT CAST(NULL, 'Nullable(Float64)') AS a
    FROM numbers(3)
)

┌─max(a)─┐
│   ᴺᵁᴸᴸ │
└────────┘

SELECT avg(a)
FROM
(
    SELECT CAST(NULL, 'Nullable(Float64)') AS a
    FROM numbers(3)
)

┌─avg(a)─┐
│   ᴺᵁᴸᴸ │
└────────┘
```

**Comment by CAspeling** [comment]
ClickHouse 19.5.3.8

select 
    id, maxIf(value, id == 1) as max
from (
select
  number as id,
  number * 2 as value
from
  numbers(5)
) group by id

versus

select 
    id, avgIf(value, id == 1) as max
from (
select
  number as id,
  number * 2 as value
from
  numbers(5)
) group by id

**Comment by CAspeling** [comment]
```select 
    id, avgIf(value, id == 1) as max
from (
select
  number as id,
  CAST(NULL, 'Nullable(Float64)') as value
from
  numbers(5)
) group by id
```

versus

```select 
    id,maxIf(value, id == 1) as max
from (
select
  number as id,
  CAST(NULL, 'Nullable(Float64)') as value
from
  numbers(5)
) group by id
```

 | id | max
 | 0 |
 | 4 |
 | 3 |
 | 2 |
 | 1 |

**Comment by CAspeling** [comment]
```
select id, avgIf(value, id == 1) as avg, maxIf(value, id == 1) as max
from (
select
  number as id,
  CAST(null, 'Nullable(Float64)') as value
from
  numbers(5)
) group by id
```

 | id | avg | max |
 | 0 |  |  |
 | 4 |  |  |
 | 3 |  |  |
 | 2 |  |  |
 | 1 |  |  |

and

```
select id, avgIf(value, id == 1) as avg, maxIf(value, id == 1) as max
from (
select
  number as id,
  CAST(number*2, 'Nullable(Float64)') as value
from
  numbers(5)
) group by id
```

 | id | avg | max |
 | 0 |  | 0 |
 | 4 |  | 0 |
 | 3 |  | 0 |
 | 2 |  | 0 |
 | 1 | 2 | 2 |

**Comment by CAspeling** [comment]
In fact, ifnull doesn't want to output the expected "1" either but the following at least gives the last column for max to be nulls

```
select
  id,
  avgIf(value, id == 3) as average,
  maxIf(value, id == 3) as maximum,
  ifNull(average,1) as thing,
  maximum*thing/thing as realmax
from (
select
  number as id,
  number*2 as value
from
  numbers(5)
) group by id
```

 | id | average | maximum | thing | realmax |
 | 0 | null | 0 | null | null |
 | 4 | null | 0 | null | null |
 | 3 | 6 | 6 | 6 | 6 |
 | 2 | null | 0 | null | null |
 | 1 | null | 0 | null | null |

**Comment by CAspeling** [comment]
The following maths work because it uses a number so small that the db can't actually ever store or use it so we never run into the problem of /0

```
select
  id,
  value,
  avgIf(value, id == 0) as average,
  maxIf(value, id == 0) as maximum,
  ( ( (average-0.00000000000001) / (average+0.00000000000001) ) / ( (average-0.00000000000001) / (average+0.00000000000001) ) ) as seo,
  maximum* ( ( (average-0.00000000000001) / (average+0.00000000000001) ) / ( (average-0.00000000000001) / (average+0.00000000000001) ) ) as realmax3
from (
select
  number as id,
  number-0.00000000000001 as value
from
  numbers(10)
) group by id, value
```

**Comment by den-crane** [comment]
So the difference is that avg(0/0) == null ? It seems already fixed.

Current behavior is nan for avg in case of 0 count.
19.10.1.669

```
SELECT
    id,
    avgIf(value, id = 1) AS max,
    sumIf(value, id = 1) AS sum,
    countIf(value, id = 1) AS cnt
FROM
(
    SELECT
        number AS id,
        number * 2 AS value
    FROM numbers(5)
)
GROUP BY id

┌─id─┬─max─┬─sum─┬─cnt─┐
│  0 │ nan │   0 │   0 │
│  4 │ nan │   0 │   0 │
│  3 │ nan │   0 │   0 │
│  2 │ nan │   0 │   0 │
│  1 │   2 │   2 │   1 │
└────┴─────┴─────┴─────┘
```

```
SELECT
    id,
    value,
    avgIf(value, id = 0) AS average,
    maxIf(value, id = 0) AS maximum,
    ((average - 1e-14) / (average + 1e-14)) / ((average - 1e-14) / (average + 1e-14)) AS seo,
    maximum * (((average - 1e-14) / (average + 1e-14)) / ((average - 1e-14) / (average + 1e-14))) AS realmax3
FROM
(
    SELECT
        number AS id,
        number - 1e-14 AS value
    FROM numbers(10)
)
GROUP BY
    id,
    value

┌─id─┬────────────value─┬─average─┬─maximum─┬─seo─┬─realmax3─┐
│  3 │ 2.99999999999999 │     nan │       0 │ nan │      nan │
│  7 │ 6.99999999999999 │     nan │       0 │ nan │      nan │
│  6 │ 5.99999999999999 │     nan │       0 │ nan │      nan │
│  1 │ 0.99999999999999 │     nan │       0 │ nan │      nan │
│  0 │           -1e-14 │  -1e-14 │  -1e-14 │ nan │      nan │
│  5 │ 4.99999999999999 │     nan │       0 │ nan │      nan │
│  4 │ 3.99999999999999 │     nan │       0 │ nan │      nan │
│  2 │ 1.99999999999999 │     nan │       0 │ nan │      nan │
│  9 │ 8.99999999999999 │     nan │       0 │ nan │      nan │
│  8 │ 7.99999999999999 │     nan │       0 │ nan │      nan │
└────┴──────────────────┴─────────┴─────────┴─────┴──────────┘
```

**Comment by CAspeling** [comment]
That second query, the seo column should have the value 1 on ID 0. This is what we'd expect. That is what I get when I run that query in tabix. We would expect maximum to give nan instead of 0 for all the other IDs but instead it appears that extra maths is necessary as shown in column realmax3 to make this happen which does not seem correct. maxIf should return null , the same as avgIf, right?

![image](https://user-images.githubusercontent.com/44218267/59649671-94165b00-91d7-11e9-8aa4-50eb8bb483c9.png)

What I had hoped was that such a small number such as -1e-14 would never be possible to store in the db but it seems I'm mistaken on that. This would have been a possible work-around for us as realmax3 is the expected output for us but at the same time we need to be careful to use a number small enough so that it never occurs in the results.

**Comment by CAspeling** [comment]
> So the difference is that avg(0/0) == null ? It seems already fixed.

Can't divide by 0, hence the maths to prevent that.

**Comment by den-crane** [comment]
>That second query, the seo column should have the value 1 on ID 0.

No  [ / (average + 1e-14)) AS seo ] === / ( -1e-14 +  1e-14 ) ~ nan of inf

because of math

```
SELECT 1 / 0

┌─divide(1, 0)─┐
│          inf │
└──────────────┘

SELECT 0 / 0

┌─divide(0, 0)─┐
│          nan │
└──────────────┘

```

**Comment by CAspeling** [comment]
@den-crane exactly. We cannot be dividing by 0. Check my query again. What you have is not what I have.

Something other than 0 divided by something other than 0 will always be 1.

**Comment by CAspeling** [comment]
The seo column is just something we came up with to show what we expect maxIf to return. There is still the problem of avgIf and maxIf behaving differently according to input. It would solve so many of our problems if this was resolved. We wouldn't need to implement a hack like that realmax3 and seo columns just to get around the problem.

**Comment by den-crane** [comment]
seems you are looking for -- iF(isNaN(x) or abs(x) == inf, Null, x) 
select iF(isNaN(x) or abs(x) == inf, Null, x) from (select 1/0 x union all select 0/0 union all select 1/1)
```

select
  id,
  iF(isNaN(avgIf(value, id == 3) as average) or abs(average) == inf, 0, average) avg_fix,
  maxIf(value, id == 3) as maximum
from (
select
  number as id,
  number*2 as value
from
  numbers(5)
) group by id

┌─id─┬─avg_fix─┬─maximum─┐
│  0 │       0 │       0 │
│  4 │       0 │       0 │
│  3 │       6 │       6 │
│  2 │       0 │       0 │
│  1 │       0 │       0 │
└────┴─────────┴─────────┘
```

**Comment by CAspeling** [comment]
How will we know what is a real max of 0 and what isn't?

We are drawing graphs of incoming data for IoT devices that report states.
Sometimes that state is 0 and sometimes it is a value higher or lower than
0.

We ask the database for all values according to an aggregation selection eg
max or avg etc for specific time periods eg last 5 seconds. If a device has
not reported any state in that time, it should not show 0 instead of null
or nan.

When we query using avgIf, we get nulls where no data exists but if we use
maxIf, we get false zeros and we cannot tell which ones are true zero
states reported and which ones are just the maxIf function false zeros.

This is why the example we have used has a zero result as one of the rows,
so we can show you that there is no distinction between the ID 0 result for
maxIf and all the other rows that also show 0 as a false result for maxIf,
while in avgIf, there is a clear distinction between a true 0 result and
all the other Nan results.

**Comment by den-crane** [comment]
OK. Understood now. But why you cannot add `group by device` ?



it's really wrong behavior in case of max()/avg group by 1 on zero rows.

```
select max(a),avg(a) from (select 5 a) where 1=0 settings empty_result_for_aggregation_by_empty_set=0;
┌─max(a)─┬─avg(a)─┐
│      0 │    nan │
└────────┴────────┘ 

psql > select max(a), avg(a) from (select 5 a) as t where 1=0;
 max | avg
-----+-----
     |
(1 row)

mysql> select max(a), avg(a) from (select 5 a) as t where 1=0;
+--------+--------+
| max(a) | avg(a) |
+--------+--------+
|   NULL |   NULL |
+--------+--------+
```

**Comment by CAspeling** [comment]
I don't understand what the last examples meant. We expect maxIf to give back nan instead of zero when avg would give back nan. This allows us to handle those nan's in different ways depending on what graph type we render.

**Comment by CAspeling** [comment]
Here is an example straight from our database for your perusal. At any point in time, we will query on a time frame, where a result for a specific ID may or may not occur. `maxIf()` is not behaving correctly when no result comes back, while `avgIf()` returns null/ nothing, not even NAN. 

I have tried copying the empty value out to see what it contains, whether it is infact a nan or null or something, but it's just empty, which on our end comes through as a null. This is perfect for avg because we can carry previous values forward if they did not report a state/value change in the db. Max however, is broken because it does not.

```
select
  SiteId,Value,Time,
  avgIf(Value, SiteId == 562) as average,
  maxIf(Value, SiteId == 562) as maxc
from
  temp.temptable
where
  Time > '2019-05-25 16:00:00' and Time < '2019-05-31 20:11:46'
group by
  SiteId, Value, Time
limit 10
```

Results:
```
┌─SiteId─┬─Value─┬─Time────────────────┬─average─┬─maximum─┐
|    618 |  1000 | 2019-05-26 18:32:42 |         |       0 |
|    620 |     1 | 2019-05-29 15:09:56 |         |       0 |
|    562 |     9 | 2019-05-26 08:53:24 |       9 |       9 |
|    566 |     4 | 2019-05-30 19:27:59 |         |       0 |
|    585 |   8.2 | 2019-05-29 07:40:48 |         |       0 |
|    598 |    52 | 2019-05-28 11:01:25 |         |       0 |
|   1410 |  12.4 | 2019-05-26 16:03:09 |         |       0 |
|   1507 |     2 | 2019-05-26 10:29:08 |         |       0 |
|    619 |  1000 | 2019-05-29 09:58:02 |         |       0 |
|    617 |   111 | 2019-05-27 16:33:52 |         |       0 |
└────────┴───────┴─────────────────────┴─────────┴─────────┘
```

**Comment by CAspeling** [comment]
Here is a comparison:
`avg(null) = null` or "empty string" as it is called in the documentation
`avgIf(null, id == 1) = null` or "empty string"

`max(null) = null` or "empty string"
`maxIf(null, id == 1) = 0`

**Expected:**
`maxIf(null, id == 1) = null` or "empty string"

___
![image](https://user-images.githubusercontent.com/44218267/59819433-eabc9a00-937b-11e9-942f-c9f015142f4a.png)
___
We believe the bug lies with `maxIf()`, it should not return default 0, it should return default "empty string" so that it works consistently like `avg()`, `avgIf()`, and `max()`.

This problem is very urgent for us.

**Comment by CAspeling** [comment]
Would anyone please be able to look into this this week?

**Comment by CAspeling** [comment]
Any help asap would be greatly appreciated.
