### ISSUE TITLE
How to check max_bytes_before_external_group_by&max_bytes_before_external_order_by` configuration

### ISSUE THREAD

**Issue by I-akshay** [yandex/ClickHouse#5616]
So your query is to big too be executed in memory. Did you enable on disk group by & order by?
Check max_bytes_before_external_group_by & max_bytes_before_external_order_by.

How to check max_bytes_before_external_group_by&max_bytes_before_external_order_by` configuration

**Comment by blinkov** [comment]
`select * from system.settings where name like '%max_bytes_before%';` ?

**Comment by I-akshay** [comment]
> `select * from system.settings where name like '%max_bytes_before%';` ?
Thanks blinkov for responding 
Right now for max_bytes_before_external_group_by & max_bytes_before_external_order_by i am getting 0 values for both for them could you please help me how to change this configuration  and use of this configuration 

i do have one more issue 
So i am trying to group by a distributed tables (~100 million records ) so two interesting issues are happening

1)It is throwing  Attempt to read after eof: error 
2)clickhouse service on the distributed server is getting shut down 

I really put my head down but still could get solution for this error.Do have some idea around this

**Comment by filimonov** [comment]
OOMKiller killed the clickhouse process (check `dmesg` in the shell).

**Comment by filimonov** [comment]
Continuation in #5618
