### ISSUE TITLE
Removing data parts is suboptimal.

### ISSUE THREAD

**Issue by alexey-milovidov** [yandex/ClickHouse#5619]
Removing data parts calls `Poco::File::remove(true)` (recursive remove), but this method has excessive numbers of `stat` syscalls.

It performs four `stat` calls for each directory entry (if I count correctly) - all with the same result.
Actually we can avoid `stat` as long as `readdir` in most cases, because we can assume that the data part is a directory and it contents are files, and the only content are the files we know. Other cases (directory is a symlink; directory not empty after removing files) can be implemented as a fallback.

Current behaviour can lead to low performance in cases of:
- FUSE filesystems with slow file operations;
- huge directory index;
- heavy loaded server.

**Comment by filimonov** [comment]
Probably that is more important: #5581
