### ISSUE TITLE
 DB::Exception: Memory limit (for query) exceeded clickhouse

### ISSUE THREAD

**Issue by I-akshay** [yandex/ClickHouse#5621]
Hi community,

So basically i have two server A , B 
A config = 120 GB out of which 80 GB is allocated to the clickhouse process 
B config = 32 GB out of which 20 GB is allocated to the clickhouse process 

Now when i try to perform a group by clause it is throwing 

Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Received from 10.41.122.44:9000. DB::Exception: Memory limit (for query) exceeded: would use 763.04 MiB (attempt to allocate chunk of 393216 bytes), maximum: 762.94 MiB.

![image](https://user-images.githubusercontent.com/8670602/59505918-7178ff00-8ec4-11e9-8386-6193d7f0eb5c.png)
'
Now how i need to fix this issue and also how to change  max_bytes_before_external_group_by & max_bytes_before_external_order_by configurations 
beacuse they are not present in config.xml

**Comment by filimonov** [comment]
Add them into user profile in users.xml file.

**Comment by I-akshay** [comment]
> Add them into user profile in users.xml file. The simplest option - to add them to the `<default>` profile.
I am currently using default profile

**Comment by filimonov** [comment]
Please don't create a separate issue for each tiny question.

It is a continuation of #5618, so let's keep that discussion there.
