### ISSUE TITLE
Unable to see memory_usage.xml , Do we need to create this xml manually if yes can anyone please share memory_usage.xml format

### ISSUE THREAD

**Issue by I-akshay** [yandex/ClickHouse#5649]
Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

If you still prefer GitHub issues, remove all this text and ask your question here.

**Comment by filimonov** [comment]
Please don't create a separate issue for each tiny question.

Please continue that in #5618 it contains the answer.
