### ISSUE TITLE
Enum insert error

### ISSUE THREAD

**Issue by aadim** [yandex/ClickHouse#566]
It seems the EnumX data type has and ordering issue. For example I have a table

> echo "CREATE TABLE IF NOT EXISTS test.t (w String, adv_view Enum8('' = -1, 'c' = 1, 'b' = 2, 'a' = 8 ), i Int16 ) ENGINE = Log" | lwp-request -m POST http://localhost:8123

and try to insert a value into it:

> echo "1234,a,1" | lwp-request -m POST "http://localhost:8123/?query=INSERT INTO test.t FORMAT CSV"

here's the error:

> Code: 49, e.displayText() = DB::Exception: Unknown element 'a' for type Enum8('' = -1, 'c' = 1, 'b' = 2, 'a' = 8), e.what() = DB::Exception

when I drop the table and change the adv_view column definition the insert succeeds:

> echo "drop table test.t" | lwp-request -m POST http://localhost:8123
> echo "CREATE TABLE IF NOT EXISTS test.t (w String, adv_view Enum8('' = -1, 'a' = 1, 'b' = 2, 'c' = 8 ), i Int16 ) ENGINE = Log" | lwp-request -m POST http://localhost:8123
> echo "1234,a,1" | lwp-request -m POST "http://localhost:8123/?query=INSERT INTO test.t FORMAT CSV"

here's my git show output

> git show
> commit bc9f8721db5b443c403690a6a1b187f24f73c252
> Author: Alexey Milovidov <milovidov@yandex-team.ru>
> Date:   Tue Feb 14 16:41:08 2017 +0300
> 
>     Auto version update to [54164]
> 
> diff --git a/libs/libcommon/cmake/version.cmake b/libs/libcommon/cmake/version.cmake
> index 2417b9e..058e879 100644
> --- a/libs/libcommon/cmake/version.cmake
> +++ b/libs/libcommon/cmake/version.cmake
> @@ -1,6 +1,6 @@
>  #This strings autochanged from release_lib.sh :
> -set(VERSION_DESCRIBE v1.1.54160-testing)
> -set(VERSION_REVISION 54160)
> +set(VERSION_DESCRIBE v1.1.54164-testing)
> +set(VERSION_REVISION 54164)
>  #===end of autochange
>  
>  set (VERSION_MAJOR 1)

**Comment by artpaul** [comment]
Strange, but I can't reproduce it with version 1.1.54164
Please let me known if you will have this problem in the next versions.
