### ISSUE TITLE
'alter table xxx on cluster xxx drop partition xxx' failed

### ISSUE THREAD

**Issue by shangshujie365** [yandex/ClickHouse#5668]
**Describe the bug**
'alter table xxx on cluster xxx drop partition xxx' failed on some shards

**How to reproduce**
* we use 19.5, but this bug also occurs in master branch

**Expected behavior**
partition on all shards can be dropped

**Additional context**
When we run this query, it is pushed to zk, and all the replicas of the same shard will run it on competition. If the follower got the query first, it won't send to leader because of commit 'https://github.com/yandex/ClickHouse/commit/f47e3292e1c08e3bd24007e8a9b54aa82158860a', but after handling the query, it marks 'success' on zk (DDLWorker, line 746), then, the leader got this query, but it also see the 'success' mark, so it won't execute it. In this 
scenario, none of the replicas execute the query.

**Comment by 4ertus2** [comment]
#5670
