### ISSUE TITLE
How much RAM is required for ZooKeeper?

### ISSUE THREAD

**Issue by achimbab** [yandex/ClickHouse#5677]
Is there a guide for memory usage of ZooKeeper for ClickHouse?

My system uses the ReplicatedMergeTree, creates 3000 parts for one day and stores it about one year.

I set 8GB memory for ZooKeeper. I don't know whether is it enough or not.

I hope your help.

**Comment by den-crane** [comment]
ZK is in-memory database. 

So lets check ZK database size

echo mntr | nc localhost 2181|grep zk_approximate_data_size
zk_approximate_data_size	68723698

~68MB

The same size as snapshot size
du -sh /var/lib/zookeeper/version-2/snapshot.4350f30c19
77M	/var/lib/zookeeper/version-2/snapshot.4350f30c19

So in my case ZK needs 77MB+~200MB JVM needs.
I would say 500MB is enough.


Check a MergeTree setting **use_minimalistic_part_header_in_zookeeper**. If enabled, Replicated tables will store compact part metadata in a single part znode. This can dramatically reduce ZooKeeper snapshot size (especially if the tables have a lot of columns). Note that after enabling this setting you will not be able to downgrade to a version that doesn't support it.

**Comment by achimbab** [comment]
@den-crane 
The use_minimalistic_checksums_in_zookeeper is enabled.
```
:) select * from system.merge_tree_settings

... 
use_minimalistic_checksums_in_zookeeper                    │ 1            │       0 │
...
```
My ZooKeeper's zk_approximate_data_size is ```1219607498.```

I will monitor how this value grows.

It's very helpful, thank you very much.
