### ISSUE TITLE
How to remove  Replica table ? 

### ISSUE THREAD

**Issue by sangli00** [yandex/ClickHouse#569]
```
CREATE TABLE tx
(
    EventDate Date,
    UserID UInt32,
    CounterID UInt32,
    EventTime DateTime
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/tx', '{replica}', EventDate, intHash32(UserID), (CounterID, EventDate, intHash32(UserID), EventTime), 8192)

Received exception from server:
Code: 253. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Replica /clickhouse/tables/tx/replicas/120.132.42.189 already exists..

```

**Comment by vavrusa** [comment]
We usually just delete the path from ZooKeeper.

**Comment by sangli00** [comment]
@vavrusa  how to delete path from Zookeeper?

**Comment by vavrusa** [comment]
https://kazoo.readthedocs.io/en/latest/basic_usage.html#deleting-nodes

**Comment by sangli00** [comment]
@vavrusa  I have problem in ClickHouse
```host1``` Replica table to ```host2```  
how to modify ```/etc/clickhouse-server/config.xml```

If i replica ```host1```  table ```tx``` to  ```host2```，I need modify config.xml to each other?
how to modify ``` macros```? 
what mean in parameter ```<replica>host_name</replica>``` .

Thanks.

**Comment by vavrusa** [comment]
I'm not sure what are you trying to do - I guess moving replica to another host? The config just says how the shards are arranged, it doesn't have anything to do with replica names.
I would recommend spinning up a new replica, adding it to cluster configuration, and then let it replicate. When it's done, you can stop the old replica and remove the replica path from zookeeper and cluster configuration (so yes).

The macro `{replica}` comes from your config `<macros>` section. You can call the macro whatever you want, it just expands to whatever you have in the `<macros>` section (you seem to expand it to `120.132.42.189`). See https://github.com/yandex/ClickHouse/blob/1af6311a9974fbbd7e5c5c9d14dd69cb9ee34686/dbms/src/Server/config.xml#L134

**Comment by sangli00** [comment]
so, host ```120.132.42.189```  ```macros``` is  ```120.132.42.190```?

**Comment by silviucpp** [comment]
Based on documentation to delete a replica: To delete a replica, run DROP TABLE. However, only one replica is deleted - the one that resides on the server where you run the query.

I don't think there is any need to manage yourself Zookeeper from behind. 

Silviu

**Comment by dktsudgg** [comment]
@silviucpp 
I recognized when I remove a ReplicatedMergeTree table, zookeeper znode automatically be removed after a while.
How can i adjust this delete time? is there any delete duration parameter on clickhouse config?
