### ISSUE TITLE
select  column of json fromat

### ISSUE THREAD

**Issue by kkxxr66573** [yandex/ClickHouse#5691]
![image](https://user-images.githubusercontent.com/13388843/59811959-ae1e7d80-933e-11e9-8c8d-24fd5ad70714.png)

```sql
select visitParamExtractRaw(data,'request_url') 
from event_data
```
this work
![image](https://user-images.githubusercontent.com/13388843/59811991-d0180000-933e-11e9-9e03-418c091bb6fc.png)

The following does not take effect

```sql
select visitParamExtractString(data,'request_url') 
from event_data
```
![image](https://user-images.githubusercontent.com/13388843/59812028-f63da000-933e-11e9-829d-a8d936baf5bb.png)

**Comment by filimonov** [comment]
`visitParam...` functions support only some subset of JSON. Namely: 
>The following assumptions are made:
>...
>4. The JSON doesn't have space characters outside of string literals.

https://clickhouse.yandex/docs/en/query_language/functions/json_functions/

You have a space after colon char.  

Proabably `JSON...` functions appeared in the latest version of ClickHouse should work properly with such an input. 

Can you check that?
