### ISSUE TITLE
How to drop partition from the distributed table on clickhouse ?

### ISSUE THREAD

**Issue by ravibhushankumarsonu** [yandex/ClickHouse#5693]
I made a cluster setup with multiple shards and host a distributed table over the local table on each shard. I want to drop partition on each shard from the distributed table. In documentation, I find the way to drop a partition from the table from the shard but not from the cluster. https://clickhouse.yandex/docs/en/query_language/alter/#alter_drop-partition

**Comment by filimonov** [comment]
Distributed table doesn't store any data itself. You need to drop partitions from underlying tables. 

Use `ON CLUSTER` clause to run the queries across the shards.
