### ISSUE TITLE
Import data from files/URLs set by glob pattern

### ISSUE THREAD

**Issue by a-rodin** [yandex/ClickHouse#5694]
I would like to be able to import logs data from files that have names like

```
log-20190620120000.jsonl
log-20190620120100.jsonl
...
```

to ClickHouse (or not files, but URLs, the difference seem to not matter a lot).

Is it possible to do this kind of import using only ClickHouse, without writing a separate service that would do the import?

I'm aware that it is possible to use File/URL engines, but they seem to support only a single file name, not a file name that changes over time.

**Comment by 4ertus2** [comment]
Have you seen such solutions for other DBMS?
It's looks like your service could be 10-lines bash script & cron. If you do not need guaranties. If you need guaranties you probably need something more, ex. kafka or your own service.

**Comment by den-crane** [comment]
> Have you seen such solutions for other DBMS?

I've seen :( . AWS RedShift

copy sales
from 'emr://j-SAMPLE2B500FC/myoutput/part-*'

**Comment by alexey-milovidov** [comment]
Will be solved in #5371.
