### ISSUE TITLE
DISTINCT returns duplication when number of rows > 1048576

### ISSUE THREAD

**Issue by kraeiri** [yandex/ClickHouse#5708]
DISTINCT returns duplication when number of rows > 1048576

 ClickHouse server version:  19.5.3
How to reproduce:
1. create table dist_test ( num Int64, str String) engine =Log;
2. Insert 1 500 000 entries with duplications
e.g.
insert into dist_test select toInt64(number/1000)number, 'TEST' from system.numbers limit 1500000

3. select distinct num from dist_test where str in (select 'TEST') 

actual result:
query returns duplications;

expected result:
no duplications;

Note: select distinct num from dist_test where str in ( 'TEST') - this query works as expected

**Comment by den-crane** [comment]
19.10.1.669

> clickhouse-client -q "create table dist_test ( num Int64, str String) engine =Log;"
> clickhouse-client -q "insert into dist_test select toInt64(number/1000)number, 'TEST' from system.numbers limit 1500000"
> clickhouse-client -q "select distinct num from dist_test where str in (select 'TEST') format TSV" |wc -l
1500
> clickhouse-client -q "select distinct num from dist_test where str in (select 'TEST') format TSV"|sort -u |wc -l
1500
> clickhouse-client -q "select distinct num from dist_test where str in ( 'TEST') format TSV" |wc -l
1500

No issue so far.

Add rows
> clickhouse-client -q "insert into dist_test select toInt64(number/1000)number, 'TEST' from system.numbers limit 1500000"

> clickhouse-client -q "select distinct num from dist_test where str in ( 'TEST') format TSV" |wc -l
1500
No issue

w/o distinct
> clickhouse-client -q "select num from dist_test where str in ( 'TEST') format TSV" |wc -l
3000000

**Comment by den-crane** [comment]
it probably fixed with 19.5.4.22 19.6.2.11 https://github.com/yandex/ClickHouse/pull/5001
