### ISSUE TITLE
А что, источники из грибеного-ата в нормальное хранилище переводить не собираетесь?

### ISSUE THREAD

**Issue by MironAtHome** [yandex/ClickHouse#5724]
Или гребаться с этой кучей дерьма придется до скончания лет!

**Comment by MironAtHome** [comment]
Может кто думает, что русский язык святым духом живет, но вообще - то истоки, не на русском языке, это просто позор.
А я думал здесь нормальные...

**Comment by alexey-milovidov** [comment]
Я не понял, что такое "грибеного-ата", какие источники.

**Comment by MironAtHome** [comment]
Я вот шел и думал, что наваял здесь нехорошего. Но в Вашем возрасте, молодые люди, пора знать, что такое "источники". Это то, что Ваша компания хранит здесь, на этом самом ресурсе.
Может Вы так выразили свой сарказм. Не знаю.
Но мало того, что эти самые источники на английском, так ещё и хранятся не на собственном Яндексовском хранилище, которое на русском языке, а здесь, на источнике, который могут хуавейнуть завтра. И что дальше?!

**Comment by alexey-milovidov** [comment]
Имеются ввиду вопросы:

1. "Зачем вы храните исходные коды ClickHouse на сервисе GitHub, принимая во внимание, что этот сервис принадлежит американской корпорации и не имеет отношения к Яндексу, что может вызывать опасения из-за торговых войн?"

2. "Почему мы предпочитаем вести обсуждения по поводу разработки продукта на английском языке, и пишем комментарии к коду также на английском яызке, а не на русском?"

**Comment by filimonov** [comment]
git - децентрализованеая система. Каждый кто выполнил команду git clone имеет на своём компьютере полную копию всех источников с полной историей и в течение минут можно с единственного компьютера восстановить весь репозитарий.

Github и английский язык это просто удобные инструменты для международного общения (например и с разработчиками из Китая, Европы, Индии и других стран). Если для международн

**Comment by MironAtHome** [comment]
"git - децентрализованеая система. Каждый кто выполнил команду git clone имеет на своём компьютере полную копию всех источников с полной историей и в течение минут можно с единственного компьютера восстановить весь репозитарий."
-- Вы не правы. Это крайне идеалистический взгляд на Гит, а учитывая тот факт, что Вы видимо имеете прямое отношение к административной части центра, и Гит хранилища источников, в частности, выдает мотивы, не имеющие ничего общего с созданием ПО.
Вы меня извините, но с моим опытом работы и управления творческими коллективами, шкурнические мотивы не получится прикрыть интересами профессии.

"Github и английский язык это просто удобные инструменты для международного общения (например с разработчиками из Китая, Европы, Америки и многих других стран)."
-- я думаю, что превосходство русского языка для русского разработчика творческих продуктов является более важной задачей, чем Ваше, возможно и имеющее место, удобство.
Точно так же мыть руки перед едой важнее, чем удовлетворить животный рефлекс самосохранения.
