### ISSUE TITLE
About performances of select * from xxx limit 1

### ISSUE THREAD

**Issue by Kiddinglife** [yandex/ClickHouse#5734]
Hi folks,

I did select * from xxx limit 1 in single-instance influxdb in prod and it crashes due to increditable amounts of memory and cpu comsumptions....  very slow... Now I am seeking the replacement of it and clickhouse looks like a good replacement of influxdb.

I checked the documentation that says the query results will be based on sort key. I am wondering about the performances of clickhouse on select * from xxx limit 1.

Thanks.

**Comment by den-crane** [comment]
https://www.altinity.com/blog/clickhouse-in-the-storm-part-1
https://www.altinity.com/blog/clickhouse-in-the-storm-part-2

https://www.altinity.com/blog/tag/Time+Series

**Comment by filimonov** [comment]
Also - try 19.10 / 19.11 / latest master versions. There was some improvement in that: https://github.com/yandex/ClickHouse/pull/5648#issuecomment-502562383

**Comment by alexey-milovidov** [comment]
@filimonov The trivial query `select * from xxx limit 1` will also work fine. ClickHouse will automatically lower number of threads (to one) and block size (also to one).
