### ISSUE TITLE
Support nonequi-joins

### ISSUE THREAD

**Issue by sudabon** [yandex/ClickHouse#5736]
I hope to use comparison operators in ON clause.

**How to reproduce**

- ClickHouse server version : v19.11.0
- Example with two tables

table1

`CREATE TABLE table1
(
    str1 String,
    num1 UInt64
) ENGINE=MergeTree()
ORDER BY (str1);`

table2

`CREATE TABLE table2
(
    str2 String,
    num2 UInt64
) ENGINE=MergeTree()
ORDER BY (str2);`

query

`SELECT
    *
FROM
    table1 AS t1
LEFT OUTER JOIN
    table2 AS t2
ON
    t1.str1 = t2.str2
    AND greater(t1.num1, t2.num2) = 1;`

message

`DB::Exception: Invalid columns in JOIN ON section. Columns num1 and num2 are from different tables..`

**Comment by 4ertus2** [comment]
There's only equi-join supported. It means ON section could have only equality between columns. And it's an algorithm restriction. There're no plans to support some special algorithm not equal ON sections. You could rewrite such the joins with combination of CROSS JOINs and equi-JOINs. In some cases (if you have at least one equality) it's possible just to move inequality into WHERE section.

It's possible to support inequality syntax, rewriting your query inside of ClickHouse. But performance would be the same as writing CROSS JOIN or moving inequality into WHERE.

I've searched on the internet and find the same issue for BigQuery. So we are not along here :) https://stackoverflow.com/questions/51316264/how-to-do-a-left-outer-join-on-inequality

**Comment by sudabon** [comment]
Hi Artem,

thanks for your quick reply.

I understood an algorithm restriction and no plan to support them.
I try to use comparison operators in WHERE section.
