### ISSUE TITLE
select max(event_timestamp) returns 0000-00-00 00:00:00 for CollapsingMergeTree

### ISSUE THREAD

**Issue by goranc** [yandex/ClickHouse#575]
I have situation where SELECT statement returns using function max(event_timestamp) value '0000-00-00 00:00:00' 
min(event_timestamp) function returns correct value

The table is created as CollapsingMergeTree and have fake partition_date using toDate(0)
The intention is to keep latest record for events with specific record value as a key.

CREATE TABLE events.records
(
    record String,
    status String,
    event_timestamp DateTime,
    record_timestamp DateTime,
    partition_date Date DEFAULT toDate(0),
    inserted_on DateTime DEFAULT now(),
    inserted_on_date Date DEFAULT toDate(inserted_on),
    is_generic String,
    sign Int8 DEFAULT toInt8(1)
) ENGINE = CollapsingMergeTree(partition_date, record, 8192, sign)
;

**Comment by alexey-milovidov** [comment]
It means that maximum event_timestamp value is outside of the range of datetimes that could be printed correctly. Check value of `toUInt32(max(event_timestamp))` to see timestamp.

**Comment by goranc** [comment]
Yes.
That is the issue I have.

Thanks for quick answer, 
you can close this issue.
