### ISSUE TITLE
throwIf() custom message

### ISSUE THREAD

**Issue by thyn** [yandex/ClickHouse#5772]
It would be great to have custom message using throwIf. 

For example

throwIf(count(1)<>0,'to many records')

**Comment by alexey-milovidov** [comment]
Nice feature request! By the way, it is very easy to implement.

PS. Many people wonder, what is the practical use case for `throwIf`. Can you share, please?

**Comment by thyn** [comment]
We use clickhouse for log storage and monitoring

current query

```sql
select concat(r0,r1) as text, if (text='','SUCCESS', text) as result from(
select count(1) as logMessages,
if (logMessages=0,'no logs','') as r0,
countIf(message='connection error') as errors,
if (errors>0,'to many errors','') as r1 from logs)
```

becomes

```
select throwIf(logMessages>0,'no logs') as r0,throwIf (errors=0,'to many errors','') as r1 from logs
```
Also I don't undestand why throwIf needs inverted if clause.

**Comment by alexey-milovidov** [comment]
What version of ClickHouse do you use and what is the result of the following commands?

```
~/ClickHouse$ clickhouse local --query "SELECT throwIf(1)"
Code: 395, e.displayText() = DB::Exception: Value passed to 'throwIf' function is non zero (version 19.10.1.671 (official build))
~/ClickHouse$ clickhouse local --query "SELECT throwIf(0)"
0
```

This is the expected behaviour: the function throws an exception if argument is non-zero.

**Comment by thyn** [comment]
It's ok. I think I was a little confused. Right version is

```
select throwIf(logMessages=0,'no logs') as r0,throwIf (errors>0,'to many errors','') as r1 from logs

```
