### ISSUE TITLE
Exporting IPv6 addresses as JSON corrupts them

### ISSUE THREAD

**Issue by ayng** [yandex/ClickHouse#5781]
**Bug description**
Trying to export IPv6 addresses (`FixedString(16)`) as JSON sometimes results in certain byte sequences being replaced with the replacement character �.

This is expected behavior for encoding Clickhouse strings into JSON string literals, which must be valid Unicode: https://clickhouse.yandex/docs/en/interfaces/formats/#json

However, the bytes in a IPv6 address often do not line up into valid Unicode.

**How to reproduce**
- I used `ClickHouse server version 19.9.2 revision 54421`
- In Clickhouse client, do `select IPv6StringToNum('::1bc0') format JSON`
- `1b` is a valid UTF-8 sequence (ESC character), but `c0` is not a valid UTF-8 sequence (refer to https://en.wikipedia.org/wiki/UTF-8#Codepage_layout). The corresponding JSON is: 
```"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u001B�"```

**Expected behavior**
I do not really know what to expect here, since this is a natural consequence of choosing `FixedString(16)` as the canonical IPv6 representation (https://clickhouse.yandex/docs/en/data_types/domains/ipv6/).

**Comment by alexey-milovidov** [comment]
Now you can use `IPv6` data type, that is designed specifically for IPv6 addresses.
To transform String or FixedString(16) to IPv6, write `toIPv6(x)`.
You can also transform `FixedString(16)` to text String with `IPv6NumToString(x)`.

**Comment by ayng** [comment]
Thank you, that solves my use case!
