### ISSUE TITLE
countIf and distinct parse error.

### ISSUE THREAD

**Issue by a615549958** [yandex/ClickHouse#5782]
select countIf(distinct(id)<5) from test2;

SELECT countIfDistinct(id < 5)
FROM test2 

Received exception from server (version 19.11.0):
Code: 46. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Unknown function countIfDistinct.

**Comment by alexey-milovidov** [comment]
The syntax `countIf(DISTINCT(x) < 5)` is not supported - neither in ClickHouse or any other DBMS.
You can write `uniqExactIf(x, x < 5)`.

**Comment by ogbofjnr** [comment]
@alexey-milovidov , why there is no uniqExactIf in documentation? https://clickhouse.tech/docs/en/sql-reference/aggregate-functions/reference/

**Comment by akuzm** [comment]
> @alexey-milovidov , why there is no uniqExactIf in documentation? https://clickhouse.tech/docs/en/sql-reference/aggregate-functions/reference/

`-If` is a generic suffix that can be applied to any aggregate function (see the docs here https://clickhouse.tech/docs/en/sql-reference/aggregate-functions/combinators/#agg-functions-combinator-if)
