### ISSUE TITLE
Allocator: Cannot mmap 128.00 MiB

### ISSUE THREAD

**Issue by kriulkin** [yandex/ClickHouse#5784]
Hello,
i'm getting the error on linux host with 4Gb of RAM and 3.5Gb of data:

2019.06.27 18:02:11.314895 [ 51 ] {b06c9d4e-c769-4162-899f-7843b897b743} <Error> executeQuery: Code: 173, e.displayText() = DB::ErrnoException: Allocator: Cannot mmap 128.00 MiB., errno: 12, strerror: Cannot allocate memory (version 19.7.3.9 (official build)) (from 127.0.0.1:43992) (in query: select doc, count(distinct ring) uniq, median(pos) avgPos from log where toDayOfMonth(date) = 27 and dir = 14 and modulo(doc, 100) = 6 group by doc order by uniq desc limit 100), Stack trace:

0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x75f3b16]
1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x22) [0x392b432]
2. /usr/bin/clickhouse-server(DB::throwFromErrno(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int)+0x171) [0x75dac51]
3. /usr/bin/clickhouse-server() [0x3b21f76]
4. /usr/bin/clickhouse-server(DB::Arena::addChunk(unsigned long)+0x86) [0x3b23f56]
5. /usr/bin/clickhouse-server(DB::Arena::alignedAlloc(unsigned long, unsigned long)+0x3b) [0x649749b]
6. /usr/bin/clickhouse-server(void DB::Aggregator::executeImplCase<false, DB::AggregationMethodOneNumber<unsigned long, TwoLevelHashMapTable<unsigned long, HashMapCell<unsigned long, char*, HashCRC32<unsigned long>, HashTableNoState>, HashCRC32<unsigned long>, TwoLevelHashTableGrower<8ul>, AllocatorWithHint<true, AllocatorHints::DefaultHint, 67108864ul>, HashMapTable> > >(DB::AggregationMethodOneNumber<unsigned long, TwoLevelHashMapTable<unsigned long, HashMapCell<unsigned long, char*, HashCRC32<unsigned long>, HashTableNoState>, HashCRC32<unsigned long>, TwoLevelHashTableGrower<8ul>, AllocatorWithHint<true, AllocatorHints::DefaultHint, 67108864ul>, HashMapTable> >&, DB::AggregationMethodOneNumber<unsigned long, TwoLevelHashMapTable<unsigned long, HashMapCell<unsigned long, char*, HashCRC32<unsigned long>, HashTableNoState>, HashCRC32<unsigned long>, TwoLevelHashTableGrower<8ul>, AllocatorWithHint<true, AllocatorHints::DefaultHint, 67108864ul>, HashMapTable> >::State&, DB::Arena*, unsigned long, std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*> >&, DB::Aggregator::AggregateFunctionInstruction*, std::vector<StringRef, std::allocator<StringRef> >&, char*) const+0x1a1) [0x6fe68a1]
7. /usr/bin/clickhouse-server(void DB::Aggregator::executeImpl<DB::AggregationMethodOneNumber<unsigned long, TwoLevelHashMapTable<unsigned long, HashMapCell<unsigned long, char*, HashCRC32<unsigned long>, HashTableNoState>, HashCRC32<unsigned long>, TwoLevelHashTableGrower<8ul>, AllocatorWithHint<true, AllocatorHints::DefaultHint, 67108864ul>, HashMapTable> > >(DB::AggregationMethodOneNumber<unsigned long, TwoLevelHashMapTable<unsigned long, HashMapCell<unsigned long, char*, HashCRC32<unsigned long>, HashTableNoState>, HashCRC32<unsigned long>, TwoLevelHashTableGrower<8ul>, AllocatorWithHint<true, AllocatorHints::DefaultHint, 67108864ul>, HashMapTable> >&, DB::Arena*, unsigned long, std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*> >&, DB::Aggregator::AggregateFunctionInstruction*, std::vector<StringRef, std::allocator<StringRef> >&, bool, char*) const+0xd3) [0x6fe6b13]
8. /usr/bin/clickhouse-server(DB::Aggregator::executeOnBlock(DB::Block const&, DB::AggregatedDataVariants&, std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*> >&, std::vector<std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*> >, std::allocator<std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*> > > >&, std::vector<StringRef, std::allocator<StringRef> >&, bool&)+0x157c) [0x6f864ec]
9. /usr/bin/clickhouse-server(DB::ParallelAggregatingBlockInputStream::Handler::onBlock(DB::Block&, unsigned long)+0x5c) [0x6f2840c]
10. /usr/bin/clickhouse-server(DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::thread(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long)+0x396) [0x6f2e9a6]
11. /usr/bin/clickhouse-server(ThreadFromGlobalPool::ThreadFromGlobalPool<DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::process()::{lambda()#1}>(DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::process()::{lambda()#1}&&)::{lambda()#1}::operator()() const+0x71) [0x6f2f0f1]
12. /usr/bin/clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1ab) [0x75f9aab]
13. /usr/bin/clickhouse-server() [0xb4d035f]
14. /lib64/libpthread.so.0(+0x7dd5) [0x7f2b6007edd5]
15. /lib64/libc.so.6(clone+0x6d) [0x7f2b5f69a02d]

**Comment by den-crane** [comment]
1. add 8Gb of swap.
2. change CH cache size to 500MB `<mark_cache_size>536870912</mark_cache_size>`
3. change CH user memory settings
```
<yandex>
    <profiles>
        <default>
            <max_bytes_before_external_group_by>20000000000</max_bytes_before_external_group_by>
            <max_memory_usage>40000000000</max_memory_usage>
        </default>
    </profiles>
</yandex>
```

**Comment by alexey-milovidov** [comment]
> Allocator: Cannot mmap 128.00 MiB., errno: 12, strerror: Cannot allocate memory

This error clearly states that you don't have enough RAM.
Not a bug.

> count(distinct ring) uniq

You can replace to `uniqCombined(ring) AS uniq` to save memory.

**Comment by alexey-milovidov** [comment]
Also check overcommit settings: https://clickhouse.yandex/docs/en/operations/tips/#ram

**Comment by kriulkin** [comment]
> uniqCombined(ring) AS uniq

Thanks a lot! But is there any complete explanation about of memory usage by a query ?
