### ISSUE TITLE
LEFT JOIN ....ON SUPPORT

### ISSUE THREAD

**Issue by nolouch** [yandex/ClickHouse#58]
is left join ... on support ? I test and it doesn't work. like (a.uid=b.id) or use regex in on

**Comment by alexey-milovidov** [comment]
Only USING supported, as in documentation: https://clickhouse.yandex/reference_en.html#JOIN%20clause

**Comment by nolouch** [comment]
your parser  is support on,will you plan to support ‘on’?

**Comment by alexey-milovidov** [comment]
Certainly.

**Comment by egorlitvinenko** [comment]
@alexey-milovidov when? :)

**Comment by hmonfared** [comment]
Any update on this feature ?
