### ISSUE TITLE
Docker - add clickhouse-client to image

### ISSUE THREAD

**Issue by vvp83** [yandex/ClickHouse#580]
Docker tag - latest

Please add to image clickhouse-client.

**Comment by bamx23** [comment]
Why are you can't use `yandex/clickhouse-client` image? I don't think that a client should be a part of server image.

**Comment by alexey-milovidov** [comment]
By the way, `clickhouse-client` is just a symlink to `clickhouse`.
You could also run client as `clickhouse --client`.

**Comment by AlekSi** [comment]
Wow. Maybe that could be better documented?

**Comment by AlekSi** [comment]
> You could also run client as clickhouse --client.

Not in the current Docker image:

```
$ docker exec -ti clickhouse_1 /usr/bin/clickhouse --client
ClickHouse client version 1.1.54276.
Connecting to localhost:9000.
Connected to ClickHouse server version 1.1.54276.

Poco::Exception: File not found: /nonexistent/.clickhouse-client-history
```

**Comment by sukantamaikap** [comment]
For connecting to the clickhouse-server container as part of docker-compose 

docker-compose exec -u 0 <<service name or container id>> bash
