### ISSUE TITLE
Timezone UCT instead of UTC

### ISSUE THREAD

**Issue by simPod** [yandex/ClickHouse#5804]
```sql
SELECT intDiv(toStartOfMinute(toDateTime('2019-06-29 00:00:00')), 60);
```

Returns 
> Illegal types DateTime('UCT') and UInt8 of arguments of function intDiv

should be 

```diff
-Illegal types DateTime('UCT') and UInt8 of arguments of function intDiv
+Illegal types DateTime('UTC') and UInt8 of arguments of function intDiv
```

v19.6.2.11

**Comment by den-crane** [comment]
toInt32

SELECT intDiv(toInt32(toStartOfMinute(toDateTime('2019-06-29 00:00:00'))), 60);

It's not because of TZ. And UCT it's the same as UTC (just a symlink in tzdata2019.2) and can be overridden by TZ variable (new feature of CH).

**Comment by simPod** [comment]
Yup, I know I have to convert it to Int for it to work, thanks. 

Just `UCT` seemed like a typo. Do you know a docs/PR where I can learn more about the feature?

**Comment by den-crane** [comment]
UCT is not typo, it's a legacy TZ name. And has no relation to CH.
It's just a symlink in a new version of Linux tzdata.

```
# readlink -f /etc/localtime
/usr/share/zoneinfo/UCT

# dpkg -l 'tzdata*'
||/ Name           Version      Architecture Description
+++-==============-============-============-=======================================
ii  tzdata         2019a-1      all          time zone and daylight-saving time data
```
Zulu === UTC === UCT === Universal.

**Comment by den-crane** [comment]
And CH timezone behavior can be overridden by 

Use contents of environment variable TZ as the name for timezone. 
It helps to correctly detect default timezone in some cases. https://github.com/yandex/ClickHouse/pull/5443 (Ivan)

**Comment by simPod** [comment]
Ok, thanks!

**Comment by alexey-milovidov** [comment]
It's major usability issue when if you run clickhouse-server on a server with new tzdata and clickhouse-client on a server with old tzdata.
