### ISSUE TITLE
clickhouse progress shutdown after log 'Illegal operand'

### ISSUE THREAD

**Issue by qmengss** [yandex/ClickHouse#5812]
recently, my clickhouse process shutdown frequently, error stack like the following:

2019.06.21 23:57:11.628859 [ 2 ] {} <Error> BaseDaemon: ########################################
2019.06.21 23:57:11.628909 [ 2 ] {} <Error> BaseDaemon: (from thread 18) Received signal Illegal instruction (4).
2019.06.21 23:57:11.628920 [ 2 ] {} <Error> BaseDaemon: Illegal operand.
2019.06.21 23:57:11.816579 [ 2 ] {} <Error> BaseDaemon: 0. [0x7f4617254842]
2019.06.21 23:57:11.816672 [ 2 ] {} <Error> BaseDaemon: 1. clickhouse-server(DB::MergingSortedBlockInputStream::init(std::vector<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn> > >&)+0x8d2) [0x4d8d612]
2019.06.21 23:57:11.816689 [ 2 ] {} <Error> BaseDaemon: 2. clickhouse-server(DB::MergingSortedBlockInputStream::readImpl()+0x59) [0x4d8dbb9]
2019.06.21 23:57:11.816699 [ 2 ] {} <Error> BaseDaemon: 3. clickhouse-server(DB::IProfilingBlockInputStream::read()+0x205) [0x487d7a5]
2019.06.21 23:57:11.816712 [ 2 ] {} <Error> BaseDaemon: 4. clickhouse-server(DB::MergeTreeDataMergerMutator::mergePartsToTemporaryPart(DB::MergeTreeDataMergerMutator::FuturePart const&, DB::MergeListEntry&, long, DB::DiskSpaceMonitor::Reservation*, bool)+0x284f) [0x4c0e23f]
2019.06.21 23:57:11.816724 [ 2 ] {} <Error> BaseDaemon: 5. clickhouse-server(DB::StorageMergeTree::merge(bool, std::string const&, bool, bool, std::string*)+0x3d7) [0x4b538b7]
2019.06.21 23:57:11.816733 [ 2 ] {} <Error> BaseDaemon: 6. clickhouse-server(DB::StorageMergeTree::backgroundTask()+0xf1) [0x4b56621]
2019.06.21 23:57:11.816742 [ 2 ] {} <Error> BaseDaemon: 7. clickhouse-server(DB::BackgroundProcessingPool::threadFunction()+0x396) [0x4bc36b6]
2019.06.21 23:57:11.816751 [ 2 ] {} <Error> BaseDaemon: 8. clickhouse-server() [0x632d54f]
2019.06.21 23:57:11.816760 [ 2 ] {} <Error> BaseDaemon: 9. /lib64/libpthread.so.0(+0x7dd5) [0x7f4627be0dd5]

the clickhouse-server version is 19.1.8 .
the operating system is CentOS Linux release 7.6.1810 (Core) .

**Comment by den-crane** [comment]
You need to upgrade at least to 19.1.14.

https://github.com/yandex/ClickHouse/pull/4623
