### ISSUE TITLE
`SELECT count()` could be faster

### ISSUE THREAD

**Issue by nvartolomei** [yandex/ClickHouse#5813]
At the moment `SELECT count()` reads smallest column (DateType width), it could pick one which is smallest in terms of bytes on disk instead. (ie a column of primary key).

Ticket for rainy days.

**Comment by alexey-milovidov** [comment]
https://github.com/yandex/ClickHouse/issues/2099

This was my attempt but it's abandoned:
https://github.com/yandex/ClickHouse/commit/a763a4a6c94bc0448cd35d174746f82e985338fa

CC @amosbird

**Comment by amosbird** [comment]
OK. Why is it abandoned?

**Comment by alexey-milovidov** [comment]
I was thought that I can implement it in one hour. After a few hours there were one or two failing tests. Then I switched to more important tasks and never finished. You are the only hope :)

**Comment by amosbird** [comment]
I'll see what I can do :)

**Comment by filimonov** [comment]
Should work in 19.13 and above.

**Comment by filimonov** [comment]
Side effect - that can lead to using the columns which is smaller but which is much more expensive for decompressing.
```sql
CREATE TABLE cnt_test
(
    `n` UInt64 CODEC(DoubleDelta, ZSTD(20)), 
    `n2` UInt64
)
ENGINE = MergeTree()
ORDER BY tuple();

insert into cnt_test SELECT number - 1000 + rand() % 2000 as x, x from numbers(10000000);

select count(n) from cnt_test; --  Elapsed: 0.837 sec. (smaller, but unpack is expensive)
select count(n2) from cnt_test; -- Elapsed: 0.172 sec. (larger, but unpack is cheap)
select count() from cnt_test;  --Elapsed: 0.821 sec (picks n)
```

**Comment by alexey-milovidov** [comment]
@amosbird has already addressed this issue in one of PRs. We select based on compressed size and uncompressed size.

**Comment by alexey-milovidov** [comment]
BTW, a763a4a is still not implemented.
