### ISSUE TITLE
DB::Exception: Unknown table engine Kafka.

### ISSUE THREAD

**Issue by Vxider** [yandex/ClickHouse#5821]
I have build ClickHouse from source with the latest github version. Both three types of creating Kafka table from [Instruction](https://clickhouse.yandex/docs/en/operations/table_engines/kafka/) encountered `DB::Exception: Unknown table engine Kafka.`

I have tried these three types of SQL

```
  CREATE TABLE queue (
    timestamp UInt64,
    level String,
    message String
  ) ENGINE = Kafka('localhost:9092', 'topic', 'group1', 'JSONEachRow');

  SELECT * FROM queue LIMIT 5;

  CREATE TABLE queue2 (
    timestamp UInt64,
    level String,
    message String
  ) ENGINE = Kafka SETTINGS kafka_broker_list = 'localhost:9092',
                            kafka_topic_list = 'topic',
                            kafka_group_name = 'group1',
                            kafka_format = 'JSONEachRow',
                            kafka_num_consumers = 4;

  CREATE TABLE queue2 (
    timestamp UInt64,
    level String,
    message String
  ) ENGINE = Kafka('localhost:9092', 'topic', 'group1')
              SETTINGS kafka_format = 'JSONEachRow',
                       kafka_num_consumers = 4;
```

**Comment by millin** [comment]
You need to install librdkafka and clone this repo with submodules to build ClickHouse with Kafka engine.

**Comment by den-crane** [comment]
>I have build ClickHouse from source with the latest github version. 

So you've compiled CH without Kafka. Why do you need to build CH by yourself? 

You can download latest build https://github.com/yandex/ClickHouse press green check sign -> details on 'ClickHouse build check' and download  'bundled | unsplitted'

for example https://clickhouse-builds.s3.yandex.net/0/106a2d0c0f44d09ac50376304977e3909b989c1e/report.html

**Comment by alexey-milovidov** [comment]
We also have nightly releases for .deb and .rpm in:
https://repo.yandex.ru/clickhouse/deb/testing/main/
https://repo.yandex.ru/clickhouse/rpm/testing/x86_64/

**Comment by alexey-milovidov** [comment]
> You need to install librdkafka

No, you don't have to install rdkafka, because we have this library in our submodules.

**Comment by alexey-milovidov** [comment]
To figure out, why Kafka support is not enabled, you can check cmake out for `kafka` substring.

**Comment by filimonov** [comment]
Most probably non linux platform (macos?), rdkafka build is not working properly on other platforms currently and is disabled in cmake.

**Comment by Vxider** [comment]
Thanks for replying, I was build on macos with rdkafka installed by homebrew, the cmake can find rdkafka path correctly, but it seems that the `contrib/CMakeLists.txt` does not include rdkafka path when `USE_INTERNAL_RDKAFKA_LIBRARY=OFF`, cause undefined exception when compiling `cppkafka`. I switched to the Linux  and everything is working properly.
