### ISSUE TITLE
Complex or mixed/long data

### ISSUE THREAD

**Issue by imdad1410** [yandex/ClickHouse#5831]
I have been trying to load data from a JSON( for example take the yelp
data set available)  file to Clickhouse but every time I get a parse
error as the file contains long strings with special characters included
in them for a few fields/attributes.

Also even when I try to load a CSV file with one field containing
special characters, it does not parse.

Are there any data types for such cases as the available data types does
not support those fields and I am not being able to load anything in
clickhouse.

**Comment by filimonov** [comment]
What do you mean by 'special characters'? Can you provide some minimal sample?

**Comment by imdad1410** [comment]
For example the yelp dataset in Json Format. I am trying to load it in clickhouse using 
`cat yelp_academic_dataset_business.json | clickhouse-client --input_format_skip_unknown_fields=1 --query="INSERT INTO dem FORMAT JSONEachRow`

The error I get `Code: 27. DB::Exception: Cannot parse input: expected [ before: "Golf, Active Life","hours":null}\n{"business_id":"QXAEGFB4oINsVuTFxEYKFQ","name":"Emerald Chinese Restaurant","address":"30 Eglinton Avenue W","city":"Mississau: (while read the value of key categories): (at row 1)`

The column where it is showing error has been declared as a String data type.

**Comment by filimonov** [comment]
If you will provide create table statement and sample file it will be much easier to help you.
