### ISSUE TITLE
How to pretty print a generated RowBinary file?

### ISSUE THREAD

**Issue by q0987** [yandex/ClickHouse#5853]
Hello all,

Given a valid ClickHouse RowBinary file, how I can prettyprint the row data within the file?

Thank you

**Comment by alexey-milovidov** [comment]
Sure! It's very easy to do with `clickhouse-local`:

```
clickhouse-local --structure "x UInt8, y String, ..." --query "SELECT * FROM table" --input-format RowBinary --output-format TSV
```

You have to know correct data structure (`--structure` parameter).

You can use `clickhouse-local` tool for converting between various formats and for data processing without a server.

**Comment by alexey-milovidov** [comment]
If you want **pretty**print, use `--output-format Pretty`.

**Comment by q0987** [comment]
It works for me.

Thank you!
