### ISSUE TITLE
Cross data center replication

### ISSUE THREAD

**Issue by Slind14** [yandex/ClickHouse#5869]
Hi,

is there any issue with setting up clickhouse with a cross datacenter replication? (latency)

**Comment by blinkov** [comment]
Many companies are doing that, including Yandex. Of course it's not a guarantee that you'll encounter none, but in general it works fine.

**Comment by Slind14** [comment]
Ok, thanks. Is that the same for zookeeper or do you always keep it in one datacenter?

**Comment by alexey-milovidov** [comment]
At Yandex we use 3-node ZooKeeper cluster spread across 3 datacenters with maximum about 25ms RTT and 1500 km distance.

**Comment by alexey-milovidov** [comment]
From experience of our clients, multi-continent ZooKeeper clusters are less usable.
