### ISSUE TITLE
Problem when selecting all columns from a join

### ISSUE THREAD

**Issue by George3d6** [yandex/ClickHouse#587]
When running a query alike:

SELECT * FROM
(SELECT * FROM t1)
ALL LEFT JOIN
(SELECT * FROM t2)
USING join_id

The result shows only the columns from t1, if I explicitly specify columns from t2 (e.g. SELECT *, col1, col2, col3... etc) then they are shown properly, but I would have assumed the * operator to SELECT all columns from the join, rather than from the first table. Is this normal behavior ? Or is it a bug or misuse of the query language ?

**Comment by alexey-milovidov** [comment]
This is current behaviour, please don't rely on it.
We have intention to change it to standard behaviour as soon as possible.

**Comment by alexey-milovidov** [comment]
Fixed in version 18.12.
https://github.com/yandex/ClickHouse/blob/master/CHANGELOG.md
> In requests with JOIN, the star character expands to a list of columns in all tables, in compliance with the SQL standard. You can restore the old behavior by setting asterisk_left_columns_only to 1 on the user configuration level. Winter Zhang
