### ISSUE TITLE
Can startsWith Function Be Optimized?

### ISSUE THREAD

**Issue by MeteHanC** [yandex/ClickHouse#5882]
**Use case**

Let's say I have a table which has +- 500K rows and is ordered by keyword. Create table query is;

`CREATE TABLE DEMO (`keyword` String) ENGINE = MergeTree() ORDER BY (keyword) SETTINGS index_granularity = 8192`

When I query for a specific keyword, for instance 

` select * from DEMO where keyword ='hastalık'`

It processes **8K** rows since it is ordered by keyword. But when I query with a 'startsWith' clause;

`select count() from DEMO where startsWith(keyword, 'h')`

It processes all **500K** rows. It is already ordered so why does it process all the rows?

**Comment by filimonov** [comment]
Duplicate #5310.
