### ISSUE TITLE
Unknown Function Format

### ISSUE THREAD

**Issue by MeteHanC** [yandex/ClickHouse#5884]
ClickHouse Version : version 19.7.5

Format function is not working at all. It is documented on this page : [ClickHouse Format Doc](https://clickhouse.yandex/docs/en/query_language/functions/string_functions/#format-pattern-s0-s1)

`SELECT format('{} {}', 'Hello', 'World')`

Returns ;

` DB::Exception: Unknown function format.`

And as far as I can see, there is no test case for the 'format' function too.

**Comment by YiuRULE** [comment]
https://clickhouse.yandex/docs/en/changelog/

Seem the `format` function has been release on the version `19.8.3.8`
You can check the documentation for your version on https://clickhouse.yandex/docs/v19.7/en/ :)
