### ISSUE TITLE
Exception during INSERT is not printed by clickhouse-client.

### ISSUE THREAD

**Issue by alexey-milovidov** [yandex/ClickHouse#5891]
```
$ clickhouse-client --query "INSERT INTO metrika_searches_07 FORMAT TSKV" < traf.dsv
Code: 210. DB::NetException: Connection reset by peer, while writing to socket ([::1]:9000)
```

In server logs:
```
2019.07.05 16:33:03.446593 [ 56 ] {9e2b9b1c-f2ac-465c-938c-96a5a3b51180} <Error> executeQuery: Code: 252, e.displayText() = DB::Exception: Too many partitions for single INSERT block (more than 100). The limit is controlled by 'max_partitions_per_insert_block' setting. Large number of partitions is a common misconception. It will lead to severe negative performance impact, including slow server startup, slow INSERT queries and slow SELECT queries. Recommended total number of partitions for a table is under 1000..10000. Please note, that partitioning is not intended to speed up SELECT queries (ORDER BY key is sufficient to make range queries fast). Partitions are intended for data manipulation (DROP PARTITION, etc). (version 19.11.0) (from [::1]:50014) (in query: INSERT INTO metrika_searches_07 FORMAT TSKV)
```

**Comment by alexey-milovidov** [comment]
@dimarub2000 Need to investigate this issue (how the server <-> client protocol works and is it possible to fix this issue without much effort).

**Comment by dimarub2000** [comment]
Can't reproduce the problem
`dimarub2000@virtual:~/ClickHouse/build/dbms/programs$ ./clickhouse-client -q "insert into mtree format CSV" < ~/common/kek.csv 
Received exception from server (version 19.14.1):
Code: 252. DB::Exception: Received from localhost:9000. DB::Exception: Too many partitions for single INSERT block (more than 100). The limit is controlled by 'max_partitions_per_insert_block' setting. Large number of partitions is a common misconception. It will lead to severe negative performance impact, including slow server startup, slow INSERT queries and slow SELECT queries. Recommended total number of partitions for a table is under 1000..10000. Please note, that partitioning is not intended to speed up SELECT queries (ORDER BY key is sufficient to make range queries fast). Partitions are intended for data manipulation (DROP PARTITION, etc).. `

**Comment by alexey-milovidov** [comment]
```
milovidov-Pro-P30 :) CREATE TABLE check (x UInt64, CONSTRAINT c1 CHECK x < 10000000) ENGINE = Memory

CREATE TABLE check
(
    `x` UInt64, 
    CONSTRAINT c1 CHECK x < 10000000
)
ENGINE = Memory

Ok.

0 rows in set. Elapsed: 0.033 sec. 

milovidov-Pro-P30 :) Bye.
milovidov@milovidov-Pro-P30:~/work/ClickHouse/dbms/tests$ seq 1 11000000 | clickhouse-client --query="INSERT INTO check FORMAT TSV"
Code: 210. DB::NetException: Connection reset by peer, while writing to socket (127.0.0.1:9000)
```
