### ISSUE TITLE
IS NULL and IS NOT NULL equivalents

### ISSUE THREAD

**Issue by Ngalstyan4** [yandex/ClickHouse#59]
Hey, 
Is there a way to figure out whether the value of a field is the default value or not?

I know that I can do
`SELECT * from TABLE where int == 0` for numbers and 
`SELECT * from TABLE where str == "` but is there a way to unify these two and write sth like 
`SELECT * from TABLE where var == default(var)`

**Comment by alexey-milovidov** [comment]
The idea is interesting but there are reasons of not doing it in that form or to postpone implementation:

1. Support for NULLs, Nullable data types and real IS NULL, IS NOT NULL operators is developed right now.
2. Suggested 'default' function, if implemented, would be very unusual. It is not ordinary function, but some kind of symbolic expression. Implementation is fairly easy but not consistent.

**Comment by Ngalstyan4** [comment]
You mentioned IS NULL, IS NOT NULL _are developed_ 
Is it available in a release?

**Comment by alexey-milovidov** [comment]
Are in development (in a branch).
