### ISSUE TITLE
Not found column in distributed table with columnName ALIAS expr

### ISSUE THREAD

**Issue by xoddarrin** [yandex/ClickHouse#590]
I have a distributed table:
`CREATE TABLE distributed.events ( 
    createdDate Date,
    column1 String,
    column2 String,
    column4 String ALIAS concat(column1, column2)
) ENGINE = Distributed(cluster, '', events)`

While trying to select data from it:
`SELECT column4 from events`

I'm getting such exception
`DB::Exception: Not found column: column1`

Looking forward for your help.

**Comment by ludv1x** [comment]
Confirmed.
Distributed engine don't fetch dependent columns.

As workaround you can to add not found columns explicitly:
```
SELECT column1, column2, column4 from events
```

**Comment by MikhailKalashnikov** [comment]
I have a similar error with a distributed table with an alias column:

```sql
CREATE DATABASE tmpdb;

CREATE TABLE tmpdb.test_alias_local10 (
  Id Int8,
  EventDate Date DEFAULT today(),
  field1 Int8,
  field2 String,
  field3 ALIAS CASE WHEN field1 = 1 THEN field2 ELSE '0' END
) ENGINE = MergeTree(EventDate, (Id, EventDate), 8192);

CREATE TABLE tmpdb.test_alias10 AS tmpdb.test_alias_local10 ENGINE = Distributed(s3_r1, tmpdb, test_alias_local10, cityHash64(Id));

INSERT INTO tmpdb.test_alias10 (Id, EventDate, field1, field2)
VALUES (1, today(), 1, '12345'), (2, today(), 2, '54321'), (3, today(), 0, '');
```

This query returns error. But column EventDate is not in the ALIAS expression
```
SELECT field1, field2, field3 FROM tmpdb.test_alias10 WHERE EventDate=today()
Not found column EventDate in block. There are only columns: field1, field2, field3, caseWithoutExpr(equals(field1, 1), field2, '0')
```

While following queries work without error 
```
SELECT field1, field2 FROM tmpdb.test_alias10 WHERE EventDate=today();
SELECT field1, field2, field3 FROM tmpdb.test_alias10;
```


@ludv1x Is this the similar problem or I should register another issue?

**Comment by zhang2014** [comment]
@ludv1x There are scripts in the project that will allow me to quickly start the distributed environment to reproduce this type of problem?

**Comment by ludv1x** [comment]
@zhang2014 There are integration test (see `dbms/tests/integration/test_insert_into_distributed_sync_async/test.py` for example).
In these tests, you can build any virtual cluster environment inside `docker`.

Hopefully, to debug and fix this problem you can build simple "fake" cluster consisting of `127.0.0.N` hosts:
```
    <test_fail_shard_localhost>
        <shard>
            <internal_replication>false</internal_replication>
                <replica>
                    <host>127.0.0.1</host>
                    <port>9000</port>
                </replica>
        </shard>
        <shard>
            <internal_replication>false</internal_replication>
                <replica>
                    <host>127.0.0.2</host>
                    <port>9000</port>
                </replica>
        </shard>
    </test_fail_shard_localhost>
```

**Comment by zhang2014** [comment]
@ludv1x Thanks！！

**Comment by alexey-milovidov** [comment]
Fixed in master.
