### ISSUE TITLE
No output from show processlist

### ISSUE THREAD

**Issue by nshah14285** [yandex/ClickHouse#5905]
Using clickhouse version 19.9.3.31.
"Show Processlist" command does not list any active running query.
It always displays as below
> SHOW PROCESSLIST

> Ok.

> 0 rows in set. Elapsed: 0.002 sec. 

Any idea?

**Comment by alexey-milovidov** [comment]
It may return empty set if you have no running queries.

**Comment by alexey-milovidov** [comment]
I have tested on version 19.11 with `SELECT sleep(3)` query and everything is displayed as expected.

**Comment by alexey-milovidov** [comment]
Please note, that in contrast to MySQL, `SHOW PROCESSLIST` does not display idle client connections.
