### ISSUE TITLE
simdjson is slower than rapidjson on small strings.

### ISSUE THREAD

**Issue by alexey-milovidov** [yandex/ClickHouse#5937]
That's expected, but we can improve it by dynamically choose the best algorithm by the average string length. Caveats: large portion of strings can be empty and both libraries work equally good at them.

**Comment by alexey-milovidov** [comment]
Is it fixed by patching simdjson? https://github.com/lemire/simdjson/pull/276

**Comment by vitlibar** [comment]
For example, https://clickhouse-test-reports.s3.yandex.net/0/0e896fb341f5474b0e1c6a2a3dfeea83ab61655e/performance_test/comparison_min_time_gcc_9.html

test | rapidjson (s) | simdjson (s)
----- | ---------------- | -----------------
1 | 0.212 | 0.153
2 | 0.213 | 0.156
3 | 0.214 | 0.152 
4 | 0.211 | 0.157 
5 | 0.213 | 0.157 
6 | 0.741 | 0.302 
7 | 0.783 | 0.334 
8 | 0.732 | 0.316 
9 | 0.697 | 0.312
10 | 1.131 | 0.721 
11 | 0.734 | 0.318 
12 | 0.762 | 0.362 
13 | 0.662 | 0.312
