### ISSUE TITLE
add user parsing in engine HDFS (createHDFSBuilder)

### ISSUE THREAD

**Issue by akonyaev90** [yandex/ClickHouse#5945]
**Use case**
when we using HDFs with hadoop.security.authentication=simple, we can't set username for hdfs-table.
Now hdfsLib use user from under which clickhouse is running
User in URI is ignored

**Describe the solution**
add in createHDFSBuilder set user method call

Something like this:
`auto & userInfo = uri.getUserInfo();`
`hdfsBuilderSetUserName(builder.get(), strtok(const_cast<char *> (userInfo.c_str()), ":"));`

**Comment by akonyaev90** [comment]
```
    std::string userInfo = uri.getUserInfo();
    if (userInfo.front() != ':') {
        char *user = strtok(const_cast<char *> (userInfo.c_str()), ":");
        if (user != NULL) {
            hdfsBuilderSetUserName(builder.get(), user);
        }
    }
```
I think this code is good solution to this issue.

**Comment by filimonov** [comment]
> ```
>     std::string userInfo = uri.getUserInfo();
>     if (userInfo.front() != ':') {
>         char *user = strtok(const_cast<char *> (userInfo.c_str()), ":");
>         if (user != NULL) {
>             hdfsBuilderSetUserName(builder.get(), user);
>         }
>     }
> ```
> 
> I think this code is good solution to this issue.

Can you send a pull request with proposed change? In that case your change will be built & checked by CI and you will be able to download build with that change and check it in your environment. If you will be also able to create integration test (see https://github.com/yandex/ClickHouse/tree/master/dbms/tests/integration/test_storage_hdfs) - it would be brilliant!

**Comment by akonyaev90** [comment]
https://github.com/yandex/ClickHouse/pull/5946
Already merged
