### ISSUE TITLE
ThreadSanitizer failure in Poco::ActiveDispatcher

### ISSUE THREAD

**Issue by akuzm** [yandex/ClickHouse#5950]
ThreadSanitizer reports a data race in Poco::ActiveDispatcher
https://clickhouse-test-reports.s3.yandex.net/0/bf4ace06e81280ad9323a2c03443de4466e83a63/stress_test_(thread).html
see stderr.log

What happens is that ActiveDispatcher constructor starts a thread that calls its method run(). This is a virtual method inherited from Runnable. There is no synchronization between the thread body and the constructor of objects derived from ActiveDispatcher, so the thread may call a method of a partially constructed object. If a class derived from ActiveDispatcher overrides run(), this leads to pure virtual call. ActiveDispatcher isn't used like this, so we haven't seen any real-world consequences of this, but logically this is an error, and tsan is right to complain.

We use this class indirectly when compressing and rotating log files. The code is the same in today's Poco upstream, so we should fix this and send them a PR.

**Comment by alexey-milovidov** [comment]
Fixed.

**Comment by alexey-milovidov** [comment]
Upstream PR is up to you.
