### ISSUE TITLE
SELECT FROM engineFile in the right side of IN operator

### ISSUE THREAD

**Issue by topvisor** [yandex/ClickHouse#5961]
**Describe the bug**
A "timeout exceeded" error occures while using `SELECT FROM engineFile` subquery in the right side of `IN` operator in `WHERE` clause of table of "MergeTree" family.

**How to reproduce**
ClickHouse server version 19.9.3.31 (official build).

Non-default settings:
<pre>
max_execution_time=60
</pre>

`CREATE TABLE` statements:
<pre>
CREATE TABLE IF NOT EXISTS `default`.`testTableFile` 
(`number` UInt64) 
ENGINE = File('TSV')

CREATE TABLE IF NOT EXISTS `default`.`testTableMergeTree`
(`id` UInt64) 
ENGINE = MergeTree()
PARTITION BY `id`
ORDER BY `id`
</pre>

Sample data:
<pre>
INSERT INTO `default`.`testTableFile` 
SELECT `number` 
FROM `system`.`numbers` 
LIMIT 10

INSERT INTO `default`.`testTableMergeTree` 
SELECT `number`
FROM `system`.`numbers` 
LIMIT 100
</pre>

Query to run that lead to unexpected result:
<pre>
SELECT *
FROM `default`.`testTableMergeTree` 
WHERE (
    `id` IN (
        SELECT `number` 
        FROM `default`.`testTableFile`
    )
)
</pre>

**Error message**
<pre>
Code: 159, e.displayText() = DB::Exception: Timeout exceeded: elapsed 60.003591484 seconds, maximum: 60 (version 19.9.3.31 (official build))
</pre>

**Comment by decaseal** [comment]
This error didn't throw in ClickHouse server version 19.6.3.18 (official build)

**Comment by vitlibar** [comment]
Fixed in master.
