### ISSUE TITLE
ClickHouse 19.9.4.34 cannot start if /etc/localtime a is symlink.

### ISSUE THREAD

**Issue by citrin** [yandex/ClickHouse#5975]
**Describe the bug**
ClickHouse cannot start if `/etc/localtime` is a symlink.

**How to reproduce**
* Build and install ClickHouse server version 19.9.4.34 on CentOS 7.
* Run `su -m -s /bin/sh clickhouse -c '/usr/bin/clickhouse-server --config-file=/etc/clickhouse-server/config.xml'` (config is default)

**Expected behavior**
ClickHouse should start.

**Error message and/or stacktrace**
```
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
Logging trace to console
Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Exception: Could not determine local time zone: boost::filesystem::canonical: No such file or directory: "/etc/usr/share/zoneinfo/UTC" (version 19.9.4.34)
Aborted
```

**Additional context**
`/etc/localtime` is a symlink on CentOS (and may be some other distros):
```
# ls -l /etc/localtime
lrwxrwxrwx 1 root root 25 Mar  5 17:36 /etc/localtime -> ../usr/share/zoneinfo/UTC
# strings /etc/localtime
TZif2
TZif2
UTC0
```

**Comment by citrin** [comment]
Also it looks like at least in this case time zone could be determined just reading `/etc/localtime` content. No need to look where symlink is pointing to.

**Comment by blind-oracle** [comment]
https://github.com/yandex/ClickHouse/commit/4e1286e1e562d7ec3e7ddf51fb982a5b75359bd1

This commit didn't make it to 19.9, needs to be backported.

**Comment by alexey-milovidov** [comment]
Done: https://github.com/yandex/ClickHouse/pull/5626

**Comment by alexey-milovidov** [comment]
But I strongly recommend to upgrade to 19.11 instead.
