### ISSUE TITLE
CREATE TABLE without Engine spec SIGSEGV

### ISSUE THREAD

**Issue by vavrusa** [yandex/ClickHouse#598]
Hi, I was fiddling with MATERIALIZED VIEWs, and when I create a table by using MV schema without ENGINE spec it crashes. A minimal example would be something like:

```sql
CREATE TABLE tmp (date Date, name String) ENGINE ...;
CREATE MATERIALIZED VIEW tmp_mv ENGINE = AggregatingMergeTree(date, (name), 8192) AS SELECT date, name, countState() AS cc FROM tmp GROUP BY name;
CREATE TABLE IF NOT EXISTS tmp_mv_table AS tmp_mv;
```

Crashes with:

```
<Error> BaseDaemon: ########################################
<Error> BaseDaemon: (from thread 118) Received signal Segmentation fault (11).
<Error> BaseDaemon: Address: NULL pointer.
<Error> BaseDaemon: 1. /usr/bin/clickhouse-server(DB::StorageView::StorageView(std::string const&, std::string const&, DB::Context&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::NamesAndTypesList>, DB::NamesAndTypesList const&, DB::NamesAndTypesList const&, std::unordered_map<std::string, DB::ColumnDefault, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, DB::ColumnDefault> > > const&)+0x428) [0x12ef6a8]
<Error> BaseDaemon: 2. /usr/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x96) [0x325d216]
<Error> BaseDaemon: 3. /lib/x86_64-linux-gnu/libpthread.so.0(+0x8064) [0x7f4e62c7f064]
<Error> BaseDaemon: 4. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f4e622a762d]
```

It's the last stable 1.1.54180.

It works when I create the the table from MV as:

```sql
CREATE TABLE IF NOT EXISTS tmp_mv_table AS tmp_mv ENGINE = ...;
```

**Comment by ludv1x** [comment]
Ok. Thank you for the report.

But it is not clear for me what should such clause do
```
CREATE TABLE IF NOT EXISTS tmp_mv_table AS tmp_mv;
```

Either materialized view
```
CREATE TABLE tmp_mv_table (date Date, name String, cc AggregateFunction(count)) ENGINE = AggregatingMergeTree(date, (name), 8192)
```
, either ordinary table with MV schema
```
CREATE MATERIALIZED VIEW tmp_mv_table ENGINE = AggregatingMergeTree(date, (name), 8192) AS SELECT date, name, countState() AS cc FROM tmp GROUP BY name;
```

Currently
```
CREATE TABLE IF NOT EXISTS tmp_mv_table AS tmp_mv ENGINE = ...;
``` 
creates ordinary table with specified engine.
But for me it is more logically to create MV with specified engine.
If engine isn't specified, it will use the same engine as tmp_mv.

**Comment by vavrusa** [comment]
My expectation was that `CREATE TABLE IF NOT EXISTS tmp_mv_table AS tmp_mv` creates a table that reuses the same engine as the MV (AggregatingMergeTree), but it's perfectly fine if it requires me to say explicitly what the engine should be. It just shouldn't crash the CH.

**Comment by ludv1x** [comment]
Yes, of course -)
I just needed an opinion about the semantics.

**Comment by vavrusa** [comment]
Sure :) I'd vote for: when the statment says `CREATE TABLE`, it should create a table and not MV.
The MVs are really cool by the way, really cheap way how to do rollups.
