### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by vincenzon** [yandex/ClickHouse#5983]
Hello,

Sorry, I cannot participate in telegram from work. I am running CH in a container (one of a collection), it has been working fine. The containers were recently recreated on a different machine and we started seeing this error when the service is started:

`root@47e7fcd869c9:/var/log/clickhouse-server# service clickhouse-server start`
`Start clickhouse-server service: Path to data directory in /etc/clickhouse-server/config.xml: /var/lib/clickhouse/`
`UNKNOWN`

It takes about 10 seconds after the "Start ..." line to emit the "UNKNOWN" line. The clickhouse-server.err.log shows:

`2019.07.11 18:37:05.517792 [ 1 ] {} <Error> Application: DB::Exception: Listen [::]:8123 failed: 0: DNS error: EAI: -9`

We thought that the set up of this machine was the same as the older machine that works, but apparently not. There are two differences, the non-working one was built today, the working one was built a month ago, so possibly different packages (these are Ubuntu-18.04 images). Also the machines are possibly different in some way, possibly different docker configurations (though not intentionally). 

Does this log error look familiar to anyone? Thanks in advance for any help,

Matt

**Comment by filimonov** [comment]
> DNS error: EAI: -9

Mist problably you have IPv6 disabled. Try to replace listen address from `::` to `0.0.0.0`

**Comment by filimonov** [comment]
Relates to #5932?

**Comment by vincenzon** [comment]
Thanks @filimonov  I arrived at the change of '::' to '0.0.0.0' after reading https://www.altinity.com/blog/2019/3/15/clickhouse-networking-part-1 and that fixed it. I'm not sure why ipv6 is turned off on the new machine, but thanks for your help.
