### ISSUE TITLE
Querying of system.tables become quite slow after upgrading from 1.1.54380

### ISSUE THREAD

**Issue by ddliu** [yandex/ClickHouse#5987]
After upgrading from version 1.1.54380 to latest(and also tried several recent versions), I come across a performance issue when query table `system.tables`.

For a database with 3000 tables, query time increased from 0.005 sec to 0.255 sec.

And here is the repo to reproduce the issue: https://github.com/ddliu/clickhouse-tune

**Comment by ddliu** [comment]
Tried to specify all columns instead of "*", it's much faster(0.009 sec), about twice of `1.1.54380`(0.005 sec).

```
SELECT
    database,
    name,
    engine,
    is_temporary,
    data_path,
    metadata_path
FROM system.tables
WHERE name = 'test_997'

┌─database─┬─name─────┬─engine────┬─is_temporary─┬─data_path───────────────────────────────┬─metadata_path──────────────────────────────────┐
│ test     │ test_997 │ MergeTree │            0 │ /var/lib/clickhouse/data/test/test_997/ │ /var/lib/clickhouse/metadata/test/test_997.sql │
└──────────┴──────────┴───────────┴──────────────┴─────────────────────────────────────────┴────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.009 sec. Processed 3.03 thousand rows, 465.97 KB (330.40 thousand rows/s., 50.76 MB/s.)
```

**Comment by den-crane** [comment]
because NOW CH reads columns create_table_query engine_full from metadata from .sql

**Comment by ddliu** [comment]
Got it, thank you for your explain.

**Comment by wzjandfigo** [comment]
@den-crane Why these two columns （create_table_query ，engine_full ）are not directly read from in-memory table ？What is the purpose of this coding design? thank you！

**Comment by den-crane** [comment]
@wzjandfigo  because developer decided to implement it this way, no specific reason.
