### ISSUE TITLE
load data with CSVWithNames or TabSeparatedWithNames got error when two columns  continuous  null

### ISSUE THREAD

**Issue by lordk911** [yandex/ClickHouse#5990]
I'm using clickhouse 19.9.2.4 , my csv file data like : 
business_id,dates,goods_id,tbill_code,membership_card_id,fact_new_card_id,atc1_new,atc2_new,atc3_new,atc4_new,goods_name,sex,age,birthdays,is_subscribe_wx,subscribe_time,subscribe_store,activate_time,activate_store,first_buy_date,paid_in_amt,profit
12501,2018-02-21,1062069,hnhys_PZ1A2500351654,801159913,801159913,OTC,儿科用药,儿童胃肠道用药,儿童消化不良/厌食,健儿清解液,2,NULL,NULL,0,NULL,A10U,NULL,A10U,2017-11-27,19.800000,8.300000

when I try to load data with CSVWithNames , I got error :  
Column 0,   name: business_id,        type: String,         parsed text: "12501"
Column 1,   name: dates,              type: String,         parsed text: "2018-02-21"
Column 2,   name: goods_id,           type: String,         parsed text: "1062069"
Column 3,   name: tbill_code,         type: String,         parsed text: "hnhys_PZ1A2500351654"
Column 4,   name: membership_card_id, type: String,         parsed text: "801159913"
Column 5,   name: fact_new_card_id,   type: String,         parsed text: "801159913"
Column 6,   name: atc1_new,           type: String,         parsed text: "OTC"
Column 7,   name: atc2_new,           type: String,         parsed text: "儿科用药"
Column 8,   name: atc3_new,           type: String,         parsed text: "儿童胃肠道用药"
Column 9,   name: atc4_new,           type: String,         parsed text: "儿童消化不良/厌食"
Column 10,  name: goods_name,         type: String,         parsed text: "健儿清解液"
Column 11,  name: sex,                type: UInt32,         parsed text: "2"
Column 12,  name: age,                type: UInt32,         ERROR: text "NULL,NULL," is not like UInt32

what should I do ?

**Comment by lordk911** [comment]
if I data is like this : 
12501,2018-02-21,1062069,hnhys_PZ1A2500351654,801159913,801159913,OTC,儿科用药,儿童胃肠道用药,儿童消化不良/厌食,健儿清解液,2,,,0,,A10U,,A10U,2017-11-27,19.800000,8.300000 

Column 0,   name: business_id,        type: String,         parsed text: "12501"
Column 1,   name: dates,              type: String,         parsed text: "2018-02-21"
Column 2,   name: goods_id,           type: String,         parsed text: "1062069"
Column 3,   name: tbill_code,         type: String,         parsed text: "hnhys_PZ1A2500351654"
Column 4,   name: membership_card_id, type: String,         parsed text: "801159913"
Column 5,   name: fact_new_card_id,   type: String,         parsed text: "801159913"
Column 6,   name: atc1_new,           type: String,         parsed text: "OTC"
Column 7,   name: atc2_new,           type: String,         parsed text: "儿科用药"
Column 8,   name: atc3_new,           type: String,         parsed text: "儿童胃肠道用药"
Column 9,   name: atc4_new,           type: String,         parsed text: "儿童消化不良/厌食"
Column 10,  name: goods_name,         type: String,         parsed text: "健儿清解液"
Column 11,  name: sex,                type: UInt32,         parsed text: "2"
Column 12,  name: age,                type: UInt32,         ERROR: text ",,0,,A10U," is not like UInt32

**Comment by akuzm** [comment]
First, please make sure that the type of column is Nullable(Int32), or else it won't be able to store nulls. Then, use '\N' for null values, not 'NULL'. Alternatively, you can set `input_format_defaults_for_omitted_fields = 1`, and then empty values like in your second example will be treated as nulls.
