### ISSUE TITLE
DB::Exception: File not found on long running insert (version 19.10.1)

### ISSUE THREAD

**Issue by ocmajortom** [yandex/ClickHouse#5997]
Hi,
while doing a long running insert into MergeTree-Table (insert into table select with many joins... blabla) I get the following error:

`Exception: File not found: /var/lib/clickhouse/data/test/tickets_flat/tmp_insert_5_69_69_0. `

server log prints:

`2019.07.13 00:33:04.648858 [ 113 ] {} <Trace> test.tickets_flat: Renaming temporary part tmp_insert_5_69_69_0 to 5_69_69_0.`
`2019.07.13 00:33:04.746307 [ 41 ] {c78ae94a-3aa2-4def-9d34-cef5af9ed6f4} <Error> executeQuery: Poco::Exception. Code: 1000, e.code() = 2
, e.displayText() = File not found: /var/lib/clickhouse/data/test/tickets_flat/tmp_insert_5_69_69_0 (version 19.10.1.5 (official build)`

**Comment by den-crane** [comment]
Please provide DDL of tickets_flat. Do you use   Date(Int16 / Int8) ... CODEC(Delta ?

**Comment by ocmajortom** [comment]
I only use  DateTime and no special compressions:

CREATE TABLE test.tickets_flat (`isid` Int32, `sid` String, `dim_ticket_sid` String, `duration` Float32, `quantity` Int32, `additions` Int32, `inquiries` Int32, `forwards` Int32, `working_duration` Float32, `q_contact` Int32, `registration_duration` Float32, `parking_duration` Float32, `supplement_duration` Float32, `inquiry_duration` Float32, `invalid_duration` Float32, `other_duration` Float32, `q_brochure` Int32, `q_order` Int32, `q_feedback` Int32, `hasOrders` String, `q_not_ordered` Int32, `order_price` String, `q_forward_call` Int32, `q_directorder` Int32, `quantity_appointments` Int32, `appointments_yes_no` String, `dimCorrectionTypeMulti_code` String, `dimCorrectionTypeMulti_caption` String, `dimChannel_code` String, `dimChannel_caption` String, `dimChannel_disabled` String, `dimOperator_user_id` String, `dimOperator_person_id` String, `dimOperator_caption` String, `dimOperator_function` String, `dimOperator_room` String, `dimOperator_state` String, `dimOperator_ordinal_caption` String, `dimOperator_ordinal_function` String, `dimLocation_location_type` String, `dimLocation_location_id` String, `dimLocation_location_subtype` String, `dimLocation_location_caption` String, `dimLocation_equipment_type` String, `dimLocation_equipment_caption` String, `dimLocation_service_type` String, `dimLocation_doornumber` String, `dimLocation_status` String, `dimLocation_disabled` String, `dimLocation_deleted` String, `dimLocation_building_type` String, `dimLocation_country_code` String, `dimLocation_country_caption` String, `dimLocation_zip_code` String, `dimLocation_zip_caption` String, `dimLocation_city` String, `dimLocation_street` String, `dimLocation_sap_id` String, `dimLocation_streetnumber` String, `dimLocation_stairnumber` String, `dimLocation_building_id` String, `dimLocation_building_caption` String, `dimLocation_rehabilitation_state` String, `dimLocation_is_business_unit` String, `dimLocation_acd_code` String, `dimLocation_building_address_id` String, `dimLocation_building_address_caption` String, `dimLocation_district_no` Int32, `dimTicketPreviousState_code` String, `dimTicketPreviousState_caption` String, `dimTicketPreviousState_disabled` String, `dimCaller_person_id` String, `dimCaller_caption` String, `dimWeekday_date` DateTime, `dimWeekday_year` Int32, `dimWeekday_quarter` Int32, `dimWeekday_quarter_caption` String, `dimWeekday_month` Int32, `dimWeekday_month_caption` String, `dimWeekday_week` Int32, `dimWeekday_weekyyyyww` Int32, `dimWeekday_week_caption` String, `dimWeekday_weekday` String, `dimWeekday_weekday_num` Int32, `dimWeekday_weekday_caption` String, `dimWeekday_day` Int32, `dimWeekday_day_night` String, `dimWeekday_hour` Int32, `dimWeekday_hour_caption` String, `dimWeekday_minute15` Int32, `dimWeekday_minute15_caption` String, `dimWeekday_half_year` Int32, `dimWeekday_jahreszeit` Int32, `dimWeekday_is_holiday` String, `dimWeekday_is_weekday` String, `dimWeekday_is_last_day_in_month` String, `dimWeekday_dayofyear` Int32, `dimWeekday_tagesdatum` String, `dimWeekday_half_year_caption` String, `dimWeekday_is_holiday_caption` String, `dimWeekday_is_last_day_in_month_caption` String, `dimWeekday_is_weekday_caption` String, `dimWeekday_jahreszeit_caption` String, `dimWeekday_half_hour` Int32, `dimWeekday_half_hour_caption` String, `dimHoliday_date` DateTime, `dimHoliday_year` Int32, `dimHoliday_quarter` Int32, `dimHoliday_quarter_caption` String, `dimHoliday_month` Int32, `dimHoliday_month_caption` String, `dimHoliday_week` Int32, `dimHoliday_weekyyyyww` Int32, `dimHoliday_week_caption` String, `dimHoliday_weekday` String, `dimHoliday_weekday_num` Int32, `dimHoliday_weekday_caption` String, `dimHoliday_day` Int32, `dimHoliday_day_night` String, `dimHoliday_hour` Int32, `dimHoliday_hour_caption` String, `dimHoliday_minute15` Int32, `dimHoliday_minute15_caption` String, `dimHoliday_half_year` Int32, `dimHoliday_jahreszeit` Int32, `dimHoliday_is_holiday` String, `dimHoliday_is_weekday` String, `dimHoliday_is_last_day_in_month` String, `dimHoliday_dayofyear` Int32, `dimHoliday_tagesdatum` String, `dimHoliday_half_year_caption` String, `dimHoliday_is_holiday_caption` String, `dimHoliday_is_last_day_in_month_caption` String, `dimHoliday_is_weekday_caption` String, `dimHoliday_jahreszeit_caption` String, `dimHoliday_half_hour` Int32, `dimHoliday_half_hour_caption` String, `dimSeason_date` DateTime, `dimSeason_year` Int32, `dimSeason_quarter` Int32, `dimSeason_quarter_caption` String, `dimSeason_month` Int32, `dimSeason_month_caption` String, `dimSeason_week` Int32, `dimSeason_weekyyyyww` Int32, `dimSeason_week_caption` String, `dimSeason_weekday` String, `dimSeason_weekday_num` Int32, `dimSeason_weekday_caption` String, `dimSeason_day` Int32, `dimSeason_day_night` String, `dimSeason_hour` Int32, `dimSeason_hour_caption` String, `dimSeason_minute15` Int32, `dimSeason_minute15_caption` String, `dimSeason_half_year` Int32, `dimSeason_jahreszeit` Int32, `dimSeason_is_holiday` String, `dimSeason_is_weekday` String, `dimSeason_is_last_day_in_month` String, `dimSeason_dayofyear` Int32, `dimSeason_tagesdatum` String, `dimSeason_half_year_caption` String, `dimSeason_is_holiday_caption` String, `dimSeason_is_last_day_in_month_caption` String, `dimSeason_is_weekday_caption` String, `dimSeason_jahreszeit_caption` String, `dimSeason_half_hour` Int32, `dimSeason_half_hour_caption` String, `dimAppointment_appointment_id` Int32, `dimAppointment_date` Nullable(DateTime), `dimAppointment_time_from` Nullable(DateTime), `dimAppointment_time_to` Nullable(DateTime), `dimAppointment_booked` Nullable(String), `dimAppointment_finished` Nullable(String), `dimAppointment_appointment_subject` String, `dimAppointment_appointment_user_created` String, `dimAppointment_quantity_appointments` Int32, `dimAsset_location_type` String, `dimAsset_location_id` String, `dimAsset_location_subtype` String, `dimAsset_location_caption` String, `dimAsset_equipment_type` String, `dimAsset_equipment_caption` String, `dimAsset_service_type` String, `dimAsset_doornumber` String, `dimAsset_status` String, `dimAsset_disabled` Nullable(String), `dimAsset_deleted` Nullable(String), `dimAsset_building_type` String, `dimAsset_country_code` String, `dimAsset_country_caption` String, `dimAsset_zip_code` String, `dimAsset_zip_caption` String, `dimAsset_city` String, `dimAsset_street` String, `dimAsset_sap_id` String, `dimAsset_streetnumber` String, `dimAsset_stairnumber` String, `dimAsset_building_id` String, `dimAsset_building_caption` String, `dimAsset_rehabilitation_state` String, `dimAsset_is_business_unit` Nullable(String), `dimAsset_acd_code` String, `dimAsset_building_address_id` String, `dimAsset_building_address_caption` String, `dimAsset_district_no` Int32, `dimTicketState_code` String, `dimTicketState_caption` String, `dimTicketState_disabled` String, `dimSubjectMulti_code1` String, `dimSubjectMulti_code2` String, `dimSubjectMulti_code3` String, `dimSubjectMulti_code4` String, `dimSubjectMulti_code5` String, `dimSubjectMulti_code6` String, `dimSubjectMulti_caption1` String, `dimSubjectMulti_caption2` String, `dimSubjectMulti_caption3` String, `dimSubjectMulti_caption4` String, `dimSubjectMulti_caption5` String, `dimSubjectMulti_caption6` String, `dimPersonInvolved_person_id` String, `dimPersonInvolved_caption` String, `dimCancellationTypeMulti_code` String, `dimCancellationTypeMulti_caption` String, `dimTicket_id` String, `dimTicket_ticket_id` String, `dimTicket_info_talk` String, `dimTicket_priority` String, `dimTicket_is_case` String, `dimTicket_is_content_corrected` String, `dimTicket_sla_ok` String, `dimTicket_migration` String, `dimTicket_cancellation_category` Int32, `dimTicket_time_created_str` String, `dimTicket_time_started_str` String, `dimTicket_time_end_str` String, `dimTicket_time_solved_str` String, `dimTicket_involved_person_gender` String, `dimTicket_involved_person_age` String, `dimTicket_caller_person_gender` String, `dimTicket_caller_person_age` String, `dimOrgCategory_code` String, `dimOrgCategory_caption` String, `dimOrgCategory_disabled` String, `dimHour_date` DateTime, `dimHour_year` Int32, `dimHour_quarter` Int32, `dimHour_quarter_caption` String, `dimHour_month` Int32, `dimHour_month_caption` String, `dimHour_week` Int32, `dimHour_weekyyyyww` Int32, `dimHour_week_caption` String, `dimHour_weekday` String, `dimHour_weekday_num` Int32, `dimHour_weekday_caption` String, `dimHour_day` Int32, `dimHour_day_night` String, `dimHour_hour` Int32, `dimHour_hour_caption` String, `dimHour_minute15` Int32, `dimHour_minute15_caption` String, `dimHour_half_year` Int32, `dimHour_jahreszeit` Int32, `dimHour_is_holiday` String, `dimHour_is_weekday` String, `dimHour_is_last_day_in_month` String, `dimHour_dayofyear` Int32, `dimHour_tagesdatum` String, `dimHour_half_year_caption` String, `dimHour_is_holiday_caption` String, `dimHour_is_last_day_in_month_caption` String, `dimHour_is_weekday_caption` String, `dimHour_jahreszeit_caption` String, `dimHour_half_hour` Int32, `dimHour_half_hour_caption` String, `dimTime_date` DateTime, `dimTime_year` Int32, `dimTime_quarter` Int32, `dimTime_quarter_caption` String, `dimTime_month` Int32, `dimTime_month_caption` String, `dimTime_week` Int32, `dimTime_weekyyyyww` Int32, `dimTime_week_caption` String, `dimTime_weekday` String, `dimTime_weekday_num` Int32, `dimTime_weekday_caption` String, `dimTime_day` Int32, `dimTime_day_night` String, `dimTime_hour` Int32, `dimTime_hour_caption` String, `dimTime_minute15` Int32, `dimTime_minute15_caption` String, `dimTime_half_year` Int32, `dimTime_jahreszeit` Int32, `dimTime_is_holiday` String, `dimTime_is_weekday` String, `dimTime_is_last_day_in_month` String, `dimTime_dayofyear` Int32, `dimTime_tagesdatum` String, `dimTime_half_year_caption` String, `dimTime_is_holiday_caption` String, `dimTime_is_last_day_in_month_caption` String, `dimTime_is_weekday_caption` String, `dimTime_jahreszeit_caption` String, `dimTime_half_hour` Int32, `dimTime_half_hour_caption` String, `dimTaskWorkBasket_code` String, `dimTaskWorkBasket_caption` String, `dimTaskWorkBasket_disabled` Nullable(String), `dimTicketArt_code` String, `dimTicketArt_caption` String, `dimTicketArt_disabled` String, `dimLastDayOfMonth_date` DateTime, `dimLastDayOfMonth_year` Int32, `dimLastDayOfMonth_quarter` Int32, `dimLastDayOfMonth_quarter_caption` String, `dimLastDayOfMonth_month` Int32, `dimLastDayOfMonth_month_caption` String, `dimLastDayOfMonth_week` Int32, `dimLastDayOfMonth_weekyyyyww` Int32, `dimLastDayOfMonth_week_caption` String, `dimLastDayOfMonth_weekday` String, `dimLastDayOfMonth_weekday_num` Int32, `dimLastDayOfMonth_weekday_caption` String, `dimLastDayOfMonth_day` Int32, `dimLastDayOfMonth_day_night` String, `dimLastDayOfMonth_hour` Int32, `dimLastDayOfMonth_hour_caption` String, `dimLastDayOfMonth_minute15` Int32, `dimLastDayOfMonth_minute15_caption` String, `dimLastDayOfMonth_half_year` Int32, `dimLastDayOfMonth_jahreszeit` Int32, `dimLastDayOfMonth_is_holiday` String, `dimLastDayOfMonth_is_weekday` String, `dimLastDayOfMonth_is_last_day_in_month` String, `dimLastDayOfMonth_dayofyear` Int32, `dimLastDayOfMonth_tagesdatum` String, `dimLastDayOfMonth_half_year_caption` String, `dimLastDayOfMonth_is_holiday_caption` String, `dimLastDayOfMonth_is_last_day_in_month_caption` String, `dimLastDayOfMonth_is_weekday_caption` String, `dimLastDayOfMonth_jahreszeit_caption` String, `dimLastDayOfMonth_half_hour` Int32, `dimLastDayOfMonth_half_hour_caption` String) ENGINE = MergeTree PARTITION BY isid % 10 ORDER BY isid SAMPLE BY isid SETTINGS index_granularity = 8192

**Comment by filimonov** [comment]
What the filesystem is? Do other / simpler inerts behave normally?

**Comment by ocmajortom** [comment]
Good question! 
I was running clickhouse in vmware and the database in vmhgfs (host guest file system) because lack of local space.

After copying it back to ext4 the problem disappeared!

Thanks for the hint!

**Comment by alanlans** [comment]
I have same problem

**Comment by filimonov** [comment]
> I have same problem
What type of filesystem do you use?

**Comment by alanlans** [comment]
> > I have same problem
> 
> What type of filesystem do you use?

NTFS

2020-03-31 11:39:58] Connected
default> CREATE TABLE mytable(
         	some_date Date,
         	some_int	UInt64,
         	some_str String,
         	some_float Float32
         ) ENGINE = MergeTree(some_date, (some_int, some_date), 8192)
[2020-03-31 11:39:59] completed in 50 ms
default> INSERT INTO mytable VALUES('2010-03-10', 28194901262, '8006-6129-3130-5580', 1169)
[2020-03-31 11:40:10] Poco::Exception. Code: 1000, e.code() = 2, e.displayText() = File not found: /var/lib/clickhouse/data/default/mytable/tmp_insert_20100310_20100310_1_1_0 (version 20.3.4.10 (official build))
default> INSERT INTO mytable VALUES('2010-03-10', 28194901262, '8006-6129-3130-5580', 1169)
[2020-03-31 11:49:03] Poco::Exception. Code: 1000, e.code() = 2, e.displayText() = File not found: /var/lib/clickhouse/data/default/mytable/tmp_insert_20100310_20100310_2_2_0 (version 20.3.4.10 (official build))
default> INSERT INTO mytable VALUES('2010-03-10', 28194901262, '8006-6129-3130-5580', 1169)
[2020-03-31 11:55:31] completed in 72 ms
default> INSERT INTO mytable VALUES('2010-03-10', 28194901262, '8006-6129-3130-5580', 1169)
[2020-03-31 11:55:35] completed in 65 ms
default> INSERT INTO mytable VALUES('2010-03-10', 28194901262, '8006-6129-3130-5580', 1169)
[2020-03-31 11:55:37] completed in 61 ms
default> INSERT INTO mytable VALUES('2010-03-10', 28194901262, '8006-6129-3130-5580', 1169)
[2020-03-31 11:55:51] Poco::Exception. Code: 1000, e.code() = 2, e.displayText() = File not found: /var/lib/clickhouse/data/default/mytable/tmp_insert_20100310_20100310_6_6_0 (version 20.3.4.10 (official build))
default> INSERT INTO mytable VALUES('2010-03-10', 28194901262, '8006-6129-3130-5580', 1169)
[2020-03-31 11:55:53] completed in 65 ms

**Comment by den-crane** [comment]
https://t.me/clickhouse_ru/150955

_Ntfs, докер, винда. Уже разобрался. Вольюм с данными БД коряво прокинул.  Самое интересное в том что порой проходило, порой нет)

clickhouse-server:
      image: yandex/clickhouse-server
      restart: always
      ulimits:
        nofile:
          soft: 262144
          hard: 262144
      volumes:
        - ${DATA_PATH_HOST}/clickhouse:/var/lib/clickhouse


вот ${DATA_PATH_HOST}  вел в users/user/.docker

при отключении, заработало нормально_

**Comment by alanlans** [comment]
> https://t.me/clickhouse_ru/150955
> 
> _Ntfs, докер, винда. Уже разобрался. Вольюм с данными БД коряво прокинул. Самое интересное в том что порой проходило, порой нет)
> 
> clickhouse-server:
> image: yandex/clickhouse-server
> restart: always
> ulimits:
> nofile:
> soft: 262144
> hard: 262144
> volumes:
> - ${DATA_PATH_HOST}/clickhouse:/var/lib/clickhouse
> 
> вот ${DATA_PATH_HOST} вел в users/user/.docker
> 
> при отключении, заработало нормально_

Это я же и написал)

**Comment by alexrozz** [comment]
@filimonov подскажи плиз, а с ntfs есть проблемы? Запускаю на винде в докере, и при любом инсерте такая ошибка, при том что директория с файлами такая существует, а не файл:
`HttpCode:500 ;  ;Poco::Exception. Code: 1000, e.code() = 2, e.displayText() = File not found: /var/lib/clickhouse/data/mydb/operation/tmp_insert_202102_4_4_0 (version 20.8.8.2 (official build))`

На убунте (на ext4, кажется) было всё ок.

**Comment by filimonov** [comment]
Скорее всего дело в отсутствии каких-то фичеров файловой системы в windows. Или hard link или atomic rename.

Докер добавляет всяких своих слоев поверх и все становится сложнее. Попробуйте не пробрасывать volume снаружи. 

Кстати в каких-то соседних тикетах писали что КХ запускается под последним WSL (я не пробовал).

**Comment by alexey-milovidov** [comment]
@filimonov Could you please add to the docs that ClickHouse is not supposed to work in Docker on Windows?
