### ISSUE TITLE
Issue with import tsv files containing zero-padded numbers

### ISSUE THREAD

**Issue by MahmoudGoda0** [yandex/ClickHouse#5999]
I'm using clickhouse for the first time, and when I'm doing import like this
cat /home/data/XDR_IMPORT_1001_20001010_000001.tsv | clickhouse-client --password=123 --query="INSERT INTO ts FORMAT TSV";

It gives me error : Column 13, name: dpc, type: Nullable(Int32), parsed text: "0" ERROR: garbage after Nullable(Int32): "3242"

And this is because i have a column (dpc) in type Int32 and the value of this column is 03242, so it seems the import process takes only 0 and trying to find the tap after it

Any help please ?

**Comment by filimonov** [comment]
Confirmed:
```
clickhouse-client --query='create table x( c1 Nullable(Int32), c2 Nullable(Int32)) Engine=TinyLog'

printf "0123\t01234\n" | clickhouse-client --query='insert into x format TSV' --stacktrace
Code: 27. DB::Exception: Cannot parse input: expected \t before: 123\t01234\n: (at row 1)

Row 1:
Column 0,   name: c1, type: Nullable(Int32), parsed text: "0"
ERROR: garbage after Nullable(Int32): "123<TAB>01234<LINE FEED>"



Stack trace:
0. clickhouse-client(StackTrace::StackTrace()+0x22) [0x7808852]
1. clickhouse-client(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x22) [0x39fe402]
2. clickhouse-client(DB::throwAtAssertionFailed(char const*, DB::ReadBuffer&)+0x138) [0x71cb7e8]
3. clickhouse-client(DB::TabSeparatedRowInputStream::read(std::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::RowReadExtension&)+0x1cb) [0x6b659cb]
4. clickhouse-client(DB::BlockInputStreamFromRowInputStream::readImpl()+0x168) [0x6e2ec48]
5. clickhouse-client(DB::IBlockInputStream::read()+0x188) [0x6613f28]
6. clickhouse-client(DB::AsynchronousBlockInputStream::calculate()+0x58) [0x660cd68]
7. clickhouse-client() [0x660d140]
8. clickhouse-client(ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::_List_iterator<ThreadFromGlobalPool>)+0x1af) [0x71aaecf]
9. clickhouse-client(ThreadFromGlobalPool::ThreadFromGlobalPool<ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::function<void ()>, int, std::optional<unsigned long>)::{lambda()#3}>(ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::function<void ()>, int, std::optional<unsigned long>)::{lambda()#3}&&)::{lambda()#1}::operator()() const+0x3c) [0x71ac31c]
10. clickhouse-client(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1af) [0x71aa0af]
11. clickhouse-client() [0xb299d6f]
12. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7fe6e93c06db]
13. /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7fe6e8b4788f]
```

**Comment by MahmoudGoda0** [comment]
So we dont have any solution right now for this issue ?

**Comment by filimonov** [comment]
Only workarounds. Like use another format (CSV for example), reformat numbers with some simple regexp, read to temporary table as String, or use clickhouse-local as preprocessor: https://www.altinity.com/blog/2019/6/11/clickhouse-local-the-power-of-clickhouse-sql-in-a-single-command

**Comment by filimonov** [comment]
The fix is easy - check here:
https://github.com/yandex/ClickHouse/blob/3c7178a8d1c642b92782e2ae27483e88e14307f0/dbms/src/IO/ReadHelpers.h#L349-L354

But it also require test case.

**Comment by MahmoudGoda0** [comment]
Could you please elaborate more what should i do to apply this fix in my case ?
Another question, i have around 7800 files, and i need parallel import, how i can do it ? and how i can tell clickhouse to use more cpus ?

**Comment by alexey-milovidov** [comment]
@filimonov It is documented behaviour and should not be fixed.

**Comment by filimonov** [comment]
documented? didn't see that. 

Indeed it can hit the performance in cases where TSV has a lot of zeros - probably testing performance degradation only for that single border case should be ok.

**Comment by alexey-milovidov** [comment]
I also cannot find it in documentation (I thought it was there).

Note that parsing numbers starting with zero can be quite dangerous. Example in JavaScript:
```
var obj = {"x":0123};
alert(obj.x);

var json = '{"x":0123}';
alert(JSON.parse(json).x);
```

In the first example, it will output 83, because JavaScript (as well as C, Perl, PHP...) parses 0123 as octal number.

In the second example, it refused to parse string as JSON (in my Firefox browser) because the spec http://json.org/ doesn't allow numbers with extra leading zeros.

**Comment by alexey-milovidov** [comment]
High ratio of zeros in datasets is very common case.
In "NYC taxi" dataset, 60% of all integers are zero.
In "Yandex.Metrica" dataset, 76% of all integers are zero.

**Comment by alexey-milovidov** [comment]
@MahmoudGoda0 
Workaround:
- create a temporary table with String data type instead of integer;
- load your data as usual;
- insert into destination table with INSERT SELECT query and `toInt32` function.

**Comment by MahmoudGoda0** [comment]
Thanks for this workaround, but i have a table with more than 3 billion rows, and by this workaround it will take lot of time, specially we receive a file (~ 700 K rows) every 11 second.

**Comment by filimonov** [comment]
> Thanks for this workaround, but i have a table with more than 3 billion rows, and by this workaround it will take lot of time, specially we receive a file (~ 700 K rows) every 11 second.

I've gave you a [link](https://www.altinity.com/blog/2019/6/11/clickhouse-local-the-power-of-clickhouse-sql-in-a-single-command) above... :\

clickhouse-local can do that in quite a simple and very efficient way:
```bash
cat data.csv | clickhouse-local --table='input' \
--structure="col1 String, col2 String, col3 String" \
--input-format='TSV' \
--query="SELECT toUInt64OrZero(col1) a, toFloat64OrZero(col2) b, col3 c FROM input'" --format=Native\
| clickhouse-client --query='INSERT INTO target_table FORMAT Native'
```

Please pay attention that when passing Native format columns names / types / order should exactly match in selected stream and inserted stream.

**Comment by MahmoudGoda0** [comment]
Just to make sure I understand these lines correctly, it will copy the data from from a file "data.csv" (in my case it will be the TSV file, then insert it into "target_table" with the correct type, to remove the zero ?
If this is true, this will work if i pass the folder path to insert all files ?
like this cat *.tsv |......

**Comment by alexey-milovidov** [comment]
Yes, it will work as expected.
`clickhouse-local` works in streaming fashion.

**Comment by MahmoudGoda0** [comment]
Thanks guys for your support.
I have 2 question please :)
1- Do we have parallel import ? So I can speed up the import time ?
2 - After imported all files, i run query that take some time (23 seconds) and i realized the clcikhouse use only 10 CPUs during the query run time, how i tell clickhouse to use more CPUs( i have 32 CPUs)

**Comment by filimonov** [comment]
1. You need to run several inserts in parallel, i.e. run that pipe on each file separately in parallel.
2. Check `max_threads` setting. Also for small enough queries ClickHouse can decrease the number of threads automatically. Also if you can have concurrent queries - using all cores by single query can be suboptimal.

**Comment by MahmoudGoda0** [comment]
Thank you very much for your kind support.
