### ISSUE TITLE
Os x docker client connection fail (-ti)

### ISSUE THREAD

**Issue by 127** [yandex/ClickHouse#60]
На os x 10.11.5 по примеру (https://hub.docker.com/r/yandex/clickhouse-server/) при попытке приаттачиться нативным клиентом: 
1. Не возвращается tty (-it)
2. Клиент падает 
ClickHouse client version 1.1.53998.
Connecting to localhost:9000.
Code: 210. DB::NetException: Connection refused: (localhost:9000, ::1)

docker -v 
Docker version 1.12.0-rc4, build e4a0dbc, experimental

сервер:
docker run -d -p 8123 --name ccs yandex/clickhouse-server

Клиент
 docker run -it --rm --link ccs:clickhouse-server yandex/clickhouse-client

**Comment by bamx23** [comment]
При запуске клиента надо указать хост:
```
docker run -it --rm --link ccs:clickhouse-server yandex/clickhouse-client --host clickhouse-server
```
В каком случае не возвращался tty?

**Comment by 127** [comment]
Если указать хост — то же самое.
Разве не должна вернуться консоль server-client при указании  -ti?

**Comment by bamx23** [comment]
Вызов на той же версии докера команд:
```
docker run -d -p 8123 --name ccs yandex/clickhouse-server
docker run -it --rm --link ccs:clickhouse-server yandex/clickhouse-client --host clickhouse-server
```
– приводит в консоль клиента. 
В последней версии клиента была исправлена проблема с аргументами хоста. Попробуйте обновить образы:
```
docker pull yandex/clickhouse-server
docker pull yandex/clickhouse-client
```

**Comment by 127** [comment]
Спасибо, теперь работает!
