### ISSUE TITLE
Table info  isn't show on system.parts 

### ISSUE THREAD

**Issue by ngoanpham** [yandex/ClickHouse#6013]
I created table (for example XX), queried successfully. 
How ever I can't see any info of table XX when I query info from system.parts. 
When I run `Select table from system.parts` that didn't display XX. It displayed 4 names: cpu, cpu, cpu, tags.

Could I find the information of a table I created in database (such name, size,..)?

**Comment by den-crane** [comment]
system.parts have information about parts of MergeTree tables.
If XX is empty it has no parts, and the size of the X is 0.

For engines *Log you can use OS utilities only [du -sh /var/lib/clickhouse/data/db/XX]
For engine Memory no way at all.

**Comment by ngoanpham** [comment]
Very clear, thank you. @den-crane
