### ISSUE TITLE
ALTER TABLE DROP DETACHED PART

### ISSUE THREAD

**Issue by blinkov** [yandex/ClickHouse#6041]

**Comment by alexey-milovidov** [comment]
And a setting to enable this query, disabled by default.

Use case: in cloud providers the user has no access to filesystem and has no way to deal with detached parts.

**Comment by alexey-milovidov** [comment]
It will allow to remove arbitrary directory inside `detached` by its name. But be careful - name must not contain path components (example: `../../../../../data`).
