### ISSUE TITLE
kafka engine with sasl_plaintext+ PLAIN+sasl_username+sasl_password ，DB::Exception: Local: Invalid argument or configuration. 

### ISSUE THREAD

**Issue by florida-hehe** [yandex/ClickHouse#6042]
**Describe the bug**
when clickhouse  execute select * from kafka engine table they return this message:
← Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.) Received exception from server (version 19.7.54419):
Code: 1001. DB::Exception: Received from localhost:9000. DB::Exception: Local: Invalid argument or configuration. 

when i use no sasl  authentification kafka cluster test they work fine.but i use sasl  authentification kafka cluster is not work.

my clickhouse kafka config file:
`<kafka>`
`<debug>all</debug>`
`<auto_offset_reset>latest</auto_offset_reset>`
`<security_protocol>sasl_plaintext</security_protocol>`
`<sasl_mechanism>PLAIN</sasl_mechanism>`
`<compression_type>snappy</compression_type>`
`<sasl_username>test</sasl_username>`
`<sasl_password>test</sasl_password>`
`</kafka>`

clickhouse error log:
2019.07.18 01:03:19.069061 [ 179 ] {} <Trace> StorageKafka (queue_json_12): Polled batch of 0 messages
2019.07.18 01:03:19.069220 [ 165 ] {} <Trace> StorageKafka (queue_json_12): Polled batch of 0 messages
2019.07.18 01:03:23.568808 [ 175 ] {} <Trace> StorageKafka (queue_json_12): Committing message with offset 0
2019.07.18 01:03:23.568807 [ 163 ] {} <Trace> StorageKafka (queue_json_12): Committing message with offset 0
2019.07.18 01:03:23.569443 [ 181 ] {ea10b707-9749-4b3b-b61f-7c9ca8d1ffff} <Error> executeQuery: std::exception. Code: 1001, type: cppkafka::HandleException, e.what() = Local: Invalid argument or configuration, version = 19.7.5.27 (from xx) (in query: select * from queue_json_12 ;)
2019.07.18 01:03:23.569592 [ 181 ] {ea10b707-9749-4b3b-b61f-7c9ca8d1ffff} <Debug> MemoryTracker: Peak memory usage (for query): 1.03 MiB.
2019.07.18 01:03:23.569637 [ 181 ] {ea10b707-9749-4b3b-b61f-7c9ca8d1ffff} <Trace> UnionBlockInputStream: Waiting for threads to finish
2019.07.18 01:03:23.569677 [ 181 ] {ea10b707-9749-4b3b-b61f-7c9ca8d1ffff} <Trace> UnionBlockInputStream: Waited for threads to finish
2019.07.18 01:03:23.569747 [ 181 ] {ea10b707-9749-4b3b-b61f-7c9ca8d1ffff} <Error> virtual DB::UnionBlockInputStream::~UnionBlockInputStream(): std::exception. Code: 1001, type: cppkafka::HandleException, e.what() = Local: Invalid argument or configuration, version = 19.7.5.27
2019.07.18 01:03:23.569805 [ 181 ] {ea10b707-9749-4b3b-b61f-7c9ca8d1ffff} <Trace> StorageKafka (queue_json_12): Re-joining claimed consumer after failure
2019.07.18 01:03:23.569887 [ 181 ] {ea10b707-9749-4b3b-b61f-7c9ca8d1ffff} <Trace> StorageKafka (queue_json_12): Re-joining claimed consumer after failure
2019.07.18 01:03:23.569949 [ 181 ] {ea10b707-9749-4b3b-b61f-7c9ca8d1ffff} <Trace> StorageKafka (queue_json_12): Re-joining claimed consumer after failure
2019.07.18 01:03:23.570148 [ 181 ] {ea10b707-9749-4b3b-b61f-7c9ca8d1ffff} <Information> TCPHandler: Processed in 5.003 sec.
2019.07.18 01:03:26.075604 [ 130 ] {} <Trace> SystemLog (system.query_log): Flushing system log
2019.07.18 01:03:26.079641 [ 130 ] {} <Trace> system.query_log (Data): Renaming temporary part tmp_insert_20190715_1815_1815_0 to 20190715_1853_1853_0.
2019.07.18 00:40:18.337784 [ 167 ] {} <Error> StorageKafka (queue_json_12): Consumer error: Local: Broker transport failure

2019.07.18 11:29:40.857659 [ 144 ] {} <Trace> StorageKafka (queue_json_1): Execution took 5001 ms.
2019.07.18 11:29:41.357759 [ 147 ] {} <Debug> StorageKafka (queue_json_1): Started streaming to 1 attached views
2019.07.18 11:29:46.358274 [ 174 ] {} <Trace> StorageKafka (queue_json_1): Committing message with offset 0
2019.07.18 11:29:46.358274 [ 179 ] {} <Trace> StorageKafka (queue_json_1): Committing message with offset 0
2019.07.18 11:29:46.358280 [ 175 ] {} <Trace> StorageKafka (queue_json_1): Committing message with offset 0
2019.07.18 11:29:46.358291 [ 161 ] {} <Trace> StorageKafka (queue_json_1): Committing message with offset 0
2019.07.18 11:29:46.358297 [ 173 ] {} <Trace> StorageKafka (queue_json_1): Committing message with offset 0
2019.07.18 11:29:46.358638 [ 147 ] {} <Trace> UnionBlockInputStream: Waiting for threads to finish
2019.07.18 11:29:46.358690 [ 147 ] {} <Trace> UnionBlockInputStream: Waited for threads to finish
2019.07.18 11:29:46.358768 [ 147 ] {} <Error> virtual DB::UnionBlockInputStream::~UnionBlockInputStream(): std::exception. Code: 1001, type: cppkafka::HandleException, e.what() = Local: Invalid argument or configuration, version = 19.7.5.27
2019.07.18 11:29:46.358800 [ 147 ] {} <Trace> StorageKafka (queue_json_1): Re-joining claimed consumer after failure
2019.07.18 11:29:46.358861 [ 147 ] {} <Trace> StorageKafka (queue_json_1): Re-joining claimed consumer after failure
2019.07.18 11:29:46.358907 [ 147 ] {} <Trace> StorageKafka (queue_json_1): Re-joining claimed consumer after failure
2019.07.18 11:29:46.358941 [ 147 ] {} <Trace> StorageKafka (queue_json_1): Re-joining claimed consumer after failure
2019.07.18 11:29:46.358974 [ 147 ] {} <Trace> StorageKafka (queue_json_1): Re-joining claimed consumer after failure
2019.07.18 11:29:46.359031 [ 147 ] {} <Error> void DB::StorageKafka::streamThread(): std::exception. Code: 1001, type: cppkafka::HandleException, e.what() = Local: Invalid argument or configuration, version = 19.7.5.27

**Comment by florida-hehe** [comment]
@filimonov haved you tested 
<kafka>
<debug>all</debug>
<auto_offset_reset>latest</auto_offset_reset>
<security_protocol>sasl_plaintext</security_protocol>
<sasl_mechanism>PLAIN</sasl_mechanism>
<compression_type>snappy</compression_type>
<sasl_username>test</sasl_username>
<sasl_password>test</sasl_password>
</kafka>

**Comment by abyss7** [comment]
@florida-hehe can you provide your Kafka server configuration regarding the auth settings?

**Comment by filimonov** [comment]
@florida-hehe SASL support was added recently, and it looks it first introduced in 19.8 version

https://github.com/yandex/ClickHouse/pull/5253/commits/67cf1bc48c5a4ac147a6abd2159d0e4f8ed6d814

It looks like you're using 19.7.54419. Please try 19.11, it also contains some more Kafka related fixes.

About tests: currently we don't have too many Kafka-related tests, and Kafka is not used in Yandex internally. So we will be very appreciated if you will be able to provide test configurations / setup to check those cases (ideally as docker compose), and we will be able to add it to ClickHouse CI system.

**Comment by abyss7** [comment]
My bad, haven't looked at the version. There are no plans to backport Kafka+SASL support to 19.7

**Comment by florida-hehe** [comment]
> @florida-hehe can you provide your Kafka server configuration regarding the auth settings?

<kafka>
    <debug>all</debug>
    <auto_offset_reset>latest</auto_offset_reset>
    <security_protocol>sasl_plaintext</security_protocol>
    <sasl_mechanism>PLAIN</sasl_mechanism>
    <compression_type>snappy</compression_type>
    <sasl_username>test</sasl_username>
    <sasl_password>11</sasl_password>
</kafka>

**Comment by florida-hehe** [comment]
> @florida-hehe can you provide your Kafka server configuration regarding the auth settings?

`<kafka>`
    `<debug>all</debug>`
    `<auto_offset_reset>latest</auto_offset_reset>`
    `<security_protocol>sasl_plaintext</security_protocol>`
    `<sasl_mechanism>PLAIN</sasl_mechanism>`
    `<compression_type>snappy</compression_type>`
    `<sasl_username>test</sasl_username>`
    `<sasl_password>11</sasl_password>`
`</kafka>`

**Comment by florida-hehe** [comment]
> @florida-hehe SASL support was added recently, and it looks it first introduced in 19.8 version
> 
> [67cf1bc](https://github.com/yandex/ClickHouse/commit/67cf1bc48c5a4ac147a6abd2159d0e4f8ed6d814)
> 
> It looks like you're using 19.7.54419. Please try 19.11, it also contains some more Kafka related fixes.
> 
> About tests: currently we don't have too many Kafka-related tests, and Kafka is not used in Yandex internally. So we will be very appreciated if you will be able to provide test configurations / setup to check those cases (ideally as docker compose), and we will be able to add it to ClickHouse CI system.

version = 19.7.5.27
