### ISSUE TITLE
Minus zero values

### ISSUE THREAD

**Issue by minouminou** [yandex/ClickHouse#605]
In most of databases there is no minus zero for float values (implicitly assumed plus when stored in tables).
See join and group by with minus zero. If you plan to add support for joins like in other databases it can add ambiguous behavior.

Tested in v1.1.54164:
```
create table t1 (a UInt8,b Float32) ENGINE=Memory;
create table t2 (a UInt8,b Float32) ENGINE=Memory;
insert into t1 values (1,0),(2,-0.0);
insert into t2 VALUES (3,0.0);

select * from t1
┌─a─┬──b─┐
│ 1 │  0 │
│ 2 │ -0 │
└───┴────┘

select b from t1 group by b
┌──b─┐
│  0 │
│ -0 │
└────┘

select * from t1 all inner join t2 using b
┌─a─┬─b─┐
│ 3 │ 0 │
└───┴───┘

select 1 where -0.0 = 0.0
┌─1─┐
│ 1 │
└───┘

select uniq(b) from t1
┌─uniq(b)─┐
│       2 │
└─────────┘

select min(b) from t1
┌─min(b)─┐
│      0 │
└────────┘

select max(b) from t1
┌─max(b)─┐
│      0 │
└────────┘

select equals(0.0, -0.0)
┌─equals(0., -0.)─┐
│               1 │
└─────────────────┘
```

**Comment by ludv1x** [comment]
We don't plan to interpret +0.0 and -0.0 as equal numbers due to simplicity and efficiency reasons.

BTW, see a quote from the [doc](https://clickhouse.yandex/reference_en.html#Float32, Float64):
> Float32 and Float64 are not SQL compatible types, instead they are mapped directly to C++ float and double.
