### ISSUE TITLE
19.11-*-stable dictionaries loading failed

### ISSUE THREAD

**Issue by mikeeremin** [yandex/ClickHouse#6050]
After upgrading to 19.11 dictionaries loading fail with error:

```
2019.07.18 13:46:47.501892 [ 57 ] {} <Warning> ExternalDictionaries: /etc/clickhouse-server/dnl_dictionary.xml: file contains unknown node 'interserver_http_host', expected 'dictionary'
2019.07.18 13:46:47.502034 [ 57 ] {} <Warning> ExternalDictionaries: /etc/clickhouse-server/dnl_dictionary.xml: file contains unknown node 'listen_host', expected 'dictionary'
2019.07.18 13:46:47.502177 [ 57 ] {} <Warning> ExternalDictionaries: /etc/clickhouse-server/dnl_dictionary.xml: file contains unknown node 'listen_host[1]', expected 'dictionary'
2019.07.18 13:46:47.502256 [ 57 ] {} <Warning> ExternalDictionaries: /etc/clickhouse-server/dnl_dictionary.xml: file contains unknown node 'listen_host[2]', expected 'dictionary'
2019.07.18 13:46:47.502324 [ 57 ] {} <Warning> ExternalDictionaries: /etc/clickhouse-server/dnl_dictionary.xml: file contains unknown node 'logger', expected 'dictionary'
2019.07.18 13:46:47.502388 [ 57 ] {} <Warning> ExternalDictionaries: /etc/clickhouse-server/dnl_dictionary.xml: file contains unknown node 'profiles', expected 'dictionary'
2019.07.18 13:46:47.502472 [ 57 ] {} <Warning> ExternalDictionaries: /etc/clickhouse-server/dnl_dictionary.xml: file contains unknown node 'max_concurrent_queries', expected 'dictionary'
2019.07.18 13:46:47.502539 [ 57 ] {} <Warning> ExternalDictionaries: /etc/clickhouse-server/dnl_dictionary.xml: file contains unknown node 'zookeeper-servers', expected 'dictionary'

```

 cat /etc/clickhouse-server/dnl_dictionary.xml

```
<?xml version="1.0"?>
<yandex>
  <dictionary>
    <name>hosts</name>
    <source>
      <odbc>
        <connection_string>DSN=PostgreSQLCHglobal</connection_string>
        <table>hosts</table>
      </odbc>
......
......
......
</yandex>

```
Works on 19.9.4.34 and older.

**Comment by alexey-milovidov** [comment]
Dictionaries will load successfully regardless to this warning.

This warning present, because some config elements get substituted into `/etc/clickhouse-server/dnl_dictionary.xml`. You can check it in `/etc/clickhouse-server/preprocessed/...` directory.

Extraneous config elements are substituted from `conf.d` directory.
You can override configuration with files from `conf.d` or _config_name_.d directory, for example `config.d`, `users.d` or `dnl_dictionary.d`. Overrides from `conf.d` directory will be substituted into every configuration file while overrides from _config_name_.d directories will be substituted only to the corresponding configuration file.

**Comment by mikeeremin** [comment]
```
clickhouse-test-node1 :) system reload dictionaries;

SYSTEM RELOAD DICTIONARIES

Ok.

0 rows in set. Elapsed: 0.005 sec.

clickhouse-test-node1 :) select * from system.dictionaries\G

SELECT *
FROM system.dictionaries

Row 1:
──────
name:               programreleasefiles
status:             NOT_LOADED
origin:             /etc/clickhouse-server/dnl_dictionary.xml
type:
key:
attribute.names:    []
attribute.types:    []
bytes_allocated:    0
query_count:        0
hit_rate:           0
element_count:      0
load_factor:        0
source:
loading_start_time: 0000-00-00 00:00:00
loading_duration:   0
last_exception:


```

**Comment by vitlibar** [comment]
SYSTEM RELOAD DICTIONARIES reloads only those dictionaries which have been loaded before.
Clickhouse has not loaded `programreleasefiles` before so `SYSTEM RELOAD DICTIONARIES` doesn't reload it.

If you want `programreleasefiles` to be loaded use

```
SYSTEM RELOAD DICTIONARY programreleasefiles
```

or just start using this dictionary
```
SELECT dictGetUInt64('programreleasefiles', 'a', 1)
```

**Comment by mikeeremin** [comment]
Worked, thanks.

**Comment by fessmage** [comment]
I got NOT_LOADED state for every dictionary after update of clickhouse-server from 18.* to 19.* and only thing that worked for me - advice from @vitlibar. `system reload dictionary <dictionary_name>` for every dictionary - fixes problem.

**Comment by filimonov** [comment]
> I got NOT_LOADED state for every dictionary after update of clickhouse-server from 18.* to 19.* and only thing that worked for me - advice from @vitlibar. `system reload dictionary <dictionary_name>` for every dictionary - fixes problem.

Try disabling lazy loading of dictionaries if you need them preinitialized.

**Comment by fessmage** [comment]
Oh, thanks, i understood reason now. On server start i have problem with `clickhouse-odbc-bridge` - forgot to update it with rest packages. And with setting `dictionaries_lazy_load` defaults true - because of that error with odbc dictionaries, it resulted in all dictionaries not loaded.

**Comment by Naveen071110** [comment]
when i type system reload dictionary dictionary_name
Then it shows that connection to all replicas failed!
Can you explain why?
