### ISSUE TITLE
Clickhouse count is not working

### ISSUE THREAD

**Issue by masosky** [yandex/ClickHouse#6064]
Hi,

I have some issues when trying to count the number of rows of a table using a simple query like:
`SELECT count()
FROM mop3 
WHERE (key = category) AND (value = lips)`

The table is
`CREATE TABLE mop3
(
    customer_id Int32,
    order_id Int64,
    order_date_created DateTime,
    key String,
    value String,
    quantity Int32,
    unit_amount Decimal32(4),
    total_amount Decimal32(4)
) ENGINE = MergeTree()
PARTITION BY toYYYYMM(order_date_created)
ORDER BY (key, value)
`

Thank you very much

**Comment by moverlock1024** [comment]
What's the issue, and what version do you use?

**Comment by amosbird** [comment]
What's the issue, and what version do you use?

**Comment by masosky** [comment]
I am using last version released
`Code: 47. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Missing columns: 'labios' 'category' while processing query: 'SELECT count() FROM mop3  WHERE (key = category) AND (value = labios) AND (order_date_created = toDate(now()))', required columns: 'labios' 'order_date_created' 'key' 'category' 'value', source columns: 'quantity' 'unit_amount' 'value' 'customer_id' 'order_id' 'total_amount' 'order_date_created' 'key'. `

**Comment by vasyaabr** [comment]
Use
`SELECT count() FROM mop3 WHERE (key = 'category') AND (value = 'lips')`

**Comment by masosky** [comment]
Oops, I forgot the single quotes.
But I do not understand I tried that previously and I didn't work.
But now it is working!

Sorry for the inconvenience and thanks for the fast answer.
