### ISSUE TITLE
ODBC PGSQL dictionary partial update

### ISSUE THREAD

**Issue by tishkinis** [yandex/ClickHouse#6069]
For initial load PGSQL dictionary via ODBC w <update_field> uses time '0000-00-00 00:00:00' 
https://github.com/temoon/ClickHouse/blob/7de5d58f415c95cfc1dd76fa8b10d0d3f9135bf9/dbms/src/Dictionaries/ExecutableDictionarySource.cpp#L92

PGSQL causes error
date/time field value out of range: "0000-00-00 00:00:00"
As result dictionary data not loaded at all.

Correct PGSQL time value is '0001-01-01 00:00:00'

**Comment by den-crane** [comment]
BTW, wrong file. It should be fixed in XDBCDictionarySource.cpp

https://github.com/temoon/ClickHouse/blob/master/dbms/src/Dictionaries/XDBCDictionarySource.cpp#L131

And obviously it is should be generalized.

**Comment by alexey-milovidov** [comment]
Let's change it to `1971-01-01 00:00:00`.
