### ISSUE TITLE
What is the most stable version?

### ISSUE THREAD

**Issue by achimbab** [yandex/ClickHouse#6099]
I am using ClickHouse ```18.14.19``` for Enterprise Business and considering to update to a newer version of ClickHouse.

What version of ClickHouse is the most stable?

I ask your advice.
Thank you in advance.

**Comment by alexey-milovidov** [comment]
19.11 is the most stable version in all terms except Kafka integration.

You should evaluate any new version in testing environment before installing in production.

**Comment by achimbab** [comment]
@alexey-milovidov 
Thank you for your advice! :)
