### ISSUE TITLE
Beginner to ClickHouse

### ISSUE THREAD

**Issue by Sundarcj** [yandex/ClickHouse#6102]
Hi Team, am new to Clickhouse I have doubts in the following area. anyone could please shed some lights on it.

I have a use case of trillions of record processing.. with aggregation function and joins.. what could be the perfect table engine. how partition works in the mergetree family. is there any callbacks available in JDBC for update and delete.

Thanks

**Comment by filimonov** [comment]
Please start with official tutorial: https://clickhouse.yandex/tutorial.html

Also please read that: https://github.com/yandex/ClickHouse/issues/2161

Also you can watch one of many presentation:   
https://www.youtube.com/channel/UChtmrD-dsdpspr42P_PyRAw
https://github.com/yandex/clickhouse-presentations 

For paid training & support - you can also contact http://altinity.com
