### ISSUE TITLE
Clickhouse crushes under load with segfault

### ISSUE THREAD

**Issue by Imomoi** [yandex/ClickHouse#6105]
Hi there.

We have issue on 19.9.3.31 (official build) under Ubuntu on AWS EC2.

I cannot reproduce it on our test servers, but it happens time to time in our high load periods (weekly reporting, main working hours).

Bad thig about it - it took about 5 minutes from systemd to detect this fault and restart server.

We are heavily using `CREATE MATERIALIZED VIEW our_main_events_table TO some_data_dimension` to populate different tables for report.

    2019.07.22 12:46:00.869158 [ 1560 ] {} <Error> BaseDaemon: ########################################
    2019.07.22 12:46:00.869244 [ 1560 ] {} <Error> BaseDaemon: (version 19.9.3.31 (official build)) (from thread 1519) Received signal Segmentation fault (11).
    2019.07.22 12:46:00.869272 [ 1560 ] {} <Error> BaseDaemon: Address: NULL pointer.
    2019.07.22 12:46:00.869289 [ 1560 ] {} <Error> BaseDaemon: Access: read.
    2019.07.22 12:46:00.869322 [ 1560 ] {} <Error> BaseDaemon: Unknown si_code.
    2019.07.22 12:46:01.325007 [ 1560 ] {} <Error> BaseDaemon: 0. /lib/x86_64-linux-gnu/libc.so.6(+0x16eff6) [0x7fed46d9aff6]
    2019.07.22 12:46:01.345662 [ 1560 ] {} <Error> BaseDaemon: 1. /usr/bin/clickhouse-server(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const+0x24) [0x39d8b14]
    2019.07.22 12:46:01.345718 [ 1560 ] {} <Error> BaseDaemon: 2. /usr/bin/clickhouse-server(DB::SyntaxAnalyzer::analyze(std::shared_ptr<DB::IAST>&, DB::NamesAndTypesList const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::shared_ptr<DB::IStorage>) const+0x1510) [0x67bc360]
    2019.07.22 12:46:01.345748 [ 1560 ] {} <Error> BaseDaemon: 3. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, std::shared_ptr<DB::IBlockInputStream> const&, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x49e) [0x66e3fee]
    2019.07.22 12:46:01.345774 [ 1560 ] {} <Error> BaseDaemon: 4. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x4a) [0x66e4e4a]
    2019.07.22 12:46:01.345792 [ 1560 ] {} <Error> BaseDaemon: 5. /usr/bin/clickhouse-server(DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x76f) [0x66f1e4f]
    2019.07.22 12:46:01.345828 [ 1560 ] {} <Error> BaseDaemon: 6. /usr/bin/clickhouse-server(DB::StorageView::read(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, DB::SelectQueryInfo const&, DB::Context const&, DB::QueryProcessingStage::Enum, unsigned long, unsigned int)+0x48a) [0x6d5725a]
    2019.07.22 12:46:01.345849 [ 1560 ] {} <Error> BaseDaemon: 7. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::InterpreterSelectQuery::Pipeline&, std::shared_ptr<DB::PrewhereInfo> const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x202a) [0x66def4a]
    2019.07.22 12:46:01.345873 [ 1560 ] {} <Error> BaseDaemon: 8. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::executeImpl(DB::InterpreterSelectQuery::Pipeline&, std::shared_ptr<DB::IBlockInputStream> const&, bool)+0x6f7) [0x66e25d7]
    2019.07.22 12:46:01.345891 [ 1560 ] {} <Error> BaseDaemon: 9. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::executeWithMultipleStreams()+0x4f) [0x66e513f]
    2019.07.22 12:46:01.345900 [ 1560 ] {} <Error> BaseDaemon: 10. /usr/bin/clickhouse-server(DB::InterpreterSelectWithUnionQuery::executeWithMultipleStreams()+0x6c) [0x66f069c]
    2019.07.22 12:46:01.345916 [ 1560 ] {} <Error> BaseDaemon: 11. /usr/bin/clickhouse-server(DB::InterpreterSelectWithUnionQuery::execute()+0x38) [0x66f0f38]
    2019.07.22 12:46:01.345939 [ 1560 ] {} <Error> BaseDaemon: 12. /usr/bin/clickhouse-server() [0x6d05e37]
    2019.07.22 12:46:01.345948 [ 1560 ] {} <Error> BaseDaemon: 13. /usr/bin/clickhouse-server(DB::LazyBlockInputStream::readImpl()+0x7f) [0x68e29ff]
    2019.07.22 12:46:01.345963 [ 1560 ] {} <Error> BaseDaemon: 14. /usr/bin/clickhouse-server(DB::IBlockInputStream::read()+0x188) [0x65926e8]
    2019.07.22 12:46:01.345971 [ 1560 ] {} <Error> BaseDaemon: 15. /usr/bin/clickhouse-server(DB::CreatingSetsBlockInputStream::createOne(DB::SubqueryForSet&)+0x55c) [0x6b5df9c]
    2019.07.22 12:46:01.345984 [ 1560 ] {} <Error> BaseDaemon: 16. /usr/bin/clickhouse-server(DB::CreatingSetsBlockInputStream::readPrefixImpl()+0x3f) [0x6b6003f]
    2019.07.22 12:46:01.345993 [ 1560 ] {} <Error> BaseDaemon: 17. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x7a) [0x658e56a]
    2019.07.22 12:46:01.346001 [ 1560 ] {} <Error> BaseDaemon: 18. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346018 [ 1560 ] {} <Error> BaseDaemon: 19. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346026 [ 1560 ] {} <Error> BaseDaemon: 20. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346039 [ 1560 ] {} <Error> BaseDaemon: 21. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346048 [ 1560 ] {} <Error> BaseDaemon: 22. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346061 [ 1560 ] {} <Error> BaseDaemon: 23. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346070 [ 1560 ] {} <Error> BaseDaemon: 24. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346082 [ 1560 ] {} <Error> BaseDaemon: 25. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346092 [ 1560 ] {} <Error> BaseDaemon: 26. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346110 [ 1560 ] {} <Error> BaseDaemon: 27. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346119 [ 1560 ] {} <Error> BaseDaemon: 28. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346131 [ 1560 ] {} <Error> BaseDaemon: 29. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346141 [ 1560 ] {} <Error> BaseDaemon: 30. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346153 [ 1560 ] {} <Error> BaseDaemon: 31. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346163 [ 1560 ] {} <Error> BaseDaemon: 32. /usr/bin/clickhouse-server(DB::IBlockInputStream::readPrefix()+0x59) [0x658e549]
    2019.07.22 12:46:01.346177 [ 1560 ] {} <Error> BaseDaemon: 33. /usr/bin/clickhouse-server(DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::thread(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long)+0x157) [0x6ba2c97]
    2019.07.22 12:46:01.346227 [ 1560 ] {} <Error> BaseDaemon: 34. /usr/bin/clickhouse-server(ThreadFromGlobalPool::ThreadFromGlobalPool<DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::process()::{lambda()#1}>(DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::process()::{lambda()#1}&&)::{lambda()#1}::operator()() const+0x71) [0x6ba3291]
    2019.07.22 12:46:01.346241 [ 1560 ] {} <Error> BaseDaemon: 35. /usr/bin/clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1af) [0x728caef]
    2019.07.22 12:46:01.346249 [ 1560 ] {} <Error> BaseDaemon: 36. /usr/bin/clickhouse-server() [0xb1a369f]
    2019.07.22 12:46:01.346256 [ 1560 ] {} <Error> BaseDaemon: 37. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7fed477126ba]

Also I have this partial crash: 
[_usr_bin_clickhouse.0.crash.log](https://github.com/yandex/ClickHouse/files/3417721/_usr_bin_clickhouse.0.crash.log)

**Comment by alexey-milovidov** [comment]
Does it reproduce on version 19.11?

**Comment by filimonov** [comment]
> Hi there.
> 
> We have issue on 19.9.3.31 (official build) under Ubuntu on AWS EC2.
> 
> I cannot reproduce it on our test servers, but it happens time to time in our high load periods (weekly reporting, main working hours).
> 
> Bad thig about it - it took about 5 minutes from systemd to detect this fault and restart server.
> 
> We are heavily using `CREATE MATERIALIZED VIEW our_main_events_table TO some_data_dimension` to populate different tables for report.
> 
> ```
> 2019.07.22 12:46:00.869158 [ 1560 ] {} <Error> BaseDaemon: ########################################
> 2019.07.22 12:46:00.869244 [ 1560 ] {} <Error> BaseDaemon: (version 19.9.3.31 (official build)) (from thread 1519) Received signal Segmentation fault (11).
> 2019.07.22 12:46:00.869272 [ 1560 ] {} <Error> BaseDaemon: Address: NULL pointer.
> 2019.07.22 12:46:00.869289 [ 1560 ] {} <Error> BaseDaemon: Access: read.
> 2019.07.22 12:46:00.869322 [ 1560 ] {} <Error> BaseDaemon: Unknown si_code.
> 2019.07.22 12:46:01.325007 [ 1560 ] {} <Error> BaseDaemon: 0. /lib/x86_64-linux-gnu/libc.so.6(+0x16eff6) [0x7fed46d9aff6]
> 2019.07.22 12:46:01.345662 [ 1560 ] {} <Error> BaseDaemon: 1. /usr/bin/clickhouse-server(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const+0x24) [0x39d8b14]
> 2019.07.22 12:46:01.345718 [ 1560 ] {} <Error> BaseDaemon: 2. /usr/bin/clickhouse-server(DB::SyntaxAnalyzer::analyze(std::shared_ptr<DB::IAST>&, DB::NamesAndTypesList const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::shared_ptr<DB::IStorage>) const+0x1510) [0x67bc360]
...
> ```

Can you please try to find what was happening just before the crash, and especially - what the thread with number 1560 was doing? You can find that in /vat/log/clickhouse-server/clickhouse-server.log

**Comment by Imomoi** [comment]
Last output by thread 1519 was:

    2019.07.14 23:40:58.711455 [ 1519 ] {f86efa41-f1b7-4546-8d20-25ad9e6a4877} <Information> TCPHandler: Processed in 0.039 sec.

    2019.07.14 23:41:00.013460 [ 1519 ] {} <Error> ServerErrorHandler: Code: 210, e.displayText() = DB::NetException: Connection reset by peer, while reading from socket (54.152.97.218:53568), Stack trace:

    0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x72868b6]
    1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x22) [0x39a9032]
    2. /usr/bin/clickhouse-server() [0x3847a89]
    3. /usr/bin/clickhouse-server(DB::TCPHandler::runImpl()+0x8ec) [0x39b4aec]
    4. /usr/bin/clickhouse-server(DB::TCPHandler::run()+0x2b) [0x39b4f7b]
    5. /usr/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x739579f]
    6. /usr/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0xe9) [0x7395ed9]
    7. /usr/bin/clickhouse-server(Poco::PooledThread::run()+0x81) [0x7446b51]
    8. /usr/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x7442f58]
    9. /usr/bin/clickhouse-server() [0xb1a369f]
    10. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f43e3c0e6ba]
    11. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f43e322f41d]
    (version 19.9.3.31 (official build))


Also I found that in period since 2019.07.14 23:41:00.002073 to 23:41:00.033291 we got 293 such errors (possibly it was our application restart).

**Comment by Imomoi** [comment]
@alexey-milovidov We cannot reproduce this bug on our test servers (neither 19.9 or 19.11).

We are currently testing 19.11 before install it on our release servers.

**Comment by Imomoi** [comment]
@alexey-milovidov On 19.11 it looks OK. No more crashes for now. (Around 2 weeks in release).

**Comment by alexey-milovidov** [comment]
Thank you!
