### ISSUE TITLE
modify mergetree settings 

### ISSUE THREAD

**Issue by isiyu** [yandex/ClickHouse#6130]
How do you modify mergetree settings on an existing table? for a distributed table. 

Specifically trying to temporarily modify `replicated_deduplication_window` to flush or deactivate deduplication blocks on a cluster.

**Comment by den-crane** [comment]
https://github.com/yandex/ClickHouse/issues/2607#issuecomment-403454286

**Comment by alesapin** [comment]
@den-crane's answer is correct. Also we have plans to add query `ALTER TABLE xxx MODIFY SETTING replicated_deduplication_window=yyyy`.
