### ISSUE TITLE
Choose sharding_key for shrading based on IP address

### ISSUE THREAD

**Issue by linrl3** [yandex/ClickHouse#6133]
Hi guys, I'm new to clickhouse. I'd like to shard a table based on the IP address field. So I'm gonna use the DIstributed engine. But I'm wondering what shrading_key I should choose. I know clickhouse only support hash and rand(). Which hash function should I choose for the IP address field in this senerio?

**Comment by alexey-milovidov** [comment]
If you store IPv4 address in UInt32, `intHash64` will suffice,
otherwise use `cityHash64`.
