### ISSUE TITLE
[Question] Insert string to Clickhouse over Protobuf format 

### ISSUE THREAD

**Issue by igor-sh8** [yandex/ClickHouse#6135]
Hello. 
I faced with the next situation in work with Protobuf format in Clickhouse. 
I am trying to insert some data to Clickhouse using Protobuf format. When I insert data, for example just some int values, all works fine, but when I am trying to insert string to Clickhouse it displays just as empty strings and there is no any exceptions on the server side. 
An example of my Protobuf schema:
```
syntax = "proto3";
message Test{
int32 Id = 1;
int64 Date =2;
int32 Id2=3;
string TestStr=4;
};
```
When I insert data over clickhouse-client console:
`cat Test.txt | clickhouse-client --query "INSERT INTO default.proto FORMAT Protobuf SETTINGS format_schema='test.proto:Test'" `
all data is inserted normally.
In work I use custom c# client (just HTTP handler inside). When I use it, all fields are inserted except strings. In tables I see such strings as empty strings. 
Also example of code on c# end:
```
var ev = new Test()
                        {
                            Date = (long)1562337042,
                            Id = i,
                            Id2 = i,
                            TestStr = "Test"
                        };
using (var ms = new MemoryStream())
                        {
                            ev.WriteDelimitedTo(ms);
                            bytes = ms.ToArray();
                        }
```
The main thing in this situation is that I generate the file Test.txt (in Protobuf format) from c# client. So I can insert this file to Clickhouse with the clickhouse-client but I can not do that with my c# client.
Maybe you some advise for me ?

**Comment by vitlibar** [comment]
Maybe there is a problem in HTTP handler or in your code.

Can you try the following:
```
cat Test.txt | curl 'http://localhost:8123/?query=INSERT%20INTO%20default.proto%20FORMAT%20Protobuf%20SETTINGS%20format_schema%3D%27test.proto%3ATest%27' --data-binary @-
```
Does it work?

**Comment by igor-sh8** [comment]
Hi. 
Sorry, we didn’t determine what the problem was, so we closed tests with `Protobuf` (it was already before your reply). 
And for now we just decided to use a different format, in our case `Native`.
Thanks.
