### ISSUE TITLE
Submodule did not upgrade after merge from official master.

### ISSUE THREAD

**Issue by kindred77** [yandex/ClickHouse#6145]
I forked from clickhouse official master and have done some own code work.
Yesterday, I merged code from master to my branch and got a build error when executing cmake:

cmake -DGLIBC_COMPATIBILITY=0 -DNO_WERROR=1 -DCMAKE_EXE_LINKER_FLAGS="-static-libstdc++" ..

-- Using occi lib: /clickhouse-deploy/instantclient_12_1/libocci.so /clickhouse-deploy/instantclient_12_1/libclntsh.so
-- Target check already exists
-- Configuring done
CMake Error at contrib/libunwind-cmake/CMakeLists.txt:27 (add_library):
  Cannot find source file:

    /clickhouse-deploy/ClickHouse/contrib/libunwind/src/libunwind.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at contrib/librdkafka-cmake/CMakeLists.txt:60 (add_library):
  Cannot find source file:

    /clickhouse-deploy/ClickHouse/contrib/librdkafka/src/rdkafka_cert.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at contrib/libunwind-cmake/CMakeLists.txt:27 (add_library):
  No SOURCES given to target: unwind_static

CMake Error at contrib/librdkafka-cmake/CMakeLists.txt:60 (add_library):
  No SOURCES given to target: rdkafka

-- Build files have been written to: /clickhouse-deploy/ClickHouse/build

I found the version of my submodules(librdkafka, libunwind and some others) did not match the official master.
Could you give me a help?

**Comment by akuzm** [comment]
Please try:
```
git submodule sync
git submodule update --init --recursive
```

**Comment by alexey-milovidov** [comment]
It's git usability issue. Submodules are not updated on merge or pull.
You always have to update them manually with the commands above.

You can blame git for this.
