### ISSUE TITLE
Cannot create a database which name starts with a number

### ISSUE THREAD

**Issue by olegkv** [yandex/ClickHouse#6160]
When I run:
"create database 1test"

I get:
Syntax error: Wrong number 
(version 19.11.3.11 (official build))

**Comment by alexey-milovidov** [comment]
You have to quote database name like this:
```
CREATE DATABASE `1test`
```
or this:
```
CREATE DATABASE "1test"
```

**Comment by olegkv** [comment]
I tried single quotes like '1test' and it did not work, did not try double quotes.
Using double quotes solves it, but it is still sort of inconvenient because tables always need to be referenced like "1test".table1 instead of 1test.table1, but that's minor.
Thanks!
