### ISSUE TITLE
-Wshadow for GCC

### ISSUE THREAD

**Issue by kreuzerkrieg** [yandex/ClickHouse#6166]
Correct me if I wrong, but it looks like `-Wshadow` used only in case the compiler is `Clang`. Why not to apply it for GCC too?

**Comment by alexey-milovidov** [comment]
Yes, we can enable it for gcc.

PS. Why it isn't enabled right now? - We use both gcc and clang in our CI and after we enabled maximum possible warnings for clang, there is less motivation to add them in gcc.

**Comment by kreuzerkrieg** [comment]
Ok, I will PR during the upcoming week.

**Comment by kreuzerkrieg** [comment]
hm... I've added the `-Wshadow` to the CMakeList and got a bunch of errors like
>> /home/Development/ClickHouse/dbms/src/Common/RWLock.h:71:35: error: declaration of ‘type’ shadows a member of ‘DB::RWLockImpl::Group’ [-Werror=shadow]
         explicit Group(Type type) : type{type} {}

or 
>> /home/Development/ClickHouse/dbms/src/Core/Types.h:73:5: error: declaration of ‘Float32’ shadows a global declaration [-Werror=shadow]
     Float32,
     ^~~~~~~
/home/Development/ClickHouse/dbms/src/Core/Types.h:25:22: note: shadowed declaration is here
 using Float32 = float;


which are, IMHO, are correct warnings, dont know how the CLang let it compile, maybe it somewhat more relaxed than GCC. What do you want me to do with it. Apparently I cant create PR with all these errors

**Comment by alexey-milovidov** [comment]
> ‘type’ shadows a member

It's not very convenient, because

```
class C
{
int x;
C(int x) : x(x) {}
};
```

is a common practice.

We also write

```
class C
{
int x;
C(int x_) : x(x_) {}
};
```

in many places, but it apparently may be more error-prone.

**Comment by alexey-milovidov** [comment]
For clang we also have `-Wno-shadow-field-in-constructor`

**Comment by alexey-milovidov** [comment]
But we can rewrite all the code and enable it. It's not hard (a few hours work).

**Comment by kreuzerkrieg** [comment]
I hit the `:a(a)` some time ago
https://stackoverflow.com/questions/48888177/shadowing-and-gcc-wshadow
and the explanation why it is not valid code is quite simple

I didnt find the `no-shadow-field-in-constructor` equivalent for GCC, so no luck here

I can change the filed initialization myself, not too complicated stuff, but what you gonna do with types declaration in Types.h? it is more complicated and error prone, IMHO

**Comment by alexey-milovidov** [comment]
> but what you gonna do with types declaration in Types.h?

It is inside `enum class`:

```
using Float32 = ...;
...
enum class TypeIndex
{
    Float32 = ...
};
```

 - looks perfectly Ok.
But look at the first answer here:
https://stackoverflow.com/questions/53841625/wshadow-global-considers-enum-class-entry-shadowing-a-global-why

Maybe reordering code will help?

**Comment by alexey-milovidov** [comment]
> I hit the :a(a) some time ago

Let's replace all `a(a)` to `a(a_)`. I appreciate if you can help!

**Comment by kreuzerkrieg** [comment]
> I hit the :a(a) some time ago
> 
> Let's replace all a(a) to a(a_). I appreciate if you can help!

Will do

**Comment by kreuzerkrieg** [comment]
Calamity! It was more like 5 hours...
I want to see if it passes CI and then I will additional changes, mostly to bring headers in line with CPPs
