### ISSUE TITLE
clickhouse-client --query does not return results

### ISSUE THREAD

**Issue by bseng** [yandex/ClickHouse#62]
I'm use the clickhouse-client in interactive mode and when I run a query with inner join between 2 subqueries, results are returned

However when I run the same query with batch mode i.e. 'clickhouse-client --query=""' no results are return in bash.

there's no error in the log and the access log looks the same for the 2 queries

can you see if you can replicate it?

**Comment by bseng** [comment]
I've found out whats wrong, when it run with batch mode the regexp get encode so \\1 becomes \1 so nothing can be match.

you will need to put \\\\1 instead of \\1

**Comment by alexey-milovidov** [comment]
Also possible to pass query to stdin:
`clickhouse-client < query.sql`

That avoids shell escaping issues.
