### ISSUE TITLE
Way to Disable TTL

### ISSUE THREAD

**Issue by simPod** [yandex/ClickHouse#6200]
Is there a way to disable TTL on tables? To somehow freeze it?

I'd like to do so in my integration tests. CH in testing environment manages to expire my fixture data with 2018 timestamps in tables with eg. 90 days TTL set before the assertions happen.

**Comment by alexey-milovidov** [comment]
Probably SYSTEM STOP MERGES will help (but it will also disable all merges).

**Comment by simPod** [comment]
Yup, seems to do the thing but also disables mutations which breaks the tests in other way. 

Does it makes sense to have option in CH to disable TTL or should I find some workaround?

**Comment by alexey-milovidov** [comment]
Yes, it makes sense.

Another option: specify large enough `merge_with_ttl_timeout` (e.g. `1000000`) in `/yandex/merge_tree` in config.xml (it's a place for global MergeTree settings; you can find all the settings in `MergeTreeSettings.h` file; if you have not specified a setting in `SETTINGS` clause of CREATE TABLE, global value will be used).

**Comment by CurtizJ** [comment]
I suggest to introduce query `SYSTEM STOP TTL MERGES`.

**Comment by alexey-milovidov** [comment]
@CurtizJ Ok.

**Comment by CurtizJ** [comment]
Implemented in #6274
