### ISSUE TITLE
issue with replaceRegexpOne

### ISSUE THREAD

**Issue by kkxxr66573** [yandex/ClickHouse#6203]
```sql
select replaceRegexpOne('smc.exec.ds.alpha.testcase.testcase4g.epsfallback.epsfallback_5g2eps_test.go','(.*)\..+\.go','\\1')
```

the result should be 'smc.exec.ds.alpha.testcase.testcase4g.epsfallback'
but the test result is 'smc.exec.ds.alpha.testcase.testcase4g.epsfallback.epsfallback_5g2eps_te'

**Comment by alexey-milovidov** [comment]
To put backslash in regexp, you have to escape it in a string literal with another backslash. Example:
```
select replaceRegexpOne('smc.exec.ds.alpha.testcase.testcase4g.epsfallback.epsfallback_5g2eps_test.go','(.*)\\..+\\.go','\\1')
```

**Comment by alexey-milovidov** [comment]
It works as expected.

**Comment by filimonov** [comment]
#10922
