### ISSUE TITLE
materialized view with multiple source table

### ISSUE THREAD

**Issue by ramazanpolat** [yandex/ClickHouse#6213]
As far as I understand, materialized view can only have one source table.

Can somebody explain the idea behind this decision?

Is it too hard to implement a multi source materialized view?

Or there are conceptual difficulties behind this?

**Comment by filimonov** [comment]
In ClickHouse materialized view behaves more like BEFORE INSERT TRIGGER, each time processing new block arrived with insert. 

So that is quite natural limitation as inserts to 2 different table will come asynchronously and you usually expect to see in JOINs whole table not only newly arrived blocks.

**Comment by lud4ik** [comment]
https://altinity.com/blog/2020-07-14-joins-in-clickhouse-materialized-views
Here id described that they work
> materialized views trigger off the left-most table of the join.  The materialized view will pull values from right-side tables in the join but will not trigger if those tables change

Is it true? I just didn't find this in docs.

**Comment by ychensha** [comment]
> https://altinity.com/blog/2020-07-14-joins-in-clickhouse-materialized-views
> Here is described that they work
> 
> > materialized views trigger off the left-most table of the join.  The materialized view will pull values from right-side tables in the join but will not trigger if those tables change
> 
> Is it true? I just didn't find this in docs.

Found that too, have you reproduced ? I wanna try myself...
