### ISSUE TITLE
A bug in ParquetBlockInputStream?

### ISSUE THREAD

**Issue by kreuzerkrieg** [yandex/ClickHouse#6237]
Here
https://github.com/yandex/ClickHouse/blob/c43dfce041c8aa0e018eb829bb19165aa3979d9d/dbms/src/Formats/ParquetBlockInputStream.cpp#L129

Isnt the outer `for` overwrites the data in the `column_data` over and over again?

**Comment by proller** [comment]
Its a bug!
https://github.com/yandex/ClickHouse/pull/6264

**Comment by alexey-milovidov** [comment]
Fixed. But @proller failed to add a test, so test on your own.
