### ISSUE TITLE
cache very big and don't release

### ISSUE THREAD

**Issue by quyaxing** [yandex/ClickHouse#6238]
The query cache has been growing, and the configuration item uncompressed_cache_size is not in effect!

**Comment by den-crane** [comment]
There is no query cache in CH. 
Do you mean Linux cache? It normal Unix-like OS use all free memory for the disk cache.

**Comment by quyaxing** [comment]
Thank you very much for your reply！
 I would like to ask what the specific function of this configuration item uncompressed_cache_size is. Can't it be used to control the query cache?


| |
屈亚星
|
|
quyaxing23@126.com
|
签名由网易邮箱大师定制


On 08/1/2019 00:59，Denis Zhuravlev<notifications@github.com> wrote：

There is no query cache in CH.
Do you mean Linux cache? It normal Unix-like OS use all free memory for the disk cache.

**Comment by den-crane** [comment]
use_uncompressed_cache
https://clickhouse.yandex/docs/en/operations/settings/settings/#setting-use_uncompressed_cache
it is disabled by default

**Comment by alexey-milovidov** [comment]
> I would like to ask what the specific function of this configuration item uncompressed_cache_size is. Can't it be used to control the query cache?

It allows to cache blocks of data in decompressed form to avoid the cost of decompressing data and reading data from disk for repeating queries. Uncompressed cache is less efficient than OS page cache and usually kept small (for example, 10% or RAM).
