### ISSUE TITLE
Data duplication Solve

### ISSUE THREAD

**Issue by qietingfengling** [yandex/ClickHouse#6259]
I use the ReplacingMergeTree engine, how to solve the problem of data duplication? I need to be more real-time.

**Comment by filimonov** [comment]
Duplicate
https://github.com/yandex/ClickHouse/issues/5125
https://github.com/yandex/ClickHouse/issues/5409
https://github.com/yandex/ClickHouse/issues/4159
https://github.com/yandex/ClickHouse/issues/1178
https://github.com/yandex/ClickHouse/issues/3312
and others...
