### ISSUE TITLE
Consider updating to simdjson 0.2.0

### ISSUE THREAD

**Issue by lemire** [yandex/ClickHouse#6285]
The library simdjson has a new major release (0.2.0). Major changes:

* Support for 64-bit ARM processors, can run under iOS (iPhone).
* Runtime dispatching on x64 processors (switches to SSE on older x64 processors, uses AVX2 when available). Supports processors as far back as the Intel Westmere.
* More accurate number parsing.
* Fixes most warnings under Visual Studio.
* Several small bugs have been fixed.
* Better performance in some cases.
* Introduces a JSON Pointer interface https://tools.ietf.org/html/rfc6901
* Better and more specific error messages (with optional textual descriptions).
* valgrind clean.
* Unified code style (LLVM).

**Comment by alexey-milovidov** [comment]
> Runtime dispatching on x64 processors

Does it require to compile all translation units with `-mavx2`?

```
  // Determining which implementation is the more suitable
  // Should be done at runtime. Does not make any sense on preprocessor.
#ifdef __AVX2__
  instruction_set best_implementation = instruction_set::avx2;
```

(for __AVX2__ to be defined)

In that case, it cannot work on machines without AVX2, because compiler will emit AVX2 instructions for any code in the translation unit and the program will get Illegal Instruction before attempt to dynamic dispatch.

**Comment by alexey-milovidov** [comment]
PS. JSON Pointer is great, we should add support for it in ClickHouse :)

**Comment by lemire** [comment]
> Does it require to compile all translation units with -mavx2?

No! Of course not.  See simdjson/src/jsonparser.cpp for the dispatching logic.

Of course, if you compile with -mavx2, then you will defeat the purpose of runtime dispatching. 

We recommend compiling with ' -msse4.2 -mpclmul' if you use GNU GCC, LLVM CLANG. This corresponds to Intel Westmere... This then gives you support for Westemere, Sandy Bridge, and so forth.

**Comment by alexey-milovidov** [comment]
Ok. Another question: is it tested with TSan (or is there something that may affect it in newer version)?
We have one TSan report for pull request with upgrading but unfortunately without enough context.

PS. Maybe dynamic dispatch use non atomic variable?
You can switch to atomic variable with memory_order_relaxed access, that will be equivalent but TSan will not argue.

**Comment by lemire** [comment]
The simdjson library is single-threaded.

The runtime dispatch assigns the right function the first time the function is called. This is not thread-safe: so the first function call must be single-threaded.

**Comment by alexey-milovidov** [comment]
That's right and it is very easy to fix.

**Comment by alexey-milovidov** [comment]
Another example: https://github.com/yandex/ClickHouse/pull/6141

**Comment by lemire** [comment]
Let us know if there is anything we can do to help. I have added documentation to our README.

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse-Extras/simdjson/commit/e3f6322af762213ff2087ce3366bf9541c7fd355

I can send a pull request if you are Ok with this solution.

**Comment by alexey-milovidov** [comment]
Step 2: https://github.com/yandex/ClickHouse/pull/6320

**Comment by lemire** [comment]
Please do open a pull request upstream. I'll create an issue upstream to match.

Regarding the proposed solution, the pointer can be assigned only in one function (json_parse_dispatch). Instead of changing the pointer type to an atomic type, can't we just create an exclusive lock in json_parse_dispatch with a test early in the function to check whether the pointer has already be reassigned? This json_parse_dispatch should be called only once.

**Comment by alexey-milovidov** [comment]
We can serialize `json_parse_dispatch` with lock (or with function static variable). This will prevent concurrent execution of CPU detection (though it's not a bad thing).

But if the variable `json_parse_ptr` is assigned under lock but read without a lock, it doesn't make sense (TSan will report data race).

**Comment by lemire** [comment]
You are right.
