### ISSUE TITLE
How to bypass user checking on startup?

### ISSUE THREAD

**Issue by ddliu** [yandex/ClickHouse#6289]
```
Application: DB::Exception: Effective user of the process (root) does not match the owner of the data (1000). Run under 'sudo -u 1000'.
```

Is it possible to bypass the data owner checking without `chown`, since I have too many files to wait for.

**Comment by filimonov** [comment]
Currently it is not possible. When you run it as root it will finish with exception. See:  https://github.com/yandex/ClickHouse/pull/3785#discussion_r240163579

Can i ask why do you need to run clickhouse as root?

**Comment by alexey-milovidov** [comment]
If you want to run clickhouse-server as root, you can chown data directory to root:
`chown -R root:root /var/lib/clickhouse`

When you will need to get back normal, you can chown back:
`chown -R clickhouse:clickhouse /var/lib/clickhouse`

**Comment by alexey-milovidov** [comment]
We have this check to avoid situation when the user temporarily runs clickhouse-server as root and it will pollute data directory with some root-owned files, that normally run clickhouse-server can't manipulate.

**Comment by ddliu** [comment]
> Currently it is not possible. When you run it as root it will finish with exception. See: [#3785 (comment)](https://github.com/yandex/ClickHouse/pull/3785#discussion_r240163579)
> 
> Can i ask why do you need to run clickhouse as root?

I have some projects which need to be migrated to Docker deployment, and that might cause this ownership problem.

**Comment by ddliu** [comment]
Seems ok to just `chown` the top level directory.

https://github.com/yandex/ClickHouse/blob/8dfe294fc4da29deeee0a46ddce381faabce8c65/dbms/programs/server/Server.cpp#L238

**Comment by filimonov** [comment]
> I have some projects which need to be migrated to Docker deployment, and that might cause this ownership problem.

Official docker image run clickhouse process in non-root mode
