### ISSUE TITLE
Cannot load time zone Z

### ISSUE THREAD

**Issue by AlexMAS** [yandex/ClickHouse#6290]
Hi,

Please, add alias `Z` for `UTC` time zone.

Presently I can execute statements passing `UTC` constant:

```sql
:) select toStartOfDay(now(), 'UTC') as utcTime

SELECT toStartOfDay(now(), 'UTC') AS utcTime

┌─────────────utcTime─┐
│ 2019-08-02 00:00:00 │
└─────────────────────┘

1 rows in set. Elapsed: 0.002 sec.
```

But cannot execute statements passing `Z` constant:

```sql
:) select toStartOfDay(now(), 'Z') as utcTime

SELECT toStartOfDay(now(), 'Z') AS utcTime

Received exception from server (version 19.4.3):
Code: 1000. DB::Exception: Received from s:9000, 172.18.0.4.
DB::Exception: Exception: Cannot load time zone Z.

0 rows in set. Elapsed: 0.002 sec.
```

I expect that `Z` will be an alias for `UTC`. Yes, I know that `Z` refers to the time zone *offset*. But anyway it'll be convenient especially for Java developers who use [java.time.ZoneId](https://docs.oracle.com/javase/8/docs/api/java/time/ZoneId.html) and the constant for [UTC](https://docs.oracle.com/javase/8/docs/api/java/time/ZoneOffset.html#UTC) which string representation is `Z`. At the moment I have to do a workaround before querying data:

```java
ZoneId timeZone; //
String timeZoneId;

if (timeZone == null || timeZone.equals(ZoneOffset.UTC)) {
	timeZoneId = "UTC";
} else {
	timeZoneId = timeZone.getId();
}
```

P.s. I'm using ClickHouse version `19.4.3` revision `54416`.

**Comment by filimonov** [comment]
Actually ClickHouse supports timezones from tzdata package, i.e. known in OS level.

https://unix.stackexchange.com/questions/504043/how-to-list-timezones-known-to-the-system

There is no timezone named `Z` in tzdata, but if you need you can easely add symlink in appropriate folder, and such a timezone will appear.  
```
root@70886bf525da:/usr/share/zoneinfo# cd /usr/share/zoneinfo
root@70886bf525da:/usr/share/zoneinfo# ln -s UCT posix/ZZZZZZZ
root@70886bf525da:/usr/share/zoneinfo# ln -s UCT ZZZZZZZ

root@70886bf525da:/usr/share/zoneinfo# clickhouse-client 
ClickHouse client version 19.11.2.7 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 19.11.2 revision 54423.

70886bf525da :) select toStartOfDay(now(), 'ZZZZZZZ') as utcTime;

SELECT toStartOfDay(now(), 'ZZZZZZZ') AS utcTime

┌─────────────utcTime─┐
│ 2019-08-02 00:00:00 │
└─────────────────────┘

1 rows in set. Elapsed: 0.013 sec. 
```

**Comment by filimonov** [comment]
That topic pops up again, and in current versions the same workaround as above is not possible (now tzdata is bundled in ClickHouse)

`Z` is not the standard timezone name, i think it can easily done in Java (smth like `TimeZone.getTimeZone("Z").getID()`)

Adding extra alias  to clickhouse is doable (& not hard), but I have some doubts about that - i general i prefer to avoid adding some hacks in the standard component (tzdata) in a standard distribution. It sounds like an ad-hoc thing, if not - better to convince tzdata maintainers to add such an alias (so it will be recognized generally and will work not only for ClickHouse)

**Comment by den-crane** [comment]
Instead of creating aliases I would hardcoded a substitute `If tz=Z then UTC else tz`

**Comment by alexey-milovidov** [comment]
@filimonov It is named `Zulu`:

```
milovidov@milovidov-desktop:~/work/ClickHouse$ clickhouse-local 
ClickHouse local version 23.2.1.1.

milovidov-desktop :) SELECT now('Zulu')

SELECT now('Zulu')

Query id: dffe45e6-238f-4a86-bede-991ffe032096

┌─────────now('Zulu')─┐
│ 2023-02-02 14:26:53 │
└─────────────────────┘
```

**Comment by den-crane** [comment]
@alexey-milovidov You don't understand. 

Clickhouse makes JAVA developers to hardcode `If tz=Z then UTC else tz` in JAVA. Because they have 'Z'. And it's not that easy sometimes because it's covered by layers of abstractions like spark.
