### ISSUE TITLE
Changelog for New Updates

### ISSUE THREAD

**Issue by hardik137** [yandex/ClickHouse#6291]
**Use case**
We need to understand if it is worthwhile to upgrade to new version of clickhouse or not - There is not guideline for fixes and release since last 1 month

**Describe the solution you'd like**
For every release - can we get changelog to understand what is fixed.

**Comment by blinkov** [comment]
You can always see what's changed via `git log` or GitHub web interface like https://github.com/yandex/ClickHouse/compare/19.7...19.11 , while manually reviewed [CHANGELOG.md](https://github.com/yandex/ClickHouse/blob/master/CHANGELOG.md) is produced as fast as we physically can.
