### ISSUE TITLE
Error on LowCardinality(String) to UInt64 conversion

### ISSUE THREAD

**Issue by MetalRex101** [yandex/ClickHouse#6293]
create table test (a LowCardinality(String)) engine=MergeTree() Order by a;
create table test2 (a UInt64) engine=MergeTree() Order by a;
create materialized view test_mv to test2 as select toUInt64(a = 'foo') from test;

Code: 455. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Creating columns of type LowCardinality(UInt64) is prohibited by default due to expected negative impact on performance. It can be enabled with the "allow_suspicious_low_cardinality_types" setting..

**Comment by MetalRex101** [comment]
Clickhouse converts LowCardinality(String) to LowCardinality(Int8) and then to LowCardinality(UInt64) instead of usual Uint64

**Comment by den-crane** [comment]
```
DESCRIBE TABLE
(
    SELECT CAST(a, 'String') = 'foo'
    FROM test
)

┌─name─────────────────────────────┬─type──┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ equals(CAST(a, 'String'), 'foo') │ UInt8 │              │                    │         │                  │                │
└──────────────────────────────────┴───────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘
```
