### ISSUE TITLE
Kafka engine consumes messages in an infinite loop

### ISSUE THREAD

**Issue by luck143** [yandex/ClickHouse#6308]
Latest version of clickhouse version 19.11.4.24 has this bug

kafka engine is consuming messages in infinite loop 

even if kafka stream has only one message the clickhouse kafka engine will consume it over and over again and fill the DB

**Comment by ivanprostran** [comment]
I confirm this behavior, I had to drop 2 partitions   ('2019-08-03',  '2019-08-02'). 1.5 Billion records.
Now downgraded to : clickhouse-server-19.11.3.11-1.el7.x86_64
We use clickhouse in production. Kafka engine drives us crazy. 
I Don't know what to do (perhaps bulk insert through clickhosue-client as temporary solutin until kafka consuming is resolved). Apart from this above, kafka consumers hang and we have LAGs. Detach/Attach doesn't help, only forcerestart.

**Comment by luck143** [comment]
> I confirm this behavior, I had to drop 2 partitions ('2019-08-03', '2019-08-02'). 1.5 Billion records.
> Now downgraded to : clickhouse-server-19.11.3.11-1.el7.x86_64
> We use clickhouse in production. Kafka engine drives us crazy.
> I Don't know what to do (perhaps bulk insert through clickhosue-client as temporary solutin until kafka consuming is resolved). Apart from this above, kafka consumers hang and we have LAGs. Detach/Attach doesn't help, only forcerestart.

This must be a noobish question but how to you downgrade clickhouse version safely from the production server without turning off the while cluster?

**Comment by ivanprostran** [comment]
> This must be a noobish question but how to you downgrade clickhouse version safely from the production server without turning off the while cluster?

Downtime!

I turned off the cluster, backed up the data directory, metrika.xml and /etc/clickhouse-server.
Another solution is rolling restart/upgrade/downgrade but this should be tested.
(At least I haven't tested it)

**Comment by abyss7** [comment]
This bug emerged with #6075 - it shows the breakage in tests but nevertheless it was merged. I will do a proper fix ASAP.

**Comment by splichy** [comment]
@abyss7 same on version 19.11.5.28

**Comment by alexey-milovidov** [comment]
The issue has been fixed by @abyss7 in version 19.11.7.
