### ISSUE TITLE
 clickhouse - How to downgrade or install previous version ?

### ISSUE THREAD

**Issue by luck143** [yandex/ClickHouse#6313]
This must be  noobish question but how to you downgrade clickhouse version or install previous version of clickhouse on centos 7. 

I installed clickhouse using https://packagecloud.io/Altinity/clickhouse package

> curl -s
> https://packagecloud.io/install/repositories/altinity/clickhouse/script.rpm.sh
> | sudo bash yum -y install clickhouse-server clickhouse-client
> clickhouse-server-common clickhouse-compressor

but in this package it already version  19.11.4.24 but has too many bugs (especially in kafka engine tables)

i wish to install stable lower version of clickhouse version 19.7.3.1 but i am not sure how to do it. 

i tried installing all packages manually but its always give one or the other dependency errors.

i would appreciate if someone could give me advise how to install previous versions. thanks

**Comment by slimtom95** [comment]
Try `showduplicates`  to see all available versions. For example:
```
yum search clickhouse-server --showduplicates
```

There is version 19.7.3.9 available, if it suits you.

**Comment by filimonov** [comment]
1. Check available versions,  and pick the version to install, 
```
yum --showduplicates list clickhouse-server

Loaded plugins: fastestmirror, langpacks, priorities
Loading mirror speeds from cached hostfile
 * epel: ftp.icm.edu.pl
 * ius: lon.mirror.rackspace.com
 * nux-dextop: mirror.li.nux.ro
244 packages excluded due to repository priority protections
Installed Packages
clickhouse-server.x86_64          19.6.2.11-1.el7           @altinity_clickhouse
Available Packages
clickhouse-server.x86_64          1.1.54292-3.el7           altinity_clickhouse 
clickhouse-server.x86_64          1.1.54304-3.el7           altinity_clickhouse 

...
clickhouse-server.x86_64          18.14.19-1.el7            altinity_clickhouse 
...
clickhouse-server.x86_64          19.11.4.24-1.el7          altinity_clickhouse
```

2. Check which clikchouse packages are installed:
```
➜ yum list installed "clickhouse*"
Loaded plugins: fastestmirror, langpacks, priorities
Loading mirror speeds from cached hostfile
 * epel: ftp.icm.edu.pl
 * ius: lon.mirror.rackspace.com
 * nux-dextop: mirror.li.nux.ro
594 packages excluded due to repository priority protections
Installed Packages
clickhouse-client.x86_64              19.6.2.11-1.el7       @altinity_clickhouse
clickhouse-common-static.x86_64       19.6.2.11-1.el7       @altinity_clickhouse
clickhouse-server.x86_64              19.6.2.11-1.el7       @altinity_clickhouse
clickhouse-server-common.x86_64       19.6.2.11-1.el7       @altinity_clickhouse
```

3. Downgrade ALL installed clickhouse packages simultaniously (in one downgrade command) to avoid dependency errors

```
➜ yum --showduplicates list clickhouse-server
➜ yum downgrade clickhouse-server-18.14.19-1.el7 clickhouse-client-18.14.19-1.el7 clickhouse-common-static-18.14.19-1.el7 clickhouse-server-common-18.14.19-1.el7  
```

4. Restart `clickhouse-server`
```
➜ systemctl daemon-reload 
➜ systemctl restart clickhouse-server 

➜ clickhouse-client 
ClickHouse client version 18.14.19.
Connecting to localhost:9000.
Connected to ClickHouse server version 18.14.19 revision 54409.
```

**Comment by luck143** [comment]
Thankyou very much

**Comment by rameshgarg475** [comment]
Hi I am facing the same issue,  but i followed the same steps. it is not working. can you help me with this?
