### ISSUE TITLE
what happen in error: field ‘_ctx’ has incomplete type ‘EVP_CIPHER_CTX {aka evp_cipher_ctx_st}’

### ISSUE THREAD

**Issue by sangli00** [yandex/ClickHouse#633]
```
/data/clickhouse_install/off_line_install/ClickHouse/contrib/libpoco/Crypto/src/CipherImpl.cpp:80:21: error: field ‘_ctx’ has incomplete type ‘EVP_CIPHER_CTX {aka evp_cipher_ctx_st}’
   EVP_CIPHER_CTX    _ctx;
                     ^~~~
In file included from /usr/local/include/openssl/crypto.h:31:0,
                 from /data/clickhouse_install/off_line_install/ClickHouse/contrib/libpoco/Crypto/include/Poco/Crypto/OpenSSLInitializer.h:26,
                 from /data/clickhouse_install/off_line_install/ClickHouse/contrib/libpoco/Crypto/include/Poco/Crypto/CipherKeyImpl.h:24,
                 from /data/clickhouse_install/off_line_install/ClickHouse/contrib/libpoco/Crypto/include/Poco/Crypto/CipherKey.h:24,
                 from /data/clickhouse_install/off_line_install/ClickHouse/contrib/libpoco/Crypto/include/Poco/Crypto/CipherImpl.h:25,
                 from /data/clickhouse_install/off_line_install/ClickHouse/contrib/libpoco/Crypto/src/CipherImpl.cpp:17:
/usr/local/include/openssl/ossl_typ.h:90:16: note: forward declaration of ‘EVP_CIPHER_CTX {aka struct evp_cipher_ctx_st}’
 typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
                ^~~~~~~~~~~~~~~~~
cc1plus: warning: unrecognized command line option ‘-Wno-for-loop-analysis’
cc1plus: warning: unrecognized command line option ‘-Wno-unused-local-typedef’
cc1plus: warning: unrecognized command line option ‘-Wno-unused-private-field’
make[2]: *** [contrib/libpoco/Crypto/CMakeFiles/PocoCrypto.dir/src/CipherImpl.cpp.o] Error 1
make[1]: *** [contrib/libpoco/Crypto/CMakeFiles/PocoCrypto.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

```

I make Clickhouse is this error.

**Comment by proller** [comment]
fail in debian jessie
with openssl 1.0.1t

**Comment by proller** [comment]
fixed in poco - https://github.com/pocoproject/poco/commit/bfaa161c61cca06526eaf238bfdddd190381616b

**Comment by proller** [comment]
current fastest way - build with poco 1.7.8 manually:
%%
cd                                                                                                 
git clone --recursive --depth 1 --branch poco-1.7.8-release https://github.com/pocoproject/poco.git
cd ~/poco && cmake . && make -j `nproc || sysctl -n hw.ncpu || echo 4`                             
cd ~/ClickHouse/                                                                                   
mkdir build                                                                                        
cd build                                                                                           
cmake .. -DUSE_INTERNAL_POCO_LIBRARY=0 -DPoco_ROOT_DIR=~/poco                                      
make -j `nproc || sysctl -n hw.ncpu || echo 4` clickhouse                                          
%%

**Comment by alexey-milovidov** [comment]
Did the answer has helped you?
