### ISSUE TITLE
MergedRows metrice  lost when query using http post

### ISSUE THREAD

**Issue by simonhou** [yandex/ClickHouse#6341]
Hi, 
I can get rows returned when I run the query   "select event,value from system.events where event = 'MergedRows'  in a clickhosue client. 
```
localhost :)    select event,value from system.events where event = 'MergedRows'

SELECT 
    event, 
    value
FROM system.events 
WHERE event = 'MergedRows'

┌─event──────┬─value─┐
│ MergedRows │     4 │
└────────────┴───────┘
```
However, there is no result returned when this query is executed in postman.
`http://ip:10024/?user=xx&password=xx&query=select event,value from system.events where event = 'MergedRows'`.
What is the reason? Is this a bug of http port accessing?

**Comment by filimonov** [comment]
You need to use url encoding (aka [Percent-encoding](https://en.wikipedia.org/wiki/Percent-encoding)) when sending queries in GET requests

Please try:
```
http://ip:10024/?user=xx&password=xx&query=select%20event%2Cvalue%20from%20system.events%20where%20event%20%3D%20%27MergedRows%27
```

**Comment by simonhou** [comment]
@filimonov Thanks for your replying. I've tried as what you supported. There is still no matching data returned. The CH version is 19.6.2.1 .  I download the rpm package form https://packagecloud.io/Altinity/clickhouse.

**Comment by den-crane** [comment]
CH uses 3 tcp ports

8123 -- http
9000 -- tcp
9009 -- http replication

make sure that ip:10024 --> 8123 -- http
```
curl 'localhost:8123/?query=select%20event,value%20from%20system.events%20where%20event%3D%27MergedRows%27format%20TSV'
MergedRows	933405
```

**Comment by simonhou** [comment]
@den-crane  This is the configuration of http port.
```
[root@~]# cat /etc/ck9024/config.xml | grep http
    <http_port>10024</http_port>
```
Besides, I can get results using select * from system.events. Are some events removed in 19.6.2?

**Comment by den-crane** [comment]
Check something simple

curl 'localhost:8123/'
Ok.

curl 'localhost:8123/?query=select%201'
1

**Comment by alexey-milovidov** [comment]
> Are some events removed in 19.6.2?

No, `MergedRows` metric is in place.

Example from version 19.11.3.11:
```
:) SELECT * FROM system.events WHERE event = 'MergedRows'

SELECT *
FROM system.events
WHERE event = 'MergedRows'

┌─event──────┬───────value─┬─description───────────────────────────────────────────────────────────────┐
│ MergedRows │ 60298127897 │ Rows read for background merges. This is the number of rows before merge. │
└────────────┴─────────────┴───────────────────────────────────────────────────────────────────────────┘
```
