### ISSUE TITLE
Error resolving qualified table names after the JOIN keyword

### ISSUE THREAD

**Issue by tobia** [yandex/ClickHouse#635]
Example data:
```sql
:) create database test
:) create table test.tab (n UInt8) engine=TinyLog
:) insert into test.tab values (1)
```
If I use a qualified name after `join`, I get an error:
```sql
:) select * from test.tab all inner join test.tab using n

Received exception from server:
Code: 60. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: 
Table default.test.tab doesn't exist.
```
If I set the current database and use an unqualified name, it works as expected:
```sql
:) use test
:) select * from tab all inner join tab using n
┌─n─┐
│ 1 │
└───┘
```
If I use a subquery it works as well:
```sql
:) select * from test.tab all inner join (select * from test.tab) using n
┌─n─┐
│ 1 │
└───┘
```

**Comment by ishirav** [comment]
+1
This is a bug that should be fixed IMO. It was reported also in the infi.clickhouse_orm project - see **https://github.com/Infinidat/infi.clickhouse_orm/issues/37**

**Comment by jazzido** [comment]
I'm seeing a probably related error on a much simpler query:

```sql
SELECT foo.column FROM foo
```

Allowing fully-qualified column names would be great for compatibility with tools that generate SQL.

**Comment by alexey-milovidov** [comment]
Fully qualified names are on the way.

**Comment by jazzido** [comment]
Great! That would probably be enough for our attempt of using Clickhouse with Mondrian.

**Comment by alexey-milovidov** [comment]
We have implemented qualified names in early, minimal way:

https://github.com/yandex/ClickHouse/pull/890/commits/f6be68771723c8676fd8ca7970538abdf2f09327#diff-1613521a0e28c68b97ff10ba032993eb

**Comment by sanjayraja** [comment]
Any idea when this would be available ?
We are also trying to use Clickhouse with Mondrian - but the generated SQL uses joins with alias which is not supported in Clickhouse

**Comment by alexey-milovidov** [comment]
We have supported aliases and qualified names for both sides of JOIN; JOIN ... ON clause and correct behaviour of asterisks.

Please reopen if you have another issues.
