### ISSUE TITLE
Using runningDifference() and quantilesExactWeighted() correctly on time series data

### ISSUE THREAD

**Issue by oflasch** [yandex/ClickHouse#6353]
We need to calculate exact value quantiles on large non-uniformly sampled time series data. The schema is (String sensor_path, DateTime timestamp, Float64 value). 

It would be perfect if we could use something like „SELECT quantilesExactWeighted(...)(value, delta)...“,
where „delta“ is the result of „runningDifference(timestamp)“. 
Unfortunately, this does not work, because for each row, delta is the time difference between the previous and the current row instead of the time difference between the current and the next row, as needed for the weights parameter of quantilesExactWeighted(). 

Self-joining the time series to shift delta forward one row will probably not work when the time series does not fit into memory, right?

Is there maybe another, more efficient solution?

I’d be glad to try to submit a patch with a new variant of runningDifference() if there is no other solution. 

Many thanks for your excellent work on ClickHouse!

**Comment by zombiemonkey** [comment]
You can use arrays to get a series per key, sort by timestamp then calculate pretty much anything on the series. Performance on array vectors is certainly not the same as column vectors however if you consider the fact you have to sort to get things in order you end up with performance that roughly matches the new optimize order by primary key functionality. GROUP BY can also spill to disk which can help the memory issue.

Example assuming positive values only - generate 1000 individual series and some metrics

```
DROP TABLE IF EXISTS timeseries;

CREATE TABLE timeseries
ENGINE = MergeTree
PARTITION BY toStartOfDay(ts)
ORDER BY (key, ts) AS
SELECT 
    concat('device-', toString(number % 1000)) AS key, 
    toDateTime('2019-01-01 00:00:00') + toIntervalSecond(rand(number) % 1000) AS ts, 
    any(rand(number + 100000)) AS value
FROM numbers(1000000)
GROUP BY key, ts;
```

Calculate the delta and convert back to column

```
select
    key,
    quantilesExactWeighted(0.5)(_value, _delta) AS q
from (
    with
        arrayMap(i -> (_s[i].1, _s[i].2, abs(_s[i+1].2 - _s[i].2)), arrayEnumerate(arraySort(x -> x.1, groupArray((ts, value))) AS _s)) AS _d
    select
        key,
        (arrayJoin(_d) AS series).1 AS _ts,
        series.2 AS _value,
        series.3 AS _delta
    from 
        timeseries
    group by key
) group by key
```

Calculate the delta and use -Array combiner on the array without conversion.

```
select
    key,
    quantilesExactWeightedArray(0.5)(_d.2, _d.3) AS q
from (
    select
        key,
        arrayMap(i -> (_s[i].1, _s[i].2, abs(_s[i+1].2 - _s[i].2)), arrayEnumerate(arraySort(x -> x.1, groupArray((ts, value))) AS _s)) AS _d
    from timeseries
    group by key
) group by key
```

**Comment by oflasch** [comment]
Many thanks for the detailed solution, looks very good. 
It did not know about the effect of GROUP BY on memory usage. 
Neat optimization. 

Your observation that the series must be sorted anyway brought another possible solution to mind that I wanted to document for others perhaps facing the same task:
We can simply sort the series by timestamp in descending order before calculating runningDifference(), then apply abs() to the resulting negative deltas, which should give the desired “forward_delta”:

‘’’
SELECT 
    *, 
    abs(runningDifference(q)) AS forward_delta
FROM 
(
    SELECT 
        number AS n, 
        n * n AS q
    FROM numbers(15)
    ORDER BY n DESC
)
ORDER BY n ASC

┌──n─┬───q─┬─forward_delta─┐
│  0 │   0 │             1 │
│  1 │   1 │             3 │
│  2 │   4 │             5 │
│  3 │   9 │             7 │
│  4 │  16 │             9 │
│  5 │  25 │            11 │
│  6 │  36 │            13 │
│  7 │  49 │            15 │
│  8 │  64 │            17 │
│  9 │  81 │            19 │
│ 10 │ 100 │            21 │
│ 11 │ 121 │            23 │
│ 12 │ 144 │            25 │
│ 13 │ 169 │            27 │
│ 14 │ 196 │             0 │
└────┴─────┴───────────────┘
‘’’
