### ISSUE TITLE
Can ClickHouse cache recent data in memory not disk?

### ISSUE THREAD

**Issue by achimbab** [yandex/ClickHouse#6359]
I am using ClickHouse with servers having very large memory capacities.

Can I set ClickHouse to store latest one month data in the main memory?

Thank you.

**Comment by sundy-li** [comment]
Maybe the Block TTL feature for Storage Memory could help you.

If it's really useful, I will make a simple PR.

```
ubuntu-172.21.214.52 :)  CREATE TABLE default.testa (`number` UInt64) ENGINE = Memory() settings memory_max_data_lifetime = 3;

CREATE TABLE default.testa
(
    `number` UInt64
)
ENGINE = Memory()
SETTINGS memory_max_data_lifetime = 3

Ok.

0 rows in set. Elapsed: 0.002 sec.

ubuntu-172.21.214.52 :) insert into default.testa select * from numbers(10000);

INSERT INTO default.testa SELECT *
FROM numbers(10000)

Ok.

0 rows in set. Elapsed: 0.002 sec. Processed 10.00 thousand rows, 80.00 KB (4.06 million rows/s., 32.49 MB/s.)

ubuntu-172.21.214.52 :) select sleep(3)

SELECT sleep(3)

┌─sleep(3)─┐
│        0 │
└──────────┘

1 rows in set. Elapsed: 3.002 sec.

ubuntu-172.21.214.52 :) select count() from default.testa;

SELECT count()
FROM default.testa

┌─count()─┐
│   10000 │
└─────────┘

1 rows in set. Elapsed: 0.002 sec. Processed 10.00 thousand rows, 80.00 KB (4.02 million rows/s., 32.14 MB/s.)

ubuntu-172.21.214.52 :) insert into default.testa select * from numbers(30);

INSERT INTO default.testa SELECT *
FROM numbers(30)

Ok.

0 rows in set. Elapsed: 0.002 sec.

ubuntu-172.21.214.52 :) select count() from default.testa;

SELECT count()
FROM default.testa

┌─count()─┐
│      30 │
└─────────┘

1 rows in set. Elapsed: 0.002 sec.

```

**Comment by alexey-milovidov** [comment]
@sundy-li Looks like a very interesting feature! I appreciate if you'll make a PR.

**Comment by alexey-milovidov** [comment]
Multi-volumes (in development) feature will help: https://github.com/yandex/ClickHouse/pull/6489
You will be able to create a volume for fresh data in tmpfs.

**Comment by alexey-milovidov** [comment]
> Can I set ClickHouse to store latest one month data in the main memory?

Right now it isn't possible out of the box.

Some ugly solutions exist. You can move some data parts to tmps and symlink them from their usual place. Also you can force some data files to be cached in memory using `vmtouch` tool. Nevertheless, if some data is used by queries, it will be automatically cached (in page cache) by OS.

**Comment by sergiuhlihor** [comment]
Is there any plan to address caching issue in the future with an out of the box solution like all other major databases? Relying on OS for page cache works many times but is not a reliable solution, specially for non dedicated servers.

**Comment by haiertashu** [comment]
hi @alexey-milovidov 
`if some data is used by queries, it will be automatically cached (in page cache) by OS.`
Is this means ch use BIO to read and write data? and why not DIO?
