### ISSUE TITLE
system.metric_log table

### ISSUE THREAD

**Issue by alexey-milovidov** [yandex/ClickHouse#6363]
If this system table is enabled in configuration, launch a thread that will wakeup with specified period (once a second by default) and insert a row with current values of ProfileEvents, CurrentMetrics and AsynchronousMetrics to SystemLog.

Try to align wakeup time to every period of wall clock time (to avoid time drift due to time spend in this thread). Time points can be lost if the system is overloaded.

It should allow to specify period less than a second. You can use milliseconds for period to avoid floating point values. (Note that microseconds are non-practical.)

The table will have the following columns:

event_date Date
event_time DateTime
milliseconds UInt32 -- useful for the case when period is less than a second

ProfileEvent_* UInt64 -- a column for every ProfileEvent
CurrentMetric_* Int64 -- a column for every CurrentMetrics
AsynchronousMetrics_* Float64 -- a column for every AsynchronousMetrics. Note that values will repeat for many consecutive rows.

The table will have huge number of columns - that's Ok.

**Comment by alexey-milovidov** [comment]
We have decided to remove AsynchronousMetrics from metric_log.

**Comment by alexey-milovidov** [comment]
I forgot that ProfileEvents must be differentiated (the same as in GraphiteSender)

**Comment by alexey-milovidov** [comment]
BTW, your implementation is totally and absolutely wrong.
It calculates metrics on flush time instead to do it each second.

**Comment by alexey-milovidov** [comment]
And you use UInt64 for CurrentMetrics - this is also wrong.

**Comment by nikitamikhaylov** [comment]
Ok. And I think we should create Block objects every second and somehow flush them. Sorry for UInt, It is just copypaste. Сolumns for current metrics are created with the correct type

**Comment by alexey-milovidov** [comment]
Ok, I'm fixing it right now...
