### ISSUE TITLE
Accessing the JSON String from inside an Kafka Engine

### ISSUE THREAD

**Issue by amchakra789** [yandex/ClickHouse#6368]
I have a table of Engine=Kafka(), and the kafka_format = 'JSONEachRow'. Is there a way to access the JSON String from inside the table definition:

create table kafka_ingest (
 jsonString  String, (This is the JSON value that we are trying to ingest)
 jsonField1 String,
jsonField2 UInt64
) Engine=kafka()
Settings kafka_broker_list = '......' , kafka_format='JSONEachRow'

Thanks a lot for your help

**Comment by millin** [comment]
I'm not sure that is, but you can try to use another kafka_format, eg TSV if there no tabs in data,  and extract fields using JSON functions.

```
create table kafka_ingest (
jsonString String,
jsonField1 String DEFAULT JSONExtractString(jsonString, 'field1'),
jsonField2 UInt64 DEFAULT JSONExtractUInt(jsonString, 'field2')
) Engine=kafka()
Settings kafka_broker_list = '......' , kafka_format='TSV'
```

**Comment by amchakra789** [comment]
Thank you so much, appreciate much your help. I will try and update this thread.

**Comment by StephenSorriaux** [comment]
Hi,

If somebody wants to do the same thing, suggestion from @millin works pretty well, just need to also add the `kafka_row_delimiter='\n'` parameter:
```
create table kafka_ingest (
jsonString String,
jsonField1 String DEFAULT JSONExtractString(jsonString, 'field1'),
jsonField2 UInt64 DEFAULT JSONExtractUInt(jsonString, 'field2')
) Engine=kafka()
Settings kafka_broker_list = '......' , kafka_format='TSV', kafka_row_delimiter='\n'
```

**Comment by HungUnicorn** [comment]
@StephenSorriaux hi, I use the same Settings but saw the following error. 
`DB::Exception: Cannot parse input: expected \t at end of stream.: (at row 1)`
have you seen it?
