### ISSUE TITLE
FixedString queries do not work as expected

### ISSUE THREAD

**Issue by El-76** [yandex/ClickHouse#637]
Greetings!

I have the following problem:

There is a table defined as something like:

CREATE TABLE stat.actions ( action_date Date DEFAULT toDate(action_time),  action_time DateTime, action_id UInt32,  w_id UInt32, country FixedString(2) ) ENGINE = CollapsingMergeTree(action_date, (w_id, action_id, action_time), 8192, sign)

When I query the table filtering by country FixedString(2) field I am getting very strange results like:

:) select country, count() from actions where action_date = toDate('2017-03-27') and country = 'RU' group by country;

SELECT
    country,
    count()
FROM actions
WHERE (action_date = toDate('2017-03-27')) AND (country = 'RU')
GROUP BY country

┌─country─┬─count()─┐
│ \0\0    │    2309 │
│ DZ      │      10 │
│ ME      │      13 │
│ MD      │     278 │
│ AP      │       2 │
│ JO      │      30 │
│ AR      │      37 │
│ BW      │      17 │
│ LB      │       3 │
...
│ HK      │      20 │
└─────────┴─────────┘

108 rows in set. Elapsed: 0.007 sec. Processed XXX thousand rows, YYY MB (ZZ million rows/s., WWW MB/s.)

We have 2 configurations - distributed and single-host and the issue reproduces for both configurations.

I also tried toString(...), toStringCutToZero(...), toFixedString(...) to build WHERE clause - the result is the same.

It also reproduces for similar table using MergeTree engine.

Note the actual tables are much more complex,

It looks like I am doing something deeply wrong since the issue is quite fundamental, could you please point me to my mistake.

ClickHouse version is: 1.1.54188

**Comment by alexey-milovidov** [comment]
Please update to latest version: 1.1.54190.

**Comment by El-76** [comment]
OMFG, it works! Thank you for so prompt answer!
