### ISSUE TITLE
Option to increase concurrency on MergeTreeDataPart removal during Cleanup.

### ISSUE THREAD

**Issue by JTCunning** [yandex/ClickHouse#6372]
Hello ClickHouse maintainers, I'm James and I am the person responsible for administrating our cluster at Sentry. We love what you've built at Yandex, so much that we [replaced our Postgres infrastructure with it](https://blog.sentry.io/2019/05/16/introducing-snuba-sentrys-new-search-infrastructure) and now use ClickHouse as [our primary search and storage system](https://blog.sentry.io/2019/07/25/field-guide-mitigating-risk-transitioning-databases). I'd like to pose a feature that will allow us to write to our production cluster at greater frequency while also enabling us to increase our column count.

In our current production cluster, write frequency is bound by the single-threaded cleanup of obsolete parts. This is due to the amount of files (from both column count and `Nullable` types) that need to be `unlink`ed for each part. If we increase our write frequency, the single thread cannot keep up with the amount of parts to remove, and the replica(s) will eventually refuse writes (as they should).

If this process was multi-threaded, we would be able to increase our write frequency and our column count. The disks we currently use are Google Compute Environment SSD Persistent Disks, which allow concurrent syscalls like `unlink`.

Either an option to enable/disable concurrent cleanup, or a count of threads to submit to the `BackgroundSchedulePool` would be sufficient for us. Anything that could give us the concurrency that our disks support would be gratefully appreciated.

**Comment by filimonov** [comment]
Great to hear that Sentry is using ClickHouse now :) (sidenote: i've used Sentry for some petproject some time ago and it's great). 

Can I ask how many inserts per second per server do you have? What is insert batch duże? Did you consider increasing insert batch size instead of increasing number of inserts? (usually it's much better option for ClickHouse) How did you find that unlinking is a bottleneck? 

I'm asking because usually on high insert rate background merges process is bottleneck, not unlinking. By default CH removes unneeded parts not immideately, but after some time interval (configured, and set to 7.5 min by default AFAIR).

**Comment by JTCunning** [comment]
Sure! Here is our breakdown:
Main cluster is 3 shards with 3 replicas.
Inserts are roughly once a second in order to reduce latency in actions triggered off of individual rows that mean conditions ([alerts with time intervals](https://docs.sentry.io/workflow/notifications/alerts/).
We have considered increasing batch size, but that ultimately increases our latency in between receiving an event and being able to trigger an alert off of it.
The `unlink` syscall is ultimately our bottleneck because of the direct io it performs. Our background merges are not a bottleneck because we can properly utilize page cache.

Increasing the batch size doesn't really aid our issue.
For example, if it takes roughly 500ms to `unlink` all of our column files (~320 .bin and .mark combined) and we write at 250ms intervals, CH could not sustain removing unneeded parts if they are all deleted in serial.

We found that the deleting of obsoleted parts was the bottleneck by watching CH only schedule a single thread per-table to do the removal. We continued to write at a faster rate than it could delete, and queried for non-active parts using the system table. While the maximum active parts per partition never rose over 20, the count of inactive parts continued to sawtooth upwards.

I'll try and find a graph from our system to better illustrate the issue.

**Comment by alexey-milovidov** [comment]
How does it relate to the mounting options of the filesystem? I mean noatime, nodiratime, nobarrier, writeback...

**Comment by alexey-milovidov** [comment]
Parallel files removal is not a hard thing to do...

PS. Do you use enough recent version? (recently we have made a small optimization in this place):
https://github.com/yandex/ClickHouse/blob/master/CHANGELOG.md#performance-improvement-1

**Comment by JTCunning** [comment]
@alexey-milovidov: All four of the specified mounting options are already in place. If I had to make a guess, the latency comes from GCP's Persistent Disk itself. The block storage system is able to record high marks on write iops by making concurrent calls. A single-threaded application can commit upwards to 2k write ops, but can achieve 25/30k by utilizing all vCPUs.

Once the changelog was shipped for 19.10/11, I did perform an upgrade to see if https://github.com/yandex/ClickHouse/pull/5648 would reduce the bottleneck. It removed the entirety of the `stat` calls from directory cleanup, but we only saw a 5% improvement because of how fast those calls return on normal block storages.

Here is a sample `strace` count when following the cleanup thread.
Note: I could not time this properly for the entire thread execution since it is part of a pool. It's just a sample portion.
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 99.76    1.773754         111     15975           unlink
  0.20    0.003536          71        50           rmdir
  0.02    0.000383           8        50        50 stat
  0.02    0.000299           6        50           rename
------ ----------- ----------- --------- --------- ----------------
100.00    1.777972                 16125        50 total
```

**Comment by JTCunning** [comment]
@filimonov: Here is an illustration of my description.

In this graph, we're recording `SELECT count() AS parts FROM system.parts WHERE not active;`.
I've doubled our frequency of writing at 9:18. The number of inactive parts climbs because we wait for that 7.5min inactivity marker you described, and then we start to clean them up. As you can see, the graph begins to saw-tooth since the single cleanup thread cannot sustain the volume of obsoleted parts.
An important distinction we have here is that we have set `cleanup_delay_period` to 1 so that we do not wait 30s to wake the thread up. We have done this because it leads to more consistent IO and less time spent not cleaning up obsoleted parts.
<img width="1340" alt="Screenshot 2019-08-11 09 41 03" src="https://user-images.githubusercontent.com/1189446/62836874-c911bd80-bc1c-11e9-9e7e-6cd52995a819.png">

Additionally, here is a graph during the same time of the `max_part_count_for_partition` metric to illustrate that merging low-level parts is not the bottleneck.
<img width="1347" alt="Screenshot 2019-08-11 09 41 52" src="https://user-images.githubusercontent.com/1189446/62836887-1f7efc00-bc1d-11e9-99ad-8eaeeaf0eb7d.png">

**Comment by alexey-milovidov** [comment]
BTW, one our customer has exactly the opposite experience:
- when we removing data files, there is too high IO load, and they propose something to gradually truncate files before removal.

**Comment by alexey-milovidov** [comment]
I've made a change for you. But now you have to test it and report the results.

Download a package here:
https://clickhouse-builds.s3.yandex.net/6438/28e0e64638b2487282bb0f5de85ee530dc1e55c0/report.html

(from top row - gcc9, relwithdebuginfo)

**Comment by JTCunning** [comment]
That was extremely quick, thank you.

Since this is our current production cluster on the latest version in changelog (19.11.5.28), I'll figure out how we can test this with minimal risk ad report back.

**Comment by JTCunning** [comment]
From my initial testing on a single machine we use for access logs, this seems to be working great. I can see multiple threads in the `BackgrProcPool` pinning IO in iotop. The ioutil graph is pinned at 100% and the iowait graph is going higher than a single core's percentage.

More importantly, the obsoleted parts are not sawtoothing, and the single server is keeping up in background merges.

I'd be hesitant to apply this patch to our production cluster since we'd be upgrading without any other testing, but this individual change is looking very successful from my point of view.

**Comment by alexey-milovidov** [comment]
That's great! Please keep in touch.
