### ISSUE TITLE
left/right/substring from mysql table reports error

### ISSUE THREAD

**Issue by RangerWolf** [yandex/ClickHouse#6381]
**Describe the bug**
Could not use `left` or `right` or `substring` when selecting data from mysql directly

**How to reproduce**
* Version: 19.11.2
* SQL that could run with error
```SQL
-- Exception msg for below sql : 
-- Code: 1000. DB::Exception: Received from clickhouse-server:9000. DB::Exception: mysqlxx::BadQuery: Operand should contain 1 column(s)
select 
            `id`
from mysql('host:port', 'database', 'tablename', 'username', 'password')
where 1=1 and left(stat_datetime, 10)='2019-08-07'  and advertiser_id = '12345'
```
* SQL that runs OK
```SQL
select 
	`id`
from mysql('host:port', 'database', 'tablename', 'username', 'password')
where 1=1 and advertiser_id = '12345'
```

**Expected behavior**
Both SQL should run OK

**Comment by alexey-milovidov** [comment]
@dimarub2000 Please try to reproduce this issue.

**Comment by dimarub2000** [comment]
Reproduced the issue, trying to find the problem.
when `select * from mysql('localhost:3306', 'test', 'kek', 'dsrub', 'kek') where id=123 and 1=1;`
mysql gets `SELECT `s`, `id` FROM `test`.`kek` WHERE (`id` = 123) AND (1 = 1)`

when `select * from mysql('localhost:3306', 'test', 'kek', 'dsrub', 'kek') where left(s, 2) = 'ke'`
mysql gets `SELECT `s`, `id` FROM `test`.`kek``

when `select * from mysql('localhost:3306', 'test', 'kek', 'dsrub', 'kek') where left(s, 2) = 'ke' and id=123 and 1=1;`
mysql gets `SELECT `s`, `id` FROM `test`.`kek` WHERE (`id` = 123, 1 = 1)`
