### ISSUE TITLE
DROP PARTITION BY DAY

### ISSUE THREAD

**Issue by qietingfengling** [yandex/ClickHouse#6383]
how to drop partition by day .

**Comment by den-crane** [comment]
First of all your table should be partitioned by day. And the answer depends of your partitioning expression PARTITION BY toYYYYMMDD(date) / PARTITION BY date.

Also check TTL https://clickhouse.yandex/docs/en/operations/table_engines/mergetree/#table_engine-mergetree-ttl

**Comment by qietingfengling** [comment]
thanks ,I will try it

**Comment by 631068264** [comment]
How to change partition @den-crane
