### ISSUE TITLE
Infinite loop of restarting due to OutOfMemoryError (I guess)

### ISSUE THREAD

**Issue by Chocorean** [yandex/ClickHouse#6393]
I have no reproducible example so I ask this as an open question. I have around a billion rows in my db, and, I don't know what I did but I suspect the device rebooted while clickhouse has working on merge parts or whatever.
What I'm currently experiencing is clickhouse crashes on loading (out of memory according to `top` and logs). No error is raised (`clickhouse-server.err.log` is empty).
I attach the `clickhouse-server.log` for a complete start-to-crash scenario.

I have no idea what to do to get rid of this except removing all my data and inserting it again. What do you think of this ?

[clickhouse-server.log](https://github.com/yandex/ClickHouse/files/3480407/clickhouse-server.log)

EDIT: I remember I was trying a script about de-deplucating my data, so a lot of DELETEs and UPDATEs were performed. Can this be the cause ?

**Comment by akuzm** [comment]
What does `dmesg` say, is oom killer invoked?

**Comment by Chocorean** [comment]
It looks like it does kill clickhouse-server. There is a short extract from `dmesg` output:
```
[ 5683.514206] Out of memory: Kill process 1887 (clickhouse-serv) score 979 or sacrifice child
[ 5683.514305] Killed process 1887 (clickhouse-serv) total-vm:22897712kB, anon-rss:16065748kB, file-rss:0kB, shmem-rss:0kB
[ 5684.381747] oom_reaper: reaped process 1887 (clickhouse-serv), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

**Comment by akuzm** [comment]
It's strange that the log is almost empty, let's set `logger.level = "trace"` so that we have more messages (https://clickhouse.yandex/docs/en/operations/server_settings/settings/#server_settings-logger).

Does it run long enough so that you connect with clickhouse-client? What's in `system.merges`? I've recently seen a problem where there was a very big array field in the table, and it required about 30GB of memory to complete the merge. They had to migrate to a larger instance so that the merge could complete.

**Comment by Chocorean** [comment]
`clickhouse-client --query "select * from system.merges"`
```
default	credential	1.143259521	0	1	['20190729_28016_791975_4_821925']	20190729_28016_791975_4_1231304	20190729	1	11172356	86	0	0	0	0	0	567393504	12
default	credential	0.952820128	0	1	['20190805_813035_823186_4_872908']	20190805_813035_823186_4_1231304	20190805	1	4695788	38	0	0	0	0	0	508029824	13
default	credential	0.779207283	0	1	['20190805_896161_900069_3_934048']	20190805_896161_900069_3_1231304	20190805	1	12864515	98	0	0	0	0	0	398894304	14
default	credential	0.599287864	0	1	['20190805_900218_905745_4_930396']	20190805_900218_905745_4_1231304	20190805	1	21272275	160	0	0	0	0	0	289415200	16
default	credential	0.252530037	0	1	['20190805_905838_917049_3_935883']	20190805_905838_917049_3_1231304	20190805	1	25443008	217	0	0	0	0	0	92279008	20```

The logger level is already to `trace` btw...
Is there any chance I can deal with this without migrating to a larger instance ? Or should I just erase everything ?

**Comment by den-crane** [comment]
You can cancel mutations by kill mutation or manually.
You can reduce background_pool_size / background_schedule_pool_size -- number of simultaneously running tasks.

**Comment by Chocorean** [comment]
Thanks a lot. Clickhouse is running again, I reduced the pool size.
