### ISSUE TITLE
Kafka extra messages after server restart

### ISSUE THREAD

**Issue by filimonov** [yandex/ClickHouse#6414]
After clickhouse server restarted some messages get duplicated.

See https://github.com/yandex/ClickHouse/pull/6365/commits/76b48a03a079e3619d360653861db5caa9c761e4

**Comment by abyss7** [comment]
The reason is about new processors code - the `ReadSuffix()` method is now called less frequently than it was, causing Kafka commits to occur only when a message stream is "dried up".

**Comment by abyss7** [comment]
Should be fixed in 19.14+
