### ISSUE TITLE
Regular expressions in function Clickhouse

### ISSUE THREAD

**Issue by Alexey-Chegodaykin** [yandex/ClickHouse#6434]
Hello. study ClickHouse. I am interested in the syntax of regular expressions. For example, I need to find string that contain character '2' followed by '3' or '4'. Has tried: '\2[3-4]' not particularly helps. Maybe someone can help, thank you.

**Comment by den-crane** [comment]
```

select x, match(x, '2[3-4]') as match from (select arrayJoin(['12345', '224', '125432']) x)

┌─x──────┬─match─┐
│ 12345  │     1 │
│ 224    │     1 │
│ 125432 │     0 │
└────────┴───────┘
```

**Comment by alexey-milovidov** [comment]
We use re2 syntax that is limited version of PCRE:
https://clickhouse.yandex/docs/en/query_language/functions/string_search_functions/#match-haystack-pattern
