### ISSUE TITLE
PCRE

### ISSUE THREAD

**Issue by Jim-Raynor** [yandex/ClickHouse#644]
Планируется ли добавление поддержки PCRE? Не по-умолчанию, а чтобы можно было собрать сервер с указанием определённого флага, который включал бы полноценные регулярки.

**Comment by alexey-milovidov** [comment]
С PCRE слишком легко создать регексп, который будет выполняться очень долго или даже уронит сервер. Хотя мы могли бы добавить поддержку PCRE, даже во все сборки по-умолчанию, но включаемую отдельной опцией в конфиге или настройкой для пользователя.

В коде уже присутсвует PCRE (внутри Poco). Хотя если добавлять такие функции, то лучше было бы добавить также и PCRE JIT.

В связи с тем, что у нас сейчас в этом нет потребности, мы вряд ли это добавим самостоятельно.
Но вы можете сделать сами, по аналогии с использованием re2. Функции назвать немного по-другому - PCREMatch, вместо match и т. п.

**Comment by Jim-Raynor** [comment]
Спасибо за ответ)
