### ISSUE TITLE
How to make replica write only?

### ISSUE THREAD

**Issue by astudnev** [yandex/ClickHouse#6488]
If i have cluster of servers with replicated tables and do not want that clients can modify any data in replicas? How to configure that?

**Comment by alex-zaitsev** [comment]
Use readonly profile.

**Comment by astudnev** [comment]
What you mean profile? It is about just a table, not user... or tables have profiles?

**Comment by alex-zaitsev** [comment]
There is no way to make a single table readonly in current ClickHouse. Flexible RBAC should be available later this year (Q4).

**Comment by astudnev** [comment]
Problem is NOT in user access. The problem is that clickhouse nodes read data for replication from arbitrary remote nodes, and sometimes it breaks the original table. I want to prevent master node to read anything from untrusted nodes. This is not user level security, it is security of server

**Comment by alex-zaitsev** [comment]
There is no master node in ClickHouse. I do not understand what you are talking about. Replication consistency is controlled by ZooKeeper, that also checks checksums and so on.

**Comment by astudnev** [comment]
At least 2 use cases for this:

1) i do update of clickhouse software for one of server and i do not want that at any circumstance the new software can corrupt database. So i would configure the updated servers as read only. I already met with the situation when updating a server corrupted a table on existing table: https://github.com/yandex/ClickHouse/issues/6472

2) i give the server to a client to use and no modifications to this server should not corrupt database

I think there are more than that. The repication as complete P2P in clickhose only good in a completely treusted "enterprise" environment, where everything is under control. However, this is not the case in many situations

**Comment by astudnev** [comment]
The name is confusing. This is not read-only this is write-only

**Comment by alex-zaitsev** [comment]
What you describe is non-sense. If you stop the replica, your system becomes inconsistent.

**Comment by astudnev** [comment]
I need to configure replica, that is used only for reading. It is not expected that anybody will write in it. This limitation will remove the risk of corrupting the main database.
Some analogue of master-slave in MySQL

**Comment by astudnev** [comment]
https://github.com/yandex/ClickHouse/issues/6506

**Comment by filimonov** [comment]
Let's continue in #6506 to avoid duplicates.
