### ISSUE TITLE
Error when using splitByChar with cannot be inside Nullable type

### ISSUE THREAD

**Issue by HuchGit** [yandex/ClickHouse#6517]
when I try do perform an  splitByChar with an nullable array I receive the following exception:
### Code: 43, e.displayText() = DB::Exception: Nested type Array(String) cannot be inside Nullable type (version 19.5.5.1)
query:
SELECT splitByChar('=',url)[1]
FROM client_log
WHERE  datetime > '2019-08-15 21:00:00'
  AND datetime < '2019-08-15 21:05:00'
  AND resource_type = 'VIDEO'
  AND  isNotNull(url)
LIMIT 10

Is this a bug or an intended behaviour?

**Comment by 4ertus2** [comment]
I don't think it's a bug. It's easy to remove nullability from column, ex. with ```assumeNotNull(url)``` that should solve your problem. There're also ifNull() and coalesce() functions.
