### ISSUE TITLE
How to downgrade CH version

### ISSUE THREAD

**Issue by MahmoudGoda0** [yandex/ClickHouse#6531]
Hello Team,
I installed ClickHouse using the below commands:
echo "deb http://repo.yandex.ru/clickhouse/deb/stable/ main/" | sudo tee /etc/apt/sources.list.d/clickhouse.list
sudo apt-get update
sudo apt-get install -y clickhouse-server clickhouse-client
Now the current version is "19.13.2.19", but i need to downgrade it to be version "19.13.1.961"
How i can do this ?

Thanks in advance.

**Comment by alexey-milovidov** [comment]
You can specify exact version in `apt-get install`:

```
sudo apt-get install clickhouse-server=19.13.1.11 clickhouse-client=19.13.1.11 clickhouse-common-static=19.13.1.11
```

You can also download packages directly from 
https://repo.yandex.ru/clickhouse/deb/stable/main/
and install them with `sudo dpkg -i`.

**Comment by MahmoudGoda0** [comment]
Thanks alot!
