### ISSUE TITLE
Parts retrieval in ReplicatedMergeTree

### ISSUE THREAD

**Issue by kreuzerkrieg** [yandex/ClickHouse#6532]
It takes a long time. Looks like each part retrieved sequentially. Am I right? Is it any tweak, like configuration to make it faster, like downloading parts in parallel?

**Comment by alexey-milovidov** [comment]
Parts fetching done in parallel with a maximum of "background_pool_size" connections.
Usually it saturates network 100% (at least for 10GBit) and cannot be made any faster.
It may have negative consequences though - sometimes you have to shape replication traffic manually.

**Comment by kreuzerkrieg** [comment]
Good to know and thanks for prompt reply.
Could you please elaborate about manual traffic configuration? Like, why and when?
Thanks!

**Comment by alexey-milovidov** [comment]
If your network is overloaded and you need to save some bandwidth for queries.

**Comment by kreuzerkrieg** [comment]
Oh, I see. Thanks again

**Comment by kreuzerkrieg** [comment]
@alexey-milovidov is there any chance the system starts to back-off in background pool once number of threads starts to increase? with 32 threads parts fetch starts ~5 minutes after server starts, with 64 threads after ~10 minutes. Though I didnt have a chance to debug it properly.
Ideas?

**Comment by alexey-milovidov** [comment]
Do you mean total number of threads in background pool or the number of active threads (that are doing merges or fetches)?

You can check the status of fetching parts (what parts are currently fetched) in `system.replication_queue` table.

**Comment by kreuzerkrieg** [comment]
Pay attention, exactly 10 minutes, from finding last needed part and starting to download

> 2019.08.19 16:55:19.458588 [ 77 ] {} <Warning> default.ontime_replicated (ReplicatedMergeTreePartCheckThread): Checking part 199901_2_2_0
> 2019.08.19 16:55:19.458692 [ 77 ] {} <Warning> default.ontime_replicated (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part covering 199901_2_2_0.
> 2019.08.19 16:55:19.459051 [ 77 ] {} <Warning> default.ontime_replicated (ReplicatedMergeTreePartCheckThread): Found part 199901_2_2_0 on replica-001_shadow that covers the missing part 199901_2_2_0
> 2019.08.19 16:55:21.522247 [ 149 ] {} <Debug> ConfigReloader: Loading config `config.xml'
> Include not found: clickhouse_remote_servers
> Include not found: clickhouse_compression
> 2019.08.19 16:55:22.087121 [ 86 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeCleanupThread): Execution took 2674 ms.
> 2019.08.19 16:55:57.504462 [ 81 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeCleanupThread): Checking 100 blocks (100 are not cached) to clear old ones from ZooKeeper.
> 2019.08.19 16:56:02.480756 [ 82 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeCleanupThread): Execution took 2288 ms.
> 2019.08.19 16:56:19.400322 [ 90 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeRestartingThread): Absolute delay: 30134. Relative delay: 30134.
> 2019.08.19 16:56:19.400364 [ 90 ] {} <Information> default.ontime_replicated (ReplicatedMergeTreeRestartingThread): Relative replica delay (30134 seconds) is bigger than threshold (120). Will yield leadership.
> 2019.08.19 16:56:19.400377 [ 90 ] {} <Information> default.ontime_replicated: Stopped being leader
> 2019.08.19 16:56:19.404218 [ 91 ] {} <Information> default.ontime_replicated: Became leader
> 2019.08.19 16:56:35.671352 [ 99 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeCleanupThread): Checking 100 blocks (100 are not cached) to clear old ones from ZooKeeper.
> 2019.08.19 16:56:35.678053 [ 99 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeCleanupThread): Execution took 2362 ms.
> 2019.08.19 16:57:10.101500 [ 108 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeCleanupThread): Execution took 2434 ms.
> 2019.08.19 16:57:19.405638 [ 111 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeRestartingThread): Absolute delay: 30194. Relative delay: 30194.
> 2019.08.19 16:57:48.483825 [ 120 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeCleanupThread): Execution took 2415 ms.
> 2019.08.19 16:58:19.406237 [ 129 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeRestartingThread): Absolute delay: 30254. Relative delay: 30254.
> 2019.08.19 16:58:20.900708 [ 128 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeCleanupThread): Execution took 2133 ms.
> 2019.08.19 16:59:03.706012 [ 86 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeCleanupThread): Execution took 2847 ms.
> 2019.08.19 16:59:19.406801 [ 80 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeRestartingThread): Absolute delay: 30314. Relative delay: 30314.
> 2019.08.19 16:59:45.561321 [ 70 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeCleanupThread): Execution took 2175 ms.
> 2019.08.19 17:00:19.408060 [ 100 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeRestartingThread): Absolute delay: 30374. Relative delay: 30374.
> 2019.08.19 17:00:19.812254 [ 98 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeCleanupThread): Execution took 2455 ms.
> 2019.08.19 17:00:53.204492 [ 108 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeCleanupThread): Execution took 2289 ms.
> 2019.08.19 17:01:19.408828 [ 116 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeRestartingThread): Absolute delay: 30434. Relative delay: 30434.
> 2019.08.19 17:01:31.170512 [ 120 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeCleanupThread): Execution took 2537 ms.
> 2019.08.19 17:02:04.297888 [ 130 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeCleanupThread): Execution took 2164 ms.
> 2019.08.19 17:02:19.409321 [ 134 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeRestartingThread): Absolute delay: 30494. Relative delay: 30494.
> 2019.08.19 17:02:46.432209 [ 86 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeCleanupThread): Execution took 2569 ms.
> 2019.08.19 17:03:19.409919 [ 84 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeRestartingThread): Absolute delay: 30554. Relative delay: 30554.
> 2019.08.19 17:03:24.655433 [ 89 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeCleanupThread): Execution took 2454 ms.
> 2019.08.19 17:04:01.785871 [ 99 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeCleanupThread): Execution took 2643 ms.
> 2019.08.19 17:04:19.410566 [ 104 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeRestartingThread): Absolute delay: 30614. Relative delay: 30614.
> 2019.08.19 17:04:35.948177 [ 108 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeCleanupThread): Execution took 2140 ms.
> 2019.08.19 17:05:15.120625 [ 121 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeCleanupThread): Execution took 2125 ms.
> 2019.08.19 17:05:19.411169 [ 122 ] {} <Trace> default.ontime_replicated (ReplicatedMergeTreeRestartingThread): Absolute delay: 30674. Relative delay: 30674.
> 2019.08.19 17:05:19.670128 [ 27 ] {} <Debug> default.ontime_replicated: Fetching part 201105_1_1_0 from /foo/tables/ontime_replicated/replicas/replica-001_shadow
> 2019.08.19 17:05:19.670302 [ 27 ] {} <Trace> ReadWriteBufferFromHTTP: Sending request to http://host:9009/?endpoint=DataPartsExchange%3A%2Ffoo%2Ftables%2Fontime_replicated%2Freplicas%2Freplica-001_shadow&part=201105_1_1_0&compress=false
> 2019.08.19 17:05:19.670541 [ 169 ] {} <Trace> InterserverIOHTTPHandler-factory: HTTP Request for InterserverIOHTTPHandler-factory. Method: POST, Address: 172.31.14.178:41422, User-Agent: none, Content Type: , Transfer Encoding: identity
> 2019.08.19 17:05:19.670603 [ 169 ] {} <Trace> InterserverIOHTTPHandler: Request URI: /?endpoint=DataPartsExchange%3A%2Ffoo%2Ftables%2Fontime_replicated%2Freplicas%2Freplica-001_shadow&part=201105_1_1_0&compress=false
> 2019.08.19 17:05:19.670619 [ 169 ] {} <Trace> default.ontime_replicated (Replicated PartsService): Sending part 201105_1_1_0
> 2019.08.19 17:05:19.673996 [ 66 ] {} <Debug> default.ontime_replicated: Fetching part 198908_1_1_0 from /foo/tables/ontime_replicated/replicas/replica-001_shadow
