### ISSUE TITLE
Replace Column Values

### ISSUE THREAD

**Issue by Sundarcj** [yandex/ClickHouse#6535]
each column chunk is stored in a  individual file right?..so is it possible to replace a existing column with a new values

**Comment by filimonov** [comment]
That is happening when you do `ALTER TABLE ... UPDATE colunmname=... WHERE ....`

There is also `ALTER TABLE tablename CLEAR COLUMN colunmname IN PARTITION ... `

**Comment by Sundarcj** [comment]
okay, consider this following scenario.  I need to change all the values in the column.
so  I run a loop
` 
LEN = somemillion or some billion;
for(long i=0;i<LENi++){
connetion.createStatement.execute("alter table sample update columnX = "+_someAlgorithm()+" where row_id="+i");
}`

so how many times the partition deletion will be executed?
is it combines all the query and run single deletion and update with a new value or LEN times?

**Comment by filimonov** [comment]
Actually it combines the value but will still work ineffecient.

Instead you can create a simple key-value dictionary or table with engine=Join and just do `alter table update col1=dictGet..where 1` (or with joinGet in case of table with engine=Join).

**Comment by Sundarcj** [comment]
which one will be efficient dictGet or Join.
i don't have knowledge about dict in CH. Is dictGet can be used in join Engine?

**Comment by filimonov** [comment]
For dictionaries - use one of dictGet... functions. 

For engine=Join - use joinGet. 

Performance is almost the same. Engine=Join is bit more handy (no XML config, easy to fill / maintain). Dictionaries consume more memory.

**Comment by Sundarcj** [comment]
Okay thank u
