### ISSUE TITLE
Feature request: add ability to drop MergeTree table parts by primary key range

### ISSUE THREAD

**Issue by valyala** [yandex/ClickHouse#654]
### The issue

Suppose the following `MergeTree` table exists with rows sorted by `(EventID, EventDate, ClientID)`.

```sql
CREATE TABLE a (
    EventID UInt8,
    EventDate Date,
    ClientID UInt32,
    Payload String
) ENGINE = MergeTree(EventDate, (EventID, EventDate, ClientID), 8192)
```

Currently only monthly parts may be dropped via `ALTER TABLE a DROP PARTITION YYYYMM`. This allows dropping all the old data, but doesn't allow dropping old data for certain unimportant events (for instance, cursor movement events), while preserving old data for important events (for instance, goals completed).

### Possible solution

It would be great if `clickhouse` could drop certain parts of `MergeTree` table based on the primary key range. For instance:

Drop all the data for the event `42`:

```sql
ALTER TABLE a DROP KEY RANGE EventID = 42
```

Drop data for the event `42` that is older than `2017-01-01`.

```sql
ALTER TABLE a DROP KEY RANGE EventID = 42 and EventDate < '2017-01-01'
```

Drop data for the event `42` and client `1234` for the `2017-02-01`:

```sql
ALTER TABLE a DROP KEY RANGE EventID = 42 and EventDate = '2017-02-01' and ClientID = 1234
```

### Thoughts on the implementation

Since rows are sorted by the primary key, `ALTER TABLE ... DROP KEY RANGE` can quickly locate the range over parts which should be dropped. There are the following cases:
1) The range covers the whole part. In this case the part may be just dropped.
2) The range covers either the head or the tail of the part. In this case the part may be substituted by a new part without the rows from key range.
3) The range is located inside the part. In this case the part may be substituted by two new parts - the first one with rows before the range and the second one with rows after the range.

Case 1 is executed in a constant time, while the execution time for the cases 2 and 3 should be proportional to the size of the corresponding part.

### Possible workaround

To create a `Merge` table over multiple tables each containing either important or unimportant events, so unimportant events may be dropped independently of important events.

**Comment by valyala** [comment]
Additionally the following feature could be added to be consistent with `DROP/DETACH PARTITION`, so the detached key range could be archived and/or copied to another place.

```sql
ALTER TABLE ... DETACH KEY RANGE ...
```

**Comment by valyala** [comment]
This feature is orthogonal to the upcoming [ALTER TABLE DROP COLUMN FROM PARTITION](https://github.com/yandex/ClickHouse/pull/622), so the following additional feature could be implemented later:
```sql
ALTER TABLE ... DROP COLUMN ... FROM KEY RANGE ...
```
This would drop column values for the given key range only.

**Comment by blinkov** [comment]
Most of it has been implemented as `ALTER TABLE ... DELETE ...`, see: https://clickhouse.yandex/docs/en/query_language/queries/#mutations
