### ISSUE TITLE
Clickhouse FTBS in Ubuntu Eoan (MySQL 8 + GCC 9)

### ISSUE THREAD

**Issue by rafaeldtinoco** [yandex/ClickHouse#6552]
Reference:
Ubuntu Bug LP: #1840511
https://bugs.launchpad.net/ubuntu/+source/bareos/+bug/1840485/

**Operating system**
Ubuntu Eoan (in development, to be frozen Aug 22)

**Cmake version**
3.13.4

**Ninja version**
1.9.0

**Compiler name and version**

gcc (Ubuntu 9.2.0-1ubuntu1) 9.2.0
and
gcc-8 (Ubuntu 8.3.0-19ubuntu1) 8.3.0

**Full cmake and/or ninja output**

https://launchpadlibrarian.net/429654087/buildlog_ubuntu-eoan-amd64.clickhouse_18.16.1+ds-4build1_BUILDING.txt.gz

----

[ 6%] Building CXX object libs/libmysqlxx/CMakeFiles/mysqlxx.dir/src/Connection.cpp.o
cd /<<BUILDDIR>>/clickhouse-18.16.1+ds/obj-x86_64-linux-gnu/libs/libmysqlxx && /usr/bin/c++ -I/<<BUILDDIR>>/clickhouse-18.16.1+ds/libs/libmysqlxx/include -I/<<BUILDDIR>>/clickhouse-18.16.1+ds/libs/libcommon/include -I/<<BUILDDIR>>/clickhouse-18.16.1+ds/obj-x86_64-linux-gnu/libs/libcommon/include -I/<<BUILDDIR>>/clickhouse-18.16.1+ds/contrib/cityhash102/include -g -O2 -fdebug-prefix-map=/<<BUILDDIR>>/clickhouse-18.16.1+ds=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -pipe -fno-omit-frame-pointer -Wall -Wnon-virtual-dtor -O2 -g -DNDEBUG -O3 -flto -fno-fat-lto-objects -fPIC -std=c++17 -o CMakeFiles/mysqlxx.dir/src/Connection.cpp.o -c /<<BUILDDIR>>/clickhouse-18.16.1+ds/libs/libmysqlxx/src/Connection.cpp
In file included from /<<BUILDDIR>>/clickhouse-18.16.1+ds/libs/libmysqlxx/include/mysqlxx/ResultBase.h:4,
                 from /<<BUILDDIR>>/clickhouse-18.16.1+ds/libs/libmysqlxx/include/mysqlxx/UseQueryResult.h:3,
                 from /<<BUILDDIR>>/clickhouse-18.16.1+ds/libs/libmysqlxx/include/mysqlxx/Query.h:6,
                 from /<<BUILDDIR>>/clickhouse-18.16.1+ds/libs/libmysqlxx/include/mysqlxx/Connection.h:10,
                 from /<<BUILDDIR>>/clickhouse-18.16.1+ds/libs/libmysqlxx/src/Connection.cpp:7:
/<<BUILDDIR>>/clickhouse-18.16.1+ds/libs/libmysqlxx/include/mysqlxx/Types.h:7:23: error: conflicting declaration ‘using MYSQL = struct st_mysql’
 using MYSQL = st_mysql;
                       ^
In file included from /<<BUILDDIR>>/clickhouse-18.16.1+ds/libs/libmysqlxx/src/Connection.cpp:4:
/usr/include/mysql/mysql.h:335:3: note: previous declaration as ‘typedef struct MYSQL MYSQL’
 } MYSQL;

----

We are upgrading MySQL to version 8 in the next Ubuntu (Eoan) and we faced the regression above. C and C++ differ in the form of types being defined. While C++ structs are defined also as new types, in C you have to explicitly typedef the struct to have a new type. 

If I edit file libs/libmysqlxx/include/mysqlxx/Types.h and comment the following lines:

//struct st_mysql;
//using MYSQL = st_mysql;
//
//struct st_mysql_res;
//using MYSQL_RES = st_mysql_res;
//
//using MYSQL_ROW = char**;
//
//struct st_mysql_field;
//using MYSQL_FIELD = st_mysql_field;

and add

#include <mysql/mysql.h>

I solve the issue, as MYSQL, MYSQL_RES, MYSQL_ROW and MYSQL_FIELD types are defined by the mysql.h header file (as C++ would expect). Not sure if this would be the best way to address this, any recommendation ?

----

Note: Unfortunately doing that with gcc-9 was not successful not because of the change, per se, but gcc-9 crashed during clickhouse compilation. When changing gcc-9 to gcc-8 as the default compiler (Ubuntu Eoan userland) I was able to compile clickhouse libmysqlxx library successfully with the mentioned changes.

**Comment by alexey-milovidov** [comment]
> Not sure if this would be the best way to address this, any recommendation?

If it works both for libmysqlclient and libmariadbclient, it's fine.

**Comment by alexey-milovidov** [comment]
You can send a pull request with this change and it will be tested automatically.

**Comment by alexey-milovidov** [comment]
Also you can change
```
using MYSQL = st_mysql;
```

to

```
using MYSQL = struct st_mysql;
```

**Comment by alexey-milovidov** [comment]
We avoid to include `<mysql/mysql.h>` in header files to avoid namespace pollution. Better to include in `.cpp` whenever possible. So, we use forward declarations.

**Comment by rafaeldtinoco** [comment]
Alright, let me propose a merge then. Thx for the advices.

**Comment by rafaeldtinoco** [comment]
Im testing our Ubuntu Builds and will propose a patch tomorrow (basically a #ifndef _mysql_h before the declarations, seem to have worked pretty well with minimum changes).

**Comment by rafaeldtinoco** [comment]
https://github.com/yandex/ClickHouse/pull/6569

**Comment by rafaeldtinoco** [comment]
Pull request made! Thx for reviewing this.

**Comment by rafaeldtinoco** [comment]
GCC 9 issue is being tracked here:

https://github.com/yandex/ClickHouse/issues/6560

Closing this since the patch was merged.

Thx a lot for considering the fix.
