### ISSUE TITLE
OPTIMIZE is not cancelled immediately

### ISSUE THREAD

**Issue by vmarkovtsev** [yandex/ClickHouse#6572]
[After finding out how to generate secondary indexes](https://github.com/yandex/ClickHouse/issues/6561), I ran

```
OPTIMIZE TABLE xxx FINAL;
```

and went to drink tea. However, when I checked the command status in a few minutes, I saw

```
Timeout exceeded while receiving data from server. Waited for 300 seconds, timeout is 300 seconds.
Cancelling query.
```

The command did not return control back. I waited ~10 minutes and then Ctrl-C it. The server continued to consume 100% CPU for 6 hours, apparently materializing all the indexes. In the end, it deleted them - because the command was canceled due to the timeout! It was a big failure.

So OPTIMIZE was not canceled at once, and I consider this a bug: it makes no sense to heat the air in a server room for 6 hours.

P.S.
I used `--max_execution_time $MANY_SECONDS --http_receive_timeout $MANY_SECONDS --receive_timeout $MANY_SECONDS --idle_connection_timeout $MANY_SECONDS` to do my task. IDK which timeout is required and which is not. How about including this helpful suggestion in the error message above.

**Comment by den-crane** [comment]
>Timeout exceeded while receiving data from server. Waited for 300 seconds, timeout is 300 seconds.
>Cancelling query.

It means nothing. Nothing wes canceled. 
Opimize was working until the successful end.

**Comment by 4ertus2** [comment]
duplicate #6093

**Comment by vmarkovtsev** [comment]
@den-crane I doubled-checked this: no, the indexes were not created.

**Comment by filimonov** [comment]
Proper way would be just to skip both timeout / and cancellation logic in case of non-breakable queries. 

But actually the main problem here is lack of transparency / misleading messages. So logic can even stay the same, but at least messages should give better feeling of what happens inside.

**Comment by zhouyao1994** [comment]
> > Timeout exceeded while receiving data from server. Waited for 300 seconds, timeout is 300 seconds.
> > Cancelling query.
> 
> It means nothing. Nothing was canceled.
> Optimize was working until the successful end.
> 
> `optimize` and `alter` are uninterruptible due timeout. It means that client did not receive any messages from server and tried to cancel a query but the cancellation is impossible.

thanks a lot.
