### ISSUE TITLE
document that groupby results has to fit into memory

### ISSUE THREAD

**Issue by jangorecki** [yandex/ClickHouse#6576]
more details in: https://github.com/yandex/ClickHouse/issues/5618#issuecomment-521956381

**Comment by alexey-milovidov** [comment]
GROUP BY result doesn't have to fit in memory, look at https://clickhouse.yandex/docs/en/query_language/select/#select-group-by-in-external-memory

**Comment by jangorecki** [comment]
@alexey-milovidov your link does not seems to work. Searching for "external memory" on a website it points now is not finding anything. Related issue #5618 has been closed, but it is not clear if it is resolved already. @filimonov wrote

> We have to copy the relevant information

was that information copied at all?
I am still stuck on this documentation gap in tunning clickhouse benchmark.

**Comment by alexey-milovidov** [comment]
I found that the info was moved here:
https://clickhouse.tech/docs/en/sql-reference/statements/select/group-by/#select-group-by-in-external-memory
