### ISSUE TITLE
Is any way to rename table mannualy

### ISSUE THREAD

**Issue by thyn** [yandex/ClickHouse#6588]
When I try to rename table I've got

`
File access error: Invalid cross-device link
`
It's true :)

How to rename table manually? When I try to attach with different name i've got 

`
Code: 107, e.displayText() = DB::ErrnoException: Cannot open file /data/clickhouse/metadata/income/income_old.sql, errno: 2, strerror: No such file or directory (version 19.13.2.19)
`

**Comment by stavrolia** [comment]
What kind of engine do you use?

**Comment by 4ertus2** [comment]
There's a RENAME query: https://clickhouse.yandex/docs/en/query_language/misc/#misc_operations-rename
It recuires that your source and destination tables are on the same device (to be able move data by hard links). Could you print ```show create metadata.income``` and your rename query to check if you made an error.

**Comment by alexey-milovidov** [comment]
@thyn There is a way to move table to a separate device:
1. Stop `clickhouse-server`.
2. Move table data directory to desired location.
3. Create symlink in a place of previous directory that points to new place. Make sure it is accessible to `clickhouse` user.
4. Start `clickhouse-server`.

**Comment by thyn** [comment]
> @thyn There is a way to move table to a separate device:
> 
> 1. Stop `clickhouse-server`.
> 2. Move table data directory to desired location.
> 3. Create symlink in a place of previous directory that points to new place. Make sure it is accessible to `clickhouse` user.
> 4. Start `clickhouse-server`.

I need to rename table. not moving. Also path already hardlinked But I can't move table in it.

final path is /data/clickhouse/metadata/income/ 
/data/clickhouse/ is  hardlink
