### ISSUE TITLE
Running INSERT query on a VIEW does not throw an exception

### ISSUE THREAD

**Issue by Ngalstyan4** [yandex/ClickHouse#66]
When trying to insert into a NON MATERIALIZED VIEW clickhouse returns Ok, 
but actually inserts nothing.
It is normal that in this case nothing shall be inserted as it says in the documentation that non materialized view is just a saved query.
However, I think an exception shall be thrown in this case to prevent some potential bugs.

**Comment by alexey-milovidov** [comment]
> I think an exception shall be thrown in this case to prevent some potential bugs.

Right, need to fix.

**Comment by zhang2014** [comment]
@alexey-milovidov Maybe It has been fixed, can we close this issue?
