### ISSUE TITLE
extractAll Segmentation fault

### ISSUE THREAD

**Issue by vmanyushin** [yandex/ClickHouse#6627]
This query lead to segmentation fault

`
SELECT extractAll(visitParamExtractString('{"userAgent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.143 YaBrowser/19.7.2.455 Yowser/2.5 Safari/537.36"}', 'userAgent'), '[Y][a-zA-Z]{8}/[1-9]([1-9]+)?(((.?)([0-9]+)?){0,4})?')
`

CH Version (from altinity packages)
- 19.13.2.19
- 19.13.1.11

**Comment by 4ertus2** [comment]
No crash in debug master build. Need some investigation.

**Comment by alexey-milovidov** [comment]
Does it reproduce in official build?

**Comment by den-crane** [comment]
official build 19.13.1.1066 (Debian LXC) Debian 3.16.43-2+deb8u2

Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000
Connecting to localhost:9000 as user default.
Code: 210. DB::NetException: Connection refused (localhost:9000)

ClickHouse client version 19.13.1.1066 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 19.13.1 revision 54425.

2019.08.23 12:46:45.857333 [ 59 ] {} <Fatal> BaseDaemon: ########################################
2019.08.23 12:46:45.857376 [ 59 ] {} <Fatal> BaseDaemon: (version 19.13.1.1066 (official build)) (from thread 46) Received signal Aborted (6).
2019.08.23 12:46:45.857388 [ 59 ] {} <Fatal> BaseDaemon:
2019.08.23 12:46:45.857572 [ 59 ] {} <Fatal> BaseDaemon: 3. 0x7fa54260bfff raise /lib/x86_64-linux-gnu/libc-2.24.so
4. 0x7fa54260d42a abort /lib/x86_64-linux-gnu/libc-2.24.so
5. 0x7fa542649c00 ? /lib/x86_64-linux-gnu/libc-2.24.so
6. 0x7fa5426d2437 __fortify_fail /lib/x86_64-linux-gnu/libc-2.24.so
7. 0x7fa5426d2400 __fortify_fail /lib/x86_64-linux-gnu/libc-2.24.so
8. 0x7a79604 ? /usr/bin/clickhouse
9. 0x446c0a9 DB::FunctionTokens<DB::ExtractAllImpl>::executeImpl(DB::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long) /usr/bin/clickhouse
10. 0x745ce50 DB::PreparedFunctionImpl::execute(DB::Block&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, unsigned long, bool) /usr/bin/clickhouse
11. 0x76478c9 DB::ExpressionAction::prepare(DB::Block&, DB::Settings const&) /usr/bin/clickhouse
12. 0x7648615 DB::ExpressionActions::addImpl(DB::ExpressionAction, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) /usr/bin/clickhouse
13. 0x7648a43 DB::ExpressionActions::add(DB::ExpressionAction const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) /usr/bin/clickhouse
14. 0x7786032 DB::ScopeStack::addAction(DB::ExpressionAction const&) /usr/bin/clickhouse
15. 0x7789824 DB::ActionsVisitor::visit(std::shared_ptr<DB::IAST> const&) /usr/bin/clickhouse
16. 0x7788bf5 DB::ActionsVisitor::visit(std::shared_ptr<DB::IAST> const&) /usr/bin/clickhouse
17. 0x765abd9 DB::ExpressionAnalyzer::getRootActions(std::shared_ptr<DB::IAST> const&, bool, std::shared_ptr<DB::ExpressionActions>&, bool) /usr/bin/clickhouse
18. 0x765d3d2 DB::ExpressionAnalyzer::appendSelect(DB::ExpressionActionsChain&, bool) /usr/bin/clickhouse
19. 0x6f52b40 DB::InterpreterSelectQuery::analyzeExpressions(DB::QueryProcessingStage::Enum, bool, std::shared_ptr<DB::FilterInfo> const&) /usr/bin/clickhouse
20. 0x6f70be6 void DB::InterpreterSelectQuery::executeImpl<DB::InterpreterSelectQuery::Pipeline>(DB::InterpreterSelectQuery::Pipeline&, std::shared_ptr<DB::IBlockInputStream> const&, bool) /usr/bin/clickhouse
21. 0x6f546c7 DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, std::shared_ptr<DB::IBlockInputStream> const&, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) /usr/bin/clickhouse
22. 0x6f55127 DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) /usr/bin/clickhouse
23. 0x6f750b8 DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) /usr/bin/clickhouse
24. 0x6f36358 DB::InterpreterFactory::get(std::shared_ptr<DB::IAST>&, DB::Context&, DB::QueryProcessingStage::Enum) /usr/bin/clickhouse
25. 0x707ac1e ? /usr/bin/clickhouse
26. 0x707afcc DB::executeQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) /usr/bin/clickhouse
27. 0x3d65b20 DB::TCPHandler::runImpl() /usr/bin/clickhouse
28. 0x3d664eb DB::TCPHandler::run() /usr/bin/clickhouse
29. 0x7ae2e40 Poco::Net::TCPServerConnection::start() /usr/bin/clickhouse
30. 0x7ae355d Poco::Net::TCPServerDispatcher::run() /usr/bin/clickhouse
31. 0x8201e31 Poco::PooledThread::run() /usr/bin/clickhouse
--------------------------

Docker hangs with 100% CPU

ClickHouse client version 19.13.2.19 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 19.13.2 revision 54425.

Timeout exceeded while receiving data from server. Waited for 300 seconds, timeout is 300 seconds.
Cancelling query.

**Comment by den-crane** [comment]
19.13.3.26  
Linux xxxx 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3 (2017-12-03) x86_64 GNU/Linux

Also crashes

**Comment by 4ertus2** [comment]
gcc build crashes

**Comment by 4ertus2** [comment]
Crash cause of stack corruption here https://github.com/yandex/ClickHouse/blob/master/dbms/src/Common/OptimizedRegularExpression.cpp#L416

MAX_SUBPATTERNS = 5,
limit = 6
