### ISSUE TITLE
Build fails on Ubuntu 18.04 for v19.13.3.26-stable

### ISSUE THREAD

**Issue by boqu** [yandex/ClickHouse#6628]
Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.yandex/docs/en/development/build/

**Operating system**
OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.

**Cmake version**

**Ninja version**

**Compiler name and version**

**Full cmake and/or ninja output**

**Comment by alesapin** [comment]
Our CI uses exactly ubuntu 18.04 and checks every commit with two different compilers (`gcc-9` and `clang-8`) and multiple cmake options. You can build reports in status reference for each commit in master and PR. Example https://clickhouse-builds.s3.yandex.net/0/7985270624e877de15f958f0e3f19a23365f34de/report.html. 

It seems like something wrong with your setup. Please, provide any details and reopen issue.
