### ISSUE TITLE
ThreadSanitizer: clickhouse-client thread-leak warning

### ISSUE THREAD

**Issue by vzakaznikov** [yandex/ClickHouse#6655]
Thread sanitizer sometimes throws a warning when clickhouse-client is killed.
 
WARNING: ThreadSanitizer: thread leak (pid=5876)
  Thread T1 (tid=5878, finished) created by main thread at:
    #0 pthread_create ??:? (clickhouse+0x35b02c6)
    #1 std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) ??:? (clickhouse+0xbf36504)
    #2 DB::Suggest::load(DB::ConnectionParameters const&, unsigned long) /home/user/github/ClickHouse_vzakaznikov/build/../dbms/programs/client/Suggest.h:169 (clickhouse+0x3746198)
    #3 DB::Client::mainImpl() /home/user/github/ClickHouse_vzakaznikov/build/../dbms/programs/client/Client.cpp:416 (clickhouse+0x374172e)
    #4 DB::Client::main(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) /home/user/github/ClickHouse_vzakaznikov/build/../dbms/programs/client/Client.cpp:242 (clickhouse+0x373f244)
    #5 Poco::Util::Application::run() /home/user/github/ClickHouse_vzakaznikov/build/../contrib/poco/Util/src/Application.cpp:335 (clickhouse+0xac9db0d)
    #6 mainEntryClickHouseClient(int, char**) /home/user/github/ClickHouse_vzakaznikov/build/../dbms/programs/client/Client.cpp:1860 (clickhouse+0x3732b04)
    #7 main /home/user/github/ClickHouse_vzakaznikov/build/../dbms/programs/main.cpp:166 (clickhouse+0x364bede)

SUMMARY: ThreadSanitizer: thread leak ??:? in pthread_create

**Comment by alexey-milovidov** [comment]
Suggest is a singleton and thread is joined in global destructors.
Nevertheless, it's Ok for clickhouse-client to not wait for suggest thread to finish.
