### ISSUE TITLE
Incl where to configure

### ISSUE THREAD

**Issue by xingxing9688** [yandex/ClickHouse#666]
By default, path to file with substitutions is /etc/metrika.xml. It could be changed in config in 'include_from' element?
  The incl attribute is added and changed

**Comment by ztlpn** [comment]
Yes, you can change substitutions file in the main config.xml by setting `include_from` parameter. Like this:
```xml
<?xml version="1.0"?>
<yandex>
    <include_from>/path/to/your/substitutions.xml</include_from>
    ...
```

**Comment by alexey-milovidov** [comment]
Please tell if our answer has helped you.

**Comment by RustRw** [comment]
can i use tow include_froms ， for example： macros in different host is different
