### ISSUE TITLE
Is there any function like hive's concat_ws or explode or collect_list/collect_array

### ISSUE THREAD

**Issue by Tasselmi** [yandex/ClickHouse#6664]
IS there any function like hive's concat_ws or explode or collect_list/collect_array?
Thanks.

**Comment by filimonov** [comment]
Check that https://clickhouse.yandex/docs/en/query_language/functions/splitting_merging_functions/

**Comment by Tasselmi** [comment]
Thanks

**Comment by akbarali1** [comment]
```
 arrayStringConcat([users.l_name, users.f_name, users.m_name], ' ') as full_name
```
