### ISSUE TITLE
Dictionary not work ,Need help?

### ISSUE THREAD

**Issue by lzy305** [yandex/ClickHouse#6668]
updategrade to 19.13.3.26,  Dictionary  not work.

select * from system.dictionaries;

dw_good_info,NOT_LOADED,/etc/clickhouse-server/dw_good_info_dictionary.xml,"","","","",0,0,0,0,0,"",,0,""
dw_buinfo,NOT_LOADED,/etc/clickhouse-server/dw_buinfo_dictionary.xml,"","","","",0,0,0,0,0,"",,0,""
mapping_shop_address_info,NOT_LOADED,/etc/clickhouse-server/mapping_shop_address_info_dictionary.xml,"","","","",0,0,0,0,0,"",,0,""
dw_vender_info,NOT_LOADED,/etc/clickhouse-server/dw_vender_info_dictionary.xml,"","","","",0,0,0,0,0,"",,0,""
mapping_category_fresh_info,NOT_LOADED,/etc/clickhouse-server/mapping_category_fresh_info_dictionary.xml,"","","","",0,0,0,0,0,"",,0,""
dw_category_info,NOT_LOADED,/etc/clickhouse-server/dw_category_info_dictionary.xml,"","","","",0,0,0,0,0,"",,0,""
mapping_shop_bu_info,NOT_LOADED,/etc/clickhouse-server/mapping_shop_bu_info_dictionary.xml,"","","","",0,0,0,0,0,"",,0,""
dw_shop,NOT_LOADED,/etc/clickhouse-server/dw_shop_info_dictionary.xml,"","","","",0,0,0,0,0,"",,0,""

How to solve it?

**Comment by alexey-milovidov** [comment]
Dictionaries will load on first use.

**Comment by lzy305** [comment]
I restart clickhouse-server and then wait for an hour. I find still "NOT_LOADED".

**Comment by vitlibar** [comment]
> I restart clickhouse-server and then wait for an hour. I find still "NOT_LOADED".

If a dictionary is "NOT LOADED" it means it hasn't been loaded because none needed it.
Just start using any dictionary and check the status then:

```
SELECT dictHas('dw_good_info', 1)
```
