### ISSUE TITLE
Collapsing Merge Tree Using FINAL in the SQL

### ISSUE THREAD

**Issue by MeteHanC** [yandex/ClickHouse#6671]
Hello,

I decided to use CollapsingMergeTree for a test table. This table basically keeps the football players name and their teams. For example ;

```
CREATE TABLE players
    (
     `team_id` UInt32,
     `player_name` String,
      `pid` UInt32,
      sign Int8 DEFAULT 1
    ) ENGINE = CollapsingMergeTree(sign) ORDER BY (player_name, pid) SETTINGS index_granularity = 8192
```
So I understood the usage of sign for the querying with 'having' but what I want to ask is when I want to get the player count by grouping by team_id, having sum(sign) > 0 ' won't work properly since it will aggregate all the player's sign values. 

So what I would like to ask is if I use FINAL in my SQL all the time, will it decrease performance dramatically? (There could be around 50M-100M rows at maximum!)

Thanks in the advance!

**Comment by alexey-milovidov** [comment]
Yes, FINAL affects performance dramatically.

**Comment by MeteHanC** [comment]
> Yes, FINAL affects performance dramatically.

Thank you! And this issue could be helpful as well : #1661
