### ISSUE TITLE
Segmentation fault in 19.8.3.8

### ISSUE THREAD

**Issue by woozhijun** [yandex/ClickHouse#6683]
**clickhouse segmentation fault, unknown reason.**

> (version 19.8.3.8)
2019.08.25 23:02:12.443223 [ 9442 ] {} <Error> BaseDaemon: ########################################
2019.08.25 23:02:12.443428 [ 9442 ] {} <Error> BaseDaemon: (version 19.8.3.8) (from thread2893) Received signal Segmentation fault (11).
2019.08.25 23:02:12.443441 [ 9442 ] {} <Error> BaseDaemon: Address: NULL pointer.
2019.08.25 23:02:12.443448 [ 9442 ] {} <Error> BaseDaemon: Access: read.
2019.08.25 23:02:12.443454 [ 9442 ] {} <Error> BaseDaemon: Unknown si_code.
2019.08.25 23:02:12.708359 [ 9442 ] {} <Error> BaseDaemon: 0. clickhouse-server(DB::MergeTreeDataPart::getColumnSizeImpl(std::string const&, DB::IDataType const&, std::unordered_set<std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::string> >*) const+0xa5) [0x63138b5]
2019.08.25 23:02:12.708417 [ 9442 ] {} <Error> BaseDaemon: 1. clickhouse-server(DB::MergeTreeDataPart::getTotalColumnsSize() const+0xaf) [0x6313a2f]
2019.08.25 23:02:12.708429 [ 9442 ] {} <Error> BaseDaemon: 2. clickhouse-server(DB::StorageSystemParts::processNextStorage(std::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::StoragesInfo const&, bool)+0xa36) [0x5edc6e6]
2019.08.25 23:02:12.708440 [ 9442 ] {} <Error> BaseDaemon: 3. clickhouse-server(DB::StorageSystemPartsBase::read(std::vector<std::string, std::allocator<std::string> > const&, DB::SelectQueryInfo const&, DB::Context const&, DB::QueryProcessingStage::Enum, unsigned long, unsigned int)+0xbd) [0x5ee15cd]
2019.08.25 23:02:12.708451 [ 9442 ] {} <Error> BaseDaemon: 4. clickhouse-server(DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::InterpreterSelectQuery::Pipeline&, std::shared_ptr<DB::PrewhereInfo> const&, std::vector<std::string, std::allocator<std::string> > const&)+0x1e4b) [0x607b69b]
2019.08.25 23:02:12.708470 [ 9442 ] {} <Error> BaseDaemon: 5. clickhouse-server(DB::InterpreterSelectQuery::executeImpl(DB::InterpreterSelectQuery::Pipeline&, std::shared_ptr<DB::IBlockInputStream> const&, bool)+0x742) [0x607ec82]

**Comment by filimonov** [comment]
It looks like it's connected to some query from system.parts. Can you try to find that query in /var/log/clickhouse-server/clickhouse-server.log ? It should be somewhere before the segfault.

**Comment by woozhijun** [comment]
> It looks like it's connected to some query from system.parts. Can you try to find that query in /var/log/clickhouse-server/clickhouse-server.log ? It should be somewhere before the segfault.

I check the log and found,
`The part /clickhouse/tables/shard/nx_access/replicas/clickhouse6-master/parts/20190726_100844_101049_44 on a replica suddenly appeared, will recheck checksums`
And check system.query_log exist like parts query,
`select database, table, sum(bytes) as bytes, count() as parts, sum(rows) as rows from system.parts where active = 1 group by database, table
`
But, this query not cause segfault/crash.

**Comment by alexey-milovidov** [comment]
This bug is fixed in https://github.com/yandex/ClickHouse/pull/6514 and backported to 19.13, 19.11.
