### ISSUE TITLE
DB::Exception: Cannot create table from metadata file

### ISSUE THREAD

**Issue by MeteHanC** [yandex/ClickHouse#6714]
Hello,
So I have 3 replicas and 3 zookeeper instances. It was all working fine and I decided to test the _'[Recovery After Complete Data Loss](https://clickhouse.yandex/docs/en/operations/table_engines/replication/#recovery-after-complete-data-loss)'_ section in a test environment. I killed one replica, format its disks and reinstall clickhouse and the zookeeper. After completing the configuration, I copied all the meta data and forced to replicate and restart the CH. It was looking good at that point but after that I have done random stuff like ; killing zookeeper instances and re-initializing, alter table updates etc. Then I've noticed that alter table update was scheduled _(with querying 'system.mutations table')_ but it was not taking place at that moment and it was not set to done after 1 hour. 

So I killed the leader zookeeper node, and suddenly mutation took place in the other 2 replicas. I restarted the zookeeper in the previous leader node but the mutation still did not take place so I restarted the ClickHouse. However CH initialize failed with the following error  : **_'DB::Exception: Cannot create table from metadata file /../clickhouse/metadata/default//player.sql, error: Coordination::Exception: No node, path: /clickhouse/tables/01-01/player/replicas/server2/parts' (Server-2 is the node with issues)_**

Full Stack Trace : 
```
`2019.08.28 20:19:51.484874 [ 1 ] {} <Error> Application: DB::Exception: Cannot create table from metadata file /../clickhouse/metadata/default//player.sql, error: Coordination::Exception: No node, path: /clickhouse/tables/01-01/player/replicas/server-2/parts, stack trace:
0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x30) [0x7f6b5f0]
1. /usr/bin/clickhouse-server(Coordination::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int)+0x30) [0x764f210]
2. /usr/bin/clickhouse-server(Coordination::Exception::Exception(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x163) [0x764fb03]
3. /usr/bin/clickhouse-server() [0x3a8d1c7]
4. /usr/bin/clickhouse-server(DB::StorageReplicatedMergeTree::checkParts(bool)+0x9d) [0x6fd19ed]
5. /usr/bin/clickhouse-server(DB::StorageReplicatedMergeTree::StorageReplicatedMergeTree(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::ColumnsDescription const&, DB::IndicesDescription const&, DB::Context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::IAST> const&, DB::MergeTreeData::MergingParams const&, DB::MergeTreeSettings const&, bool)+0x12e3) [0x6fe4253]
6. /usr/bin/clickhouse-server() [0x712fb3b]
7. /usr/bin/clickhouse-server(std::_Function_handler<std::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&), std::shared_ptr<DB::IStorage> (*)(DB::StorageFactory::Arguments const&)>::_M_invoke(std::_Any_data const&, DB::StorageFactory::Arguments const&)+0x25) [0x71317f5]
8. /usr/bin/clickhouse-server(DB::StorageFactory::get(DB::ASTCreateQuery&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context&, DB::Context&, DB::ColumnsDescription const&, bool, bool) const+0x28e) [0x6f7621e]
9. /usr/bin/clickhouse-server(DB::createTableFromDefinition(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x2d1) [0x6ce3601]
10. /usr/bin/clickhouse-server() [0x738e19d]
11. /usr/bin/clickhouse-server() [0x738e6cf]
12. /usr/bin/clickhouse-server(ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::_List_iterator<ThreadFromGlobalPool>)+0x1a7) [0x3c785e7]
13. /usr/bin/clickhouse-server(ThreadFromGlobalPool::ThreadFromGlobalPool<ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::function<void ()>, int, std::optional<unsigned long>)::{lambda()#3}>(ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::function<void ()>, int, std::optional<unsigned long>)::{lambda()#3}&&)::{lambda()#1}::operator()() const+0x3e) [0x3c78bce]
14. /usr/bin/clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1a6) [0x3c760f6]
15. /usr/bin/clickhouse-server() [0xba3e1a0]
16. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7efe7221e6db]
17. /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7efe719a588f]`

```
I double checked other 2 live replicas and both were working fine, getting the mutations done in seconds. 
I have solved the issue by deleting the player table from all replicas and recreate it again. Although this approach solved my problem, this can not be done in production for obvious reasons. Could this be a bug? And if it is an expected behavior, what was the reason of the issue? To be honest, I did not quite understand why would this happen after an alter update.

Thanks in the advance

**Comment by MeteHanC** [comment]
I think this could be related to  : #6496

**Comment by filimonov** [comment]
It's nice to get a feedback from such a chaos testing session. :)

General answer is: to replace one replica you don't need to recreate tables or do any destructive operations. But to make it work you need to have same server configuration and healthy zookeeper state. If you have zookeeper data damaged or server configurationis different - you may need to make some manual manipulation on zookeeper side (like remove fragment related to missing replica), or recreate the table by migrating it from Replicated to non-Replicated and back again (there are instructions is in docs).

From your story the most unclear moments are: 
1) what do you mean by 're-initializing zookeeper instances'
2) what do you mean by 'It was looking good at that point' (at least you need to check system.replicas table after each step)
3) 'I killed the leader zookeeper node, and suddenly mutation took place' - may be some of your manipulations make the zookeeper to a 'split brain' situation? I.e. you actually have had 2 ensembles after reinitialization instead of one?  
4) Did you use the same with {replica} macro value "before" and "after"?

**Comment by MeteHanC** [comment]
> It's nice to get a feedback from such a chaos testing session. :)
> 
> From your story the most unclear moments are:
> 
> 1. what do you mean by 're-initializing zookeeper instances'
> 2. what do you mean by 'It was looking good at that point' (at least you need to check system.replicas table after each step)
> 3. 'I killed the leader zookeeper node, and suddenly mutation took place' - may be some of your manipulations make the zookeeper to a 'split brain' situation? I.e. you actually have had 2 ensembles after reinitialization instead of one?
> 4. Did you use the same with {replica} macro value "before" and "after"?

Thank you and sorry about the confusing parts of the issue. So let me answer the questions;
1. I basically restarted the zookeeper service by executing **'zkServer.sh'** file

2. Yes, I checked 'system.replicas' table at the each step, it was as expected and I ran the query which was on the [official documentation ](https://clickhouse-docs.readthedocs.io/en/latest/system_tables/system.replicas.html)to make sure everything was working fine. And data was being replicated as well. (Though, at the first step I misconfigured **'macros.xml'** and got an error. Server name was pointing the server-2(It should be set to Server-1), so I noticed and changed it. After the change it worked fine, I am not sure this could damage the 'player' table on the cluster. By the way server-2 is the replica with the issues) 

3. Hmm, but the thing is after killing all the zookeeper executables, I restarted them all with 'zkServer.sh start-foreground', and election took place in all 3 replicas. Let me give you some detailed information about that step. So after executing the mutation, I checked the 'system.mutations' table and task was not done yet. So I thought it would be done after running 'optimize' query for that table, however optimize query failed with an error code which included 'server-2' again. (Server-2 was the zookeeper leader at that time). So I killed the zookeeper in server-2 and checked the 'mutations' table again, and mutation was done in server-1 and server-3 and then I checked server-2 but mutation was still not done. So I restarted the CH node and got this issue from that time. 

4. Actually yes, it was the same but as I said I made a small mistake as I described in 2nd question. After that I changed it and it was the exact same config.

I hope my answers were clear for you

**Comment by filimonov** [comment]
> After the change it worked fine, I am not sure this could damage the 'player' table on the cluster. By the way server-2 is the replica with the issues)

In certain circumstances it definitely can make a mess in zookeeper. I'm not 100% sure but i would say with some 'extra luck' it may be a source of the problem you describe  

> So I restarted the CH node and got this issue from that time.

I think that restart itself without all that manipulation would lead to the same result. The think that helped migration to be finished - is disappearing of that malfunctioning node which didn't send any acknowledgements about  the mutation state.

**Comment by MeteHanC** [comment]
> > 
> I think that restart itself without all that manipulation would lead to the same result. The thing that helped migration to be finished - is disappearing of that malfunctioning node which didn't send any acknowledgements about the mutation state.

Hmm, I see. You are probably right. I deleted all the disks and reinstalled the OS and RAID from scratch and made a clean CH and Zookeeper installation for server-2 yet the issue was not solved. When I have the time I will try to reproduce this issue and when it occurs, I will just change the server name in macros.xml and metrika.xml files. If it works fine that way, problem is definitely zookeeper mess.

Thanks a lot !
