### ISSUE TITLE
导入分隔符为“|”的csv格式数据转义符\|不识别问题

### ISSUE THREAD

**Issue by xuxudede** [yandex/ClickHouse#6745]
csv数据内容如下，正常是只有一个列（类型为String），导入时却被识别成两个列。
`aaa\|bbbb`
请问有什么参数设置能识别转义符吗\

**Comment by filimonov** [comment]
CHeck `format_csv_delimiter`

**Comment by xuxudede** [comment]
> format_csv_delimiter

--format_csv_delimiter="|"

**Comment by filimonov** [comment]
Yes.
