### ISSUE TITLE
Refuse to support atomicity of multiple tables rename

### ISSUE THREAD

**Issue by alexey-milovidov** [yandex/ClickHouse#6757]
The query

```
RENAME a TO c, b TO a, c TO b
```

is documented to be atomic from the point of view of other clients.
For example, no one else will see table `c` in any moment of time.

This is barely supported in ClickHouse, but many complications exist:

1. It isn't atomic in respect to `kill -9`.
2. It isn't atmoic in the case of unexpected errors in the middle of rename chain.
3. The query `SELECT * FROM a UNION ALL SELECT * FROM b` doesn't use atomic snapshot of database catalog. In presence of concurrent `RENAME a TO c, b TO a, c TO b` it may read from `a` two times or from `b` two times. Every sub-select uses atomic snapshot of database catalog but not all query as a whole.
4. The logic to support atomicity of RENAME is too complicated and it's difficult to avoid deadlocks (it's technically possible, but the logic is broken).

Proposed solution:

- multiple tables rename is still supported (as now);
- it is serialized in respect to other DDL operations involving the same tables (as now);
- it's checked that all rename chain is possible and in absense of unexpected errors, either all renames performed or no renames performed (as now);
- other clients may see intermediate state - for example, clients may see table `c` of `RENAME a TO c, b TO a, c TO b` (this is what will be changed).

**Comment by winter7** [comment]
How to avoid `Table a doesn't exist` error during `RENAME  table a TO c, b TO a`?

**Comment by zhuyoucui0909** [comment]
@alexey-milovidov  Could you explain more about `EXCHANGE TABLES`? From which version it is supported? How to create a database of Atomic engine? How to exchange two tables? Could you  help to give some examples?

Thanks

**Comment by arjenzhou** [comment]
@zhuyoucui0909 
https://clickhouse.tech/docs/en/engines/database-engines/atomic/#exchange-tables

This may resolve your question.

**Comment by arjenzhou** [comment]
Just remind: this feature need linux kernel support (renameat2(), which was introduced after 3.15)
