### ISSUE TITLE
Clickhouse giving 

### ISSUE THREAD

**Issue by George3d6** [yandex/ClickHouse#676]
When setting up a replicating table (on tow machines in a local network) I get the following error once I insert some data into one of the machines:

> Apr 11 15:05:26 ryzen2 clickhouse-server[25789]: 2017.04.11 15:05:26.331496 [ 10 ] <Trace> ReadWriteBufferFromHTTP: Sending request to http://ryzen1:9009/?endpoint=DataPartsExchange:%2Fclickhouse%2Ftables%2FimpressionsFtest%2Freplicas%2F1&part=20170327_20170327_200_200_0&shard=&compress=false
> Apr 11 15:05:26 ryzen2 clickhouse-server[25789]: 2017.04.11 15:05:26.343856 [ 10 ] <Error> DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 86, e.displayText() = DB::Exception: Received error from remote server http://ryzen1:9009/?endpoint=DataPartsExchange:%2Fclickhouse%2Ftables%2FimpressionsFtest%2Freplicas%2F1&part=20170327_20170327_200_200_0&shard=&compress=false. HTTP status code: 400 Bad Request, body: , e.what() = DB::Exception, Stack trace:
> Apr 11 15:05:26 ryzen2 clickhouse-server[25789]: 0. /usr/lib/libclickhouse.so.1(StackTrace::StackTrace()+0x16) [0x7f05dab27156]
> Apr 11 15:05:26 ryzen2 clickhouse-server[25789]: 1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x26) [0x503816]
> Apr 11 15:05:26 ryzen2 clickhouse-server[25789]: 2. /usr/lib/libclickhouse.so.1(DB::ReadWriteBufferFromHTTP::ReadWriteBufferFromHTTP(Poco::URI const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (std::ostream&)>, unsigned long, DB::HTTPTimeouts const&)+0x1645) [0x7f05dab50db5]
> Apr 11 15:05:26 ryzen2 clickhouse-server[25789]: 3. /usr/lib/libclickhouse.so.1(DB::DataPartsExchange::Fetcher::fetchPartImpl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)+0x4fa) [0x7f05dac60e6a]
> Apr 11 15:05:26 ryzen2 clickhouse-server[25789]: 4. /usr/lib/libclickhouse.so.1(DB::DataPartsExchange::Fetcher::fetchPart(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, bool)+0x69) [0x7f05dac63829]
> Apr 11 15:05:26 ryzen2 clickhouse-server[25789]: 5. /usr/lib/libclickhouse.so.1(DB::StorageReplicatedMergeTree::fetchPart(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, unsigned long)+0x232) [0x7f05dac25af2]
> Apr 11 15:05:26 ryzen2 clickhouse-server[25789]: 6. /usr/lib/libclickhouse.so.1(DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry const&)+0x1407) [0x7f05dac27d87]
> Apr 11 15:05:26 ryzen2 clickhouse-server[25789]: 7. /usr/lib/libclickhouse.so.1(+0x28d2610) [0x7f05dac2a610]
> Apr 11 15:05:26 ryzen2 clickhouse-server[25789]: 8. /usr/lib/libclickhouse.so.1(DB::ReplicatedMergeTreeQueue::processEntry(std::function<std::shared_ptr<zkutil::ZooKeeper> ()>, std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::function<bool (std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>)+0x40) [0x7f05dacf7970]
> Apr 11 15:05:26 ryzen2 clickhouse-server[25789]: 9. /usr/lib/libclickhouse.so.1(DB::StorageReplicatedMergeTree::queueTask()+0x152) [0x7f05dac0a5b2]
> Apr 11 15:05:26 ryzen2 clickhouse-server[25789]: 10. /usr/lib/libclickhouse.so.1(DB::BackgroundProcessingPool::threadFunction()+0x41b) [0x7f05dac5c64b]
> Apr 11 15:05:26 ryzen2 clickhouse-server[25789]: 11. /usr/bin/clickhouse-server() [0x67231f]
> Apr 11 15:05:26 ryzen2 clickhouse-server[25789]: 12. /lib64/libpthread.so.0(+0x7537) [0x7f05d6d37537]
> Apr 11 15:05:26 ryzen2 clickhouse-server[25789]: 13. /lib64/libc.so.6(clone+0x3f) [0x7f05d59c304f]
> 

I would like to put emphasis on:

> Apr 11 15:05:26 ryzen2 clickhouse-server[25789]: 2017.04.11 15:05:26.331496 [ 10 ] <Trace> ReadWriteBufferFromHTTP: Sending request to http://ryzen1:9009/?endpoint=DataPartsExchange:%2Fclickhouse%2Ftables%2FimpressionsFtest%2Freplicas%2F1&part=20170327_20170327_200_200_0&shard=&compress=false
> Apr 11 15:05:26 ryzen2 clickhouse-server[25789]: 2017.04.11 15:05:26.343856 [ 10 ] <Error> DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 86, e.displayText() = DB::Exception: Received error from remote server http://ryzen1:9009/?endpoint=DataPartsExchange:%2Fclickhouse%2Ftables%2FimpressionsFtest%2Freplicas%2F1&part=20170327_20170327_200_200_0&shard=&compress=false. HTTP status code: 400 Bad Request, body: , e.what() = DB::Exception, Stack trace:

Since this is what confuses me.... when I run wget (or curl -X GET) on the following url:

http://ryzen1:9009/?endpoint=DataPartsExchange:%2Fclickhouse%2Ftables%2FimpressionsFtest%2Freplicas%2F1&part=20170327_20170327_200_200_0&shard=&compress=false

I just get a binary body of ~100MB and a status of 200(OK).... so I'm quite unsure why clickhouse is reading that as status 400 (Bad Request). Do you guys have any ideas/suggestions as to why this might be happening ?

**Comment by proller** [comment]
you catch broken version.
should be fixed here - https://github.com/yandex/ClickHouse/commit/38e9254d330a5a791e84fe0a2921ac00cd0226ff

for production better to use stable tags (like https://github.com/yandex/ClickHouse/tree/v1.1.54198-stable )

**Comment by George3d6** [comment]
I was running on an unsupported OS so I just cloned github and compiled, my bad :/ 
I will use the latest stable one from now, thank you very much for spotting this, I might have spend hours wondering what the hell was going on.

**Comment by proller** [comment]
also here true stable branch: https://github.com/yandex/ClickHouse/commits/stable
