### ISSUE TITLE
Настройка join_use_nulls = 1 не работает для Int

### ISSUE THREAD

**Issue by PlatonB** [yandex/ClickHouse#6765]
ClickHouse client version 19.13.3.26 (official build).
ClickHouse server version 19.13.3 revision 54425.

Из [документации](https://clickhouse.yandex/docs/ru/operations/settings/settings/#settings-join_use_nulls):
> join_use_nulls:
<...>
Возможные значения:
<...>
1 — JOIN ведёт себя как в стандартном SQL. Тип соответствующего поля преобразуется в Nullable, а пустые ячейки заполняются значениями NULL.

На самом деле, при join_use_nulls = 1, в результате применения LEFT JOIN на месте отсутствующего правого численного значения образуется 0, а не ожидаемый NULL.

Пример кода:
```
SET join_use_nulls = 1

CREATE DATABASE test
USE test

CREATE TABLE tbl_1 (int_col Int64) ENGINE = MergeTree() ORDER BY (int_col)
INSERT INTO tbl_1 (int_col) VALUES (1), (2), (3), (4), (5)

CREATE TABLE tbl_2 (int_col Int64) ENGINE = MergeTree() ORDER BY (int_col)
INSERT INTO tbl_2 (int_col) VALUES (3), (4), (5), (6), (7)

SELECT * FROM tbl_1 LEFT JOIN tbl_2 ON tbl_1.int_col = tbl_2.int_col
```

Получается:
```
┌─int_col─┬─tbl_2.int_col─┐
│       1 │             0 │
│       2 │             0 │
│       3 │             3 │
│       4 │             4 │
│       5 │             5 │
└─────────┴───────────────┘
```

Должно быть:
```
┌─int_col─┬─tbl_2.int_col─┐
│       1 │          NULL │
│       2 │          NULL │
│       3 │             3 │
│       4 │             4 │
│       5 │             5 │
└─────────┴───────────────┘
```

**Comment by den-crane** [comment]
Пример? Версия КХ?

Была проблема с ключевыми полями приходилось алиасить, починено месяц назад.
```
create table t(a Int64, b Int64) engine = TinyLog;
insert into t values(1,1);
create table s(a Int64, b Int64) engine = TinyLog;

set join_use_nulls = 1
select t.a, t.b, s.a, s.alias_a from t left join (select a,b, a as alias_a from s) s on (t.a=s.a);
┌─a─┬─b─┬─s.a─┬─alias_a─┐
│ 1 │ 1 │   0 │    ᴺᵁᴸᴸ │
└───┴───┴─────┴─────────┘
```
сейчас:
```
┌─a─┬─b─┬──s.a─┬─alias_a─┐
│ 1 │ 1 │ ᴺᵁᴸᴸ │    ᴺᵁᴸᴸ │
└───┴───┴──────┴─────────┘
```

**Comment by PlatonB** [comment]
Дополнил.

**Comment by den-crane** [comment]
Все как я и написал

Сейчас:
```
SELECT *
FROM tbl_1
LEFT JOIN tbl_2 ON tbl_1.int_col = tbl_2.int_col

┌─int_col─┬─tbl_2.int_col─┐
│       1 │          ᴺᵁᴸᴸ │
│       2 │          ᴺᵁᴸᴸ │
│       3 │             3 │
│       4 │             4 │
│       5 │             5 │
└─────────┴───────────────┘

19.14.1.1203
```

Раньше алиасить

```
SELECT * FROM tbl_1 LEFT JOIN 
(select *, int_col as int_col_XXX from tbl_2) as tbl_2  ON tbl_1.int_col = tbl_2.int_col;
┌─int_col─┬─tbl_2.int_col─┬─int_col_XXX─┐
│       1 │             0 │        ᴺᵁᴸᴸ │
│       2 │             0 │        ᴺᵁᴸᴸ │
│       3 │             3 │           3 │
│       4 │             4 │           4 │
│       5 │             5 │           5 │
└─────────┴───────────────┴─────────────┘
```

duplicate for https://github.com/yandex/ClickHouse/issues/3145

**Comment by PlatonB** [comment]
> Сейчас (починено #6249 ):
> 
> ```
> SELECT *
> FROM tbl_1
> LEFT JOIN tbl_2 ON tbl_1.int_col = tbl_2.int_col
> 
> ┌─int_col─┬─tbl_2.int_col─┐
> │       1 │          ᴺᵁᴸᴸ │
> │       2 │          ᴺᵁᴸᴸ │
> │       3 │             3 │
> │       4 │             4 │
> │       5 │             5 │
> └─────────┴───────────────┘
> 
> 19.14.1.1203
> ```

А как это у Вас с той же инструкцией вывелись два NULL, а не два нуля? У меня стабильно нули получаются.

**Comment by den-crane** [comment]
>А как это у Вас с моим вариантом инструкции вывелись два NULL, 
>а не два нуля? У меня стабильно нули получаются.

Эммм. Я написал что это уже починено месяц назад. Логично что я проверяю на починеной версии?

**Comment by alexey-milovidov** [comment]
Да, это ещё не вошло в релиз. Есть в 19.14 testing.
