### ISSUE TITLE
How does replicatingX decide what is the correct data ?

### ISSUE THREAD

**Issue by George3d6** [yandex/ClickHouse#679]
As far as I've seen in the documentation, a Replicating table will self-correct by measuring the size of blocks and moving mad blocks to a detached folder while replacing them with blocks from replica.

How does this mechanism work in order to decided what the correct block is ? I assume in a 3-replica scenario if 1 replica is different from the other 2, it just assumes that the other 2 are correct ? What about when you have only 2 replicas ? Can it handle that in any way (e.g. chose the block with the largest size) ? Is the mechanism by which it does this configurable at all ?

**Comment by xingxing9688** [comment]
Hello, I am also studying clickhouse, I built a distributed cluster, did you test the distributed cluster?

**Comment by ztlpn** [comment]
I assume that you are talking about [this section in the docs](https://clickhouse.yandex/reference_en.html#Recovery%20after%20failures). Replicas store info about their local parts in ZooKeeper (each replica in its own ZooKeeper path). During initialization of the table ClickHouse checks if this info is consistent with what is actually present on disk. As calculating the checksums of all parts would be prohibitively expensive, during server startup only file sizes are checked. So the replica is in a sense compared with itself.

Comparisons with other replicas are also performed - after downloading a new part or merging two parts. The parts with the same id must be byte-identical on all replicas. If the new part is somehow different from existing parts on other replicas it will be re-downloaded from one of them (doesn't matter which one - they are all identical).

**Comment by George3d6** [comment]
"Comparisons with other replicas are also performed - after downloading a new part or merging two parts."... Ok, so this first mechanism is independent of how many replicas you have whilst the second one, I'd assume, require 3 or more, am I right in that assumption ?

xingxing9688
Currently I'm planning on working with a very limited setup, a total of 5 or 6 machines (2xshards with 3xreplica each) so I can't help you very much on that. As far as I understand from the docs the ynadex guys are running ~300 machines so they are probably better suited to answer any questions.
