### ISSUE TITLE
insert into table format CSV 

### ISSUE THREAD

**Issue by xuxudede** [yandex/ClickHouse#6795]
Error on processing query: INSERT INTO test.xxx FORMAT CSV
Code: 69, e.displayText() = DB::Exception: Decimal value is too small, Stack trace:

0. clickhouse-client(StackTrace::StackTrace()+0x30) [0x6f28fc0]
1. clickhouse-client(DB::Exception::Exception(std::string const&, int)+0x1f) [0x31638df]
2. clickhouse-client(void DB::readDecimalText<DB::Decimal<__int128> >(DB::ReadBuffer&, DB::Decimal<__int128>&, unsigned int, unsigned int&, bool)+0xd0) [0x5d15bb0]
3. clickhouse-client(DB::DataTypeDecimal<DB::Decimal<__int128> >::readText(DB::Decimal<__int128>&, DB::ReadBuffer&, unsigned int, unsigned int, bool)+0x2d) [0x5d15cbd]
4. clickhouse-client(DB::DataTypeDecimal<DB::Decimal<__int128> >::deserializeTextCSV(DB::IColumn&, DB::ReadBuffer&, DB::FormatSettings const&) const+0x24) [0x5d15e84]
5. clickhouse-client(DB::CSVRowInputStream::read(std::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::RowReadExtension&)+0x17f) [0x65fac8f]
6. clickhouse-client(DB::BlockInputStreamFromRowInputStream::readImpl()+0x134) [0x65f5e24]
7. clickhouse-client(DB::IBlockInputStream::read()+0x238) [0x5c53388]
8. clickhouse-client(DB::AsynchronousBlockInputStream::calculate()+0x44) [0x5c4b714]
9. clickhouse-client() [0x5c4bc1a]
10. clickhouse-client(ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::_List_iterator<ThreadFromGlobalPool>)+0x1b8) [0x3194018]
11. clickhouse-client(ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::function<void ()>, int, std::optional<unsigned long>)::{lambda()#3}>(void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::function<void ()>, int, std::optional<unsigned long>)::{lambda()#3}&&)::{lambda()#1}::operator()() const+0x28) [0x31945f8]
12. clickhouse-client(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1b8) [0x3191c88]
13. clickhouse-client() [0x76cc0ff]
14. /lib64/libpthread.so.0(+0x7dd5) [0x7f8c08f9cdd5]
15. /lib64/libc.so.6(clone+0x6d) [0x7f8c089c4b3d]
 (version 19.13.3.26)

**Comment by filimonov** [comment]
Can you show a sample row of data?

**Comment by xuxudede** [comment]
Has been resolved, thank you！

**Comment by slimtom95** [comment]
Hi @xuxudede would you like to share more how you guys resolve this issue? I got this same exception, but the data caused it is not available
