### ISSUE TITLE
toLocalTime function

### ISSUE THREAD

**Issue by bseng** [yandex/ClickHouse#68]
Hi,

Can we add a toTimeZone function that takes a timezone parameter?

so if I want to convert any datetime to a timezone I can just do toTimeZone(datetime, "AST") or toTimeZone(datetime, "+4:00") and return the datetime.

**Comment by alexey-milovidov** [comment]
In fact, time zones are already supported.
(it is not covered in english version of documentation)

To do transformations on DateTime in given time zone, pass second argument with time zone name:

```
SELECT
    toDateTime('2016-06-15 23:00:00') AS time,
    toDate(time) AS date_local,
    toDate(time, 'Asia/Yekaterinburg') AS date_yekat,
    toString(time, 'US/Samoa') AS time_samoa

┌────────────────time─┬─date_local─┬─date_yekat─┬─time_samoa──────────┐
│ 2016-06-15 23:00:00 │ 2016-06-15 │ 2016-06-16 │ 2016-06-15 09:00:00 │
└─────────────────────┴────────────┴────────────┴─────────────────────┘
```

To format DateTime in given time zone:
`toString(now(), 'Asia/Yekaterinburg')`

To get unix timestamp for string with datetime in specified time zone:
`toUnixTimestamp('2000-01-01 00:00:00', 'Asia/Yekaterinburg')`

**Comment by bseng** [comment]
Thanks only if I know Russian

**Comment by bseng** [comment]
#69 I've added those to the english documentation.

**Comment by bseng** [comment]
Sorry can we add this function to toDateTime as well so we can do 
`toDateTime(datetime, 'US/Samoa')`

rather than 
`toDateTime(toString(datetime, 'US/Samoa'))`

**Comment by alexey-milovidov** [comment]
It has no clear semantic.

DateTime is represented and stored in database as unix timestamp internally.
As you know, unix timestamp is time zone independent.

Time zone matters only when value of DateTime type is formatted as String (or parsed from String),
either when data is output with text format or when using toString function.
For this transform, local time is used by default, but you could specify another time zone in second argument of toString function.

So, it seems that DateTime has time zone, but it really doesn't.

What you could achieve, is to create "fake DateTime", which stores such unix timestamp internally, that when formatted with default (local) time zone, will give you string with YYYY-MM-DD hh:mm:ss in another time zone. It is rather difficult for understanding, I don't recommend this solution.

**Comment by bseng** [comment]
yeah okay.

I'm asking because most of the time when you query the tables regarding timezone you always want to do analysis on it. e.g. `toHour(toDateTime(toString(datetime,'US/Samoa')))` and seems likes toString first and toDateTime complicated the operations.

**Comment by alexey-milovidov** [comment]
All functions like `toHour` allow to pass time zone as second argument:
`toHour(datetime, 'US/Samoa')`

**Comment by bseng** [comment]
ah sweet, too good!

**Comment by adokukin** [comment]
@alexey-milovidov 

> To get unix timestamp for string with datetime in specified time zone:
> toUnixTimestamp('2000-01-01 00:00:00', 'Asia/Yekaterinburg')

Which version of clickhouse-sever does that? I just upgraded clickhouse-server-common to version 1.1.54362 and server responds with "DB::Exception: Number of arguments for function toUnixTimestamp doesn't match: passed 2, should be 1.."
