### ISSUE TITLE
Cannot filter result of WITH ROLLUP from subquery using WHERE

### ISSUE THREAD

**Issue by simPod** [yandex/ClickHouse#6803]
```sql
CREATE TABLE test (
    attr  String,
    value UInt32,
    dt    DateTime
)
    ENGINE = Memory;

INSERT INTO test
VALUES ('S100', 10, 1),
    ('S101', 15, 1),
    ('S102', 80, 1)
;


SELECT *
FROM (
      SELECT dt, attr, sum(value) AS sum
      FROM test
      GROUP BY dt, attr
      WITH ROLLUP
    )
where dt is not null
```

I'm getting this

```
dt	attr	sum
	""	105
1970-01-01 00:00:01	""	105
1970-01-01 00:00:01	S102	80
1970-01-01 00:00:01	S100	10
1970-01-01 00:00:01	S101	15
```

But I'd expect this
```
dt	attr	sum
1970-01-01 00:00:01	""	105
1970-01-01 00:00:01	S102	80
1970-01-01 00:00:01	S100	10
1970-01-01 00:00:01	S101	15
```

**Comment by den-crane** [comment]
Or `WHERE dt != 0`
or `dt    Nullable(DateTime)` + `where dt is not null`

**Comment by simPod** [comment]
Ah, Datagrip displayed it as null
![image](https://user-images.githubusercontent.com/327717/64191941-e3386780-ce79-11e9-8ae2-709173e04f56.png)


thanks

**Comment by den-crane** [comment]
> Ah, Datagrip displayed it as null
> ![image](https://user-images.githubusercontent.com/327717/64191941-e3386780-ce79-11e9-8ae2-709173e04f56.png)
> 
> thanks

OK. I would open a ticket in Datagrip support.

**Comment by simPod** [comment]
Not a bug then. Thanks for quick response.
