### ISSUE TITLE
groupBitmap vs length(bitmapToArray())

### ISSUE THREAD

**Issue by joebling** [yandex/ClickHouse#6818]
`
select 
    groupBitmap(toUInt32(uid)) dau
from qmkg_abtest.fd_qmkg_abtest_kboss_user_locate
where ftime = '2019-08-29'
`
41608324

`
select 
    length(bitmapToArray(nuid_bitmap)) as dau
from 
(
    select 
        groupBitmapMergeState(uid_bitmap) as nuid_bitmap  
    from qmkg_abtest.fd_qmkg_abtest_kboss_user_locate_bitmap 
    where ftime = '2019-08-29'
) 
`
22393354

I don't  why. would someone tell me the reason?

**Comment by alexey-milovidov** [comment]
CC @yuzhichang

**Comment by yuzhichang** [comment]
@joebling, I have the following quesiton?
- What's the relationship between `fd_qmkg_abtest_kboss_user_locate` and  `fd_qmkg_abtest_kboss_user_locate_bitmap`? 
- Is `uid` an UInt32 column? 
- Can you try following query?
`select bitmapCardinality(groupBitmapMergeState(uid_bitmap)) as nuid_bitmap from qmkg_abtest.fd_qmkg_abtest_kboss_user_locate_bitmap where ftime = '2019-08-29' `

**Comment by joebling** [comment]
@yuzhichang 
That is how i create table and bitmap table:

CREATE TABLE qmkg_abtest.fd_qmkg_abtest_kboss_user_locate 
(`ftime` Date COMMENT '',
 `env_type` String COMMENT '',
 `key` String,
 `platform` Int64 COMMENT '',
 `account_source` Int64 COMMENT '',
 `app_ver` String COMMENT '',
 `app_ver_id` String,
 `uid` Int64,
 `str6` String,
 `statistics_type` Int64,
 `data_source` Int32,
 `module_id` String COMMENT '',
 `group_id` String COMMENT ''
 ) ENGINE = Distributed(athena,
 qmkg_abtest,
 fd_qmkg_abtest_kboss_user_locate_local,
 rand())
 ;
 
CREATE MATERIALIZED VIEW qmkg_abtest.fd_qmkg_abtest_kboss_user_locate_bitmap 
(`ftime` Date COMMENT 'yyyymmdd',
 `env_type` String COMMENT '',
 `key` String,
 `platform` Int64 COMMENT '',
 `account_source` Int64 COMMENT '',
 `app_ver` String COMMENT '',
 `str6` String,
 `statistics_type` Int64,
 `data_source` Int32,
 `module_id` String COMMENT '',
 `group_id` String COMMENT '',
 `uid_bitmap` AggregateFunction(groupBitmap,UInt64)
 ) ENGINE = AggregatingMergeTree() 
PARTITION BY ftime 
ORDER BY (ftime,env_type,key,platform,account_source,
 app_ver, str6, statistics_type, data_source, module_id, group_id) 
 SETTINGS index_granularity = 8192 AS SELECT ftime,
 env_type,
 key,
 platform,
 account_source,
 app_ver,
 str6,
 statistics_type,
 data_source,
 module_id,
 group_id,
 groupBitmapState(toUInt64(uid)) AS uid_bitmap 
 FROM qmkg_abtest.fd_qmkg_abtest_kboss_user_locate 
 GROUP BY 
 ftime,
 env_type,
 key,
 platform,
 account_source,
 app_ver,
 str6,
 statistics_type,
 data_source,
 module_id,
 group_id
 ;

**Comment by joebling** [comment]
Another question:

#1. 
select 
    ftime, 
    bitmapCardinality(uid_bitmap) dau 
from 
(
    select 
        ftime,
        groupBitmapState(toUInt64(uid)) as uid_bitmap
    from qmkg_abtest.fd_qmkg_abtest_kboss_user_locate
    group by ftime 
) t  
---
2019-08-26	41767618
2019-08-27	42019433
2019-08-28	41781866

#2. 
select 
    ftime,
    groupBitmap(toUInt64(uid)) dau
from qmkg_abtest.fd_qmkg_abtest_kboss_user_locate
group by ftime 
---
2019-08-26	41767618
2019-08-27	42019433
2019-08-28	41781866

#3.
select 
    ftime, 
    bitmapCardinality(uid_bitmap) as dau
from 
(
    select 
        ftime,
        groupBitmapMergeState(uid_bitmap) as uid_bitmap  
    from qmkg_abtest.fd_qmkg_abtest_kboss_user_locate_bitmap
    group by ftime 
) t

2019-09-01	29888430
2019-09-04	6480312

#1 = #2 != #3 
That is very strange.
From aboving, we know how table fd_qmkg_abtest_kboss_user_locate_bitmap formed.

**Comment by yuzhichang** [comment]
Your usage of `view of distributed table` looks  bad. The idiomatic way is to setup a view for the local table on every node， then setup a distributed view for those local views. See [this](https://github.com/yandex/ClickHouse/issues/467) for reference.

**Comment by joebling** [comment]
> Your usage of `view of distributed table` looks bad. The idiomatic way is to setup a view for the local table on every node， then setup a distributed view for those local views. See [this](https://github.com/yandex/ClickHouse/issues/467) for reference.

thank you, it works
