### ISSUE TITLE
Is there a way to read bin and mark files in clikchouse 

### ISSUE THREAD

**Issue by kainever7** [yandex/ClickHouse#6830]
Is there a way to read bin and mark files in clikchouse

**Comment by blinkov** [comment]
There were some examples in this talk (slides are in description), but most of it is in Russian: https://www.youtube.com/watch?v=7pyNmackUTw

**Comment by filimonov** [comment]
https://stackoverflow.com/questions/57801513/is-there-a-way-to-read-bin-and-mark-files-in-clickhouse/57813669#57813669

**Comment by kainever7** [comment]
> There were some examples in this talk (slides are in description), but most of it is in Russian: https://www.youtube.com/watch?v=7pyNmackUTw

Russian..oh...no...  Do you have it in English?

**Comment by filimonov** [comment]
Mark files has quite simple structure, while bin files structure is quite complicated. 

The ClickHouse is opensource.

Please read the sources, there is no better way or step-by-step instructions.

The best way to read clickhouse files is to read it with ClickHouse.

If you have some concrete questions - please ask, but in current form it's too general (like "how to use computer").
