### ISSUE TITLE
HTTPConnection metric does not return consistent answer with different interface.

### ISSUE THREAD

**Issue by etah000** [yandex/ClickHouse#6844]
Version info:
ClickHouse client version 19.11.7.40.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 19.13.3 revision 54425.

with DBeaver 6.0.3, I tried the following query:
`  select * from system.metrics where metric like '%Connection';
`
it returned:  

TCPConnection	1	Number of connections to TCP server (clients with native interface)
HTTPConnection	1	Number of connections to HTTP server
InterserverConnection	0	Number of connections from other replicas to fetch parts

but with command line, it returned: 

┌─metric────────────────┬─value─┬─description─────────────────────────────────────────────────────────┐
│ TCPConnection         │     1 │ Number of connections to TCP server (clients with native interface) │
│ HTTPConnection        │     0 │ Number of connections to HTTP server                                │
│ InterserverConnection │     0 │ Number of connections from other replicas to fetch parts            │
└───────────────────────┴───────┴─────────────────────────────────────────────────────────────────────┘

The number of "HTTPConnection" is not equal to each other from different user interface!

**Comment by abyss7** [comment]
Because command-line doesn't use HTTP interface? Please describe your scenario better, in steps.

**Comment by etah000** [comment]
The same metric query should return the same result no matter what network protocol it uses. DBeaver uses http-based jdbc and clickhouse-client uses tcp. When both clients connect to the server, the query should return "httpconnection: 1; tcpconnection:1", but the result for "clickhouse-client" gets "httpconnection: 0".

**Comment by den-crane** [comment]
@etah000 Because HTTP connections are very short. Just execute long running SQL in DBeaver and check `select sleep(3) from numbers(20) settings max_block_size=1`

`SELECT value
FROM system.metrics
WHERE metric LIKE '%HTTPConnection%'

┌─value─┐
│     1 │
└───────┘`

**Comment by alexey-milovidov** [comment]
@etah000 What is `snowball-client` and where to obtain it?

**Comment by etah000** [comment]
> @etah000 What is `snowball-client` and where to obtain it?

Sorry, just a typo, it should be "ClickHouse client" .

**Comment by etah000** [comment]
@den-crane  I am a little confused.  You mean that even a  jdbc-based GUI client keeps a connection session to a Clickhouse server, but actually it has no lasting long connection to the server.  The connection is valid/establed only when it submits a query. After it gets the result, it disconnects the connection. 

Is my understanding correct?  So there is no long connection and session management for http-based jdbc connection.

**Comment by den-crane** [comment]
>but actually it has no lasting long connection to the server

yes.

>Is my understanding correct? 

JDBC creates a new HTTP connection for every query.

But there are CH sessions (even JDBC) https://clickhouse.yandex/docs/en/interfaces/http/ . You can set through JDBC the session_id=.... and  have one session for different queries (different http connections).
