### ISSUE TITLE
Clickhouse client results in groups – what does it mean?

### ISSUE THREAD

**Issue by simPod** [yandex/ClickHouse#6860]
I sometimes get results for a query run via clickhouse-client separated in groups

![image](https://user-images.githubusercontent.com/327717/64480379-c75cfa80-d1c6-11e9-9d1b-3486c7e529b7.png)

I was just curious what does it mean? Why are there multiple blocks with results?

**Comment by den-crane** [comment]
Yes, blocks. Try:

select number from numbers(10);

select number from numbers(10) settings max_block_size=1;

 select number from numbers(10) settings max_block_size=1 format PrettyCompactMonoBlock;

**Comment by simPod** [comment]
Oh I see. Thanks for quick response!
