### ISSUE TITLE
Altinity version vs Git version

### ISSUE THREAD

**Issue by MahmoudGoda0** [yandex/ClickHouse#6863]
Hi Team, Hope you are fine, I have a question please, I receive email from ALTINITY team, saying that "new 'Altinity Stable’ release 19.11.8! ", But when i install latest stable version from main branch (http://repo.yandex.ru/clickhouse/deb/stable/ main/), its 19.13.3.26, So what is the diff between Altinity team releases and git releases please, I'm expecting its the same team ? or ?

**Comment by cameronbraid** [comment]
I'd like to know the same

**Comment by filimonov** [comment]
Altinity marks some version as stable after collecting feedback, analizing known issues, doing some extra tests. In general it the it's always behind the edge version (latest avaliable in from yandex repo).

In general: avoid using versions older than latest Altinity stable.

Use Yandex latest version when possible - it have all the newest features (but sometimes new features introduce new issues). If you have some issues with Yandex latest - get Altinity stable.
