### ISSUE TITLE
sql select by index:DB::Exception: Received from localhost:9000. DB::Exception: Bad size of marks file

### ISSUE THREAD

**Issue by 80631004** [yandex/ClickHouse#6864]
add second index success,but select meet error:
DB::Exception: Received from localhost:9000. DB::Exception: Bad size of marks file

following is log step:

izwz96niist70p1dpt8wpoz :) alter table pos_stockledger_local add index idx_stockledgerlocal_itemcode ItemCode TYPE ngrambf_v1(2, 512, 4, 7) GRANULARITY 64;

ALTER TABLE pos_stockledger_local
    ADD INDEX 
    idx_stockledgerlocal_itemcode ItemCode TYPE ngrambf_v1(2, 512, 4, 7) GRANULARITY 64

Ok.

0 rows in set. Elapsed: 0.022 sec. 

izwz96niist70p1dpt8wpoz :) OPTIMIZE TABLE pos_stockledger_local  FINAL;

izwz96niist70p1dpt8wpoz :) select * from pos_stockledger_local t where t.StoreId='69dc427a881b44d9801c16ae224095e3' and t.TransDate>='2019-07-01' and t.ItemCode like '%6925303721039%' limit 0,10;

SELECT *
FROM pos_stockledger_local AS t
WHERE (t.StoreId = '69dc427a881b44d9801c16ae224095e3') AND (t.TransDate >= '2019-07-01') AND (t.ItemCode LIKE '%6925303721039%')
LIMIT 0, 10

Received exception from server (version 19.13.3):
Code: 246. DB::Exception: Received from localhost:9000. DB::Exception: Bad size of marks file '/var/lib/clickhouse/data/default/pos_stockledger_local/201907_1_21299_7/skp_idx_idx_stockledgerlocal_itemcode.mrk2': 96, must be: 744. 

0 rows in set. Elapsed: 0.243 sec. 

**How to reproduce**
* Which ClickHouse server version to use
 19.13.3.26

**Comment by abyss7** [comment]
Fixed in 19.14+ with https://github.com/yandex/ClickHouse/pull/6748
