### ISSUE TITLE
Use MergeTree key when locating rows on `key_column IN (subquery)` conditions

### ISSUE THREAD

**Issue by valyala** [yandex/ClickHouse#687]
### The issue

Let the following `MergeTree` table exist:

```sql
CREATE TABLE events (
    EventID UInt8,
    EventDate Date,
    ClientID UInt32,
    Payload String
) Engine = MergeTree(EventDate, (EventID, EventDate, ClientID), 8192);
```
    
Clickhouse successfully uses `MergeTree` key for `key_column IN (static_list)` conditions if `key_column` belongs to the key:

```sql
SELECT ClientID, count(*) FROM events WHERE ClientID IN (1,2,3,4)
```

But `key_column IN (subquery)` or `key_column GLOBAL IN (subquery)` disables key usage and leads to full scan:

```sql
SELECT
    ClientID,
    count(*)
FROM events
WHERE
    ClientID IN (
        SELECT DISTINCT ClientID
        FROM events WHERE ClientID IN (1,2,3,4) AND EventDate = today()
    )
```

```sql
SELECT
    ClientID,
    count(*)
FROM events_distributed
WHERE
    ClientID GLOBAL IN (
        SELECT DISTINCT ClientID
        FROM events_distributed WHERE ClientID IN (1,2,3,4) AND EventDate = today()
    )
```

### Expected behavior

It would be great if `clickhouse` could use `MergeTree` key when locating rows for `key_column IN (subquery)` conditions.

**Comment by ztlpn** [comment]
Yes, that would be great! Unfortunately this feature requires substantial reworking of the query execution engine. The good news is that we actually plan to do it so stay tuned.

**Comment by inv2004** [comment]
I have created duplicate: https://github.com/yandex/ClickHouse/issues/932

**Comment by Maxistua** [comment]
Any updates on this?

**Comment by alexey-milovidov** [comment]
Implemented.
