### ISSUE TITLE
with totals modifier  support not only group by 

### ISSUE THREAD

**Issue by peaksnail** [yandex/ClickHouse#6870]
hi 
has with totals modifier support not only group by?

I can do the sql 
```
select field_a,field_b from table with totals
```
It can return the result 
```
value_a     value_b
value_a1    value_b1
...

totals
count  fields_a_sum  field_b_sum
10        100                200
```

**Comment by filimonov** [comment]
In common case it's impossible to calculate the sums (just imagine that field_a is `String` or `Array`). 

There relates feature called extremes:  https://clickhouse.yandex/docs/en/query_language/select/#extreme-values

And you can always calculate that with 2 queries. 
1) `SELECT * FROM ... `
2) `SELECT count(), sum(...) FROM `

**Comment by alexey-milovidov** [comment]
It's difficult to figure out what aggregate function do you want.
Hardcoding `sum` aggregate function is not a good way to do.
