### ISSUE TITLE
about the LIMIT  keyword when query in parallel 

### ISSUE THREAD

**Issue by peaksnail** [yandex/ClickHouse#6903]
hi
I have something question about the LIMIT keyword
If I execute the sql
```
select * from table where create_date>=today()-10 and create_date<today() limit 10
```
And there  has two data parts in the disk,  parts one and part two. So it will query data in parallel with two thread

I assume that there has 9 rows target data in parts one and 2 rows target data in parts two

What will be  the result?

It will return the 9 rows data in parts one plus the first target data or the 2 rows target data(execute faster than another one) in parts two and 8 rows target data in parts  one

thanks

**Comment by filimonov** [comment]
Please consider that behaviour non determenistic, and don't rely on that. You've requested SOME 10 row and you get some. 

If you need 10 rows by some order, use ORDER BY.

**Comment by peaksnail** [comment]
thanks, I just want to get the data by sorted key, and the create_date is the sorted key.

If using as a time series db,all data is inserted by order create_date, when I want to get the first 10 row, so  should I always use ORDER BY create_date limit 10?

And I find that the performance is bad to ORDER BY with large data

**Comment by alexey-milovidov** [comment]
Performance of ORDER BY table's sorting key has been improved since version 19.14 if you enable the `optimize_read_in_order` setting.

**Comment by alexey-milovidov** [comment]
Please try the new version and the setting and tell us the results.
