### ISSUE TITLE
Error fetching data from materialized view

### ISSUE THREAD

**Issue by buremba** [yandex/ClickHouse#7]
I loaded example `ontime` dataset and created a materialized view with the following definition:

```
CREATE MATERIALIZED VIEW basic ENGINE = AggregatingMergeTree(FlightDate, Carrier, 8192) AS
SELECT
    FlightDate,
    Carrier,
    uniqState(FlightNum) AS Users
FROM ontime
GROUP BY
    FlightDate,
    Carrier
```

Then I inserted data to `ontime` database and tried to query `basic` table with `SELECT * FROM basic LIMIT 10` via the clickhouse-client

The output of the query is:

> Exception on client:
> Code: 89. DB::Exception: QuickLZ compression method is disabled: while receiving packet from localhost:9000, ::1

The problem is that I try to fetch the aggregation state stored in `User` column. I can execute the following query successfully: `select uniqMerge(Users) from basic` since the output of uniqMerge is a numeric value. I think the server should throw a more descriptive error or return the aggregation state as binary type.

**Comment by alexey-milovidov** [comment]
When you `SELECT *`, you select Users column, which have (unusual) type `AggregateFunction(uniq, String)`.
Something is wrong with transferring values of this type to client and it triggers a bug.

By the way, if it works correctly, it would display serialized state of aggregate function in binary form - not very informative.

Aggregation states is intended to be merged, like this:
```
:) SELECT FlightDate, Carrier, uniqMerge(Users) FROM basic GROUP BY FlightDate, Carrier LIMIT 10

SELECT 
    FlightDate, 
    Carrier, 
    uniqMerge(Users)
FROM basic
GROUP BY 
    FlightDate, 
    Carrier
LIMIT 10

┌─FlightDate─┬─Carrier─┬─uniqMerge(Users)─┐
│ 2010-12-04 │ OO      │             1303 │
│ 1988-04-03 │ PS      │              407 │
│ 1999-12-01 │ NW      │             1284 │
│ 1996-03-05 │ TW      │              514 │
│ 1989-11-04 │ US      │             1889 │
│ 1998-07-01 │ UA      │             1788 │
│ 2015-02-02 │ OO      │             1460 │
│ 2010-02-01 │ DL      │             1797 │
│ 1999-11-02 │ DL      │             1859 │
│ 1992-02-03 │ AS      │              164 │
└────────────┴─────────┴──────────────────┘

10 rows in set. Elapsed: 0.032 sec. Processed 4.89 thousand rows, 1.50 MB (151.61 thousand rows/s., 46.43 MB/s.)
```

And as you see, SELECT-ing result of uniqMerge works correct.

**Comment by alexey-milovidov** [comment]
> Something is wrong with transferring values of this type to client and it triggers a bug.

Fix is committed and scheduled for next release.
