### ISSUE TITLE
Exception: Cannot compare std

### ISSUE THREAD

**Issue by viputh6** [yandex/ClickHouse#7010]
Below error message continuously reported in clickhouse-server.err.log. I guess below exception thrown from clickhouse background component. because there is no insert during that time.

please help me to fix this issue. 

 (version 19.11.4.24 (official build))

Error:

2019.09.20 08:21:44.715804 [ 7 ] {} <Error> void DB::BackgroundProcessingPool::threadFunction(): Code: 169, e.displayText() = DB::Exception: Cannot compare std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > with DB::Null, Stack trace:

0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x30) [0x7d2c950]
1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x25) [0x3bb8975]
2. /usr/bin/clickhouse-server(bool DB::FieldVisitorAccurateLess::cantCompare<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, DB::Null>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Null const&) const+0x101) [0x3952963]
3. /usr/bin/clickhouse-server(std::decay_t::ResultType DB::applyVisitor<DB::FieldVisitorAccurateLess, DB::Field const&, DB::Field const&>(DB::FieldVisitorAccurateLess&&, DB::Field const&, DB::Field const&)+0x863) [0x6edbda3]
4. /usr/bin/clickhouse-server(DB::KeyCondition::checkInParallelogram(std::vector<DB::Range, std::allocator<DB::Range> > const&, std::vector<std::shared_ptr<DB::IDataType const>, std::allocator<std::shared_ptr<DB::IDataType const> > > const&) const+0x4fa) [0x6ed585a]
5. /usr/bin/clickhouse-server(DB::MergeTreeDataSelectExecutor::readFromParts(std::vector<std::shared_ptr<DB::MergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::MergeTreeDataPart const> > >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, DB::SelectQueryInfo const&, DB::Context const&, unsigned long, unsigned int, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, long, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, long> > > const*) const+0x1338) [0x6f31be8]
6. /usr/bin/clickhouse-server(DB::StorageFromMergeTreeDataPart::read(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, DB::SelectQueryInfo const&, DB::Context const&, DB::QueryProcessingStage::Enum, unsigned long, unsigned int)+0xea) [0x6f09f8a]
7. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::InterpreterSelectQuery::Pipeline&, std::shared_ptr<DB::PrewhereInfo> const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x1fda) [0x6c2b96a]
8. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::executeImpl(DB::InterpreterSelectQuery::Pipeline&, std::shared_ptr<DB::IBlockInputStream> const&, bool)+0x794) [0x6c2e8a4]
9. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::execute()+0x55) [0x6c310e5]
10. /usr/bin/clickhouse-server(DB::MutationsInterpreter::isStorageTouchedByMutations() const+0x3b5) [0x7290d15]
11. /usr/bin/clickhouse-server(DB::MergeTreeDataMergerMutator::mutatePartToTemporaryPart(DB::FutureMergedMutatedPart const&, std::vector<DB::MutationCommand, std::allocator<DB::MutationCommand> > const&, DB::MergeListEntry&, DB::Context const&)+0x29d) [0x6f070ad]
12. /usr/bin/clickhouse-server(DB::StorageMergeTree::tryMutatePart()+0x6c2) [0x6e476e2]
13. /usr/bin/clickhouse-server(DB::StorageMergeTree::backgroundTask()+0x1bc) [0x6e47afc]
14. /usr/bin/clickhouse-server(DB::BackgroundProcessingPool::threadFunction()+0x544) [0x6ec2724]
15. /usr/bin/clickhouse-server() [0x6ec309a]
16. /usr/bin/clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1a6) [0x768a766]
17. /usr/bin/clickhouse-server() [0xb7fec00]
18. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f2464be06db]
19. /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f246436788f]
 (version 19.11.4.24 (official build))

**Comment by filimonov** [comment]
Is there some mutation (update/delete) is executed? Can you check if there are some failed mutation in `system.mutations`?

**Comment by viputh6** [comment]
Yes. you are right. it is fixed after killing those failed mutation.

Thanks a lot filimonov
