### ISSUE TITLE
https://clickhouse.yandex/ is broken

### ISSUE THREAD

**Issue by andreybolonin** [yandex/ClickHouse#717]
http://i.imgur.com/MXyBkT3.jpg

**Comment by khrisanfov** [comment]
It works fine

**Comment by alexey-milovidov** [comment]
On "traffic by minute" chart, we see no issues.
Probably, temporary connectivity problems.
Tell me if this issue still present.

**Comment by andreybolonin** [comment]
hmm. its interesting.
May be my ISP not support very fresh domain name like .yandex

**Comment by andreybolonin** [comment]
@alexey-milovidov all works fine via 3g.

But.

```
sudo apt-get install clickhouse-server-common clickhouse-client
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 clickhouse-client : Depends: clickhouse-server-base (= 1.1.54198) but it is not going to be installed
 clickhouse-server-common : Depends: clickhouse-server-base (= 1.1.54198) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by alexey-milovidov** [comment]
We have no pre-built packages for 17.04.
You could build packages from sources according to the instruction: 
https://github.com/yandex/ClickHouse/blob/master/doc/build.md

**Comment by andreybolonin** [comment]
thx

**Comment by andreybolonin** [comment]
http://andreybolonin.com/clickhouse/clickhouse-client_1.1.54197_amd64.deb
http://andreybolonin.com/clickhouse/clickhouse-compressor_1.1.54197_amd64.deb
http://andreybolonin.com/clickhouse/clickhouse-server-base_1.1.54197_amd64.deb
http://andreybolonin.com/clickhouse/clickhouse-server-common_1.1.54197_amd64.deb

Working fine for ubuntu 17.04

**Comment by seufagner** [comment]
I'm using EC2 ubuntu 16.04 and got the error

ubuntu@ip-172-30-10-137:~$ sudo apt-get install clickhouse-server-base clickhouse-server-common clickhouse-client -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 clickhouse-server-base : Depends: libc6 (< 2.20) but 2.23-0ubuntu9 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by VladislavPershin** [comment]
@seufagner,  16.04 ubuntu:
sed -i 's/trusty/xenial/' /etc/apt/sources.list.d/clickhouse.list
apt-get update
apt-get install clickhouse-server-base clickhouse-server-common clickhouse-client -y
