### ISSUE TITLE
[HELP] Clickhouse does not start in Docker container

### ISSUE THREAD

**Issue by andreevlex** [yandex/ClickHouse#721]
Good afternoon. Can't run test server. 

Command:
`docker run -d --name some-clickhouse-server2 --ulimit nofile=262144:262144 yandex/clickhouse-server`

Logs:
```log
Include not found: clickhouse_remote_servers
Include not found: clickhouse_compression
2017.04.22 12:58:53.637640 [ 1 ] <Warning> Application: Logging to console
2017.04.22 12:58:53.642657 [ 1 ] <Information> : Starting daemon with revision 54198
2017.04.22 12:58:53.642918 [ 1 ] <Information> Application: starting up
2017.04.22 12:58:53.651384 [ 1 ] <Debug> Application: rlimit on number of file descriptors is 262144
2017.04.22 12:58:53.651416 [ 1 ] <Debug> Application: Initializing DateLUT.
2017.04.22 12:58:53.651424 [ 1 ] <Trace> Application: Initialized DateLUT with time zone `Zulu'.
2017.04.22 12:58:53.653246 [ 1 ] <Debug> Application: Configuration parameter 'interserver_http_host' doesn't exist or exists and empty. Will use '693693910db0' as replica host.
2017.04.22 12:58:53.653461 [ 1 ] <Debug> ConfigReloader: Loading config `/etc/clickhouse-server/users.xml'
2017.04.22 12:58:53.657915 [ 1 ] <Warning> ConfigProcessor: Include not found: networks
2017.04.22 12:58:53.657954 [ 1 ] <Warning> ConfigProcessor: Include not found: networks
2017.04.22 12:58:53.659692 [ 1 ] <Information> Application: Loading metadata.
2017.04.22 12:58:53.660188 [ 1 ] <Information> DatabaseOrdinary (default): Total 0 tables.
2017.04.22 12:58:53.660600 [ 1 ] <Debug> Application: Loaded metadata.
2017.04.22 12:58:53.660818 [ 1 ] <Information> DatabaseOrdinary (system): Total 0 tables.
2017.04.22 12:58:53.666024 [ 1 ] <Information> Application: Shutting down storages.
2017.04.22 12:58:53.666145 [ 1 ] <Debug> Application: Shutted down storages.
2017.04.22 12:58:53.667361 [ 1 ] <Debug> Application: Destroyed global context.
2017.04.22 12:58:53.667829 [ 1 ] <Error> Application: Net Exception: Cannot assign requested address: [::1]:8123
2017.04.22 12:58:53.667853 [ 1 ] <Information> Application: shutting down
2017.04.22 12:58:53.667861 [ 1 ] <Debug> Application: Uninitializing subsystem: Logging Subsystem
2017.04.22 12:58:53.667950 [ 2 ] <Information> BaseDaemon: Stop SignalListener thread
```

**Comment by alexey-milovidov** [comment]
Good evening.
Seems that your container has no support for IPv6.
Try to edit `/etc/clickhouse-server/config.xml` and set value of `<listen_host>` to `0.0.0.0` to listen wildcard IPv4 address. If there are more than one `<listen_host>`, leave just one.

**Comment by andreevlex** [comment]
Thank you. Understood. Launched on ipv4

**Comment by sjoerdmulder** [comment]
@alexey-milovidov Shouldn't we start by default on ipv4? Seems this made the change from ipv4 to ipv6: https://github.com/yandex/ClickHouse/commit/e552983db52d9c0146183fea613fbc451d565f09

**Comment by sjoerdmulder** [comment]
Hmmm.. it seems docker has changed something. I have one host with docker version 17.04.0-ce that doesn't work anymore with ipv6 addresses giving the `Cannot assign requested address: [::1]` errors. but the host with docker version 1.12.3 still works. both have the ipv6 disabled for the bridge network.

**Comment by LavinJ** [comment]
> Good evening.
> Seems that your container has no support for IPv6.
> Try to edit `/etc/clickhouse-server/config.xml` and set value of `<listen_host>` to `0.0.0.0` to listen wildcard IPv4 address. If there are more than one `<listen_host>`, leave just one.

I'm specifing that `<listen_host>` but I can't spawn a container with ClickHouse

**Comment by kkrgwbj** [comment]
I also encountered the same problem, changing listern_host to 0.0.0.0 also failed.clickhouse version is 18

@alexey-milovidov  @bamx23
