### ISSUE TITLE
Docu lacks example for insert via clickhouse-client

### ISSUE THREAD

**Issue by shinguz** [yandex/ClickHouse#73]
echo -ne "1, 'some text', '2016-08-14 00:00:00'\n2, 'some more text', '2016-08-14 00:00:01'" | clickhouse-client --database=test --query="INSERT INTO test FORMAT CSV";

cat <<_EOF | clickhouse-client --database=test --query="INSERT INTO test FORMAT CSV";
3, 'some text', '2016-08-14 00:00:00'
4, 'some more text', '2016-08-14 00:00:01'
_EOF

cat file.csv | clickhouse-client --database=test --query="INSERT INTO test FORMAT CSV";

**Comment by alexey-milovidov** [comment]
Added your examples.
https://github.com/yandex/ClickHouse/commit/9b07e449146f4492b84f7106818c877c9c4b6adc
