### ISSUE TITLE
000000 doesn't look like month

### ISSUE THREAD

**Issue by f1yegor** [yandex/ClickHouse#738]
By mistake inserted some data with 0000-00-00 date.

Now I'm unable to drop such partition. 
```
alter table hits drop partition '000000';

Invalid partition format: 000000 doesn't look like month
```

**Comment by alexey-milovidov** [comment]
Check `system.parts` table. Probably you have data in partition 197001.
Note that ClickHouse displays out-of-range date as 0000-00-00, but it is usually start of epoch.

**Comment by f1yegor** [comment]
you are right, thanks
