### ISSUE TITLE
Clickhouse refused to work with multidimension array from sub select

### ISSUE THREAD

**Issue by erebus1** [yandex/ClickHouse#742]
assume uid is a string column in table page_visit, then:
`SELECT arrayMap(uds -> uds, 
    (
            SELECT groupArray(uids)
            FROM 
            (
                SELECT groupArray(uid) AS uids
                FROM 
                (
                    SELECT *
                    FROM page_visit 
                    LIMIT 10
                ) 
                GROUP BY date
                ORDER BY date ASC
            ) 
    ))
`
throw: Type inference of multidimensional arrays is not supported. 
but this code works perfectly:
`select arrayMap(x -> x, [[1,2], [3,4]])`

And as I can see from this file:
https://github.com/yandex/ClickHouse/blob/master/dbms/src/DataTypes/FieldToDataType.cpp#L162
The problem, is that CH can't choose datatype for returned multidimensional array.

But why we can't just ensure, that all elements in inner arrays are of string type, and set string type to whole 2d array?
Or may be it could be solved other way.

It would be very useful to have opportunity to operate with multidimensional arrays from subqueries.

**Comment by alexey-milovidov** [comment]
Fixed in latest version.
