### ISSUE TITLE
Что за команда POST в документации?

### ISSUE THREAD

**Issue by greenx** [yandex/ClickHouse#76]
В документации есть такие строки:

> Создаём таблицу:
> echo 'CREATE TABLE t (a UInt8) ENGINE = Memory' | POST 'http://localhost:8123/'

Вроде подразумевается, что это shell, тогда POST это команда для запуска. Опечатка?

**Comment by vladimir-vg** [comment]
Нет, это утилита /usr/bin/POST

**Comment by greenx** [comment]
В этом же параграфе речь идет о методах HTTP GET и POST, думаю, поэтому не очевидно, что в примере имеется уже ввиду утилита. (не все жеж убунтийские перловоды :) )

**Comment by alexey-milovidov** [comment]
Согласен - не очевидно (что это скрипты из пакета libwww-perl)
Лучше будет заменить все примеры на curl.
