### ISSUE TITLE
NULL pointer in DB::AggregateFunctionCount::merge

### ISSUE THREAD

**Issue by tobia** [yandex/ClickHouse#762]
Create a simple table:

```sql
CREATE TABLE test (
    x UInt32, 
    date Date MATERIALIZED toDate(0)
) ENGINE = MergeTree(date, x, 8192)
```

Insert 100k rows, of which 10k are duplicates:

```sql
INSERT INTO test 
SELECT toUInt32(number)
FROM system.numbers 
LIMIT 10000
UNION ALL 
SELECT toUInt32(number)
FROM system.numbers 
LIMIT 100000
```

Count the duplicates:

```sql
SELECT count()
FROM (
    SELECT x, count() AS num
    FROM test 
    GROUP BY x
    HAVING num > 1
) 

┌─count()─┐
│   10000 │
└─────────┘
```

Ok, now DROP and CREATE the table, try again with 20M rows (or some other large number) with the same number 10k of duplicates:

```sql
INSERT INTO test 
SELECT toUInt32(number)
FROM system.numbers 
LIMIT 10000
UNION ALL 
SELECT toUInt32(number)
FROM system.numbers 
LIMIT 20000000
```

If you run the SELECT above, the result should still be 10000, but this time the server crashes:

```
<Error> BaseDaemon: ########################################
<Error> BaseDaemon: (from thread 17) Received signal Segmentation fault (11).
<Error> BaseDaemon: Address: NULL pointer.
<Error> BaseDaemon: 1. clickhouse-server(DB::AggregateFunctionCount::merge(char*, char const*, DB::Arena*) const+0x4) [0x253ba44]
<Error> BaseDaemon: 2. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x96) [0x320d316]
<Error> BaseDaemon: 3. /lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x7f4c3a5e4184]
<Error> BaseDaemon: 4. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f4c39bffbed]
```

I'm using the latest amd64 DEB package 1.1.54213 on Ubuntu Trusty.

I get the same error on the Log engine, so it's not specific to MergeTree.

Is there any memory limit that I can try to increase?

**Comment by ludv1x** [comment]
Hi, 
I cannot reproduce the problem on my laptop and server.
Increasing the number of rows I can obtain only correct exception:
```
Received exception from server:
Code: 241. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Memory limit (for query) exceeded: would use 9.31 GiB (attempt to allocate chunk of 786432 bytes), maximum: 9.31 GiB. 
```

Can you fix number of threads (`--max_threads=1`) to make the example more reproducible?
Do you use default configs from DEB package?

**Comment by tobia** [comment]
Please ignore this issue. My server had an intermittent RAM problem. I should have checked on more than one machine!

Sorry for wasting your time.
