### ISSUE TITLE
Build fails with openssl 1.1.0

### ISSUE THREAD

**Issue by kmeaw** [yandex/ClickHouse#765]
OpenSSL 1.1.0 makes some of its structures opaque to the user program (see https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes for more details), which breaks compatibility.

**Comment by kmeaw** [comment]
One possible way to resolve this is updating bundled Poco.
I don't see any other code relying in legacy openssl APIs.

`/tmp/pkgbuilder-1000/clickhouse/src/ClickHouse-1.1.54198-stable/contrib/libpoco/Crypto/src/RSAKeyImpl.cpp: In member function ‘Poco::Crypto::RSAKeyImpl::ByteVec Poco::Crypto::RSAKeyImpl::encryptionExponent() const’:
/tmp/pkgbuilder-1000/clickhouse/src/ClickHouse-1.1.54198-stable/contrib/libpoco/Crypto/src/RSAKeyImpl.cpp:216:31: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
  return convertToByteVec(_pRSA->e);                                                                                                                     
                               ^~                                                                                                            
In file included from /usr/include/openssl/crypto.h:31:0,                                                   
                 from /tmp/pkgbuilder-1000/clickhouse/src/ClickHouse-1.1.54198-stable/contrib/libpoco/Crypto/include/Poco/Crypto/OpenSSLInitializer.h:26,
                 from /tmp/pkgbuilder-1000/clickhouse/src/ClickHouse-1.1.54198-stable/contrib/libpoco/Crypto/include/Poco/Crypto/RSAKeyImpl.h:24,                 
                 from /tmp/pkgbuilder-1000/clickhouse/src/ClickHouse-1.1.54198-stable/contrib/libpoco/Crypto/src/RSAKeyImpl.cpp:17:                     
/usr/include/openssl/ossl_typ.h:110:16: note: forward declaration of ‘RSA {aka struct rsa_st}’                            
 typedef struct rsa_st RSA;                                                                                   
                ^~~~~~                                                                                   
/tmp/pkgbuilder-1000/clickhouse/src/ClickHouse-1.1.54198-stable/contrib/libpoco/Crypto/src/RSAKeyImpl.cpp: In member function ‘Poco::Crypto::RSAKeyImpl::ByteVec Poco::Crypto::RSAKeyImpl::decryptionExponent() const’:
/tmp/pkgbuilder-1000/clickhouse/src/ClickHouse-1.1.54198-stable/contrib/libpoco/Crypto/src/RSAKeyImpl.cpp:222:31: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
  return convertToByteVec(_pRSA->d);                                                                        
`

**Comment by ludv1x** [comment]
You could disable `USE_INTERNAL_POCO_LIBRARY` CMake variable and specify path to new Poco library in `Poco_ROOT_DIR`.

**Comment by kmeaw** [comment]
Yes, that problem is fixed in newer version of Poco ( https://github.com/pocoproject/poco/commit/bfaa161c61cca06526eaf238bfdddd190381616b ). However USE_INTERNAL_POCO_LIBRARY is enabled by default and the issue will break the build if a user has a new version of openssl.
I suggest either to add the latest compatible version of openssl to contrib (and implement USE_INTERNAL_OPENSSL_LIBRARY option), or to update the bundled version of Poco.

**Comment by ludv1x** [comment]
@proller

**Comment by proller** [comment]
Already fixed.
https://github.com/yandex/ClickHouse/commit/d2d7aaac692d30ef8422774f1a8d0bd327546061

And yes, we want update bundled poco to latest version, but not right now,

**Comment by kmeaw** [comment]
Sorry, missed that -- i was validating the latest -stable tag.
I will bundle then d2d7aaa into 1.1.54198 gentoo ebuild and archlinux pkgbuild.
