### ISSUE TITLE
A malformed znode prevents ClickHouse from starting

### ISSUE THREAD

**Issue by SaltTan** [yandex/ClickHouse#780]
A few times we had a situation when ClickHouse would not start after a crash because of a malformed record in ZooKeeper. I had to remove the record manually.

Examples of malformed znodes:
```
format version: 3
create_ti-e: 217,04-05 22:51:20
source replica: sde90
block_id: 15439625176991181799_5308645922780965059
get
20170405_20170405_1668_1668_0

format version: 3
create_time: 2017-05-04 13:00:44
source repliba: �de500
block_id: 
merge
20170501_20170504_200_49083_12589
20170504_20170504_49084_49084_0
into
20170501_20170504_200_49084_12590
```

**Comment by alexey-milovidov** [comment]
"source repli**b**a" looks like random bit flip in memory.
Do you have any related messages in `dmesg` on servers with ClickHouse or on servers with ZooKeeper? Do you have ECC memory on your servers?

**Comment by SaltTan** [comment]
I didn't save those records, so I cannot tell you what exactly was there. It definitely looks like corruption. But there are no messages in dmesg, and we have ECC memory in our servers.

**Comment by alexey-milovidov** [comment]
It is very unlikely (near impossible), that single bit flips are related to software bug in ClickHouse itself.
You should suspect your hardware (example: memory on network controller).

It is also possible (but very unlikely), that you have accidentially have run zookeeper under some fuzzer, like `zzuf`.

**Comment by blinkov** [comment]
@SaltTan is this issue still relevant?

**Comment by SaltTan** [comment]
I can't remember when the last time it happened. I wouldn't say we get a lot of crashes though :)
