### ISSUE TITLE
problem with loading data

### ISSUE THREAD

**Issue by trivita** [yandex/ClickHouse#79]
i know NULL isnt supported by clickhouse. but if i have a csv with ,,, line in it. why cant clickhouse just insert data with default values?

**Comment by alexey-milovidov** [comment]
Acknowledged. Will do.

**Comment by alexey-milovidov** [comment]
It is already supported for numeric types and String. But not for Date, DateTime.

**Comment by trivita** [comment]
> It is already supported for numeric types and String. But not for Date, DateTime.

thanks, you mean the git version?

**Comment by alexey-milovidov** [comment]
> thanks, you mean the git version?

For numeric types and String, empty is parsed as zero/empty string (this behaviour was from the beginning).
Example:

```
:) CREATE TABLE test.csv (a String, b UInt64, c Int64, d String) ENGINE = Log

...

$ echo ',,,' | clickhouse-client --query="INSERT INTO test.csv FORMAT CSV"

...

:) SELECT * FROM test.csv

┌─a─┬─b─┬─c─┬─d─┐
│   │ 0 │ 0 │   │
└───┴───┴───┴───┘
```

But it is not implemented for Date, DateTime, Array and other data types.
If you have empty instead of Date/DateTime, parser will look for next field at 10/19 bytes forward, and will be confused with it.

I am going to implement the intended behaviour for Date, DateTime too.

**Comment by trivita** [comment]
ehh, yeah, but not seem to work with TabSeparatedWithNames

**Comment by alexey-milovidov** [comment]
Could you please provide complete example, because trivial examples working:

`CREATE TABLE test.tsv (a String, b UInt64, c Int64, d String) ENGINE = Log`

```
$ echo -e '\t\t\t' | clickhouse-client --query="INSERT INTO test.tsv FORMAT TabSeparated"
$ echo -ne 'a\tb\tc\td\n\t\t\t\n' | clickhouse-client --query="INSERT INTO test.tsv FORMAT TabSeparatedWithNames"
```

Maybe it works just accidently.

**Comment by pluk** [comment]
Hi.

> If you have empty instead of Date/DateTime, parser will look for next field at 10/19 bytes forward, and will be confused with it.

I have several consecutive DateTime fields and It behaves like this
`CREATE TABLE test
(
    id UInt32, 
    entity UInt8, 
    add_date DateTime, 
    mod_date DateTime, 
    date Date
) ENGINE = MergeTree(date, (id, date), `8192)``
...
`$ echo '111111,,"2017-05-15 20:07:48","2017-05-19 21:44:49",2017-05-18' | clickhouse-client --database=default --host=X.X.X.X --query="INSERT INTO test FORMAT CSV"
Code: 27. DB::Exception: Cannot parse input: expected " before:  21:44:49",2017-05-18\n: (at row 1)

Row 1:
Column 0,   name: id,       type: UInt32,   parsed text: "111111"
Column 1,   name: entity,   type: UInt8,    ERROR: text ",<DOUBLE QUOTE>2017-05-" is not like UInt8
`

**Comment by alexey-milovidov** [comment]
We have implicit default values for Date and DateTime - `0000-00-00` and `0000-00-00 00:00:00`.
The problem is not with default values, but that empty string is not parsed as default in CSV.

**Comment by sunsingerus** [comment]
Hello!

It looks like Data type is still have issues with default values while reading from CSV file.
Have the following situation right now:

1. Log table with the following fields
```
date_1 Nullable(Date)
datetime_1 Nullable(DateTime)
timestamp_1 Nullable(DateTime)`
```
CSV file
```
date_1,datetime_1,timestamp_1,tinyint_1
0000-00-00,,,
2017-10-31,2017-10-31 11:37:42,2017-10-31 11:37:43,
```
All is OK

CSV file with empty Date field

```
date_1,datetime_1,timestamp_1,tinyint_1
,,,
2017-10-31,2017-10-31 11:37:42,2017-10-31 11:37:43,
```
run
```
tail -n +2 'ttimestamp.csv' | clickhouse-client  --host=192.168.74.251 --port=9000 --user=default --query='INSERT INTO `db`.`datatypes` (`date_1`, `datetime_1`, `timestamp_1`, `tinyint_1`) FORMAT CSV'
Code: 27. DB::Exception: Cannot parse input: expected , before: 10-31,2017-10-31 11:37:42,2017-10-31 11:37:43,\r\n: (at row 1)

Row 1:
Column 0,   name: date_1,      type: Nullable(Date),     parsed text: ",,,<CARRIAGE RETURN><LINE FEED>2017-"
ERROR: garbage after Nullable(Date): "10-31,2017"
```

clickhouse-client installed of the following version
```
sudo apt list installed 'clickhouse*'
Listing... Done
clickhouse-client/unknown,now 1.1.54304 amd64 [installed]
clickhouse-common-dbg/unknown 1.1.54304 amd64
clickhouse-compressor/unknown 1.1.54304 amd64
clickhouse-server-base/unknown,now 1.1.54304 amd64 [installed,automatic]
clickhouse-server-common/unknown 1.1.54304 amd64
```

Please, advise...
Thanks!

**Comment by kmatt** [comment]
I'm also seeing the error when tab delimited data to numeric types is not parsed when column values are empty:

`ERROR: text "<TAB><TAB><TAB><TAB><TAB><TAB>5135" is not like UInt64`

**Comment by abdrakhmanov** [comment]
i have similar problem. For example:
```
CREATE TABLE `t1` (
  `c0` UInt8,
  `c1` Nullable(Date),
  `c4` Date
) ENGINE = MergeTree(c4, (c4), 8192)
```
Insert query in tabix work fine for `NULL` in second column and return error for empty value:
```
INSERT INTO t1 VALUES (1,NULL,'2018-04-01') -- OK
INSERT INTO t1 VALUES (1,,'2018-04-01') -- Cannot parse expression of type Nullable(Date) here: ,'2018-04-01')
```
Insert query in command-line doesn't work anyway:
```
#cat c.csv
1,NULL,'2018-04-01'
1,,'2018-04-01'
```
```
cat c.csv | clickhouse-client --host=clickhouse.local --query="INSERT INTO t1 FORMAT CSV"
```
```
Code: 27. DB::Exception: Cannot parse input: expected , before: -04-01\'\n1,,\'2018-04-01\'\n: (at row 1)

Row 1:
Column 0,   name: c0, type: UInt8,          parsed text: "1"
Column 1,   name: c1, type: Nullable(Date), parsed text: "NULL,<SINGLE QUOTE>2018"
ERROR: garbage after Nullable(Date): "-04-01<SINGLE QUOTE><LINE FEED>1,"

```
What am I doing wrong?

**Comment by abdrakhmanov** [comment]
More complicated example:
```
CREATE TABLE `t3` (
  `c0` UInt8,
  `c1` UInt8,
  `c2` DateTime,
  `c3` UInt32,
  `c4` UInt32,
  `c5` String,
  `c6` String,
  `c7` String,
  `c8` Nullable(Date),
  `c9` UInt8,
  `c10` UInt32,
  `c11` Date,
  `c12` String,
  `c13` DateTime,
  `c14` UInt32,
  `c15` UInt32,
  `c16` String,
  `c17` UInt32,
  `c18` UInt32,
  `c19` String,
  `c20` String,
  `c21` String,
  `c22` Nullable(Date),
  `c23` UInt8,
  `c24` UInt32,
  `c25` UInt8,
  `c26` String,
  `c27` UInt32,
  `c28` Date,
  `c29` Date,
  `c30` UInt32,
  `c31` UInt16,
  `c32` UInt8,
  `c33` UInt8,
  `c34` UInt32,
  `c35` String,
  `c36` UInt8,
  `c37` UInt8,
  `c38` UInt8,
  `c39` UInt8,
  `c40` String
) ENGINE = MergeTree(c11, (c11, c28, c29, c4, c18, c34, c15, c32, c25), 8192)
```
```
INSERT INTO t3 VALUES (4,2,'2018-04-04 09:19:02',5441337,5078196,'String1','String2','String3','2018-04-04',8,253768764,'2018-04-04','String4','2018-04-04 08:00:00',28800,35993,'String5',507968,5620422,'String6','String7','String8',NULL,,1852738,2,,,'String9','2018-04-04',89637,149,4,4,526,'String10',5,18,3,9,'String11')
```
In tabix return: ```Code: 62, e.displayText() = DB::Exception: Cannot parse expression of type String here: ,,'String9','2018-04-04',89637,149,4,4,526,'String10',5,18,3,9,'String11'), e.what() = DB::Exception```
In clickhouse-client:
```
Code: 27. DB::Exception: Cannot parse input: expected , before: 738,2,,,\'String9\',\'2018-04-04\',89637,149,4,4,526,\'String10\',5,18,3,9,\'String11\'\n: (at row 1)

Row 1:
Column 0,   name: c0,  type: UInt8,          parsed text: "4"
Column 1,   name: c1,  type: UInt8,          parsed text: "2"
Column 2,   name: c2,  type: DateTime,       parsed text: "<SINGLE QUOTE>2018-04-04 09:19:02<SINGLE QUOTE>"
Column 3,   name: c3,  type: UInt32,         parsed text: "5441337"
Column 4,   name: c4,  type: UInt32,         parsed text: "5078196"
Column 5,   name: c5,  type: String,         parsed text: "<SINGLE QUOTE>String1<SINGLE QUOTE>"
Column 6,   name: c6,  type: String,         parsed text: "<SINGLE QUOTE>String2<SINGLE QUOTE>"
Column 7,   name: c7,  type: String,         parsed text: "<SINGLE QUOTE>String3<SINGLE QUOTE>"
Column 8,   name: c8,  type: Nullable(Date), parsed text: "<SINGLE QUOTE>2018-04-04<SINGLE QUOTE>"
Column 9,   name: c9,  type: UInt8,          parsed text: "8"
Column 10,  name: c10, type: UInt32,         parsed text: "253768764"
Column 11,  name: c11, type: Date,           parsed text: "<SINGLE QUOTE>2018-04-04<SINGLE QUOTE>"
Column 12,  name: c12, type: String,         parsed text: "<SINGLE QUOTE>String4<SINGLE QUOTE>"
Column 13,  name: c13, type: DateTime,       parsed text: "<SINGLE QUOTE>2018-04-04 08:00:00<SINGLE QUOTE>"
Column 14,  name: c14, type: UInt32,         parsed text: "28800"
Column 15,  name: c15, type: UInt32,         parsed text: "35993"
Column 16,  name: c16, type: String,         parsed text: "<SINGLE QUOTE>String5<SINGLE QUOTE>"
Column 17,  name: c17, type: UInt32,         parsed text: "507968"
Column 18,  name: c18, type: UInt32,         parsed text: "5620422"
Column 19,  name: c19, type: String,         parsed text: "<SINGLE QUOTE>String6<SINGLE QUOTE>"
Column 20,  name: c20, type: String,         parsed text: "<SINGLE QUOTE>String7<SINGLE QUOTE>"
Column 21,  name: c21, type: String,         parsed text: "<SINGLE QUOTE>String8<SINGLE QUOTE>"
Column 22,  name: c22, type: Nullable(Date), parsed text: "NULL,,1852"
ERROR: garbage after Nullable(Date): "738,2,,,<SINGLE QUOTE>S"

```

**Comment by filimonov** [comment]
In TSV Nulls are represened as \N
Usually you can check exactly which format clickhouse expect to see by writing few rows in that format by clickhouse. I.e.
```
SELECT * FROM t1 FORMAT TSV;
```

**Comment by DivyaRao30** [comment]
Trying to load data into the table and its throwing error which is not in specific 

Table:

 CREATE TABLE insightbasev2.company_temp (
  company_id UInt32,
  location_id String,
  company_name String,
  street_address1 String,
  street_address2 String,
  city_name String,
  state_province_code String,
  state_province_name String,
  postal_code String,
  country_code String,
  cmsa UInt32,
  domain String,
  company_phone String,
  location_naics2_code UInt32,
  location_naics2_description String,
  location_naics4_code UInt32,
  location_naics4_description String,
  location_naics6_code UInt32,
  location_naics6_description String,
  location_sic4_code UInt32,
  location_sic4_description String,
  location_TI_industry_category String,
  location_TI_industry String,
  location_Ti_industryid UInt32,
  primary_naics2_code UInt32,
  primary_naics2_description String,
  primary_naics4_code UInt32,
  primary_naics4_description String,
  primary_naics6_code UInt32,
  primary_naics6_description String,
  primary_sic4_code UInt32,
  primary_sic4_description String,
  primary_TI_industry_category String,
  primary_TI_industry String,
  location_employeecount_range_id UInt32,
  location_employeecount_range String,
  location_employeecount UInt32,
  location_employeecount_reliability_code UInt32,
  corp_employeecount_range String,
  corp_employeecount UInt32,
  corp_employeecount_reliability_code UInt32,
  location_revenue_range_id UInt32,
  location_revenue_range String,
  location_revenue UInt32,
  location_revenue_reliability_code UInt32,
  corp_revenue_range String,
  corp_revenue UInt32,
  corp_revenue_reliability_code UInt32,
  linkedin_company_url String,
  global_ultimate_duns UInt32,
  domestic_ultimate_duns UInt32,
  parent_duns UInt32,
  hq_duns UInt32,
  location_duns UInt32,
  dnb_status_code UInt32,
  dnb_subsidiary_indicator UInt32,
  dnb_line_of_business String,
  global_ultimate_indicator String,
  fortune_1000_rank String,
  global_500_rank String,
  top_500_franchise String,
  TI_source_id UInt32,
  TI_verification_status String,
  TI_verification_source String,
  company_last_verified_date Date,
  company_phone_last_verified_date Date,
  created_user_id UInt32,
  created_date Date,
  modified_user_id UInt32,
  modified_date Date,
  verifier_user_id UInt32,
  verified_date Date,
  futureuse1 String,
  futureuse2 String,
  futureuse3 String,
  futureuse4 String,
  futureuse5 String
) ENGINE = MergeTree PARTITION BY state_province_code
ORDER BY
  domain SETTINGS index_granularity = 8192

Insert statement:

clickhouse-client -h1.0.1.2.3 -u default --password xxxx --query="INSERT INTO insightbasev2.company_temp FORMAT CSV" </temp/company_1/3.csv

Error:

Syntax error: failed at position 1:

clickhouse-client -h1.0.1.2.3 -u default --password xxxx --query="INSERT INTO insightbasev2.company_temp FORMAT CSV" </temp/company_1/4.csv

Expected one of: CREATE, ATTACH, DETACH, DROP, SHOW, SELECT, WITH, DESC, SYSTEM query, AST, list of elements, ALTER query, ALTER TABLE, CREATE TABLE or ATTACH TABLE query, Query with output, SHOW PROCESSLIST query, SHOW PROCESSLIST, RENAME query, RENAME TABLE, SELECT query, possibly with UNION, SET query, SHOW [TEMPORARY] TABLES|DATABASES [[NOT] LIKE 'str'], EXISTS or SHOW CREATE query, SELECT query, subquery, possibly with UNION, USE query, SELECT subquery, CHECK TABLE, DESCRIBE query, DROP query, EXISTS, TRUNCATE, INSERT query, INSERT INTO, KILL QUERY query, KILL QUERY, OPTIMIZE query, OPTIMIZE TABLE, SELECT query, DESCRIBE, Query, USE, SET

any suggestion will be appreciated

**Comment by filimonov** [comment]
@DivyaRao30 please don't duplicate your comments. I've answered you in #3847

**Comment by filimonov** [comment]
Let's continue the discussion in #469 to have a clearer backlog.
