### ISSUE TITLE
Cannot assign requested address: [::1]:8123

### ISSUE THREAD

**Issue by vvp83** [yandex/ClickHouse#790]
root@Debian-87-jessie-64-minimal ~ # docker create --name clickhouse-server yandex/clickhouse-server:1.1.54181
94ef550867e84125e8eefadf2b84d73c2d62e3f082c0f62ae3ecdf24f8d7dc3d
root@Debian-87-jessie-64-minimal ~ # docker start clickhouse-server
clickhouse-server
root@Debian-87-jessie-64-minimal ~ # docker logs -f clickhouse-server
Include not found: clickhouse_remote_servers
Include not found: clickhouse_compression
2017.05.15 08:33:50.539179 [ 1 ] <Warning> Application: Logging to console
2017.05.15 08:33:50.567878 [ 1 ] <Information> : Starting daemon with revision 54180
2017.05.15 08:33:50.568580 [ 1 ] <Information> Application: starting up
2017.05.15 08:33:50.569081 [ 1 ] <Debug> Application: rlimit on number of file descriptors is 1048576
2017.05.15 08:33:50.569097 [ 1 ] <Debug> Application: Initializing DateLUT.
2017.05.15 08:33:50.569105 [ 1 ] <Trace> Application: Initialized DateLUT.
2017.05.15 08:33:50.569227 [ 1 ] <Debug> Application: Configuration parameter 'interserver_http_host' doesn't exist or exists and empty. Will use '9                                                 4ef550867e8' as replica host.
2017.05.15 08:33:50.569300 [ 1 ] <Debug> ConfigReloader: Loading config '/etc/clickhouse-server/config.xml'
Include not found: clickhouse_remote_servers
Include not found: clickhouse_compression
2017.05.15 08:33:50.575327 [ 1 ] <Debug> ConfigReloader: Loading config '/etc/clickhouse-server/users.xml'
Include not found: networks
Include not found: networks
2017.05.15 08:33:50.577558 [ 1 ] <Information> Application: Loading metadata.
2017.05.15 08:33:50.577801 [ 1 ] <Information> DatabaseOrdinary (default): Total 0 tables.
2017.05.15 08:33:50.577985 [ 1 ] <Debug> Application: Loaded metadata.
2017.05.15 08:33:50.578122 [ 1 ] <Information> DatabaseOrdinary (system): Total 0 tables.
2017.05.15 08:33:50.578724 [ 1 ] <Information> Application: Shutting down storages.
2017.05.15 08:33:50.578798 [ 1 ] <Debug> Application: Shutted down storages.
2017.05.15 08:33:50.579532 [ 1 ] <Debug> Application: Destroyed global context.
2017.05.15 08:33:50.595347 [ 1 ] <Error> Application: Net Exception: Cannot assign requested address: [::1]:8123
2017.05.15 08:33:50.595362 [ 1 ] <Information> Application: shutting down

root@Debian-87-jessie-64-minimal ~ # ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever

And so.

no  aplication on 8123 port

**Comment by ludv1x** [comment]
What is your docker version?
I faced with the same problem using docker `17.04.1~ce-0~ubuntu-trusty`.
But, downgrade to `17.03` helped me to avoid the problem.

So, I guess that it could be docker issue.

**Comment by mgilbir** [comment]
There is this other closed issue that may be relevant here: https://github.com/yandex/ClickHouse/issues/721

**Comment by genestack-solomatin** [comment]
Reproduced once again after upgrade to `Docker 17.06.0-ce-mac18 (18433)`

> There is this other closed issue that may be relevant here: #721

Yes, it is.  This comment helped me to workaround my troubles. https://github.com/yandex/ClickHouse/issues/721#issuecomment-296400878
