### ISSUE TITLE
ClickHouse Client Assembly

### ISSUE THREAD

**Issue by daskol** [yandex/ClickHouse#793]
How to build ClickHouse client? I tried
```bash
cmake --target clickhouse-client .
make clickhouse-client
```
It turns out that target is static library `libclickhouse-client.a`. As I understand there is no executable target except `clickhouse-server` and test executables.

**Comment by alexey-milovidov** [comment]
`clickhouse-client` is a symlink to `clickhouse` binary.
You could create symlink with name `clickhouse-client` an run it.
`clickhouse` will decide by program name, what do you want to run.
Also you could run ClickHouse client as `clickhouse --client`.

**Comment by daskol** [comment]
@alexey-milovidov Wow! This is very unexpectedly and is not obvious. Thanks. 

Is it possible to split `clickhouse` binary into `clickhouse-client` and `clickhouse-server`. The reason is sometimes one needs either client or server but both.

**Comment by alexey-milovidov** [comment]
Recently clickhouse-client was separate binary. But it links most of ClickHouse codebase and size of that binary was almost the same as size of clickhouse-server.

Then we needed to add few more binaries - clickhouse-benchmark, clickhouse-local, and decided to make single binary to avoid duplication.

Now we are going to allow to build lite version of clickhouse binary without some parts - for example, without functions, aggregate functions, table engines, etc. It will allow to build more lite binary to use solely as client.
