### ISSUE TITLE
Ability to display WITH TOTALS' result for Vertical format

### ISSUE THREAD

**Issue by hatarist** [yandex/ClickHouse#799]
I think It'd be convenient to be able to see WITH TOTALS results not only in TSV/Pretty formats, but for the, at least, Vertical, too.

**Comment by alexey-milovidov** [comment]
Reasonable. Will do.

**Comment by alexey-milovidov** [comment]
https://github.com/yandex/ClickHouse/commit/7269f3a23b2e4fb4836ccce81be334cd3b2c3231
