### ISSUE TITLE
В документации отсутствует информация по логированию

### ISSUE THREAD

**Issue by wavedocs** [yandex/ClickHouse#81]
Добавьте пожалуйста в докуметацию информацию по уровням логирования.

**Comment by alexey-milovidov** [comment]
На всякий случай напишу сначала здесь. Потом можно будет перенести в документацию.

Уровень логгирования trace (по-умолчанию) - наиболее подробный уровень логгирования.
Несмотря на название, даже логгирование с уровнем trace не несёт каких-либо существенных проблем с объёмом лога или с производительностью, и уменьшать этот уровень не имеет смысла. Поэтому мы используем и рекомендуем использовать уровень логгирования trace в продакшене.

Доступные уровни: trace, debug, information, warning, error.

**Comment by wavedocs** [comment]
@alexey-milovidov не могу с Вами согласиться.
Буквально на днях заливали данные в базу на скорости 15К RPS, сегодня уровень логирования выставили в  warning и выжали больше 80К RPS

**Comment by alexey-milovidov** [comment]
Возможно, причина в том, что данные загружались слишком маленькими пачками.
https://clickhouse.yandex/reference_ru.html#%D0%9F%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%BE%D0%B4%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D1%8C%20%D0%BF%D1%80%D0%B8%20%D0%B2%D1%81%D1%82%D0%B0%D0%B2%D0%BA%D0%B5%20%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85.

Рекомендуется загружать, например, всего лишь одну пачку (запрос INSERT) в секунду, зато в каждом по 100 000 строк.

С уровнем trace, сервер пишет в лог,
- на каждый INSERT в районе нескольких строк;
- на каждый SELECT до нескольких десятков строк.

Ещё не всякий случай:
- если в данных, загружаемых в таблицу типа MergeTree, идут данные за разные месяцы (то есть, партиции) вперемешку, то данные будут загружаться медленнее (по сути, одна загружаемая пачка разбивается на несколько по месяцам)

**Comment by wavedocs** [comment]
Данные загружаем в виде sql batch insert. Тип MergeTree(Distributed-таблицу). Данные по дате уже структурированы.

**Comment by alexey-milovidov** [comment]
Думаю, всё зависит от размера этого batch-а. Если поставите побольше - будет лучше.

**Comment by wavedocs** [comment]
Возможно, но производительность проседала именно из-за логирования, т.к. кроме метода логирования, ничего не менялось.

**Comment by alexey-milovidov** [comment]
Верю.
Вы правы: производительность может проседать из-за логгирования.

**Comment by blinkov** [comment]
Nowadays it's mentioned in docs:
```
operations/server_settings/settings.md:313:- level – Logging level. Acceptable values: ``trace``, ``debug``, ``information``, ``warning``, ``error``.
operations/server_settings/settings.md:323:    <level>trace</level>
```
