### ISSUE TITLE
<Error> Application: Net Exception: Address family not supported

### ISSUE THREAD

**Issue by qietingfengling** [yandex/ClickHouse#815]
I install ClickHouse on centos7.2,gcc6.2.I get  successfully,but when I start use "clickhouse-server --config=/usr/local/etc/clickhouse-server/config.xml",it get a error as "<Error> Application: Net Exception: Address family not supported",anybody tell me why?

2017.05.20 23:06:49.002758 [ 1 ] <Warning> Application: Logging to console
2017.05.20 23:06:49.007378 [ 1 ] <Information> : Starting daemon with revision 54226
2017.05.20 23:06:49.007519 [ 1 ] <Information> Application: starting up
2017.05.20 23:06:49.008517 [ 1 ] <Debug> Application: rlimit on number of file descriptors is 262143
2017.05.20 23:06:49.008563 [ 1 ] <Debug> Application: Initializing DateLUT.
2017.05.20 23:06:49.008587 [ 1 ] <Trace> Application: Initialized DateLUT with time zone `Asia/Shanghai'.
2017.05.20 23:06:49.008879 [ 1 ] <Debug> Application: Configuration parameter 'interserver_http_host' doesn't exist or exists and empty. Will use 'localhost' as replica host.
2017.05.20 23:06:49.009019 [ 1 ] <Debug> ConfigReloader: Loading config `/usr/local/etc/clickhouse-server/users.xml'
2017.05.20 23:06:49.013399 [ 1 ] <Information> Application: Loading metadata.
2017.05.20 23:06:49.013891 [ 1 ] <Information> DatabaseOrdinary (system): Total 0 tables.
2017.05.20 23:06:49.013990 [ 1 ] <Information> DatabaseOrdinary (default): Total 0 tables.
2017.05.20 23:06:49.014249 [ 1 ] <Debug> Application: Loaded metadata.
2017.05.20 23:06:49.026868 [ 2 ] <Debug> ReshardingWorker: Started resharding background thread.
2017.05.20 23:06:49.028699 [ 1 ] <Information> Application: Shutting down storages.
2017.05.20 23:06:49.028828 [ 1 ] <Debug> Application: Shutted down storages.
2017.05.20 23:06:50.028814 [ 2 ] <Debug> ReshardingWorker: Resharding background thread terminated.
2017.05.20 23:06:50.029530 [ 1 ] <Information> ~ZooKeeper: Closing ZooKeeper session
2017.05.20 23:06:50.029695 [ 1 ] <Information> ~ZooKeeper: Removing 1 watches
2017.05.20 23:06:50.029712 [ 1 ] <Information> ~ZooKeeper: Removed watches
2017.05.20 23:06:50.029724 [ 1 ] <Debug> Application: Destroyed global context.
2017.05.20 23:06:50.029966 [ 1 ] <Error> Application: Net Exception: Address family not supported
2017.05.20 23:06:50.029982 [ 1 ] <Information> Application: shutting down
2017.05.20 23:06:50.029989 [ 1 ] <Debug> Application: Uninitializing subsystem: Logging Subsystem
2017.05.20 23:06:50.030021 [ 3 ] <Information> BaseDaemon: Stop SignalListener thread

**Comment by proller** [comment]
maybe you have disabled ipv6.
try edit config: remove <listen_host>::1</listen_host> and leave only <listen_host>127.0.0.1</listen_host>

**Comment by qietingfengling** [comment]
Oh yes,you are right ,thanks,I fix it
