### ISSUE TITLE
Cannot Insert data into ReplicatedMergeTree

### ISSUE THREAD

**Issue by jaykelin** [yandex/ClickHouse#827]
> (Replicated OutputStream): Block with ID 9125361514582012557_14309323673096342990 already exists; ignoring it (removing part 20170506_20170506_265_265_0)

I would like to know if this is normal, and in what scenario will happen?

**Comment by alexey-milovidov** [comment]
It happens, when you insert duplicate block - with exactly the same content as before.

Documentation:

> Blocks of data are duplicated. For multiple writes of the same data block (data blocks of the same size containing the same rows in the same order), the block is only written once. The reason for this is in case of network failures when the client application doesn't know if the data was written to the DB, so the INSERT query can simply be repeated. It doesn't matter which replica INSERTs were sent to with identical data - INSERTs are idempotent.

**Comment by jaykelin** [comment]
@alexey-milovidov but, before insert same block, Has been successfully executed_alter table x drop partition 201705_

**Comment by alexey-milovidov** [comment]
Yes, this is the issue. `DROP PARTITION` doesn't clear set of blocks for deduplication.
Currently, the only solution, is to clear all nodes in ZooKeeper inside `/blocks/` in table path.

**Comment by jaykelin** [comment]
Which nodes in Zookeeper could be clear is difficult to select.
is there prossible to delete nodes in Zookeeper during droping partition?

**Comment by ztlpn** [comment]
Yes, I plan to fix it soon.

**Comment by Foxsa** [comment]
Any updates?

**Comment by alexey-milovidov** [comment]
We are doing this task right now.
