### ISSUE TITLE
system.query_log table is not documented

### ISSUE THREAD

**Issue by bobrik** [yandex/ClickHouse#847]
It's missing from here: https://clickhouse.yandex/docs/en/system_tables/index.html

**Comment by bobrik** [comment]
What's the meaning of `type` column? — that was my initial question, though.

**Comment by alexey-milovidov** [comment]
https://github.com/BayoNet is going to add the documentation.

> What's the meaning of type column? — that was my initial question, though.

1 - start of query execution
2 - end of query execution
3 - exception before start of query execution
4 - exception while query execution

Each query create one or two events in `query_log` table:
- two events with types 1 and 2: usual, successful case;
- two events with types 1 and 4;
- single event with type 3;

**Comment by hagen1778** [comment]
Are there any way to avoid writing `INSERT` queries into query_log ?

**Comment by alexey-milovidov** [comment]
There is no way. Please note, that INSERTs are logged without data.

**Comment by jangorecki** [comment]
can I safely truncate `query_log` table?

**Comment by filimonov** [comment]
> can I safely truncate `query_log` table?

Yes, it's 100% safe.

**Comment by filimonov** [comment]
Documentation is added and available on the official website:
https://clickhouse.yandex/docs/en/operations/system_tables/#system_tables-query-log
