### ISSUE TITLE
Add links to edit documentation

### ISSUE THREAD

**Issue by bobrik** [yandex/ClickHouse#849]
Elasticsearch has buttons on each page to edit the docs on Github:

* https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html

![image](https://cloud.githubusercontent.com/assets/89186/26747015/f2be568e-47a7-11e7-8c73-daa034f62393.png)

Kubernetes also adopted this pattern. I think it's useful to do the same for ClickHouse docs as well.

List styles are weird here, but instead of getting issues to fix it you can get PRs:

![image](https://cloud.githubusercontent.com/assets/89186/26747035/17b10bd0-47a8-11e7-958b-eef824b28273.png)

**Comment by bobrik** [comment]
Another funny example that I can just fix myself:

* https://clickhouse.yandex/docs/en/interfaces/cli.html

![image](https://cloud.githubusercontent.com/assets/89186/26748198/65425f9a-47b0-11e7-8793-3aa089b2d8e1.png)

**Comment by blinkov** [comment]
Good idea, pulled this into our internal task tracker to later take a look on how this's supposed to be done.

The last screenshot has already been [fixed few days ago](https://github.com/yandex/ClickHouse/commit/dc3a618d7ab506ffd9601571c5a23d8e22be7020), but it still haven't been published because unfortunately this new docs release process is not fully automated yet. I've just pushed the button, so it probably will go live soon.

**Comment by silviucpp** [comment]
@blinkov there is nothing in documentation about Null-able fields even if this feature was added.

**Comment by blinkov** [comment]
@bobrik The links for editing documentation are live (in the bottom of sidebar).

@silviucpp That probably deserves it's own pull request or issue.

**Comment by silviucpp** [comment]
@blinkov I'll send a bug report

**Comment by bobrik** [comment]
@blinkov 👍 

I've tried grepping for leftovers of russian text in english docs:

```
$ grep '[а-я]' -ri doc/reference/en
```

And found this:

![image](https://user-images.githubusercontent.com/89186/27008089-c9e20edc-4e1d-11e7-8c93-58747dd5e715.png)

But on the website I see this:

![image](https://user-images.githubusercontent.com/89186/27008088-bf65f658-4e1d-11e7-9f24-c12b26871d65.png)

Seems that website is out of sync somehow.

**Comment by blinkov** [comment]
@bobrik That's a side effect of not yet fully automated website release process. I've already fixed this one and published without waiting for pull request to be merged to master.

@silviucpp Thanks.

**Comment by bobrik** [comment]
I think this can be closed, unless you think there's anything else to do. The link is less visible than on elasticsearch website, but it's a lot better than nothing.

Thanks!
