### ISSUE TITLE
ClickHouse crashes on all full join with the empty left table

### ISSUE THREAD

**Issue by alex-zaitsev** [yandex/ClickHouse#854]
ClickHouse version 1.1.54231.

    select a, b from
    (select 1 a, 0 fake_key where 0)
    all full join
    (select 2 b, 0 fake_key) using (fake_key);

Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000, ::1

Connecting to localhost:9000.
Code: 210. DB::NetException: Connection reset by peer: while reading from socket ([::1]:9000)

Without 'where 0' condition it works fine.

**Comment by alex-zaitsev** [comment]
Could be fixed in: 1.1.54236: https://github.com/yandex/ClickHouse/commit/aeb83f9ef7cdc3d3f597cc950d13d1ed619f1ce4

**Comment by ztlpn** [comment]
Yes, please upgrade to 1.1.54236
