### ISSUE TITLE
Statement is parsed incorrectly

### ISSUE THREAD

**Issue by StarWix** [yandex/ClickHouse#858]
```
CREATE TABLE test (
    A Float64
) ENGINE = Log;

SELECT min(if(A >= 0, 1.0, -1.0)) FROM (SELECT if(A >= 0, 1.0, -1.0) FROM test); 
```
And get error
```
DB::Exception: Invalid nested column name: if(greaterOrEquals(A, 0), 1., -1.).
```

But query execution without double numbers works correct:
```
SELECT min(if(A >= 0, 1, -1)) FROM (SELECT if(A >= 0, 1, -1) FROM test);
```

**Comment by ludv1x** [comment]
Affirmed. Problem with sub-queries.
Minimal example: `SELECT * FROM (SELECT pow(1., 2.))` fails
`SELECT * FROM (SELECT pow(1., 2))` works
` SELECT * FROM (SELECT pow(1., 2.) as a)` works

**Comment by zhang2014** [comment]
@ludv1x can we close this issue?

**Comment by alexey-milovidov** [comment]
Yes, it is fixed. Thanks!
