### ISSUE TITLE
Nullable fileds are not documented

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#867]
Hello,

Looking into the documentation there is nothing about Nullable fields even if this feature was implemented for some time.

Silviu

**Comment by alexey-milovidov** [comment]
We are still considering NULLs as beta (currently late beta).
Documentation will be added soon.

**Comment by filimonov** [comment]
Currenty NULLs looks quite mature. Probably documentation should be added.

**Comment by opavader** [comment]
@alexey-milovidov any updates on this ?

**Comment by BayoNet** [comment]
I'll try to add the documentation today.

**Comment by silviucpp** [comment]
@BayoNet was documentation added ? In case yes you can close the bug

**Comment by alexey-milovidov** [comment]
It wasn't.

**Comment by BayoNet** [comment]
Ready.

**Comment by francisdb** [comment]
Thanks @BayoNet , would you mind adding a link to the specific pages?

**Comment by blinkov** [comment]
@francisdb it's kind of scattered across many parts of documentation on other topics, but they are easy to find by searching "Null". Also the issue is closed a bit early as that patch in English is not live yet, but will be hopefully today or maybe tomorrow.

**Comment by filimonov** [comment]
https://clickhouse.yandex/docs/ru/data_types/nullable/
vs 
https://clickhouse.yandex/docs/en/data_types/nullable/ ?

**Comment by filimonov** [comment]
> Also the issue is closed a bit early as that patch in English is not live yet, but will be hopefully today or maybe tomorrow.

aha, ok.

**Comment by blinkov** [comment]
English version is now also available on website.
