### ISSUE TITLE
Subselects are not supported as function parameters

### ISSUE THREAD

**Issue by alex-zaitsev** [yandex/ClickHouse#871]
This is certainly an artificial example:

    :) select 1 where today()=toDate(select now());

    Syntax error: failed at position 38:

    select 1 where today()=toDate(select now());

    Expected end of query

    :) select 1 where today()=(select toDate(now()));
    
    ┌─1─┐
    │ 1 │
    └───┘

    1 rows in set. Elapsed: 0.029 sec. 

Looks counterintuitive.

**Comment by ztlpn** [comment]
Scalar subqueries must always be included in parentheses of their own (parentheses of the function call operator are insufficient). So, for example, this works:
```
:) select 1 where today()=toDate((select now()));

SELECT 1
WHERE today() = toDate(
(
    SELECT now()
))

┌─1─┐
│ 1 │
└───┘

1 rows in set. Elapsed: 0.001 sec.
```

As far as I can tell, this is the behavior required by SQL standard. See e.g. item 7.11 in http://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt

**Comment by alex-zaitsev** [comment]
ok. agree
