### ISSUE TITLE
A nullable column cannot contain another nullable column

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#874]
Hello,

Seems you are able to create a nullable column that contain another nullable column, but when you do the select the entire table is broken.

```sql
create table test.funnel (EventDate Date, a Nullable(UInt8)) ENGINE = MergeTree(EventDate, (EventDate), 8192);
alter table test.funnel ADD COLUMN b Nullable(Array(Nullable(UInt8)));
select * from test.funnel format JSON
```

Code: 44, e.displayText() = DB::Exception: A nullable column cannot contain another nullable column: (wh"...

If this is not allowed then ALTER should fail. if it's allowed select should work :)

Silviu

**Comment by alexey-milovidov** [comment]
Now ALTER will fail. https://github.com/yandex/ClickHouse/commit/a726c688654deea7981799198e00c718e0ab552b
