### ISSUE TITLE
Japanese characters have different width in cli output

### ISSUE THREAD

**Issue by bobrik** [yandex/ClickHouse#888]
Hopefully this still makes sense after roskomnadzoring:

![image](https://user-images.githubusercontent.com/89186/27250854-5884af94-52ee-11e7-822c-c4c509125b5f.png)

Path with Japanese characters produces misaligned column.

**Comment by bobrik** [comment]
```
:) select 'упячка'

SELECT 'упячка'

┌─\'упячка\'─┐
│ упячка     │
└────────────┘

1 rows in set. Elapsed: 0.001 sec.

:) select '모'

SELECT '모'

┌─\'모\'─┐
│ 모     │
└───────┘

1 rows in set. Elapsed: 0.001 sec.

:)
```

**Comment by ztlpn** [comment]
Acknowledged. Currently visible width is determined by simply counting unicode code points. Of course the reality is [more involved](https://news.ycombinator.com/item?id=10206380). We should use some variant of the [wcwidth()](http://www.cl.cam.ac.uk/~mgk25/ucs/wcwidth.html) function instead.

**Comment by alexey-milovidov** [comment]
Ok to use `wcwidth` if we will measure performance and possibly (if needed) provide fast path for ASCII and cyrillic.

**Comment by djma** [comment]
Korean characters ;)

**Comment by filimonov** [comment]
#3257
