### ISSUE TITLE
Aggregation function: HDR Histograms

### ISSUE THREAD

**Issue by beberlei** [yandex/ClickHouse#9]
As a complement to `quantile(s)` aggregation function, it could be useful to have a histogram aggregation  function based on https://github.com/HdrHistogram/HdrHistogram_c where you specify the min, max and signifcant figures and it then bucketizes values into the histogram and returns it.

**Comment by alexey-milovidov** [comment]
Very promising. 
Also histogram could be calculated on top of t-digest algorithm.

**Comment by elrik75** [comment]
Histogram approximation in one pass (without setting the min / max) is also possible, as explain here : http://jmlr.org/papers/volume11/ben-haim10a/ben-haim10a.pdf 
Different implementations in different languages are available.

**Comment by alexey-milovidov** [comment]
#2521
