### ISSUE TITLE
Problem when machines in the zookeeper cluster go down

### ISSUE THREAD

**Issue by George3d6** [yandex/ClickHouse#904]
I've noticed a sort of "undefined behavior" when machines in the same shard go down. Sometimes it seems to go by without me noticing and nothing happens, other times the other machines in the cluster stop ingesting data ind instead keeping spamming errors such as:

```
Jun 20 12:51:11 ryzen1 clickhouse-server[15907]: 2017.06.20 12:51:11.048134 [ 37 ] <Warning> ZooKeeper: Error on attempt 1: connection loss. Retry
Jun 20 12:51:11 ryzen1 clickhouse-server[15907]: 2017.06.20 12:51:11.048732 [ 38 ] <Error> void DB::StorageReplicatedMergeTree::queueUpdatingThread(): Code: 999, e.displayText() = zkutil::KeeperException: invalid zhandle state, path: /clickhouse/tables/1/analytics_v2_logv_85/transactions/replicas/1/log_pointer, e.what() = zkutil::KeeperException, Stack trace:
```

Are shards supposed to stop ingesting data when a single machine goes down ? Might this be an error with the way I setup zookeeper rather than a clickhouse related error ?

**Comment by jackpgao** [comment]
I've got the same problem.

**Comment by jackpgao** [comment]
It seems that the problem comes from the zookeeper which is very slow.

**Comment by alexey-milovidov** [comment]
When a node of ZooKeeper cluster goes down, ClickHouse have to reinitialize a session with another ZooKeeper node. INSERTs will stop to work until the session is reinitialized. In most cases it should not take longer than ZooKeeper session timeout (30 seconds by default) but usually it will do quicker.

In recent ClickHouse releases there was improvements on session reinitialization delay.
