### ISSUE TITLE
debian/control: build dependency issues

### ISSUE THREAD

**Issue by bzed** [yandex/ClickHouse#911]
To build in a clean stretch chroot, the following changes are necessary:

- add **clang** as build-dependency as the binaries are being copied at the end.
- clickhouse doesn't seem to build with openssl > 1.0, so depend on **libssl1.0-dev**. To stay compatible with older releases and Ubuntu, using **libssl1.0-dev | libssl-dev** should work.

Thanks a lot,

Bernd

**Comment by blinkov** [comment]
Is this issue still relevant?
