### ISSUE TITLE
Any new release ?

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#924]
Seems lot of nice stuffs added and bugs fixed in the last master comparing with the current stable.

Any release planned to integrate those ? Or why not creating a testing distribution with nightly builds that makes testing much simple. Right now you need to build yourself the debs

Silviu

**Comment by alexey-milovidov** [comment]
We plan to have new release next week.

Actually we have per-commit tests (functional tests and tests under ASan), nightly Valgrind tests,
integration tests with Yandex.Metrica and Yandex.AppMetrica code,
testing environment with real data similar to production cluster,
and performance regression tests.

But currently we publish packages as stable only after release to production Yandex.Metrica cluster.

**Comment by silviucpp** [comment]
Hello Alexey,

I think community can provide also fast feedback in case you will have another channel where releases can happened much faster.. (maybe at each commit in master or daily)

Silviu

**Comment by alexey-milovidov** [comment]
Ok, added a task for our QA team for auto publishing.

**Comment by silviucpp** [comment]
Hello I see v1.1.54242-stable was released in github but not yet in the deb repository. It's a known behavior ?

**Comment by silviucpp** [comment]
By the way for all those that needs and want to test the testing releases they need to change only in `/etc/apt/sources.list`:

`deb http://repo.yandex.ru/clickhouse/trusty stable main`

with 

`deb http://repo.yandex.ru/clickhouse/trusty testing main`

I think this should be documented :)

**Comment by alexey-milovidov** [comment]
Ok. Now we have auto-publishing of testing packages; and possibility to use testing repositories was documented.
