### ISSUE TITLE
Extend RowBinary format with column names and column types metainformation.

### ISSUE THREAD

**Issue by bgaifullin** [yandex/ClickHouse#929]
Extend RowBinary format with column names and column types metainformation.

Currently we have RowBinary that is the next fast format (after Native), which can be used without any restrictions. (according to documentation)
But for deserialising  data, which are returned in RowBinary format, client must have additional information about types of columns.

It's very hard to implement connector for this format in my unoficial connector library https://github.com/mailru/go-clickhouse since there is no information about types and columns in response which is needed by for to implement golang database/sql/driver.

Please extend this format with addition information about column names and column types can help to use RowBinary format in connectors without additional efforts.

**Comment by filimonov** [comment]
Probably can be closed?

**Comment by bgaifullin** [comment]
Yes, thank you
