### ISSUE TITLE
Reduce memory usage during vertical merge

### ISSUE THREAD

**Issue by valyala** [yandex/ClickHouse#931]
## Preface

We tried increasing `max_bytes_to_merge_at_max_space_in_pool` from default 100Gb to 500Gb in order to reduce the number of parts for a huge table according to the suggestion from @alexey-milovidov .

## The issue

The server run out of memory in a 20 minutes after the restart (it looks like the `max_bytes_to_merge_at_max_space_in_pool` is applied only after clickhouse restart). See memory usage graph below.

![clickhouse-memory-usage](https://user-images.githubusercontent.com/283442/27584818-31890136-5b42-11e7-8cb1-423bfe950ca4.png)

The server has 104GB of RAM. Clickhouse memory usage was stable around 30GB before the restart. After the restart clickhouse started concurrent merge of 100GB parts into bigger ones and memory usage grew linearly up to 100GB in 20 minutes.

It looks like the vertical merge algorithm used by clickhouse requires O(N) additional memory when merging N rows. This memory is used for building an array of part indexes for quick sequential merge of columns outside `MergeTree` primary key. Each index corresponds to a single row in the resulting part.

## The solution

To stream compressed array of part indexes to a temporary file instead of holding it uncompressed in memory. This should reduce memory usage during vertical merge to O(1).

**Comment by ztlpn** [comment]
Is increasing `max_bytes_to_merge_at_max_space_in_pool` the only thing that changed? In particular I'm interested if you have left ClickHouse version intact (which version is it BTW?) or did you reinstall ClickHouse from source?

**Comment by valyala** [comment]
Yes, the only thing is `max_bytes_to_merge_at_max_space_in_pool` that changed from 100Gb to 500Gb.

clickhouse version is 1.1.54236 , installed from the official deb package `deb http://repo.yandex.ru/clickhouse/xenial stable main`

**Comment by ztlpn** [comment]
Yes, problem acknowledged. When you raised the part size limit, the server suddenly became aware that it can do a lot of new merges. As with the default settings ClickHouse can execute 8 merges without any size limit, 8 concurrent heavy merges were launched. Together they ate up all the RAM.

Your proposed solution seems reasonable, most likely we will implement it. Fun fact: memory consumption is not only O(N), but approximately equals N! E.g. if the resulting part has 10 billion rows, the memory consumption is around 10Gb.

**Comment by hagen1778** [comment]
Any workaround how to avoid RAM exhaustion and increase part size?

**Comment by ztlpn** [comment]
For now you can try lowering the number of concurrent heavy merges. It is controlled by `background_pool_size` (configurable in the default user profile, 16 by default) and `number_of_free_entries_in_pool_to_lower_max_size_of_merge` (configurable in the `merge_tree` config section, but unfortunately only after https://github.com/yandex/ClickHouse/commit/9de4d8facb412fa178cd8380a4411c30da43acc7. Default value is 8). So e.g. if you want the number of concurrent heavy merges to be around 2, you can set `background_pool_size` to 10. Of course, this can impede the ability to perform merges in general, so proceed with caution.

**Comment by ztlpn** [comment]
Implemented and turned on by default in 1.1.54276.
