### ISSUE TITLE
cant stdin to clickhouse-client ( not | )

### ISSUE THREAD

**Issue by yctn** [yandex/ClickHouse#935]
i use syslog-ng to start an external application to stdin query's Into clickhouse-client. this way i dont have to reopen the connection for every query.

but this wasnt working. i think i know why.

to test stdin to clickhouse-client i did echo "query\n" > /proc/pid/fd/0 the line appeared in the clickhouse-client as "query\n" so my guess is that clickhouse-client does not accept STDIN correctly.

can you fix this in clickhouse-client so i can use syslog-ng to STDIN data to clickhouse-client?

https://www.balabit.com/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/configuring-destinations-program.html

**Comment by ludv1x** [comment]
Could you provide your queries?
The following examples work correctly for me:

```
vludv@vludv-ub14:~/distcc-ClickHouse$ echo "select 1" | clickhouse-client
1
vludv@vludv-ub14:~/distcc-ClickHouse$ echo "select 1, 2, 3" | clickhouse-client
1	2	3
vludv@vludv-ub14:~/distcc-ClickHouse$ echo -e "select 1, 2, 3;\n select 4, 5, 6;\n\n" | clickhouse-client -n
1	2	3
4	5	6
```

**Comment by yctn** [comment]
@ludv1x you are piping and not STDIN. piping works fine. only STDIN doesnt cause clickhouse-client does not understand \n

**Comment by ei-grad** [comment]
@yctn https://stackoverflow.com/questions/5374255/how-to-write-data-to-existing-processs-stdin-from-external-process
