### ISSUE TITLE
Feature request: Support substitutions in external dictionaries

### ISSUE THREAD

**Issue by eskomorokhov** [yandex/ClickHouse#940]
Typically the source of dictionary depends on an environment of db.
Like on development environment should have a connection to dev db and on production to production with passwords and so on. On test environment need localhost or file source for a dictionary.
As I see it could be done with ConfigProcessor class with context.
Thank you.

**Comment by lemmsh** [comment]
This actually used to work in older versions. At least I was able to specify "includes" in the dictionaries xml and they got replaced with actual passwords.

The problem seems to be that ExternalLoader that is used for dictionaries does not do config preprocessing unilke the ConfigProcessor.

**Comment by lemmsh** [comment]
What if instead of 
            Poco::AutoPtr<Poco::Util::XMLConfiguration> config = new Poco::Util::XMLConfiguration(config_path); in ExternalLoader.cpp:280 we reuse ConfigProcessor.cpp:375 and so on? I'll try to make a PR a bit later

**Comment by alexey-milovidov** [comment]
I think it should be fine! Looking forward for PR.
