### ISSUE TITLE
CSV import error

### ISSUE THREAD

**Issue by arduanov** [yandex/ClickHouse#941]
CSV import error
```
cat 05-15.csv | clickhouse --client --query 'INSERT INTO billing.invoice4 FORMAT CSVWithNames'
clickhouse(19738,0x700000691000) malloc: *** error for object 0x141d8e000: pointer being realloc'd was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```
csv size 2,5gb, 1750450 lines, 160 rows, macos, ClickHouse version 1.1.54236.

**Comment by alexey-milovidov** [comment]
Looks like it is using default malloc library from system libc version for some allocations, although ClickHouse should be linked to tcmalloc. Probably, this is build issue on Mac OS (there are some difficulties with allocators).

The issue should not present if you will run clickhouse from Ubuntu in Docker image.

**Comment by arduanov** [comment]
thanks for the answer, i use mac only for tests
