### ISSUE TITLE
Buffer table does not work with materialized columns

### ISSUE THREAD

**Issue by ishirav** [yandex/ClickHouse#957]
When the underlying table has a materialized column, the database raises an exception when trying to flush the buffer to disk. Here's a simple example that demonstrates the problem:
```
CREATE DATABASE IF NOT EXISTS test;

CREATE TABLE test.nums (
    n UInt64,
    m UInt64 MATERIALIZED n+1
) ENGINE = Log;

CREATE TABLE nums_buf AS test.nums ENGINE = Buffer(test, nums, 1, 10, 100, 1, 3, 10000000, 100000000);

INSERT INTO nums_buf (n) VALUES (1);
INSERT INTO nums_buf (n) VALUES (2);
INSERT INTO nums_buf (n) VALUES (3);
INSERT INTO nums_buf (n) VALUES (4);
INSERT INTO nums_buf (n) VALUES (5);
```

After inserting a few rows successfully, you get this error:
```
Received exception from server:
Code: 44. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Cannot insert column m. 
```

The server log shows this stack trace:
```
2017.07.08 09:58:08.198983 [ 9 ] <Trace> StorageBuffer (nums_buf): Flushing buffer with 4 rows, 64 bytes, age 1 seconds.
2017.07.08 09:58:08.238359 [ 9 ] <Error> void DB::StorageBuffer::flushThread(): Code: 44, e.displayText() = DB::Exception: Cannot insert column m, e.what() = DB::Exception, Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x2969826]
1. clickhouse-server(DB::ProhibitColumnsBlockOutputStream::write(DB::Block const&)+0x112) [0x2bedfa2]
2. clickhouse-server(DB::SquashingBlockOutputStream::finalize()+0x3f5) [0x2d74145]
3. clickhouse-server(DB::SquashingBlockOutputStream::writeSuffix()+0x11) [0x2d742b1]
4. clickhouse-server(DB::StorageBuffer::writeBlockToDestination(DB::Block const&, std::shared_ptr<DB::IStorage>)+0xb8c) [0x2a1c63c]
5. clickhouse-server() [0x2a1d4f4]
6. clickhouse-server(DB::StorageBuffer::flushThread()+0x63) [0x2a1d793]
7. clickhouse-server() [0x36744ef]
8. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7ff1c2c656ba]
9. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7ff1c22863dd]
```

**Comment by alexey-milovidov** [comment]
Buffer tables just doing ordinary INSERTs to destination table.
That's why they could not have columns, that are MATERIALIZED in destination table.

This is understandable, but inconvenient behavior.

We could do one of the following:
- add a flag, that will allow to INSERT into MATERIALIZED column, if INSERT is generated internally (it will also solve the same issue in Distributed tables);
- add a check, that will verify, that Buffer table can INSERT data to destination table.

**Comment by alexey-milovidov** [comment]
> add a flag, that will allow to INSERT into MATERIALIZED column, if INSERT is generated internally (it will also solve the same issue in Distributed tables);

That is the preferred solution.
This is very easy task (half an hour for those who are familiar with the codebase).

1. Add a setting `insert_allow_materialized_columns`, default 0.
2. Use this setting in InterpreterInsertQuery, InterpreterCreateQuery to bypass ProhibitColumnsBlockInputStream.
3. Pass this setting to INSERT query in StorageBuffer and in RemoteBlockOutputStream in DistributedDirectoryMonitor.
