### ISSUE TITLE
Clickhouse MacOS building problem

### ISSUE THREAD

**Issue by santaux** [yandex/ClickHouse#962]
There was a problem to build Clickhouse on MacOS Sierra:

`[ 11%] Built target our_mysql_client
In file included from /Users/kgrabar/Projects/AdTracker/ClickHouse/libs/libcommon/src/apple_rt.cpp:8:0:
/Users/kgrabar/Projects/AdTracker/ClickHouse/libs/libcommon/include/common/apple_rt.h:11:102: fatal error: common/config_common.h: No such file or directory
 #include <common/config_common.h>`

The problem was fixed by setting a full path to the file:

`#include "/Users/kgrabar/Projects/AdTracker/ClickHouse/build/libs/libcommon/include/common/config_common.h"`

And also you missed `make install` command as the last command into your instruction here: https://clickhouse.yandex/docs/en/development/build_osx.html

**Comment by proller** [comment]
Can you try now with fresh master ?
