### ISSUE TITLE
Fail to skip unknown fields with negative values on INSERT with JSONEachRow format

### ISSUE THREAD

**Issue by abonavita** [yandex/ClickHouse#964]
`clickhouse-client -n --query='create table t (d Date, a Int32) ENGINE=Memory'`

This is OK with a positive ignored column:
`clickhouse-client -n --query='set input_format_skip_unknown_fields=1;insert into t format JSONEachRow' <<< '{"d":"2017-01-01", "a":2, "b":3}'`

But fails for negative value:
`clickhouse-client -n --query='set input_format_skip_unknown_fields=1;insert into t format JSONEachRow' <<< '{"d":"2017-01-01", "a":2, "b":-3}'`
`Code: 117. DB::Exception: Unexpected symbol for key 'b'`

I think the problem comes from here https://github.com/yandex/ClickHouse/blob/master/dbms/src/IO/ReadHelpers.cpp#L686.

**Comment by alexey-milovidov** [comment]
Also please replace all occurences of `isdigit` to `isNumericASCII` (minor modification).
