### ISSUE TITLE
Can't use full table name (dbname.tablename) in JOIN clause

### ISSUE THREAD

**Issue by shalugin** [yandex/ClickHouse#97]
For example, this query:
`select srcip, dstip, score from db1.alert any left join db1.black_list using srcip limit 10;`
ends with error:

> Expected USING or ON

But this query ends successfully:
`select srcip, dstip, score from db1.alert any left join black_list using srcip limit 10;`

Is it error? Is it possible to join tables from different databases?

**Comment by alexey-milovidov** [comment]
For JOINs, only "subquery JOIN subquery" is well supported, as in examples in documentation.
For other cases, work in progress.

**Comment by zhang2014** [comment]
@alexey-milovidov can we close this issue?
