### ISSUE TITLE
Records are missing

### ISSUE THREAD

**Issue by alniks** [yandex/ClickHouse#973]
We have a Distributed table with two-node cluster with ReplicatedMergeTree tables. Once in 3 secs we make an insert to the Distributed table and see that some of the data are missing. Why and how we can avoid this?

ClickHouse server version 1.1.54236

**Comment by blinkov** [comment]
Have you tried inserting directly to ReplicatedMergeTree tables instead of Distributed one?

**Comment by alniks** [comment]
No, but somehow problem resolved.
