### ISSUE TITLE
Read timed out

### ISSUE THREAD

**Issue by alniks** [yandex/ClickHouse#974]
We also notice timeouts when making requests to clickhouse from servers in the same data center:

`ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 159, host: ip6-localhost, port: 8123; Read timed out, query: `

although the load is pretty low and there are no problems with accessing mysql on the same server

ClickHouse server version 1.1.54236

**Comment by blinkov** [comment]
Is this issue still relevant? If so, is there any way to reproduce it?

**Comment by alniks** [comment]
The problem was due to lags in ClickHouse server under high load and different timeout settings in ClickHouse server and JDBC driver. When we have many select queries, performance of ClickHouse server degrades significantly and simple queries will run for more than 30 secs causing timeouts in JDBC driver

**Comment by dongchaohui** [comment]
how to fix this issue ?

**Comment by sc750531323** [comment]
how to fix this issue ?

+1
