### ISSUE TITLE
runningDifference should consider arguments of the groupBy clause

### ISSUE THREAD

**Issue by m1schka** [yandex/ClickHouse#975]
hey,

I have a question regarding runningDifference (I'm currently evaluating clickhouse in the most recent docker container).
I'm currently grouping my event log by a column (`case_id`) and want to have the runningDifference (because there is no equivalent window or lag function) of the event times to calculate some average durations (later). I know the runningDifference is already not really standard and pretty custom but is there an option to reset the counter for each group?

here is an example:
```SQL
SELECT
    case_id,
    activity_datetime,
    runningDifference(activity_datetime) AS delta
FROM
(
    SELECT
        case_id,
        activity_datetime
    FROM business_activity
    ORDER BY
        case_id ASC,
        activity_datetime ASC
)
ORDER BY
    case_id ASC,
    activity_datetime ASC,
    delta DESC
```

gives me
```
┌─case_id─┬───activity_datetime─┬─────delta─┐
│ 1       │ 2012-01-13 01:00:00 │         0 │
│ 1       │ 2016-06-27 16:19:51 │ 140627991 │
│ 1       │ 2016-06-27 16:19:51 │         0 │
│ 1       │ 2016-06-27 16:19:51 │         0 │
│ 10      │ 2013-10-23 02:00:00 │ -84550791 │
│ 10      │ 2016-07-25 18:54:49 │  86979289 │
│ 10      │ 2016-07-25 18:54:49 │         0 │
│ 10      │ 2016-07-25 18:54:49 │         0 │
│ 10      │ 2016-07-25 18:56:44 │       115 │
│ 100     │ 2014-07-07 02:00:00 │ -64774604 │
│ 100     │ 2016-01-29 11:27:02 │  49368422 │
│ 1000    │ 2015-02-20 01:00:00 │ -29672822 │
```

as you can see, all new groups start with a negative runningDifference, which is not good when aggregating the data later:
```
SELECT
    case_id,
    groupArray(runningDifference(activity_datetime))
FROM
(
    SELECT
        case_id,
        activity_datetime,
        activity_id
    FROM business_activity
    ORDER BY
        case_id ASC,
        activity_datetime ASC
)
GROUP BY case_id
ORDER BY case_id ASC

┌─case_id─┬─groupArray(runningDifference(activity_datetime))─┐
│ 1       │ [0,140627991,0,0]                                │
│ 10      │ [-84550791,86979289,0,0,115]                     │
│ 100     │ [-64774604,49368422]                             │
│ 1000    │ [-29672822,39624062]                             │
└─────────┴──────────────────────────────────────────────────┘
```
Since the first data point per group is not interesting at all, can I maybe remove it from the resulting array?

Any other suggestions?

Thx

**Comment by valyala** [comment]
See how `$rateColumns` is implemented at [clickhouse-grafana](https://github.com/Vertamedia/clickhouse-grafana/blob/master/README.md)

**Comment by hagen1778** [comment]
Hi @m1schka 
You could try http://clickhouse.readthedocs.io/en/latest/reference_en.html#arrayFilter function to filter all elements with i=0.
But it would be better to filter these not interesting results at your application.
Btw, there is a telegram-channel where I believe you can have answers much faster - https://t.me/clickhouse_en

**Comment by m1schka** [comment]
thanks for the valuable insights!
I ended up with the following statement, which gave me the results I was looking for (see the `i != 1` as enumerate starts with 1):
```SQL
SELECT
    case_id,
    arrayFilter((x, i) -> (i != 1), groupArray(runningDifference(activity_datetime)) AS arr, arrayEnumerate(arr)) AS delta,
    count(*) AS cnt
FROM
(
    SELECT
        case_id,
        activity_datetime,
        activity_id
    FROM business_activity
    ORDER BY
        case_id ASC,
        activity_datetime ASC
)
GROUP BY case_id
ORDER BY case_id ASC
LIMIT 10

┌─case_id─┬─delta────────────────┬─cnt─┐
│ 1       │ [140627991,0,0]      │   4 │
│ 10      │ [86979289,0,0,115]   │   5 │
│ 100     │ [49368422]           │   2 │
│ 1000    │ [39624062]           │   2 │
│ 10000   │ [631899]             │   2 │
│ 100000  │ [46518,0,1040,0,0]   │   6 │
│ 100001  │ [46518,0,1040,0,0]   │   6 │
│ 100002  │ [46518,0,1040,0,0]   │   6 │
│ 100003  │ [46518,0,1040,0,0]   │   6 │
│ 100004  │ [46518,0,1040,1,0,0] │   7 │
└─────────┴──────────────────────┴─────┘
```

**Comment by ervivekmehta** [comment]
RunningDifference(x) for multiple x values
Ask Question
up vote
0
down vote
favorite

My Table tbl_data(event_time, monitor_id,type,event_date,status)

select status,sum(runningDifference(event_time)) as delta from (SELECT status,event_date,event_time FROM tbl_data WHERE event_date >= '2018-05-01' AND monitor_id =3 ORDER BY event_time ASC) group by status

Result will be

status           delta
1               4665465
2                965

This query result give me right answer for single monitor_id, Now I required it for multiple monitor_id,

How can I achieve it in single/same query??

I have tried by grouping but it also run calculation based on monitor grouping, so monitor grouping will not solve problem as I think.

please revert if you have any solution for me.

**Comment by filimonov** [comment]
You can easy archive needed result with  higher-order functions.

I've created sample here: https://gist.github.com/filimonov/2ff5f083c2f874eceebde8877721afc4

**Comment by yu45020** [comment]
Thanks all for previous discussions, and here is an alternative way to perform running difference per group 

Suppose we have a the following data 

```sql
create view nid_date as
select nid, date
from data
group by nid, date
order by nid, date
limit 20;
```

| nid  | date |
| ------------- | ------------- |
|2	 |16257 |
|3	 |16144 |
|3	 |16147 |
|3	 |16153 |
|3	 |16154 |
|3	 |16156 |
|3	 |16157 |
|3	 |16159 |
|20	 |16280 |
|20	 |16281 |
|20	 |16282 | 
|22	 |16277 |
|22	 |16278 |
|22	 |16279 |
|22	 |16280 |
|22	 |16281 |
|22	 |16282 |
|22	 |16283
|22	 |16284
|22	 |16285

Then the running difference per group will be 

```sql

select nid, group_date as date, delta_date as delta_date
from (
      select nid, groupArray(date) as group_date, arrayDifference(group_date) as delta_date
      from nid_date
      group by nid
      order by nid
       ) array join
     group_date,
     delta_date;

```



| nid | date  | delta_date |
|-----|-------|------------|
| 2   | 16257 | 0          |
| 3   | 16144 | 0          |
| 3   | 16147 | 3          |
| 3   | 16153 | 6          |
| 3   | 16154 | 1          |
| 3   | 16156 | 2          |
| 3   | 16157 | 1          |
| 3   | 16159 | 2          |
| 20  | 16280 | 0          |
| 20  | 16281 | 1          |
| 20  | 16282 | 1          |
| 22  | 16277 | 0          |
| 22  | 16278 | 1          |
| 22  | 16279 | 1          |
| 22  | 16280 | 1          |
| 22  | 16281 | 1          |
| 22  | 16282 | 1          |
| 22  | 16283 | 1          |
| 22  | 16284 | 1          |
| 22  | 16285 | 1          |

**Comment by alexz0000** [comment]
Hi, Could anyone help me here ?
Let's say I have a table and it has columns ts, env, instance, value.  the env only has two values 'env1' and 'env2', and instance has 10 values 'instance1', 'instance2' ...., How could I runningDifference for the group of env and instance?

┌─case_id─┬───activity_datetime─┬─────delta─┐
│ 1       │ 2012-01-13 01:00:00 │         0 │
│ 1       │ 2016-06-27 16:19:51 │ 140627991 │
│ 1       │ 2016-06-27 16:19:51 │         0 │
│ 1       │ 2016-06-27 16:19:51 │         0 │
│ 10      │ 2013-10-23 02:00:00 │ -84550791 │
│ 10      │ 2016-07-25 18:54:49 │  86979289 │
│ 10      │ 2016-07-25 18:54:49 │         0 │
│ 10      │ 2016-07-25 18:54:49 │         0 │
│ 10      │ 2016-07-25 18:56:44 │       115 │
│ 100     │ 2014-07-07 02:00:00 │ -64774604 │
│ 100     │ 2016-01-29 11:27:02 │  49368422 │
│ 1000    │ 2015-02-20 01:00:00 │ -29672822 │

**Comment by yu45020** [comment]
@alexz0000 
Do you mean running difference within group ? One way to do it is to turn each group into array, then use running difference, then use array join to flat them back into a column. It will be easier if you provide some sample data.

**Comment by filimonov** [comment]
Please check that https://stackoverflow.com/questions/51856397/clickhouse-running-diff-with-grouping

**Comment by alexz0000** [comment]
@yu45020 @filimonov Thank you. My table looks like below
|                      ts                |       env         |          group     |        instance   |  domain | url |  val  |
|------------------------|-------------|---------------|---------------|---------|----|-----|
|    1555926155                |     public      |       blue            |     192.168.2.3| githup.com|/clickhouse| 100|

**Comment by vsmelov** [comment]
Using of `runningDifference` is absolutely not safe because it breaks on `max_block_count` block borders.

Is there any way to solve it? Or I should use `arrayDifference(groupArray(...))` instead?

```
select 
	instrument,
	arr_timestamp as timestamp,
	arr_gap as gap,
from (
 	select 
 		instrument, 
 		groupArray(timestamp) as arr_timestamp, 
 		arrayDifference(timestamp) as arr_gap
 	from t
 	group by instrument
 	order by instrument
) array join
	arr_timestamp,
	arr_gap
```
