### ISSUE TITLE
make source code error 

### ISSUE THREAD

**Issue by SunGuo** [yandex/ClickHouse#98]
In file included from /home/work/xiaoxian/ClickHouse/ClickHouse-master/contrib/libtcmalloc/src/libc_override.h:79:0,
                 from /home/work/xiaoxian/ClickHouse/ClickHouse-master/contrib/libtcmalloc/src/tcmalloc.cc:156:
/home/work/xiaoxian/ClickHouse/ClickHouse-master/contrib/libtcmalloc/src/libc_override_glibc.h:132:71: error: conflicting declaration ‘void\* (\* volatile __malloc_hook)(size_t, const void_)’
 void_ (\* MALLOC_HOOK_MAYBE_VOLATILE __malloc_hook)(size_t, const void_)
                                                                       ^
In file included from /home/work/xiaoxian/ClickHouse/ClickHouse-master/contrib/libtcmalloc/include/gperftools/tcmalloc.h:49:0,
                 from /home/work/xiaoxian/ClickHouse/ClickHouse-master/contrib/libtcmalloc/src/tcmalloc.cc:91:
/usr/include/malloc.h:165:16: note: previous declaration as ‘void_ (\* __malloc_hook)(size_t, const void_)’
 extern void *(___malloc_hook) __MALLOC_PMT ((size_t __size,
                ^
In file included from /home/work/xiaoxian/ClickHouse/ClickHouse-master/contrib/libtcmalloc/src/libc_override.h:79:0,
                 from /home/work/xiaoxian/ClickHouse/ClickHouse-master/contrib/libtcmalloc/src/tcmalloc.cc:156:
/home/work/xiaoxian/ClickHouse/ClickHouse-master/contrib/libtcmalloc/src/libc_override_glibc.h:134:79: error: conflicting declaration ‘void\* (\* volatile __realloc_hook)(void_, size_t, const void_)’
 void\* (\* MALLOC_HOOK_MAYBE_VOLATILE __realloc_hook)(void_, size_t, const void_)
                                                                               ^
In file included from /home/work/xiaoxian/ClickHouse/ClickHouse-master/contrib/libtcmalloc/include/gperftools/tcmalloc.h:49:0,
                 from /home/work/xiaoxian/ClickHouse/ClickHouse-master/contrib/libtcmalloc/src/tcmalloc.cc:91:
  sr/include/malloc.h:167:16: note: previous declaration as ‘void\* (\* __realloc_hook)(void_, size_t, const void_)’
 extern void _(___realloc_hook) __MALLOC_PMT ((void ___ptr, size_t __size,
                ^
In file included from /home/work/xiaoxian/ClickHouse/ClickHouse-master/contrib/libtcmalloc/src/libc_override.h:79:0,
                 from /home/work/xiaoxian/ClickHouse/ClickHouse-master/contrib/libtcmalloc/src/tcmalloc.cc:156:
/home/work/xiaoxian/ClickHouse/ClickHouse-master/contrib/libtcmalloc/src/libc_override_glibc.h:136:67: error: conflicting declaration ‘void (_ volatile __free_hook)(void_, const void_)’
 void (\* MALLOC_HOOK_MAYBE_VOLATILE __free_hook)(void_, const void_)
                                                                   ^
In file included from /home/work/xiaoxian/ClickHouse/ClickHouse-master/contrib/libtcmalloc/include/gperftools/tcmalloc.h:49:0,
                 from /home/work/xiaoxian/ClickHouse/ClickHouse-master/contrib/libtcmalloc/src/tcmalloc.cc:91:
/usr/include/malloc.h:163:15: note: previous declaration as ‘void (\* __free_hook)(void_, const void_)’
 extern void (___free_hook) __MALLOC_PMT ((void *__ptr,
               ^
In file included from /home/work/xiaoxian/ClickHouse/ClickHouse-master/contrib/libtcmalloc/src/libc_override.h:79:0,
                 from /home/work/xiaoxian/ClickHouse/ClickHouse-master/contrib/libtcmalloc/src/tcmalloc.cc:156:
/home/work/xiaoxian/ClickHouse/ClickHouse-master/contrib/libtcmalloc/src/libc_override_glibc.h:138:80: error: conflicting declaration ‘void_ (\* volatile __memalign_hook)(size_t, size_t, const void_)’
 void_ (\* MALLOC_HOOK_MAYBE_VOLATILE __memalign_hook)(size_t,size_t, const void_)
                                                                                ^
In file included from /home/work/xiaoxian/ClickHouse/ClickHouse-master/contrib/libtcmalloc/include/gperftools/tcmalloc.h:49:0,
                 from /home/work/xiaoxian/ClickHouse/ClickHouse-master/contrib/libtcmalloc/src/tcmalloc.cc:91:
/usr/include/malloc.h:169:16: note: previous declaration as ‘void_ (\* __memalign_hook)(size_t, size_t, const void_)’
 extern void *(___memalign_hook) __MALLOC_PMT ((size_t __alignment,

**Comment by alexey-milovidov** [comment]
It because source code contains tcmalloc library, that was pre-configured (by running configure script) for specific system, where signatures of malloc hooks may differ than corresponding signatures on your system.

There is few different ways to avoid this problem:

1. Edit `contrib/libtcmalloc/src/config.h` file, line 222, `#define MALLOC_HOOK_MAYBE_VOLATILE` according to your system.

2. Download libtcmalloc, run configure script, and copy resulting `config.h` file in place of `contrib/libtcmalloc/src/config.h`.

3. (More complicated) Edit CMakeLists.txt to correctly define MALLOC_HOOK_MAYBE_VOLATILE macro instead of `config.h` file.

4. Build on VM with Ubuntu and install on target system as described here:
https://github.com/yandex/ClickHouse/issues/61#issuecomment-236002259

**Comment by alexey-milovidov** [comment]
Updated tcmalloc library to latest version, which was removed usage of obsolete malloc hooks.
