### ISSUE TITLE
max_parallel_replicas does not work when Distributed and Replicated tables are on the same server

### ISSUE THREAD

**Issue by zrkn** [yandex/ClickHouse#982]
Is case when Distributed table has only one shard with some number of replicas and one of replicas is located on the same server as Distributed table, max_parallel_replicas parameter seems not working. Request gets processed only on local table.

**Comment by ztlpn** [comment]
Good catch! Yes, when one of the shards has a local replica, ClickHouse uses it regardless of any settings.

**Comment by alexey-milovidov** [comment]
We have introduced a setting `prefer_localhost_replica` which is 1 by default.
You can turn it off to use parallel replicas even if one of shards contain localhost replicas.
