### ISSUE TITLE
time function

### ISSUE THREAD

**Issue by jackpgao** [yandex/ClickHouse#990]
Does ClickHouse provides functions like MySQL's 'INTERVAL'?

Sometimes, I'd like to use a SQL to limit the time range, such as 3hours ago to now()

**Comment by ztlpn** [comment]
There is no INTERVAL type at the moment. But you can use arithmetic functions with Date and DateTime types. For example, here is how you get DateTime 3 hours ago from now and Date one week ago from today:

```
:) select now(), now() - 3 * 3600, today(), today() - 7

SELECT
    now(),
    now() - (3 * 3600),
    today(),
    today() - 7

┌───────────────now()─┬─minus(now(), multiply(3, 3600))─┬────today()─┬─minus(today(), 7)─┐
│ 2017-07-17 21:00:09 │             2017-07-17 18:00:09 │ 2017-07-17 │        2017-07-10 │
└─────────────────────┴─────────────────────────────────┴────────────┴───────────────────┘

1 rows in set. Elapsed: 0.001 sec.
```

**Comment by jackpgao** [comment]
Thanks @ztlpn . 

I search the whole document, but didn't find some demo like this. 

Hope that you can provide more demo in the document.
